Repository pancakeswap/pancake-frontend, pull requests merged in 2021-08, with the labels that each got.

#1790 feat: Farm Auctions
  package.json
  public/images/burnt-cake.png
  src/config/abi/farmAuction.json
  src/config/constants/contracts.ts
  src/config/constants/farmAuctions.ts
  src/config/constants/types.ts
  src/config/index.ts
  src/config/localization/translations.json
  src/hooks/useContract.ts
  src/utils/addressHelpers.ts
  src/utils/contractHelpers.ts
  src/utils/types.ts
  src/views/FarmAuction/components/AuctionDetail.tsx
  src/views/FarmAuction/components/AuctionDetailsCard/AuctionFooter.tsx
  src/views/FarmAuction/components/AuctionDetailsCard/AuctionSchedule.tsx
  src/views/FarmAuction/components/AuctionDetailsCard/CannotBidMessage.tsx
  src/views/FarmAuction/components/AuctionDetailsCard/index.tsx
  src/views/FarmAuction/components/AuctionHistory.tsx
  src/views/FarmAuction/components/AuctionLeaderboard/AuctionLeaderboardTable.tsx
  src/views/FarmAuction/components/AuctionLeaderboard/AuctionProgress.tsx
  src/views/FarmAuction/components/AuctionLeaderboard/AuctionRibbon.tsx
  src/views/FarmAuction/components/AuctionLeaderboard/index.tsx
  src/views/FarmAuction/components/AuctionTimer.tsx
  src/views/FarmAuction/components/CongratulationsCard.tsx
  src/views/FarmAuction/components/FAQs.tsx
  src/views/FarmAuction/components/NotWhitelistedNotice.tsx
  src/views/FarmAuction/components/PlaceBidModal.tsx
  src/views/FarmAuction/components/ReclaimBidCard.tsx
  src/views/FarmAuction/components/TabToggle.tsx
  src/views/FarmAuction/components/WhitelistedBiddersButton.tsx
  src/views/FarmAuction/components/WhitelistedBiddersModal.tsx
  src/views/FarmAuction/helpers.tsx
  src/views/FarmAuction/hooks/useAuctionHistory.tsx
  src/views/FarmAuction/hooks/useCongratulateAuctionWinner.tsx
  src/views/FarmAuction/hooks/useCurrentFarmAuction.ts
  src/views/FarmAuction/hooks/useReclaimAuctionBid.ts
  src/views/FarmAuction/hooks/useWhitelistedAddresses.ts
  src/views/FarmAuction/index.tsx
  yarn.lock
Labels: epic

#1813 feat(farm/pool): Revv
  public/images/tokens/0x833F307aC507D47309fD8CDD1F835BeF8D702a93.png
  public/images/tokens/0x833F307aC507D47309fD8CDD1F835BeF8D702a93.svg
  src/config/constants/farms.ts
  src/config/constants/pools.ts
  src/config/constants/tokens.ts
Labels: delayed release

#1854 feat(farm/pool): TUSD
  public/images/tokens/0xa2B726B1145A4773F68593CF171187d8EBe4d495.png
  public/images/tokens/0xa2B726B1145A4773F68593CF171187d8EBe4d495.svg
  src/config/constants/farms.ts
  src/config/constants/pools.ts
Labels: delayed release

#1924 feat(homepage): Token per Block
  src/config/index.ts
  src/views/Home/components/CakeDataRow.tsx
Labels: Delayed Release

#1847 Feature/predictions v3
  .env.development
  .env.production
  public/images/chartwarning.svg
  src/__tests__/state/predictions/helpers.test.ts
  src/components/RoundProgress.tsx
  src/config/abi/chainlinkOracle.json
  src/config/abi/predictions.json
  src/config/constants/contracts.ts
  src/config/localization/translations.json
  src/state/hooks.ts
  src/state/predictions/config.ts
  src/state/predictions/helpers.ts
  src/state/predictions/hooks.ts
  src/state/predictions/index.ts
  src/state/predictions/queries.ts
  src/state/types.ts
  src/utils/types.ts
  src/views/Predictions/components/ChartDisclaimer.tsx
  src/views/Predictions/components/CollectRoundWinningsModal.tsx
  src/views/Predictions/components/History/BetDetails.tsx
  src/views/Predictions/components/History/BetResult.tsx
  src/views/Predictions/components/History/HistoricalBet.tsx
  src/views/Predictions/components/History/PnlTab/PnlTab.tsx
  src/views/Predictions/components/Label.tsx
  src/views/Predictions/components/ReclaimPositionButton.tsx
  src/views/Predictions/components/RoundCard/CalculatingCard.tsx
  src/views/Predictions/components/RoundCard/CanceledRoundCard.tsx
  src/views/Predictions/components/RoundCard/CardHeader.tsx
  src/views/Predictions/components/RoundCard/EnteredTag.tsx
  src/views/Predictions/components/RoundCard/ExpiredRoundCard.tsx
  src/views/Predictions/components/RoundCard/LiveRoundCard.tsx
  src/views/Predictions/components/RoundCard/OpenRoundCard.tsx
  src/views/Predictions/components/RoundCard/SetPositionCard.tsx
  src/views/Predictions/components/RoundCard/SoonRoundCard.tsx
  src/views/Predictions/helpers.ts
  src/views/Predictions/hooks/useCountdown.ts
  src/views/Predictions/hooks/usePollOraclePrice.ts
  src/views/Predictions/hooks/usePollPredictions.ts
  src/views/Predictions/hooks/useRoundCountdown.ts
  src/views/Predictions/index.tsx
Labels: epic

#1973 [20:00 JST] Pha farm pool
  public/images/tokens/0x0112e557d400474717056C4e6D40eDD846F38351.png
  public/images/tokens/0x0112e557d400474717056C4e6D40eDD846F38351.svg
  src/config/constants/farms.ts
  src/config/constants/pools.ts
  src/config/constants/tokens.ts
Labels: Delayed Release

#2010 chore(lottery): Restore original lottery history user notice
  src/config/localization/translations.json
  src/views/Lottery/components/YourHistoryCard/index.tsx
Labels: Delayed Release

#1837 Feature/leaderboard
  package.json
  src/App.tsx
  src/__tests__/state/predictions/helpers.test.ts
  src/components/ConnectWalletButton.tsx
  src/components/Select/Select.tsx
  src/config/localization/translations.json
  src/state/index.ts
  src/state/predictions/config.ts
  src/state/predictions/helpers.ts
  src/state/predictions/hooks.ts
  src/state/predictions/index.ts
  src/state/predictions/queries.ts
  src/state/profile/getProfile.ts
  src/state/profile/helpers.ts
  src/state/profile/hooks.ts
  src/state/profile/index.tsx
  src/state/types.ts
  src/utils/contractHelpers.ts
  src/utils/types.ts
  src/views/Farms/Farms.tsx
  src/views/Pools/index.tsx
  src/views/Predictions/Leaderboard/components/AddressSearch.tsx
  src/views/Predictions/Leaderboard/components/Crumbs.tsx
  src/views/Predictions/Leaderboard/components/Filters/TimePeriodFilter.tsx
  src/views/Predictions/Leaderboard/components/Filters/index.tsx
  src/views/Predictions/Leaderboard/components/Hero.tsx
  src/views/Predictions/Leaderboard/components/MobileBetsTable.tsx
  src/views/Predictions/Leaderboard/components/PositionLabel.tsx
  src/views/Predictions/Leaderboard/components/PreviousBetsTable.tsx
  src/views/Predictions/Leaderboard/components/Results/ConnectedWalletResult.tsx
  src/views/Predictions/Leaderboard/components/Results/DesktopBetsTable.tsx
  src/views/Predictions/Leaderboard/components/Results/DesktopResults.tsx
  src/views/Predictions/Leaderboard/components/Results/DesktopRow.tsx
  src/views/Predictions/Leaderboard/components/Results/MobileResults.tsx
  src/views/Predictions/Leaderboard/components/Results/MobileRow.tsx
  src/views/Predictions/Leaderboard/components/Results/RankingCard.tsx
  src/views/Predictions/Leaderboard/components/Results/ResultAvatar.tsx
  src/views/Predictions/Leaderboard/components/Results/index.tsx
  src/views/Predictions/Leaderboard/components/Results/styles.tsx
  src/views/Predictions/Leaderboard/components/WalletStatsModal.tsx
  src/views/Predictions/Leaderboard/index.tsx
  src/views/Predictions/components/HistoryButton.tsx
  src/views/Predictions/components/Menu.tsx
  src/views/Predictions/components/TradingView.tsx
  src/views/TradingCompetition/components/BattleCta/index.tsx
  src/views/Voting/CreateProposal/index.tsx
  src/views/Voting/components/BreadcrumbLink.tsx
  src/views/Voting/components/Proposals/Proposals.tsx
  yarn.lock
Labels: Epic

#2042 feat(pool/farm): QBT
  public/images/tokens/0x17B7163cf1Dbd286E262ddc68b553D899B93f526.png
  public/images/tokens/0x17B7163cf1Dbd286E262ddc68b553D899B93f526.svg
  src/config/constants/farms.ts
  src/config/constants/pools.ts
  src/config/constants/tokens.ts
Labels: Delayed Release
