Repository pancakeswap/pancake-frontend, pull requests merged in 2022-03, with the labels that each got.

#3364 chore: Add automerge in updateLPsAPR
  .github/workflows/updateLPsAPR.yml
Labels: size/XS, automerge

#3365 chore(farms): Auction 16 whitelist
  src/config/constants/farmAuctions.ts
Labels: size/XS

#3366 fix: Error message from estimatedCalls missing
  src/hooks/useSwapCallback.ts
Labels: size/XS, automerge

#3355 chore: Replace pretty-quick to lint-staged
  .lintstagedrc
  package.json
  yarn.lock
Labels: size/L

#3370 refactor: Use swr in collection lowest price stat box
  src/views/Nft/market/Collection/LowestPriceStatBoxItem.tsx
Labels: size/M

#3334 feat: Add copy token address button to currency input panel
  src/components/CopyButton/index.tsx
  src/components/CurrencyInputPanel/index.tsx
  src/components/Menu/UserMenu/CopyAddress.tsx
Labels: size/L, automerge

#3240 fix: Max stake per user shown when pool is finished
  src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
Labels: size/S

#3368 fix: Check IntersectionObserver
  src/hooks/useIntersectionObserver.ts
Labels: size/M, automerge

#3371 fix: Translation missing
  src/config/__tests__/translations.test.ts
  src/config/localization/translations.json
Labels: size/XS, automerge

#3361 feat: Add table view to collections page
  src/components/ToggleView/ToggleView.tsx
  src/state/nftMarket/helpers.ts
  src/state/nftMarket/hooks.ts
  src/views/Farms/Farms.tsx
  src/views/Farms/components/ToggleView/ToggleView.tsx
  src/views/Nft/market/Collection/LowestPriceStatBoxItem.tsx
  src/views/Nft/market/Collections/index.tsx
  src/views/Pools/components/PoolTabButtons.tsx
Labels: size/L, automerge

#3273 refactor: Use swr for refresh hooks that doesn't dispatch to redux
  src/views/FarmAuction/components/AuctionHistory.tsx
  src/views/FarmAuction/components/AuctionLeaderboard/AuctionProgress.tsx
  src/views/FarmAuction/hooks/useAuctionHistory.tsx
  src/views/FarmAuction/hooks/useCurrentFarmAuction.ts
  src/views/FarmAuction/hooks/useFarmAuction.ts
  src/views/FarmAuction/hooks/useWhitelistedAddresses.ts
  src/views/Home/components/CakeDataRow.tsx
  src/views/Home/components/WinSection/LotteryCardContent.tsx
  src/views/Home/components/WinSection/PredictionCardContent.tsx
  src/views/Home/hooks/useFarmsWithBalance.tsx
Labels: size/L, automerge

#3376 fix: Missing translations
  src/config/localization/translations.json
Labels: size/XS, automerge

#3260 feat: (pool): Add auto earnings interest breakdown to pool cards
  src/views/Ifos/components/IfoPoolVaultCard.tsx
  src/views/Pools/components/AutoEarningsBreakdown.tsx
  src/views/Pools/components/CakeVaultCard/RecentCakeProfitBalance.tsx
  src/views/Pools/components/CakeVaultCard/RecentCakeProfitRow.tsx
  src/views/Pools/components/CakeVaultCard/index.tsx
  src/views/Pools/components/PoolsTable/Cells/AutoEarningsCell.tsx
Labels: size/L

#3381 chore: Bump typescript-eslint
  .eslintrc
  packages/eslint-config/lib/index.js
  packages/eslint-config/package.json
  src/__tests__/state/predictions/helpers.test.ts
  src/utils/requestWithTimeout.ts
  src/views/Predictions/Leaderboard/components/Crumbs.tsx
  yarn.lock
Labels: size/L

#3384 chore: Add Medium link and icon to footer
  packages/uikit/src/components/Footer/config.tsx
  packages/uikit/src/components/Svg/Icons/Medium.tsx
  packages/uikit/src/components/Svg/index.tsx
Labels: size/M, automerge

#3349 feat: Add Coinbase Wallet and Blocto Wallet
  package.json
  packages/uikit/src/widgets/WalletModal/config.tsx
  packages/uikit/src/widgets/WalletModal/types.ts
  src/components/Menu/UserMenu/WalletWrongNetwork.tsx
  src/hooks/useAuth.ts
  src/react-app-env.d.ts
  src/utils/wallet.ts
  src/utils/web3React.ts
  yarn.lock
Labels: size/L, automerge

#3312 feat: Use next-themes
  package.json
  src/Providers.tsx
  src/components/Menu/GlobalSettings/SettingsModal.tsx
  src/components/Menu/index.tsx
  src/hooks/useTheme.ts
  src/state/user/actions.ts
  src/state/user/hooks/index.tsx
  src/state/user/reducer.ts
  yarn.lock
Labels: size/M

#3386 fix: Avoid undefined call matchMedia
  packages/uikit/src/hooks/useMatchBreakpoints.ts
Labels: size/M, automerge

#3388 chore: Update wallet config
  packages/uikit/src/widgets/WalletModal/config.tsx
Labels: size/S

#3387 chore: Turn on ComingSoon section
  src/config/constants/ifo.ts
Labels: size/XS

#3389 fix: Bunny slider image in firefox
  packages/uikit/src/components/Slider/styles.ts
Labels: size/XS

#3115 fix: (nft): Missing items in Collection listing
  next.config.js
  src/views/Nft/market/Collection/Items/CollectionNfts.tsx
  src/views/Nft/market/Collection/Items/CollectionWrapper.tsx
  src/views/Nft/market/Collection/Items/FilteredCollectionNfts.tsx
  src/views/Nft/market/hooks/useCollectionNfts.tsx
Labels: size/XL

#3393 chore: Bump sdk 2.4.4
  package.json
  yarn.lock
Labels: size/S, automerge

#3392 refactor: Remove global constant objects
  src/hooks/useRefreshEffect.ts
  src/state/nftMarket/hooks.ts
  src/utils/constantObjects.ts
  src/views/Home/hooks/useFarmsWithBalance.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/ForSaleTableCard/utils.ts
  src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/index.tsx
  src/views/Nft/market/hooks/useCollectionNfts.tsx
Labels: size/M

#3270 feat: Only attempt to setup network once
  src/contexts/ToastsContext/Provider.tsx
  src/hooks/useAuth.ts
  src/hooks/useEagerConnect.ts
  src/utils/wallet.ts
  src/utils/web3React.ts
Labels: size/L, automerge

#3331 test: Add info test back
  cypress.json
  cypress/integration/info/info.test.ts
  src/state/info/queries/tokens/tokenData.ts
Labels: size/S

#3321 test: Add basic swap test
  jest.config.js
  jest.setup.js
  package.json
  src/__tests__/state/swap/fetch/__fixtures__/day-pair-data.json
  src/__tests__/state/swap/fetch/__fixtures__/hour-pair-data.json
  src/__tests__/state/swap/fetch/util.test.ts
  src/hooks/Trades.test.ts
  src/hooks/Trades.ts
  src/hooks/__snapshots__/Trades.test.ts.snap
  src/hooks/useRefreshEffect.test.ts
  src/state/index.ts
  src/state/multicall/retry.test.ts
  src/state/swap/hooks.test.ts
  src/testUtils.tsx
  src/utils/maxAmountSpend.test.ts
  src/utils/maxAmountSpend.ts
  src/utils/trades.test.ts
  src/utils/trades.ts
  src/views/Swap/index.test.tsx
  yarn.lock
Labels: size/XXL, automerge

#3380 feat(uikit): Tree shake
  packages/uikit/babel.config.js
  packages/uikit/jest.config.js
  packages/uikit/package.json
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/components/BottomNav/BottomNav.tsx
  packages/uikit/src/components/BottomNav/mock.tsx
  packages/uikit/src/components/BottomNavItem/BottomNavItem.tsx
  packages/uikit/src/components/BottomNavItem/index.stories.tsx
  packages/uikit/src/components/BottomNavItem/types.ts
  packages/uikit/src/components/Button/index.stories.tsx
  packages/uikit/src/components/DropdownMenu/DropdownMenu.tsx
  packages/uikit/src/components/DropdownMenu/mock.tsx
  packages/uikit/src/components/Footer/Components/SocialLinks.tsx
  packages/uikit/src/components/Footer/config.tsx
  packages/uikit/src/components/Footer/index.stories.tsx
  packages/uikit/src/components/Image/index.stories.tsx
  packages/uikit/src/components/Link/index.stories.tsx
  packages/uikit/src/components/MenuItems/MenuItems.tsx
  packages/uikit/src/components/MenuItems/types.ts
  packages/uikit/src/components/Progress/index.stories.tsx
  packages/uikit/src/components/SubMenuItems/SubMenuItems.tsx
  packages/uikit/src/components/SubMenuItems/types.ts
  packages/uikit/src/components/Svg/AnimatedIconComponent.tsx
  packages/uikit/src/components/Svg/IconComponent.tsx
  packages/uikit/src/components/Svg/Icons/Crown.tsx
  packages/uikit/src/components/Svg/Icons/PresentCheck.tsx
  packages/uikit/src/components/Svg/index.stories.tsx
  packages/uikit/src/components/Svg/index.tsx
  packages/uikit/src/components/Svg/types.ts
  packages/uikit/src/components/Tag/index.stories.tsx
  packages/uikit/src/components/ThemeSwitcher/ThemeSwitcher.tsx
  packages/uikit/src/components/ThemeSwitcher/index.stories.tsx
  packages/uikit/src/components/Timeline/InfoTooltip.tsx
  packages/uikit/src/components/Timeline/Timeline.tsx
  packages/uikit/src/components/Toggle/index.stories.tsx
  packages/uikit/src/widgets/Menu/config.ts
  packages/uikit/src/widgets/Menu/index.stories.tsx
  packages/uikit/tsconfig.json
  src/components/Menu/config/config.ts
  src/pages/_app.tsx
  yarn.lock
Labels: size/XXL

#3294 chore: More testnet support
  .env.testnet
  src/config/constants/farmAuctions.ts
  src/config/constants/index.ts
  src/hooks/useApproveCallback.ts
  src/state/farms/getFarmsPrices.ts
  src/state/farms/hooks.ts
  src/state/farms/index.ts
  src/utils/index.ts
  src/utils/wallet.ts
  src/views/AddLiquidity/index.tsx
  src/views/RemoveLiquidity/index.tsx
Labels: size/XXL

#3395 perf: Prevent rerun toCallState when currentBlock changes
  src/state/block/hooks.ts
  src/state/multicall/hooks.ts
  src/views/Nft/market/hooks/useCollectionNfts.tsx
  src/views/Swap/hooks/useRefreshBlockNumber.ts
Labels: size/M

#3398 fix: Add DarkTheme for TimePicker
  src/views/Voting/components/DatePicker/DatePickerPortal.tsx
Labels: size/S, automerge

#3397 chore: Update farm auction 16
  src/config/constants/farms.ts
Labels: size/M, automerge

#3399 fix: (nft): Wrong result amount in collection listing
  src/views/Nft/market/hooks/useCollectionNfts.tsx
Labels: size/XS, automerge

#3178 fix: (prediction): Bump up swiper and reduce memory and use same amount of swiper cards
  package.json
  src/state/predictions/index.ts
  src/views/Nft/market/Collection/IndividualNFTPage/shared/MoreFromThisCollection.tsx
  src/views/Predictions/Positions.tsx
  src/views/Predictions/components/RoundCard/LiveRoundCard.tsx
  src/views/Predictions/components/RoundCard/LiveRoundPrice.tsx
  src/views/Predictions/components/RoundCard/index.tsx
  src/views/Predictions/helpers.ts
  src/views/Predictions/hooks/useOnNextRound.ts
  src/views/Predictions/hooks/usePollPredictions.ts
  yarn.lock
Labels: size/L

#3404 feat(swap): Pass focus when clicking currency input panel
  src/components/CurrencyInputPanel/index.tsx
Labels: size/S, automerge

#3406 feat(voting): Proposals filter in session
  next.config.js
  src/hooks/useSessionStorage.ts
  src/views/Voting/components/Proposals/Proposals.tsx
Labels: size/M, automerge

#3407 New Crowdin updates
  public/locales/ar-SA.json
  public/locales/bn-BD.json
  public/locales/de-DE.json
  public/locales/el-GR.json
  public/locales/en-US.json
  public/locales/es-ES.json
  public/locales/fi-FI.json
  public/locales/fil-PH.json
  public/locales/fr-FR.json
  public/locales/hi-IN.json
  public/locales/hu-HU.json
  public/locales/id-ID.json
  public/locales/it-IT.json
  public/locales/ja-JP.json
  public/locales/ko-KR.json
  public/locales/nl-NL.json
  public/locales/pl-PL.json
  public/locales/pt-BR.json
  public/locales/pt-PT.json
  public/locales/ro-RO.json
  public/locales/ru-RU.json
  public/locales/sv-SE.json
  public/locales/ta-IN.json
  public/locales/tr-TR.json
  public/locales/uk-UA.json
  public/locales/vi-VN.json
  public/locales/zh-CN.json
  public/locales/zh-TW.json
Labels: size/XXL

#3177 perf: (pools): Fix array dependencies that makes pools page rerender redundantly
  src/state/pools/helpers.ts
  src/state/pools/hooks.ts
  src/state/pools/index.ts
  src/state/pools/selectors.ts
  src/state/types.ts
  src/views/Home/hooks/useGetTopPoolsByApr.tsx
  src/views/Pools/components/PoolsTable/Cells/IFOCreditCell.tsx
  src/views/Pools/components/PoolsTable/Cells/StakedCell.tsx
  src/views/Pools/index.tsx
Labels: size/XL

#3224 refactor: Move reader cake contract calls to pcs nodes for better ux
  src/hooks/useApproveConfirmTransaction.tsx
  src/hooks/useContract.ts
  src/hooks/useTokenBalance.ts
  src/utils/requiresApproval.ts
  src/views/FarmAuction/components/PlaceBidModal.tsx
  src/views/FarmAuction/components/ReclaimBidCard.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx
  src/views/Ifos/components/IfoFoldableCard/index.tsx
  src/views/Lottery/components/BuyTicketsModal/BuyTicketsModal.tsx
  src/views/Nft/market/Profile/components/EditProfileModal/ApproveCakeView.tsx
  src/views/Nft/market/Profile/components/EditProfileModal/StartView.tsx
  src/views/Nft/market/components/BuySellModals/BuyModal/index.tsx
  src/views/Nft/market/components/BuySellModals/SellModal/index.tsx
  src/views/Nft/market/hooks/useCompleteNft.tsx
  src/views/Nft/market/hooks/useNftOwner.tsx
  src/views/PancakeSquad/components/Buttons/BuyTickets.tsx
  src/views/Pools/hooks/useApprove.tsx
  src/views/ProfileCreation/ConfirmProfileCreationModal.tsx
  src/views/ProfileCreation/Mint.tsx
Labels: size/L

#3410 fix: (nft): Approval request check in sellmodal
  src/views/Nft/market/components/BuySellModals/SellModal/index.tsx
Labels: size/XS

#3409 fix(wallet): Eager connect SafePal
  package.json
  src/hooks/useEagerConnect.ts
  yarn.lock
Labels: size/S, automerge

#3412 fix(proposal): Fix time select on light theme
  src/views/Voting/components/DatePicker/DatePickerPortal.tsx
Labels: size/XS, automerge

#3401 fix: Remove user data from farms and pools after logout
  src/state/farms/index.ts
  src/state/global/actions.ts
  src/state/pools/index.ts
  src/utils/clearUserStates.ts
Labels: size/M

#3414 chore(ifo): Add DUET
  public/images/achievements/ifo-duet.svg
  public/images/decorations/3d-ifo-duet.png
  public/images/ifos/duet-bg.png
  public/images/tokens/0x95EE03e1e2C5c4877f9A298F1C0D6c98698FAB7B.png
  public/images/tokens/0x95EE03e1e2C5c4877f9A298F1C0D6c98698FAB7B.svg
  src/components/Menu/config/config.ts
  src/config/constants/campaigns.ts
  src/config/constants/ifo.ts
  src/config/constants/tokens.ts
Labels: size/L

#3417 chore(ifo): Update ifo content
  src/config/localization/translations.json
  src/views/Ifos/components/IfoQuestions/config.tsx
Labels: size/XS

#3418 fix(wallet): Local injected eager connect
  src/hooks/useEagerConnect.ts
Labels: size/XS

#3405 feat: UserMenu improve
  packages/eslint-config/lib/index.js
  packages/uikit/src/components/CakePrice/CakePrice.tsx
  packages/uikit/src/widgets/Menu/Menu.tsx
  src/components/ConnectWalletButton.tsx
  src/components/Menu/UserMenu/index.tsx
  src/config/localization/translations.json
  src/hooks/useSWRContract.ts
  src/state/profile/helpers.ts
  src/state/profile/hooks.ts
  src/views/PancakeSquad/components/Header/index.tsx
Labels: size/L

#3419 perf(voting): Remove snapshot.js
  package.json
  src/state/types.ts
  src/state/voting/helpers.ts
  src/views/Voting/Proposal/Overview.tsx
  src/views/Voting/Proposal/Results.tsx
  src/views/Voting/Proposal/Votes.tsx
  src/views/Voting/helpers.ts
  yarn.lock
Labels: size/L

#3424 fix: Update cursor color in editor
  src/components/EasyMde/index.tsx
Labels: size/XS, automerge

#3426 chore: Add transition for UIKit Modal
  packages/uikit/package.json
  packages/uikit/src/widgets/Modal/ModalContext.tsx
  yarn.lock
Labels: size/L, automerge

#3320 chore: Use Public rpc on dev
  .env.development
Labels: size/XS

#3429 fix: Profile team nullable
  src/components/ProfileAvatarWithTeam.tsx
  src/state/types.ts
  src/views/TradingCompetition/components/YourScore/CardUserInfo.tsx
Labels: size/XS

#3430 feat: exchange BNB logo
  packages/uikit/src/components/Svg/Icons/Binance.tsx
  public/images/tokens/0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c.png
  public/images/tokens/0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c.svg
Labels: size/S, automerge

#3431 chore: Update CODEOWNERS
  .github/CODEOWNERS
Labels: size/XS

#3432 feat: Add gelato logo
  public/images/powered_by_gelato_black.svg
  public/images/powered_by_gelato_white.svg
  src/components/Menu/Footer.tsx
  src/config/constants/index.ts
  src/views/LimitOrders/index.tsx
  src/views/Page.tsx
  src/views/Swap/index.tsx
Labels: size/M, automerge

#3363 chore: Block sanctioned regions
  src/components/BlockCountry/BlockCountryModal.tsx
  src/components/BlockCountry/index.tsx
  src/config/constants/cookie-names.ts
  src/config/localization/translations.json
  src/pages/_app.tsx
  src/pages/_middleware.ts
Labels: size/L

#3439 chore: Exchange Canceled to Cancelled
  public/locales/ar-SA.json
  public/locales/bn-BD.json
  public/locales/de-DE.json
  public/locales/el-GR.json
  public/locales/en-US.json
  public/locales/es-ES.json
  public/locales/fi-FI.json
  public/locales/fil-PH.json
  public/locales/fr-FR.json
  public/locales/hi-IN.json
  public/locales/hu-HU.json
  public/locales/id-ID.json
  public/locales/it-IT.json
  public/locales/ja-JP.json
  public/locales/ko-KR.json
  public/locales/nl-NL.json
  public/locales/pl-PL.json
  public/locales/pt-BR.json
  public/locales/pt-PT.json
  public/locales/ro-RO.json
  public/locales/ru-RU.json
  public/locales/sv-SE.json
  public/locales/ta-IN.json
  public/locales/tr-TR.json
  public/locales/uk-UA.json
  public/locales/vi-VN.json
  public/locales/zh-CN.json
  public/locales/zh-TW.json
  src/config/localization/translations.json
  src/views/Predictions/components/History/BetDetails.tsx
  src/views/Predictions/components/History/BetResult.tsx
  src/views/Predictions/components/History/HistoricalBet.tsx
  src/views/Predictions/components/Notification/PauseNotification.tsx
  src/views/Predictions/components/RoundCard/CanceledRoundCard.tsx
  src/views/Predictions/components/RoundResult/RoundResult.tsx
  src/views/Predictions/components/RoundResult/RoundResultHistory.tsx
Labels: size/L

#3433 fix: Collection listing order by token id load more
  src/views/Nft/market/hooks/useCollectionNfts.tsx
Labels: size/XS

#3440 feat: Add ifo pool selectors
  src/state/pools/hooks.ts
  src/state/pools/selectors.ts
Labels: size/M

#3438 feat: Add GMT pool and farm
  public/images/tokens/0x3019BF2a2eF8040C242C9a4c5c4BD4C81678b2A1.png
  public/images/tokens/0x3019BF2a2eF8040C242C9a4c5c4BD4C81678b2A1.svg
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
  src/config/constants/tokens.ts
Labels: size/M

#3425 fix: Pools selectors memoization
  src/state/pools/selectors.ts
Labels: size/M

#3446 fix: Ifo banner keeps being alive after ifo ends
  src/hooks/useActiveIfoWithBlocks.ts
Labels: size/XS, automerge

#3441 revert: Revert "chore: Use Public rpc on dev"
  .env.development
Labels: size/XS

#3447 fix: Select token mobile css
  src/components/SearchModal/ImportRow.tsx
Labels: size/S, automerge

#3443 perf: Token list remove useless code
  src/state/lists/updater.ts
Labels: size/XS

#3422 perf: Use selectors for farms
  src/state/farms/hooks.ts
  src/state/farms/selectors.ts
Labels: size/L

#3444 fix: Multiple banner still shows fade effect when only one item
  src/views/Home/components/Banners/MultipleBanner.tsx
Labels: size/M, automerge

#3450 perf: Modal animation performance optimization
  packages/uikit/src/widgets/Modal/ModalContext.tsx
Labels: size/M, automerge

#3449 fix: Liquidity page css
  src/components/SearchModal/CommonBases.tsx
  src/views/AddLiquidity/ConfirmAddModalBottom.tsx
  src/views/Swap/components/ConfirmRemoveLiquidityModal.tsx
Labels: size/S, automerge

#3423 perf: Use selectors on prediction hooks
  src/state/predictions/hooks.ts
  src/state/predictions/selectors.ts
Labels: size/L

#3420 chore: Add and initialize style-lint
  .stylelintrc.js
  package.json
  yarn.lock
Labels: size/L

#3434 chore: Bottom drawer overlay transition
  packages/uikit/src/components/BottomDrawer/BottomDrawer.tsx
  packages/uikit/src/components/BottomDrawer/styles.ts
  packages/uikit/src/components/Overlay/Overlay.tsx
Labels: size/M, automerge

#3332 chore: Handle Error on getting vote power
  src/config/localization/translations.json
  src/views/Voting/components/CastVoteModal/MainView.tsx
  src/views/Voting/components/CastVoteModal/index.tsx
  src/views/Voting/hooks/useGetVotingPower.tsx
Labels: size/L

#3435 fix: (limit-orders): Order still visible after executed in open orders tab
  src/utils/localStorageOrders.ts
  src/views/LimitOrders/components/LimitOrderTable/index.tsx
  src/views/LimitOrders/hooks/useFormattedOrderData.ts
  src/views/LimitOrders/hooks/useGelatoLimitOrdersHistory.ts
  src/views/LimitOrders/types.ts
Labels: size/L

#3452 refactor: Ifo user credit selector
  src/state/pools/selectors.ts
Labels: size/XS

#3456 revert: Order still visible after executed
  src/utils/localStorageOrders.ts
  src/views/LimitOrders/components/LimitOrderTable/index.tsx
  src/views/LimitOrders/hooks/useFormattedOrderData.ts
  src/views/LimitOrders/hooks/useGelatoLitmitOrdersHistory.ts
  src/views/LimitOrders/types.ts
Labels: size/L

#3437 feat: Provide more token lists options
  src/components/SearchModal/ManageLists.tsx
  src/config/constants/lists.ts
  src/hooks/Tokens.ts
  src/state/index.ts
  src/state/lists/hooks.ts
  src/state/user/hooks/index.tsx
Labels: size/M, automerge

#3458 fix: Redux migration
  src/state/index.ts
Labels: size/XS

#3459 fix: Remove redux token list migration
  src/state/index.ts
Labels: size/S

#3460 test(cypress): Tmp increase pool timeout
  cypress/integration/exchange/liquidity.test.ts
Labels: size/XS, automerge

#3462 chore: Comment out Coingecko list in default list
  src/config/constants/lists.ts
Labels: size/XS, automerge

#3455 chore: Update IFO Live
  src/components/Menu/config/config.ts
Labels: size/XS

#3457 chore(earn): Add Duet farm and pool
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
Labels: size/S

#3464 chore(ifo): Turn IFO off
  src/components/Menu/config/config.ts
Labels: size/XS

#3463 chore: Details of banner UI
  src/config/constants/lists.ts
  src/config/localization/translations.json
  src/views/Home/components/Banners/IFOBanner.tsx
  src/views/Home/components/Banners/LotteryBanner.tsx
  src/views/Home/components/Banners/Styled.tsx
Labels: size/M

#3461 fix: Prevent TypeError in Nft Collection
  src/state/nftMarket/helpers.ts
Labels: size/M

#3451 feat: Dynamic status tags for menu items
  src/components/Menu/index.tsx
  src/hooks/useMenuItems.ts
  src/hooks/useMenuItemsStatus.ts
  src/views/Home/components/Banners/hooks/useIsRenderIFOBanner.tsx
Labels: size/M

#3467 chore:(ifo): Update DUET ifo's articleUrl
  src/config/constants/ifo.ts
Labels: size/XS

#3466 fix: Remove limit order local storage data after disconnect
  src/utils/clearUserStates.ts
  src/utils/getLocalStorageItemKeys.ts
  src/utils/localStorageOrders.ts
Labels: size/S

#3470 fix(limit-orders): Avoid showing incorrect price format in confirm modal
  src/views/LimitOrders/index.tsx
Labels: size/XS

#3421 feat: (farms): Show token amounts inside LP
  src/state/farms/fetchFarms.ts
  src/state/farms/selectors.ts
  src/state/types.ts
  src/views/Farms/Farms.tsx
  src/views/Farms/components/FarmCard/CardActionsContainer.tsx
  src/views/Farms/components/FarmCard/FarmCard.tsx
  src/views/Farms/components/FarmCard/StakeAction.tsx
  src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  src/views/Farms/components/FarmTable/Actions/HarvestAction.tsx
  src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
  src/views/Farms/components/FarmTable/Row.tsx
  src/views/Farms/components/StakedLP.tsx
  src/views/Farms/components/types.ts
  src/views/Home/hooks/useGetTopFarmsByApr.tsx
Labels: size/L

#3472 fix: Prevent undefined TypeError in lottery
  src/views/Lottery/components/PreviousRoundCard/Body.tsx
Labels: size/XS

#3476 fix: Avoid totalSupply undefined
  src/state/nftMarket/helpers.ts
  src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/index.tsx
  src/views/Nft/market/Collection/Traits/PancakeBunniesTraits.tsx
  src/views/Nft/market/Collections/index.tsx
  src/views/Nft/market/hooks/useCollectionNfts.tsx
Labels: size/S

#3465 fix: (limit-orders): Open orders still visible after executed
  src/utils/localStorageOrders.ts
  src/views/LimitOrders/components/LimitOrderTable/index.tsx
  src/views/LimitOrders/hooks/useFormattedOrderData.ts
  src/views/LimitOrders/hooks/useGelatoLimitOrdersHistory.ts
  src/views/LimitOrders/types.ts
Labels: size/L

#3475 fix: Avoid sentry undefined collectionName
  src/state/nftMarket/hooks.ts
  src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/MainNFTCard.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/ManageNFTsCard.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/MainPancakeBunnyCard.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/ManagePancakeBunniesCard.tsx
  src/views/Nft/market/Collection/Items/PancakeBunniesCollectionNfts.tsx
  src/views/Nft/market/Profile/components/UnconnectedProfileNfts.tsx
  src/views/Nft/market/Profile/components/UserNfts.tsx
  src/views/Nft/market/components/Activity/ActivityRow.tsx
  src/views/Nft/market/components/Activity/MobileModal.tsx
  src/views/Nft/market/components/BuySellModals/BuyModal/ReviewStage.tsx
  src/views/Nft/market/components/BuySellModals/SellModal/EditStage.tsx
  src/views/Nft/market/components/BuySellModals/SellModal/SellStage.tsx
  src/views/Nft/market/components/BuySellModals/SellModal/TransferStage.tsx
  src/views/Nft/market/components/CollectibleCard/CardBody.tsx
  src/views/Nft/market/components/ProfileNftModal.tsx
Labels: size/M

#3474 fix: Avoid TypeError undefined marketData.currentAskPrice
  src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/MainNFTCard.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/ManageNFTsCard.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/OwnerCard.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/ForSaleTableCard/ForSaleTableRows.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/MainPancakeBunnyCard.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/ManagePancakeBunniesCard.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/index.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/shared/MoreFromThisCollection.tsx
  src/views/Nft/market/Collection/Items/CollectionNfts.tsx
  src/views/Nft/market/Home/Newest.tsx
  src/views/Nft/market/Profile/components/UnconnectedProfileNfts.tsx
  src/views/Nft/market/Profile/components/UserNfts.tsx
  src/views/Nft/market/components/BuySellModals/BuyModal/index.tsx
  src/views/Nft/market/components/BuySellModals/SellModal/EditStage.tsx
  src/views/Nft/market/components/BuySellModals/SellModal/index.tsx
Labels: size/M

#3469 chore: LotteryBanner while preparing
  src/config/localization/translations.json
  src/views/Home/components/Banners/LotteryBanner.tsx
  src/views/Home/components/Banners/hooks/useIsRenderLotteryBanner.tsx
Labels: size/M

#3479 chore: Add bsw
  public/images/tokens/0x965f527d9159dce6288a2219db51fc6eef120dd1.png
  public/images/tokens/0x965f527d9159dce6288a2219db51fc6eef120dd1.svg
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
  src/config/constants/tokens.ts
Labels: size/M, automerge

#3483 fix: bsw token image
  public/images/tokens/0x965F527D9159dCe6288a2219DB51fc6Eef120dD1.png
  public/images/tokens/0x965F527D9159dCe6288a2219DB51fc6Eef120dD1.svg
  src/config/constants/tokens.ts
Labels: size/XS, automerge

#3481 feat: Add perp entry
  packages/uikit/src/components/SubMenuItems/SubMenuItems.tsx
  packages/uikit/src/components/SubMenuItems/types.ts
  src/components/Menu/config/config.ts
  src/components/Menu/hooks/useMenuItems.ts
  src/components/Menu/hooks/useMenuItemsStatus.ts
  src/components/Menu/index.tsx
  src/config/localization/translations.json
Labels: size/M

#3484 fix: Modal transition issue
  packages/uikit/src/widgets/Modal/ModalContext.tsx
Labels: size/XS, automerge

#3490 fix: Token list sorting ref
  src/components/SearchModal/CurrencySearch.tsx
Labels: size/XS, automerge

#3489 fix: (nft): Order by collection in collections page
  src/views/Nft/market/Collections/index.tsx
Labels: size/XS

#3494 chore(farms): Whitelist #17
  src/config/constants/farmAuctions.ts
Labels: size/XS, automerge

#3498 refactor: Use Number.isNaN instead of global method
  src/state/limitOrders/hooks.ts
  src/state/swap/hooks.ts
Labels: size/XS, automerge

#3501 chore: Remove unused js-cookie dependency
  package.json
  yarn.lock
Labels: size/XS

#3499 chore: Bump up swr
  package.json
  yarn.lock
Labels: size/S

#3486 fix: Menu utils test and add more language support to perpetuals
  src/components/Menu/config/config.ts
  src/components/Menu/hooks/useMenuItems.ts
  src/utils/getPerpetualLanguageCode.ts
Labels: size/S

#3500 fix: Swr hooks rerenders before fetch although isValidating is not used
  src/hooks/useSWRContract.ts
Labels: size/S

#3503 refactor: (lottery): Use memoized selectors in lottery hooks
  src/state/lottery/helpers.ts
  src/state/lottery/hooks.ts
  src/state/lottery/selectors.ts
Labels: size/L

#3493 fix: Pool APR skeleton when pool not yet started
  src/views/Pools/components/Apr.tsx
  src/views/Pools/components/PoolCard/AprRow.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
  src/views/Pools/components/PoolsTable/Cells/AprCell.tsx
  src/views/Pools/components/PoolsTable/Cells/AutoAprCell.tsx
Labels: size/L

#3482 perf: Reduce render and calls in swap
  src/state/swap/hooks.test.ts
  src/state/swap/hooks.ts
  src/views/Swap/index.tsx
Labels: size/L

#3505 fix: Fix color for Lottery Input
  src/views/Lottery/components/BuyTicketsModal/TicketInput.tsx
Labels: size/XS, automerge

#3507 chore: Turn off active IFO
  src/config/constants/ifo.ts
Labels: size/XS

#3495 refactor: Use orderBy instead of sort
  src/components/Menu/utils.ts
  src/state/info/queries/tokens/priceData.ts
  src/state/swap/fetch/fetchDerivedPriceData.ts
  src/state/wallet/hooks.ts
  src/utils/localStorageOrders.ts
  src/views/FarmAuction/helpers.tsx
  src/views/Info/components/InfoSearch/index.tsx
  src/views/Info/components/InfoTables/TokensTable.tsx
  src/views/Info/hooks/useBlocksFromTimestamps.ts
  src/views/LimitOrders/hooks/useGelatoLimitOrdersHistory.ts
  src/views/Lottery/components/ViewTicketsModal/PreviousRoundTicketsInner.tsx
  src/views/Nft/market/ActivityHistory/utils/sortActivity.tsx
  src/views/Nft/market/Collection/Traits/PancakeBunniesTraits.tsx
  src/views/Nft/market/Collections/index.tsx
  src/views/Nft/market/Profile/utils/sortUserActivity.tsx
  src/views/TradingCompetition/components/TeamRanks/index.tsx
Labels: size/L

#3506 fix: (prediction) Wrong buffer phase let users to bet until the very end of the open round
  src/state/predictions/config.ts
  src/views/Predictions/components/RoundCard/OpenRoundCard.tsx
Labels: size/XS

#3514 chore: use next image to avoid layout shift
  public/images/home/lunar-bunny/bunny.png
  public/images/home/lunar-bunny/bunny.webp
  public/images/home/lunar-bunny/bunny@1.5x.png
  public/images/home/lunar-bunny/bunny@1.5x.webp
  public/images/home/lunar-bunny/bunny@2x.webp
  src/views/Home/components/Hero.tsx
Labels: size/S, automerge

#3515 feat(wallet): Trust Wallet IOS use injected connector
  packages/uikit/src/widgets/WalletModal/WalletCard.tsx
Labels: size/S, automerge

#3516 chore: Try enable sourcemap
  next.config.js
  src/components/ErrorBoundary/ErrorBoundary.tsx
  tsconfig.json
Labels: size/XS

#3518 chore: Add farms from auction 17
  public/images/tokens/0x19e6BfC1A6e4B042Fb20531244D47E252445df01.png
  public/images/tokens/0x19e6BfC1A6e4B042Fb20531244D47E252445df01.svg
  src/config/constants/farms.ts
  src/config/constants/tokens.ts
Labels: size/M

#3521 chore: Avoid matchMedia not function error
  packages/uikit/src/components/Image/BackgroundImage.tsx
  packages/uikit/src/hooks/useMatchBreakpoints.ts
Labels: size/XS

#3519 fix: Reset lottery user state when logout
  src/state/lottery/index.ts
Labels: size/XS

#3523 chore: Enable Sentry
  next.config.js
  sentry.server.config.js
Labels: size/XS

#3513 feat: Testnet swap
  package.json
  packages/uikit/src/components/Image/tokens.ts
  src/components/TransactionConfirmationModal/index.tsx
  src/config/constants/tokenLists/pancake-default.tokenlist.json
  src/config/constants/tokens.ts
  src/hooks/useBUSDPrice.ts
  src/views/Home/hooks/useGetTopPoolsByApr.tsx
  src/views/Nft/market/components/BuySellModals/BuyModal/index.tsx
  yarn.lock
Labels: size/M, automerge

#3520 fix: (swap): Initial token search freezes the app couple of second
  src/state/lists/hooks.ts
Labels: size/M, automerge

#3492 fix: (liquidity): No Lp found message when lp's are loading
  src/views/Pool/index.tsx
Labels: size/S, automerge

#3526 chore(middleware): Lower edge function computation
  src/pages/_middleware.ts
Labels: size/S, automerge

#3525 chore(prep): Only allow whitelist lang to prep
  src/utils/getPerpetualLanguageCode.ts
Labels: size/XS, automerge

#3527 fix: Fix address undefined TypeError
  src/views/Nft/market/ActivityHistory/ActivityFilters.tsx
  src/views/Nft/market/ActivityHistory/ActivityHistory.tsx
Labels: size/XS

#3511 fix: (prediction): Swiper doesn't work after clicking back button on round card on mobile
  src/views/Predictions/components/RoundCard/SetPositionCard.tsx
Labels: size/S, automerge

#3536 chore: Remove unused import
  src/views/Predictions/components/RoundCard/SetPositionCard.tsx
Labels: size/XS, automerge

#3535 fix: Avoid null TypeError null
  src/views/Predictions/components/Label.tsx
Labels: size/XS, automerge

#3533 fix: Avoid collection.address error
  src/views/Nft/market/Collection/Items/CollectionNfts.tsx
Labels: size/XS

#3534 chore: Fix IntersectionObserver
  packages/uikit/src/components/Image/Image.tsx
Labels: size/S

#3538 fix: Avoid getItem undefined error
  src/hooks/useEagerConnect.ts
Labels: size/XS

#3540 fix: Avoid Object.fromEntries error
  src/state/lists/hooks.ts
Labels: size/XS, automerge

#3541 fix: Avoid address undefined in nft
  src/views/Nft/market/Collection/Items/CollectionWrapper.tsx
  src/views/Nft/market/Collection/Items/Filters.tsx
Labels: size/S

#3532 feat(limit-order): Add Warning modal
  src/components/DisclaimerModal/index.tsx
  src/config/localization/translations.json
  src/state/user/actions.ts
  src/state/user/hooks/index.tsx
  src/state/user/reducer.ts
  src/views/LimitOrders/components/ClaimWarning.tsx
  src/views/LimitOrders/index.tsx
Labels: size/L

#3542 chore: Remove js-cookie type definitions
  package.json
  yarn.lock
Labels: size/XS

#3546 fix: Lottery selectors not trigger rerender after user tickets fetch
  src/state/lottery/index.ts
Labels: size/XS

#3543 fix: Avoid tickets.map undefined
  src/state/lottery/index.ts
Labels: size/XS

#3545 fix: Avoid localstorage null called
  src/hooks/useAuth.ts
  src/hooks/useEagerConnect.ts
  src/utils/clearUserStates.ts
Labels: size/S

#3548 refactor: (prediction): Use memoized selector for earliest epoch
  src/state/predictions/hooks.ts
  src/state/predictions/selectors.ts
Labels: size/S

#3544 fix: Remove user tickets from current round when logout
  src/state/lottery/index.ts
Labels: size/XS

#3551 chore: Avoid getItem null
  src/hooks/useSWRContract.ts
Labels: size/XS

#3553 fix: Farm auction page keep loading
  src/views/FarmAuction/helpers.tsx
Labels: size/XS, automerge

#3550 chore: Add debug for Pair.getAddress
  src/hooks/usePairs.ts
Labels: size/S

#3539 chore: Bump styled components
  package.json
  packages/uikit/package.json
  yarn.lock
Labels: size/S

#3547 perf: Fetch public data only for lottery banner
  src/state/lottery/hooks.ts
  src/views/Home/components/Banners/hooks/useIsRenderLotteryBanner.tsx
Labels: size/XS

#3552 chore: Add types for base in theme
  packages/uikit/src/components/Card/CardRibbon.tsx
  packages/uikit/src/theme/base.ts
  packages/uikit/src/theme/types.ts
Labels: size/S, automerge
