Repository pancakeswap/pancake-frontend, pull requests merged in 2022-08, with the labels that each got.

#4368 perf: (theme): Don't create function each time getThemeValue called
  packages/uikit/src/components/Svg/Svg.tsx
  packages/uikit/src/components/Text/Text.tsx
  packages/uikit/src/util/getThemeValue.ts
  packages/uikit/src/widgets/Modal/Modal.tsx
  packages/uikit/src/widgets/WalletModal/ConnectModal.tsx
Labels: size/S

#4370 feat: Add more perpetual language
  src/utils/getPerpetualLanguageCode.ts
Labels: size/S, automerge

#4367 perf(Prediction): Use promise all in fetch claimStatuses
  src/state/predictions/index.ts
Labels: size/S

#4363 perf: (farms): Extract lp total supply big number to variable in farm fetch
  src/state/farms/fetchFarms.ts
  src/state/farmsV1/fetchFarms.ts
Labels: size/S

#4362 perf: (coinswitcher): Memoize props in inner coin switcher
  packages/uikit/src/components/CoinSwitcher/CoinSwitcher.tsx
Labels: size/S

#4360 perf: (slider): Use callback on handle change to not create a function when sliding
  packages/uikit/src/components/Slider/Slider.tsx
  src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
  src/views/Pools/components/PoolCard/Modals/StakeModal.tsx
  src/views/Predictions/components/RoundCard/SetPositionCard.tsx
  src/views/RemoveLiquidity/index.tsx
Labels: size/L

#4372 feat: Add meta title
  src/config/constants/meta.ts
  src/config/localization/translations.json
Labels: size/XS, automerge

#4369 perf: (uikit): Reduce rerenders in useOnClickOutside hook
  packages/uikit/src/components/BottomDrawer/BottomDrawer.tsx
  packages/uikit/src/components/DropdownMenu/DropdownMenu.tsx
  packages/uikit/src/hooks/useOnClickOutside.ts
Labels: size/M

#4364 feat(ROI Calculator): Farms displays both LP and CAKE rewards
  src/components/RoiCalculatorModal/RoiCalculatorFooter.tsx
  src/config/localization/translations.json
Labels: size/S

#4298 feat: vCake
  packages/uikit/src/components/Svg/Icons/RocketIcon.tsx
  packages/uikit/src/components/Svg/index.tsx
  src/config/localization/translations.json
  src/views/Voting/components/CastVoteModal/DetailsView.tsx
  src/views/Voting/components/CastVoteModal/MainView.tsx
  src/views/Voting/components/CastVoteModal/index.tsx
  src/views/Voting/components/CastVoteModal/styles.tsx
  src/views/Voting/components/VoteDetailsModal.tsx
  src/views/Voting/helpers.ts
  src/views/Voting/hooks/useGetVotingPower.tsx
  src/views/Voting/strategies.ts
Labels: size/L

#4380 chore(ifo): Update ifo banner name
  src/config/constants/ifo.ts
  src/views/Home/components/Banners/IFOBanner.tsx
  src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/M

#4378 chore: Typos
  packages/uikit/src/components/BalanceInput/index.stories.tsx
  packages/uikit/src/components/Breadcrumbs/Breadcrumbs.tsx
  packages/uikit/src/components/PancakeToggle/StyledPancakeToggle.tsx
  packages/uikit/src/widgets/Modal/index.stories.tsx
Labels: size/XS

#4366 perf: (pools): Reduce fetch pools async calls calculations
  src/state/pools/fetchPoolsUser.ts
Labels: size/M

#4377 chore: Fix overridden properties in uikit css
  packages/uikit/src/ResetCSS.tsx
  packages/uikit/src/components/Card/CardRibbon.tsx
  packages/uikit/src/components/Input/Input.tsx
  packages/uikit/src/widgets/Modal/ModalContext.tsx
  packages/uikit/src/widgets/Modal/styles.tsx
Labels: size/XS

#4373 feat: Support urlQuery for mp
  src/components/SearchInput/SearchInput.tsx
  src/views/Farms/Farms.tsx
  src/views/Pools/index.tsx
Labels: size/S

#4384 fix: payload maybe not an object
  src/utils/mpBridge.ts
Labels: size/XS

#4386 feat: Remove BBT-BNB
  src/config/constants/farmAuctions.ts
Labels: size/XS, automerge

#4376 perf: Run cleanup function on base menu only once
  packages/uikit/src/components/BaseMenu/BaseMenu.tsx
Labels: size/S

#4375 perf: Dynamic load fixed subgraph health indicator
  src/components/SubgraphHealthIndicator/FixedSubgraphHealthIndicator.tsx
  src/components/SubgraphHealthIndicator/index.tsx
  src/pages/_app.tsx
  src/views/LimitOrders/components/LimitOrderTable/TableNavigation.tsx
  src/views/TradingCompetition/components/TeamRanks/TopTradersCard/index.tsx
  src/views/TradingCompetition/components/YourScore/ScoreCard.tsx
Labels: size/S

#4385 fix: Circle svg distribution issue in firefox
  src/views/AddLiquidity/components/common.tsx
Labels: size/XS

#4381 feat(GlobalSettings): Setting button optimization
  cypress/integration/exchange/swap.test.ts
  packages/uikit/src/widgets/Modal/types.ts
  src/components/Menu/GlobalSettings/SettingsModal.tsx
  src/components/Menu/GlobalSettings/index.tsx
  src/components/Menu/GlobalSettings/types.ts
  src/components/Menu/index.tsx
  src/views/LimitOrders/components/CurrencyInputHeader.tsx
  src/views/Swap/components/CurrencyInputHeader.tsx
Labels: size/L

#4109 fix: (pool): Extend duration check based on current duration causes locked vault to not extend
  src/config/localization/translations.json
  src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
  src/views/Pools/components/LockedPool/Buttons/ExtendDurationButton.tsx
  src/views/Pools/components/LockedPool/Common/ExtendEnable.tsx
  src/views/Pools/components/LockedPool/Common/LockDurationField.tsx
  src/views/Pools/components/LockedPool/Common/LockedActions.tsx
  src/views/Pools/components/LockedPool/Common/LockedModalBody.tsx
  src/views/Pools/components/LockedPool/Modals/AddAmountModal.tsx
  src/views/Pools/components/LockedPool/Modals/ExtendDurationModal.tsx
  src/views/Pools/components/LockedPool/hooks/useExtendEnable.tsx
  src/views/Pools/components/LockedPool/types/index.ts
  src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
  src/views/Pools/helpers.tsx
Labels: size/L

#4335 chore: improve chinese translation
  public/locales/zh-TW.json
Labels: size/L

#4355 fix(Profile): remove subMenu
  src/components/Menu/UserMenu/ProfileUserMenuItem.tsx
  src/components/Menu/UserMenu/index.tsx
  src/config/constants/meta.ts
  src/pages/nfts/profile/[accountAddress]/activity.tsx
  src/pages/profile/[accountAddress].tsx
  src/pages/profile/[accountAddress]/achievements.tsx
  src/pages/profile/[accountAddress]/activity.tsx
  src/pages/profile/index.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IFORequirements.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardActions.tsx
  src/views/Ifos/components/IfoSteps.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/MainNFTCard.tsx
  src/views/Nft/market/Home/index.tsx
  src/views/Nft/market/components/BuySellModals/SellModal/SellStage.tsx
  src/views/Nft/market/components/ProfileCell.tsx
  src/views/Nft/market/components/ProfileNftModal.tsx
  src/views/Nft/market/components/SearchBar.tsx
  src/views/PancakeSquad/components/Buttons/EndEvent.tsx
  src/views/Pools/components/ProfileRequirementWarning.tsx
  src/views/Profile/components/Achievements/AchievementAvatar.tsx
  src/views/Profile/components/Achievements/AchievementCard.tsx
  src/views/Profile/components/Achievements/AchievementDescription.tsx
  src/views/Profile/components/Achievements/AchievementRow/PointsLabel.tsx
  src/views/Profile/components/Achievements/AchievementRow/index.tsx
  src/views/Profile/components/Achievements/AchievementTitle.tsx
  src/views/Profile/components/Achievements/AchievementsList.tsx
  src/views/Profile/components/Achievements/ClaimPointsCallout.tsx
  src/views/Profile/components/Achievements/index.tsx
  src/views/Profile/components/ActivityHistory/index.tsx
  src/views/Profile/components/EditProfileAvatar.tsx
  src/views/Profile/components/EditProfileModal/ApproveCakeView.tsx
  src/views/Profile/components/EditProfileModal/ChangeProfilePicView.tsx
  src/views/Profile/components/EditProfileModal/PauseProfileView.tsx
  src/views/Profile/components/EditProfileModal/StartView.tsx
  src/views/Profile/components/EditProfileModal/index.tsx
  src/views/Profile/components/EditProfileModal/reducer.ts
  src/views/Profile/components/ProfileHeader.tsx
  src/views/Profile/components/SubMenu.tsx
  src/views/Profile/components/TabMenu.tsx
  src/views/Profile/components/UnconnectedProfileNfts.tsx
  src/views/Profile/components/UserNfts.tsx
  src/views/Profile/hooks/useGetProfileCosts.ts
  src/views/Profile/index.tsx
  src/views/Profile/utils/sortUserActivity.tsx
  src/views/ProfileCreation/Header.tsx
  src/views/ProfileCreation/index.tsx
  src/views/TradingCompetition/components/HowToJoin/index.tsx
  src/views/TradingCompetition/components/RegisterModal/MakeProfile.tsx
  src/views/TradingCompetition/components/RegisterModal/ReactivateProfile.tsx
Labels: size/L

#4387 perf: Remove redundant refs in toast
  src/components/Toast/Toast.tsx
  src/contexts/ToastsContext/Listener.tsx
Labels: size/S

#4392 fix(GlobalSettings): Fix Liquidity settings content
  src/components/App/AppHeader.tsx
  src/components/Menu/GlobalSettings/SettingsModal.tsx
Labels: size/S

#4382 chore: ifo banner mobile fontsize
  src/views/Home/components/Banners/IFOBanner.tsx
Labels: size/S

#4374 perf: Dynamic load easter egg
  src/components/EasterEgg/EasterEgg.tsx
Labels: size/XS

#4379 perf: Remove useRef hook in useIntersectionObserver hook
  src/hooks/useIntersectionObserver.ts
Labels: size/XS

#4351 chore: New Crowdin updates
  public/locales/ar-SA.json
  public/locales/bn-BD.json
  public/locales/de-DE.json
  public/locales/el-GR.json
  public/locales/en-US.json
  public/locales/es-ES.json
  public/locales/fi-FI.json
  public/locales/fil-PH.json
  public/locales/fr-FR.json
  public/locales/hi-IN.json
  public/locales/hu-HU.json
  public/locales/id-ID.json
  public/locales/it-IT.json
  public/locales/ja-JP.json
  public/locales/ko-KR.json
  public/locales/nl-NL.json
  public/locales/pl-PL.json
  public/locales/pt-BR.json
  public/locales/pt-PT.json
  public/locales/ro-RO.json
  public/locales/ru-RU.json
  public/locales/sv-SE.json
  public/locales/ta-IN.json
  public/locales/tr-TR.json
  public/locales/uk-UA.json
  public/locales/vi-VN.json
  public/locales/zh-CN.json
  public/locales/zh-TW.json
Labels: size/XL

#4396 feat: Vote space name
  src/state/voting/helpers.ts
  src/views/Voting/config.ts
Labels: size/XS

#4398 fix: LP Apr script
  package.json
  src/config/constants/lpAprs.json
Labels: size/L

#4400 feat: Add voting admin address
  src/views/Voting/config.ts
Labels: size/XS, automerge

#4401 fix(Profile): Fix profile subMenu marginBottom
  src/views/Profile/components/SubMenu.tsx
Labels: size/XS

#4393 feat: Move SDAO to finished pool
  src/config/constants/pools.tsx
Labels: size/S, automerge

#4389 refactor: Remove redundant ref in select component
  src/components/Select/Select.tsx
Labels: size/XS

#4394 fix(SwapSettings): Add transationSpeed option
  src/components/Menu/GlobalSettings/SettingsModal.tsx
Labels: size/XS

#4390 feat: List farm auction 27 winner
  src/config/constants/farms.ts
Labels: size/M

#4403 perf: Use img onerror for fallback instead of picture tag to not load fallback always
  src/components/PhishingWarningBanner/index.tsx
  src/views/Home/components/CompositeImage.tsx
Labels: size/M

#4406 fix(lock-pool): Remove zero display
  src/views/Pools/components/LockedPool/Common/LockDurationField.tsx
  src/views/Pools/components/LockedPool/Common/LockedModalBody.tsx
Labels: size/S

#4404 feat: List peel shell
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
Labels: size/M

#4408 chore: Remove tag
  src/config/constants/farms.ts
Labels: size/XS

#4409 fix: Not show max duration recommend when user lock below 52 weeks
  src/views/Pools/components/LockedPool/Common/LockDurationField.tsx
  src/views/Pools/components/LockedPool/Common/LockedModalBody.tsx
  src/views/Pools/components/LockedPool/types/index.ts
Labels: size/S

#4411 fix: IFO vesting total release amount
  src/views/Ifos/components/IfoVesting/VestingPeriod/TokenInfo.tsx
Labels: size/S

#4405 chore: Add wagmi tsconfig
  tsconfig.json
Labels: size/XS

#4395 feat: Support default active for mp search
  src/components/SearchInput/SearchInput.tsx
  src/views/Farms/Farms.tsx
  src/views/Farms/components/FarmTable/FarmTable.tsx
  src/views/Farms/components/FarmTable/Row.tsx
  src/views/Pools/components/PoolsTable/ExpandRow.tsx
  src/views/Pools/components/PoolsTable/PoolRow.tsx
  src/views/Pools/components/PoolsTable/PoolsTable.tsx
  src/views/Pools/index.tsx
Labels: size/L

#4413 chore: use lazy motion in MotionBox
  packages/uikit/src/components/Box/Box.tsx
Labels: size/XS

#4415 fix: LockedDate
  src/views/Pottery/components/Pot/Claim/AvailableWithdraw.tsx
Labels: size/S, automerge

#4412 refactor(mono): Migrate mono patch 1
  apps/test/cypress.json
  apps/test/cypress/.eslintrc
  apps/test/cypress/integration/exchange/add-liquidity.test.ts
  apps/test/cypress/integration/exchange/liquidity.test.ts
  apps/test/cypress/integration/exchange/lists.test.ts
  apps/test/cypress/integration/exchange/remove-liquidity.test.ts
  apps/test/cypress/integration/exchange/send.test.ts
  apps/test/cypress/integration/exchange/swap.test.ts
  apps/test/cypress/integration/farms/farms.test.ts
  apps/test/cypress/integration/home/home.test.ts
  apps/test/cypress/integration/ifo/ifo.test.ts
  apps/test/cypress/integration/info/info.test.ts
  apps/test/cypress/integration/lottery/lottery.test.ts
  apps/test/cypress/integration/nfts/nfts.test.ts
  apps/test/cypress/integration/pools/pools.test.ts
  apps/test/cypress/integration/predictions/predictions.test.ts
  apps/test/cypress/integration/teamsAndProfile/leaderboard.test.ts
  apps/test/cypress/integration/teamsAndProfile/profile.test.ts
  apps/test/cypress/integration/tradingCompetition/tradingCompetition.test.ts
  apps/test/cypress/integration/voting/voting.test.ts
  apps/test/cypress/support/commands.js
  apps/test/cypress/support/index.d.ts
  apps/test/cypress/support/index.js
  apps/test/cypress/tsconfig.json
  apps/test/package.json
  jest.config.js
  package.json
  turbo.json
  yarn.lock
Labels: size/XXL

#4416 chore: Hide timer
  src/views/Pottery/components/Banner/index.tsx
  src/views/Pottery/components/Pot/Deposit/index.tsx
Labels: size/XS, automerge

#4417 feat: Show pottery timer
  src/views/Pottery/components/Banner/index.tsx
  src/views/Pottery/components/Pot/Deposit/index.tsx
Labels: size/XS, automerge

#4434 perf: Remove Hops address from admins list
  src/views/Voting/config.ts
Labels: size/XS, automerge

#4422 chore: lazy motion feature adjustment
  packages/uikit/src/widgets/Modal/ModalContext.tsx
Labels: size/S

#4437 fix: User only can withdraw when status is unlock
  src/state/pottery/fetchPottery.ts
  src/views/Pottery/components/Pot/Claim/AvailableWithdraw.tsx
  src/views/Pottery/components/Pot/Claim/WithdrawButton.tsx
Labels: size/S, automerge

#4435 chore: Move XCN to finished pool
  src/config/constants/pools.tsx
Labels: size/S, automerge

#4388 refactor: Remove redundant ref in trading view component
  src/components/TradingView.tsx
Labels: size/XS, automerge

#4419 feat: Add support for add token to wallet button for other wallet apps
  packages/localization/src/config/translations.json
  src/components/AddToWallet/AddToWalletButton.tsx
  src/components/CurrencyInputPanel/index.tsx
  src/components/TransactionConfirmationModal/index.tsx
  src/utils/wallet.ts
  src/views/Pools/components/PoolStatsInfo.tsx
Labels: size/L

#4441 docs: Update localization import path
  doc/i18n.md
Labels: size/XS

#4444 fix: Pottery round bug
  src/state/pottery/fetchPottery.ts
  src/views/Pottery/components/FinishedRounds/AllHistoryCard/index.tsx
Labels: size/XS, automerge

#4436 feat: List pStake
  public/images/tokens/0x4C882ec256823eE773B25b414d36F92ef58a7c0C.png
  public/images/tokens/0xc2E9d07F66A89c44062459A47a0D2Dc038E4fb16.png
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
  src/config/constants/tokens.ts
Labels: size/M, automerge

#4446 style: NFT submenu css
  src/views/Nft/market/components/BaseSubMenu.tsx
Labels: size/XS, automerge

#4442 fix: (prediction): Swiper error on mobile chart when clicking dots
  src/views/Home/components/Banners/MultipleBanner.tsx
  src/views/Predictions/MobileChart.tsx
  src/views/Predictions/Positions.tsx
  src/views/Predictions/components/PrevNextNav.tsx
Labels: size/M

#4432 perf: Don't make a request to on chain for pool length when it is in state
  src/state/farms/index.ts
Labels: size/S

#4440 chore: Typo
  packages/localization/package.json
Labels: size/XS

#4448 fix: Modal container minWidth not recognized in dom warning
  packages/uikit/src/widgets/Modal/styles.tsx
  packages/uikit/src/widgets/WalletModal/ConnectModal.tsx
  src/components/DisclaimerModal/index.tsx
  src/components/Menu/UserMenu/WalletModal.tsx
  src/views/Lottery/components/ClaimPrizesModal/index.tsx
  src/views/PancakeSquad/components/Modals/BuyTickets/index.tsx
  src/views/PancakeSquad/components/Modals/Confirm/index.tsx
  src/views/Predictions/Leaderboard/components/WalletStatsModal.tsx
  src/views/Predictions/components/ChainlinkChartDisclaimer.tsx
  src/views/Predictions/components/ChartDisclaimer.tsx
  src/views/Predictions/components/CollectRoundWinningsModal.tsx
  src/views/Predictions/components/v1/NothingToClaimModal.tsx
  src/views/Swap/components/SwapWarningModal/index.tsx
Labels: size/S

#4449 feat: Farm pid
  src/config/constants/farms.ts
Labels: size/S

#4439 chore: Update yarn lock
  yarn.lock
Labels: size/XXL

#4428 fix: Transaction description in recent trxs can be off if slippage is too high and add translation support
  packages/localization/src/config/translations.json
  src/__tests__/translations.test.ts
  src/components/Menu/UserMenu/TransactionRow.tsx
  src/hooks/useSwapCallback.ts
  src/state/transactions/actions.ts
  src/state/transactions/hooks.tsx
  src/state/transactions/reducer.ts
Labels: size/L

#4438 chore: Bump up swiper
  package.json
  yarn.lock
Labels: size/S

#4452 feat: Rename to bridge
  apps/bridge/.gitignore
  apps/bridge/README.md
  apps/bridge/components/Menu.tsx
  apps/bridge/components/getTimePeriods.ts
  apps/bridge/components/stargate/config.ts
  apps/bridge/components/stargate/index.tsx
  apps/bridge/components/stargate/network.ts
  apps/bridge/components/stargate/theme.ts
  apps/bridge/next-env.d.ts
  apps/bridge/next.config.mjs
  apps/bridge/package.json
  apps/bridge/pages/_app.tsx
  apps/bridge/pages/_document.tsx
  apps/bridge/pages/index.tsx
  apps/bridge/public/chains/1.png
  apps/bridge/public/chains/10.png
  apps/bridge/public/chains/137.png
  apps/bridge/public/chains/250.png
  apps/bridge/public/chains/4.png
  apps/bridge/public/chains/4002.png
  apps/bridge/public/chains/42161.png
  apps/bridge/public/chains/421611.png
  apps/bridge/public/chains/43113.png
  apps/bridge/public/chains/43114.png
  apps/bridge/public/chains/56.png
  apps/bridge/public/chains/69.png
  apps/bridge/public/chains/80001.png
  apps/bridge/public/chains/97.png
  apps/bridge/public/stargate.png
  apps/bridge/tsconfig.json
  apps/transfer/README.md
  apps/transfer/components/Menu.tsx
  apps/transfer/components/stargate/config.ts
  apps/transfer/wagmi/index.ts
  packages/wagmi/src/chains.ts
  yarn.lock
Labels: size/XL

#4445 feat(Swap&LimitOrder): Add common tokens
  packages/localization/src/config/translations.json
  src/components/CurrencyInputPanel/index.tsx
  src/components/CurrencySelect/index.tsx
  src/components/SearchModal/CommonBases.tsx
  src/components/SearchModal/CurrencySearch.tsx
  src/components/SearchModal/CurrencySearchModal.tsx
  src/components/SearchModal/types.ts
  src/views/AddLiquidity/ChoosePair.tsx
  src/views/AddLiquidity/index.tsx
  src/views/LimitOrders/index.tsx
  src/views/PoolFinder/index.tsx
  src/views/RemoveLiquidity/index.tsx
  src/views/Swap/index.tsx
Labels: size/M

#4457 chore: modal adjustment
  src/components/Menu/GlobalSettings/SettingsModal.tsx
  src/components/SearchModal/CurrencySearchModal.tsx
  src/views/Nft/market/components/ProfileNftModal.tsx
Labels: size/S

#4460 chore: Bump next
  apps/bridge/package.json
  package.json
  yarn.lock
Labels: size/L

#4450 feat(LockCAKEPool): Add burn helpIcon
  packages/localization/src/config/translations.json
  src/state/types.ts
  src/views/Pools/components/LockedPool/LockedStakingApy.tsx
  src/views/Pools/components/LockedPool/hooks/useUserDataInVaultPresenter.ts
  src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
Labels: size/M

#4459 fix: Typo in price impact message in add liquidity
  packages/localization/src/config/translations.json
  src/views/AddLiquidity/index.tsx
Labels: size/XS

#4463 test: Skip test on jest.spyOn bug after upgrading next
  src/hooks/Trades.test.ts
  src/hooks/__snapshots__/Trades.test.ts.snap
  src/hooks/useVaultApy.test.ts
Labels: size/XXL

#4458 feat: Update emissions per block
  src/views/Home/components/CakeDataRow.tsx
Labels: size/XS, automerge

#4469 fix: Swap modal warning style
  src/components/ImportTokenWarningModal.tsx
Labels: size/XS

#4477 fix: Cake display
  src/views/Pottery/components/FinishedRounds/AllHistoryCard/PreviousRoundCardBody.tsx
Labels: size/XS

#4478 fix: (pottery): Undefined nickname is displayed when winner has no profile
  src/views/Pottery/components/FinishedRounds/AllHistoryCard/Winner.tsx
Labels: size/XS

#4474 chore: (pottery): Remove unused gql request variable and change query names
  src/state/pottery/fetchPottery.ts
  src/state/pottery/fetchUserPottery.ts
Labels: size/XS

#4462 chore: cal token list height for react window
  src/components/SearchModal/CurrencyList.tsx
  src/components/SearchModal/CurrencySearch.tsx
  src/components/SearchModal/CurrencySearchModal.tsx
Labels: size/S

#4489 fix: bcake multipler decimal issue
  src/views/Farms/components/YieldBooster/hooks/useBoostMultipler.ts
Labels: size/XS

#4494 chore: Update SafePal logo
  packages/uikit/src/components/Svg/Icons/SafePal.tsx
  public/images/tokens/0xD41FDb03Ba84762dD66a0af1a6C8540FF1ba5dfb.png
  public/images/tokens/0xD41FDb03Ba84762dD66a0af1a6C8540FF1ba5dfb.svg
Labels: size/S

#4498 fix: (farms): Boosted farms not visible when staked only option selected
  src/views/Farms/Farms.tsx
Labels: size/S

#4500 fix: Link inside Booster tooltip cannot be clicked in mobile
  packages/uikit/src/hooks/useTooltip/types.ts
  packages/uikit/src/hooks/useTooltip/useTooltip.tsx
  src/views/Farms/components/YieldBooster/components/ActionButton.tsx
Labels: size/S

#4501 chore(uikit): add india to footer tg shortcuts
  packages/uikit/src/components/Footer/config.tsx
Labels: size/XS

#4490 refactor: Use locale lowercase only in translations
  packages/uikit/src/widgets/WalletModal/WalletCard.tsx
  src/state/pools/helpers.ts
  src/utils/apr.ts
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx
  src/views/Pottery/components/Pot/Deposit/index.tsx
  src/views/Profile/components/ActivityHistory/index.tsx
Labels: size/S

#4488 perf: (bottomnav): Use some instead of reduce
  packages/uikit/src/components/BottomNav/BottomNav.tsx
Labels: size/XS

#4499 refactor: Use css text transform for uppercase instead of toLocaleUppercase
  src/components/CurrencyInputPanel/index.tsx
  src/components/RoiCalculatorModal/index.tsx
  src/views/Pottery/components/WinRateModal/ButtonMenu.tsx
Labels: size/S

#4503 fix(mint): No liquidity crash
  src/hooks/useTotalSupply.ts
  src/state/mint/hooks.ts
Labels: size/S

#4492 fix: (farms): Ondone button warning on proxy button
  src/views/Farms/components/YieldBooster/components/CreateProxyButton.tsx
Labels: size/S

#4504 fix: bCake bootedcard tooltip mobile issue
  src/views/Farms/components/BCakeBoosterCard.tsx
Labels: size/XS

#4507 fix(bcake): Add cache name in getting multiple from MC
  src/views/Farms/components/YieldBooster/components/BoostedApr.tsx
  src/views/Farms/components/YieldBooster/hooks/useBoostMultipler.ts
Labels: size/XS

#4508 fix(mp): Link to pool
  src/views/Farms/components/BCakeBoosterCard.tsx
Labels: size/S

#4509 feat: List farm auction 28
  src/config/constants/farmAuctions.ts
Labels: size/M

#4510 chore: Add iconPath to manifest.json
  public/manifest.json
Labels: size/XS

#4453 feat: Add translation support transaction records for zap, liquidity, approve and limit order
  packages/localization/src/config/translations.json
  src/__tests__/translations.test.ts
  src/hooks/limitOrders/useGelatoLimitOrdersHandlers.ts
  src/hooks/useApproveCallback.ts
  src/hooks/useWrapCallback.ts
  src/state/transactions/actions.ts
  src/state/transactions/hooks.tsx
  src/state/transactions/reducer.ts
  src/views/AddLiquidity/index.tsx
  src/views/RemoveLiquidity/index.tsx
Labels: size/L

#4487 perf: (translation): Check translated text includes variable only when data passed and memoize regex
  packages/localization/src/Provider.tsx
Labels: size/S

#4512 perf: Remove translation.json in bundle
  packages/localization/src/Provider.tsx
  packages/localization/src/index.tsx
  packages/localization/src/types.ts
  src/__tests__/translations.test.ts
  tsconfig.json
Labels: size/S

#4513 chore: Remove reacttext
  packages/uikit/src/components/BalanceInput/types.ts
  src/state/transactions/actions.ts
  src/state/transactions/hooks.tsx
  src/state/transactions/reducer.ts
  src/views/AddLiquidity/index.tsx
  src/views/TradingCompetition/components/ShareImageModal.tsx
  src/views/TradingCompetition/components/YourScore/CardUserInfo.tsx
  src/views/TradingCompetition/helpers.ts
  src/views/TradingCompetition/types.ts
Labels: size/M, automerge

#4485 refactor: Move lint-staged to dev dependency
  package.json
Labels: size/XS

#4476 feat(TokenSelect): No autoFocus on Mobile
  src/components/SearchModal/CurrencySearch.tsx
Labels: size/XS, automerge

#4486 fix: Fix subgraph healthy show status
  src/components/SubgraphHealthIndicator/index.tsx
Labels: size/XS, automerge

#4517 chore: Remove warnings
  src/components/SearchModal/CurrencySearch.tsx
Labels: size/XS, automerge

#4518 fix: Prevent translation set not found
  packages/localization/src/Provider.tsx
Labels: size/XS

#4427 fix: Minus zero displayed in lp rewards apr in roi calculator in farms
  src/components/RoiCalculatorModal/RoiCalculatorFooter.tsx
Labels: size/XS, automerge

#4523 fix(DropdownMenu): DropdownMenu will overlay BottomNav
  packages/uikit/src/components/DropdownMenu/styles.tsx
Labels: size/XS

#4515 chore: Bump sentry v7
  next.config.js
  package.json
  sentry.client.config.js
  sentry.server.config.js
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/hooks/useCallWithGasPrice.ts
  src/hooks/useSentryUser.ts
  src/pages/_error.tsx
  src/utils/clearUserStates.ts
  src/utils/sentry.ts
  src/views/NotFound.tsx
  yarn.lock
Labels: size/L

#4511 fix: Make Boosted Apr calculation based on cake rewards apr
  src/views/Farms/components/FarmCard/FarmCard.tsx
  src/views/Farms/components/FarmTable/Apr.tsx
  src/views/Farms/components/FarmTable/FarmTable.tsx
  src/views/Farms/components/FarmTable/Row.tsx
  src/views/Farms/components/YieldBooster/components/BoostedApr.tsx
  src/views/Migration/components/MigrationStep2/NewFarm/index.tsx
Labels: size/M

#4521 fix(SubgraphHealth): marginBottom use safe area
  src/components/ScrollToTopButton/index.tsx
  src/components/SubgraphHealthIndicator/index.tsx
Labels: size/S

#4524 fix(sdk): module file path
  packages/swap-sdk/package.json
Labels: size/XS

#4527 fix: (farms): Earned not updated after harvest
  src/views/Farms/components/FarmCard/HarvestAction.tsx
  src/views/Farms/components/FarmTable/Actions/HarvestAction.tsx
Labels: size/S

#4525 chore(sdk): Publish version
  apps/bridge/components/Menu.tsx
  packages/swap-sdk/package.json
  yarn.lock
Labels: size/M

#4528 chore: Update stargate ui
  apps/bridge/components/stargate/config.ts
Labels: size/XS

#4519 fix: Set language to local storage only when response success
  packages/localization/src/Provider.tsx
Labels: size/S, automerge

#4482 feat(Swap&LimitOrder): Token pair share
  src/utils/replaceBrowserHistory.ts
  src/views/LimitOrders/index.tsx
  src/views/Swap/index.tsx
Labels: size/S

#4522 feat: List farm auction 28 winner
  src/config/constants/farms.ts
Labels: size/M

#4532 chore: Fix typo
  src/views/Farms/components/YieldBooster/hooks/useBoostMultiplier.ts
Labels: size/XS

#4537 feat(Famrs&Pools&NFTCollections): Use the same ToTop button
  src/components/ScrollToTopButton/ScrollToTopButtonV2.tsx
  src/views/Farms/Farms.tsx
  src/views/Farms/components/FarmTable/FarmTable.tsx
  src/views/Farms/components/FarmTable/Row.tsx
  src/views/Nft/market/Collection/Items/CollectionWrapper.tsx
  src/views/Pools/components/PoolsTable/PoolsTable.tsx
  src/views/Pools/index.tsx
  src/views/Pottery/index.tsx
Labels: size/M

#4526 chore: banner layout issue
  src/views/Home/components/Banners/LotteryBanner.tsx
  src/views/Home/components/Banners/MultipleBanner.tsx
  src/views/Home/components/Banners/PerpetualBanner.tsx
Labels: size/M

#4530 perf: use Cake pair price
  packages/swap-sdk/src/entities/pair.ts
  src/components/Menu/index.tsx
  src/hooks/useBUSDPrice.ts
  src/state/farms/hooks.ts
  src/state/farmsV1/hooks.ts
Labels: size/M

#4466 feat: SafepalWallet hide "Add to TrustWallet"
  packages/localization/src/config/translations.json
  packages/uikit/src/react-app-env.d.ts
  packages/uikit/src/widgets/WalletModal/ConnectModal.tsx
  src/components/AddToWallet/AddToWalletButton.tsx
  src/utils/wallet.ts
Labels: size/S

#4471 perf: (voting): Reduce calculations in voting
  src/views/Voting/helpers.ts
Labels: size/M

#4454 perf: Reduce gas estimate calls to on chain in remove liquidity
  src/views/RemoveLiquidity/index.tsx
Labels: size/M

#4461 perf: (pools): Reduce calculations by half when storing values to redux
  src/state/pools/fetchPools.ts
  src/state/pools/index.ts
Labels: size/M

#4464 feat: (liquidity): Add user readable error messages to zap
  src/views/AddLiquidity/components/ZapErrorMessage.tsx
  src/views/AddLiquidity/index.tsx
Labels: size/XS

#4465 perf: (farms): Reduce calculations when storing values to redux
  src/state/farms/index.ts
  src/views/Farms/components/YieldBooster/helpers/splitProxyFarms.ts
Labels: size/M

#3686 fix: (trading-competition): Crash when changing accounts, avoid flashing and set inital state statically
  src/views/TradingCompetition/EasterCompetition.tsx
  src/views/TradingCompetition/FanTokenCompetition.tsx
  src/views/TradingCompetition/MoDCompetition.tsx
  src/views/TradingCompetition/MoboxCompetition.tsx
  src/views/TradingCompetition/components/BattleCta/index.tsx
  src/views/TradingCompetition/easter/components/YourScore/EasterYourScore.tsx
  src/views/TradingCompetition/types.ts
Labels: size/L

#4484 perf: (info): Reduce calculations in info
  src/state/info/queries/helpers.ts
Labels: size/S

#4480 feat: (liquidity): Add lp rewards apr info to the first step of add liquidity
  src/views/AddLiquidity/ChoosePair.tsx
Labels: size/S

#4322 perf: (migration): Remove useTable hook from migration farm tables
  src/views/Migration/components/MigrationFarmTable.tsx
  src/views/Migration/components/MigrationStep1/OldFarm/FarmTable.tsx
  src/views/Migration/components/MigrationStep1/OldFarm/index.tsx
  src/views/Migration/components/MigrationStep2/NewFarm/FarmTable.tsx
  src/views/Migration/components/MigrationStep2/NewFarm/index.tsx
Labels: size/L

#4209 fix: Bet results history displayed decimal amount and make it configurable
  src/__tests__/views/predictions/components/History/helpers.test.ts
  src/__tests__/views/predictions/helpers.test.ts
  src/state/types.ts
  src/views/Predictions/components/History/BetResult.tsx
  src/views/Predictions/components/History/HistoricalBet.tsx
  src/views/Predictions/components/History/PnlTab/PnlTab.tsx
  src/views/Predictions/components/History/PnlTab/SummaryRow.tsx
  src/views/Predictions/components/History/helpers.ts
  src/views/Predictions/components/RoundCard/EnteredTag.tsx
  src/views/Predictions/components/RoundCard/LiveRoundCard.tsx
  src/views/Predictions/components/RoundCard/OpenRoundCard.tsx
  src/views/Predictions/components/RoundResult/RoundResultHistory.tsx
  src/views/Predictions/components/RoundResult/styles.tsx
  src/views/Predictions/context/config.ts
  src/views/Predictions/helpers.ts
Labels: size/L

#3610 fix: Swap modal doesn't show insufficient input token info after price change
  packages/localization/src/config/translations.json
  src/views/Swap/components/ConfirmSwapModal.tsx
  src/views/Swap/components/SwapModalFooter.tsx
  src/views/Swap/components/SwapModalHeader.tsx
  src/views/Swap/index.tsx
Labels: size/L

#4514 fix: Handle chainId accurately
  package.json
  packages/localization/src/config/translations.json
  packages/uikit/src/react-app-env.d.ts
  packages/uikit/src/widgets/Modal/styles.tsx
  public/images/check-your-network.png
  public/images/decorations/3d-pan-bunny.png
  src/components/CommitButton.tsx
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/components/ErrorBoundary/SentryErrorBoundary.tsx
  src/components/ErrorBoundary/index.ts
  src/components/Logo/ChainLogo.tsx
  src/components/Menu/GlobalSettings/SettingsModal.tsx
  src/components/Menu/UserMenu/WalletInfo.tsx
  src/components/Menu/UserMenu/index.tsx
  src/components/Menu/config/config.ts
  src/components/Menu/index.tsx
  src/components/NetworkModal/NetworkModal.tsx
  src/components/NetworkModal/PageNetworkSupportModal.tsx
  src/components/NetworkModal/UnsupportedNetworkModal.tsx
  src/components/NetworkModal/WrongNetworkModal.tsx
  src/components/NetworkModal/index.ts
  src/components/NetworkSupportModal/index.ts
  src/components/NetworkSwitcher.tsx
  src/config/constants/supportChains.ts
  src/global.d.ts
  src/hooks/useAccountEventListener.ts
  src/hooks/useActiveChainId.ts
  src/hooks/useActiveWeb3React.ts
  src/hooks/useAuth.tsx
  src/hooks/useProviderOrSigner.ts
  src/hooks/useSessionChainId.ts
  src/hooks/useSwitchNetwork.ts
  src/hooks/useSwitchNetworkLoading.ts
  src/pages/404.tsx
  src/pages/451.tsx
  src/pages/_app.tsx
  src/pages/add/[[...currency]].tsx
  src/pages/find.tsx
  src/pages/index.tsx
  src/pages/liquidity.tsx
  src/pages/remove/[[...currency]].tsx
  src/pages/swap.tsx
  src/state/pools/index.ts
  src/utils/exchange.ts
  src/utils/wagmi.ts
  src/views/AddLiquidity/index.tsx
  src/views/Home/components/FarmsPoolsRow/index.tsx
  src/views/Home/hooks/useGetTopFarmsByApr.tsx
  src/views/Home/hooks/useGetTopPoolsByApr.tsx
  src/views/Home/index.tsx
  src/views/Predictions/components/LabelPrice.tsx
  src/views/Predictions/components/RoundCard/LiveRoundPrice.tsx
  src/views/Swap/index.tsx
  yarn.lock
Labels: size/XL

#4539 feat(LimitOrder): add translation
  packages/localization/src/config/translations.json
  src/state/limitOrders/hooks.ts
  src/views/LimitOrders/components/LimitOrderPrice.tsx
Labels: size/S

#4542 revert: Revert "perf: (migration): Remove useTable hook from migration farm tables"
  src/views/Migration/components/MigrationFarmTable.tsx
  src/views/Migration/components/MigrationStep1/OldFarm/FarmTable.tsx
  src/views/Migration/components/MigrationStep1/OldFarm/index.tsx
  src/views/Migration/components/MigrationStep2/NewFarm/FarmTable.tsx
  src/views/Migration/components/MigrationStep2/NewFarm/index.tsx
Labels: size/L

#4540 feat: List SFUND
  public/images/tokens/0x477bC8d23c634C154061869478bce96BE6045D12.png
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
Labels: size/M

#4548 fix(NFTMarketplace&Profile): Fix subMenu active status
  packages/uikit/src/components/SubMenuItems/SubMenuItems.tsx
  src/views/Nft/market/Collection/Header.tsx
Labels: size/XS

#4551 feat(LimitIOrder): Improve "never executes" desc
  packages/localization/src/config/translations.json
  src/views/LimitOrders/components/LimitOrderPrice.tsx
Labels: size/S, automerge

#4550 fix: SUGGESTED_BASES when chainId is not supported
  src/components/SearchModal/CommonBases.tsx
Labels: size/XS

#4552 fix(Wallet): SafePal no show "Add to Wallet"
  src/components/AddToWallet/AddToWalletButton.tsx
  src/utils/wallet.ts
Labels: size/M

#4555 fix(Prediction): Fix Leaderboard sort
  src/views/Predictions/Leaderboard/components/Filters/index.tsx
Labels: size/XS

#4549 feat: Support on action
  src/utils/mpBridge.ts
Labels: size/S

#4554 fix: (farms): Farms userdata reset after harvest until next fetch
  src/state/farms/index.ts
Labels: size/XS

#4558 chore(bridge): Update title
  apps/bridge/components/stargate/index.tsx
Labels: size/XS

#4546 fix(wallet): Unsupported Switch network flow
  packages/localization/src/config/translations.json
  packages/wagmi/src/connectors/bscConnector.ts
  src/components/Menu/UserMenu/WalletWrongNetwork.tsx
  src/components/NetworkModal/NetworkModal.tsx
  src/components/NetworkModal/PageNetworkSupportModal.tsx
  src/components/NetworkModal/UnsupportedNetworkModal.tsx
  src/components/NetworkModal/WrongNetworkModal.tsx
  src/components/NetworkSwitcher.tsx
  src/hooks/useAuth.tsx
  src/hooks/useSwitchNetwork.ts
  src/views/AddLiquidity/index.tsx
  src/views/RemoveLiquidity/index.tsx
Labels: size/L

#4560 fix(exchange): Prevent crash when price denominator is 0
  src/utils/prices.ts
Labels: size/XS

#4561 chore: Add bridge link
  packages/localization/src/config/translations.json
  src/components/Menu/config/config.ts
Labels: size/S

#4556 feat: List WOM IFO
  public/images/achievements/ifo-wom.svg
  public/images/ifos/wom-bg.png
  public/images/tokens/0xAD6742A35fB341A9Cc6ad674738Dd8da98b94Fb1.png
  src/config/constants/campaigns.ts
  src/config/constants/ifo.ts
  src/config/constants/tokens.ts
Labels: size/M
