Repository pancakeswap/pancake-frontend, pull requests merged in 2022-11, with the labels that each got.

#5154 chore(aptos): Add liquidity error log
  apps/aptos/components/Liquidity/hooks/useAddLiquidityHandler.ts
Labels: size/XS

#5158 chore(awgmi): Update blocto sdk
  .changeset/new-hairs-complain.md
  apps/aptos/client.ts
  packages/awgmi/core/src/connectors/blocto.ts
  packages/awgmi/package.json
  yarn.lock
Labels: size/S

#5157 feat(aptos): Add SafePal connector
  .changeset/blue-eyes-begin.md
  apps/aptos/client.ts
  apps/aptos/config/wallets.ts
  packages/awgmi/connectors/safePal/package.json
  packages/awgmi/core/src/connectors/martian.ts
  packages/awgmi/core/src/connectors/safePal.ts
  packages/awgmi/package.json
  packages/awgmi/tsup.config.ts
Labels: size/L

#5162 fix: changeset ignore pkg
  .changeset/blue-eyes-begin.md
  .changeset/new-hairs-complain.md
Labels: size/XS

#5156 fix: Update lp apr workflow
  package.json
  scripts/updateLPsAPR.ts
Labels: size/S

#5161 fix: (info): Pools data fetch
  apps/web/src/state/info/queries/helpers.ts
  apps/web/src/state/info/queries/pools/poolData.ts
  apps/web/src/state/info/queries/pools/transactions.ts
  apps/web/src/state/info/queries/types.ts
Labels: size/L

#5146 refactor: (swap): Use context for swap supported feature instead of props
  apps/web/src/pages/swap.tsx
  apps/web/src/views/Swap/StableSwap/components/StableSwapForm.tsx
  apps/web/src/views/Swap/StableSwap/index.tsx
  apps/web/src/views/Swap/SwapFeaturesContext.tsx
  apps/web/src/views/Swap/components/CurrencyInputHeader.tsx
  apps/web/src/views/Swap/components/SwapForm.tsx
  apps/web/src/views/Swap/components/SwapTab.tsx
  apps/web/src/views/Swap/index.tsx
Labels: size/L

#5141 fix(Farms): Fix ROICalculator Base APR
  packages/uikit/src/components/RoiCalculatorModal/RoiCalculatorFooter.tsx
Labels: size/M

#5167 feat: Update default og image
  apps/aptos/components/Layout/ExchangeLayout.tsx
  apps/aptos/next-seo.config.ts
  apps/aptos/public/images/hero.png
  apps/web/public/images/hero.png
Labels: size/XS

#5168 fix(awgmi): Add Fewcha tx options
  .changeset/wise-islands-protect.md
  packages/awgmi/core/src/connectors/fewcha.ts
Labels: size/S

#5170 fix(awgmi): Consolidate Fewcha error
  .changeset/new-fans-pull.md
  packages/awgmi/core/src/connectors/fewcha.ts
Labels: size/S

#5127 chore: New Crowdin updates
  apps/web/public/locales/ar-SA.json
  apps/web/public/locales/bn-BD.json
  apps/web/public/locales/el-GR.json
  apps/web/public/locales/fil-PH.json
  apps/web/public/locales/hi-IN.json
  apps/web/public/locales/id-ID.json
  apps/web/public/locales/it-IT.json
  apps/web/public/locales/nl-NL.json
  apps/web/public/locales/ru-RU.json
  apps/web/public/locales/zh-CN.json
  apps/web/public/locales/zh-TW.json
Labels: size/L

#5166 fix: Update Lp apr workflow format command
  .github/workflows/updateLPsAPR.yml
Labels: size/XS

#5174 chore: Add swap token log
  apps/web/src/hooks/useSwapCallback.ts
  apps/web/src/utils/log.ts
Labels: size/M

#5164 refactor(Pool): Move Apr to widget
  apps/web/src/views/Pools/components/Apr.tsx
  apps/web/src/views/Pools/components/PoolCard/AprRow.tsx
  packages/uikit/src/widgets/Pool/Apr.tsx
  packages/uikit/src/widgets/Pool/AprRowWithToolTip.tsx
  packages/uikit/src/widgets/Pool/index.tsx
  packages/uikit/src/widgets/Pool/types.ts
Labels: size/L

#4994 feat: Bring back gas settings to bsc
  apps/web/src/components/Menu/GlobalSettings/GasSettings.tsx
  apps/web/src/components/Menu/GlobalSettings/SettingsModal.tsx
  apps/web/src/hooks/useApproveCallback.ts
  apps/web/src/hooks/useCakeApprove.tsx
  apps/web/src/hooks/useCallWithGasPrice.ts
  apps/web/src/hooks/useSwapCallback.ts
  apps/web/src/hooks/useWrapCallback.ts
  apps/web/src/state/types.ts
  apps/web/src/state/user/actions.ts
  apps/web/src/state/user/hooks/index.tsx
  apps/web/src/state/user/reducer.ts
  apps/web/src/utils/calls/farms.ts
  apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
  apps/web/src/views/AddLiquidity/index.tsx
  apps/web/src/views/FarmAuction/components/PlaceBidModal.tsx
  apps/web/src/views/FarmAuction/components/ReclaimBidCard.tsx
  apps/web/src/views/Farms/components/YieldBooster/hooks/useBoosterFarmHandlers.ts
  apps/web/src/views/Farms/components/YieldBooster/hooks/useProxyStakedActions.ts
  apps/web/src/views/Farms/hooks/useApproveFarm.ts
  apps/web/src/views/Farms/hooks/useHarvestFarm.ts
  apps/web/src/views/Farms/hooks/useStakeFarms.ts
  apps/web/src/views/Farms/hooks/useUnstakeFarms.ts
  apps/web/src/views/Home/components/UserBanner/HarvestCard.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx
  apps/web/src/views/Ifos/hooks/useIfoApprove.ts
  apps/web/src/views/Lottery/components/BuyTicketsModal/BuyTicketsModal.tsx
  apps/web/src/views/Lottery/components/ClaimPrizesModal/ClaimPrizesInner.tsx
  apps/web/src/views/Migration/components/MigrationStep1/OldPool/UnstakeButton.tsx
  apps/web/src/views/Migration/hook/V1/Farms/useUnstakeFarms.ts
  apps/web/src/views/Migration/hook/V1/Pool/useUnstakePool.ts
  apps/web/src/views/Nft/market/components/BuySellModals/BuyModal/index.tsx
  apps/web/src/views/Nft/market/components/BuySellModals/SellModal/index.tsx
  apps/web/src/views/PancakeSquad/components/Buttons/BuyTickets.tsx
  apps/web/src/views/PancakeSquad/components/Buttons/Mint.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
  apps/web/src/views/Pools/components/LockedPool/Buttons/ConvertToFlexibleButton.tsx
  apps/web/src/views/Pools/components/LockedPool/hooks/useLockedPool.tsx
  apps/web/src/views/Pools/hooks/useApprove.tsx
  apps/web/src/views/Pools/hooks/useHarvestPool.ts
  apps/web/src/views/Pools/hooks/useStakePool.ts
  apps/web/src/views/Pools/hooks/useUnstakePool.ts
  apps/web/src/views/Pottery/hooks/useApprovePottery.tsx
  apps/web/src/views/Predictions/components/CollectRoundWinningsModal.tsx
  apps/web/src/views/Predictions/components/ReclaimPositionButton.tsx
  apps/web/src/views/Predictions/components/RoundCard/SetPositionCard.tsx
  apps/web/src/views/Profile/components/Achievements/AchievementRow/index.tsx
  apps/web/src/views/Profile/components/EditProfileModal/ChangeProfilePicView.tsx
  apps/web/src/views/Profile/components/EditProfileModal/PauseProfileView.tsx
  apps/web/src/views/ProfileCreation/ConfirmProfileCreationModal.tsx
  apps/web/src/views/ProfileCreation/Mint.tsx
  apps/web/src/views/ProfileCreation/ProfilePicture.tsx
  apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/index.tsx
  apps/web/src/views/TradingCompetition/components/ClaimModal/index.tsx
  apps/web/src/views/TradingCompetition/components/RegisterModal/RegisterWithProfile.tsx
  packages/localization/src/config/translations.json
Labels: size/XL

#4807 fix: (import-row): Use token's chainid instead of globals
  apps/web/src/components/SearchModal/ImportRow.tsx
  apps/web/src/components/SearchModal/ImportToken.tsx
Labels: size/S

#5012 fix: (swap): Url construction wrong when output token selected as input token and vice versa
  apps/web/src/views/LimitOrders/index.tsx
  apps/web/src/views/Swap/StableSwap/components/StableSwapForm.tsx
  apps/web/src/views/Swap/components/SwapForm.tsx
Labels: size/M

#4637 perf: (info): Don't process info search component to add to dom when show menu is false
  apps/web/src/views/Info/components/InfoSearch/index.tsx
Labels: size/L

#4931 fix: Default liquidity tokens not loaded intermittently when changing network
  apps/web/src/hooks/useActiveWeb3React.ts
Labels: size/S

#5177 refactor: Remove unnecessary data fetch in useLpApr hook
  apps/web/src/state/swap/useLPApr.ts
Labels: size/M

#4788 perf: (nft): Don't use object entries to reduce memory footprint
  apps/web/src/state/nftMarket/helpers.ts
  apps/web/src/views/Nft/market/hooks/useGetCollectionDistribution.tsx
Labels: size/S

#5173 fix(uikit): Modalv2 unmount animation
  apps/web/src/hooks/useAccountEventListener.ts
  apps/web/src/hooks/useAuth.tsx
  apps/web/src/utils/clearUserStates.ts
  packages/uikit/package.json
  packages/uikit/src/__tests__/widgets/walletModal.test.tsx
  packages/uikit/src/index.ts
  packages/uikit/src/widgets/Modal/ModalV2.tsx
  packages/uikit/src/widgets/WalletModal/ConnectModal.tsx
  packages/uikit/src/widgets/WalletModal/CopyToClipboard.tsx
  packages/uikit/src/widgets/WalletModal/WalletCard.tsx
  packages/uikit/src/widgets/WalletModal/config.tsx
  packages/uikit/src/widgets/WalletModal/index.stories.tsx
  packages/uikit/src/widgets/WalletModal/index.tsx
  packages/uikit/src/widgets/WalletModal/types.ts
  packages/uikit/src/widgets/WalletModal/useWalletModal.tsx
Labels: size/XL

#5171 ci: Run cypress only changes
  .changeset/config.json
  .github/workflows/integrationTests.yml
  apps/e2e/cypress.json
  apps/e2e/cypress/.eslintrc
  apps/e2e/cypress/integration/exchange/add-liquidity.test.ts
  apps/e2e/cypress/integration/exchange/liquidity.test.ts
  apps/e2e/cypress/integration/exchange/lists.test.ts
  apps/e2e/cypress/integration/exchange/remove-liquidity.test.ts
  apps/e2e/cypress/integration/exchange/send.test.ts
  apps/e2e/cypress/integration/exchange/swap.test.ts
  apps/e2e/cypress/integration/farms/farms.test.ts
  apps/e2e/cypress/integration/home/home.test.ts
  apps/e2e/cypress/integration/ifo/ifo.test.ts
  apps/e2e/cypress/integration/info/info.test.ts
  apps/e2e/cypress/integration/lottery/lottery.test.ts
  apps/e2e/cypress/integration/nfts/nfts.test.ts
  apps/e2e/cypress/integration/pools/pools.test.ts
  apps/e2e/cypress/integration/predictions/predictions.test.ts
  apps/e2e/cypress/integration/teamsAndProfile/leaderboard.test.ts
  apps/e2e/cypress/integration/teamsAndProfile/profile.test.ts
  apps/e2e/cypress/integration/tradingCompetition/tradingCompetition.test.ts
  apps/e2e/cypress/integration/voting/voting.test.ts
  apps/e2e/cypress/support/commands.js
  apps/e2e/cypress/support/index.d.ts
  apps/e2e/cypress/support/index.js
  apps/e2e/cypress/tsconfig.json
  apps/e2e/package.json
  apps/test/package.json
  doc/Cypress.md
  package.json
  turbo.json
Labels: size/M

#5178 refactor: Sentry log for call with gas price hook
  apps/web/src/hooks/useCallWithGasPrice.ts
  apps/web/src/state/user/hooks/index.tsx
Labels: size/S

#5180 chore: Remove warnings
  apps/web/src/hooks/useSwapCallback.ts
  apps/web/src/utils/calls/farms.ts
  apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
  apps/web/src/views/AddLiquidity/index.tsx
  apps/web/src/views/Migration/hook/V1/Farms/useUnstakeFarms.ts
  apps/web/src/views/Migration/hook/V1/Pool/useUnstakePool.ts
  apps/web/src/views/Pools/hooks/useHarvestPool.ts
  apps/web/src/views/Pools/hooks/useStakePool.ts
  apps/web/src/views/Pools/hooks/useUnstakePool.ts
  apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/index.tsx
Labels: size/S

#5183 fix(TradingCompetition): Fix TeamRanks section UI
  apps/web/src/views/TradingCompetition/MoDCompetition.tsx
  apps/web/src/views/TradingCompetition/MoboxCompetition.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanksSection.tsx
Labels: size/XS

#4993 feat: (homepage): Bring back username visibility toggle
  apps/web/src/components/Menu/GlobalSettings/SettingsModal.tsx
  apps/web/src/hooks/useUsernameWithVisibility.ts
  apps/web/src/views/Home/components/UserBanner/UserDetail.tsx
  apps/web/src/views/Profile/components/ProfileHeader.tsx
  apps/web/src/views/TradingCompetition/components/RegisterModal/RegisterWithProfile.tsx
  apps/web/src/views/TradingCompetition/components/YourScore/CardUserInfo.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#5184 fix(stableswap): Update APR formular
  scripts/updateLPsAPR.ts
Labels: size/XS

#5186 fix(aptos): Add useAuth return
  apps/aptos/hooks/useAuth.ts
Labels: size/XS

#5185 fix(aptos): Avoid using account resources to get all pair reserves
  apps/aptos/hooks/usePairs.ts
  packages/awgmi/src/index.ts
Labels: size/L

#5188 feat(aptos): Add Celer usdc as trade base
  apps/aptos/config/coins.ts
  apps/aptos/config/constants/exchange.ts
Labels: size/S

#5191 perf: Use active chain hook directly
  apps/web/src/components/Menu/hooks/useMenuItems.ts
  apps/web/src/components/SearchModal/CurrencyList.tsx
  apps/web/src/components/SearchModal/CurrencySearch.tsx
  apps/web/src/components/SearchModal/ImportToken.tsx
  apps/web/src/components/SearchModal/ManageLists.tsx
  apps/web/src/components/SearchModal/ManageTokens.tsx
  apps/web/src/components/Toast/DescriptionWithTx.tsx
  apps/web/src/components/TransactionConfirmationModal/index.tsx
  apps/web/src/components/UnsupportedCurrencyFooter.tsx
  apps/web/src/hooks/Tokens.ts
  apps/web/src/hooks/Trades.ts
  apps/web/src/hooks/limitOrders/useGasOverhead.ts
  apps/web/src/hooks/limitOrders/useGelatoLimitOrdersLib.ts
  apps/web/src/hooks/useActiveWeb3React.ts
  apps/web/src/hooks/useBUSDPrice.ts
  apps/web/src/hooks/useContract.ts
  apps/web/src/hooks/useNativeCurrency.ts
  apps/web/src/hooks/usePairs.ts
  apps/web/src/hooks/useRefreshEffect.ts
  apps/web/src/pages/add/[[...currency]].tsx
  apps/web/src/state/block/hooks.ts
  apps/web/src/state/farms/hooks.ts
  apps/web/src/state/limitOrders/hooks.ts
  apps/web/src/state/multicall/hooks.ts
  apps/web/src/state/multicall/updater.tsx
  apps/web/src/state/pools/hooks.ts
  apps/web/src/state/swap/hooks.ts
  apps/web/src/state/transactions/hooks.tsx
  apps/web/src/state/user/hooks/index.tsx
  apps/web/src/state/user/hooks/useUserAddedTokens.ts
  apps/web/src/views/AddLiquidity/components/ConfirmZapInModal.tsx
  apps/web/src/views/Farms/Farms.tsx
  apps/web/src/views/Farms/components/FarmCard/FarmCard.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/Farms/components/FarmTable/Apr.tsx
  apps/web/src/views/Home/hooks/useGetTopFarmsByApr.tsx
  apps/web/src/views/Home/hooks/useGetTopPoolsByApr.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/Timer.tsx
  apps/web/src/views/Info/index.tsx
  apps/web/src/views/LimitOrders/components/ConfirmLimitOrderModal.tsx
  apps/web/src/views/LimitOrders/components/LimitOrderTable/DetailLimitOrderModal.tsx
  apps/web/src/views/LimitOrders/hooks/useFormattedOrderData.ts
  apps/web/src/views/Migration/hook/V1/Pool/useFetchUserPools.ts
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/shared/DetailsCard.tsx
  apps/web/src/views/Nft/market/components/Activity/ActivityRow.tsx
  apps/web/src/views/Nft/market/components/Activity/MobileModal.tsx
  apps/web/src/views/Nft/market/components/BuySellModals/shared/TransactionConfirmed.tsx
  apps/web/src/views/PancakeSquad/components/Modals/Confirm/index.tsx
  apps/web/src/views/Pottery/components/Pot/Deposit/DepositAction.tsx
  apps/web/src/views/Swap/StableSwap/hooks/useStableConfig.ts
  apps/web/src/views/Swap/SwapFeaturesContext.tsx
  apps/web/src/views/Swap/components/AddressInputPanel.tsx
  apps/web/src/views/Swap/components/ConfirmSwapModal.tsx
  apps/web/src/views/Swap/hooks/useRefreshBlockNumber.ts
Labels: size/L

#5192 fix: Ethereum farm apr
  apps/web/src/utils/apr.ts
Labels: size/XS

#5197 chore(gala): Add GALA warning
  apps/web/src/config/constants/swapWarningTokens.ts
  apps/web/src/config/constants/warningTokens.ts
  apps/web/src/views/Swap/components/SwapWarningModal/GalaWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/index.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#5198 chore: Gala warning text
  apps/web/src/views/Swap/components/SwapWarningModal/GalaWarning.tsx
  packages/localization/src/config/translations.json
Labels: size/XS, automerge

#5195 fix: Exchange chart height increases infinitely
  apps/web/src/views/Swap/components/Chart/BasicChart.tsx
Labels: size/XS

#5189 feat(Limit): Add scan risk
  apps/web/src/views/LimitOrders/index.tsx
Labels: size/S

#5200 fix(aptos): bnb logo
  apps/aptos/config/constants/tokenLists/pancake-default.tokenlist.json
Labels: size/M

#5201 chore(web): Add BraveWallet download link
  apps/web/src/config/wallet.ts
Labels: size/XS

#5202 chore: Port token image path changes to web
  apps/aptos/config/constants/tokenLists/pancake-default.tokenlist.json
  apps/web/src/config/constants/tokenLists/pancake-default.tokenlist.json
Labels: size/M

#5206 chore: Remove warning
  apps/web/src/views/LimitOrders/index.tsx
Labels: size/XS

#5175 feat: renew and after lock improvement
  apps/web/src/views/Pools/components/LockedPool/Buttons/ExtendDurationButton.tsx
  apps/web/src/views/Pools/components/LockedPool/Common/AfterLockedActions.tsx
  apps/web/src/views/Pools/components/LockedPool/Common/LockedModalBody.tsx
  apps/web/src/views/Pools/components/LockedPool/Modals/ExtendDurationModal.tsx
  apps/web/src/views/Pools/components/LockedPool/hooks/useAvgLockDuration.tsx
  apps/web/src/views/Pools/components/LockedPool/hooks/useLockedPool.tsx
  apps/web/src/views/Pools/components/LockedPool/types/index.ts
  packages/localization/src/config/translations.json
Labels: size/M

#5208 chore: Update LP APR with new end point locally
  apps/web/src/config/constants/lpAprs/1.json
  apps/web/src/config/constants/lpAprs/56.json
  apps/web/src/utils/apr.ts
Labels: size/L

#5211 fix: Farm deposit modal
  packages/uikit/src/widgets/Farm/components/DepositModal/index.tsx
Labels: size/XS, automerge

#5212 chore: Move arv to finished pools
  apps/web/src/config/constants/pools.tsx
Labels: size/S

#5218 chore(NetworkSwitcher): Change tooltip placement to bottom
  apps/web/src/components/NetworkSwitcher.tsx
Labels: size/XS

#5219 chore(aptos): Use jpeg for hero
  apps/aptos/next-seo.config.ts
  apps/aptos/public/images/hero.jpeg
Labels: size/XS

#5217 chore: update farm LP APR
  apps/web/src/config/constants/lpAprs/1.json
  apps/web/src/config/constants/lpAprs/56.json
Labels: size/L

#5190 feat(ScrollToTopButton): Move to _app.tsx
  apps/aptos/components/Farms/components/Farms.tsx
  apps/aptos/components/Pools/index.tsx
  apps/web/src/components/Menu/index.tsx
  apps/web/src/pages/_app.tsx
  apps/web/src/views/Farms/Farms.tsx
  apps/web/src/views/Nft/market/Collection/Items/CollectionWrapper.tsx
  apps/web/src/views/Pools/index.tsx
  apps/web/src/views/Pottery/index.tsx
Labels: size/M

#5224 feat: (pottery): Add skeleton to pottery prize when loading
  apps/web/src/views/Pottery/components/Banner/index.tsx
Labels: size/S

#5205 refactor: (ifo): Remove release block number
  apps/web/src/config/constants/ifo.ts
  apps/web/src/config/constants/types.ts
  apps/web/src/views/Ifos/hooks/v1/useGetPublicIfoData.ts
  apps/web/src/views/Ifos/hooks/v2/useGetPublicIfoData.ts
  apps/web/src/views/Ifos/hooks/v3/useGetPublicIfoData.ts
Labels: size/M

#5221 feat: smart router
  apps/web/next.config.mjs
  apps/web/package.json
  packages/smart-router/evm/abis/IPancakePair.json
  packages/smart-router/evm/abis/StableSwapPair.json
  packages/smart-router/evm/constants/common.ts
  packages/smart-router/evm/constants/exchange.ts
  packages/smart-router/evm/constants/index.ts
  packages/smart-router/evm/getAllCommonPairs.ts
  packages/smart-router/evm/getBestTradeFromV2.ts
  packages/smart-router/evm/getBestTradeWithStableSwap.ts
  packages/smart-router/evm/getStableSwapPairs.ts
  packages/smart-router/evm/index.ts
  packages/smart-router/evm/onchain/getPairs.ts
  packages/smart-router/evm/onchain/getStableSwapOutputAmount.ts
  packages/smart-router/evm/onchain/index.ts
  packages/smart-router/evm/package.json
  packages/smart-router/evm/stableSwap.ts
  packages/smart-router/evm/types/bestTrade.ts
  packages/smart-router/evm/types/chain.ts
  packages/smart-router/evm/types/index.ts
  packages/smart-router/evm/utils/currency.ts
  packages/smart-router/evm/utils/pair.ts
  packages/smart-router/evm/utils/trade.ts
  packages/smart-router/jest.config.js
  packages/smart-router/package.json
  packages/smart-router/tsconfig.json
  packages/smart-router/tsup.config.ts
  yarn.lock
Labels: size/XXL

#5226 fix(smart-router): minor setup fix for smart router pkg
  .changeset/config.json
  package.json
  packages/smart-router/evm/onchain/getPairs.ts
  packages/smart-router/evm/onchain/getStableSwapOutputAmount.ts
  packages/smart-router/package.json
  yarn.lock
Labels: size/XXL

#5228 fix: uncaught exception when making multicall to non existing address
  packages/multicall/index.ts
  packages/smart-router/evm/onchain/getPairs.ts
Labels: size/M

#5193 chore: Use default gas limit for pools, v1 farms and non-proxy farms
  apps/web/src/utils/calls/farms.ts
  apps/web/src/views/Farms/components/YieldBooster/hooks/useProxyStakedActions.ts
  apps/web/src/views/Migration/hook/V1/Farms/useUnstakeFarms.ts
  apps/web/src/views/Migration/hook/V1/Pool/useUnstakePool.ts
  apps/web/src/views/Pools/hooks/useHarvestPool.ts
  apps/web/src/views/Pools/hooks/useStakePool.ts
  apps/web/src/views/Pools/hooks/useUnstakePool.ts
Labels: size/M

#5153 feat(aptos-pools): Add Pools
  apps/aptos/components/Pools/components/PoolCard/Apr.tsx
  apps/aptos/components/Pools/components/PoolCard/AprRow.tsx
  apps/aptos/components/Pools/components/PoolCard/CakeCardActions.tsx
  apps/aptos/components/Pools/components/PoolCard/CakeCollectModal.tsx
  apps/aptos/components/Pools/components/PoolCard/CakeStakeModal.tsx
  apps/aptos/components/Pools/components/PoolCard/CardActions.tsx
  apps/aptos/components/Pools/components/PoolCard/CardFooter.tsx
  apps/aptos/components/Pools/components/PoolCard/CollectModal.tsx
  apps/aptos/components/Pools/components/PoolCard/CollectModalContainer.tsx
  apps/aptos/components/Pools/components/PoolCard/HarvestActions.tsx
  apps/aptos/components/Pools/components/PoolCard/PoolCardHeader.tsx
  apps/aptos/components/Pools/components/PoolCard/PoolStatsInfo.tsx
  apps/aptos/components/Pools/components/PoolCard/StakeActions.tsx
  apps/aptos/components/Pools/components/PoolCard/StakeModal.tsx
  apps/aptos/components/Pools/components/PoolCard/StakeModalContainer.tsx
  apps/aptos/components/Pools/components/PoolCard/Stat.tsx
  apps/aptos/components/Pools/components/PoolCard/StyledCard.tsx
  apps/aptos/components/Pools/components/PoolCard/index.tsx
  apps/aptos/components/Pools/components/PoolControls.tsx
  apps/aptos/components/Pools/components/PoolTabButtons.tsx
  apps/aptos/components/Pools/constants.ts
  apps/aptos/components/Pools/hooks/useHarvestPool.ts
  apps/aptos/components/Pools/hooks/usePoolsList.ts
  apps/aptos/components/Pools/hooks/useStakePool.ts
  apps/aptos/components/Pools/hooks/useUnstakePool.ts
  apps/aptos/components/Pools/index.tsx
  apps/aptos/components/Pools/transformers/transformCakePool.ts
  apps/aptos/components/Pools/transformers/transformPool.ts
  apps/aptos/components/Pools/types.ts
  apps/aptos/components/Pools/utils/cakePoolRelatedQueries.ts
  apps/aptos/components/Pools/utils/convertFarmsWithPriceIntoUSD.ts
  apps/aptos/components/Pools/utils/getFarmTokenPerSecond.ts
  apps/aptos/components/Pools/utils/getSecondsLeftFromNow.ts
  apps/aptos/components/Pools/utils/getTokenByAddress.ts
  apps/aptos/components/Pools/utils/poolRelatedQueries.ts
  apps/aptos/components/Pools/utils/splitTypeTag.ts
  apps/aptos/config/constants/farms/2.ts
  apps/aptos/config/constants/tokens/2.ts
  apps/aptos/contracts/generated/smartchef.ts
  apps/aptos/contracts/smartchef/constants.ts
  apps/aptos/contracts/smartchef/index.ts
  apps/aptos/hooks/useCatchTxError.tsx
  apps/aptos/state/farms/hook.ts
  apps/aptos/state/pools/constants.ts
  apps/aptos/state/pools/fetchPools.ts
  apps/aptos/state/pools/hooks.ts
  apps/aptos/state/pools/syrup.ts
  apps/aptos/state/pools/types.ts
  apps/aptos/state/pools/utils.ts
  packages/uikit/src/components/RoiCalculatorModal/RoiCalculatorFooter.tsx
  packages/uikit/src/widgets/Pool/CollectModal.tsx
  packages/uikit/src/widgets/Pool/index.tsx
  packages/uikit/src/widgets/Pool/types.ts
  packages/uikit/src/widgets/Pool/withCardActions.tsx
  packages/uikit/src/widgets/Pool/withCollectModal.tsx
Labels: size/XXL

#5229 fix: use own stable swap pool config instead of depending on farms
  packages/smart-router/evm/constants/stableSwap/1.ts
  packages/smart-router/evm/constants/stableSwap/4.ts
  packages/smart-router/evm/constants/stableSwap/5.ts
  packages/smart-router/evm/constants/stableSwap/56.ts
  packages/smart-router/evm/constants/stableSwap/97.ts
  packages/smart-router/evm/constants/stableSwap/index.ts
  packages/smart-router/evm/constants/stableSwap/pools.ts
  packages/smart-router/evm/getStableSwapPairs.ts
  packages/smart-router/evm/index.ts
  packages/smart-router/evm/types/pool.ts
  packages/smart-router/package.json
Labels: size/M

#5223 perf: (exchange): Reduce multicall computations in token&currency balance calls
  apps/web/src/state/burn/hooks.ts
  apps/web/src/state/limitOrders/hooks.ts
  apps/web/src/state/mint/hooks.ts
  apps/web/src/state/swap/hooks.ts
  apps/web/src/state/wallet/hooks.ts
  apps/web/src/views/AddLiquidity/AddStableLiquidity/hooks/useStableLPDerivedMintInfo.tsx
  apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/hooks/useStableDerivedBurnInfo.ts
  apps/web/src/views/Swap/StableSwap/hooks/useDerivedStableSwapInfo.ts
Labels: size/M

#5222 chore(Pottery): FAQ answer content style
  apps/web/src/views/Pottery/components/FAQ.tsx
Labels: size/XS

#5230 fix: recalculate Popover position for user menu
  apps/web/src/views/Info/components/InfoNav/index.tsx
  packages/uikit/src/widgets/Menu/components/UserMenu/index.tsx
  packages/uikit/src/widgets/Menu/components/UserMenu/types.ts
Labels: size/S

#5231 feat(aptos): Add trust wallet asset logo
  apps/aptos/components/Logo/CurrencyLogo.tsx
  package.json
Labels: size/S

#5237 fix: (voting): Crash when voting power details open when in cast vote modal while casting vote
  apps/web/src/views/Voting/components/CastVoteModal/index.tsx
  apps/web/src/views/Voting/components/VoteDetailsModal.tsx
  apps/web/src/views/Voting/hooks/useGetVotingPower.tsx
Labels: size/M

#5236 chore: Update CAKE address
  apps/aptos/components/Pools/components/PoolCard/CakeCollectModal.tsx
  apps/aptos/components/Pools/components/PoolCard/CakeStakeModal.tsx
  apps/aptos/components/Pools/components/PoolControls.tsx
  apps/aptos/components/Pools/constants.ts
  apps/aptos/components/Pools/hooks/usePoolsList.ts
  apps/aptos/components/Pools/index.tsx
  apps/aptos/components/Pools/transformers/transformPool.ts
  apps/aptos/config/constants/farms/2.ts
  apps/aptos/config/constants/index.ts
  apps/aptos/config/constants/tokens/2.ts
  apps/aptos/state/farms/hook.ts
  packages/uikit/src/widgets/Modal/NotEnoughTokensModal.tsx
  packages/uikit/src/widgets/Pool/PoolControls.tsx
  packages/uikit/src/widgets/Pool/PoolTabButtons.tsx
  packages/uikit/src/widgets/Pool/withCardActions.tsx
  packages/uikit/src/widgets/Pool/withStakeActions.tsx
Labels: size/M

#5232 chore: update farm LP APR
  apps/web/src/config/constants/lpAprs/1.json
  apps/web/src/config/constants/lpAprs/56.json
Labels: size/L

#5235 perf: Memoize getLpAddress
  apps/web/src/utils/getLpAddress.ts
Labels: size/M

#5238 refactor(pool): Move PoolTable into widget
  apps/aptos/components/Pools/index.tsx
  apps/aptos/components/Pools/transformers/transformPool.ts
  apps/web/src/views/Pools/components/PoolsTable/PoolsTable.tsx
  apps/web/src/views/Pools/index.tsx
  packages/uikit/src/widgets/Pool/PoolsTable/index.tsx
  packages/uikit/src/widgets/Pool/index.tsx
Labels: size/L

#5241 chore: Add safe guard to avoid undefined error
  apps/aptos/components/Pools/hooks/usePoolsList.ts
  apps/aptos/components/Pools/transformers/transformCakePool.ts
Labels: size/S

#5240 feat: add support for exact output
  packages/smart-router/evm/getBestTradeFromV2.ts
  packages/smart-router/evm/getBestTradeWithStableSwap.ts
  packages/smart-router/evm/index.ts
  packages/smart-router/evm/stableSwap.ts
  packages/smart-router/evm/types/index.ts
  packages/smart-router/evm/types/stableSwap.ts
Labels: size/L

#5242 feat(awgmi): Catch more wallets user reject error
  .changeset/pretty-mails-trade.md
  packages/awgmi/README.md
  packages/awgmi/core/src/accounts/signMessage.ts
  packages/awgmi/core/src/client.ts
  packages/awgmi/core/src/connectors/blocto.ts
  packages/awgmi/core/src/connectors/martian.ts
  packages/awgmi/core/src/connectors/pontem.ts
  packages/awgmi/core/src/errors.ts
  packages/awgmi/core/src/transactions/sendTransaction.ts
  packages/awgmi/core/src/transactions/simulateTransaction.ts
  packages/awgmi/package.json
  packages/awgmi/src/index.ts
Labels: size/L

#5246 chore: update auction whitelist
  apps/web/src/config/constants/farmAuctions.ts
Labels: size/S

#5247 feat: list XCAD farms and pools
  apps/web/src/config/constants/pools.tsx
  packages/farms/constants/56.ts
Labels: size/S

#5245 refactor: clarify stable swap related types
  packages/smart-router/evm/stableSwap.ts
  packages/smart-router/evm/types/stableSwap.ts
  packages/smart-router/evm/utils/pair.ts
Labels: size/M

#5248 chore: add changeset for previous api update
  .changeset/orange-olives-search.md
Labels: size/XS

#5250 fix: (pools): All pools shown
  apps/web/src/views/Pools/index.tsx
Labels: size/XS

#5249 fix: (farms): LP Apr's not visible on some farms
  packages/farms/constants/56.ts
Labels: size/M

#5243 fix: Aptos pool staking balance
  apps/aptos/components/Pools/transformers/transformPool.ts
Labels: size/S

#5252 chore(FA): Change DEXT FA wallet address
  apps/web/src/config/constants/farmAuctions.ts
Labels: automerge

#5253 chore(FA): Revert DEXT wallet address
  apps/web/src/config/constants/farmAuctions.ts
Labels: size/XS, automerge

#5255 chore(aptos-pool): Update earning per 10 seconds
  apps/aptos/components/Pools/constants.ts
  apps/aptos/components/Pools/hooks/usePoolsList.ts
Labels: size/S

#5254 perf(Aptos): Not show error when user rejected
  apps/aptos/hooks/useCatchTxError.tsx
Labels: size/S

#5260 fix(Aptos): Low native balance warning
  apps/aptos/components/Menu/UserMenu.tsx
  apps/aptos/components/Menu/WalletModal.tsx
Labels: size/XS, automerge

#5261 feat: Add route type to identify trade with stable swap
  .changeset/short-fishes-smash.md
  packages/smart-router/evm/getBestTrade.ts
  packages/smart-router/evm/getBestTradeWithStableSwap.ts
  packages/smart-router/evm/index.ts
  packages/smart-router/evm/stableSwap.ts
  packages/smart-router/evm/types/bestTrade.ts
  packages/smart-router/evm/types/stableSwap.ts
Labels: size/L

#5213 feat(wagmi): Add blocto connector
  .changeset/warm-schools-agree.md
  apps/web/jest.config.js
  apps/web/src/components/DisclaimerModal/index.tsx
  apps/web/src/config/wallet.ts
  apps/web/src/utils/wagmi.ts
  apps/web/src/views/Farms/components/FarmCard/StakeAction.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
  apps/web/src/views/Farms/index.tsx
  packages/localization/src/config/translations.json
  packages/wagmi/connectors/blocto/blocto.ts
  packages/wagmi/connectors/blocto/index.ts
  packages/wagmi/connectors/blocto/package.json
  packages/wagmi/package.json
  packages/wagmi/tsup.config.ts
Labels: size/L

#5214 feat: (wallet): Show wnative token balance in wallet info modal if exist
  apps/web/src/components/Menu/UserMenu/WalletInfo.tsx
Labels: size/M

#5264 chore: update farm LP APR
  apps/web/src/config/constants/lpAprs/1.json
  apps/web/src/config/constants/lpAprs/56.json
Labels: size/L

#5268 chore: Release multicall
  .changeset/rotten-buttons-love.md
  .changeset/tiny-radios-brush.md
  packages/multicall/index.ts
  packages/multicall/package.json
  packages/multicall/tsconfig.json
  packages/multicall/tsup.config.ts
  packages/smart-router/evm/types/pool.ts
  packages/smart-router/package.json
  packages/smart-router/tsup.config.ts
  packages/token-lists/package.json
  packages/tokens/package.json
Labels: size/M, automerge

#5266 chore: Add networkname dependency
  apps/aptos/components/Pools/hooks/useAddressPriceMap.ts
  apps/aptos/components/Pools/hooks/usePoolsList.ts
  apps/aptos/components/Pools/transformers/transformPool.ts
  apps/aptos/components/Pools/utils/convertFarmsWithPriceIntoUSD.ts
  apps/aptos/pages/swap.tsx
  packages/uikit/src/components/RoiCalculatorModal/RoiCalculatorModal.tsx
  packages/uikit/src/widgets/Pool/Apr.tsx
  packages/uikit/src/widgets/Pool/StakeModal.tsx
Labels: size/L

#5271 chore: patch sdk version to rebuild the package
  .changeset/chatty-pigs-scream.md
Labels: size/XS

#5270 feat(token-lists): PancakeSwap version spec
  .changeset/honest-mirrors-tell.md
  apps/aptos/components/SearchModal/CurrencySearchModal.tsx
  apps/aptos/components/SearchModal/ImportList.tsx
  apps/aptos/components/SearchModal/Manage.tsx
  apps/aptos/components/SearchModal/ManageLists.tsx
  apps/aptos/components/SearchModal/filtering.ts
  apps/aptos/config/constants/tokenLists/pancake-default.tokenlist.json
  apps/aptos/state/lists/hooks.ts
  apps/aptos/state/lists/index.ts
  apps/aptos/state/lists/updater.tsx
  apps/web/package.json
  apps/web/src/components/SearchModal/CurrencySearchModal.tsx
  apps/web/src/components/SearchModal/ImportList.tsx
  apps/web/src/components/SearchModal/Manage.tsx
  apps/web/src/components/SearchModal/ManageLists.tsx
  apps/web/src/components/SearchModal/filtering.ts
  apps/web/src/state/lists/hooks.ts
  apps/web/src/state/lists/lists.ts
  apps/web/src/state/lists/updater.ts
  apps/web/src/views/Voting/components/VoteDetailsModal.tsx
  packages/token-lists/package.json
  packages/token-lists/react/actions.ts
  packages/token-lists/react/getTokenList.ts
  packages/token-lists/react/index.ts
  packages/token-lists/react/lists.ts
  packages/token-lists/react/package.json
  packages/token-lists/react/reducer.test.ts
  packages/token-lists/react/reducer.ts
  packages/token-lists/react/useFetchListCallback.ts
  packages/token-lists/schema/pancakeswap.json
  packages/token-lists/schema/uniswap.json
  packages/token-lists/src/getVersionUpgrade.ts
  packages/token-lists/src/index.ts
  packages/token-lists/src/types.ts
  packages/token-lists/src/validator.ts
  packages/token-lists/src/wrappedTokenInfo.ts
  packages/token-lists/tsconfig.json
  packages/token-lists/tsup.config.ts
  yarn.lock
Labels: size/L

#5274 feat: list farm auction winner 33
  packages/farms/constants/56.ts
Labels: size/S, automerge

#5275 feat: (pools): Use on chain token per block data and use uikit types
  apps/web/src/__tests__/state/pools/helpers.test.ts
  apps/web/src/config/constants/pools.tsx
  apps/web/src/config/constants/types.ts
  apps/web/src/state/pools/fetchPools.ts
  apps/web/src/state/pools/index.ts
  apps/web/src/state/types.ts
  packages/uikit/src/widgets/Pool/types.ts
Labels: size/L

#5277 feat: (swap): Show usd amount in swap currency input
  apps/web/src/components/CurrencyInputPanel/index.tsx
  apps/web/src/views/Swap/components/SwapForm.tsx
Labels: size/S

#5265 fix: (pools): Vault Extend modal flickers when max selected
  apps/web/src/views/Pools/components/LockedPool/Common/LockDurationField.tsx
  apps/web/src/views/Pools/components/LockedPool/Common/LockedModalBody.tsx
  apps/web/src/views/Pools/components/LockedPool/Modals/ExtendDurationModal.tsx
  apps/web/src/views/Pools/components/LockedPool/types/index.ts
  apps/web/src/views/Pools/components/Vault/VaultRoiCalculatorModal.tsx
Labels: size/M

#5279 fix(farm): Withdraw decimals
  packages/uikit/src/widgets/Farm/components/DepositModal/index.tsx
  packages/uikit/src/widgets/Farm/components/WithdrawModal/index.tsx
Labels: size/S, automerge

#5281 fix(web/pools): Cake withdrawal Modal mess with flexible and locked
  apps/web/src/views/Pools/components/CakeVaultCard/VaultCardActions/HasSharesActions.tsx
Labels: size/S

#5283 chore(Info): Separate wordings for "Pools"
  apps/web/src/config/constants/meta.ts
  apps/web/src/views/Info/Overview/index.tsx
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/Info/Pools/index.tsx
  apps/web/src/views/Info/Tokens/TokenPage.tsx
  apps/web/src/views/Info/components/InfoNav/index.tsx
  apps/web/src/views/Info/components/InfoSearch/index.tsx
  apps/web/src/views/Info/components/InfoTables/PoolsTable.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#5282 revert: Pool token per block info on chain fetch
  apps/web/src/__tests__/state/pools/helpers.test.ts
  apps/web/src/config/constants/pools.tsx
  apps/web/src/state/pools/fetchPools.ts
  apps/web/src/state/pools/index.ts
  packages/uikit/src/widgets/Pool/types.ts
Labels: size/L

#5276 fix(aptos-pool): Avoid throwing invariant error in trade
  apps/aptos/components/Pools/hooks/useAddressPriceMap.ts
  apps/aptos/components/Pools/hooks/usePoolsList.ts
  apps/aptos/components/Pools/utils/getPriceInUSDC.ts
  packages/uikit/src/widgets/Modal/NotEnoughTokensModal.tsx
  packages/uikit/src/widgets/Pool/withStakeActions.tsx
Labels: size/M

#5288 chore: Move gq to finished pools
  apps/web/src/config/constants/pools.tsx
Labels: size/S

#5291 feat(swap): Wordings updates on BSC Swap Page
  apps/aptos/components/Layout/ExchangeLayout.tsx
  apps/web/src/config/constants/index.ts
  apps/web/src/views/Page.tsx
  apps/web/src/views/Swap/index.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/widgets/Swap/Footer.tsx
  packages/uikit/src/widgets/Swap/Page.tsx
Labels: size/M, automerge

#5286 fix(wagmi): Emit disconnect when try to connect blocto error
  .changeset/violet-chairs-approve.md
  packages/wagmi/connectors/blocto/blocto.ts
Labels: size/XS

#5294 fix(wagmi): Update bsc testnet rpc
  packages/wagmi/chains/chains.ts
Labels: size/XS

#5298 feat: Enable pancakeswap token list by default
  apps/web/src/components/SearchModal/ManageLists.tsx
  apps/web/src/config/constants/lists.ts
Labels: size/XS

#5297 feat: Allow to get all common pairs externally
  .changeset/flat-waves-draw.md
  packages/smart-router/evm/getBestTradeFromV2.ts
  packages/smart-router/evm/types/bestTrade.ts
  packages/smart-router/package.json
Labels: size/S, automerge

#5302 fix(wagmi): Blocto request account popup unintentionally
  .changeset/spotty-jars-watch.md
  packages/wagmi/connectors/blocto/blocto.ts
Labels: size/XS

#5284 feat(aptos): Add coin helper group
  apps/aptos/components/CoinRegisterButton.tsx
  apps/aptos/components/CurrencyInputPanel/index.tsx
  apps/aptos/components/Logo/CurrencyLogo.css.ts
  apps/aptos/components/Logo/CurrencyLogo.tsx
  apps/aptos/components/Logo/Logo.tsx
  apps/aptos/components/NetworkSwitcher.tsx
  apps/aptos/components/SearchModal/CurrencyList.tsx
  apps/aptos/components/SearchModal/CurrencySearch.tsx
  apps/aptos/components/SearchModal/ImportRow.tsx
  apps/aptos/components/SearchModal/ImportToken.tsx
  apps/aptos/components/SearchModal/ManageTokens.tsx
  apps/aptos/pages/_document.tsx
  apps/aptos/pages/swap.tsx
  apps/web/src/components/CurrencyInputPanel/index.tsx
  apps/web/src/components/SearchModal/CurrencyList.tsx
  apps/web/src/components/SearchModal/CurrencySearch.tsx
  apps/web/src/components/SearchModal/ImportRow.tsx
  apps/web/src/components/SearchModal/ManageTokens.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/components/CopyButton/CopyAddress.tsx
  packages/uikit/src/components/CopyButton/CopyButton.tsx
  packages/uikit/src/components/Loading/Loading.tsx
  packages/uikit/src/components/Message/Message.tsx
  packages/uikit/src/components/Message/theme.ts
  packages/uikit/src/components/Message/types.ts
  packages/uikit/src/components/Svg/Icons/AddCircle.tsx
  packages/uikit/src/components/Svg/Icons/DeleteOutline.tsx
  packages/uikit/src/components/Svg/Icons/HelpFilled.tsx
  packages/uikit/src/components/Svg/Icons/InfoFilled.tsx
  packages/uikit/src/components/Svg/Icons/WalletRegister.tsx
  packages/uikit/src/components/Svg/index.tsx
  packages/uikit/src/hooks/useTooltip/types.ts
  packages/uikit/src/hooks/useTooltip/useTooltip.tsx
  packages/uikit/src/widgets/Menu/components/UserMenu/MenuIcon.tsx
  packages/uikit/src/widgets/Menu/components/UserMenu/index.tsx
  packages/uikit/src/widgets/Menu/components/UserMenu/types.ts
  packages/uikit/src/widgets/Modal/Modal.tsx
  packages/uikit/src/widgets/Modal/types.ts
Labels: size/XL

#5306 chore: Filter not started pool yet
  apps/aptos/components/Farms/hooks/useHarvestFarm.ts
  apps/aptos/components/Farms/hooks/useStakeFarms.ts
  apps/aptos/components/Farms/hooks/useUnstakeFarms.ts
  apps/aptos/components/Liquidity/hooks/useAddLiquidityHandler.ts
  apps/aptos/components/Liquidity/hooks/useRemoveLiquidityHandler.ts
  apps/aptos/components/Pools/components/PoolCard/CollectModal.tsx
  apps/aptos/components/Pools/components/PoolCard/StakeModal.tsx
  apps/aptos/components/Pools/hooks/useHarvestPool.ts
  apps/aptos/components/Pools/hooks/useStakePool.ts
  apps/aptos/components/Pools/hooks/useUnstakePool.ts
  apps/aptos/components/Pools/transformers/transformPool.ts
  apps/aptos/contracts/generated/smartchef.ts
  apps/aptos/hooks/useSimulationAndSendTransaction.ts
  apps/aptos/pages/swap.tsx
  packages/uikit/src/widgets/Pool/PoolCard.tsx
  packages/utils/compoundApyHelpers.ts
Labels: size/L

#5307 fix(aptos): Add missing props on apt logo
  apps/aptos/components/Logo/CurrencyLogo.tsx
Labels: size/XS

#5305 chore: Remove warnings
  apps/web/src/views/Pools/components/LockedPool/Common/LockDurationField.tsx
  apps/web/src/views/Pools/components/PoolsTable/Cells/StakedCell.tsx
  apps/web/src/views/Swap/index.tsx
Labels: size/XS

#5308 chore: Update test
  packages/utils/compoundApyHelpers.ts
Labels: size/XS

#5296 chore: update farm LP APR
  apps/web/src/config/constants/lpAprs/1.json
  apps/web/src/config/constants/lpAprs/56.json
Labels: size/L

#5310 chore: separate smart swap with the old v2 swap
  apps/web/src/views/Swap/SmartSwap/index.tsx
  apps/web/src/views/Swap/index.tsx
Labels: size/S

#5312 feat: add static methods to trade & route with stable swap
  packages/smart-router/evm/index.ts
  packages/smart-router/evm/route.ts
  packages/smart-router/evm/trade.ts
  packages/smart-router/evm/types/pair.ts
  packages/smart-router/evm/types/route.ts
  packages/smart-router/evm/types/stableSwap.ts
  packages/smart-router/evm/utils/route.ts
  packages/smart-router/package.json
Labels: size/L

#5316 feat: add smart router global toggle setting
  apps/web/src/components/Menu/GlobalSettings/SettingsModal.tsx
  apps/web/src/state/user/smartRouter.ts
  apps/web/src/views/Swap/index.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#5314 perf: (prediction): Don't serialize rounds when fetching them in history
  apps/web/src/state/predictions/index.ts
Labels: size/XS

#5290 feat(Aptos): Add useTokenUsdcPrice hook
  apps/aptos/hooks/useStablePrice.ts
Labels: size/S

#5289 feat: (prediction): Show house on live round
  apps/web/src/views/Predictions/components/RoundCard/LiveRoundCard.tsx
  apps/web/src/views/Predictions/components/RoundCard/LiveRoundPrice.tsx
Labels: size/M

#3673 fix: (create-profile): No collectibles nft error not shown when setting profile picture and add pancake collectibles page
  apps/web/src/pages/profile/pancake-collectibles.tsx
  apps/web/src/views/Nft/market/Collections/index.tsx
  apps/web/src/views/Nft/market/components/CollectibleCard/CollectionCard.tsx
  apps/web/src/views/Nft/market/components/CollectibleCard/CollectionCardWithVolume.tsx
  apps/web/src/views/Profile/components/PancakeCollectibles.tsx
  apps/web/src/views/Profile/components/PancakeCollectiblesPageRouter.tsx
  apps/web/src/views/ProfileCreation/ProfilePicture.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#5313 feat: add util functions for exchanging trade with stable swap
  apps/web/src/views/Swap/SmartSwap/utils/exchange.ts
Labels: size/M

#5322 chore: Decouple v2trade with swap components and methods
  apps/web/src/__tests__/utils/prices.test.ts
  apps/web/src/utils/exchange.ts
  apps/web/src/views/Swap/SmartSwap/index.tsx
  apps/web/src/views/Swap/components/AdvancedSwapDetails.tsx
  apps/web/src/views/Swap/components/ConfirmSwapModal.tsx
  apps/web/src/views/Swap/components/ConfirmationPendingContent.tsx
  apps/web/src/views/Swap/components/RouterViewer.tsx
  apps/web/src/views/Swap/components/SwapRoute.tsx
  packages/swap-sdk/src/entities/trade.ts
Labels: size/L

#5323 refactor: decouple swap modal header from trade type
  apps/web/src/views/Swap/StableSwap/components/StableSwapModalHeader.tsx
  apps/web/src/views/Swap/components/SwapModalHeader.tsx
  apps/web/src/views/Swap/components/TransactionConfirmSwapContent.tsx
Labels: size/M

#5326 chore(aptos-pool): Allow harvest when finished
  apps/aptos/components/Pools/hooks/useHarvestPool.ts
Labels: size/XS

#5328 chore: useSmartRouterContract
  apps/web/src/config/abi/pancakeSwapSmartRouter.json
  apps/web/src/utils/exchange.ts
  apps/web/src/views/Swap/SmartSwap/utils/exchange.ts
Labels: size/L

#5329 fix(lists): Loaded from indexeddb after fetch
  .changeset/tricky-flies-wonder.md
  apps/web/src/index.tsx
  apps/web/src/pages/_app.tsx
  packages/token-lists/react/lists.ts
Labels: size/S

#5287 chore(Info): Info pools redirection
  apps/e2e/cypress/integration/info/info.test.ts
  apps/web/next.config.mjs
  apps/web/src/__tests__/utils/utils.test.ts
  apps/web/src/config/constants/meta.ts
  apps/web/src/pages/info/pairs/[address].tsx
  apps/web/src/pages/info/pairs/index.tsx
  apps/web/src/views/FarmAuction/components/AuctionLeaderboard/AuctionLeaderboardTable.tsx
  apps/web/src/views/Farms/components/FarmCard/FarmCard.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/Info/components/InfoNav/index.tsx
  apps/web/src/views/Info/components/InfoSearch/index.tsx
  apps/web/src/views/Info/components/InfoTables/PoolsTable.tsx
Labels: size/M

#5336 chore: Decouple v2trade for AdvancedSwapDetails
  apps/web/src/views/Swap/SmartSwap/index.tsx
  apps/web/src/views/Swap/components/AdvancedSwapDetails.tsx
  apps/web/src/views/Swap/components/AdvancedSwapDetailsDropdown.tsx
  apps/web/src/views/Swap/components/SwapForm.tsx
Labels: size/L

#5332 feat: get best trade from smart router
  apps/web/src/state/swap/fetch/fetchBestPriceWithRouter.ts
  apps/web/src/views/Swap/SmartSwap/hooks/index.ts
  apps/web/src/views/Swap/SmartSwap/hooks/useDerivedSwapInfoWithStableSwap.ts
  apps/web/src/views/Swap/SmartSwap/index.tsx
  apps/web/src/views/Swap/SmartSwap/utils/exchange.ts
  packages/farms/package.json
  packages/smart-router/evm/index.ts
  packages/smart-router/evm/stableSwap.ts
  yarn.lock
Labels: size/L

#5187 feat: info test endpoint and types adjustment
  apis/farms/src/lpApr.ts
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/hooks/useBucket.ts
  apps/web/src/middleware.ts
  apps/web/src/state/info/constant.ts
  apps/web/src/state/info/hooks.ts
  apps/web/src/state/info/queries/pools/poolData.ts
  apps/web/src/state/info/queries/pools/transactions.ts
  apps/web/src/state/info/queries/search/index.ts
  apps/web/src/state/info/queries/tokens/chartData.ts
  apps/web/src/state/info/queries/tokens/poolsForToken.ts
  apps/web/src/state/info/queries/tokens/priceData.ts
  apps/web/src/state/info/queries/tokens/tokenData.ts
  apps/web/src/state/info/queries/tokens/topTokens.ts
  apps/web/src/state/info/queries/tokens/transactions.ts
  apps/web/src/state/swap/fetch/fetchDerivedPriceData.ts
  apps/web/src/state/swap/fetch/fetchPairPriceData.ts
  apps/web/src/state/swap/hooks.ts
  apps/web/src/state/swap/queries/getDerivedPrices.ts
  apps/web/src/state/swap/queries/lastPairDayId.ts
  apps/web/src/state/swap/queries/pairDayDatas.ts
  apps/web/src/state/swap/queries/pairDayDatasByIdsQuery.ts
  apps/web/src/state/swap/queries/pairHourDatasByIds.ts
  apps/web/src/utils/buckets.ts
  apps/web/src/utils/graphql.ts
  apps/web/src/views/Info/Overview/index.tsx
  apps/web/src/views/Info/components/InfoSearch/index.tsx
  packages/localization/src/config/translations.json
  scripts/updateLPsAPR.ts
Labels: Delayed Release, size/L

#5340 fix(aptos-pool): Update earning and harvest after finish
  apps/aptos/components/Pools/transformers/transformCakePool.ts
  apps/aptos/components/Pools/transformers/transformPool.ts
Labels: size/M

#5342 revert: "fix(lists): Loaded from indexeddb after fetch"
  .changeset/tricky-flies-wonder.md
  apps/web/src/index.tsx
  apps/web/src/pages/_app.tsx
  packages/token-lists/react/lists.ts
Labels: size/S

#5344 chore: Get best price in trade
  apps/aptos/components/Pools/hooks/useAddressPriceMap.ts
  apps/aptos/components/Pools/transformers/transformPool.ts
  apps/aptos/components/Pools/utils/getPriceInUSDC.ts
Labels: size/S

#5343 fix: Ifo and pools page crash intermittently when cake vault is in flexible mode
  apps/web/src/views/Pools/components/LockedPool/Common/ConvertToLock.tsx
  apps/web/src/views/Pools/components/LockedPool/hooks/useAvgLockDuration.tsx
Labels: size/M

#5341 chore: Bump up jotai
  apps/web/package.json
  yarn.lock
Labels: size/S

#5339 chore: Remove warnings
  apps/web/src/state/info/queries/pools/transactions.ts
  apps/web/src/state/swap/fetch/fetchDerivedPriceData.ts
Labels: size/XS

#5338 feat: Set farm booster activate gas limit
  apps/web/src/views/Farms/components/YieldBooster/hooks/useBoosterFarmHandlers.ts
Labels: size/XS

#5349 chore: Update grapqhl url
  apps/web/src/config/constants/endpoints.ts
Labels: size/XS

#5348 fix(token-list): Not updating from indexeddb from version bump
  .changeset/neat-adults-brush.md
  apps/aptos/state/lists/index.ts
  apps/aptos/state/lists/updater.tsx
  apps/web/src/state/lists/lists.ts
  apps/web/src/state/lists/updater.ts
  packages/token-lists/react/lists.ts
  turbo.json
Labels: size/L

#5347 feat: remove dependency of v2 trade in smart swap
  apps/web/src/views/Swap/SmartSwap/hooks/useTradeInfo.ts
  apps/web/src/views/Swap/SmartSwap/index.tsx
  apps/web/src/views/Swap/components/AdvancedSwapDetails.tsx
  apps/web/src/views/Swap/components/AdvancedSwapDetailsDropdown.tsx
  apps/web/src/views/Swap/components/RouterViewer.tsx
  packages/smart-router/evm/index.ts
  packages/smart-router/evm/trade.ts
  packages/smart-router/evm/types/stableSwap.ts
  packages/smart-router/evm/utils/pair.ts
  packages/smart-router/evm/utils/route.ts
Labels: size/L

#5351 fix(turbo): postinstall path
  turbo.json
Labels: size/XS

#5311 chore(pool): Move Moni to finished pool
  apps/web/src/config/constants/pools.tsx
Labels: size/S, automerge

#5331 feat(aptos): Add usePriceCakeUsdc
  apps/aptos/components/Farms/components/FarmCard/HarvestAction.tsx
  apps/aptos/components/Farms/components/FarmCard/StakeAction.tsx
  apps/aptos/components/Farms/components/FarmTable/Actions/HarvestAction.tsx
  apps/aptos/components/Farms/components/FarmTable/Actions/StakedAction.tsx
  apps/aptos/components/Farms/components/Farms.tsx
  apps/aptos/config/coins.ts
  apps/aptos/hooks/useStablePrice.ts
  apps/aptos/pages/farms/history.tsx
  apps/aptos/pages/farms/index.tsx
Labels: size/M, automerge

#5354 chore: Update config on abtesting
  apps/web/src/hooks/useBucket.ts
  apps/web/src/middleware.ts
  apps/web/src/state/info/constant.ts
  apps/web/src/state/info/queries/tokens/priceData.ts
  apps/web/src/state/swap/fetch/fetchDerivedPriceData.ts
  apps/web/src/utils/buckets.ts
Labels: size/S

#5353 fix(aptos): Show warning modal after token list is ready
  apps/aptos/components/Liquidity/hooks/useAddLiquidityHandler.ts
  apps/aptos/pages/swap.tsx
  apps/aptos/state/lists/updater.tsx
  apps/aptos/state/swap.ts
Labels: size/M

#5350 refactor: combine getting trade from api & on chain
  apps/web/src/views/Swap/SmartSwap/hooks/useBestTrade.ts
  apps/web/src/views/Swap/SmartSwap/hooks/useDerivedSwapInfoWithStableSwap.ts
  apps/web/src/views/Swap/SmartSwap/utils/exchange.ts
  apps/web/src/views/Swap/components/AdvancedSwapDetails.tsx
  apps/web/src/views/Swap/components/AdvancedSwapDetailsDropdown.tsx
Labels: size/L

#5360 fix(aptos-pool): Should not increase earnings for finished pool
  apps/aptos/components/Pools/transformers/transformPool.ts
Labels: size/M

#5357 perf(aptos): Token list external url
  apps/aptos/components/SearchModal/ManageLists.tsx
Labels: size/XS, automerge

#5356 feat: Import token with logo
  apps/aptos/components/SearchModal/ImportToken.tsx
  apps/web/src/components/SearchModal/ImportToken.tsx
Labels: size/S

#5355 perf(pottery): Show Locked date when status is before lock
  apps/web/src/views/Pottery/components/Pot/Deposit/index.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#5361 fix: info multichain pair page
  apps/web/src/pages/info/[chainName]/pairs/[address].tsx
  apps/web/src/pages/info/[chainName]/pairs/index.tsx
Labels: size/XS
