Repository pancakeswap/pancake-frontend, pull requests merged in 2022-04, with the labels that each got.

#3618 feat: List YEL farms
  public/images/tokens/0xD3b71117E6C1558c1553305b44988cd944e97300.png
  public/images/tokens/0xD3b71117E6C1558c1553305b44988cd944e97300.svg
  src/config/constants/farms.ts
  src/config/constants/tokens.ts
Labels: size/M

#3619 chore: Update YEL token image
  public/images/tokens/0xD3b71117E6C1558c1553305b44988cd944e97300.png
  public/images/tokens/0xD3b71117E6C1558c1553305b44988cd944e97300.svg
Labels: size/M

#3620 chore: Scale down yel image
  public/images/tokens/0xD3b71117E6C1558c1553305b44988cd944e97300.png
  public/images/tokens/0xD3b71117E6C1558c1553305b44988cd944e97300.svg
Labels: size/M

#3624 fix: Hide WC button if in TW browser
  packages/uikit/src/react-app-env.d.ts
  packages/uikit/src/widgets/WalletModal/ConnectModal.tsx
  src/react-app-env.d.ts
Labels: size/S

#3625 feat: Mobox trading competition
  cypress/integration/tradingCompetition/tradingCompetition.test.ts
  public/images/achievements/MBOX-champion-bronze.svg
  public/images/achievements/MBOX-champion-gold.svg
  public/images/achievements/MBOX-champion-silver.svg
  public/images/achievements/MBOX-participant-bronze.svg
  public/images/achievements/MBOX-participant-gold.svg
  public/images/achievements/MBOX-participant-silver.svg
  public/images/achievements/MBOX-top-500-bronze.svg
  public/images/achievements/MBOX-top-500-gold.svg
  public/images/achievements/MBOX-top-500-silver.svg
  public/images/tc-easter-bunnies.png
  public/images/tc-fantoken-bunnies.png
  src/config/abi/tradingCompetitionMobox.json
  src/config/constants/contracts.ts
  src/config/constants/trading-competition/phases.ts
  src/config/constants/trading-competition/prizes.ts
  src/config/localization/translations.json
  src/hooks/useContract.ts
  src/pages/competition.tsx
  src/pages/competition/finished.tsx
  src/pages/competition/index.tsx
  src/utils/addressHelpers.ts
  src/utils/contractHelpers.ts
  src/views/Home/components/Banners/CompetitionBanner.tsx
  src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  src/views/Home/components/Banners/images/index.ts
  src/views/Home/components/Banners/images/mbox-tc-desktop.png
  src/views/Home/components/Banners/images/mbox-tc-mobile.png
  src/views/TradingCompetition/FanTokenCompetition.tsx
  src/views/TradingCompetition/FinishedCompetitions.tsx
  src/views/TradingCompetition/MoboxCompetition.tsx
  src/views/TradingCompetition/components/BattleBanner/index.tsx
  src/views/TradingCompetition/components/FinishedCompetitionBanner/index.tsx
  src/views/TradingCompetition/components/HowToJoin/index.tsx
  src/views/TradingCompetition/components/PrizesInfo/PrizesCard.tsx
  src/views/TradingCompetition/components/PrizesInfo/PrizesText.tsx
  src/views/TradingCompetition/components/RegisterModal/RegisterWithProfile.tsx
  src/views/TradingCompetition/components/Rules/FAQs.tsx
  src/views/TradingCompetition/components/Rules/index.tsx
  src/views/TradingCompetition/components/SubMenu/index.tsx
  src/views/TradingCompetition/index.tsx
  src/views/TradingCompetition/pngs/mbox-all-bunnies.png
  src/views/TradingCompetition/pngs/mbox-storm-bunny.png
  src/views/TradingCompetition/pngs/mbox_flipper.png
  src/views/TradingCompetition/styles.ts
Labels: size/XXL

#3627 chore: adjustment for competition banner
  src/views/Home/components/Banners/CompetitionBanner.tsx
  src/views/Home/components/Banners/LotteryBanner.tsx
  src/views/Home/components/Banners/MultipleBanner.tsx
  src/views/Home/components/Banners/Styled.tsx
  src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  src/views/Home/components/Banners/images/mbox-tc-desktop.png
  src/views/Home/components/Banners/images/mbox-tc-mobile.png
Labels: size/M

#3629 fix: (lottery banner): Missing current lottery fetch causes banner always shows preparing
  src/views/Home/components/Banners/MultipleBanner.tsx
  src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/M, automerge

#3630 fix: Missing translation in currency list
  src/components/SearchModal/CurrencyList.tsx
  src/config/localization/translations.json
Labels: size/XS

#3637 feat: Trading competition menu add soon tag
  src/components/Menu/config/config.ts
Labels: size/XS, automerge

#3634 refactor: Bump up graphql and graphql-request
  package.json
  yarn.lock
Labels: size/S, automerge

#3638 feat: Update achievement images
  public/images/achievements/MBOX-top-10-bronze.svg
  public/images/achievements/MBOX-top-10-gold.svg
  public/images/achievements/MBOX-top-10-silver.svg
  public/images/achievements/MBOX-top-100-bronze.svg
  public/images/achievements/MBOX-top-100-gold.svg
  public/images/achievements/MBOX-top-100-silver.svg
  src/config/constants/trading-competition/prizes.ts
Labels: size/XL, automerge

#3622 fix: User added tokens logos is not visible on token search modal list
  src/components/CurrencyInputPanel/index.tsx
  src/components/Logo/CurrencyLogo.tsx
  src/components/Menu/GlobalSettings/GasSettings.tsx
  src/components/SearchModal/CurrencySearch.tsx
  src/components/TransactionConfirmationModal/index.tsx
  src/config/constants/types.ts
  src/hooks/Tokens.ts
  src/state/lists/hooks.ts
  src/state/types.ts
  src/state/user/hooks/helpers.ts
  src/state/user/hooks/index.tsx
  src/state/user/reducer.ts
  src/utils/getGasPrice.ts
  src/utils/index.ts
  src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/index.tsx
  src/views/Swap/components/SwapWarningModal/index.tsx
Labels: size/L

#3639 style: Banner css and exchange bunny image
  public/images/competition/banner-star.png
  src/views/TradingCompetition/MoboxCompetition.tsx
  src/views/TradingCompetition/components/BattleBanner/index.tsx
  src/views/TradingCompetition/pageSectionStyles.tsx
  src/views/TradingCompetition/pngs/cakers.png
  src/views/TradingCompetition/pngs/mbox-all-bunnies.png
  src/views/TradingCompetition/pngs/mbox-storm-bunny.png
  src/views/TradingCompetition/pngs/mbox_flipper.png
Labels: size/M, automerge

#3581 refactor(voting): Use default strategy to reduce voting request
  src/config/__tests__/pools.test.ts
  src/config/constants/pools.tsx
  src/config/constants/poolsDeployedBlockNumber.ts
  src/config/constants/types.ts
  src/config/localization/translations.json
  src/state/voting/helpers.ts
  src/utils/calls/pools.ts
  src/utils/multicall.ts
  src/views/Voting/Proposal/Overview.tsx
  src/views/Voting/components/CastVoteModal/DetailsView.tsx
  src/views/Voting/components/CastVoteModal/MainView.tsx
  src/views/Voting/components/CastVoteModal/index.tsx
  src/views/Voting/components/Proposal/VoteRow.tsx
  src/views/Voting/getScores.ts
  src/views/Voting/helpers.ts
  src/views/Voting/hooks/useGetVotingPower.tsx
  src/views/Voting/legacy/getVotingPowerList.ts
  src/views/Voting/legacy/strategy.ts
  src/views/Voting/strategies.ts
Labels: size/XXL

#3642 fix: Duplicate translation key
  src/config/localization/translations.json
Labels: size/XS

#3644 feat: List TINC
  public/images/tokens/0x05aD6E30A855BE07AfA57e08a4f30d00810a402e.png
  public/images/tokens/0x05aD6E30A855BE07AfA57e08a4f30d00810a402e.svg
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
  src/config/constants/tokens.ts
Labels: size/M, automerge

#3647 chore: Bump up canvas confetti
  package.json
  yarn.lock
Labels: size/XS

#3645 chore: Bump up easymde
  package.json
  yarn.lock
Labels: size/XS

#3572 fix: (prediction): Round card transition on prediction
  src/state/predictions/hooks.ts
  src/state/predictions/index.ts
  src/state/predictions/selectors.ts
  src/views/Predictions/Positions.tsx
  src/views/Predictions/components/PrevNextNav.tsx
  src/views/Predictions/hooks/useOnNextRound.ts
  src/views/Predictions/hooks/usePollPredictions.ts
Labels: size/L

#3648 fix: Manage nft cards still shows user nfts after logout
  src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/ManagePancakeBunniesCard.tsx
  src/views/Nft/market/hooks/useNftsForAddress.tsx
Labels: size/S

#3650 chore: Update Sentry Version on Prod
  next.config.js
Labels: size/XS

#3653 fix: Swiper moves to next round card from currently focused after removing earliest card
  src/views/Predictions/hooks/useOnNextRound.ts
Labels: size/XS

#3656 fix: Increase gas limit to 250k because GMI pool fails on deposit
  src/config/index.ts
Labels: size/XS

#3658 refactor: Use more visible colors for chainlink chart round dots
  src/views/Predictions/components/ChainlinkChart.tsx
Labels: size/S

#3660 fix: Not show collect win after polling predictions
  src/state/predictions/index.ts
Labels: size/XS

#3666 chore: Fix typo in filename
  src/components/Menu/UserMenu/ProfileUserMenuItem.tsx
  src/components/Menu/UserMenu/index.tsx
Labels: size/XS

#3664 fix: Setup profile link in trading competition
  src/views/TradingCompetition/components/HowToJoin/index.tsx
Labels: size/S, automerge

#3651 chore: Update Sentry package
  package.json
  packages/uikit/src/widgets/WalletModal/WalletCard.tsx
  src/contexts/Localization/Provider.tsx
  src/hooks/usePersistState.ts
  yarn.lock
Labels: size/L

#3671 chore(voting): Update after strategy
  src/config/localization/translations.json
  src/state/voting/helpers.ts
  src/views/Voting/components/CastVoteModal/DetailsView.tsx
  src/views/Voting/components/CastVoteModal/index.tsx
  src/views/Voting/helpers.ts
  src/views/Voting/legacy/getVotingPowerList.ts
  src/views/Voting/legacy/strategy.ts
Labels: size/XL

#3665 fix: Tradingcompetition mobox
  src/config/localization/translations.json
  src/utils/contractHelpers.ts
  src/views/TradingCompetition/FanTokenCompetition.tsx
  src/views/TradingCompetition/MoboxCompetition.tsx
  src/views/TradingCompetition/components/ClaimModal/index.tsx
  src/views/TradingCompetition/components/YourScore/UserPrizeGrid.tsx
  src/views/TradingCompetition/helpers.ts
  src/views/TradingCompetition/types.ts
Labels: size/XL

#3635 fix: (nft): Pancake Bunny Nft cheapest price and for sale card shows obsolete data which causes error when buy
  src/config/abi/nftMarket.json
  src/config/constants/index.ts
  src/config/localization/translations.json
  src/state/nftMarket/helpers.ts
  src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/ForSaleTableCard/ForSaleTableRows.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/ForSaleTableCard/index.tsx
  src/views/Nft/market/hooks/useGetLowestPrice.ts
  src/views/Nft/market/hooks/usePancakeBunnyCheapestNfts.tsx
  src/views/Nft/market/hooks/usePancakeBunnyOnSaleNfts.tsx
Labels: size/L

#3674 chore: Remove unused imports
  src/views/TradingCompetition/FanTokenCompetition.tsx
Labels: size/XS

#3677 feat(farm): Auction 19 whitelist
  src/config/constants/farmAuctions.ts
Labels: size/S

#3672 chore: Set up SENTRY_RELEASE env on client
  next.config.js
Labels: size/S

#3676 feat: Participants count, Subgraph Indicator, share images
  src/components/SubgraphHealthIndicator/index.tsx
  src/config/constants/endpoints.ts
  src/config/localization/translations.json
  src/views/TradingCompetition/components/ShareImageModal.tsx
  src/views/TradingCompetition/components/TeamRanks/Podium/index.tsx
  src/views/TradingCompetition/components/TeamRanks/Podium/useGetParticipants.ts
  src/views/TradingCompetition/components/TeamRanks/TopTradersCard/index.tsx
  src/views/TradingCompetition/components/TeamRanks/index.tsx
  src/views/TradingCompetition/components/YourScore/ScoreCard.tsx
  src/views/TradingCompetition/pngs/mobox-cakers-share.png
  src/views/TradingCompetition/pngs/mobox-flippers-share.png
  src/views/TradingCompetition/pngs/mobox-storm-share.png
Labels: size/L

#3670 feat: Menu competition status set to live
  src/components/Menu/config/config.ts
Labels: size/XS

#3680 fix: Update share image
  src/views/TradingCompetition/components/ShareImageModal.tsx
  src/views/TradingCompetition/pngs/mobox-cakers-share.png
  src/views/TradingCompetition/pngs/mobox-flippers-share.png
  src/views/TradingCompetition/pngs/mobox-share-profile-mask.png
  src/views/TradingCompetition/pngs/mobox-storm-share.png
Labels: size/XS

#3663 fix: Previous account data shown when change account
  src/hooks/useAccountEventListener.ts
  src/pages/_app.tsx
Labels: size/S, automerge

#3675 chore: Use Deutsch as a language label
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/components/Footer/config.tsx
Labels: size/XS, automerge

#3681 chore: Remove unused code
  packages/uikit/src/hooks/useTooltip/useTooltip.tsx
Labels: size/XS

#3684 chore: Bump up swr
  package.json
  yarn.lock
Labels: size/S, automerge

#3682 docs: Add quick start in README
  README.md
Labels: size/S

#3689 style: Farm token width set to 32px
  src/views/Farms/components/FarmTable/Farm.tsx
Labels: size/XS, automerge

#3687 perf(voting): Reduce network request
  src/state/voting/helpers.ts
  src/views/Voting/Proposal/Overview.tsx
  src/views/Voting/helpers.ts
Labels: size/M

#3688 feat: List CEEK farms & Farm Auction 19 winner farms
  public/images/tokens/0xF5d8A096CcCb31b9D7bcE5afE812BE23e3D4690d.png
  public/images/tokens/0xF5d8A096CcCb31b9D7bcE5afE812BE23e3D4690d.svg
  public/images/tokens/0xFa40d8FC324bcdD6Bbae0e086De886c571C225d4.png
  public/images/tokens/0xFa40d8FC324bcdD6Bbae0e086De886c571C225d4.svg
  public/images/tokens/0xe0F94Ac5462997D2BC57287Ac3a3aE4C31345D66.png
  public/images/tokens/0xe0F94Ac5462997D2BC57287Ac3a3aE4C31345D66.svg
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
  src/config/constants/tokens.ts
Labels: size/L

#3692 fix: Reduce prediction dust by tenth and set max balance to zero if it is lower than
  src/views/Predictions/components/RoundCard/SetPositionCard.tsx
Labels: size/XS

#3615 fix: (nft): Token detail and user profile pages not show updated market data
  src/state/nftMarket/helpers.ts
  src/state/nftMarket/types.ts
  src/views/Nft/market/hooks/useCompleteNft.tsx
  src/views/Nft/market/hooks/useNftOwner.tsx
Labels: size/L

#3685 chore: Bump up swiper
  package.json
  yarn.lock
Labels: size/S

#3683 chore: Bump up rollup
  packages/uikit/package.json
  yarn.lock
Labels: size/S

#3698 chore: Bump up recharts
  package.json
  yarn.lock
Labels: size/L

#3695 chore: Update v1 farms & pools configs
  public/images/tokens/0xF5d8A096CcCb31b9D7bcE5afE812BE23e3D4690d.png
  public/images/tokens/0xF5d8A096CcCb31b9D7bcE5afE812BE23e3D4690d.svg
  public/images/tokens/0xFa40d8FC324bcdD6Bbae0e086De886c571C225d4.png
  public/images/tokens/0xFa40d8FC324bcdD6Bbae0e086De886c571C225d4.svg
  public/images/tokens/0xe0F94Ac5462997D2BC57287Ac3a3aE4C31345D66.png
  public/images/tokens/0xe0F94Ac5462997D2BC57287Ac3a3aE4C31345D66.svg
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
  src/config/constants/tokens.ts
Labels: size/L

#3701 chore(sentry): Clean up release setup
  next.config.js
Labels: size/S

#3700 chore: Bump walletconnect
  package.json
  src/utils/web3React.ts
  yarn.lock
Labels: size/XL

#3697 fix: (nft): Collection listings not updated in user session
  src/views/Nft/market/hooks/useCollectionNfts.tsx
Labels: size/XS

#3690 feat(wallet): Deeplink metamask
  packages/uikit/src/widgets/WalletModal/ConnectModal.tsx
  packages/uikit/src/widgets/WalletModal/WalletCard.tsx
  packages/uikit/src/widgets/WalletModal/config.tsx
  packages/uikit/src/widgets/WalletModal/types.ts
  src/hooks/useEagerConnect.ts
Labels: size/M

#3707 fix: Unused import
  src/hooks/useEagerConnect.ts
Labels: size/XS

#3706 chore: Reorder token list token import
  src/config/constants/lists.ts
Labels: size/XS

#3713 chore: Bump up typescript
  package.json
  yarn.lock
Labels: size/S

#3712 fix: Prediction leaderboard fetching state when filter
  src/state/predictions/index.ts
Labels: size/XS

#3715 chore: Adjust TC for claiming phase
  src/config/localization/translations.json
  src/views/TradingCompetition/MoboxCompetition.tsx
  src/views/TradingCompetition/components/ClaimModal/index.tsx
  src/views/TradingCompetition/pngs/mobox-bunny-nft.png
  src/views/TradingCompetition/pngs/mystery-box.png
Labels: size/M

#3704 chore: Turn off trading competition banner
  src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/XS

#3703 chore: Trading competition menu remove live status
  src/components/Menu/config/config.ts
Labels: size/XS

#3711 chore: Avoid evaluation error in name prop
  src/views/Nft/market/components/Activity/ActivityRow.tsx
  src/views/Nft/market/components/Activity/MobileModal.tsx
Labels: size/S

#3714 chore: Avoid undefined error in limit order
  src/hooks/limitOrders/useGasOverhead.ts
Labels: size/M

#3721 chore: Deposit modal lpLabel set default value
  src/views/Farms/components/DepositModal.tsx
Labels: size/XS

#3724 fix: Farm apr
  src/__tests__/utils/apr.test.ts
  src/utils/apr.ts
Labels: size/XS

#3727 fix: Missing public pool data on step 2
  src/views/Migration/components/MigrationStep2/NewPool/index.tsx
Labels: size/S

#3720 fix: User balance not available in cake pool roi modal
  src/components/RoiCalculatorModal/index.tsx
  src/views/Pools/components/Vault/VaultRoiCalculatorModal.tsx
Labels: size/S

#3729 chore: Prevent throwing browser localstorage error
  src/hooks/useEagerConnect.ts
Labels: size/S

#3728 perf(migration): Reduce step 2 new pool request
  src/state/pools/index.ts
  src/utils/apr.ts
  src/views/Migration/components/MigrationStep2/NewPool/index.tsx
Labels: size/M

#3725 feat: Get regular cake per block from sc
  src/__tests__/utils/apr.test.ts
  src/state/farms/fetchMasterChefData.ts
  src/state/farms/index.ts
  src/state/farms/selectors.ts
  src/state/types.ts
  src/utils/apr.ts
  src/views/Farms/Farms.tsx
  src/views/Home/hooks/useGetTopFarmsByApr.tsx
  src/views/Migration/components/MigrationStep1/OldFarm/index.tsx
  src/views/Migration/components/MigrationStep2/NewFarm/index.tsx
Labels: size/M

#3723 fix: Farm table history integration test
  cypress/integration/farms/farms.test.ts
  src/views/Farms/components/FarmTable/FarmTable.tsx
Labels: size/XS

#3733 fix(locked-pool): Avoid add large number in week input
  src/views/Pools/components/LockedPool/Common/LockDurationField.tsx
Labels: size/S

#3731 fix: Use Flexible APY for Flexible Tab
  src/components/RoiCalculatorModal/index.tsx
  src/views/Pools/components/Vault/VaultRoiCalculatorModal.tsx
Labels: size/M

#3736 chore: Fix Unit Test
  src/components/RoiCalculatorModal/index.tsx
Labels: size/XS

#3732 perf: Reduce calculation in memorized pool selector
  src/state/pools/selectors.ts
Labels: size/S

#3735 fix: Cake pool card mode AddIcon
  src/views/Pools/components/CakeVaultCard/VaultCardActions/VaultStakeActions.tsx
  src/views/Pools/components/CakeVaultCard/VaultCardActions/index.tsx
Labels: size/S, automerge

#3737 chore: Update Flexible APY with no fee
  src/hooks/useVaultApy.test.ts
  src/hooks/useVaultApy.ts
Labels: size/S

#3741 feat: Update Voting
  src/views/Voting/helpers.ts
  src/views/Voting/strategies.ts
Labels: size/M

#3746 fix: Voting
  src/views/Voting/helpers.ts
  src/views/Voting/strategies.ts
Labels: size/S

#3747 chore: Add Unstaking Fee warning in the cake pool
  src/views/Pools/components/PoolsTable/ActionPanel/AutoHarvest.tsx
Labels: size/XS

#3743 refactor: Change translation to comply with testing
  src/views/Pools/components/PoolsTable/Cells/StakedCell.tsx
Labels: size/XS

#3738 chore: Remove unused pb update frequency constant
  src/config/index.ts
Labels: size/XS

#3750 Revert "chore: Update LP APRs for Farms"
  src/config/constants/lpAprs.json
Labels: size/L

#3751 fix: LP APRs script after migration
  scripts/updateLPsAPR.ts
Labels: size/XS

#3755 fix(home): Home page top pools cake pool apy
  src/state/pools/selectors.ts
  src/views/Home/components/FarmsPoolsRow/TopFarmPool.tsx
  src/views/Home/components/FarmsPoolsRow/index.tsx
  src/views/Home/hooks/useGetTopPoolsByApr.tsx
Labels: size/M

#3722 refactor: Remove masterchef calls for cake vault user balance
  src/state/pools/fetchPoolsUser.ts
Labels: size/S

#3753 feat: List aBNBc farms and ANKR pool
  public/images/tokens/0xE85aFCcDaFBE7F2B096f268e31ccE3da8dA2990A.png
  public/images/tokens/0xE85aFCcDaFBE7F2B096f268e31ccE3da8dA2990A.svg
  public/images/tokens/0xf307910A4c7bbc79691fD374889b36d8531B08e3.png
  public/images/tokens/0xf307910A4c7bbc79691fD374889b36d8531B08e3.svg
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
  src/config/constants/tokens.ts
Labels: size/XXL

#3740 feat: skeleton with transition
  packages/uikit/src/components/Skeleton/Skeleton.tsx
  packages/uikit/src/components/Skeleton/index.stories.tsx
  packages/uikit/src/components/Skeleton/types.ts
  packages/uikit/src/index.ts
  packages/uikit/src/util/animationToolkit.ts
  packages/uikit/src/widgets/Modal/ModalContext.tsx
  src/views/Home/components/Banners/MultipleBanner.tsx
Labels: size/L

#3718 chore: Bump up next
  package.json
  yarn.lock
Labels: size/L

#3726 refactor: Reduce multicall size for pool user balances fetch
  src/state/pools/fetchPoolsUser.ts
Labels: size/S

#3758 feat: Display mbox rank
  src/config/localization/translations.json
  src/views/TradingCompetition/MoboxCompetition.tsx
  src/views/TradingCompetition/components/ClaimModal/index.tsx
  src/views/TradingCompetition/components/YourScore/CardUserInfo.tsx
  src/views/TradingCompetition/helpers.ts
  src/views/TradingCompetition/types.ts
Labels: size/M

#3760 refactor: Move price helper fetch to pools
  src/config/constants/priceHelperLps.ts
  src/state/farms/index.ts
  src/state/pools/index.ts
Labels: size/M

#3756 perf: Use multicall to reduce farms public data requests
  src/state/farms/fetchMasterChefData.ts
  src/state/farms/index.ts
Labels: size/M

#3754 fix(pool): Avoid NAN usd
  src/views/Pools/components/PoolsTable/ActionPanel/AutoHarvest.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
Labels: size/S

#3762 refactor: Change pancake rabbits name to pancake bunnies
  src/config/abi/pancakeBunnies.json
  src/config/constants/contracts.ts
  src/config/constants/nftsCollections/index.ts
  src/hooks/useContract.ts
  src/utils/addressHelpers.ts
  src/utils/contractHelpers.ts
  src/views/Nft/market/constants.ts
  src/views/Nft/market/hooks/useGetCollectionDistribution.tsx
Labels: size/M

#3763 fix: Language selector dropdown appears when scrolling in mobile
  packages/uikit/src/components/Dropdown/Dropdown.tsx
Labels: size/M

#3564 fix: (prediction): Timer shows more time remaining than actual and use timeouts to trigger phase changes
  src/state/predictions/hooks.ts
  src/state/predictions/selectors.ts
  src/utils/getNow.ts
  src/views/Predictions/components/Label.tsx
  src/views/Predictions/components/RoundCard/LiveRoundCard.tsx
  src/views/Predictions/components/RoundCard/OpenRoundCard.tsx
Labels: size/M

#3717 chore: Add MBOX TC achievements
  src/config/constants/campaigns.ts
Labels: size/M

#3770 feat: Add tooltips at Pool card & Lock Modal
  src/config/localization/translations.json
  src/views/Pools/components/LockedPool/Common/Overview/BalanceRow.tsx
  src/views/Pools/components/LockedPool/Common/Overview/DateRow.tsx
  src/views/Pools/components/LockedPool/Common/Overview/index.tsx
  src/views/Pools/components/LockedPool/LockedStakingApy.tsx
Labels: size/L

#3769 fix: Locked roi should depends on locked duration
  src/views/Pools/components/Vault/VaultRoiCalculatorModal.tsx
Labels: size/XS

#3771 feat: Add View Tutorial link at Cake pool
  src/config/localization/translations.json
  src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
Labels: size/S, automerge

#3749 fix(voting): Improve voting display after migration
  src/config/localization/translations.json
  src/views/Voting/components/CastVoteModal/DetailsView.tsx
  src/views/Voting/helpers.ts
  src/views/Voting/hooks/useGetVotingPower.tsx
Labels: size/L

#3773 fix(cake-pool): Total staked cake amount
  src/state/pools/fetchVaultPublic.ts
Labels: size/XS

#3774 fix: Migration Total staked amount
  src/views/Migration/hook/V1/Pool/fetchPublicVaultData.ts
  src/views/Migration/hook/V1/Pool/useFetchIfoPool.ts
Labels: size/M, automerge

#3775 fix: Update roi in lock modal
  src/views/Pools/components/LockedPool/Common/Overview/index.tsx
  src/views/Pools/components/LockedPool/utils/formatRoi.ts
Labels: size/S

#3776 fix: Update ROI calculate modal when prop is changed
  src/views/Pools/components/PoolsTable/Cells/AutoAprCell.tsx
Labels: size/XS

#3524 refactor: Remove ENS related code
  package.json
  src/components/SearchModal/ManageLists.tsx
  src/config/abi/ens-public-resolver.json
  src/config/abi/ens-registrar.json
  src/config/localization/translations.json
  src/hooks/ENS/useENS.ts
  src/hooks/ENS/useENSAddress.ts
  src/hooks/ENS/useENSContentHash.ts
  src/hooks/ENS/useENSName.ts
  src/hooks/useContract.ts
  src/hooks/useFetchListCallback.ts
  src/hooks/useHttpLocations.ts
  src/hooks/useSwapCallArguments.ts
  src/hooks/useSwapCallback.ts
  src/state/swap/hooks.test.ts
  src/state/swap/hooks.ts
  src/state/swap/reducer.ts
  src/utils/ENS/parseENSAddress.test.ts
  src/utils/ENS/parseENSAddress.ts
  src/utils/ENS/resolveENSContentHash.ts
  src/utils/contenthashToUri.ts
  src/utils/getTokenList.ts
  src/views/Swap/components/AddressInputPanel.tsx
  src/views/Swap/index.tsx
  yarn.lock
Labels: size/XXL

#3772 fix: Language Dropdown appears intermittently when tapping its potential visible area
  packages/uikit/src/components/Dropdown/Dropdown.tsx
Labels: size/XS, automerge

#3778 feat: List Farm Action 20
  src/config/constants/farmAuctions.ts
Labels: size/M

#3780 fix(home): Temp TVL fix
  src/pages/index.tsx
Labels: size/S

#3781 fix: Dropdown props dom warning
  packages/uikit/src/components/Dropdown/Dropdown.tsx
Labels: size/XS

#3782 fix(locked-pool): Remove user locked UI when logging out
  src/views/Pools/components/CakeVaultCard/index.tsx
Labels: size/XS

#3783 feat(locked-pool): Add Average lock duration
  src/config/localization/translations.json
  src/hooks/useVaultApy.ts
  src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
  src/views/Pools/components/Stat.tsx
Labels: size/L

#3779 chore: Remove unused isArchivedPid & isArchivedPidV1
  src/state/farms/hooks.ts
  src/state/farms/index.ts
  src/state/farmsV1/hooks.ts
  src/state/farmsV1/index.ts
  src/state/pools/hooks.ts
  src/utils/farmHelpers.ts
  src/views/Farms/Farms.tsx
  src/views/Home/hooks/useGetTopFarmsByApr.tsx
  src/views/Migration/components/MigrationStep1/OldFarm/index.tsx
  src/views/Migration/components/MigrationStep2/NewFarm/index.tsx
  src/views/Migration/hook/V1/Pool/useFetchPublicPoolsData.ts
  src/views/Migration/index.tsx
Labels: size/M

#3786 feat: Remove migration notification and change Finished text
  src/config/localization/translations.json
  src/views/Farms/Farms.tsx
  src/views/Farms/components/MigrationSticky.tsx
  src/views/Pools/index.tsx
Labels: size/L, automerge

#3787 feat: add skeleton for lock cake table view
  packages/uikit/src/components/Skeleton/Skeleton.tsx
  packages/uikit/src/components/Skeleton/index.tsx
  packages/uikit/src/components/Skeleton/types.ts
  src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
Labels: size/M

#3788 chore: Checksum NBT account address
  src/config/constants/farmAuctions.ts
Labels: size/XS, automerge

#3791 fix: Farms archive unknow problem
  src/config/constants/farmAuctions.ts
Labels: size/XS, automerge

#3792 chore: Add comment in farms archive config
  src/config/constants/farmAuctions.ts
Labels: size/S, automerge

#3790 style: Farms Card & Table view
  src/views/Farms/components/FarmCard/FarmCard.tsx
  src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  src/views/Farms/components/FarmTable/FarmTable.tsx
  src/views/Farms/components/FarmTable/Row.tsx
  src/views/Pools/components/PoolCard/StyledCard.tsx
Labels: size/S, automerge

#3795 feat: List farm auction 20 winners
  src/config/constants/farms.ts
Labels: size/M, automerge

#3799 feat: Update TokenPocket.tsx
  packages/uikit/src/components/Svg/Icons/TokenPocket.tsx
Labels: size/M, automerge

#3793 feat(locked-pool): Add Convert To Lock note
  src/config/localization/translations.json
  src/views/Pools/components/CakeVaultCard/VaultCardActions/HasSharesActions.tsx
  src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
  src/views/Pools/components/LockedPool/Common/ConvertToLock.tsx
  src/views/Pools/components/LockedPool/hooks/useAvgLockDuration.tsx
  src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
  src/views/Pools/components/Stat.tsx
Labels: size/L

#3797 perf(cake-pool): Move some vars to constants reduce network calls
  src/config/constants/pools.tsx
  src/hooks/useVaultApy.test.ts
  src/hooks/useVaultApy.ts
  src/hooks/useVaultMaxDuration.ts
  src/utils/cakePool.test.ts
  src/views/Home/components/FarmsPoolsRow/index.tsx
  src/views/Pools/components/CakeVaultCard/StakingApy.tsx
  src/views/Pools/components/CakeVaultCard/VaultCardActions/HasSharesActions.tsx
  src/views/Pools/components/LockedPool/Common/LockedModalBody.tsx
  src/views/Pools/components/LockedPool/Modals/ExtendDurationModal.tsx
  src/views/Pools/components/LockedPool/hooks/useAvgLockDuration.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/CakeVaultApr.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
  src/views/Pools/components/PoolsTable/Cells/AutoAprCell.tsx
  src/views/Pools/components/Stat.tsx
  src/views/Pools/components/Vault/VaultRoiCalculatorModal.tsx
  src/views/Pools/components/Vault/VaultStakeButtonGroup.tsx
Labels: size/L

#3744 perf: Reduce cheapest bunny calls by half
  src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/MainPancakeBunnyCard.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/index.tsx
  src/views/Nft/market/hooks/usePancakeBunnyCheapestNfts.tsx
Labels: size/M, automerge

#3802 feat: List RPG farm and pool
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
Labels: size/S, automerge

#3806 chore(lock-pool): Add withdraw warning
  src/config/localization/translations.json
  src/views/Pools/components/LockedPool/Common/LockedModalBody.tsx
  src/views/Pools/components/LockedPool/Common/Overview/index.tsx
  src/views/Pools/components/LockedPool/Modals/ExtendDurationModal.tsx
  src/views/Pools/components/LockedPool/types/index.ts
Labels: size/L
