Repository pancakeswap/pancake-frontend, pull requests merged in 2022-09, with the labels that each got.

#4629 revert(prediction): Claimed amount in tooltip round card
  src/views/Predictions/components/RoundCard/EnteredTag.tsx
  src/views/Predictions/components/RoundCard/MultiplierArrow.tsx
  src/views/Predictions/helpers.ts
Labels: size/S

#4630 chore: Remove BUNNY
  src/config/constants/tokenLists/pancake-default.tokenlist.json
Labels: size/XS, automerge

#4632 fix(mp): force chain id
  packages/wagmi/connectors/miniProgram/miniProgram.ts
Labels: size/XS

#4642 chore(birdge): Update version
  apps/bridge/components/Menu.tsx
  apps/bridge/components/stargate/config.ts
Labels: size/XS

#4631 feat: List farm auction 29 winners
  packages/tokens/src/56.ts
  public/images/tokens/0x6AA217312960A21aDbde1478DC8cBCf828110A67.png
  src/config/constants/farmAuctions.ts
  src/config/constants/farms/56.ts
Labels: size/M, automerge

#4407 feat: Red alarm
  packages/localization/src/config/translations.json
  src/config/constants/endpoints.ts
  src/views/Swap/components/AccessRisk/RiskMessage.tsx
  src/views/Swap/components/AccessRisk/index.tsx
  src/views/Swap/hooks/fetchTokenRisk.ts
  src/views/Swap/index.tsx
Labels: size/L, automerge

#4644 chore: Hide SPIN-BNB
  src/config/constants/farms/56.ts
Labels: size/S, automerge

#4646 chore: Update AccessRisk wording
  packages/localization/src/config/translations.json
  src/views/Swap/components/AccessRisk/index.tsx
  src/views/Swap/index.tsx
Labels: size/XS, automerge

#4645 chore: Show SPIN-BNB LP
  src/config/constants/farms/56.ts
Labels: size/S

#4647 chore: Hide Next draw date when status is BEFORE_LOCK
  src/views/Pottery/components/Pot/Deposit/index.tsx
Labels: size/S, automerge

#4649 feat: (pottery): Make pottery status pot open in menu when before lock
  src/components/Menu/hooks/useMenuItems.ts
  src/components/Menu/hooks/useMenuItemsStatus.ts
  src/components/Menu/hooks/usePotteryStatus.ts
Labels: size/S

#4648 chore(swap): Add additional bases for SFUND-SNFTS
  packages/tokens/src/56.ts
  src/config/constants/exchange.ts
Labels: size/XS

#4659 fix: dev warning
  packages/tokens/src/56.ts
  packages/wagmi/chains/chains.ts
  src/utils/wagmi.ts
Labels: size/M

#4664 fix(wallet): RPC setting overrided
  packages/wagmi/chains/chains.ts
Labels: size/XS

#4665 fix: Hide deposit by cohort and remaining period
  src/views/Pottery/components/Pot/Claim/CardFooter.tsx
Labels: size/M, automerge

#4650 fix(Wallet): SafePal&BinanceWallet no show AddToWalletButton
  src/components/AddToWallet/AddToWalletButton.tsx
Labels: size/S

#4662 feat: farm APR tooltip for bCake
  packages/localization/src/config/translations.json
  src/views/Farms/components/FarmCard/ApyButton.tsx
Labels: size/S

#4653 chore(AppHeader): Move Helper to the end of the Title
  src/components/App/AppHeader.tsx
Labels: size/XS

#4660 fix(Limit): Fix confirm window UI in Mobile
  src/views/LimitOrders/components/ConfirmLimitOrderModal.tsx
  src/views/LimitOrders/components/LimitOrderTable/DetailLimitOrderModal.tsx
Labels: size/S

#4673 chore: Move ole and trivia to finished pools
  src/config/constants/pools.tsx
Labels: size/S

#4674 chore: Update GAL token
  packages/tokens/src/56.ts
  public/images/tokens/0xe4Cc45Bb5DBDA06dB6183E8bf016569f40497Aa5.png
  public/images/tokens/0xe4Cc45Bb5DBDA06dB6183E8bf016569f40497Aa5.svg
Labels: size/S

#4672 perf: (pools): Fetch only unfinished pools block limits and profile requirements
  src/state/pools/fetchPools.ts
Labels: size/S

#4567 chore: New Crowdin updates
  public/locales/ar-SA.json
  public/locales/bn-BD.json
  public/locales/de-DE.json
  public/locales/el-GR.json
  public/locales/en-US.json
  public/locales/es-ES.json
  public/locales/fi-FI.json
  public/locales/fil-PH.json
  public/locales/fr-FR.json
  public/locales/hi-IN.json
  public/locales/hu-HU.json
  public/locales/id-ID.json
  public/locales/it-IT.json
  public/locales/ja-JP.json
  public/locales/ko-KR.json
  public/locales/nl-NL.json
  public/locales/pl-PL.json
  public/locales/pt-BR.json
  public/locales/pt-PT.json
  public/locales/ro-RO.json
  public/locales/ru-RU.json
  public/locales/sv-SE.json
  public/locales/ta-IN.json
  public/locales/tr-TR.json
  public/locales/uk-UA.json
  public/locales/vi-VN.json
  public/locales/zh-CN.json
  public/locales/zh-TW.json
Labels: size/XXL

#4652 fix(PriceChart): Hide TradingView button and fix Limit tokenPairs visable
  src/views/LimitOrders/index.tsx
  src/views/Swap/components/Chart/PriceChart.tsx
Labels: size/M, automerge

#4643 perf(lists): Move away from redux persist
  src/components/SearchModal/ImportList.tsx
  src/components/SearchModal/ManageLists.tsx
  src/hooks/Tokens.ts
  src/hooks/useFetchListCallback.ts
  src/pages/451.tsx
  src/pages/_app.tsx
  src/state/index.ts
  src/state/lists/actions.ts
  src/state/lists/hooks.ts
  src/state/lists/lists.ts
  src/state/lists/reducer.test.ts
  src/state/lists/reducer.ts
  src/state/lists/updater.ts
  src/utils/IndexedDBStorage.ts
Labels: size/L

#4612 chore: Clean up envs
  .env
  .env.development
  .env.production
  src/config/constants/endpoints.ts
  src/utils/graphql.ts
Labels: size/M

#4676 fix: Profile api env
  src/state/profile/helpers.ts
  src/views/TradingCompetition/EasterCompetition.tsx
  src/views/TradingCompetition/FanTokenCompetition.tsx
  src/views/TradingCompetition/MoDCompetition.tsx
  src/views/TradingCompetition/MoboxCompetition.tsx
  src/views/TradingCompetition/useCanClaimSpecialNFT.ts
  src/views/TradingCompetition/useTeamInformation.ts
Labels: size/M, automerge

#4675 fix: (farms): Use promise all in farm fetch
  packages/farms/src/fetchFarms.ts
Labels: size/S, automerge

#4680 chore: Bump stargate version
  apps/bridge/components/stargate/config.ts
  apps/bridge/pages/index.tsx
Labels: size/XS

#4679 fix(Pottery): Title use translations
  packages/localization/src/config/translations.json
  src/views/Pottery/components/Pot/index.tsx
Labels: size/XS, automerge

#4678 perf: (info): Use swr in useCmcLink hook to fetch url
  src/views/Info/hooks/useCMCLink.ts
Labels: size/S

#4677 feat(uikit): Wallet Modal generic
  package.json
  packages/uikit/src/components/Svg/index.tsx
  packages/uikit/src/widgets/WalletModal/ConnectModal.tsx
  packages/uikit/src/widgets/WalletModal/WalletCard.tsx
  packages/uikit/src/widgets/WalletModal/config.tsx
  packages/uikit/src/widgets/WalletModal/index.stories.tsx
  packages/uikit/src/widgets/WalletModal/index.tsx
  packages/uikit/src/widgets/WalletModal/types.ts
  packages/uikit/src/widgets/WalletModal/useWalletModal.tsx
  patches/@vanilla-extract+css+1.9.0.patch
  src/components/PageSection/index.tsx
  src/config/wallet.ts
  src/global.d.ts
  src/hooks/useAuth.tsx
  src/hooks/useSwitchNetwork.ts
  src/hooks/useWallet.ts
  src/views/Home/components/Hero.tsx
  src/views/Home/components/WedgeSvgs.tsx
  src/views/Home/index.tsx
  yarn.lock
Labels: size/XL

#4682 fix(bridge): Chain id update
  apps/bridge/components/Menu.tsx
  apps/bridge/components/stargate/network.ts
Labels: size/S

#4685 fix(trans): Typo Italian
  public/locales/it-IT.json
Labels: size/XS

#4687 chore: Close IFO
  src/config/constants/ifo.ts
Labels: size/XS, automerge

#4688 fix(uikit): import
  packages/uikit/src/components/Toast/Toast.tsx
Labels: size/XS

#4689 style: Fix ios IFO vesting card
  src/views/Ifos/components/IfoVesting/VestingPeriod/Expand.tsx
  src/views/Ifos/components/IfoVesting/index.tsx
Labels: size/XS, automerge

#4686 feat: List GQ
  packages/farms/constants/56.ts
  packages/tokens/src/56.ts
  public/images/tokens/0xF700D4c708C2be1463E355F337603183D20E0808.png
  src/config/constants/pools.tsx
Labels: size/S

#4639 perf: (limit): Use promise all when syncing graph queries to local storage
  src/views/LimitOrders/hooks/useGelatoLimitOrdersHistory.ts
Labels: size/M

#4640 perf: (lottery): Use promise all when fetching user tickets multiple rounds
  src/state/lottery/getUserTicketsData.ts
Labels: size/S

#4666 fix: (pools): Stake modal max sets to wrong value and balance shows staking limit instead of user balance when there is limit
  src/views/Pools/components/PoolCard/Modals/StakeModal.tsx
Labels: size/S

#4621 perf: (swap): Eliminate intermediate arrays in swap chart normalization
  src/state/swap/normalizers.ts
Labels: size/S

#4635 perf: (achievements): Reduce intermediate arrays when getting achievements
  src/state/achievements/helpers.ts
Labels: size/S

#4693 fix: hook import
  package.json
  packages/hooks/src/useInterval.ts
  packages/utils/copyText.ts
  packages/utils/isUndefinedOrNull.ts
  packages/utils/isZero.ts
  packages/utils/package.json
  packages/utils/replaceBrowserHistory.ts
  packages/utils/truncateHash.test.ts
  packages/utils/truncateHash.ts
  packages/utils/tryParseAmount.test.ts
  packages/utils/tryParseAmount.ts
  src/components/Balance.tsx
  src/components/CopyButton/index.tsx
  src/components/ErrorBoundary/SentryErrorBoundary.tsx
  src/components/SearchModal/ImportToken.tsx
  src/components/Toast/DescriptionWithTx.tsx
  src/hooks/limitOrders/useGasOverhead.ts
  src/hooks/useAccountEventListener.ts
  src/hooks/useAuth.tsx
  src/hooks/useSwapCallback.ts
  src/hooks/useSwitchNetwork.ts
  src/hooks/useWrapCallback.ts
  src/state/burn/hooks.ts
  src/state/farms/selectors.ts
  src/state/limitOrders/hooks.ts
  src/state/mint/hooks.ts
  src/state/swap/hooks.ts
  src/views/FarmAuction/components/WhitelistedBiddersModal.tsx
  src/views/Farms/components/YieldBooster/components/BoostedApr.tsx
  src/views/Farms/components/YieldBooster/helpers/splitProxyFarms.ts
  src/views/Farms/components/YieldBooster/hooks/useYieldBoosterState.ts
  src/views/Home/components/UserBanner/UserDetail.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoVestingCard/ReleasedTokenInfo.tsx
  src/views/Info/Tokens/TokenPage.tsx
  src/views/Info/components/InfoTables/TransactionsTable.tsx
  src/views/LimitOrders/index.tsx
  src/views/Nft/market/components/Activity/MobileModal.tsx
  src/views/Nft/market/components/ProfileCell.tsx
  src/views/PancakeSquad/components/Modals/Confirm/index.tsx
  src/views/Pools/components/LockedPool/Common/Overview/BalanceRow.tsx
  src/views/Pools/components/LockedPool/Common/Overview/TextRow.tsx
  src/views/Pools/components/LockedPool/LockedStakingApy.tsx
  src/views/Pools/components/LockedPool/hooks/useExtendEnable.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
  src/views/Pottery/components/FinishedRounds/AllHistoryCard/Winner.tsx
  src/views/Predictions/Leaderboard/components/Results/RankingCard.tsx
  src/views/Predictions/Leaderboard/components/Results/ResultAvatar.tsx
  src/views/Predictions/Leaderboard/components/WalletStatsModal.tsx
  src/views/Profile/components/ProfileHeader.tsx
  src/views/Swap/components/SwapModalHeader.tsx
  src/views/Swap/index.tsx
  src/views/TradingCompetition/components/TeamRanks/TopTradersCard/ExpandedGridItem.tsx
  src/views/TradingCompetition/components/TeamRanks/TopTradersCard/GridItem.tsx
  src/views/Voting/CreateProposal/index.tsx
  src/views/Voting/Proposal/Details.tsx
  src/views/Voting/components/Proposal/VoteRow.tsx
  turbo.json
Labels: size/L

#4692 feat: Farm add Skeleton effect
  src/views/Farms/components/FarmCard/CardActionsContainer.tsx
  src/views/Farms/components/FarmCard/CardHeading.tsx
  src/views/Farms/components/FarmTable/Farm.tsx
  src/views/Farms/components/FarmTable/FarmTable.tsx
  src/views/Farms/components/FarmTable/Row.tsx
  src/views/Farms/components/YieldBooster/components/BoostedApr.tsx
Labels: size/M

#4699 fix(farm): Show APR in calculator
  src/components/RoiCalculatorModal/RoiCalculatorFooter.tsx
Labels: size/XS

#4700 chore: Update Spin url
  packages/tokens/src/56.ts
Labels: size/S

#4704 revert: Refactor packages and add test
  .github/workflows/unitTests.yml
  package.json
  packages/hooks/src/index.ts
  packages/token-lists/package.json
  packages/token-lists/src/index.ts
  packages/token-lists/src/lists.ts
  packages/token-lists/src/reducer.ts
  packages/uikit/.storybook/main.js
  packages/uikit/.storybook/preview.jsx
  packages/uikit/babel.config.js
  packages/uikit/jest.config.js
  packages/uikit/package.json
  packages/uikit/src/__tests__/components/alert.test.tsx
  packages/uikit/src/__tests__/components/balanceinput.test.tsx
  packages/uikit/src/__tests__/components/breadcrumbs.test.tsx
  packages/uikit/src/__tests__/components/button.test.tsx
  packages/uikit/src/__tests__/components/buttonmenu.test.tsx
  packages/uikit/src/__tests__/components/card.test.tsx
  packages/uikit/src/__tests__/components/checkbox.test.tsx
  packages/uikit/src/__tests__/components/dropdown.test.tsx
  packages/uikit/src/__tests__/components/fallingbunnies.test.tsx
  packages/uikit/src/__tests__/components/heading.test.tsx
  packages/uikit/src/__tests__/components/input.test.tsx
  packages/uikit/src/__tests__/components/link.test.tsx
  packages/uikit/src/__tests__/components/notificationdot.test.tsx
  packages/uikit/src/__tests__/components/overlay.test.tsx
  packages/uikit/src/__tests__/components/pancaketoggle.test.tsx
  packages/uikit/src/__tests__/components/progress.test.tsx
  packages/uikit/src/__tests__/components/radio.test.tsx
  packages/uikit/src/__tests__/components/skeleton.test.tsx
  packages/uikit/src/__tests__/components/spinner.test.tsx
  packages/uikit/src/__tests__/components/svg.test.tsx
  packages/uikit/src/__tests__/components/tabmenu.test.tsx
  packages/uikit/src/__tests__/components/tag.test.tsx
  packages/uikit/src/__tests__/components/text.test.tsx
  packages/uikit/src/__tests__/components/toggle.test.tsx
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/__tests__/widgets/modal.test.tsx
  packages/uikit/src/__tests__/widgets/walletModal.test.tsx
  packages/uikit/tsconfig.json
  src/__tests__/utils/uriToHttp.test.ts
  src/components/SearchModal/ImportList.tsx
  src/components/SearchModal/ManageLists.tsx
  src/hooks/useFetchListCallback.ts
  src/hooks/useHttpLocations.ts
  src/hooks/useInterval.ts
  src/hooks/useIsWindowVisible.ts
  src/state/lists/actions.ts
  src/state/lists/hooks.ts
  src/state/lists/lists.ts
  src/state/lists/reducer.test.ts
  src/state/lists/reducer.ts
  src/state/lists/updater.ts
  src/utils/getTokenList.ts
  src/utils/uriToHttp.ts
  src/views/Ifos/components/IfoFoldableCard/index.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/shared/DetailsCard.tsx
  src/views/Pools/components/LockedPool/Common/BurningCountDown.tsx
  src/views/Predictions/hooks/useCountdown.ts
  yarn.lock
Labels: size/XXL

#4710 fix(farm): Display wrong USDC value
  packages/farms/src/farmPrices.ts
Labels: size/XS

#4713 chore: (pools): Remove redundant await
  src/state/pools/index.ts
Labels: size/XS

#4716 revert: "revert: Refactor packages and add test"
  .github/workflows/unitTests.yml
  package.json
  packages/hooks/src/index.ts
  packages/hooks/src/useInterval.ts
  packages/hooks/src/useIsWindowVisible.ts
  packages/token-lists/package.json
  packages/token-lists/src/actions.ts
  packages/token-lists/src/getTokenList.ts
  packages/token-lists/src/index.ts
  packages/token-lists/src/lists.ts
  packages/token-lists/src/reducer.test.ts
  packages/token-lists/src/reducer.ts
  packages/token-lists/src/useFetchListCallback.ts
  packages/uikit/.storybook/main.js
  packages/uikit/.storybook/preview.jsx
  packages/uikit/babel.config.js
  packages/uikit/jest.config.js
  packages/uikit/package.json
  packages/uikit/src/__tests__/components/alert.test.tsx
  packages/uikit/src/__tests__/components/balanceinput.test.tsx
  packages/uikit/src/__tests__/components/breadcrumbs.test.tsx
  packages/uikit/src/__tests__/components/button.test.tsx
  packages/uikit/src/__tests__/components/buttonmenu.test.tsx
  packages/uikit/src/__tests__/components/card.test.tsx
  packages/uikit/src/__tests__/components/checkbox.test.tsx
  packages/uikit/src/__tests__/components/dropdown.test.tsx
  packages/uikit/src/__tests__/components/fallingbunnies.test.tsx
  packages/uikit/src/__tests__/components/heading.test.tsx
  packages/uikit/src/__tests__/components/input.test.tsx
  packages/uikit/src/__tests__/components/link.test.tsx
  packages/uikit/src/__tests__/components/notificationdot.test.tsx
  packages/uikit/src/__tests__/components/overlay.test.tsx
  packages/uikit/src/__tests__/components/pancaketoggle.test.tsx
  packages/uikit/src/__tests__/components/progress.test.tsx
  packages/uikit/src/__tests__/components/radio.test.tsx
  packages/uikit/src/__tests__/components/skeleton.test.tsx
  packages/uikit/src/__tests__/components/spinner.test.tsx
  packages/uikit/src/__tests__/components/svg.test.tsx
  packages/uikit/src/__tests__/components/tabmenu.test.tsx
  packages/uikit/src/__tests__/components/tag.test.tsx
  packages/uikit/src/__tests__/components/text.test.tsx
  packages/uikit/src/__tests__/components/toggle.test.tsx
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/__tests__/widgets/modal.test.tsx
  packages/uikit/src/__tests__/widgets/walletModal.test.tsx
  packages/uikit/tsconfig.json
  packages/utils/uriToHttp.test.ts
  packages/utils/uriToHttp.ts
  src/components/SearchModal/ImportList.tsx
  src/components/SearchModal/ManageLists.tsx
  src/hooks/useHttpLocations.ts
  src/state/lists/hooks.ts
  src/state/lists/lists.ts
  src/state/lists/reducer.ts
  src/state/lists/updater.ts
  src/views/Ifos/components/IfoFoldableCard/index.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/shared/DetailsCard.tsx
  src/views/Pools/components/LockedPool/Common/BurningCountDown.tsx
  src/views/Predictions/hooks/useCountdown.ts
  yarn.lock
Labels: size/XXL

#4714 chore(farm): Restyle tooltip text in boosted farm
  packages/localization/src/config/translations.json
  src/views/Farms/components/FarmCard/ApyButton.tsx
Labels: size/S

#4722 chore: Use inline null check for callbacks
  src/views/Predictions/components/CollectRoundWinningsModal.tsx
  src/views/Predictions/components/ReclaimPositionButton.tsx
  src/views/Profile/components/Achievements/ClaimPointsCallout.tsx
  src/views/Profile/components/EditProfileModal/ChangeProfilePicView.tsx
  src/views/Profile/components/EditProfileModal/PauseProfileView.tsx
  src/views/Profile/components/ProfileHeader.tsx
  src/views/Voting/Proposal/Vote.tsx
Labels: size/M

#4721 fix: (ifo): Fix ifo function properties return type
  src/views/Ifos/types.ts
Labels: size/XS

#4711 perf: (farms): Don't fetch farm user data until proxy address fetched and dont fetch proxy farm data when proxy is not created
  src/state/farms/hooks.ts
Labels: size/XS

#4695 fix(Farm): CardView APR use tooltipText
  src/views/Farms/components/FarmCard/FarmCard.tsx
Labels: size/XS

#4701 feat(farms): Show Boosted APR of address
  packages/localization/src/config/translations.json
  src/views/Farms/components/FarmCard/ApyButton.tsx
Labels: size/S

#4720 fix: Add missing translations in error toasts
  packages/localization/src/config/translations.json
  src/components/ClaimNftModal/ClaimNftModal.tsx
  src/hooks/useCatchTxError.tsx
Labels: size/S

#4728 fix: Changes on logic files cause pr to run farm config workflow
  .github/workflows/farmConfig.yml
Labels: size/XS

#4726 fix: PollFarmsWithUserData not fetch data when chainId is not BSC
  packages/farms/src/index.ts
  src/state/farms/hooks.ts
  src/views/Farms/components/BCakeBoosterCard.tsx
  src/views/Farms/components/BCakeMigrateModal.tsx
  src/views/Farms/components/YieldBooster/hooks/useProxyCAKEBalance.ts
  src/views/Farms/components/YieldBooster/hooks/useProxyStakedActions.ts
  src/views/Farms/components/YieldBooster/hooks/useYieldBoosterState.ts
  src/views/Farms/hooks/useBCakeProxyContractAddress.ts
Labels: size/M

#4696 fix: Do not remove transactions in local storage when chain change and handle multiple chains
  src/components/App/Transactions/Transaction.tsx
  src/components/App/Transactions/TransactionsModal.tsx
  src/components/Menu/UserMenu/TransactionRow.tsx
  src/components/Menu/UserMenu/WalletTransactions.tsx
  src/hooks/useAccountEventListener.ts
  src/hooks/useAuth.tsx
  src/state/global/actions.ts
  src/state/transactions/actions.ts
  src/state/transactions/hooks.tsx
  src/state/transactions/reducer.test.ts
  src/state/transactions/reducer.ts
  src/state/transactions/updater.tsx
  src/utils/clearUserStates.ts
Labels: size/L

#4731 ci: Only publish when repo owner is pancakeswap
  .github/workflows/farmConfig.yml
Labels: size/XS

#4732 ci: Fix farmConfig jobs if
  .github/workflows/farmConfig.yml
Labels: size/S

#4734 ci: Add paths back [skip-ci]
  .github/workflows/farmConfig.yml
Labels: size/S

#4735 perf: WalletTransactions add key
  src/components/Menu/UserMenu/WalletTransactions.tsx
Labels: size/XS, automerge

#4739 refactor: Use block explorer name from package
  src/utils/index.ts
Labels: size/XS

#4740 refactor: Remove deprecated getGasPrice and use hook and fix gas settings not applied to the transactions when changed
  src/utils/getGasPrice.ts
  src/views/Migration/hook/V1/Farms/useUnstakeFarms.ts
  src/views/Migration/hook/V1/Pool/useUnstakePool.ts
  src/views/Pools/hooks/useHarvestPool.ts
  src/views/Pools/hooks/useStakePool.ts
  src/views/Pools/hooks/useUnstakePool.ts
Labels: size/M

#4741 refactor: Remove deprecated serialize token
  packages/tokens/src/helpers.ts
Labels: size/S

#4727 fix: (currency-search): Currency search handle enter keyboard event for native currency of different chains
  src/components/SearchModal/CurrencySearch.tsx
Labels: size/XS

#4742 fix: useHover hook
  src/hooks/useHover.ts
Labels: size/M

#4737 fix: Farmconfig workflow excluded files paths
  .github/workflows/farmConfig.yml
Labels: size/XS

#4736 chore: fix shouldUseProxyFarm issue
  src/views/Farms/components/YieldBooster/hooks/useYieldBoosterState.ts
Labels: size/S

#4747 style: Modal Actions css
  src/components/Modal/ModalActions.tsx
Labels: size/XS, automerge

#4748 feat: List farm auction 30 winners
  packages/farms/constants/56.ts
Labels: size/S, automerge

#4751 fix: Transaction list order
  src/state/transactions/hooks.tsx
Labels: size/M

#4750 style: WalletTransactions add scrollbar
  src/components/Menu/UserMenu/WalletTransactions.tsx
Labels: size/M

#4752 feat: BCakeCalculator
  packages/localization/src/config/translations.json
  src/components/RoiCalculatorModal/BCakeCalculator.tsx
  src/components/RoiCalculatorModal/BCakeLockedDuration.tsx
  src/components/RoiCalculatorModal/index.tsx
  src/state/pools/hooks.ts
  src/views/Farms/components/BCakeBoosterCard.tsx
  src/views/Farms/components/DepositModal.tsx
  src/views/Farms/components/FarmCard/ApyButton.tsx
  src/views/Farms/components/FarmCard/FarmCard.tsx
  src/views/Farms/components/FarmCard/StakeAction.tsx
  src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
  src/views/Farms/components/FarmTable/Apr.tsx
  src/views/Farms/components/FarmTable/FarmTable.tsx
  src/views/Farms/components/FarmTable/Row.tsx
  src/views/Farms/hooks/useUserLockedCakeStatus.ts
  src/views/Migration/components/MigrationStep2/NewFarm/StakeButton.tsx
Labels: size/XL

#4749 feat: activate the new boost farm
  packages/farms/constants/56.ts
Labels: size/XS

#4756 fix(wallet): Binance wallet auto connect
  packages/wagmi/connectors/binanceWallet/binanceWallet.ts
Labels: size/S

#4759 chore: Update current emissions
  src/views/Home/components/CakeDataRow.tsx
Labels: size/XS, automerge

#4755 chore: farm list order adjustment for BCake
  packages/farms/constants/56.ts
Labels: size/M

#4758 feat: List MONI farms and pools
  packages/farms/constants/56.ts
  src/components/RoiCalculatorModal/index.tsx
  src/config/constants/pools.tsx
  src/views/Farms/components/DepositModal.tsx
Labels: size/S

#4754 fix(bcake): Update showing Migrate logic
  src/views/Farms/components/YieldBooster/hooks/useYieldBoosterState.ts
Labels: size/S

#4765 feat(ifo): Add HOOP cIFO
  packages/tokens/src/56.ts
  packages/uikit/src/components/Image/Image.tsx
  packages/uikit/src/components/Image/types.ts
  public/images/achievements/ifo-placeholder-bun.png
  public/images/ifos/hoop-bg.png
  public/images/tokens/0xF19cfb40B3774dF6Eed83169Ad5aB0Aaf6865F25.png
  src/config/constants/campaigns.ts
  src/config/constants/ifo.ts
  src/views/Ifos/components/IfoFoldableCard/Achievement.tsx
Labels: size/M

#4766 fix: cifo requirements
  src/views/Ifos/hooks/v3/useGetPublicIfoData.ts
  src/views/Ifos/types.ts
Labels: size/XS, automerge

#4764 refactor: (pools): Remove compound props from pools
  packages/localization/src/config/translations.json
  src/views/Pools/components/PoolCard/CardActions/HarvestActions.tsx
  src/views/Pools/components/PoolCard/Modals/CollectModal.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/Harvest.tsx
  src/views/Pools/components/PoolsTable/Cells/EarningsCell.tsx
Labels: size/M

#4763 fix: (pools): Balance in stake modal when withdraw
  src/views/Pools/components/PoolCard/Modals/StakeModal.tsx
Labels: size/XS

#4771 chore(liquidity): Return farmconfig in farm list
  src/state/user/hooks/index.tsx
Labels: size/XS

#4761 perf: Fetch cake pools user data only in fetch ifo hook
  src/state/pools/hooks.ts
Labels: size/XS

#4762 fix: Tooltip text decoration not visible in safari
  packages/uikit/src/components/Text/TooltipText.tsx
Labels: size/XS

#4743 chore: Bump up swiper
  package.json
  yarn.lock
Labels: size/S

#4760 fix(voting): Cake locked amount in tooltip
  packages/multicall/index.ts
  src/views/Voting/helpers.ts
  src/views/Voting/strategies.ts
Labels: size/L

#4778 chore(ifo): Update hoop image
  public/images/achievements/ifo-hoop.svg
  public/images/ifos/hoop-bg.png
Labels: size/S

#4780 perf: (vesting): Don't call current timestamp on each loop
  src/views/Ifos/hooks/vesting/useFetchVestingData.ts
Labels: size/XS

#4773 feat: IFO card title
  src/config/constants/ifo.ts
  src/config/constants/types.ts
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/index.tsx
Labels: size/XS

#4784 feat: farm adjustment related to BCake calculator
  packages/localization/src/config/translations.json
  src/components/RoiCalculatorModal/BCakeCalculator.tsx
  src/components/RoiCalculatorModal/BCakeLockedDuration.tsx
  src/views/Farms/components/FarmCard/ApyButton.tsx
  src/views/Farms/components/FarmCard/CardActionsContainer.tsx
  src/views/Farms/components/FarmCard/FarmCard.tsx
  src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  src/views/Farms/components/FarmTable/Row.tsx
  src/views/Farms/components/YieldBooster/components/BoostedAction.tsx
  src/views/Farms/components/YieldBooster/components/BoostedApr.tsx
  src/views/Farms/components/YieldBooster/hooks/useGetBoostedAPR.ts
Labels: size/L

#4791 chore: Remove nodereal provider
  apis/farms/src/provider.ts
Labels: size/XS

#4790 revert: Cake locked amount in tooltip
  packages/multicall/index.ts
  src/views/Voting/helpers.ts
  src/views/Voting/strategies.ts
Labels: size/L

#4786 fix: Memoize selector to avoid infinite renders
  src/hooks/Tokens.ts
  src/state/user/hooks/useUserAddedTokens.ts
Labels: size/S

#4787 perf: Use mapValues instead of entries and fromPairs in list token map
  src/state/lists/hooks.ts
Labels: size/S

#4781 perf: (ifo): Reduce calculations in fetch vesting data
  src/views/Ifos/hooks/vesting/useFetchVestingData.ts
Labels: size/M

#4793 revert: "revert: Cake locked amount in tooltip"
  packages/multicall/index.ts
  src/views/Voting/helpers.ts
  src/views/Voting/strategies.ts
Labels: size/L

#4733 chore(stableswap): Add Stable Farm logic
  apis/farms/src/lpApr.ts
  packages/farms/src/types.ts
  scripts/updateLPsAPR.ts
  src/components/Tags.tsx
  src/config/constants/endpoints.ts
  src/state/farms/index.ts
  src/state/farms/selectors.ts
  src/state/types.ts
  src/utils/graphql.ts
  src/views/AddLiquidity/AddStableLiquidity/hooks/useStableLPDerivedMintInfo.tsx
  src/views/AddLiquidity/AddStableLiquidity/index.tsx
  src/views/AddLiquidity/components/ConfirmAddLiquidityModal.tsx
  src/views/Farms/components/FarmTable/Farm.tsx
  src/views/Farms/components/FarmTable/FarmTable.tsx
  src/views/Swap/StableSwap/hooks/useStableSwapCallArgs.ts
  src/views/Swap/StableSwap/hooks/useStableTradeExactIn.ts
Labels: size/L

#4789 refactor: bCake calculator
  src/views/Farms/components/DepositModal.tsx
  src/views/Farms/components/FarmCard/ApyButton.tsx
  src/views/Farms/components/YieldBooster/components/BCakeCalculator.tsx
  src/views/Farms/components/YieldBooster/components/BCakeLockedDuration.tsx
  src/views/Farms/components/YieldBooster/hooks/useGetBoostedAPR.ts
  src/views/Pools/components/utils/formatSecondsToWeeks.ts
Labels: size/L

#4796 chore: Add missing translation key
  packages/localization/src/config/translations.json
Labels: size/XS

#4797 fix: (farms): Memoize farm selector to avoid infinite rerenders
  src/state/farms/hooks.ts
Labels: size/XS

#4799 fix: Avoid isToken undefined
  src/hooks/useBUSDPrice.ts
Labels: size/XS

#4800 chore: Upgrade prettier
  package.json
  packages/tokens/src/helpers.ts
  src/components/Menu/config/config.ts
  src/state/limitOrders/actions.ts
  src/state/limitOrders/hooks.ts
  src/state/swap/actions.ts
  src/state/swap/hooks.ts
  src/state/transactions/actions.ts
  src/state/user/actions.ts
  src/views/AddLiquidity/components/ConfirmAddLiquidityModal.tsx
  src/views/FarmAuction/components/NotWhitelistedNotice.tsx
  src/views/Lottery/components/PreviousRoundCard/Body.tsx
  src/views/Lottery/components/PreviousRoundCard/FooterExpanded.tsx
  src/views/TradingCompetition/Footer.tsx
  src/views/TradingCompetition/components/TeamRanks/TopTradersCard/ExpandedGridItem.tsx
  yarn.lock
Labels: size/XXL

#4757 feat(anniversary): Add 2nd anniversary claiming modal
  packages/localization/src/config/translations.json
  public/images/achievements/2-year.svg
  src/components/GlobalCheckClaimStatus/AnniversaryAchievementModal.tsx
  src/components/GlobalCheckClaimStatus/GalaxyNFTClaimModal.tsx
  src/components/GlobalCheckClaimStatus/index.tsx
  src/config/abi/anniversaryAchievement.json
  src/config/constants/campaigns.ts
  src/config/constants/contracts.ts
Labels: size/L

#4803 chore: Update Next and use remotePatterns for strict safety
  apps/bridge/components/Menu.tsx
  apps/bridge/next.config.mjs
  apps/bridge/package.json
  next.config.js
  package.json
  src/components/Logo/ChainLogo.tsx
  src/pages/_app.tsx
  yarn.lock
Labels: size/L

#4804 feat: navigate to profile after claim
  src/components/GlobalCheckClaimStatus/AnniversaryAchievementModal.tsx
Labels: size/XS

#4806 chore(stableswap): Add HAY-BUSD
  apis/farms/src/lpApr.ts
  packages/farms/constants/56.ts
  packages/farms/constants/index.ts
  src/components/PositionCard/index.tsx
  src/config/__tests__/farms.test.ts
  src/config/constants/endpoints.ts
  src/pages/remove/[[...currency]].tsx
  src/views/Pool/index.tsx
  src/views/Swap/index.tsx
Labels: size/M

#4808 chore(StableSwap): Add desc translation
  packages/localization/src/config/translations.json
  src/views/Swap/StableSwap/components/StableSwapForm.tsx
Labels: size/XS

#4811 chore: Close hoop ifo
  src/config/constants/ifo.ts
Labels: size/XS

#4814 chore(farms): Launch stable LP farm
  packages/farms/constants/56.ts
  packages/farms/src/fetchFarms.ts
  src/views/Farms/Farms.tsx
Labels: size/S

#4818 chore(stableswap): Update style
  src/components/Tags.tsx
Labels: size/XS

#4819 chore(stableswap): Add StableTag in card view
  src/components/Tags.tsx
  src/views/Farms/components/FarmCard/CardHeading.tsx
  src/views/Farms/components/FarmCard/FarmCard.tsx
  src/views/Farms/components/FarmTable/Farm.tsx
Labels: size/S

#4821 fix(stableswap): Use pid to lptoken price
  packages/farms/src/types.ts
  src/state/farms/hooks.ts
  src/state/farms/selectors.ts
  src/views/Farms/components/FarmCard/StakeAction.tsx
  src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
  src/views/Farms/components/StakedLP.tsx
Labels: size/S

#4825 Fix: Update farm test
  src/config/__tests__/farms.test.ts
Labels: size/XS

#4817 refactor: (pools): Move common pool modals from pools card to components
  src/views/Pools/components/CakeVaultCard/VaultCardActions/HasSharesActions.tsx
  src/views/Pools/components/CakeVaultCard/VaultCardActions/VaultStakeActions.tsx
  src/views/Pools/components/LockedPool/Buttons/AddCakeButton.tsx
  src/views/Pools/components/Modals/CollectModal.tsx
  src/views/Pools/components/Modals/NotEnoughTokensModal.tsx
  src/views/Pools/components/Modals/PercentageButton.tsx
  src/views/Pools/components/Modals/StakeModal.tsx
  src/views/Pools/components/PoolCard/CardActions/HarvestActions.tsx
  src/views/Pools/components/PoolCard/CardActions/StakeActions.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/Harvest.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
  src/views/Pools/components/PoolsTable/Cells/EarningsCell.tsx
Labels: size/S

#4822 refactor: Use farm lptoken price property
  src/state/farms/hooks.ts
  src/state/farms/selectors.ts
  src/state/types.ts
  src/views/Farms/components/FarmCard/ApyButton.tsx
  src/views/Farms/components/FarmCard/FarmCard.tsx
  src/views/Farms/components/FarmCard/StakeAction.tsx
  src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
  src/views/Farms/components/FarmTable/Apr.tsx
  src/views/Farms/components/FarmTable/FarmTable.tsx
  src/views/Farms/components/StakedLP.tsx
  src/views/Migration/components/MigrationFarmTable.tsx
  src/views/Migration/components/MigrationStep2/NewFarm/StakeButton.tsx
Labels: size/M

#4810 fix: (claim): Success toast appears before transaction is successful
  src/components/GlobalCheckClaimStatus/index.tsx
Labels: size/S

#4776 perf: (refresh hook): Don't read & write swr cache when chainid is undefined
  src/hooks/useRefreshEffect.ts
  src/state/block/hooks.ts
Labels: size/S

#4782 feat: (swap): Add scanning risks for input token
  src/state/lists/hooks.ts
  src/views/Swap/components/AccessRisk/RiskMessage.tsx
  src/views/Swap/components/AccessRisk/index.tsx
  src/views/Swap/components/SwapForm.tsx
Labels: size/L

#4634 perf: (teams): Reduce memory footprint
  src/state/teams/helpers.ts
Labels: size/M

#4820 perf: Use memoized decimal multiplier
  packages/farms/src/const.ts
  packages/farms/src/fetchFarms.ts
  packages/farms/src/getFullDecimalMultiplier.ts
  src/config/index.ts
  src/views/Farms/components/YieldBooster/components/BCakeCalculator.tsx
  src/views/Pools/components/LockedPool/hooks/useAvgLockDuration.tsx
  src/views/Pottery/components/Pot/Deposit/DepositAction.tsx
  src/views/Pottery/components/Pot/Deposit/DepositButton.tsx
  src/views/Pottery/hooks/useDepositPottery.tsx
  src/views/Pottery/hooks/useWinRateCalculator.tsx
Labels: size/M

#4826 feat: Add vote now tag to voting menu link if there is active proposal
  src/components/Menu/hooks/useMenuItemsStatus.ts
  src/components/Menu/hooks/useVotingStatus.ts
Labels: size/M

#4827 feat: (voting): Use only core proposals to put tag on voting link
  src/components/Menu/hooks/useVotingStatus.ts
Labels: size/S

#4828 feat: List CO IFO
  packages/tokens/src/56.ts
  public/images/achievements/ifo-co.svg
  public/images/ifos/co-bg.png
  public/images/tokens/0x936B6659Ad0C1b244Ba8Efe639092acae30dc8d6.png
  src/config/constants/campaigns.ts
  src/config/constants/ifo.ts
Labels: size/M

#4823 fix: Flexible cake withdraw bug
  src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
Labels: size/S

#4832 fix: Key warning in common bases component
  src/components/SearchModal/CommonBases.tsx
Labels: size/XS

#4805 chore: Update wagmi
  apps/bridge/package.json
  package.json
  yarn.lock
Labels: size/L

#4815 chore: Update farm auction wording
  packages/localization/src/config/translations.json
  src/views/FarmAuction/index.tsx
Labels: size/XS, automerge

#4833 chore(bridge): Remove fee from ui
  apps/bridge/components/stargate/config.ts
Labels: size/XS

#4834 feat: Support multichain in transaction updater
  src/components/Toast/DescriptionWithTx.tsx
  src/index.tsx
  src/state/transactions/hooks.tsx
  src/state/transactions/updater.test.ts
  src/state/transactions/updater.tsx
Labels: size/L

#4830 feat(IFO): Add bscscan countdown and under 1 mins to show "< 1m"
  src/views/Ifos/components/IfoFoldableCard/Timer.tsx
Labels: size/S

#4838 perf: Global claim only run in BSC chain
  src/components/GlobalCheckClaimStatus/index.tsx
Labels: size/XS

#4836 feat(SwapTab): Optimize UI
  src/views/Swap/components/SwapTab.tsx
Labels: size/M

#4840 feat: Add Message at Edit Profile
  packages/localization/src/config/translations.json
  src/views/Profile/components/EditProfileModal/StartView.tsx
Labels: size/S, automerge

#4841 feat: Enable eth
  packages/localization/src/config/translations.json
  packages/swap-sdk/src/constants.ts
  packages/tokens/src/common.ts
  packages/wagmi/src/useWeb3React.ts
  src/components/GlobalCheckClaimStatus/index.tsx
  src/components/Menu/UserMenu/WalletInfo.tsx
  src/components/Menu/UserMenu/WalletModal.tsx
  src/components/Menu/UserMenu/WalletWrongNetwork.tsx
  src/components/Menu/config/config.ts
  src/components/NetworkModal/NetworkModal.tsx
  src/components/NetworkModal/PageNetworkSupportModal.tsx
  src/components/NetworkModal/UnsupportedNetworkModal.tsx
  src/components/NetworkModal/WrongNetworkModal.tsx
  src/components/NetworkSwitcher.tsx
  src/components/SearchModal/ImportToken.tsx
  src/config/constants/exchange.ts
  src/config/constants/tokenLists/pancake-default.tokenlist.json
  src/hooks/useActiveWeb3React.ts
  src/hooks/useSwitchNetwork.ts
  src/utils/wagmi.ts
  src/views/AddLiquidity/ChoosePair.tsx
  src/views/AddLiquidity/index.tsx
  src/views/Home/index.tsx
  src/views/RemoveLiquidity/index.tsx
Labels: size/L

#4844 perf: Perpetual only support bsc
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/components/DropdownMenu/DropdownMenu.tsx
  packages/uikit/src/components/DropdownMenu/styles.tsx
  packages/uikit/src/components/MenuItem/styles.tsx
  packages/uikit/src/widgets/Menu/components/UserMenu/styles.tsx
  src/components/Menu/config/config.ts
  src/components/Menu/hooks/useMenuItemsStatus.ts
Labels: size/S, automerge

#4847 feat: Remove pointer-events
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/components/DropdownMenu/styles.tsx
  packages/uikit/src/components/MenuItem/styles.tsx
  packages/uikit/src/widgets/Menu/components/UserMenu/styles.tsx
Labels: size/XS, automerge

#4850 chore(ifo): Add cIFO FAQ
  packages/localization/src/config/translations.json
  src/views/Ifos/components/IfoQuestions/config.tsx
Labels: size/S

#4852 chore: Change HAY token name
  packages/tokens/src/56.ts
Labels: size/XS, automerge

#4843 refactor: (voting): Remove space data from proposal/vote fetch
  src/state/types.ts
  src/state/voting/helpers.ts
Labels: size/S

#4856 feat: List farm auction 31
  src/config/constants/farmAuctions.ts
Labels: size/XS

#4853 fix: (expert-mode): Expert mode modal width in desktop and remove maxWidth property from modals
  packages/uikit/src/__tests__/widgets/modal.test.tsx
  packages/uikit/src/__tests__/widgets/walletModal.test.tsx
  packages/uikit/src/widgets/Modal/styles.tsx
  src/components/Menu/GlobalSettings/ExpertModal.tsx
  src/components/Menu/GlobalSettings/SettingsModal.tsx
  src/components/UnsupportedCurrencyFooter.tsx
  src/views/Nft/market/components/Activity/MobileModal.tsx
  src/views/Pools/components/LockedPool/Modals/AddAmountModal.tsx
Labels: size/M

#4831 fix: User can click claim in vesting card when isVestingInitialized false
  src/views/Ifos/components/IfoVesting/VestingPeriod/Claim.tsx
  src/views/Ifos/components/IfoVesting/VestingPeriod/Info.tsx
  src/views/Ifos/hooks/vesting/fetchUserWalletIfoData.ts
Labels: size/M, automerge

#4851 feat: Vesting weeks to days
  packages/localization/src/config/translations.json
  public/locales/ru-RU.json
  src/utils/getTimePeriods.ts
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
Labels: size/S, automerge

#4777 perf: (ifo): Reduce calls to onchain
  src/state/pools/hooks.ts
  src/views/Ifos/components/IfoFoldableCard/index.tsx
Labels: size/M
