Repository pancakeswap/pancake-frontend, pull requests merged in 2022-07, with the labels that each got.

#4175 chore: Temp hide lp aprs
  src/state/swap/hooks.ts
Labels: size/M

#4166 feat: PerpetualLangs add japanese
  src/utils/getPerpetualLanguageCode.ts
Labels: size/XS, automerge

#4181 chore: Clean unused var
  src/state/swap/hooks.ts
Labels: size/S

#4182 fix: (prediction): Charts in small size mobile phones
  src/views/Predictions/MobileChart.tsx
  src/views/Predictions/components/Container.tsx
Labels: size/M

#4184 refactor: Remove setting default tooltip option
  src/components/QuestionHelper/index.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IFORequirements.tsx
Labels: size/XS

#4183 refactor: Add bnb suffix to prediction config
  .env.development
  .env.production
  src/config/constants/contracts.ts
  src/config/constants/endpoints.ts
  src/state/predictions/helpers.ts
  src/utils/addressHelpers.ts
  src/views/Predictions/context/config.ts
Labels: size/S

#4178 perf: Stop swiper slide autoplay on mouse enter and start autoplay on mouse leave
  src/views/Home/components/Banners/MultipleBanner.tsx
Labels: size/XS, automerge

#4168 perf: Use batched updates in pool hooks
  src/state/pools/hooks.ts
  src/views/Migration/components/MigrationStep2/NewPool/index.tsx
Labels: size/S

#4153 perf: Use ProfileAvatar component
  src/views/Nft/market/components/ProfileCell.tsx
  src/views/TradingCompetition/components/TeamRanks/TopTradersCard/ExpandedGridItem.tsx
  src/views/TradingCompetition/components/TeamRanks/TopTradersCard/GridItem.tsx
Labels: size/M, automerge

#4152 style: Trading competition countdown
  src/views/TradingCompetition/components/Countdown/index.tsx
Labels: size/XS, automerge

#4142 perf: Use memo in page section and inline functions
  src/components/PageSection/CurvedDivider.tsx
  src/components/PageSection/index.tsx
Labels: size/S

#3992 perf: Run lists updater only when the page has currency search
  src/hooks/useInterval.ts
  src/state/lists/updater.ts
Labels: size/M

#4180 chore(pools): Avoid fetching all farms in pools
  src/config/constants/pools.tsx
  src/state/pools/hooks.ts
Labels: size/S

#4186 perf: Separate label price countup from label component to reduce rerender
  src/views/Predictions/components/Label.tsx
  src/views/Predictions/components/LabelPrice.tsx
  src/views/Predictions/components/RoundCard/LiveRoundPrice.tsx
Labels: size/M

#4185 feat: Use 4 digit precision when showing prediction price difference
  src/__tests__/views/predictions/helpers.test.ts
  src/state/types.ts
  src/views/Predictions/components/RoundCard/LiveRoundCard.tsx
  src/views/Predictions/components/RoundResult/styles.tsx
  src/views/Predictions/context/config.ts
  src/views/Predictions/helpers.ts
Labels: size/S

#4177 fix: (prediction): Error & pause notification Back button not visible in mobile when screen size is small
  src/views/Predictions/components/Notification/Notification.tsx
Labels: size/S

#4188 fix: Avoid undefined of autoplay error
  src/views/Home/components/Banners/MultipleBanner.tsx
Labels: size/XS

#4189 perf: Use textTransform
  src/views/TradingCompetition/components/Countdown/ProgressStepper.tsx
  src/views/TradingCompetition/components/Countdown/Step.tsx
Labels: size/S, automerge

#4032 feat: Zap
  cypress/integration/exchange/add-liquidity.test.ts
  packages/uikit/package.json
  packages/uikit/src/components/Box/Box.tsx
  packages/uikit/src/components/Box/types.ts
  packages/uikit/src/components/CoinSwitcher/index.stories.tsx
  src/components/App/AppHeader.tsx
  src/components/App/Transactions/index.tsx
  src/components/CurrencyInputPanel/ZapCheckbox.tsx
  src/components/CurrencyInputPanel/index.tsx
  src/components/CurrencySelect/index.tsx
  src/components/Layout/Row.tsx
  src/components/Menu/GlobalSettings/SettingsModal.tsx
  src/components/PositionCard/index.tsx
  src/components/SearchModal/CurrencySearchModal.tsx
  src/components/TransactionConfirmationModal/index.tsx
  src/config/abi/zap.json
  src/config/constants/contracts.ts
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
  src/config/localization/translations.json
  src/hooks/useBUSDPrice.ts
  src/hooks/useContract.ts
  src/hooks/usePreviousValue.ts
  src/hooks/useSWRContract.ts
  src/hooks/useTokenBalance.ts
  src/state/burn/hooks.ts
  src/state/mint/hooks.ts
  src/state/user/actions.ts
  src/state/user/hooks/index.tsx
  src/state/user/reducer.ts
  src/utils/addressHelpers.ts
  src/utils/calls/estimateGas.ts
  src/utils/contractHelpers.ts
  src/utils/getLpSymbol.ts
  src/utils/index.ts
  src/utils/prices.ts
  src/utils/types.ts
  src/views/AddLiquidity/ChoosePair.tsx
  src/views/AddLiquidity/ConfirmAddModalBottom.tsx
  src/views/AddLiquidity/components/ConfirmAddLiquidityModal.tsx
  src/views/AddLiquidity/components/ConfirmZapInModal.tsx
  src/views/AddLiquidity/components/ZapErrorMessage.tsx
  src/views/AddLiquidity/components/common.tsx
  src/views/AddLiquidity/index.tsx
  src/views/AddLiquidity/useCurrencySelectRoute.ts
  src/views/Predictions/components/PositionTag.tsx
  src/views/RemoveLiquidity/index.tsx
  src/views/Swap/components/ConfirmRemoveLiquidityModal.tsx
  yarn.lock
Labels: size/XXL

#4187 feat: List SDAO
  public/images/tokens/0x90Ed8F1dc86388f14b64ba8fb4bbd23099f18240.png
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
Labels: size/M, automerge

#4190 fix: Add liquidity overview page to the token list fetchers
  src/state/lists/updater.ts
Labels: size/XS

#4193 fix: Position tag background
  src/views/Predictions/components/PositionTag.tsx
Labels: size/S

#4195 fix: Zap token amount optional
  src/state/mint/hooks.ts
  src/views/AddLiquidity/components/ConfirmZapInModal.tsx
  src/views/AddLiquidity/index.tsx
Labels: size/M

#4194 feat: Remove prediction coin switcher tooltip preference from local storage after logout
  src/config/constants/index.ts
  src/utils/clearUserStates.ts
  src/views/Predictions/components/Label.tsx
Labels: size/S

#4192 feat: List farm auction 25
  src/config/constants/farmAuctions.ts
Labels: size/S, automerge

#4176 feat: UI fixes for ifo
  src/config/localization/translations.json
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardTokens.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/VestingAvailableToClaim.tsx
  src/views/Ifos/components/IfoFoldableCard/index.tsx
  src/views/Pools/helpers.tsx
Labels: size/L, automerge

#4191 feat: List TRIVIA IFO
  public/images/achievements/ifo-trivia.svg
  public/images/ifos/trivia-bg.png
  public/images/tokens/0xb465f3cb6Aba6eE375E12918387DE1eaC2301B05.png
  src/config/constants/campaigns.ts
  src/config/constants/ifo.ts
  src/config/constants/tokens.ts
Labels: size/L, automerge

#4197 chore: Move GAL to finished pools
  src/config/constants/pools.tsx
Labels: size/S, automerge

#4196 fix: Style system bg
  packages/uikit/src/components/Box/Box.tsx
  packages/uikit/src/components/Box/types.ts
  src/views/Predictions/components/PositionTag.tsx
Labels: size/S, automerge

#4208 chore: Use css text transform instead of method call
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardTokens.tsx
  src/views/Ifos/components/IfoFoldableCard/Timer.tsx
  src/views/LimitOrders/components/ConfirmLimitOrderModal.tsx
Labels: size/S, automerge

#4179 feat: Modal to Bottom action sheet on mobile with swipe down feature
  packages/uikit/src/components/BottomDrawer/styles.ts
  packages/uikit/src/components/Box/Box.tsx
  packages/uikit/src/components/Box/index.tsx
  packages/uikit/src/widgets/Modal/Modal.tsx
  packages/uikit/src/widgets/Modal/ModalContext.tsx
  packages/uikit/src/widgets/Modal/styles.tsx
  src/components/SearchModal/CurrencySearchModal.tsx
Labels: size/L

#4206 chore: Bump up swiper
  package.json
  yarn.lock
Labels: size/S

#4205 chore: Bump up recharts to be compatible with react 18
  package.json
  yarn.lock
Labels: size/M

#4199 fix: Border color of liquidity pool info
  src/components/Card/index.tsx
Labels: size/XS

#4212 revert: "feat: Modal to Bottom action sheet on mobile with swipe down feature"
  packages/uikit/src/components/BottomDrawer/styles.ts
  packages/uikit/src/components/Box/Box.tsx
  packages/uikit/src/components/Box/index.tsx
  packages/uikit/src/widgets/Modal/Modal.tsx
  packages/uikit/src/widgets/Modal/ModalContext.tsx
  packages/uikit/src/widgets/Modal/styles.tsx
  src/components/SearchModal/CurrencySearchModal.tsx
Labels: size/L

#4170 fix: Temp update fetch lp aprs script
  .github/workflows/updateLPsAPR.yml
  scripts/updateLPsAPR.ts
  scripts/updateLPsAPR_old.ts
  src/config/constants/lpAprs.json
Labels: size/L

#4215 fix: Busd price crash
  src/hooks/useBUSDPrice.ts
Labels: size/XS

#4213 chore(nft): Allow user to reclaim after delist
  src/config/constants/nftsCollections/delist.ts
  src/state/nftMarket/helpers.ts
  src/views/Nft/market/components/BuySellModals/SellModal/EditStage.tsx
  src/views/Nft/market/hooks/useNftsForAddress.tsx
Labels: size/M

#4216 fix: Prediction Insufficient wording
  src/views/Predictions/components/RoundCard/SetPositionCard.tsx
Labels: size/XS, automerge

#4198 fix: (prediction): To burn tooltip position in round card in mobile
  src/views/Predictions/components/PositionTag.tsx
Labels: size/XS

#4200 perf: (prediction): Pass price as props to not call poll oracle price hook when counting up
  src/views/Predictions/components/Label.tsx
  src/views/Predictions/components/LabelPrice.tsx
  src/views/Predictions/components/RoundCard/LiveRoundCard.tsx
  src/views/Predictions/components/RoundCard/LiveRoundPrice.tsx
Labels: size/S

#4225 chore: Update CODEOWNERS
  .github/CODEOWNERS
Labels: size/XS

#4221 style: Trading Competition css
  src/views/TradingCompetition/components/Countdown/index.tsx
Labels: size/XS, automerge

#4155 chore: New Crowdin updates
  public/locales/ar-SA.json
  public/locales/bn-BD.json
  public/locales/de-DE.json
  public/locales/el-GR.json
  public/locales/en-US.json
  public/locales/es-ES.json
  public/locales/fi-FI.json
  public/locales/fil-PH.json
  public/locales/fr-FR.json
  public/locales/hi-IN.json
  public/locales/hu-HU.json
  public/locales/id-ID.json
  public/locales/it-IT.json
  public/locales/ja-JP.json
  public/locales/ko-KR.json
  public/locales/nl-NL.json
  public/locales/pl-PL.json
  public/locales/pt-BR.json
  public/locales/pt-PT.json
  public/locales/ro-RO.json
  public/locales/ru-RU.json
  public/locales/sv-SE.json
  public/locales/ta-IN.json
  public/locales/tr-TR.json
  public/locales/uk-UA.json
  public/locales/vi-VN.json
  public/locales/zh-CN.json
  public/locales/zh-TW.json
Labels: size/XXL

#4227 fix(zap): Confirm modal mobile styles
  packages/uikit/src/widgets/Modal/styles.tsx
  packages/uikit/src/widgets/Modal/types.ts
  src/views/AddLiquidity/components/ConfirmAddLiquidityModal.tsx
  src/views/AddLiquidity/components/ConfirmZapInModal.tsx
Labels: size/S

#4226 chore: Update Medium url and jest snapshot
  packages/uikit/src/__tests__/components/alert.test.tsx
  packages/uikit/src/__tests__/components/balanceinput.test.tsx
  packages/uikit/src/__tests__/components/button.test.tsx
  packages/uikit/src/__tests__/components/buttonmenu.test.tsx
  packages/uikit/src/__tests__/components/dropdown.test.tsx
  packages/uikit/src/__tests__/components/fallingbunnies.test.tsx
  packages/uikit/src/__tests__/components/heading.test.tsx
  packages/uikit/src/__tests__/components/link.test.tsx
  packages/uikit/src/__tests__/components/overlay.test.tsx
  packages/uikit/src/__tests__/components/skeleton.test.tsx
  packages/uikit/src/__tests__/components/spinner.test.tsx
  packages/uikit/src/__tests__/components/svg.test.tsx
  packages/uikit/src/__tests__/components/text.test.tsx
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/__tests__/widgets/modal.test.tsx
  packages/uikit/src/__tests__/widgets/walletModal.test.tsx
  packages/uikit/src/components/Footer/config.tsx
Labels: size/L

#4214 chore: List farm auction 25 winner
  public/images/tokens/0x2C717059b366714d267039aF8F59125CAdce6D8c.png
  src/config/constants/farms.ts
  src/config/constants/tokens.ts
Labels: Delayed Release, size/M

#4230 feat(pools): support mp
  src/pages/_mp/pools/history.tsx
  src/pages/_mp/pools/index.tsx
  src/utils/mpBridge.ts
  src/views/Pools/MpPageLayout.tsx
  src/views/Pools/components/PoolTabButtons.tsx
Labels: size/M

#4218 feat: List TRIVIA
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
Labels: size/S

#4237 perf: Memoize team podium icon component
  src/views/TradingCompetition/components/TeamRanks/Podium/TeamPodiumIcon.tsx
Labels: size/S

#4228 chore(pools): Reduce re-rendering in PoolRow
  src/state/pools/hooks.ts
  src/state/pools/selectors.ts
  src/views/Pools/components/PoolsTable/ExpandRow.tsx
  src/views/Pools/components/PoolsTable/PoolRow.tsx
  src/views/Pools/components/PoolsTable/PoolsTable.tsx
Labels: size/L

#4235 fix(settings): Add deadline limit
  packages/uikit/src/components/Input/Input.tsx
  src/components/Menu/GlobalSettings/TransactionSettings.tsx
Labels: size/S

#4234 perf: Use memo in bet result
  src/views/Predictions/components/History/BetResult.tsx
Labels: size/S

#4201 feat: Perpetual link add light or dark mode
  package.json
  src/components/Menu/config/config.ts
  src/components/Menu/hooks/useMenuItems.ts
  src/hooks/useTheme.ts
  src/utils/getPerpetualTheme.ts
  src/views/Home/components/Banners/PerpetualBanner.tsx
  yarn.lock
Labels: size/M, automerge

#4245 chore: New Crowdin updates
  public/locales/zh-CN.json
  public/locales/zh-TW.json
Labels: size/XS

#4246 perf: Prefer useEffect instead of each useTheme
  src/hooks/useTheme.ts
  src/hooks/useThemeCookie.ts
  src/pages/_app.tsx
Labels: size/S

#4244 fix: External link ui error in mp webview
  src/utils/mpBridge.ts
Labels: size/M

#4247 feat: Liquidity pair default set to BNB and CAKE
  src/views/AddLiquidity/index.tsx
Labels: size/XS, automerge

#4243 fix: Perdiction switch button style
  packages/uikit/src/components/CoinSwitcher/CoinSwitcher.tsx
  src/views/Predictions/components/Label.tsx
Labels: size/XS, automerge

#4240 feat: List OLE
  public/images/tokens/0xa865197A84E780957422237B5D152772654341F3.png
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
  src/config/constants/tokens.ts
Labels: size/M, automerge

#4229 perf: (prediction): Memoize text color in round price
  src/views/Predictions/components/RoundResult/styles.tsx
Labels: size/XS

#4232 fix: (prediction): Open round card shows wrong entered position after refresh
  src/config/localization/translations.json
  src/views/Predictions/components/RoundCard/OpenRoundCard.tsx
Labels: size/M

#4250 chore: New Crowdin updates
  public/locales/ar-SA.json
  public/locales/bn-BD.json
  public/locales/de-DE.json
  public/locales/el-GR.json
  public/locales/en-US.json
  public/locales/es-ES.json
  public/locales/fi-FI.json
  public/locales/fil-PH.json
  public/locales/fr-FR.json
  public/locales/hi-IN.json
  public/locales/hu-HU.json
  public/locales/id-ID.json
  public/locales/it-IT.json
  public/locales/ja-JP.json
  public/locales/ko-KR.json
  public/locales/nl-NL.json
  public/locales/pl-PL.json
  public/locales/pt-BR.json
  public/locales/pt-PT.json
  public/locales/ro-RO.json
  public/locales/ru-RU.json
  public/locales/sv-SE.json
  public/locales/ta-IN.json
  public/locales/tr-TR.json
  public/locales/uk-UA.json
  public/locales/vi-VN.json
  public/locales/zh-CN.json
  public/locales/zh-TW.json
Labels: size/M

#4022 fix: (liquidity): Missing user readable error messages
  src/config/localization/translations.json
  src/hooks/useSwapCallback.ts
  src/utils/transactionErrorToUserReadableMessage.ts
  src/views/AddLiquidity/index.tsx
  src/views/RemoveLiquidity/index.tsx
Labels: size/L

#4255 revert: LP apr scripts
  .github/workflows/updateLPsAPR.yml
  scripts/updateLPsAPR.ts
  scripts/updateLPsAPR_old.ts
  src/config/constants/lpAprs.json
Labels: size/L

#4254 revert: "chore: Temp hide lp aprs"
  src/state/swap/hooks.ts
Labels: size/M

#4256 feat: Add i18n support
  src/utils/mpBridge.ts
  src/views/Farms/MpPageLayout.tsx
  src/views/Pools/MpPageLayout.tsx
Labels: size/S

#4253 fix: Theme cookie
  src/hooks/useTheme.ts
  src/hooks/useThemeCookie.ts
Labels: size/S

#4257 fix: swap hook reverted issue
  src/state/swap/hooks.ts
Labels: size/S

#4258 chore: New Crowdin updates
  public/locales/ar-SA.json
  public/locales/bn-BD.json
  public/locales/de-DE.json
  public/locales/el-GR.json
  public/locales/en-US.json
  public/locales/es-ES.json
  public/locales/fi-FI.json
  public/locales/fil-PH.json
  public/locales/fr-FR.json
  public/locales/hi-IN.json
  public/locales/hu-HU.json
  public/locales/id-ID.json
  public/locales/it-IT.json
  public/locales/ja-JP.json
  public/locales/ko-KR.json
  public/locales/nl-NL.json
  public/locales/pl-PL.json
  public/locales/pt-BR.json
  public/locales/pt-PT.json
  public/locales/ro-RO.json
  public/locales/ru-RU.json
  public/locales/sv-SE.json
  public/locales/ta-IN.json
  public/locales/tr-TR.json
  public/locales/uk-UA.json
  public/locales/vi-VN.json
  public/locales/zh-CN.json
  public/locales/zh-TW.json
Labels: size/L

#4249 perf: Memoize profile header components
  src/views/Nft/market/Profile/components/ProfileHeader.tsx
  src/views/Nft/market/Profile/index.tsx
Labels: size/M

#4248 perf: Use constants for base fields in graphql queries instead of method call
  src/state/nftMarket/helpers.ts
  src/state/nftMarket/queries.ts
  src/state/predictions/bnbQueries.ts
  src/state/predictions/cakeQueries.ts
  src/state/predictions/queries.ts
Labels: size/M

#4163 perf: Use method directly in onclicks instead of creating new one on each render
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/components/ExpandableSectionButton/ExpandableSectionButton.tsx
  src/views/Farms/components/FarmCard/FarmCard.tsx
  src/views/LimitOrders/components/SwitchTokensButton.tsx
  src/views/LimitOrders/index.tsx
  src/views/Lottery/components/BuyTicketsModal/EditNumbersModal.tsx
  src/views/Lottery/components/YourHistoryCard/index.tsx
  src/views/Pools/components/LockedPool/Buttons/ConvertToFlexibleButton.tsx
  src/views/Swap/components/CurrencyInputHeader.tsx
  src/views/TradingCompetition/components/BattleCta/index.tsx
  src/views/TradingCompetition/components/YourScore/ScoreCard.tsx
Labels: size/M

#4261 chore: New Crowdin updates
  public/locales/ar-SA.json
  public/locales/bn-BD.json
  public/locales/de-DE.json
  public/locales/el-GR.json
  public/locales/en-US.json
  public/locales/es-ES.json
  public/locales/fi-FI.json
  public/locales/fil-PH.json
  public/locales/fr-FR.json
  public/locales/hi-IN.json
  public/locales/hu-HU.json
  public/locales/id-ID.json
  public/locales/it-IT.json
  public/locales/ja-JP.json
  public/locales/ko-KR.json
  public/locales/nl-NL.json
  public/locales/pl-PL.json
  public/locales/pt-BR.json
  public/locales/pt-PT.json
  public/locales/ro-RO.json
  public/locales/ru-RU.json
  public/locales/sv-SE.json
  public/locales/ta-IN.json
  public/locales/tr-TR.json
  public/locales/uk-UA.json
  public/locales/vi-VN.json
  public/locales/zh-CN.json
  public/locales/zh-TW.json
Labels: size/M

#4241 feat: modal to bottom action sheet on mobile and fixing bottom button issue
  packages/uikit/src/components/BottomDrawer/styles.ts
  packages/uikit/src/components/Box/Box.tsx
  packages/uikit/src/components/Box/index.tsx
  packages/uikit/src/widgets/Modal/Modal.tsx
  packages/uikit/src/widgets/Modal/ModalContext.tsx
  packages/uikit/src/widgets/Modal/index.tsx
  packages/uikit/src/widgets/Modal/styles.tsx
  src/components/Menu/GlobalSettings/SettingsModal.tsx
  src/components/SearchModal/CommonBases.tsx
  src/components/SearchModal/CurrencySearch.tsx
  src/components/SearchModal/CurrencySearchModal.tsx
Labels: size/L

#4260 feat: MP webview
  public/images/nav-title-dark.png
  public/images/nav-title-light.png
  src/components/ConnectWalletButton.tsx
  src/components/Navbar.bmp.tsx
  src/hooks/useEagerConnect.bmp.ts
  src/pages/_app.tsx
  src/pages/_mp/farms/history.tsx
  src/pages/_mp/farms/index.tsx
  src/pages/_mp/pools/history.tsx
  src/pages/_mp/pools/index.tsx
  src/react-app-env.d.ts
  src/utils/mpBridge.ts
  src/views/Farms/MpPageLayout.tsx
  src/views/Farms/components/FarmTabButtons/index.tsx
  src/views/Pools/MpPageLayout.tsx
  src/views/Pools/components/PoolTabButtons.tsx
Labels: size/XL

#4222 fix: Predictions v1 claiming
  src/config/abi/predictionsV1.json
  src/config/constants/contracts.ts
  src/hooks/useContract.ts
  src/utils/addressHelpers.ts
  src/utils/contractHelpers.ts
  src/views/Predictions/components/CollectRoundWinningsModal.tsx
  src/views/Predictions/components/v1/V1ClaimCheck.tsx
  src/views/Predictions/components/v1/helpers.ts
Labels: size/XXL

#4265 fix: Modal bottom style
  packages/uikit/src/widgets/Modal/styles.tsx
  src/components/RoiCalculatorModal/index.tsx
  src/views/FarmAuction/components/PlaceBidModal.tsx
  src/views/Lottery/components/BuyTicketsModal/BuyTicketsModal.tsx
  src/views/Lottery/components/BuyTicketsModal/EditNumbersModal.tsx
  src/views/Lottery/components/ViewTicketsModal/index.tsx
Labels: size/M, automerge

#4268 style(limit-orders): Set max width
  src/views/LimitOrders/index.tsx
Labels: size/XS, automerge

#4271 fix: Add Liquidity connect wallet button been disabled
  src/views/AddLiquidity/ChoosePair.tsx
Labels: size/S, automerge

#4266 fix: UseMatchBreakPoint prevMinWidth
  packages/uikit/src/hooks/useMatchBreakpoints.ts
Labels: size/XS, automerge

#4264 fix: Remove js.cookie use js-cookie
  package.json
  src/hooks/useTheme.ts
  src/hooks/useThemeCookie.ts
  yarn.lock
Labels: size/S, automerge

#4233 fix: (prediction): Collect winnings button not displayed in bet results
  src/views/Predictions/components/History/BetResult.tsx
Labels: size/XS

#4251 perf: (farms): Calculate rowdata only when table view selected and remove useTable usage
  src/pages/farms/history.tsx
  src/pages/farms/index.tsx
  src/views/Farms/Farms.tsx
  src/views/Farms/components/FarmTable/FarmTable.tsx
  src/views/Farms/components/getDisplayApr.ts
  src/views/Migration/components/MigrationStep2/NewFarm/index.tsx
Labels: size/L

#4275 fix: Fix swap deeplink
  src/utils/mpBridge.ts
Labels: size/XS

#4277 feat: Transfer page
  apps/transfer/.gitignore
  apps/transfer/README.md
  apps/transfer/components/Menu.tsx
  apps/transfer/components/stargate/config.ts
  apps/transfer/components/stargate/index.tsx
  apps/transfer/components/stargate/theme.ts
  apps/transfer/next-env.d.ts
  apps/transfer/next.config.mjs
  apps/transfer/package.json
  apps/transfer/pages/_app.tsx
  apps/transfer/pages/_document.tsx
  apps/transfer/pages/index.tsx
  apps/transfer/public/chains/1.png
  apps/transfer/public/chains/10.png
  apps/transfer/public/chains/137.png
  apps/transfer/public/chains/250.png
  apps/transfer/public/chains/4.png
  apps/transfer/public/chains/4002.png
  apps/transfer/public/chains/42161.png
  apps/transfer/public/chains/421611.png
  apps/transfer/public/chains/43113.png
  apps/transfer/public/chains/43114.png
  apps/transfer/public/chains/56.png
  apps/transfer/public/chains/69.png
  apps/transfer/public/chains/80001.png
  apps/transfer/public/chains/97.png
  apps/transfer/tsconfig.json
  apps/transfer/wagmi/chains.ts
  apps/transfer/wagmi/index.ts
  package.json
  packages/eslint-config/.prettierrc
  packages/tsconfig/base.json
  packages/tsconfig/nextjs.json
  packages/tsconfig/package.json
  packages/uikit/.prettierrc
  packages/uikit/package.json
  packages/uikit/src/components/MenuItem/MenuItem.tsx
  packages/uikit/src/widgets/Menu/index.ts
  packages/uikit/src/widgets/WalletModal/ConnectModal.tsx
  packages/uikit/src/widgets/WalletModal/index.stories.tsx
  packages/uikit/src/widgets/WalletModal/index.tsx
  packages/uikit/src/widgets/WalletModal/types.ts
  packages/uikit/src/widgets/WalletModal/useWalletModal.tsx
  src/Providers.tsx
  src/components/ConnectWalletButton.tsx
  src/components/Menu/config/config.ts
  src/config/constants/farms.ts
  src/views/TradingCompetition/components/BattleCta/index.tsx
  tsconfig.json
  yarn.lock
Labels: size/XXL

#4281 fix(modal): Enable scroll in small screen
  packages/uikit/src/widgets/Modal/styles.tsx
Labels: size/XS

#4280 fix(transfer): filter bsc testnet login
  apps/transfer/components/Menu.tsx
  apps/transfer/wagmi/chains.ts
  apps/transfer/wagmi/index.ts
Labels: size/S

#4278 fix(zap): Setting apply to remove liquidity
  src/components/Menu/GlobalSettings/SettingsModal.tsx
  src/config/localization/translations.json
  src/state/burn/hooks.ts
  src/views/RemoveLiquidity/index.tsx
Labels: size/L

#4283 chore: set max height for extreme small device for modal sheet
  packages/uikit/src/widgets/Modal/styles.tsx
Labels: size/XS

#4282 chore: Update framer and use velocity to close modal
  packages/uikit/.storybook/main.js
  packages/uikit/.storybook/preview-head.html
  packages/uikit/.storybook/preview.jsx
  packages/uikit/package.json
  packages/uikit/src/components/Svg/index.stories.tsx
  packages/uikit/src/widgets/Modal/Modal.tsx
  packages/uikit/src/widgets/Modal/index.tsx
  src/components/SearchModal/CurrencySearchModal.tsx
  yarn.lock
Labels: size/XXL

#4274 chore: New Crowdin updates
  public/locales/ar-SA.json
  public/locales/bn-BD.json
  public/locales/de-DE.json
  public/locales/el-GR.json
  public/locales/en-US.json
  public/locales/es-ES.json
  public/locales/fi-FI.json
  public/locales/fil-PH.json
  public/locales/fr-FR.json
  public/locales/hi-IN.json
  public/locales/hu-HU.json
  public/locales/id-ID.json
  public/locales/it-IT.json
  public/locales/ja-JP.json
  public/locales/ko-KR.json
  public/locales/nl-NL.json
  public/locales/pl-PL.json
  public/locales/pt-BR.json
  public/locales/pt-PT.json
  public/locales/ro-RO.json
  public/locales/ru-RU.json
  public/locales/sv-SE.json
  public/locales/ta-IN.json
  public/locales/tr-TR.json
  public/locales/uk-UA.json
  public/locales/vi-VN.json
  public/locales/zh-CN.json
  public/locales/zh-TW.json
Labels: size/XXL

#4290 fix: ts-node version
  package.json
  yarn.lock
Labels: size/M

#4289 fix: Risk modal mobile bottom style
  cypress/integration/predictions/predictions.test.ts
  src/components/DisclaimerModal/index.tsx
  src/views/Predictions/components/RiskDisclaimer.tsx
  src/views/Predictions/index.tsx
Labels: size/L, automerge

#4293 chore: New Crowdin updates
  public/locales/ar-SA.json
  public/locales/el-GR.json
  public/locales/fil-PH.json
  public/locales/fr-FR.json
  public/locales/ko-KR.json
  public/locales/pl-PL.json
  public/locales/zh-CN.json
Labels: size/XL

#4297 fix: Fix infinite loop for mp
  src/views/Farms/MpPageLayout.tsx
  src/views/Pools/MpPageLayout.tsx
Labels: size/XS

#4292 feat: add wagmi package
  apps/transfer/next.config.mjs
  apps/transfer/package.json
  apps/transfer/tsconfig.json
  apps/transfer/wagmi/index.ts
  packages/tsconfig/nextjs.json
  packages/tsconfig/react-library.json
  packages/wagmi/package.json
  packages/wagmi/src/chains.ts
  packages/wagmi/src/connectors/bnInjectedConnector.ts
  packages/wagmi/src/connectors/bscConnector.ts
  packages/wagmi/src/connectors/index.ts
  packages/wagmi/src/index.ts
  packages/wagmi/src/provider.tsx
  packages/wagmi/src/useWeb3React.ts
  packages/wagmi/tsconfig.json
  src/components/CurrencyInputPanel/index.tsx
  src/components/TransactionConfirmationModal/index.tsx
  src/utils/wallet.ts
Labels: size/L

#4285 fix(transfer): UI minor fix
  apps/transfer/components/Menu.tsx
  apps/transfer/components/stargate/index.tsx
  apps/transfer/pages/_app.tsx
  apps/transfer/pages/index.tsx
  apps/transfer/public/stargate.png
Labels: size/M

#4300 chore: Update swap sound url
  src/components/SearchModal/swapSound.ts
Labels: size/XS

#4286 feat: Set IFO TRIVIA to finished
  src/config/constants/ifo.ts
  src/views/Ifos/components/IfoVesting/VestingPeriod/Claim.tsx
  src/views/Ifos/components/IfoVesting/VestingPeriod/Info.tsx
  src/views/Ifos/components/IfoVesting/index.tsx
  src/views/Ifos/hooks/vesting/fetchUserWalletIfoData.ts
  src/views/Ifos/hooks/vesting/useFetchVestingData.ts
Labels: size/M, automerge

#4306 chore: Remove BBT
  src/config/constants/farmAuctions.ts
Labels: size/XS

#4305 feat: Read theme from binance app
  src/views/Farms/MpPageLayout.tsx
  src/views/Pools/MpPageLayout.tsx
Labels: size/S

#4302 fix: Vote mobile modal
  src/views/Voting/components/CastVoteModal/index.tsx
  src/views/Voting/components/CastVoteModal/styles.tsx
  src/views/Voting/components/VoteDetailsModal.tsx
Labels: size/XS, automerge

#4308 fix: Lint and skip subgraph health e2e check
  cypress/integration/nfts/nfts.test.ts
  src/views/Farms/MpPageLayout.tsx
Labels: size/XS

#4313 fix: Lint
  src/views/Pools/MpPageLayout.tsx
Labels: size/XS

#4296 chore: New Crowdin updates
  public/locales/ar-SA.json
  public/locales/bn-BD.json
  public/locales/de-DE.json
  public/locales/el-GR.json
  public/locales/en-US.json
  public/locales/es-ES.json
  public/locales/fi-FI.json
  public/locales/fil-PH.json
  public/locales/fr-FR.json
  public/locales/hi-IN.json
  public/locales/hu-HU.json
  public/locales/id-ID.json
  public/locales/it-IT.json
  public/locales/ja-JP.json
  public/locales/ko-KR.json
  public/locales/nl-NL.json
  public/locales/pl-PL.json
  public/locales/pt-BR.json
  public/locales/pt-PT.json
  public/locales/ro-RO.json
  public/locales/ru-RU.json
  public/locales/sv-SE.json
  public/locales/ta-IN.json
  public/locales/tr-TR.json
  public/locales/uk-UA.json
  public/locales/vi-VN.json
  public/locales/zh-CN.json
  public/locales/zh-TW.json
Labels: size/XXL

#4309 feat: List farm auction 26 winner
  public/images/tokens/0x208cfEc94d2BA8B8537da7A9BB361c6baAD77272.png
  public/images/tokens/0x431e0cD023a32532BF3969CddFc002c00E98429d.png
  src/config/constants/farms.ts
  src/config/constants/tokens.ts
Labels: Delayed Release, size/M

#4314 chore: New Crowdin updates
  public/locales/fr-FR.json
  public/locales/ko-KR.json
Labels: size/XS

#4320 chore: Move mix pool to finished
  src/config/constants/pools.tsx
  tsconfig.json
Labels: size/S, automerge

#4270 feat: Prompt Zap is available
  src/config/localization/translations.json
  src/views/AddLiquidity/index.tsx
Labels: size/M

#4263 feat: Make disabling zap from prompt easier
  src/config/localization/translations.json
  src/views/AddLiquidity/components/ConfirmZapInModal.tsx
  src/views/AddLiquidity/components/ZapErrorMessage.tsx
  src/views/AddLiquidity/index.tsx
  src/views/RemoveLiquidity/index.tsx
  src/views/Swap/components/ConfirmRemoveLiquidityModal.tsx
Labels: size/L

#4327 fix: Use same view bscscan text
  src/config/localization/translations.json
  src/views/LimitOrders/components/LimitOrderTable/DetailLimitOrderModal.tsx
Labels: size/XS

#4323 chore: Remove unused import
  src/views/RemoveLiquidity/index.tsx
Labels: size/XS

#4331 feat: Network switcher
  packages/uikit/src/widgets/Menu/Menu.tsx
  packages/uikit/src/widgets/Menu/components/UserMenu/index.tsx
  packages/uikit/src/widgets/Menu/components/UserMenu/types.ts
  packages/uikit/src/widgets/Menu/index.stories.tsx
  packages/uikit/src/widgets/Menu/types.ts
  packages/wagmi/src/chains.ts
  packages/wagmi/src/connectors/bnInjectedConnector.ts
  packages/wagmi/src/connectors/bscConnector.ts
  src/components/Menu/config/config.ts
  src/components/Menu/index.tsx
  src/components/NetworkSwitcher.tsx
  src/config/localization/translations.json
  src/react-app-env.d.ts
Labels: size/L

#4333 fix: Clean up CHAIN_ID
  .github/workflows/updateLPsAPR.yml
  src/config/constants/networks.ts
  src/hooks/limitOrders/useGasOverhead.ts
  src/state/farms/getFarmsAuctionData.ts
  src/utils/getGasPrice.ts
Labels: size/S

#4329 perf: Convert external link props to constant from method call
  packages/uikit/src/components/Button/Button.tsx
  packages/uikit/src/components/Link/Link.tsx
  packages/uikit/src/util/externalLinkProps.ts
  packages/uikit/src/util/getExternalLinkProps.ts
  packages/uikit/src/widgets/WalletModal/ConnectModal.tsx
Labels: size/S

#4324 chore: Bump up swiper
  package.json
  yarn.lock
Labels: size/S

#4328 fix: (activity): Invisible view bscscan button text on mobile nft activity transaction details
  src/views/Nft/market/components/Activity/MobileModal.tsx
Labels: size/XS

#4338 perf: (pools): Use promise all in fetch user balances
  src/state/pools/fetchPoolsUser.ts
Labels: size/S

#4343 feat: Update thunder token image
  public/images/tokens/0x990E7154bB999FAa9b2fa5Ed29E822703311eA85.png
Labels: size/XS, automerge

#4340 style: Migration css
  src/views/Migration/components/ProgressSteps.tsx
Labels: size/XS, automerge

#4341 fix: Nft modal mobile style
  src/views/Nft/market/components/Activity/MobileModal.tsx
Labels: size/XS, automerge

#4342 fix: Nfts collections style
  src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/index.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/index.tsx
Labels: size/XS, automerge

#4334 feat: List High pool
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
Labels: size/M

#4347 fix: WC rpc missing
  src/utils/web3React.ts
Labels: size/XS

#4321 chore: New Crowdin updates
  public/locales/ar-SA.json
  public/locales/bn-BD.json
  public/locales/de-DE.json
  public/locales/el-GR.json
  public/locales/en-US.json
  public/locales/es-ES.json
  public/locales/fi-FI.json
  public/locales/fil-PH.json
  public/locales/fr-FR.json
  public/locales/hi-IN.json
  public/locales/hu-HU.json
  public/locales/id-ID.json
  public/locales/it-IT.json
  public/locales/ja-JP.json
  public/locales/ko-KR.json
  public/locales/nl-NL.json
  public/locales/pl-PL.json
  public/locales/pt-BR.json
  public/locales/pt-PT.json
  public/locales/ro-RO.json
  public/locales/ru-RU.json
  public/locales/sv-SE.json
  public/locales/ta-IN.json
  public/locales/tr-TR.json
  public/locales/uk-UA.json
  public/locales/vi-VN.json
  public/locales/zh-CN.json
  public/locales/zh-TW.json
Labels: size/XL

#4348 fix: shouldShowWarningToken error
  src/utils/shouldShowSwapWarning.ts
Labels: size/XS

#4330 fix: TemporarilyZapMode
  src/views/AddLiquidity/index.tsx
  src/views/RemoveLiquidity/index.tsx
Labels: size/XS

#4345 fix: Wide add cake to lock pool modal in desktop
  src/views/Pools/components/LockedPool/Modals/AddAmountModal.tsx
Labels: size/XS

#4350 chore: Move ANTEX to finished
  src/config/constants/pools.tsx
Labels: size/S, automerge

#4287 feat: subMenu component support mobile scroll
  packages/uikit/src/components/MenuItem/MenuItem.tsx
  packages/uikit/src/components/MenuItem/types.ts
  packages/uikit/src/components/SubMenuItems/SubMenuItems.tsx
  packages/uikit/src/components/SubMenuItems/index.stories.tsx
  packages/uikit/src/components/SubMenuItems/mock.tsx
  packages/uikit/src/components/SubMenuItems/styles.tsx
Labels: size/L

#4354 feat: Rename ThunderCore
  src/config/constants/tokens.ts
Labels: size/XS, automerge

#4356 feat: List IFO PEEL
  public/images/achievements/ifo-peel.svg
  public/images/ifos/peel-bg.png
  public/images/tokens/0x734548a9e43d2D564600b1B2ed5bE9C2b911c6aB.png
  src/config/constants/campaigns.ts
  src/config/constants/ifo.ts
  src/config/constants/tokens.ts
Labels: size/M, automerge

#4359 chore: Typo
  src/views/Swap/index.tsx
Labels: size/XS
