Repository pancakeswap/pancake-frontend, pull requests merged in 2022-02, with the labels that each got.

#3179 feat: add wrong network and pending message to menu
  src/components/Menu/UserMenu/ProfileUserMenutItem.tsx
  src/components/Menu/UserMenu/WalletModal.tsx
  src/components/Menu/UserMenu/WalletUserMenuItem.tsx
  src/components/Menu/UserMenu/WalletWrongNetwork.tsx
  src/components/Menu/UserMenu/index.tsx
  src/config/localization/translations.json
  src/state/transactions/hooks.tsx
Labels: size/L

#3185 chore: Update text
  src/config/localization/translations.json
  src/views/Pools/index.tsx
Labels: size/XS

#2942 feat: Migrate user transactions to fetchWithCatchTxError
  src/hooks/useApproveConfirmTransaction.tsx
  src/hooks/useCatchTxError.tsx
  src/utils/calls/nftMarket.ts
  src/views/Farms/components/DepositModal.tsx
  src/views/Farms/components/FarmCard/CardActionsContainer.tsx
  src/views/Farms/components/FarmCard/HarvestAction.tsx
  src/views/Farms/components/FarmCard/StakeAction.tsx
  src/views/Farms/components/FarmTable/Actions/HarvestAction.tsx
  src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
  src/views/Farms/components/WithdrawModal.tsx
  src/views/Farms/hooks/useApproveFarm.ts
  src/views/Farms/hooks/useHarvestFarm.ts
  src/views/Farms/hooks/useStakeFarms.ts
  src/views/Farms/hooks/useUnstakeFarms.ts
  src/views/Home/components/UserBanner/HarvestCard.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ClaimButton.tsx
  src/views/Ifos/components/IfoFoldableCard/index.tsx
  src/views/Ifos/components/IfoSteps.tsx
  src/views/Ifos/hooks/useIfoApprove.ts
  src/views/Lottery/components/ClaimPrizesModal/ClaimPrizesInner.tsx
  src/views/Nft/market/Profile/components/Achievements/AchievementRow/index.tsx
  src/views/Nft/market/Profile/components/EditProfileModal/ApproveCakeView.tsx
  src/views/Nft/market/Profile/components/EditProfileModal/PauseProfileView.tsx
  src/views/PancakeSquad/components/Buttons/Mint.tsx
  src/views/Pools/components/BountyModal.tsx
  src/views/Pools/components/CakeVaultCard/VaultCardActions/VaultApprovalAction.tsx
  src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
  src/views/Pools/components/PoolCard/CardActions/ApprovalAction.tsx
  src/views/Pools/components/PoolCard/Modals/CollectModal.tsx
  src/views/Pools/components/PoolCard/Modals/StakeModal.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
  src/views/Pools/hooks/useApprove.tsx
  src/views/Pools/hooks/useHarvestPool.ts
  src/views/Pools/hooks/useStakePool.ts
  src/views/Pools/hooks/useUnstakePool.ts
  src/views/Predictions/components/CollectRoundWinningsModal.tsx
  src/views/Predictions/components/ReclaimPositionButton.tsx
  src/views/Predictions/components/RoundCard/SetPositionCard.tsx
  src/views/ProfileCreation/ProfilePicture.tsx
  src/views/TradingCompetition/components/ClaimModal/index.tsx
  src/views/TradingCompetition/components/RegisterModal/RegisterWithProfile.tsx
Labels: size/XXL

#3186 chore: Remove netlify
  netlify.toml
  package.json
  static.json
  yarn.lock
Labels: size/XL

#3187 refactor: (contract): Use simple rpc provider for contract calls that making no user transaction
  src/hooks/useContract.ts
  src/hooks/useTokenBalance.ts
  src/views/Ifos/hooks/v1/useGetWalletIfoData.ts
  src/views/Ifos/hooks/v2/useGetWalletIfoData.ts
  src/views/Nft/market/components/BuySellModals/BuyModal/index.tsx
  src/views/Pools/hooks/useApprove.tsx
Labels: size/S

#3192 fix: Update updateLPsAPR
  scripts/updateLPsAPR.ts
Labels: size/XS

#3193 fix: Add CI version of infoClient
  scripts/updateLPsAPR.ts
  src/utils/graphql.ts
Labels: size/S

#3130 feat(pool): Add user requirement
  .env.testnet
  .eslintrc
  src/config/abi/sousChefV3.json
  src/config/constants/farms.ts
  src/config/constants/networks.ts
  src/config/constants/pools.ts
  src/config/constants/tokens.ts
  src/config/constants/types.ts
  src/config/localization/translations.json
  src/hooks/useActiveWeb3React.ts
  src/hooks/useContract.ts
  src/state/pools/fetchPools.ts
  src/state/pools/helpers.ts
  src/state/pools/index.ts
  src/state/types.ts
  src/state/user/hooks/index.tsx
  src/utils/calls/pools.ts
  src/utils/contractHelpers.ts
  src/utils/getGasPrice.ts
  src/utils/web3React.ts
  src/views/Pools/components/PoolCard/CardActions/index.tsx
  src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/styles.ts
  src/views/Pools/components/ProfileRequirementWarning.tsx
  src/views/Pools/hooks/useProfileRequirement.ts
Labels: size/XL

#3155 feat: (nft): Add skeleton to activity row item column
  src/views/Nft/market/components/Activity/ActivityRow.tsx
Labels: size/M

#3157 feat: (import): Add buttons to import pool component instead of text link
  src/config/localization/translations.json
  src/views/PoolFinder/index.tsx
Labels: size/M

#3183 feat(pool&farm): Add new sorting option for Latest
  src/views/Farms/Farms.tsx
  src/views/Pools/index.tsx
Labels: size/S

#3194 fix: Workflow env var
  .github/workflows/updateLPsAPR.yml
  scripts/updateLPsAPR.ts
  src/utils/graphql.ts
Labels: size/S

#3195 Revert "chore: Update text"
  src/config/localization/translations.json
  src/views/Pools/index.tsx
Labels: size/XS

#3197 fix: Add CHAIN_ID to workflow vars
  .github/workflows/updateLPsAPR.yml
Labels: size/XS

#3198 fix: Rename CHAIN_ID workflow var
  .github/workflows/updateLPsAPR.yml
Labels: size/XS

#3200 fix: Typo
  .github/workflows/integrationTests.yml
  .github/workflows/updateLPsAPR.yml
Labels: size/XS

#2738 test: Update translation checking
  src/__tests__/config/translations.test.ts
  src/components/ConnectWalletButton.tsx
  src/components/FoldableSection/FoldableText.tsx
  src/components/SearchModal/ImportList.tsx
  src/components/SubgraphHealthIndicator/index.tsx
  src/components/Trans.tsx
  src/config/constants/pools.tsx
  src/config/localization/translations.json
  src/contexts/Localization/Provider.tsx
  src/contexts/Localization/index.tsx
  src/contexts/Localization/types.ts
  src/pages/index.tsx
  src/views/Home/components/FarmsPoolsRow/TopFarmPool.tsx
  src/views/Home/components/FarmsPoolsRow/index.tsx
  src/views/Home/components/SalesSection/data.ts
  src/views/Home/components/SalesSection/index.tsx
  src/views/Home/index.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardTokens.tsx
  src/views/Ifos/components/IfoQuestions/config.ts
  src/views/Ifos/components/IfoQuestions/config.tsx
  src/views/Ifos/components/IfoQuestions/index.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/shared/MoreFromThisCollection.tsx
  src/views/Nft/market/components/BuySellModals/BuyModal/index.tsx
  src/views/PancakeSquad/components/Modals/BuyTickets/index.tsx
  src/views/Pools/components/CakeVaultCard/index.tsx
  src/views/Pools/components/PoolCard/PoolCardHeader.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
  src/views/Pools/components/PoolsTable/Cells/NameCell.tsx
  src/views/Predictions/components/RoundCard/SetPositionCard.tsx
  src/views/ProfileCreation/Header.tsx
  src/views/TradingCompetition/components/PrizesInfo/PrizesGrid/index.tsx
Labels: size/XL

#3202 fix: Token image case
  public/images/tokens/0x07663837218A003e66310a01596af4bf4e44623D.png
  public/images/tokens/0x07663837218A003e66310a01596af4bf4e44623D.svg
  public/images/tokens/0x477bC8d23c634C154061869478bce96BE6045D12.png
  public/images/tokens/0x477bC8d23c634C154061869478bce96BE6045D12.svg
  public/images/tokens/0x6679eB24F59dFe111864AEc72B443d1Da666B360.png
  public/images/tokens/0x6679eB24F59dFe111864AEc72B443d1Da666B360.svg
  public/images/tokens/0x758d08864fB6cCE3062667225ca10b8F00496cc2.png
  public/images/tokens/0x758d08864fB6cCE3062667225ca10b8F00496cc2.svg
  public/images/tokens/0x8729438EB15e2C8B576fCc6AeCdA6A148776C0F5.png
  public/images/tokens/0x8729438EB15e2C8B576fCc6AeCdA6A148776C0F5.svg
  public/images/tokens/0xACB8f52DC63BB752a51186D1c55868ADbFfEe9C1.png
  public/images/tokens/0xACB8f52DC63BB752a51186D1c55868ADbFfEe9C1.svg
  public/images/tokens/0xBe1a001FE942f96Eea22bA08783140B9Dcc09D28.png
  public/images/tokens/0xBe1a001FE942f96Eea22bA08783140B9Dcc09D28.svg
  public/images/tokens/0xF750A26EB0aCf95556e8529E72eD530f3b60f348.png
  public/images/tokens/0xF750A26EB0aCf95556e8529E72eD530f3b60f348.svg
  public/images/tokens/0xFeea0bDd3D07eb6FE305938878C0caDBFa169042.png
  public/images/tokens/0xFeea0bDd3D07eb6FE305938878C0caDBFa169042.svg
  public/images/tokens/0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6.png
  public/images/tokens/0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6.svg
  src/config/constants/farms.ts
  src/config/constants/tokenLists/pancake-default.tokenlist.json
Labels: size/XS

#3127 fix: (nft): Sort and order options defaulted when clicking filter clear button
  src/state/nftMarket/reducer.ts
  src/views/Nft/market/Collection/Items/ClearAllButton.tsx
  src/views/Nft/market/Collection/Items/Filters.tsx
  src/views/Nft/market/Collection/Items/SortSelect.tsx
Labels: size/S

#3171 refactor: (bounty): Use props instead of hooks inside modal to reduce calculation and memory
  src/views/Pools/components/BountyCard.tsx
  src/views/Pools/components/BountyModal.tsx
Labels: size/M

#3205 fix(nft): Add missing fetch collection
  src/views/Nft/market/Profile/index.tsx
Labels: size/XS

#3210 fix(nft): Modal title error
  src/views/Nft/market/components/BuySellModals/BuyModal/index.tsx
Labels: size/XS

#3184 feat: PAN-128 country warning vercel
  package.json
  src/components/BlockCountry/BlockCountryModal.tsx
  src/components/BlockCountry/index.tsx
  src/config/constants/cookie-names.ts
  src/config/localization/translations.json
  src/pages/_app.tsx
  src/pages/_middleware.ts
  yarn.lock
Labels: size/L

#3213 fix(nft): Collection ssg redux state overrided
  src/pages/nfts/collections/[collectionAddress].tsx
Labels: size/XS

#3220 fix: Voting cache on not closed state
  src/pages/voting/proposal/[id].tsx
Labels: size/XS

#3221 fix(nft): Bunny defense code
  src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/index.tsx
Labels: size/S

#3227 chore(swap): Remove TradingView
  src/views/Swap/components/Chart/PriceChart.tsx
Labels: size/S

#3233 chore: Remove netlify state from readme
  README.md
Labels: size/XS

#3236 chore: Filter country log
  src/pages/_middleware.ts
Labels: size/XS

#3231 feat: List ACH
  public/images/tokens/0xBc7d6B50616989655AfD682fb42743507003056D.png
  public/images/tokens/0xBc7d6B50616989655AfD682fb42743507003056D.svg
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
  src/config/constants/tokens.ts
Labels: size/M

#3239 feat: Add new pool
  src/config/constants/pools.tsx
Labels: size/S

#3243 fix: (pools): Enable emergency withdraw option for ach pool
  src/config/constants/pools.tsx
Labels: size/XS

#3242 feat: (pools): Emergency withdraw option on stake modal
  src/config/localization/translations.json
  src/views/Pools/components/PoolCard/Modals/StakeModal.tsx
Labels: size/S

#3226 fix: Translation variable data in ifo card
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardTokens.tsx
Labels: size/S

#3218 feat(ifo 3.1): Add Private Sale
  public/images/achievements/ifo-era.svg
  public/images/ifos/era-bg.png
  public/images/tokens/0x6f9F0c4ad9Af7EbD61Ac5A1D4e0F2227F7B0E5f9.png
  public/images/tokens/0x6f9F0c4ad9Af7EbD61Ac5A1D4e0F2227F7B0E5f9.svg
  src/components/Menu/config/config.ts
  src/config/abi/ifoV3.json
  src/config/constants/campaigns.ts
  src/config/constants/ifo.ts
  src/config/constants/tokens.ts
  src/config/localization/translations.json
  src/pages/nfts/profile/[accountAddress]/achievements.tsx
  src/state/profile/hooks.ts
  src/views/Ifos/CurrentIfo.tsx
  src/views/Ifos/PastIfo.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeButton.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IFORequirements.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/Icons/OkNFT.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/Icons/OkProfilePoints.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardActions.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardTokens.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/index.tsx
  src/views/Ifos/components/IfoFoldableCard/index.tsx
  src/views/Ifos/components/IfoQuestions/config.tsx
  src/views/Ifos/components/IfoSteps.tsx
  src/views/Ifos/components/TransWithElement.tsx
  src/views/Ifos/hooks/v2/useGetPublicIfoData.ts
  src/views/Ifos/hooks/v3/useCriterias.ts
  src/views/Ifos/hooks/v3/useGetWalletIfoData.ts
  src/views/Ifos/types.ts
  src/views/Pools/components/CakeVaultCard/VaultCardActions/index.tsx
  src/views/Pools/components/PoolsTable/Cells/IFOCreditCell.tsx
Labels: size/XXL

#3211 chore: Fix typos
  src/components/Menu/GlobalSettings/SettingsModal.tsx
  src/pages/_middleware.ts
Labels: size/XS

#3222 fix: Make subgraph health indicator text not selectable
  src/components/SubgraphHealthIndicator/index.tsx
Labels: size/XS

#3248 chore(farm-auction): update auction apply link
  src/views/FarmAuction/helpers.tsx
Labels: size/XS

#3208 chore: Add missing translation in unsupported currency component
  src/components/UnsupportedCurrencyFooter.tsx
  src/config/localization/translations.json
Labels: size/S

#3237 refactor: Use ethers bignumbers constants
  src/state/predictions/helpers.ts
  src/views/Nft/market/Profile/hooks/useGetProfileCosts.ts
  src/views/Nft/market/components/BuySellModals/BuyModal/index.tsx
  src/views/Predictions/components/RoundCard/SetPositionCard.tsx
  src/views/Predictions/helpers.ts
  src/views/Predictions/hooks/useGetLatestOraclePrice.ts
Labels: size/M

#3251 feat(ifo): Add ERA banner
  public/images/decorations/3d-ifo-era.png
  src/views/Home/components/Banners/IFOBanner.tsx
  src/views/Home/index.tsx
Labels: size/S

#3252 fix: Wording
  src/views/Home/components/Banners/IFOBanner.tsx
Labels: size/XS

#3235 chore: Remove sentry txn trace
  sentry.client.config.js
  sentry.server.config.js
Labels: size/XS

#3234 chore: Update BTT warning
  src/components/Trans.tsx
  src/config/constants/pools.tsx
  src/config/localization/translations.json
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IFORequirements.tsx
  src/views/Ifos/components/IfoQuestions/config.tsx
  src/views/Swap/components/Chart/PriceChart.tsx
  src/views/Swap/components/SwapWarningModal/BTTWarning.tsx
Labels: size/M

#3215 fix: (nft): Nft Media with video not shown when low power mode enabled in mobile
  src/state/nftMarket/hooks.ts
  src/state/nftMarket/reducer.ts
  src/state/nftMarket/types.ts
  src/views/Nft/market/components/NFTMedia.tsx
Labels: size/S

#3259 fix: (ifo): Ifo private sale tooltip li position
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/index.tsx
Labels: size/XS

#3262 feat: Farm auction 15
  src/config/constants/farmAuctions.ts
Labels: size/S

#3256 fix: (swap): Missing error translation in wrap
  src/config/localization/translations.json
  src/hooks/useWrapCallback.ts
Labels: size/S

#3067 refactor: (intersection): Disconnect observer when component unmounted
  src/hooks/useIntersectionObserver.ts
Labels: size/S

#3263 test(pool): Add reward per block test
  jest.config.js
  package.json
  src/config/__tests__/campaigns.test.ts
  src/config/__tests__/contracts.test.ts
  src/config/__tests__/farms.test.ts
  src/config/__tests__/ifo.test.ts
  src/config/__tests__/pools.test.ts
  src/config/__tests__/teams.test.ts
  src/config/__tests__/tokens.test.ts
  src/config/__tests__/translations.test.ts
Labels: size/S

#3271 fix(nft): Individual page crash
  src/pages/nfts/collections/[collectionAddress]/[tokenId].tsx
  src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/index.tsx
  src/views/Nft/market/hooks/useCompleteNft.tsx
Labels: size/S

#3277 chore: Remove unused SNAPSHOT_VOTING_API
  .env.development
  .env.production
  src/config/constants/endpoints.ts
Labels: size/XS

#3269 chore: Shared component AnimatedBlanace
  src/components/Balance.tsx
  src/views/Pools/components/BountyCard.tsx
Labels: size/M

#3274 fix(ifo 3.1): Fix bugs in Live and Finished phases
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardActions.tsx
  src/views/Ifos/hooks/v3/useGetWalletIfoData.ts
  src/views/Ifos/types.ts
Labels: size/S

#3254 perf(prediction): Avoid redundant re-render
  src/views/Predictions/Desktop.tsx
  src/views/Predictions/Mobile.tsx
  src/views/Predictions/components/CollectWinningsPopup.tsx
  src/views/Predictions/components/Container.tsx
  src/views/Predictions/context/SwiperProvider.tsx
Labels: size/S

#3276 fix: (ifo nft) Fix missing page titles
  src/views/Ifos/index.tsx
  src/views/Nft/market/Collection/index.tsx
  src/views/TradingCompetition/index.tsx
Labels: size/L

#3281 chore: Update sentry
  package.json
  sentry.client.config.js
  src/utils/sentry.ts
  yarn.lock
Labels: size/L

#3283 fix(predictions): Prevent crash when missing currentRound
  src/state/predictions/hooks.ts
  src/views/Predictions/components/Label.tsx
Labels: size/XS

#3280 chore(farm): Add LOA-BUSD and FIGHT-BUSD farms
  public/images/tokens/0x4f39c3319188A723003670c3F9B9e7EF991E52F3.png
  public/images/tokens/0x4f39c3319188A723003670c3F9B9e7EF991E52F3.svg
  public/images/tokens/0x94b69263FCA20119Ae817b6f783Fc0F13B02ad50.png
  public/images/tokens/0x94b69263FCA20119Ae817b6f783Fc0F13B02ad50.svg
  src/config/constants/farms.ts
  src/config/constants/tokens.ts
Labels: size/M

#3241 feat(farms): Add poolLength check
  src/state/farms/fetchMasterChefData.ts
  src/state/farms/hooks.ts
  src/state/farms/index.ts
  src/state/types.ts
  src/views/Farms/Farms.tsx
  src/views/Home/hooks/useFarmsWithBalance.tsx
Labels: size/M

#3267 chore: Update to BNB Smart Chain
  public/locales/ar-SA.json
  public/locales/bn-BD.json
  public/locales/de-DE.json
  public/locales/el-GR.json
  public/locales/en-AU.json
  public/locales/en-US.json
  public/locales/es-ES.json
  public/locales/fi-FI.json
  public/locales/fil-PH.json
  public/locales/fr-FR.json
  public/locales/hi-IN.json
  public/locales/hu-HU.json
  public/locales/id-ID.json
  public/locales/it-IT.json
  public/locales/ja-JP.json
  public/locales/ko-KR.json
  public/locales/nl-NL.json
  public/locales/pl-PL.json
  public/locales/pt-BR.json
  public/locales/pt-PT.json
  public/locales/ro-RO.json
  public/locales/ru-RU.json
  public/locales/sv-SE.json
  public/locales/ta-IN.json
  public/locales/tr-TR.json
  public/locales/uk-UA.json
  public/locales/vi-VN.json
  public/locales/zh-CN.json
  public/locales/zh-TW.json
  src/config/localization/translations.json
  src/pages/_app.tsx
  src/utils/wallet.ts
  src/views/Home/components/SalesSection/data.ts
  src/views/Ifos/components/Hero.tsx
  src/views/Nft/market/Home/config.tsx
  src/views/Nft/market/Home/index.tsx
  src/views/Nft/market/components/BuySellModals/SellModal/TransferStage.tsx
Labels: size/L

#3297 chore(ifo): Update Live Status for IFO
  src/components/Menu/config/config.ts
  src/views/Home/components/Banners/IFOBanner.tsx
Labels: size/XS

#3295 chore(pool&farm): Add ERA-BNB farm and pool
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
Labels: size/S

#3301 chore(pool): Add new THG pool
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
Labels: size/M

#3300 chore: Allow Sentry sourcemap next file
  next.config.js
Labels: size/XS

#3303 chore(ifo): Update Era7 name
  src/config/constants/campaigns.ts
  src/config/constants/pools.tsx
Labels: size/XS

#3285 fix: (nft): Sell modal crash when no collection is found yet
  src/state/nftMarket/hooks.ts
  src/views/Nft/market/components/BuySellModals/SellModal/SetPriceStage.tsx
Labels: size/M

#3311 chore: Remove space at ada token name
  src/config/constants/tokens.ts
Labels: size/XS

#3309 fix: Remove 0 teams point in leaderboard page
  src/views/Teams/components/TeamListCard.tsx
Labels: size/XS

#3307 fix(ifo): Fix how does it work buttons
  src/views/Ifos/components/Hero.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardTokens.tsx
Labels: size/S

#3306 feat: Add tvl to static props
  src/pages/index.tsx
  src/views/Home/components/MetricsSection/index.tsx
Labels: size/S

#3305 chore: Remove past ifo images
  public/images/decorations/3d-ifo-era.png
  public/images/decorations/3d-ifo-froyo.png
  public/images/decorations/3d-ifo-santos.png
Labels: size/XS

#3296 perf: Lazy get swr status
  src/hooks/useSWRContract.ts
Labels: size/S

#3286 fix: Add null check to onDismiss before calling it
  src/components/ClaimNftModal/ClaimNftModal.tsx
  src/components/GlobalCheckClaimStatus/AnniversaryAchievementModal.tsx
  src/components/Menu/UserMenu/WalletInfo.tsx
  src/components/Menu/UserMenu/WalletWrongNetwork.tsx
  src/components/SearchModal/CurrencySearchModal.tsx
  src/components/TransactionConfirmationModal/index.tsx
  src/views/FarmAuction/components/PlaceBidModal.tsx
  src/views/Farms/components/DepositModal.tsx
  src/views/Farms/components/WithdrawModal.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx
  src/views/Lottery/components/BuyTicketsModal/BuyTicketsModal.tsx
  src/views/Lottery/components/ClaimPrizesModal/index.tsx
  src/views/Nft/market/Profile/components/EditProfileModal/ChangeProfilePicView.tsx
  src/views/Nft/market/Profile/components/EditProfileModal/PauseProfileView.tsx
  src/views/PancakeSquad/components/Buttons/Mint.tsx
  src/views/PancakeSquad/components/Modals/Confirm/index.tsx
  src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
  src/views/Pools/components/PoolCard/Modals/CollectModal.tsx
  src/views/Pools/components/PoolCard/Modals/StakeModal.tsx
  src/views/Predictions/Leaderboard/components/WalletStatsModal.tsx
  src/views/Predictions/components/ChartDisclaimer.tsx
  src/views/Swap/components/ImportTokenWarningModal.tsx
Labels: size/M

#3244 feat: (nft): New look for collections page
  src/components/Select/Select.tsx
  src/config/localization/translations.json
  src/state/nftMarket/hooks.ts
  src/views/Nft/market/Collections/index.tsx
Labels: size/L

#3159 feat: (profile): Remove profile state from redux
  src/hooks/useSWRContract.ts
  src/pages/_app.tsx
  src/pages/nfts/profile/[accountAddress].tsx
  src/pages/nfts/profile/[accountAddress]/achievements.tsx
  src/state/index.ts
  src/state/profile/helpers.ts
  src/state/profile/hooks.ts
  src/state/profile/index.tsx
  src/state/types.ts
  src/utils/clearUserStates.ts
  src/views/Nft/market/Profile/components/Achievements/ClaimPointsCallout.tsx
  src/views/Nft/market/Profile/components/EditProfileModal/ApproveCakeView.tsx
  src/views/Nft/market/Profile/components/EditProfileModal/ChangeProfilePicView.tsx
  src/views/Nft/market/Profile/components/EditProfileModal/PauseProfileView.tsx
  src/views/Nft/market/Profile/components/EditProfileModal/StartView.tsx
  src/views/Nft/market/Profile/index.tsx
  src/views/Nft/market/components/ProfileCell.tsx
  src/views/Nft/market/hooks/useCompleteNft.tsx
  src/views/Nft/market/hooks/useNftsForAddress.tsx
  src/views/Predictions/Leaderboard/components/Results/ConnectedWalletResult.tsx
  src/views/Predictions/Leaderboard/components/Results/RankingCard.tsx
  src/views/Predictions/Leaderboard/components/Results/ResultAvatar.tsx
  src/views/Predictions/Leaderboard/components/WalletStatsModal.tsx
  src/views/ProfileCreation/ConfirmProfileCreationModal.tsx
  src/views/TradingCompetition/components/ShareImageModal.tsx
  src/views/TradingCompetition/components/YourScore/CardUserInfo.tsx
Labels: size/XL

#3230 refactor: Remove block state from redux
  package.json
  src/hooks/useRefreshEffect.test.ts
  src/hooks/useRefreshEffect.ts
  src/hooks/useSubgraphHealth.ts
  src/state/actions.ts
  src/state/block/hooks.ts
  src/state/block/index.ts
  src/state/index.ts
  src/state/pools/hooks.ts
  src/state/pools/index.ts
  src/state/types.ts
  src/views/Home/hooks/useGetTopPoolsByApr.tsx
  yarn.lock
Labels: size/L

#3314 chore: Disable translate
  src/pages/_document.tsx
Labels: size/XS

#3313 chore: Add eventId on ErrorBoundary
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/components/Menu/UserMenu/CopyAddress.tsx
  src/config/localization/translations.json
  src/utils/copyText.ts
Labels: size/M

#3316 chore(sentry): Enable source map next folder
  next.config.js
Labels: size/XS

#3298 feat: Confirm limit order modal
  src/components/ConfirmLimitOrderModal.tsx
  src/config/localization/translations.json
Labels: size/L

#3279 fix: (profile): No Nft warning in Change profile modal
  src/views/Nft/market/Profile/components/EditProfileModal/ChangeProfilePicView.tsx
Labels: size/M

#3308 feat: Add add to metamask icon to swap page
  src/components/CurrencyInputPanel/index.tsx
Labels: size/M

#3323 chore: Add lodash import eslint
  .eslintrc
  package.json
  src/state/nftMarket/hooks.ts
  yarn.lock
Labels: size/S

#3325 ci: Add lint pr title
  .github/workflows/lintPrTitle.yml
Labels: size/S

#3326 feat: Make it clear that voting power includes CAKE before XX block
  src/config/localization/translations.json
  src/views/Voting/components/CastVoteModal/DetailsView.tsx
  src/views/Voting/components/CastVoteModal/index.tsx
  src/views/Voting/components/VoteDetailsModal.tsx
Labels: size/S

#3288 ci: Cypress test vercel preview link
  .github/workflows/integrationTests.yml
  cypress.json
  cypress/integration/nfts/nfts.test.ts
  cypress/support/commands.js
  next.config.js
  package.json
  src/utils/graphql.ts
  src/views/Nft/market/Collections/index.tsx
  yarn.lock
Labels: size/L

#3329 revert: Cypress vercel
  .github/workflows/integrationTests.yml
Labels: size/S

#3330 chore: Remove sentry dns
  sentry.client.config.js
  sentry.server.config.js
Labels: size/XS

#3304 feat: (home) Make home banner automatically appear when ifo or auction is alive or soon
  src/hooks/useActiveIfoWithBlocks.ts
  src/views/Home/components/Banners/FarmAuctionsBanner.tsx
  src/views/Home/components/Banners/HomeBanner.tsx
  src/views/Home/components/Banners/IFOBanner.tsx
  src/views/Home/index.tsx
Labels: size/L

#3327 ci: Update lp farm PR title
  .github/workflows/updateLPsAPR.yml
Labels: size/XS

#3335 fix: Missing max button translation on swap
  src/components/CurrencyInputPanel/index.tsx
Labels: size/XS

#3318 feat(swap): Error message and handle
  src/config/localization/translations.json
  src/hooks/useParsedQueryString.ts
  src/hooks/useSwapCallArguments.ts
  src/hooks/useSwapCallback.ts
  src/state/mint/hooks.ts
  src/state/swap/hooks.ts
Labels: size/L

#3340 chore: Add kodiak
  .github/.kodiak.toml
Labels: size/XS

#3344 chore: Add tooltip for community farms and reword
  src/components/Tags.tsx
  src/config/localization/translations.json
  src/views/Farms/components/FarmCard/CardHeading.tsx
  src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  src/views/Voting/components/Proposals/tags.tsx
Labels: size/M, automerge

#3345 fix: SWR fallback undefined override
  src/pages/nfts/collections/[collectionAddress].tsx
  src/pages/nfts/collections/[collectionAddress]/[tokenId].tsx
  src/pages/teams/[id].tsx
Labels: size/XS, automerge

#3341 feat(voting): Order Proposals by end ASC
  src/state/voting/helpers.ts
Labels: size/XS, automerge

#3337 fix(voting): Handle voting error when api is not stable
  src/pages/voting/proposal/[id].tsx
  src/views/Voting/Proposal/Overview.tsx
Labels: size/S, automerge

#3347 chore(pool): Add HIGH pool
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
Labels: size/M, automerge

#3223 feat: (pool): Add max stake limit ends block countdown
  src/config/abi/sousChefV2.json
  src/config/localization/translations.json
  src/state/pools/fetchPools.ts
  src/state/pools/helpers.ts
  src/state/pools/index.ts
  src/state/types.ts
  src/views/Pools/components/MaxStakeRow.tsx
  src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
Labels: size/L, automerge

#3348 chore(lottery): Replace Winner with Winning Tickets
  src/config/localization/translations.json
  src/views/Lottery/components/RewardBracketDetail.tsx
Labels: size/XS, automerge

#3350 fix(voting): Closed proposals orderDirection
  src/state/voting/helpers.ts
Labels: size/XS, automerge

#3351 fix: Voting CommunityTag
  src/components/Tags.tsx
  src/views/Voting/components/Proposals/tags.tsx
Labels: size/S, automerge

#3356 chore: Update some core farms
  src/config/constants/farms.ts
Labels: size/XS

#3358 fix: Default list token logo checksum
  src/config/constants/tokenLists/pancake-default.tokenlist.json
Labels: size/S
