Repository pancakeswap/pancake-frontend, pull requests merged in 2022-05, with the labels that each got.

#3816 chore: Bump up swiper
  package.json
  yarn.lock
Labels: size/S

#3757 fix: Excessive space in pool table stake component
  src/views/Pools/components/PoolsTable/ActionPanel/Harvest.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/styles.ts
Labels: size/XS

#3815 fix: Total locked info not visible in pools table
  src/views/Pools/components/PoolCard/CardFooter/index.tsx
  src/views/Pools/components/PoolStatsInfo.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/CakeVaultApr.tsx
  src/views/Pools/components/Stat.tsx
  src/views/Pools/components/Vault/VaultPositionTag.tsx
Labels: size/L

#3827 fix: UseIsWindowVisible hook initial state value calculated on each render
  src/hooks/useIsWindowVisible.ts
Labels: size/XS

#3826 fix: (nft): Collection listing page scroll to top button renders on each scroll event
  src/components/ScrollToTopButton/index.tsx
Labels: size/M

#3825 refactor: (nft) Use userActivity interface and remove UserNftInitializationState
  src/state/nftMarket/helpers.ts
  src/state/nftMarket/types.ts
  src/views/Nft/market/Profile/utils/sortUserActivity.tsx
Labels: size/S

#3824 perf: Use promise all to reduce execution time of farms fetch
  src/state/farms/fetchFarms.ts
  src/state/farms/index.ts
Labels: size/S

#3823 perf: Use promise all to reduce execution time of pools user data fetch
  src/state/pools/index.ts
Labels: size/S

#3822 perf: Use promise all to reduce execution time of pools public data fetch
  src/state/pools/index.ts
Labels: size/XS

#3817 fix: (pool): Lock duration hook name typo and date translation
  src/utils/timeHelper.ts
  src/views/Pools/components/LockedPool/LockedStakingApy.tsx
  src/views/Pools/components/LockedPool/hooks/useUserDataInVaultPrensenter.ts
  src/views/Pools/components/LockedPool/hooks/useUserDataInVaultPresenter.ts
  src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/AutoHarvest.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
Labels: size/L

#3831 fix: pool table view ROI calculator mobile issue
  src/views/Pools/components/Apr.tsx
  src/views/Pools/components/PoolStatsInfo.tsx
  src/views/Pools/components/Stat.tsx
Labels: size/M

#3832 feat: Galaxy NFT
  public/images/nfts/galaxy.png
  src/components/GlobalCheckClaimStatus/AnniversaryAchievementModal.tsx
  src/components/GlobalCheckClaimStatus/GalaxyNFTClaimModal.tsx
  src/components/GlobalCheckClaimStatus/index.tsx
  src/config/abi/galaxyNFTClaiming.json
  src/config/constants/contracts.ts
  src/config/constants/endpoints.ts
  src/config/constants/index.ts
  src/config/localization/translations.json
  src/hooks/useContract.ts
  src/utils/addressHelpers.ts
  src/utils/contractHelpers.ts
Labels: size/L

#3836 fix(nft): Update address
  src/config/constants/contracts.ts
Labels: size/XS

#3837 feat: Add nft drop twitter link
  src/components/GlobalCheckClaimStatus/GalaxyNFTClaimModal.tsx
  src/config/localization/translations.json
Labels: size/S

#3838 perf: Use promise all top pools by apr
  src/views/Home/hooks/useGetTopPoolsByApr.tsx
Labels: size/XS

#3835 fix: Avoid initial state calculation on each render in pools
  src/views/Pools/components/Vault/VaultRoiCalculatorModal.tsx
  src/views/Pools/hooks/useWithdrawalFeeTimer.ts
Labels: size/XS

#3833 fix: Contract hooks cause unnecessary rerenders and requests even signer not used
  src/hooks/useContract.ts
Labels: size/M

#3843 fix: NFT drop account change modal appear
  cypress/integration/nfts/nfts.test.ts
  src/components/GlobalCheckClaimStatus/index.tsx
Labels: size/XS

#3821 chore: Bump up Next
  package.json
  yarn.lock
Labels: size/L

#3803 fix: NFT activity page layout issue
  src/views/Nft/market/ActivityHistory/ActivityFilter.tsx
  src/views/Nft/market/ActivityHistory/ActivityFilters.tsx
  src/views/Nft/market/ActivityHistory/ActivityHistory.tsx
  src/views/Nft/market/ActivityHistory/ClearAllButton.tsx
  src/views/Nft/market/components/Filters/ListFilter/styles.tsx
Labels: size/S

#3845 feat: List GAL pool and farm
  public/images/tokens/0xe4Cc45Bb5DBDA06dB6183E8bf016569f40497Aa5.png
  public/images/tokens/0xe4Cc45Bb5DBDA06dB6183E8bf016569f40497Aa5.svg
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
  src/config/constants/tokens.ts
Labels: size/M

#3847 fix: Typo on tooltip hook
  packages/uikit/src/hooks/useTooltip/useTooltip.tsx
Labels: size/XS

#3846 fix: Can return contract check in useContract hook
  src/hooks/useContract.ts
Labels: size/XS

#3851 fix: Swap import token
  src/state/index.ts
Labels: size/S

#3854 chore: Change default trustwallet logo url
  src/views/Info/components/CurrencyLogo/index.tsx
Labels: size/XS, automerge

#3857 fix: Typo on uikit
  packages/uikit/src/hooks/useMatchBreakpoints.ts
  packages/uikit/src/hooks/useTooltip/useTooltip.stories.tsx
Labels: size/XS

#3858 fix: Uikit https warning
  packages/uikit/src/components/Image/tokens.ts
Labels: size/XS

#3862 feat: trading competition MoD
  public/images/achievements/MoD-champion-bronze.svg
  public/images/achievements/MoD-champion-gold.svg
  public/images/achievements/MoD-champion-silver.svg
  public/images/achievements/MoD-participant-bronze.svg
  public/images/achievements/MoD-participant-gold.svg
  public/images/achievements/MoD-participant-silver.svg
  public/images/achievements/MoD-top-10-bronze.svg
  public/images/achievements/MoD-top-10-gold.svg
  public/images/achievements/MoD-top-10-silver.svg
  public/images/achievements/MoD-top-100-bronze.svg
  public/images/achievements/MoD-top-100-gold.svg
  public/images/achievements/MoD-top-100-silver.svg
  public/images/achievements/MoD-top-500-bronze.svg
  public/images/achievements/MoD-top-500-gold.svg
  public/images/achievements/MoD-top-500-silver.svg
  src/config/abi/tradingCompetitionMoD.json
  src/config/constants/contracts.ts
  src/config/constants/trading-competition/phases.ts
  src/config/constants/trading-competition/prizes.ts
  src/config/localization/translations.json
  src/hooks/useContract.ts
  src/utils/addressHelpers.ts
  src/utils/contractHelpers.ts
  src/views/TradingCompetition/MoDCompetition.tsx
  src/views/TradingCompetition/components/BattleBanner/index.tsx
  src/views/TradingCompetition/components/ClaimModal/index.tsx
  src/views/TradingCompetition/components/HowToJoin/index.tsx
  src/views/TradingCompetition/components/PrizesInfo/PrizesCard.tsx
  src/views/TradingCompetition/components/PrizesInfo/PrizesText.tsx
  src/views/TradingCompetition/components/RegisterModal/RegisterWithProfile.tsx
  src/views/TradingCompetition/components/Rules/FAQs.tsx
  src/views/TradingCompetition/components/Rules/index.tsx
  src/views/TradingCompetition/components/TeamRanks/index.tsx
  src/views/TradingCompetition/index.tsx
  src/views/TradingCompetition/pageSectionStyles.tsx
  src/views/TradingCompetition/pngs/MoD-bg-shine.png
  src/views/TradingCompetition/pngs/MoD-caker.png
  src/views/TradingCompetition/pngs/MoD-flipper.png
  src/views/TradingCompetition/pngs/MoD-hero-bunnies.png
  src/views/TradingCompetition/pngs/MoD-storm-bunny.png
  src/views/TradingCompetition/pngs/mod-mesh.png
  src/views/TradingCompetition/pngs/mod-text-light.png
  src/views/TradingCompetition/styles.ts
  src/views/TradingCompetition/svgs/MoDLogo.tsx
  src/views/TradingCompetition/svgs/index.tsx
Labels: size/XXL

#3864 feat: TC Menu soon
  src/components/Menu/config/config.ts
Labels: size/XS

#3866 chore: adjust wording for TC
  src/config/localization/translations.json
  src/views/TradingCompetition/components/PrizesInfo/PrizesText.tsx
Labels: size/S

#3865 chore: Show Mod banner
  src/config/localization/translations.json
  src/views/Home/components/Banners/CompetitionBanner.tsx
  src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  src/views/Home/components/Banners/images/index.ts
  src/views/Home/components/Banners/images/mbox-tc-desktop.png
  src/views/Home/components/Banners/images/mbox-tc-mobile.png
  src/views/Home/components/Banners/images/mod-tc-desktop.png
  src/views/Home/components/Banners/images/mod-tc-mobile.png
  src/views/Home/components/Banners/images/mod-white-logo.png
Labels: size/M, automerge

#3870 refactor: Make initial state calculation once in useLast hook
  src/hooks/useLast.ts
Labels: size/XS

#3869 chore: Remove deprecated substr
  cypress/support/commands.js
  src/utils/formatTimePeriod.ts
  src/utils/uriToHttp.ts
Labels: size/S

#3876 chore: (useBUSDPrice): Use bnb name instead of eth
  src/hooks/useBUSDPrice.ts
Labels: size/S

#3874 refactor: (voting): Make create proposal initial state run once
  src/views/Voting/CreateProposal/index.tsx
Labels: size/XS

#3873 chore: Add transaction type on transaction history for swap and liquidity
  src/hooks/useApproveCallback.ts
  src/hooks/useSwapCallback.ts
  src/hooks/useWrapCallback.ts
  src/state/transactions/actions.ts
  src/views/AddLiquidity/index.tsx
  src/views/RemoveLiquidity/index.tsx
Labels: size/S

#3867 perf: Reduce banner check calls by only making with intervals
  src/views/Home/components/Banners/hooks/useIsRenderLotteryBanner.tsx
Labels: size/XS, automerge

#3872 refactor: Use same default input output currency constants
  src/config/constants/index.ts
  src/state/limitOrders/constants.ts
  src/state/limitOrders/hooks.ts
  src/state/swap/constants.ts
  src/state/swap/hooks.test.ts
  src/state/swap/hooks.ts
Labels: size/S, automerge

#3871 refactor: Use cached big number in farms fetching
  src/state/farms/fetchFarms.ts
  src/state/farmsV1/fetchFarms.ts
  src/utils/bigNumber.ts
Labels: size/XS, automerge

#3878 feat: Update 8pay project wallet address
  src/config/constants/farmAuctions.ts
Labels: size/M, automerge

#3841 perf: Don't make price requests when view mode is card and not sorted by price
  src/views/Nft/market/Collections/index.tsx
Labels: size/M, automerge

#3882 perf: Reduce image size
  public/images/decorations/3d-ifo-duet.png
  public/images/decorations/auction-bunny.png
  public/images/decorations/vrbunny.png
  public/images/easter-battle.png
  public/images/hero.png
  public/images/nfts/galaxy.png
Labels: size/XS

#3883 perf: Use png for tokens
  packages/uikit/src/components/Image/index.stories.tsx
  src/components/TokenImage/index.tsx
  src/views/Home/components/Banners/IFOBanner.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/GetTokenModal.tsx
Labels: size/S

#3884 chore: Update trust wallet logo asset url
  src/views/Info/components/CurrencyLogo/index.tsx
Labels: size/XS

#3886 perf: Reduce image size 2
  public/images/help.png
  public/images/hero.png
  public/logo.png
  src/utils/getTokenLogoURL.ts
Labels: size/XS

#3888 perf: Reduce image size 3
  public/images/burnt-cake.png
  public/images/competition/banner-star.png
  public/images/competition/banner.png
  public/images/competition/banner_sm.png
  public/images/easter-battle.png
  public/images/ifos/assets/ifo-banner-dark.png
  public/images/ifos/assets/ifo-banner-light.png
  public/images/ifos/assets/ifo-coming-soon-desktop.png
  public/images/ifos/assets/ifo-coming-soon.png
  public/images/lottery/tombola.png
  public/images/nfts/baller-lg.png
  public/images/nfts/cakeston-easter-21-lg.png
  public/images/nfts/christmas-2021.png
  public/images/nfts/claire-lg.png
  public/images/nfts/easter-champion-storm-lg.png
  public/images/nfts/flipsie-easter-21-lg.png
  public/images/nfts/lottie-lg.png
  public/images/nfts/lucky-lg.png
  public/images/nfts/mixie-1-lg.png
  public/images/nfts/mixie-2-lg.png
  public/images/nfts/mixie-3-lg.png
  public/images/nfts/panurai-lg.png
  public/images/nfts/stormy-easter-21-lg.png
  public/images/prediction_promotion.png
  public/images/teams/cakers-banner.png
  public/images/teams/fearsome-flippers-lg.png
  public/images/teams/flippers-banner.png
  public/images/teams/storm-banner.png
  public/images/teams/syrup-storm-lg.png
Labels: size/XS

#3839 fix: Migration page new cake pool add cake button gets stuck and use userdataloaded per pool
  src/state/pools/index.ts
  src/state/types.ts
  src/views/Migration/components/MigrationStep2/NewPool/PoolRow.tsx
  src/views/Migration/components/MigrationStep2/NewPool/index.tsx
  src/views/Pools/components/CakeVaultCard/VaultCardActions/VaultStakeActions.tsx
  src/views/Pools/components/LockedPool/Buttons/AddCakeButton.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/AutoHarvest.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/Harvest.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
  src/views/Pools/components/PoolsTable/Cells/EarningsCell.tsx
  src/views/Pools/components/PoolsTable/Cells/StakedCell.tsx
  src/views/Pools/components/PoolsTable/PoolRow.tsx
  src/views/Pools/components/PoolsTable/PoolsTable.tsx
  src/views/Pools/index.tsx
Labels: size/M

#3885 chore: close the GalaxyNFTClaim event
  src/components/GlobalCheckClaimStatus/index.tsx
Labels: size/XS

#3889 chore: update TC image to 2x
  src/views/Home/components/Banners/images/mod-tc-desktop.png
  src/views/Home/components/Banners/images/mod-tc-mobile.png
Labels: size/XS

#3880 feat: (farms): Add auction core tags to table view
  src/views/Farms/Farms.tsx
  src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  src/views/Farms/components/FarmTable/Row.tsx
  src/views/Farms/components/types.ts
Labels: size/L

#3887 feat: List farm auction 21 winners
  public/images/tokens/0x7324c7C0d95CEBC73eEa7E85CbAac0dBdf88a05b.png
  src/config/constants/farms.ts
  src/config/constants/tokens.ts
Labels: size/M

#3899 chore: compress MoD assets to save bandwidth
  public/images/competition/banner-star.png
  src/views/Home/components/Banners/images/mod-white-logo.png
  src/views/TradingCompetition/components/BattleBanner/index.tsx
  src/views/TradingCompetition/pngs/MoD-bg-shine.png
  src/views/TradingCompetition/pngs/MoD-caker.png
  src/views/TradingCompetition/pngs/MoD-flipper.png
  src/views/TradingCompetition/pngs/MoD-hero-bunnies.png
  src/views/TradingCompetition/pngs/MoD-storm-bunny.png
  src/views/TradingCompetition/pngs/mod-mesh.png
  src/views/TradingCompetition/pngs/mod-text-light.png
Labels: size/XS

#3892 feat: Update useEagerConnect logic
  src/hooks/useEagerConnect.ts
Labels: size/S

#3900 chore: Prettier add json format
  .lintstagedrc
  package.json
Labels: size/XS

#3903 fix(voting): Chunk voters
  src/state/voting/helpers.ts
Labels: size/S

#3904 fix(voting): missing block number
  src/state/voting/helpers.ts
Labels: size/XS

#3902 style: Fix Trading Competition banner style
  public/images/competition/banner-star.png
  src/views/TradingCompetition/MoDCompetition.tsx
  src/views/TradingCompetition/components/BattleBanner/index.tsx
Labels: size/M, automerge

#3894 fix: wrong query condition in token transaction
  src/state/info/queries/tokens/transactions.ts
Labels: size/XS

#3906 perf: Use promise all when fetching pb all nfts
  src/views/Nft/market/hooks/useAllPancakeBunnyNfts.ts
Labels: size/XS

#3897 perf: Make User detail component render only one component based on device
  src/views/Home/components/UserBanner/UserDetail.tsx
Labels: size/M

#3910 fix: Update lintstagedrc json format
  .lintstagedrc
Labels: size/XS

#3911 perf: Reduce image size 4
  next.config.js
  public/images/decorations/countdownBg.png
  src/views/Home/components/Banners/images/IFO.png
  src/views/Home/components/Banners/images/competition.png
  src/views/Home/components/Banners/images/competitionMobile.png
  src/views/Home/components/Banners/images/lottery.png
Labels: size/S

#3912 fix: TW token logo url
  src/utils/getTokenLogoURL.ts
Labels: size/XS

#3920 perf: Use promise all in info
  src/state/info/queries/protocol/overview.ts
Labels: size/XS

#3919 perf: Use promise all in lottery
  src/state/lottery/getLotteriesData.ts
  src/state/lottery/getUserLotteryData.ts
Labels: size/XS

#3918 perf: Use promise all in fetching vault public data
  src/state/pools/fetchVaultPublic.ts
Labels: size/S

#3917 perf: Use promise all in get active pools
  src/utils/calls/pools.ts
Labels: size/XS

#3915 perf: Use promise all derived price data
  src/state/swap/fetch/fetchDerivedPriceData.ts
Labels: size/XS

#3914 refactor: Use promise all lottery previous round
  src/views/Lottery/components/ViewTicketsModal/PreviousRoundTicketsInner.tsx
Labels: size/XS

#3908 refactor: Use optional chaining for profile
  src/views/TradingCompetition/components/RegisterModal/index.tsx
  src/views/TradingCompetition/components/YourScore/CardUserInfo.tsx
Labels: size/XS

#3893 feat: Make isCommunity data fetched from farm auction on chain contract
  src/config/constants/farms.ts
  src/config/constants/index.ts
  src/config/constants/types.ts
  src/config/localization/translations.json
  src/state/farms/fetchFarmsWithAuctions.ts
  src/state/farms/getFarmsAuctionData.ts
  src/state/farms/hooks.ts
  src/state/farms/index.ts
  src/state/farms/selectors.ts
  src/views/FarmAuction/helpers.tsx
  src/views/Farms/components/FarmCard/DetailsSection.tsx
  src/views/Farms/components/FarmCard/FarmCard.tsx
  src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
Labels: size/L

#3931 feat: List METIS farm and pool
  public/images/tokens/0xe552Fb52a4F19e44ef5A967632DBc320B0820639.png
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
  src/config/constants/tokens.ts
Labels: size/M

#3809 chore(infra): Add next-transpile
  next.config.js
  package.json
  packages/uikit/package.json
  tsconfig.json
  yarn.lock
Labels: Delayed Release, size/M

#3936 fix: Missing translation on modals max button
  src/views/FarmAuction/components/PlaceBidModal.tsx
  src/views/Lottery/components/BuyTicketsModal/BuyTicketsModal.tsx
Labels: size/XS

#3933 fix: (cake pool): Expected roi calculation in other languages
  src/utils/formatBalance.ts
  src/views/Pools/components/LockedPool/utils/formatRoi.ts
Labels: size/S

#3834 fix: Avoid initial state calculation on each render in last updated hook
  src/hooks/useLastUpdated.ts
Labels: size/XS

#3828 fix: (prediction): Round card arrow svgs disappears on ios browsers after making app on foreground again
  packages/uikit/src/components/Svg/Svg.tsx
Labels: size/XS

#3938 chore: Add litepaper
  src/components/Menu/config/footerConfig.ts
  src/config/localization/translations.json
Labels: size/XS

#3930 feat: MoD TC starting period
  src/views/TradingCompetition/MoDCompetition.tsx
  src/views/TradingCompetition/MoboxCompetition.tsx
  src/views/TradingCompetition/components/ClaimModal/index.tsx
  src/views/TradingCompetition/helpers.ts
  src/views/TradingCompetition/mobox/components/YourScore/MoboxUserPrizeGrid.tsx
  src/views/TradingCompetition/mod/components/YourScore/ModUserPrizeGrid.tsx
  src/views/TradingCompetition/mod/components/YourScore/ModYourScore.tsx
  src/views/TradingCompetition/types.ts
Labels: size/L

#3928 chore: Swap sound IPFS
  public/swap.mp3
  src/components/SearchModal/swapSound.ts
Labels: size/XS

#3929 chore: Cache images
  next.config.js
  public/favicon.ico
  public/logo.png
  public/manifest.json
Labels: size/S

#3940 fix: Prediction page UI
  src/views/Predictions/Desktop.tsx
  src/views/Predictions/components/History/PnlTab/PnlChart.tsx
  src/views/Predictions/components/History/PnlTab/PnlTab.tsx
  src/views/Predictions/components/History/PnlTab/SummaryRow.tsx
Labels: size/S, automerge

#3941 feat: MoD TC UI details
  packages/uikit/src/components/Skeleton/Skeleton.tsx
  src/config/localization/translations.json
  src/views/TradingCompetition/MoDCompetition.tsx
  src/views/TradingCompetition/components/TeamRanks/TopTradersCard/ExpandedGridItem.tsx
  src/views/TradingCompetition/components/TeamRanks/TopTradersCard/GridItem.tsx
  src/views/TradingCompetition/mod/components/BattleBanner/ModBattleBanner.tsx
  src/views/TradingCompetition/mod/components/PrizesInfo/ModPrizesInfo.tsx
  src/views/TradingCompetition/mod/components/YourScore/ModYourScore.tsx
  src/views/TradingCompetition/useTeamInformation.ts
Labels: size/M

#3944 fix: (trading-competition): Participant data in team ranks
  src/config/constants/endpoints.ts
  src/views/TradingCompetition/MoDCompetition.tsx
  src/views/TradingCompetition/MoboxCompetition.tsx
  src/views/TradingCompetition/components/TeamRanks/Podium/useGetParticipants.ts
  src/views/TradingCompetition/components/TeamRanks/TeamRanksWithParticipants.tsx
Labels: size/S

#3946 chore: MoD TC UI details part2
  src/config/localization/translations.json
  src/views/TradingCompetition/MoDCompetition.tsx
  src/views/TradingCompetition/components/BattleCta/index.tsx
  src/views/TradingCompetition/mod/components/BattleBanner/ModBattleBanner.tsx
  src/views/TradingCompetition/mod/components/YourScore/ModYourScore.tsx
  src/views/TradingCompetition/pngs/MoD-banner-dar.png
  src/views/TradingCompetition/pngs/MoD-banner-dar2.png
  src/views/TradingCompetition/pngs/MoD-banner-dar3.png
  src/views/TradingCompetition/types.ts
Labels: size/L

#3916 fix: Finished competition banners size in mobile
  src/views/TradingCompetition/components/FinishedCompetitionBanner/index.tsx
Labels: size/XS

#3952 chore: Update chainlink description
  src/config/localization/translations.json
  src/views/Predictions/components/ChainlinkChartDisclaimer.tsx
Labels: size/XS

#3953 fix: Trading competition menu shows soon when loading page
  src/components/Menu/hooks/useCompetitionStatus.ts
Labels: size/XS

#3945 fix: Cake Pool slider reset after ROI
  src/views/Pools/components/LockedPool/Common/BalanceField.tsx
Labels: size/S

#3948 fix: Missing max translation on remove liquidity
  src/views/RemoveLiquidity/index.tsx
Labels: size/XS

#3875 feat: (limit-orders): Add import token warning modal
  src/components/ImportTokenWarningModal.tsx
  src/views/LimitOrders/index.tsx
  src/views/Swap/index.tsx
Labels: size/M

#3814 fix: Modal close on overlay click cannot be disabled
  packages/uikit/src/widgets/Modal/ModalContext.tsx
  packages/uikit/src/widgets/Modal/useModal.ts
  src/views/Swap/components/SwapWarningModal/index.tsx
  src/views/Swap/index.tsx
Labels: size/M

#3956 fix(farms): Keep auction label after end
  src/state/farms/fetchFarmsWithAuctions.ts
Labels: size/XS

#3959 revert(farms): Keep auction label after end
  src/state/farms/fetchFarmsWithAuctions.ts
Labels: size/XS

#3947 feat(wallet): Add Opera option
  packages/uikit/src/components/Svg/Icons/Opera.tsx
  packages/uikit/src/components/Svg/index.tsx
  packages/uikit/src/react-app-env.d.ts
  packages/uikit/src/widgets/WalletModal/ConnectModal.tsx
  packages/uikit/src/widgets/WalletModal/WalletCard.tsx
  packages/uikit/src/widgets/WalletModal/config.tsx
  packages/uikit/src/widgets/WalletModal/types.ts
  src/hooks/useEagerConnect.ts
  src/react-app-env.d.ts
Labels: size/M

#3960 fix(farms): Mark auction only farms is community
  src/config/constants/farms.ts
Labels: size/XS

#3967 fix: Auction hosting seconds
  src/config/constants/index.ts
Labels: size/XS

#3971 fix: Dar volume rank
  src/views/TradingCompetition/mod/components/YourScore/ModYourScore.tsx
Labels: size/XS

#3972 fix: (farms): Invalid date on farm auction hosting data after hosting period ends
  src/views/Farms/components/FarmCard/DetailsSection.tsx
  src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
Labels: size/XS

#3969 New Crowdin updates
  public/locales/ar-SA.json
  public/locales/bn-BD.json
  public/locales/de-DE.json
  public/locales/el-GR.json
  public/locales/en-US.json
  public/locales/es-ES.json
  public/locales/fi-FI.json
  public/locales/fil-PH.json
  public/locales/fr-FR.json
  public/locales/hi-IN.json
  public/locales/hu-HU.json
  public/locales/id-ID.json
  public/locales/it-IT.json
  public/locales/ja-JP.json
  public/locales/ko-KR.json
  public/locales/nl-NL.json
  public/locales/pl-PL.json
  public/locales/pt-BR.json
  public/locales/pt-PT.json
  public/locales/ro-RO.json
  public/locales/ru-RU.json
  public/locales/sv-SE.json
  public/locales/ta-IN.json
  public/locales/tr-TR.json
  public/locales/uk-UA.json
  public/locales/vi-VN.json
  public/locales/zh-CN.json
  public/locales/zh-TW.json
Labels: size/XXL

#3951 fix: Extend button to not disable if at least 1 week can be extended
  src/config/constants/pools.tsx
  src/views/Pools/components/LockedPool/Buttons/ExtendDurationButton.tsx
  src/views/Pools/components/LockedPool/hooks/useLockedPool.tsx
Labels: size/S

#3977 fix: (uikit): Menu stories
  packages/uikit/src/widgets/Menu/index.stories.tsx
Labels: size/S

#3975 fix: Locked Pool min duration extend
  src/views/Pools/components/LockedPool/Buttons/AddCakeButton.tsx
  src/views/Pools/components/LockedPool/Modals/AddAmountModal.tsx
  src/views/Pools/components/LockedPool/hooks/useLockedPool.tsx
  src/views/Pools/components/LockedPool/types/index.ts
Labels: size/M

#3980 feat(wallet): Handle TW on desktop and add deeplink
  packages/uikit/src/widgets/WalletModal/ConnectModal.tsx
  packages/uikit/src/widgets/WalletModal/WalletCard.tsx
  packages/uikit/src/widgets/WalletModal/config.tsx
  packages/uikit/src/widgets/WalletModal/types.ts
Labels: size/S

#3989 perf: (pools): Put block number fetch inside promise all
  src/state/pools/index.ts
Labels: size/XS

#3988 perf: Use promise all subgraph health
  src/hooks/useSubgraphHealth.ts
Labels: size/S

#3987 feat: Make multiple banners shuffled to show a random banner each time homepage visited
  src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/M

#3984 perf: (farm-auction): Make total burned amount request only when it is visible
  src/views/FarmAuction/components/AuctionCakeBurn.tsx
Labels: size/XS

#3978 fix: Prediction shows old user data when switching account
  src/hooks/useAccountLocalEventListener.ts
  src/views/Predictions/index.tsx
Labels: size/S

#3901 perf: Dont load floating pancakes wrapper on mobile
  src/views/Home/components/Footer.tsx
Labels: size/S

#3976 perf: (menu): Make bnb account balance call only when dropdown user menu open
  packages/uikit/src/widgets/Menu/components/UserMenu/index.tsx
  packages/uikit/src/widgets/Menu/components/UserMenu/types.ts
  src/components/Menu/UserMenu/WalletUserMenuItem.tsx
  src/components/Menu/UserMenu/index.tsx
Labels: size/M

#3965 refactor: Remove duplicate utils functions in pools
  src/views/Pools/components/LockedPool/Common/LockDurationField.tsx
  src/views/Pools/components/LockedPool/Common/Overview/index.tsx
  src/views/Pools/components/LockedPool/hooks/useAvgLockDuration.tsx
  src/views/Pools/components/LockedPool/hooks/useUserDataInVaultPresenter.ts
  src/views/Pools/components/LockedPool/utils/formatSecondsToWeeks.ts
Labels: size/S

#3962 chore: Bump up swiper
  package.json
  yarn.lock
Labels: size/S

#3961 chore: Bump up next themes
  package.json
  yarn.lock
Labels: size/S

#3950 perf: (prediction-card): Fetch bnb price only when visible on home page
  src/views/Home/components/WinSection/PredictionCardContent.tsx
Labels: size/S

#3981 fix: Locked Pool renew duration 1 week after add cake
  src/views/Pools/components/LockedPool/Modals/AddAmountModal.tsx
Labels: size/S

#3932 fix: (currency-search): Exact matched tokens not on top in currency search
  src/components/SearchModal/CurrencySearch.tsx
  src/components/SearchModal/filtering.ts
Labels: size/M

#3985 feat: Add perpetual banner
  src/config/localization/translations.json
  src/views/Home/components/Banners/PerpetualBanner.tsx
  src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  src/views/Home/components/Banners/images/index.ts
  src/views/Home/components/Banners/images/perpetual.png
  src/views/Home/components/Banners/images/perpetualMobile.png
Labels: size/M, automerge

#3968 perf: Reduce lottery card content calls
  src/views/Home/components/WinSection/LotteryCardContent.tsx
Labels: size/S

#3991 fix: Don't clear connectorIdv2 when user switching account
  src/hooks/useAccountEventListener.ts
  src/hooks/useAuth.tsx
  src/utils/clearUserStates.ts
Labels: size/S

#3995 feat: List MIX farm and pool
  public/images/tokens/0x398f7827DcCbeFe6990478876bBF3612D93baF05.png
  src/config/__tests__/tokens.test.ts
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
  src/config/constants/tokens.ts
Labels: size/M

#3996 chore(wallet): Update Opera wallet name
  packages/uikit/src/widgets/WalletModal/config.tsx
Labels: size/XS

#3999 fix(wallet): TW deeplink https
  packages/uikit/src/widgets/WalletModal/config.tsx
Labels: size/XS

#3997 chore(swap): Remove UST as trade against base
  src/config/constants/index.ts
  src/hooks/__snapshots__/Trades.test.ts.snap
Labels: size/XL

#4003 chore(home): Update burn and add circulatingSupply
  src/config/localization/translations.json
  src/views/Home/components/CakeDataRow.tsx
Labels: size/M

#4005 chore: update perpetual banner image to 2x
  src/views/Home/components/Banners/images/perpetual.png
  src/views/Home/components/Banners/images/perpetualMobile.png
Labels: size/XS

#4006 chore: Tally period UI for TC
  packages/uikit/src/components/Svg/Icons/Twitter.tsx
  src/config/localization/translations.json
  src/views/TradingCompetition/components/BattleCta/index.tsx
Labels: size/M

#4007 fix: Tally period month display
  src/views/TradingCompetition/components/BattleCta/index.tsx
Labels: size/XS

#4008 chore: Finished initial state for TC
  src/views/TradingCompetition/MoDCompetition.tsx
  src/views/TradingCompetition/components/BattleCta/index.tsx
Labels: size/XS

#4001 chore: Bump up redux to 8.0.2
  package.json
  src/state/index.ts
  src/state/pools/index.ts
  src/state/types.ts
  src/views/Pools/components/PoolCard/Modals/CollectModal.tsx
  src/views/Pools/components/PoolCard/Modals/StakeModal.tsx
  src/views/Pools/hooks/useApprove.tsx
  yarn.lock
Labels: size/L

#4010 chore(auction): Whitelist 22
  src/config/constants/farmAuctions.ts
Labels: size/XS

#4011 feat: Add MoD TC campaign ids
  src/config/constants/campaigns.ts
Labels: size/M

#4014 chore: Bump up recharts
  package.json
  yarn.lock
Labels: size/M

#3998 fix: (liquidity): Unnecessary forwarding when manage pool clicked in import page
  src/views/PoolFinder/index.tsx
Labels: size/XS

#4016 chore: claiminng phase for TC
  src/config/localization/translations.json
  src/views/TradingCompetition/MoDCompetition.tsx
  src/views/TradingCompetition/components/ClaimModal/index.tsx
  src/views/TradingCompetition/components/ShareImageModal.tsx
  src/views/TradingCompetition/components/YourScore/AchievementPoints.tsx
  src/views/TradingCompetition/components/YourScore/CardUserInfo.tsx
  src/views/TradingCompetition/mod/components/YourScore/ModUserPrizeGrid.tsx
  src/views/TradingCompetition/mod/components/YourScore/ModYourScore.tsx
  src/views/TradingCompetition/pngs/MoD-cakers-share.png
  src/views/TradingCompetition/pngs/MoD-flippers-share.png
  src/views/TradingCompetition/pngs/MoD-nft-prize.png
  src/views/TradingCompetition/pngs/MoD-storm-share.png
Labels: size/M

#4013 chore: Bump up react window for react 18 support
  package.json
  yarn.lock
Labels: size/S

#4000 perf: Reduce owner of onchain requests
  src/views/Nft/market/hooks/useCompleteNft.tsx
  src/views/Nft/market/hooks/useNftOwner.tsx
Labels: size/S

#4019 chore: update MoD TC SC address
  src/config/constants/contracts.ts
  src/config/localization/translations.json
  src/views/TradingCompetition/MoDCompetition.tsx
  src/views/TradingCompetition/components/ClaimModal/index.tsx
  src/views/TradingCompetition/mod/components/YourScore/ModUserPrizeGrid.tsx
  src/views/TradingCompetition/useCanClaimSpecialNFT.ts
Labels: size/M

#4021 feat: Sort farm auction winner
  src/config/constants/farms.ts
Labels: size/M, automerge

#4024 chore: Fix warnings
  src/views/TradingCompetition/components/BattleCta/index.tsx
Labels: size/XS

#4023 fix: (competition): Prize claim button still available after claim
  src/config/abi/tradingCompetitionMoD.json
  src/views/TradingCompetition/MoDCompetition.tsx
Labels: size/M

#4034 chore: Fix typos
  src/components/Balance.tsx
  src/components/GlobalCheckClaimStatus/index.tsx
  src/hooks/limitOrders/useGelatoLimitOrdersHandlers.ts
  src/state/limitOrders/hooks.ts
  src/utils/clearUserStates.ts
  src/views/LimitOrders/hooks/useGelatoLimitOrdersHistory.ts
  src/views/Swap/components/Chart/SwapLineChart.tsx
Labels: size/M

#4035 perf: Memoize menu items
  packages/uikit/src/components/BottomNav/BottomNav.tsx
  packages/uikit/src/components/MenuItems/MenuItems.tsx
Labels: size/XS

#4036 perf: (auction-voting): Make visible prefetch false for links
  src/views/Farms/Farms.tsx
  src/views/Voting/components/Footer.tsx
  src/views/Voting/components/Hero.tsx
Labels: size/XS

#4033 feat: Add cake modal input empty
  src/views/Pools/components/LockedPool/Modals/AddAmountModal.tsx
Labels: size/XS, automerge

#4029 chore: NFT Marketplace wording fixes
  public/locales/ar-SA.json
  public/locales/bn-BD.json
  public/locales/de-DE.json
  public/locales/el-GR.json
  public/locales/en-US.json
  public/locales/es-ES.json
  public/locales/fi-FI.json
  public/locales/fil-PH.json
  public/locales/fr-FR.json
  public/locales/hi-IN.json
  public/locales/hu-HU.json
  public/locales/id-ID.json
  public/locales/it-IT.json
  public/locales/ja-JP.json
  public/locales/ko-KR.json
  public/locales/nl-NL.json
  public/locales/pl-PL.json
  public/locales/pt-BR.json
  public/locales/pt-PT.json
  public/locales/ro-RO.json
  public/locales/ru-RU.json
  public/locales/sv-SE.json
  public/locales/ta-IN.json
  public/locales/tr-TR.json
  public/locales/uk-UA.json
  public/locales/vi-VN.json
  public/locales/zh-CN.json
  public/locales/zh-TW.json
  src/config/localization/translations.json
  src/views/Nft/market/Home/config.tsx
  src/views/Nft/market/Home/index.tsx
  src/views/PancakeSquad/components/EventStepsSection/index.tsx
  src/views/PancakeSquad/components/Header/index.tsx
Labels: size/L, automerge
