Repository pancakeswap/pancake-frontend, pull requests merged in 2022-06, with the labels that each got.

#4040 chore: Skeleton component support border radius
  packages/uikit/src/components/Skeleton/Skeleton.tsx
  packages/uikit/src/components/Skeleton/types.ts
  src/views/TradingCompetition/components/TeamRanks/TopTradersCard/ExpandedGridItem.tsx
  src/views/TradingCompetition/components/TeamRanks/TopTradersCard/GridItem.tsx
Labels: size/S

#4039 perf(pools): Move all known finished pools
  src/config/constants/pools.tsx
Labels: size/S

#4041 fix: Avoid flashing when searching token by address
  src/components/SearchModal/CurrencySearch.tsx
Labels: size/L

#4043 refactor: Remove redundant div block
  src/config/constants/types.ts
  src/views/Nft/market/Home/Newest.tsx
Labels: size/XS

#4046 chore: Bump up redux toolkit for react 18 support
  package.json
  yarn.lock
Labels: size/S

#3964 fix: (trading-competition): Finished competitions show double prizes info grid
  src/views/TradingCompetition/MoDCompetition.tsx
  src/views/TradingCompetition/components/PrizesInfoSection.tsx
Labels: size/M

#4044 perf: Remove redundant deserialize farm in farm selector hooks
  src/state/farms/selectors.ts
Labels: size/S

#3982 perf: Use promise all in account nft data
  src/state/nftMarket/helpers.ts
Labels: size/M

#3905 fix: (nft): Nft activity metadata uniq function iteratee
  src/views/Nft/market/ActivityHistory/ActivityHistory.tsx
  src/views/Nft/market/ActivityHistory/utils/fetchActivityNftMetadata.tsx
  src/views/Nft/market/Profile/components/ActivityHistory/index.tsx
Labels: size/M

#4048 feat: Sort farm CHR
  src/config/constants/farms.ts
  src/config/constants/pools.tsx
Labels: size/M

#4049 fix: Media queries off by 1px
  packages/uikit/src/hooks/useMatchBreakpoints.ts
Labels: size/XS

#4053 fix(wallet): Coinbase eager connect keep deeplink on mobile
  packages/uikit/src/react-app-env.d.ts
  src/hooks/useEagerConnect.ts
  src/react-app-env.d.ts
Labels: size/XS

#4054 chore(pool): XCN pool
  src/config/constants/pools.tsx
Labels: size/S

#4051 feat: (liquidity) Add lp reward apr info to the lps in liquidity pages
  src/__tests__/views/info/utils/infoData.test.ts
  src/__tests__/views/info/utils/infoQueryHelpers.test.ts
  src/components/PositionCard/index.tsx
  src/pages/index.tsx
  src/state/info/queries/pools/poolData.ts
  src/state/info/queries/pools/topPools.ts
  src/state/info/queries/protocol/overview.ts
  src/state/info/queries/tokens/priceData.ts
  src/state/info/queries/tokens/tokenData.ts
  src/state/info/queries/tokens/topTokens.ts
  src/state/swap/fetch/fetchDerivedPriceData.ts
  src/state/swap/hooks.ts
  src/utils/getBlocksFromTimestamps.ts
  src/utils/getChangeForPeriod.ts
  src/utils/getDeltaTimestamps.ts
  src/utils/getLpFeesAndApr.ts
  src/views/AddLiquidity/index.tsx
  src/views/Info/hooks/useBlocksFromTimestamps.ts
  src/views/Info/hooks/useBnbPrices.ts
  src/views/Info/utils/infoDataHelpers.ts
  src/views/Info/utils/infoQueryHelpers.ts
  src/views/RemoveLiquidity/index.tsx
Labels: size/L

#4056 feat: List Farm Auction 23
  src/config/constants/farmAuctions.ts
Labels: size/XS

#4063 fix(farms): LP balance decimals ui
  src/utils/formatBalance.ts
  src/views/Farms/components/StakedLP.tsx
  src/views/Migration/components/MigrationStep1/OldFarm/ActionPanel/Staked.tsx
  src/views/Migration/components/MigrationStep1/OldFarm/Cells/Staked.tsx
Labels: size/M

#4064 fix: (nft): Set price with decimals in mobile cannot be placed
  src/views/Nft/market/components/BuySellModals/SellModal/SetPriceStage.tsx
Labels: size/S

#4066 chore: Unsupport pokemoney
  src/config/constants/lists.ts
  src/config/constants/tokenLists/pancake-warning.tokenlist.json
  src/hooks/Tokens.ts
  src/hooks/Trades.ts
  src/state/lists/hooks.ts
  src/views/AddLiquidity/index.tsx
Labels: size/M

#4067 feat: Add rugpull warning
  src/config/constants/rugPullTokens.ts
  src/config/constants/swapWarningTokens.ts
  src/config/constants/tokens.ts
  src/config/localization/translations.json
  src/views/Swap/components/SwapWarningModal/RugPullWarning.tsx
  src/views/Swap/components/SwapWarningModal/index.tsx
Labels: size/M

#4068 feat: List Farm Auction 23 winner
  public/images/tokens/0x630d98424eFe0Ea27fB1b3Ab7741907DFFEaAd78.png
  src/config/constants/farms.ts
  src/config/constants/tokens.ts
Labels: size/M

#4070 fix: Missing auction hosting ends info in community farms
  src/config/constants/farms.ts
Labels: size/XS

#4072 chore: Bump up swiper
  package.json
  src/views/Home/components/Banners/MultipleBanner.tsx
  yarn.lock
Labels: size/S

#3766 refactor: Use accurate timer for countdown hook
  src/utils/accurateTimer.ts
  src/views/Predictions/hooks/useCountdown.ts
Labels: size/M

#3291 feat: (nft): Show user nfts on collection inside manage nft card on nft detail page
  src/config/localization/translations.json
  src/pages/nfts/profile/[accountAddress].tsx
  src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/ManageNFTsCard.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/index.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/index.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/shared/ManageNFTsCard.tsx
  src/views/Nft/market/Profile/components/EditProfileModal/ChangeProfilePicView.tsx
  src/views/Nft/market/Profile/index.tsx
  src/views/Nft/market/hooks/useNftsForAddress.tsx
  src/views/ProfileCreation/ProfilePicture.tsx
Labels: size/L

#4073 feat: Auto connect & fix connect wallet
  src/hooks/useEagerConnect.bmp.tsx
  src/utils/mpBridge.ts
  src/views/Farms/index.tsx
Labels: size/M

#4077 chore: Bump up swiper
  package.json
  yarn.lock
Labels: size/S

#4074 refactor: Use activeweb3react / web3react to reduce rerenders based on the needs
  src/components/PositionCard/index.tsx
  src/components/RoiCalculatorModal/index.tsx
  src/components/SearchModal/CurrencyList.tsx
  src/hooks/useAccountEventListener.ts
  src/hooks/useAccountLocalEventListener.ts
  src/hooks/useActiveWeb3React.ts
  src/hooks/useApproveCallback.ts
  src/hooks/useAuth.tsx
  src/hooks/useSentryUser.ts
  src/index.tsx
  src/state/swap/hooks.test.ts
  src/state/swap/hooks.ts
  src/views/LimitOrders/index.tsx
  src/views/Pool/index.tsx
  src/views/PoolFinder/index.tsx
  src/views/Swap/index.tsx
Labels: size/M

#4078 refactor: Use memoized function for full decimal multiplier
  src/state/farms/fetchFarms.ts
  src/state/farmsV1/fetchFarms.ts
  src/utils/formatBalance.ts
  src/utils/getFullDecimalMultiplier.ts
  src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
  src/views/Pools/components/LockedPool/Common/BalanceField.tsx
  src/views/Pools/components/LockedPool/hooks/useAvgLockDuration.tsx
  src/views/Pools/hooks/useStakePool.ts
Labels: size/M

#4081 fix: Hide lp rewards apr when not tracked
  src/components/PositionCard/index.tsx
  src/state/swap/hooks.ts
  src/views/AddLiquidity/index.tsx
  src/views/RemoveLiquidity/index.tsx
Labels: size/M

#4080 perf: Memoize custom metadata to reduce calculation
  src/components/Layout/Page.tsx
  src/config/constants/meta.ts
Labels: size/L

#4084 chore: useAppDispatch when it is possible
  src/components/App/Transactions/TransactionsModal.tsx
  src/components/Menu/UserMenu/WalletTransactions.tsx
  src/components/SearchModal/ImportList.tsx
  src/components/SearchModal/ManageLists.tsx
  src/hooks/useFetchListCallback.ts
  src/state/burn/hooks.ts
  src/state/info/hooks.ts
  src/state/limitOrders/hooks.ts
  src/state/lists/updater.ts
  src/state/mint/hooks.ts
  src/state/multicall/hooks.ts
  src/state/multicall/updater.tsx
  src/state/swap/hooks.ts
  src/state/transactions/hooks.tsx
  src/state/transactions/updater.tsx
  src/state/user/hooks/index.tsx
  src/views/AddLiquidity/index.tsx
Labels: size/L

#4086 perf: Memoize footer links
  src/components/Menu/index.tsx
Labels: size/XS

#4090 refactor: (pools): Remove redundant sort order
  src/__tests__/state/pools/helpers.test.ts
  src/config/constants/pools.tsx
  src/config/constants/types.ts
  src/views/Migration/hook/V1/Pool/useFetchUserPools.ts
Labels: size/L

#4092 feat(farm): Intercept link click in mp
  src/utils/mpBridge.ts
  src/views/Farms/index.tsx
Labels: size/M

#4093 feat(farm-mp): Add Navbar
  public/images/nav-title-dark.png
  public/images/nav-title-light.png
  src/components/Navbar.bmp.tsx
  src/pages/_mp/farms/history.tsx
  src/pages/_mp/farms/index.tsx
  src/utils/mpBridge.ts
  src/views/Farms/MpPageLayout.tsx
  src/views/Farms/index.tsx
Labels: size/L

#4094 feat: list ANTEX pool
  src/config/constants/pools.tsx
  src/config/constants/priceHelperLps.ts
Labels: size/S

#4097 chore: (pools): Remove antex sort order
  src/config/constants/pools.tsx
Labels: size/XS

#4105 perf: (info): Consolidate Info page chart hover logic and improve performance
  src/views/Info/Overview/index.tsx
  src/views/Info/components/InfoCharts/HoverableChart.tsx
Labels: size/L

#4095 chore: Add metis to finished pools
  src/config/constants/pools.tsx
Labels: size/S

#3925 feat: (liquidity): Dollar value of LP in liquidity page
  src/components/PositionCard/index.tsx
Labels: size/L

#4099 perf: (userdetail): Inline jsx functions to not create on each render
  src/views/Home/components/UserBanner/UserDetail.tsx
Labels: size/M

#4096 refactor: (pools): Remove unused state hooks
  src/state/pools/hooks.ts
Labels: size/S

#4100 perf: (pools): Use memoize in getPoolBlockInfo
  src/views/Pools/helpers.tsx
Labels: size/S

#4111 feat: Always show navbar
  src/pages/_app.tsx
  src/utils/mpBridge.ts
  src/views/Farms/MpPageLayout.tsx
Labels: size/M

#4113 feat: Set ANKR to finishedPools
  src/config/constants/pools.tsx
Labels: size/S, automerge

#4102 perf: Use jsbi constants and reduce initial bundle size
  src/__tests__/utils/index.test.ts
  src/__tests__/utils/prices.test.ts
  src/components/Menu/GlobalSettings/SettingsModal.tsx
  src/components/PositionCard/index.tsx
  src/components/SearchModal/CommonBases.tsx
  src/config/constants/exchange.ts
  src/config/constants/index.ts
  src/config/constants/types.ts
  src/hooks/Trades.ts
  src/hooks/limitOrders/useGasOverhead.ts
  src/hooks/limitOrders/useGelatoLimitOrdersLib.ts
  src/hooks/useApproveCallback.ts
  src/hooks/useSwapCallArguments.ts
  src/state/limitOrders/hooks.ts
  src/state/mint/hooks.ts
  src/state/swap/hooks.test.ts
  src/state/swap/hooks.ts
  src/state/swap/useSwapActionHandlers.ts
  src/state/user/reducer.test.ts
  src/utils/exchange.ts
  src/utils/index.ts
  src/utils/maxAmountSpend.ts
  src/utils/prices.ts
  src/utils/trades.ts
  src/views/AddLiquidity/PoolPriceBar.tsx
  src/views/AddLiquidity/index.tsx
  src/views/LimitOrders/index.tsx
  src/views/PoolFinder/index.tsx
  src/views/RemoveLiquidity/index.tsx
  src/views/Swap/components/AdvancedSwapDetails.tsx
  src/views/Swap/components/FormattedPriceImpact.tsx
  src/views/Swap/components/SwapModalFooter.tsx
  src/views/Swap/components/SwapModalHeader.tsx
  src/views/Swap/components/confirmPriceImpactWithoutFee.ts
  src/views/Swap/index.tsx
Labels: size/XL

#4114 feat: List Farm Auction 24 whitelist
  src/config/constants/farmAuctions.ts
Labels: size/S, automerge

#4119 chore: Update Meta Apes link
  src/config/constants/farmAuctions.ts
Labels: size/XS

#4115 feat(farm): Add error handle
  src/utils/mpBridge.ts
Labels: size/S

#4120 perf: (tokensearch): Take out trim search query logic out of for loop
  src/components/SearchModal/CurrencySearch.tsx
Labels: size/XS

#4117 refactor: Memoize isAddress
  src/utils/index.ts
Labels: size/XS

#4116 refactor: Inline local variable
  src/utils/index.ts
Labels: size/XS

#4118 fix: Alignment of connect wallet modal in wide mobile screens
  packages/uikit/src/widgets/WalletModal/ConnectModal.tsx
Labels: size/XS

#4098 refactor: (pools): Remove redundant harvest property
  src/__tests__/state/pools/helpers.test.ts
  src/config/constants/pools.tsx
  src/config/constants/types.ts
  src/views/Migration/hook/V1/Pool/useFetchUserPools.ts
  src/views/Pools/components/PoolCard/CardActions/index.tsx
Labels: size/L

#4124 feat(farm): Support farm history
  src/utils/mpBridge.ts
  src/views/Farms/components/FarmTabButtons/index.tsx
Labels: size/S

#4126 fix(voting): More chunks
  src/state/voting/helpers.ts
Labels: size/XS

#4130 perf: Use memo in bnb balances hook to not serialize on each render
  src/state/wallet/hooks.ts
Labels: size/XS

#4129 refactor: Remove redundant multiply
  src/__tests__/utils/compoundApyHelpers.test.ts
Labels: size/XS

#4128 refactor: Remove unused imports
  src/state/voting/helpers.ts
  src/views/Pools/components/LockedPool/Modals/AddAmountModal.tsx
  src/views/Pools/components/LockedPool/hooks/useLockedPool.tsx
  src/views/Voting/helpers.ts
Labels: size/XS

#4127 refactor: Remove redundant local variables
  src/config/constants/rugPullTokens.ts
  src/config/constants/tokens.ts
  src/views/Farms/Farms.tsx
  src/views/Migration/components/MigrationStep1/OldFarm/index.tsx
  src/views/Migration/components/MigrationStep2/NewFarm/index.tsx
Labels: size/S

#4125 fix: Treasury and buyback fee constants
  src/config/constants/info.ts
Labels: size/XS

#4133 fix: Menu language
  src/components/Menu/hooks/useMenuItems.ts
Labels: size/XS, automerge

#4132 perf: Modal input css
  src/components/Modal/ModalInput.tsx
Labels: size/S, automerge

#4135 fix: Refresh translation function on first load when other language selected
  src/components/Menu/hooks/useMenuItems.ts
  src/contexts/Localization/Provider.tsx
Labels: size/S

#4136 fix: Leftover items from previous language in mobile menu navigation
  packages/uikit/src/components/BottomNav/BottomNav.tsx
Labels: size/XS

#4137 chore: Warning free
  src/config/constants/swapWarningTokens.ts
  src/config/constants/warningTokens.ts
  src/config/localization/translations.json
  src/views/Swap/components/SwapWarningModal/FREEWarning.tsx
  src/views/Swap/components/SwapWarningModal/index.tsx
Labels: size/M

#4122 feat: List farm auction 24 winner
  public/images/tokens/0x1D3437E570e93581Bd94b2fd8Fbf202d4a65654A.png
  src/config/constants/farms.ts
  src/config/constants/tokens.ts
Labels: size/M

#4134 feat: Update mpBridge
  src/utils/mpBridge.ts
Labels: size/M

#4148 fix: coin switcher frame issue
  packages/uikit/src/components/CoinSwitcher/SequencePlayer.tsx
Labels: size/XS

#4145 perf: Memoize toggle view
  src/components/ToggleView/ToggleView.tsx
  src/views/Farms/Farms.tsx
  src/views/Nft/market/Collections/index.tsx
  src/views/Pools/components/PoolTabButtons.tsx
Labels: size/M

#4143 perf: Use key instead of translated text for include variable check
  src/contexts/Localization/Provider.tsx
Labels: size/XS

#4061 feat: Flexible side pool
  src/config/abi/cakeFlexibleSideVaultV2.json
  src/config/constants/contracts.ts
  src/config/constants/pools.tsx
  src/config/localization/translations.json
  src/hooks/useContract.ts
  src/state/pools/fetchVaultPublic.ts
  src/state/pools/fetchVaultUser.ts
  src/state/pools/helpers.ts
  src/state/pools/hooks.ts
  src/state/pools/index.ts
  src/state/pools/selectors.ts
  src/state/types.ts
  src/utils/addressHelpers.ts
  src/utils/contractHelpers.ts
  src/views/Home/hooks/useGetTopPoolsByApr.tsx
  src/views/Migration/components/MigrationStep1/OldPool/Cells/NameCell.tsx
  src/views/Migration/components/MigrationStep1/OldPool/Cells/StakedCell.tsx
  src/views/Migration/components/MigrationStep1/OldPool/Cells/TotalStakedCell.tsx
  src/views/Migration/components/MigrationStep1/OldPool/PoolRow.tsx
  src/views/Migration/components/MigrationStep1/OldPool/UnstakeButton.tsx
  src/views/Migration/components/MigrationStep2/NewPool/PoolRow.tsx
  src/views/Migration/components/MigrationStep2/NewPool/index.tsx
  src/views/Pools/components/AutoEarningsBreakdown.tsx
  src/views/Pools/components/CakeVaultCard/RecentCakeProfitRow.tsx
  src/views/Pools/components/CakeVaultCard/StakingApy.tsx
  src/views/Pools/components/CakeVaultCard/VaultCardActions/HasSharesActions.tsx
  src/views/Pools/components/CakeVaultCard/VaultCardActions/VaultApprovalAction.tsx
  src/views/Pools/components/CakeVaultCard/VaultCardActions/VaultStakeActions.tsx
  src/views/Pools/components/CakeVaultCard/VaultCardActions/index.tsx
  src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
  src/views/Pools/components/CakeVaultCard/index.tsx
  src/views/Pools/components/LockedPool/Buttons/ConvertToFlexibleButton.tsx
  src/views/Pools/components/LockedPool/hooks/useLockedPool.tsx
  src/views/Pools/components/PoolStatsInfo.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/AutoHarvest.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/CakeVaultApr.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
  src/views/Pools/components/PoolsTable/Cells/AutoAprCell.tsx
  src/views/Pools/components/PoolsTable/Cells/AutoEarningsCell.tsx
  src/views/Pools/components/PoolsTable/Cells/ExpandActionCell.tsx
  src/views/Pools/components/PoolsTable/Cells/NameCell.tsx
  src/views/Pools/components/PoolsTable/Cells/StakedCell.tsx
  src/views/Pools/components/PoolsTable/PoolRow.tsx
  src/views/Pools/components/Stat.tsx
  src/views/Pools/components/Vault/VaultRoiCalculatorModal.tsx
  src/views/Pools/components/Vault/VaultStakeButtonGroup.tsx
  src/views/Pools/helpers.tsx
  src/views/Pools/hooks/useApprove.tsx
  src/views/Pools/index.tsx
Labels: size/XXL

#4156 chore: Update emission number
  src/views/Home/components/CakeDataRow.tsx
Labels: size/XS

#4158 chore: Update crowdin pr message
  crowdin.yml
Labels: size/XS

#4159 Revert "feat: Flexible side pool"
  src/config/abi/cakeFlexibleSideVaultV2.json
  src/config/constants/contracts.ts
  src/config/constants/pools.tsx
  src/config/localization/translations.json
  src/hooks/useContract.ts
  src/state/pools/fetchVaultPublic.ts
  src/state/pools/fetchVaultUser.ts
  src/state/pools/helpers.ts
  src/state/pools/hooks.ts
  src/state/pools/index.ts
  src/state/pools/selectors.ts
  src/state/types.ts
  src/utils/addressHelpers.ts
  src/utils/contractHelpers.ts
  src/views/Home/hooks/useGetTopPoolsByApr.tsx
  src/views/Migration/components/MigrationStep1/OldPool/Cells/NameCell.tsx
  src/views/Migration/components/MigrationStep1/OldPool/Cells/StakedCell.tsx
  src/views/Migration/components/MigrationStep1/OldPool/Cells/TotalStakedCell.tsx
  src/views/Migration/components/MigrationStep1/OldPool/PoolRow.tsx
  src/views/Migration/components/MigrationStep1/OldPool/UnstakeButton.tsx
  src/views/Migration/components/MigrationStep2/NewPool/PoolRow.tsx
  src/views/Migration/components/MigrationStep2/NewPool/index.tsx
  src/views/Pools/components/AutoEarningsBreakdown.tsx
  src/views/Pools/components/CakeVaultCard/RecentCakeProfitRow.tsx
  src/views/Pools/components/CakeVaultCard/StakingApy.tsx
  src/views/Pools/components/CakeVaultCard/VaultCardActions/HasSharesActions.tsx
  src/views/Pools/components/CakeVaultCard/VaultCardActions/VaultApprovalAction.tsx
  src/views/Pools/components/CakeVaultCard/VaultCardActions/VaultStakeActions.tsx
  src/views/Pools/components/CakeVaultCard/VaultCardActions/index.tsx
  src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
  src/views/Pools/components/CakeVaultCard/index.tsx
  src/views/Pools/components/LockedPool/Buttons/ConvertToFlexibleButton.tsx
  src/views/Pools/components/LockedPool/hooks/useLockedPool.tsx
  src/views/Pools/components/PoolStatsInfo.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/AutoHarvest.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/CakeVaultApr.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
  src/views/Pools/components/PoolsTable/Cells/AutoAprCell.tsx
  src/views/Pools/components/PoolsTable/Cells/AutoEarningsCell.tsx
  src/views/Pools/components/PoolsTable/Cells/ExpandActionCell.tsx
  src/views/Pools/components/PoolsTable/Cells/NameCell.tsx
  src/views/Pools/components/PoolsTable/Cells/StakedCell.tsx
  src/views/Pools/components/PoolsTable/PoolRow.tsx
  src/views/Pools/components/Stat.tsx
  src/views/Pools/components/Vault/VaultRoiCalculatorModal.tsx
  src/views/Pools/components/Vault/VaultStakeButtonGroup.tsx
  src/views/Pools/helpers.tsx
  src/views/Pools/hooks/useApprove.tsx
  src/views/Pools/index.tsx
Labels: size/XXL

#4161 chore: Update swap tooltips wording
  src/views/Swap/components/AdvancedSwapDetails.tsx
  src/views/Swap/components/SwapModalFooter.tsx
Labels: size/S, automerge

#4162 fix: Sonar security warning
  src/views/TradingCompetition/components/BattleCta/index.tsx
Labels: size/XS

#4165 chore: zap token error message
  src/config/localization/translations.json
  src/views/AddLiquidity/components/ZapErrorMessage.tsx
  src/views/AddLiquidity/index.tsx
  src/views/RemoveLiquidity/index.tsx
Labels: size/M

#4160 feat: Flexible side pool
  src/config/abi/cakeFlexibleSideVaultV2.json
  src/config/constants/contracts.ts
  src/config/constants/pools.tsx
  src/config/localization/translations.json
  src/hooks/useContract.ts
  src/state/pools/fetchVaultPublic.ts
  src/state/pools/fetchVaultUser.ts
  src/state/pools/helpers.ts
  src/state/pools/hooks.ts
  src/state/pools/index.ts
  src/state/pools/selectors.ts
  src/state/types.ts
  src/utils/addressHelpers.ts
  src/utils/contractHelpers.ts
  src/views/Home/hooks/useGetTopPoolsByApr.tsx
  src/views/Migration/components/MigrationStep1/OldPool/Cells/NameCell.tsx
  src/views/Migration/components/MigrationStep1/OldPool/Cells/StakedCell.tsx
  src/views/Migration/components/MigrationStep1/OldPool/Cells/TotalStakedCell.tsx
  src/views/Migration/components/MigrationStep1/OldPool/PoolRow.tsx
  src/views/Migration/components/MigrationStep1/OldPool/UnstakeButton.tsx
  src/views/Migration/components/MigrationStep2/NewPool/PoolRow.tsx
  src/views/Migration/components/MigrationStep2/NewPool/index.tsx
  src/views/Pools/components/AutoEarningsBreakdown.tsx
  src/views/Pools/components/CakeVaultCard/RecentCakeProfitRow.tsx
  src/views/Pools/components/CakeVaultCard/StakingApy.tsx
  src/views/Pools/components/CakeVaultCard/VaultCardActions/HasSharesActions.tsx
  src/views/Pools/components/CakeVaultCard/VaultCardActions/VaultApprovalAction.tsx
  src/views/Pools/components/CakeVaultCard/VaultCardActions/VaultStakeActions.tsx
  src/views/Pools/components/CakeVaultCard/VaultCardActions/index.tsx
  src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
  src/views/Pools/components/CakeVaultCard/index.tsx
  src/views/Pools/components/LockedPool/Buttons/ConvertToFlexibleButton.tsx
  src/views/Pools/components/LockedPool/hooks/useLockedPool.tsx
  src/views/Pools/components/PoolStatsInfo.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/AutoHarvest.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/CakeVaultApr.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
  src/views/Pools/components/PoolsTable/Cells/AutoAprCell.tsx
  src/views/Pools/components/PoolsTable/Cells/AutoEarningsCell.tsx
  src/views/Pools/components/PoolsTable/Cells/ExpandActionCell.tsx
  src/views/Pools/components/PoolsTable/Cells/NameCell.tsx
  src/views/Pools/components/PoolsTable/Cells/StakedCell.tsx
  src/views/Pools/components/PoolsTable/PoolRow.tsx
  src/views/Pools/components/Stat.tsx
  src/views/Pools/components/Vault/VaultRoiCalculatorModal.tsx
  src/views/Pools/components/Vault/VaultStakeButtonGroup.tsx
  src/views/Pools/helpers.tsx
  src/views/Pools/hooks/useApprove.tsx
  src/views/Pools/index.tsx
Labels: size/XXL

#4171 perf: Reduce calculations in import lp pool finder
  src/hooks/usePairs.ts
Labels: size/XS

#4172 feat: Remove PANCAKE_TOP100 in DEFAULT_LIST_OF_LISTS
  src/config/constants/lists.ts
Labels: size/XS, automerge

#4150 fix: Prediction height in mobile
  packages/uikit/src/components/CoinSwitcher/CoinSwitcher.tsx
  src/views/Predictions/Mobile.tsx
  src/views/Predictions/components/Container.tsx
  src/views/Predictions/components/Label.tsx
Labels: size/M
