Repository pancakeswap/pancake-frontend, pull requests merged in 2022-12, with the labels that each got.

#5472 fix: (smartrouter): Stable swap cannot fallback to v2 when insufficient liquidity balance
  apps/web/src/views/Swap/SmartSwap/hooks/useDerivedSwapInfoWithStableSwap.ts
  apps/web/src/views/Swap/SmartSwap/hooks/useTradeInfo.ts
  apps/web/src/views/Swap/SmartSwap/index.tsx
Labels: size/M

#5480 perf: Fix multicall v3 and use possible places to reduce calls
  apps/web/src/state/pools/fetchPoolsUser.ts
  apps/web/src/state/pools/fetchVaultPublic.ts
  apps/web/src/state/pottery/fetchPottery.ts
  apps/web/src/utils/calls/pools.ts
  apps/web/src/utils/multicall.ts
  apps/web/src/views/Home/components/CakeDataRow.tsx
  packages/multicall/index.ts
Labels: size/L

#5479 perf: Return busd price of busd directly in busd price hook
  apps/web/src/hooks/useBUSDPrice.ts
Labels: size/XS

#5478 chore: Variable naming in transaction warning hook
  apps/web/src/hooks/Trades.ts
Labels: size/XS

#5445 fix: getBetHistory query syntax error
  apps/web/src/state/predictions/helpers.ts
Labels: size/XS

#5484 chore: Hide aBNBc farm
  apps/web/src/views/Farms/Farms.tsx
  packages/farms/constants/56.ts
Labels: size/S

#5487 chore: Hide HAY-BUSD
  apps/web/src/views/Farms/Farms.tsx
  packages/farms/constants/56.ts
Labels: size/S

#5486 chore: Ignore aBNBc in token test case
  apps/web/src/config/__tests__/tokens.test.ts
  packages/farms/constants/56.ts
Labels: size/S

#5490 chore: Update warning wording for abnbc
  apps/web/src/views/Swap/components/SwapWarningModal/ABNBWarning.tsx
  packages/localization/src/config/translations.json
Labels: size/XS, automerge

#5491 feat(farm): List HOOK
  apps/web/public/images/tokens/0xa260E12d2B924cb899AE80BB58123ac3fEE1E2F0.png
  apps/web/public/images/tokens/0xa260E12d2B924cb899AE80BB58123ac3fEE1E2F0.svg
  packages/farms/constants/56.ts
  packages/tokens/src/56.ts
Labels: size/L

#5492 chore: Set release version
  .changeset/cool-grapes-train.md
  .changeset/neat-adults-brush.md
  packages/smart-router/CHANGELOG.md
  packages/smart-router/package.json
  packages/token-lists/CHANGELOG.md
  packages/token-lists/package.json
Labels: size/S, automerge

#5493 fix: updateLPsAPR package deps issue
  package.json
Labels: size/XS

#5470 fix: (trading-competition): Fix potential prize grid nan/0 shown
  apps/web/src/views/TradingCompetition/easter/components/PrizesInfo/PrizesGrid/EasterPrizesGrid.tsx
  apps/web/src/views/TradingCompetition/easter/components/YourScore/EasterUserPrizeGrid.tsx
  apps/web/src/views/TradingCompetition/helpers.ts
Labels: size/S

#5502 fix: (pottery): Banner apy shows nan when first load
  apps/web/src/views/Pottery/components/Banner/index.tsx
Labels: size/S

#5501 fix: (pottery): Pottery lock date in deposit card
  apps/web/src/state/pottery/hook.ts
  apps/web/src/state/pottery/selectors.ts
  apps/web/src/views/Pottery/components/Pot/Deposit/index.tsx
Labels: size/S

#5505 perf: (multicall): Return outdated listening key immediately when no data
  apps/web/src/state/multicall/updater.tsx
Labels: size/XS

#5506 fix: info token price chart issue
  apps/web/src/state/info/queries/tokens/priceData.ts
Labels: size/S

#5507 feat(farm/pool): List HFT
  apps/web/public/images/tokens/0x44Ec807ce2F4a6F2737A92e985f318d035883e47.png
  apps/web/public/images/tokens/0x44Ec807ce2F4a6F2737A92e985f318d035883e47.svg
  apps/web/src/config/constants/pools.tsx
  packages/farms/constants/56.ts
  packages/tokens/src/56.ts
Labels: size/M

#5499 chore: Update fixed term wordings
  apps/web/src/views/Home/components/FarmsPoolsRow/TopFarmPool.tsx
  apps/web/src/views/Home/components/FarmsPoolsRow/index.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/StakingApy.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/index.tsx
  apps/web/src/views/Pools/components/LockedPool/Common/LockedAprTooltipContent.tsx
  apps/web/src/views/Pools/components/LockedPool/Common/Overview/index.tsx
  apps/web/src/views/Pools/components/LockedPool/LockedStakingApy.tsx
  apps/web/src/views/Pools/components/PoolCard/CardFooter/index.tsx
  apps/web/src/views/Pools/components/PoolTypeTag.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/CakeVaultApr.tsx
  apps/web/src/views/Pools/components/PoolsTable/Cells/AutoAprCell.tsx
  apps/web/src/views/Pools/components/Vault/VaultRoiCalculatorModal.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/components/RoiCalculatorModal/RoiCalculatorFooter.tsx
  packages/uikit/src/components/RoiCalculatorModal/RoiCalculatorModal.tsx
  packages/uikit/src/widgets/Farm/components/Tags/index.tsx
  packages/uikit/src/widgets/Pool/AprRowWithToolTip.tsx
Labels: Delayed Release, size/L

#5509 chore(footer): Remove Online Store
  apps/aptos/components/Menu/footerConfig.ts
  apps/web/src/components/Menu/config/footerConfig.ts
  packages/localization/src/config/translations.json
Labels: size/S, automerge

#5471 feat: (stableswap): Add currency select to stable swap
  apps/web/src/components/CurrencyInputPanel/index.tsx
  apps/web/src/components/SearchModal/CurrencySearch.tsx
  apps/web/src/components/SearchModal/CurrencySearchModal.tsx
  apps/web/src/views/Swap/StableSwap/components/StableSwapForm.tsx
  apps/web/src/views/Swap/StableSwap/index.tsx
  packages/localization/src/config/translations.json
Labels: Delayed Release, size/L

#5510 fix: (pools): Pools tag auto/locked shown for manual pools when account not connected
  apps/web/src/views/Pools/components/PoolTypeTag.tsx
Labels: size/XS

#5513 fix(BoosterFarms): "FARMING" not shown
  apps/web/src/views/Farms/components/FarmTable/Farm.tsx
Labels: size/XS

#5514 chore: Add nft subgraph warning
  apps/web/src/pages/nfts/activity.tsx
  apps/web/src/pages/nfts/collections/[collectionAddress].tsx
  apps/web/src/pages/nfts/collections/[collectionAddress]/[tokenId].tsx
  apps/web/src/pages/nfts/collections/index.tsx
  apps/web/src/pages/nfts/index.tsx
  apps/web/src/views/Nft/market/NftSubgraphWarning.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#5508 chore: Bump up next.js
  apps/aptos/components/NetworkSwitcher.tsx
  apps/aptos/package.json
  apps/bridge/components/Menu.tsx
  apps/bridge/package.json
  apps/bridge/pages/index.tsx
  apps/web/package.json
  apps/web/src/components/Logo/ChainLogo.tsx
  apps/web/src/components/NetworkModal/PageNetworkSupportModal.tsx
  apps/web/src/components/NetworkModal/UnsupportedNetworkModal.tsx
  apps/web/src/components/NetworkModal/WrongNetworkModal.tsx
  apps/web/src/components/NetworkSwitcher.tsx
  apps/web/src/testUtils.tsx
  apps/web/src/views/Farms/components/BCakeBoosterCard.tsx
  apps/web/src/views/Home/components/Banners/AptosBanner.tsx
  apps/web/src/views/Home/components/Banners/CompetitionBanner.tsx
  apps/web/src/views/Home/components/Banners/IFOBanner.tsx
  apps/web/src/views/Home/components/Banners/LotteryBanner.tsx
  apps/web/src/views/Home/components/Banners/PerpetualBanner.tsx
  apps/web/src/views/Home/components/Hero.tsx
  apps/web/src/views/Nft/market/components/BannerHeader/index.tsx
  apps/web/src/views/Nft/market/components/CollectibleCard/CollectionCard.tsx
  apps/web/src/views/Pottery/components/PrizeFunds.tsx
  apps/web/src/views/TradingCompetition/Footer.tsx
  apps/web/src/views/TradingCompetition/MoDCompetition.tsx
  apps/web/src/views/TradingCompetition/components/ClaimModal/index.tsx
  apps/web/src/views/TradingCompetition/components/FinishedCompetitionBanner/index.tsx
  apps/web/src/views/TradingCompetition/components/PrizesInfo/PrizesGrid/PrizesGrid.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TeamRanks.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TeamRanksWithParticipants.tsx
  apps/web/src/views/TradingCompetition/easter/components/BattleBanner/EasterBattleBanner.tsx
  apps/web/src/views/TradingCompetition/easter/components/PrizesInfo/EasterPrizesText.tsx
  apps/web/src/views/TradingCompetition/fantoken/components/BattleBanner/FanTokenBattleBanner.tsx
  apps/web/src/views/TradingCompetition/fantoken/components/PrizesInfo/FanTokenPrizesText.tsx
  apps/web/src/views/TradingCompetition/mobox/components/BattleBanner/MoboxBattleBanner.tsx
  apps/web/src/views/TradingCompetition/mobox/components/PrizesInfo/MoboxPrizesText.tsx
  apps/web/src/views/TradingCompetition/mod/components/BattleBanner/ModBattleBanner.tsx
  apps/web/src/views/TradingCompetition/mod/components/PrizesInfo/ModPrizesText.tsx
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/components/DropdownMenu/styles.tsx
  packages/uikit/src/widgets/Menu/components/Logo.tsx
  packages/uikit/src/widgets/Pool/PoolTabButtons.tsx
  yarn.lock
Labels: size/XL

#5516 fix(farm): Pair info url
  apps/web/src/views/Farms/components/FarmCard/FarmCard.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
Labels: size/XS, automerge

#5511 fix: Strengthen the round limit of getRoundIdsArray
  apps/web/src/state/lottery/helpers.ts
Labels: size/XS

#5515 chore: Change "pool" to "pair" in the text description of liquidity
  apps/aptos/components/Liquidity/components/AddLiquidityButton.tsx
  apps/aptos/components/Liquidity/components/ConfirmAddLiquidityModal.tsx
  apps/aptos/components/Liquidity/components/PoolPriceBar.tsx
  apps/aptos/components/Liquidity/components/PositionCard.tsx
  apps/aptos/components/Liquidity/components/PricePoolShareSection.tsx
  apps/aptos/components/Liquidity/components/common.tsx
  apps/aptos/pages/add/[[...currency]].tsx
  apps/web/src/components/PositionCard/index.tsx
  apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
  apps/web/src/views/AddLiquidity/ChoosePair.tsx
  apps/web/src/views/AddLiquidity/PoolPriceBar.tsx
  apps/web/src/views/AddLiquidity/components/ConfirmAddLiquidityModal.tsx
  apps/web/src/views/AddLiquidity/components/common.tsx
  apps/web/src/views/AddLiquidity/index.tsx
  apps/web/src/views/Info/Tokens/TokenPage.tsx
  apps/web/src/views/Migration/components/Farm/ActionPanel/Liquidity.tsx
  apps/web/src/views/Migration/components/Farm/Cells/Liquidity.tsx
  apps/web/src/views/Pool/index.tsx
  apps/web/src/views/PoolFinder/index.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/widgets/Farm/components/FarmTable/Liquidity.tsx
  packages/uikit/src/widgets/Liquidity/AddLiquidity/FirstLP.tsx
  packages/uikit/src/widgets/Liquidity/FindOtherLP.tsx
Labels: size/L

#5522 chore: Remove padding from farms tab buttons
  packages/uikit/src/widgets/Farm/components/FarmTabButtons.tsx
Labels: size/XS

#5525 fix(aptos-pool): Update format
  apps/aptos/components/Pools/components/PoolTable/PoolRow.tsx
  packages/uikit/src/widgets/Pool/Cells/EarningCell.tsx
  packages/uikit/src/widgets/Pool/Cells/TotalStakedCell.tsx
Labels: size/M

#5532 chore: info support all stableSwap pairs
  apps/web/src/state/info/queries/pools/topPools.ts
Labels: size/XS

#5495 fix: updateLPsAPR part2
  .github/workflows/updateLPsAPR.yml
  apps/web/src/utils/graphql.ts
  package.json
Labels: size/S

#5533 feat: smart router updates
  apps/web/src/components/Menu/GlobalSettings/SettingsModal.tsx
  apps/web/src/state/user/smartRouter.ts
  apps/web/src/views/Swap/SmartSwap/index.tsx
  apps/web/src/views/Swap/index.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#5523 fix: Disable account change event listener for blocto in-app browser
  apps/web/src/hooks/useAccountEventListener.ts
  apps/web/src/state/farms/index.ts
  apps/web/src/views/Farms/components/FarmTable/Row.tsx
  apps/web/src/views/Farms/hooks/useBCakeProxyContractAddress.ts
  apps/web/src/views/Farms/hooks/useFarmCProxyAddress.ts
Labels: size/S

#5388 chore(Aptos): Update Aptos Farm APR
  apps/aptos/config/constants/farms/1.ts
  apps/aptos/config/constants/lpAprs/1.json
  apps/aptos/config/constants/tokens/1.ts
  scripts/updateAptosLpsAPR/farmsOneWeekAgo.json
  scripts/updateAptosLpsAPR/index.ts
Labels: size/L

#5404 feat(pool): Check approval again
  apps/web/src/hooks/useCakeApprovalStatus.ts
  apps/web/src/views/Farms/components/FarmCard/StakeAction.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/VaultCardActions/index.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
  apps/web/src/views/Pools/components/Modals/StakeModal.tsx
  apps/web/src/views/Pools/components/PoolCard/CardActions/index.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/widgets/Farm/components/DepositModal/index.tsx
  packages/uikit/src/widgets/Modal/ModalInput.tsx
  packages/uikit/src/widgets/Pool/StakeModal.tsx
Labels: size/L, automerge

#5539 chore: Remove nft warning
  apps/web/src/pages/nfts/activity.tsx
  apps/web/src/pages/nfts/collections/[collectionAddress].tsx
  apps/web/src/pages/nfts/collections/[collectionAddress]/[tokenId].tsx
  apps/web/src/pages/nfts/collections/index.tsx
  apps/web/src/pages/nfts/index.tsx
Labels: size/S

#5477 feat: token highlight list
  apps/web/src/config/constants/lists.ts
  apps/web/src/hooks/useSwapHotTokenDisplay.ts
  apps/web/src/state/info/hooks.ts
  apps/web/src/state/info/queries/tokens/tokenData.ts
  apps/web/src/state/info/queries/tokens/topTokens.ts
  apps/web/src/utils/getTokenLogoURL.ts
  apps/web/src/views/Info/components/InfoTables/shared.tsx
  apps/web/src/views/Swap/components/CurrencyInputHeader.tsx
  apps/web/src/views/Swap/components/HotTokenList/SwapTokenTable.tsx
  apps/web/src/views/Swap/components/HotTokenList/index.tsx
  apps/web/src/views/Swap/index.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/components/Box/Box.tsx
  packages/uikit/src/components/Box/index.tsx
  packages/uikit/src/components/Svg/Icons/Hot.tsx
  packages/uikit/src/components/Svg/Icons/HotDisable.tsx
  packages/uikit/src/components/Svg/Icons/SortArrowIcon.tsx
  packages/uikit/src/components/Svg/index.tsx
Labels: size/XL

#5548 chore(translations): Remove redundant word
  packages/localization/src/config/translations.json
Labels: size/XS

#5545 fix: (liquidity): Lp apr for busd-bnb pair when adding liquidity
  apps/web/src/state/swap/useLPApr.ts
Labels: size/XS

#5544 chore: Bump up jotai
  apps/web/package.json
  packages/token-lists/package.json
  yarn.lock
Labels: size/S

#5543 chore: Bump up react count up
  apps/web/package.json
  yarn.lock
Labels: size/M

#5542 perf: (pools): Use keyby instead of frompairs to not create intermediate array
  apps/web/src/state/pools/index.ts
Labels: size/S

#5541 perf: (farms): Use keyby instead of frompairs to not create intermediate array
  apps/web/src/state/farms/index.ts
Labels: size/XS

#5538 chore: Bump up redux
  apps/web/package.json
  packages/token-lists/package.json
  yarn.lock
Labels: size/M

#5528 fix: Avoid hybrid error
  packages/uikit/src/components/NextLink/NextLink.tsx
Labels: size/XS

#5540 chore: add github action for updateAptosLPsAPR
  .github/workflows/updateAptosLPsAPR.yml
Labels: size/M

#5549 chore: Aptos APR github action adjustment
  .github/workflows/updateAptosLPsAPR.yml
Labels: size/XS

#5558 feat(aptos): Add whitelist token
  apps/aptos/config/constants/tokenLists/pancake-default.tokenlist.json
Labels: size/S, automerge

#5560 feat(Aptos): List wormhole USDC
  apps/aptos/config/constants/tokenLists/pancake-default.tokenlist.json
Labels: size/XS, automerge

#5552 fix(NoticeAlert): Click "I understand" to trigger the checkbox
  apps/web/src/views/Swap/components/SwapWarningModal/Acknowledgement.tsx
Labels: size/S

#5555 fix: (tooltip): Tap to tooltip causes other elements to react
  packages/uikit/src/hooks/useTooltip/useTooltip.tsx
Labels: size/XS

#5563 feat(Aptos): List CAKE token
  apps/aptos/config/coins.ts
  apps/aptos/config/constants/tokenLists/pancake-default.tokenlist.json
  apps/aptos/config/constants/tokens/1.ts
  apps/aptos/pages/add/[[...currency]].tsx
  apps/aptos/state/swap.ts
Labels: size/S, automerge

#5559 feat(IFO): List Squad IFO
  apps/web/public/images/achievements/ifo-squad.svg
  apps/web/public/images/ifos/squad-bg.png
  apps/web/public/images/tokens/0x724A32dFFF9769A0a0e1F0515c0012d1fB14c3bd.png
  apps/web/src/config/constants/campaigns.ts
  apps/web/src/config/constants/ifo.ts
  packages/tokens/src/56.ts
Labels: size/M, automerge

#5412 feat(bridge): Aptos bridge
  apps/bridge/components/Menu.tsx
  apps/bridge/components/layerZero/AptosBridgeFooter.tsx
  apps/bridge/components/layerZero/AptosBridgeMessage.tsx
  apps/bridge/components/layerZero/LayerZeroWidget.tsx
  apps/bridge/components/layerZero/PoweredBy.tsx
  apps/bridge/components/layerZero/config.ts
  apps/bridge/components/layerZero/theme.ts
  apps/bridge/components/stargate/theme.ts
  apps/bridge/pages/aptos.tsx
  apps/bridge/public/layerZero.svg
Labels: size/L, automerge

#5565 style: Fix css
  apps/bridge/components/layerZero/AptosBridgeMessage.tsx
  apps/bridge/components/layerZero/PoweredBy.tsx
  apps/bridge/pages/aptos.tsx
Labels: automerge

#5566 chore(Aptos): Revert back default token usdc
  apps/aptos/pages/add/[[...currency]].tsx
  apps/aptos/state/swap.ts
Labels: size/XS, automerge

#5557 chore: Remove HAY warning
  apps/web/src/config/constants/swapWarningTokens.ts
  apps/web/src/views/Swap/components/SwapWarningModal/HayWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/index.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#5572 fix: (ifo): Squad ifo voting article url
  apps/web/src/config/constants/ifo.ts
Labels: size/XS, automerge

#5570 fix: (table): Border overflow in action panel in farm/pools table
  apps/aptos/components/Farms/components/FarmTable/FarmTable.tsx
  apps/web/src/views/Farms/components/FarmTable/FarmTable.tsx
  packages/uikit/src/widgets/Pool/PoolsTable/index.tsx
Labels: size/S

#5571 style(bridge): Fix css
  apps/bridge/pages/aptos.tsx
Labels: size/S, automerge

#5370 chore: New Crowdin updates
  apps/web/public/locales/ar-SA.json
  apps/web/public/locales/bn-BD.json
  apps/web/public/locales/de-DE.json
  apps/web/public/locales/el-GR.json
  apps/web/public/locales/en-US.json
  apps/web/public/locales/es-ES.json
  apps/web/public/locales/fi-FI.json
  apps/web/public/locales/fil-PH.json
  apps/web/public/locales/fr-FR.json
  apps/web/public/locales/hi-IN.json
  apps/web/public/locales/hu-HU.json
  apps/web/public/locales/id-ID.json
  apps/web/public/locales/it-IT.json
  apps/web/public/locales/ja-JP.json
  apps/web/public/locales/ko-KR.json
  apps/web/public/locales/nl-NL.json
  apps/web/public/locales/pl-PL.json
  apps/web/public/locales/pt-BR.json
  apps/web/public/locales/pt-PT.json
  apps/web/public/locales/ro-RO.json
  apps/web/public/locales/ru-RU.json
  apps/web/public/locales/sv-SE.json
  apps/web/public/locales/ta-IN.json
  apps/web/public/locales/tr-TR.json
  apps/web/public/locales/uk-UA.json
  apps/web/public/locales/vi-VN.json
  apps/web/public/locales/zh-CN.json
  apps/web/public/locales/zh-TW.json
Labels: size/XXL

#5575 chore(web): Switch to prod worker endpoint
  apis/farms/src/lpApr.ts
  apps/web/src/config/constants/endpoints.ts
Labels: size/XS

#5576 feat: Rename Aptos token symbol
  apps/aptos/config/coins.ts
  apps/aptos/config/constants/farms/1.ts
  apps/aptos/config/constants/tokenLists/pancake-default.tokenlist.json
  apps/aptos/config/constants/tokens/1.ts
Labels: size/M, automerge

#5547 feat(Farms): Add farm types filter
  apps/web/src/views/Farms/Farms.tsx
  apps/web/src/views/Farms/components/FarmTypesFilter.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/widgets/Farm/components/FarmTabButtons.tsx
Labels: size/L, automerge

#5582 chore: (pools): Move krs to finished pools
  apps/web/src/config/constants/pools.tsx
Labels: size/S, automerge

#5580 fix: http
  apps/web/src/views/Nft/market/NftSubgraphWarning.tsx
Labels: size/XS

#5584 chore(aptos-pool): Update format
  packages/uikit/src/widgets/Pool/Cells/TotalStakedCell.tsx
Labels: size/XS

#5583 fix: (pools): Balance rounding when choosing max results insufficient balance error
  packages/uikit/src/widgets/Pool/StakeModal.tsx
  packages/utils/removeTrailingZeros.test.ts
  packages/utils/removeTrailingZeros.ts
Labels: size/M

#5578 chore: Adjustment aptos token name
  apps/aptos/config/constants/tokenLists/pancake-default.tokenlist.json
Labels: size/XS, automerge

#5577 fix(Farms): Farm types filter error
  apps/web/src/views/Farms/Farms.tsx
Labels: size/S

#5586 chore(aptos): Remove TW ios only
  apps/aptos/config/wallets.ts
Labels: size/XS

#5554 refactor: Remove legacy next image
  apps/web/src/components/NetworkModal/UnsupportedNetworkModal.tsx
  apps/web/src/views/Farms/components/BCakeBoosterCard.tsx
  apps/web/src/views/Home/components/Banners/AptosBanner.tsx
  apps/web/src/views/Home/components/Banners/CompetitionBanner.tsx
  apps/web/src/views/Home/components/Banners/IFOBanner.tsx
  apps/web/src/views/Home/components/Banners/LotteryBanner.tsx
  apps/web/src/views/Home/components/Banners/PerpetualBanner.tsx
  apps/web/src/views/Home/components/Hero.tsx
  apps/web/src/views/Nft/market/components/BannerHeader/index.tsx
  apps/web/src/views/Nft/market/components/CollectibleCard/CollectionCard.tsx
  apps/web/src/views/Pottery/components/PrizeFunds.tsx
  apps/web/src/views/TradingCompetition/Footer.tsx
  apps/web/src/views/TradingCompetition/MoDCompetition.tsx
  apps/web/src/views/TradingCompetition/components/ClaimModal/index.tsx
  apps/web/src/views/TradingCompetition/components/FinishedCompetitionBanner/index.tsx
  apps/web/src/views/TradingCompetition/components/PrizesInfo/PrizesGrid/PrizesGrid.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TeamRanks.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TeamRanksWithParticipants.tsx
  apps/web/src/views/TradingCompetition/easter/components/BattleBanner/EasterBattleBanner.tsx
  apps/web/src/views/TradingCompetition/easter/components/PrizesInfo/EasterPrizesText.tsx
  apps/web/src/views/TradingCompetition/fantoken/components/BattleBanner/FanTokenBattleBanner.tsx
  apps/web/src/views/TradingCompetition/fantoken/components/PrizesInfo/FanTokenPrizesText.tsx
  apps/web/src/views/TradingCompetition/mobox/components/BattleBanner/MoboxBattleBanner.tsx
  apps/web/src/views/TradingCompetition/mobox/components/PrizesInfo/MoboxPrizesText.tsx
  apps/web/src/views/TradingCompetition/mod/components/BattleBanner/ModBattleBanner.tsx
  apps/web/src/views/TradingCompetition/mod/components/PrizesInfo/ModPrizesText.tsx
Labels: size/M

#5592 fix: (ifo): Trigger wallet data fetch when account change
  apps/web/src/state/pools/hooks.ts
Labels: size/XS

#5595 fix(aptos-swap-sdk): Aptos coin sort before compare
  .changeset/few-ads-melt.md
  packages/aptos-swap-sdk/src/aptosCoin.ts
Labels: size/S

#5589 fix: (pools): Render warning in stake modal
  packages/uikit/src/widgets/Pool/StakeModal.tsx
Labels: size/XS

#5581 feat: Merge common hook and utils
  apps/aptos/components/Farms/components/Farms.tsx
  apps/aptos/components/SearchModal/ImportList.tsx
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
  apps/aptos/views/Ifos/components/IfoFoldableCard/Timer.tsx
  apps/bridge/components/Menu.tsx
  apps/bridge/components/getTimePeriods.ts
  apps/web/src/hooks/useIntersectionObserver.ts
  apps/web/src/hooks/useTheme.ts
  apps/web/src/utils/formatTimePeriod.ts
  apps/web/src/utils/getTimePeriods.ts
  apps/web/src/views/FarmAuction/components/AuctionCakeBurn.tsx
  apps/web/src/views/FarmAuction/components/AuctionTimer.tsx
  apps/web/src/views/Farms/Farms.tsx
  apps/web/src/views/Home/components/Banners/LotteryBanner.tsx
  apps/web/src/views/Home/components/CakeDataRow.tsx
  apps/web/src/views/Home/components/FarmsPoolsRow/index.tsx
  apps/web/src/views/Home/components/WinSection/LotteryCardContent.tsx
  apps/web/src/views/Home/components/WinSection/PredictionCardContent.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/Timer.tsx
  apps/web/src/views/Lottery/components/Countdown/index.tsx
  apps/web/src/views/Nft/market/components/NFTMedia.tsx
  apps/web/src/views/PancakeSquad/utils.ts
  apps/web/src/views/Pools/components/CakeVaultCard/WithdrawalFeeTimer.tsx
  apps/web/src/views/Pools/components/LockedPool/Common/BurningCountDown.tsx
  apps/web/src/views/Pottery/components/Pot/Deposit/index.tsx
  apps/web/src/views/Pottery/components/Timer.tsx
  apps/web/src/views/Predictions/helpers.ts
  apps/web/src/views/TradingCompetition/components/Countdown/index.tsx
  packages/hooks/src/index.ts
  packages/hooks/src/useTheme.ts
  packages/utils/getTimePeriods.test.ts
  packages/utils/getTimePeriods.ts
Labels: size/L

#5597 fix(Farm): Stableswap info url
  apps/web/src/state/farms/selectors.ts
  apps/web/src/views/Farms/components/FarmCard/FarmCard.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  packages/farms/src/types.ts
Labels: size/M

#5588 feat: Add stable swap output estimation with & without fee
  .changeset/dull-forks-film.md
  apps/web/src/hooks/useStableSwapInfo.ts
  apps/web/src/views/AddLiquidity/AddStableLiquidity/hooks/useDerivedLPInfo.ts
  apps/web/src/views/AddLiquidity/AddStableLiquidity/hooks/useStableLPDerivedMintInfo.tsx
  apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
  packages/smart-router/evm/stableSwap/amm.ts
  packages/smart-router/evm/stableSwap/getSwapOutput.ts
  packages/smart-router/evm/stableSwap/index.ts
Labels: size/L

#5593 chore: Remove redundant contract in remove liquidity
  apps/web/src/views/RemoveLiquidity/index.tsx
Labels: size/XS

#5600 fix: Revert "refactor: Remove legacy next image"
  apps/web/src/components/NetworkModal/UnsupportedNetworkModal.tsx
  apps/web/src/views/Farms/components/BCakeBoosterCard.tsx
  apps/web/src/views/Home/components/Banners/AptosBanner.tsx
  apps/web/src/views/Home/components/Banners/CompetitionBanner.tsx
  apps/web/src/views/Home/components/Banners/IFOBanner.tsx
  apps/web/src/views/Home/components/Banners/LotteryBanner.tsx
  apps/web/src/views/Home/components/Banners/PerpetualBanner.tsx
  apps/web/src/views/Home/components/Hero.tsx
  apps/web/src/views/Nft/market/components/BannerHeader/index.tsx
  apps/web/src/views/Nft/market/components/CollectibleCard/CollectionCard.tsx
  apps/web/src/views/Pottery/components/PrizeFunds.tsx
  apps/web/src/views/TradingCompetition/Footer.tsx
  apps/web/src/views/TradingCompetition/MoDCompetition.tsx
  apps/web/src/views/TradingCompetition/components/ClaimModal/index.tsx
  apps/web/src/views/TradingCompetition/components/FinishedCompetitionBanner/index.tsx
  apps/web/src/views/TradingCompetition/components/PrizesInfo/PrizesGrid/PrizesGrid.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TeamRanks.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TeamRanksWithParticipants.tsx
  apps/web/src/views/TradingCompetition/easter/components/BattleBanner/EasterBattleBanner.tsx
  apps/web/src/views/TradingCompetition/easter/components/PrizesInfo/EasterPrizesText.tsx
  apps/web/src/views/TradingCompetition/fantoken/components/BattleBanner/FanTokenBattleBanner.tsx
  apps/web/src/views/TradingCompetition/fantoken/components/PrizesInfo/FanTokenPrizesText.tsx
  apps/web/src/views/TradingCompetition/mobox/components/BattleBanner/MoboxBattleBanner.tsx
  apps/web/src/views/TradingCompetition/mobox/components/PrizesInfo/MoboxPrizesText.tsx
  apps/web/src/views/TradingCompetition/mod/components/BattleBanner/ModBattleBanner.tsx
  apps/web/src/views/TradingCompetition/mod/components/PrizesInfo/ModPrizesText.tsx
Labels: size/M

#5603 fix: Use legacy image only when placeholder blur
  apps/web/src/components/NetworkModal/UnsupportedNetworkModal.tsx
  apps/web/src/views/Nft/market/components/BannerHeader/index.tsx
  apps/web/src/views/Nft/market/components/CollectibleCard/CollectionCard.tsx
  apps/web/src/views/Pottery/components/PrizeFunds.tsx
  apps/web/src/views/TradingCompetition/Footer.tsx
  apps/web/src/views/TradingCompetition/MoDCompetition.tsx
  apps/web/src/views/TradingCompetition/components/ClaimModal/index.tsx
  apps/web/src/views/TradingCompetition/components/FinishedCompetitionBanner/index.tsx
  apps/web/src/views/TradingCompetition/components/PrizesInfo/PrizesGrid/PrizesGrid.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TeamRanks.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TeamRanksWithParticipants.tsx
  apps/web/src/views/TradingCompetition/easter/components/BattleBanner/EasterBattleBanner.tsx
  apps/web/src/views/TradingCompetition/easter/components/PrizesInfo/EasterPrizesText.tsx
  apps/web/src/views/TradingCompetition/fantoken/components/BattleBanner/FanTokenBattleBanner.tsx
  apps/web/src/views/TradingCompetition/fantoken/components/PrizesInfo/FanTokenPrizesText.tsx
  apps/web/src/views/TradingCompetition/mobox/components/BattleBanner/MoboxBattleBanner.tsx
  apps/web/src/views/TradingCompetition/mobox/components/PrizesInfo/MoboxPrizesText.tsx
  apps/web/src/views/TradingCompetition/mod/components/BattleBanner/ModBattleBanner.tsx
  apps/web/src/views/TradingCompetition/mod/components/PrizesInfo/ModPrizesText.tsx
Labels: size/M

#5590 refactor: (pools): Remove unused pool types
  apps/web/src/views/Pools/components/LockedPool/types/index.ts
  apps/web/src/views/Pools/components/types/index.ts
Labels: size/L

#5567 feat: (ifo): Calculate distribution ratio via onchain data
  apps/web/src/config/constants/ifo.ts
  apps/web/src/config/constants/types.ts
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardTokens.tsx
  apps/web/src/views/Ifos/hooks/v3/useGetPublicIfoData.ts
  apps/web/src/views/Ifos/types.ts
Labels: size/M

#5594 chore: Bump up swr
  apps/web/package.json
  apps/web/src/hooks/useSWRContract.ts
  apps/web/src/state/block/hooks.ts
  apps/web/src/state/multicall/hooks.ts
  apps/web/src/views/Nft/market/Collections/index.tsx
  apps/web/src/views/Nft/market/hooks/useNftsForAddress.tsx
  apps/web/src/views/Predictions/components/ChainlinkChart.tsx
  apps/web/src/views/Swap/SmartSwap/hooks/useBestTrade.ts
  apps/web/src/views/Swap/StableSwap/hooks/useStableTradeExactIn.ts
  packages/wagmi/package.json
  yarn.lock
Labels: size/M

#5606 chore: update Aptos github action setting
  .github/workflows/updateAptosLPsAPR.yml
Labels: size/XS

#5591 chore: List SQUAD
  apps/web/src/config/constants/pools.tsx
  packages/farms/constants/56.ts
Labels: size/S, automerge

#5604 feat: Support perpetuals eth link
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/utils/getPerpetualUrl.ts
  apps/web/src/views/Home/components/Banners/PerpetualBanner.tsx
Labels: size/M, automerge

#5587 feat(PercentButtons): "MAX" not disappear and button highlight when clicked
  apps/web/src/components/CurrencyInputPanel/index.tsx
  apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
  apps/web/src/views/AddLiquidity/index.tsx
  apps/web/src/views/LimitOrders/index.tsx
  apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/index.tsx
  apps/web/src/views/Swap/SmartSwap/index.tsx
  apps/web/src/views/Swap/StableSwap/components/StableSwapForm.tsx
  apps/web/src/views/Swap/components/SwapForm.tsx
Labels: size/L

#5608 chore: remove info warning
  apps/web/src/views/Info/Overview/index.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#5609 feat: Socials add youtube link
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/components/Footer/config.tsx
  packages/uikit/src/components/Svg/Icons/YoutubeIcon.tsx
  packages/uikit/src/components/Svg/index.tsx
Labels: size/M, automerge

#5611 chore(OpenNewIcon): Use invertedContrast color
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/GetTokenModal.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/GetTokenModal.tsx
  apps/web/src/views/Predictions/components/History/PnlTab/PnlTab.tsx
Labels: size/XS

#5615 fix: (pools): Pool profile requirement info not visible
  apps/web/src/state/pools/fetchPools.ts
Labels: size/XS

#5614 chore: Update quadruple hop
  apps/aptos/config/coins.ts
  apps/aptos/config/constants/exchange.ts
  apps/aptos/hooks/Trades.ts
  apps/web/src/state/lists/hooks.ts
  packages/aptos-swap-sdk/src/generated/swap.ts
  packages/aptos-swap-sdk/src/router.ts
Labels: size/L

#5613 style(TokenManage): Change LinkExternalIcon position
  apps/aptos/components/SearchModal/ManageTokens.tsx
  apps/web/src/components/SearchModal/ManageTokens.tsx
Labels: size/S

#5568 feat: Aptos Farms
  apps/aptos/components/Farms/components/FarmCard/CardActionsContainer.tsx
  apps/aptos/components/Farms/components/FarmCard/FarmCard.tsx
  apps/aptos/components/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/aptos/components/Farms/components/FarmTable/FarmTable.tsx
  apps/aptos/components/Farms/components/Farms.tsx
  apps/aptos/components/Menu/Menu.tsx
  apps/aptos/config/constants/contracts/masterchef.ts
  apps/aptos/config/constants/farms/1.ts
  apps/aptos/config/constants/index.ts
  apps/aptos/config/constants/priceHelperLps/farms/1.ts
  apps/aptos/config/constants/tokens/1.ts
  apps/aptos/next.config.mjs
  apps/aptos/pages/_app.tsx
  apps/aptos/public/images/tokens/0x159df6b7689437016108a019fd5bef736bac692b6d4a1f10c941f6fbb9a74ca6::oft::CakeOFT.png
  apps/aptos/public/images/tokens/0x1::aptos_coin::AptosCoin.png
  apps/aptos/public/images/tokens/0x5e156f1207d0ebfa19a9eeff00d62a282278fb8719f4fab3a586a0a2c0fffbea::coin::T.png
  apps/aptos/public/images/tokens/0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::BnbCoin.png
  apps/aptos/public/images/tokens/0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::UsdcCoin.png
  apps/aptos/public/images/tokens/0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::UsdtCoin.png
  apps/aptos/public/images/tokens/0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::WethCoin.png
  apps/aptos/public/images/tokens/0xcc8a89c8dce9693d354449f1f73e60e14e347417854f029db5bc8e7454008abb::coin::T.png
  apps/aptos/public/images/tokens/0xccc9620d38c4f3991fa68a03ad98ef3735f18d04717cb75d7a1300dd8a7eed75::coin::T.png
  apps/aptos/public/images/tokens/0xd11107bdf0d6d7040c6c0bfbdecb6545191fdf13e8d8d259952f53e1713f61b5::staked_coin::StakedAptos.png
  apps/aptos/public/images/tokens/0xf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa::asset::USDC.png
  apps/aptos/public/images/tokens/0xf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa::asset::USDT.png
  apps/aptos/public/images/tokens/0xf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa::asset::WETH.png
  apps/aptos/state/farms/hook.ts
  apps/aptos/state/farms/utils/pendingCake.ts
  apps/aptos/style/Global.tsx
  apps/aptos/utils/farmApr.ts
  packages/uikit/src/components/RoiCalculatorModal/RoiCalculatorFooter.tsx
  packages/uikit/src/widgets/Farm/components/FarmTable/Actions/StakeComponent.tsx
  packages/uikit/src/widgets/Farm/components/FarmTable/Actions/StakedActionComponent.tsx
Labels: size/L

#5624 fix: (farms): Aptos farm prices
  packages/farms/src/farmPrices.ts
Labels: size/S, automerge

#5626 revert: "chore: Bump up swr"
  apps/web/package.json
  apps/web/src/hooks/useSWRContract.ts
  apps/web/src/state/block/hooks.ts
  apps/web/src/state/multicall/hooks.ts
  apps/web/src/views/Nft/market/Collections/index.tsx
  apps/web/src/views/Nft/market/hooks/useNftsForAddress.tsx
  apps/web/src/views/Predictions/components/ChainlinkChart.tsx
  apps/web/src/views/Swap/SmartSwap/hooks/useBestTrade.ts
  apps/web/src/views/Swap/StableSwap/hooks/useStableTradeExactIn.ts
  packages/wagmi/package.json
  yarn.lock
Labels: size/M

#5625 chore: Close HFT pool
  apps/web/src/config/constants/pools.tsx
Labels: size/S, automerge

#5628 revert: "fix: (farms): Aptos farm prices (#5624)"
  packages/farms/src/farmPrices.ts
Labels: size/S, automerge

#5630 fix: (aptos): Aptos farm prices for apt cake lp
  apps/aptos/state/farms/hook.ts
Labels: size/XS

#5640 chore: Remove unused parameter
  apps/aptos/state/transactions/reducer.ts
Labels: size/XS

#5639 perf: (usermenu): Don't define components during render
  apps/aptos/components/Menu/UserMenu.tsx
  apps/aptos/components/Menu/WalletModal.tsx
  apps/web/src/components/Menu/UserMenu/WalletModal.tsx
  apps/web/src/components/Menu/UserMenu/index.tsx
Labels: size/L

#5645 fix(stable-swap): Support many stable swap farms
  apis/farms/src/lpApr.ts
  scripts/updateLPsAPR.ts
Labels: size/S

#5562 chore: Bump wagmi
  apis/farms/src/lpApr.ts
  apps/aptos/next.config.mjs
  apps/bridge/components/Menu.tsx
  apps/bridge/components/stargate/config.ts
  apps/bridge/components/stargate/network.ts
  apps/bridge/next.config.mjs
  apps/bridge/package.json
  apps/bridge/tsconfig.json
  apps/web/.env.example
  apps/web/jest.config.js
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/src/components/Menu/UserMenu/WalletInfo.tsx
  apps/web/src/components/Menu/UserMenu/WalletModal.tsx
  apps/web/src/components/Menu/UserMenu/WalletUserMenuItem.tsx
  apps/web/src/config/constants/exchange.ts
  apps/web/src/hooks/useBucket.ts
  apps/web/src/hooks/useMasterchef.ts
  apps/web/src/state/lists/hooks.ts
  apps/web/src/utils/index.ts
  apps/web/src/utils/safeConnector.ts
  apps/web/src/utils/wagmi.ts
  apps/web/src/utils/wallet.ts
  apps/web/src/views/Info/components/InfoNav/index.tsx
  apps/web/src/views/Pools/components/PoolStatsInfo.tsx
  apps/web/src/views/Swap/SmartSwap/utils/exchange.ts
  packages/smart-router/evm/constants/exchange.ts
  packages/smart-router/evm/constants/stableSwap/pools.ts
  packages/swap-sdk-core/test/token.test.ts
  packages/swap-sdk/src/constants.ts
  packages/swap-sdk/src/index.ts
  packages/tokens/src/common.ts
  packages/tokens/src/helpers.ts
  packages/wagmi/chains/chains.ts
  packages/wagmi/chains/index.ts
  packages/wagmi/chains/package.json
  packages/wagmi/connectors/binanceWallet/binanceWallet.ts
  packages/wagmi/connectors/blocto/blocto.ts
  packages/wagmi/global.d.ts
  packages/wagmi/package.json
  packages/wagmi/tsconfig.json
  packages/wagmi/tsup.config.ts
  yarn.lock
Labels: size/XXL

#5650 feat(farm/pool): List ZBC
  apps/web/public/images/tokens/0x37a56cdcD83Dce2868f721De58cB3830C44C6303.png
  apps/web/public/images/tokens/0x37a56cdcD83Dce2868f721De58cB3830C44C6303.svg
  apps/web/src/config/constants/pools.tsx
  packages/farms/constants/56.ts
  packages/tokens/src/56.ts
Labels: size/M

#5652 fix(web/prediction): Chainlink chart crash with swr compare loop
  apps/web/src/views/Predictions/components/ChainlinkChart.tsx
Labels: size/XS

#5654 chore: Move wmx to finished pools
  apps/web/src/config/constants/pools.tsx
Labels: size/S, automerge

#5646 chore: Update getImageUrlFromToken url
  apps/aptos/components/TokenImage/index.tsx
  apps/aptos/public/images/tokens/0x159df6b7689437016108a019fd5bef736bac692b6d4a1f10c941f6fbb9a74ca6::oft::CakeOFT.png
  apps/aptos/public/images/tokens/0x1::aptos_coin::AptosCoin.png
  apps/aptos/public/images/tokens/0x5e156f1207d0ebfa19a9eeff00d62a282278fb8719f4fab3a586a0a2c0fffbea::coin::T.png
  apps/aptos/public/images/tokens/0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::BnbCoin.png
  apps/aptos/public/images/tokens/0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::UsdcCoin.png
  apps/aptos/public/images/tokens/0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::UsdtCoin.png
  apps/aptos/public/images/tokens/0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::WethCoin.png
  apps/aptos/public/images/tokens/0xcc8a89c8dce9693d354449f1f73e60e14e347417854f029db5bc8e7454008abb::coin::T.png
  apps/aptos/public/images/tokens/0xccc9620d38c4f3991fa68a03ad98ef3735f18d04717cb75d7a1300dd8a7eed75::coin::T.png
  apps/aptos/public/images/tokens/0xd11107bdf0d6d7040c6c0bfbdecb6545191fdf13e8d8d259952f53e1713f61b5::staked_coin::StakedAptos.png
  apps/aptos/public/images/tokens/0xf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa::asset::USDC.png
  apps/aptos/public/images/tokens/0xf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa::asset::USDT.png
  apps/aptos/public/images/tokens/0xf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa::asset::WETH.png
Labels: size/XS, automerge

#5618 chore(aptos-pool): Update minor format
  apps/aptos/components/Pools/index.tsx
  apps/aptos/components/Pools/transformers/transformPool.ts
  apps/aptos/config/constants/tokens/2.ts
  apps/aptos/next.config.mjs
  apps/web/src/views/Pools/components/PoolCard/AprRow.tsx
  packages/uikit/src/widgets/Pool/AprRowWithToolTip.tsx
  packages/utils/removeTrailingZeros.test.ts
  packages/utils/removeTrailingZeros.ts
Labels: size/M

#5657 feat: (voting): Add soon tag to voting menu
  apps/web/src/components/Menu/hooks/useMenuItemsStatus.ts
  apps/web/src/components/Menu/hooks/useVotingStatus.ts
Labels: size/S

#5656 fix: (info): Info page shows wrong info when access stableswap page with different chain name
  apps/web/src/views/Info/index.tsx
Labels: size/S

#5648 chore: New Spinner UI
  apps/web/public/images/pancake-3d-spinner.gif
  packages/uikit/src/__tests__/components/spinner.test.tsx
  packages/uikit/src/components/Spinner/PanIcon.tsx
  packages/uikit/src/components/Spinner/PancakeIcon.tsx
  packages/uikit/src/components/Spinner/Spinner.tsx
Labels: size/L, automerge

#5655 feat: Lock-end notifications for CAKE Pool
  apps/web/src/components/Menu/hooks/useMenuItems.ts
  apps/web/src/components/Menu/hooks/useMenuItemsStatus.ts
  apps/web/src/hooks/useLockedEndNotification.tsx
  apps/web/src/pages/_app.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#5659 perf(Aptos): Default token set to CAKE
  apps/aptos/pages/add/[[...currency]].tsx
  apps/aptos/state/swap.ts
Labels: size/XS, automerge

#5638 style(RemoveLiquidity): Adjust the arrangement of Buttons on mobile
  apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/index.tsx
Labels: size/XS

#5633 fix: (info): Breadcrumbs redirects to swap info pages when in stableswap
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/Info/Tokens/TokenPage.tsx
Labels: size/S

#5649 chore: All buttons linked to BscScan use BscScanIcon
  apps/web/src/components/Menu/UserMenu/TransactionRow.tsx
  apps/web/src/components/Menu/UserMenu/WalletInfo.tsx
  apps/web/src/components/SearchModal/ImportToken.tsx
  apps/web/src/components/Toast/DescriptionWithTx.tsx
  apps/web/src/components/TransactionConfirmationModal/index.tsx
  apps/web/src/components/TransactionDetailModal/FarmTransactionModal/FarmDetail.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/Info/components/InfoTables/TransactionsTable.tsx
  apps/web/src/views/LimitOrders/components/LimitOrderTable/DetailLimitOrderModal.tsx
  apps/web/src/views/Nft/market/components/Activity/ActivityRow.tsx
  apps/web/src/views/Nft/market/components/Activity/MobileModal.tsx
  apps/web/src/views/Nft/market/components/BuySellModals/SellModal/EditStage.tsx
  apps/web/src/views/Nft/market/components/BuySellModals/SellModal/SellStage.tsx
  apps/web/src/views/Nft/market/components/BuySellModals/shared/TransactionConfirmed.tsx
  apps/web/src/views/Nft/market/components/ProfileNftModal.tsx
  apps/web/src/views/PancakeSquad/components/Modals/Confirm/index.tsx
  apps/web/src/views/Pools/components/PoolStatsInfo.tsx
  apps/web/src/views/Pottery/components/FinishedRounds/AllHistoryCard/PreviousRoundCardBody.tsx
  apps/web/src/views/Predictions/components/History/BetResult.tsx
  apps/web/src/views/Predictions/components/History/PnlTab/PnlTab.tsx
  apps/web/src/views/Swap/components/AddressInputPanel.tsx
  apps/web/src/views/TradingCompetition/components/Countdown/Timer.tsx
  apps/web/src/views/Voting/Proposal/Details.tsx
  apps/web/src/views/Voting/components/Proposal/VoteRow.tsx
  packages/uikit/src/components/Link/LinkExternal.tsx
  packages/uikit/src/components/Link/types.ts
  packages/uikit/src/widgets/Farm/components/FarmCard/DetailsSection.tsx
Labels: size/L

#5485 feat(aptos-pool): Enable Syrup Pool
  apps/aptos/components/Menu/Menu.tsx
  apps/aptos/components/Pools/components/PoolCard/StakeModalContainer.tsx
  apps/aptos/components/Pools/components/PoolTable/ActionPanel.tsx
  apps/aptos/components/Pools/hooks/usePoolsList.ts
  apps/aptos/components/Pools/index.tsx
  apps/aptos/components/Pools/utils/isVaultPool.tsx
  apps/aptos/contracts/generated/smartchef.ts
  apps/aptos/next.config.mjs
  packages/uikit/src/widgets/Pool/StakeModal.tsx
Labels: size/M

#5663 fix: Spinner
  packages/uikit/src/__tests__/components/spinner.test.tsx
  packages/uikit/src/__tests__/widgets/modal.test.tsx
  packages/uikit/src/components/Spinner/Spinner.tsx
  packages/uikit/src/widgets/Farm/components/DepositModal/index.tsx
  packages/uikit/src/widgets/Farm/components/FarmTable/Details.tsx
  packages/uikit/src/widgets/Pool/Cells/ExpandActionCell.tsx
  packages/uikit/src/widgets/Pool/StakeModal.tsx
  packages/uikit/src/widgets/Pool/withCardActions.tsx
Labels: size/M, automerge

#5636 feat(Farms): Stake & untake LP percent button highlight
  packages/uikit/src/widgets/Farm/components/DepositModal/index.tsx
  packages/uikit/src/widgets/Farm/components/WithdrawModal/index.tsx
  packages/uikit/src/widgets/Modal/ModalInput.tsx
Labels: size/M

#5661 fix: stable lp apr 7days
  apps/web/src/config/constants/lpAprs/1.json
  apps/web/src/config/constants/lpAprs/56.json
  scripts/updateLPsAPR.ts
Labels: size/L

#5653 chore: Add eth coin list
  apps/web/src/components/SearchModal/ManageLists.tsx
  apps/web/src/config/constants/lists.ts
  apps/web/src/state/lists/hooks.ts
Labels: size/M

#5665 chore: Add Mojito warning
  apps/aptos/components/SwapWarningModal/MojoWarning.tsx
  apps/aptos/components/SwapWarningModal/config.ts
  apps/aptos/components/SwapWarningModal/index.tsx
  apps/aptos/pages/swap.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/components/Acknowledgement/index.tsx
  packages/uikit/src/components/index.ts
Labels: size/L

#5667 chore: Add Pool Stat Info
  apps/aptos/components/Pools/components/PoolCard/PoolStatsInfo.tsx
  apps/aptos/components/Pools/transformers/transformPool.ts
  apps/aptos/components/Pools/types.ts
  apps/aptos/config/constants/tokens/1.ts
  packages/localization/src/config/translations.json
Labels: size/M

#5670 chore: Update timestamp
  apps/aptos/components/Pools/components/PoolCard/PoolStatsInfo.tsx
  apps/aptos/components/Pools/transformers/transformPool.ts
Labels: size/XS

#5662 feat: (pools): Add allowance approve button to lock modals
  apps/web/src/components/ApproveConfirmButtons.tsx
  apps/web/src/views/Pools/components/LockedPool/Common/BalanceField.tsx
  apps/web/src/views/Pools/components/LockedPool/Common/ExtendEnable.tsx
  apps/web/src/views/Pools/components/LockedPool/Common/LockedModalBody.tsx
  apps/web/src/views/Pools/components/LockedPool/Modals/AddAmountModal.tsx
  apps/web/src/views/Pools/components/LockedPool/Modals/LockedStakeModal.tsx
Labels: size/L

#5664 fix(BscScanIcon): Fix color and missing
  apps/web/src/components/App/Transactions/Transaction.tsx
  apps/web/src/components/SearchModal/ImportToken.tsx
  apps/web/src/components/Toast/DescriptionWithTx.tsx
  apps/web/src/components/TransactionConfirmationModal/index.tsx
  apps/web/src/views/LimitOrders/components/LimitOrderTable/DetailLimitOrderModal.tsx
  apps/web/src/views/Swap/components/AddressInputPanel.tsx
  apps/web/src/views/TradingCompetition/components/Countdown/Timer.tsx
Labels: size/S

#5637 feat(StableLP): Add/Remove LP add percentButton
  apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
Labels: size/S

#5612 style(TokenManage): SearchBox is not truncated
  apps/aptos/components/SearchModal/Manage.tsx
  apps/web/src/components/SearchModal/Manage.tsx
Labels: size/XS

#5672 feat(Aptos): Buy Cake link
  apps/aptos/components/Menu/Menu.tsx
  apps/web/src/components/Menu/index.tsx
  packages/uikit/src/__tests__/widgets/menu.test.tsx
  packages/uikit/src/components/Footer/Footer.tsx
  packages/uikit/src/components/Footer/types.ts
  packages/uikit/src/widgets/Menu/Menu.tsx
  packages/uikit/src/widgets/Menu/types.ts
Labels: size/S, automerge

#5660 feat(Aptos): Swap and Liquidity add bridge notice
  apps/aptos/components/CurrencyInputPanel/index.tsx
  apps/aptos/components/Liquidity/components/ChoosePair.tsx
  apps/aptos/components/Liquidity/components/LiquidityBridgeWarning.tsx
  apps/aptos/components/Swap/BridgeButton.tsx
  apps/aptos/components/Swap/hooks/useBridgeInfo.tsx
  apps/aptos/pages/swap.tsx
  packages/localization/src/config/translations.json
  packages/ui/tokens/index.ts
  packages/uikit/src/components/Svg/Icons/BridgeIcon.tsx
  packages/uikit/src/components/Svg/index.tsx
  packages/uikit/src/widgets/Swap/CurrencyInputPanel.tsx
  packages/uikit/src/widgets/Swap/SwapWidget.css.ts
Labels: size/L, automerge

#5673 fix(Liquidity): Url not defined
  apps/web/src/components/SearchModal/CurrencySearch.tsx
  packages/localization/src/config/translations.json
Labels: size/XS, automerge

#5675 revert: "chore: Add eth coin list (#5653)"
  apps/web/src/components/SearchModal/ManageLists.tsx
  apps/web/src/config/constants/lists.ts
  apps/web/src/state/lists/hooks.ts
Labels: size/M

#5676 fix: NetworkSupportModal button style
  apps/web/src/components/NetworkModal/PageNetworkSupportModal.tsx
Labels: size/XS

#5674 feat(web): Add Ledger connector
  apps/web/public/images/wallets/ledger.png
  apps/web/src/config/wallet.ts
  apps/web/src/utils/wagmi.ts
Labels: size/S

#5677 fix: (lockedpool): Check approval based on final amount
  apps/web/src/views/Pools/components/LockedPool/Common/LockedModalBody.tsx
Labels: size/S

#5441 chore(aptos-ifo): Minor update patch
  apps/aptos/components/Card/index.tsx
  apps/aptos/config/constants/ifo.ts
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ClaimButton.tsx
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardTokens.tsx
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoVestingCard/TotalPurchased.tsx
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoVestingCard/index.tsx
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/VestingClaimButton.tsx
  apps/aptos/views/Ifos/components/IfoFoldableCard/index.tsx
  apps/aptos/views/Ifos/components/IfoVesting/NotTokens.tsx
  apps/aptos/views/Ifos/components/IfoVesting/VestingPeriod/Claim.tsx
  apps/aptos/views/Ifos/components/IfoVesting/VestingPeriod/Info.tsx
  apps/aptos/views/Ifos/generated/ifo.ts
  apps/aptos/views/Ifos/hooks/useIfoVesting.ts
  apps/aptos/views/Ifos/hooks/vesting/useFetchUserWalletIfoData.ts
  apps/aptos/views/Ifos/hooks/vesting/useVestingCharacteristics.ts
  apps/aptos/views/Ifos/utils/index.ts
  packages/utils/__tests__/formatBalance.test.ts
  packages/utils/formatBalance.ts
Labels: size/L

#5682 chore: Update whwEth word
  apps/aptos/config/constants/farms/1.ts
  apps/aptos/config/constants/tokens/1.ts
Labels: size/XS

#5680 feat: Bump wagmi version
  apps/bridge/package.json
  apps/web/package.json
  packages/wagmi/package.json
  yarn.lock
Labels: size/M

#5688 chore: Fill in the missing BscScanIcon
  apps/web/src/views/Voting/CreateProposal/index.tsx
  apps/web/src/views/Voting/components/CastVoteModal/DetailsView.tsx
Labels: size/S

#5689 feat: Update chainlinkOracleBNB contract address
  apps/web/src/config/constants/contracts.ts
  apps/web/src/views/Predictions/Desktop.tsx
  apps/web/src/views/Predictions/Mobile.tsx
Labels: size/S, automerge

#5690 fix(Aptos): Lp symbol typo
  apps/aptos/config/constants/farms/1.ts
  apps/aptos/config/constants/tokens/1.ts
Labels: size/XS, automerge

#5666 chore: Update stableSwap APR for info page
  apis/farms/src/lpApr.ts
  apps/web/src/state/info/hooks.ts
  apps/web/src/state/info/queries/pools/poolData.ts
  apps/web/src/views/Info/Pools/PoolPage.tsx
Labels: size/M

#5692 chore: Bidder Address use BscScanIcon
  apps/web/src/views/FarmAuction/components/AuctionLeaderboard/AuctionLeaderboardTable.tsx
Labels: size/XS

#5694 refactor: (swap-sdk): Remove duplicate swap sdk util functions
  .changeset/early-bikes-fix.md
  packages/swap-sdk/src/entities/trade.ts
  packages/swap-sdk/src/index.ts
  packages/swap-sdk/src/utils.ts
  packages/swap-sdk/test/miscellaneous.test.ts
Labels: size/M

#5684 fix: (liquidity): Add liquidity pair distribution
  apps/web/src/views/AddLiquidity/components/ConfirmAddLiquidityModal.tsx
Labels: size/XS

#5699 chore: patch only the recent change
  .changeset/early-bikes-fix.md
Labels: size/XS

#5700 chore: Update Blocto logo
  apps/aptos/public/images/wallets/blocto.png
  apps/web/public/images/wallets/blocto.png
  apps/web/src/config/wallet.ts
Labels: size/XS

#5691 chore: Info chart XAxis from day to month
  apps/web/src/views/Info/components/InfoCharts/BarChart/index.tsx
  apps/web/src/views/Info/components/InfoCharts/LineChart/index.tsx
Labels: size/XS
