Repository pancakeswap/pancake-frontend, pull requests merged in 2022-10, with the labels that each got.

#4878 fix: (menu): Add missing translations in menu item status
  packages/localization/src/config/translations.json
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/components/DropdownMenu/DropdownMenu.tsx
  src/components/Menu/hooks/useMenuItems.ts
  src/components/Menu/hooks/useMenuItemsStatus.ts
Labels: size/M

#4879 fix: (menu): Status live color
  src/components/Menu/hooks/useMenuItems.ts
Labels: size/XS

#4876 fix(FarmBooster): To be able to unset when booster is active and no LP
  src/views/Farms/components/YieldBooster/components/BoostedAction.tsx
  src/views/Farms/components/YieldBooster/hooks/useYieldBoosterState.ts
Labels: size/XS

#4882 chore: Close CO IFO
  public/images/tokens/0x936B6659Ad0C1b244Ba8Efe639092acae30dc8d6.png
  public/images/tokens/0x936B6659Ad0C1b244Ba8Efe639092acae30dc8d6.svg
  src/config/constants/ifo.ts
Labels: size/XS, automerge

#4890 chore: Update NetworkSwitcher placement
  packages/uikit/src/widgets/Menu/components/UserMenu/index.tsx
  packages/uikit/src/widgets/Menu/components/UserMenu/types.ts
  src/components/NetworkSwitcher.tsx
Labels: size/XS

#4896 fix: (activity): Wrong type of value set to width prop when device width is not a isMd
  src/views/Nft/market/ActivityHistory/ActivityHistory.tsx
Labels: size/XS

#4888 perf(stableswap): better interaction when typing value
  packages/uikit/src/__tests__/widgets/modal.test.tsx
  packages/uikit/src/__tests__/widgets/walletModal.test.tsx
  packages/uikit/src/widgets/Modal/styles.tsx
  src/views/Swap/StableSwap/hooks/useStableTradeExactIn.ts
Labels: size/S

#4894 fix: (swap): Swap url contains with native token of other chains won't work
  src/state/swap/hooks.test.ts
  src/state/swap/hooks.ts
Labels: size/S

#4891 chore: (pools): Remove peel, shell and high from live pools list
  src/config/constants/pools.tsx
Labels: size/S

#4898 chore(farm): Add ARV Pool
  packages/farms/constants/56.ts
  src/config/constants/pools.tsx
Labels: size/S

#4904 chore: Change showBNB prop name to showNative
  src/components/SearchModal/CurrencyList.tsx
  src/components/SearchModal/CurrencySearch.tsx
Labels: size/S

#4902 fix: (swap): Query params from previous network causes to tokens to not get loaded
  src/config/constants/exchange.ts
  src/hooks/useActiveWeb3React.ts
  src/state/lists/updater.ts
Labels: size/S

#4809 feat(IFO): Show CAKE spent info and tooltip
  packages/localization/src/config/translations.json
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardTokens.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoVestingCard/TotalAvailableClaim.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoVestingCard/TotalPurchased.tsx
Labels: size/L

#4899 chore: multichain info adjustment
  src/state/info/queries/pools/poolData.ts
  src/state/info/queries/pools/topPools.ts
  src/state/info/queries/tokens/tokenData.ts
  src/state/info/queries/tokens/topTokens.ts
Labels: size/S

#4915 refactor: Use activechain hook where chainId is needed
  src/views/Nft/market/components/BuySellModals/BuyModal/index.tsx
  src/views/Pottery/components/Pot/Deposit/DepositAction.tsx
Labels: size/XS

#4914 chore: Remove unused atom in active chain hook
  src/hooks/useActiveChainId.ts
Labels: size/XS

#4913 fix: (anniversary): Anniversary check throws error when wallet network and page network is not the same
  src/components/GlobalCheckClaimStatus/index.tsx
Labels: size/XS

#4908 fix: Network support modal shown in all chains supported pages when wallet network is other than bsc and eth
  src/components/NetworkModal/NetworkModal.tsx
Labels: size/XS

#4907 refactor: (liquidity): Simplify lp7dApr hook
  src/state/swap/hooks.ts
Labels: size/S

#4917 fix: Cannot switch network when accessing page via url with query
  src/components/NetworkModal/PageNetworkSupportModal.tsx
Labels: size/XS

#4893 feat: (pottery): Add next pot lock time countdown to pottery page
  packages/localization/src/config/translations.json
  src/state/pottery/fetchPottery.ts
  src/state/pottery/index.ts
  src/state/types.ts
  src/views/Pottery/components/Banner/index.tsx
  src/views/Pottery/components/Timer.tsx
Labels: size/M

#4892 fix: (pottery): Winner row height in winners component when no profile
  src/views/Pottery/components/FinishedRounds/AllHistoryCard/Winner.tsx
Labels: size/XS

#4887 fix: (nft): Pancake Bunny traits components cannot be shown if page accessed via activity row link
  src/components/SearchModal/CurrencySearch.tsx
  src/components/SearchModal/filtering.ts
  src/state/nftMarket/helpers.ts
  src/views/Nft/market/ActivityHistory/utils/fetchActivityNftMetadata.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/index.tsx
  src/views/Nft/market/Collection/Items/index.tsx
  src/views/Nft/market/Collection/Traits/index.tsx
  src/views/Nft/market/Home/Newest.tsx
  src/views/Nft/market/components/Activity/ActivityRow.tsx
  src/views/Nft/market/components/BuySellModals/SellModal/EditStage.tsx
  src/views/Nft/market/components/BuySellModals/SellModal/SellStage.tsx
  src/views/Nft/market/components/CollectibleCard/CardBody.tsx
  src/views/Nft/market/components/CollectibleCard/CollectibleLinkCard.tsx
  src/views/Nft/market/components/ProfileNftModal.tsx
  src/views/Nft/market/hooks/useAllPancakeBunnyNfts.ts
  src/views/Nft/market/hooks/useGetLowestPrice.ts
Labels: size/M

#4873 feat(Liquidity): Add QuickInputButton
  src/views/AddLiquidity/index.tsx
  src/views/RemoveLiquidity/index.tsx
Labels: size/S

#4874 perf: Farms test
  src/config/__tests__/farms.test.ts
Labels: size/XS

#4723 perf: (token-search): Remove tag info from wrappedtokeninfo
  packages/tokens/src/helpers.ts
  src/components/SearchModal/CurrencySearch.tsx
  src/state/lists/hooks.ts
Labels: size/M

#4636 perf: (info): Eliminate intermediate arrays when getting ids
  src/state/info/queries/search/index.ts
Labels: size/XS

#4920 feat: List KRS IFO
  packages/tokens/src/56.ts
  public/images/achievements/ifo-krs.svg
  public/images/ifos/krs-bg.png
  public/images/tokens/0x37b53894e7429f794B56F22a32E1695567Ee9913.png
  public/images/tokens/0x37b53894e7429f794B56F22a32E1695567Ee9913.svg
  src/config/constants/campaigns.ts
  src/config/constants/ifo.ts
Labels: size/M

#4922 refactor: Run update lp apr only on pcs repo
  .github/workflows/updateLPsAPR.yml
Labels: size/XS

#4925 fix: Native StableLP
  packages/farms/src/farmPrices.ts
Labels: size/XS

#4926 fix: Remove queries only when chainid change
  src/hooks/useActiveWeb3React.ts
Labels: size/S

#4927 perf: Check prev chain id first to not run list check if it is false
  src/hooks/useActiveWeb3React.ts
Labels: size/XS

#4928 fix: Proxy harvest
  src/views/Farms/components/FarmCard/CardActionsContainer.tsx
Labels: size/XS

#4930 feat: Remove user gas fee for bsc
  packages/localization/src/config/translations.json
  src/components/Menu/GlobalSettings/GasSettings.tsx
  src/components/Menu/GlobalSettings/SettingsModal.tsx
  src/hooks/useApproveCallback.ts
  src/hooks/useCakeApprove.tsx
  src/hooks/useCallWithMarketGasPrice.ts
  src/hooks/useSwapCallback.ts
  src/hooks/useWrapCallback.ts
  src/state/user/actions.ts
  src/state/user/hooks/index.tsx
  src/state/user/reducer.ts
  src/utils/calls/farms.ts
  src/views/AddLiquidity/AddStableLiquidity/index.tsx
  src/views/AddLiquidity/index.tsx
  src/views/FarmAuction/components/PlaceBidModal.tsx
  src/views/FarmAuction/components/ReclaimBidCard.tsx
  src/views/Farms/components/YieldBooster/hooks/useBoosterFarmHandlers.ts
  src/views/Farms/components/YieldBooster/hooks/useProxyStakedActions.ts
  src/views/Farms/hooks/useApproveFarm.ts
  src/views/Farms/hooks/useHarvestFarm.ts
  src/views/Farms/hooks/useStakeFarms.ts
  src/views/Farms/hooks/useUnstakeFarms.ts
  src/views/Home/components/UserBanner/HarvestCard.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx
  src/views/Ifos/hooks/useIfoApprove.ts
  src/views/Lottery/components/BuyTicketsModal/BuyTicketsModal.tsx
  src/views/Lottery/components/ClaimPrizesModal/ClaimPrizesInner.tsx
  src/views/Migration/components/MigrationStep1/OldPool/UnstakeButton.tsx
  src/views/Migration/hook/V1/Farms/useUnstakeFarms.ts
  src/views/Migration/hook/V1/Pool/useUnstakePool.ts
  src/views/Nft/market/components/BuySellModals/BuyModal/index.tsx
  src/views/Nft/market/components/BuySellModals/SellModal/index.tsx
  src/views/PancakeSquad/components/Buttons/BuyTickets.tsx
  src/views/PancakeSquad/components/Buttons/Mint.tsx
  src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
  src/views/Pools/components/LockedPool/Buttons/ConvertToFlexibleButton.tsx
  src/views/Pools/components/LockedPool/hooks/useLockedPool.tsx
  src/views/Pools/hooks/useApprove.tsx
  src/views/Pools/hooks/useHarvestPool.ts
  src/views/Pools/hooks/useStakePool.ts
  src/views/Pools/hooks/useUnstakePool.ts
  src/views/Pottery/hooks/useApprovePottery.tsx
  src/views/Predictions/components/CollectRoundWinningsModal.tsx
  src/views/Predictions/components/ReclaimPositionButton.tsx
  src/views/Predictions/components/RoundCard/SetPositionCard.tsx
  src/views/Profile/components/Achievements/AchievementRow/index.tsx
  src/views/Profile/components/EditProfileModal/ChangeProfilePicView.tsx
  src/views/Profile/components/EditProfileModal/PauseProfileView.tsx
  src/views/ProfileCreation/ConfirmProfileCreationModal.tsx
  src/views/ProfileCreation/Mint.tsx
  src/views/ProfileCreation/ProfilePicture.tsx
  src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
  src/views/RemoveLiquidity/index.tsx
  src/views/TradingCompetition/components/ClaimModal/index.tsx
  src/views/TradingCompetition/components/RegisterModal/RegisterWithProfile.tsx
Labels: size/XL

#4919 feat(Pottery): Add WithdrawableDate and remaining period change to 'days'
  packages/localization/src/config/translations.json
  src/utils/timeHelper.ts
  src/views/Pottery/components/Pot/Claim/AvailableWithdraw.tsx
  src/views/Pottery/components/Pot/Claim/CardFooter.tsx
Labels: size/M

#4936 refactor: (workflow): Run stale issues flow only on pcs repo
  .github/workflows/staleIssues.yml
Labels: size/XS

#4938 fix: (ifo): View info link in token vesting doesn't point to the ifo component
  src/views/Ifos/components/IfoVesting/VestingPeriod/Expand.tsx
Labels: size/XS

#4941 chore: info search adjustment
  src/state/info/hooks.ts
  src/state/info/queries/pools/poolData.ts
  src/state/info/queries/tokens/tokenData.ts
Labels: size/M

#4916 fix: (trading-competition): Trading competition contract makes calls on different chains resulting error
  src/views/TradingCompetition/EasterCompetition.tsx
  src/views/TradingCompetition/FanTokenCompetition.tsx
  src/views/TradingCompetition/MoDCompetition.tsx
  src/views/TradingCompetition/MoboxCompetition.tsx
Labels: size/L

#4940 refactor: Remove timestamp store data from user redux and don't use delete operator
  src/state/user/reducer.ts
Labels: size/S

#4935 feat: Update farm test
  src/config/__tests__/farms.test.ts
Labels: size/M

#4795 feat: Wallet modal v2
  jest.config.js
  packages/hooks/src/index.ts
  packages/hooks/src/usePreloadImage.ts
  packages/localization/src/Trans.ts
  packages/localization/src/config/translations.json
  packages/localization/src/index.tsx
  packages/ui-wallets/package.json
  packages/ui-wallets/src/WalletModal.css.ts
  packages/ui-wallets/src/WalletModal.tsx
  packages/ui-wallets/src/components/Intro.tsx
  packages/ui-wallets/src/components/QRCode.tsx
  packages/ui-wallets/src/docLangCodeMapping.ts
  packages/ui-wallets/src/index.ts
  packages/ui-wallets/tsconfig.json
  packages/ui/components/AtomBox.tsx
  packages/ui/css/sprinkles.css.ts
  packages/ui/tokens/index.ts
  packages/uikit/package.json
  packages/uikit/src/components/Image/Image.tsx
  packages/uikit/src/components/TabMenu/TabMenu.tsx
  packages/uikit/src/components/TabMenu/types.ts
  packages/uikit/src/util/animationToolkit.ts
  packages/uikit/src/widgets/Modal/Modal.tsx
  packages/uikit/src/widgets/Modal/ModalContext.tsx
  packages/uikit/src/widgets/Modal/ModalV2.tsx
  packages/uikit/src/widgets/Modal/index.tsx
  packages/uikit/src/widgets/Modal/types.ts
  packages/wagmi/package.json
  public/images/wallets/binance.png
  public/images/wallets/blocto.png
  public/images/wallets/brave.png
  public/images/wallets/coin98.png
  public/images/wallets/coinbase.png
  public/images/wallets/mathwallet.png
  public/images/wallets/metamask.png
  public/images/wallets/opera.png
  public/images/wallets/safepal.png
  public/images/wallets/tokenpocket.png
  public/images/wallets/trust.png
  public/images/wallets/walletconnect.png
  src/__tests__/translations.test.ts
  src/components/AddToWallet/AddToWalletButton.tsx
  src/components/ConnectWalletButton.tsx
  src/config/wallet.ts
  src/global.d.ts
  src/hooks/useAuth.tsx
  src/hooks/useSwitchNetwork.ts
  src/hooks/useWallet.ts
  src/pages/index.tsx
  src/utils/wagmi.ts
  src/utils/wallet.ts
  src/views/TradingCompetition/components/BattleCta/index.tsx
  yarn.lock
Labels: size/XXL

#4937 refactor: Remove array index as key usage
  src/views/Info/components/InfoSearch/index.tsx
  src/views/Swap/components/SwapRoute.tsx
Labels: size/XS

#4939 refactor: Make getlpsymbol generic
  src/utils/getLpSymbol.ts
  src/views/AddLiquidity/components/common.tsx
  src/views/AddLiquidity/index.tsx
  src/views/RemoveLiquidity/index.tsx
Labels: size/M

#4816 feat: (ifo): Add dynamic cake to burn info for ifos
  src/config/constants/ifo.ts
  src/config/constants/types.ts
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
Labels: size/M

#4895 fix: (ifo banner): Fix ifo banner and status in other chains
  src/components/Menu/hooks/useMenuItemsStatus.ts
  src/state/block/hooks.ts
  src/views/Home/components/Banners/IFOBanner.tsx
  src/views/Home/components/Banners/hooks/useIsRenderIFOBanner.tsx
Labels: size/M

#4947 chore: Remove static cake to burn info for krs ifo
  src/config/constants/ifo.ts
Labels: size/XS

#4945 feat: List KRS
  packages/farms/constants/56.ts
  src/config/constants/pools.tsx
Labels: size/M, automerge

#4946 feat: Add IFO NFT warning text
  packages/localization/src/config/translations.json
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardTokens.tsx
Labels: size/S, automerge

#4944 perf: Pools page add loading animation
  src/views/Pools/components/CakeVaultCard/index.tsx
  src/views/Pools/components/PoolCard/index.tsx
  src/views/Pools/components/PoolsTable/Cells/NameCell.tsx
Labels: size/L

#4948 chore(wallet): Update wallet wording
  packages/localization/src/config/translations.json
  packages/ui-wallets/src/WalletModal.tsx
  packages/ui-wallets/src/components/Intro.tsx
Labels: size/S

#4949 style(wallet): Wallet connect v2 button height
  packages/ui-wallets/src/components/Intro.tsx
Labels: size/XS, automerge

#4950 style(IFO): Hide CakeVaultCard loading animation
  src/views/Ifos/components/IfoPoolVaultCard.tsx
  src/views/Pools/components/CakeVaultCard/index.tsx
Labels: size/XS, automerge

#4953 chore: fix multi-chain watch list
  src/state/info/hooks.ts
Labels: size/XS

#4955 feat: (swap): Add stable swap warning to swap tab
  src/views/Swap/components/SwapForm.tsx
Labels: size/M

#4958 feat: Astronaut bunny image
  public/images/home/lunar-bunny/astronaut-bunny.png
  public/images/home/lunar-bunny/bunny@2x.png
  src/views/Home/components/Hero.tsx
Labels: size/XS, automerge

#4960 fix(wallet): deeplink on dapp
  packages/ui-wallets/src/WalletModal.tsx
  src/config/wallet.ts
Labels: size/XS

#4963 fix: (wallet): Filter non installed wallets in mobile dapp browser
  packages/ui-wallets/src/WalletModal.tsx
Labels: size/XS, automerge

#4964 fix: (wallet): Missing translation in wallet modal
  packages/ui-wallets/src/WalletModal.tsx
Labels: size/XS, automerge

#4969 fix(voting): Quick fix for snaphost breaking change
  package.json
  packages/localization/src/config/translations.json
  src/views/Voting/CreateProposal/index.tsx
  src/views/Voting/components/CastVoteModal/index.tsx
  yarn.lock
Labels: size/XL

#4970 fix: (harvest-card): Boost farms not available on harvest card homepage
  src/views/Home/components/UserBanner/HarvestCard.tsx
  src/views/Home/hooks/useFarmsWithBalance.tsx
Labels: size/M

#4973 chore: Bump up redux
  package.json
  yarn.lock
Labels: size/S

#4974 chore: Bump up graphql and request
  package.json
  yarn.lock
Labels: size/S

#4972 chore: Bump up countup
  package.json
  yarn.lock
Labels: size/S

#4968 style: Tooltip color flip
  packages/uikit/src/components/Tooltip/theme.ts
  packages/uikit/src/hooks/useTooltip/useTooltip.tsx
  src/views/Predictions/components/Label.tsx
Labels: size/S, automerge

#4967 fix(TabMenu): Tab active should highlight when active
  packages/uikit/src/components/TabMenu/TabMenu.tsx
  packages/uikit/src/components/TabMenu/types.ts
Labels: size/S

#4966 perf: (nft): Use isAddress when comparing address instead of toLowerCase
  src/views/Nft/market/ActivityHistory/ActivityHistory.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/ForSaleTableCard/ForSaleTableRows.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/MainPancakeBunnyCard.tsx
  src/views/Nft/market/Collection/IndividualNFTPage/shared/ManageNFTsCard.tsx
  src/views/Nft/market/components/BuySellModals/SellModal/TransferStage.tsx
  src/views/Nft/market/components/Filters/ListCollectionFilter/index.tsx
  src/views/Nft/market/hooks/useCompleteNft.tsx
  src/views/Nft/market/hooks/useNftOwner.tsx
  src/views/Nft/market/hooks/usePancakeBunnyOnSaleNfts.tsx
Labels: size/M

#4954 fix: (ifo): Funds to raise info not shown when ifo is live
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
Labels: size/XS

#4965 perf: (nft): Use partition in nft activity to separate pb collections
  src/views/Nft/market/ActivityHistory/utils/fetchActivityNftMetadata.tsx
Labels: size/M

#4981 chore: Update cIFO status
  src/config/constants/ifo.ts
Labels: size/XS

#4983 chore: Update achievements ifo wording
  src/utils/achievements.ts
Labels: size/XS, automerge

#4982 feat: List WMX IFO
  packages/tokens/src/56.ts
  public/images/achievements/ifo-wmx.svg
  public/images/ifos/wmx-bg.png
  public/images/tokens/0xa75d9ca2a0a1D547409D82e1B06618EC284A2CeD.png
  public/images/tokens/0xa75d9ca2a0a1D547409D82e1B06618EC284A2CeD.svg
  src/config/constants/campaigns.ts
  src/config/constants/ifo.ts
Labels: size/L

#4985 fix: define the locale setting in test environment
  package.json
Labels: size/XS

#4987 feat: Pottery wording
  packages/localization/src/config/translations.json
  src/views/Pottery/components/Banner/index.tsx
Labels: size/XS, automerge

#4991 fix(ifo): Update display amount
  src/config/constants/ifo.ts
Labels: size/XS

#4992 chore: Update the raise amount
  src/config/constants/ifo.ts
Labels: size/XS

#4990 chore: Bump up recharts and remove hover updater
  package.json
  src/views/Info/components/InfoCharts/BarChart/index.tsx
  src/views/Info/components/InfoCharts/LineChart/index.tsx
  src/views/Predictions/components/ChainlinkChart.tsx
  src/views/Swap/components/Chart/SwapLineChart.tsx
  yarn.lock
Labels: size/L

#4997 revert: (claim): Success toast appears before transaction is successf…
  src/components/GlobalCheckClaimStatus/index.tsx
Labels: size/S

#4998 revert: "perf: (refresh hook): Don't read & write swr cache"
  src/hooks/useRefreshEffect.ts
  src/state/block/hooks.ts
Labels: size/S

#4999 revert: Revert optimization prs
  src/components/GlobalCheckClaimStatus/index.tsx
  src/hooks/useRefreshEffect.ts
  src/state/block/hooks.ts
Labels: size/S

#4996 feat: WMX farm and pool
  packages/farms/constants/56.ts
  src/config/constants/pools.tsx
Labels: size/S

#5001 feat(wallets): Update styles and remove extended config
  packages/ui-wallets/src/WalletModal.css.ts
  packages/ui-wallets/src/WalletModal.tsx
  packages/ui/css/sprinkles.css.ts
  packages/ui/tokens/colors.ts
  packages/ui/tokens/index.ts
  packages/uikit/src/widgets/Modal/ModalV2.tsx
  src/config/wallet.ts
Labels: size/L

#4988 chore: Bump up date-fns
  package.json
  yarn.lock
Labels: size/XS

#4995 chore: filter unknown tokens and pools from top token and pools
  src/views/Info/Overview/index.tsx
Labels: size/XS

#5003 fix: (ifo): Vesting schedule tooltip text
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
Labels: size/XS

#5006 fix: (farms): Boost button not fully clickable
  src/views/Farms/components/YieldBooster/components/BoostedAction.tsx
Labels: size/S

#4978 perf: Use poll core farm data only in pools and farms instead of global
  src/pages/_app.tsx
  src/state/farms/hooks.ts
  src/state/pools/hooks.ts
Labels: size/M

#5009 chore: reduce unnecessary refetch for info page
  src/state/info/hooks.ts
Labels: size/M

#5008 chore: Pools recent cake tooltip adjustment
  packages/localization/src/config/translations.json
  src/views/Pools/components/AutoEarningsBreakdown.tsx
Labels: size/M

#5022 fix: (swap): Numpad appears after clicking max
  src/components/CurrencyInputPanel/index.tsx
Labels: size/S

#5021 fix: (farms): Farms not visible after switching network back
  src/state/farms/hooks.ts
  src/state/farms/index.ts
  src/state/pools/hooks.ts
  src/state/types.ts
Labels: size/M

#5025 refactor: Remove warning and call dispatch only when chain id different
  src/state/farms/index.ts
  src/state/pools/hooks.ts
Labels: size/M

#5023 feat: List farm auction winner 32
  packages/farms/constants/56.ts
Labels: size/M

#5020 fix: (ifo): Vault card roi calculator doesn't show roi
  src/state/pools/hooks.ts
Labels: size/S

#5018 chore: cake profit tooltip adjustment part2
  src/views/Pools/components/AutoEarningsBreakdown.tsx
Labels: size/XS

#5004 feat(IFO): Change pricePerTokenWithFee's precision from 2 to 4
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
Labels: size/XS

#4909 fix: (info): Infinite redirect loop in development mode in info page with different network than bsc
  src/views/Info/index.tsx
Labels: size/XS

#5032 chore: pool locked button styling
  src/views/Pools/components/LockedPool/Buttons/ConvertToFlexibleButton.tsx
  src/views/Pools/components/LockedPool/Common/AfterLockedActions.tsx
Labels: size/S

#5027 chore(nft): Shadow delist inactive collections
  packages/localization/src/config/translations.json
  src/config/constants/nftsCollections/delist.ts
  src/views/Nft/market/Collection/Header.tsx
  src/views/Nft/market/Collections/index.tsx
  src/views/Nft/market/components/MarketPageTitle.tsx
Labels: size/M

#5036 chore: Remove global claim checking
  src/components/GlobalCheckClaimStatus/index.tsx
Labels: size/XS

#5037 perf(voting): VP get from graphql
  src/state/types.ts
  src/state/voting/helpers.ts
Labels: size/S

#5038 chore: Move finished sfund pool to finished pools
  src/config/constants/pools.tsx
Labels: size/S

#5035 fix: (swap): Refresh block number hook doesn't call the block number swr hook
  src/state/block/hooks.ts
  src/views/Swap/hooks/useRefreshBlockNumber.ts
Labels: size/XS

#5034 perf: Use web3 react hook directly when only account is needed
  src/components/App/Transactions/TransactionsModal.tsx
  src/components/CurrencyInputPanel/index.tsx
  src/components/CurrencySelect/index.tsx
  src/state/mint/hooks.ts
  src/state/transactions/hooks.tsx
  src/views/AddLiquidity/AddStableLiquidity/hooks/useStableLPDerivedMintInfo.tsx
  src/views/AddLiquidity/ChoosePair.tsx
  src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
  src/views/Farms/components/YieldBooster/hooks/useBoostMultiplier.ts
  src/views/Farms/components/YieldBooster/hooks/useYieldBoosterState.ts
  src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/index.tsx
  src/views/Ifos/components/IfoVesting/index.tsx
  src/views/Pottery/components/Pot/Claim/index.tsx
  src/views/Pottery/components/Pot/Deposit/index.tsx
  src/views/Pottery/components/WinRateModal/ButtonMenu.tsx
  src/views/RemoveLiquidity/RemoveStableLiquidity/hooks/useStableDerivedBurnInfo.ts
  src/views/Swap/StableSwap/components/StableSwapForm.tsx
Labels: size/M

#5029 chore(WalletModal): Remove tab gap
  packages/ui-wallets/src/WalletModal.tsx
Labels: size/XS

#5030 refactor: (profile): Use isaddress to check connected account
  src/views/Profile/components/ProfileHeader.tsx
Labels: size/XS

#5028 feat(Limit): Hide the MAX button when it is clicked
  src/views/LimitOrders/index.tsx
Labels: size/XS

#5013 chore: Bump up jotai
  package.json
  src/hooks/useFeatureFlag.ts
  yarn.lock
Labels: size/S

#5041 fix: (stableswap): Remove empty lp fee row from stableswap confirm modal
  src/views/Swap/StableSwap/components/StableSwapModalFooter.tsx
Labels: size/S

#5044 test: Update eth test node url
  src/utils/wagmi.ts
Labels: size/XS

#5045 feat: PancakeSwap X Aptos banner
  packages/localization/src/config/translations.json
  src/views/Home/components/Banners/AptosBanner.tsx
  src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  src/views/Home/components/Banners/images/Aptos.png
  src/views/Home/components/Banners/images/AptosXPancakeSwap.png
  src/views/Home/components/Banners/images/index.ts
Labels: size/M

#5046 chore: hide aptos banner and styling for mobile
  src/views/Home/components/Banners/AptosBanner.tsx
  src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/S

#5052 chore: Show Aptos banner
  src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/XS

#5059 fix: Safari regex lookbehind not supported
  packages/awgmi/core/src/utils.ts
Labels: size/S

#5057 fix: Phishing warning text
  apps/aptos/components/PhishingWarningBanner.tsx
Labels: size/XS, automerge

#5050 chore: Remove eslint-disable-next-line consistent-return ignore
  packages/token-lists/src/lists.ts
  packages/uikit/src/components/CoinSwitcher/SequencePlayer.tsx
  src/components/TradingView.tsx
  src/hooks/useApproveCallback.ts
  src/hooks/useAuth.tsx
Labels: size/S

#5048 fix: Low native balance check threshold is too low
  src/components/Menu/UserMenu/WalletModal.tsx
  src/components/Menu/UserMenu/WalletUserMenuItem.tsx
Labels: size/XS

#5063 chore: Version package
  packages/awgmi/package.json
Labels: size/XS

#5066 chore: Setup changeset
  .changeset/README.md
  .changeset/config.json
  .github/workflows/release.yml
  package.json
  packages/eslint-config/package.json
  packages/farms/package.json
  packages/hooks/package.json
  packages/localization/package.json
  packages/multicall/package.json
  packages/tokens/package.json
  packages/tsconfig/package.json
  packages/ui-wallets/package.json
  packages/ui/package.json
  packages/uikit/package.json
  packages/utils/package.json
  yarn.lock
Labels: size/XL

#5064 fix(awgmi): Allow petra connector id override
  .changeset/dirty-ducks-walk.md
  packages/awgmi/core/src/connectors/petra.ts
Labels: size/XS

#5017 chore: Remove vanilla extract patch
  package.json
  packages/ui/package.json
  packages/uikit/package.json
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  patches/@vanilla-extract+css+1.9.0.patch
  yarn.lock
Labels: size/L

#5062 perf(aptos): Memo tx updater
  apps/aptos/state/transactions/updater.tsx
Labels: size/M

#5068 chore: Rename release title
  .github/workflows/release.yml
Labels: size/XS

#5053 chore: Bump up countup
  package.json
  yarn.lock
Labels: size/S

#5070 chore: Yarn lock changes
  yarn.lock
Labels: size/XS

#5071 feat(aptos): Add trustwallet deeplink IOS
  apps/aptos/config/wallets.ts
Labels: size/XS

#4942 refactor(mono): Prepare patch 3
  src/components/SearchModal/ManageLists.tsx
  src/react-app-env.d.ts
  src/state/farms/fetchFarmUser.ts
  src/state/farms/fetchMasterChefData.ts
  src/state/farms/index.ts
  src/views/Farms/components/MultiChainHarvestModal.tsx
  src/views/Farms/hooks/useFarmCProxyAddress.ts
Labels: size/S

#5054 chore: Bump up redux toolkit
  package.json
  yarn.lock
Labels: size/S

#5077 chore: Update LP APRs for Farms
  apps/web/jest.config.js
  apps/web/src/config/constants/lpAprs/1.json
  apps/web/src/config/constants/lpAprs/56.json
  packages/wagmi/package.json
  turbo.json
Labels: size/L

#5078 fix: Lock file and ci
  .changeset/config.json
  package.json
  yarn.lock
Labels: size/XXL

#5080 chore: Setup aptos swap sdk release
  .changeset/funny-pots-grin.md
  packages/aptos-swap-sdk/package.json
  packages/aptos-swap-sdk/src/router.ts
Labels: size/XS

#5081 fix(web): Dev script
  apps/web/package.json
  lerna.json
  package.json
  packages/farms/package.json
  packages/wagmi/chains/package.json
  packages/wagmi/connectors/binanceWallet/package.json
  packages/wagmi/connectors/miniProgram/package.json
  packages/wagmi/package.json
  packages/wagmi/tsup.config.ts
  turbo.json
Labels: size/M

#5084 fix: Swap sdk packages
  packages/swap-sdk/package.json
Labels: size/XS

#5085 feat(ifo): List IFO MGP
  apps/web/public/images/achievements/ifo-mgp.svg
  apps/web/public/images/ifos/mgp-bg.png
  apps/web/public/images/tokens/0xD06716E1Ff2E492Cc5034c2E81805562dd3b45fa.png
  apps/web/public/images/tokens/0xD06716E1Ff2E492Cc5034c2E81805562dd3b45fa.svg
  apps/web/src/config/constants/campaigns.ts
  apps/web/src/config/constants/ifo.ts
  packages/tokens/src/56.ts
Labels: size/L, automerge

#5088 fix(uitkit): Menu height css
  apps/aptos/components/Layout/ExchangeLayout.tsx
  apps/web/package.json
  apps/web/src/components/Layout/Page.tsx
  apps/web/src/views/Swap/index.tsx
  packages/ui/css/sprinkles.css.ts
  packages/uikit/package.json
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/components/Footer/Footer.tsx
  packages/uikit/src/widgets/Menu/Menu.tsx
  packages/uikit/src/widgets/Swap/Page.tsx
  packages/uikit/src/widgets/Swap/SwapWidget.css.ts
  yarn.lock
Labels: size/XXL

#5089 fix(home): Fix tvl data
  apps/web/src/pages/index.tsx
Labels: size/XS

#5090 docs: Update README and doc
  README.md
  cli/aptos-codegen/0xc7efb4076dbe143cbcd98cfaaa929ecfc8f299203dfff63b95ccb6bfe19850fa.ts
  doc/Farms.md
  doc/Info.md
  doc/Pools.md
  doc/Tokens.md
  packages/aptos-swap-sdk/README.md
  packages/swap-sdk/README.md
Labels: size/L

#5033 fix: (swap): Chart button visible when chain is not supported
  apps/web/src/views/Swap/StableSwap/components/StableSwapForm.tsx
  apps/web/src/views/Swap/StableSwap/index.tsx
  apps/web/src/views/Swap/components/CurrencyInputHeader.tsx
  apps/web/src/views/Swap/components/SwapForm.tsx
  apps/web/src/views/Swap/index.tsx
Labels: size/L

#5091 fix(aptos): Handle simulation error on Liquidity
  apps/aptos/components/Liquidity/hooks/useAddLiquidityHandler.ts
  apps/aptos/components/Liquidity/hooks/useRemoveLiquidityHandler.ts
Labels: size/M

#5087 feat: List MGP farm and pool
  apps/web/src/config/constants/pools.tsx
  packages/farms/constants/56.ts
Labels: size/S

#5093 chore: Remove hasWarningBanner
  apps/web/src/views/Page.tsx
  packages/uikit/src/widgets/Swap/Page.tsx
Labels: size/XS, automerge

#5094 fix(uikit): Menu body height
  apps/web/src/views/LimitOrders/index.tsx
  apps/web/src/views/Swap/components/Chart/styles.tsx
  apps/web/src/views/Swap/index.tsx
  packages/uikit/src/widgets/Menu/Menu.tsx
  packages/uikit/src/widgets/Swap/SwapWidget.css.ts
Labels: size/S

#5092 chore: Remove finished ankr pool and price helper lp
  apps/web/src/config/constants/pools.tsx
  apps/web/src/config/constants/priceHelperLps/pools/56.ts
Labels: size/S

#5074 fix: Custom error component show network modal error on other chains
  apps/web/src/pages/_error.tsx
Labels: size/XS

#5051 fix: (limitorder): Missing order cancellation transaction translation
  apps/web/src/__tests__/translations.test.ts
  apps/web/src/hooks/limitOrders/useGelatoLimitOrdersHandlers.ts
  packages/localization/src/config/translations.json
Labels: size/S

#5031 perf: (swap): Don't render access risk component when it is not supported
  apps/web/src/views/Swap/components/SwapForm.tsx
Labels: size/XS

#4910 fix: (swap): Import token modal appears if accessing swap page with unsupported network
  apps/web/src/views/Swap/hooks/useWarningImport.tsx
Labels: size/S

#4431 perf: Don't run getFarmFromTokenSymbol when farm quote token is bnb or busd
  apps/web/src/state/farms/getFarmsPrices.ts
Labels: size/S

#5096 fix(wagmi): binance wallet package path
  .changeset/honest-seahorses-wait.md
  packages/wagmi/connectors/binanceWallet/package.json
Labels: size/XS

#5095 fix(health-indicator): Remove NFT words for generic usage
  apps/web/src/components/Menu/GlobalSettings/SettingsModal.tsx
  packages/localization/src/config/translations.json
Labels: size/XS
