Repository pancakeswap/pancake-frontend, pull requests merged in 2023-02, with the labels that each got.

#5981 fix: eth farm info path when wallet unconnected
  apps/web/src/views/Farms/components/FarmCard/FarmCard.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
Labels: size/S

#5984 chore(farm): Sort ETH farm
  packages/farms/constants/1.ts
Labels: size/M, automerge

#5974 feat(web): Changes gas settings wording
  apps/web/src/components/Menu/GlobalSettings/GasSettings.tsx
  packages/localization/src/config/translations.json
Labels: size/S, automerge

#5951 refactor: (pools): Remove duplicate total token component
  apps/aptos/components/Pools/components/PoolCard/PoolStatsInfo.tsx
  apps/aptos/components/Pools/components/PoolCard/Stat.tsx
  apps/web/src/views/Pools/components/PoolStatsInfo.tsx
  apps/web/src/views/Pools/components/Stat.tsx
  packages/uikit/src/widgets/Pool/StatWrapper.tsx
  packages/uikit/src/widgets/Pool/TotalStaked.tsx
  packages/uikit/src/widgets/Pool/index.tsx
Labels: size/L

#5934 refactor: Remove duplicate transaction error and confirmation modal content components
  apps/aptos/components/Liquidity/components/ConfirmAddLiquidityModal.tsx
  apps/aptos/components/Liquidity/components/ConfirmRemoveLiquidityModal.tsx
  apps/aptos/components/Swap/ConfirmSwapModal.tsx
  apps/aptos/components/Swap/TransactionConfirmSwapContent.tsx
  apps/aptos/components/TransactionConfirmationModal/index.tsx
  apps/web/src/components/TransactionConfirmationModal/index.tsx
  apps/web/src/views/AddLiquidity/components/ConfirmAddLiquidityModal.tsx
  apps/web/src/views/AddLiquidity/components/ConfirmZapInModal.tsx
  apps/web/src/views/LimitOrders/components/ConfirmLimitOrderModal.tsx
  apps/web/src/views/LimitOrders/components/LimitOrderTable/DetailLimitOrderModal.tsx
  apps/web/src/views/Swap/SmartSwap/components/ConfirmSwapModal.tsx
  apps/web/src/views/Swap/SmartSwap/components/TransactionConfirmSwapContent.tsx
  apps/web/src/views/Swap/components/ConfirmRemoveLiquidityModal.tsx
  apps/web/src/views/Swap/components/ConfirmSwapModal.tsx
  apps/web/src/views/Swap/components/TransactionConfirmSwapContent.tsx
  packages/uikit/src/widgets/Swap/ConfirmationModalContent.tsx
  packages/uikit/src/widgets/Swap/TransactionErrorContent.tsx
  packages/uikit/src/widgets/Swap/index.ts
Labels: size/L

#5884 fix: (swap): Swap modal trade info text should contain amount and symbol and remove duplicate swap modal headers
  apps/aptos/components/Swap/SwapModalHeader.tsx
  apps/web/src/views/Swap/SmartSwap/components/SwapModalHeader.tsx
  apps/web/src/views/Swap/SmartSwap/components/TransactionConfirmSwapContent.tsx
  apps/web/src/views/Swap/StableSwap/components/StableSwapModalHeader.tsx
  apps/web/src/views/Swap/components/SwapModalHeader.tsx
  apps/web/src/views/Swap/components/TransactionConfirmSwapContent.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#5973 chore: Compress Spinner gif
  apps/web/public/images/pancake-3d-spinner-v2.gif
  apps/web/public/images/pancake-3d-spinner.gif
  packages/uikit/src/components/Spinner/Spinner.tsx
Labels: size/XS, automerge

#5972 feat(Blog): New layout
  apps/blog/components/Menu.tsx
  apps/blog/next.config.mjs
  apps/blog/pages/[slug].tsx
  apps/blog/pages/blog/article/index.tsx
  apps/blog/pages/index.tsx
  apps/blog/views/Blog/components/Article/AllArticle/index.tsx
  apps/blog/views/Blog/components/Article/ArticleView.tsx
  apps/blog/views/Blog/components/Article/CardArticle.tsx
  apps/blog/views/Blog/components/Article/SingleArticle/ArticleInfo.tsx
  apps/blog/views/Blog/components/Article/SingleArticle/SimilarArticles.tsx
  apps/blog/views/Blog/components/ChefsChoice/index.tsx
  apps/blog/views/Blog/components/MoreButton.tsx
  apps/blog/views/Blog/components/NewBlog.tsx
  apps/blog/views/Blog/components/SearchBar.tsx
  apps/blog/views/Blog/index.tsx
  apps/blog/views/Blog/utils/api.ts
  apps/blog/views/Blog/utils/transformArticle.ts
  apps/web/src/__tests__/translations.test.ts
  packages/localization/src/config/translations.json
Labels: size/L, automerge

#5989 feat(Blog): Move views folder to root
  apps/blog/components/Article/AllArticle/index.tsx
  apps/blog/components/Article/ArticleSortSelect.tsx
  apps/blog/components/Article/ArticleView.tsx
  apps/blog/components/Article/CardArticle.tsx
  apps/blog/components/Article/CategoriesSelector.tsx
  apps/blog/components/Article/SingleArticle/ArticleInfo.tsx
  apps/blog/components/Article/SingleArticle/HowItWork.tsx
  apps/blog/components/Article/SingleArticle/SimilarArticles.tsx
  apps/blog/components/Article/SingleArticle/SocialIcon.tsx
  apps/blog/components/BlogCard.tsx
  apps/blog/components/ChefsChoice/index.tsx
  apps/blog/components/MoreButton.tsx
  apps/blog/components/NewBlog.tsx
  apps/blog/components/SkeletonArticle.tsx
  apps/blog/hooks/getArticle.ts
  apps/blog/hooks/useAllArticle.ts
  apps/blog/hooks/useSearchBarArticle.ts
  apps/blog/pages/articles/[slug].tsx
  apps/blog/pages/index.tsx
  apps/blog/types.ts
  apps/blog/utils/api.ts
  apps/blog/utils/transformArticle.ts
  apps/blog/views/Blog/components/Article/SingleArticle/index.tsx
  apps/blog/views/Blog/index.tsx
Labels: size/L, automerge

#5995 feat(farm/pool): List CHAMP
  apps/web/public/images/tokens/0x7e9AB560d37E62883E882474b096643caB234B65.png
  apps/web/src/config/constants/pools.tsx
  packages/farms/constants/56.ts
  packages/tokens/src/56.ts
Labels: size/S

#5999 fix: (uikit): Import from path not library
  packages/uikit/src/widgets/Ifo/IfoGenericIfoCard.tsx
  packages/uikit/src/widgets/Ifo/IfoPercentageOfTotal.tsx
  packages/uikit/src/widgets/Ifo/IfoProgressStepper.tsx
  packages/uikit/src/widgets/Ifo/IfoSkeletons.tsx
  packages/uikit/src/widgets/Ifo/IfoVestingAvailableToClaim.tsx
  packages/uikit/src/widgets/Ifo/IfoVestingFooter.tsx
Labels: size/S

#5997 chore(Info): Add BscScanIcon
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/Info/Tokens/TokenPage.tsx
Labels: size/S

#5996 refactor: Remove duplicate release chart and bunny components
  apps/aptos/views/Ifos/components/ComingSoonSection.tsx
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/Icons/BunnyKnownPlaceholder.tsx
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoVestingCard/ReleasedChart.tsx
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoVestingCard/ReleasedTokenInfo.tsx
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoVestingCard/Step.tsx
  apps/web/src/views/Ifos/components/ComingSoonSection.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/Icons/BunnyKnownPlaceholder.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoVestingCard/ReleasedChart.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoVestingCard/ReleasedTokenInfo.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoVestingCard/Step.tsx
  packages/uikit/src/components/index.ts
Labels: size/L

#6001 chore: Bump up swiper
  apps/blog/package.json
  apps/web/package.json
  yarn.lock
Labels: size/S

#6008 chore(Bridge): Update aptos bridge wording
  apps/bridge/components/layerZero/AptosBridgeMessage.tsx
Labels: size/XS, automerge

#6006 chore(Farms): Adjust the placement of the ViewContract
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  packages/uikit/src/widgets/Farm/components/FarmCard/DetailsSection.tsx
Labels: size/XS

#6002 revert: Bump up swiper (#6001)
  apps/blog/package.json
  apps/web/package.json
  yarn.lock
Labels: size/S

#6007 fix(Pottery): Fix prize being cut on mobile
  apps/web/src/views/Pottery/components/Banner/index.tsx
Labels: size/XS

#6011 chore(HomePage): Add externalLinkIcon of "Learn"
  apps/web/src/views/Home/components/Footer.tsx
  apps/web/src/views/Home/components/SalesSection/index.tsx
Labels: size/XS

#6012 fix(Limit): Fix BSCScanIcon color
  apps/web/src/views/LimitOrders/components/LimitOrderTable/DetailLimitOrderModal.tsx
Labels: size/XS

#6000 feat: Add swiper to wallet intro
  apps/aptos/package.json
  apps/web/package.json
  packages/ui-wallets/package.json
  packages/ui-wallets/src/components/Intro.tsx
Labels: size/M

#6005 refactor: Use path instead of uikit library for all widgets
  packages/uikit/src/widgets/Farm/components/FarmTabButtons.tsx
  packages/uikit/src/widgets/Liquidity/AddLiquidity/ChoosePairView.tsx
  packages/uikit/src/widgets/Liquidity/AprRow.tsx
  packages/uikit/src/widgets/Liquidity/LiquidityCardHeader.tsx
  packages/uikit/src/widgets/Liquidity/PercentSlider.tsx
  packages/uikit/src/widgets/Pool/AprRowWithToolTip.tsx
  packages/uikit/src/widgets/Pool/Cells/AprCell.tsx
  packages/uikit/src/widgets/Pool/Cells/TotalStakedCell.tsx
  packages/uikit/src/widgets/Pool/CollectModal.tsx
  packages/uikit/src/widgets/Pool/PoolCard.tsx
  packages/uikit/src/widgets/Pool/withCollectModal.tsx
  packages/uikit/src/widgets/Pool/withStakeActions.tsx
  packages/uikit/src/widgets/Swap/ExpertModal.tsx
  packages/uikit/src/widgets/Swap/TradePrice.tsx
Labels: size/L

#6015 chore: Update lp reward fee percent of stable swap pairs
  packages/farms/constants/56.ts
Labels: size/XS

#6016 chore(Pottery): Change APY to APR
  apps/web/src/views/Pottery/components/Banner/index.tsx
  apps/web/src/views/Pottery/components/Pot/Deposit/index.tsx
  apps/web/src/views/Pottery/components/PrizeFunds.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#5882 refactor: (swap): Remove duplicate confirmation pending content
  apps/aptos/README.md
  apps/aptos/components/Swap/ConfirmSwapModal.tsx
  apps/aptos/components/Swap/ConfirmationPendingContent.tsx
  apps/aptos/components/TransactionConfirmationModal/index.tsx
  apps/web/src/components/TransactionConfirmationModal/index.tsx
  apps/web/src/views/LimitOrders/components/LimitOrderTable/DetailLimitOrderModal.tsx
  apps/web/src/views/Swap/SmartSwap/components/ConfirmSwapModal.tsx
  apps/web/src/views/Swap/components/ConfirmSwapModal.tsx
  apps/web/src/views/Swap/components/ConfirmationPendingContent.tsx
  packages/uikit/src/components/Column/AutoColumn.tsx
  packages/uikit/src/widgets/Swap/ConfirmationPendingContent.tsx
  packages/uikit/src/widgets/Swap/index.ts
Labels: size/L, automerge

#6014 feat: List Fuse-WETH LP
  apps/web/public/images/1/tokens/0x970B9bB2C0444F5E81e9d0eFb84C8ccdcdcAf84d.png
  packages/farms/constants/1.ts
  packages/tokens/src/1.ts
Labels: size/S, automerge

#6019 chore: Rename LP symbol
  packages/farms/constants/1.ts
Labels: size/XS, automerge

#6022 refactor: Remove duplicate tokens pages static path getters
  apps/web/src/pages/info/[chainName]/tokens/[address].tsx
  apps/web/src/pages/info/tokens/[address].tsx
  apps/web/src/utils/pageUtils.ts
Labels: size/M

#6018 test: add concurrent to some tests
  apps/web/src/__tests__/translations.test.ts
  apps/web/src/__tests__/views/lottery/generateTicketNumbers.test.ts
  apps/web/src/config/__tests__/farms.test.ts
  apps/web/src/config/__tests__/pools.test.ts
  apps/web/src/config/__tests__/tokens.test.ts
  apps/web/src/state/multicall/retry.test.ts
  apps/web/src/utils/cakePool.test.ts
Labels: size/M

#5889 chore: New Crowdin updates
  apps/web/public/locales/ar-SA.json
  apps/web/public/locales/bn-BD.json
  apps/web/public/locales/de-DE.json
  apps/web/public/locales/el-GR.json
  apps/web/public/locales/en-US.json
  apps/web/public/locales/es-ES.json
  apps/web/public/locales/fi-FI.json
  apps/web/public/locales/fil-PH.json
  apps/web/public/locales/fr-FR.json
  apps/web/public/locales/hi-IN.json
  apps/web/public/locales/hu-HU.json
  apps/web/public/locales/id-ID.json
  apps/web/public/locales/it-IT.json
  apps/web/public/locales/ja-JP.json
  apps/web/public/locales/ko-KR.json
  apps/web/public/locales/nl-NL.json
  apps/web/public/locales/pl-PL.json
  apps/web/public/locales/pt-BR.json
  apps/web/public/locales/pt-PT.json
  apps/web/public/locales/ro-RO.json
  apps/web/public/locales/ru-RU.json
  apps/web/public/locales/sv-SE.json
  apps/web/public/locales/ta-IN.json
  apps/web/public/locales/tr-TR.json
  apps/web/public/locales/uk-UA.json
  apps/web/public/locales/vi-VN.json
  apps/web/public/locales/zh-CN.json
  apps/web/public/locales/zh-TW.json
Labels: size/XXL

#6025 feat(blog): Add analytics and balancer title
  apps/blog/components/Article/SingleArticle/ArticleInfo.tsx
  apps/blog/package.json
  apps/blog/pages/_app.tsx
  yarn.lock
Labels: size/S

#6020 fix: (liquidity): Default tokens cannot switch when adding liquidity
  apps/web/src/views/AddLiquidity/useCurrencySelectRoute.ts
Labels: size/XS

#6026 feat(Blog): Update UI
  apps/blog/components/Article/CardArticle.tsx
  apps/blog/components/Article/SingleArticle/ArticleInfo.tsx
  apps/blog/components/Article/SingleArticle/HowItWork.tsx
  apps/blog/components/Article/SingleArticle/SimilarArticles.tsx
  apps/blog/components/BlogCard.tsx
  apps/blog/components/ChefsChoice/index.tsx
  apps/blog/components/NewBlog.tsx
  apps/blog/components/StyledLineClamp.tsx
Labels: size/M, automerge

#6029 feat(Aptos): List BlueMove IFO
  apps/aptos/components/Menu/Menu.tsx
  apps/aptos/config/constants/ifo.ts
  apps/aptos/config/constants/tokens/1.ts
  apps/aptos/next.config.mjs
  apps/aptos/public/images/achievements/ifo-move.svg
  apps/aptos/public/images/ifos/move-bg.png
Labels: size/M

#6031 fix(Aptos): Typo
  apps/aptos/components/Menu/Menu.tsx
  apps/aptos/config/constants/tokens/1.ts
Labels: size/XS

#6033 feat(aptos-ifo): Add footer
  apps/aptos/config/constants/ifo.ts
  apps/aptos/config/constants/tokens/1.ts
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoCardFooter.tsx
  apps/aptos/views/Ifos/components/IfoFoldableCard/index.tsx
Labels: size/L

#6034 chore: Add Aptos icon
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoCardFooter.tsx
Labels: size/S

#6032 fix: Token selection with same but non-checksummed address causes both sides to be selected with same token
  apps/web/src/components/SearchModal/CurrencySearch.tsx
  apps/web/src/state/lists/hooks.ts
  apps/web/src/utils/index.ts
Labels: size/M

#6035 feat: Add dynamic menu status to aptos
  apps/aptos/components/Menu/Menu.tsx
  apps/aptos/components/Menu/hooks/useMenuItems.ts
  apps/aptos/components/Menu/hooks/useMenuItemsStatus.ts
  apps/aptos/hooks/useActiveIfoWithBlocks.ts
  apps/aptos/views/Ifos/hooks/useIfoResources.ts
Labels: size/L

#6027 fix(web): total tx not fetching on static build
  .github/workflows/integrationTests.yml
  apps/e2e/cypress/support/commands.js
  apps/web/src/pages/index.tsx
  apps/web/src/utils/graphql.ts
Labels: size/M

#6030 fix: Import token row not collapsed correctly when token symbol is too long
  apps/aptos/components/SearchModal/ImportRow.tsx
  apps/web/src/components/SearchModal/ImportRow.tsx
Labels: size/M

#6028 refactor: Remove duplicate get token modal
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeButton.tsx
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/GetTokenModal.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeButton.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/GetTokenModal.tsx
  packages/uikit/src/widgets/Ifo/IfoGetTokenModal.tsx
  packages/uikit/src/widgets/Ifo/index.ts
Labels: size/L

#6040 feat(web): Update og image
  apis/og-image/next-env.d.ts
  apps/web/next-seo.config.ts
  apps/web/src/components/Layout/Page.tsx
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/config/constants/meta.ts
  apps/web/src/pages/_app.tsx
  apps/web/src/pages/api/_log/[...params].ts
  apps/web/src/views/FarmAuction/index.tsx
  apps/web/src/views/Home/index.tsx
  apps/web/src/views/Ifos/index.tsx
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/Info/Tokens/TokenPage.tsx
  apps/web/src/views/Lottery/index.tsx
  apps/web/src/views/Nft/market/Collection/index.tsx
  apps/web/src/views/Nft/market/Home/index.tsx
  apps/web/src/views/Page.tsx
  apps/web/src/views/Pottery/index.tsx
  apps/web/src/views/Predictions/Leaderboard/index.tsx
  apps/web/src/views/Predictions/index.tsx
  apps/web/src/views/TradingCompetition/FanTokenCompetition.tsx
  apps/web/src/views/TradingCompetition/MoDCompetition.tsx
  apps/web/src/views/TradingCompetition/MoboxCompetition.tsx
  apps/web/src/views/Voting/CreateProposal/index.tsx
  apps/web/src/views/Voting/Proposal/Overview.tsx
  apps/web/src/views/Voting/index.tsx
Labels: size/L

#6041 feat: Add og image api app
  apis/og-image/.eslintrc.json
  apis/og-image/.gitignore
  apis/og-image/README.md
  apis/og-image/components/nft-collection.tsx
  apis/og-image/components/nft.tsx
  apis/og-image/components/swap.tsx
  apis/og-image/components/voting.tsx
  apis/og-image/config.ts
  apis/og-image/next.config.js
  apis/og-image/package.json
  apis/og-image/pages/api/v1/[template].tsx
  apis/og-image/tsconfig.json
  apps/web/src/pages/_app.tsx
  apps/web/src/pages/voting/proposal/[id].tsx
  yarn.lock
Labels: size/XXL

#6042 feat(Aptos-Bridge): Add other cross-chain protocol links
  apps/bridge/components/Menu.tsx
  packages/uikit/src/components/index.ts
Labels: size/M, automerge

#6043 chore(aptos-ifo): Update Unlimited Sale text
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/index.tsx
Labels: size/S

#6039 feat(Aptos): List APT-MOVELP
  apps/aptos/config/constants/farms/1.ts
  apps/aptos/config/constants/tokens/1.ts
Labels: size/S, automerge

#6048 fix(uikit): Storybook build
  package.json
  packages/uikit/.eslintignore
  packages/uikit/.storybook/main.js
  packages/uikit/README.md
  packages/uikit/package.json
  turbo.json
Labels: size/S

#6047 feat(Aptos-IFO): StartTime and endTime use tooltip
  apps/aptos/views/Ifos/components/IfoFoldableCard/Timer.tsx
Labels: size/M

#6049 chore(api): Update node endpoint
  apis/farms/src/provider.ts
Labels: size/XS

#6021 chore(Swap): Change default price display
  packages/uikit/src/widgets/Swap/TradePrice.tsx
Labels: size/XS

#6055 chore(Aptos-IFO): Remove CAKE lock info
  apps/aptos/views/Ifos/components/IfoVesting/NotTokens.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#6053 chore(Swap): Change price symbol
  packages/uikit/src/widgets/Swap/TradePrice.tsx
Labels: size/XS

#6058 fix: Aptos pool reset to 0
  apps/aptos/components/Pools/hooks/usePoolsList.ts
Labels: size/XS

#6059 fix(aptos-ifo): Update vesting title to Unlimited Sale
  apps/aptos/views/Ifos/components/IfoVesting/VestingPeriod/Info.tsx
Labels: size/XS

#6013 refactor: Remove duplicate filter token component
  apps/aptos/components/SearchModal/CurrencySearch.tsx
  apps/aptos/components/SearchModal/filtering.ts
  apps/web/src/components/SearchModal/CurrencySearch.tsx
  apps/web/src/components/SearchModal/filtering.ts
  packages/hooks/package.json
  packages/hooks/src/index.ts
  packages/hooks/src/useSortedTokensByQuery.ts
  packages/utils/filtering.ts
  packages/utils/package.json
Labels: size/L

#5935 refactor: Use autocolumn from uikit
  apps/web/src/components/Layout/Column.tsx
  apps/web/src/components/PositionCard/index.tsx
  apps/web/src/components/SearchModal/CommonBases.tsx
  apps/web/src/components/SearchModal/CurrencyList.tsx
  apps/web/src/components/SearchModal/CurrencySearch.tsx
  apps/web/src/components/SearchModal/ImportRow.tsx
  apps/web/src/components/SearchModal/ImportToken.tsx
  apps/web/src/components/SearchModal/ManageLists.tsx
  apps/web/src/components/SearchModal/ManageTokens.tsx
  apps/web/src/components/TransactionConfirmationModal/index.tsx
  apps/web/src/components/UnsupportedCurrencyFooter.tsx
  apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
  apps/web/src/views/AddLiquidity/PoolPriceBar.tsx
  apps/web/src/views/AddLiquidity/components/ConfirmZapInModal.tsx
  apps/web/src/views/AddLiquidity/components/common.tsx
  apps/web/src/views/AddLiquidity/index.tsx
  apps/web/src/views/LimitOrders/components/SwitchTokensButton.tsx
  apps/web/src/views/LimitOrders/index.tsx
  apps/web/src/views/PoolFinder/index.tsx
  apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/index.tsx
  apps/web/src/views/Swap/SmartSwap/components/SmartSwapCommitButton.tsx
  apps/web/src/views/Swap/SmartSwap/components/SwapModalFooter.tsx
  apps/web/src/views/Swap/SmartSwap/index.tsx
  apps/web/src/views/Swap/StableSwap/components/StableSwapCommitButton.tsx
  apps/web/src/views/Swap/StableSwap/components/StableSwapForm.tsx
  apps/web/src/views/Swap/StableSwap/components/StableSwapModalFooter.tsx
  apps/web/src/views/Swap/components/AddressInputPanel.tsx
  apps/web/src/views/Swap/components/AdvancedSwapDetails.tsx
  apps/web/src/views/Swap/components/ConfirmRemoveLiquidityModal.tsx
  apps/web/src/views/Swap/components/ProgressSteps.tsx
  apps/web/src/views/Swap/components/SwapCommitButton.tsx
  apps/web/src/views/Swap/components/SwapForm.tsx
  apps/web/src/views/Swap/components/SwapModalFooter.tsx
  apps/web/src/views/Swap/components/SwapModalHeader.tsx
  apps/web/src/views/Swap/components/styleds.tsx
Labels: size/L

#6062 chore(aptos-Pools): Change ViewProjectSite position
  apps/aptos/components/Pools/components/PoolCard/PoolStatsInfo.tsx
Labels: size/S

#6054 feat(Aptos-IFO): Add spent info
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardTokens.tsx
Labels: size/M

#6050 feat(Swap&Limit): ScanRisk's tooltip click to show on mobile
  apps/web/src/views/Swap/components/AccessRisk/index.tsx
Labels: size/XS

#6017 refactor: Remove duplicate has vesting and not tokens components
  apps/aptos/next.config.mjs
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx
  apps/aptos/views/Ifos/components/IfoVesting/NotTokens.tsx
  apps/aptos/views/Ifos/components/IfoVesting/index.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx
  apps/web/src/views/Ifos/components/IfoVesting/index.tsx
  packages/uikit/src/widgets/Ifo/IfoHasVestingNotice.tsx
  packages/uikit/src/widgets/Ifo/IfoNotTokens.tsx
  packages/uikit/src/widgets/Ifo/index.ts
  packages/uikit/src/widgets/Ifo/styleds.ts
Labels: size/L

#6067 fix(web): Small issue on eth or mm
  apps/web/src/state/lists/updater.ts
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButton.tsx
  apps/web/src/views/Swap/MMLinkPools/components/SwapModalFooter.tsx
  apps/web/src/views/Swap/MMLinkPools/hooks/useGetRFQTrade.ts
  apps/web/src/views/Swap/SmartSwap/index.tsx
  apps/web/src/views/Swap/hooks/useWarningImport.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#6066 chore(Swap): Price symbol use SyncAltIcon
  packages/uikit/src/widgets/Swap/TradePrice.tsx
Labels: size/XS

#6075 fix(IFO): Fix step icon
  packages/uikit/src/components/DateStep/DateStep.tsx
Labels: size/XS

#6051 fix(api): Revert allow origin
  apis/farms/src/index.ts
  packages/worker-utils/index.test.ts
  packages/worker-utils/index.ts
  packages/worker-utils/package.json
Labels: size/M

#6068 feat(web): USD value for Ethereum
  apps/web/src/config/constants/lists.ts
  apps/web/src/hooks/useBUSDPrice.ts
Labels: size/S

#6081 chore: Adjust MM linked pool RFQ expiry limit
  apps/web/src/views/Swap/MMLinkPools/constants.ts
Labels: size/XS

#6082 chore: Move finished pools
  apps/web/src/config/constants/pools.tsx
Labels: size/M

#6077 fix: Token pocket multi chain harvest
  apps/web/src/views/Farms/Farms.tsx
  apps/web/src/views/Farms/components/MultiChainHarvestModal.tsx
  apps/web/src/views/Farms/hooks/useMultiChainHarvestModal.tsx
Labels: size/M

#6085 chore: additional info for MM dev panel
  apps/web/src/views/Swap/MMLinkPools/apis/index.ts
  apps/web/src/views/Swap/MMLinkPools/components/MMAndAMMDealDisplay.tsx
  apps/web/src/views/Swap/MMLinkPools/hooks/useGetRFQTrade.ts
  apps/web/src/views/Swap/MMLinkPools/types.ts
  apps/web/src/views/Swap/SmartSwap/index.tsx
Labels: size/M

#6086 fix(web): currency possible undefined after token list disable
  apps/web/src/views/Swap/SmartSwap/hooks/useBestTrade.ts
Labels: size/XS

#6076 fix(aptos-Swap): Fix title placement
  apps/aptos/pages/swap.tsx
Labels: size/S

#6088 feat(Farm): List SDAO-BNB LP farm
  packages/farms/constants/56.ts
Labels: size/XS, automerge

#6087 chore: mm-linked-pool-refetch-strategy
  apps/web/src/views/Swap/MMLinkPools/apis/index.ts
  apps/web/src/views/Swap/MMLinkPools/components/MMAndAMMDealDisplay.tsx
  apps/web/src/views/Swap/MMLinkPools/constants.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useGetRFQTrade.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useIsMMQuotingPair.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMOrderBookTrade.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMQuoteCountDown.ts
  apps/web/src/views/Swap/MMLinkPools/types.ts
  apps/web/src/views/Swap/MMLinkPools/utils/exchange.ts
  apps/web/src/views/Swap/SmartSwap/index.tsx
Labels: size/L

#6072 fix(Swap): Fix confirmSwap's tooltip placement on mobile
  apps/aptos/components/Swap/AdvancedSwapDetails.tsx
  apps/aptos/components/Swap/SwapModalFooter.tsx
  apps/web/src/views/Swap/MMLinkPools/components/SwapModalFooter.tsx
  apps/web/src/views/Swap/SmartSwap/components/SwapModalFooter.tsx
  apps/web/src/views/Swap/StableSwap/components/StableSwapModalFooter.tsx
  apps/web/src/views/Swap/components/AdvancedSwapDetails.tsx
  apps/web/src/views/Swap/components/SwapModalFooter.tsx
Labels: size/S

#6074 fix(aptos-IFO): Fix vesting balance display decimals
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoVestingCard/ReleasedTokenInfo.tsx
Labels: size/XS

#6071 fix(aptos-Pools): Fix viewProjectSite position on mobile
  apps/aptos/components/Pools/components/PoolCard/PoolStatsInfo.tsx
Labels: size/S

#6091 chore: Remove gas price on Ethereum
  apps/web/src/state/user/hooks/index.tsx
  apps/web/src/views/Swap/MMLinkPools/hooks/useSwapCallback.ts
Labels: size/S

#6097 feat(web): Add MM loading status
  apps/web/.env
  apps/web/src/components/CurrencyInputPanel/index.tsx
  apps/web/src/components/Svg/RefreshIcon.tsx
  apps/web/src/views/Swap/MMLinkPools/apis/index.ts
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButton.tsx
  apps/web/src/views/Swap/MMLinkPools/hooks/useGetRFQTrade.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMOrderBookTrade.ts
  apps/web/src/views/Swap/SmartSwap/index.tsx
Labels: size/L

#6063 feat(aptos-IFO): Add vesting time info
  apps/aptos/views/Ifos/components/IfoVesting/VestingPeriod/Info.tsx
Labels: size/S

#6065 feat(aptos-Pools): Add contract info
  apps/aptos/components/Pools/components/PoolCard/PoolStatsInfo.tsx
  apps/aptos/utils/getContactAddress.ts
  packages/uikit/src/components/Link/LinkExternal.tsx
  packages/uikit/src/components/Link/types.ts
Labels: size/M

#6092 chore: mm linked pool fetch mechanism adjustment
  apps/web/.env
  apps/web/src/components/CurrencyInputPanel/index.tsx
  apps/web/src/components/Svg/RefreshIcon.tsx
  apps/web/src/config/constants/lists.ts
  apps/web/src/views/Swap/MMLinkPools/apis/index.ts
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButton.tsx
  apps/web/src/views/Swap/MMLinkPools/hooks/index.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useGetRFQTrade.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMOrderBookTrade.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMParam.ts
  apps/web/src/views/Swap/SmartSwap/index.tsx
  apps/web/src/views/Swap/index.tsx
Labels: size/L

#6096 feat: Sync miniprogram connecting status
  apps/web/src/components/Navbar.bmp.tsx
  apps/web/src/utils/mpBridge.ts
Labels: size/S

#6100 feat(Blog): Get locales data from API
  apps/blog/components/Article/AllArticle/index.tsx
  apps/blog/hooks/useLanguage.ts
  apps/blog/pages/api/locales.tsx
Labels: size/M, automerge

#6106 fix: (aptos): Staking limit row visible after it is over
  apps/aptos/components/Pools/transformers/transformPool.ts
Labels: size/XS

#6093 fix: Duplicate liquidity pairs
  apps/web/src/state/user/hooks/index.tsx
  apps/web/src/views/PoolFinder/index.tsx
Labels: size/XS

#6107 revert: "chore: Remove gas price on Ethereum (#6091)"
  apps/web/src/state/user/hooks/index.tsx
  apps/web/src/views/Swap/MMLinkPools/hooks/useSwapCallback.ts
Labels: size/S

#6103 feat(web): Better MM error message
  apps/web/src/views/Swap/MMLinkPools/apis/index.ts
  apps/web/src/views/Swap/MMLinkPools/components/MMAndAMMDealDisplay.tsx
  apps/web/src/views/Swap/MMLinkPools/hooks/useGetRFQTrade.ts
  apps/web/src/views/Swap/SmartSwap/index.tsx
Labels: size/L

#6099 chore: Move gif to asset url
  packages/uikit/src/components/Spinner/Spinner.tsx
Labels: size/XS

#6098 fix(web): Move all wallets installed as getter
  apps/web/src/config/wallet.ts
Labels: size/M

#6113 fix: Incorrect slippage when stable token is not 18 decimals
  packages/smart-router/evm/stableSwap/getLPOutput.ts
Labels: size/S

#6112 chore(aptos): Add explorer icon
  apps/aptos/components/Menu/WalletInfo.tsx
  apps/aptos/components/SearchModal/ImportToken.tsx
  apps/aptos/components/Toast/DescriptionWithTx.tsx
  apps/aptos/components/TransactionConfirmationModal/index.tsx
Labels: size/S

#6116 feat: Add axlUSDC pool
  apps/web/src/config/constants/pools.tsx
Labels: size/S, automerge

#6119 chore: update token list storage key
  apps/web/src/state/lists/lists.ts
Labels: size/XS

#6114 feat: Trust wallet campaign banner
  apps/web/src/views/Home/components/Banners/AptosBanner.tsx
  apps/web/src/views/Home/components/Banners/MultipleBanner.tsx
  apps/web/src/views/Home/components/Banners/Styled.tsx
  apps/web/src/views/Home/components/Banners/TrustWalletCampaignBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  apps/web/src/views/Home/components/Banners/images/index.ts
  apps/web/src/views/Home/components/Banners/images/trustwalletBg.png
  apps/web/src/views/Home/components/Banners/images/trustwalletBunny.png
  packages/localization/src/config/translations.json
Labels: size/L

#6118 fix: Allow multihop pure stable swaps
  apps/web/src/config/constants/exchange.ts
  packages/smart-router/evm/constants/exchange.ts
  packages/smart-router/evm/getBestTrade.ts
  packages/smart-router/evm/getBestTradeFromStablePools.ts
Labels: size/L

#6122 fix(web): Temp fix for alxusdc pool apr
  apps/web/src/state/pools/index.ts
Labels: size/XS, automerge

#6124 fix: Eth gas price undefined
  apps/web/src/state/user/hooks/index.tsx
Labels: size/XS, automerge

#6125 fix: Unstake nonbsc undefined
  apps/web/src/views/Farms/hooks/useStakeFarms.ts
  apps/web/src/views/Farms/hooks/useUnstakeFarms.ts
Labels: size/XS

#6117 chore(blog): Replace image url
  apps/blog/.env.example
  apps/blog/pages/api/articles.tsx
  apps/blog/types.ts
  apps/blog/utils/transformArticle.ts
Labels: size/M

#6128 feat: Campaign tooltip shows automatically every-time on page loaded
  apps/web/src/views/Swap/components/CurrencyInputHeader.tsx
Labels: size/M

#6129 fix: (farms): Axlusdc farm lp token price and pool apr
  apps/web/src/state/pools/hooks.ts
  apps/web/src/state/pools/index.ts
  packages/farms/src/fetchFarms.ts
Labels: size/S

#6115 fix(web): Update stableswap subgraph
  apps/web/src/state/info/queries/protocol/overview.ts
Labels: size/M

#6121 chore(Farms): Modify links placement on mobile
  apps/aptos/components/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/Farms/components/FarmTable/Row.tsx
  packages/uikit/src/widgets/Farm/components/FarmCard/DetailsSection.tsx
Labels: size/M

#6090 perf: Use ref to reduce renders in modal
  packages/uikit/src/widgets/Modal/useModal.ts
Labels: size/XS

#6073 feat(Tooltip): Use click to show on mobile
  apps/web/src/views/Swap/components/AccessRisk/index.tsx
  packages/uikit/src/hooks/useTooltip/useTooltip.tsx
Labels: size/S

#6120 chore: timer for TrustWallet banner
  apps/web/src/views/Home/components/Banners/hooks/useIsRenderTrustWalletCampaignBanner.ts
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/S

#6136 fix: LP fee not accurate with axlUSDC
  packages/farms/constants/56.ts
  packages/smart-router/evm/constants/stableSwap/56.ts
  packages/smart-router/evm/onchain/getStableSwapFee.ts
Labels: size/XS

#6135 feat(blog): add next image
  apps/blog/components/Article/CardArticle.tsx
  apps/blog/components/Article/SingleArticle/ArticleInfo.tsx
  apps/blog/components/Article/SingleArticle/SimilarArticles.tsx
  apps/blog/components/BlogCard.tsx
  apps/blog/components/ChefsChoice/index.tsx
  apps/blog/components/NewBlog.tsx
  apps/blog/hooks/getArticle.ts
  apps/blog/next.config.mjs
  apps/blog/types.ts
  apps/blog/utils/transformArticle.ts
Labels: size/M

#6137 fix(web): stableswap chart
  apps/web/src/state/swap/fetch/fetchDerivedPriceData.ts
  apps/web/src/state/swap/fetch/fetchPairPriceData.ts
  apps/web/src/state/swap/fetch/types.ts
  apps/web/src/state/swap/hooks.ts
  apps/web/src/state/swap/normalizers.ts
  apps/web/src/state/swap/queries/getDerivedPrices.ts
  apps/web/src/state/swap/queries/pairDayDatas.ts
  apps/web/src/state/swap/queries/pairDayDatasByIdsQuery.ts
  apps/web/src/state/swap/queries/pairHourDatas.ts
  apps/web/src/state/swap/queries/pairHourDatasByIds.ts
  apps/web/src/state/swap/types.ts
  apps/web/src/state/swap/useStableSwapPairs.ts
  apps/web/src/views/Swap/components/Chart/PriceChart.tsx
  packages/aptos-swap-sdk/package.json
  packages/awgmi/package.json
  packages/localization/src/config/translations.json
  packages/multicall/package.json
  packages/smart-router/evm/constants/stableSwap/index.ts
  packages/smart-router/evm/constants/stableSwap/pools.ts
  packages/smart-router/evm/getStableSwapPairs.ts
  packages/smart-router/package.json
  packages/swap-sdk-core/package.json
  packages/swap-sdk/package.json
  packages/token-lists/package.json
  packages/wagmi/package.json
  packages/wagmi/src/hooks/useSignMessage.ts
  yarn.lock
Labels: size/XL

#6138 chore(Farms): LP names should not be forced to uppercase
  apps/web/src/views/Farms/components/FarmCard/FarmCard.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/Farms/components/FarmTable/FarmTable.tsx
  apps/web/src/views/Migration/components/MigrationFarmTable.tsx
  apps/web/src/views/Migration/components/MigrationStep2/NewFarm/FarmRow.tsx
Labels: size/S

#6139 fix: (aptos): Locate assets link still visible on not enough token modal
  apps/aptos/components/Pools/components/PoolTable/ActionPanel.tsx
  packages/uikit/src/widgets/Pool/withCardActions.tsx
Labels: size/XS

#6140 feat: raise the MM linked expiry limit to 25
  apps/web/src/views/Swap/MMLinkPools/constants.ts
Labels: size/XS

#6133 feat(web/nft): Support walletOfOwner
  apps/web/src/config/constants/nftsCollections/index.ts
  apps/web/src/state/nftMarket/helpers.ts
  apps/web/src/views/Nft/market/components/BannerHeader/index.tsx
Labels: size/M

#6143 chore(Blog): Update wording
  apps/blog/components/ChefsChoice/index.tsx
  apps/web/src/__tests__/translations.test.ts
  packages/localization/src/config/translations.json
Labels: size/XS, automerge

#6146 feat(farm/pool): List CSIX
  apps/web/public/images/tokens/0x04756126F044634C9a0f0E985e60c88a51ACC206.png
  apps/web/src/config/constants/pools.tsx
  packages/farms/constants/56.ts
  packages/tokens/src/56.ts
Labels: size/S

#6105 style: Fix footer SocialLinks
  packages/uikit/src/components/Footer/Components/SocialLinks.tsx
Labels: size/M, automerge

#6145 fix: Swap token table trade select same token with un-checksummed address
  apps/web/src/views/Swap/components/HotTokenList/SwapTokenTable.tsx
Labels: size/S

#6167 fix: Image url issue
  apps/web/next.config.mjs
Labels: size/S

#6158 chore: Bump up swr
  apps/web/package.json
  packages/wagmi/package.json
  yarn.lock
Labels: size/S

#6168 revert: "feat(blog): add next image"
  apps/blog/components/Article/CardArticle.tsx
  apps/blog/components/Article/SingleArticle/ArticleInfo.tsx
  apps/blog/components/Article/SingleArticle/SimilarArticles.tsx
  apps/blog/components/BlogCard.tsx
  apps/blog/components/ChefsChoice/index.tsx
  apps/blog/components/NewBlog.tsx
  apps/blog/hooks/getArticle.ts
  apps/blog/next.config.mjs
  apps/blog/types.ts
  apps/blog/utils/transformArticle.ts
Labels: size/M

#6166 refactor(CurrencyInputPanel): Rename "ShowBUSD" to "ShowUSDPrice"
  apps/web/src/components/CurrencyInputPanel/index.tsx
  apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
  apps/web/src/views/AddLiquidity/index.tsx
  apps/web/src/views/Swap/SmartSwap/index.tsx
  apps/web/src/views/Swap/components/SwapForm.tsx
Labels: size/S

#6127 feat(Pools): When two EndsBlock are the same, only one is displayed
  apps/aptos/components/Pools/components/PoolCard/PoolStatsInfo.tsx
  apps/web/src/views/Pools/components/MaxStakeRow.tsx
  apps/web/src/views/Pools/components/PoolStatsInfo.tsx
Labels: size/M

#6151 chore(Wallet): No show "Welcome!"
  apps/aptos/components/Menu/WalletModal.tsx
  apps/web/src/components/Menu/UserMenu/WalletModal.tsx
Labels: size/XS

#6156 fix(Footer): Fix Token is sometimes displayed incorrectly
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/components/Svg/Icons/LogoRound.tsx
Labels: size/XS

#6154 chore: Unified tag with outline style
  packages/uikit/src/widgets/Farm/components/Tags/index.tsx
Labels: size/M

#6152 chore(TrustWalletBanner): Add button icon
  apps/web/src/views/Home/components/Banners/TrustWalletCampaignBanner.tsx
Labels: size/S

#6176 revert: "chore(blog): Replace image url"
  apps/blog/.env.example
  apps/blog/pages/api/articles.tsx
  apps/blog/types.ts
  apps/blog/utils/transformArticle.ts
Labels: size/M

#6101 feat: support ETH native token for mm linked pools
  apps/web/src/views/Swap/MMLinkPools/apis/index.ts
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButton.tsx
  apps/web/src/views/Swap/MMLinkPools/constants.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useGetRFQTrade.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useIsMMQuotingPair.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMOrderBookTrade.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMParam.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useSwapCallArguments.ts
  apps/web/src/views/Swap/MMLinkPools/utils/exchange.ts
  apps/web/src/views/Swap/SmartSwap/index.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#6177 feat(Aptos): List tAPT-whUSDC LP
  apps/aptos/config/constants/farms/1.ts
  apps/aptos/config/constants/tokens/1.ts
Labels: size/S, automerge

#6172 perf: Don't calculate busd currency amount when there is no amount
  apps/web/src/hooks/useBUSDPrice.ts
Labels: size/S

#6175 fix(TrustWalletBanner): Fix "Trade Now" icon color
  apps/web/src/views/Home/components/Banners/TrustWalletCampaignBanner.tsx
Labels: size/XS

#6179 fix(aptos-Farms): Fix getLP placement
  apps/aptos/components/Farms/components/FarmTable/Row.tsx
Labels: size/XS, automerge

#6180 fix(aptos-exploreLink): Remove extra "/"
  apps/aptos/utils/index.ts
Labels: size/XS

#6153 chore(Farms): Change tag placement of frams
  apps/web/src/views/Farms/components/FarmCard/CardHeading.tsx
  apps/web/src/views/Farms/components/FarmTable/Farm.tsx
  apps/web/src/views/Farms/components/FarmTable/FarmTable.tsx
  apps/web/src/views/Farms/components/FarmTable/Row.tsx
  packages/uikit/src/widgets/Farm/components/FarmTable/FarmTokenInfo.tsx
  packages/uikit/src/widgets/Farm/components/Tags/index.tsx
  packages/uikit/src/widgets/Farm/types.ts
Labels: size/M

#6164 chore(aptos-IFO): "View IFO" of Token Vesting should appear only when IFO is not Active
  apps/aptos/config/constants/ifo.ts
  apps/aptos/config/constants/index.ts
  apps/aptos/views/Ifos/components/IfoVesting/VestingPeriod/Expand.tsx
Labels: size/S

#6162 feat(Limit): Show USD price
  apps/web/src/views/LimitOrders/index.tsx
Labels: size/XS

#6155 fix(Farms): Fix stableLP & Farm Auction tootip placement on mobile
  packages/uikit/src/widgets/Farm/components/Tags/index.tsx
Labels: size/XS

#6160 perf: Dont call custom resolver for isaddress memoize
  apps/web/src/utils/index.ts
Labels: size/S

#6148 perf: Call get chain only when initializing the state
  apps/web/src/state/info/hooks.ts
Labels: size/XS

#6183 fix(web/info): Stableswap axlusdc volume
  apps/web/src/state/info/queries/tokens/topTokens.ts
  apps/web/src/views/LimitOrders/index.tsx
Labels: size/M

#6184 fix(web/info): Stableswap token url and refetch loading
  apps/web/src/state/info/hooks.ts
  apps/web/src/views/Info/Pools/PoolPage.tsx
Labels: size/XS

#6186 feat(multicall): Integrate with abitype
  apps/web/src/utils/multicall.ts
  packages/multicall/index.ts
  packages/utils/abitype.ts
Labels: size/XL

#6189 feat(aptos-IFO): Add CAKE commit info when finished
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoVestingCard/TotalPurchased.tsx
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoVestingCard/index.tsx
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/index.tsx
Labels: size/L

#6147 perf: Use memoize to reduce rerenders for info
  apps/web/src/state/info/hooks.ts
  apps/web/src/state/user/hooks/index.tsx
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/Info/Tokens/TokenPage.tsx
Labels: size/M

#6188 fix(Swap&Limit): Fix broken page on tablet
  apps/web/src/views/LimitOrders/index.tsx
  apps/web/src/views/LimitOrders/styles.tsx
  apps/web/src/views/Swap/components/Chart/BasicChart.tsx
  apps/web/src/views/Swap/index.tsx
  packages/uikit/src/components/BottomDrawer/BottomDrawer.tsx
Labels: size/S

#6165 feat(aptos-Swap&Liquidity): Add token USD price
  apps/aptos/components/CurrencyInputPanel/index.tsx
  apps/aptos/components/Liquidity/components/AddLiquidityForm.tsx
  apps/aptos/pages/swap.tsx
Labels: size/M

#6195 feat(Vote): Add admin
  apps/web/src/views/Voting/config.ts
Labels: size/XS, automerge

#6208 chore: Move finished pools
  apps/web/src/config/constants/pools.tsx
Labels: size/M

#6204 perf: Memoize truncate hash function
  packages/utils/truncateHash.ts
Labels: size/S
