Repository pancakeswap/pancake-frontend, pull requests merged in 2023-07, with the labels that each got.

#7258 chore: New farm
  .github/workflows/testConfig.yml
  .github/workflows/testConfigPass.yml
  packages/farms/constants/1.ts
  packages/tokens/src/1.ts
Labels: size/S

#7254 fix: Faqs detail button not aligned to the right
  apps/web/src/components/FoldableSection/FoldableText.tsx
  packages/uikit/src/components/Button/ExpandableButton.tsx
Labels: size/S

#7246 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XXL

#7259 chore: New Crowdin updates
  locales/es-ES.json
Labels: size/S

#7260 chore: Move finished pools
  packages/pools/src/constants/pools/56.ts
Labels: size/S

#7262 chore: New Crowdin updates
  locales/ar-SA.json
  locales/de-DE.json
  locales/el-GR.json
  locales/es-ES.json
  locales/fr-FR.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/ta-IN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XXL

#7269 feat(Trading Reward): Add Anchor
  apps/web/src/views/TradingReward/components/Leaderboard/index.tsx
Labels: size/XS, automerge

#7268 feat: List xALGO
  packages/farms/constants/56.ts
  packages/pools/src/constants/pools/56.ts
  packages/tokens/src/56.ts
Labels: size/S, automerge

#7248 fix: Swap chart shows wrong price difference when hover
  apps/web/src/views/Swap/components/Chart/BasicChart.tsx
  apps/web/src/views/Swap/components/Chart/utils.ts
Labels: size/M

#7272 chore: New Crowdin updates
  locales/el-GR.json
  locales/ru-RU.json
  locales/vi-VN.json
  locales/zh-TW.json
Labels: size/XL

#7271 feat: add wallet connect v2 id to ledger
  apps/web/src/utils/wagmi.ts
Labels: size/XS

#7270 fix: Disclaimers can't be dismissed when going back
  apps/web/src/views/LimitOrders/components/ClaimWarning.tsx
  apps/web/src/views/Predictions/components/RiskDisclaimer.tsx
  packages/uikit/src/widgets/Modal/ModalContext.tsx
Labels: size/S

#7274 fix: Incorrect token symbol
  .github/workflows/testConfig.yml
  .github/workflows/testConfigPass.yml
  apps/web/src/config/__tests__/tokens.test.ts
  packages/tokens/src/1.ts
  packages/tokens/src/56.ts
Labels: size/S

#7167 chore: Bump up jotai
  .changeset/wise-mangos-do.md
  apps/aptos/package.json
  apps/web/package.json
  packages/token-lists/package.json
  packages/token-lists/react/lists.ts
  packages/ui-wallets/package.json
  packages/utils/package.json
  pnpm-lock.yaml
Labels: size/M

#7276 chore: Add polygon zkevm node
  apps/web/src/config/nodes.ts
Labels: size/S

#7279 fix: Hovered price can't be removed after mouse leaving
  apps/web/src/views/Swap/components/Chart/BasicChart.tsx
Labels: size/XS

#7280 perf: Use spread operator to copy arrays
  apps/aptos/state/lists/hooks.ts
  apps/web/src/state/lists/hooks.ts
  apps/web/src/views/Info/components/InfoTables/TransactionsTable.tsx
  apps/web/src/views/V3Info/components/TransactionsTable/index.tsx
Labels: size/S

#7277 chore: New Crowdin updates
  locales/fil-PH.json
  locales/hi-IN.json
  locales/id-ID.json
  locales/pt-BR.json
  locales/ro-RO.json
  locales/sv-SE.json
  locales/tr-TR.json
  locales/vi-VN.json
Labels: size/XXL

#7283 fix: Token list page crash
  apps/web/src/views/Swap/components/HotTokenList/useList.tsx
Labels: size/XS

#7286 chore: Add subgraph api backup for supported chains
  apis/routing/src/constants.ts
Labels: size/S

#7284 feat(info): Add polygon zkevm info
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/state/info/constant.ts
  apps/web/src/state/info/hooks.ts
  apps/web/src/state/info/queries/tokens/tokenData.ts
  apps/web/src/state/info/queries/tokens/topTokens.ts
  apps/web/src/utils/getTokenLogoURL.ts
  apps/web/src/utils/graphql.ts
  apps/web/src/views/Info/components/CurrencyLogo/index.tsx
  apps/web/src/views/Info/components/InfoNav/index.tsx
  apps/web/src/views/Info/components/InfoTables/TransactionsTable.tsx
  apps/web/src/views/Info/hooks/useBlocksFromTimestamps.ts
  apps/web/src/views/V3Info/components/Layout/InfoNav.tsx
  apps/web/src/views/V3Info/components/TransactionsTable/index.tsx
  apps/web/src/views/V3Info/constants.ts
  apps/web/src/views/V3Info/utils/index.ts
Labels: size/L

#7261 fix(TokenHighlight): Responsive mode is broken
  apps/web/src/views/Swap/components/HotTokenList/SwapTokenTable.tsx
Labels: size/L

#7278 feat: Add invert price button to farm v3 staked cards
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/PoolListItem.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3StakeAndUnStake.tsx
Labels: size/M

#7287 chore: Improve polygon quoting speed
  packages/smart-router/evm/v3-router/constants/index.ts
  packages/smart-router/evm/v3-router/constants/routeConfig.ts
  packages/smart-router/evm/v3-router/getBestTrade.ts
  packages/smart-router/evm/v3-router/types/trade.ts
Labels: size/M

#7288 chore: New Crowdin updates
  locales/id-ID.json
Labels: size/S

#7295 fix: Polygon quoting issue
  packages/smart-router/evm/constants/multicall.ts
Labels: size/XS

#7297 chore: Update polygon zkevm rpc node
  apps/web/src/config/nodes.ts
Labels: size/S

#7298 chore: Remove quicknode rpc endpoint
  apps/web/src/config/nodes.ts
Labels: size/XS

#7224 fix: nav submenu hover issue on mobile
  apps/web/src/views/BuyCrypto/components/FAQ.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/components/DropdownMenu/DropdownMenu.tsx
Labels: size/M

#7291 chore: New Crowdin updates
  locales/fil-PH.json
  locales/id-ID.json
  locales/ja-JP.json
  locales/uk-UA.json
Labels: size/XXL

#7300 feat: Add METIS warning
  apps/web/src/config/constants/swapWarningTokens.ts
  apps/web/src/views/Swap/components/SwapWarningModal/METISWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/index.tsx
  packages/localization/src/config/translations.json
Labels: size/M, automerge

#7299 refactor: On chain quoting
  packages/smart-router/evm/constants/multicall.ts
  packages/smart-router/evm/v3-router/providers/onChainQuoteProvider.ts
Labels: size/L

#7303 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#7305 fix: Cannot go back on prediction card on ios
  apps/web/src/views/Predictions/components/CardFlip.tsx
Labels: size/XS

#7177 feat: support multiple MM for mm linked pool
  apps/web/src/views/Swap/MMLinkPools/constants.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useSwapCallArguments.ts
Labels: size/XS

#7306 fix: Wrong v2 token order on pair detail page causes incorrect balance displayed
  apps/web/src/pages/liquidity/index.tsx
  apps/web/src/pages/v2/pair/[[...currency]].tsx
  apps/web/src/views/PoolFinder/index.tsx
Labels: size/M

#7311 chore: Fix lockfile issue
  pnpm-lock.yaml
Labels: size/XL

#7312 chore: Update domain for proxy worker
  apis/farms/src/lpApr.ts
  apps/web/src/config/constants/endpoints.ts
Labels: size/XS

#7266 fix: tooltip refactor for buyCrypto entry
  apps/web/src/components/Menu/UserMenu/WalletInfo.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/hooks/useTooltip/types.ts
  packages/uikit/src/hooks/useTooltip/useTooltip.tsx
Labels: size/L

#7314 chore(Farm): Only show booster msg on booster farms
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3Card.tsx
Labels: size/XS

#7313 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/S

#7265 fix: quote sorting and css issues
  apps/web/public/AUD.svg
  apps/web/public/BRL.svg
  apps/web/public/CAD.svg
  apps/web/public/EUR.svg
  apps/web/public/GBP.svg
  apps/web/public/HKD.svg
  apps/web/public/IDR.svg
  apps/web/public/JPY.svg
  apps/web/public/KRW.svg
  apps/web/public/SGD.svg
  apps/web/public/TWD.svg
  apps/web/public/USD.svg
  apps/web/public/VND.svg
  apps/web/public/images/currencies/aud.png
  apps/web/public/images/currencies/brl.png
  apps/web/public/images/currencies/cad.png
  apps/web/public/images/currencies/eur.png
  apps/web/public/images/currencies/gbp.png
  apps/web/public/images/currencies/hkd.png
  apps/web/public/images/currencies/jpy.png
  apps/web/public/images/currencies/krw.png
  apps/web/public/images/currencies/usd.png
  apps/web/public/images/currencies/vnd.png
  apps/web/public/images/on-ramp-providers/binanceConnectSvg.svg
  apps/web/public/images/on-ramp-providers/mercuryoLogo.svg
  apps/web/public/images/on-ramp-providers/mercuryo_new_logo_black.png
  apps/web/public/images/on-ramp-providers/mercuryo_new_logo_white.png
  apps/web/public/images/on-ramp-providers/moonpaySvg.svg
  apps/web/src/components/App/AppHeader.tsx
  apps/web/src/components/FiatOnRampModal/FiatOnRampModal.tsx
  apps/web/src/components/Logo/CurrencyLogo.tsx
  apps/web/src/components/SearchModal/CurrencySearch.tsx
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/hooks/Tokens.ts
  apps/web/src/hooks/useCheckAvailability.ts
  apps/web/src/views/BuyCrypto/Icons/Icons.tsx
  apps/web/src/views/BuyCrypto/components/AccordianDropdown/Accordian.tsx
  apps/web/src/views/BuyCrypto/components/AccordianDropdown/AccordianItem.tsx
  apps/web/src/views/BuyCrypto/components/AssetSelect.tsx
  apps/web/src/views/BuyCrypto/components/GetQuotesButton.tsx
  apps/web/src/views/BuyCrypto/components/NewIcon.tsx
  apps/web/src/views/BuyCrypto/components/OnRampCurrencySelect/index.tsx
  apps/web/src/views/BuyCrypto/components/OnRampProviderLogo/OnRampProviderLogo.tsx
  apps/web/src/views/BuyCrypto/components/styled.tsx
  apps/web/src/views/BuyCrypto/constants.ts
  apps/web/src/views/BuyCrypto/containers/BuyCryptoForm.tsx
  apps/web/src/views/BuyCrypto/containers/CryptoQuoteForm.tsx
  apps/web/src/views/BuyCrypto/containers/FormContainer.tsx
  apps/web/src/views/BuyCrypto/containers/FormHeader.tsx
  apps/web/src/views/BuyCrypto/hooks/usePriceQuoter.ts
  apps/web/src/views/BuyCrypto/hooks/useProviderAvailability.ts
  apps/web/src/views/BuyCrypto/hooks/useProviderQuotes.ts
  apps/web/src/views/BuyCrypto/index.tsx
  apps/web/src/views/BuyCrypto/styles.tsx
  apps/web/src/views/BuyCrypto/types.ts
  packages/localization/src/config/translations.json
  packages/uikit/src/components/Skeleton/Skeleton.tsx
  packages/uikit/src/components/Skeleton/types.ts
Labels: size/XXL

#7304 chore: Bump up swiper to 10
  apps/aptos/package.json
  apps/blog/components/Article/SingleArticle/SimilarArticles.tsx
  apps/blog/components/ChefsChoice/index.tsx
  apps/blog/package.json
  apps/web/package.json
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/StepIntro.tsx
  apps/web/src/views/Home/components/Banners/MultipleBanner.tsx
  apps/web/src/views/Predictions/Positions.tsx
  packages/ui-wallets/src/components/Intro.tsx
  pnpm-lock.yaml
Labels: size/M

#7309 chore: Move Finished ETH Pool
  packages/pools/src/constants/pools/1.ts
Labels: size/M, automerge

#7320 feat: List axlUSDC-USDT farm
  packages/farms/constants/56.ts
Labels: size/XS, automerge

#7296 feat: New trading reward UI
  apps/web/src/views/TradingReward/components/Leaderboard/DesktopResult.tsx
  apps/web/src/views/TradingReward/components/Leaderboard/DesktopView.tsx
  apps/web/src/views/TradingReward/components/Leaderboard/MobileResult.tsx
  apps/web/src/views/TradingReward/components/Leaderboard/MobileView.tsx
  apps/web/src/views/TradingReward/components/Leaderboard/MyRank.tsx
  apps/web/src/views/TradingReward/components/Leaderboard/RankingCard.tsx
  apps/web/src/views/TradingReward/components/Leaderboard/index.tsx
  apps/web/src/views/TradingReward/components/RewardsBreakdown/DesktopView.tsx
  apps/web/src/views/TradingReward/components/RewardsBreakdown/MobileView.tsx
  apps/web/src/views/TradingReward/components/RewardsBreakdown/index.tsx
  apps/web/src/views/TradingReward/components/TopTraders/YourTradingReward/CurrentPeriod.tsx
  apps/web/src/views/TradingReward/hooks/useRankList.tsx
  apps/web/src/views/TradingReward/hooks/useUserTradeRank.tsx
  apps/web/src/views/TradingReward/index.tsx
  apps/web/src/views/TradingReward/top-traders.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#7324 chore: MM linked pool doc adjustment
  apps/web/src/views/Swap/MMLinkPools/components/SwapModalFooter.tsx
  apps/web/src/views/Swap/components/AdvancedSwapDetails.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#7326 chore: Move cake price to rpc call
  apps/web/src/hooks/useBUSDPrice.ts
  apps/web/src/hooks/useCakePriceAsBN.ts
  apps/web/src/state/farms/hooks.ts
  apps/web/src/state/farmsV3/hooks.ts
  apps/web/src/state/pools/index.ts
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3ApyButton.tsx
  apps/web/src/views/Migration/components/v3/Step1.tsx
  packages/farms/src/fetchFarmsV3.ts
  packages/utils/useCakePrice.ts
Labels: size/M

#7327 fix: farm cake price oracle chain id
  packages/farms/src/fetchFarmsV3.ts
Labels: size/XS

#7325 fix: estimate gas by passing gas price for AA
  apps/web/src/hooks/useCallWithGasPrice.ts
Labels: size/S

#7330 perf: Memoize farm ui widgets
  packages/uikit/src/widgets/Farm/components/DepositModal/index.tsx
  packages/uikit/src/widgets/Farm/components/FarmApyButton/index.tsx
  packages/uikit/src/widgets/Farm/components/FarmTable/FarmTokenInfo.tsx
  packages/uikit/src/widgets/Farm/components/WithdrawModal/index.tsx
Labels: size/M

#7329 fix: Ifo disclaimer modal closed by overlay click
  apps/web/src/components/Menu/index.tsx
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/Congratulations.tsx
  apps/web/src/views/Home/components/Banners/PerpetualApolloXCampaignBanner.tsx
  apps/web/src/views/Home/components/Banners/PerpetualBanner.tsx
  apps/web/src/views/Ifos/index.tsx
Labels: size/S

#7334 fix: Not able to route through v2 if v3 pools available while no vali…
  packages/smart-router/evm/v3-router/providers/quoteProviders.ts
Labels: size/XS

#7331 feat(Bridge): Update Stargate UI
  apps/bridge/components/stargate/config.ts
  apps/bridge/components/stargate/index.tsx
Labels: size/XS

#7342 feat: Introduce use scroll to hash hook
  apps/web/src/hooks/useActiveWeb3React.ts
  apps/web/src/hooks/useScrollToHash.ts
  apps/web/src/utils/getHashFromRouter.ts
  apps/web/src/views/TradingReward/top-traders.tsx
Labels: size/M

#7336 feat: zk testnet farms
  apis/farms/src/provider.ts
  apis/farms/src/v3.ts
  apps/web/src/config/chains.ts
  apps/web/src/config/constants/contracts.ts
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/config/constants/supportChains.ts
  apps/web/src/config/constants/tokenLists/pancake-default.tokenlist.json
  apps/web/src/config/nodes.ts
  apps/web/src/state/farmsV3/hooks.ts
  apps/web/src/views/Farms/FarmsV3.tsx
  apps/web/src/views/Farms/components/YieldBooster/hooks/bCakeV3/useBCakeV3Info.ts
  apps/web/src/views/TradingReward/config/pairs/index.tsx
  packages/farms/constants/1442.ts
  packages/farms/constants/280.ts
  packages/farms/constants/common/index.ts
  packages/farms/constants/index.ts
  packages/farms/constants/v3/index.ts
  packages/farms/src/const.ts
  packages/farms/src/fetchFarmsV3.ts
  packages/farms/src/index.ts
  packages/farms/src/v2/fetchFarmsV2.ts
  packages/smart-router/evm/constants/exchange.ts
  packages/smart-router/evm/constants/multicall.ts
  packages/smart-router/evm/constants/v3.ts
  packages/smart-router/evm/v3-router/providers/multicallSwapProvider.ts
  packages/smart-router/evm/v3-router/providers/onChainQuoteProvider.ts
  packages/swap-sdk/src/constants.ts
  packages/swap-sdk/src/entities/pair.ts
  packages/swap-sdk/test/pair.test.ts
  packages/tokens/src/1442.ts
  packages/tokens/src/280.ts
  packages/uikit/src/components/CurrencyLogo/utils.ts
  packages/v3-sdk/src/constants.ts
  packages/v3-sdk/src/utils/computePoolAddress.test.ts
  packages/v3-sdk/src/utils/computePoolAddress.ts
Labels: size/L

#7345 fix: Scroll to hash
  apps/web/src/hooks/useScrollToHash.ts
Labels: size/S

#7352 feat: Add Vote Admin
  apps/web/src/views/Voting/config.ts
Labels: size/XS, automerge

#7337 fix: Redirect problem
  apps/web/src/hooks/useScrollToHash.ts
  apps/web/src/views/TradingReward/components/RewardsBreakdown/MobileView.tsx
  apps/web/src/views/TradingReward/index.tsx
  apps/web/src/views/TradingReward/top-traders.tsx
Labels: size/S, automerge

#7355 chore: Bump pkg
  .changeset/lovely-starfishes-build.md
Labels: size/XS

#7350 chore: fix hot token list table style
  apps/web/src/views/Info/components/InfoTables/shared.tsx
Labels: size/XS

#7346 chore: bCake v3 UI QA details
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3ApyButton.tsx
  packages/uikit/src/components/Skeleton/types.ts
Labels: size/XS

#7357 fix: Scroll to hash id
  apps/web/src/hooks/useScrollToHash.ts
Labels: size/S

#7292 fix: (info): Transactions shows bscscan logo on other chains
  apps/aptos/components/Menu/WalletInfo.tsx
  apps/aptos/components/Pools/components/PoolCard/PoolStatsInfo.tsx
  apps/aptos/components/SearchModal/ImportToken.tsx
  apps/aptos/components/Toast/DescriptionWithTx.tsx
  apps/aptos/components/TransactionConfirmationModal/index.tsx
  apps/web/src/components/App/Transactions/Transaction.tsx
  apps/web/src/components/Menu/UserMenu/WalletInfo.tsx
  apps/web/src/components/TransactionDetailModal/FarmTransactionModal/FarmDetail.tsx
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/views/FarmAuction/components/AuctionLeaderboard/AuctionLeaderboardTable.tsx
  apps/web/src/views/Farms/components/FarmCard/FarmCard.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3Card.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/Info/Tokens/TokenPage.tsx
  apps/web/src/views/Info/components/InfoTables/TransactionsTable.tsx
  apps/web/src/views/Nft/market/components/BuySellModals/SellModal/EditStage.tsx
  apps/web/src/views/Nft/market/components/BuySellModals/SellModal/SellStage.tsx
  apps/web/src/views/Nft/market/components/BuySellModals/shared/TransactionConfirmed.tsx
  apps/web/src/views/Nft/market/components/ProfileNftModal.tsx
  apps/web/src/views/PancakeSquad/components/Modals/Confirm/index.tsx
  apps/web/src/views/Pools/components/PoolStatsInfo.tsx
  apps/web/src/views/Pottery/components/FinishedRounds/AllHistoryCard/PreviousRoundCardBody.tsx
  apps/web/src/views/Predictions/Leaderboard/components/WalletStatsModal.tsx
  apps/web/src/views/Predictions/components/History/BetResult.tsx
  apps/web/src/views/Profile/components/ProfileHeader.tsx
  apps/web/src/views/V3Info/components/TransactionsTable/index.tsx
  apps/web/src/views/V3Info/views/PoolPage.tsx
  apps/web/src/views/V3Info/views/TokenPage.tsx
  apps/web/src/views/Voting/CreateProposal/index.tsx
  apps/web/src/views/Voting/Proposal/Details.tsx
  apps/web/src/views/Voting/components/CastVoteModal/DetailsView.tsx
  apps/web/src/views/Voting/components/Proposal/VoteRow.tsx
  packages/uikit/src/components/Link/LinkExternal.tsx
  packages/uikit/src/components/Link/ScanLink.tsx
  packages/uikit/src/components/Link/index.tsx
  packages/uikit/src/components/Link/types.ts
  packages/uikit/src/widgets/Farm/components/FarmCard/DetailsSection.tsx
Labels: size/L

#7360 fix: Add missing translation to add liquidity
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/StepCounter.tsx
  packages/uikit/src/widgets/RoiCalculator/StepCounter.tsx
Labels: size/XS

#7363 fix: Module resolution error
  packages/uikit/src/widgets/Modal/NotEnoughTokensModal.tsx
Labels: size/XS

#7367 chore: Update TUSD-USDD route
  packages/smart-router/evm/constants/exchange.ts
  packages/smart-router/evm/v3-router/utils/getPoolSelectorConfig.ts
  packages/tokens/src/56.ts
Labels: size/S

#7372 chore: Eth v2 router address update
  packages/smart-router/evm/constants/exchange.ts
Labels: size/XS

#7339 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XL

#7377 chore: list PENDLE farm on eth
  packages/farms/constants/1.ts
  packages/tokens/src/1.ts
Labels: size/S

#7359 feat: Update Bridge
  apps/bridge/components/Menu.tsx
  apps/bridge/components/layerZero/LayerZeroWidget.tsx
  apps/bridge/components/layerZero/config.ts
  apps/bridge/components/layerZero/index.tsx
  apps/bridge/components/layerZero/theme.ts
  apps/bridge/components/stargate/config.ts
  apps/bridge/components/stargate/index.tsx
  apps/bridge/components/stargate/network.ts
  apps/bridge/components/stargate/theme.ts
  apps/bridge/next.config.mjs
  apps/bridge/pages/aptos.tsx
  apps/bridge/pages/index.tsx
  apps/bridge/pages/stargate.tsx
  package.json
Labels: size/XXL, automerge

#7376 chore: list eqb farm and pool
  packages/farms/constants/56.ts
  packages/pools/src/constants/pools/56.ts
  packages/tokens/src/56.ts
Labels: size/M

#7378 chore: New Crowdin updates
  locales/hi-IN.json
  locales/ru-RU.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/M

#7383 chore: fix mp wallet connect
  apps/web/src/components/ConnectWalletButton.tsx
Labels: size/XS

#7364 feat: Add IFO key word
  apps/web/src/components/DisclaimerModal/index.tsx
  apps/web/src/components/Modal/USCitizenConfirmModal.tsx
  apps/web/src/views/Ifos/index.tsx
  packages/localization/src/config/translations.json
Labels: size/M, automerge

#7386 feat: Show zkEVM in info page
  apps/web/src/state/info/constant.ts
  apps/web/src/views/Info/components/InfoNav/index.tsx
  apps/web/src/views/V3Info/components/Layout/InfoNav.tsx
Labels: size/S, automerge

#7392 chore: List Sable Cifo
  apps/web/public/images/achievements/ifo-sable.svg
  apps/web/public/images/ifos/sable-bg.png
  apps/web/src/config/constants/campaigns.ts
  apps/web/src/config/constants/ifo.ts
  packages/tokens/src/56.ts
Labels: size/M, automerge

#7391 fix: Cycle import in bunny known placeholder
  packages/uikit/src/components/BunnyKnownPlaceholder/BunnyKnownPlaceholder.tsx
Labels: size/XS

#7399 chore: list new BSC farms
  packages/farms/constants/56.ts
Labels: size/M, automerge

#7400 feat(IFO): Update Stable IFO desc
  apps/web/src/config/constants/ifo.ts
Labels: size/XS

#7114 feat: Blog add blog localStorage
  apps/blog/components/Article/AllArticle/index.tsx
  apps/blog/utils/getLanguageCodeFromLS.ts
  apps/blog/utils/getLocalStorageLanguageCode.ts
Labels: size/M, automerge

#7409 feat: Add fallback configuration to v3 candidate pools
  .changeset/silver-camels-pay.md
  packages/smart-router/evm/utils/withFallback.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/getV3CandidatePools.ts
Labels: size/M

#7405 chore: Bump up swiper
  apps/aptos/package.json
  apps/blog/package.json
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/S

#7411 chore: Bump tokens version
  .changeset/tidy-flies-drum.md
Labels: size/XS

#7402 feat: Filter News tag
  apps/blog/hooks/getArticle.ts
  apps/blog/pages/index.tsx
  apps/blog/types.ts
  apps/blog/utils/transformArticle.ts
Labels: size/S, automerge

#7413 chore: list WLD farm on eth
  packages/farms/constants/1.ts
  packages/tokens/src/1.ts
Labels: size/S

#7414 chore: list rpl pool on eth
  packages/pools/src/constants/pools/1.ts
Labels: size/XS

#7375 feat: Farms - Polygon Zkevm
  apis/farms/.dev.vars
  apis/farms/src/bindings.d.ts
  apis/farms/src/lpApr.ts
  apis/farms/src/provider.ts
  apis/farms/src/v3.ts
  apis/farms/wrangler.toml
  apis/routing/.dev.vars
  apps/web/src/components/SearchModal/ManageLists.tsx
  apps/web/src/components/TokenImage/index.tsx
  apps/web/src/config/__tests__/farms.test.ts
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/config/constants/lists.ts
  apps/web/src/config/constants/supportChains.ts
  apps/web/src/config/constants/tokenLists/pancake-default.tokenlist.json
  apps/web/src/state/farmsV3/hooks.ts
  apps/web/src/state/lists/hooks.ts
  apps/web/src/views/Home/components/Banners/PolygonZkEvmBanner.tsx
  apps/web/src/views/TradingReward/config/pairs/index.tsx
  packages/farms/constants/1101.ts
  packages/farms/constants/common/index.ts
  packages/farms/constants/v3/index.ts
  packages/farms/src/const.ts
  packages/localization/src/config/translations.json
  packages/smart-router/evm/constants/v3.ts
  packages/tokens/src/1101.ts
  packages/tokens/src/common.ts
Labels: size/L

#7418 chore: list SABLE farm & pool
  packages/farms/constants/56.ts
  packages/pools/src/constants/pools/56.ts
Labels: size/S

#7419 chore: fix zkevm token logo path
  packages/uikit/src/components/CurrencyLogo/utils.ts
Labels: size/XS

#7420 chore: check if v3 migration support on multichain
  apps/web/src/views/Farms/Farms.tsx
  apps/web/src/views/Farms/FarmsV3.tsx
Labels: size/M

#7384 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#7421 fix(wagmi): Remove trust wallet chain checking
  packages/wagmi/connectors/trustWallet/trustWallet.ts
Labels: size/S

#7422 chore: Temporary sort sable farm (need to be fixed)
  apps/web/src/views/Farms/FarmsV3.tsx
Labels: size/S

#7423 fix: Pool components contains different cake price
  apps/web/src/state/pools/hooks.ts
  apps/web/src/state/pools/index.ts
  apps/web/src/views/Pools/components/CakeVaultCard/VaultCardActions/HasSharesActions.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/VaultCardActions/VaultStakeActions.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/index.tsx
  apps/web/src/views/Pools/components/LockedPool/Buttons/AddCakeButton.tsx
  apps/web/src/views/Pools/components/LockedPool/Buttons/ExtendDurationButton.tsx
  apps/web/src/views/Pools/components/LockedPool/Common/AfterLockedActions.tsx
  apps/web/src/views/Pools/components/LockedPool/Common/ConvertToLock.tsx
  apps/web/src/views/Pools/components/LockedPool/Common/LockedActions.tsx
  apps/web/src/views/Pools/components/LockedPool/Common/LockedModalBody.tsx
  apps/web/src/views/Pools/components/LockedPool/LockedStakingApy.tsx
  apps/web/src/views/Pools/components/LockedPool/Modals/AddAmountModal.tsx
  apps/web/src/views/Pools/components/LockedPool/Modals/ExtendDurationModal.tsx
  apps/web/src/views/Pools/components/LockedPool/Modals/LockedStakeModal.tsx
  apps/web/src/views/Pools/components/LockedPool/hooks/useLockedPool.tsx
  apps/web/src/views/Pools/components/LockedPool/types/index.ts
  apps/web/src/views/Pools/components/OriginalLockedInfo.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
  apps/web/src/views/TradingReward/components/YourTradingReward/Actions.tsx
  apps/web/src/views/TradingReward/components/YourTradingReward/NoCakeLockedOrExtendLock.tsx
  apps/web/src/views/TradingReward/components/YourTradingReward/QualifiedPreview.tsx
Labels: size/L

#7426 fix: Decimal error in pool cake usd price
  apps/web/src/views/Pools/components/LockedPool/Common/BalanceField.tsx
  apps/web/src/views/Pools/components/LockedPool/Common/LockedModalBody.tsx
  apps/web/src/views/Pools/components/LockedPool/Modals/AddAmountModal.tsx
  apps/web/src/views/Pools/components/LockedPool/Modals/ExtendDurationModal.tsx
  apps/web/src/views/Pools/components/LockedPool/Modals/LockedStakeModal.tsx
  apps/web/src/views/Pools/components/LockedPool/hooks/useLockedPool.tsx
Labels: size/M

#7427 fix: Pool expected roi shows old value when it is smaller than 0.00
  apps/web/src/views/Pools/components/LockedPool/Common/Overview/BalanceRow.tsx
Labels: size/XS

#7403 feat: zksync
  .changeset/kind-bats-wash.md
  apps/web/src/config/chains.ts
  apps/web/src/config/constants/contracts.ts
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/state/swap/fetch/fetchDerivedPriceData.ts
  apps/web/src/utils/graphql.ts
  packages/smart-router/evm/constants/exchange.ts
  packages/smart-router/evm/constants/gasModel/index.ts
  packages/smart-router/evm/constants/v3.ts
  packages/smart-router/evm/v3-router/providers/multicallSwapProvider.ts
  packages/swap-sdk/src/constants.ts
  packages/tokens/src/324.ts
  packages/tokens/src/common.ts
  packages/v3-sdk/src/constants.ts
Labels: size/M

#7431 chore: add zksync banner
  apps/web/src/views/Home/components/Banners/ZksyncBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  apps/web/src/views/Home/components/Banners/images/eraLogo.png
  apps/web/src/views/Home/components/Banners/images/index.ts
  apps/web/src/views/Home/components/Banners/images/zkSyncBg.png
  apps/web/src/views/Home/components/Banners/images/zkSyncBgMobile.png
  apps/web/src/views/Home/components/Banners/images/zkSyncBunny.png
  packages/localization/src/config/translations.json
Labels: size/L

#7432 chore: Add zksync era support to routing api
  apis/routing/src/constants.ts
  apis/routing/src/provider.ts
Labels: size/S

#7434 chore: zksync banner adjustment
  apps/web/src/views/Home/components/Banners/ZksyncBanner.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#7437 chore: zksync v2 factory
  .changeset/bright-dolphins-fold.md
  packages/swap-sdk/src/constants.ts
  packages/swap-sdk/test/pair.test.ts
Labels: size/S

#7348 chore: Add nodereal zkevm
  apps/web/src/config/nodes.ts
  apps/web/src/utils/nodeReal.ts
Labels: size/S

#7428 feat: Add useShowOnceAirdropModal hook
  apps/web/src/components/GlobalCheckClaimStatus/V3AirdropModal.tsx
  apps/web/src/components/GlobalCheckClaimStatus/hooks/useAirdropModalStatus.tsx
  apps/web/src/components/GlobalCheckClaimStatus/index.tsx
  apps/web/src/components/Menu/UserMenu/ClaimYourNFT.tsx
  apps/web/src/components/Menu/UserMenu/index.tsx
  apps/web/src/hooks/useShowOnceAirdropModal.ts
  packages/localization/src/config/translations.json
Labels: size/L

#7439 chore: list bsc farms
  apps/web/src/config/__tests__/farms.test.ts
  apps/web/src/views/Farms/FarmsV3.tsx
  packages/farms/constants/56.ts
  packages/farms/tests/v3.test.ts
  packages/pools/src/constants/pools/56.ts
  packages/tokens/src/56.ts
Labels: size/M

#7433 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#7415 chore: Bump up jotai
  apps/aptos/package.json
  apps/web/package.json
  packages/token-lists/package.json
  packages/ui-wallets/package.json
  packages/utils/package.json
  pnpm-lock.yaml
Labels: size/M

#7440 chore: Lower multicall for zkevm
  apps/web/src/config/nodes.ts
  apps/web/src/utils/viem.ts
Labels: size/XS

#7442 feat: support zksync info
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/state/info/constant.ts
  apps/web/src/state/info/hooks.ts
  apps/web/src/utils/getTokenLogoURL.ts
  apps/web/src/utils/graphql.ts
  apps/web/src/views/Info/components/InfoNav/index.tsx
  apps/web/src/views/V3Info/components/Layout/InfoNav.tsx
  apps/web/src/views/V3Info/constants.ts
Labels: size/M

#7446 fix(ci): locales workflow env
  .github/workflows/deployLocales.yml
Labels: size/XS

#7443 chore: New Crowdin updates
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/M

#7447 fix(ci): locales workflow env with branch
  .github/workflows/deployLocales.yml
Labels: size/XS

#7449 chore: zkevm nodereal
  apps/web/src/config/nodes.ts
Labels: size/XS

#7450 chore: revert zkevm node order
  apps/web/src/config/nodes.ts
Labels: size/XS

#7455 chore: Update tradingRewardTopTrades contract
  apps/web/src/config/constants/contracts.ts
Labels: size/XS, automerge

#7457 chore: list planet farm and pool
  packages/farms/constants/56.ts
  packages/pools/src/constants/pools/56.ts
  packages/tokens/src/56.ts
Labels: size/S

#7458 chore: Add v3 gas estimation on zkrollup chains
  packages/smart-router/evm/constants/gasModel/v3.ts
Labels: size/S

#7459 fix: Prevent filtering zero liquidity v3 pools
  packages/smart-router/evm/v3-router/providers/poolProviders/onChainPoolProviders.ts
Labels: size/XS

#7460 chore: Bump smart router version
  .changeset/tough-eyes-fix.md
Labels: size/XS

#7382 feat: Revenue sharing pool
  apps/web/public/images/pool/lockCAKEbenefit.png
  apps/web/public/images/pool/lockcaketooltip.png
  apps/web/src/config/abi/revenueSharingPool.ts
  apps/web/src/config/abi/vCake.ts
  apps/web/src/config/constants/contracts.ts
  apps/web/src/hooks/useContract.ts
  apps/web/src/utils/addressHelpers.ts
  apps/web/src/utils/contractHelpers.ts
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3Card.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/index.tsx
  apps/web/src/views/Pools/components/LockedPool/Common/LockedActions.tsx
  apps/web/src/views/Pools/components/LockedPool/LockedStaking.tsx
  apps/web/src/views/Pools/components/LockedPool/LockedStakingApy.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/AutoHarvest.tsx
  apps/web/src/views/Pools/components/RevenueSharing/BenefitsModal/BenefitsText.tsx
  apps/web/src/views/Pools/components/RevenueSharing/BenefitsModal/BenefitsTooltipsText.tsx
  apps/web/src/views/Pools/components/RevenueSharing/BenefitsModal/ClaimButton.tsx
  apps/web/src/views/Pools/components/RevenueSharing/BenefitsModal/LockedBenefits.tsx
  apps/web/src/views/Pools/components/RevenueSharing/BenefitsModal/RevenueSharing.tsx
  apps/web/src/views/Pools/components/RevenueSharing/BenefitsModal/SharingPoolNameCell.tsx
  apps/web/src/views/Pools/components/RevenueSharing/BenefitsModal/index.tsx
  apps/web/src/views/Pools/components/RevenueSharing/JoinRevenueModal/JoinButton.tsx
  apps/web/src/views/Pools/components/RevenueSharing/JoinRevenueModal/VCakeModal.tsx
  apps/web/src/views/Pools/components/RevenueSharing/JoinRevenueModal/index.tsx
  apps/web/src/views/Pools/hooks/useRevenueSharingPool.ts
  apps/web/src/views/Pools/hooks/useVCake.tsx
  apps/web/src/views/Pools/index.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/components/Svg/Icons/BCake.tsx
  packages/uikit/src/components/Svg/Icons/ICake.tsx
  packages/uikit/src/components/Svg/Icons/VCake.tsx
  packages/uikit/src/components/Svg/index.tsx
Labels: size/XXL
