Repository pancakeswap/pancake-frontend, pull requests merged in 2023-11, with the labels that each got.

#8264 chore: New Crowdin updates
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/S

#8266 chore: position manager details
  apps/web/src/views/PositionManagers/components/Header.tsx
  apps/web/src/views/PositionManagers/components/VaultInfo.tsx
  apps/web/src/views/PositionManagers/hooks/useFetchApr.ts
  packages/localization/src/config/translations.json
Labels: size/S

#8269 feat: update words
  packages/localization/src/config/translations.json
  packages/widgets-internal/farm/components/MerklNotice/index.tsx
Labels: size/XS

#8273 fix: position manager display details
  apps/web/src/views/PositionManagers/components/VaultInfo.tsx
Labels: size/XS

#8279 chore: update zksync testnet address
  apps/web/src/views/PositionManagers/components/VaultInfo.tsx
  packages/localization/src/config/translations.json
  packages/universal-router-sdk/src/utils/constants.ts
  packages/widgets-internal/farm/components/MerklNotice/index.tsx
Labels: size/S

#8275 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#8245 refactor: Use query in farms
  apps/web/src/hooks/useFarm.ts
  apps/web/src/state/farms/hooks.ts
  apps/web/src/state/farmsV3/hooks.ts
  apps/web/src/views/Farms/components/YieldBooster/hooks/bCakeV3/useBCakeV3Info.ts
  apps/web/src/views/Farms/components/YieldBooster/hooks/useBoostMultiplier.ts
  apps/web/src/views/Farms/components/YieldBooster/hooks/useFarmBoosterConstants.ts
  apps/web/src/views/Farms/hooks/useBCakeProxyBalance.ts
  apps/web/src/views/Farms/hooks/useBCakeProxyContractAddress.ts
  apps/web/src/views/Farms/hooks/useFarmCProxyAddress.ts
  apps/web/src/views/Farms/hooks/useFirstTimeCrossFarming.ts
  apps/web/src/views/Farms/hooks/useUserBoosterStatus.ts
  apps/web/src/views/Farms/hooks/v3/useFarmV3Actions.tsx
Labels: size/L

#8253 refactor: Use query for block hooks
  apps/web/src/hooks/useRefreshEffect.test.ts
  apps/web/src/hooks/useRefreshEffect.ts
  apps/web/src/state/block/hooks.ts
  apps/web/src/state/multicall/hooks.ts
  apps/web/src/testUtils.tsx
  apps/web/src/views/Swap/hooks/useRefreshBlockNumber.ts
Labels: size/L

#8272 chore: Adjust the subgraph and scrollToTop placement
  apps/web/src/components/SubgraphHealthIndicator/SubgraphHealthIndicator.tsx
  packages/uikit/src/components/ScrollToTopButton/ScrollToTopButtonV2.tsx
Labels: size/XS

#8280 chore: add GA4 for blog
  apps/blog/pages/_app.tsx
Labels: size/S

#8274 refactor: Use query for blog pages
  apps/blog/components/Article/AllArticle/index.tsx
  apps/blog/components/Article/SingleArticle/ArticleInfo.tsx
  apps/blog/components/Article/SingleArticle/SimilarArticles.tsx
  apps/blog/components/ChefsChoice/index.tsx
  apps/blog/components/NewBlog.tsx
  apps/blog/hooks/useAllArticle.ts
  apps/blog/hooks/useLanguage.ts
  apps/blog/hooks/useSearchBarArticle.ts
  apps/blog/package.json
  apps/blog/pages/_app.tsx
  apps/blog/pages/articles/[slug].tsx
  apps/blog/pages/index.tsx
  pnpm-lock.yaml
Labels: Delayed Release, size/L

#8281 chore: Remove swr dependency in games
  apps/games/package.json
  pnpm-lock.yaml
Labels: size/XS

#8259 refactor: Use query in predictions
  apps/web/src/views/Predictions/components/ChainlinkChart.tsx
  apps/web/src/views/Predictions/hooks/usePollPredictions.ts
Labels: size/M

#8282 chore: Remove swr dependency in utils and aptos
  apps/aptos/components/Farms/hooks/useLpRewardsAprs.ts
  apps/aptos/components/Providers.tsx
  apps/aptos/hooks/useCakePrice.ts
  apps/aptos/hooks/useLedgerTimestamp.ts
  apps/aptos/hooks/useStablePrice.ts
  apps/aptos/package.json
  apps/aptos/pages/swap.tsx
  apps/aptos/state/lists/updater.tsx
  packages/utils/package.json
  pnpm-lock.yaml
Labels: size/L

#8287 fix: Exeception when add liquidity
  apps/web/src/hooks/useFarm.ts
Labels: size/XS

#8288 fix: Potential np3 v3 boost farm query hook
  apps/web/src/state/farmsV3/hooks.ts
Labels: size/XS

#8289 feat: add MEME-ETH farm
  packages/farms/constants/eth.ts
  packages/tokens/src/1.ts
Labels: size/S

#8290 chore: Use logo components from internal widgets
  apps/web/src/components/CurrencyInputPanel/index.tsx
Labels: size/XS

#8294 chore: update vault pool fee tier
  packages/position-managers/src/constants/vaults/56.ts
Labels: size/XS

#8303 chore: update api endpoint for vault LP APR data
  packages/position-managers/src/constants/endpoints.ts
Labels: size/XS

#8305 chore: set GA4 for games page
  apps/games/pages/_app.tsx
Labels: size/XS

#8304 chore: fix roi calculator for position manager
  apps/web/src/views/PositionManagers/components/AddLiquidity.tsx
  apps/web/src/views/PositionManagers/components/AprButton.tsx
  apps/web/src/views/PositionManagers/components/DuoTokenVaultCard.tsx
  apps/web/src/views/PositionManagers/components/YieldInfo.tsx
Labels: size/S

#8291 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#8256 fix(Pools): Fix tooltip placement
  apps/web/src/views/Pools/components/Vault/VaultStakeButtonGroup.tsx
Labels: size/XS

#8283 refactor: Use query in voting
  apps/web/src/pages/voting/proposal/[id].tsx
  apps/web/src/views/Voting/Proposal/Overview.tsx
  apps/web/src/views/Voting/components/Proposals/Proposals.tsx
  apps/web/src/views/Voting/hooks/useGetVotingPower.tsx
Labels: size/L

#8295 refactor: Use query in info
  apps/web/src/hooks/useStableSwapAPR.ts
  apps/web/src/state/info/hooks.ts
  apps/web/src/state/info/queries/search/index.ts
  apps/web/src/views/Info/Overview/index.tsx
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/Info/Pools/index.tsx
  apps/web/src/views/Info/Tokens/TokenPage.tsx
  apps/web/src/views/Info/Tokens/index.tsx
  apps/web/src/views/Info/components/InfoCharts/CandleChart/index.tsx
  apps/web/src/views/Info/components/InfoCharts/ChartCard/index.tsx
  apps/web/src/views/Info/components/InfoSearch/index.tsx
  apps/web/src/views/Info/components/InfoTables/PoolsTable.tsx
  apps/web/src/views/Info/components/InfoTables/TokensTable.tsx
  apps/web/src/views/Info/components/TopTokenMovers/index.tsx
  apps/web/src/views/Info/hooks/useBlocksFromTimestamps.ts
  apps/web/src/views/Info/hooks/useCMCLink.ts
  apps/web/src/views/Info/hooks/usePoolsData.ts
  apps/web/src/views/Swap/components/HotTokenList/useList.tsx
  apps/web/src/views/V3Info/data/pool/poolData.ts
  apps/web/src/views/V3Info/data/protocol/overview.ts
  apps/web/src/views/V3Info/data/search/index.ts
  apps/web/src/views/V3Info/data/token/tokenData.ts
  apps/web/src/views/V3Info/hooks/index.ts
  apps/web/src/views/V3Info/utils/getEthPrices.ts
Labels: size/XL

#8238 chore: remove legacy GA config
  apps/web/src/pages/_app.tsx
Labels: size/S, automerge

#8307 fix(Blog): Filter issue
  apps/blog/hooks/useAllArticle.ts
Labels: size/S, automerge

#8309 fix: Remove keepPreviousData flag from farm v3 public
  apps/web/src/state/farmsV3/hooks.ts
Labels: size/XS

#8313 chore: New Crowdin updates
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/S

#8308 chore: fix bCake boosted tag issue
  apps/web/src/state/farmsV3/hooks.ts
Labels: size/XS

#8091 feat: Merkl Integration
  apps/web/package.json
  apps/web/src/components/Merkl/MerklSection.tsx
  apps/web/src/components/Merkl/MerklTag.tsx
  apps/web/src/components/SearchModal/CurrencySearch.tsx
  apps/web/src/hooks/useMerkl.tsx
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/pages/liquidity/index.tsx
  apps/web/src/views/AddLiquidity/components/LiquidityCardRow/index.tsx
  apps/web/src/views/AddLiquidityV3/components/StablePairCard.tsx
  apps/web/src/views/AddLiquidityV3/components/V2PairCard.tsx
  apps/web/src/views/Migration/components/v3/Step4.tsx
  packages/localization/src/config/translations.json
  pnpm-lock.yaml
Labels: size/XL

#8320 fix(aptos): use new msafe sdk
  .changeset/two-cobras-greet.md
  apps/aptos/package.json
  apps/aptos/public/images/wallets/msafe.png
  packages/awgmi/core/src/connectors/msafe.ts
  packages/awgmi/package.json
  pnpm-lock.yaml
Labels: size/M

#8317 chore: Fix lockfile
  apis/farms/package.json
  apis/proxy-worker/package.json
  apis/routing/package.json
  apps/aptos/package.json
  apps/blog/package.json
  apps/bridge/package.json
  apps/e2e/package.json
  apps/games/package.json
  apps/web/package.json
  examples/playground/package.json
  package.json
  packages/awgmi/package.json
  packages/multicall/package.json
  packages/pools/package.json
  packages/position-managers/package.json
  packages/smart-router/package.json
  packages/swap-sdk-core/package.json
  packages/token-lists/package.json
  packages/uikit/package.json
  packages/utils/package.json
  packages/v3-sdk/package.json
  pnpm-lock.yaml
Labels: size/XXL

#8323 fix(aptos): allow msafe reconnect
  apps/aptos/client.ts
  apps/aptos/config/wallets.ts
  apps/aptos/hooks/useEagerConnect.ts
  packages/ui-wallets/src/WalletModal.tsx
Labels: size/S

#8324 chore: Default to use pokt on polygon
  apps/web/src/config/nodes.ts
Labels: size/S

#8325 Revert "chore: Default to use pokt on polygon"
  apps/web/src/config/nodes.ts
Labels: size/S

#8329 chore: Fix dev build issue
  apps/web/package.json
  package.json
Labels: size/S

#8322 chore: Move BSC finished pool
  .changeset/real-ways-press.md
  packages/pools/src/constants/pools/56.ts
Labels: size/M, automerge

#8328 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#8331 chore: Default to use Nodies on polygon
  apps/web/.env.example
  apps/web/src/config/nodes.ts
  apps/web/src/config/pools.ts
  packages/multicall/src/constants/blockConflictTolerance.ts
Labels: size/M

#8332 chore: Remove merkl farm
  apps/web/src/config/merkl.ts
Labels: size/XS

#8333 Revert "chore: Default to use Nodies on polygon"
  apps/web/.env.example
  apps/web/src/config/nodes.ts
  apps/web/src/config/pools.ts
  packages/multicall/src/constants/blockConflictTolerance.ts
Labels: size/M

#8298 feat(PositionManager): Add totalStakedTokenAmount
  apps/web/src/views/PositionManagers/components/LiquidityManagement.tsx
  apps/web/src/views/PositionManagers/components/RewardAssets.tsx
  apps/web/src/views/PositionManagers/components/StakedAssets.tsx
  apps/web/src/views/PositionManagers/hooks/index.ts
  apps/web/src/views/PositionManagers/hooks/useTotalAssetInSingleDepositTokenAmount.ts
Labels: Triage, size/M

#8339 chore: Add zkevm fallback and lower timeout thershold
  apps/web/.env.example
  apps/web/src/config/nodes.ts
  apps/web/src/utils/viem.ts
Labels: size/M

#8340 chore: Shuffle zkevm node
  apps/web/src/config/nodes.ts
  apps/web/src/utils/viem.ts
Labels: size/XS

#8341 fix: Invalid token allowance fetch
  apps/web/src/hooks/useTokenAllowance.ts
Labels: size/S, automerge

#8342 fix(smart-router): Add default exports path
  .changeset/dirty-zoos-rule.md
  packages/smart-router/package.json
Labels: size/S

#8299 fix: Currency amount significant digits
  .changeset/serious-books-battle.md
  apps/web/src/components/CurrencyInputPanel/index.tsx
  apps/web/src/components/FormattedCurrencyAmount/FormattedCurrencyAmount.tsx
  apps/web/src/components/RangePriceSection/index.tsx
  apps/web/src/hooks/useFarm.ts
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/state/multicall/hooks.ts
  apps/web/src/state/swap/useLPApr.ts
  apps/web/src/state/transactions/actions.ts
  apps/web/src/state/transactions/hooks.tsx
  apps/web/src/utils/currencyId.ts
  apps/web/src/utils/isPoolTickInRange.ts
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
  apps/web/src/views/AddLiquidityV3/formViews/StableFormView.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/PositionPreview.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/RateToggle.tsx
  apps/web/src/views/RemoveLiquidity/RemoveLiquidityV3.tsx
  apps/web/src/views/RemoveLiquidity/index.tsx
  apps/web/src/views/Swap/components/ConfirmRemoveLiquidityModal.tsx
  packages/localization/src/Provider.tsx
  packages/localization/src/types.ts
  packages/tokens/src/helpers.ts
  packages/widgets-internal/swap/NumericalInput.tsx
Labels: size/L

#8338 chore: New Crowdin updates
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/S

#8310 refactor: Use query in home
  apps/web/src/pages/index.tsx
  apps/web/src/utils/apr.ts
  apps/web/src/utils/verifyBscNetwork.ts
  apps/web/src/views/Home/components/Banners/hooks/useIsRenderLotteryBanner.tsx
  apps/web/src/views/Home/components/CakeDataRow.tsx
  apps/web/src/views/Home/components/CommunitySection/LotteryCardContent.tsx
  apps/web/src/views/Home/components/CommunitySection/PredictionCardContent.tsx
  apps/web/src/views/Home/components/MetricsSection/index.tsx
  apps/web/src/views/Home/hooks/useAllArticle.ts
  apps/web/src/views/Home/hooks/useFarmsWithBalance.tsx
  apps/web/src/views/Home/hooks/useGetTopFarmsByApr.tsx
  apps/web/src/views/Home/hooks/useGetTopPoolsByApr.tsx
  packages/farms/constants/index.ts
Labels: size/L

#8349 chore: Default to use nodies
  apps/web/src/config/nodes.ts
Labels: size/XS

#8350 chore: use api from zkevm usd price
  apps/web/src/hooks/useBUSDPrice.ts
Labels: size/S

#8355 chore: Fix build error
  .eslintrc
  apis/farms/package.json
  apis/routing/package.json
  apps/aptos/package.json
  apps/aptos/utils/getContactAddress.ts
  apps/aptos/utils/splitTypeTag.ts
  apps/blog/package.json
  apps/bridge/package.json
  apps/games/package.json
  apps/web/package.json
  packages/aptos-swap-sdk/package.json
  packages/awgmi/package.json
  packages/farms/package.json
  packages/hooks/package.json
  packages/multicall/package.json
  packages/pools/package.json
  packages/position-managers/package.json
  packages/smart-router/package.json
  packages/swap-sdk-core/package.json
  packages/swap-sdk/package.json
  packages/uikit/package.json
  packages/utils/package.json
  packages/v3-sdk/package.json
  packages/wagmi/package.json
  packages/widgets-internal/package.json
  pnpm-lock.yaml
  scripts/package.json
Labels: size/XXL

#8334 refactor: Use query in pools
  apps/web/src/hooks/useCallWithGasPrice.ts
  apps/web/src/hooks/useUserCakeLockStatus.ts
  apps/web/src/state/pools/hooks.ts
  apps/web/src/views/Pools/components/LockedPool/Buttons/ConvertToFlexibleButton.tsx
  apps/web/src/views/Pools/components/LockedPool/hooks/useLockedPool.tsx
  apps/web/src/views/Pools/hooks/useRevenueSharingPool.ts
  apps/web/src/views/Pools/hooks/useVCake.tsx
Labels: size/L

#8351 refactor: Use query in profile
  apps/web/src/views/ProfileCreation/TeamSelection.tsx
Labels: size/XS

#8353 refactor: Use query in pool info
  apps/web/src/hooks/usePoolAvgInfo.ts
Labels: size/S

#8352 chore: New Crowdin updates
  locales/zh-TW.json
Labels: size/XS

#8335 feat: Process more tokens with Wallchain
  apps/web/src/config/wallchain.ts
  apps/web/src/views/Swap/V3Swap/hooks/useWallchain.ts
Labels: size/M

#8354 perf: Reduce no use requests for quote
  apps/web/src/config/chains.ts
  apps/web/src/config/nodes.ts
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/hooks/useCommonPools.ts
  apps/web/src/hooks/useGetENSAddressByName.ts
  apps/web/src/hooks/useV3Pools.ts
  apps/web/src/hooks/useWrapCallback.ts
  apps/web/src/state/swap/hooks.ts
  apps/web/src/state/wallet/hooks.ts
  apps/web/src/utils/wagmi.ts
  apps/web/src/views/Swap/V3Swap/containers/BuyCryptoLink.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useCheckSufficient.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSwapBestTrade.ts
  apps/web/src/views/Swap/index.tsx
Labels: size/L

#8359 fix: Infinite scroll not working on farms
  packages/hooks/src/useIntersectionObserver.ts
Labels: size/XS

#8360 chore: Move axl to finished pools
  packages/pools/src/constants/pools/56.ts
Labels: size/S, automerge

#8356 chore: New Crowdin updates
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/S

#8362 chore: Update default open graph image
  apps/blog/next-seo.config.ts
  apps/games/next-seo.config.ts
  apps/web/next-seo.config.ts
Labels: size/XS

#8366 chore: hide single token display while it's duo
  apps/web/src/views/PositionManagers/components/LiquidityManagement.tsx
  apps/web/src/views/PositionManagers/components/StakedAssets.tsx
Labels: size/S

#8367 chore: list farm on BSC and ETH
  packages/farms/constants/bsc.ts
  packages/farms/constants/eth.ts
Labels: size/S

#8368 fix: Cors error on farm api
  .gitignore
  apps/games/components/Game/Project/QuickAccess.tsx
  packages/games/src/constants/games/binaryX.ts
  packages/games/src/types.ts
  packages/worker-utils/index.ts
Labels: size/S

#8370 chore: Direct to dedicated domain on mobile for pp
  apps/games/components/Game/Community/Banner/index.tsx
  apps/games/components/Game/Home/Game.tsx
  apps/games/hooks/useGameLink.ts
  apps/games/utils/getGameLink.ts
Labels: size/S

#8376 fix: Game cors issue
  packages/worker-utils/index.ts
Labels: size/XS

#8378 chore: Redirect to game page on mobile
  apps/games/components/Game/Community/Banner/index.tsx
  apps/games/components/Game/Home/Game.tsx
  apps/games/components/Game/project.tsx
  apps/games/hooks/useGameLink.ts
  apps/games/utils/getGameLink.ts
Labels: size/S

#8381 feat: Remove new tag
  apps/web/src/components/Menu/config/config.ts
Labels: size/XS, automerge

#8380 style(Game): Css
  apps/games/components/Game/Home/Carousel.tsx
  apps/games/components/Game/Home/Game.tsx
  apps/games/components/Game/Home/OtherGames.tsx
Labels: size/M, automerge

#8375 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XXL

#8382 fix: Games carousel slide buttons
  apps/games/components/Game/Community/Banner/index.tsx
  apps/games/components/Game/Home/Carousel.tsx
Labels: size/M

#8385 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XL

#8263 feat(position manager): support range protocol vault
  apps/web/src/hooks/useCatchTxError.tsx
  apps/web/src/views/PositionManagers/components/AddLiquidity.tsx
  apps/web/src/views/PositionManagers/components/AprButton.tsx
  apps/web/src/views/PositionManagers/components/CardTitle.tsx
  apps/web/src/views/PositionManagers/components/DuoTokenVaultCard.tsx
  apps/web/src/views/PositionManagers/components/RewardAssets.tsx
  apps/web/src/views/PositionManagers/containers/PCSVaultCard.tsx
  apps/web/src/views/PositionManagers/containers/VaultCards.tsx
  apps/web/src/views/PositionManagers/hooks/useFetchApr.ts
  apps/web/src/views/PositionManagers/utils/strategy.ts
  packages/localization/src/config/translations.json
  packages/position-managers/src/constants/managers.ts
  packages/position-managers/src/constants/supportedChains.ts
  packages/position-managers/src/constants/vaults/1.ts
  packages/position-managers/src/constants/vaults/bsc.ts
  packages/position-managers/src/constants/vaults/eth.ts
  packages/position-managers/src/constants/vaults/index.ts
  packages/position-managers/src/types.ts
Labels: size/L

#8386 fix: position manager single token pending text
  apps/web/src/views/PositionManagers/components/AddLiquidity.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#8371 refactor: Use query in lottery
  apps/web/src/views/Home/components/Banners/LotteryBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useNextEventCountdown.ts
  apps/web/src/views/Lottery/hooks/useGetNextLotteryEvent.ts
Labels: size/M

#8346 refactor: Use query in swap
  .changeset/hip-buses-swim.md
  apps/web/src/hooks/useV2Pools.ts
  apps/web/src/hooks/v3/useAllV3TicksQuery.ts
  apps/web/src/hooks/v3/useFeeTierDistributionQuery.ts
  apps/web/src/state/lists/updater.ts
  apps/web/src/state/swap/hooks.ts
  apps/web/src/state/swap/useLPApr.ts
  apps/web/src/utils/graphql.ts
  apps/web/src/utils/shouldShowSwapWarning.ts
  apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/hooks/useStableDerivedBurnInfo.ts
  apps/web/src/views/Swap/V3Swap/hooks/useWallchain.ts
  apps/web/src/views/Swap/components/Chart/utils.ts
  apps/web/src/views/Swap/hooks/useEstimatedAmount.ts
  apps/web/src/views/Swap/hooks/useWarningImport.tsx
  packages/smart-router/evm/v3-router/types/providers.ts
Labels: size/L

#8393 fix: Dev module not found issue
  turbo.json
Labels: size/XS

#8389 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#8306 feat: Pool added boosted apr
  apps/web/src/utils/viem.ts
  apps/web/src/views/Farms/components/FarmCard/CardHeading.tsx
  apps/web/src/views/Farms/components/FarmTable/Row.tsx
  apps/web/src/views/Pools/components/Apr.tsx
  apps/web/src/views/Pools/components/Modals/StakeModal.tsx
  apps/web/src/views/Pools/components/PoolsTable/Cells/AprCell.tsx
  apps/web/src/views/Pools/components/PoolsTable/Cells/NameCell.tsx
  apps/web/src/views/Pools/hooks/useBoostedPoolApr.ts
  apps/web/src/views/Pools/index.tsx
  packages/localization/src/config/translations.json
  packages/pools/src/constants/boostedPools/arb.ts
  packages/pools/src/constants/boostedPools/index.ts
  packages/pools/src/constants/index.ts
  packages/pools/src/index.test.ts
  packages/pools/src/utils/boosted/apr/fetchAlpBoostedPoolApr.ts
  packages/pools/src/utils/boosted/apr/getBoostedPoolApr.ts
  packages/pools/src/utils/boosted/checkIsBoostedPool.ts
  packages/pools/src/utils/boosted/types.ts
  packages/pools/src/utils/index.ts
  packages/uikit/src/components/Balance/BalanceWithLoading.tsx
  packages/uikit/src/components/Svg/Icons/AlpIcon.tsx
  packages/uikit/src/components/Svg/index.tsx
  packages/widgets-internal/farm/components/Tags/index.tsx
  packages/widgets-internal/pool/Apr.tsx
  packages/widgets-internal/pool/PoolCard.tsx
  packages/widgets-internal/pool/PoolCardHeader.tsx
Labels: size/XL

#8401 fix: responsive part 2
  apps/web/src/views/CakeStaking/components/LockCake/Migrate.tsx
  apps/web/src/views/CakeStaking/components/LockCake/NotLocking.tsx
  apps/web/src/views/CakeStaking/components/LockCakeForm.tsx
  apps/web/src/views/CakeStaking/components/LockWeeksForm.tsx
Labels: size/M

#8402 fix: check reward responsive modal
  apps/web/src/views/CakeStaking/components/CakeRewardsCard.tsx
Labels: size/XS

#8403 fix: filter responsive
  apps/web/src/views/GaugesVoting/components/Table/AddGauge/AddGaugeModal.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/index.tsx
Labels: size/S

#8404 fix: Responsive on increase veCake card
  apps/web/src/views/CakeStaking/components/LockCake/Staking.tsx
  apps/web/src/views/CakeStaking/components/LockCakeForm.tsx
  apps/web/src/views/CakeStaking/components/LockWeeksForm.tsx
  apps/web/src/views/CakeStaking/components/LockedVeCakeStatus.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/TableHeader.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/index.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/TableHeader.tsx
  apps/web/src/views/GaugesVoting/components/Table/styled.tsx
  apps/web/src/views/GaugesVoting/index.tsx
Labels: size/L

#8405 fix: Show gauges list on mobile
  apps/web/src/views/GaugesVoting/components/GaugeTokenImage.tsx
  apps/web/src/views/GaugesVoting/components/NetworkBadge/NetworkBadge.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/List.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/index.tsx
  apps/web/src/views/GaugesVoting/index.tsx
Labels: size/L

#8397 chore: Don't set swiper in game
  apps/games/components/Game/Home/Games.tsx
Labels: size/XS

#8406 fix: gauge vote mobile view
  apps/web/src/views/GaugesVoting/components/Table/AddGauge/AddGaugeModal.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/List.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/List.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/index.tsx
Labels: size/L

#8414 fix: Multicall not working on local development mode
  .changeset/tidy-mails-travel.md
  apps/web/src/state/multicall/fetchChunk.ts
  packages/multicall/src/abis/IMulticall3.ts
  packages/multicall/src/constants/contracts.ts
  packages/multicall/src/getMulticallContract.ts
  packages/multicall/src/index.test.ts
  packages/multicall/src/index.ts
Labels: size/L

#8411 fix: Dom warnings in alert
  packages/uikit/src/components/Alert/Alert.tsx
Labels: size/XS

#8416 fix: Proposal total count
  apps/web/src/views/CakeStaking/components/LockCakeForm.tsx
  apps/web/src/views/CakeStaking/hooks/useGaugesVotingCount.ts
  apps/web/src/views/CakeStaking/hooks/useLockAllowance.ts
  apps/web/src/views/CakeStaking/hooks/useSnapshotProposalsCount.ts
  apps/web/src/views/CakeStaking/hooks/useTotalIFOSold.ts
  apps/web/src/views/CakeStaking/index.tsx
Labels: size/M

#8418 chore: Add custom base for czusd
  packages/smart-router/evm/constants/exchange.ts
Labels: size/S

#8419 fix: chart tooltip refinement
  apps/web/src/views/GaugesVoting/components/ChartTooltip.tsx
  apps/web/src/views/GaugesVoting/components/TripleLogo.tsx
  packages/widgets-internal/components/CurrencyLogo/ChainLogo.tsx
  packages/widgets-internal/components/CurrencyLogo/CurrencyLogo.tsx
  packages/widgets-internal/components/CurrencyLogo/utils.ts
Labels: size/L

#8424 feat: update doc links
  apps/web/src/views/CakeStaking/components/LockedVeCakeStatus.tsx
  apps/web/src/views/CakeStaking/components/NewCakeStakingCard.tsx
Labels: size/S

#8425 chore: Update locked cake modal
  apps/web/src/views/Pools/components/Apr.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/AutoHarvest.tsx
  apps/web/src/views/Pools/components/PoolsTable/Cells/AprCell.tsx
  apps/web/src/views/Pools/components/RevenueSharing/BenefitsModal/ClaimButton.tsx
  apps/web/src/views/Pools/components/RevenueSharing/BenefitsModal/RevenueSharing.tsx
  apps/web/src/views/Pools/components/RevenueSharing/BenefitsModal/index.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#8427 chore: Update learn more link
  apps/web/src/views/CakeStaking/components/SyrupPool/LearnMoreLink.tsx
  apps/web/src/views/CakeStaking/components/SyrupPool/VeCakeMigrateCard.tsx
  apps/web/src/views/CakeStaking/components/SyrupPool/VeCakeUpdateCard.tsx
  apps/web/src/views/CakeStaking/components/SyrupPool/index.ts
  apps/web/src/views/Pools/components/CakeVaultCard/VaultCardActions/HasSharesActions.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#8426 feat: vecake banner
  apps/web/src/views/Home/components/Banners/VeCakeBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  apps/web/src/views/Home/components/Banners/images/index.ts
  apps/web/src/views/Home/components/Banners/images/vecake-bg.png
  apps/web/src/views/Home/components/Banners/images/vecake-desktop-bunny.png
  apps/web/src/views/Home/components/Banners/images/vecake-mobile-bg.png
  apps/web/src/views/Home/components/Banners/images/vecake-mobile-bunny.png
  apps/web/src/views/Home/components/Banners/images/vecake-ruby.png
  apps/web/src/views/Home/components/Banners/images/vecake-title.png
  packages/localization/src/config/translations.json
Labels: size/L

#8428 chore: Update cake APR tooltip
  apps/web/src/config/constants/pools.tsx
  apps/web/src/views/Pools/components/LockedPool/Common/LockedAprTooltipContent.tsx
  apps/web/src/views/Pools/components/PoolsTable/Cells/AutoAprCell.tsx
  packages/localization/src/config/translations.json
Labels: size/M, automerge

#8430 chore: Add gas margin on vecake write
  apps/web/src/views/CakeStaking/hooks/useContractWrite/useWriteLockCallback.ts
  apps/web/src/views/CakeStaking/hooks/useContractWrite/useWriteMigrateCallback.tsx
Labels: size/S

#8422 fix: Pool boosted UI
  apps/web/src/views/Pools/hooks/useBoostedPoolApr.ts
Labels: size/XS, automerge

#8408 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XXL

#8423 fix(CAKE Staking): Fix HelpIcon color & BubbleBox
  apps/web/src/views/CakeStaking/components/NewCakeStakingCard.tsx
Labels: size/S

#8421 fix(Games): Fix carouseImage width
  apps/games/components/Game/Home/Carousel.tsx
Labels: size/S

#8436 chore(CAKE Staking): Adjust Gauges Voting coming soon btn gap
  apps/web/src/views/CakeStaking/components/BenefitCard.tsx
Labels: size/XS

#8429 fix: Apr returns value when current tick equals to upper bound
  .changeset/green-owls-beg.md
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
  packages/v3-sdk/src/index.test.ts
  packages/v3-sdk/src/utils/feeCalculator.ts
  packages/v3-sdk/src/utils/index.ts
  packages/v3-sdk/src/utils/isPoolTickInRange.ts
Labels: size/S

#8379 chore: Remove withdraw warning
  apps/web/src/hooks/useCatchTxError.tsx
  apps/web/src/views/FixedStaking/hooks/useHandleWithdrawSubmission.tsx
  packages/localization/src/config/translations.json
Labels: Delayed Release, size/M

#8444 feat: Move finished pools
  .changeset/large-dogs-film.md
  packages/pools/src/constants/pools/324.ts
  packages/pools/src/constants/pools/56.ts
Labels: size/M

#8446 feat: Update application list games link
  apps/games/components/Game/Developers/Banner.tsx
  apps/games/components/Game/Developers/Footer.tsx
  apps/games/components/Game/Home/Banner.tsx
Labels: size/S, automerge

#8453 chore: Log wallet name when wallet connect
  apps/web/src/utils/customGTMEventTracking.ts
  packages/ui-wallets/src/WalletModal.tsx
Labels: size/S

#8447 chore: position manager vault test case
  .changeset/shaggy-crabs-hug.md
  apps/web/src/config/__tests__/tokens.test.ts
  apps/web/src/config/__tests__/vaults.test.ts
  apps/web/src/config/abi/IPancakeV3Pool.json
  packages/position-managers/constants/index.ts
  packages/position-managers/src/constants/vaults/eth.ts
  packages/smart-router/evm/constants/index.ts
  packages/smart-router/evm/constants/stableSwap/index.ts
  packages/smart-router/evm/index.test.ts
  packages/smart-router/evm/index.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/onChainPoolProviders.ts
  packages/smart-router/package.json
  packages/v3-sdk/package.json
  packages/v3-sdk/src/abi/IPancakeV3Pool.ts
  packages/v3-sdk/src/index.test.ts
  packages/v3-sdk/src/index.ts
Labels: size/XL

#8452 fix: Missing error handling in v3 remove liquidity
  apps/web/src/views/RemoveLiquidity/RemoveLiquidityV3.tsx
Labels: size/M

#8457 feat: Add new ALP pool
  .changeset/yellow-sheep-share.md
  packages/pools/src/constants/boostedPools/arb.ts
  packages/pools/src/constants/pools/42161.ts
Labels: size/S

#8456 chore: list new BRIL vault and resort vaults
  packages/position-managers/src/constants/vaults/bsc.ts
Labels: size/L

#8435 chore: Gauges staging
  .vscode/settings.json
  apps/web/next.config.mjs
  apps/web/src/config/abi/veCake.ts
  apps/web/src/config/constants/contracts.ts
  apps/web/src/config/constants/gauges.ts
  apps/web/src/config/constants/types.ts
  apps/web/src/views/CakeStaking/components/BenefitCard.tsx
  apps/web/src/views/CakeStaking/components/CakePoolLockStatus.tsx
  apps/web/src/views/CakeStaking/components/HeadImage.tsx
  apps/web/src/views/CakeStaking/components/LockCake/NotLocking.tsx
  apps/web/src/views/CakeStaking/components/LockCakeForm.tsx
  apps/web/src/views/CakeStaking/components/LockedVeCakeStatus.tsx
  apps/web/src/views/CakeStaking/components/Tooltips.tsx
  apps/web/src/views/CakeStaking/index.tsx
  apps/web/src/views/GaugesVoting/components/ChartTooltip.tsx
  apps/web/src/views/GaugesVoting/components/CurrentEpoch.tsx
  apps/web/src/views/GaugesVoting/components/GaugeTokenImage.tsx
  apps/web/src/views/GaugesVoting/components/MyVeCakeBalance.tsx
  apps/web/src/views/GaugesVoting/components/RemainVeCakeBalance.tsx
  apps/web/src/views/GaugesVoting/components/RemainingVotePower.tsx
  apps/web/src/views/GaugesVoting/components/Table/AddGauge/AddGaugeModal.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/List.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/TableRow.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/index.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/types.ts
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/List.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/PercentInput.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/TableRow.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/hooks/useGaugeRows.ts
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/hooks/useRowVoteState.ts
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/index.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/types.ts
  apps/web/src/views/GaugesVoting/components/TripleLogo.tsx
  apps/web/src/views/GaugesVoting/components/WeightsPieChart.tsx
  apps/web/src/views/GaugesVoting/hooks/useEpochTime.ts
  apps/web/src/views/GaugesVoting/hooks/useEpochVotePower.ts
  apps/web/src/views/GaugesVoting/hooks/useGaugeEpochEnd.ts
  apps/web/src/views/GaugesVoting/hooks/useGaugePair.ts
  apps/web/src/views/GaugesVoting/hooks/useGaugesPresets.ts
  apps/web/src/views/GaugesVoting/hooks/useGaugesVoting.ts
  apps/web/src/views/GaugesVoting/hooks/useUserVote.ts
  apps/web/src/views/GaugesVoting/hooks/useUserVoteGuages.ts
  apps/web/src/views/GaugesVoting/hooks/useWriteGaugesVoteCallback.tsx
  apps/web/src/views/GaugesVoting/index.tsx
  packages/localization/src/config/translations.json
  packages/tokens/src/1.ts
  packages/tokens/src/42161.ts
  packages/tokens/src/56.ts
  packages/uikit/src/components/Svg/Icons/Cross.tsx
  packages/uikit/src/components/Svg/index.tsx
  packages/uikit/src/tokens/colors.ts
Labels: size/XXL

#8459 chore: remove unlock warning
  apps/web/src/views/CakeStaking/components/HeadImage.tsx
  apps/web/src/views/GaugesVoting/components/CurrentEpoch.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/hooks/useRowVoteState.ts
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/index.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#8455 feat: Update TRADING_REWARD_API
  apps/web/src/config/constants/endpoints.ts
Labels: size/XS, automerge

#8465 chore: List cake sdcake stable pair
  .changeset/five-steaks-kneel.md
  packages/smart-router/evm/constants/stableSwap/56.ts
  packages/tokens/src/56.ts
Labels: size/S

#8451 feat: add prod did.json in prep for web notifications launch
  apps/web/public/.well-known/did.json
Labels: size/S

#8463 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XL

#8470 fix: Untransformed variables in translations
  packages/localization/src/Provider.tsx
Labels: size/XS

#8471 feat: add 6 new gauges
  apps/web/src/config/constants/gauges.ts
  packages/tokens/src/42161.ts
Labels: size/M

#8473 fix: token url
  packages/widgets-internal/components/CurrencyLogo/utils.ts
Labels: size/S

#8475 fix: chainName
  packages/widgets-internal/components/CurrencyLogo/utils.ts
Labels: size/XS

#8477 fix: Quote failed due to low success rate
  .changeset/silent-tigers-kiss.md
  packages/multicall/src/constants/gasLimit.ts
  packages/smart-router/evm/v3-router/constants/routeConfig.ts
  packages/smart-router/evm/v3-router/providers/onChainQuoteProvider.ts
Labels: size/S

#8480 perf: Prioritize single swap quotes
  .changeset/sixty-knives-refuse.md
  packages/smart-router/evm/constants/exchange.ts
  packages/smart-router/evm/v3-router/providers/onChainQuoteProvider.ts
  packages/smart-router/evm/v3-router/providers/quoteProviders.ts
  packages/smart-router/evm/v3-router/types/providers.ts
Labels: size/L

#8481 fix: vecake banner responsive
  apps/web/src/views/Home/components/Banners/VeCakeBanner.tsx
Labels: size/XS, automerge

#8489 chore: Increase candidate pool pick for whitelist token
  packages/smart-router/evm/v3-router/constants/poolSelector.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/poolTvlSelectors.ts
Labels: size/M

#8488 fix: missing link
  apps/web/src/views/CakeStaking/components/HeadImage.tsx
Labels: size/S, automerge

#8467 chore(GaugesVoting): Adjust bunny position on mobile
  apps/web/src/views/GaugesVoting/index.tsx
Labels: size/XS
