Repository pancakeswap/pancake-frontend, pull requests merged in 2023-03, with the labels that each got.

#6178 fix: Use mm quote count down only when there is a trade
  apps/web/src/views/Swap/MMLinkPools/components/ConfirmSwapModal.tsx
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButton.tsx
  apps/web/src/views/Swap/MMLinkPools/components/SwapModalFooter.tsx
  apps/web/src/views/Swap/MMLinkPools/components/SwapModalHeader.tsx
  apps/web/src/views/Swap/MMLinkPools/components/TransactionConfirmSwapContent.tsx
  apps/web/src/views/Swap/MMLinkPools/constants.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useDerivedSwapInfoWithMM.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useGetRFQTrade.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useIsMMSupportChain.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useIsMMTradeBetter.tsx
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMOrderBookTrade.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMQuoteCountDown.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMTradeInfo.ts
  apps/web/src/views/Swap/MMLinkPools/types.ts
  apps/web/src/views/Swap/SmartSwap/index.tsx
  apps/web/src/views/Swap/components/AdvancedSwapDetails.tsx
  apps/web/src/views/Swap/components/SwapModalHeader.tsx
  packages/localization/src/config/translations.json
Labels: size/XL

#6227 fix(Aptos): Update Aptos Lps APR
  apps/aptos/config/constants/farms/2.ts
  apps/aptos/config/constants/lpAprs/1.json
  scripts/updateAptosLpsAPR/farmsOneWeekAgo.json
  scripts/updateAptosLpsAPR/index.ts
Labels: size/L, automerge

#6230 chore: remove campaign icon
  apps/web/src/views/Swap/components/CurrencyInputHeader.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#6228 chore(web): Remove api farm flag
  apps/web/src/config/flag.ts
  apps/web/src/hooks/useFeatureFlag.ts
  apps/web/src/state/farms/hooks.ts
  apps/web/src/state/farms/index.ts
  apps/web/src/state/pools/hooks.ts
  apps/web/src/views/Home/hooks/useGetTopFarmsByApr.tsx
Labels: size/L

#6202 chore(Prediction): Add BSCScanIcon of Leaderboard
  apps/web/src/views/Predictions/Leaderboard/components/Results/RankingCard.tsx
  apps/web/src/views/Predictions/Leaderboard/components/Results/ResultAvatar.tsx
  apps/web/src/views/Predictions/Leaderboard/components/WalletStatsModal.tsx
Labels: size/S

#6201 chore(Info): Modify pairs APR tooltip placement
  apps/web/src/views/Info/Pools/PoolPage.tsx
Labels: size/XS

#6218 feat(web): Add stableswap bnb wrap helper for add/remove liquidity
  apps/web/src/config/abi/stableSwapNativeHelper.json
  apps/web/src/config/constants/contracts.ts
  apps/web/src/hooks/useContract.ts
  apps/web/src/pages/remove/[[...currency]].tsx
  apps/web/src/state/swap/useStableSwapPairs.ts
  apps/web/src/utils/addressHelpers.ts
  apps/web/src/utils/contractHelpers.ts
  apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
  apps/web/src/views/Swap/SmartSwap/hooks/useIsSmartRouterBetter.tsx
  apps/web/src/views/Swap/StableSwap/components/StableSwapForm.tsx
  apps/web/src/views/Swap/StableSwap/hooks/useStableConfig.ts
  apps/web/src/views/Swap/StableSwap/index.tsx
  apps/web/src/views/Swap/components/SwapForm.tsx
  packages/smart-router/.gitignore
  packages/smart-router/evm/constants/stableSwap/56.ts
  packages/smart-router/evm/constants/stableSwap/97.ts
  packages/smart-router/evm/getStableSwapPairs.ts
  packages/smart-router/evm/stableSwap/getLPOutput.ts
  packages/smart-router/evm/stableSwap/getSwapOutput.ts
  packages/smart-router/evm/stableSwap/utils.ts
  packages/smart-router/evm/types/pool.ts
  packages/smart-router/evm/types/stableSwap.ts
Labels: size/L

#6225 feat: Update FUSE image
  apps/web/public/images/tokens/0x5857c96DaE9cF8511B08Cb07f85753C472D36Ea3.png
  apps/web/public/images/tokens/0x5857c96DaE9cF8511B08Cb07f85753C472D36Ea3.svg
Labels: size/XS, automerge

#6209 feat(Swap): Add USDT in Common tokens
  apps/web/src/config/constants/exchange.ts
Labels: size/XS, automerge

#6238 feat: Enable stableswap wrap helper and update smart router address
  apps/web/src/views/AddLiquidity/AddStableLiquidity/hooks/useStableLPDerivedMintInfo.tsx
  apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
  apps/web/src/views/Swap/SmartSwap/utils/exchange.ts
  packages/smart-router/evm/utils/route.ts
Labels: size/S

#6239 feat(Aptos): List ETERN & BLT Farm
  apps/aptos/config/constants/farms/1.ts
  apps/aptos/config/constants/tokens/1.ts
Labels: size/M, automerge

#6236 feat(Farm): List WBNB-stkBNB LP
  apps/web/src/config/constants/pools.tsx
  packages/farms/constants/56.ts
  packages/smart-router/evm/constants/stableSwap/56.ts
Labels: size/S, automerge

#6242 feat: List BNBx-BNB
  apps/web/public/images/tokens/0x1bdd3Cf7F79cfB8EdbB955f20ad99211551BA275.png
  packages/farms/constants/56.ts
  packages/smart-router/evm/constants/stableSwap/56.ts
  packages/tokens/src/56.ts
Labels: size/S, automerge

#6244 fix(Aptos): ETERN priceHelper
  apps/aptos/config/constants/priceHelperLps/farms/1.ts
Labels: size/XS, automerge

#6240 fix: Slippage doesn't show correct decimals
  apps/web/src/views/Swap/components/SwapModalHeader.tsx
Labels: size/XS

#6232 feat: BSC mm linked pools
  apps/web/src/config/constants/contracts.ts
  apps/web/src/config/constants/lists.ts
  apps/web/src/views/Swap/MMLinkPools/components/MMAndAMMDealDisplay.tsx
  apps/web/src/views/Swap/MMLinkPools/constants.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useIsMMQuotingPair.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useIsMMTradeBetter.tsx
  apps/web/src/views/Swap/SmartSwap/index.tsx
Labels: size/M

#6246 fix(stableswap-farm): Correct LP USD price for non-stablecoin farms
  packages/farms/src/farmPrices.ts
Labels: size/XS

#6256 chore: Move finished CHAMP pool
  apps/web/src/config/constants/pools.tsx
Labels: size/S

#6250 style(SubgraphHealth): Modify tooltip's Dot align
  apps/web/src/components/SubgraphHealthIndicator/index.tsx
Labels: size/XS

#6260 feat(Pool): List SD pool
  apps/web/public/images/tokens/0x3BC5AC0dFdC871B365d159f728dd1B9A0B5481E8.png
  apps/web/src/config/constants/pools.tsx
  packages/tokens/src/56.ts
Labels: size/S

#6261 feat(blog): Add simple api validation and cache
  apps/blog/pages/api/articles.tsx
  apps/blog/pages/api/locales.tsx
Labels: size/S

#6241 fix: Don't show edit button of slippage tolerance when in mm
  apps/web/src/views/Swap/SmartSwap/index.tsx
  packages/uikit/src/widgets/Swap/SwapInfo.tsx
Labels: size/S

#5976 feat: Add blog url link
  apps/aptos/components/Menu/hooks/useMenuItems.ts
  apps/web/src/components/Menu/config/config.ts
Labels: size/XS, automerge

#6266 chore(Blog): Remove transalte no on html
  apps/blog/pages/_document.tsx
Labels: size/XS, automerge

#6267 fix(aptos-Pools): Stake limit endTime
  apps/aptos/components/Pools/components/PoolCard/PoolStatsInfo.tsx
Labels: size/XS

#6270 fix: add txHash cache for mm confirm model
  apps/web/src/views/Swap/MMLinkPools/components/ConfirmSwapModal.tsx
Labels: size/XS

#6269 feat(Farm): List agEUR-USDT LP
  apps/web/public/images/tokens/0x12f31B73D812C6Bb0d735a218c086d44D5fe5f89.png
  packages/farms/constants/56.ts
  packages/tokens/src/56.ts
Labels: size/S, automerge

#6268 feat: Update footer blog url
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/components/Footer/config.tsx
  packages/uikit/src/widgets/Menu/components/footerConfig.ts
Labels: size/M, automerge

#6271 chore: unique id for mm modal
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButton.tsx
Labels: size/XS

#6273 fix: price data issue for stableSwap
  apps/web/src/state/info/queries/tokens/priceData.ts
  apps/web/src/views/Info/utils/infoQueryHelpers.ts
Labels: size/S

#6276 feat: Update blog
  apps/blog/components/Article/AllArticle/index.tsx
  apps/blog/components/ChefsChoice/index.tsx
  apps/blog/hooks/useLanguage.ts
  apps/web/src/__tests__/translations.test.ts
  packages/localization/src/config/translations.json
Labels: size/S, automerge

#5871 refactor: (farms): Use farm booster constants from sc
  apps/web/src/views/Farms/components/YieldBooster/components/BCakeCalculator.tsx
  apps/web/src/views/Farms/components/YieldBooster/hooks/useFarmBoosterConstants.ts
  apps/web/src/views/Farms/components/YieldBooster/hooks/useGetBoostedAPR.ts
Labels: size/M

#6259 fix: Only show banner when domain is canonical
  apps/aptos/state/user/phishingBanner.ts
  apps/web/src/state/user/hooks/index.tsx
Labels: size/S

#6253 fix: Don't show v2 trade when rfq quote is refetching
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButton.tsx
  apps/web/src/views/Swap/MMLinkPools/hooks/useGetRFQTrade.ts
  apps/web/src/views/Swap/MMLinkPools/types.ts
  apps/web/src/views/Swap/SmartSwap/index.tsx
Labels: size/M

#6251 refactor(VotedTag): Integrate VotedTag into Tags
  apps/web/src/views/Voting/Proposal/Results.tsx
  apps/web/src/views/Voting/components/Proposal/VoteRow.tsx
  packages/uikit/src/widgets/Farm/components/Tags/index.tsx
Labels: size/M

#6278 feat(IFO): Close BSC & Aptos IFO
  apps/aptos/config/constants/ifo.ts
  apps/web/src/config/constants/ifo.ts
Labels: size/XS, automerge

#6245 chore: remove campaign banner legacy code
  apps/web/src/views/Home/components/Banners/TrustWalletCampaignBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useIsRenderTrustWalletCampaignBanner.ts
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#6280 chore(Blog): Typo
  apps/blog/components/ChefsChoice/index.tsx
  apps/web/src/__tests__/translations.test.ts
  packages/localization/src/config/translations.json
Labels: size/XS, automerge

#6279 feat: v3 banner
  apps/web/src/views/Home/components/Banners/V3Banner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  apps/web/src/views/Home/components/Banners/images/index.ts
  apps/web/src/views/Home/components/Banners/images/v3AirdropBunny.png
  apps/web/src/views/Home/components/Banners/images/v3BgBlingBlur.png
  apps/web/src/views/Home/components/Banners/images/v3BgBlingNormal.png
  apps/web/src/views/Home/components/Banners/images/v3BgCoinDown.png
  apps/web/src/views/Home/components/Banners/images/v3BgCoinUp.png
  apps/web/src/views/Home/components/Banners/images/v3Board.png
  apps/web/src/views/Swap/components/CurrencyInputHeader.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#5890 feat(aptos): Rise wallet
  .changeset/angry-spies-cross.md
  apps/aptos/client.ts
  apps/aptos/components/NetworkSwitcher.tsx
  apps/aptos/components/Pools/components/PoolCard/PoolStatsInfo.tsx
  apps/aptos/components/Pools/components/PoolCard/StakeActions.tsx
  apps/aptos/config/ChainName.ts
  apps/aptos/config/wallets.ts
  apps/aptos/public/images/wallets/rise.png
  apps/aptos/views/Ifos/components/Hero.tsx
  packages/awgmi/connectors/rise/package.json
  packages/awgmi/core/src/connectors/rise.ts
  packages/awgmi/core/src/connectors/types.ts
  packages/awgmi/package.json
  packages/awgmi/tsup.config.ts
  packages/localization/src/config/translations.json
Labels: size/L

#6282 chore: v3 banner adjustment
  apps/web/src/components/App/AppHeader.tsx
  apps/web/src/components/V3SwapPromotionIcon.tsx
  apps/web/src/views/AddLiquidity/ChoosePair.tsx
  apps/web/src/views/AddLiquidity/index.tsx
  apps/web/src/views/Home/components/Banners/V3Banner.tsx
  apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/index.tsx
  apps/web/src/views/Swap/components/CurrencyInputHeader.tsx
Labels: size/L

#6284 fix: V3 banner link
  apps/web/src/views/Home/components/Banners/V3Banner.tsx
Labels: size/XS

#6285 fix: v3 tooltip link
  apps/web/src/components/V3SwapPromotionIcon.tsx
Labels: size/XS

#6283 fix: Usd value for aptos tokens
  apps/aptos/config/coins.ts
  apps/aptos/config/constants/exchange.ts
  apps/aptos/hooks/useStablePrice.ts
Labels: size/L

#6289 chore: GTM setting for custom event
  apps/web/src/pages/_app.tsx
Labels: size/S

#6292 fix: Aptos pools token usd values
  apps/aptos/components/Pools/hooks/useAddressPriceMap.ts
Labels: size/L

#6293 fix: use vercel env to show phishing banner
  apps/aptos/state/user/phishingBanner.ts
  apps/web/src/state/user/hooks/index.tsx
Labels: size/S

#6286 fix(Farms): Fix BoostedActionPanel broken on mobile
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
Labels: size/XS

#6291 chore(Prediction): Modify ChainLink image placement on mobile
  apps/web/src/views/Predictions/Mobile.tsx
Labels: size/S

#6297 chore: remove the new GTM
  apps/web/src/pages/_app.tsx
Labels: size/S

#6200 style(Profiles): Modify BSCScanIcon placement
  apps/web/src/views/Profile/components/ProfileHeader.tsx
Labels: size/S

#6290 chore(Pools): Earned token not use uppercase
  apps/web/src/views/Pools/components/PoolCard/CardActions/index.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/Harvest.tsx
  packages/uikit/src/widgets/Pool/PoolsTable/HarvestAction.tsx
  packages/uikit/src/widgets/Pool/withCardActions.tsx
Labels: size/XS

#6299 refactor: Use mm quote count down hook
  apps/web/src/views/Swap/MMLinkPools/hooks/useDerivedSwapInfoWithMM.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMQuoteCountDown.ts
Labels: size/S

#6298 chore: v3 emoji for specific farm
  apps/web/src/components/V3SwapPromotionIcon.tsx
  apps/web/src/views/Farms/components/FarmCard/CardHeading.tsx
  apps/web/src/views/Farms/components/FarmCard/FarmCard.tsx
  apps/web/src/views/Farms/components/FarmTable/Row.tsx
Labels: size/M

#6302 chore(farm): Add STG migration warning
  apps/web/src/components/STGWarningModal/STGWarning.tsx
  apps/web/src/components/STGWarningModal/STGWarningModalContainer.tsx
  apps/web/src/components/STGWarningModal/STGWarningTooltip.tsx
  apps/web/src/components/STGWarningModal/constants.ts
  apps/web/src/components/STGWarningModal/index.tsx
  apps/web/src/components/STGWarningModal/useHasSTGLP.ts
  apps/web/src/pages/_app.tsx
  apps/web/src/views/AddLiquidity/index.tsx
  apps/web/src/views/Farms/Farms.tsx
  apps/web/src/views/Farms/components/FarmCard/CardHeading.tsx
  apps/web/src/views/Farms/components/FarmTable/Farm.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#6313 feat(Farm): List CAPS-ETH
  apps/web/public/images/1/tokens/0x03Be5C903c727Ee2C8C4e9bc0AcC860Cca4715e2.png
  packages/farms/constants/1.ts
  packages/tokens/src/1.ts
Labels: size/S, automerge

#6314 fix: add chianId for v3PromotionFarms
  apps/web/src/components/V3SwapPromotionIcon.tsx
  apps/web/src/views/Farms/components/FarmCard/CardHeading.tsx
  apps/web/src/views/Farms/components/FarmTable/Row.tsx
Labels: size/S

#6252 refactor: Show farm tags in mobile in column
  apps/web/src/views/Farms/components/FarmTable/Row.tsx
  packages/uikit/src/widgets/Farm/components/Tags/index.tsx
Labels: size/S

#6301 fix(Pools): Fix token size on mobile when token name too long
  apps/aptos/components/Pools/components/PoolTable/PoolRow.tsx
  apps/web/src/views/Pools/components/PoolsTable/Cells/NameCell.tsx
  packages/uikit/src/widgets/Pool/Cells/BaseCell.tsx
Labels: size/S

#6311 feat: Affiliates program layout (UI only)
  apps/web/next.config.mjs
  apps/web/public/images/affiliates-program/banner.png
  apps/web/public/images/affiliates-program/bobbing-1.png
  apps/web/public/images/affiliates-program/bobbing-2.png
  apps/web/public/images/affiliates-program/bobbing-3.png
  apps/web/public/images/affiliates-program/comming-soon.png
  apps/web/public/images/affiliates-program/high-commission-rates.png
  apps/web/public/images/affiliates-program/m-1.png
  apps/web/public/images/affiliates-program/m-2.png
  apps/web/public/images/affiliates-program/m-3.png
  apps/web/public/images/affiliates-program/m-4.png
  apps/web/public/images/affiliates-program/m-5.png
  apps/web/public/images/affiliates-program/perpetual.png
  apps/web/public/images/affiliates-program/personalized-support.png
  apps/web/public/images/affiliates-program/profit-sharing.png
  apps/web/public/images/affiliates-program/real-time-reporting.png
  apps/web/public/images/affiliates-program/stableSwap.png
  apps/web/public/images/affiliates-program/user-friendly-platform.png
  apps/web/src/pages/affiliates-program/dashboard.tsx
  apps/web/src/pages/affiliates-program/index.tsx
  apps/web/src/views/AffiliatesProgram/components/AffiliatesProgramLayout.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/Banner.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/ClaimReward.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/CommissionInfo.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/MyReferralLink.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/PieChartContainer.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/index.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/AffiliatesBanner.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/Benefits.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/Calculator.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/CommissionStructure.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/HowItWork.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/Question.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/RewardCalculate.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/index.tsx
  apps/web/src/views/AffiliatesProgram/utils/commisionList.tsx
  apps/web/src/views/Lottery/components/Hero.tsx
  packages/localization/src/config/translations.json
Labels: size/XXL, automerge

#6321 feat(farm/pool): List CAPS
  apps/web/public/images/tokens/0xFfBa7529AC181c2Ee1844548e6D7061c9A597dF4.png
  apps/web/src/config/constants/pools.tsx
  packages/farms/constants/56.ts
  packages/tokens/src/56.ts
Labels: size/S

#6325 chore(farm): revert STG Warning
  apps/web/src/components/STGWarningModal/STGWarning.tsx
  apps/web/src/components/STGWarningModal/STGWarningModalContainer.tsx
  apps/web/src/components/STGWarningModal/STGWarningTooltip.tsx
  apps/web/src/components/STGWarningModal/constants.ts
  apps/web/src/components/STGWarningModal/index.tsx
  apps/web/src/components/STGWarningModal/useHasSTGLP.ts
  apps/web/src/pages/_app.tsx
  apps/web/src/views/AddLiquidity/index.tsx
  apps/web/src/views/Farms/Farms.tsx
  apps/web/src/views/Farms/components/FarmCard/CardHeading.tsx
  apps/web/src/views/Farms/components/FarmTable/Farm.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#6326 feat(Vote): Update Admin Address
  apps/web/src/views/Voting/config.ts
Labels: size/XS, automerge

#6327 chore: GTM migration plan part 2
  apps/web/src/pages/_app.tsx
  apps/web/src/utils/customGTMEventTracking.ts
  apps/web/src/views/Swap/components/HotTokenList/SwapTokenTable.tsx
Labels: size/M

#6335 feat(Info): Token logo use multiple resources
  apps/aptos/components/Logo/CurrencyLogo.tsx
  apps/aptos/components/SearchModal/CurrencySearchModal.tsx
  apps/aptos/components/SearchModal/ImportRow.tsx
  apps/aptos/components/SearchModal/ImportToken.tsx
  apps/aptos/components/SearchModal/ManageLists.tsx
  apps/web/src/components/Logo/CurrencyLogo.tsx
  apps/web/src/components/SearchModal/CurrencySearchModal.tsx
  apps/web/src/components/SearchModal/ImportRow.tsx
  apps/web/src/components/SearchModal/ImportToken.tsx
  apps/web/src/components/SearchModal/ManageLists.tsx
  apps/web/src/views/Info/components/CurrencyLogo/index.tsx
  apps/web/src/views/Info/components/InfoTables/TokensTable.tsx
  apps/web/src/views/Swap/components/HotTokenList/SwapTokenTable.tsx
  packages/uikit/src/components/TokenLogo/TokenLogo.tsx
  packages/uikit/src/widgets/Swap/ImportList.tsx
  packages/uikit/src/widgets/Swap/ListLogo.tsx
Labels: size/L

#6340 chore: Remove abnbc hardcoded farm filter
  apps/web/src/views/Farms/Farms.tsx
Labels: size/XS

#6341 chore: Bump up jotai to 2.0.3
  .changeset/slow-poems-melt.md
  apps/aptos/state/transactions/reducer.ts
  apps/web/package.json
  apps/web/src/hooks/useLockedEndNotification.tsx
  apps/web/src/utils/atomWithStorageWithErrorCatch.ts
  packages/token-lists/package.json
  packages/token-lists/react/lists.ts
  yarn.lock
Labels: size/L

#6346 perf: Use is mm quoting pair once in mm hooks
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMOrderBookTrade.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMParam.ts
Labels: size/M

#6342 fix: (info): Stable Pair page token price display has missing decimals
  apps/web/src/components/PairPriceDisplay.tsx
  apps/web/src/utils/formatInfoNumbers.ts
  apps/web/src/views/Info/Pools/PoolPage.tsx
Labels: size/S

#6339 chore: try fix page view tracking for new GTM
  apps/web/src/pages/_app.tsx
Labels: size/XS

#6331 fix: MM Trade cannot be turned off after fetched
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMOrderBookTrade.ts
Labels: size/XS

#6351 fix: Temp remove metamask connector ready
  apps/web/src/config/wallet.ts
Labels: size/XS

#6352 chore(Vote): Revert Lime admin role
  apps/web/src/views/Voting/config.ts
Labels: size/XS, automerge

#6349 feat: kind reminder when MM has temporary liquidity issue
  apps/web/src/views/Swap/MMLinkPools/components/MMLiquidityWarning.tsx
  apps/web/src/views/Swap/MMLinkPools/utils/exchange.ts
  apps/web/src/views/Swap/SmartSwap/index.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#6353 feat(farm/pool): List LVL
  apps/web/public/images/tokens/0xB64E280e9D1B5DbEc4AcceDb2257A87b400DB149.png
  apps/web/src/config/constants/pools.tsx
  packages/farms/constants/56.ts
  packages/tokens/src/56.ts
Labels: size/S

#6356 feat(Aptos): LpApr get from github json
  apps/aptos/components/Farms/components/Farms.tsx
  apps/aptos/components/Farms/hooks/useLpRewardsAprs.ts
  apps/aptos/utils/farmApr.ts
Labels: size/M, automerge

#6357 fix: Show unknown risk when token is not in token lists
  apps/web/src/views/Swap/components/AccessRisk/index.tsx
  apps/web/src/views/Swap/hooks/fetchTokenRisk.ts
  packages/localization/src/config/translations.json
Labels: size/M

#6305 chore(Swap): Fix horizontal drag issue on mobile
  apps/web/src/views/Swap/styles.tsx
Labels: size/XS

#6364 chore: List unw
  apps/web/public/images/tokens/0x5b65cd9feb54F1Df3D0C60576003344079f8Dc06.png
  apps/web/src/config/constants/pools.tsx
  packages/farms/constants/56.ts
  packages/tokens/src/56.ts
Labels: size/S, automerge

#6363 feat: Implement unknown risk only when risk below high
  apps/web/src/views/Swap/components/AccessRisk/index.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#6365 chore: Update XCAD token address
  apps/web/public/images/tokens/0xa026Ad2ceDa16Ca5FC28fd3C72f99e2C332c8a26.png
  apps/web/public/images/tokens/0xa026Ad2ceDa16Ca5FC28fd3C72f99e2C332c8a26.svg
  apps/web/src/config/constants/swapWarningTokens.ts
  apps/web/src/config/constants/warningTokens.ts
  apps/web/src/views/Swap/components/SwapWarningModal/XCADWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/index.tsx
  packages/localization/src/config/translations.json
  packages/tokens/src/56.ts
Labels: size/M

#6371 feat: Space id integration
  apps/web/package.json
  apps/web/src/components/Menu/UserMenu/WalletInfo.tsx
  apps/web/src/components/Menu/UserMenu/index.tsx
  apps/web/src/config/abi/SID.json
  apps/web/src/config/abi/SIDResolver.json
  apps/web/src/hooks/useContract.ts
  apps/web/src/hooks/useSid.ts
  apps/web/src/hooks/useUsernameWithVisibility.ts
  apps/web/src/state/profile/hooks.ts
  apps/web/src/utils/contractHelpers.ts
  apps/web/src/utils/namehash.ts
  apps/web/src/views/FarmAuction/components/WhitelistedBiddersModal.tsx
  apps/web/src/views/Home/components/UserBanner/UserDetail.tsx
  apps/web/src/views/Info/components/InfoTables/TransactionsTable.tsx
  apps/web/src/views/Nft/market/components/Activity/MobileModal.tsx
  apps/web/src/views/Nft/market/components/ProfileCell.tsx
  apps/web/src/views/Pottery/components/FinishedRounds/AllHistoryCard/Winner.tsx
  apps/web/src/views/Predictions/Leaderboard/components/Results/RankingCard.tsx
  apps/web/src/views/Predictions/Leaderboard/components/Results/ResultAvatar.tsx
  apps/web/src/views/Predictions/Leaderboard/components/WalletStatsModal.tsx
  apps/web/src/views/Profile/components/ProfileHeader.tsx
  apps/web/src/views/TradingCompetition/components/RegisterModal/RegisterWithProfile.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TopTradersCard/ExpandedGridItem.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TopTradersCard/GridItem.tsx
  apps/web/src/views/TradingCompetition/components/YourScore/CardUserInfo.tsx
Labels: size/XL

#6375 feat: List ID
  apps/web/public/images/tokens/0x2dfF88A56767223A5529eA5960Da7A3F5f766406.png
  apps/web/src/config/constants/pools.tsx
  packages/farms/constants/56.ts
  packages/tokens/src/56.ts
Labels: size/S, automerge

#6374 chore: Update next
  apis/og-image/.eslintrc.json
  apis/og-image/.gitignore
  apis/og-image/README.md
  apis/og-image/components/nft-collection.tsx
  apis/og-image/components/nft.tsx
  apis/og-image/components/swap.tsx
  apis/og-image/components/voting.tsx
  apis/og-image/config.ts
  apis/og-image/next-env.d.ts
  apis/og-image/next.config.js
  apis/og-image/package.json
  apis/og-image/pages/api/v1/[template].tsx
  apis/og-image/tsconfig.json
  apps/aptos/next.config.mjs
  apps/aptos/package.json
  apps/blog/next.config.mjs
  apps/blog/package.json
  apps/bridge/package.json
  apps/web/next.config.mjs
  apps/web/package.json
  package.json
  packages/ui/package.json
  packages/uikit/package.json
  yarn.lock
Labels: size/XXL

#6207 chore: Modify QuestionHelper's tooltip placement
  apps/aptos/components/Menu/Settings/SettingsModal.tsx
  apps/aptos/components/Swap/AdvancedSwapDetails.tsx
  apps/web/src/components/App/AppHeader.tsx
  apps/web/src/components/Menu/GlobalSettings/GasSettings.tsx
  apps/web/src/components/Menu/GlobalSettings/SettingsModal.tsx
  apps/web/src/components/Menu/GlobalSettings/TransactionSettings.tsx
  apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
  apps/web/src/views/Swap/components/AdvancedSwapDetails.tsx
  packages/uikit/src/widgets/Liquidity/LiquidityCardHeader.tsx
Labels: size/M

#6372 feat(Aptos): Update wording
  apps/aptos/public/images/ifos/assets/ifo-coming-soon.png
  packages/localization/src/config/translations.json
  packages/uikit/src/components/RoiCalculatorModal/RoiCalculatorFooter.tsx
Labels: size/M, automerge

#6373 feat(Blog): New Blog add Card UI
  apps/blog/components/NewBlog.tsx
Labels: size/M, automerge

#6384 chore: Remove buffer
  apps/web/package.json
  apps/web/src/hooks/useSid.ts
  apps/web/src/utils/namehash.ts
Labels: size/M

#6398 chore: List hay-usdt stable pair
  packages/smart-router/evm/constants/stableSwap/56.ts
Labels: size/S

#6395 chore: Add fetcher to sdk
  .changeset/slow-phones-exercise.md
  packages/swap-sdk/src/fetcher.ts
Labels: size/M

#6392 chore(aptos-Farms): Modify filters placement
  apps/aptos/components/Farms/components/Farms.tsx
Labels: size/S

#6400 chore: Bump sentry
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/sentry.edge.config.js
  yarn.lock
Labels: size/L

#6402 feat: List RDNT
  apps/web/public/images/tokens/0xf7DE7E8A6bd59ED41a4b5fe50278b3B7f31384dF.png
  apps/web/src/config/constants/pools.tsx
  packages/farms/constants/56.ts
  packages/tokens/src/56.ts
Labels: size/S, automerge

#6403 feat: Remove RDNT-BNB LP
  apps/web/src/config/constants/priceHelperLps/pools/56.ts
  packages/farms/constants/56.ts
Labels: size/S, automerge

#6334 feat: Connect Affiliate API
  apps/blog/utils/api.ts
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/public/images/affiliates-program/high-commission-rates.png
  apps/web/public/images/affiliates-program/partner.png
  apps/web/public/images/affiliates-program/slider/1.png
  apps/web/public/images/affiliates-program/slider/2.png
  apps/web/public/images/affiliates-program/slider/3.png
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/config/constants/affiliatesProgram.ts
  apps/web/src/pages/api/affiliates-program/affiliate-exist.ts
  apps/web/src/pages/api/affiliates-program/affiliate-fee-create.ts
  apps/web/src/pages/api/affiliates-program/affiliate-fee-exist.ts
  apps/web/src/pages/api/affiliates-program/affiliate-info.ts
  apps/web/src/pages/api/affiliates-program/affiliate-login.ts
  apps/web/src/pages/api/affiliates-program/affiliate-nonce.ts
  apps/web/src/pages/api/affiliates-program/user-exist.ts
  apps/web/src/pages/api/affiliates-program/user-register-fee.ts
  apps/web/src/utils/clearUserStates.ts
  apps/web/src/views/AffiliatesProgram/components/AffiliatesProgramLayout.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/AffiliateLinks.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/Banner.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/ClaimReward.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/ComingSoon.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/CommissionInfo.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/LoginButton.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/MyReferralLink.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/index.tsx
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/Congratulations.tsx
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/DesktopView.tsx
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/MobileView.tsx
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/StepIntro.tsx
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/WelcomePage.tsx
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/index.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/AffiliatesBanner.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/Benefits.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/Calculator.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/CommissionStructure.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/HowItWork.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/Question.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/RewardCalculate.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/index.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useAuthAffiliate.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useAuthAffiliateExist.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useDefaultLinkId.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useUserExist.tsx
  apps/web/src/views/AffiliatesProgram/utils/commisionList.tsx
  packages/localization/src/config/translations.json
  yarn.lock
Labels: size/XXL, automerge

#6405 feat: Prod cookie domain
  apps/web/src/config/constants/affiliatesProgram.ts
Labels: size/XS, automerge

#6406 feat: Show OnBoardingModal
  apps/web/src/views/AffiliatesProgram/components/Overview/index.tsx
Labels: size/XS, automerge

#6408 feat: add us citizen confirm modal for perpetual submenu
  packages/uikit/src/components/SubMenuItems/SubMenuItems.tsx
  packages/uikit/src/components/SubMenuItems/types.ts
Labels: size/XS

#6407 fix: Info chart warning when hover
  apps/web/src/views/Info/components/InfoCharts/BarChart/index.tsx
  apps/web/src/views/Info/components/InfoCharts/LineChart/index.tsx
  apps/web/src/views/Info/hooks/useChartCallbacks.ts
Labels: size/M

#6411 feat: List RDNT-BNB LP
  apps/web/src/config/constants/priceHelperLps/pools/56.ts
  packages/farms/constants/56.ts
Labels: size/S, automerge

#6412 fix: BSC wallet sign message only accept string
  apps/web/src/config/constants/affiliatesProgram.ts
  apps/web/src/views/AffiliatesProgram/components/Dashboard/MyReferralLink.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/index.tsx
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/index.tsx
Labels: size/M, automerge

#6416 feat: Add log
  apps/web/src/config/constants/affiliatesProgram.ts
Labels: size/XS, automerge

#6419 fix: User exist
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/index.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useUserExist.tsx
Labels: size/XS, automerge

#6417 chore: Bump wagmi
  apps/bridge/package.json
  apps/web/package.json
  apps/web/src/components/NetworkSwitcher.tsx
  apps/web/src/config/wallet.ts
  apps/web/src/hooks/limitOrders/useGelatoLimitOrdersLib.ts
  apps/web/src/utils/wagmi.ts
  packages/wagmi/connectors/binanceWallet/binanceWallet.ts
  packages/wagmi/package.json
  yarn.lock
Labels: size/XXL

#6420 feat: Add nickname and ablePerps
  apps/web/src/views/AffiliatesProgram/components/Dashboard/AffiliateLinks.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/MyReferralLink.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/index.tsx
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/Congratulations.tsx
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/DesktopView.tsx
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/MobileView.tsx
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/WelcomePage.tsx
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/index.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useAuthAffiliate.tsx
  apps/web/src/views/AffiliatesProgram/utils/commisionList.tsx
  packages/localization/src/config/translations.json
Labels: size/L, automerge

#6421 fix: Nested a warnings
  apps/web/src/components/Menu/UserMenu/ProfileUserMenuItem.tsx
  apps/web/src/components/Menu/UserMenu/index.tsx
  apps/web/src/components/NetworkModal/PageNetworkSupportModal.tsx
  apps/web/src/views/PancakeSquad/components/EventDescriptionSection/config.tsx
  apps/web/src/views/PancakeSquad/components/EventStepsSection/index.tsx
  apps/web/src/views/PancakeSquad/components/Header/index.tsx
  apps/web/src/views/Pool/index.tsx
  apps/web/src/views/Predictions/components/Menu.tsx
  apps/web/src/views/Teams/Team.tsx
  apps/web/src/views/Teams/components/NoProfileCard.tsx
  apps/web/src/views/Teams/components/TeamListCard.tsx
  apps/web/src/views/Voting/Proposal/Overview.tsx
  packages/uikit/src/components/NotFound/NotFound.tsx
  packages/uikit/src/widgets/Liquidity/FindOtherLP.tsx
  packages/uikit/src/widgets/Liquidity/LiquidityCardHeader.tsx
Labels: size/M

#6390 chore: Use pcs rpc for zap estimate
  apps/web/src/state/mint/hooks.ts
Labels: size/XS

#6389 chore(NFT): Filter row noWarp on mobile
  apps/web/src/views/Nft/market/ActivityHistory/ActivityFilters.tsx
  apps/web/src/views/Nft/market/Collection/Items/Filters.tsx
Labels: size/S

#6424 feat: Update link
  apps/web/src/views/AffiliatesProgram/components/Dashboard/MyReferralLink.tsx
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/WelcomePage.tsx
  packages/localization/src/config/translations.json
Labels: size/M, automerge

#6426 fix: Testnet check chain undefined
  apps/web/src/utils/wagmi.ts
Labels: size/XS

#6427 revert: wagmi version
  apps/bridge/package.json
  apps/web/package.json
  apps/web/src/config/wallet.ts
  apps/web/src/utils/wagmi.ts
  packages/wagmi/package.json
  yarn.lock
Labels: size/XL

#6428 fix: (farms): Enable contract couldn't refresh view after approval
  apps/web/src/state/farms/index.ts
Labels: size/XS

#6429 feat(farm/pool): List HAY
  apps/web/src/config/constants/pools.tsx
  packages/farms/constants/56.ts
Labels: size/S

#6430 chore: update pid for HAY-USDT farm
  packages/farms/constants/56.ts
Labels: size/XS

#6432 fix: Reverse pools apr
  apps/web/src/state/pools/hooks.ts
Labels: size/XS
