Repository pancakeswap/pancake-frontend, pull requests merged in 2023-10, with the labels that each got.

#8017 fix: (affiliate modal): Non-Affiliate modal agreement modal can be closed without accepting it
  apps/web/src/views/AffiliatesProgram/components/Dashboard/AffiliateModal/NonAffiliateModal.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/AffiliateModal/index.tsx
Labels: size/S

#8014 fix: Transaction confirmations got stuck intermittently
  apps/web/src/state/transactions/updater.tsx
Labels: size/S

#8011 chore: Bump up swiper
  apps/aptos/package.json
  apps/blog/package.json
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/S

#8007 chore: Export chain id from v2 sdk
  .changeset/curvy-drinks-remain.md
  packages/swap-sdk/src/index.ts
Labels: size/XS

#8025 style(prediction): Fix style problem
  apps/web/src/views/Predictions/components/JupiterPredictors.tsx
  apps/web/src/views/Predictions/components/Menu.tsx
  apps/web/src/views/Predictions/components/MobileMenu.tsx
Labels: size/S, automerge

#8018 fix: (affiliate): Affiliate api's when development mode and improve wrong url check on prod
  apps/web/src/pages/api/affiliates-program/affiliate-claim-fee.ts
  apps/web/src/pages/api/affiliates-program/affiliate-claim-list.ts
  apps/web/src/pages/api/affiliates-program/affiliate-exist.ts
  apps/web/src/pages/api/affiliates-program/affiliate-fee-create.ts
  apps/web/src/pages/api/affiliates-program/affiliate-fee-exist.ts
  apps/web/src/pages/api/affiliates-program/affiliate-info.ts
  apps/web/src/pages/api/affiliates-program/affiliate-login.ts
  apps/web/src/pages/api/affiliates-program/affiliate-nonce.ts
  apps/web/src/pages/api/affiliates-program/affiliate-regenerate-signature.ts
  apps/web/src/pages/api/affiliates-program/leader-board.ts
  apps/web/src/pages/api/affiliates-program/user-claim-fee.ts
  apps/web/src/pages/api/affiliates-program/user-claim-list.ts
  apps/web/src/pages/api/affiliates-program/user-exist.ts
  apps/web/src/pages/api/affiliates-program/user-info.ts
  apps/web/src/pages/api/affiliates-program/user-regenerate-signature.ts
  apps/web/src/pages/api/affiliates-program/user-register-fee.ts
Labels: size/M

#8027 feat: remove moonpay during maintence hours
  apps/web/src/views/BuyCrypto/components/AccordionDropdown/Accordion.tsx
Labels: size/S

#8026 feat: add galxe banners
  apps/web/src/hooks/useViewport.ts
  apps/web/src/views/Home/components/Banners/GalxePedictBanner.tsx
  apps/web/src/views/Home/components/Banners/GalxeSyndicateBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  apps/web/src/views/Home/components/Banners/images/galaxe-pancake-banner-logo.png
  apps/web/src/views/Home/components/Banners/images/galxe-predictors-bg.png
  apps/web/src/views/Home/components/Banners/images/galxe-predictors-bunny.png
  apps/web/src/views/Home/components/Banners/images/galxe-syndicate-bg.png
  apps/web/src/views/Home/components/Banners/images/galxe-syndicate-bunny.png
  apps/web/src/views/Home/components/Banners/images/galxeBirthdayCampaignBg.png
  apps/web/src/views/Home/components/Banners/images/galxeMobileBunnny2.png
  apps/web/src/views/Home/components/Banners/images/galxeMobileBunny1.png
  apps/web/src/views/Home/components/Banners/images/galxePredictorsBg.png
  apps/web/src/views/Home/components/Banners/images/galxeSyndicateBg.png
  apps/web/src/views/Home/components/Banners/images/index.ts
  packages/localization/src/config/translations.json
Labels: size/L

#8035 chore: update transak logo to new one
  apps/web/public/images/on-ramp-providers/transak-offical-logo.png
  apps/web/src/views/BuyCrypto/Icons/index.tsx
Labels: size/XS

#8034 chore: change galxe mobile banner text
  apps/web/src/views/Home/components/Banners/GalxePedictBanner.tsx
  apps/web/src/views/Home/components/Banners/GalxeSyndicateBanner.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#8036 feat: Add Simple Staking
  apps/web/src/views/Home/components/EcoSystemSection/index.tsx
  packages/localization/src/config/translations.json
Labels: size/S, automerge

#8039 fix: (menu): Submenu link status and arrow notification dot on mobile
  packages/uikit/src/components/SubMenuItems/SubMenuItems.tsx
  packages/uikit/src/components/SubMenuItems/types.ts
Labels: size/S

#8009 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XXL

#8047 feat: List new zksync farms
  packages/farms/constants/324.ts
  packages/tokens/src/324.ts
Labels: size/M

#8056 fix: wallachain & mixed route trade builder fix
  apps/web/src/views/Swap/V3Swap/containers/SwapCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useSwapCallArguments.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSwapCallback.ts
  packages/smart-router/evm/v3-router/index.ts
  packages/uikit/vite.config.ts.timestamp-1696789971802-e89100b471c52.mjs
  packages/uikit/vite.config.ts.timestamp-1696790098529-e744416f1bc19.mjs
  packages/uikit/vite.config.ts.timestamp-1696790735929-eb34651d6adc8.mjs
  packages/uikit/vite.config.ts.timestamp-1696790756612-e4aba8918fb24.mjs
  packages/uikit/vite.config.ts.timestamp-1696790795782-f734d8878b8a2.mjs
  packages/universal-router-sdk/src/SwapRouterPancake.ts
  packages/universal-router-sdk/src/entities/protocols/pancakeswap.ts
  packages/universal-router-sdk/src/index.ts
  packages/universal-router-sdk/test/trade.test.ts
  packages/universal-router-sdk/tsconfig.json
Labels: size/XXL

#8052 fix: (buy-crypto): Buy crypto return to input page instead of query when closing fiat on ramp modal
  apps/web/src/components/Card/index.tsx
  apps/web/src/components/FiatOnRampModal/FiatOnRampModal.tsx
  apps/web/src/views/BuyCrypto/components/AccordionDropdown/AccordionItem.tsx
Labels: size/M

#8048 feat: remove moonpay block
  apps/web/src/views/BuyCrypto/hooks/usePriceQuoter.ts
Labels: size/S

#8051 chore(aptos-Swap): Adjustment tokenlogo margin
  apps/aptos/components/CurrencyInputPanel/index.tsx
Labels: size/XS

#8024 chore: Enable BNB
  apps/web/src/views/FixedStaking/constant.ts
Labels: size/XS

#8040 chore: Bump viem and wagmi
  apis/farms/package.json
  apis/routing/package.json
  apps/bridge/package.json
  apps/web/package.json
  apps/web/src/config/chains.ts
  apps/web/src/hooks/useCallWithGasPrice.ts
  packages/farms/package.json
  packages/multicall/package.json
  packages/pools/package.json
  packages/smart-router/package.json
  packages/swap-sdk/package.json
  packages/uikit/package.json
  packages/v3-sdk/package.json
  packages/wagmi/package.json
  packages/widgets-internal/package.json
  pnpm-lock.yaml
  scripts/package.json
Labels: size/L

#8061 fix: permit2 compile
  packages/permit2-sdk/src/abis/Permit2.json
  packages/permit2-sdk/src/index.ts
Labels: size/XS

#8000 test: universal router v3 & mix
  packages/universal-router-sdk/package.json
  packages/universal-router-sdk/src/SwapRouterPancake.ts
  packages/universal-router-sdk/src/index.ts
  packages/universal-router-sdk/test/__snapshots__/trade.test.ts.snap
  packages/universal-router-sdk/test/fixtures/address.ts
  packages/universal-router-sdk/test/fixtures/constants/abi.ts
  packages/universal-router-sdk/test/fixtures/constants/tokens.ts
  packages/universal-router-sdk/test/trade.test.ts
  packages/universal-router-sdk/test/utils/buildTrade.ts
Labels: size/XL, automerge

#8063 fix: typo
  apps/web/src/views/Swap/V3Swap/hooks/useSwapCallArguments.ts
Labels: size/XS

#8065 Revert "chore: Enable BNB"
  apps/web/src/views/FixedStaking/constant.ts
Labels: size/XS

#8068 chore: Update landing wording
  apps/web/src/views/Home/components/MetricsSection/index.tsx
  packages/localization/src/config/translations.json
Labels: size/S, automerge

#8067 fix: permit2 structure type
  packages/permit2-sdk/src/allowanceTransfer.ts
  packages/permit2-sdk/src/domain.ts
  packages/permit2-sdk/src/signatureTransfer.ts
  packages/permit2-sdk/src/utils/types.ts
  packages/permit2-sdk/tsup.config.ts
  packages/universal-router-sdk/test/utils/permit.ts
Labels: size/M

#8069 ci: use strictNullChecks locally
  .github/workflows/tsCheck.yml
  apps/web/next.config.mjs
  apps/web/tsconfig.build.json
  apps/web/tsconfig.json
Labels: size/XS

#8070 feat: Revert chain svg color
  apps/web/src/views/Home/components/MetricsSection/ChainTags.tsx
  packages/uikit/src/components/Svg/Icons/Base.tsx
  packages/uikit/src/components/Svg/Icons/BinanceChain.tsx
  packages/uikit/src/components/Svg/Icons/ZkEVM.tsx
Labels: size/M, automerge

#8073 chore: Bump action version
  .github/workflows/tsCheck.yml
  apps/web/tsconfig.json
Labels: size/S

#8071 chore: remove all unnessecary files
  packages/permit2-sdk/.gitattributes
  packages/permit2-sdk/.github/workflows/forge-tests.yml
  packages/permit2-sdk/.github/workflows/lint.yml
  packages/permit2-sdk/.github/workflows/unit-tests.yml
  packages/permit2-sdk/.gitmodules
  packages/permit2-sdk/.vscode/settings.json
  packages/permit2-sdk/foundry.toml
  packages/permit2-sdk/remappings.txt
  packages/permit2-sdk/test/Permit2.t.sol
  packages/permit2-sdk/test/interop.json
  packages/permit2-sdk/test/mock/MockERC20.sol
  packages/permit2-sdk/test/mock/MockWitness.sol
  packages/permit2-sdk/tsconfig.json
  packages/permit2-sdk/writeInterop.js
  packages/universal-router-sdk/hardhat.config.ts
  packages/universal-router-sdk/package.json
  packages/universal-router-sdk/src/entities/protocols/pancakeswap.ts
  packages/universal-router-sdk/src/utils/numbers.ts
  pnpm-lock.yaml
Labels: size/XXL

#8072 fix: remove bsc usdt warning
  apps/web/src/views/BuyCrypto/components/AccordionDropdown/Accordion.tsx
  apps/web/src/views/BuyCrypto/constants.ts
  apps/web/src/views/BuyCrypto/containers/BuyCryptoForm.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#8078 feat: Move Eth finished Pools
  packages/pools/src/constants/pools/1.ts
Labels: size/S, automerge

#8075 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/M

#8001 feat: update top pair spam strategy
  apps/web/src/views/Info/Overview/index.tsx
  apps/web/src/views/Info/Pools/index.tsx
  apps/web/src/views/Info/components/InfoCharts/HoverableChart.tsx
  apps/web/src/views/Info/components/InfoTables/TransactionsTable.tsx
  apps/web/src/views/Info/hooks/usePoolsData.ts
Labels: size/M

#8079 fix: Missing token logo image on opbnb
  packages/widgets-internal/components/CurrencyLogo/utils.ts
Labels: size/M

#8083 chore: Resolve conflict
  apps/web/src/views/Swap/V3Swap/hooks/useSwapCallArguments.ts
  pnpm-lock.yaml
Labels: size/M

#8085 fix: strictNullChecks errors
  apps/web/src/components/AddToWallet/AddToWalletButton.tsx
  apps/web/src/state/swap/reducer.ts
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/components/SwapModalFooter.tsx
  apps/web/src/views/Swap/V3Swap/components/TransactionConfirmSwapContent.tsx
  apps/web/src/views/Swap/V3Swap/containers/ConfirmSwapModal.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalState.tsx
  apps/web/src/views/Swap/components/SwapModalHeader.tsx
  packages/widgets-internal/swap/ApproveModalContent.tsx
  packages/widgets-internal/swap/SwapPendingModalContent.tsx
  packages/widgets-internal/swap/TokenTransferInfo.tsx
Labels: size/M

#8086 chore: sync develop
  apps/web/src/components/AddToWallet/AddToWalletButton.tsx
  apps/web/src/state/swap/reducer.ts
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/components/SwapModalFooter.tsx
  apps/web/src/views/Swap/V3Swap/components/TransactionConfirmSwapContent.tsx
  apps/web/src/views/Swap/V3Swap/containers/ConfirmSwapModal.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalState.tsx
  apps/web/src/views/Swap/components/SwapModalHeader.tsx
  packages/widgets-internal/swap/ApproveModalContent.tsx
  packages/widgets-internal/swap/SwapPendingModalContent.tsx
  packages/widgets-internal/swap/TokenTransferInfo.tsx
Labels: size/M

#8088 fix: Invalid date when creating proposal
  apps/web/src/views/Voting/CreateProposal/helpers.ts
Labels: size/XS

#8090 fix: Format of dayjs dates
  apps/aptos/views/Ifos/components/IfoVesting/VestingPeriod/Info.tsx
  apps/web/src/utils/formatTime.ts
  apps/web/src/views/FixedStaking/components/StakedPositionSection.tsx
  apps/web/src/views/Ifos/components/IfoVesting/VestingPeriod/Info.tsx
  apps/web/src/views/Info/components/InfoCharts/CandleChart/index.tsx
  apps/web/src/views/Voting/Proposal/Details.tsx
  packages/uikit/src/widgets/Ifo/IfoProgressStepper.tsx
  packages/uikit/src/widgets/Ifo/IfoVestingFooter.tsx
Labels: size/S

#8087 refactor: Switch to use chain names for configuration files
  .changeset/angry-islands-dream.md
  apps/web/src/config/__tests__/farms.test.ts
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/TradingReward/config/pairs/index.tsx
  packages/chains/src/chainId.ts
  packages/chains/src/chainNames.ts
  packages/chains/src/index.ts
  packages/farms/constants/arb.ts
  packages/farms/constants/base.ts
  packages/farms/constants/bsc.ts
  packages/farms/constants/bscTestnet.ts
  packages/farms/constants/eth.ts
  packages/farms/constants/goerli.ts
  packages/farms/constants/index.ts
  packages/farms/constants/linea.ts
  packages/farms/constants/polygonZkEVM.ts
  packages/farms/constants/polygonZkEVMTestnet.ts
  packages/farms/constants/v3/index.ts
  packages/farms/constants/zkSync.ts
  packages/farms/constants/zkSyncTestnet.ts
  packages/farms/scripts/build.ts
Labels: size/L

#8033 chore: Add more nodes and increase zkSync success rate
  apps/web/src/config/nodes.ts
  apps/web/src/utils/nodeReal.ts
  packages/smart-router/evm/v3-router/providers/onChainQuoteProvider.ts
Labels: size/M

#8096 perf: Increase zksync refresh interval
  apps/web/src/config/pools.ts
Labels: size/XS

#8008 feat: improve UI on approval swap step flow
  apps/web/src/hooks/usePermit2Allowance.ts
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/containers/ConfirmSwapModal.tsx
  apps/web/src/views/Swap/V3Swap/containers/SwapCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalState.tsx
  apps/web/src/views/Swap/V3Swap/types.ts
  packages/localization/src/config/translations.json
  packages/permit2-sdk/src/constants.ts
  packages/uikit/vite.config.ts.timestamp-1696936363894-5dc1a2d69cefe.mjs
  packages/widgets-internal/swap/ApproveModalContent.tsx
  packages/widgets-internal/swap/Logos.tsx
  packages/widgets-internal/swap/SwapPendingModalContent.tsx
  packages/widgets-internal/swap/SwapTransactionReceiptModalContent.tsx
  packages/widgets-internal/swap/TransactionErrorContent.tsx
  packages/widgets-internal/swap/assets/permitIcon.svg
  packages/widgets-internal/swap/index.ts
  packages/widgets-internal/swap/styles.tsx
  packages/widgets-internal/swap/useUnmountingAnimation.ts
Labels: size/XXL

#8099 fix: Incorrect date time on simple staking
  apps/web/src/utils/formatTime.ts
  apps/web/src/views/FixedStaking/components/ClaimModal.tsx
  apps/web/src/views/FixedStaking/components/FixedStakingOverview.tsx
  apps/web/src/views/FixedStaking/components/StakedLimitEndOn.tsx
Labels: size/M

#8101 fix: Unix timestamp issues
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/pages/swap.tsx
  apps/web/src/utils/getNow.ts
  apps/web/src/utils/getNowInSeconds.ts
  apps/web/src/views/FarmAuction/components/AuctionLeaderboard/AuctionProgress.tsx
  apps/web/src/views/Ifos/components/IfoVesting/VestingPeriod/Info.tsx
  apps/web/src/views/Predictions/components/RoundCard/LiveRoundCard.tsx
  apps/web/src/views/Predictions/components/RoundCard/OpenRoundCard.tsx
  apps/web/src/views/Predictions/hooks/useCountdown.ts
  packages/uikit/src/widgets/Ifo/IfoProgressStepper.tsx
  packages/utils/user/phishingBanner.ts
Labels: size/M

#8097 feat(test): calldata serializer
  packages/universal-router-sdk/src/SwapRouterPancake.ts
  packages/universal-router-sdk/src/abis/UniversalRouter.json
  packages/universal-router-sdk/src/abis/UniversalRouter.ts
  packages/universal-router-sdk/test/__snapshots__/trade.test.ts.snap
  packages/universal-router-sdk/test/trade.test.ts
  packages/universal-router-sdk/test/utils/calldataDecode.ts
Labels: size/XXL

#8100 feat: support opbnb info page
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/state/info/constant.ts
  apps/web/src/state/info/hooks.ts
  apps/web/src/views/Info/components/InfoNav/index.tsx
  apps/web/src/views/V3Info/components/Layout/InfoNav.tsx
  apps/web/src/views/V3Info/constants.ts
Labels: size/M

#8080 chore: cleanup config file & lint & ts check
  .gitignore
  apps/web/src/hooks/useGetENSAddressByName.ts
  apps/web/src/hooks/usePermit2Allowance.ts
  apps/web/src/hooks/usePermitAllowance.ts
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/containers/MMCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useSwapCallArguments.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSwapCallback.ts
  packages/permit2-sdk/.gitignore
  packages/permit2-sdk/package.json
  packages/permit2-sdk/pnpm-lock.yaml
  packages/permit2-sdk/src/abis/Permit2.json
  packages/permit2-sdk/src/abis/Permit2.ts
  packages/permit2-sdk/src/allowanceTransfer.ts
  packages/permit2-sdk/src/index.ts
  packages/permit2-sdk/src/signatureTransfer.ts
  packages/permit2-sdk/tsconfig.json
  packages/uikit/vite.config.ts.timestamp-1696787831007-2e1e19f3215e.mjs
  packages/uikit/vite.config.ts.timestamp-1696787850844-a0e7f7e1808e.mjs
  packages/uikit/vite.config.ts.timestamp-1696787905367-e33a932a60ee9.mjs
  packages/uikit/vite.config.ts.timestamp-1696788146919-75ba01c190049.mjs
  packages/uikit/vite.config.ts.timestamp-1696788232566-f293f831a4766.mjs
  packages/uikit/vite.config.ts.timestamp-1696788252763-234b24f05dbb2.mjs
  packages/uikit/vite.config.ts.timestamp-1696788266954-3197ce69c9b34.mjs
  packages/uikit/vite.config.ts.timestamp-1696788301650-4a0707319b0ab.mjs
  packages/uikit/vite.config.ts.timestamp-1696788447992-0824dd0d5c65d.mjs
  packages/uikit/vite.config.ts.timestamp-1696789971802-e89100b471c52.mjs
  packages/uikit/vite.config.ts.timestamp-1696790098529-e744416f1bc19.mjs
  packages/uikit/vite.config.ts.timestamp-1696790735929-eb34651d6adc8.mjs
  packages/uikit/vite.config.ts.timestamp-1696790756612-e4aba8918fb24.mjs
  packages/uikit/vite.config.ts.timestamp-1696790795782-f734d8878b8a2.mjs
  packages/uikit/vite.config.ts.timestamp-1696936363894-5dc1a2d69cefe.mjs
  packages/universal-router-sdk/.gitignore
  packages/universal-router-sdk/package.json
  packages/universal-router-sdk/src/SwapRouterPancake.ts
  packages/universal-router-sdk/src/entities/protocols/pancakeswap.ts
  packages/universal-router-sdk/src/entities/protocols/unwrapWETH.ts
  packages/universal-router-sdk/src/index.ts
  packages/universal-router-sdk/src/utils/inputTokens.ts
  packages/universal-router-sdk/src/utils/routerCommands.ts
  packages/universal-router-sdk/src/utils/types.ts
  packages/universal-router-sdk/test/fixtures/address.ts
  packages/universal-router-sdk/test/fixtures/constants/chains.ts
  packages/universal-router-sdk/test/trade.test.ts
  packages/universal-router-sdk/test/utils/buildTrade.ts
  packages/universal-router-sdk/test/utils/permit.ts
  packages/universal-router-sdk/tsconfig.json
  packages/universal-router-sdk/tsup.config.ts
  pnpm-lock.yaml
Labels: size/XXL

#8102 ci: upgrade min node version support
  .github/workflows/lintPrTitle.yml
Labels: size/XS

#8062 feat: Remove v3 migration banner
  apps/web/src/config/constants/supportChains.ts
  apps/web/src/pages/liquidity/index.tsx
  apps/web/src/pages/migration.tsx
  apps/web/src/utils/isV3MigrationSupported.ts
  apps/web/src/views/Farms/Farms.tsx
  apps/web/src/views/Farms/FarmsV3.tsx
  apps/web/src/views/Farms/context.ts
  apps/web/src/views/Farms/utils/getStakedFarms.ts
  apps/web/src/views/Farms/utils/getStakedMinProgramFarms.ts
  apps/web/src/views/Home/components/Banners/FarmV3MigrationBanner.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/widgets/Liquidity/FindOtherLP.tsx
Labels: size/L, automerge

#8103 fix: stable swap command
  packages/universal-router-sdk/src/entities/protocols/pancakeswap.ts
  packages/universal-router-sdk/test/__snapshots__/trade.test.ts.snap
Labels: size/L

#8107 fix: Fail to execute update lp apr script
  scripts/updateLPsAPR.ts
Labels: size/XS

#8108 chore: Disable staking and unstaking buttons
  apps/web/src/views/FixedStaking/components/FixedStakingCard.tsx
  apps/web/src/views/FixedStaking/components/FixedStakingRow.tsx
  apps/web/src/views/FixedStaking/components/StakedPositionSection.tsx
  apps/web/src/views/FixedStaking/index.tsx
Labels: size/M

#8109 feat: List new alp pool
  packages/pools/src/constants/pools/42161.ts
Labels: size/XS, automerge

#8111 chore: Upgrade next axiom
  apps/aptos/package.json
  apps/blog/package.json
  apps/bridge/package.json
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/M

#8112 fix: middle route recipient
  packages/universal-router-sdk/src/entities/protocols/pancakeswap.ts
  packages/universal-router-sdk/src/utils/constants.ts
  packages/universal-router-sdk/test/__snapshots__/trade.test.ts.snap
Labels: size/L

#8104 fix: Blog similar articles item width
  apps/blog/components/Article/SingleArticle/SimilarArticles.tsx
  apps/blog/components/ChefsChoice/index.tsx
  apps/blog/pages/api/articles.tsx
  apps/blog/pages/articles/[slug].tsx
  apps/web/src/pages/_app.tsx
Labels: size/S, automerge

#8114 feat: Update changeset
  .changeset/violet-geese-count.md
  packages/pools/src/constants/pools/42161.ts
Labels: size/S, automerge

#8113 feat: add esDRNT on binance
  packages/tokens/src/56.ts
Labels: size/XS

#8116 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#8122 revert: Disable staking and unstaking buttons (#8108)
  apps/web/src/views/FixedStaking/components/FixedStakingCard.tsx
  apps/web/src/views/FixedStaking/components/FixedStakingRow.tsx
  apps/web/src/views/FixedStaking/components/StakedPositionSection.tsx
  apps/web/src/views/FixedStaking/index.tsx
Labels: size/M

#8123 feat: List TWT-BNB farm
  packages/farms/constants/bsc.ts
Labels: size/XS, automerge

#8117 feat: review comments
  apps/web/src/hooks/usePermitAllowance.ts
  apps/web/src/views/Swap/V3Swap/containers/MMCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/containers/SwapCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useSwapCallArguments.ts
  packages/permit2-sdk/src/constants.ts
  packages/universal-router-sdk/.eslintrc
  packages/universal-router-sdk/.prettierignore
  packages/universal-router-sdk/package.json
  packages/universal-router-sdk/src/SwapRouterPancake.ts
  packages/universal-router-sdk/src/abis/ERC20.json
  packages/universal-router-sdk/src/abis/ERC20.ts
  packages/universal-router-sdk/src/abis/Element.json
  packages/universal-router-sdk/src/abis/Element.ts
  packages/universal-router-sdk/src/abis/Foundation.json
  packages/universal-router-sdk/src/abis/Foundation.ts
  packages/universal-router-sdk/src/abis/IUniswapV3Pool.json
  packages/universal-router-sdk/src/abis/IUniswapV3Pool.ts
  packages/universal-router-sdk/src/abis/LooksRareV2.json
  packages/universal-router-sdk/src/abis/LooksRareV2.ts
  packages/universal-router-sdk/src/abis/NFT20.json
  packages/universal-router-sdk/src/abis/NFT20.ts
  packages/universal-router-sdk/src/abis/NFTXZap.json
  packages/universal-router-sdk/src/abis/NFTXZap.ts
  packages/universal-router-sdk/src/abis/Seaport.json
  packages/universal-router-sdk/src/abis/Seaport.ts
  packages/universal-router-sdk/src/abis/Sudoswap.json
  packages/universal-router-sdk/src/abis/Sudoswap.ts
  packages/universal-router-sdk/src/abis/X2Y2.json
  packages/universal-router-sdk/src/abis/X2Y2.ts
  packages/universal-router-sdk/src/entities/protocols/pancakeswap.ts
  packages/universal-router-sdk/src/entities/protocols/unwrapWETH.ts
  packages/universal-router-sdk/src/entities/types.ts
  packages/universal-router-sdk/src/index.ts
  packages/universal-router-sdk/src/utils/constants.ts
  packages/universal-router-sdk/src/utils/inputTokens.ts
  packages/universal-router-sdk/src/utils/routerCommands.ts
  packages/universal-router-sdk/test/fixtures/address.ts
  packages/universal-router-sdk/test/fixtures/constants/chains.ts
  packages/universal-router-sdk/test/trade.test.ts
  packages/utils/user/slippage.ts
  packages/v3-sdk/src/abi/V3PoolAbi.ts
  packages/v3-sdk/src/index.ts
  pnpm-lock.yaml
Labels: size/XXL

#8098 feat: Remove all birthday items
  apps/web/public/images/predictions/birthday/birthday-icon.png
  apps/web/public/images/predictions/birthday/desktop-bunny.png
  apps/web/public/images/predictions/birthday/mobile-bunny.png
  apps/web/public/images/third-year-cake.svg
  apps/web/src/__tests__/utils/utils.test.ts
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/components/Menu/utils.ts
  apps/web/src/pages/_app.tsx
  apps/web/src/pages/index.tsx
  apps/web/src/pages/nfts/activity.tsx
  apps/web/src/pages/nfts/collections/[collectionAddress].tsx
  apps/web/src/pages/nfts/collections/[collectionAddress]/[tokenId].tsx
  apps/web/src/pages/nfts/collections/index.tsx
  apps/web/src/pages/nfts/index.tsx
  apps/web/src/views/Home/components/Banners/GalxePedictBanner.tsx
  apps/web/src/views/Home/components/Banners/GalxeSyndicateBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  apps/web/src/views/Home/components/Banners/images/galaxe-pancake-banner-logo.png
  apps/web/src/views/Home/components/Banners/images/galxe-predictors-bg.png
  apps/web/src/views/Home/components/Banners/images/galxe-predictors-bunny.png
  apps/web/src/views/Home/components/Banners/images/galxe-syndicate-bg.png
  apps/web/src/views/Home/components/Banners/images/galxe-syndicate-bunny.png
  apps/web/src/views/Home/components/Banners/images/galxeBirthdayCampaignBg.png
  apps/web/src/views/Home/components/Banners/images/galxeMobileBunnny2.png
  apps/web/src/views/Home/components/Banners/images/galxeMobileBunny1.png
  apps/web/src/views/Home/components/Banners/images/galxePredictorsBg.png
  apps/web/src/views/Home/components/Banners/images/galxeSyndicateBg.png
  apps/web/src/views/Home/components/Banners/images/index.ts
  apps/web/src/views/Home/components/ThirdYearBirthdayCake.tsx
  apps/web/src/views/Home/index.tsx
  apps/web/src/views/Nft/market/components/SubMenu/index.tsx
  apps/web/src/views/Predictions/Mobile.tsx
  apps/web/src/views/Predictions/components/CollectWinningsPopup.tsx
  apps/web/src/views/Predictions/components/Container.tsx
  apps/web/src/views/Predictions/components/JupiterPredictors.tsx
  apps/web/src/views/Predictions/components/Menu.tsx
  apps/web/src/views/Predictions/components/MobileMenu.tsx
  apps/web/src/views/Predictions/components/PrevNextNav.tsx
  apps/web/src/views/Predictions/index.tsx
  packages/localization/src/config/translations.json
Labels: size/XL

#8128 fix: Blog image problem
  apps/blog/types.ts
  apps/blog/utils/transformArticle.ts
  apps/web/src/views/Home/types.ts
  apps/web/src/views/Home/utils/transformArticle.ts
Labels: size/XS, automerge

#8132 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XL

#8134 chore: Upgrade zod
  .changeset/modern-seals-raise.md
  apis/farms/package.json
  apps/blog/package.json
  apps/web/package.json
  packages/smart-router/package.json
  pnpm-lock.yaml
Labels: size/L

#8129 fix: Blog categories API
  apps/blog/components/Article/AllArticle/index.tsx
  apps/blog/hooks/getArticle.ts
  apps/web/src/views/Home/hooks/getArticle.ts
Labels: size/S, automerge

#8137 chore: Dependencies update
  .changeset/wise-trainers-teach.md
  apis/farms/package.json
  apis/proxy-worker/package.json
  apis/routing/package.json
  packages/farms/package.json
  packages/uikit/package.json
  pnpm-lock.yaml
Labels: size/XL

#8136 feat(test): add exports snopshots for publich pkgs
  packages/aptos-swap-sdk/src/index.test.ts
  packages/awgmi/core/src/index.test.ts
  packages/awgmi/package.json
  packages/awgmi/src/index.test.ts
  packages/awgmi/vitest.config.ts
  packages/chains/src/index.test.ts
  packages/farms/index.test.ts
  packages/multicall/src/index.test.ts
  packages/pools/src/index.test.ts
  packages/smart-router/evm/index.test.ts
  packages/smart-router/legacy-router/index.test.ts
  packages/swap-sdk-core/src/index.test.ts
  packages/swap-sdk/src/index.test.ts
  packages/token-lists/react/index.test.ts
  packages/token-lists/src/index.test.ts
  packages/v3-sdk/src/index.test.ts
Labels: size/XL, automerge

#8089 fix: Wrong token address being used for price query
  apps/web/src/state/swap/hooks.ts
Labels: size/XS

#7798 chore: Enable Safepal switch network
  apps/web/src/hooks/useSwitchNetwork.ts
  apps/web/src/utils/wallet.ts
Labels: size/XS

#6852 fix: Quick input stays same after amount change
  apps/aptos/components/CurrencyInputPanel/index.tsx
  apps/web/src/components/CurrencyInputPanel/index.tsx
Labels: size/S

#7609 fix: Leaking v2 states in add liquidity modal
  apps/web/src/views/AddLiquidityV3/Modal.tsx
Labels: size/M

#8139 fix: lint error
  packages/smart-router/evm/index.test.ts
  packages/universal-router-sdk/package.json
  packages/universal-router-sdk/test/utils/buildTrade.ts
  packages/universal-router-sdk/test/utils/calldataDecode.ts
  packages/universal-router-sdk/test/utils/permit.ts
  packages/universal-router-sdk/test/utils/signPermit.ts
Labels: size/S, automerge

#8140 fix: update snapshot
  packages/v3-sdk/src/index.test.ts
Labels: size/XS, automerge

#8092 feat(simple-staking): Support BNB
  apps/web/src/views/FixedStaking/components/AmountWithUSDSub.tsx
  apps/web/src/views/FixedStaking/components/ClaimModal.tsx
  apps/web/src/views/FixedStaking/components/FixedStakingCalculator.tsx
  apps/web/src/views/FixedStaking/components/FixedStakingCard.tsx
  apps/web/src/views/FixedStaking/components/FixedStakingModal.tsx
  apps/web/src/views/FixedStaking/components/FixedStakingOverview.tsx
  apps/web/src/views/FixedStaking/components/HarvestModal.tsx
  apps/web/src/views/FixedStaking/components/ModalTitle.tsx
  apps/web/src/views/FixedStaking/components/RestakeFixedStakingModal.tsx
  apps/web/src/views/FixedStaking/components/StakeConfirmModal.tsx
  apps/web/src/views/FixedStaking/components/StakedPositionSection.tsx
  apps/web/src/views/FixedStaking/components/StakingModalTemplate.tsx
  apps/web/src/views/FixedStaking/components/UnstakeBeforeEndedModal.tsx
  apps/web/src/views/FixedStaking/constant.ts
  apps/web/src/views/FixedStaking/hooks/useCalculateProjectedReturnAmount.ts
  apps/web/src/views/FixedStaking/hooks/useHandleWithdrawSubmission.ts
  apps/web/src/views/FixedStaking/hooks/useStakedPools.ts
  apps/web/src/views/FixedStaking/index.tsx
  packages/localization/src/config/translations.json
Labels: size/L, automerge

#8118 chore: Move finished pools
  .changeset/pink-moose-appear.md
  packages/pools/src/constants/pools/1.ts
  packages/pools/src/constants/pools/56.ts
Labels: Delayed Release, size/M

#7406 chore: Bump up swr
  apps/aptos/package.json
  apps/blog/package.json
  apps/web/package.json
  packages/utils/package.json
  pnpm-lock.yaml
Labels: size/S

#7754 chore: Bump up jotai
  .changeset/shy-sheep-smile.md
  apps/aptos/package.json
  apps/web/package.json
  packages/token-lists/package.json
  packages/utils/package.json
  pnpm-lock.yaml
Labels: size/M

#7815 refactor: Use infobox from uikit
  apps/web/src/components/InfoBox/index.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V2FormView.tsx
  packages/widgets-internal/swap/index.ts
Labels: size/S

#8044 fix: (homepage): Harvest card send failed trx if no v3 farms but only v2 farms, stop swiper when harvesting
  apps/web/src/views/Home/components/UserBanner/HarvestCard.tsx
  apps/web/src/views/Home/components/UserBanner/index.tsx
Labels: size/M

#8147 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/M

#8144 refactor: move liquidity to widget
  apps/aptos/components/Liquidity/components/AddLiquidityForm.tsx
  apps/aptos/components/Liquidity/components/ChoosePair.tsx
  apps/aptos/components/Liquidity/components/LiquidityList.tsx
  apps/aptos/components/Liquidity/components/SimpleRemoveForm.tsx
  apps/aptos/pages/add/[[...currency]].tsx
  apps/aptos/pages/liquidity.tsx
  apps/aptos/pages/remove/[[...currency]].tsx
  apps/web/src/components/FiatOnRampModal/FiatOnRampModal.tsx
  apps/web/src/pages/liquidity/index.tsx
  packages/uikit/src/components/LoadingDot/index.tsx
  packages/uikit/src/components/index.ts
  packages/uikit/src/index.ts
  packages/widgets-internal/index.ts
  packages/widgets-internal/liquidity/AddLiquidity/ChoosePairView.tsx
  packages/widgets-internal/liquidity/AddLiquidity/FirstLP.tsx
  packages/widgets-internal/liquidity/AprRow.tsx
  packages/widgets-internal/liquidity/FindOtherLP.tsx
  packages/widgets-internal/liquidity/GotoAddLiquidityButton.tsx
  packages/widgets-internal/liquidity/LiquidityCard.tsx
  packages/widgets-internal/liquidity/LiquidityCardHeader.tsx
  packages/widgets-internal/liquidity/LiquidityNotConnect.tsx
  packages/widgets-internal/liquidity/NoLiquidity.tsx
  packages/widgets-internal/liquidity/PercentSlider.tsx
  packages/widgets-internal/liquidity/index.ts
Labels: size/M

#8149 fix: split amount by mix-route
  packages/universal-router-sdk/src/entities/protocols/pancakeswap.ts
Labels: size/XS, automerge

#8152 chore: Add farms to opbnb testnet
  apps/web/src/config/chains.ts
  apps/web/src/config/constants/supportChains.ts
  apps/web/src/views/TradingReward/config/pairs/index.tsx
  packages/chains/src/chainNames.ts
  packages/chains/src/index.test.ts
  packages/chains/src/index.ts
  packages/chains/src/utils.ts
  packages/farms/constants/common/index.ts
  packages/farms/constants/opBnbTestnet.ts
  packages/farms/constants/v3/index.ts
  packages/farms/index.test.ts
  packages/farms/src/const.ts
  packages/farms/src/fetchFarmsV3.ts
  packages/farms/src/index.ts
  packages/smart-router/evm/constants/common.ts
  packages/smart-router/evm/index.test.ts
  packages/smart-router/evm/v3-router/providers/getCommonTokenPrices.ts
  packages/tokens/src/5611.ts
Labels: size/L

#8155 chore: sync abi compile from source
  packages/permit2-sdk/src/abis/Permit2.ts
  packages/universal-router-sdk/src/abis/UniversalRouter.ts
Labels: size/XL, automerge

#8156 chore: list csix pool
  packages/pools/src/constants/pools/56.ts
Labels: size/XS

#8158 fix: (swap): Recipient text two chars shown when no recipient
  apps/aptos/components/Swap/SwapModalHeader.tsx
  apps/web/src/views/Swap/components/SwapModalHeader.tsx
Labels: size/XS

#8161 fix: Nft collection pagination wrong
  apps/web/src/views/Nft/market/Collections/index.tsx
Labels: size/S

#8162 fix: More from collection pagination wrong
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/shared/MoreFromThisCollection.tsx
Labels: size/M

#7544 refactor: Remove deprecated token prices hook
  apps/web/src/components/CurrencySelect/index.tsx
  apps/web/src/hooks/useBNBPrice.ts
  apps/web/src/hooks/useBUSDPrice.ts
  apps/web/src/hooks/useCakePrice.ts
  apps/web/src/views/Home/components/CommunitySection/PredictionCardContent.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
  apps/web/src/views/Ifos/components/IfoVesting/VestingPeriod/TokenInfo.tsx
  apps/web/src/views/Predictions/Leaderboard/components/Results/styles.tsx
  apps/web/src/views/Predictions/components/CollectRoundWinningsModal.tsx
  apps/web/src/views/Predictions/components/History/BetResult.tsx
  apps/web/src/views/Predictions/components/History/PnlTab/PnlTab.tsx
  apps/web/src/views/Predictions/components/History/PnlTab/SummaryRow.tsx
  apps/web/src/views/Predictions/hooks/useTokenPrice.ts
  apps/web/src/views/TradingCompetition/helpers.ts
Labels: size/L

#8164 chore: list new farms for zkevm
  packages/farms/constants/polygonZkEVM.ts
  packages/tokens/src/1101.ts
Labels: size/S

#8165 chore: list new farms for base
  packages/farms/constants/base.ts
  packages/tokens/src/8453.ts
Labels: size/S

#8166 chore: list new farms for linea
  packages/farms/constants/linea.ts
  packages/tokens/src/59144.ts
Labels: size/S

#8167 feat: update address
  packages/universal-router-sdk/src/utils/constants.ts
  packages/universal-router-sdk/test/__snapshots__/trade.test.ts.snap
Labels: size/M

#8168 fix(aptos): dev mode error due to ve
  apps/aptos/css/theme.css.ts
  apps/aptos/next.config.mjs
  package.json
  packages/uikit/package.json
Labels: size/S

#8171 chore: New Crowdin updates
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XS

#8175 chore: list farm for bsc
  packages/farms/constants/bsc.ts
Labels: size/XS

#8176 chore: list farm for aptos
  apps/aptos/config/constants/farms/1.ts
  apps/aptos/config/constants/tokens/1.ts
Labels: size/S

#8177 chore: add price helper for aptos new farm
  apps/aptos/config/constants/farms/1.ts
  apps/aptos/config/constants/priceHelperLps/farms/1.ts
Labels: size/XS

#8181 refactor(uikit): remove next-seo
  apps/aptos/pages/404.tsx
  apps/blog/pages/404.tsx
  apps/blog/pages/articles/[slug].tsx
  apps/web/src/pages/404.tsx
  apps/web/src/pages/_error.tsx
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/views/Voting/Proposal/Overview.tsx
  packages/uikit/package.json
  packages/uikit/src/components/NotFound/NotFound.tsx
  pnpm-lock.yaml
Labels: size/M

#8184 chore: New Crowdin updates
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XS

#8188 feat: add FDUSD-USDT (0.01%) farm
  packages/farms/constants/bsc.ts
  packages/tokens/src/56.ts
Labels: size/S

#8187 chore: Add subgraph endpoints to chains
  .changeset/clean-mayflies-do.md
  apis/routing/src/constants.ts
  apis/routing/src/provider.ts
  apps/web/src/config/constants/endpoints.ts
  packages/chains/src/index.test.ts
  packages/chains/src/index.ts
  packages/chains/src/subgraphs.ts
Labels: size/L

#8173 feat: mekle notice
  .vscode/settings.json
  apis/farms/src/v3.ts
  apps/aptos/components/Farms/components/FarmTable/Farm.tsx
  apps/web/src/config/merkl.ts
  apps/web/src/utils/getMerklLink.tsx
  apps/web/src/views/Farms/components/FarmCard/CardHeading.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3Card.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/Farms/components/FarmTable/Farm.tsx
  apps/web/src/views/Farms/components/FarmTable/FarmTable.tsx
  packages/localization/src/config/translations.json
  packages/widgets-internal/farm/FarmWidget.tsx
  packages/widgets-internal/farm/components/FarmTable/FarmTokenInfo.tsx
  packages/widgets-internal/farm/components/FarmV3Table/Actions/NoPosition.tsx
  packages/widgets-internal/farm/components/MerklNotice/index.tsx
  packages/widgets-internal/farm/components/Tags/index.tsx
  packages/widgets-internal/farm/types.ts
Labels: size/L

#8186 refactor: Enable ssr for react-query and use it in teams pages
  apps/web/src/Providers.tsx
  apps/web/src/pages/_app.tsx
  apps/web/src/pages/teams/[id].tsx
  apps/web/src/pages/teams/index.tsx
  apps/web/src/testUtils.tsx
  apps/web/src/views/Teams/components/TeamCard.tsx
  apps/web/src/views/Teams/index.tsx
Labels: size/L

#8182 fix: Liquid staking received token add to wallet not working
  apps/web/src/components/AddToWallet/AddToWalletButton.tsx
  apps/web/src/pages/liquid-staking/[contract].tsx
  apps/web/src/utils/wallet.ts
Labels: size/M

#8178 perf: (swap): Don't request all token highlights when in bsc
  apps/web/src/state/info/hooks.ts
  apps/web/src/views/Swap/components/HotTokenList/useList.tsx
Labels: size/M

#8190 feat: add ethx-eth farm
  apps/web/src/config/merkl.ts
  packages/farms/constants/eth.ts
  packages/tokens/src/1.ts
Labels: size/S, automerge

#8191 fix: Revalidate for teams
  apps/web/src/pages/teams/index.tsx
Labels: size/XS

#8192 chore: Fix pid
  packages/farms/constants/eth.ts
Labels: size/XS

#8196 refactor: Use query in farm auction
  apps/web/src/views/FarmAuction/components/AuctionLeaderboard/AuctionProgress.tsx
  apps/web/src/views/FarmAuction/hooks/useCurrentFarmAuction.ts
  apps/web/src/views/FarmAuction/hooks/useFarmAuction.ts
  apps/web/src/views/FarmAuction/hooks/useWhitelistedAddresses.ts
Labels: size/M

#8198 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#8197 fix: roi calc
  apps/web/src/utils/isPoolTickInRange.ts
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
  packages/widgets-internal/roi/RoiCalculator.tsx
Labels: size/M

#8201 feat: add GRAI-USDC (0.05%) merkl notice
  apps/web/src/config/merkl.ts
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  packages/widgets-internal/farm/components/MerklNotice/index.tsx
Labels: size/S

#8203 fix: isPoolTickInRange null
  apps/web/src/utils/isPoolTickInRange.ts
Labels: size/XS, automerge

#8207 refactor: remove deprecated address define
  packages/permit2-sdk/src/constants.ts
  packages/universal-router-sdk/src/index.ts
  packages/universal-router-sdk/src/utils/constants.ts
  packages/universal-router-sdk/test/fixtures/address.ts
Labels: size/M, automerge

#8195 refactor: Use query in trading reward
  apps/web/src/views/TradingReward/hooks/useAllTradingRewardPair.tsx
  apps/web/src/views/TradingReward/hooks/useAllUserCampaignInfo.tsx
  apps/web/src/views/TradingReward/hooks/useCampaignIdInfo.tsx
  apps/web/src/views/TradingReward/hooks/useClaimAllReward.tsx
  apps/web/src/views/TradingReward/hooks/useRankList.tsx
  apps/web/src/views/TradingReward/hooks/useRewardBreakdown.tsx
  apps/web/src/views/TradingReward/hooks/useTradingFeeClaimedRecord.tsx
  apps/web/src/views/TradingReward/hooks/useUserTradeRank.tsx
Labels: size/M

#8206 chore: New Crowdin updates
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XS

#8209 chore: Add more testing node
  apps/web/src/config/nodes.ts
  apps/web/src/utils/node/nodeReal.ts
  apps/web/src/utils/node/pokt.ts
  apps/web/src/utils/viem.server.ts
Labels: size/L

#8210 fix: Remove mandatory cookie from affiliate apis
  apps/web/src/pages/api/affiliates-program/affiliate-claim-fee.ts
  apps/web/src/pages/api/affiliates-program/affiliate-claim-list.ts
  apps/web/src/pages/api/affiliates-program/affiliate-exist.ts
  apps/web/src/pages/api/affiliates-program/affiliate-fee-create.ts
  apps/web/src/pages/api/affiliates-program/affiliate-fee-exist.ts
  apps/web/src/pages/api/affiliates-program/affiliate-info.ts
  apps/web/src/pages/api/affiliates-program/affiliate-login.ts
  apps/web/src/pages/api/affiliates-program/affiliate-regenerate-signature.ts
  apps/web/src/pages/api/affiliates-program/leader-board.ts
  apps/web/src/pages/api/affiliates-program/user-claim-fee.ts
  apps/web/src/pages/api/affiliates-program/user-claim-list.ts
  apps/web/src/pages/api/affiliates-program/user-exist.ts
  apps/web/src/pages/api/affiliates-program/user-info.ts
  apps/web/src/pages/api/affiliates-program/user-regenerate-signature.ts
  apps/web/src/pages/api/affiliates-program/user-register-fee.ts
Labels: size/M

#8183 fix: (affiliate-program): DefaultLink hook cache refetch not work and move to react-query
  apps/web/src/views/AffiliatesProgram/components/Dashboard/LoginButton.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useAffiliateClaimList.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useAuthAffiliate.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useAuthAffiliateExist.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useDefaultLinkId.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useLeaderboard.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useUserClaimList.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useUserExist.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useUserInfo.tsx
Labels: size/L

#8212 fix: native token unwrap
  packages/universal-router-sdk/src/entities/protocols/pancakeswap.ts
  packages/universal-router-sdk/test/__snapshots__/trade.test.ts.snap
Labels: size/L

#8211 refactor: Use query in liquid staking
  apps/web/src/views/LiquidStaking/hooks/useExchangeRate.tsx
  apps/web/src/views/LiquidStaking/hooks/useLiquidStakingApr.tsx
  apps/web/src/views/LiquidStaking/hooks/useLiquidStakingList.tsx
Labels: size/M

#8213 fix: v3 route percent
  packages/universal-router-sdk/src/entities/protocols/pancakeswap.ts
Labels: size/XS

#8208 feat(aptos): Add msafe connector
  .changeset/spicy-kids-change.md
  apps/aptos/client.ts
  apps/aptos/config/wallets.ts
  apps/aptos/hooks/useEagerConnect.ts
  apps/aptos/pages/_app.tsx
  apps/aptos/public/images/wallets/msafe.png
  packages/awgmi/connectors/msafe/package.json
  packages/awgmi/core/src/connectors/msafe.ts
  packages/awgmi/package.json
  packages/awgmi/tsup.config.ts
  pnpm-lock.yaml
Labels: size/L

#8227 feat(Pool): Move finished pools
  .changeset/fresh-beans-sneeze.md
  packages/pools/src/constants/pools/1.ts
  packages/pools/src/constants/pools/56.ts
Labels: size/M, automerge

#8226 chore: Bump nextjs
  apps/aptos/package.json
  apps/blog/package.json
  apps/bridge/package.json
  apps/web/package.json
  apps/web/src/testUtils.tsx
  apps/web/src/views/TradingCompetition/Footer.tsx
  apps/web/src/views/TradingCompetition/components/FinishedCompetitionBanner/index.tsx
  apps/web/src/views/TradingCompetition/components/ShareImageModal.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TeamRanksWithParticipants.tsx
  apps/web/src/views/TradingCompetition/components/YourScore/ScoreCard.tsx
  apps/web/src/views/TradingCompetition/types.ts
  examples/playground/package.json
  packages/next-config/package.json
  packages/widgets-internal/package.json
  pnpm-lock.yaml
Labels: size/L

#8229 chore: Bump next axiom
  apps/aptos/package.json
  apps/blog/package.json
  apps/bridge/package.json
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/M

#8231 chore: Bump crypto js
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/S

#8233 chore: Remove log on prod
  apps/aptos/package.json
  apps/blog/package.json
  apps/bridge/package.json
  apps/web/package.json
  apps/web/src/quote-worker.ts
  apps/web/src/testUtils.tsx
  apps/web/src/views/TradingCompetition/Footer.tsx
  apps/web/src/views/TradingCompetition/components/FinishedCompetitionBanner/index.tsx
  apps/web/src/views/TradingCompetition/components/ShareImageModal.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TeamRanksWithParticipants.tsx
  apps/web/src/views/TradingCompetition/components/YourScore/ScoreCard.tsx
  apps/web/src/views/TradingCompetition/types.ts
  examples/playground/package.json
  packages/next-config/package.json
  packages/widgets-internal/package.json
  pnpm-lock.yaml
Labels: size/L

#8234 fix: recipient
  packages/universal-router-sdk/src/entities/protocols/pancakeswap.ts
  packages/universal-router-sdk/test/__snapshots__/trade.test.ts.snap
  packages/universal-router-sdk/test/fixtures/address.ts
  packages/universal-router-sdk/test/fixtures/constants/tokens.ts
  packages/universal-router-sdk/test/trade.test.ts
  packages/universal-router-sdk/test/utils/buildTrade.ts
Labels: size/XXL, automerge

#8232 refactor: Use query in limit orders
  apps/web/src/hooks/limitOrders/useGelatoLimitOrdersHandlers.ts
  apps/web/src/hooks/limitOrders/useGelatoLimitOrdersLib.ts
  apps/web/src/views/LimitOrders/hooks/useGelatoLimitOrdersHistory.ts
Labels: size/M

#8237 refactor: Use query in block hooks
  apps/web/src/hooks/useRefreshEffect.test.ts
  apps/web/src/hooks/useRefreshEffect.ts
  apps/web/src/state/block/hooks.ts
  apps/web/src/state/multicall/hooks.ts
  apps/web/src/testUtils.tsx
Labels: size/L

#8249 Revert "refactor: Use query in block hooks"
  apps/web/src/hooks/useRefreshEffect.test.ts
  apps/web/src/hooks/useRefreshEffect.ts
  apps/web/src/state/block/hooks.ts
  apps/web/src/state/multicall/hooks.ts
  apps/web/src/testUtils.tsx
Labels: size/L

#8250 feat: Add game folder
  README.md
  apps/games/.env.example
  apps/games/.eslintrc
  apps/games/.gitignore
  apps/games/README.md
  apps/games/components/Menu.tsx
  apps/games/components/PageMeta.tsx
  apps/games/next-env.d.ts
  apps/games/next-seo.config.ts
  apps/games/next.config.mjs
  apps/games/package.json
  apps/games/pages/404.tsx
  apps/games/pages/_app.tsx
  apps/games/pages/_document.tsx
  apps/games/pages/index.tsx
  apps/games/tsconfig.json
  package.json
  pnpm-lock.yaml
Labels: size/XXL

#8255 chore: fix position managers details
  apps/web/src/views/PositionManagers/components/AprButton.tsx
  apps/web/src/views/PositionManagers/components/RemoveLiquidity.tsx
  apps/web/src/views/PositionManagers/components/SingleTokenWarning.tsx
Labels: size/M

#8257 fix: mmTrade query-key
  apps/web/src/views/Swap/V3Swap/containers/MMCommitButton.tsx
Labels: size/XS

#8258 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XXL

#8262 chore: Remove quote logs
  apps/web/src/quote-worker.ts
Labels: size/XS

#8254 chore: Add datadog integration
  apps/web/.env.example
  apps/web/package.json
  apps/web/src/quote-worker.ts
  apps/web/src/utils/datadog.ts
  apps/web/src/utils/log.ts
  apps/web/src/utils/workerPolyfill.ts
  pnpm-lock.yaml
Labels: size/L
