Repository pancakeswap/pancake-frontend, pull requests merged in 2023-12, with the labels that each got.

#8494 feat: unlist sdCake
  packages/gauges/src/constants/config.ts
  packages/smart-router/evm/constants/stableSwap/56.ts
Labels: size/M, automerge

#8496 chore: add missed dev script
  packages/gauges/package.json
Labels: size/XS, automerge

#8491 chore(Menu): Display NewTag in the externalLink
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/components/DropdownMenu/DropdownMenu.tsx
Labels: size/L

#8495 feat: add calc gauges voting sc
  apps/web/src/config/abi/gaugesVoting.ts
  apps/web/src/config/constants/contracts.ts
  apps/web/src/hooks/useContract.ts
  apps/web/src/pages/api/gauges/getAllGauges.ts
  apps/web/src/pages/api/gauges/getAllGaugesCSV.ts
  apps/web/src/state/vecake/atoms.ts
  apps/web/src/utils/addressHelpers.ts
  apps/web/src/utils/contractHelpers.ts
  apps/web/src/views/GaugesVoting/hooks/useGauges.ts
  apps/web/src/views/GaugesVoting/hooks/useGaugesTotalWeight.ts
  apps/web/src/views/GaugesVoting/hooks/useUserVoteGauges.ts
  packages/gauges/src/abis/calcGaugesVoting.ts
  packages/gauges/src/abis/index.ts
  packages/gauges/src/constants/address.ts
  packages/gauges/src/contract.ts
  packages/gauges/src/fetchGaugeVoting.ts
  packages/gauges/src/getAllGauges.ts
  packages/gauges/src/index.test.ts
  packages/gauges/src/index.ts
  packages/gauges/src/types.ts
Labels: size/XL

#8484 chore: Bump up wagmi viem
  .changeset/eighty-pants-exercise.md
  apis/farms/package.json
  apis/routing/package.json
  apps/bridge/package.json
  apps/web/package.json
  apps/web/src/components/Menu/UserMenu/hooks/useCakeBenefits.ts
  apps/web/src/hooks/useApproveCallback.ts
  apps/web/src/utils/contractHelpers.ts
  apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
  apps/web/src/views/AddLiquidityV3/Migrate.tsx
  packages/farms/package.json
  packages/gauges/package.json
  packages/ifos/package.json
  packages/ifos/src/queries/fetchUserIfo.ts
  packages/ifos/src/utils/getInfoSenderContract.ts
  packages/multicall/package.json
  packages/pools/package.json
  packages/position-managers/package.json
  packages/smart-router/package.json
  packages/swap-sdk/package.json
  packages/uikit/package.json
  packages/v3-sdk/package.json
  packages/wagmi/package.json
  packages/widgets-internal/package.json
  pnpm-lock.yaml
  scripts/package.json
Labels: size/L

#8504 fix(GaugesVoting): Fix sort button
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/TableHeader.tsx
Labels: size/XS

#8518 fix: v2 token table left paren
  apps/web/src/views/Info/components/InfoTables/TokensTable.tsx
Labels: size/S

#8519 chore: Revert nextjs bump
  apps/aptos/package.json
  apps/blog/package.json
  apps/bridge/package.json
  apps/games/package.json
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/src/testUtils.tsx
  apps/web/src/views/TradingCompetition/Footer.tsx
  apps/web/src/views/TradingCompetition/components/FinishedCompetitionBanner/index.tsx
  apps/web/src/views/TradingCompetition/components/ShareImageModal.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TeamRanksWithParticipants.tsx
  apps/web/src/views/TradingCompetition/components/YourScore/ScoreCard.tsx
  apps/web/src/views/TradingCompetition/types.ts
  examples/playground/package.json
  packages/next-config/package.json
  packages/widgets-internal/package.json
  pnpm-lock.yaml
Labels: size/L

#8516 fix: Missing translations in liquidity add/remove modals
  apps/web/src/views/AddLiquidityV3/IncreaseLiquidityV3.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
  apps/web/src/views/RemoveLiquidity/RemoveLiquidityV3.tsx
Labels: size/M

#8522 chore: nextjs bump
  apps/aptos/package.json
  apps/blog/package.json
  apps/bridge/package.json
  apps/games/package.json
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/src/config/abi/AngleProtocolDistributor.ts
  apps/web/src/config/merkl.ts
  apps/web/src/hooks/useMerkl.tsx
  apps/web/src/testUtils.tsx
  apps/web/src/views/TradingCompetition/Footer.tsx
  apps/web/src/views/TradingCompetition/components/FinishedCompetitionBanner/index.tsx
  apps/web/src/views/TradingCompetition/components/ShareImageModal.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TeamRanksWithParticipants.tsx
  apps/web/src/views/TradingCompetition/components/YourScore/ScoreCard.tsx
  apps/web/src/views/TradingCompetition/types.ts
  examples/playground/package.json
  packages/next-config/package.json
  packages/widgets-internal/package.json
  pnpm-lock.yaml
Labels: size/XXL

#8526 fix: vote table width
  .vscode/settings.json
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/index.tsx
Labels: size/XS, automerge

#8527 chore: New Crowdin updates
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/M

#8528 fix: vote table tbody
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/index.tsx
Labels: size/XS, automerge

#8479 chore: web3 notification banner
  apps/web/src/views/Home/components/Banners/WebNotificationBanner.tsx
  apps/web/src/views/Home/components/Banners/animations.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  apps/web/src/views/Home/components/Banners/images/web3-notification-bg-mobile.png
  apps/web/src/views/Home/components/Banners/images/web3-notification-bg.png
  apps/web/src/views/Home/components/Banners/images/web3-notification-bubble-mobile.png
  apps/web/src/views/Home/components/Banners/images/web3-notification-bubble.png
  apps/web/src/views/Home/components/Banners/images/web3-notification-bunny.png
  apps/web/src/views/Home/components/Banners/images/web3-notification-check.png
  packages/localization/src/config/translations.json
Labels: size/L

#8530 chore(simple-staking): Disable cake pool
  apps/web/src/views/FixedStaking/components/AmountWithUSDSub.tsx
  apps/web/src/views/FixedStaking/components/ClaimModal.tsx
  apps/web/src/views/FixedStaking/components/FixedStakingCard.tsx
  apps/web/src/views/FixedStaking/components/FixedStakingRow.tsx
  apps/web/src/views/FixedStaking/components/StakedPositionSection.tsx
Labels: size/L

#8534 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XL

#8536 feat: voting sort
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/TableRow.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/hooks/useGaugeRows.ts
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/hooks/useRowVoteState.ts
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/index.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/types.ts
  apps/web/src/views/GaugesVoting/hooks/useUserVote.ts
Labels: size/L

#8535 feat: Add meetup banner
  apps/web/src/views/Home/components/Banners/MultipleBanner.tsx
  apps/web/src/views/Home/components/Banners/SpainMeetupBanner.tsx
  apps/web/src/views/Home/components/Banners/Styled.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  apps/web/src/views/Home/components/Banners/images/spain-meetup-bg.png
  apps/web/src/views/Home/components/Banners/images/spain-meetup-bunny.png
  apps/web/src/views/Home/components/Banners/images/spain-meetup-ticket-btn.png
  packages/hooks/package.json
  packages/hooks/src/index.ts
  packages/hooks/src/useCountdown.ts
  packages/localization/src/config/translations.json
  pnpm-lock.yaml
Labels: size/L

#8541 fix: Mobile banner
  apps/web/src/views/Home/components/Banners/SpainMeetupBanner.tsx
Labels: size/S

#8542 fix: fix node version to 18.18.2
  .github/workflows/unitTests.yml
Labels: size/XS

#8515 fix: gauges ux
  apps/web/public/images/cake-staking/lock.png
  apps/web/src/hooks/useVaultApy.ts
  apps/web/src/utils/addressHelpers.ts
  apps/web/src/views/CakeStaking/components/BenefitCard.tsx
  apps/web/src/views/CakeStaking/components/CakeRewardsCard.tsx
  apps/web/src/views/CakeStaking/components/DataSet/DataBox.tsx
  apps/web/src/views/CakeStaking/components/DataSet/NewStakingDataSet.tsx
  apps/web/src/views/CakeStaking/components/HeadImage.tsx
  apps/web/src/views/CakeStaking/components/LockCake/Expired.tsx
  apps/web/src/views/CakeStaking/components/LockCake/Migrate.tsx
  apps/web/src/views/CakeStaking/components/LockCake/NotLocking.tsx
  apps/web/src/views/CakeStaking/components/LockCake/Staking.tsx
  apps/web/src/views/CakeStaking/components/LockCake/index.tsx
  apps/web/src/views/CakeStaking/components/LockCakeForm.tsx
  apps/web/src/views/CakeStaking/components/LockWeeksForm.tsx
  apps/web/src/views/CakeStaking/components/MyVeCakeCard.tsx
  apps/web/src/views/CakeStaking/components/PageHead.tsx
  apps/web/src/views/CakeStaking/components/SyrupPool/VeCakeCard.tsx
  apps/web/src/views/CakeStaking/index.tsx
  apps/web/src/views/GaugesVoting/components/ChartTooltip.tsx
  apps/web/src/views/GaugesVoting/components/CurrentEpoch.tsx
  apps/web/src/views/GaugesVoting/components/GaugeTokenImage.tsx
  apps/web/src/views/GaugesVoting/components/MyVeCakeBalance.tsx
  apps/web/src/views/GaugesVoting/components/Table/AddGauge/AddGaugeModal.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/List.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/TableHeader.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/TableRow.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/index.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/EmptyTable.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/List.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/PercentInput.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/TableRow.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/index.tsx
  apps/web/src/views/GaugesVoting/components/Table/styled.tsx
  apps/web/src/views/GaugesVoting/components/WeightsPieChart.tsx
  apps/web/src/views/GaugesVoting/index.tsx
  apps/web/src/views/Pools/components/MaxStakeRow.tsx
  apps/web/src/views/Pools/components/PoolStatsInfo.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
  apps/web/src/views/Pools/components/PoolsTable/Cells/AutoAprCell.tsx
  apps/web/src/views/Pools/components/PoolsTable/Cells/AutoEarningsCell.tsx
  apps/web/src/views/Pools/components/PoolsTable/Cells/StakedCell.tsx
  apps/web/src/views/Pools/components/PoolsTable/Cells/TotalStakedCell.tsx
  apps/web/src/views/Pools/components/PoolsTable/PoolRow.tsx
  apps/web/src/views/Pools/components/Stat.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/components/Table/Cell.tsx
  packages/widgets-internal/pool/Cells/EndsInCell.tsx
  packages/widgets-internal/pool/TotalStaked.tsx
Labels: size/XXL

#8543 fix: Cannot add/remove v2 liquidity on zksync
  apps/web/src/views/AddLiquidity/components/ConfirmAddLiquidityModal.tsx
  apps/web/src/views/AddLiquidity/components/common.tsx
  apps/web/src/views/AddLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/index.tsx
Labels: size/M

#8540 feat: merkl script
  .github/workflows/updateAptosLPsAPR.yml
  .github/workflows/updateCron.yml
  .github/workflows/updateLPsAPR.yml
  apps/web/src/config/constants/merklPools.json
  apps/web/src/config/merkl.ts
  apps/web/src/utils/getMerklLink.tsx
  package.json
  scripts/updateMerkl/index.ts
Labels: size/L

#8544 chore: update Merkl learn more link
  apps/web/src/components/Merkl/MerklSection.tsx
Labels: size/S

#8363 feat: support position manager defiedge vault
  .github/workflows/testConfig.yml
  .github/workflows/tsCheck.yml
  .github/workflows/unitTests.yml
  apps/web/src/config/__tests__/vaults.test.ts
  apps/web/src/views/PositionManagers/components/AprButton.tsx
  apps/web/src/views/PositionManagers/components/CardTitle.tsx
  apps/web/src/views/PositionManagers/hooks/useFetchApr.ts
  apps/web/src/views/PositionManagers/utils/strategy.ts
  packages/localization/src/config/translations.json
  packages/position-managers/constants/index.ts
  packages/position-managers/src/constants/managers.ts
  packages/position-managers/src/constants/supportedChains.ts
  packages/position-managers/src/constants/vaults/arb.ts
  packages/position-managers/src/constants/vaults/base.ts
  packages/position-managers/src/constants/vaults/bsc.ts
  packages/position-managers/src/constants/vaults/index.ts
  packages/position-managers/src/constants/vaults/zkevm.ts
  packages/position-managers/src/constants/vaults/zksync.ts
  packages/position-managers/src/types.ts
Labels: size/L

#8545 feat: Remove games new tag
  apps/web/src/components/Menu/config/config.ts
Labels: size/XS, automerge

#8539 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#8410 refactor: Use query in menu
  apps/web/src/components/Menu/UserMenu/CakeBenefitsCard.tsx
  apps/web/src/components/Menu/UserMenu/hooks/useCakeBenefits.ts
  apps/web/src/components/Menu/hooks/useCompetitionStatus.ts
  apps/web/src/components/Menu/hooks/useIfoStatus.ts
  apps/web/src/components/Menu/hooks/usePotteryStatus.ts
  apps/web/src/components/Menu/hooks/useVotingStatus.ts
  apps/web/src/views/Pools/components/RevenueSharing/JoinRevenueModal/VCakeModal.tsx
Labels: size/L

#8548 fix: xs device
  apps/web/src/views/Home/components/Banners/VeCakeBanner.tsx
Labels: size/S

#8549 fix: fix node version
  .github/workflows/updateCron.yml
Labels: size/XS, automerge

#8552 feat(web): Add rabby logo
  apps/web/src/config/wallet.ts
  packages/ui-wallets/src/WalletModal.tsx
Labels: size/S

#8555 feat: add arb farm
  packages/farms/constants/arb.ts
Labels: size/M, automerge

#8553 feat: highlight changed vote
  apps/web/src/views/GaugesVoting/components/ChartLabel.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/List.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/TableRow.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/hooks/useRowVoteState.ts
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/index.tsx
Labels: size/L

#8561 chore: New Crowdin updates
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XS

#8472 chore: Cyberwallet integration
  apis/farms/package.json
  apis/routing/package.json
  apps/bridge/package.json
  apps/web/package.json
  apps/web/src/config/wallet.ts
  apps/web/src/hooks/useEagerConnect.ts
  apps/web/src/utils/wagmi.ts
  packages/farms/package.json
  packages/gauges/package.json
  packages/ifos/package.json
  packages/multicall/package.json
  packages/pools/package.json
  packages/position-managers/package.json
  packages/smart-router/package.json
  packages/swap-sdk/package.json
  packages/v3-sdk/package.json
  packages/wagmi/package.json
  packages/widgets-internal/package.json
  pnpm-lock.yaml
  scripts/package.json
Labels: size/L

#8547 fix: loading states on notification onboard
  apps/web/src/views/Notifications/components/NotificationDropdown/NotificationMenu.tsx
  apps/web/src/views/Notifications/containers/OnBoardingView.tsx
  apps/web/src/views/Notifications/index.tsx
Labels: size/M

#8566 chore: Remove axiom
  apis/farms/.dev.vars
  apis/routing/.dev.vars
  apis/routing/src/bindings.d.ts
  apis/routing/src/index.ts
  apis/routing/src/log.ts
  apis/routing/wrangler.toml
  apps/aptos/components/Liquidity/hooks/useAddLiquidityHandler.ts
  apps/aptos/next.config.mjs
  apps/aptos/package.json
  apps/blog/next.config.mjs
  apps/blog/package.json
  apps/bridge/next.config.mjs
  apps/bridge/package.json
  apps/games/next.config.mjs
  apps/games/package.json
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/src/pages/api/_report/csp.ts
  pnpm-lock.yaml
Labels: size/L

#8569 chore: Banner copy update
  apps/web/src/views/Home/components/Banners/PerpetualBanner.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#8570 feat: Move finished pools
  .changeset/quick-lions-know.md
  packages/pools/src/constants/pools/56.ts
Labels: size/S, automerge

#8562 feat: Remove blog duplicate code
  apps/blog/components/Article/AllArticle/index.tsx
  apps/blog/components/Article/CardArticle.tsx
  apps/blog/components/Article/CategoriesSelector.tsx
  apps/blog/components/Article/SingleArticle/ArticleInfo.tsx
  apps/blog/components/Article/SingleArticle/SimilarArticles.tsx
  apps/blog/components/BlogCard.tsx
  apps/blog/components/ChefsChoice/index.tsx
  apps/blog/components/NewBlog.tsx
  apps/blog/hooks/getArticle.ts
  apps/blog/hooks/useAllArticle.ts
  apps/blog/hooks/useSearchBarArticle.ts
  apps/blog/package.json
  apps/blog/pages/articles/[slug].tsx
  apps/blog/types.ts
  apps/blog/utils/transformArticle.ts
  apps/web/package.json
  apps/web/src/views/Home/hooks/getArticle.ts
  apps/web/src/views/Home/hooks/useAllArticle.ts
  apps/web/src/views/Home/types.ts
  apps/web/src/views/Home/utils/transformArticle.ts
  package.json
  packages/blog/src/utils/transformArticle.ts
  pnpm-lock.yaml
Labels: size/L

#8571 feat: Remove banner
  apps/web/src/views/Home/components/Banners/LiquidStakingBanner.tsx
  apps/web/src/views/Home/components/Banners/TradingRewardBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  apps/web/src/views/Home/components/Banners/images/butter-2.png
  apps/web/src/views/Home/components/Banners/images/butter.png
  apps/web/src/views/Home/components/Banners/images/index.ts
  apps/web/src/views/Home/components/Banners/images/liquidStakingBunny.png
  apps/web/src/views/Home/components/Banners/images/liquidStakingBunnyBg1.png
  apps/web/src/views/Home/components/Banners/images/liquidStakingBunnyBg2.png
  apps/web/src/views/Home/components/Banners/images/liquidStakingBunnyBg2Mobile.png
  apps/web/src/views/Home/components/Banners/images/liquidStakingBunnyBg3.png
  apps/web/src/views/Home/components/Banners/images/liquidStakingBunnyBg4.png
  apps/web/src/views/Home/components/Banners/images/liquidStakingBunnyMobile.png
  apps/web/src/views/Home/components/Banners/images/liquidStakingTitle.png
  apps/web/src/views/Home/components/Banners/images/liquidStakingTitleMobile.png
  apps/web/src/views/Home/components/Banners/images/love-butter.png
  apps/web/src/views/Home/components/Banners/images/trading-reward-bg.png
  apps/web/src/views/Home/components/Banners/images/trading-reward-bunny.png
  packages/localization/src/config/translations.json
Labels: size/XL, automerge

#8574 feat: add 3 bsc v3 farm & update merkl notice
  .changeset/blue-oranges-tan.md
  apps/web/src/views/Farms/components/FarmCard/CardHeading.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3Card.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/Farms/components/FarmTable/Farm.tsx
  apps/web/src/views/Farms/components/FarmTable/FarmTable.tsx
  packages/farms/constants/bsc.ts
  packages/localization/src/config/translations.json
  packages/tokens/src/56.ts
  packages/widgets-internal/farm/components/FarmTable/FarmTokenInfo.tsx
  packages/widgets-internal/farm/components/MerklNotice/index.tsx
  packages/widgets-internal/farm/types.ts
Labels: size/L

#8575 feat: update eth farm list
  packages/farms/constants/eth.ts
  packages/tokens/src/1.ts
Labels: size/M, automerge

#8576 chore: Remove ledger
  apps/web/src/config/wallet.ts
  apps/web/src/hooks/useEagerConnect.bmp.ts
  apps/web/src/utils/wagmi.ts
  package.json
  packages/ifos/package.json
  packages/pools/package.json
  packages/position-managers/package.json
  packages/uikit/package.json
  packages/wagmi/package.json
  pnpm-lock.yaml
Labels: size/XL

#8579 revert: "chore: Remove ledger"
  apps/web/src/config/wallet.ts
  apps/web/src/hooks/useEagerConnect.bmp.ts
  apps/web/src/utils/wagmi.ts
  package.json
  packages/ifos/package.json
  packages/pools/package.json
  packages/position-managers/package.json
  packages/uikit/package.json
  packages/wagmi/package.json
  pnpm-lock.yaml
Labels: size/XL

#8577 chore: Patch ledger connect kit
  package.json
  patches/@ledgerhq__connect-kit-loader@1.1.2.patch
  pnpm-lock.yaml
Labels: size/M

#8582 feat: add gauges config
  packages/gauges/src/constants/config.ts
Labels: size/M

#8559 refactor: use react-window render gauges list
  apps/web/package.json
  apps/web/src/views/GaugesVoting/components/Table/AddGauge/AddGaugeModal.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/TableRow.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/index.tsx
  pnpm-lock.yaml
Labels: size/M, automerge

#8586 chore: update landing community section
  apps/web/src/views/Home/components/CommunitySection/CommunitySummary.tsx
  apps/web/src/views/Home/components/CommunitySection/TwitterCards.tsx
Labels: size/S

#8474 feat: VeCAKE voting power
  apps/web/src/utils/calls/pools.ts
  apps/web/src/views/Voting/components/CastVoteModal/DetailsView.tsx
  apps/web/src/views/Voting/components/CastVoteModal/MainView.tsx
  apps/web/src/views/Voting/components/CastVoteModal/index.tsx
  apps/web/src/views/Voting/components/VoteDetailsModal.tsx
  apps/web/src/views/Voting/helpers.ts
  apps/web/src/views/Voting/hooks/useGetVotingPower.tsx
  apps/web/src/views/Voting/strategies.ts
  packages/localization/src/config/translations.json
Labels: Delayed Release, size/L

#8596 feat: list ace in syrup pool
  packages/pools/src/constants/pools/56.ts
  packages/tokens/src/56.ts
Labels: size/S

#8597 ci: fixed all workflow node version
  .github/workflows/deploy-apis.yml
  .github/workflows/farmConfig.yml
  .github/workflows/format.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
Labels: size/S

#8600 chore: veCake UI QA pool table view
  apps/web/src/views/CakeStaking/components/SyrupPool/VeCakeButton.tsx
  apps/web/src/views/CakeStaking/components/SyrupPool/VeCakeMigrateCard.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/RecentCakeProfitRow.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/AutoHarvest.tsx
Labels: size/M

#8598 feat: Tokens missing project link
  packages/tokens/src/1101.ts
  packages/tokens/src/42161.ts
  packages/tokens/src/59144.ts
  packages/tokens/src/8453.ts
Labels: size/L, automerge

#8592 chore: Upgrade merkl v2
  apps/web/src/hooks/useMerkl.tsx
Labels: size/M

#8595 chore: Update pokt url
  apps/web/src/config/nodes.ts
  apps/web/src/utils/node/pokt.ts
Labels: size/S

#8585 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#8581 chore: Ledger connector
  apps/web/src/config/wallet.ts
  apps/web/src/utils/wagmi.ts
Labels: size/M

#8514 feat: Ve-bcake
  .changeset/bright-months-melt.md
  apps/web/src/config/chains.ts
  apps/web/src/config/constants/contracts.ts
  apps/web/src/hooks/useContract.ts
  apps/web/src/state/farmsV3/hooks.ts
  apps/web/src/utils/addressHelpers.ts
  apps/web/src/utils/contractHelpers.ts
  apps/web/src/utils/viem.ts
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
  apps/web/src/views/Farms/components/FarmCard/CardHeading.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3ApyButton.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3Card.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/SingleFarmV3Card.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/Farms/components/FarmTable/Row.tsx
  apps/web/src/views/Farms/components/YieldBooster/components/BoostedAction.tsx
  apps/web/src/views/Farms/components/YieldBooster/components/bCakeV3/BCakeBoosterCard.tsx
  apps/web/src/views/Farms/components/YieldBooster/components/bCakeV3/CardView.tsx
  apps/web/src/views/Farms/components/YieldBooster/components/bCakeV3/StatusView.tsx
  apps/web/src/views/Farms/components/YieldBooster/hooks/bCakeV3/multiplierAPI.ts
  apps/web/src/views/Farms/components/YieldBooster/hooks/bCakeV3/useBCakeV3Info.ts
  apps/web/src/views/Farms/components/YieldBooster/hooks/bCakeV3/useBoostStatus.ts
  apps/web/src/views/Farms/components/YieldBooster/hooks/bCakeV3/useIsSomePositionBoosted.ts
  apps/web/src/views/Farms/components/YieldBooster/hooks/bCakeV3/useUpdateLiquidity.ts
  packages/farms/constants/v3/abi/bCakeFarmBoosterV3.ts
  packages/farms/constants/v3/abi/bCakeFarmBoosterVeCake.ts
  packages/farms/constants/v3/index.ts
  packages/farms/index.test.ts
  packages/farms/package.json
  packages/farms/src/index.ts
  packages/localization/src/config/translations.json
  packages/widgets-internal/farm/components/FarmTable/Multiplier.tsx
Labels: size/XXL

#8601 chore: VeCake UI QA pool table view part2
  apps/web/src/views/CakeStaking/components/SyrupPool/LearnMoreLink.tsx
  apps/web/src/views/CakeStaking/components/SyrupPool/VeCakeUpdateCard.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/AutoHarvest.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#8588 chore: Update voting threshold
  apps/web/src/views/Voting/config.ts
Labels: size/XS

#8599 feat: opBNB farm
  .vscode/settings.json
  apis/farms/.dev.vars
  apis/farms/src/bindings.d.ts
  apis/farms/src/provider.ts
  apis/farms/src/v3.ts
  apps/web/src/components/TokenImage/index.tsx
  apps/web/src/config/constants/tokenLists/pancake-default.tokenlist.json
  apps/web/src/views/TradingReward/config/pairs/index.tsx
  packages/chains/src/subgraphs.ts
  packages/farms/constants/common/index.ts
  packages/farms/constants/opBNB.ts
  packages/farms/constants/v3/index.ts
  packages/farms/src/const.ts
  packages/multicall/src/constants/gasLimit.ts
  packages/tokens/src/common.ts
Labels: size/L

#8605 feat: add opbnb common price
  packages/farms/constants/common/index.ts
Labels: size/XS, automerge

#8606 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XL

#8593 chore: Bump up swiper
  apps/aptos/package.json
  apps/blog/package.json
  apps/games/package.json
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/M

#8609 chore: Remove meetup banner
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/XS

#8604 fix: ACE apr
  apps/web/src/state/pools/fetchAceTokenPrice.ts
  apps/web/src/state/pools/index.ts
  apps/web/src/views/V3Info/components/TokenTable/index.tsx
Labels: size/L

#8612 feat: Add APTS Warning Modal
  apps/aptos/components/SwapWarningModal/APTSWarning.tsx
  apps/aptos/components/SwapWarningModal/config.ts
  packages/localization/src/config/translations.json
Labels: size/S, automerge

#8611 feat: Sort banner
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/XS

#8396 refactor: Use query in airdrop
  apps/web/src/components/GlobalCheckClaimStatus/V3AirdropModal.tsx
  apps/web/src/components/GlobalCheckClaimStatus/hooks/useAirdropModalStatus.tsx
Labels: size/M

#8602 chore: list BRIL vault on Eth for position manager
  packages/position-managers/src/constants/vaults/eth.ts
Labels: Delayed Release, size/S

#8618 chore: update duplicate id
  packages/position-managers/src/constants/vaults/eth.ts
Labels: size/XS

#8615 chore: Add dd rum integration
  .github/pull_request_template.md
  apps/web/.env.example
  apps/web/package.json
  apps/web/src/hooks/useDataDogRUM.ts
  apps/web/src/hooks/useExperimentalFeatureEnabled.ts
  apps/web/src/pages/_app.tsx
  apps/web/src/state/user/hooks/index.tsx
  pnpm-lock.yaml
Labels: size/L

#8622 feat: List Farms
  packages/farms/constants/bsc.ts
  packages/farms/constants/eth.ts
  packages/tokens/src/1.ts
  packages/tokens/src/56.ts
Labels: size/M

#8624 fix: Remove gas cost adjustment for single hop v3 swaps
  packages/smart-router/evm/constants/gasModel/index.ts
  packages/smart-router/evm/v3-router/providers/onChainQuoteProvider.ts
  packages/smart-router/evm/v3-router/providers/quoteProviders.ts
Labels: size/M

#8558 feat: Binance web3 wallet integration
  apps/web/package.json
  apps/web/src/config/wallet.ts
  apps/web/src/hooks/useEagerConnect.ts
  apps/web/src/utils/wagmi.ts
  pnpm-lock.yaml
Labels: size/L

#8626 feat: Add gauges
  packages/gauges/src/constants/config.ts
Labels: size/M

#8614 feat: veCake apr
  apps/web/src/config/constants/contracts.ts
  apps/web/src/views/CakeStaking/components/CakeRewardsCard.tsx
  apps/web/src/views/CakeStaking/hooks/useAPR.ts
  apps/web/src/views/CakeStaking/hooks/useVeCakeTotalSupply.ts
  packages/localization/src/config/translations.json
Labels: size/L

#8629 feat: Add farms
  packages/farms/constants/bsc.ts
  packages/gauges/src/constants/config.ts
  packages/tokens/src/56.ts
Labels: size/M

#8623 feat: List Alp opBNB pool
  .changeset/dull-tools-hide.md
  apps/web/src/state/pools/index.ts
  apps/web/src/utils/fetchTokenAplPrice.ts
  apps/web/src/utils/llamaPrice.ts
  packages/pools/src/constants/boostedPools/index.ts
  packages/pools/src/constants/boostedPools/opBNB.ts
  packages/pools/src/constants/contracts.ts
  packages/pools/src/constants/pools/204.ts
  packages/pools/src/constants/pools/index.ts
  packages/pools/src/constants/supportedChains.ts
  packages/pools/src/utils/boosted/apr/getBoostedPoolApr.ts
  packages/tokens/src/204.ts
Labels: size/L, automerge

#8628 chore: Increase sample rate for rum
  apps/web/src/hooks/useDataDogRUM.ts
Labels: size/XS

#8631 chore: List sdcake cake stable pool
  packages/smart-router/evm/constants/stableSwap/56.ts
  packages/tokens/src/56.ts
Labels: size/M

#8636 feat: Add ALP opBNB boosted APR
  packages/pools/src/constants/boostedPools/opBNB.ts
  packages/pools/src/utils/boosted/apr/fetchAlpBoostedPoolApr.ts
  packages/pools/src/utils/boosted/apr/getBoostedPoolApr.ts
Labels: size/M, automerge

#8627 feat: Xmas Effect
  apps/web/public/images/x-mas-2023/flakes-1.png
  apps/web/public/images/x-mas-2023/flakes-2.png
  apps/web/public/images/x-mas-2023/flakes-3.png
  apps/web/public/images/x-mas-2023/flakes-4.png
  apps/web/public/images/x-mas-2023/flakes-5.png
  apps/web/public/images/x-mas-2023/flakes-6.png
  apps/web/public/images/x-mas-2023/flakes-7.png
  apps/web/public/images/x-mas-2023/flakes-8.png
  apps/web/public/images/x-mas-2023/xmas-1.png
  apps/web/public/images/x-mas-2023/xmas-2.png
  apps/web/public/images/x-mas-2023/xmas-3.png
  apps/web/src/components/XmasEffect/index.tsx
  apps/web/src/pages/_app.tsx
  apps/web/src/pages/index.tsx
Labels: size/M, automerge

#8633 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#8632 feat: add sdcake gauge
  packages/gauges/src/constants/config.ts
Labels: size/S

#8637 chore: RUM strategy update
  apps/web/src/components/Menu/GlobalSettings/TransactionSettings.tsx
  apps/web/src/components/Menu/GlobalSettings/index.tsx
  apps/web/src/config/experimentalFeatures.ts
  apps/web/src/hooks/useDataDogRUM.ts
  apps/web/src/hooks/useExperimentalFeatureEnabled.ts
  apps/web/src/hooks/useGlobalSettingsEvaluation.ts
  apps/web/src/hooks/useWebNotifications.ts
  apps/web/src/middlewares/ab-test-middleware.ts
  apps/web/src/pages/_app.tsx
  apps/web/src/state/user/hooks/index.tsx
  apps/web/src/utils/datadog.ts
Labels: size/L

#8638 feat: Add token price references
  .changeset/fresh-bags-fail.md
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/hooks/useCurrencyPrice.ts
  apps/web/src/quote-worker.ts
  apps/web/src/utils/getCurrencyPrice.ts
  packages/smart-router/evm/v3-router/gasModel.ts
  packages/smart-router/evm/v3-router/getBestTrade.ts
  packages/smart-router/evm/v3-router/providers/quoteProviders.ts
  packages/smart-router/evm/v3-router/schema.ts
  packages/smart-router/evm/v3-router/types/trade.ts
Labels: size/L

#8643 chore(smart-router): clean up log
  .changeset/calm-oranges-agree.md
  .vscode/settings.json
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/hooks/usePoolsOnChain.ts
  apps/web/src/hooks/useV3Pools.ts
  packages/smart-router/evm/index.test.ts
  packages/smart-router/evm/utils/withFallback.ts
  packages/smart-router/evm/v3-router/functions/computeAllRoutes.ts
  packages/smart-router/evm/v3-router/functions/getBestRouteCombinationByQuotes.ts
  packages/smart-router/evm/v3-router/getRoutesWithValidQuote.ts
  packages/smart-router/evm/v3-router/providers/getCommonTokenPrices.ts
  packages/smart-router/evm/v3-router/providers/multicallSwapProvider.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/getV2CandidatePools.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/subgraphPoolProviders.ts
  packages/smart-router/evm/v3-router/providers/quoteProviders.ts
  packages/smart-router/evm/v3-router/smartRouter.ts
  packages/smart-router/evm/v3-router/utils/index.ts
  packages/smart-router/evm/v3-router/utils/logger.ts
  packages/smart-router/evm/v3-router/utils/metric.ts
Labels: size/L

#8641 feat: Add farms
  packages/farms/constants/bsc.ts
  packages/farms/constants/eth.ts
  packages/gauges/src/constants/config.ts
Labels: size/L

#8613 chore: Ignore migrated position and CAKE pool position when user delegated
  apps/web/src/state/types.ts
  apps/web/src/views/CakeStaking/hooks/useIsUserDelegated.ts
  apps/web/src/views/CakeStaking/types.ts
  apps/web/src/views/Pools/components/CakeVaultCard/VaultCardActions/HasSharesActions.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/VaultCardActions/VaultStakeActions.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/VaultCardActions/index.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/index.tsx
  apps/web/src/views/Pools/components/LockedPool/Modals/LockedStakeModal.tsx
  apps/web/src/views/Pools/components/LockedPool/types/index.ts
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
  apps/web/src/views/Pools/components/PoolsTable/PoolRow.tsx
Labels: size/L

#8616 chore: position manager APR time window adjustment
  apps/web/src/views/PositionManagers/components/AddLiquidity.tsx
  apps/web/src/views/PositionManagers/components/AprButton.tsx
  apps/web/src/views/PositionManagers/components/DuoTokenVaultCard.tsx
  apps/web/src/views/PositionManagers/components/LiquidityManagement.tsx
  apps/web/src/views/PositionManagers/components/YieldInfo.tsx
  apps/web/src/views/PositionManagers/containers/PCSVaultCard.tsx
  apps/web/src/views/PositionManagers/containers/VaultCards.tsx
  apps/web/src/views/PositionManagers/hooks/useFetchApr.ts
  packages/localization/src/config/translations.json
  packages/position-managers/src/types.ts
Labels: size/L

#8647 fix: farm card unconnected UI
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3Card.tsx
Labels: size/XS

#8646 feat: add galxe banner
  apps/web/src/views/Home/components/Banners/GalxeTraverseBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#8649 fix: update banner word
  apps/web/src/views/Home/components/Banners/GalxeTraverseBanner.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#8651 refactor: Automatically load all experimental flags based on config
  apps/web/src/hooks/useDataDogRUM.ts
  apps/web/src/hooks/useExperimentalFeatureEnabled.ts
Labels: size/M

#8650 feat: re-enable buy crypto
  apps/web/src/views/BuyCrypto/components/GetQuotesButton.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#8655 fix: gauge pair name
  packages/gauges/src/constants/config.ts
Labels: size/XS

#8656 fix: onramp fixes an cleanup
  apps/web/src/components/Card/index.tsx
  apps/web/src/config/constants/tokenLists/pancake-supported-onramp-currency-list.json
  apps/web/src/views/BuyCrypto/components/AccordionDropdown/Accordion.tsx
  apps/web/src/views/BuyCrypto/components/AccordionDropdown/AccordionItem.tsx
  apps/web/src/views/BuyCrypto/components/ProviderCampaign/ProviderCampaign.tsx
  apps/web/src/views/BuyCrypto/components/Tooltip/Tooltip.tsx
  apps/web/src/views/BuyCrypto/constants.ts
  apps/web/src/views/BuyCrypto/containers/BuyCryptoForm.tsx
  apps/web/src/views/BuyCrypto/styles.tsx
  apps/web/src/views/BuyCrypto/types.ts
  packages/localization/src/config/translations.json
Labels: size/L

#8660 fix: correct the gid
  packages/gauges/src/constants/config.ts
Labels: size/M

#8476 feat: iCAKE v2 -> (i)veCAKE
  apps/web/public/images/ifos/assets/ifo-sales-active.png
  apps/web/public/images/ifos/assets/ifo-sales.png
  apps/web/src/config/constants/contracts.ts
  apps/web/src/state/pools/hooks.ts
  apps/web/src/utils/addressHelpers.ts
  apps/web/src/views/CakeStaking/hooks/useLockAllowance.ts
  apps/web/src/views/Ifos/CurrentIfo.tsx
  apps/web/src/views/Ifos/SoonIfo.tsx
  apps/web/src/views/Ifos/components/IfoCardStyles.tsx
  apps/web/src/views/Ifos/components/IfoContainer.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ICakeTips.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardTokens.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/index.tsx
  apps/web/src/views/Ifos/components/IfoPoolVaultCard.tsx
  apps/web/src/views/Ifos/components/IfoQuestions/config.tsx
  apps/web/src/views/Ifos/components/IfoSteps.tsx
  apps/web/src/views/Ifos/components/IfoVesting/index.tsx
  apps/web/src/views/Ifos/components/VeCakeCard.tsx
  apps/web/src/views/Ifos/hooks/useIfoCredit.ts
  apps/web/src/views/Ifos/hooks/useUserIfoInfo.ts
  apps/web/src/views/Pools/components/PoolStatsInfo.tsx
  packages/ifos/src/abis/ICake.ts
  packages/ifos/src/constants/contracts.ts
  packages/ifos/src/index.test.ts
  packages/ifos/src/queries/fetchUserIfo.ts
  packages/localization/src/config/translations.json
  packages/pools/src/constants/contracts.ts
  packages/uikit/src/components/Balance/Balance.tsx
  packages/uikit/src/components/Balance/index.tsx
  packages/uikit/src/components/Button/ExpandableButton.tsx
  packages/uikit/src/tokens/colors.ts
  packages/utils/formatTimestamp.ts
  packages/widgets-internal/ifo/BalanceDisplay.tsx
  packages/widgets-internal/ifo/ICakeInfo.tsx
  packages/widgets-internal/ifo/LockInfoCard.tsx
  packages/widgets-internal/ifo/MyVeCake.tsx
  packages/widgets-internal/ifo/Tips.tsx
  packages/widgets-internal/ifo/VeCakeCard.tsx
  packages/widgets-internal/ifo/index.ts
  packages/widgets-internal/index.ts
Labels: Delayed Release, size/XXL

#8661 feat: use sonner as toast
  apps/aptos/pages/_app.tsx
  apps/web/src/Providers.tsx
  packages/uikit/.storybook/main.js
  packages/uikit/.storybook/preview.jsx
  packages/uikit/package.json
  packages/uikit/src/Providers.tsx
  packages/uikit/src/components/Toast/Toast.stories.tsx
  packages/uikit/src/components/Toast/Toast.tsx
  packages/uikit/src/components/Toast/ToastContainer.tsx
  packages/uikit/src/components/Toast/index.ts
  packages/uikit/src/components/Toast/types.ts
  packages/uikit/src/contexts/ToastsContext/Listener.tsx
  packages/uikit/src/contexts/ToastsContext/Provider.tsx
  packages/uikit/src/contexts/ToastsContext/types.ts
  pnpm-lock.yaml
Labels: size/XL

#8652 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#8658 fix: resolve notification not loading bug
  apps/web/src/views/Notifications/components/NotificationDropdown/NotificationMenu.tsx
  apps/web/src/views/Notifications/index.tsx
Labels: size/S

#8664 chore: Log swap error
  apps/web/src/utils/log.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSendSwapTransaction.ts
Labels: size/S

#8662 fix(ci): Workflow lint should follow repo config
  .github/workflows/lint.yml
  package.json
  packages/swap-sdk-core/src/errors.ts
  turbo.json
Labels: size/S

#8665 chore: Fix readme
  README.md
Labels: size/M

#8666 fix: remove repeated guage
  packages/gauges/src/constants/config.ts
Labels: size/S

#8668 feat: update arb farm
  packages/farms/constants/arb.ts
Labels: size/L

#8667 fix: cake extend amount
  apps/web/src/views/CakeStaking/components/DataSet/LockWeeksDataSet.tsx
Labels: size/S

#8670 feat: add RDP farm
  packages/farms/constants/bsc.ts
  packages/tokens/src/56.ts
Labels: size/S, automerge

#8669 test: better test describe
  packages/farms/tests/v3.test.ts
Labels: size/M, automerge

#8675 fix: 0 denominator
  apps/web/src/views/CakeStaking/components/CakeRewardsCard.tsx
  apps/web/src/views/CakeStaking/hooks/useAPR.ts
Labels: size/XS

#8674 fix(uikit): toast theme override
  .vscode/extensions.json
  apps/web/src/hooks/useCatchTxError.tsx
  apps/web/src/views/FixedStaking/hooks/useHandleWithdrawSubmission.tsx
  packages/uikit/src/components/Toast/Toast.tsx
  packages/uikit/src/contexts/ToastsContext/Listener.tsx
  packages/uikit/src/contexts/ToastsContext/Provider.tsx
  packages/uikit/src/contexts/ToastsContext/types.ts
Labels: size/L

#8676 fix: rdp token
  packages/tokens/src/56.ts
Labels: size/XS

#8678 chore: Update swap error log cause
  apps/web/src/views/Swap/V3Swap/hooks/useSendSwapTransaction.ts
Labels: size/XS

#8679 feat: add zksync gauges
  packages/gauges/src/constants/config.ts
Labels: size/L

#8680 ci: upgrade checkout action
  .github/workflows/format.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/testConfig.yml
  .github/workflows/unitTests.yml
  .github/workflows/updateCron.yml
Labels: size/S

#8681 fix: wrong token image
  packages/gauges/src/constants/config.ts
Labels: size/XS

#8682 feat: add gauge
  packages/gauges/src/constants/config.ts
Labels: size/S

#8687 fix: reverse lp address
  apps/aptos/config/constants/farms/1.ts
Labels: size/XS

#8648 chore: update homepage v2
  apps/aptos/components/NetworkSwitcher.tsx
  apps/web/src/components/NetworkModal/PageNetworkSupportModal.tsx
  apps/web/src/components/NetworkSwitcher.tsx
  apps/web/src/utils/chainNameConverter.ts
  apps/web/src/views/AffiliatesProgram/components/Overview/Question.tsx
  apps/web/src/views/BuyCrypto/constants.ts
  apps/web/src/views/Home/components/CakeSection/CakeSectionTag.tsx
  apps/web/src/views/Home/components/CakeSection/PartnerLogos.tsx
  apps/web/src/views/Home/components/EcoSystemSection/index.tsx
  apps/web/src/views/Home/components/MetricsSection/ChainTags.tsx
  apps/web/src/views/Home/images/earn-bunny.png
  apps/web/src/views/Home/images/earn-farm-purple.png
  apps/web/src/views/Home/images/earn-farm.png
  apps/web/src/views/Home/images/earn-fixed-staking-purple.png
  apps/web/src/views/Home/images/earn-fixed-staking.png
  apps/web/src/views/Home/images/earn-liquidity-staking-purple.png
  apps/web/src/views/Home/images/earn-liquidity-staking.png
  apps/web/src/views/Home/images/earn-pools-purple.png
  apps/web/src/views/Home/images/earn-pools.png
  apps/web/src/views/Home/images/eth-tag.png
  apps/web/src/views/Home/images/game-lottery-purple.png
  apps/web/src/views/Home/images/game-lottery.png
  apps/web/src/views/Home/images/game-nft-bunny.png
  apps/web/src/views/Home/images/game-pancake-protectors-purple.png
  apps/web/src/views/Home/images/game-pancake-protectors.png
  apps/web/src/views/Home/images/game-pottery-purple.png
  apps/web/src/views/Home/images/game-pottery.png
  apps/web/src/views/Home/images/game-prediction-purple.png
  apps/web/src/views/Home/images/game-prediction.png
  apps/web/src/views/Home/images/hero.gif
  apps/web/src/views/Home/images/linea-tag.png
  apps/web/src/views/Home/images/nft-marketplace-purple.png
  apps/web/src/views/Home/images/nft-marketplace.png
  apps/web/src/views/Home/images/partner-1inch.png
  apps/web/src/views/Home/images/partner-binance.png
  apps/web/src/views/Home/images/partner-ledger.png
  apps/web/src/views/Home/images/partner-metamask.png
  apps/web/src/views/Home/images/partner-more.png
  apps/web/src/views/Home/images/polygon-zkevm-tag.png
  apps/web/src/views/Home/images/trade-bridge-purple.png
  apps/web/src/views/Home/images/trade-bridge.png
  apps/web/src/views/Home/images/trade-bunny.png
  apps/web/src/views/Home/images/trade-buy-crypto-purple.png
  apps/web/src/views/Home/images/trade-buy-crypto.png
  apps/web/src/views/Home/images/trade-liquidity-purple.png
  apps/web/src/views/Home/images/trade-liquidity.png
  apps/web/src/views/Home/images/trade-perpetual-purple.png
  apps/web/src/views/Home/images/trade-perpetual.png
  apps/web/src/views/Home/images/trade-swap-purple.png
  apps/web/src/views/Home/images/trade-swap.png
  packages/localization/src/config/translations.json
  packages/uikit/src/components/Svg/Icons/Bulb.tsx
  packages/uikit/src/components/Svg/Icons/PieChart.tsx
  packages/uikit/src/components/Svg/index.tsx
Labels: size/L

#8686 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XXL

#8690 fix: landing eco system pm link
  apps/web/src/views/Home/components/EcoSystemSection/index.tsx
Labels: size/XS

#8691 feat: Remove Ace token price
  apps/web/src/state/pools/index.ts
Labels: size/S, automerge

#8694 fix: invert token
  apps/aptos/config/constants/farms/1.ts
Labels: size/XS

#8697 fix(aptos): simulation use expireation ledger time
  apps/aptos/hooks/useLedgerTimestamp.ts
  apps/aptos/hooks/useSimulationAndSendTransaction.ts
  packages/awgmi/core/src/transactions/simulateTransaction.ts
Labels: size/S

#8698 feat: add gauges and farms
  packages/farms/constants/bsc.ts
  packages/gauges/src/constants/config.ts
  packages/tokens/src/56.ts
Labels: size/M

#8703 chore: Update unsupported token
  apps/web/src/config/constants/tokenLists/pancake-unsupported.tokenlist.json
  apps/web/src/state/info/queries/tokens/poolsForToken.ts
  apps/web/src/state/lists/hooks.ts
  apps/web/src/utils/pageUtils.ts
Labels: size/M

#8693 fix: delegated user treat as no staking
  apps/web/src/views/CakeStaking/hooks/useVeCakeUserInfo.ts
Labels: size/S

#8704 feat: list nfp farm & gauge
  packages/farms/constants/bsc.ts
  packages/gauges/src/constants/config.ts
  packages/tokens/src/56.ts
Labels: size/S

#8673 fix: update ve amount calc
  apps/web/src/utils/getVeCakeAmount.ts
  apps/web/src/views/CakeStaking/components/DataSet/DataBox.tsx
  apps/web/src/views/CakeStaking/components/DataSet/LockCakeDataSet.tsx
  apps/web/src/views/CakeStaking/components/DataSet/LockWeeksDataSet.tsx
  apps/web/src/views/CakeStaking/components/DataSet/NewStakingDataSet.tsx
  apps/web/src/views/CakeStaking/components/LockCake/NotLocking.tsx
  apps/web/src/views/CakeStaking/components/LockWeeksForm.tsx
  apps/web/src/views/CakeStaking/components/LockedVeCakeStatus.tsx
  apps/web/src/views/CakeStaking/components/Tooltips.tsx
  apps/web/src/views/CakeStaking/hooks/useMaxUnlockTime.ts
  apps/web/src/views/CakeStaking/hooks/useTargetUnlockTime.ts
  apps/web/src/views/CakeStaking/hooks/useVeCakeAmount.ts
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/TableRow.tsx
Labels: size/L

#8708 feat: delist 8pay, new list 8pay v2
  apps/web/src/config/constants/farmAuctions.ts
  packages/farms/constants/bsc.ts
  packages/pools/src/constants/pools/56.ts
  packages/tokens/src/56.ts
Labels: size/S

#8709 feat: add 3 farms & gauges
  packages/farms/constants/bsc.ts
  packages/farms/constants/zkSync.ts
  packages/gauges/src/constants/config.ts
Labels: size/M

#8710 fix: allow symbol contain space
  packages/token-lists/schema/pancakeswap.json
Labels: size/XS

#8711 fix(ui): button option width
  apps/web/src/views/CakeStaking/components/LockWeeksForm.tsx
Labels: size/XS

#8712 fix: sdcake cake stableswap address
  apps/web/src/views/AddLiquidity/AddStableLiquidity/hooks/useStableLPDerivedMintInfo.tsx
  apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
  packages/smart-router/evm/constants/stableSwap/56.ts
Labels: size/M

#8714 chore: update X content
  apps/web/src/views/Home/components/CommunitySection/TwitterCards.tsx
Labels: size/S

#8717 fix: add delegate condition
  apps/web/src/views/CakeStaking/hooks/useVeCakeUserInfo.ts
Labels: size/S

#8718 feat: add sdcake farm & gauge
  packages/farms/constants/bsc.ts
  packages/gauges/src/constants/config.ts
Labels: size/S
