Repository pancakeswap/pancake-frontend, pull requests merged in 2023-05, with the labels that each got.

#6739 chore: sort latest from v3 to v2 in farm
  apps/aptos/components/Menu/Menu.tsx
  apps/web/src/components/Menu/index.tsx
  apps/web/src/views/Farms/Farms.tsx
  apps/web/src/views/Farms/FarmsV3.tsx
  packages/uikit/src/__tests__/widgets/menu.test.tsx
  packages/uikit/src/components/CakePrice/CakePrice.tsx
  packages/uikit/src/components/Footer/Footer.tsx
  packages/uikit/src/components/Footer/types.ts
  packages/uikit/src/widgets/Menu/Menu.tsx
  packages/uikit/src/widgets/Menu/types.ts
Labels: size/M

#6789 fix(v2-sdk): fetcher export
  .changeset/shy-panthers-hear.md
  packages/swap-sdk/src/index.ts
Labels: size/XS

#6786 feat: v3 onchain fallback
  apps/web/src/components/CurrencyInputPanel/index.tsx
  apps/web/src/hooks/useBUSDPrice.ts
  apps/web/src/hooks/useCommonPools.ts
  apps/web/src/hooks/useV3Pools.ts
Labels: size/M

#6788 feat: V3 priceChart precision improvement
  packages/uikit/src/components/Chart/PairPriceChart.tsx
Labels: size/XS

#6782 chore(LockPool): AfterBurning alert UI adjustment
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
Labels: size/S

#6780 feat(FarmsV3): Add farmTypes filter
  apps/web/src/views/Farms/FarmsV3.tsx
  apps/web/src/views/Farms/components/FarmTypesFilter.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#6778 chore(aptos-Pools): Ends in cell don't show on mobile
  apps/aptos/components/Pools/components/PoolTable/PoolRow.tsx
Labels: size/XS

#6765 chore: Move bunny png
  apps/web/src/views/Home/components/Hero.tsx
Labels: size/S

#6756 fix: Min width prop error on modals
  apps/aptos/components/Menu/WalletModal.tsx
  apps/web/src/components/Menu/UserMenu/WalletModal.tsx
  apps/web/src/views/PancakeSquad/components/Modals/BuyTickets/index.tsx
  apps/web/src/views/PancakeSquad/components/Modals/Confirm/index.tsx
  apps/web/src/views/Predictions/Leaderboard/components/WalletStatsModal.tsx
  apps/web/src/views/Predictions/components/ChainlinkChartDisclaimer.tsx
  apps/web/src/views/Predictions/components/ChartDisclaimer.tsx
Labels: size/M

#6701 feat: Affiliate program phase 1.5
  apps/web/src/pages/affiliates-program/leaderboard.tsx
  apps/web/src/pages/api/affiliates-program/leader-board.ts
  apps/web/src/pages/api/affiliates-program/user-info.ts
  apps/web/src/views/AffiliatesProgram/components/AffiliatesProgramLayout.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/AffiliateLinks.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/AffiliateModal/index.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/Banner.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/ClaimReward.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/ComingSoon.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/CommissionInfo.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/MyReferralLink.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/PieChartContainer.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/index.tsx
  apps/web/src/views/AffiliatesProgram/components/LeaderBoard/LeaderBoardList.tsx
  apps/web/src/views/AffiliatesProgram/components/LeaderBoard/NewUsers.tsx
  apps/web/src/views/AffiliatesProgram/components/LeaderBoard/Podium.tsx
  apps/web/src/views/AffiliatesProgram/components/LeaderBoard/PodiumAvatar.tsx
  apps/web/src/views/AffiliatesProgram/components/LeaderBoard/PodiumText.tsx
  apps/web/src/views/AffiliatesProgram/components/LeaderBoard/index.tsx
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/Congratulations.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/index.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useAuthAffiliate.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useLeaderboard.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useUserInfo.tsx
  packages/localization/src/config/translations.json
Labels: size/XXL

#6774 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XXL

#6794 chore: list peel pool
  packages/pools/src/constants/pools/56.ts
Labels: size/XS

#6777 chore(Liquid Staking): UI improvement
  apps/web/src/views/LiquidStaking/components/ExchangeRateTitle.tsx
  apps/web/src/views/LiquidStaking/components/FAQs.tsx
Labels: size/S

#6800 fix: minor fix after pnpm
  .changeset/config.json
  packages/farms/package.json
  packages/localization/package.json
  packages/smart-router/tsup.config.ts
  pnpm-lock.yaml
Labels: size/M

#6801 perf: Remove web3 provider
  .changeset/calm-walls-crash.md
  .github/workflows/release.yml
  apps/web/src/Providers.tsx
  apps/web/src/state/user/hooks/index.tsx
  apps/web/src/views/AddLiquidityV3/Migrate.tsx
  apps/web/src/views/RemoveLiquidity/index.tsx
  apps/web/src/views/Voting/CreateProposal/index.tsx
  apps/web/src/views/Voting/components/CastVoteModal/index.tsx
  package.json
  packages/wagmi/package.json
  packages/wagmi/src/index.ts
  packages/wagmi/src/provider.tsx
  pnpm-lock.yaml
Labels: size/L

#6795 feat: Show affiliate modal
  apps/web/src/views/AffiliatesProgram/components/Dashboard/AffiliateModal/index.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/index.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useUserExist.tsx
  apps/web/src/views/Home/index.tsx
  packages/localization/src/config/translations.json
Labels: size/M, automerge

#6747 feat: Unstoppable domain integration
  apps/web/src/components/Menu/UserMenu/WalletInfo.tsx
  apps/web/src/components/Menu/UserMenu/index.tsx
  apps/web/src/config/abi/UNS.json
  apps/web/src/hooks/useContract.ts
  apps/web/src/hooks/useDomain.ts
  apps/web/src/hooks/useSid.ts
  apps/web/src/hooks/useUns.ts
  apps/web/src/utils/contractHelpers.ts
  apps/web/src/utils/providers.ts
  apps/web/src/views/FarmAuction/components/WhitelistedBiddersModal.tsx
  apps/web/src/views/Home/components/UserBanner/UserDetail.tsx
  apps/web/src/views/Info/components/InfoTables/TransactionsTable.tsx
  apps/web/src/views/Nft/market/components/Activity/MobileModal.tsx
  apps/web/src/views/Nft/market/components/ProfileCell.tsx
  apps/web/src/views/Pottery/components/FinishedRounds/AllHistoryCard/Winner.tsx
  apps/web/src/views/Predictions/Leaderboard/components/Results/RankingCard.tsx
  apps/web/src/views/Predictions/Leaderboard/components/Results/ResultAvatar.tsx
  apps/web/src/views/Predictions/Leaderboard/components/WalletStatsModal.tsx
  apps/web/src/views/Profile/components/ProfileHeader.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TopTradersCard/ExpandedGridItem.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TopTradersCard/GridItem.tsx
Labels: size/XXL

#6806 chore: Add images redirect
  apps/web/next.config.mjs
  apps/web/src/views/Home/components/Banners/EthBanner.tsx
  apps/web/src/views/Home/components/Banners/FarmV3MigrationBanner.tsx
  apps/web/src/views/Home/components/Banners/LiquidStakingBanner.tsx
  apps/web/src/views/Home/components/Banners/PerpetualApolloXCampaignBanner.tsx
  apps/web/src/views/Home/components/Banners/V3LaunchBanner.tsx
Labels: size/L

#6808 chore: Fix pkg build error
  packages/smart-router/package.json
  pnpm-lock.yaml
Labels: size/S

#6807 chore: list PEEL and BNBX farm
  apps/web/src/pages/index.tsx
  packages/farms/constants/56.ts
Labels: size/S

#6809 chore: Fix remove unnecessary dependencies
  packages/smart-router/package.json
  pnpm-lock.yaml
Labels: size/S

#6812 chore: Increase candidate pools threshold to get better routes
  packages/smart-router/evm/v3-router/providers/subgraphProvider.ts
Labels: size/XS

#6746 feat: V3 Airdrop
  apps/web/public/images/nfts/v3-part1.jpg
  apps/web/public/images/nfts/v3-part2.jpg
  apps/web/src/components/GlobalCheckClaimStatus/V3AirdropModal.tsx
  apps/web/src/components/GlobalCheckClaimStatus/index.tsx
  apps/web/src/config/abi/v3Airdrop.json
  apps/web/src/config/constants/contracts.ts
  apps/web/src/hooks/useContract.ts
  apps/web/src/utils/addressHelpers.ts
  apps/web/src/utils/contractHelpers.ts
  packages/localization/src/config/translations.json
Labels: size/L

#6815 fix: Crash v3 claim
  apps/web/src/components/GlobalCheckClaimStatus/V3AirdropModal.tsx
  apps/web/src/components/GlobalCheckClaimStatus/index.tsx
Labels: size/S

#6811 feat(liquid-staking): add apr
  apps/web/src/pages/liquid-staking/[currency].tsx
  apps/web/src/views/LiquidStaking/Stake/index.tsx
  apps/web/src/views/LiquidStaking/components/ExchangeRateTitle.tsx
  apps/web/src/views/LiquidStaking/components/LiquidStakingApr.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#6817 chore(Profile): Tab gap adjustment
  apps/web/src/views/Nft/market/components/MarketPageHeader.tsx
Labels: size/XS

#6819 chore: Add strict null check to staged files
  .lintstaged.eslintrc
  .lintstagedrc
Labels: size/XS

#6814 chore: Bump up swr and remove jsbi
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/S

#6821 chore: list GAL v3 farm
  packages/farms/constants/56.ts
Labels: size/XS

#6820 chore: remove apollox banner
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/XS

#6824 chore: support tvl chart for v3 pool page
  apps/web/src/views/V3Info/views/PoolPage.tsx
Labels: size/M

#6826 chore: List pepe eth farm
  packages/farms/constants/1.ts
  packages/tokens/src/1.ts
Labels: size/S

#6828 chore(TabMenu): Padding bottom adjustment
  packages/uikit/src/components/TabMenu/TabMenu.tsx
Labels: size/XS, automerge

#6830 fix: Broken image on farm page
  apps/web/public/images/autorenew.svg
  apps/web/public/images/ifo-pool-icon.svg
  apps/web/src/config/constants/pools.tsx
Labels: size/S

#6839 chore(Pools): Change v1 migration url
  apps/web/src/views/Pools/index.tsx
Labels: size/XS

#6840 perf: reduce bundle size double by quote worker deps
  apps/web/next.config.mjs
  apps/web/src/hooks/useBestAMMTrade.ts
  packages/smart-router/evm/legacyRouter/onchain/getPairs.ts
  packages/smart-router/evm/legacyRouter/onchain/getStableSwapFee.ts
  packages/smart-router/evm/legacyRouter/onchain/getStableSwapOutputAmount.ts
  packages/smart-router/evm/legacyRouter/types/bestTrade.ts
  packages/smart-router/evm/v3-router/utils/approveAndCall.ts
  packages/smart-router/evm/v3-router/utils/encodeMixedRouteToPath.ts
  packages/smart-router/evm/v3-router/utils/multicallExtended.ts
  packages/smart-router/evm/v3-router/utils/paymentsExtended.ts
  packages/smart-router/evm/v3-router/utils/swapRouter.ts
  packages/smart-router/evm/v3-router/utils/transformer.ts
  packages/smart-router/package.json
  packages/swap-sdk/package.json
  packages/swap-sdk/src/entities/pair.ts
  packages/swap-sdk/src/fetcher.ts
  packages/swap-sdk/src/utils.ts
  packages/v3-sdk/package.json
  packages/v3-sdk/src/masterchefV3.ts
  packages/v3-sdk/src/multicall.ts
  packages/v3-sdk/src/nonfungiblePositionManager.ts
  packages/v3-sdk/src/payments.ts
  packages/v3-sdk/src/quoter.ts
  packages/v3-sdk/src/selfPermit.ts
  packages/v3-sdk/src/staker.ts
  packages/v3-sdk/src/swapRouter.ts
  packages/v3-sdk/src/utils/computePoolAddress.ts
  packages/v3-sdk/src/utils/encodeRouteToPath.ts
  pnpm-lock.yaml
Labels: size/L

#6842 fix: Dev build error due to splitChunks not turned on
  apps/web/next.config.mjs
Labels: size/XS

#6810 feat: ENS integration
  apps/web/src/components/Menu/UserMenu/index.tsx
  apps/web/src/hooks/useDomain.ts
  apps/web/src/state/swap/hooks.ts
  apps/web/src/state/swap/reducer.ts
  apps/web/src/views/AffiliatesProgram/components/LeaderBoard/PodiumAvatar.tsx
  apps/web/src/views/Home/components/UserBanner/UserDetail.tsx
  apps/web/src/views/Pottery/components/FinishedRounds/AllHistoryCard/Winner.tsx
  apps/web/src/views/Predictions/Leaderboard/components/Results/RankingCard.tsx
  apps/web/src/views/Predictions/Leaderboard/components/Results/ResultAvatar.tsx
  apps/web/src/views/Predictions/Leaderboard/components/WalletStatsModal.tsx
  apps/web/src/views/Profile/components/ProfileHeader.tsx
  apps/web/src/views/Swap/components/AddressInputPanel.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TopTradersCard/ExpandedGridItem.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TopTradersCard/GridItem.tsx
Labels: size/L

#6843 fix: info token realted pool fees usd issue
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/views/V3Info/data/pool/poolData.ts
  apps/web/src/views/V3Info/views/PoolPage.tsx
Labels: size/S

#6846 revert: Revert "chore(TabMenu): Padding bottom adjustment"
  packages/uikit/src/components/TabMenu/TabMenu.tsx
Labels: size/XS

#6847 chore: Update test config node version
  .github/workflows/testConfig.yml
Labels: size/XS

#6845 fix: line chart default color
  apps/web/src/views/V3Info/components/BarChart/index.tsx
  apps/web/src/views/V3Info/components/CandleChart/index.tsx
  apps/web/src/views/V3Info/components/LineChart/alt.tsx
  apps/web/src/views/V3Info/components/LineChart/index.tsx
  apps/web/src/views/V3Info/views/PoolPage.tsx
Labels: size/XS

#6850 fix(liquid-staking): Update staking eth
  apps/web/src/pages/liquid-staking/[currency].tsx
Labels: size/XS

#6783 refactor: Move states to jotai and remove unused functions in swap
  apps/web/src/__tests__/state/swap/fetch/__fixtures__/day-pair-data.json
  apps/web/src/__tests__/state/swap/fetch/__fixtures__/hour-pair-data.json
  apps/web/src/__tests__/state/swap/fetch/util.test.ts
  apps/web/src/pages/add/[[...currency]].tsx
  apps/web/src/pages/increase/[[...currency]].tsx
  apps/web/src/pages/v2/add/[[...currency]].tsx
  apps/web/src/state/burn/hooks.ts
  apps/web/src/state/burn/reducer.ts
  apps/web/src/state/index.ts
  apps/web/src/state/limitOrders/hooks.ts
  apps/web/src/state/limitOrders/reducer.ts
  apps/web/src/state/mint/hooks.ts
  apps/web/src/state/mint/reducer.test.ts
  apps/web/src/state/mint/reducer.ts
  apps/web/src/state/multicall/hooks.ts
  apps/web/src/state/multicall/reducer.test.ts
  apps/web/src/state/multicall/reducer.ts
  apps/web/src/state/multicall/updater.tsx
  apps/web/src/state/swap/fetch/constants.ts
  apps/web/src/state/swap/fetch/fetchPairPriceData.ts
  apps/web/src/state/swap/fetch/types.ts
  apps/web/src/state/swap/fetch/utils.ts
  apps/web/src/state/swap/hooks.test.ts
  apps/web/src/state/swap/hooks.ts
  apps/web/src/state/swap/normalizers.ts
  apps/web/src/state/swap/queries/lastPairDayId.ts
  apps/web/src/state/swap/queries/lastPairHourId.ts
  apps/web/src/state/swap/queries/pairDayDatas.ts
  apps/web/src/state/swap/queries/pairDayDatasByIdsQuery.ts
  apps/web/src/state/swap/queries/pairHourDatas.ts
  apps/web/src/state/swap/queries/pairHourDatasByIds.ts
  apps/web/src/state/swap/reducer.test.ts
  apps/web/src/state/swap/reducer.test.tsx
  apps/web/src/state/swap/reducer.ts
  apps/web/src/state/swap/selectors.ts
  apps/web/src/state/swap/useSwapActionHandlers.ts
  apps/web/src/testUtils.tsx
Labels: size/XXL

#6860 fix: Optional position contract
  apps/web/src/hooks/v3/useV3Positions.ts
Labels: size/S

#6861 chore(liquid-staking): Update APR text
  apps/web/src/views/LiquidStaking/components/LiquidStakingApr.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#6859 feat: Allow to display apr with new farms
  apps/web/src/views/Farms/FarmsV3.tsx
Labels: size/S

#6848 fix: ens name as Recipient
  apps/web/src/state/swap/hooks.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSwapCallArguments.ts
  apps/web/src/views/Swap/components/AddressInputPanel.tsx
Labels: size/M

#6862 chore(liquid-staking): Update APR tooltip
  apps/web/src/views/LiquidStaking/components/LiquidStakingApr.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#6851 chore: Farms token sorting
  apps/web/src/utils/wrappedCurrency.ts
  apps/web/src/views/AddLiquidityV3/Modal.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3ApyButton.tsx
  packages/farms/constants/1.ts
  packages/farms/constants/5.ts
  packages/farms/constants/56.ts
  packages/farms/constants/97.ts
  packages/farms/constants/v3/index.ts
  packages/farms/package.json
  packages/farms/src/defineFarmV3Configs.ts
  packages/farms/src/fetchFarmsV3.ts
  packages/farms/src/index.ts
  packages/farms/src/types.ts
  packages/farms/tests/v3.test.ts
  packages/utils/unwrappedToken.ts
Labels: size/XL

#6864 fix(farm-v3): Update staked pool compare
  apps/web/src/state/farmsV3/hooks.ts
  packages/farms/src/types.ts
Labels: size/S

#6855 chore(TabMenu): Padding bottom adjustment
  packages/ui-wallets/src/WalletModal.tsx
  packages/uikit/src/components/TabMenu/TabMenu.tsx
  packages/uikit/src/components/TabMenu/types.ts
Labels: size/S

#6657 chore: Remove unused contracts / constants / helpers
  apps/web/src/components/ClaimNftModal/ClaimNftModal.tsx
  apps/web/src/config/abi/bunnySpecial.json
  apps/web/src/config/abi/bunnySpecialCakeVault.json
  apps/web/src/config/abi/bunnySpecialLottery.json
  apps/web/src/config/abi/bunnySpecialPrediction.json
  apps/web/src/config/abi/bunnySpecialXmas.json
  apps/web/src/config/abi/claimRefund.json
  apps/web/src/config/abi/easterNft.json
  apps/web/src/config/abi/syrup.json
  apps/web/src/config/constants/index.ts
  apps/web/src/config/constants/nftsCollections/types.ts
  apps/web/src/config/constants/rpc.ts
  apps/web/src/config/constants/supportChains.ts
  apps/web/src/config/constants/types.ts
  apps/web/src/config/constants/warningTokens.ts
  apps/web/src/hooks/useContract.ts
  apps/web/src/hooks/useNftClaimStatusCheck.tsx
  apps/web/src/utils/addressHelpers.ts
  apps/web/src/utils/contractHelpers.ts
Labels: size/XXL

#6869 chore: Update perpetual url
  apps/web/src/utils/getPerpetualUrl.ts
Labels: size/XS

#6837 chore(RangeTag): Tooltip placement adjustment
  apps/web/src/components/RangeTag.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3StakeAndUnStake.tsx
Labels: size/XS

#6871 fix(farms): crash on wrong network
  apps/web/src/hooks/v3/useV3Positions.ts
Labels: size/XS

#6868 fix(farms): position sorting
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3StakeAndUnStake.tsx
Labels: size/M

#6879 fix: Migrate text incorrectly displayed
  apps/web/src/views/AddLiquidityV3/Migrate.tsx
Labels: size/S

#6877 chore: list blur&ens farm
  packages/farms/constants/1.ts
  packages/tokens/src/1.ts
Labels: size/M

#6874 chore: Add security related http headers
  apps/aptos/next.config.mjs
  apps/aptos/package.json
  apps/blog/next.config.mjs
  apps/blog/package.json
  apps/bridge/next.config.mjs
  apps/bridge/package.json
  apps/web/next.config.mjs
  apps/web/package.json
  packages/next-config/package.json
  packages/next-config/tsconfig.json
  packages/next-config/withWebSecurityHeaders.ts
  pnpm-lock.yaml
Labels: size/L

#6883 chore: set volume as default sorting
  apps/web/src/views/V3Info/components/TokenTable/index.tsx
Labels: size/XS

#6885 feat: Add apr breakdown on each position
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3ApyButton.tsx
Labels: size/S

#6886 chore: Move to finished pools
  packages/pools/src/constants/pools/56.ts
Labels: size/M

#6870 style: Radio and checkbox add border at dark mode
  packages/uikit/src/__tests__/components/checkbox.test.tsx
  packages/uikit/src/__tests__/components/radio.test.tsx
  packages/uikit/src/components/Checkbox/Checkbox.tsx
  packages/uikit/src/components/Radio/Radio.tsx
Labels: size/S, automerge

#6890 fix: Remove cache on block on update reminder
  apps/web/src/views/Farms/components/UpdatePositionsReminder.tsx
Labels: size/XS

#6891 chore: list v3 id farm
  packages/farms/constants/56.ts
Labels: size/XS

#6896 fix: Pottery missing image
  apps/web/public/images/pot-icon.svg
  apps/web/src/views/Pottery/components/Pot/index.tsx
Labels: size/XS, automerge

#6771 feat: Add CAKE locked tooltip
  apps/web/src/state/types.ts
  apps/web/src/views/Pools/components/AutoEarningsBreakdown.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/index.tsx
  apps/web/src/views/Pools/components/LockedPool/LockedStakingApy.tsx
  apps/web/src/views/Pools/components/OriginalLockedInfo.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/AutoHarvest.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
  apps/web/src/views/Pools/components/PoolsTable/Cells/AutoEarningsCell.tsx
  apps/web/src/views/Pools/components/PoolsTable/Cells/StakedCell.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#6901 chore: Add iframe whitelist
  packages/next-config/withWebSecurityHeaders.ts
Labels: size/S

#6902 chore: Remove csp
  packages/next-config/withWebSecurityHeaders.ts
Labels: size/S

#6903 chore: Whitelist trading pairs
  packages/smart-router/evm/constants/exchange.ts
Labels: size/S

#6904 fix: Remove duplicated pools
  packages/pools/src/constants/pools/56.ts
Labels: size/M

#6875 chore: v3 info UI improvement
  apps/web/src/views/V3Info/components/BarChart/alt.tsx
  apps/web/src/views/V3Info/components/LineChart/index.tsx
  apps/web/src/views/V3Info/components/PoolTable/index.tsx
  apps/web/src/views/V3Info/components/TokenTable/index.tsx
  apps/web/src/views/V3Info/components/TransactionsTable/index.tsx
Labels: size/M

#6876 chore: ensName as recipient improvement
  apps/web/src/hooks/useGetENSAddressByName.ts
  apps/web/src/state/swap/hooks.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSwapCallArguments.ts
  apps/web/src/views/Swap/components/AddressInputPanel.tsx
Labels: size/M

#6872 feat: Axelar bridge
  apps/bridge/components/Menu.tsx
  apps/bridge/components/Page.tsx
  apps/bridge/next.config.mjs
  apps/bridge/package.json
  apps/bridge/pages/index.tsx
  apps/bridge/pages/stargate.tsx
  pnpm-lock.yaml
Labels: size/XXL

#6909 fix: Missing currency logo display
  apps/web/src/views/Swap/V3Swap/components/RouteDisplayModal.tsx
  packages/uikit/src/components/CurrencyLogo/CurrencyLogo.tsx
  packages/uikit/src/components/CurrencyLogo/utils.ts
Labels: size/M

#6910 chore: list USH farm on BSC
  packages/farms/constants/56.ts
Labels: size/XS

#6906 chore: add warning text for v2 info
  apps/web/src/views/Info/components/InfoNav/index.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#6916 chore: list FUSE farm on ETH
  packages/farms/constants/1.ts
Labels: size/XS

#6917 chore: Remove frame csp due to third party usage
  packages/next-config/withWebSecurityHeaders.ts
Labels: size/S

#6913 chore: Move to finished pools
  packages/pools/src/constants/pools/56.ts
Labels: size/M

#6921 chore: Remove home page AffiliateModal
  apps/web/src/views/Home/index.tsx
Labels: size/XS, automerge

#6922 chore: list C98 farm on BSC
  packages/farms/constants/56.ts
Labels: size/XS

#6923 fix: ROI calculator chart issue on ETH
  apps/web/src/views/V3Info/hooks/index.ts
Labels: size/XS

#6924 feat: Update info page warning text
  apps/web/src/views/Info/components/InfoNav/index.tsx
  packages/localization/src/config/translations.json
Labels: size/S, automerge

#6928 feat: Add subgraph health indicators
  apps/web/src/components/SubgraphHealthIndicator/FloatingSubgraphHealthIndicators.tsx
  apps/web/src/components/SubgraphHealthIndicator/SubgraphHealthIndicator.tsx
  apps/web/src/components/SubgraphHealthIndicator/index.tsx
  apps/web/src/hooks/useSubgraphHealth.ts
  apps/web/src/pages/add/[[...currency]].tsx
  apps/web/src/pages/liquidity/index.tsx
  apps/web/src/pages/swap.tsx
  apps/web/src/views/Farms/FarmsV3.tsx
  apps/web/src/views/Lottery/index.tsx
  apps/web/src/views/Pools/index.tsx
  apps/web/src/views/Predictions/index.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#6930 feat(Affiliate): Add subgraph health indicators
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/DesktopView.tsx
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/MobileView.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/index.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useShowWarningMessage.tsx
  packages/localization/src/config/translations.json
Labels: size/M, automerge

#6931 fix: Unexpected cursor jump when typing in swap fields
  apps/web/src/state/swap/useSwapActionHandlers.ts
Labels: size/XS

#6929 feat: Add Trading reward nav status
  apps/web/src/components/Menu/hooks/useMenuItemsStatus.ts
  apps/web/src/components/Menu/hooks/useTradingRewardStatus.ts
Labels: size/S, automerge

#6935 chore: update pancake protector banner link
  apps/web/src/views/Home/components/Banners/PancakeProtectorBanner.tsx
Labels: size/XS

#6932 feat: Rename noperps to perps
  apps/web/src/views/AffiliatesProgram/components/Dashboard/AffiliateLinks.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/AffiliateModal/index.tsx
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/WelcomePage.tsx
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/index.tsx
Labels: size/S, automerge

#6936 refactor: Use intl numberformat instead of numbro to reduce bundle size
  apps/web/package.json
  apps/web/src/views/V3Info/utils/numbers.ts
  packages/utils/formatInfoNumbers.ts
  packages/utils/package.json
  pnpm-lock.yaml
Labels: size/M

#6950 fix: Farmv3 tvl timeout
  apps/web/src/state/farmsV3/hooks.ts
Labels: size/XS

#6952 fix: v3 info search limit issue
  apps/web/src/views/V3Info/constants.ts
  apps/web/src/views/V3Info/data/search/index.ts
Labels: size/S

#6954 perf: Minor improve for unstable network
  apps/web/src/config/nodes.ts
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/hooks/useV3Pools.ts
  apps/web/src/utils/nodeReal.ts
  apps/web/src/utils/viem.ts
  apps/web/src/utils/wagmi.ts
  apps/web/src/views/Farms/components/UpdatePositionsReminder.tsx
Labels: size/M

#6948 style(Swap): Align checkbox
  apps/web/src/views/Swap/components/HotTokenList/index.tsx
Labels: size/XS

#6938 chore: add menu item for pancakeProtector
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/components/Menu/hooks/useMenuItems.ts
  packages/localization/src/config/translations.json
Labels: size/S

#6953 fix(Trading Reward): Bug
  apps/web/src/views/TradingReward/components/YourTradingReward/NoCakeLockedOrExtendLock.tsx
  apps/web/src/views/TradingReward/components/YourTradingReward/QualifiedPreview.tsx
Labels: size/S, automerge

#6962 chore: Update batch size
  apps/web/src/utils/viem.server.ts
  apps/web/src/utils/viem.ts
Labels: size/S

#6963 chore: Update risk warning of import token
  apps/web/src/components/SearchModal/ImportToken.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#6961 fix(aptos-Farms): Fix multiplier tooltip
  apps/aptos/components/Farms/components/FarmCard/FarmCard.tsx
  apps/aptos/components/Farms/components/FarmTable/FarmTable.tsx
  apps/aptos/components/Farms/components/getDisplayFarmCakePerSecond.ts
  packages/farms/src/types.ts
Labels: size/S

#6959 fix: Ens avatar hook gives error on bsc network
  apps/web/src/hooks/useDomain.ts
Labels: size/XS

#6939 chore: Remove unused ethers experimental package
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/S

#6934 fix: Missing await rule sonar
  apps/aptos/components/SearchModal/ManageLists.tsx
  apps/web/src/components/SearchModal/ManageLists.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/index.tsx
  apps/web/src/views/Ifos/components/IfoVesting/VestingPeriod/Info.tsx
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/index.tsx
  packages/smart-router/evm/v3-router/providers/offChainQuoteProvider.ts
  packages/ui-wallets/src/WalletModal.tsx
Labels: size/M

#6968 fix: ROI calculator min max price issue
  apps/web/src/views/V3Info/data/token/priceData.ts
Labels: size/XS

#6972 fix: Liquidity page crash
  apps/web/src/hooks/useFarm.ts
  packages/farms/constants/common/index.ts
  packages/farms/src/fetchFarmsV3.ts
  packages/farms/src/index.ts
  packages/utils/formatFractions.ts
  packages/v3-sdk/src/entities/tick.ts
  packages/v3-sdk/src/utils/feeCalculator.ts
  packages/v3-sdk/src/utils/positionMath.ts
Labels: size/M

#6973 chore: Farm typing issue
  packages/farms/src/fetchFarmsV3.ts
Labels: size/XS

#6974 chore: Add RPC logger
  apps/web/src/quote-worker.ts
Labels: size/S

#6976 fix: logger log itself
  apps/web/src/quote-worker.ts
Labels: size/S

#6978 fix: Apr mismatch on liquidity page and farm
  apps/web/src/components/Chart/FormattedCurrencyAmount/FormattedCurrencyAmount.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3ApyButton.tsx
Labels: size/M

#6979 fix: Subgraph health indicator crash
  apps/web/src/hooks/useSubgraphHealth.ts
Labels: size/XS

#6977 fix: ROI calculator min max price issue
  apps/web/src/views/V3Info/data/token/priceData.ts
Labels: size/M

#6983 chore: list bsc farm
  packages/farms/constants/56.ts
Labels: size/S

#6982 fix(migration): filter farm sorting issue
  apps/web/src/views/Migration/components/v3/Step2.tsx
Labels: size/XS

#6988 fix: user gas undefined
  apps/web/src/state/user/hooks/index.tsx
Labels: size/XS

#6990 fix: Prevent crash on unsupported network
  apps/web/src/state/swap/hooks.test.ts
  apps/web/src/state/swap/hooks.ts
  apps/web/src/utils/contractHelpers.ts
Labels: size/S

#6969 fix: Scam v3 Lp
  apps/web/src/pages/liquidity/index.tsx
Labels: size/M

#6991 refactor: Pool providers code reuse
  packages/smart-router/evm/v3-router/constants/poolSelector.ts
  packages/smart-router/evm/v3-router/providers/index.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/hybridPoolProvider.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/index.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/internalTypes.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/onChainPoolProviders.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/poolProviderWithCache.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/poolTvlSelectors.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/staticPoolProvider.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/subgraphPoolProviders.ts
  packages/smart-router/evm/v3-router/providers/subgraphProvider.ts
  packages/smart-router/evm/v3-router/providers/v2SubgraphProvider.ts
  packages/smart-router/evm/v3-router/smartRouter.ts
  packages/smart-router/evm/v3-router/types/pool.ts
  packages/smart-router/evm/v3-router/types/poolSelector.ts
  packages/smart-router/evm/v3-router/utils/getPoolSelectorConfig.ts
  packages/smart-router/evm/v3-router/utils/pool.ts
Labels: size/XXL

#6995 fix: Eth farm loading after connected wallet
  apps/web/src/state/farms/fetchFarmUser.ts
Labels: size/XS

#6994 fix: safe app tx value undefined
  apps/web/sentry.client.config.js
  apps/web/src/hooks/useCallWithGasPrice.ts
  apps/web/src/utils/calls/estimateGas.ts
  apps/web/src/utils/sentry.ts
  apps/web/src/views/Farms/hooks/v3/useFarmV3Actions.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useSendSwapTransaction.ts
Labels: size/S

#6996 fix: callWithEstimateGas params
  apps/web/src/utils/calls/estimateGas.ts
Labels: size/XS

#6998 fix: callWithEstimateGas missing account
  apps/web/src/utils/calls/estimateGas.ts
Labels: size/XS

#6937 chore: Remove unused cids library
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/M

#6987 chore: Bump up jotai
  apps/aptos/package.json
  apps/web/package.json
  packages/token-lists/package.json
  packages/ui-wallets/package.json
  packages/utils/package.json
  pnpm-lock.yaml
Labels: size/M

#6907 perf: Throttle handle refresh in swap to reduce amount of requests
  apps/web/src/views/AddLiquidity/AddStableLiquidity/hooks/useStableLPDerivedMintInfo.tsx
  apps/web/src/views/Swap/V3Swap/index.tsx
  apps/web/src/views/Swap/hooks/useEstimatedAmount.ts
  apps/web/src/views/Swap/index.tsx
Labels: size/S

#7000 chore: try fix build
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/XS

#6999 chore: update pancake Protector Banner
  apps/web/src/views/Home/components/Banners/PancakeProtectorBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#6997 chore: Unify public client types
  apps/web/src/hooks/usePublicNodeWaitForTransaction.ts
  packages/smart-router/legacy-router/types/bestTrade.ts
Labels: size/XS

#6797 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XXL

#6993 feat: try fallback nodes
  apps/web/src/config/nodes.ts
  apps/web/src/utils/viem.ts
  apps/web/src/utils/wagmi.ts
Labels: size/M

#7004 chore: Bump turbo
  package.json
  pnpm-lock.yaml
Labels: size/M

#7007 revert: "feat: try fallback nodes"
  apps/web/src/config/nodes.ts
  apps/web/src/utils/viem.ts
  apps/web/src/utils/wagmi.ts
Labels: size/M

#7009 chore: list rETH-BTC farm on ETH
  packages/farms/constants/1.ts
Labels: size/XS

#7011 chore: list rpl pool on ETH
  packages/pools/src/constants/pools/1.ts
Labels: size/XS

#7014 fix: reth farm issue
  packages/farms/constants/1.ts
Labels: size/XS

#7012 chore: Sort ETH farm list
  packages/farms/constants/1.ts
Labels: size/S, automerge

#7013 feat(Bridge): Upgrade widget version
  apps/bridge/package.json
  pnpm-lock.yaml
Labels: size/L, automerge

#7018 fix: allow failure on lm pool fetching
  packages/farms/src/fetchFarmsV3.ts
  packages/farms/tests/v3.test.ts
Labels: size/S

#7019 fix: Pool config test not triggered
  .github/workflows/testConfig.yml
  .github/workflows/testConfigPass.yml
  packages/pools/src/constants/pools/1.ts
Labels: size/XS

#7006 refactor: Pool providers with fallback
  apps/web/src/config/pools.ts
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/hooks/useCommonPools.ts
  apps/web/src/hooks/useV2Pools.ts
  apps/web/src/hooks/useV3Pools.ts
  packages/smart-router/evm/utils/withFallback.ts
  packages/smart-router/evm/v3-router/functions/getPairCombinations.ts
  packages/smart-router/evm/v3-router/gasModel.ts
  packages/smart-router/evm/v3-router/getBestTrade.ts
  packages/smart-router/evm/v3-router/providers/getCommonTokenPrices.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/getCandidatePools.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/getStableCandidatePools.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/getV2CandidatePools.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/getV3CandidatePools.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/hybridPoolProvider.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/index.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/onChainPoolProviders.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/poolTvlSelectors.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/staticPoolProvider.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/subgraphPoolProviders.ts
  packages/smart-router/evm/v3-router/smartRouter.ts
  packages/smart-router/evm/v3-router/types/providers.ts
Labels: size/XL

#7020 feat: Update new version
  apps/bridge/package.json
  apps/bridge/pages/index.tsx
  pnpm-lock.yaml
Labels: size/S, automerge

#7026 fix: Sid name
  apps/web/src/hooks/useSid.ts
Labels: size/XS
