Repository pancakeswap/pancake-frontend, pull requests merged in 2023-04, with the labels that each got.

#6447 fix: Rename info path
  apps/web/src/pages/info/v3/[chainName]/pools/[address].tsx
  apps/web/src/pages/info/v3/[chainName]/tokens/[address].tsx
  apps/web/src/pages/info/v3/pairs/[address].tsx
  apps/web/src/pages/info/v3/pairs/index.tsx
  apps/web/src/pages/info/v3/tokens/[address].tsx
Labels: size/XS

#6446 fix: cross chain loading
  apps/web/src/views/Migration/components/MigrationFarmTable.tsx
  apps/web/src/views/Migration/components/v3/OldFarmRow.tsx
  apps/web/src/views/Migration/components/v3/Step3.tsx
  apps/web/src/views/Migration/components/v3/UnstakeButton.tsx
Labels: size/L

#6449 chore: Use v2 pools on chain
  apps/web/src/hooks/useCommonPools.ts
Labels: size/XS

#6450 feat: Add migration warning on cake emission
  apps/web/src/views/Migration/components/v3/Step3.tsx
  apps/web/src/views/Migration/components/v3/Step5.tsx
Labels: size/M

#6453 feat: Eth farms 2
  apps/web/public/images/1/tokens/0x514910771AF9Ca656af840dff83E8264EcF986CA.png
  apps/web/public/images/1/tokens/0x5A98FcBEA516Cf06857215779Fd812CA3beF1B32.png
  apps/web/public/images/1/tokens/0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0.png
  apps/web/public/images/1/tokens/0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0.png
  apps/web/src/pages/info/[chainName]/pairs/[address].tsx
  apps/web/src/pages/info/[chainName]/tokens/[address].tsx
  packages/farms/constants/1.ts
  packages/tokens/src/1.ts
  packages/uikit/src/__tests__/components/tokenimage.test.tsx
  packages/uikit/src/components/Image/TokenImage.tsx
Labels: size/M

#6457 fix(farms): pool length check condition
  apps/web/src/state/farmsV3/hooks.ts
Labels: size/XS

#6460 fix: start block
  apps/web/src/views/V3Info/constants.ts
Labels: size/XS

#6459 refactor: Fix sonar bugs
  apps/aptos/views/Ifos/components/IfoVesting/VestingPeriod/Info.tsx
  apps/web/src/components/LiquidityCardRow/index.tsx
  apps/web/src/components/SearchModal/ImportToken.tsx
  apps/web/src/components/TransactionDetailModal/FarmTransactionModal/index.tsx
  apps/web/src/state/farms/index.ts
  apps/web/src/state/lists/hooks.ts
  apps/web/src/views/Home/components/Banners/V3Banner.tsx
  apps/web/src/views/Ifos/components/IfoVesting/VestingPeriod/Info.tsx
  apps/web/src/views/Pool/index.tsx
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMOrderBookTrade.ts
  apps/web/src/views/V3Info/components/Row/index.tsx
Labels: size/M

#6452 chore: v3 launch banner
  apps/web/src/views/Home/components/Banners/V3LaunchBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  apps/web/src/views/Home/components/Banners/images/index.ts
  apps/web/src/views/Home/components/Banners/images/v3LaunchBg.png
  apps/web/src/views/Home/components/Banners/images/v3LaunchBgMobile.png
  apps/web/src/views/Home/components/Banners/images/v3LaunchBunny.png
  apps/web/src/views/Home/components/Banners/images/v3LaunchBunnyMobile.png
  packages/localization/src/config/translations.json
Labels: size/L

#6454 chore: v3 info adjustment
  apps/web/src/pages/info/v3/pools/[address].tsx
  apps/web/src/pages/info/v3/pools/index.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3Card.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/V3Info/data/pool/tickData.ts
  apps/web/src/views/V3Info/hooks/index.ts
  apps/web/src/views/V3Info/views/PoolPage.tsx
Labels: size/M

#6461 chore(Liquidity): Modify tokenLogo placement
  apps/web/src/components/Logo/DoubleLogo.tsx
Labels: size/XS

#6445 feat(Bridge): Aptos Bridge version 10
  apps/bridge/components/layerZero/config.ts
  apps/bridge/tsconfig.json
Labels: size/XS, automerge

#6448 feat: Add ETH banner
  apps/web/src/views/Home/components/Banners/EthBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  apps/web/src/views/Home/components/Banners/images/ETHBunny.png
  apps/web/src/views/Home/components/Banners/images/ethXpancakeswap.png
  apps/web/src/views/Home/components/Banners/images/index.ts
  packages/localization/src/config/translations.json
Labels: size/M, automerge

#6465 fix(farms): per sorting
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3StakeAndUnStake.tsx
  apps/web/src/views/V3Info/utils/index.ts
Labels: size/S

#6463 fix: Aptos farm
  apps/aptos/components/Farms/components/FarmTable/Farm.tsx
Labels: size/XS

#6467 chore: Temp disable e2e
  .github/workflows/integrationTests.yml
Labels: size/M

#6466 fix(lp): wbnb link and remove tx err stuck
  apps/web/src/views/AddLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/index.tsx
Labels: size/S

#6468 chore: Hide ImpermanentLossCalculator
  packages/uikit/src/widgets/RoiCalculator/RoiCalculator.tsx
Labels: size/XS

#6469 fix(farms): avoid isloading retrigger skeleton
  apps/web/src/state/farmsV3/hooks.ts
Labels: size/XS

#6443 feat: List Pools
  apps/web/src/config/constants/pools.tsx
Labels: size/M, automerge

#6475 chore: Temp remove e2e action
  .github/workflows/integrationTests.yml
Labels: size/M

#6471 fix: Aptos build
  apps/aptos/components/Liquidity/components/PricePoolShareSection.tsx
  apps/aptos/components/Swap/SwapModalHeader.tsx
  apps/aptos/state/user/index.ts
  apps/aptos/views/Ifos/hooks/v3/useGetPublicIfoData.ts
  packages/farms/farmPrices.ts
  packages/uikit/src/components/LiquidityChartRangeInput/Area.tsx
  packages/utils/formatFractions.ts
  packages/utils/formatInfoNumbers.ts
  packages/utils/isPositionOutOfRange.ts
  packages/v3-sdk/src/staker.ts
Labels: size/S

#6472 chore: Add missing token image
  apps/web/public/images/1/tokens/0x4d224452801ACEd8B2F0aebE155379bb5D594381.png
Labels: size/XS

#6441 feat: Add Terms of service
  apps/web/src/pages/terms-of-service.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/widgets/Menu/components/footerConfig.ts
Labels: size/L, automerge

#6476 fix: Eth token list overlapped
  apps/web/src/components/SearchModal/CurrencyList.tsx
Labels: size/XS, automerge

#6478 fix: Fix Spacer width
  apps/web/src/components/Modal/Spacer.tsx
  packages/uikit/src/widgets/Modal/Spacer.tsx
Labels: size/S

#6477 fix: checking ethers reject error code
  apps/web/sentry.client.config.js
  apps/web/src/hooks/useApproveCallback.ts
  apps/web/src/hooks/useSwapCallback.ts
  apps/web/src/utils/sentry.ts
  apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
  apps/web/src/views/AddLiquidity/index.tsx
  apps/web/src/views/AddLiquidityV3/IncreaseLiquidityV3.tsx
  apps/web/src/views/AddLiquidityV3/Migrate.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
  apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/index.tsx
  apps/web/src/views/Swap/MMLinkPools/hooks/useSwapCallback.ts
  apps/web/src/views/Swap/SmartSwap/hooks/useSwapCallback.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSendSwapTransaction.ts
Labels: size/M

#6473 chore: liquidity improvement
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/pages/liquidity/index.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
  apps/web/src/views/PoolFinder/index.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#6480 fix(blog): Build
  packages/farms/constants/common/index.ts
  packages/farms/src/fetchFarmsV3.ts
  packages/farms/src/v2/farmPrices.ts
  packages/farms/src/v2/fetchFarmsV2.ts
  packages/farms/src/v2/fetchPublicFarmData.ts
  packages/swap-sdk-core/src/fractions/currencyAmount.ts
  packages/swap-sdk-core/src/fractions/fraction.ts
Labels: size/M

#6483 fix(wallet): pointer event block blocto
  packages/ui-wallets/src/WalletModal.tsx
  packages/uikit/src/widgets/Modal/ModalV2.tsx
Labels: size/S

#6481 fix(TokenList): Fix tooltip click issue
  apps/web/src/components/SearchModal/ManageLists.tsx
  packages/uikit/src/hooks/useTooltip/types.ts
  packages/uikit/src/hooks/useTooltip/useTooltip.tsx
Labels: size/XS

#6196 refactor(OutlineTag): Integrate the background of OutlineTag into UIKit.
  apps/web/src/views/Farms/components/YieldBooster/components/BoostedTag.tsx
  packages/uikit/src/components/Tag/StyledTag.tsx
  packages/uikit/src/widgets/Farm/components/Tags/index.tsx
Labels: size/M

#6435 feat: Show Affiliate Landing
  apps/web/src/components/Modal/USCitizenConfirmModal.tsx
  apps/web/src/views/AffiliatesProgram/components/AffiliatesProgramLayout.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/AffiliateLinks.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/index.tsx
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/Congratulations.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/AffiliatesBanner.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/Benefits.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/index.tsx
  packages/localization/src/config/translations.json
Labels: size/L, automerge

#6490 fix: Apr mismatch on liquidity page
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
Labels: size/XS

#6491 chore: Update fee-on transfer token warning message
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
Labels: size/XS

#6495 fix(liquidity): Avoid decimal error when toFix
  apps/web/src/components/Chart/FormattedCurrencyAmount/FormattedCurrencyAmount.tsx
Labels: size/XS

#6498 feat: List 5 v3 farms
  packages/farms/constants/56.ts
Labels: size/M

#6501 fix: Update migration text
  apps/web/src/views/Migration/components/v3/Step3.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#6497 chore(Migration): Modify step4 position's tag placement
  apps/web/src/components/LiquidityCardRow/index.tsx
  apps/web/src/views/Migration/components/v3/Step4.tsx
Labels: size/XS

#6505 feat: List GQ pool
  apps/web/src/config/constants/pools.tsx
Labels: size/S, automerge

#6485 chore: migrate to new gtm
  apps/blog/pages/_app.tsx
  apps/bridge/pages/_app.tsx
  apps/web/src/pages/_app.tsx
  apps/web/src/utils/customGTMEventTracking.ts
Labels: Delayed Release, size/S

#6492 fix(Migrarion): SubTitle use safeArea
  apps/web/src/views/Migration/components/MigrationSticky.tsx
Labels: size/XS

#6507 fix(liquidity): Avoid exception when parsing v3 amount is undefined
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/FeeSelector.tsx
Labels: size/S

#6496 fix: Redundant calls to rpc providers when initializing
  apps/web/src/utils/providers.ts
Labels: size/M

#6509 feat: List Aptos Farm and BNB pool
  apps/aptos/config/constants/farms/1.ts
  apps/aptos/config/constants/tokens/1.ts
  apps/web/public/images/tokens/0xF98b660AdF2ed7d9d9D9dAACC2fb0CAce4F21835.png
  apps/web/src/config/constants/pools.tsx
  packages/tokens/src/56.ts
Labels: size/M

#6512 fix(aptos-TokenList): Fix tooltip click issue
  apps/aptos/components/SearchModal/ManageLists.tsx
Labels: size/XS, automerge

#6513 fix(Liquidity): Fix addLiquidityV2 percent issue
  apps/web/src/views/AddLiquidityV3/formViews/V2FormView.tsx
Labels: size/XS

#6511 chore: GTM customized event tracking
  apps/web/src/utils/calls/farms.ts
  apps/web/src/utils/customGTMEventTracking.ts
  apps/web/src/views/AddLiquidityV3/formViews/StableFormView.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V2FormView.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/SingleFarmV3Card.tsx
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButton.tsx
  apps/web/src/views/Swap/SmartSwap/components/SmartSwapCommitButton.tsx
  apps/web/src/views/Swap/StableSwap/components/StableSwapCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/containers/SwapCommitButton.tsx
  apps/web/src/views/Swap/components/SwapCommitButton.tsx
Labels: size/M

#6514 fix: Remove dollar symbol from apy
  packages/uikit/src/widgets/RoiCalculator/Details.tsx
  packages/uikit/src/widgets/RoiCalculator/RoiCalculator.tsx
Labels: size/S

#6517 chore: event tracking adjustment
  apps/blog/pages/_app.tsx
  apps/web/src/pages/_app.tsx
  apps/web/src/utils/customGTMEventTracking.ts
  apps/web/src/views/Swap/components/HotTokenList/SwapTokenTable.tsx
Labels: size/M

#6489 chore: v3 info adjustment
  apps/web/src/pages/info/v3/[chainName]/pairs/[address].tsx
  apps/web/src/pages/info/v3/[chainName]/pairs/index.tsx
  apps/web/src/pages/info/v3/pairs/[address].tsx
  apps/web/src/pages/info/v3/pairs/index.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3Card.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/V3Info/components/Layout/InfoNav.tsx
  apps/web/src/views/V3Info/components/PoolTable/index.tsx
  apps/web/src/views/V3Info/views/PoolPage.tsx
  apps/web/src/views/V3Info/views/TokenPage.tsx
Labels: size/M

#6521 chore: update MM signer
  apps/web/src/views/Swap/MMLinkPools/constants.ts
Labels: size/XS

#6516 chore(Liquidity): Modify claimFees symbol textColor
  apps/web/src/pages/liquidity/[tokenId].tsx
Labels: size/XS

#6508 fix(Liquidity): Fix tooltip placement
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
  packages/uikit/src/widgets/RoiCalculator/DepositAmount.tsx
Labels: size/XS

#6504 chore(Farms): UI improvement
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3ApyButton.tsx
Labels: size/M

#6503 chore(Farms): Adjust V3 APR placement
  packages/uikit/src/widgets/Farm/components/FarmApyButton/index.tsx
Labels: size/XS

#6502 chore(Liquidity): Adjust token panel placement
  apps/web/src/pages/liquidity/[tokenId].tsx
Labels: size/XS

#6494 fix: Uncontrolled input warning in swap
  apps/web/src/views/Swap/V3Swap/containers/FormMain.tsx
Labels: size/S

#6520 fix: SIS pool APR
  apps/web/src/config/constants/priceHelperLps/pools/56.ts
Labels: size/XS

#6523 chore(Farms): LP position's link not use external
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3StakeAndUnStake.tsx
Labels: size/XS

#6522 chore: check test
  apps/web/src/config/__tests__/tokens.test.ts
Labels: size/XS

#6528 fix: Missing quote when gas estimation failed
  packages/smart-router/evm/v3-router/gasModel.ts
Labels: size/S

#6530 chore: Add copilot support to pull request template
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: size/S

#6524 chore: v3 launch banner adjustment
  apps/web/src/views/Home/components/Banners/V3LaunchBanner.tsx
  apps/web/src/views/Home/components/Banners/images/index.ts
  apps/web/src/views/Home/components/Banners/images/v3LaunchBg.png
  apps/web/src/views/Home/components/Banners/images/v3LaunchBnb.png
  apps/web/src/views/Home/components/Banners/images/v3LaunchEth.png
  apps/web/src/views/Home/components/Banners/images/v3LaunchFlag.png
Labels: size/M

#6531 fix(liquidity): Sync APY with Farm
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
Labels: size/XS

#6329 chore: Bump up swr
  apps/web/package.json
  packages/wagmi/package.json
  yarn.lock
Labels: size/S

#6527 chore(Farms): Adjust APR placement
  packages/uikit/src/widgets/Farm/components/FarmApyButton/index.tsx
Labels: size/XS

#6493 fix(Migration): Fix expand logic
  apps/web/src/views/Migration/components/MigrationStep1/OldFarm/FarmRow.tsx
  apps/web/src/views/Migration/components/MigrationStep2/NewFarm/FarmRow.tsx
  apps/web/src/views/Migration/components/v3/OldFarmRow.tsx
Labels: size/S

#6484 fix(HomePage): Fix harvest collect desc
  apps/web/src/views/Home/components/UserBanner/HarvestCard.tsx
Labels: size/XS

#6482 chore(Liquidity): V3 history's timestamp improvement
  apps/web/src/pages/liquidity/[tokenId].tsx
Labels: size/S

#6529 perf: Disable price auto update when getting token usd price from amm
  apps/web/src/hooks/useBUSDPrice.ts
  apps/web/src/hooks/useBestAMMTrade.ts
Labels: size/S

#6431 chore(Pools): Modifty filters placement
  packages/uikit/src/widgets/Pool/PoolTabButtons.tsx
Labels: size/XS

#6388 chore: Use pcs rpc for cake lock status
  apps/web/src/hooks/useUserCakeLockStatus.ts
Labels: size/XS

#6387 chore(Profile): Modify ChangeProfilePicFlow margin
  apps/web/src/views/Profile/components/EditProfileModal/StartView.tsx
Labels: size/XS

#6382 feat(aptos-Pools): Add Ends in cell
  apps/aptos/components/Pools/components/PoolCard/PoolStatsInfo.tsx
  apps/aptos/components/Pools/components/PoolTable/PoolRow.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/widgets/Pool/Cells/EndsInCell.tsx
  packages/uikit/src/widgets/Pool/index.tsx
Labels: size/M

#6377 chore(UserMenu): SID should not omit text
  apps/web/src/components/Menu/UserMenu/index.tsx
  packages/uikit/src/widgets/Menu/components/UserMenu/index.tsx
  packages/uikit/src/widgets/Menu/components/UserMenu/types.ts
Labels: size/S

#6336 perf: Memoize latinise func
  packages/utils/latinise.ts
Labels: size/XS

#6169 refactor: Remove duplicate import token row
  apps/aptos/components/SearchModal/ImportRow.tsx
  apps/aptos/components/SearchModal/ImportTokenRow.tsx
  apps/aptos/components/SearchModal/TokenRowWithCurrencyLogo.tsx
  apps/web/src/components/SearchModal/ImportRow.tsx
  apps/web/src/components/SearchModal/ImportTokenRow.tsx
  apps/web/src/components/SearchModal/TokenRowWithCurrencyLogo.tsx
  packages/uikit/src/widgets/Swap/TokenRowButton.tsx
  packages/uikit/src/widgets/Swap/index.ts
  packages/uikit/src/widgets/Swap/withCurrencyLogo.tsx
Labels: size/L

#6533 chore: Reduce img size
  apps/web/next.config.mjs
  apps/web/public/images/home/lunar-bunny/astronaut-bunny.png
Labels: size/M

#6519 chore: v3 info adjustment part3
  apps/web/src/views/V3Info/components/BarChart/alt.tsx
  apps/web/src/views/V3Info/components/Layout/index.tsx
  apps/web/src/views/V3Info/components/Search/index.tsx
  apps/web/src/views/V3Info/components/TransactionsTable/index.tsx
  apps/web/src/views/V3Info/components/shared.tsx
  apps/web/src/views/V3Info/data/pool/tickData.ts
  apps/web/src/views/V3Info/data/protocol/overview.ts
  apps/web/src/views/V3Info/data/search/index.ts
  apps/web/src/views/V3Info/data/token/tokenData.ts
  apps/web/src/views/V3Info/hooks/index.ts
  apps/web/src/views/V3Info/index.tsx
  apps/web/src/views/V3Info/views/PoolPage.tsx
Labels: size/L

#6056 chore: New Crowdin updates
  apps/web/public/locales/ar-SA.json
  apps/web/public/locales/bn-BD.json
  apps/web/public/locales/de-DE.json
  apps/web/public/locales/el-GR.json
  apps/web/public/locales/en-US.json
  apps/web/public/locales/es-ES.json
  apps/web/public/locales/fi-FI.json
  apps/web/public/locales/fil-PH.json
  apps/web/public/locales/fr-FR.json
  apps/web/public/locales/hi-IN.json
  apps/web/public/locales/hu-HU.json
  apps/web/public/locales/id-ID.json
  apps/web/public/locales/it-IT.json
  apps/web/public/locales/ja-JP.json
  apps/web/public/locales/ko-KR.json
  apps/web/public/locales/nl-NL.json
  apps/web/public/locales/pl-PL.json
  apps/web/public/locales/pt-BR.json
  apps/web/public/locales/pt-PT.json
  apps/web/public/locales/ro-RO.json
  apps/web/public/locales/ru-RU.json
  apps/web/public/locales/sv-SE.json
  apps/web/public/locales/ta-IN.json
  apps/web/public/locales/tr-TR.json
  apps/web/public/locales/uk-UA.json
  apps/web/public/locales/vi-VN.json
  apps/web/public/locales/zh-CN.json
  apps/web/public/locales/zh-TW.json
Labels: size/XXL

#6534 chore(Liquidity): Use translation
  apps/web/src/components/LiquidityChartRangeInput/index.tsx
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/views/AddLiquidityV3/IncreaseLiquidityV3.tsx
  apps/web/src/views/AddLiquidityV3/Migrate.tsx
  apps/web/src/views/AddLiquidityV3/components/StableV3Selector.tsx
  apps/web/src/views/AddLiquidityV3/components/V2Selector.tsx
  apps/web/src/views/AddLiquidityV3/formViews/StableFormView.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V2FormView.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/FeeSelector.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/PositionPreview.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/RangeSelector.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
  apps/web/src/views/AddLiquidityV3/index.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3Card.tsx
  apps/web/src/views/Migration/components/v3/Step3.tsx
  apps/web/src/views/V3Info/components/DensityChart/CurrentPriceLabel.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/components/LiquidityChartRangeInput/index.tsx
  packages/uikit/src/widgets/RoiCalculator/RangeSelector.tsx
Labels: size/L

#6537 fix: homepage horizontal overflow issue
  apps/web/src/views/Home/components/Banners/V3LaunchBanner.tsx
Labels: size/XS

#6535 feat: Update position reminder
  apps/web/src/index.tsx
  apps/web/src/views/Farms/FarmsV3.tsx
  apps/web/src/views/Farms/components/UpdatePositionsReminder.tsx
  apps/web/src/views/Migration/components/v3/Step5.tsx
  packages/farms/src/fetchFarmsV3.ts
  packages/v3-sdk/src/masterchefV3.ts
Labels: size/L

#6540 revert: Revert "chore(UserMenu): SID should not omit text"
  apps/web/src/components/Menu/UserMenu/index.tsx
  packages/uikit/src/widgets/Menu/components/UserMenu/index.tsx
  packages/uikit/src/widgets/Menu/components/UserMenu/types.ts
Labels: size/S

#6544 fix: V3 info UI details
  apps/web/src/views/Info/components/CurrencyLogo/index.tsx
  apps/web/src/views/Info/components/InfoTables/shared.tsx
  apps/web/src/views/V3Info/components/PoolTable/index.tsx
  apps/web/src/views/V3Info/components/SortButton/index.ts
  apps/web/src/views/V3Info/components/TokenTable/index.tsx
  apps/web/src/views/V3Info/components/TransactionsTable/index.tsx
  apps/web/src/views/V3Info/index.tsx
  apps/web/src/views/V3Info/utils/numbers.ts
  apps/web/src/views/V3Info/views/TokenPage.tsx
Labels: size/L

#6547 perf: Prevent ui lag when chaning input on swap page
  apps/web/src/state/swap/hooks.ts
Labels: size/S

#6554 feat: Routing api
  .github/workflows/deploy-apis.yml
  apis/routing/.dev.vars
  apis/routing/.eslintrc
  apis/routing/package.json
  apis/routing/src/bindings.d.ts
  apis/routing/src/index.ts
  apis/routing/src/provider.ts
  apis/routing/tsconfig.json
  apis/routing/wrangler.toml
  apps/web/.env
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/hooks/usePoolsOnChain.ts
  apps/web/src/pages/api/routing/index.ts
  apps/web/src/state/swap/hooks.ts
  apps/web/src/utils/nodeReal.ts
  apps/web/src/utils/viem.ts
  apps/web/src/utils/wagmi.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSwapBestTrade.ts
  apps/web/tsconfig.json
  apps/web/vitest.setup.js
  packages/smart-router/evm/abis/InterfaceMulticall.ts
  packages/smart-router/evm/v3-router/providers/multicallProvider.ts
  packages/smart-router/evm/v3-router/providers/multicallSwapProvider.ts
  packages/smart-router/evm/v3-router/providers/onChainPoolProviderFactory.ts
  packages/smart-router/evm/v3-router/providers/onChainQuoteProvider.ts
  packages/smart-router/evm/v3-router/smartRouter.ts
  packages/smart-router/evm/v3-router/types/providers.ts
  packages/smart-router/evm/v3-router/utils/index.ts
  packages/smart-router/evm/v3-router/utils/metric.ts
  packages/smart-router/evm/v3-router/utils/swapRouter.test.ts
  packages/smart-router/evm/v3-router/utils/transformer.ts
  packages/smart-router/package.json
  packages/smart-router/tsconfig.json
  packages/smart-router/tsup.config.ts
  packages/wagmi/src/useWeb3React.ts
  packages/worker-utils/index.ts
  yarn.lock
Labels: size/XXL

#6548 perf: Prevent recalculating v3 pool addresses every time
  apps/web/src/hooks/useV3Pools.ts
  packages/smart-router/evm/v3-router/providers/subgraphProvider.ts
Labels: size/M

#6555 fix: Deploy action
  .github/workflows/deploy-apis.yml
Labels: size/S

#6556 fix: Deploy action install pkg
  .github/workflows/deploy-apis.yml
Labels: size/XS

#6557 ci: Build pkg [skip-ci]
  .github/workflows/deploy-apis.yml
Labels: size/XS

#6560 chore: info v3 details
  apps/web/src/views/Info/components/InfoTables/shared.tsx
  apps/web/src/views/V3Info/components/CandleChart/index.tsx
  apps/web/src/views/V3Info/components/DensityChart/CustomToolTip.tsx
  apps/web/src/views/V3Info/components/PoolTable/index.tsx
  apps/web/src/views/V3Info/components/TokenTable/index.tsx
  apps/web/src/views/V3Info/views/TokenPage.tsx
Labels: size/M

#6546 chore(V3Info): Use translation
  apps/web/src/views/V3Info/components/DensityChart/CustomToolTip.tsx
  apps/web/src/views/V3Info/components/TokenTable/index.tsx
  apps/web/src/views/V3Info/components/TransactionsTable/index.tsx
  apps/web/src/views/V3Info/index.tsx
  apps/web/src/views/V3Info/views/PoolPage.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#6536 chore: Handle get rpc revert error
  apps/web/src/state/multicall/updater.tsx
Labels: size/XS

#6561 chore: Update error text
  apps/web/src/state/multicall/updater.tsx
Labels: size/XS

#6563 feat: list XCAD syrup pool
  apps/web/src/config/constants/pools.tsx
Labels: size/S

#6565 fix: Page crash when filtering v2 candidate pools
  apps/web/src/hooks/useV2Pools.ts
Labels: size/XS

#6566 chore: Add log
  apis/routing/.dev.vars
  apis/routing/src/bindings.d.ts
  apis/routing/src/index.ts
  apis/routing/src/log.ts
  apis/routing/wrangler.toml
Labels: size/M

#6567 chore: Bump smart router
  .changeset/yellow-fans-boil.md
Labels: size/XS

#6569 chore: Update smart router version
  .changeset/yellow-fans-boil.md
Labels: size/XS

#6570 fix: add price helper for XCAD syrup pool
  apps/web/src/config/constants/priceHelperLps/pools/56.ts
Labels: size/XS

#6571 chore: Get quotes from quoter directly
  apps/web/src/hooks/useBestAMMTrade.ts
Labels: size/S

#6572 chore: update v3 pools every 5 blocks
  apps/web/src/hooks/useV3Pools.ts
Labels: size/XS

#6573 fix: apr calculator crash
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
Labels: size/XS

#6564 chore: v3 info improvements
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/views/Info/index.tsx
  apps/web/src/views/V3Info/components/BarChart/alt.tsx
  apps/web/src/views/V3Info/components/DensityChart/index.tsx
  apps/web/src/views/V3Info/components/Layout/index.tsx
  apps/web/src/views/V3Info/components/Search/index.tsx
  apps/web/src/views/V3Info/components/TransactionsTable/index.tsx
  apps/web/src/views/V3Info/data/pool/transactions.ts
  apps/web/src/views/V3Info/data/token/transactions.ts
  apps/web/src/views/V3Info/hooks/index.ts
  apps/web/src/views/V3Info/index.tsx
  apps/web/src/views/V3Info/utils/numbers.ts
  apps/web/src/views/V3Info/views/PoolPage.tsx
  apps/web/src/views/V3Info/views/TokenPage.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#6579 chore: v3 UI details improvement part2
  apps/web/src/views/V3Info/components/BarChart/alt.tsx
  apps/web/src/views/V3Info/components/CandleChart/index.tsx
  apps/web/src/views/V3Info/components/DensityChart/index.tsx
  apps/web/src/views/V3Info/components/LineChart/alt.tsx
  apps/web/src/views/V3Info/components/LineChart/index.tsx
  apps/web/src/views/V3Info/components/PoolTable/index.tsx
  apps/web/src/views/V3Info/components/TokenTable/index.tsx
  apps/web/src/views/V3Info/components/TopTokenMovers/index.tsx
  apps/web/src/views/V3Info/index.tsx
  apps/web/src/views/V3Info/views/PoolPage.tsx
  apps/web/src/views/V3Info/views/TokenPage.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#6578 fix: Tabs not visible in wallet modal and don't load swiper for each page
  packages/ui-wallets/src/WalletModal.tsx
  packages/uikit/src/__tests__/widgets/modal.test.tsx
  packages/uikit/src/widgets/Modal/Modal.tsx
Labels: size/M

#6581 fix(Liquidity): Fix rangeTag issue on remove liquidity
  apps/web/src/hooks/v3/useDerivedV3BurnInfo.ts
Labels: size/XS

#6582 chore: Bump up framer motion and use domAnimation to reduce bundle size
  packages/uikit/package.json
  packages/uikit/src/widgets/Modal/ModalContext.tsx
  packages/uikit/src/widgets/Modal/ModalV2.tsx
  packages/uikit/src/widgets/Modal/motionDomAnimation.ts
  packages/uikit/src/widgets/Modal/motionDomMax.ts
  yarn.lock
Labels: size/M

#6562 chore: Avoid apply protocol fee in Liquidity Detail page
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
Labels: size/XS

#6586 chore: add ankrBNB icon
  apps/web/public/images/tokens/0x52F24a5e03aee338Da5fd9Df68D2b6FAe1178827.png
Labels: size/XS

#6543 chore(Farms): UI improvement#2
  apps/aptos/components/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/components/RangeTag.tsx
  apps/web/src/views/AddLiquidityV3/IncreaseLiquidityV3.tsx
  apps/web/src/views/AddLiquidityV3/Migrate.tsx
  apps/web/src/views/AddLiquidityV3/components/StableV3Selector.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/FeeTierPercentageBadge.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3StakeAndUnStake.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/Farms/components/UpdatePositionsReminder.tsx
  apps/web/src/views/Migration/components/Farm/ActionPanel/Liquidity.tsx
  apps/web/src/views/Migration/components/Farm/ActionPanel/Multiplier.tsx
  apps/web/src/views/Migration/components/Farm/Cells/Liquidity.tsx
  apps/web/src/views/Migration/components/Farm/Cells/Multiplier.tsx
  apps/web/src/views/RemoveLiquidity/RemoveLiquidityV3.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/widgets/Farm/components/FarmCard/DetailsSection.tsx
  packages/uikit/src/widgets/Farm/components/FarmTable/Liquidity.tsx
  packages/uikit/src/widgets/Farm/components/FarmTable/Multiplier.tsx
  packages/uikit/src/widgets/Farm/types.ts
Labels: size/L

#6587 chore: list cbETH-ETH farm
  apps/web/public/images/1/tokens/0x0100546F2cD4C9D97f798fFC9755E47865FF7Ee6.png
  apps/web/public/images/1/tokens/0x3432B6A60D23Ca0dFCa7761B7ab56459D9C964D0.png
  apps/web/public/images/1/tokens/0x5E8422345238F34275888049021821E8E08CAa1f.png
  apps/web/public/images/1/tokens/0xBe9895146f7AF43049ca1c1AE358B0541Ea49704.png
  apps/web/public/images/1/tokens/0xD33526068D116cE69F19A9ee46F0bd304F21A51f.png
  apps/web/public/images/1/tokens/0xE95A203B1a91a908F9B9CE46459d101078c2c3cb.png
  apps/web/public/images/1/tokens/0xae78736Cd615f374D3085123A210448E74Fc6393.png
  apps/web/public/images/1/tokens/0xdBdb4d16EdA451D0503b854CF79D55697F90c8DF.png
  apps/web/public/images/tokens/0x52F24a5e03aee338Da5fd9Df68D2b6FAe1178827.png
  apps/web/public/images/tokens/0xe05A08226c49b636ACf99c40Da8DC6aF83CE5bB3.png
  packages/farms/constants/1.ts
Labels: size/XS

#6589 chore: Fix typo in roi calculator description
  packages/localization/src/config/translations.json
  packages/uikit/src/widgets/RoiCalculator/Details.tsx
Labels: size/XS

#6588 chore: Mark all position update as reduce
  apps/web/src/views/Farms/components/UpdatePositionsReminder.tsx
Labels: size/S

#6591 chore: Move liquidity to farms api
  .github/workflows/deploy-apis.yml
  apis/farms/.dev.vars
  apis/farms/package.json
  apis/farms/src/bindings.d.ts
  apis/farms/src/helper.ts
  apis/farms/src/index.ts
  apis/farms/src/provider.ts
  apis/farms/src/v3.ts
  apis/farms/wrangler.toml
  yarn.lock
Labels: size/XL

#6594 fix: Unsync lm data on retrigger check
  apps/web/src/views/Farms/components/UpdatePositionsReminder.tsx
Labels: size/M

#6596 chore: Bump up swr
  apps/web/package.json
  packages/wagmi/package.json
  yarn.lock
Labels: size/S

#6597 chore: List Moni syrup pool
  apps/web/src/config/constants/pools.tsx
Labels: size/S

#6599 chore: Pair logo use token list path
  apps/web/public/images/tokens/1/0x0100546F2cD4C9D97f798fFC9755E47865FF7Ee6.png
  apps/web/public/images/tokens/1/0x03Be5C903c727Ee2C8C4e9bc0AcC860Cca4715e2.png
  apps/web/public/images/tokens/1/0x152649eA73beAb28c5b49B26eb48f7EAD6d4c898.png
  apps/web/public/images/tokens/1/0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599.png
  apps/web/public/images/tokens/1/0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599.svg
  apps/web/public/images/tokens/1/0x3432B6A60D23Ca0dFCa7761B7ab56459D9C964D0.png
  apps/web/public/images/tokens/1/0x4d224452801ACEd8B2F0aebE155379bb5D594381.png
  apps/web/public/images/tokens/1/0x514910771AF9Ca656af840dff83E8264EcF986CA.png
  apps/web/public/images/tokens/1/0x5A98FcBEA516Cf06857215779Fd812CA3beF1B32.png
  apps/web/public/images/tokens/1/0x5E8422345238F34275888049021821E8E08CAa1f.png
  apps/web/public/images/tokens/1/0x6B175474E89094C44Da98b954EedeAC495271d0F.png
  apps/web/public/images/tokens/1/0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0.png
  apps/web/public/images/tokens/1/0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0.png
  apps/web/public/images/tokens/1/0x970B9bB2C0444F5E81e9d0eFb84C8ccdcdcAf84d.png
  apps/web/public/images/tokens/1/0x993864E43Caa7F7F12953AD6fEb1d1Ca635B875F.png
  apps/web/public/images/tokens/1/0x993864E43Caa7F7F12953AD6fEb1d1Ca635B875F.svg
  apps/web/public/images/tokens/1/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48.png
  apps/web/public/images/tokens/1/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48.svg
  apps/web/public/images/tokens/1/0xAf5191B0De278C7286d6C7CC6ab6BB8A73bA2Cd6.png
  apps/web/public/images/tokens/1/0xBe9895146f7AF43049ca1c1AE358B0541Ea49704.png
  apps/web/public/images/tokens/1/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2.png
  apps/web/public/images/tokens/1/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2.svg
  apps/web/public/images/tokens/1/0xD33526068D116cE69F19A9ee46F0bd304F21A51f.png
  apps/web/public/images/tokens/1/0xE95A203B1a91a908F9B9CE46459d101078c2c3cb.png
  apps/web/public/images/tokens/1/0xae78736Cd615f374D3085123A210448E74Fc6393.png
  apps/web/public/images/tokens/1/0xdAC17F958D2ee523a2206206994597C13D831ec7.png
  apps/web/public/images/tokens/1/0xdAC17F958D2ee523a2206206994597C13D831ec7.svg
  apps/web/public/images/tokens/1/0xdBdb4d16EdA451D0503b854CF79D55697F90c8DF.png
  apps/web/src/components/TokenImage/index.tsx
Labels: size/S

#6601 feat: Blog default language get from localStorage
  apps/blog/components/Article/AllArticle/index.tsx
  apps/blog/components/Article/ArticleSortSelect.tsx
  apps/blog/utils/getLanguageCodeFromLS.ts
  apps/blog/utils/getLocalStorageLanguageCode.ts
Labels: size/M, automerge

#6603 fix(Blog): Key naming
  apps/blog/components/Article/AllArticle/index.tsx
  apps/blog/components/Article/ArticleSortSelect.tsx
Labels: size/S, automerge

#6605 chore: Bump wagmi
  apps/bridge/package.json
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/src/config/wallet.ts
  apps/web/src/utils/wagmi.ts
  apps/web/tsconfig.json
  package.json
  packages/awgmi/package.json
  packages/smart-router/evm/package.json
  packages/smart-router/evm/v3-router/providers/multicallSwapProvider.ts
  packages/smart-router/tsconfig.json
  packages/token-lists/package.json
  packages/tsconfig/base.json
  packages/utils/package.json
  packages/wagmi/package.json
  turbo.json
  yarn.lock
Labels: size/XL

#6584 chore: use react-device-detect to detect mobile for uikit Modal
  packages/uikit/src/widgets/Modal/ModalContext.tsx
  packages/uikit/src/widgets/Modal/ModalV2.tsx
Labels: size/S

#6541 chore: New Crowdin updates
  apps/web/public/locales/ar-SA.json
  apps/web/public/locales/bn-BD.json
  apps/web/public/locales/de-DE.json
  apps/web/public/locales/el-GR.json
  apps/web/public/locales/en-US.json
  apps/web/public/locales/es-ES.json
  apps/web/public/locales/fi-FI.json
  apps/web/public/locales/fil-PH.json
  apps/web/public/locales/fr-FR.json
  apps/web/public/locales/hi-IN.json
  apps/web/public/locales/hu-HU.json
  apps/web/public/locales/id-ID.json
  apps/web/public/locales/it-IT.json
  apps/web/public/locales/ja-JP.json
  apps/web/public/locales/ko-KR.json
  apps/web/public/locales/nl-NL.json
  apps/web/public/locales/pl-PL.json
  apps/web/public/locales/pt-BR.json
  apps/web/public/locales/pt-PT.json
  apps/web/public/locales/ro-RO.json
  apps/web/public/locales/ru-RU.json
  apps/web/public/locales/sv-SE.json
  apps/web/public/locales/ta-IN.json
  apps/web/public/locales/tr-TR.json
  apps/web/public/locales/uk-UA.json
  apps/web/public/locales/vi-VN.json
  apps/web/public/locales/zh-CN.json
  apps/web/public/locales/zh-TW.json
Labels: size/XXL

#6595 revert: Use box allow passing style props
  packages/uikit/src/__tests__/widgets/modal.test.tsx
  packages/uikit/src/widgets/Modal/Modal.tsx
  packages/uikit/src/widgets/Modal/styles.tsx
Labels: size/M

#6612 fix: Remove custom multicall type
  .changeset/brown-panthers-double.md
  apis/farms/src/helper.ts
  apis/farms/src/v3.ts
  apps/web/src/pages/api/v3/[chainId]/farms/liquidity/[address].ts
  apps/web/src/utils/multicall.ts
  packages/farms/src/fetchFarmsV3.ts
  packages/multicall/index.ts
  packages/tokens/package.json
  packages/utils/abitype.ts
Labels: size/XL

#6610 chore: list AXL farm
  apps/web/public/images/tokens/1/0x467719aD09025FcC6cF6F8311755809d45a5E5f3.png
  packages/farms/constants/1.ts
  packages/tokens/src/1.ts
Labels: size/S

#6616 chore: Move some external packages to ts emit
  apps/web/next.config.mjs
  packages/aptos-swap-sdk/package.json
  packages/awgmi/package.json
  packages/multicall/package.json
  packages/smart-router/evm/package.json
  packages/smart-router/package.json
  packages/smart-router/tsconfig.json
  packages/smart-router/tsup.config.ts
  packages/swap-sdk-core/tsconfig.json
  packages/swap-sdk-core/tsup.config.ts
  packages/swap-sdk/tsconfig.json
  packages/swap-sdk/tsup.config.ts
  packages/token-lists/package.json
  packages/tokens/tsconfig.json
  packages/tokens/tsup.config.ts
  packages/v3-sdk/tsconfig.json
  packages/v3-sdk/tsup.config.ts
  packages/wagmi/package.json
  yarn.lock
Labels: size/L

#6617 fix: modal overflow style
  packages/uikit/src/__tests__/widgets/modal.test.tsx
  packages/uikit/src/widgets/Modal/Modal.tsx
Labels: size/XS

#6619 chore: update token name for v2 subgraph
  apps/web/src/state/info/constant.ts
  apps/web/src/views/Info/Tokens/TokenPage.tsx
  apps/web/src/views/Info/components/InfoSearch/index.tsx
  apps/web/src/views/Info/components/InfoTables/TokensTable.tsx
Labels: size/S

#6620 chore: transaction table detail improvement
  apps/web/src/views/V3Info/components/TransactionsTable/index.tsx
  apps/web/src/views/V3Info/utils/numbers.ts
Labels: size/M

#6621 chore: v3 info transaction table improvement
  apps/web/src/views/V3Info/components/TransactionsTable/index.tsx
Labels: size/S

#6607 chore: Move to finished pool
  apps/web/src/config/constants/pools.tsx
Labels: size/S

#6625 chore: Move to finished pool
  apps/web/src/config/constants/pools.tsx
Labels: size/M

#6618 fix: Use Exact out for more precise usd price
  apps/web/src/hooks/useBUSDPrice.ts
Labels: size/S

#6629 chore: Move wallet and chains image
  apps/aptos/components/NetworkSwitcher.tsx
  apps/aptos/config/index.ts
  apps/web/src/components/Logo/ChainLogo.tsx
  apps/web/src/components/Logo/CurrencyLogo.tsx
  apps/web/src/components/NetworkSwitcher.tsx
  apps/web/src/config/wallet.ts
  apps/web/src/views/Info/components/InfoNav/index.tsx
  apps/web/src/views/V3Info/components/Layout/InfoNav.tsx
  packages/uikit/src/components/CurrencyLogo/CurrencyLogo.tsx
Labels: size/M

#6628 chore: Add Discord Icon
  apps/blog/components/Article/SingleArticle/SocialIcon.tsx
Labels: size/XS, automerge

#6614 chore: New Crowdin updates
  apps/web/public/locales/ar-SA.json
  apps/web/public/locales/bn-BD.json
  apps/web/public/locales/de-DE.json
  apps/web/public/locales/es-ES.json
  apps/web/public/locales/fi-FI.json
  apps/web/public/locales/fil-PH.json
  apps/web/public/locales/fr-FR.json
  apps/web/public/locales/hu-HU.json
  apps/web/public/locales/ko-KR.json
  apps/web/public/locales/nl-NL.json
  apps/web/public/locales/pt-BR.json
  apps/web/public/locales/pt-PT.json
  apps/web/public/locales/zh-CN.json
  apps/web/public/locales/zh-TW.json
Labels: size/XXL

#6630 perf: improve Swap input
  apps/web/src/hooks/useBUSDPrice.ts
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/state/swap/useSwapActionHandlers.ts
  packages/smart-router/evm/v3-router/gasModel.ts
  packages/smart-router/evm/v3-router/getBestTrade.ts
  packages/smart-router/evm/v3-router/getRoutesWithValidQuote.ts
  packages/smart-router/evm/v3-router/providers/multicallSwapProvider.ts
  packages/smart-router/evm/v3-router/types/providers.ts
  packages/smart-router/evm/v3-router/types/trade.ts
Labels: size/M

#6631 fix: Block number compare
  apps/web/src/hooks/useBestAMMTrade.ts
Labels: size/S

#6632 chore: List sfund pool
  apps/web/src/config/constants/pools.tsx
Labels: size/S

#6633 chore: List GQ v3 farm
  packages/farms/constants/56.ts
Labels: size/XS

#6635 chore: v3 liquidity chart initial position
  apps/web/src/views/V3Info/components/DensityChart/index.tsx
Labels: size/XS

#6637 chore: UI adjustment
  apps/web/src/views/Profile/components/EditProfileModal/index.tsx
  packages/uikit/src/__tests__/widgets/modal.test.tsx
  packages/uikit/src/widgets/Modal/Modal.tsx
  packages/uikit/src/widgets/Modal/types.ts
Labels: size/S

#6636 fix: Corner style in some modals
  apps/web/src/views/Farms/components/FarmCard/V3/FarmInfo.tsx
  packages/uikit/src/__tests__/widgets/modal.test.tsx
  packages/uikit/src/widgets/Modal/Modal.tsx
  packages/uikit/src/widgets/Modal/styles.tsx
Labels: size/XS

#6602 chore: switch v3 subgraph endpoint to nodeReal
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/utils/graphql.ts
  apps/web/src/views/V3Info/data/pool/chartData.ts
  apps/web/src/views/V3Info/data/pool/poolData.ts
  apps/web/src/views/V3Info/data/pool/tickData.ts
  apps/web/src/views/V3Info/data/pool/topPools.ts
  apps/web/src/views/V3Info/data/pool/transactions.ts
  apps/web/src/views/V3Info/data/protocol/chart.ts
  apps/web/src/views/V3Info/data/protocol/overview.ts
  apps/web/src/views/V3Info/data/protocol/transactions.ts
  apps/web/src/views/V3Info/data/search/index.ts
  apps/web/src/views/V3Info/data/token/chartData.ts
  apps/web/src/views/V3Info/data/token/poolsForToken.ts
  apps/web/src/views/V3Info/data/token/priceData.ts
  apps/web/src/views/V3Info/data/token/tokenData.ts
  apps/web/src/views/V3Info/data/token/topTokens.ts
  apps/web/src/views/V3Info/data/token/transactions.ts
  apps/web/src/views/V3Info/hooks/index.ts
  apps/web/src/views/V3Info/utils/getEthPrices.ts
  apps/web/src/views/V3Info/views/TokenPage.tsx
Labels: size/L

#6642 chore: List AXL farm and pool
  apps/web/src/config/constants/pools.tsx
  packages/farms/constants/56.ts
  packages/tokens/src/56.ts
Labels: size/S

#6643 fix: tsc handle error
  packages/smart-router/evm/v3-router/providers/hybridPoolProvider.ts
  packages/smart-router/tsup.config.ts
  packages/swap-sdk-core/tsup.config.ts
  packages/swap-sdk/tsup.config.ts
  packages/tokens/tsup.config.ts
  packages/v3-sdk/tsup.config.ts
Labels: size/M
