Repository pancakeswap/pancake-frontend, pull requests merged in 2023-08, with the labels that each got.

#7463 fix: Tooltip not visible when hover in modals
  packages/uikit/package.json
  packages/uikit/src/widgets/Modal/ModalContext.tsx
  packages/uikit/src/widgets/Modal/ModalV2.tsx
  pnpm-lock.yaml
Labels: size/M

#7461 feat(Bridge): Bump LayerZero Widget
  apps/bridge/components/layerZero/config.ts
Labels: size/XS, automerge

#7466 chore: set zksync default list
  apps/web/src/components/SearchModal/ManageLists.tsx
  apps/web/src/config/constants/lists.ts
  apps/web/src/state/lists/hooks.ts
Labels: size/M

#7456 chore: log wallet connect event
  apps/web/src/components/ConnectWalletButton.tsx
  apps/web/src/utils/customGTMEventTracking.ts
  packages/ui-wallets/src/WalletModal.tsx
Labels: size/S

#7469 chore: zksync token list turn up default
  apps/web/src/config/constants/lists.ts
Labels: size/XS

#7470 chore: list dck farm and pool
  packages/farms/constants/56.ts
  packages/pools/src/constants/pools/56.ts
  packages/tokens/src/56.ts
Labels: size/S

#7471 refactor: Warning Modal Support Multiple Chains
  apps/web/src/config/constants/swapWarningTokens.ts
  apps/web/src/utils/shouldShowSwapWarning.ts
  apps/web/src/views/Swap/components/SwapWarningModal/1/ALETHWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/1/index.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/56/ABNBWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/56/BTTWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/56/BondlyWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/56/CcarWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/56/FREEWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/56/GalaWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/56/ItamWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/56/METISWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/56/RugPullWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/56/SafemoonWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/56/XCADWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/56/index.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/index.tsx
  apps/web/src/views/Swap/hooks/useWarningImport.tsx
  packages/localization/src/config/translations.json
Labels: size/L, automerge

#7468 chore: update banner wording
  apps/web/src/views/Home/components/Banners/ZksyncBanner.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#7472 fix: Step intro not working in wallet modal
  packages/ui-wallets/src/components/Intro.tsx
Labels: size/XS

#7475 fix(Blog): Image url
  apps/blog/types.ts
  apps/blog/utils/transformArticle.ts
Labels: size/XS, automerge

#7477 feat: farm on zksync
  apis/farms/.dev.vars
  apis/farms/src/bindings.d.ts
  apis/farms/src/lpApr.ts
  apis/farms/src/provider.ts
  apis/farms/src/v3.ts
  apis/farms/wrangler.toml
  apps/web/src/components/TokenImage/index.tsx
  apps/web/src/config/constants/supportChains.ts
  apps/web/src/config/constants/tokenLists/pancake-default.tokenlist.json
  apps/web/src/views/TradingReward/config/pairs/index.tsx
  packages/farms/constants/324.ts
  packages/farms/constants/common/index.ts
  packages/farms/constants/v3/index.ts
  packages/farms/src/const.ts
  packages/farms/tests/v3.test.ts
  packages/tokens/src/324.ts
  packages/tokens/src/common.ts
Labels: size/M

#7480 feat: Add More chains
  apps/aptos/components/NetworkSwitcher.tsx
Labels: size/XS, automerge

#7488 fix(Trading Reward): Pagination
  apps/web/src/views/TradingReward/components/Leaderboard/index.tsx
  apps/web/src/views/TradingReward/components/RewardsBreakdown/index.tsx
Labels: size/M, automerge

#7489 chore: list wom farm on eth
  packages/farms/constants/1.ts
  packages/tokens/src/1.ts
Labels: size/S

#7490 fix: WOM farm config
  packages/farms/constants/1.ts
Labels: size/XS

#7491 fix: zksync Currency logo path
  packages/uikit/src/components/CurrencyLogo/utils.ts
Labels: size/XS

#7385 feat: Change to Hashdit
  apps/web/src/components/AccessRisk/AccessRiskTooltips.tsx
  apps/web/src/components/AccessRisk/index.tsx
  apps/web/src/components/AccessRisk/utils/fetchTokenRisk.ts
  apps/web/src/components/Menu/GlobalSettings/SettingsModal.tsx
  apps/web/src/components/SearchModal/ImportToken.tsx
  apps/web/src/pages/api/risk/[chainId]/[address].ts
  apps/web/src/views/LimitOrders/index.tsx
  apps/web/src/views/Swap/V3Swap/containers/RiskCheck.tsx
  apps/web/src/views/Swap/hooks/fetchTokenRisk.ts
  packages/localization/src/config/translations.json
Labels: size/L, automerge

#7508 chore: Revert Change to Hashdit
  apps/web/src/components/AccessRisk/AccessRiskTooltips.tsx
  apps/web/src/components/AccessRisk/utils/fetchTokenRisk.ts
  apps/web/src/components/Menu/GlobalSettings/SettingsModal.tsx
  apps/web/src/components/SearchModal/ImportToken.tsx
  apps/web/src/pages/api/risk/[chainId]/[address].ts
  apps/web/src/views/LimitOrders/index.tsx
  apps/web/src/views/Swap/V3Swap/containers/RiskCheck.tsx
  apps/web/src/views/Swap/components/AccessRisk/index.tsx
  apps/web/src/views/Swap/hooks/fetchTokenRisk.ts
  packages/localization/src/config/translations.json
Labels: size/L

#7510 feat: List Farms
  packages/farms/constants/56.ts
Labels: size/S, automerge

#7515 feat: List unshETH
  packages/farms/constants/56.ts
  packages/pools/src/constants/pools/56.ts
Labels: size/S

#7507 chore(Pool): Move eth pools to finished
  packages/pools/src/constants/pools/1.ts
Labels: size/S, automerge

#7509 feat: Change to Hashdit
  apps/web/src/components/AccessRisk/AccessRiskTooltips.tsx
  apps/web/src/components/AccessRisk/index.tsx
  apps/web/src/components/AccessRisk/utils/fetchTokenRisk.ts
  apps/web/src/components/Menu/GlobalSettings/SettingsModal.tsx
  apps/web/src/components/SearchModal/ImportToken.tsx
  apps/web/src/pages/api/risk/[chainId]/[address].ts
  apps/web/src/views/LimitOrders/index.tsx
  apps/web/src/views/Swap/V3Swap/containers/RiskCheck.tsx
  apps/web/src/views/Swap/hooks/fetchTokenRisk.ts
  packages/localization/src/config/translations.json
Labels: Delayed Release, size/L

#7493 feat: Return to liquidity detail page instead of overview after increase liquidity
  apps/web/src/views/AddLiquidityV3/IncreaseLiquidityV3.tsx
Labels: size/S

#7492 feat: Add time to liquidity history in mobile
  apps/web/src/pages/liquidity/[tokenId].tsx
Labels: size/M

#7481 feat: Hide Your shares percentage when totalSupplyAt is zero
  apps/web/src/views/Pools/components/RevenueSharing/BenefitsModal/RevenueSharing.tsx
Labels: size/S, automerge

#7520 fix: Sentry issue
  apps/web/src/utils/shouldShowSwapWarning.ts
  apps/web/src/views/TradingReward/components/YourTradingReward/QualifiedPreview.tsx
Labels: size/S

#7521 feat(Blog): Add filterTagArray
  apps/blog/hooks/getArticle.ts
  apps/blog/pages/index.tsx
  apps/blog/utils/filterTagArray.ts
Labels: size/XS, automerge

#7485 feat: Arbitrum
  .changeset/dry-waves-dress.md
  apis/routing/.dev.vars
  apis/routing/src/constants.ts
  apis/routing/src/provider.ts
  apps/web/src/components/NetworkSwitcher.tsx
  apps/web/src/config/chains.ts
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/config/constants/lists.ts
  apps/web/src/config/constants/tokenLists/pancake-default.tokenlist.json
  apps/web/src/state/info/constant.ts
  packages/tokens/src/42161.ts
  packages/tokens/src/common.ts
Labels: size/M

#7523 fix(swap): optional warning
  apps/web/src/utils/shouldShowSwapWarning.ts
  apps/web/src/views/Swap/components/SwapWarningModal/index.tsx
Labels: size/XS

#7525 chore: ARB banner
  apps/web/src/views/Home/components/Banners/ArbitrumOneBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  apps/web/src/views/Home/components/Banners/images/arbBg.png
  apps/web/src/views/Home/components/Banners/images/arbBgMobile.png
  apps/web/src/views/Home/components/Banners/images/arbBunny.png
  apps/web/src/views/Home/components/Banners/images/arbLogo.png
  apps/web/src/views/Home/components/Banners/images/index.ts
  packages/localization/src/config/translations.json
Labels: size/L

#7503 perf(farm-api): kv cache for v3 lp liquidity
  apis/farms/src/kv.ts
  apis/farms/src/v3.ts
  apps/web/src/pages/_document.tsx
  apps/web/src/state/farmsV3/hooks.ts
  packages/farms/src/index.ts
  packages/farms/src/types.ts
Labels: size/L

#7517 perf: Use next router link for internal links
  apps/web/src/components/Menu/SubNav.tsx
  apps/web/src/hooks/useLockedEndNotification.tsx
  apps/web/src/views/Home/components/Banners/LiquidStakingBanner.tsx
  apps/web/src/views/LiquidStaking/components/FAQs.tsx
  apps/web/src/views/Voting/components/CastVoteModal/DetailsView.tsx
Labels: size/L

#7531 chore(farms): Update zkevm subgraph
  apis/farms/src/v3.ts
Labels: size/XS

#7532 chore: bsctestnet whitelist
  apps/web/src/config/constants/tokenLists/pancake-default.tokenlist.json
Labels: size/M

#7526 feat(Aptos): Network Switch add Arbitrum
  apps/aptos/components/NetworkSwitcher.tsx
Labels: size/XS, automerge

#7535 chore: Export Transformer from smart router
  .changeset/seven-crews-reply.md
  packages/smart-router/evm/v3-router/index.ts
Labels: size/XS

#7537 chore: update subgraph endpoint for arb
  apis/routing/src/constants.ts
  apps/web/src/config/constants/endpoints.ts
Labels: size/XS

#7527 perf: Remove deprecated cake bnb price hooks and cache them to reduce amount of requests
  apps/web/src/components/Menu/index.tsx
  apps/web/src/hooks/useBNBPrice.ts
  apps/web/src/hooks/useBUSDPrice.ts
  apps/web/src/hooks/useCakePrice.ts
  apps/web/src/hooks/useGetDocumentTitlePrice.ts
  apps/web/src/state/farms/hooks.ts
  apps/web/src/state/farmsV3/hooks.ts
  apps/web/src/state/pools/index.ts
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3ApyButton.tsx
  apps/web/src/views/Home/components/WinSection/PredictionCardContent.tsx
  apps/web/src/views/Ifos/components/IfoSteps.tsx
  apps/web/src/views/Migration/components/v3/Step1.tsx
  apps/web/src/views/Nft/market/ActivityHistory/ActivityHistory.tsx
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/ActivityCard.tsx
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/MainNFTCard.tsx
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/OwnerCard.tsx
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/ForSaleTableCard/ForSaleTableRows.tsx
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/MainPancakeBunnyCard.tsx
  apps/web/src/views/Nft/market/components/Activity/ActivityPrice.tsx
  apps/web/src/views/Nft/market/components/Activity/ActivityRow.tsx
  apps/web/src/views/Nft/market/components/Activity/MobileModal.tsx
  apps/web/src/views/Nft/market/components/BuySellModals/BuyModal/styles.tsx
  apps/web/src/views/Nft/market/components/BuySellModals/SellModal/SetPriceStage.tsx
  apps/web/src/views/Nft/market/components/BuySellModals/SellModal/styles.tsx
  apps/web/src/views/Nft/market/components/CollectibleCard/CardBody.tsx
  apps/web/src/views/Nft/market/components/CollectibleCard/styles.tsx
  apps/web/src/views/Profile/components/ActivityHistory/index.tsx
  apps/web/src/views/TradingCompetition/helpers.ts
Labels: size/L

#7548 chore: Graceful upgrade routing api
  packages/smart-router/evm/v3-router/providers/poolProviders/getV3CandidatePools.ts
Labels: size/XS

#7549 chore: Reset routing api domain
  apis/routing/wrangler.toml
  packages/smart-router/evm/v3-router/providers/poolProviders/getV3CandidatePools.ts
Labels: size/XS

#7550 fix: Duplicate css attributes in bridge
  apps/bridge/components/Page.tsx
  apps/bridge/components/layerZero/index.tsx
Labels: size/XS

#7530 feat: Arbitrum info
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/state/info/constant.ts
  apps/web/src/state/info/hooks.ts
  apps/web/src/utils/getTokenLogoURL.ts
  apps/web/src/views/Info/components/InfoNav/index.tsx
  apps/web/src/views/V3Info/components/Layout/InfoNav.tsx
  apps/web/src/views/V3Info/constants.ts
Labels: size/S

#7553 chore(farms): Api more timeout
  apis/farms/src/v3.ts
Labels: size/XS

#7522 feat(Blog): Add Preview Link
  apps/blog/pages/api/disabled-preview.tsx
  apps/blog/pages/api/preview.tsx
  apps/blog/pages/articles/[slug].tsx
Labels: size/M

#7554 fix: Revenue Sharing Pool lastTokenTimestamp
  apps/web/src/views/Pools/hooks/useRevenueSharingPool.ts
Labels: size/S, automerge

#7497 refactor(Liquid Staking): Support BNB/SnBNB
  apps/web/src/config/abi/snBNB.ts
  apps/web/src/config/constants/liquidStaking.ts
  apps/web/src/pages/liquid-staking/[contract].tsx
  apps/web/src/pages/liquid-staking/[currency].tsx
  apps/web/src/pages/liquid-staking/index.tsx
  apps/web/src/views/LiquidStaking/Stake/index.tsx
  apps/web/src/views/LiquidStaking/components/ExchangeRateTitle.tsx
  apps/web/src/views/LiquidStaking/components/FAQs.tsx
  apps/web/src/views/LiquidStaking/components/LiquidStakingApr.tsx
  apps/web/src/views/LiquidStaking/components/LiquidStakingButton.tsx
  apps/web/src/views/LiquidStaking/components/StakeInfo/ExchangeRateTitle.tsx
  apps/web/src/views/LiquidStaking/components/StakeInfo/LiquidStakingApr.tsx
  apps/web/src/views/LiquidStaking/components/StakeInfo/index.tsx
  apps/web/src/views/LiquidStaking/constants/1.ts
  apps/web/src/views/LiquidStaking/constants/5.ts
  apps/web/src/views/LiquidStaking/constants/56.ts
  apps/web/src/views/LiquidStaking/constants/97.ts
  apps/web/src/views/LiquidStaking/constants/FAQs/BnbSnbnbFaq.tsx
  apps/web/src/views/LiquidStaking/constants/FAQs/EthWbethFaq.tsx
  apps/web/src/views/LiquidStaking/constants/types.ts
  apps/web/src/views/LiquidStaking/hooks/useCallStakingContract.tsx
  apps/web/src/views/LiquidStaking/hooks/useExchangeRate.tsx
  apps/web/src/views/LiquidStaking/hooks/useLiquidStakingApprovalStatus.tsx
  apps/web/src/views/LiquidStaking/hooks/useLiquidStakingApprove.tsx
  apps/web/src/views/LiquidStaking/hooks/useLiquidStakingApr.tsx
  apps/web/src/views/LiquidStaking/hooks/useLiquidStakingList.tsx
  packages/localization/src/config/translations.json
Labels: size/XXL, automerge

#7556 chore: List cyber eth farm
  packages/farms/constants/1.ts
  packages/tokens/src/1.ts
Labels: size/S

#7557 fix: Ifo terms and conditions link opens in the same tab
  apps/web/src/components/Modal/USCitizenConfirmModal.tsx
Labels: size/XS

#7563 revert: Hook useCakePrice & useBNBPrice
  apps/web/src/hooks/useBNBPrice.ts
  apps/web/src/hooks/useCakePrice.ts
Labels: size/M

#7565 chore: Export types from transformer
  .changeset/neat-carrots-clap.md
  packages/smart-router/evm/v3-router/utils/transformer.ts
Labels: size/S

#7564 feat: farm on Arbitrum
  apis/farms/.dev.vars
  apis/farms/src/bindings.d.ts
  apis/farms/src/lpApr.ts
  apis/farms/src/provider.ts
  apis/farms/src/v3.ts
  apis/farms/wrangler.toml
  apps/web/src/components/TokenImage/index.tsx
  apps/web/src/config/constants/supportChains.ts
  apps/web/src/config/constants/tokenLists/pancake-default.tokenlist.json
  apps/web/src/views/TradingReward/config/pairs/index.tsx
  packages/farms/constants/42161.ts
  packages/farms/constants/common/index.ts
  packages/farms/constants/priceHelperLps/42161.ts
  packages/farms/constants/priceHelperLps/getFarmsPriceHelperLpFiles.ts
  packages/farms/constants/v3/index.ts
  packages/farms/src/const.ts
  packages/farms/tests/v3.test.ts
  packages/tokens/src/42161.ts
  packages/tokens/src/common.ts
Labels: size/L

#7567 chore: add multi-call3 address
  apps/web/src/config/constants/contracts.ts
Labels: size/XS

#7448 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XXL

#7568 revert: Hook useCakePrice & useBNBPrice (#7563)
  apps/web/src/hooks/useBNBPrice.ts
  apps/web/src/hooks/useCakePrice.ts
Labels: size/M

#7572 chore: Add arb node
  apps/web/src/config/constants/exchange.ts
  apps/web/src/config/nodes.ts
  apps/web/src/utils/nodeReal.ts
  packages/smart-router/evm/constants/multicall.ts
Labels: size/M

#7573 feat(Bridge): Bump up bridge version 0.0.24
  apps/bridge/components/layerZero/config.ts
Labels: size/XS, automerge

#7516 feat: Bump blockto v2
  .changeset/smart-plants-juggle.md
  packages/awgmi/core/src/connectors/types.ts
  packages/awgmi/package.json
  packages/wagmi/connectors/blocto/blocto.ts
  packages/wagmi/package.json
  pnpm-lock.yaml
Labels: size/M, automerge

#7575 chore: New Crowdin updates
  locales/zh-TW.json
Labels: size/M

#7579 chore: Reduce banner size
  apps/web/src/views/Home/components/Banners/images/galxe-traverse-bg-mobile.png
  apps/web/src/views/Home/components/Banners/images/galxe-traverse-bg.png
  apps/web/src/views/Home/components/Banners/images/galxe-traverse-bunny.png
  apps/web/src/views/Home/components/Banners/images/galxe-traverse-cloud.png
Labels: size/XS

#7578 feat: Only show v1 farm in BSC
  apps/web/src/views/Farms/Farms.tsx
  apps/web/src/views/Farms/FarmsV3.tsx
Labels: size/XS, automerge

#7476 feat: add new chains for fiat onramp
  apps/web/.env
  apps/web/public/images/AUD.svg
  apps/web/public/images/on-ramp-providers/binanceConnectSvg.svg
  apps/web/public/images/pocket-watch.svg
  apps/web/src/components/FiatOnRampModal/FiatOnRampModal.tsx
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/config/constants/supportChains.ts
  apps/web/src/config/constants/tokenLists/pancake-supported-onramp-currency-list.json
  apps/web/src/state/buyCrypto/actions.ts
  apps/web/src/state/buyCrypto/hooks.ts
  apps/web/src/state/buyCrypto/reducer.ts
  apps/web/src/views/BuyCrypto/Icons/Icons.tsx
  apps/web/src/views/BuyCrypto/Icons/index.tsx
  apps/web/src/views/BuyCrypto/components/AccordianDropdown/Accordian.tsx
  apps/web/src/views/BuyCrypto/components/AccordianDropdown/AccordianItem.tsx
  apps/web/src/views/BuyCrypto/components/FAQ.tsx
  apps/web/src/views/BuyCrypto/components/OnRampCurrencySelect/index.tsx
  apps/web/src/views/BuyCrypto/constants.ts
  apps/web/src/views/BuyCrypto/containers/BuyCryptoForm.tsx
  apps/web/src/views/BuyCrypto/containers/CryptoQuoteForm.tsx
  apps/web/src/views/BuyCrypto/hooks/usePriceQuoter.ts
  apps/web/src/views/BuyCrypto/hooks/useProviderAvailability.ts
  apps/web/src/views/BuyCrypto/hooks/useProviderQuotes.ts
  apps/web/src/views/BuyCrypto/types.ts
  packages/localization/src/config/translations.json
Labels: size/XL

#7582 fix: update mercuryo widget
  apps/web/src/components/FiatOnRampModal/FiatOnRampModal.tsx
Labels: size/XS, automerge

#7584 revert: Fiat onramp
  apps/web/.env
  apps/web/public/images/AUD.svg
  apps/web/public/images/on-ramp-providers/binanceConnectSvg.svg
  apps/web/public/images/pocket-watch.svg
  apps/web/src/components/FiatOnRampModal/FiatOnRampModal.tsx
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/config/constants/supportChains.ts
  apps/web/src/config/constants/tokenLists/pancake-supported-onramp-currency-list.json
  apps/web/src/state/buyCrypto/actions.ts
  apps/web/src/state/buyCrypto/hooks.ts
  apps/web/src/state/buyCrypto/reducer.ts
  apps/web/src/views/BuyCrypto/Icons/Icons.tsx
  apps/web/src/views/BuyCrypto/Icons/index.tsx
  apps/web/src/views/BuyCrypto/components/AccordianDropdown/Accordian.tsx
  apps/web/src/views/BuyCrypto/components/AccordianDropdown/AccordianItem.tsx
  apps/web/src/views/BuyCrypto/components/FAQ.tsx
  apps/web/src/views/BuyCrypto/components/OnRampCurrencySelect/index.tsx
  apps/web/src/views/BuyCrypto/constants.ts
  apps/web/src/views/BuyCrypto/containers/BuyCryptoForm.tsx
  apps/web/src/views/BuyCrypto/containers/CryptoQuoteForm.tsx
  apps/web/src/views/BuyCrypto/hooks/usePriceQuoter.ts
  apps/web/src/views/BuyCrypto/hooks/useProviderAvailability.ts
  apps/web/src/views/BuyCrypto/hooks/useProviderQuotes.ts
  apps/web/src/views/BuyCrypto/types.ts
  packages/localization/src/config/translations.json
Labels: size/XL

#7587 fix(wagmi): Blocto keep connection after disconnect
  .changeset/empty-trees-boil.md
  packages/wagmi/connectors/blocto/blocto.ts
Labels: size/S

#7586 feat: Fiat onramp
  apps/web/.env
  apps/web/public/images/AUD.svg
  apps/web/public/images/on-ramp-providers/binanceConnectSvg.svg
  apps/web/public/images/pocket-watch.svg
  apps/web/src/components/FiatOnRampModal/FiatOnRampModal.tsx
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/config/constants/supportChains.ts
  apps/web/src/config/constants/tokenLists/pancake-supported-onramp-currency-list.json
  apps/web/src/state/buyCrypto/actions.ts
  apps/web/src/state/buyCrypto/hooks.ts
  apps/web/src/state/buyCrypto/reducer.ts
  apps/web/src/views/BuyCrypto/Icons/Icons.tsx
  apps/web/src/views/BuyCrypto/Icons/index.tsx
  apps/web/src/views/BuyCrypto/components/AccordianDropdown/Accordian.tsx
  apps/web/src/views/BuyCrypto/components/AccordianDropdown/AccordianItem.tsx
  apps/web/src/views/BuyCrypto/components/FAQ.tsx
  apps/web/src/views/BuyCrypto/components/OnRampCurrencySelect/index.tsx
  apps/web/src/views/BuyCrypto/constants.ts
  apps/web/src/views/BuyCrypto/containers/BuyCryptoForm.tsx
  apps/web/src/views/BuyCrypto/containers/CryptoQuoteForm.tsx
  apps/web/src/views/BuyCrypto/hooks/usePriceQuoter.ts
  apps/web/src/views/BuyCrypto/hooks/useProviderAvailability.ts
  apps/web/src/views/BuyCrypto/hooks/useProviderQuotes.ts
  apps/web/src/views/BuyCrypto/types.ts
  packages/localization/src/config/translations.json
Labels: size/XL

#7589 feat: Remove text
  apps/web/src/views/BuyCrypto/components/AccordianDropdown/AccordianItem.tsx
  apps/web/src/views/BuyCrypto/components/FAQ.tsx
  packages/localization/src/config/translations.json
Labels: size/XS, automerge

#7583 chore: moonpay banner
  apps/web/src/views/Home/components/Banners/MoonPayBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  apps/web/src/views/Home/components/Banners/images/index.ts
  apps/web/src/views/Home/components/Banners/images/moonpay-bg-mobile.png
  apps/web/src/views/Home/components/Banners/images/moonpay-bg.png
  apps/web/src/views/Home/components/Banners/images/moonpay-cash.png
  apps/web/src/views/Home/components/Banners/images/moonpay-logo.png
  packages/localization/src/config/translations.json
Labels: size/L

#7590 chore: Typo
  apps/web/src/views/BuyCrypto/components/FAQ.tsx
  packages/localization/src/config/translations.json
Labels: size/XS, automerge

#7594 fix(Pool): Lock CAKE Modal
  apps/web/src/views/Pools/components/LockedPool/Common/Overview/BalanceRow.tsx
  apps/web/src/views/Pools/components/LockedPool/Common/Overview/index.tsx
  apps/web/src/views/Pools/components/LockedPool/utils/formatICake.ts
Labels: size/S, automerge

#7598 chore: list cyber farm on bsc
  packages/farms/constants/56.ts
  packages/tokens/src/56.ts
Labels: size/S

#7602 fix: Axl finished pool
  packages/pools/src/constants/pools/56.ts
Labels: size/XS

#7603 fix: Finished pools apr modal still available
  packages/uikit/src/widgets/Pool/Apr.tsx
Labels: size/M

#7600 fix: Liquidity urls not correctly constructed
  apps/web/src/views/AddLiquidityV3/components/StableV3Selector.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/FeeSelector.tsx
  apps/web/src/views/AddLiquidityV3/index.tsx
Labels: size/M

#7599 fix: Add liquidity v2 leaks state between lp's
  apps/web/src/pages/add/[[...currency]].tsx
  apps/web/src/pages/increase/[[...currency]].tsx
  apps/web/src/pages/v2/add/[[...currency]].tsx
  apps/web/src/state/mint/hooks.ts
  apps/web/src/state/mint/reducer.ts
  apps/web/src/views/AddLiquidity/AddLiquidityV2FormProvider.tsx
  apps/web/src/views/AddLiquidity/AddStableLiquidity/hooks/useStableLPDerivedMintInfo.tsx
  apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
  apps/web/src/views/AddLiquidity/index.tsx
  apps/web/src/views/AddLiquidityV3/index.tsx
Labels: size/L

#7591 fix: Remove liquidity v2 leaks state between lp's
  apps/web/src/pages/v2/remove/[[...currency]].tsx
  apps/web/src/state/burn/hooks.ts
  apps/web/src/state/burn/reducer.ts
  apps/web/src/views/Migration/components/v3/Step2.tsx
  apps/web/src/views/RemoveLiquidity/RemoveLiquidityV2FormProvider.tsx
  apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/hooks/useStableDerivedBurnInfo.ts
  apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/index.tsx
Labels: size/L

#7607 fix: Missing farming translation
  apps/web/src/pages/liquidity/index.tsx
  apps/web/src/views/Migration/components/v3/Step4.tsx
Labels: size/XS

#7612 perf: Memoize cake approval status to not create bignumber each render
  apps/web/src/hooks/useCakeApprovalStatus.ts
Labels: size/S

#7608 fix: Lp shows active tag when loading
  apps/web/src/pages/liquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/RemoveLiquidityV3.tsx
Labels: size/XS

#7595 feat: Directly use red alarm api and Modal content change for risk scanner
  apps/web/src/components/AccessRisk/AccessRiskTooltips.tsx
  apps/web/src/components/AccessRisk/index.tsx
  apps/web/src/components/AccessRisk/utils/fetchTokenRisk.ts
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/pages/api/risk/[chainId]/[address].ts
  packages/localization/src/config/translations.json
Labels: size/L, automerge

#7562 feat: More testnet
  .changeset/eight-toys-eat.md
  apps/web/package.json
  apps/web/src/components/NetworkSwitcher.tsx
  apps/web/src/config/chains.ts
  apps/web/src/config/constants/contracts.ts
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/config/constants/exchange.ts
  apps/web/src/config/constants/tokenLists/pancake-default.tokenlist.json
  apps/web/src/config/nodes.ts
  apps/web/src/config/pools.ts
  apps/web/src/hooks/useInfoUserSavedTokensAndPoolsList.ts
  apps/web/src/state/lists/hooks.ts
  apps/web/src/state/swap/fetch/fetchDerivedPriceData.ts
  packages/pools/package.json
  packages/smart-router/evm/constants/common.ts
  packages/smart-router/evm/constants/exchange.ts
  packages/smart-router/evm/constants/gasModel/index.ts
  packages/smart-router/evm/constants/multicall.ts
  packages/smart-router/evm/constants/v3.ts
  packages/smart-router/evm/v3-router/providers/multicallSwapProvider.ts
  packages/smart-router/evm/v3-router/providers/onChainQuoteProvider.ts
  packages/swap-sdk/src/constants.ts
  packages/tokens/package.json
  packages/tokens/src/534351.ts
  packages/tokens/src/5611.ts
  packages/tokens/src/84531.ts
  packages/tokens/src/common.ts
  packages/tokens/src/helpers.ts
  packages/tokens/src/index.ts
  packages/tokens/tsconfig.json
  packages/uikit/package.json
  packages/utils/enumValues.ts
  packages/v3-sdk/src/constants.ts
  packages/wagmi/connectors/blocto/blocto.ts
  packages/wagmi/connectors/trustWallet/trustWallet.ts
  packages/wagmi/package.json
  packages/wagmi/src/hooks/useSignMessage.ts
  pnpm-lock.yaml
Labels: size/XXL

#7618 fix: combineMap
  apps/web/src/components/NetworkSwitcher.tsx
  apps/web/src/config/chains.ts
  apps/web/src/config/constants/contracts.ts
  apps/web/src/state/lists/hooks.ts
Labels: size/S

#7622 feat: Add testnet subgraph
  apis/routing/src/constants.ts
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/state/swap/fetch/fetchDerivedPriceData.ts
  apps/web/src/utils/graphql.ts
Labels: size/S

#7615 feat(Buy Crypto): Remove duplicate code
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/pages/buy-crypto/index.tsx
  apps/web/src/views/BuyCrypto/components/NewIcon.tsx
  apps/web/src/views/BuyCrypto/constants.ts
Labels: size/S, automerge

#7616 feat(Buy Crypto): Change to ENV
  apps/web/src/components/FiatOnRampModal/FiatOnRampModal.tsx
  apps/web/src/state/buyCrypto/hooks.ts
  apps/web/src/views/BuyCrypto/components/FiatOnRampSearchModal/constants.ts
  apps/web/src/views/BuyCrypto/containers/BuyCryptoForm.tsx
  apps/web/src/views/BuyCrypto/hooks/useProviderQuotes.ts
Labels: size/S, automerge

#7623 chore: list RPL pool on eth
  packages/pools/src/constants/pools/1.ts
Labels: size/XS

#7624 chore: list zksync farm
  packages/farms/constants/324.ts
Labels: size/XS

#7625 chore: list bsc farms and pool
  packages/farms/constants/56.ts
  packages/pools/src/constants/pools/56.ts
  packages/tokens/src/56.ts
Labels: size/M

#7606 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#7577 feat: Add Online Store
  packages/localization/src/config/translations.json
  packages/uikit/src/widgets/Menu/components/footerConfig.ts
Labels: size/S, automerge

#7619 perf: Memoize token info data
  apps/web/src/hooks/v3/usePairTokensPrice.ts
  apps/web/src/views/V3Info/hooks/index.ts
Labels: size/M

#7628 chore: Pools package release
  .changeset/polite-bags-swim.md
  apps/web/next.config.mjs
  packages/pools/index.ts
  packages/pools/package.json
  packages/pools/src/queries/fetchUserIfo.ts
  packages/pools/src/types.ts
  packages/pools/tsconfig.json
  packages/pools/tsup.config.ts
  pnpm-lock.yaml
Labels: size/L

#7631 fix: Swap toggle chart triggers effect on each render
  apps/web/src/views/Swap/index.tsx
Labels: size/XS

#7637 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#7636 chore: Prepare for next ifo
  apps/web/src/config/constants/ifo.ts
Labels: size/XS

#7635 fix: Handle wrapped token info on swap detail modal
  apps/web/src/views/Swap/MMLinkPools/components/TransactionConfirmSwapContent.tsx
  apps/web/src/views/Swap/V3Swap/components/TransactionConfirmSwapContent.tsx
  apps/web/src/views/Swap/components/SwapModalHeader.tsx
Labels: size/S

#7547 feat: Linea
  .changeset/wild-insects-fetch.md
  apis/routing/src/constants.ts
  apps/aptos/components/NetworkSwitcher.tsx
  apps/web/src/components/NetworkSwitcher.tsx
  apps/web/src/config/chains.ts
  apps/web/src/config/constants/contracts.ts
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/config/constants/exchange.ts
  apps/web/src/config/constants/lists.ts
  apps/web/src/config/constants/tokenLists/pancake-default.tokenlist.json
  apps/web/src/config/nodes.ts
  apps/web/src/config/pools.ts
  apps/web/src/state/swap/fetch/fetchDerivedPriceData.ts
  apps/web/src/utils/graphql.ts
  packages/smart-router/evm/constants/common.ts
  packages/smart-router/evm/constants/exchange.ts
  packages/smart-router/evm/constants/gasModel/index.ts
  packages/smart-router/evm/constants/multicall.ts
  packages/smart-router/evm/constants/v3.ts
  packages/smart-router/evm/v3-router/providers/multicallSwapProvider.ts
  packages/smart-router/evm/v3-router/providers/onChainQuoteProvider.ts
  packages/swap-sdk/src/constants.ts
  packages/tokens/src/59144.ts
  packages/tokens/src/common.ts
  packages/tokens/src/index.ts
  packages/uikit/src/components/CurrencyLogo/utils.ts
  packages/v3-sdk/src/constants.ts
Labels: size/L

#7597 chore: update RPG and MIX token info
  apps/web/src/config/__tests__/tokens.test.ts
  packages/pools/src/constants/pools/56.ts
  packages/tokens/src/56.ts
Labels: size/M

#7639 chore: Linea Banner
  apps/web/src/views/Home/components/Banners/LineaBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  apps/web/src/views/Home/components/Banners/images/index.ts
  apps/web/src/views/Home/components/Banners/images/linea-bg-mobile.png
  apps/web/src/views/Home/components/Banners/images/linea-bg.png
  apps/web/src/views/Home/components/Banners/images/linea-bunny-mobile.png
  apps/web/src/views/Home/components/Banners/images/linea-bunny.png
  apps/web/src/views/Home/components/Banners/images/linea-logo.png
  packages/localization/src/config/translations.json
Labels: size/L

#7640 perf: Use account instead of full web3 react hook
  apps/web/src/hooks/v3/useDerivedV3BurnInfo.ts
  apps/web/src/hooks/v3/useV3DerivedInfo.ts
  apps/web/src/views/Farms/components/YieldBooster/components/bCakeV3/StatusView.tsx
  apps/web/src/views/Farms/components/YieldBooster/hooks/bCakeV3/useBoostStatus.ts
  apps/web/src/views/Swap/V3Swap/containers/FormMain.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useSwapInputError.ts
  apps/web/src/views/TradingReward/components/Leaderboard/MyRank.tsx
Labels: size/S

#7641 chore: fix linea banner details
  apps/web/src/views/Home/components/Banners/LineaBanner.tsx
Labels: size/XS

#7646 feat: Customized v3 pool fallbacks and tvl references
  .changeset/stupid-walls-cheer.md
  packages/smart-router/evm/v3-router/providers/poolProviders/README.md
  packages/smart-router/evm/v3-router/providers/poolProviders/getV3CandidatePools.ts
Labels: size/L

#7649 chore: Remove invalid dependency
  .changeset/hip-eggs-tie.md
  packages/tokens/package.json
  packages/tokens/tsup.config.ts
Labels: size/XS

#7650 Revert "chore: Remove invalid dependency"
  .changeset/hip-eggs-tie.md
  packages/tokens/package.json
  packages/tokens/tsup.config.ts
Labels: size/XS

#7651 chore: Remove invalid dependency
  .changeset/hip-eggs-tie.md
  packages/tokens/package.json
  packages/tokens/tsup.config.ts
  pnpm-lock.yaml
Labels: size/S

#7653 chore: Export provider functions from smart router
  .changeset/lovely-horses-glow.md
  packages/smart-router/evm/v3-router/smartRouter.ts
Labels: size/S

#7656 docs: Fix incorrect import statement
  packages/smart-router/evm/v3-router/providers/poolProviders/README.md
Labels: size/S

#7657 feat: Customizable v2 pool provider
  packages/smart-router/evm/utils/withFallback.ts
  packages/smart-router/evm/v3-router/providers/getCommonTokenPrices.ts
  packages/smart-router/evm/v3-router/providers/index.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/README.md
  packages/smart-router/evm/v3-router/providers/poolProviders/getCandidatePools.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/getV2CandidatePools.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/getV3CandidatePools.ts
Labels: size/L

#7658 chore: Bump smart router pkg version
  .changeset/tough-tomatoes-move.md
Labels: size/XS

#7665 fix: Missing translation in buy crypto
  apps/web/src/views/BuyCrypto/components/AccordianDropdown/AccordianItem.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#7660 fix: (buy-crypto): End time of moonpay zero fee
  apps/web/src/components/FiatOnRampModal/FiatOnRampModal.tsx
  apps/web/src/state/buyCrypto/hooks.ts
  apps/web/src/views/BuyCrypto/Icons/index.tsx
  apps/web/src/views/BuyCrypto/components/AccordionDropdown/Accordion.tsx
  apps/web/src/views/BuyCrypto/components/AccordionDropdown/AccordionItem.tsx
  apps/web/src/views/BuyCrypto/components/FAQ.tsx
  apps/web/src/views/BuyCrypto/constants.ts
  apps/web/src/views/BuyCrypto/containers/CryptoQuoteForm.tsx
  apps/web/src/views/BuyCrypto/hooks/usePriceQuoter.ts
  apps/web/src/views/BuyCrypto/hooks/useProviderQuotes.ts
  apps/web/src/views/BuyCrypto/index.tsx
  apps/web/src/views/BuyCrypto/styles.tsx
  apps/web/src/views/BuyCrypto/types.ts
Labels: size/M

#7672 chore: Add missing subgraphs for routing api
  apis/routing/src/provider.ts
Labels: size/XS

#7664 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#7566 feat: Add Arbitrum Pool
  apps/web/src/config/abi/tokenApl.ts
  apps/web/src/config/constants/priceHelperLps/index.ts
  apps/web/src/config/constants/priceHelperLps/pools/42161.ts
  apps/web/src/config/constants/priceHelperLps/pools/421613.ts
  apps/web/src/config/constants/supportChains.ts
  apps/web/src/config/constants/tokenLists/pancake-default.tokenlist.json
  apps/web/src/state/pools/index.ts
  apps/web/src/utils/fetchTokenAplPrice.ts
  apps/web/src/views/Pools/components/PoolCard/CardActions/index.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
  packages/pools/src/constants/contracts.ts
  packages/pools/src/constants/pools/42161.ts
  packages/pools/src/constants/pools/421613.ts
  packages/pools/src/constants/pools/index.ts
  packages/pools/src/constants/supportedChains.ts
  packages/tokens/src/42161.ts
  packages/tokens/src/421613.ts
  packages/tokens/src/common.ts
  packages/utils/llamaPrice.ts
Labels: size/XXL, automerge

#7674 feat: Bump pool packages version
  .changeset/lovely-suns-float.md
Labels: size/XS

#7676 feat: Add Liquid Staking Supported Chains
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/config/constants/supportChains.ts
  apps/web/src/pages/liquid-staking/[contract].tsx
  apps/web/src/pages/liquid-staking/index.tsx
Labels: size/S, automerge

#7677 chore: Update Perpetual URL
  apps/web/src/utils/getPerpetualUrl.ts
Labels: size/S, automerge

#7679 fix: Invalid apr for arb pool
  apps/web/src/state/pools/index.ts
Labels: size/S

#7680 fix: Remove gas limit and price on stake call
  apps/web/src/views/Pools/hooks/useStakePool.ts
  apps/web/src/views/Pools/hooks/useUnstakePool.ts
Labels: size/M

#7684 fix: Invalid routing on zksync era
  packages/smart-router/evm/constants/multicall.ts
Labels: size/S

#7685 chore: list tes farm on zksync
  packages/farms/constants/324.ts
  packages/tokens/src/324.ts
Labels: size/S

#7379 fix: (liquidity): Add liquidity 0.1 fee step counters not working
  apps/web/src/components/LiquidityChartRangeInput/Area.tsx
  apps/web/src/components/LiquidityChartRangeInput/AxisBottom.tsx
  apps/web/src/components/LiquidityChartRangeInput/Brush.tsx
  apps/web/src/components/LiquidityChartRangeInput/Chart.tsx
  apps/web/src/components/LiquidityChartRangeInput/Line.tsx
  apps/web/src/components/LiquidityChartRangeInput/Loader.tsx
  apps/web/src/components/LiquidityChartRangeInput/Zoom.tsx
  apps/web/src/components/LiquidityChartRangeInput/index.tsx
  apps/web/src/components/LiquidityChartRangeInput/svg.tsx
  apps/web/src/components/LiquidityChartRangeInput/types.ts
  apps/web/src/hooks/v3/useV3DerivedInfo.ts
  apps/web/src/hooks/v3/utils/index.ts
  apps/web/src/views/AddLiquidityV3/Migrate.tsx
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V2FormView.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/RangeSelector.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/StepCounter.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/form/actions.ts
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/form/hooks/useRangeHopCallbacks.ts
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/form/hooks/useV3MintActionHandlers.ts
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/form/reducer.ts
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
  apps/web/src/views/AddLiquidityV3/hooks/useDensityChartData.ts
  apps/web/src/views/AddLiquidityV3/types.ts
  apps/web/src/views/Migration/components/v3/Step3.tsx
  packages/uikit/src/components/LiquidityChartRangeInput/LiquidityChartRangeInput.tsx
  packages/uikit/src/components/LiquidityChartRangeInput/index.stories.tsx
  packages/uikit/src/components/LiquidityChartRangeInput/index.tsx
  packages/uikit/src/components/LiquidityChartRangeInput/types.ts
  packages/uikit/src/widgets/RoiCalculator/RoiCalculator.tsx
  packages/uikit/src/widgets/RoiCalculator/hooks/usePriceRange.ts
Labels: size/XXL

#7696 chore: Remove huge alp abi
  apps/web/src/config/abi/tokenApl.ts
  apps/web/src/utils/fetchTokenAplPrice.ts
Labels: size/XXL

#7690 perf: Use specific account chain hooks instead of web3react hook
  apps/web/src/hooks/useDomain.ts
  apps/web/src/pages/liquidity/index.tsx
  apps/web/src/views/Farms/components/YieldBooster/components/bCakeV3/BCakeBoosterCard.tsx
  apps/web/src/views/Farms/components/YieldBooster/hooks/bCakeV3/useBCakeV3Info.ts
  apps/web/src/views/Pools/components/RevenueSharing/BenefitsModal/ClaimButton.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/index.tsx
Labels: size/S

#7686 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/es-ES.json
  locales/hu-HU.json
  locales/ko-KR.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/sv-SE.json
  locales/tr-TR.json
  locales/zh-CN.json
Labels: size/XXL

#7691 feat(Bridge): Bump x-pancakeswap-widget
  apps/bridge/components/layerZero/config.ts
Labels: size/XS, automerge

#7687 chore: support linea info page
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/state/info/constant.ts
  apps/web/src/state/info/hooks.ts
  apps/web/src/utils/getTokenLogoURL.ts
  apps/web/src/utils/graphql.ts
  apps/web/src/views/Info/components/InfoNav/index.tsx
  apps/web/src/views/V3Info/components/Layout/InfoNav.tsx
  apps/web/src/views/V3Info/constants.ts
Labels: size/M

#7697 chore: launch farm on linea
  apis/farms/.dev.vars
  apis/farms/src/bindings.d.ts
  apis/farms/src/lpApr.ts
  apis/farms/src/provider.ts
  apis/farms/src/v3.ts
  apis/farms/wrangler.toml
  apps/web/src/components/TokenImage/index.tsx
  apps/web/src/config/constants/supportChains.ts
  apps/web/src/config/constants/tokenLists/pancake-default.tokenlist.json
  apps/web/src/views/TradingReward/config/pairs/index.tsx
  packages/farms/constants/59144.ts
  packages/farms/constants/common/index.ts
  packages/farms/constants/priceHelperLps/59144.ts
  packages/farms/constants/priceHelperLps/getFarmsPriceHelperLpFiles.ts
  packages/farms/constants/v3/index.ts
  packages/farms/src/const.ts
  packages/farms/tests/v3.test.ts
  packages/tokens/src/59144.ts
  packages/tokens/src/common.ts
Labels: size/L

#7698 chore: list axl pool on bsc
  packages/pools/src/constants/pools/56.ts
Labels: size/XS

#7704 chore: Show minutes countdown
  apps/web/src/views/BuyCrypto/components/AccordionDropdown/AccordionItem.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#7701 chore: New Crowdin updates
  locales/de-DE.json
  locales/el-GR.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fr-FR.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pt-BR.json
  locales/ta-IN.json
  locales/uk-UA.json
  locales/zh-TW.json
Labels: size/XXL

#7700 fix: Wrong url when switching to v3 from v2 add liquidity
  apps/web/src/views/AddLiquidityV3/index.tsx
  apps/web/src/views/RemoveLiquidity/index.tsx
Labels: size/S

#7694 refactor: Remove unused zap from add/remove liquidity v2
  apps/web/src/components/CurrencyInputPanel/index.tsx
  apps/web/src/state/burn/hooks.ts
  apps/web/src/views/AddLiquidity/components/ConfirmZapInModal.tsx
  apps/web/src/views/AddLiquidity/components/ZapErrorMessage.tsx
  apps/web/src/views/RemoveLiquidity/index.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/widgets/Swap/CurrencyInputPanel.tsx
  packages/uikit/src/widgets/Swap/SwapWidget.css.ts
Labels: size/XL

#7683 fix: Cannot add v2 liquidity if pair has reserves without total supply
  apps/web/src/state/mint/hooks.ts
  apps/web/src/views/AddLiquidity/components/common.tsx
  apps/web/src/views/AddLiquidity/index.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V2FormView.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#7706 chore: list farms on zksync
  packages/farms/constants/324.ts
  packages/tokens/src/324.ts
Labels: size/M

#7707 chore: list farms on abritrum
  packages/farms/constants/42161.ts
  packages/tokens/src/42161.ts
Labels: size/S

#7708 chore: remove moon pay banner
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/XS

#7712 fix: Base v2 factory address
  .changeset/four-moons-camp.md
  packages/swap-sdk/src/constants.ts
Labels: size/S

#7711 chore: base banner
  apps/web/src/views/Home/components/Banners/BaseBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  apps/web/src/views/Home/components/Banners/images/base-bg-mobile.png
  apps/web/src/views/Home/components/Banners/images/base-bg.png
  apps/web/src/views/Home/components/Banners/images/base-bunny.png
  apps/web/src/views/Home/components/Banners/images/base-moon.png
  apps/web/src/views/Home/components/Banners/images/base-tree.png
  apps/web/src/views/Home/components/Banners/images/index.ts
  packages/localization/src/config/translations.json
Labels: size/L
