Repository pancakeswap/pancake-frontend, pull requests merged in 2023-06, with the labels that each got.

#7030 chore: Whitelist reth in route quoting
  packages/smart-router/evm/constants/exchange.ts
Labels: size/XS

#7024 chore: Move finished pools
  packages/pools/src/constants/pools/56.ts
Labels: size/S

#7008 refactor: refactor Chainlink oracle contract imports and typings
  .gitignore
  apis/farms/package.json
  apps/bridge/components/stargate/config.ts
  apps/bridge/components/stargate/network.ts
  apps/bridge/package.json
  apps/bridge/tsconfig.json
  apps/web/package.json
  apps/web/src/utils/calls/estimateGas.ts
  apps/web/src/utils/contractHelpers.ts
  apps/web/src/views/AddLiquidityV3/Migrate.tsx
  apps/web/src/views/Predictions/components/ChainlinkChart.tsx
  apps/web/src/views/Predictions/hooks/usePollOraclePrice.ts
  packages/farms/package.json
  packages/pools/package.json
  packages/smart-router/package.json
  packages/swap-sdk/package.json
  packages/uikit/package.json
  packages/utils/package.json
  packages/v3-sdk/package.json
  packages/wagmi/package.json
  pnpm-lock.yaml
  scripts/package.json
  turbo.json
Labels: size/L

#7025 chore: Remove masterchefv1 contract
  apps/web/src/config/abi/masterchefV1.ts
  apps/web/src/hooks/useContract.ts
  apps/web/src/utils/addressHelpers.ts
  apps/web/src/utils/contractHelpers.ts
Labels: size/XL

#7001 fix: (liquidity): Quick range input stays highlighted when range changes
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
Labels: size/S

#7027 chore: add game category to user menu
  apps/web/src/__tests__/utils/utils.test.ts
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/components/Menu/hooks/useMenuItems.ts
  packages/localization/src/config/translations.json
  packages/uikit/package.json
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/components/DropdownMenu/DropdownMenu.tsx
  packages/uikit/src/components/MenuItem/styles.tsx
  packages/uikit/src/components/Svg/Icons/PancakeProtector.tsx
  packages/uikit/src/components/Svg/index.tsx
Labels: size/L

#7033 feat(Bridge): Axelar router
  apps/bridge/components/Menu.tsx
  apps/bridge/pages/axelar.tsx
Labels: size/L, automerge

#7034 chore: add uns banner
  apps/web/src/views/Home/components/Banners/UnsDomainBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#7039 chore: Bump viem
  apis/farms/package.json
  apps/bridge/package.json
  apps/web/package.json
  apps/web/src/hooks/useCallWithGasPrice.ts
  apps/web/src/hooks/useContract.ts
  apps/web/src/state/multicall/hooks.ts
  apps/web/src/utils/calls/estimateGas.ts
  apps/web/src/utils/contractHelpers.ts
  packages/farms/package.json
  packages/pools/package.json
  packages/smart-router/evm/v3-router/providers/multicallProvider.ts
  packages/smart-router/evm/v3-router/providers/onChainQuoteProvider.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/onChainPoolProviders.ts
  packages/smart-router/package.json
  packages/swap-sdk/package.json
  packages/uikit/package.json
  packages/utils/package.json
  packages/v3-sdk/package.json
  packages/wagmi/package.json
  pnpm-lock.yaml
  scripts/package.json
  turbo.json
Labels: size/L

#7031 feat: Add pool fallback api endpoint
  apis/routing/package.json
  apis/routing/src/bindings.d.ts
  apis/routing/src/constants.ts
  apis/routing/src/index.ts
  apis/routing/src/pools.ts
  apis/routing/src/provider.ts
  apis/routing/src/subgraphPoolBackup.ts
  apis/routing/wrangler.toml
  packages/smart-router/evm/v3-router/providers/poolProviders/getV3CandidatePools.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/subgraphPoolProviders.ts
  packages/smart-router/evm/v3-router/schema.ts
  packages/smart-router/evm/v3-router/smartRouter.ts
  pnpm-lock.yaml
Labels: size/XL

#7042 feat: Add v2 pool fallback api
  apis/routing/package.json
  apps/web/src/hooks/useV2Pools.ts
  packages/smart-router/evm/constants/common.ts
  packages/smart-router/evm/utils/withFallback.ts
  packages/smart-router/evm/v3-router/providers/getCommonTokenPrices.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/getV2CandidatePools.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/getV3CandidatePools.ts
  pnpm-lock.yaml
Labels: size/L

#7041 chore: Bump viem
  apis/farms/package.json
  apis/routing/package.json
  apps/bridge/package.json
  apps/web/package.json
  packages/farms/package.json
  packages/pools/package.json
  packages/smart-router/package.json
  packages/swap-sdk/package.json
  packages/uikit/package.json
  packages/utils/package.json
  packages/v3-sdk/package.json
  packages/wagmi/package.json
  pnpm-lock.yaml
  scripts/package.json
Labels: size/L

#7046 chore: Bump up swiper
  apps/aptos/package.json
  apps/blog/package.json
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/M

#7050 fix: Chainlink chart crash
  apps/web/src/views/Predictions/components/ChainlinkChart.tsx
Labels: size/S

#7051 chore: update uns banner copywriting
  apps/web/src/views/Home/components/Banners/UnsDomainBanner.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#7053 fix: Disclaimers disappear when global claim check ondismiss
  apps/web/src/components/GlobalCheckClaimStatus/index.tsx
  packages/uikit/src/widgets/Modal/useModal.ts
Labels: size/S

#7052 fix: Unrecognized prop warning
  apps/web/src/components/DisclaimerModal/index.tsx
  packages/uikit/src/widgets/Farm/components/FarmV3Card/ViewAllFarmModal.tsx
Labels: size/S

#7058 chore: Add default ttl for l2 deadline
  apps/web/src/config/chains.ts
  apps/web/src/config/constants/index.ts
  apps/web/src/hooks/useTransactionDeadline.ts
Labels: size/S

#7060 feat(Bridge): Update url
  apps/bridge/components/Menu.tsx
  apps/bridge/pages/cake.tsx
  apps/bridge/pages/index.tsx
Labels: size/L, automerge

#7066 chore: Update typescript
  .vscode/settings.json
  apis/farms/package.json
  apis/proxy-worker/package.json
  apis/routing/package.json
  apps/aptos/package.json
  apps/blog/package.json
  apps/bridge/package.json
  apps/e2e/package.json
  apps/web/package.json
  apps/web/src/views/Nft/market/hooks/useGetCollectionDistribution.tsx
  apps/web/src/views/TradingCompetition/components/PrizesInfo/PrizesGrid/PrizesGrid.tsx
  apps/web/src/views/TradingCompetition/easter/components/PrizesInfo/PrizesGrid/EasterPrizesGrid.tsx
  package.json
  packages/pools/package.json
  packages/smart-router/evm/v3-router/providers/onChainQuoteProvider.ts
  packages/smart-router/legacy-router/onchain/getPairs.ts
  packages/smart-router/package.json
  packages/v3-sdk/package.json
  pnpm-lock.yaml
Labels: size/XL

#7067 chore: Use custom domain for routing api
  packages/smart-router/evm/v3-router/providers/poolProviders/getV3CandidatePools.ts
Labels: size/XS

#7043 refactor: Remove unused farm hooks
  apps/web/src/state/farms/hooks.ts
  apps/web/src/views/Farms/hooks/useBCakeProxyContractAddress.ts
Labels: size/M

#7068 fix: wagmi bigint on cache
  apps/aptos/pages/_app.tsx
  apps/web/src/pages/_app.tsx
  apps/web/src/utils/wagmi.ts
  packages/uikit/src/widgets/Modal/useModal.ts
Labels: size/S, automerge

#7069 chore: hardcode info for farm auction v3
  apps/web/src/views/FarmAuction/components/AuctionDetailsCard/AuctionFooter.tsx
  apps/web/src/views/FarmAuction/components/AuctionHistory.tsx
  apps/web/src/views/FarmAuction/components/AuctionLeaderboard/AuctionLeaderboardTable.tsx
  apps/web/src/views/FarmAuction/components/AuctionLeaderboard/index.tsx
  apps/web/src/views/FarmAuction/components/CongratulationsCard.tsx
  apps/web/src/views/FarmAuction/constants.ts
Labels: size/M

#7064 fix: (trading-reward): Active reward campaigns not filtered correctly
  apps/web/src/components/Menu/hooks/useTradingRewardStatus.ts
  apps/web/src/views/Swap/hooks/useTradingRewardTokenList.tsx
  apps/web/src/views/TradingReward/components/CurrentRewardPool.tsx
  apps/web/src/views/TradingReward/components/YourTradingReward/CurrentPeriod.tsx
  apps/web/src/views/TradingReward/components/YourTradingReward/NoCakeLockedOrExtendLock.tsx
  apps/web/src/views/TradingReward/components/YourTradingReward/TotalPeriod.tsx
  apps/web/src/views/TradingReward/index.tsx
Labels: size/S

#6946 fix: Migrate bugs
  apps/web/src/hooks/useTokenBalance.ts
  apps/web/src/pages/v2/pair/[[...currency]].tsx
  apps/web/src/views/AddLiquidityV3/Migrate.tsx
Labels: size/L

#7076 chore: Bump turbo
  package.json
  pnpm-lock.yaml
Labels: size/M

#7078 chore: sort banners
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/XS

#7079 chore: whitelist Farm auction
  apps/web/src/config/constants/farmAuctions.ts
Labels: size/S

#7082 chore: Update aog farm
  apps/web/src/config/constants/farmAuctions.ts
Labels: size/XS

#7032 chore: IFO flatfee rebase
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
  apps/web/src/views/Ifos/hooks/v3/useGetPublicIfoData.ts
  apps/web/src/views/Ifos/types.ts
Labels: size/L

#7077 chore: Bump viem and wagmi
  apis/farms/package.json
  apis/routing/package.json
  apis/routing/src/provider.ts
  apps/bridge/package.json
  apps/web/package.json
  apps/web/src/hooks/useContract.ts
  apps/web/src/state/user/hooks/index.tsx
  apps/web/src/utils/contractHelpers.ts
  packages/farms/package.json
  packages/pools/package.json
  packages/smart-router/package.json
  packages/swap-sdk/package.json
  packages/uikit/package.json
  packages/utils/package.json
  packages/v3-sdk/package.json
  packages/wagmi/package.json
  pnpm-lock.yaml
  scripts/package.json
Labels: size/XL

#7086 fix: Unsafe optional chaining
  apps/web/src/state/info/queries/pools/chartData.ts
Labels: size/S

#7090 chore: Update text
  packages/localization/src/config/translations.json
  packages/uikit/src/widgets/Menu/components/footerConfig.ts
Labels: size/XS

#7085 fix: Identical conditions
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/views/Ifos/hooks/v2/useGetPublicIfoData.ts
  apps/web/src/views/Ifos/hooks/v3/useGetPublicIfoData.ts
Labels: size/XS

#6898 feat: Add default apr to add liquidity
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/form/hooks/useV3MintActionHandlers.ts
  packages/uikit/src/widgets/RoiCalculator/RoiCalculator.tsx
  packages/uikit/src/widgets/RoiCalculator/utils/getTokenAmountsFromDepositUsd.ts
  packages/utils/formatFractions.ts
Labels: size/M

#7089 fix: (trading-reward): Show unlocks in 0 seconds when pool position is unlocked
  apps/web/src/views/TradingReward/components/Banner.tsx
  apps/web/src/views/TradingReward/components/YourTradingReward/NoCakeLockedOrExtendLock.tsx
Labels: size/M

#7075 feat: Add US warning modal for IFO
  apps/web/src/components/Menu/index.tsx
  apps/web/src/components/Modal/USCitizenConfirmModal.tsx
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/Congratulations.tsx
  apps/web/src/views/Home/components/Banners/PerpetualApolloXCampaignBanner.tsx
  apps/web/src/views/Home/components/Banners/PerpetualBanner.tsx
  apps/web/src/views/Ifos/index.tsx
  packages/localization/src/config/translations.json
Labels: size/M, automerge

#7093 chore: list farm auction #34 winner
  packages/farms/constants/56.ts
  packages/farms/src/types.ts
  packages/tokens/src/56.ts
Labels: size/M

#7092 feat: US citizen
  apps/web/src/components/Menu/hooks/useMenuItems.ts
  apps/web/src/components/Menu/index.tsx
  apps/web/src/components/Modal/USCitizenConfirmModal.tsx
  apps/web/src/hooks/useUserIsUsCitizenAcknowledgement.ts
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/Congratulations.tsx
  apps/web/src/views/Home/components/Banners/PerpetualApolloXCampaignBanner.tsx
  apps/web/src/views/Home/components/Banners/PerpetualBanner.tsx
  apps/web/src/views/Ifos/index.tsx
Labels: size/M

#7094 chore: support community tag on v3 farm
  apps/web/src/views/Farms/components/FarmCard/CardHeading.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3Card.tsx
  apps/web/src/views/Farms/components/FarmTable/FarmTable.tsx
  apps/web/src/views/Farms/components/FarmTable/Row.tsx
  packages/uikit/src/widgets/Farm/types.ts
Labels: size/S

#7036 chore: Bump up pnpm version for workflows
  package.json
  pnpm-lock.yaml
Labels: size/XS

#7091 chore: Update vitest and add codecov
  .github/workflows/unitTests.yml
  apps/aptos/package.json
  apps/blog/package.json
  apps/bridge/package.json
  apps/web/.gitignore
  apps/web/package.json
  package.json
  packages/awgmi/package.json
  packages/next-config/package.json
  packages/pools/package.json
  packages/swap-sdk-core/package.json
  packages/uikit/package.json
  packages/utils/package.json
  packages/v3-sdk/package.json
  packages/wagmi/connectors/blocto/blocto.ts
  packages/wagmi/package.json
  pnpm-lock.yaml
Labels: size/XXL

#6829 perf: Don't fetch v3 claim jsons upfront
  apps/web/src/components/GlobalCheckClaimStatus/V3AirdropModal.tsx
  apps/web/src/components/GlobalCheckClaimStatus/index.tsx
  apps/web/src/hooks/useSWRContract.ts
Labels: size/L

#7072 fix: (liquidity): Farm hint shown when another account active
  apps/web/src/pages/liquidity/[tokenId].tsx
Labels: size/XS

#7096 chore: Move finished pools
  packages/pools/src/constants/pools/56.ts
Labels: size/S

#7095 chore(Farm): Adjustment FarmAuctionTag position
  apps/web/src/views/Farms/components/FarmTable/Row.tsx
  packages/uikit/src/widgets/Farm/components/Tags/index.tsx
Labels: size/M

#7102 revert: "chore: Update vitest and add codecov"
  .github/workflows/unitTests.yml
  apps/aptos/package.json
  apps/blog/package.json
  apps/bridge/package.json
  apps/web/.gitignore
  apps/web/package.json
  package.json
  packages/awgmi/package.json
  packages/next-config/package.json
  packages/pools/package.json
  packages/swap-sdk-core/package.json
  packages/uikit/package.json
  packages/utils/package.json
  packages/v3-sdk/package.json
  packages/wagmi/connectors/blocto/blocto.ts
  packages/wagmi/package.json
  pnpm-lock.yaml
Labels: size/XXL

#7100 chore: Clean up sonar report
  .github/workflows/lint.yml
  .github/workflows/testConfig.yml
  .github/workflows/unitTests.yml
  .sonarcloud.properties
  apps/web/.eslintrc
  apps/web/src/views/Swap/MMLinkPools/utils/exchange.ts
Labels: size/S

#7022 chore(TradingReward): Adjust button align center on mobile
  apps/web/src/views/TradingReward/components/Banner.tsx
Labels: size/XS

#7063 feat: (info): Use lightweight charts in v2
  apps/web/src/views/Info/components/InfoCharts/BarChart/index.tsx
  apps/web/src/views/Info/components/InfoCharts/LineChart/index.tsx
Labels: size/L

#7103 chore: remove uns banner
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/XS

#7109 fix: Crash when single asset deposit
  .changeset/short-news-watch.md
  packages/v3-sdk/src/utils/feeCalculator.ts
Labels: size/S

#7115 fix: Affilaite Problem
  apps/web/src/views/AffiliatesProgram/components/Dashboard/Reward/SingleHistoricalReward.tsx
Labels: size/XS

#7116 feat: List AXL pool
  packages/farms/constants/1.ts
  packages/farms/constants/56.ts
  packages/pools/src/constants/pools/56.ts
Labels: size/M, automerge

#7117 fix: Config unit test not running
  package.json
Labels: size/XS

#7121 fix: Return type of farm actions props
  apps/web/src/views/Farms/hooks/v3/useFarmV3Actions.tsx
Labels: size/S

#7120 fix: Prediction text sonar warnings
  apps/web/src/__tests__/state/predictions/helpers.test.ts
Labels: size/S

#7119 fix: Apr shows value other than 0 when position is inactive
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/utils/isPoolTickInRange.ts
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
Labels: size/S

#7055 feat: Use lightweight charts in prediction chainlink
  apps/web/src/views/Predictions/components/ChainlinkChart.tsx
Labels: size/L

#7125 feat(Affiliate Program): Add Agreement
  apps/web/src/pages/affiliates-program/agreement.tsx
  apps/web/src/pages/affiliates-program/us-agreement.tsx
  apps/web/src/pages/terms-of-service.tsx
Labels: size/XL

#7129 chore: viem version and packages publish
  .changeset/warm-pillows-dress.md
  apis/farms/package.json
  apis/routing/package.json
  apps/bridge/package.json
  apps/web/package.json
  apps/web/src/hooks/useAccountEventListener.ts
  packages/farms/package.json
  packages/pools/package.json
  packages/smart-router/package.json
  packages/swap-sdk/package.json
  packages/uikit/package.json
  packages/utils/package.json
  packages/v3-sdk/package.json
  packages/wagmi/connectors/blocto/blocto.ts
  packages/wagmi/package.json
  pnpm-lock.yaml
  scripts/package.json
Labels: size/XL

#7133 fix: Latest price from chart not updating when changing tokens
  apps/web/src/state/swap/hooks.ts
  packages/uikit/src/components/Chart/PairPriceChart.tsx
Labels: size/S

#7137 fix: Invalid quote when pool liquidity is not enough
  packages/smart-router/evm/v3-router/providers/offChainQuoteProvider.ts
Labels: size/XS

#7138 fix: Not using the best amm quote when swap with exact output
  apps/web/src/hooks/useBestAMMTrade.ts
  packages/smart-router/evm/v3-router/utils/pool.ts
Labels: size/S

#7130 style: Error message text style
  packages/uikit/src/__tests__/components/alert.test.tsx
  packages/uikit/src/components/Alert/Alert.tsx
Labels: Delayed Release, size/XS

#7140 fix: Page crash
  pnpm-lock.yaml
Labels: size/M

#7141 chore: Add second hop config for wbeth
  packages/smart-router/evm/v3-router/constants/poolSelector.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/poolTvlSelectors.ts
Labels: size/S

#7143 fix: Don't return old trade when currency change
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/state/swap/hooks.ts
Labels: size/S

#7142 chore: Remove chainlink round data crash workaround
  apps/web/src/views/Predictions/components/ChainlinkChart.tsx
Labels: size/S

#7144 feat: Update Telegram link
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/components/Footer/config.tsx
Labels: size/M, automerge

#7136 fix: Transaction updater not handling failed transactions
  apps/web/src/hooks/usePublicNodeWaitForTransaction.ts
  apps/web/src/state/transactions/updater.tsx
Labels: size/S

#7150 chore: Remove offchain quoting
  apps/web/src/hooks/useBestAMMTrade.ts
  packages/smart-router/evm/v3-router/functions/getBestRouteCombinationByQuotes.ts
Labels: size/M

#6989 feat: WalletConnect v2
  apps/web/src/components/ConnectWalletButton.tsx
  apps/web/src/config/chains.ts
  apps/web/src/config/wallet.ts
  apps/web/src/hooks/useSwitchNetwork.ts
  apps/web/src/utils/sentry.ts
  apps/web/src/utils/wagmi.ts
  apps/web/vitest.config.ts
  packages/ui-wallets/src/WalletModal.tsx
Labels: size/M

#7166 fix: tusd token test case
  apps/web/src/config/__tests__/tokens.test.ts
  packages/farms/constants/56.ts
  packages/pools/src/constants/pools/56.ts
  packages/tokens/src/56.ts
Labels: size/S

#7169 fix(Bridge): Fix menu highlight
  apps/bridge/components/Menu.tsx
Labels: size/XS

#7173 fix: Overflow in homepage in mobile
  apps/web/src/views/Home/components/Banners/PancakeProtectorBanner.tsx
Labels: size/XS

#7155 chore: Remove to locale string from numbers
  apps/web/src/views/FarmAuction/components/AuctionDetailsCard/index.tsx
  apps/web/src/views/FarmAuction/components/AuctionLeaderboard/AuctionLeaderboardTable.tsx
  apps/web/src/views/FarmAuction/components/CongratulationsCard.tsx
  apps/web/src/views/FarmAuction/components/PlaceBidModal.tsx
  apps/web/src/views/FarmAuction/components/ReclaimBidCard.tsx
  apps/web/src/views/Lottery/components/PreviousRoundCard/FooterExpanded.tsx
  apps/web/src/views/Migration/components/Farm/Cells/Earned.tsx
  apps/web/src/views/Pools/components/PoolStatsInfo.tsx
  apps/web/src/views/Pools/components/ProfileRequirementWarning.tsx
  apps/web/src/views/Predictions/Leaderboard/components/PreviousBetsTable.tsx
  apps/web/src/views/Predictions/Leaderboard/components/Results/DesktopRow.tsx
  apps/web/src/views/Predictions/Leaderboard/components/Results/MobileRow.tsx
  apps/web/src/views/Predictions/Leaderboard/components/Results/RankingCard.tsx
  apps/web/src/views/Predictions/Leaderboard/components/WalletStatsModal.tsx
  apps/web/src/views/Predictions/components/History/HistoricalBet.tsx
  apps/web/src/views/Profile/components/Achievements/AchievementCard.tsx
  apps/web/src/views/Profile/components/Achievements/AchievementRow/PointsLabel.tsx
  apps/web/src/views/ProfileCreation/TeamSelection.tsx
  apps/web/src/views/Teams/components/TeamListCard.tsx
  apps/web/src/views/TradingCompetition/components/ShareImageModal.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/Podium/useGetParticipants.ts
  apps/web/src/views/TradingCompetition/components/YourScore/CardUserInfo.tsx
  apps/web/src/views/Voting/Proposal/Votes.tsx
  packages/uikit/src/widgets/Farm/components/FarmTable/Earned.tsx
  packages/uikit/src/widgets/Farm/components/FarmTable/LpAmount.tsx
Labels: size/M

#7151 fix(Lottery): Fix enable button is displayed when don't input anything
  apps/web/src/views/Lottery/components/BuyTicketsModal/BuyTicketsModal.tsx
Labels: size/XS

#7158 fix: Sonar reliability issues
  packages/v3-sdk/src/entities/pool.test.ts
  packages/v3-sdk/src/entities/trade.test.ts
  scripts/updateAptosLpsAPR/index.ts
Labels: size/M

#7131 style: Fix NFT background image height
  apps/web/src/views/Nft/market/components/CollectibleCard/CollectionCard.tsx
Labels: size/S, automerge

#7149 chore: Reduce min bnb by tenth to show quick action buttons when amount is lower than 0.01 bnb
  apps/web/src/config/constants/exchange.ts
Labels: size/XS

#7180 fix: qa feedback
  apps/web/src/components/CurrencyInputPanel/index.tsx
  apps/web/src/components/SearchModal/CurrencyList.tsx
  apps/web/src/components/SearchModal/CurrencySearch.tsx
  apps/web/src/config/constants/tokenLists/pancake-supported-onramp-currency-list.json
  apps/web/src/views/BuyCrypto/containers/BuyCryptoForum.tsx
Labels: size/M

#7179 fix: Sonar security hotspot
  packages/utils/removeTrailingZeros.ts
Labels: size/XS

#6873 feat: bCake V3
  apps/web/src/config/abi/bCakeFarmBoosterV3.ts
  apps/web/src/config/constants/contracts.ts
  apps/web/src/config/constants/pools.tsx
  apps/web/src/config/index.ts
  apps/web/src/hooks/useContract.ts
  apps/web/src/state/farmsV3/hooks.ts
  apps/web/src/state/lists/hooks.ts
  apps/web/src/utils/addressHelpers.ts
  apps/web/src/utils/contractHelpers.ts
  apps/web/src/views/Farms/Farms.tsx
  apps/web/src/views/Farms/FarmsV3.tsx
  apps/web/src/views/Farms/components/FarmCard/CardActionsContainer.tsx
  apps/web/src/views/Farms/components/FarmCard/CardHeading.tsx
  apps/web/src/views/Farms/components/FarmCard/FarmCard.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3ApyButton.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3Card.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3CardList.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3StakeAndUnStake.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/SingleFarmV3Card.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/Farms/components/FarmTable/Row.tsx
  apps/web/src/views/Farms/components/FarmTypesFilter.tsx
  apps/web/src/views/Farms/components/YieldBooster/components/BCakeCalculator.tsx
  apps/web/src/views/Farms/components/YieldBooster/components/bCakeV3/BCakeBoosterCard.tsx
  apps/web/src/views/Farms/components/YieldBooster/components/bCakeV3/CardView.tsx
  apps/web/src/views/Farms/components/YieldBooster/components/bCakeV3/StatusView.tsx
  apps/web/src/views/Farms/components/YieldBooster/hooks/bCakeV3/multiplierAPI.ts
  apps/web/src/views/Farms/components/YieldBooster/hooks/bCakeV3/useBCakeV3Info.ts
  apps/web/src/views/Farms/components/YieldBooster/hooks/bCakeV3/useBoostBcakeV3.ts
  apps/web/src/views/Farms/components/YieldBooster/hooks/bCakeV3/useBoostStatus.ts
  apps/web/src/views/Farms/hooks/v3/useFarmV3Actions.tsx
  apps/web/src/views/Migration/components/v3/Step5.tsx
  packages/localization/src/config/translations.json
  packages/pools/src/constants/contracts.ts
  packages/pools/src/constants/pools/97.ts
  packages/tokens/src/common.ts
  packages/uikit/src/components/Balance/Balance.tsx
  packages/uikit/src/widgets/Farm/components/FarmTable/Earned.tsx
  packages/uikit/src/widgets/Farm/components/FarmV3Table/Actions/HarvestAction.tsx
  packages/utils/isPositionOutOfRange.ts
Labels: size/XXL

#7170 chore: Move finished pools
  packages/pools/src/constants/pools/56.ts
Labels: size/M

#7184 fix: Hide Trading Reward Token List
  apps/web/src/views/Swap/components/HotTokenList/index.tsx
  apps/web/src/views/Swap/hooks/useTradingRewardTokenList.tsx
Labels: size/M, automerge

#7189 feat: Info Page Rename Old TUSD
  apps/web/src/state/info/constant.ts
  apps/web/src/state/info/queries/pools/poolData.ts
  apps/web/src/views/Info/Tokens/TokenPage.tsx
  apps/web/src/views/Info/components/InfoSearch/index.tsx
  apps/web/src/views/Info/components/InfoTables/TokensTable.tsx
  apps/web/src/views/Info/components/InfoTables/TransactionsTable.tsx
  apps/web/src/views/V3Info/components/PoolTable/index.tsx
  apps/web/src/views/V3Info/components/Search/index.tsx
  apps/web/src/views/V3Info/components/TransactionsTable/index.tsx
  apps/web/src/views/V3Info/views/TokenPage.tsx
Labels: size/M, automerge

#7191 fix: Avoid crash page
  apps/web/src/hooks/Tokens.ts
Labels: size/XS

#7192 fix: (buycrypto): Buycrypto not fit small mobile phones
  apps/web/src/views/BuyCrypto/components/GetQuotesButton.tsx
  apps/web/src/views/BuyCrypto/containers/BuyCryptoForm.tsx
  apps/web/src/views/BuyCrypto/containers/CryptoQuoteForm.tsx
  apps/web/src/views/BuyCrypto/containers/FormHeader.tsx
  apps/web/src/views/BuyCrypto/index.tsx
  apps/web/src/views/BuyCrypto/styles.tsx
  apps/web/src/views/BuyCrypto/types.ts
Labels: size/M

#7201 fix: removed
  JPY.svg
Labels: size/M

#7200 chore: Move finished pools
  packages/pools/src/constants/pools/56.ts
Labels: size/M

#7205 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XXL

#7206 chore: Add linea testnet network switcher
  apps/web/src/components/NetworkSwitcher.tsx
  apps/web/src/pages/liquidity/index.tsx
  apps/web/src/pages/migration.tsx
  apps/web/src/utils/isV3MigrationSupported.ts
Labels: size/S

#7207 fix: farm APR tooptip style
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3ApyButton.tsx
Labels: size/XS

#7215 fix: loading user data in eth
  apps/web/src/state/farms/hooks.ts
Labels: size/XS

#7216 chore: Sunset wallet connect v1
  apps/web/src/config/wallet.ts
Labels: size/XS

#7196 fix: buy crypto css issues
  apps/web/src/views/BuyCrypto/components/FAQ.tsx
  apps/web/src/views/BuyCrypto/containers/BuyCryptoForm.tsx
  apps/web/src/views/BuyCrypto/containers/CryptoQuoteForm.tsx
  apps/web/src/views/BuyCrypto/index.tsx
  apps/web/src/views/BuyCrypto/styles.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/components/Link/LinkExternal.tsx
  packages/uikit/src/components/Link/types.ts
Labels: size/M

#7209 chore: list RPL farm on ETH
  packages/pools/src/constants/pools/1.ts
Labels: size/XS

#7208 chore: Bump wagmi and viem
  apis/farms/package.json
  apis/routing/package.json
  apps/bridge/package.json
  apps/web/package.json
  apps/web/src/utils/wagmi.ts
  packages/farms/package.json
  packages/farms/src/fetchFarmsV3.ts
  packages/farms/src/v2/fetchFarmsV2.ts
  packages/pools/package.json
  packages/smart-router/package.json
  packages/swap-sdk/package.json
  packages/uikit/.storybook/main.js
  packages/uikit/package.json
  packages/utils/package.json
  packages/v3-sdk/package.json
  packages/wagmi/package.json
  pnpm-lock.yaml
  scripts/package.json
Labels: size/XL

#7218 fix: farm page for linea testnet
  apps/web/src/state/farmsV3/hooks.ts
Labels: size/XS

#7187 fix: (swap): Tap to tooltip triggers multihop toggling and fix typo in tooltip text
  apps/web/src/components/Menu/GlobalSettings/SettingsModal.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#7212 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#7181 feat: moonpay onramp integration
  apps/web/src/components/Card/index.tsx
  apps/web/src/components/CurrencyInputPanel/index.tsx
  apps/web/src/components/FiatOnRampModal/FiatOnRampModal.tsx
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/config/constants/tokenLists/pancake-supported-onramp-currency-list.json
  apps/web/src/pages/buy-crypto/index.tsx
  apps/web/src/state/user/hooks/index.tsx
  apps/web/src/views/BuyCrypto/components/AccordianDropdown/Accordian.tsx
  apps/web/src/views/BuyCrypto/components/AccordianDropdown/AccordianItem.tsx
  apps/web/src/views/BuyCrypto/components/AssetSelect.tsx
  apps/web/src/views/BuyCrypto/components/FAQ.tsx
  apps/web/src/views/BuyCrypto/constants.ts
  apps/web/src/views/BuyCrypto/containers/BuyCryptoForm.tsx
  apps/web/src/views/BuyCrypto/hooks/usePriceQuoter.ts
  apps/web/src/views/BuyCrypto/index.tsx
  apps/web/src/views/BuyCrypto/styles.tsx
  apps/web/src/views/Swap/components/CurrencyInputHeader.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/widgets/Swap/CurrencyInputPanel.tsx
Labels: size/L

#7220 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XL

#7225 fix: Wallet connect modal is not on the correct layer
  apps/web/src/style/Global.tsx
Labels: size/S

#7227 chore: Update trading reward banner
  apps/web/src/views/Home/components/Banners/TradingRewardBanner.tsx
  apps/web/src/views/TradingReward/components/Banner.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#7226 feat: new v3 farm auction config
  apps/web/src/views/FarmAuction/components/AuctionDetailsCard/AuctionFooter.tsx
  apps/web/src/views/FarmAuction/components/AuctionHistory.tsx
  apps/web/src/views/FarmAuction/components/AuctionLeaderboard/AuctionLeaderboardTable.tsx
  apps/web/src/views/FarmAuction/components/AuctionLeaderboard/index.tsx
  apps/web/src/views/FarmAuction/components/CongratulationsCard.tsx
  apps/web/src/views/FarmAuction/constants.ts
  apps/web/src/views/FarmAuction/hooks/useV3FarmAuctionConfig.ts
Labels: size/M

#7228 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/M

#7229 fix: (lottery): Button not available when not approved
  apps/web/src/views/Lottery/components/BuyTicketsModal/BuyTicketsModal.tsx
  apps/web/src/views/Lottery/components/BuyTicketsModal/useTicketsReducer.tsx
Labels: size/M

#7230 chore: update farm auction 35 config
  apps/web/src/config/constants/farmAuctions.ts
Labels: size/XS

#7161 feat: support v3 for token highlight
  apps/web/src/views/Swap/components/HotTokenList/SwapTokenTable.tsx
  apps/web/src/views/Swap/components/HotTokenList/constants.ts
  apps/web/src/views/Swap/components/HotTokenList/index.tsx
  apps/web/src/views/Swap/components/HotTokenList/types.ts
  apps/web/src/views/Swap/components/HotTokenList/useList.tsx
  apps/web/src/views/Swap/components/HotTokenList/utils.ts
  apps/web/src/views/V3Info/data/token/tokenData.ts
  apps/web/src/views/V3Info/hooks/index.ts
  apps/web/src/views/V3Info/types.ts
Labels: size/L

#7231 feat: add AMA text for top farm bid
  apps/web/src/views/FarmAuction/components/AuctionLeaderboard/AuctionLeaderboardTable.tsx
  apps/web/src/views/FarmAuction/constants.ts
Labels: size/S

#7232 chore: list farm auction winner 35
  packages/farms/constants/56.ts
Labels: size/XS

#7233 fix: farm auction v3 info page
  apps/web/src/views/FarmAuction/components/AuctionLeaderboard/AuctionLeaderboardTable.tsx
Labels: size/XS, automerge

#7234 chore: New Crowdin updates
  locales/es-ES.json
  locales/fi-FI.json
  locales/hu-HU.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/sv-SE.json
  locales/tr-TR.json
Labels: size/XXL

#7240 fix: Token highlight loading on eth
  apps/web/src/state/info/hooks.ts
  apps/web/src/views/Swap/components/HotTokenList/useList.tsx
Labels: size/S

#7241 chore: New Crowdin updates
  locales/bn-BD.json
Labels: size/M

#7243 chore: Update domain of trading rebate api endpoint
  apps/web/src/config/constants/endpoints.ts
Labels: size/XS

#7245 chore: Add concurrency to aptos dev
  package.json
Labels: size/XS

#7242 chore: New chain - Polygon ZkEVM
  apps/web/src/components/SearchModal/CommonBases.tsx
  apps/web/src/components/SearchModal/CurrencyList.tsx
  apps/web/src/config/chains.ts
  apps/web/src/config/constants/tokenLists/pancake-default.tokenlist.json
  apps/web/src/hooks/useCanBuyCrypto.ts
  apps/web/src/pages/buy-crypto/index.tsx
  apps/web/src/state/swap/fetch/fetchDerivedPriceData.ts
  apps/web/src/state/swap/hooks.ts
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
  apps/web/src/views/AddLiquidityV3/hooks/useCurrencyParams.ts
  apps/web/src/views/BuyCrypto/constants.ts
  apps/web/src/views/Swap/V3Swap/containers/BuyCryptoLink.tsx
  apps/web/src/views/Swap/V3Swap/containers/index.ts
  apps/web/src/views/Swap/V3Swap/index.tsx
  packages/localization/src/config/translations.json
  packages/smart-router/evm/constants/gasModel/index.ts
  packages/tokens/src/common.ts
  packages/uikit/src/components/CurrencyLogo/CurrencyLogo.tsx
  packages/uikit/src/components/CurrencyLogo/utils.ts
  packages/uikit/src/widgets/RoiCalculator/RoiCalculator.tsx
  packages/uikit/src/widgets/RoiCalculator/hooks/useAmounts.ts
  packages/uikit/src/widgets/RoiCalculator/hooks/useRoi.ts
  packages/v3-sdk/src/utils/feeCalculator.ts
Labels: size/L

#7247 feat: New banners
  apps/web/src/views/Home/components/Banners/GalxeTraverseBanner.tsx
  apps/web/src/views/Home/components/Banners/PolygonZkEvmBanner.tsx
  apps/web/src/views/Home/components/Banners/animations.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  apps/web/src/views/Home/components/Banners/images/galxe-logo.png
  apps/web/src/views/Home/components/Banners/images/galxe-traverse-bg-mobile.png
  apps/web/src/views/Home/components/Banners/images/galxe-traverse-bg.png
  apps/web/src/views/Home/components/Banners/images/galxe-traverse-bunny.png
  apps/web/src/views/Home/components/Banners/images/galxe-traverse-cloud.png
  apps/web/src/views/Home/components/Banners/images/index.ts
  apps/web/src/views/Home/components/Banners/images/polygon-zk-bg-mobile.png
  apps/web/src/views/Home/components/Banners/images/polygon-zk-bg.png
  apps/web/src/views/Home/components/Banners/images/polygon-zk-bunny.png
  packages/localization/src/config/translations.json
Labels: size/L

#7251 fix: Cannot switch to eth info
  apps/web/src/state/info/hooks.ts
  apps/web/src/state/info/utils.ts
  apps/web/src/views/V3Info/hooks/index.ts
Labels: size/S

#7252 fix: Incorrect token info url from hot token list
  apps/web/src/state/info/types.ts
  apps/web/src/state/info/utils.ts
  apps/web/src/views/Swap/components/HotTokenList/SwapTokenTable.tsx
  apps/web/src/views/Swap/components/HotTokenList/index.tsx
  apps/web/src/views/Swap/components/HotTokenList/utils.ts
Labels: size/M

#7253 fix: Remove trading reward token mark on v2 tokens
  apps/web/src/views/Swap/components/HotTokenList/SwapTokenTable.tsx
Labels: size/XS
