Repository pancakeswap/pancake-frontend, pull requests merged in 2023-09, with the labels that each got.

#7709 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XXL

#7714 fix: Changing apr in price direction
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
Labels: size/XS

#7717 feat(Affiliate Program): Update T&C wording
  apps/web/src/pages/affiliates-program/agreement.tsx
  apps/web/src/pages/affiliates-program/us-agreement.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/AffiliateModal/index.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/CommissionInfo.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/Question.tsx
  apps/web/src/views/AffiliatesProgram/utils/commisionList.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#7720 feat(Affiliate Program): Update Affiliate Program Agreement
  apps/web/src/pages/affiliates-program/agreement.tsx
  apps/web/src/pages/affiliates-program/us-agreement.tsx
Labels: size/L, automerge

#7725 feat: Show NonAffiliateModal
  apps/web/src/views/AffiliatesProgram/components/Dashboard/AffiliateModal/NonAffiliateModal.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/index.tsx
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/Congratulations.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/index.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#7730 chore: Move finished pools
  packages/pools/src/constants/pools/56.ts
Labels: size/M

#7733 chore: Bump up swiper
  apps/aptos/package.json
  apps/blog/package.json
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/S

#7629 fix: Submenu items arrow right button not visible on mobile
  apps/aptos/views/Ifos/index.tsx
  apps/web/src/views/Ifos/index.tsx
  apps/web/src/views/Info/index.tsx
  apps/web/src/views/Page.tsx
  apps/web/src/views/V3Info/components/Layout/index.tsx
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/__tests__/widgets/menu.test.tsx
  packages/uikit/src/components/SubMenuItems/SubMenuItems.tsx
  packages/uikit/src/widgets/Menu/Menu.tsx
Labels: size/L

#7732 perf: Use cached big numbers
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/MyReferralLink.tsx
  apps/web/src/views/Farms/FarmsV3.tsx
  apps/web/src/views/LiquidStaking/hooks/useExchangeRate.tsx
Labels: size/S

#7743 feat: support base info page
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/state/info/constant.ts
  apps/web/src/state/info/hooks.ts
  apps/web/src/utils/graphql.ts
  apps/web/src/views/Info/components/InfoNav/index.tsx
  apps/web/src/views/V3Info/components/Layout/InfoNav.tsx
  apps/web/src/views/V3Info/constants.ts
Labels: size/M

#7731 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XL

#7724 fix: Link a tag descendant warning
  apps/web/src/hooks/useLockedEndNotification.tsx
  apps/web/src/views/Voting/components/CastVoteModal/DetailsView.tsx
  packages/uikit/src/__tests__/components/link.test.tsx
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/components/Link/Link.tsx
  packages/uikit/src/components/Link/index.tsx
Labels: size/L

#7747 chore: New Crowdin updates
  locales/ru-RU.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#7750 feat(Aptos): Network Select Add Base
  apps/aptos/components/NetworkSwitcher.tsx
Labels: size/XS, automerge

#7753 fix: Bunny slider component
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/components/Footer/Footer.tsx
  packages/uikit/src/components/Slider/styles.ts
Labels: size/L, automerge

#7673 feat: Add zkSync Pool config
  apps/web/src/config/constants/priceHelperLps/index.ts
  apps/web/src/config/constants/priceHelperLps/pools/280.ts
  apps/web/src/config/constants/priceHelperLps/pools/324.ts
  packages/localization/src/config/translations.json
  packages/pools/src/constants/contracts.ts
  packages/pools/src/constants/pools/280.ts
  packages/pools/src/constants/pools/324.ts
  packages/pools/src/constants/pools/index.ts
  packages/pools/src/constants/supportedChains.ts
  packages/pools/src/queries/fetchUserPoolsData.ts
  packages/tokens/src/280.ts
  packages/uikit/src/widgets/Pool/StakeModal.tsx
  packages/uikit/src/widgets/Pool/ZkSyncWarning.tsx
  packages/utils/llamaPrice.ts
Labels: size/L

#7667 feat: on-ramp campaign updates for mercuryo
  apps/web/src/components/FiatOnRampModal/FiatOnRampModal.tsx
  apps/web/src/components/Menu/UserMenu/WalletInfo.tsx
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/state/buyCrypto/actions.ts
  apps/web/src/state/buyCrypto/hooks.ts
  apps/web/src/state/buyCrypto/reducer.ts
  apps/web/src/views/BuyCrypto/components/AccordionDropdown/Accordion.tsx
  apps/web/src/views/BuyCrypto/components/AccordionDropdown/AccordionItem.tsx
  apps/web/src/views/BuyCrypto/constants.ts
  apps/web/src/views/BuyCrypto/hooks/usePriceQuoter.ts
  apps/web/src/views/BuyCrypto/hooks/useProviderAvailability.ts
  apps/web/src/views/BuyCrypto/hooks/useProviderQuotes.ts
  apps/web/src/views/Swap/components/CurrencyInputHeader.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#7758 fix: Currency list UI issue
  apps/aptos/components/SearchModal/CurrencyList.tsx
  apps/web/src/components/SearchModal/CurrencyList.tsx
Labels: size/XS

#7755 feat: Add Pool changeset
  .changeset/famous-tomatoes-stare.md
Labels: size/XS, automerge

#7757 fix: ConvertToLock Message Text disappear
  apps/web/src/views/Pools/components/LockedPool/Common/ConvertToLock.tsx
Labels: size/XS, automerge

#7760 chore: shelve moonpay banner
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/XS

#7762 fix: Use token allowance blink false when fetching
  apps/web/src/hooks/useApproveCallback.ts
  apps/web/src/hooks/useTokenAllowance.ts
Labels: Delayed Release, size/M

#7763 chore: update the mercuryo banner
  apps/web/src/views/Home/components/Banners/MoonPayBanner.tsx
  apps/web/src/views/Home/components/Banners/images/index.ts
  apps/web/src/views/Home/components/Banners/images/mercuryo-logo.png
  packages/localization/src/config/translations.json
Labels: size/M

#7767 chore: Move some banners to SHUFFLE_BANNERS
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/S, automerge

#7771 feat: launch farm on Base
  apis/farms/.dev.vars
  apis/farms/src/bindings.d.ts
  apis/farms/src/lpApr.ts
  apis/farms/src/provider.ts
  apis/farms/src/v3.ts
  apis/farms/wrangler.toml
  apps/web/src/components/TokenImage/index.tsx
  apps/web/src/config/constants/supportChains.ts
  apps/web/src/config/constants/tokenLists/pancake-default.tokenlist.json
  apps/web/src/views/TradingReward/config/pairs/index.tsx
  packages/farms/constants/8453.ts
  packages/farms/constants/common/index.ts
  packages/farms/constants/priceHelperLps/8453.ts
  packages/farms/constants/priceHelperLps/getFarmsPriceHelperLpFiles.ts
  packages/farms/constants/v3/index.ts
  packages/farms/src/const.ts
  packages/farms/tests/v3.test.ts
  packages/tokens/src/8453.ts
  packages/tokens/src/common.ts
Labels: size/L

#7745 feat: New multicall
  .changeset/cold-zoos-share.md
  apps/web/package.json
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/hooks/useMulticallGasLimit.ts
  apps/web/src/quote-worker.ts
  package.json
  packages/multicall/README.md
  packages/multicall/package.json
  packages/multicall/src/abis/IMulticall.ts
  packages/multicall/src/constants/blockConflictTolerance.ts
  packages/multicall/src/constants/contracts.ts
  packages/multicall/src/constants/gasLimit.ts
  packages/multicall/src/constants/index.ts
  packages/multicall/src/getBlockConflictTolerance.ts
  packages/multicall/src/getGasLimit.ts
  packages/multicall/src/getMulticallContract.ts
  packages/multicall/src/index.ts
  packages/multicall/src/multicall.ts
  packages/multicall/src/types.ts
  packages/multicall/tsconfig.json
  packages/multicall/tsup.config.ts
  packages/multicall/vitest.config.ts
  packages/smart-router/evm/constants/multicall.ts
  packages/smart-router/evm/types/multicall.ts
  packages/smart-router/evm/v3-router/constants/routeConfig.ts
  packages/smart-router/evm/v3-router/providers/multicallSwapProvider.ts
  packages/smart-router/evm/v3-router/providers/onChainQuoteProvider.ts
  packages/smart-router/evm/v3-router/providers/quoteProviders.ts
  packages/smart-router/evm/v3-router/schema.ts
  packages/smart-router/evm/v3-router/types/providers.ts
  packages/smart-router/package.json
  packages/utils/toBigInt.ts
  pnpm-lock.yaml
Labels: size/XXL

#7772 fix: StakeModal chainId issue
  apps/aptos/components/CurrencyInputPanel/index.tsx
  apps/web/src/views/Pools/components/Modals/StakeModal.tsx
  apps/web/src/views/Pools/components/Modals/ZkSyncWarning.tsx
  packages/uikit/src/widgets/Pool/StakeModal.tsx
  packages/uikit/src/widgets/Pool/ZkSyncWarning.tsx
Labels: size/M, automerge

#7774 fix: Remove liquidity title
  apps/web/src/views/RemoveLiquidity/RemoveLiquidityV3.tsx
Labels: size/XS, automerge

#7777 chore: list BSC farms and pools
  packages/farms/constants/56.ts
  packages/pools/src/constants/pools/56.ts
Labels: size/M

#7780 chore: Multicall pkg bump
  .changeset/sweet-dancers-smash.md
  packages/multicall/package.json
  packages/pools/package.json
  packages/smart-router/package.json
Labels: size/S

#7776 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#7782 chore: Fix readme typos and add contracts
  .changeset/tall-beds-accept.md
  packages/multicall/README.md
Labels: size/S

#7775 chore: fix styled components scss hover
  apps/aptos/components/SearchModal/CommonBases.tsx
  apps/web/src/components/Links/index.tsx
  apps/web/src/components/SearchModal/CommonBases.tsx
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/Info/Tokens/TokenPage.tsx
  apps/web/src/views/Info/components/InfoSearch/index.tsx
  apps/web/src/views/Info/components/InfoTables/PoolsTable.tsx
  apps/web/src/views/Info/components/InfoTables/TokensTable.tsx
  apps/web/src/views/Info/components/InfoTables/shared.tsx
  apps/web/src/views/Info/components/SaveIcon/index.tsx
  apps/web/src/views/Info/components/TopTokenMovers/index.tsx
  apps/web/src/views/LimitOrders/components/LimitOrderTable/TableNavigation.tsx
  apps/web/src/views/Nft/market/Collections/index.tsx
  apps/web/src/views/Swap/components/HotTokenList/SwapTokenTable.tsx
  apps/web/src/views/Swap/components/styleds.tsx
  apps/web/src/views/V3Info/components/DensityChart/index.tsx
  apps/web/src/views/V3Info/components/HoverInlineText/index.tsx
  apps/web/src/views/V3Info/components/PoolTable/index.tsx
  apps/web/src/views/V3Info/components/Search/index.tsx
  apps/web/src/views/V3Info/components/TokenTable/index.tsx
  apps/web/src/views/V3Info/components/TopTokenMovers/index.tsx
  apps/web/src/views/V3Info/components/shared.tsx
  apps/web/src/views/V3Info/views/PoolPage.tsx
  packages/uikit/src/__tests__/components/balanceinput.test.tsx
  packages/uikit/src/__tests__/components/button.test.tsx
  packages/uikit/src/__tests__/components/buttonmenu.test.tsx
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/__tests__/widgets/modal.test.tsx
  packages/uikit/src/components/Button/StyledButton.tsx
  packages/uikit/src/components/CakePrice/CakePrice.tsx
  packages/uikit/src/components/PaginationButton/PaginationButton.tsx
  packages/uikit/src/components/QuestionHelper/index.tsx
Labels: size/M

#7784 chore: remove play-usdt farm
  packages/farms/constants/56.ts
Labels: size/XS

#7787 feat(Farm): Remove isCommunity tag
  apps/web/src/views/FarmAuction/components/AuctionHistory.tsx
  apps/web/src/views/Lottery/components/AllHistoryCard/RoundSwitcher.tsx
  packages/farms/constants/56.ts
Labels: size/S, automerge

#7791 feat: Add override approve for approve callback hook
  apps/web/src/hooks/useApproveCallback.ts
Labels: size/L

#7797 fix(HotToken): Fix weird gap
  apps/web/src/components/TabToggle/index.tsx
Labels: size/XS

#7800 fix: Override approve return error
  apps/web/src/hooks/useApproveCallback.ts
Labels: size/XS

#7799 fix(Pools): Fix afterburn icon color
  apps/web/src/views/Pools/components/Vault/VaultPositionTag.tsx
Labels: size/XS

#7756 feat: Add Testnet pools for zkEVM, Linea, base
  apps/web/src/config/constants/priceHelperLps/index.ts
  apps/web/src/config/constants/priceHelperLps/pools/1101.ts
  apps/web/src/config/constants/priceHelperLps/pools/1442.ts
  apps/web/src/config/constants/priceHelperLps/pools/59140.ts
  apps/web/src/config/constants/priceHelperLps/pools/59144.ts
  apps/web/src/config/constants/priceHelperLps/pools/8453.ts
  apps/web/src/config/constants/priceHelperLps/pools/84531.ts
  packages/pools/src/constants/contracts.ts
  packages/pools/src/constants/pools/1101.ts
  packages/pools/src/constants/pools/1442.ts
  packages/pools/src/constants/pools/59140.ts
  packages/pools/src/constants/pools/59144.ts
  packages/pools/src/constants/pools/8453.ts
  packages/pools/src/constants/pools/84531.ts
  packages/pools/src/constants/pools/index.ts
  packages/pools/src/constants/supportedChains.ts
  packages/tokens/src/1442.ts
  packages/tokens/src/59140.ts
  packages/tokens/src/84531.ts
  packages/tokens/src/common.ts
  packages/utils/llamaPrice.ts
Labels: size/L, automerge

#7794 chore: New Crowdin updates
  locales/ar-SA.json
  locales/de-DE.json
  locales/es-ES.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#7803 feat: Update Perp chain query name
  apps/web/src/utils/getPerpetualUrl.ts
Labels: size/XS, automerge

#7806 fix: uikit framer build types
  packages/uikit/package.json
  packages/uikit/src/hooks/useTooltip/StyledTooltip.tsx
  packages/uikit/src/widgets/Modal/ModalContext.tsx
  packages/uikit/src/widgets/Modal/styles.tsx
  pnpm-lock.yaml
Labels: size/S

#7807 fix(awgmi): utils inline bundle
  .changeset/nice-radios-shop.md
  packages/awgmi/package.json
  pnpm-lock.yaml
Labels: size/S

#7809 fix(utils): deps refactor
  .changeset/quick-tigers-rush.md
  apps/web/src/state/pools/index.ts
  apps/web/src/utils/llamaPrice.ts
  apps/web/src/utils/wrappedCurrency.ts
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3StakeAndUnStake.tsx
  packages/farms/src/defineFarmV3Configs.ts
  packages/tokens/src/helpers.ts
  packages/utils/currencyId.ts
  packages/utils/package.json
  packages/utils/toBigInt.ts
  packages/utils/tryParseAmount.test.ts
  packages/utils/unwrappedToken.ts
  pnpm-lock.yaml
Labels: size/M

#7678 feat: Swap UI flow improvement
  .changeset/silly-jeans-pump.md
  apps/web/src/hooks/useApproveCallback.ts
  apps/web/src/views/Swap/MMLinkPools/components/ConfirmSwapModal.tsx
  apps/web/src/views/Swap/MMLinkPools/components/MMAndAMMDealDisplay.tsx
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButton.tsx
  apps/web/src/views/Swap/MMLinkPools/components/SwapModalFooter.tsx
  apps/web/src/views/Swap/MMLinkPools/components/TransactionConfirmSwapContent.tsx
  apps/web/src/views/Swap/MMLinkPools/hooks/useDerivedSwapInfoWithMM.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMTradeInfo.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useSwapCallArguments.ts
  apps/web/src/views/Swap/MMLinkPools/types.ts
  apps/web/src/views/Swap/MMLinkPools/utils/exchange.ts
  apps/web/src/views/Swap/V3Swap/components/SwapModalFooter.tsx
  apps/web/src/views/Swap/V3Swap/components/TransactionConfirmSwapContent.tsx
  apps/web/src/views/Swap/V3Swap/containers/ApproveStepFlow.tsx
  apps/web/src/views/Swap/V3Swap/containers/ConfirmSwapModal.tsx
  apps/web/src/views/Swap/V3Swap/containers/MMCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/containers/SwapCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useSendSwapTransaction.ts
  apps/web/src/views/Swap/V3Swap/types.ts
  apps/web/src/views/Swap/components/ConfirmSwapModalContainer.tsx
  apps/web/src/views/Swap/components/SwapModalHeader.tsx
  packages/localization/src/config/translations.json
  packages/smart-router/evm/v3-router/utils/getExecutionPrice.ts
  packages/uikit/src/__tests__/widgets/modal.test.tsx
  packages/uikit/src/widgets/Modal/Modal.tsx
  packages/uikit/src/widgets/Modal/styles.tsx
  packages/uikit/src/widgets/Modal/types.ts
  packages/uikit/src/widgets/Swap/ApproveModalContent.tsx
  packages/uikit/src/widgets/Swap/SwapPendingModalContent.tsx
  packages/uikit/src/widgets/Swap/SwapTransactionReceiptModalContent.tsx
  packages/uikit/src/widgets/Swap/TokenTransferInfo.tsx
  packages/uikit/src/widgets/Swap/index.ts
Labels: size/XXL

#7811 feat(Swap): More detail for amount decimals
  apps/web/src/views/Swap/V3Swap/containers/ConfirmSwapModal.tsx
Labels: size/XS

#7814 fix: Unable to quote on base
  .changeset/silly-dolls-shave.md
  apps/web/src/config/nodes.ts
  apps/web/src/hooks/useMulticallGasLimit.ts
  packages/multicall/src/constants/gasLimit.ts
  packages/multicall/src/multicall.ts
  packages/smart-router/evm/constants/multicall.ts
  packages/smart-router/evm/types/multicall.ts
  packages/smart-router/evm/v3-router/providers/multicallSwapProvider.ts
  packages/smart-router/evm/v3-router/providers/onChainQuoteProvider.ts
Labels: size/M

#7816 fix: Approval error
  apps/web/src/views/AddLiquidityV3/components/V3SubmitButton.tsx
  apps/web/src/views/AddLiquidityV3/formViews/StableFormView.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V2FormView.tsx
  apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
Labels: size/S

#7825 feat(Bridge): Bump squid widget
  apps/bridge/package.json
  pnpm-lock.yaml
Labels: size/XXL, automerge

#7821 refactor: Return object from approve callback hook
  apps/web/src/hooks/useApproveCallback.ts
  apps/web/src/hooks/useApproveConfirmTransaction.tsx
  apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
  apps/web/src/views/AddLiquidity/index.tsx
  apps/web/src/views/AddLiquidityV3/IncreaseLiquidityV3.tsx
  apps/web/src/views/AddLiquidityV3/Migrate.tsx
  apps/web/src/views/AddLiquidityV3/components/V3SubmitButton.tsx
  apps/web/src/views/AddLiquidityV3/formViews/StableFormView.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V2FormView.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
  apps/web/src/views/LimitOrders/index.tsx
  apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/index.tsx
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/containers/ConfirmSwapModal.tsx
  apps/web/src/views/Swap/V3Swap/containers/MMCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/containers/SwapCommitButton.tsx
Labels: size/L

#7824 chore: mercuryo campaign end
  apps/web/src/views/BuyCrypto/components/AccordionDropdown/Accordion.tsx
  apps/web/src/views/BuyCrypto/components/AccordionDropdown/AccordionItem.tsx
  apps/web/src/views/BuyCrypto/constants.ts
Labels: size/M

#7818 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#7829 feat(Blog): Add scroll to All articles section
  apps/blog/components/Article/AllArticle/index.tsx
Labels: size/S, automerge

#7812 chore: Add missing config to opbnb testnet
  apis/routing/src/constants.ts
  apps/web/src/config/chains.ts
  apps/web/src/config/constants/exchange.ts
  apps/web/src/config/constants/tokenLists/pancake-default.tokenlist.json
  apps/web/src/state/multicall/fetchChunk.ts
  packages/smart-router/evm/constants/gasModel/v3.ts
  packages/tokens/src/common.ts
  packages/uikit/src/components/CurrencyLogo/utils.ts
Labels: size/M

#7831 chore: remove moonpay banner
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/XS

#7830 fix: tokens list isReady state
  packages/token-lists/package.json
  packages/token-lists/react/lists.ts
  packages/token-lists/react/reducer.test.ts
  packages/token-lists/react/reducer.ts
  pnpm-lock.yaml
Labels: size/L

#7835 chore: switch bot
  .github/workflows/updateAptosLPsAPR.yml
  .github/workflows/updateLPsAPR.yml
Labels: size/XS

#7837 fix: in operation typeError
  apps/web/sentry.client.config.js
  apps/web/src/utils/sentry.ts
Labels: size/XS

#7842 chore: Fix null check issues
  apps/web/src/__tests__/state/pools/helpers.test.ts
  apps/web/src/__tests__/translations.test.ts
  apps/web/src/__tests__/utils/getLpAddress.test.ts
  apps/web/src/__tests__/utils/index.test.ts
  apps/web/src/__tests__/utils/utils.test.ts
  apps/web/src/__tests__/views/lottery/generateTicketNumbers.test.ts
  apps/web/src/__tests__/views/predictions/components/History/helpers.test.ts
  apps/web/src/components/AccessRisk/AccessRiskTooltips.tsx
  apps/web/src/components/AccessRisk/index.tsx
  apps/web/src/utils/apr.ts
  apps/web/src/utils/exchange.ts
  apps/web/src/utils/getLpAddress.ts
  apps/web/src/utils/numberOrNull.ts
  apps/web/src/views/Lottery/components/BuyTicketsModal/generateTicketNumbers.tsx
  apps/web/src/views/Predictions/components/History/helpers.ts
Labels: size/L

#7844 fix: Swap reset approval shown after reject
  apps/web/src/views/Swap/V3Swap/containers/ConfirmSwapModal.tsx
Labels: size/XS

#7841 fix: @typescript-eslint/typescript-estree mismatch ts version
  apps/web/.eslintrc
  packages/eslint-config/package.json
  pnpm-lock.yaml
Labels: size/XXL

#7845 chore: list wstETH pool
  packages/pools/src/constants/pools/1.ts
Labels: size/XS

#7846 chore: New Crowdin updates
  locales/it-IT.json
  locales/ja-JP.json
  locales/tr-TR.json
Labels: size/M

#7832 feat: Add reset approval eth usdt for liquidity
  apps/web/src/views/AddLiquidity/index.tsx
  apps/web/src/views/AddLiquidityV3/IncreaseLiquidityV3.tsx
  apps/web/src/views/AddLiquidityV3/components/ApproveLiquidityTokens.tsx
  apps/web/src/views/AddLiquidityV3/components/V3SubmitButton.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V2FormView.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
  apps/web/src/views/Swap/V3Swap/containers/ConfirmSwapModal.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#7852 chore: Add tsconfig for check usage
  apps/web/tsconfig.check.json
Labels: size/XS

#7855 chore: patch pool package
  .changeset/slow-spiders-swim.md
Labels: size/XS

#7854 perf: Increase polling interval of public clients
  apis/farms/src/provider.ts
  apps/web/src/hooks/usePublicNodeWaitForTransaction.ts
  apps/web/src/state/block/hooks.ts
  apps/web/src/utils/viem.server.ts
  apps/web/src/utils/wagmi.ts
Labels: size/M

#7790 feat: Claim Third Year Anniversary Campaign
  apps/web/public/images/achievements/3-year.svg
  apps/web/src/components/GlobalCheckClaimStatus/AnniversaryAchievementModal.tsx
  apps/web/src/components/GlobalCheckClaimStatus/V3AirdropModal.tsx
  apps/web/src/components/GlobalCheckClaimStatus/index.tsx
  apps/web/src/config/abi/anniversaryAchievement.json
  apps/web/src/config/abi/anniversaryAchievement.ts
  apps/web/src/config/constants/campaigns.ts
  apps/web/src/config/constants/contracts.ts
  apps/web/src/hooks/useContract.ts
  apps/web/src/hooks/useShowOnceAirdropModal.ts
  apps/web/src/hooks/useShowOnceAnniversaryModal.ts
  apps/web/src/utils/addressHelpers.ts
  apps/web/src/utils/contractHelpers.ts
  packages/localization/src/config/translations.json
Labels: size/XL

#7828 feat: Third Year Anniversary Home page effect
  apps/web/public/images/third-year-cake.svg
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/components/Menu/hooks/useMenuItems.ts
  apps/web/src/hooks/useAnniversaryEffect.ts
  apps/web/src/pages/_app.tsx
  apps/web/src/pages/index.tsx
  apps/web/src/pages/nfts/activity.tsx
  apps/web/src/pages/nfts/collections/[collectionAddress].tsx
  apps/web/src/pages/nfts/collections/[collectionAddress]/[tokenId].tsx
  apps/web/src/pages/nfts/collections/index.tsx
  apps/web/src/pages/nfts/index.tsx
  apps/web/src/views/Home/components/ThirdYearBirthdayCake.tsx
  apps/web/src/views/Home/index.tsx
  apps/web/src/views/Nft/market/components/SubMenu/index.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/components/ScrollToTopButton/ScrollToTopButtonV2.tsx
  packages/uikit/src/components/Svg/Icons/Birthday.tsx
  packages/uikit/src/components/Svg/index.tsx
Labels: size/L, automerge

#7866 fix: Invalid block number
  apps/web/src/state/block/hooks.ts
Labels: size/XS

#7867 chore: Add bot token back
  .github/workflows/updateAptosLPsAPR.yml
  .github/workflows/updateLPsAPR.yml
Labels: size/XS

#7863 fix: Lottery history card round not shown completely
  apps/web/src/views/Lottery/components/AllHistoryCard/RoundSwitcher.tsx
  apps/web/src/views/Lottery/components/AllHistoryCard/index.tsx
Labels: size/M

#7872 feat: Hide AnniversaryAchievementModal
  apps/web/src/components/GlobalCheckClaimStatus/index.tsx
Labels: size/XS

#7871 feat: Add Chain farms and tag
  apps/web/src/views/TradingReward/components/PairInfo.tsx
  apps/web/src/views/TradingReward/config/pairs/index.tsx
  packages/uikit/src/components/Svg/Icons/Arbitrum.tsx
  packages/uikit/src/components/Svg/Icons/Base.tsx
  packages/uikit/src/components/Svg/Icons/Linea.tsx
  packages/uikit/src/components/Svg/index.tsx
  packages/widgets-internal/farm/components/Tags/index.tsx
Labels: size/L, automerge

#7873 fix: SkeletonV2
  packages/uikit/src/components/Skeleton/Skeleton.tsx
Labels: size/XS, automerge

#7851 chore: TS check
  .github/workflows/lintPrTitle.yml
  .github/workflows/tsCheck.yml
  .lintstaged.eslintrc
  .lintstagedrc
  apps/web/src/__tests__/translations.test.ts
  apps/web/src/components/AccessRisk/AccessRiskTooltips.tsx
  apps/web/src/components/AddToWallet/AddToWalletButton.tsx
  apps/web/src/components/CurrencyInputPanel/index.tsx
  apps/web/src/components/SearchModal/CurrencySearchModal.tsx
  apps/web/src/hooks/useBUSDPrice.ts
  tsconfig.strictNullChecks.json
Labels: size/L

#7862 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#7861 perf: Memoize multicall hook props
  apps/web/src/hooks/v3/useV3PositionFees.ts
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/pages/stable/[address].tsx
  apps/web/src/state/wallet/hooks.ts
  apps/web/src/views/AddLiquidity/AddStableLiquidity/hooks/useStableLPDerivedMintInfo.tsx
Labels: size/S

#7859 perf: Memoize farms with balance hook to reduce rerenders
  apps/web/src/views/Home/hooks/useFarmsWithBalance.tsx
Labels: size/M

#7875 feat: Revert hide AnniversaryAchievementModal
  apps/web/src/components/GlobalCheckClaimStatus/index.tsx
Labels: size/XS

#7876 chore: Include tsx files for ts check
  .github/workflows/tsCheck.yml
Labels: size/XS

#7878 chore: list farms on BSC
  packages/farms/constants/56.ts
Labels: size/S

#7879 fix: Module not found on nodejs esm
  .changeset/ninety-flies-marry.md
  packages/smart-router/evm/v3-router/functions/getPairCombinations.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/getV3CandidatePools.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/subgraphPoolProviders.ts
  packages/smart-router/evm/v3-router/utils/pool.ts
  packages/smart-router/package.json
  pnpm-lock.yaml
Labels: size/M

#7877 feat: Update birthday nav items
  apps/web/src/components/Menu/config/config.ts
  packages/localization/src/config/translations.json
Labels: size/XS, automerge

#7893 fix: Typo in translation
  packages/localization/src/config/translations.json
Labels: size/XS

#7896 fix: Typo
  apps/web/src/views/Swap/V3Swap/containers/BuyCryptoLink.tsx
Labels: size/XS, automerge

#7882 fix: Change the capitalization or case of text in readme
  README.md
Labels: size/XS

#7897 chore: Add content write permission to ts check
  .github/workflows/tsCheck.yml
Labels: size/XS

#7889 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/M

#7899 chore: Grant write permission to ts check
  .github/workflows/tsCheck.yml
Labels: size/XS

#7901 chore: list woo-eth/ethereum farm up
  packages/farms/constants/1.ts
  packages/tokens/src/1.ts
Labels: size/S, automerge

#7902 chore: Only list incremental errors
  .github/workflows/tsCheck.yml
Labels: size/XS

#7883 fix: Use callback to prevent misalignment in block fetch
  apps/web/src/state/block/hooks.ts
  apps/web/src/utils/viem.ts
Labels: size/M

#7903 chore: No ts check on forked repos
  .github/workflows/tsCheck.yml
Labels: size/XS

#7874 fix: sync price from query
  apps/web/src/hooks/v3/useV3DerivedInfo.ts
  apps/web/src/views/AddLiquidityV3/IncreaseLiquidityV3.tsx
  apps/web/src/views/AddLiquidityV3/Migrate.tsx
  apps/web/src/views/AddLiquidityV3/components/V3SubmitButton.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V2FormView.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/RangeSelector.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/StepCounter.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/form/actions.ts
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/form/hooks/useInitialRange.ts
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/form/hooks/useRangeHopCallbacks.ts
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/form/hooks/useV3MintActionHandlers.ts
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/form/reducer.ts
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
  apps/web/src/views/Migration/components/v3/Step3.tsx
Labels: size/L

#7904 fix: Subgraph block error
  apps/web/src/state/block/hooks.ts
Labels: size/S

#7908 chore: list rpl pool
  packages/pools/src/constants/pools/1.ts
Labels: size/XS

#7891 fix: Tapping tooltip button or text causes roi calculator open
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
Labels: size/XS

#7894 chore: Move finished pools
  packages/pools/src/constants/pools/56.ts
Labels: size/M

#7910 style(Pool): Earning skeleton
  apps/web/src/views/Pools/components/PoolsTable/Cells/EarningsCell.tsx
Labels: size/S, automerge

#7911 fix: style-component props forward
  .changeset/nice-baboons-perform.md
  apps/web/src/components/AddressInputSelect/index.tsx
  apps/web/src/components/Modal/ModalInput.tsx
  apps/web/src/utils/prices.ts
  apps/web/src/views/Ifos/components/IfoVesting/VestingPeriod/TokenInfo.tsx
  apps/web/src/views/Migration/components/Cells/ExpandActionCell.tsx
  packages/uikit/src/__tests__/components/balanceinput.test.tsx
  packages/uikit/src/__tests__/components/buttonmenu.test.tsx
  packages/uikit/src/__tests__/components/input.test.tsx
  packages/uikit/src/components/Button/StyledButton.tsx
  packages/uikit/src/components/ButtonMenu/ButtonMenu.tsx
  packages/uikit/src/components/DropdownMenu/styles.tsx
  packages/uikit/src/components/Input/Input.tsx
  packages/uikit/src/components/NextLink/NextLink.tsx
  packages/uikit/src/components/NotificationDot/NotificationDot.tsx
  packages/uikit/src/components/SubMenuItems/SubMenuItems.tsx
  packages/uikit/src/components/Svg/Svg.tsx
  packages/uikit/src/components/Svg/styles.tsx
  packages/uikit/src/widgets/Menu/Menu.tsx
  packages/uikit/src/widgets/Menu/components/UserMenu/index.tsx
  packages/widgets-internal/farm/components/FarmTable/Details.tsx
  packages/widgets-internal/pool/Cells/ExpandActionCell.tsx
Labels: size/M

#7915 feat: Add birthday planet4 nav
  apps/web/src/components/Menu/config/config.ts
  packages/localization/src/config/translations.json
Labels: size/XS, automerge

#7916 fix: Trading reward leaderboard previous rounds switch not working
  apps/web/src/views/TradingReward/components/Leaderboard/index.tsx
Labels: size/XS

#7926 chore: list pyusd farm up
  .eslintrc
  package.json
  packages/farms/constants/1.ts
  packages/tokens/package.json
  packages/tokens/src/1.ts
  pnpm-lock.yaml
Labels: size/M

#7663 feat: transak integration
  apps/web/public/images/on-ramp-providers/transak-new.png
  apps/web/public/images/transak-logo.png
  apps/web/src/components/Card/index.tsx
  apps/web/src/components/FiatOnRampModal/FiatOnRampModal.tsx
  apps/web/src/components/SearchModal/CurrencySearch.tsx
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/config/constants/supportChains.ts
  apps/web/src/config/constants/tokenLists/pancake-supported-onramp-currency-list.json
  apps/web/src/state/buyCrypto/hooks.ts
  apps/web/src/state/buyCrypto/reducer.ts
  apps/web/src/views/BuyCrypto/Icons/index.tsx
  apps/web/src/views/BuyCrypto/components/AccordionDropdown/AccordionItem.tsx
  apps/web/src/views/BuyCrypto/components/InputHeader.tsx
  apps/web/src/views/BuyCrypto/components/OnRampCurrencySelect/index.tsx
  apps/web/src/views/BuyCrypto/components/OnRampProviderLogo/OnRampProviderLogo.tsx
  apps/web/src/views/BuyCrypto/constants.ts
  apps/web/src/views/BuyCrypto/containers/BuyCryptoForm.tsx
  apps/web/src/views/BuyCrypto/hooks/useIframeUrlFetcher.ts
  apps/web/src/views/BuyCrypto/hooks/usePriceQuoter.ts
  apps/web/src/views/BuyCrypto/hooks/useProviderAvailability.ts
  apps/web/src/views/BuyCrypto/hooks/useProviderQuotes.ts
  apps/web/src/views/BuyCrypto/types.ts
  packages/localization/src/config/translations.json
  packages/uikit/src/index.ts
  packages/uikit/src/widgets/BuyCrypto/BuyCryptoWidget.css.ts
  packages/uikit/src/widgets/BuyCrypto/BuyCryptoWidget.tsx
  packages/uikit/src/widgets/BuyCrypto/InputHeader.tsx
  packages/uikit/src/widgets/BuyCrypto/index.ts
Labels: size/XXL

#7914 feat: Liquidity url filter pair
  apps/web/src/hooks/useV2Pairs.ts
  apps/web/src/pages/liquidity/index.tsx
  apps/web/src/utils/isV3MigrationSupported.ts
  apps/web/src/views/AddLiquidityV3/components/StablePairCard.tsx
  apps/web/src/views/AddLiquidityV3/components/V2PairCard.tsx
  packages/localization/src/config/translations.json
  packages/smart-router/evm/constants/stableSwap/pools.ts
Labels: size/L, automerge

#7930 feat: Update birthday planet 5 nav
  apps/web/src/components/Menu/config/config.ts
  packages/localization/src/config/translations.json
Labels: size/XS, automerge

#7932 feat: Update code owners
  .github/CODEOWNERS
Labels: size/XS, automerge

#7934 feat: list 3 farm
  packages/farms/constants/42161.ts
  packages/farms/constants/56.ts
  packages/tokens/src/42161.ts
Labels: size/M

#7933 feat: add lUSD warning
  apps/web/src/config/constants/swapWarningTokens.ts
  apps/web/src/config/constants/warningTokens.ts
  apps/web/src/views/Swap/components/SwapWarningModal/56/LUSDWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/56/index.tsx
  packages/localization/src/config/translations.json
Labels: size/M, automerge

#7937 feat: Lottery with birthday theme
  apps/web/public/images/lottery/birthday/banner-bunny-1.png
  apps/web/public/images/lottery/birthday/birthday-cake-icon.png
  apps/web/public/images/lottery/birthday/cake3.png
  apps/web/public/images/lottery/birthday/left-2.png
  apps/web/public/images/lottery/birthday/left-star-1.png
  apps/web/public/images/lottery/birthday/mobile-1.png
  apps/web/public/images/lottery/birthday/mobile-2.png
  apps/web/public/images/lottery/birthday/right-star-1.png
  apps/web/public/images/lottery/birthday/third-cake.png
  apps/web/src/views/Lottery/components/BirthdayDecorations.tsx
  apps/web/src/views/Lottery/components/Hero.tsx
  apps/web/src/views/Lottery/index.tsx
  apps/web/src/views/Lottery/pageSectionStyles.tsx
  packages/localization/src/config/translations.json
Labels: size/L, automerge

#7924 chore: Update ScanLink component
  apps/web/src/components/App/Transactions/Transaction.tsx
  apps/web/src/components/Menu/UserMenu/WalletInfo.tsx
  apps/web/src/components/TransactionDetailModal/FarmTransactionModal/FarmDetail.tsx
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/state/info/constant.ts
  apps/web/src/views/AddLiquidityV3/formViews/V2FormView.tsx
  apps/web/src/views/FarmAuction/components/AuctionLeaderboard/AuctionLeaderboardTable.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/Info/Tokens/TokenPage.tsx
  apps/web/src/views/Info/components/InfoSearch/index.tsx
  apps/web/src/views/Info/components/InfoTables/TokensTable.tsx
  apps/web/src/views/Info/components/InfoTables/TransactionsTable.tsx
  apps/web/src/views/V3Info/components/Search/index.tsx
  apps/web/src/views/V3Info/components/TransactionsTable/index.tsx
  apps/web/src/views/V3Info/views/PoolPage.tsx
  apps/web/src/views/V3Info/views/TokenPage.tsx
  apps/web/src/views/Voting/CreateProposal/index.tsx
  apps/web/src/views/Voting/Proposal/Details.tsx
  apps/web/src/views/Voting/components/CastVoteModal/DetailsView.tsx
  apps/web/src/views/Voting/components/Proposal/VoteRow.tsx
  packages/uikit/src/components/Link/ScanLink.tsx
  packages/widgets-internal/farm/components/FarmCard/DetailsSection.tsx
  packages/widgets-internal/package.json
  pnpm-lock.yaml
Labels: size/L

#7941 refactor: Remove usePriceCakeUSD hook from farms
  apps/web/src/pages/farms/history.tsx
  apps/web/src/pages/farms/index.tsx
  apps/web/src/state/farms/hooks.ts
  apps/web/src/views/AffiliatesProgram/components/Dashboard/CommissionInfo.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/Reward/LatestReward.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useLeaderboard.tsx
  apps/web/src/views/FarmAuction/components/AuctionCakeBurn.tsx
  apps/web/src/views/FarmAuction/components/AuctionLeaderboard/AuctionLeaderboardTable.tsx
  apps/web/src/views/FarmAuction/components/PlaceBidModal.tsx
  apps/web/src/views/Farms/Farms.tsx
  apps/web/src/views/Farms/FarmsV3.tsx
  apps/web/src/views/Farms/components/FarmCard/HarvestAction.tsx
  apps/web/src/views/Farms/components/FarmCard/StakeAction.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmInfo.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/SingleFarmV3Card.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/HarvestAction.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
  apps/web/src/views/Home/components/Banners/LotteryBanner.tsx
  apps/web/src/views/Home/components/CakeDataRow.tsx
  apps/web/src/views/Home/components/UserBanner/HarvestCard.tsx
  apps/web/src/views/Home/components/WinSection/LotteryCardContent.tsx
  apps/web/src/views/Home/hooks/useGetTopFarmsByApr.tsx
  apps/web/src/views/Ifos/hooks/v2/useGetPublicIfoData.ts
  apps/web/src/views/Ifos/hooks/v3/useGetPublicIfoData.ts
  apps/web/src/views/Lottery/components/BuyTicketsModal/BuyTicketsModal.tsx
  apps/web/src/views/Lottery/components/ClaimPrizesModal/ClaimPrizesInner.tsx
  apps/web/src/views/Lottery/components/Hero.tsx
  apps/web/src/views/Lottery/components/NextDrawCard.tsx
  apps/web/src/views/Lottery/components/PreviousRoundCard/FooterExpanded.tsx
  apps/web/src/views/Lottery/components/RewardBracketDetail.tsx
  apps/web/src/views/Migration/components/v3/Step5.tsx
  apps/web/src/views/Nft/market/components/BuySellModals/BuyModal/index.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/RecentCakeProfitRow.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/VaultCardActions/HasSharesActions.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
  apps/web/src/views/Pools/components/RevenueSharing/BenefitsModal/RevenueSharing.tsx
  apps/web/src/views/Pottery/components/Banner/index.tsx
  apps/web/src/views/Pottery/components/FinishedRounds/AllHistoryCard/PreviousRoundCardBody.tsx
  apps/web/src/views/Pottery/components/Pot/Claim/AvailableWithdraw.tsx
  apps/web/src/views/Pottery/components/Pot/Claim/PrizeToBeClaimed.tsx
  apps/web/src/views/Pottery/components/Pot/YourDeposit.tsx
  apps/web/src/views/Pottery/components/Pot/index.tsx
  apps/web/src/views/Pottery/components/WinRateModal/index.tsx
  apps/web/src/views/TradingReward/components/CurrentRewardPool.tsx
  apps/web/src/views/TradingReward/components/Leaderboard/DesktopResult.tsx
  apps/web/src/views/TradingReward/components/Leaderboard/MobileResult.tsx
  apps/web/src/views/TradingReward/components/Leaderboard/RankingCard.tsx
  apps/web/src/views/TradingReward/components/TopTraders/YourTradingReward/CurrentPeriod.tsx
  apps/web/src/views/TradingReward/components/YourTradingReward/NoCakeLockedOrExtendLock.tsx
  apps/web/src/views/TradingReward/components/YourTradingReward/QualifiedPreview.tsx
Labels: size/L

#7931 feat: Add Wallchain route for selected pair
  apps/web/.env.example
  apps/web/package.json
  apps/web/src/__tests__/translations.test.ts
  apps/web/src/config/wallchain.ts
  apps/web/src/views/Swap/V3Swap/components/RoutesBreakdown.tsx
  apps/web/src/views/Swap/V3Swap/containers/ConfirmSwapModal.tsx
  apps/web/src/views/Swap/V3Swap/containers/SwapCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useSendSwapTransaction.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSwapCallback.ts
  apps/web/src/views/Swap/V3Swap/hooks/useWallchain.ts
  apps/web/src/views/Swap/components/AdvancedSwapDetails.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/widgets/Swap/ApproveModalContent.tsx
  pnpm-lock.yaml
Labels: size/XL

#7936 ci: fix farm action
  .github/workflows/farmConfig.yml
  package.json
  pnpm-lock.yaml
Labels: size/L, automerge

#7947 revert: Lottery with birthday theme (#7937)
  apps/web/public/images/lottery/birthday/banner-bunny-1.png
  apps/web/public/images/lottery/birthday/birthday-cake-icon.png
  apps/web/public/images/lottery/birthday/cake3.png
  apps/web/public/images/lottery/birthday/left-2.png
  apps/web/public/images/lottery/birthday/left-star-1.png
  apps/web/public/images/lottery/birthday/mobile-1.png
  apps/web/public/images/lottery/birthday/mobile-2.png
  apps/web/public/images/lottery/birthday/right-star-1.png
  apps/web/public/images/lottery/birthday/third-cake.png
  apps/web/src/views/Lottery/components/BirthdayDecorations.tsx
  apps/web/src/views/Lottery/components/Hero.tsx
  apps/web/src/views/Lottery/index.tsx
  apps/web/src/views/Lottery/pageSectionStyles.tsx
  packages/localization/src/config/translations.json
Labels: size/L, automerge

#7949 feat: top 10 pair need create at least 4days
  apps/web/src/state/info/queries/pools/poolData.ts
  apps/web/src/state/info/types.ts
  apps/web/src/views/Info/Overview/index.tsx
Labels: size/S

#7948 fix: Approval route type priority
  packages/uikit/src/widgets/Swap/ApproveModalContent.tsx
Labels: size/XS

#7950 fix: cannot swap on l2 chains
  apps/web/src/views/Swap/V3Swap/hooks/useWallchain.ts
Labels: size/XS

#7951 feat: add rochi usdc pool
  packages/farms/constants/1.ts
  packages/tokens/src/1.ts
Labels: size/S

#7920 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XL

#7952 feat: list roci syrup pool
  packages/farms/constants/1.ts
Labels: size/XS

#7953 feat: Update leaderboard time
  apps/web/src/state/predictions/config.ts
Labels: size/XS, automerge

#7955 feat: Birthday nav planet 5
  apps/web/src/components/Menu/config/config.ts
  packages/localization/src/config/translations.json
Labels: size/XS, automerge

#7892 chore: Remove domain packages out of uikit
  packages/uikit/package.json
  packages/uikit/src/components/CurrencyInput/index.stories.tsx
  packages/uikit/src/components/CurrencyLogo/CurrencyLogo.tsx
  packages/uikit/src/components/CurrencyLogo/index.stories.tsx
  packages/uikit/src/shared.ts
  packages/widgets-internal/mockData.ts
  packages/widgets-internal/package.json
  packages/widgets-internal/swap/LiquidityChartRangeInput/index.stories.tsx
  pnpm-lock.yaml
Labels: size/M

#7839 refactor: Move Cake Price check in fetchTokenUSDValue
  apps/web/src/state/pools/index.ts
  apps/web/src/utils/llamaPrice.ts
Labels: size/M

#7961 chore: Fix invalid import
  packages/uikit/src/shared.ts
Labels: size/XS

#7962 chore: Fix import
  packages/uikit/src/shared.ts
Labels: size/XS

#7963 feat: list arb and base farms
  packages/farms/constants/42161.ts
  packages/farms/constants/8453.ts
  packages/tokens/src/8453.ts
  packages/tokens/src/common.ts
Labels: size/M

#7965 chore: remove moonpay quotes from bsc
  apps/web/src/views/BuyCrypto/hooks/usePriceQuoter.ts
Labels: size/XS

#7935 fix: typescript errors cleanup
  apps/web/src/components/FiatOnRampModal/FiatOnRampModal.tsx
  apps/web/src/components/SearchModal/CurrencySearch.tsx
  apps/web/src/state/buyCrypto/actions.ts
  apps/web/src/state/buyCrypto/hooks.ts
  apps/web/src/state/buyCrypto/reducer.ts
  apps/web/src/views/BuyCrypto/components/AccordionDropdown/AccordionItem.tsx
  apps/web/src/views/BuyCrypto/components/OnRampCurrencySelect/index.tsx
  apps/web/src/views/BuyCrypto/constants.ts
  apps/web/src/views/BuyCrypto/containers/BuyCryptoForm.tsx
  apps/web/src/views/BuyCrypto/hooks/useIframeUrlFetcher.ts
  apps/web/src/views/BuyCrypto/hooks/usePriceQuoter.ts
Labels: size/L

#7968 feat: universal-router-polish
  apps/web/src/config/abi/permit2.json
  apps/web/src/hooks/useApproveCallback.ts
  apps/web/src/hooks/usePermit2Allowance.ts
  apps/web/src/hooks/usePermitAllowance.ts
  apps/web/src/state/multicall/hooks.ts
  apps/web/src/state/transactions/hooks.tsx
  apps/web/src/state/transactions/reducer.ts
  apps/web/src/utils/exchange.ts
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/containers/ConfirmSwapModal.tsx
  apps/web/src/views/Swap/V3Swap/containers/MMCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/containers/SwapCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalState.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useSendSwapTransaction.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSwapCallArguments.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSwapCallback.ts
  package.json
  packages/permit2-sdk/abis/Permit2.json
  packages/permit2-sdk/package.json
  packages/permit2-sdk/src/allowanceTransfer.test.ts
  packages/permit2-sdk/src/allowanceTransfer.ts
  packages/permit2-sdk/src/constants.test.ts
  packages/permit2-sdk/src/constants.ts
  packages/permit2-sdk/src/domain.ts
  packages/permit2-sdk/src/index.ts
  packages/permit2-sdk/src/signatureTransfer.test.ts
  packages/permit2-sdk/src/signatureTransfer.ts
  packages/permit2-sdk/src/utils/types.ts
  packages/permit2-sdk/src/utils/utils.ts
  packages/permit2-sdk/test/interop.json
  packages/permit2-sdk/tsup.config.ts
  packages/permit2-sdk/writeInterop.js
  packages/smart-router/evm/v3-router/index.ts
  packages/smart-router/evm/v3-router/smartRouter.ts
  packages/smart-router/evm/v3-router/utils/index.ts
  packages/universal-router-sdk/hardhat.config.ts
  packages/universal-router-sdk/package.json
  packages/universal-router-sdk/src/SwapRouterPancake.ts
  packages/universal-router-sdk/src/abis/ERC20.json
  packages/universal-router-sdk/src/abis/IUniswapV3Pool.json
  packages/universal-router-sdk/src/abis/UniversalRouter.json
  packages/universal-router-sdk/src/entities/protocols/pancakeswap.ts
  packages/universal-router-sdk/src/entities/protocols/unwrapWETH.ts
  packages/universal-router-sdk/src/index.ts
  packages/universal-router-sdk/src/utils/constants.ts
  packages/universal-router-sdk/src/utils/getNativeCurrencyValue.ts
  packages/universal-router-sdk/src/utils/inputTokens.ts
  packages/universal-router-sdk/src/utils/numbers.ts
  packages/universal-router-sdk/src/utils/routerCommands.ts
  packages/universal-router-sdk/src/utils/types.ts
  packages/universal-router-sdk/src/utils/utils.ts
  packages/universal-router-sdk/test/pancakeTrades.test.ts
  packages/universal-router-sdk/test/permit2.test.ts
  packages/universal-router-sdk/test/utils/addresses.ts
  packages/universal-router-sdk/test/utils/client.ts
  packages/universal-router-sdk/test/utils/hexToDecimalString.ts
  packages/universal-router-sdk/test/utils/pancakeswapData.ts
  packages/universal-router-sdk/test/utils/permit2.ts
  packages/universal-router-sdk/tsup.config.ts
  pnpm-lock.yaml
Labels: size/XXL

#7966 fix: (farms): Tapping V3 Row apr cell can't open farms details
  apps/web/src/views/Farms/components/FarmTable/Row.tsx
  packages/uikit/src/hooks/useTooltip/useTooltip.tsx
Labels: size/S

#7974 fix: universal router value type
  packages/universal-router-sdk/src/SwapRouterPancake.ts
Labels: size/S

#7975 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#7976 fix(universal router): TypedDataDomain
  packages/permit2-sdk/src/utils/types.ts
Labels: size/XS, automerge

#7977 chore: remove unused address and wrong unit
  packages/universal-router-sdk/src/utils/constants.ts
Labels: size/XS, automerge

#7973 feat: Predictions with birthday theme
  apps/web/public/images/predictions/birthday/birthday-icon.png
  apps/web/public/images/predictions/birthday/desktop-bunny.png
  apps/web/public/images/predictions/birthday/mobile-bunny.png
  apps/web/src/views/Predictions/Mobile.tsx
  apps/web/src/views/Predictions/components/CollectWinningsPopup.tsx
  apps/web/src/views/Predictions/components/Container.tsx
  apps/web/src/views/Predictions/components/JupiterPredictors.tsx
  apps/web/src/views/Predictions/components/Menu.tsx
  apps/web/src/views/Predictions/components/MobileMenu.tsx
  apps/web/src/views/Predictions/components/PrevNextNav.tsx
  apps/web/src/views/Predictions/index.tsx
  packages/localization/src/config/translations.json
Labels: size/L, automerge

#7978 feat: Prediction leaderboard back to prev version
  apps/web/src/state/predictions/config.ts
  apps/web/src/state/predictions/index.ts
  apps/web/src/views/Predictions/Leaderboard/components/Hero.tsx
  packages/localization/src/config/translations.json
Labels: size/S, automerge

#7979 chore: fix token search issue
  apps/web/src/views/V3Info/components/Search/index.tsx
Labels: size/XS

#7981 feat: Update Birthday nav
  apps/web/src/components/Menu/config/config.ts
  packages/localization/src/config/translations.json
Labels: size/XS, automerge

#7980 chore: add arbitrum v2 subgraph to config
  apps/web/src/utils/graphql.ts
Labels: size/XS

#7983 fix: command abi type
  packages/universal-router-sdk/src/entities/protocols/pancakeswap.ts
  packages/universal-router-sdk/src/entities/protocols/unwrapWETH.ts
  packages/universal-router-sdk/src/utils/routerCommands.ts
Labels: size/L

#7987 chore: Add default import path for evm
  .changeset/modern-feet-talk.md
  packages/smart-router/package.json
Labels: size/XS

#7990 test: v2 universal router swap
  packages/universal-router-sdk/src/utils/constants.ts
  packages/universal-router-sdk/src/utils/types.ts
  packages/universal-router-sdk/test/__snapshots__/trade.test.ts.snap
  packages/universal-router-sdk/test/fixtures/address.ts
  packages/universal-router-sdk/test/fixtures/clients.ts
  packages/universal-router-sdk/test/fixtures/constants/tokens.ts
  packages/universal-router-sdk/test/trade.test.ts
  packages/universal-router-sdk/test/utils/buildTrade.ts
  packages/universal-router-sdk/test/utils/permit.ts
  packages/universal-router-sdk/test/utils/signPermit.ts
  packages/universal-router-sdk/vitest.config.ts
Labels: size/XL, automerge

#7992 chore: Default to use subgraph fallbacks
  .changeset/smart-files-smile.md
  apis/routing/src/constants.ts
  apis/routing/src/pools.ts
  apis/routing/src/subgraphPoolBackup.ts
  apis/routing/wrangler.toml
  packages/smart-router/evm/v3-router/providers/getCommonTokenPrices.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/getV3CandidatePools.ts
Labels: size/M

#7995 chore: Remove fixed staking from homepage
  apps/web/src/views/Home/components/EcoSystemSection/index.tsx
Labels: size/S

#7994 test: universal router stableSwap
  packages/universal-router-sdk/test/__snapshots__/trade.test.ts.snap
  packages/universal-router-sdk/test/fixtures/address.ts
  packages/universal-router-sdk/test/fixtures/constants/chains.ts
  packages/universal-router-sdk/test/fixtures/constants/tokens.ts
  packages/universal-router-sdk/test/trade.test.ts
  packages/universal-router-sdk/test/utils/buildTrade.ts
Labels: size/L

#7996 feat: Birthday nav palnet 7
  apps/web/src/components/Menu/config/config.ts
  packages/localization/src/config/translations.json
Labels: size/XS, automerge
