Repository pancakeswap/pancake-frontend, pull requests merged in 2023-01, with the labels that each got.

#5756 chore: Bump up next js
  apps/aptos/next.config.mjs
  apps/aptos/package.json
  apps/bridge/next.config.mjs
  apps/bridge/package.json
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/src/views/Farms/components/BCakeBoosterCard.tsx
  apps/web/src/views/Home/components/Banners/AptosBanner.tsx
  apps/web/src/views/Home/components/Banners/CompetitionBanner.tsx
  apps/web/src/views/Home/components/Banners/IFOBanner.tsx
  apps/web/src/views/Home/components/Banners/LotteryBanner.tsx
  apps/web/src/views/Home/components/Banners/PerpetualBanner.tsx
  apps/web/src/views/Home/components/Hero.tsx
  yarn.lock
Labels: size/L

#5765 fix(Swap&Liquidity): PercentButton only appears when maxAmount has balance
  apps/web/src/components/CurrencyInputPanel/index.tsx
Labels: size/XS

#5769 fix(Swap&Farms): PercentButton only appears when maxAmount has balance
  apps/web/src/components/CurrencyInputPanel/index.tsx
  packages/uikit/src/widgets/Modal/ModalInput.tsx
Labels: size/S

#5770 fix: (farms): Show cake balance in boosted proxy address
  apps/web/src/views/Farms/components/BCakeBoosterCard.tsx
  apps/web/src/views/Farms/hooks/useBCakeProxyBalance.ts
  apps/web/src/views/Home/hooks/useFarmsWithBalance.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#5771 fix: Nested a tags warning in cake booster card
  apps/web/src/views/Farms/components/BCakeBoosterCard.tsx
Labels: size/XS

#5774 fix(NFT): Collection card key warning
  apps/web/src/views/Nft/market/components/CollectibleCard/CollectionCardWithVolume.tsx
Labels: size/XS

#5739 perf: Use direct onchain call to reduce bundle size
  apps/web/src/components/Menu/hooks/useMenuItemsStatus.ts
  apps/web/src/hooks/useLockedEndNotification.tsx
  apps/web/src/hooks/useUserCakeLockStatus.ts
  apps/web/src/views/Pools/components/LockedPool/Buttons/ConvertToFlexibleButton.tsx
  apps/web/src/views/Pools/components/LockedPool/hooks/useLockedPool.tsx
Labels: size/M

#5263 feat: (profile): Add enable button to swap required cake for change profile pic
  apps/web/src/hooks/useCakeEnable.tsx
  apps/web/src/views/Pools/components/LockedPool/Common/ExtendEnable.tsx
  apps/web/src/views/Profile/components/EditProfileModal/StartView.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#5438 perf: Reduce onchain calls in usetoken hook when token is not available on lists
  apps/web/src/hooks/Tokens.ts
Labels: size/M

#5766 feat: (liquidity): Add lp apr stable swap add liquidity
  apps/web/src/hooks/useStableSwapAPR.ts
  apps/web/src/state/info/hooks.ts
  apps/web/src/state/info/queries/pools/poolData.ts
  apps/web/src/utils/getAprsForStableFarm.ts
  apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
  apps/web/src/views/Info/Pools/PoolPage.tsx
Labels: size/L

#5778 chore: Downgrade nextjs to 13.0.7
  apps/aptos/next.config.mjs
  apps/aptos/package.json
  apps/bridge/next.config.mjs
  apps/bridge/package.json
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/src/views/Farms/components/BCakeBoosterCard.tsx
  apps/web/src/views/Home/components/Banners/AptosBanner.tsx
  apps/web/src/views/Home/components/Banners/CompetitionBanner.tsx
  apps/web/src/views/Home/components/Banners/IFOBanner.tsx
  apps/web/src/views/Home/components/Banners/LotteryBanner.tsx
  apps/web/src/views/Home/components/Banners/PerpetualBanner.tsx
  apps/web/src/views/Home/components/Hero.tsx
  yarn.lock
Labels: size/L

#5783 feat: Add liq filter for token highlight list
  apps/web/src/views/Swap/components/HotTokenList/index.tsx
Labels: size/XS

#5784 style(limit-order): LoadingContent
  apps/web/src/views/LimitOrders/components/LimitOrderTable/DetailLimitOrderModal.tsx
Labels: size/S, automerge

#5786 feat: List ankrbnb
  packages/tokens/src/56.ts
Labels: size/XS

#5788 perf: Use theme from context instead of new object for each call
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/Icons/BunnyKnownPlaceholder.tsx
  apps/bridge/components/layerZero/PoweredBy.tsx
  apps/web/src/components/Menu/hooks/useMenuItems.ts
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/Icons/BunnyKnownPlaceholder.tsx
  apps/web/src/views/Info/components/InfoCharts/CandleChart/index.tsx
  apps/web/src/views/Lottery/components/BuyTicketsButton.tsx
  apps/web/src/views/PancakeSquad/components/ArtistSection/index.tsx
  apps/web/src/views/Predictions/RoundMultiplierArrows.tsx
Labels: size/S

#5794 feat(aptos-ifo): Clean up
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardTokens.tsx
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoVestingCard/IfoVestingFooter.tsx
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoVestingCard/ReleasedTokenInfo.tsx
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoVestingCard/TotalAvailableClaim.tsx
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoVestingCard/TotalPurchased.tsx
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoVestingCard/index.tsx
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/VestingAvailableToClaim.tsx
  apps/aptos/views/Ifos/components/IfoVesting/VestingPeriod/Info.tsx
  apps/aptos/views/Ifos/constants.ts
  apps/aptos/views/Ifos/generated/ifo.ts
  apps/aptos/views/Ifos/hooks/useIfoResources.ts
  apps/aptos/views/Ifos/hooks/v3/useGetWalletIfoData.ts
  apps/aptos/views/Ifos/utils/index.ts
Labels: size/M

#5793 chore: Bump up jotai
  apps/aptos/components/Liquidity/state/add/index.ts
  apps/aptos/components/Liquidity/state/remove/index.ts
  apps/web/package.json
  packages/token-lists/package.json
  yarn.lock
Labels: size/S

#5792 chore: (uikit): Remove unused lodash imports
  packages/uikit/package.json
  packages/uikit/src/components/Balance/Balance.tsx
Labels: size/XS

#5785 chore: StableSwap farm wording
  apps/web/src/state/farms/selectors.ts
  apps/web/src/views/Farms/components/FarmCard/ApyButton.tsx
  apps/web/src/views/Farms/components/FarmCard/FarmCard.tsx
  apps/web/src/views/Farms/components/FarmTable/Apr.tsx
  apps/web/src/views/Farms/components/FarmTable/FarmTable.tsx
  packages/farms/constants/56.ts
  packages/farms/src/types.ts
  packages/localization/src/config/translations.json
  packages/uikit/src/components/RoiCalculatorModal/RoiCalculatorFooter.tsx
  packages/uikit/src/components/RoiCalculatorModal/RoiCalculatorModal.tsx
Labels: size/L

#5806 feat: Bridge meta title
  apps/bridge/pages/_app.tsx
Labels: size/XS, automerge

#5812 chore(proxy): Block empty body
  apis/proxy-worker/src/index.ts
Labels: size/XS

#5808 perf: PageSection move to uikit
  apps/web/src/components/PageSection/types.ts
  apps/web/src/views/FarmAuction/index.tsx
  apps/web/src/views/Home/index.tsx
  apps/web/src/views/Lottery/index.tsx
  apps/web/src/views/Nft/market/Home/index.tsx
  apps/web/src/views/Pottery/components/FinishedRounds/index.tsx
  apps/web/src/views/TradingCompetition/EasterCompetition.tsx
  apps/web/src/views/TradingCompetition/FanTokenCompetition.tsx
  apps/web/src/views/TradingCompetition/Footer.tsx
  apps/web/src/views/TradingCompetition/MoDCompetition.tsx
  apps/web/src/views/TradingCompetition/MoboxCompetition.tsx
  apps/web/src/views/TradingCompetition/components/PrizesInfoSection.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanksSection.tsx
  packages/uikit/src/components/PageSection/CurvedDivider.tsx
  packages/uikit/src/components/PageSection/PageSection.tsx
  packages/uikit/src/components/PageSection/index.tsx
  packages/uikit/src/components/PageSection/svg/CurvedSvg.tsx
  packages/uikit/src/components/PageSection/types.ts
  packages/uikit/src/components/index.ts
Labels: size/L, automerge

#5816 feat(farm): List SDAO cross chain farming
  apps/web/public/images/tokens/0x90Ed8F1dc86388f14b64ba8fb4bbd23099f18240.png
  apps/web/public/images/tokens/0x90Ed8F1dc86388f14b64ba8fb4bbd23099f18240.svg
  packages/farms/constants/1.ts
  packages/tokens/src/1.ts
Labels: size/S, automerge

#5817 chore: add token icon for eth SDAO
  apps/web/public/images/1/tokens/0x993864E43Caa7F7F12953AD6fEb1d1Ca635B875F.png
  apps/web/public/images/1/tokens/0x993864E43Caa7F7F12953AD6fEb1d1Ca635B875F.svg
  apps/web/src/utils/getLiquidityUrlPathParts.ts
Labels: size/S, automerge

#5805 perf: NotFound move to uikit
  apps/aptos/pages/404.tsx
  apps/web/src/pages/404.tsx
  apps/web/src/pages/_error.tsx
  apps/web/src/views/Voting/Proposal/Overview.tsx
  packages/uikit/src/components/NotFound/NotFound.tsx
  packages/uikit/src/components/NotFound/index.tsx
  packages/uikit/src/components/index.ts
Labels: size/M, automerge

#5818 fix: Chain url
  apps/aptos/components/NetworkSwitcher.tsx
  apps/aptos/config/ChainName.ts
  apps/web/src/components/TransactionDetailModal/FarmTransactionModal/FarmInfo.tsx
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/Info/Tokens/TokenPage.tsx
Labels: size/S, automerge

#5815 refactor: Move PaginationButton to uikit
  apps/web/src/views/Nft/market/ActivityHistory/ActivityHistory.tsx
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/ActivityCard.tsx
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/ForSaleTableCard/index.tsx
  apps/web/src/views/Nft/market/components/PaginationButtons.tsx
  apps/web/src/views/Profile/components/ActivityHistory/index.tsx
  packages/uikit/src/components/PaginationButton/PaginationButton.tsx
  packages/uikit/src/components/PaginationButton/index.tsx
  packages/uikit/src/components/index.ts
Labels: size/L, automerge

#5791 feat: Info stableSwap fee display adjustment
  apps/web/src/state/info/hooks.ts
  apps/web/src/state/info/queries/pools/poolData.ts
  apps/web/src/state/info/types.ts
  apps/web/src/views/Info/Pools/PoolPage.tsx
Labels: size/M

#5826 fix: info pool page chainId issue
  apps/web/src/views/Info/Pools/PoolPage.tsx
Labels: size/XS

#5821 fix(web): Keep chainId as backward compatible
  apps/web/src/config/chains.ts
  apps/web/src/hooks/useAccountEventListener.ts
  apps/web/src/hooks/useActiveChainId.ts
  apps/web/src/hooks/useActiveWeb3React.ts
  apps/web/src/hooks/useAuth.tsx
  apps/web/src/hooks/useSwitchNetwork.ts
  apps/web/src/utils/getLiquidityUrlPathParts.ts
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/Info/Tokens/TokenPage.tsx
Labels: size/M

#5827 fix(aptos): Add project link
  apps/aptos/config/constants/tokens/1.ts
Labels: size/XS

#5829 fix(aptos-pool): Avoid APR mismatch for pairs with different decimals
  apps/aptos/components/Pools/transformers/transformPool.ts
Labels: size/XS

#5830 fix(Aptos): Sort Latest Pool
  apps/aptos/components/Pools/hooks/usePoolsList.ts
  apps/aptos/components/Pools/transformers/transformPool.ts
Labels: size/XS

#5838 chore(NFT): Change filter theme
  apps/web/src/views/Nft/market/Collection/Items/Filters.tsx
Labels: size/XS

#5843 chore: Update Sentry ID in vercel build
  apps/web/sentry.client.config.js
  apps/web/sentry.server.config.js
Labels: size/XS

#5842 refactor: Remove duplicate deserialize farm
  apps/aptos/state/farms/hook.ts
  apps/web/src/config/constants/index.ts
  apps/web/src/state/farms/fetchFarmsWithAuctions.ts
  apps/web/src/state/farms/selectors.ts
  packages/farms/src/const.ts
  packages/farms/src/deserializeFarm.ts
  packages/farms/src/index.ts
Labels: size/L

#5848 chore: Update bCake CB constant
  apps/web/src/views/Farms/components/YieldBooster/components/BCakeCalculator.tsx
Labels: size/XS

#5850 fix(web): decimals with 0 in useToken
  apps/web/src/hooks/Tokens.ts
Labels: size/XS

#5851 fix: BCake boosted calculator and display issue
  apps/web/src/views/Farms/components/FarmCard/ApyButton.tsx
  apps/web/src/views/Farms/components/FarmCard/CardActionsContainer.tsx
  apps/web/src/views/Farms/components/FarmCard/StakeAction.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
  apps/web/src/views/Farms/components/YieldBooster/components/BCakeCalculator.tsx
  apps/web/src/views/Farms/components/YieldBooster/components/BoostedAction.tsx
  apps/web/src/views/Farms/components/YieldBooster/hooks/useGetBoostedAPR.ts
  apps/web/src/views/Migration/components/MigrationStep2/NewFarm/StakeButton.tsx
  packages/farms/src/deserializeFarm.ts
  packages/farms/src/fetchFarms.ts
  packages/farms/src/types.ts
Labels: size/M

#5847 feat(ifo): List ESPL IFO
  apps/web/public/images/achievements/ifo-arena.svg
  apps/web/public/images/ifos/arena-bg.png
  apps/web/public/images/tokens/0xCfFD4D3B517b77BE32C76DA768634dE6C738889B.png
  apps/web/src/config/constants/campaigns.ts
  apps/web/src/config/constants/ifo.ts
  apps/web/src/views/Ifos/hooks/v3/useGetPublicIfoData.ts
  packages/tokens/src/56.ts
Labels: size/L

#5846 chore(Voting): When on a mobile, show fewer vote results
  apps/web/src/views/Voting/Proposal/Votes.tsx
Labels: size/XS

#5854 chore: Try to update sentry id in production
  apps/web/next.config.mjs
  apps/web/sentry.client.config.js
  apps/web/sentry.server.config.js
Labels: size/XS

#5855 chore: Remove Sentry test
  apps/web/next.config.mjs
Labels: size/XS

#5856 chore: remove Sentry comment
  apps/web/next.config.mjs
Labels: size/XS

#5857 chore: Update release id
  apps/web/sentry.client.config.js
Labels: size/XS

#5858 chore: Remove sentry release
  apps/web/sentry.client.config.js
Labels: size/XS

#5841 refactor: Remove duplicate token sorting
  apps/aptos/components/SearchModal/sorting.ts
  apps/web/src/components/SearchModal/sorting.ts
  packages/swap-sdk-core/src/utils.ts
  packages/swap-sdk-core/test/token.test.ts
  packages/swap-sdk-core/test/utils.test.ts
Labels: size/L

#5840 refactor: Merge same conditions
  apps/web/src/components/Menu/GlobalSettings/SettingsModal.tsx
Labels: size/XS

#5834 perf: (farms): Use memoized provider value
  apps/web/src/views/Farms/components/YieldBooster/components/ProxyFarmContainer.tsx
Labels: size/S

#5833 chore: (pools): Move default parameter to last
  apps/web/src/views/Pools/hooks/useStakePool.ts
Labels: size/XS

#5832 chore: (voting): Use different name interface than defined one
  apps/web/src/views/Voting/CreateProposal/Choices.tsx
  apps/web/src/views/Voting/CreateProposal/index.tsx
  apps/web/src/views/Voting/CreateProposal/types.ts
Labels: size/S

#5831 perf: Use memoized provider value in aptos
  apps/aptos/components/Farms/components/Farms.tsx
  apps/aptos/views/Ifos/contexts/IfoContext.tsx
Labels: size/S

#5862 chore(farm): Push cake price route code
  apis/farms/src/handler.ts
  apis/farms/src/index.ts
  apps/aptos/hooks/useStablePrice.ts
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/pages/index.tsx
Labels: size/M

#5865 feat(web): Add log swap type
  apps/web/src/hooks/useSwapCallback.ts
  apps/web/src/utils/log.ts
  apps/web/src/views/Swap/SmartSwap/hooks/useSwapCallback.ts
  apps/web/src/views/Swap/StableSwap/components/StableSwapCommitButton.tsx
Labels: size/S

#5866 chore(web): Rename log type
  apps/web/src/hooks/useSwapCallback.ts
  apps/web/src/utils/log.ts
Labels: size/XS

#5867 feat(farm/pool): List ARENA
  apps/web/src/config/constants/pools.tsx
  packages/farms/constants/56.ts
Labels: size/S, automerge

#5870 fix(swap): Not show trade info for wrap and unwrap
  apps/web/src/views/Swap/SmartSwap/index.tsx
Labels: size/XS

#5873 refactor: (farms): Remove duplicate intersection observer
  apps/aptos/hooks/useIntersectionObserver.ts
Labels: size/M

#5872 refactor: Remove duplicate debounced change handler
  apps/web/src/hooks/useDebouncedChangeHandler.ts
  apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/index.tsx
Labels: size/M

#5883 perf: Use memoized functions for disclaimer modal props
  apps/web/src/views/Farms/index.tsx
  apps/web/src/views/LimitOrders/components/ClaimWarning.tsx
  apps/web/src/views/Predictions/components/RiskDisclaimer.tsx
Labels: size/S

#5760 chore: Bump up wagmi
  apps/bridge/package.json
  apps/web/package.json
  apps/web/src/config/wallet.ts
  packages/wagmi/package.json
  yarn.lock
Labels: size/XL

#5823 refactor: Remove duplicate confirm price impact alert
  apps/aptos/components/Swap/confirmPriceImpactWithoutFee.ts
  apps/aptos/pages/swap.tsx
  apps/web/src/views/Swap/SmartSwap/components/SmartSwapCommitButton.tsx
  apps/web/src/views/Swap/components/SwapCommitButton.tsx
  apps/web/src/views/Swap/components/confirmPriceImpactWithoutFee.ts
  packages/uikit/src/widgets/Swap/confirmPriceImpactWithoutFee.ts
  packages/uikit/src/widgets/Swap/index.ts
Labels: size/L

#5879 perf: (liquidity): Use memoized value in stable lp mint
  apps/web/src/views/AddLiquidity/AddStableLiquidity/hooks/useStableLPDerivedMintInfo.tsx
Labels: size/M

#5819 feat: (farms): Enhance farm query search
  apps/aptos/components/Farms/components/FarmTable/FarmTable.tsx
  apps/aptos/components/Farms/components/Farms.tsx
  apps/aptos/utils/latinise.ts
  apps/web/src/utils/latinise.ts
  apps/web/src/views/Farms/Farms.tsx
  apps/web/src/views/Farms/components/FarmTable/FarmTable.tsx
  packages/farms/src/filterFarmsByQuery.ts
  packages/farms/src/index.ts
Labels: size/M

#4670 fix: (prediction): Soon cards entry start time
  apps/web/src/state/predictions/index.ts
  apps/web/src/views/Predictions/components/RoundCard/SoonRoundCard.tsx
  apps/web/src/views/Predictions/hooks/usePollPredictions.ts
  apps/web/src/views/Predictions/index.tsx
Labels: size/L

#5887 feat: Move ReactMarkdown to uikit
  apps/web/package.json
  apps/web/src/components/ReactMarkdown/index.tsx
  apps/web/src/views/LimitOrders/components/LimitOrderTable/CellFormat.tsx
  apps/web/src/views/LimitOrders/components/LimitOrderTable/TextIcon.tsx
  apps/web/src/views/Voting/CreateProposal/index.tsx
  apps/web/src/views/Voting/Proposal/Overview.tsx
  packages/uikit/package.json
  packages/uikit/src/components/ReactMarkdown/ReactMarkdown.tsx
  packages/uikit/src/components/ReactMarkdown/index.tsx
  packages/uikit/src/components/ReactMarkdown/styles.tsx
  packages/uikit/src/components/index.ts
Labels: size/M, automerge

#5888 feat: Blog
  .changeset/config.json
  README.md
  apps/blog/.env
  apps/blog/.env.example
  apps/blog/.eslintrc
  apps/blog/.gitignore
  apps/blog/README.md
  apps/blog/components/Menu.tsx
  apps/blog/components/PageMeta.tsx
  apps/blog/next-env.d.ts
  apps/blog/next.config.mjs
  apps/blog/package.json
  apps/blog/pages/404.tsx
  apps/blog/pages/_app.tsx
  apps/blog/pages/_document.tsx
  apps/blog/pages/api/articles.tsx
  apps/blog/pages/blog/article/[slug].tsx
  apps/blog/pages/blog/article/index.tsx
  apps/blog/pages/blog/index.tsx
  apps/blog/public/images/how_it_work.png
  apps/blog/tsconfig.json
  apps/blog/views/Blog/components/Article/AllArticle/index.tsx
  apps/blog/views/Blog/components/Article/ArticleSortSelect.tsx
  apps/blog/views/Blog/components/Article/ArticleView.tsx
  apps/blog/views/Blog/components/Article/CardArticle.tsx
  apps/blog/views/Blog/components/Article/CategoriesSelector.tsx
  apps/blog/views/Blog/components/Article/SingleArticle/ArticleInfo.tsx
  apps/blog/views/Blog/components/Article/SingleArticle/HowItWork.tsx
  apps/blog/views/Blog/components/Article/SingleArticle/SimilarArticles.tsx
  apps/blog/views/Blog/components/Article/SingleArticle/SocialIcon.tsx
  apps/blog/views/Blog/components/Article/SingleArticle/index.tsx
  apps/blog/views/Blog/components/BlogCard.tsx
  apps/blog/views/Blog/components/ChefsChoice/index.tsx
  apps/blog/views/Blog/components/MoreButton.tsx
  apps/blog/views/Blog/components/NewBlog.tsx
  apps/blog/views/Blog/components/SearchBar.tsx
  apps/blog/views/Blog/components/SkeletonArticle.tsx
  apps/blog/views/Blog/hooks/getArticle.ts
  apps/blog/views/Blog/hooks/useAllArticle.ts
  apps/blog/views/Blog/hooks/useSearchBarArticle.ts
  apps/blog/views/Blog/index.tsx
  apps/blog/views/Blog/types.ts
  apps/blog/views/Blog/utils/api.ts
  apps/blog/views/Blog/utils/transformArticle.ts
  apps/web/src/__tests__/translations.test.ts
  package.json
  packages/localization/src/config/translations.json
  packages/uikit/src/components/LangSelector/index.tsx
  packages/uikit/src/components/index.ts
Labels: size/XXL

#5837 feat: AvengerDAO integration
  apis/farms/src/helper.ts
  apis/farms/src/index.ts
  apis/proxy-worker/src/index.ts
  apps/web/.env.example
  apps/web/package.json
  apps/web/src/components/Menu/GlobalSettings/SettingsModal.tsx
  apps/web/src/components/SearchModal/ImportToken.tsx
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/pages/api/risk/[chainId]/[address].ts
  apps/web/src/state/user/hooks/useUserTokenRisk.ts
  apps/web/src/views/LimitOrders/index.tsx
  apps/web/src/views/Swap/SmartSwap/index.tsx
  apps/web/src/views/Swap/components/AccessRisk/RiskMessage.tsx
  apps/web/src/views/Swap/components/AccessRisk/index.tsx
  apps/web/src/views/Swap/components/Chart/BasicChart.tsx
  apps/web/src/views/Swap/components/SwapForm.tsx
  apps/web/src/views/Swap/hooks/fetchTokenRisk.ts
  packages/localization/src/config/translations.json
  packages/uikit/src/components/Button/theme.ts
  packages/uikit/src/components/Button/types.ts
  packages/uikit/src/components/Card/StyledCard.tsx
  packages/uikit/src/util/animationToolkit.ts
  packages/worker-utils/index.ts
  packages/worker-utils/package.json
  yarn.lock
Labels: size/XL

#5892 chore: Yarn lock
  yarn.lock
Labels: size/XS

#5891 fix(bridge): Menu item
  apps/bridge/components/Menu.tsx
Labels: size/XS, automerge

#5814 feat: Rebase farm multipliers
  apps/web/src/state/farms/fetchFarms.ts
  apps/web/src/state/farmsV1/fetchFarms.ts
  apps/web/src/views/Migration/components/Farm/ActionPanel/Multiplier.tsx
  apps/web/src/views/Migration/components/Farm/Cells/Multiplier.tsx
  packages/farms/src/fetchFarms.ts
  packages/localization/src/config/translations.json
  packages/uikit/src/components/RoiCalculatorModal/RoiCalculatorFooter.tsx
  packages/uikit/src/widgets/Farm/components/FarmTable/Multiplier.tsx
Labels: size/L, automerge

#5897 fix(nft): try catch on chain total supply in collection
  apps/web/src/state/nftMarket/helpers.ts
Labels: size/S

#5877 feat: token highlights for ETH
  apps/web/src/config/constants/info.ts
  apps/web/src/hooks/useSwapHotTokenDisplay.ts
  apps/web/src/state/info/constant.ts
  apps/web/src/state/info/hooks.ts
  apps/web/src/state/info/queries/tokens/tokenData.ts
  apps/web/src/state/info/queries/tokens/topTokens.ts
  apps/web/src/state/info/types.ts
  apps/web/src/views/Swap/SmartSwap/index.tsx
  apps/web/src/views/Swap/components/CurrencyInputHeader.tsx
  apps/web/src/views/Swap/components/HotTokenList/SwapTokenTable.tsx
  apps/web/src/views/Swap/components/HotTokenList/index.tsx
  apps/web/src/views/Swap/components/HotTokenList/useList.tsx
  apps/web/src/views/Swap/index.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/hooks/useTooltip/useTooltip.tsx
Labels: size/L

#5902 fix(web): Only show once on mobile tooltip highlight
  apps/web/src/views/Swap/components/CurrencyInputHeader.tsx
Labels: size/S

#5903 chore: fix eth token path for token highlight
  apps/web/src/views/Info/Tokens/TokenPage.tsx
  apps/web/src/views/Info/components/InfoNav/index.tsx
  apps/web/src/views/Swap/components/HotTokenList/SwapTokenTable.tsx
Labels: size/S

#5869 feat: CNY theme
  apps/web/public/images/cny-asset/ball-1.png
  apps/web/public/images/cny-asset/ball-2.png
  apps/web/public/images/cny-asset/ball-3.png
  apps/web/public/images/cny-asset/ball-4.png
  apps/web/public/images/cny-asset/ball-5.png
  apps/web/public/images/cny-asset/ball-6.png
  apps/web/public/images/cny-asset/ball-7.png
  apps/web/public/images/cny-asset/banner-1.png
  apps/web/public/images/cny-asset/banner-2.png
  apps/web/public/images/cny-asset/banner-3.png
  apps/web/public/images/cny-asset/c-1.png
  apps/web/public/images/cny-asset/c-2.png
  apps/web/public/images/cny-asset/c-3.png
  apps/web/public/images/cny-asset/c-4.png
  apps/web/public/images/cny-asset/cny-frame.png
  apps/web/public/images/cny-asset/cny-lantern-1.png
  apps/web/public/images/cny-asset/cny-lantern-2.png
  apps/web/public/images/cny-asset/l-1.png
  apps/web/public/images/cny-asset/l-2.png
  apps/web/public/images/cny-asset/l-3.png
  apps/web/public/images/cny-asset/l-4.png
  apps/web/public/images/cny-asset/l-5.png
  apps/web/public/images/cny-asset/l-6.png
  apps/web/public/images/cny-asset/p-1.png
  apps/web/public/images/cny-asset/p-2.png
  apps/web/public/images/cny-asset/redpocket.png
  apps/web/public/images/pottery/banner-bunny-cny.png
  apps/web/src/hooks/useChineseNewYearEffect.ts
  apps/web/src/views/Home/components/Banners/CnyBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  apps/web/src/views/Home/index.tsx
  apps/web/src/views/Lottery/components/CnyLotteryDraw.tsx
  apps/web/src/views/Lottery/components/Hero.tsx
  apps/web/src/views/Lottery/components/LotteryCnyEffect.tsx
  apps/web/src/views/Lottery/index.tsx
  apps/web/src/views/Lottery/pageSectionStyles.tsx
  apps/web/src/views/Pottery/components/Banner/index.tsx
  apps/web/src/views/Pottery/components/FinishedRounds/index.tsx
  apps/web/src/views/Pottery/components/Pot/PotteryCnyEffect.tsx
  apps/web/src/views/Pottery/components/Pot/index.tsx
  apps/web/src/views/Pottery/index.tsx
  packages/localization/src/config/translations.json
Labels: size/XL, automerge

#5904 style: Banner css
  apps/web/src/views/Home/components/Banners/CnyBanner.tsx
Labels: size/S, automerge

#5898 feat: (pools): Add tooltip to aptos pool end stat
  apps/aptos/components/Pools/components/PoolCard/PoolStatsInfo.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#5911 chore: Typos
  apps/aptos/contracts/smartchef/constants.ts
  apps/aptos/state/user/phishingBanner.ts
Labels: size/S

#5910 fix: (pools): Use ledger timestamp for aptos pools instead of client timestamp
  apps/aptos/components/Pools/hooks/usePoolsList.ts
  apps/aptos/components/Pools/transformers/transformPool.ts
  apps/aptos/components/Pools/utils/getSecondsLeftFromNow.ts
Labels: size/M

#5907 chore: Use optional chain for callbacks
  apps/aptos/components/Pools/components/PoolCard/CollectModalContainer.tsx
  apps/aptos/components/Pools/components/PoolCard/StakeModalContainer.tsx
  apps/web/src/views/Pools/components/Modals/StakeModal.tsx
Labels: size/XS

#5912 style: Update css
  apps/web/src/hooks/useChineseNewYearEffect.ts
  apps/web/src/views/Home/components/Banners/CnyBanner.tsx
  apps/web/src/views/Home/components/Banners/MultipleBanner.tsx
  apps/web/src/views/Home/components/Hero.tsx
  apps/web/src/views/Home/components/MetricsSection/index.tsx
Labels: size/M, automerge

#5920 perf: (farms): Use constant for farms small amount balance check
  apps/web/src/views/Farms/components/FarmCard/HarvestAction.tsx
  packages/uikit/src/widgets/Farm/components/FarmTable/Actions/HarvestAction.tsx
  packages/uikit/src/widgets/Farm/constants.ts
  packages/uikit/src/widgets/Farm/index.ts
Labels: size/S

#5919 chore: Typo swr immutable hook
  apps/aptos/pages/swap.tsx
  apps/aptos/state/lists/updater.tsx
  apps/web/src/state/lists/updater.ts
Labels: size/S

#5918 feat: (farms): Handle small amounts in bcake proxy balance warning
  apps/web/src/views/Farms/hooks/useBCakeProxyBalance.ts
Labels: size/S

#5917 feat: (aptos): Use ledger timestamp for pool stats info
  apps/aptos/components/Pools/components/PoolCard/PoolStatsInfo.tsx
  apps/aptos/components/Pools/hooks/usePoolsList.ts
  apps/aptos/hooks/useLedgerTimestamp.ts
Labels: size/M

#5906 chore: Bump up swr
  apps/web/package.json
  apps/web/src/hooks/useSWRContract.ts
  packages/wagmi/package.json
  yarn.lock
Labels: size/S

#5901 feat(BoosterROICalculator): Use the helpicon for the cake locked tooltip
  apps/web/src/views/Farms/components/YieldBooster/components/BCakeCalculator.tsx
Labels: size/M

#5926 chore: Bump up jotai
  apps/web/package.json
  packages/token-lists/package.json
  yarn.lock
Labels: size/S

#5822 perf: (uikit): Use memo in uikit providers to reduce renders
  packages/localization/src/Provider.tsx
  packages/uikit/src/components/Message/Message.tsx
  packages/uikit/src/contexts/ToastsContext/Provider.tsx
  packages/uikit/src/widgets/Menu/Menu.tsx
  packages/uikit/src/widgets/Modal/ModalContext.tsx
Labels: size/M

#5828 refactor: Remove duplicate import list, fix style issues
  apps/aptos/components/Logo/ListLogo.tsx
  apps/aptos/components/Logo/index.ts
  apps/aptos/components/SearchModal/CurrencySearchModal.tsx
  apps/aptos/components/SearchModal/ImportList.tsx
  apps/aptos/components/SearchModal/ImportRow.tsx
  apps/aptos/components/SearchModal/ImportToken.tsx
  apps/aptos/components/SearchModal/ManageLists.tsx
  apps/web/src/components/Logo/ListLogo.tsx
  apps/web/src/components/Logo/index.ts
  apps/web/src/components/SearchModal/CurrencySearchModal.tsx
  apps/web/src/components/SearchModal/ImportList.tsx
  apps/web/src/components/SearchModal/ImportRow.tsx
  apps/web/src/components/SearchModal/ImportToken.tsx
  apps/web/src/components/SearchModal/ManageLists.tsx
  packages/uikit/src/widgets/Swap/ImportList.tsx
  packages/uikit/src/widgets/Swap/ListLogo.tsx
  packages/uikit/src/widgets/Swap/index.ts
Labels: size/XL

#5861 refactor: (prediction): Remove duplicate round response
  apps/web/src/state/predictions/bnbQueries.ts
  apps/web/src/state/predictions/bnbTransformers.ts
  apps/web/src/state/predictions/cakeQueries.ts
  apps/web/src/state/predictions/cakeTransformers.ts
  apps/web/src/state/predictions/responseType.ts
  apps/web/src/state/predictions/tokenTransformers.ts
Labels: size/L

#5787 feat: (swap): Use lightweight charts for swap instead of recharts
  apps/web/src/components/ChartLoaders/BarChartLoaderSVG.tsx
  apps/web/src/components/ChartLoaders/CandleChartLoaderSVG.tsx
  apps/web/src/components/ChartLoaders/LineChartLoaderSVG.tsx
  apps/web/src/components/ChartLoaders/index.tsx
  apps/web/src/views/Info/components/InfoCharts/BarChart/index.tsx
  apps/web/src/views/Info/components/InfoCharts/CandleChart/index.tsx
  apps/web/src/views/Info/components/InfoCharts/LineChart/index.tsx
  apps/web/src/views/Predictions/components/ChainlinkChart.tsx
  apps/web/src/views/Swap/components/Chart/BasicChart.tsx
  apps/web/src/views/Swap/components/Chart/SwapLineChart.tsx
  apps/web/src/views/Swap/components/Chart/TradingViewChart.tsx
Labels: size/L

#5932 fix: Trust Wallet connector
  apps/web/src/config/wallet.ts
  apps/web/src/utils/wagmi.ts
  apps/web/vitest.config.ts
  packages/wagmi/connectors/trustWallet/index.ts
  packages/wagmi/connectors/trustWallet/package.json
  packages/wagmi/connectors/trustWallet/trustWallet.ts
  packages/wagmi/package.json
  packages/wagmi/tsup.config.ts
Labels: size/L

#5933 chore: Fix sonar bugs
  apis/farms/src/index.ts
  apps/blog/next.config.mjs
  apps/web/src/views/Pottery/components/FinishedRounds/index.tsx
Labels: size/S

#5905 fix: Catch localstorage exceeded quota
  apps/web/src/hooks/useFeatureFlag.ts
  apps/web/src/hooks/useLockedEndNotification.tsx
  apps/web/src/hooks/useSwapHotTokenDisplay.ts
  apps/web/src/state/user/hooks/useUserTokenRisk.ts
  apps/web/src/state/user/smartRouter.ts
  apps/web/src/utils/atomWithStorageWithErrorCatch.ts
  apps/web/src/views/Swap/components/CurrencyInputHeader.tsx
Labels: size/L

#5939 fix: Avoid undefined from provider
  apps/web/src/config/wallet.ts
Labels: size/XS

#5941 chore(Lottery): Change edit number input color
  apps/web/src/views/Lottery/components/BuyTicketsModal/TicketInput.tsx
Labels: size/XS

#5880 chore(Achievement): Change IFO desc
  apps/web/src/state/achievements/helpers.ts
  apps/web/src/state/profile/hooks.ts
  apps/web/src/utils/achievements.ts
  apps/web/src/views/Profile/components/Achievements/ClaimPointsCallout.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#5946 chore: Update atomWithStorageWithErrorCatch version
  apps/web/src/utils/atomWithStorageWithErrorCatch.ts
Labels: size/L

#5944 perf(Pottery): Should no longer allow users to enable contract when deposit is close
  apps/web/src/views/Pottery/components/Pot/Deposit/DepositAction.tsx
Labels: size/XS

#5964 chore: Bump pkg version
  .changeset/happy-gifts-watch.md
Labels: size/XS

#5957 feat: Add edit button to slippage tolerance row
  apps/aptos/components/Liquidity/components/SlippageSection.tsx
  apps/aptos/pages/swap.tsx
  apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
  apps/web/src/views/AddLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/index.tsx
  apps/web/src/views/Swap/SmartSwap/index.tsx
  apps/web/src/views/Swap/StableSwap/components/StableSwapForm.tsx
  apps/web/src/views/Swap/components/SwapForm.tsx
  packages/uikit/src/widgets/Swap/SwapInfo.tsx
Labels: size/M

#5953 refactor: (pools): Remove unused breakpoint props in action panel
  apps/aptos/components/Pools/components/PoolTable/ActionPanel.tsx
  apps/aptos/components/Pools/components/PoolTable/PoolRow.tsx
  apps/web/src/views/Migration/components/MigrationStep2/NewPool/PoolRow.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
  apps/web/src/views/Pools/components/PoolsTable/PoolRow.tsx
Labels: size/M

#5955 refactor: Add missing keys to iterated components
  apps/aptos/components/Liquidity/components/ChoosePair.tsx
  apps/aptos/components/SearchModal/CommonBases.tsx
  apps/blog/views/Blog/components/Article/SingleArticle/ArticleInfo.tsx
Labels: size/XS

#5954 perf: Use big number constant instead of object
  apps/aptos/components/Pools/transformers/transformCakePool.ts
  apps/aptos/components/Pools/transformers/transformPool.ts
  apps/web/src/views/Farms/components/FarmCard/CardActionsContainer.tsx
  apps/web/src/views/Farms/components/FarmCard/FarmCard.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/VestingAvailableToClaim.tsx
  apps/web/src/views/Lottery/components/BuyTicketsModal/BuyTicketsModal.tsx
  apps/web/src/views/Migration/components/MigrationStep1/OldPool/ActionPanel/Stake.tsx
  packages/uikit/src/components/RoiCalculatorModal/RoiCalculatorFooter.tsx
  packages/uikit/src/widgets/Farm/components/DepositModal/index.tsx
  packages/uikit/src/widgets/Farm/components/WithdrawModal/index.tsx
  packages/utils/bigNumber.ts
Labels: size/M

#5940 fix(Aptos): Max button on swap page
  apps/aptos/utils/maxAmountSpend.ts
Labels: size/XS, automerge

#5961 revert: Remove Cny Effect
  apps/web/public/images/cny-asset/ball-1.png
  apps/web/public/images/cny-asset/ball-2.png
  apps/web/public/images/cny-asset/ball-3.png
  apps/web/public/images/cny-asset/ball-4.png
  apps/web/public/images/cny-asset/ball-5.png
  apps/web/public/images/cny-asset/ball-6.png
  apps/web/public/images/cny-asset/ball-7.png
  apps/web/public/images/cny-asset/banner-1.png
  apps/web/public/images/cny-asset/banner-2.png
  apps/web/public/images/cny-asset/banner-3.png
  apps/web/public/images/cny-asset/c-1.png
  apps/web/public/images/cny-asset/c-2.png
  apps/web/public/images/cny-asset/c-3.png
  apps/web/public/images/cny-asset/c-4.png
  apps/web/public/images/cny-asset/cny-frame.png
  apps/web/public/images/cny-asset/cny-lantern-1.png
  apps/web/public/images/cny-asset/cny-lantern-2.png
  apps/web/public/images/cny-asset/l-1.png
  apps/web/public/images/cny-asset/l-2.png
  apps/web/public/images/cny-asset/l-3.png
  apps/web/public/images/cny-asset/l-4.png
  apps/web/public/images/cny-asset/l-5.png
  apps/web/public/images/cny-asset/l-6.png
  apps/web/public/images/cny-asset/p-1.png
  apps/web/public/images/cny-asset/p-2.png
  apps/web/public/images/cny-asset/redpocket.png
  apps/web/public/images/pottery/banner-bunny-cny.png
  apps/web/src/hooks/useChineseNewYearEffect.ts
  apps/web/src/views/Home/components/Banners/CnyBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  apps/web/src/views/Home/index.tsx
  apps/web/src/views/Lottery/components/CnyLotteryDraw.tsx
  apps/web/src/views/Lottery/components/Hero.tsx
  apps/web/src/views/Lottery/components/LotteryCnyEffect.tsx
  apps/web/src/views/Lottery/index.tsx
  apps/web/src/views/Lottery/pageSectionStyles.tsx
  apps/web/src/views/Pottery/components/Banner/index.tsx
  apps/web/src/views/Pottery/components/FinishedRounds/index.tsx
  apps/web/src/views/Pottery/components/Pot/PotteryCnyEffect.tsx
  apps/web/src/views/Pottery/components/Pot/index.tsx
  apps/web/src/views/Pottery/index.tsx
  packages/localization/src/config/translations.json
Labels: size/XL, automerge

#5930 feat(Blog): Optimization blog
  apps/blog/components/Menu.tsx
  apps/blog/components/NoSSR.tsx
  apps/blog/components/PageMeta.tsx
  apps/blog/next-seo.config.ts
  apps/blog/next.config.mjs
  apps/blog/pages/_app.tsx
  apps/blog/pages/blog/article/[slug].tsx
  apps/blog/views/Blog/components/Article/AllArticle/index.tsx
  apps/blog/views/Blog/components/Article/ArticleView.tsx
  apps/blog/views/Blog/components/Article/SingleArticle/ArticleInfo.tsx
  apps/blog/views/Blog/components/Article/SingleArticle/SocialIcon.tsx
  apps/blog/views/Blog/components/NewBlog.tsx
  apps/blog/views/Blog/hooks/useAllArticle.ts
  apps/blog/views/Blog/types.ts
  apps/blog/views/Blog/utils/api.ts
  apps/blog/views/Blog/utils/transformArticle.ts
Labels: size/L, automerge

#5967 fix: (aptos): Overlay still visible after closing the settings with button
  apps/aptos/pages/swap.tsx
Labels: size/XS

#5966 chore(AvengerDAO): Change text color to inverted
  apps/web/src/views/Swap/components/AccessRisk/index.tsx
Labels: size/S

#5970 fix(aptos-ifo): Minor format fix
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/GetTokenModal.tsx
  apps/aptos/views/Ifos/components/IfoVesting/VestingPeriod/Info.tsx
  apps/aptos/views/Ifos/generated/ifo.ts
Labels: size/S

#5931 feat(Aptos): Testnet logo opacity
  apps/aptos/components/Logo/CurrencyLogo.css.ts
  apps/aptos/components/Logo/CurrencyLogo.tsx
  apps/aptos/components/NetworkSwitcher.tsx
Labels: size/S, automerge

#5975 chore: stableSwap top pool where condition
  apps/web/src/state/info/queries/pools/topPools.ts
Labels: size/XS

#5978 feat: list STG
  apps/web/public/images/1/tokens/0xAf5191B0De278C7286d6C7CC6ab6BB8A73bA2Cd6.png
  packages/farms/constants/1.ts
  packages/tokens/src/1.ts
Labels: size/S

#5925 feat: (aptos): Use ledger timestamp for farms pending rewards instead of client time
  apps/aptos/components/Pools/hooks/usePoolsList.ts
  apps/aptos/components/Pools/transformers/transformCakePool.ts
  apps/aptos/hooks/useLedgerTimestamp.ts
  apps/aptos/state/farms/hook.ts
  apps/aptos/state/farms/utils/pendingCake.ts
Labels: size/M

#5977 fix(mp): Farm context undefined on dev
  apps/web/src/views/Farms/Farms.tsx
  apps/web/src/views/Farms/context.ts
  apps/web/src/views/Farms/index.tsx
Labels: size/S

#5979 feat(web): can trigger disconnect on mp page
  apps/web/src/components/Navbar.bmp.tsx
  apps/web/src/utils/mpBridge.ts
Labels: size/S
