Repository pancakeswap/pancake-frontend, pull requests merged in 2024-04, with the labels that each got.

#9451 feat: list-new-arbitrum-gauges
  packages/gauges/src/constants/config/prod.ts
Labels: size/L

#9463 chore: Fast routing opt in 50%
  apps/web/src/config/experimentalFeatures.ts
Labels: size/XS

#9408 fix: Add native token to wallet not working in transaction modal
  apps/web/src/components/TransactionConfirmationModal/index.tsx
  apps/web/src/views/Swap/V3Swap/containers/ConfirmSwapModal.tsx
  apps/web/src/views/Swap/V3Swap/containers/ConfirmSwapModalV2.tsx
Labels: size/L

#9464 feat: add pepe
  .changeset/lucky-beds-promise.md
  packages/pools/src/constants/pools/56.ts
Labels: size/S

#9472 feat: auto create merkl update pr
  .github/workflows/updateCron.yml
Labels: size/XS

#9475 feat: list nmt farm
  packages/farms/constants/bsc.ts
  packages/farms/constants/eth.ts
  packages/tokens/src/constants/bsc.ts
  packages/tokens/src/constants/eth.ts
Labels: size/M

#9477 feat: add cake-weth pm
  packages/position-managers/src/constants/vaults/arb.ts
Labels: size/S

#9417 feat: List new game shadow reaml
  packages/games/src/constants/games/index.ts
  packages/games/src/constants/games/shadowRealm.ts
  packages/games/src/types.ts
Labels: Delayed Release, size/M

#9480 feat: Vercel feature flag controls integration
  apps/web/.env.example
  apps/web/README.md
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/src/components/VercelToolbar.tsx
  apps/web/src/hooks/useExperimentalFeatureEnabled.ts
  apps/web/src/hooks/useVercelToolbar.ts
  apps/web/src/pages/_app.tsx
  apps/web/src/pages/api/vercel/flags.ts
  apps/web/src/utils/vercelToolbar.ts
  pnpm-lock.yaml
Labels: size/L

#9476 feat: x sdk
  .changeset/angry-candles-stare.md
  apps/web/package.json
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/hooks/useBestAMMTrade.ts
  package.json
  packages/pcsx-sdk/package.json
  packages/pcsx-sdk/src/abi/BaseReactor.ts
  packages/pcsx-sdk/src/abi/OrderQuoter.ts
  packages/pcsx-sdk/src/constants.ts
  packages/pcsx-sdk/src/errors.ts
  packages/pcsx-sdk/src/index.ts
  packages/pcsx-sdk/src/orders/ExclusiveDutchOrder.test.ts
  packages/pcsx-sdk/src/orders/ExclusiveDutchOrder.ts
  packages/pcsx-sdk/src/orders/Order.ts
  packages/pcsx-sdk/src/orders/index.ts
  packages/pcsx-sdk/src/trades/ExclusiveDutchOrderTrade.ts
  packages/pcsx-sdk/src/trades/utils.ts
  packages/pcsx-sdk/src/utils/NonceManager.ts
  packages/pcsx-sdk/src/utils/OrderQuoter.ts
  packages/pcsx-sdk/src/utils/hashStruct.ts
  packages/pcsx-sdk/src/utils/index.ts
  packages/pcsx-sdk/tsconfig.json
  packages/pcsx-sdk/tsup.config.ts
  packages/pcsx-sdk/vitest.config.ts
  packages/price-api-sdk/package.json
  packages/price-api-sdk/src/orderPriceApiParsers.ts
  packages/price-api-sdk/src/types/order.ts
  packages/price-api-sdk/src/types/pcsx.ts
  packages/smart-router/evm/v4-router/transformer.ts
  pnpm-lock.yaml
Labels: size/XXL

#9482 feat: Game Sldier add next button
  apps/games/components/Game/Home/Games.tsx
  packages/games/src/constants/games/index.ts
Labels: size/L

#9483 feat: Update headerIconImage
  packages/games/src/constants/games/shadowRealm.ts
Labels: size/XS

#9486 feat: update top fixed farms
  packages/farms/constants/base.ts
  packages/farms/constants/bsc.ts
  packages/farms/constants/linea.ts
  packages/farms/constants/polygonZkEVM.ts
  packages/farms/constants/zkSync.ts
Labels: size/L

#9485 feat: pepe gift icon
  apps/web/src/components/GiftTooltip/GiftTooltip.tsx
  apps/web/src/views/Farms/components/FarmCard/CardHeading.tsx
  apps/web/src/views/Farms/components/FarmTable/Farm.tsx
  apps/web/src/views/Pools/components/PoolsTable/Cells/NameCell.tsx
  apps/web/src/views/Pools/components/PoolsTable/PoolRow.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#9492 feat: list new gauges
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/eth.ts
Labels: size/S

#9493 feat: List new gauges
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/S

#9491 feat: Add zkevm position managers
  packages/position-managers/src/constants/supportedChains.ts
  packages/position-managers/src/constants/vaults/zkevm.ts
Labels: size/M

#9504 feat: Update position manager config
  packages/position-managers/src/constants/vaults/eth.ts
Labels: size/S

#9509 chore: fix bcake issues
  apps/web/src/utils/calls/farms.ts
  apps/web/src/views/Farms/components/FarmCard/ApyButton.tsx
  apps/web/src/views/Farms/components/FarmCard/FarmCard.tsx
  apps/web/src/views/Farms/components/FarmCard/StakeAction.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
  apps/web/src/views/Farms/components/FarmTable/Row.tsx
Labels: size/M

#9507 feat: Update gauges
  packages/gauges/src/constants/config/prod.ts
Labels: size/L

#9513 chore: fix v2 farm allocPoint issue
  apps/web/src/views/Farms/FarmsV3.tsx
  packages/farms/constants/bsc.ts
  packages/farms/src/types.ts
  packages/farms/src/v2/fetchFarmsV2.ts
Labels: size/S

#9516 chore: fix v2 farm mock alloc point
  packages/farms/constants/bsc.ts
Labels: size/XS

#9497 fix: Limit order not visible when handler is null
  apps/web/src/views/LimitOrders/components/LimitOrderTable/DetailLimitOrderModal.tsx
  apps/web/src/views/LimitOrders/hooks/useGelatoLimitOrdersHistory.ts
Labels: size/S

#9520 feat: Update gauges
  packages/gauges/src/constants/config/prod.ts
Labels: size/S

#9506 perf: Memoize modalv2 provider to prevent redundant rerenders
  apps/web/src/components/GlobalCheckClaimStatus/AnniversaryAchievementModal.tsx
  apps/web/src/components/GlobalCheckClaimStatus/V3AirdropModal.tsx
  apps/web/src/components/Menu/GlobalSettings/SettingsModal.tsx
  apps/web/src/components/NetworkModal/NetworkModal.tsx
  apps/web/src/views/AffiliatesProgram/components/OnBoardingModal/Congratulations.tsx
  apps/web/src/views/CakeStaking/index.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmInfo.tsx
  apps/web/src/views/FixedStaking/components/FixedStakingCalculator.tsx
  apps/web/src/views/FixedStaking/components/FixedStakingModal.tsx
  apps/web/src/views/Migration/components/v3/Step4.tsx
  apps/web/src/views/Pools/components/RevenueSharing/JoinRevenueModal/VCakeModal.tsx
  apps/web/src/views/Swap/V3Swap/containers/ConfirmSwapModalV2.tsx
  packages/uikit/src/widgets/Modal/ModalV2.tsx
Labels: size/L

#9501 fix: Cyclic dependency
  packages/localization/package.json
  packages/localization/src/Provider.tsx
  packages/localization/src/hooks/useLastUpdated.ts
  packages/localization/src/hooks/usePreviousValue.ts
  pnpm-lock.yaml
Labels: size/M

#9517 fix: Farm staked only on bcake farms
  apps/web/src/views/Farms/FarmsV3.tsx
  apps/web/src/views/Farms/components/FarmCard/StakeAction.tsx
  apps/web/src/views/Farms/components/FarmTable/FarmTable.tsx
  apps/web/src/views/Farms/utils/getStakedFarms.ts
Labels: size/M

#9494 chore: typo
  apps/bridge/components/GeneralDisclaimerModal/GeneralRiskAcceptModal.tsx
  apps/web/src/views/TradingReward/components/YourTradingReward/VeCake/Header.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#9518 fix: User balance in roi calculator with bcake farms
  apps/web/src/views/Farms/components/FarmCard/ApyButton.tsx
Labels: size/M

#9522 feat: Switch trading reward contract
  apps/web/src/config/constants/contracts.ts
Labels: size/XS, automerge

#9519 feat: veCake APR display
  apps/web/src/views/CakeStaking/components/DataSet/NewStakingDataSet.tsx
  apps/web/src/views/CakeStaking/components/DataSet/TotalApy.tsx
Labels: size/M, automerge

#9524 chore: fix bCake legacy proxy migration issue
  apps/web/src/config/constants/supportChains.ts
  apps/web/src/views/Farms/FarmsV3.tsx
  apps/web/src/views/Migration/components/bCake/Step1.tsx
  packages/farms/constants/bsc.ts
  packages/localization/src/config/translations.json
Labels: size/S

#9526 feat: options banner
  .changeset/gold-lamps-lay.md
  .vscode/settings.json
  apps/web/src/views/Home/components/Banners/MultichainBanner.tsx
  apps/web/src/views/Home/components/Banners/NemesisDownfallBanner.tsx
  apps/web/src/views/Home/components/Banners/OptionsBanner.tsx
  apps/web/src/views/Home/components/Banners/VeCakeBanner.tsx
  apps/web/src/views/Home/components/Banners/WBNBFixedStakingBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
  packages/widgets-internal/components/Banner/VerticalDivider.tsx
  packages/widgets-internal/components/Banner/actions/ButtonLink.tsx
  packages/widgets-internal/components/Banner/actions/LinkExternal.tsx
  packages/widgets-internal/components/Banner/badges/CoBrandBadge.tsx
  packages/widgets-internal/components/Banner/badges/PancakeSwapBadge.tsx
  packages/widgets-internal/components/Banner/badges/index.ts
  packages/widgets-internal/components/Banner/index.ts
Labels: size/L

#9529 feat: Link to options
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/components/Menu/hooks/useMenuItems.ts
  apps/web/src/components/Menu/index.tsx
  apps/web/src/components/Modal/USCitizenConfirmModal.tsx
  apps/web/src/hooks/usePerpUrl.ts
  apps/web/src/hooks/useUserIsUsCitizenAcknowledgement.ts
  apps/web/src/utils/getOptionsUrl.ts
  apps/web/src/utils/getPerpetualUrl.ts
  packages/localization/src/config/translations.json
Labels: size/L

#9534 fix: Affiliates Program useUserClaimList
  apps/web/src/views/AffiliatesProgram/hooks/useAffiliateClaimList.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useAuthAffiliateExist.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useUserClaimList.tsx
Labels: size/S

#9539 feat: Add gagues
  packages/farms/constants/eth.ts
  packages/gauges/src/constants/config/prod.ts
Labels: size/M

#9541 fix: bCake stake amount for v2 farm
  packages/farms/src/v2/fetchPublicFarmData.ts
Labels: size/XS

#9551 fix: gauges pair name
  packages/gauges/src/constants/config/prod.ts
Labels: size/XS

#9550 chore: update bsc testnet universal-router address
  packages/universal-router-sdk/src/constants.ts
Labels: size/XS

#9552 fix: Sub menu fail to close on mobile devices
  apps/web/src/components/Menu/hooks/useMenuItems.ts
  packages/uikit/src/components/DropdownMenu/DropdownMenu.tsx
Labels: size/S

#9540 feat: add vaultAddress and pm test
  apps/web/src/config/__tests__/vaults.test.ts
  packages/position-managers/src/config.test.ts
  packages/position-managers/src/constants/supportedChains.ts
  packages/position-managers/src/constants/vaults/arb.ts
  packages/position-managers/src/constants/vaults/base.ts
  packages/position-managers/src/constants/vaults/bsc.ts
  packages/position-managers/src/constants/vaults/eth.ts
  packages/position-managers/src/constants/vaults/zkevm.ts
  packages/position-managers/src/constants/vaults/zksync.ts
  packages/position-managers/src/types.ts
Labels: size/L

#9553 fix: v2 farm tableview APR issue
  apps/aptos/components/Farms/components/FarmTable/FarmTable.tsx
  apps/web/src/views/Farms/components/FarmTable/FarmTable.tsx
Labels: size/XS

#9554 fix: v2 farm tableView APR issue part2
  apps/web/src/views/Farms/components/FarmTable/FarmTable.tsx
Labels: size/XS

#9549 feat: gauges-pm
  apps/web/src/views/GaugesVoting/components/GaugeTokenImage.tsx
  apps/web/src/views/GaugesVoting/components/PositionManagerLogo.tsx
  apps/web/src/views/GaugesVoting/components/Table/AddGauge/AddGaugeModal.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/List.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/TableHeader.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/TableRow.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/TableHeader.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/TableRow.tsx
  apps/web/src/views/GaugesVoting/components/Table/styled.tsx
  apps/web/src/views/GaugesVoting/utils.ts
  packages/gauges/package.json
  packages/gauges/src/constants/config/prod.ts
  packages/gauges/src/tests/config.test.ts
  packages/gauges/src/types.ts
  packages/localization/src/config/translations.json
  pnpm-lock.yaml
Labels: size/L

#9556 chore: Change vecake apr text
  apps/web/src/views/CakeStaking/components/CakeRewardsCard.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#9557 fix: Lp total liquidity value wrong
  packages/farms/src/v2/fetchFarmsV2.ts
Labels: size/XS

#9560 chore: Increase default opt in for fast routing and universal router
  apps/web/src/config/experimentalFeatures.ts
Labels: size/XS

#9537 fix: Eslint warnings
  apps/web/src/components/SearchModal/OnRampCurrencyModal.tsx
  apps/web/src/components/SearchModal/OnRampCurrencySearch.tsx
  apps/web/src/views/PositionManagers/components/RemoveLiquidity.tsx
Labels: size/S

#9542 perf: Improvements in utils
  packages/utils/formatBalance.ts
  packages/utils/isPositionOutOfRange.ts
  packages/utils/toBigInt.ts
  packages/utils/viem/formatUnits.ts
  packages/utils/viem/parseUnits.ts
Labels: size/S

#9527 fix: Crash in widgets internal
  apps/web/src/views/Migration/components/v3/Step4.tsx
Labels: size/XS

#9561 chore: Remove deprecated zksync testnet
  apps/web/src/config/chains.ts
Labels: size/XS

#9563 fix: Remove hot token list on twap page
  apps/web/src/components/DisclaimerModal/index.tsx
  apps/web/src/views/LimitOrders/components/ClaimWarning.tsx
  apps/web/src/views/Swap/Twap/TwapSwap.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#9562 chore: remove outdated banner
  apps/web/src/views/Home/components/Banners/WBNBFixedStakingBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#9564 fix: allowance TWAP
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/S

#9565 feat: list xcad on opbnb
  packages/farms/constants/opBNB.ts
  packages/tokens/src/constants/opBNB.ts
Labels: size/S

#9567 chore: Add limit v2 entry
  apps/web/src/components/Menu/config/config.ts
Labels: size/XS

#9568 fix: Add legacy limit link to new limit page and disable legacy limit
  apps/web/src/state/limitOrders/hooks.ts
  apps/web/src/views/Swap/Twap/Twap.tsx
  apps/web/src/views/Swap/Twap/TwapSwap.tsx
  apps/web/src/views/Swap/components/SwapSelection.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#9573 fix: Vote not found
  apps/web/src/state/voting/helpers.ts
Labels: size/XS

#9575 feat: List gauges
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/bsc.ts
  packages/tokens/src/constants/eth.ts
Labels: size/L

#9574 feat: Show MultiChainBanner
  apps/web/src/views/Home/components/Banners/MultichainBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/XS

#9577 chore: remove gift box
  apps/web/src/views/FixedStaking/components/AprCell.tsx
Labels: size/S

#9536 fix: Missing pair description in trading rewards and farm pair
  packages/farms/constants/polygonZkEVM.ts
Labels: size/XS

#9579 feat: List farms
  packages/farms/constants/bsc.ts
  packages/farms/constants/eth.ts
Labels: size/S

#9580 feat: Add stable lps gauges
  packages/gauges/src/constants/config/prod.ts
Labels: size/S

#9500 fix: Crash in swap in unsupported chain
  apps/web/src/hooks/usePermit2Details.ts
  packages/pcsx-sdk/src/constants.ts
  packages/pcsx-sdk/src/orders/ExclusiveDutchOrder.ts
  packages/pcsx-sdk/src/utils/NonceManager.ts
  packages/permit2-sdk/src/allowanceTransfer.ts
  packages/permit2-sdk/src/constants.ts
  packages/permit2-sdk/src/domain.ts
  packages/permit2-sdk/src/signatureTransfer.ts
Labels: size/S

#9583 refactor: remove duplicated switchNetwork callback
  apps/web/src/hooks/useAccountEventListener.ts
  apps/web/src/hooks/useSwitchNetwork.ts
Labels: size/M

#9584 fix(web): Mercuryo network
  apps/web/src/components/FiatOnRampModal/FiatOnRampModal.tsx
Labels: size/S

#9589 chore: list new CAKE reward PM on ARB
  packages/position-managers/src/config.test.ts
  packages/position-managers/src/constants/vaults/arb.ts
Labels: size/L

#9590 perf: use multicall
  packages/position-managers/src/config.test.ts
Labels: size/L

#9592 fix: Token highlight displayed in swap when chart enabled in twap
  apps/web/src/views/Swap/Twap/Twap.tsx
Labels: size/S

#9598 feat(web): Use bsc info gateway
  .changeset/thick-laws-end.md
  apis/farms/src/lpApr.ts
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/hooks/useV2Pools.ts
  apps/web/src/state/info/constant.ts
  apps/web/src/state/info/queries/pools/poolData.ts
  apps/web/src/state/info/queries/pools/topPools.ts
  apps/web/src/state/info/queries/tokens/poolsForToken.ts
  apps/web/src/state/info/queries/tokens/priceData.ts
  apps/web/src/state/info/queries/tokens/tokenData.ts
  apps/web/src/state/info/queries/tokens/topTokens.ts
  apps/web/src/state/swap/fetch/fetchDerivedPriceData.ts
  apps/web/src/state/swap/useLPApr.ts
  apps/web/src/utils/getAprsForStableFarm.ts
  apps/web/src/utils/getLpFeesAndApr.ts
  apps/web/src/utils/graphql.ts
  apps/web/src/views/Info/utils/infoQueryHelpers.ts
  packages/chains/src/subgraphs.ts
  scripts/updateLPsAPR.ts
Labels: size/L

#9599 fix: useActiveChainId should always return support chainId
  apps/web/src/hooks/useActiveChainId.ts
Labels: size/S

#9603 fix: Don't show sg health indicator on swap pages
  apps/web/src/views/Swap/SwapLayout.tsx
Labels: size/XS

#9601 feat: support v2 bCake farm on ARB
  apis/farms/src/handler.ts
  apps/web/src/pages/farms/index.tsx
  apps/web/src/state/farms/hooks.ts
  apps/web/src/state/farms/index.ts
  apps/web/src/utils/apr.ts
  apps/web/src/views/Farms/FarmsV3.tsx
  apps/web/src/views/Farms/components/FarmCard/CardActionsContainer.tsx
  apps/web/src/views/Farms/components/FarmCard/CardHeading.tsx
  apps/web/src/views/Farms/components/FarmCard/FarmCard.tsx
  apps/web/src/views/Farms/components/FarmCard/StakeAction.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
  apps/web/src/views/Farms/components/FarmTable/FarmTable.tsx
  apps/web/src/views/Farms/components/FarmTable/Row.tsx
  packages/farms/constants/arb.ts
  packages/farms/constants/bsc.ts
  packages/farms/src/const.ts
  packages/farms/src/types.ts
  packages/farms/src/v2/deserializeFarmUserData.ts
  packages/farms/src/v2/fetchFarmsV2.ts
  packages/farms/src/v2/fetchStableFarmData.ts
  packages/widgets-internal/farm/components/FarmCard/DetailsSection.tsx
Labels: size/L

#9604 fix: multi chain bCake UI issue
  apps/web/src/views/Farms/components/FarmCard/StakeAction.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
  apps/web/src/views/Farms/components/FarmTable/Row.tsx
  packages/farms/constants/arb.ts
Labels: size/S

#9605 chore: fix UI details
  apps/web/src/views/Farms/components/FarmCard/ApyButton.tsx
  apps/web/src/views/Farms/components/FarmTable/Row.tsx
  packages/uikit/src/components/RoiCalculatorModal/RoiCalculatorFooter.tsx
  packages/uikit/src/components/RoiCalculatorModal/RoiCalculatorModal.tsx
Labels: size/S

#9608 chore: Revert gateway subgraph
  apps/web/src/config/constants/endpoints.ts
Labels: size/XS

#9591 chore: Remove Litepaper
  apps/aptos/components/Menu/footerConfig.ts
  packages/uikit/src/widgets/Menu/components/footerConfig.ts
Labels: size/XS

#9610 chore: turn on COINGECKO list by default
  apps/web/src/config/constants/lists.ts
  packages/localization/src/config/translations.json
Labels: size/XS

#9612 chore: fix details
  apps/web/src/views/PositionManagers/hooks/useWrapperBooster.ts
Labels: size/XS

#9616 chore: fix multichain v2BCake config
  packages/farms/constants/arb.ts
Labels: size/XS

#9618 chore: list gauges
  packages/gauges/src/constants/config/prod.ts
Labels: size/M

#9617 chore: up vitest version
  package.json
  pnpm-lock.yaml
Labels: size/L

#9595 fix: Harvest card for bcake farms
  apps/web/src/views/Home/components/UserBanner/HarvestCard.tsx
  apps/web/src/views/Home/hooks/useFarmsWithBalance.tsx
  apps/web/src/views/PositionManagers/components/LiquidityManagement.tsx
  apps/web/src/views/PositionManagers/components/TableView/LiquidityManagement.tsx
Labels: size/L

#9622 chore: web3 wallet page view
  apps/web/src/hooks/useWeb3WalletView.ts
  apps/web/src/pages/_app.tsx
  apps/web/src/utils/customGTMEventTracking.ts
Labels: size/S

#9630 perf: Prevent duplicate block calls
  apps/web/src/state/block/hooks.ts
Labels: size/M

#9585 fix: Perpetual banner height
  apps/web/src/views/Home/components/Banners/PerpetualBanner.tsx
Labels: size/XS

#9629 feat: Add warning message
  apps/bridge/components/layerZero/index.tsx
Labels: size/S

#9631 chore: Ignore gamification for changesets
  .changeset/config.json
Labels: size/XS

#9636 perf: Prevent unnecessary block calls
  apps/web/src/hooks/useCurrentBlockTimestamp.ts
  apps/web/src/state/block/hooks.ts
  apps/web/src/state/farmsV3/hooks.ts
  apps/web/src/views/CakeStaking/hooks/useCurrentBlockTimestamp.ts
  apps/web/src/views/Predictions/hooks/usePollOraclePrice.ts
Labels: size/L

#9635 chore: list new PM
  packages/position-managers/src/constants/vaults/arb.ts
  packages/position-managers/src/constants/vaults/bsc.ts
Labels: size/M

#9637 perf: Deduplicate candidate pool calls
  apps/web/src/hooks/usePoolsOnChain.ts
Labels: size/M

#9633 chore: Increase cover rate for ab testing features
  apps/web/src/config/experimentalFeatures.ts
Labels: size/XS

#9642 chore: List new stable pair
  .changeset/nine-pigs-check.md
  packages/stable-swap-sdk/src/constants/pools/bsc.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/S

#9625 chore: Use exact match
  apps/web/src/views/Predictions/hooks/usePollOraclePrice.ts
  packages/wagmi/src/hooks/useBalance.ts
  packages/wagmi/src/hooks/useFeeData.ts
  packages/wagmi/src/hooks/useReadContract.ts
  packages/wagmi/src/hooks/useReadContracts.ts
Labels: size/S

#9641 perf: Unify watch blocks
  apps/web/src/state/block/hooks.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/onChainPoolProviders.ts
  packages/wagmi/src/hooks/useBalance.ts
  packages/wagmi/src/hooks/useBlock.ts
  packages/wagmi/src/hooks/useFeeData.ts
  packages/wagmi/src/hooks/useReadContract.ts
  packages/wagmi/src/hooks/useReadContracts.ts
  packages/wagmi/src/index.ts
Labels: size/L

#9644 perf: Add exact to initial block number cache
  packages/wagmi/src/hooks/useBlock.ts
Labels: size/XS

#9646 fix: Exception throws when invalidate query
  apps/web/src/views/Predictions/components/ChainlinkChart.tsx
  packages/wagmi/src/hooks/useBalance.ts
  packages/wagmi/src/hooks/useBlock.ts
  packages/wagmi/src/hooks/useFeeData.ts
  packages/wagmi/src/hooks/useReadContract.ts
  packages/wagmi/src/hooks/useReadContracts.ts
Labels: size/S

#9650 chore: typo
  apps/web/src/components/SearchModal/OnRampCurrencyList.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#9653 chore: PM details for initial staking is 0
  apps/web/src/views/PositionManagers/components/TableView/index.tsx
  apps/web/src/views/PositionManagers/containers/PCSVaultCard.tsx
  apps/web/src/views/PositionManagers/hooks/useAdapterInfo.ts
Labels: size/XS

#9654 feat: add-pm-and-gauges
  packages/gauges/src/constants/config/prod.ts
  packages/position-managers/src/constants/vaults/bsc.ts
  packages/position-managers/src/constants/vaults/zkevm.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/L

#9659 fix: address
  packages/gauges/src/constants/config/prod.ts
Labels: size/XS

#9662 feat: remove giftbox
  apps/web/src/components/CurrencyInputPanel/index.tsx
Labels: size/S

#9663 fix: remove duplicated safe connect
  apps/web/src/hooks/useEagerConnect.ts
  apps/web/src/utils/wagmi.ts
Labels: size/S

#9664 chore: Masa TC banner
  apps/web/src/views/Home/components/Banners/MasaTCBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
  packages/widgets-internal/components/Banner/badges/CoBrandBadge.tsx
Labels: size/L

#9665 chore: masa stripe
  apps/web/src/components/Menu/index.tsx
  apps/web/src/components/PhishingWarningBanner/Countdown.tsx
  apps/web/src/components/PhishingWarningBanner/Step3.tsx
  apps/web/src/components/PhishingWarningBanner/index.tsx
  apps/web/src/views/Home/components/Banners/MasaTCBanner.tsx
  packages/localization/src/config/translations.json
  packages/widgets-internal/components/Banner/badges/CoBrandBadge.tsx
Labels: size/M

#9671 feat: remove delegated vote info
  apps/web/src/views/GaugesVoting/hooks/useUserVoteGauges.ts
Labels: size/XS

#9672 fix: ignore lock when delegated
  apps/web/src/views/CakeStaking/hooks/useVeCakeUserInfo.ts
Labels: size/S

#9675 feat: new gauges & farms
  packages/farms/constants/arb.ts
  packages/farms/constants/linea.ts
  packages/farms/constants/polygonZkEVM.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/linea.ts
  packages/tokens/src/constants/polygonZkEVM.ts
Labels: size/L

#9669 fix: Affliate Program
  apps/web/src/config/abi/affiliateProgram.ts
  apps/web/src/hooks/useAccountEventListener.ts
  apps/web/src/utils/contractHelpers.ts
Labels: size/L

#9677 fix: Watch account wagmi
  apps/web/package.json
  apps/web/src/hooks/useAccountEventListener.ts
  pnpm-lock.yaml
Labels: size/M

#9681 feat: list SDT vault
  packages/position-managers/src/constants/vaults/bsc.ts
Labels: size/S

#9645 feat: Add multi chain tvl tx info
  apps/web/src/pages/index.tsx
  apps/web/src/utils/getTotalTVL.ts
  apps/web/src/utils/graphql.ts
  apps/web/src/views/Home/components/MetricsSection/index.tsx
Labels: size/L

#9655 feat: Run only when block number changes
  packages/wagmi/src/hooks/useBalance.ts
  packages/wagmi/src/hooks/useDidMountEffect.ts
  packages/wagmi/src/hooks/useFeeData.ts
  packages/wagmi/src/hooks/useReadContract.ts
  packages/wagmi/src/hooks/useReadContracts.ts
Labels: size/M

#9634 fix: Use always collection metadata for collection name
  apps/web/src/pages/nfts/collections/[collectionAddress]/[tokenId].tsx
  apps/web/src/views/Nft/market/hooks/useCompleteNft.tsx
Labels: size/XS

#9538 fix: Pool veCake apr in other chains
  apps/web/src/utils/addressHelpers.ts
  apps/web/src/views/CakeStaking/hooks/useAPR.ts
  apps/web/src/views/CakeStaking/hooks/useVeCakeTotalSupply.ts
Labels: size/S

#9685 fix: token name
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/S

#9674 fix: Limit price feature + bug fixes
  apps/web/package.json
  apps/web/src/views/Swap/Twap/Twap.tsx
  pnpm-lock.yaml
Labels: size/L

#9684 feat: gauges-filter
  .vscode/settings.json
  apps/web/src/views/GaugesVoting/components/GaugesFilter/FilterFieldByType.tsx
  apps/web/src/views/GaugesVoting/components/GaugesFilter/FilterFieldInput.tsx
  apps/web/src/views/GaugesVoting/components/GaugesFilter/FilterFiledSort.tsx
  apps/web/src/views/GaugesVoting/components/GaugesFilter/FilterModal.tsx
  apps/web/src/views/GaugesVoting/components/GaugesFilter/FilterOption.tsx
  apps/web/src/views/GaugesVoting/components/GaugesFilter/index.ts
  apps/web/src/views/GaugesVoting/components/GaugesFilter/type.ts
  apps/web/src/views/GaugesVoting/components/Table/AddGauge/AddGaugeModal.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/List.tsx
  apps/web/src/views/GaugesVoting/hooks/useGaugesFilter.ts
  apps/web/src/views/GaugesVoting/index.tsx
  packages/localization/src/config/translations.json
Labels: size/XL

#9686 chore: remove mock alloc point
  apps/aptos/components/Farms/components/Farms.tsx
  packages/farms/constants/arb.ts
  packages/farms/constants/bsc.ts
Labels: size/S

#9689 feat: list mwbETH-wbETH
  packages/farms/constants/bsc.ts
Labels: size/S

#9693 fix: vecake reward apy
  apps/web/src/views/CakeStaking/hooks/useAPR.ts
Labels: size/XS

#9688 feat: Add tvl for stable swap
  apps/web/src/utils/getTotalTVL.ts
Labels: size/XL

#9692 perf: Memoize vecake apr
  apps/web/src/views/CakeStaking/components/DataSet/TotalApy.tsx
  apps/web/src/views/CakeStaking/hooks/useAPR.ts
Labels: size/M

#9691 feat: gauges-chain-id
  .changeset/nasty-schools-sell.md
  apps/web/src/views/GaugesVoting/components/GaugesFilter/FilterOption.tsx
  packages/gauges/src/constants/chainId.ts
  packages/gauges/src/constants/index.ts
  packages/gauges/src/index.test.ts
  packages/gauges/src/index.ts
  packages/gauges/src/tests/config.test.ts
Labels: size/M

#9698 chore(BuyCrypto): Do not use translations
  apps/web/src/views/BuyCrypto/components/ProviderSelector/ProviderGroupItem.tsx
  apps/web/src/views/BuyCrypto/components/ProviderSelector/ProviderSelector.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#9707 chore: show add v2 liq for all conditions
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/FeeSelector.tsx
Labels: size/XS

#9706 chore: Fast routing opt in 80%
  apps/web/src/config/experimentalFeatures.ts
Labels: size/XS

#9710 feat: list new ad-hoc farms
  packages/farms/constants/arb.ts
  packages/farms/constants/bsc.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/S

#9700 fix: Support node v22
  apps/web/next.config.mjs
Labels: size/XS

#9717 feat: update addresses
  .changeset/angry-cougars-begin.md
  packages/pcsx-sdk/src/constants.ts
  packages/pcsx-sdk/src/errors.ts
  packages/pcsx-sdk/src/orders/ExclusiveDutchOrder.test.ts
Labels: size/S

#9709 feat: USDV page
  apps/web/package.json
  apps/web/src/components/SearchModal/CurrencySearch.tsx
  apps/web/src/hooks/useUsdvMintAvailable.ts
  apps/web/src/pages/usdv.tsx
  packages/localization/src/config/translations.json
  packages/position-managers/src/config.test.ts
  packages/widgets-internal/components/ClientOnly/index.tsx
  packages/widgets-internal/components/CurrencyLogo/CurrencyLogo.tsx
  packages/widgets-internal/components/CurrencyLogo/types.ts
  packages/widgets-internal/components/CurrencyLogo/utils.ts
  packages/widgets-internal/components/ExternalCurrencyLink/index.tsx
  packages/widgets-internal/components/PoweredBy/index.tsx
  packages/widgets-internal/index.ts
  packages/widgets-internal/usdv/ExternalMintLink.tsx
  packages/widgets-internal/usdv/index.ts
  pnpm-lock.yaml
Labels: size/L

#9721 fix: ignore killed count
  apps/web/src/views/CakeStaking/components/SyrupPool/VeCakeCard.tsx
  apps/web/src/views/CakeStaking/hooks/useGaugesVotingCount.ts
  apps/web/src/views/CakeStaking/index.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/index.tsx
  packages/gauges/src/getAllGauges.ts
Labels: size/S
