Repository pancakeswap/pancake-frontend, pull requests merged in 2024-02, with the labels that each got.

#8956 chore: Remove unused deps in migrate
  apps/web/src/views/AddLiquidityV3/Migrate.tsx
Labels: size/S

#8942 perf: Optimize loading barrel packages
  apps/web/next.config.mjs
Labels: size/XS

#8951 chore(Prediction): zkSync oracle service is powered by PYTH
  apps/web/public/images/powered-by-pyth.svg
  apps/web/src/views/Predictions/Desktop.tsx
  apps/web/src/views/Predictions/Mobile.tsx
  packages/prediction/src/type.ts
Labels: size/M

#8960 revert: "perf: Optimize loading barrel packages"
  apps/web/next.config.mjs
Labels: size/XS

#8961 fix: PM WETH-swETH vault price issue
  packages/position-managers/src/constants/vaults/eth.ts
Labels: size/XS

#8922 feat: list alpaca vault with bCake wrapper
  apps/web/src/hooks/useContract.ts
  apps/web/src/utils/contractHelpers.ts
  apps/web/src/views/PositionManagers/components/AddLiquidity.tsx
  apps/web/src/views/PositionManagers/components/DuoTokenVaultCard.tsx
  apps/web/src/views/PositionManagers/components/LiquidityManagement.tsx
  apps/web/src/views/PositionManagers/components/ManagerInfo.tsx
  apps/web/src/views/PositionManagers/components/RemoveLiquidity.tsx
  apps/web/src/views/PositionManagers/components/RewardAssets.tsx
  apps/web/src/views/PositionManagers/containers/PCSVaultCard.tsx
  apps/web/src/views/PositionManagers/hooks/useApr.ts
  apps/web/src/views/PositionManagers/hooks/useFetchApr.ts
  apps/web/src/views/PositionManagers/utils/strategy.ts
  packages/localization/src/config/translations.json
  packages/position-managers/src/abi/index.ts
  packages/position-managers/src/abi/positionManagerVeBCakeWrapper.ts
  packages/position-managers/src/constants/managers.ts
  packages/position-managers/src/constants/vaults/bsc.ts
  packages/position-managers/src/constants/vaults/index.ts
  packages/position-managers/src/types.ts
Labels: size/XL

#8965 refactor: Optimise barrel package imports
  apps/web/next.config.mjs
  apps/web/src/views/GaugesVoting/components/CurrentEpoch.tsx
Labels: size/XS

#8971 fix: add killed gauge config back
  packages/gauges/src/constants/config/prod.ts
  packages/gauges/src/tests/config.test.ts
Labels: size/M

#8973 fix: vault config
  packages/position-managers/src/constants/vaults/bsc.ts
Labels: size/XS

#8968 chore: list new farm and gauges
  packages/farms/constants/arb.ts
  packages/farms/constants/eth.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/eth.ts
Labels: size/M

#8963 chore: Add top traders banner
  apps/web/src/pages/_document.tsx
  apps/web/src/views/Home/components/Banners/TopTraderBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/contexts/index.ts
  packages/widgets-internal/components/Banner/BannerContainer.tsx
  packages/widgets-internal/components/Banner/BannerGraphics.tsx
  packages/widgets-internal/components/Banner/BannerMain.tsx
  packages/widgets-internal/components/Banner/BannerTitle.tsx
  packages/widgets-internal/components/Banner/actions/LinkExternal.tsx
  packages/widgets-internal/components/Banner/actions/index.ts
  packages/widgets-internal/components/Banner/animations.tsx
  packages/widgets-internal/components/Banner/badges/Badge.tsx
  packages/widgets-internal/components/Banner/badges/PancakeSwapBadge.tsx
  packages/widgets-internal/components/Banner/badges/index.ts
  packages/widgets-internal/components/Banner/index.ts
  packages/widgets-internal/components/Banner/types.ts
  packages/widgets-internal/index.ts
Labels: size/XL

#8954 fix: Transaction not found error when using useCatchTxError hook
  apps/web/src/config/constants/averageChainBlockTimes.ts
  apps/web/src/config/constants/index.ts
  apps/web/src/hooks/useCatchTxError.tsx
  apps/web/src/hooks/usePublicNodeWaitForTransaction.ts
  apps/web/src/state/transactions/updater.tsx
  apps/web/src/views/Ifos/hooks/useBridgeICake.ts
  apps/web/src/views/PositionManagers/components/RewardAssets.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalState.tsx
Labels: size/L

#8977 chore: Add blog link to MEOW
  apps/web/src/components/AccessRisk/index.tsx
  apps/web/src/components/CurrencyInputPanel/index.tsx
  apps/web/src/components/Menu/GlobalSettings/index.tsx
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/containers/FlipButton.tsx
  apps/web/src/views/Swap/V3Swap/containers/Recipient.tsx
  apps/web/src/views/Swap/V3Swap/containers/SwapCommitButton.tsx
  apps/web/src/views/Swap/components/CurrencyInputHeader.tsx
  packages/widgets-internal/swap/SwapInfo.tsx
Labels: size/L

#8978 test: Add globals types for apps
  apps/aptos/tsconfig.json
  apps/web/tsconfig.json
  packages/prediction/vitest.config.ts
Labels: size/XS

#8981 chore: list v2 and SS farm
  packages/farms/constants/bsc.ts
Labels: size/M

#8986 feat: add symbol alias
  apps/web/src/state/info/constant.ts
  apps/web/src/utils/getSymbolAlias.ts
  apps/web/src/views/Info/Pools/PoolPage.tsx
Labels: size/M

#8984 fix(Blog): Fix weird gap
  apps/blog/components/Article/AllArticle/index.tsx
Labels: size/M

#8989 fix: cake lock amount
  apps/web/src/views/CakeStaking/components/DataSet/NewStakingDataSet.tsx
Labels: size/XS

#8990 perf(farms): Skip fetch apr for finished v3 farms
  apps/web/src/state/farmsV3/hooks.ts
Labels: size/S

#8991 fix(farms): Apr index issue
  apps/web/src/state/farms/hooks.ts
  apps/web/src/state/farmsV3/hooks.ts
Labels: size/M

#8993 chore: list new bsc farm
  apps/web/src/views/TradingReward/config/pairs/56.tsx
  apps/web/src/views/TradingReward/config/pairs/index.tsx
  packages/farms/constants/bsc.ts
Labels: size/S

#8994 feat: Use gauges as routing reference
  packages/smart-router/evm/v3-router/functions/getPairCombinations.ts
  packages/smart-router/package.json
  packages/tokens/src/allTokens.ts
  packages/tokens/src/constants/arb.ts
  packages/tokens/src/constants/arbGoerli.ts
  packages/tokens/src/constants/base.ts
  packages/tokens/src/constants/baseTestnet.ts
  packages/tokens/src/constants/bsc.ts
  packages/tokens/src/constants/bscTestnet.ts
  packages/tokens/src/constants/common.ts
  packages/tokens/src/constants/eth.ts
  packages/tokens/src/constants/goerli.ts
  packages/tokens/src/constants/linea.ts
  packages/tokens/src/constants/lineaTestnet.ts
  packages/tokens/src/constants/opBNB.ts
  packages/tokens/src/constants/opBnbTestnet.ts
  packages/tokens/src/constants/polygonZkEVM.ts
  packages/tokens/src/constants/polygonZkEVMTestnet.ts
  packages/tokens/src/constants/scrollSepolia.ts
  packages/tokens/src/constants/zkSync.ts
  packages/tokens/src/constants/zkSyncTestnet.ts
  packages/tokens/src/helpers/getTokensByChain.ts
  packages/tokens/src/helpers/index.ts
  packages/tokens/src/index.ts
  pnpm-lock.yaml
Labels: size/L

#8995 perf: Add optimise package imports to aptos
  apps/aptos/next.config.mjs
Labels: size/XS

#8979 chore: Hide swap widget by default
  apps/web/src/components/TransactionConfirmationModal/index.tsx
  apps/web/src/hooks/useGlobalSettingsEvaluation.ts
  apps/web/src/hooks/useSwapHotTokenDisplay.ts
  apps/web/src/state/user/actions.ts
  apps/web/src/state/user/hooks/index.tsx
  apps/web/src/state/user/hooks/useUserChart.ts
  apps/web/src/state/user/reducer.ts
  apps/web/src/views/LimitOrders/components/ConfirmLimitOrderModal.tsx
  apps/web/src/views/LimitOrders/components/LimitOrderPrice.tsx
  apps/web/src/views/LimitOrders/index.tsx
  apps/web/src/views/LimitOrders/utils/getRatePercentageDifference.ts
  apps/web/src/views/LimitOrders/utils/getRatePercentageMessage.test.ts
  apps/web/src/views/LimitOrders/utils/getRatePercentageMessage.ts
  apps/web/src/views/Notifications/components/NotificationDropdown/NotificationMenu.tsx
  apps/web/src/views/Swap/SwapFeaturesContext.tsx
  apps/web/src/views/Swap/components/Chart/PriceChartContainer.tsx
  apps/web/src/views/Swap/components/CurrencyInputHeader.tsx
  apps/web/src/views/Swap/index.tsx
  packages/uikit/src/components/BottomDrawer/BottomDrawer.tsx
Labels: size/L

#8915 refactor: Use query in nfts
  apps/web/src/hooks/useContract.ts
  apps/web/src/pages/nfts/collections/[collectionAddress].tsx
  apps/web/src/pages/nfts/collections/[collectionAddress]/[tokenId].tsx
  apps/web/src/state/nftMarket/helpers.ts
  apps/web/src/state/nftMarket/types.ts
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/ForSaleTableCard/ForSaleTableRows.tsx
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/ForSaleTableCard/index.tsx
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/shared/MoreFromThisCollection.tsx
  apps/web/src/views/Nft/market/Collection/Items/CollectionNfts.tsx
  apps/web/src/views/Nft/market/Collection/LowestPriceStatBoxItem.tsx
  apps/web/src/views/Nft/market/Collections/index.tsx
  apps/web/src/views/Nft/market/components/StatBox.tsx
  apps/web/src/views/Nft/market/hooks/useCollectionNfts.tsx
  apps/web/src/views/Nft/market/hooks/useCompleteNft.tsx
  apps/web/src/views/Nft/market/hooks/useGetCollectionDistribution.tsx
  apps/web/src/views/Nft/market/hooks/useGetLowestPrice.ts
  apps/web/src/views/Nft/market/hooks/useNftOwner.tsx
  apps/web/src/views/Nft/market/hooks/useNftsForAddress.tsx
  apps/web/src/views/Nft/market/hooks/usePancakeBunnyCheapestNfts.tsx
  apps/web/src/views/Nft/market/hooks/usePancakeBunnyOnSaleNfts.tsx
Labels: size/XL

#8832 refactor: Use query in stablecoin price and change filename
  apps/web/src/components/CurrencyInputPanel/index.tsx
  apps/web/src/components/CurrencySelect/index.tsx
  apps/web/src/components/PositionCard/index.tsx
  apps/web/src/hooks/useStablecoinPrice.ts
  apps/web/src/hooks/v3/usePositionV3Liquidity.ts
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/PositionPreview.tsx
  apps/web/src/views/FixedStaking/components/AmountWithUSDSub.tsx
  apps/web/src/views/FixedStaking/components/FixedStakingCalculator.tsx
  apps/web/src/views/FixedStaking/components/StakingModalTemplate.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
  apps/web/src/views/Ifos/components/IfoVesting/VestingPeriod/TokenInfo.tsx
  apps/web/src/views/RemoveLiquidity/RemoveLiquidityV3.tsx
  apps/web/src/views/TradingCompetition/helpers.ts
Labels: size/M

#9000 chore: list bsc and arb farm
  packages/farms/constants/arb.ts
  packages/farms/constants/bsc.ts
  packages/tokens/src/constants/arb.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/M

#9005 feat(api): proxy worker add v3
  apis/proxy-worker/src/bindings.d.ts
  apis/proxy-worker/src/index.ts
Labels: size/S

#9008 refactor: Use query in nft hooks
  apps/web/src/state/nftMarket/hooks.ts
  apps/web/src/views/Nft/market/Home/index.tsx
Labels: size/M

#9007 chore: list new BRIL PM vault
  packages/position-managers/src/constants/vaults/bsc.ts
Labels: size/M

#9012 chore: update tokens name and symbol for info page
  apps/web/src/state/info/constant.ts
Labels: size/XS

#8887 refactor: Use query in vault apy and remove swr completely
  apps/web/package.json
  apps/web/src/Providers.tsx
  apps/web/src/hooks/useSWRContract.ts
  apps/web/src/hooks/useVaultApy.test.ts
  apps/web/src/hooks/useVaultApy.ts
  apps/web/src/testUtils.tsx
  pnpm-lock.yaml
Labels: size/L

#9003 chore: Update changesets
  .github/workflows/release.yml
  package.json
  pnpm-lock.yaml
Labels: size/L

#9009 chore: Update binance w3w
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/L

#9002 feat: Show testnet on settings
  apps/web/src/components/Menu/GlobalSettings/SettingsModal.tsx
  apps/web/src/components/NetworkSwitcher.tsx
  apps/web/src/state/user/hooks/useUserShowTestnet.ts
  packages/localization/src/config/translations.json
Labels: size/M

#9020 feat: Add copy button on info page
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/Info/Tokens/TokenPage.tsx
  apps/web/src/views/V3Info/components/CandleChart/index.tsx
  apps/web/src/views/V3Info/views/PoolPage.tsx
  apps/web/src/views/V3Info/views/TokenPage.tsx
Labels: size/M

#9022 chore: Publish gauges
  .changeset/tasty-trainers-sit.md
  apps/web/next.config.mjs
  packages/gauges/package.json
Labels: size/XS

#9024 feat: Pools only support withdraw or harvest
  src/config/localization/translations.json
  src/views/Pools/components/Apr.tsx
  src/views/Pools/components/CakeVaultCard/VaultCardActions/HasSharesActions.tsx
  src/views/Pools/components/CakeVaultCard/VaultCardActions/VaultStakeActions.tsx
  src/views/Pools/components/CakeVaultCard/VaultCardActions/index.tsx
  src/views/Pools/components/PoolCard/CardActions/ApprovalAction.tsx
  src/views/Pools/components/PoolCard/CardActions/StakeActions.tsx
  src/views/Pools/components/PoolCard/CardActions/index.tsx
  src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
  src/views/Pools/components/PoolsTable/Cells/IFOCreditCell.tsx
Labels: size/L

#9026 feat: Update Apply NFT link
  apps/web/src/views/Nft/market/Home/config.tsx
  apps/web/src/views/Nft/market/Home/index.tsx
Labels: size/S

#9028 fix: Transaction updater duplicate receipts
  apps/web/src/state/transactions/updater.tsx
Labels: size/XS

#9032 feat: List new pool
  .changeset/unlucky-rats-turn.md
  packages/pools/src/constants/pools/56.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/S

#9034 chore: Patch pools
  .changeset/unlucky-rats-turn.md
Labels: size/XS

#9035 feat: List gauges and new farm
  packages/farms/constants/eth.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/eth.ts
Labels: size/M

#9036 feat: List GTAI farm
  packages/farms/constants/bsc.ts
Labels: size/XS, automerge

#9045 chore: Add dlp mdlp stable pair
  .changeset/fifty-nails-sit.md
  packages/smart-router/evm/constants/stableSwap/arb.ts
  packages/tokens/src/constants/arb.ts
Labels: size/M

#9048 fix: Token list include path
  apps/web/src/config/constants/exchange.ts
  apps/web/src/hooks/useActiveWeb3React.ts
  apps/web/src/state/lists/updater.ts
Labels: size/S

#9015 feat: lottery CNY banner
  apps/web/public/images/lottery/cny-banner-coin.png
  apps/web/public/images/lottery/cny-banner-fruit.png
  apps/web/public/images/lottery/cny-banner-left-beak.png
  apps/web/public/images/lottery/cny-banner.png
  apps/web/public/images/lottery/cny-bunny.png
  apps/web/public/images/lottery/cny-golden-hat.png
  apps/web/public/images/lottery/cny-mobile-banner.png
  apps/web/src/components/Menu/index.tsx
  apps/web/src/views/Lottery/components/CnyBanner/CnyBanner.tsx
  apps/web/src/views/Lottery/components/CnyBanner/bannerConfig.ts
  apps/web/src/views/Lottery/components/Hero.tsx
  apps/web/src/views/Lottery/index.tsx
  apps/web/src/views/Lottery/pageSectionStyles.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/widgets/Menu/Menu.tsx
Labels: size/L

#9037 perf: Use account hook instead of web3
  apps/web/src/views/CakeStaking/components/LockCake/NotLocking.tsx
  apps/web/src/views/FixedStaking/hooks/useStakedPools.ts
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/index.tsx
  apps/web/src/views/PositionManagers/hooks/useAdapterInfo.ts
Labels: size/S

#9044 fix(Farms): Fix updatedTime translation
  packages/localization/src/config/translations.json
  packages/widgets-internal/farm/components/FarmTable/Liquidity.tsx
Labels: size/S

#9054 test: Skip pool testnet test
  apps/web/src/config/__tests__/pools.test.ts
Labels: size/XS

#9055 fix: now translation #9044
  packages/widgets-internal/farm/components/FarmTable/Liquidity.tsx
Labels: size/XS

#9056 fix: update cny banner
  apps/web/public/images/lottery/cny-banner.png
  apps/web/public/images/lottery/cny-mobile-banner.png
  apps/web/src/views/Lottery/components/CnyBanner/CnyBanner.tsx
  apps/web/src/views/Lottery/components/CnyBanner/bannerConfig.ts
Labels: size/M

#9063 fix: Crash in ifo
  .changeset/twelve-glasses-impress.md
  apps/web/src/components/SearchModal/CurrencySearch.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/MyReferralLink.tsx
  packages/localization/src/config/translations.json
  packages/widgets-internal/ifo/LockInfoCard.tsx
Labels: size/S

#9047 fix(v3-sdk): Remove tokens dependency
  .changeset/fresh-plants-applaud.md
  packages/v3-sdk/package.json
  packages/v3-sdk/src/utils/feeCalculator.test.ts
  pnpm-lock.yaml
Labels: size/M

#9059 feat: list sol gauges and farms
  packages/farms/constants/bsc.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/M

#9038 fix: Perpetual confirm modal can't be dismissed
  apps/web/src/components/Menu/index.tsx
  apps/web/src/views/Home/components/Banners/PerpetualApolloXCampaignBanner.tsx
  apps/web/src/views/Home/components/Banners/PerpetualBanner.tsx
  apps/web/src/views/Home/components/EcoSystemSection/index.tsx
Labels: size/XS

#9021 chore: Update linea subgraph
  apis/farms/src/lpApr.ts
  packages/chains/src/subgraphs.ts
Labels: size/M

#9016 fix: ts error
  apps/web/src/components/CurrencySelect/index.tsx
  apps/web/src/components/EasyMde/index.tsx
  apps/web/src/components/GlobalCheckClaimStatus/AnniversaryAchievementModal.tsx
  apps/web/src/components/Menu/UserMenu/WalletModal.tsx
  apps/web/src/quote-worker.ts
  apps/web/src/state/farms/fetchFarmUser.ts
  apps/web/src/views/CakeStaking/hooks/useGaugesVotingCount.ts
  apps/web/src/views/GaugesVoting/hooks/useUserVote.ts
  apps/web/src/views/GaugesVoting/hooks/useUserVoteGauges.ts
  apps/web/src/views/Voting/CreateProposal/index.tsx
  packages/smart-router/legacy-router/onchain/getStableSwapFee.ts
  packages/uikit/src/components/Chart/index.stories.tsx
  packages/uikit/src/components/Toast/Toast.stories.tsx
Labels: size/L

#9068 feat: List dmail farm
  packages/farms/constants/bsc.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/S

#9067 chore: Remove early v3 warning
  packages/localization/src/config/translations.json
  packages/widgets-internal/roi/RoiCalculator.tsx
Labels: size/M

#9070 fix: Supported chains not visible when no account connected
  apps/web/src/components/NetworkModal/NetworkModal.tsx
  apps/web/src/components/NetworkModal/UnsupportedNetworkModal.tsx
Labels: size/M

#9066 fix: ts error
  apps/web/package.json
  apps/web/src/state/farms/index.ts
  apps/web/src/views/Farms/components/BCakeMigrateModal.tsx
  apps/web/src/views/Farms/components/FarmCard/ApyButton.tsx
  apps/web/src/views/Farms/components/FarmCard/FarmCard.tsx
  apps/web/src/views/Farms/components/FarmCard/HarvestAction.tsx
  apps/web/src/views/Farms/components/FarmCard/StakeAction.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
  apps/web/src/views/Farms/components/YieldBooster/hooks/useProxyStakedActions.ts
  apps/web/src/views/Farms/hooks/useApproveFarm.ts
  apps/web/src/views/Farms/hooks/useFarmV2Multiplier.ts
  packages/farms/constants/priceHelperLps/5.ts
  packages/farms/src/defineFarmV3Configs.ts
  packages/farms/tsconfig.json
  packages/uikit/src/components/RoiCalculatorModal/RoiCalculatorFooter.tsx
  packages/uikit/src/components/RoiCalculatorModal/RoiCalculatorModal.tsx
  packages/widgets-internal/farm/components/DepositModal/index.tsx
Labels: size/L

#9073 chore: Bump token for missing sol
  .changeset/warm-ravens-shout.md
Labels: size/XS

#9076 feat: Move CAKEPIE IFO to finished
  packages/ifos/src/constants/ifos/bsc.ts
Labels: size/XS

#9069 feat: Hide Arbitrum prediction
  packages/prediction/src/chainlinkOracleContract.ts
  packages/prediction/src/constants/supportedChains.ts
  packages/prediction/src/endpoints.ts
  packages/prediction/src/galetoOracleContract.ts
  packages/prediction/src/predictionContract.ts
Labels: size/M

#9077 chore: update X weekly
  apps/web/src/views/Home/components/CommunitySection/TwitterCards.tsx
Labels: size/S

#9075 feat: List Defi pool
  .changeset/strange-garlics-end.md
  packages/pools/src/constants/pools/56.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/M

#9080 chore: log pageView data to datadog
  apps/web/src/hooks/useDataDogRUM.ts
  apps/web/src/utils/datadog.ts
Labels: size/S

#9085 feat: List Aptos farms
  apps/aptos/config/constants/farms/1.ts
Labels: size/S, automerge

#9084 fix: Tune wallet logging
  apps/web/src/hooks/useDataDogRUM.ts
  apps/web/src/utils/datadog.ts
Labels: size/M

#9086 fix: Confirm modal still visible when going back
  apps/web/src/components/Modal/USCitizenConfirmModal.tsx
Labels: size/S

#9029 chore: Remove deprecated jsx element
  apps/aptos/components/SearchModal/CurrencyList.tsx
  apps/web/src/pages/liquidity/index.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/PoolListItem.tsx
  apps/web/src/views/AddLiquidityV3/index.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/CommissionInfo.tsx
  apps/web/src/views/AffiliatesProgram/utils/commisionList.tsx
  apps/web/src/views/BuyCrypto/Icons/index.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/index.tsx
  apps/web/src/views/LiquidStaking/constants/types.ts
  apps/web/src/views/Notifications/components/NotificationHeader/NotificationHeader.tsx
  apps/web/src/views/Notifications/components/SettingsItem/SettingsItem.tsx
  apps/web/src/views/Pottery/components/WinRateModal/WinRateTvl.tsx
  apps/web/src/views/Predictions/History.tsx
  apps/web/src/views/TradingCompetition/components/Countdown/Timer.tsx
Labels: size/M

#9088 chore: Add missing translation
  apps/web/src/views/Pools/components/PoolsTable/PoolRow.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#9091 chore: Clean up Ts error
  apps/web/src/components/Menu/hooks/useMenuItems.ts
  apps/web/src/components/Menu/hooks/useTradingRewardStatus.ts
  apps/web/src/components/Modal/Spacer.tsx
  apps/web/src/state/farms/fetchFarmUser.ts
  apps/web/src/views/TradingCompetition/components/Countdown/ProgressStepper.tsx
  apps/web/src/views/Voting/CreateProposal/helpers.ts
  apps/web/src/views/Voting/CreateProposal/index.tsx
  apps/web/src/views/Voting/CreateProposal/types.ts
  packages/uikit/src/widgets/Modal/Spacer.tsx
Labels: size/M

#9089 fix: Missing translations and typos in notification events
  apps/web/src/components/Menu/GlobalSettings/WebNotiToggle.tsx
  apps/web/src/views/Notifications/constants.ts
  apps/web/src/views/Notifications/containers/NotificationSettings.tsx
  apps/web/src/views/Notifications/containers/OnBoardingView.tsx
  apps/web/src/views/Notifications/hooks/sendPushNotification.ts
  apps/web/src/views/Notifications/index.tsx
  apps/web/src/views/Notifications/types.ts
  packages/localization/src/config/translations.json
Labels: size/L

#9093 feat(worker): Add opbnb endpoint
  apis/proxy-worker/src/bindings.d.ts
  apis/proxy-worker/src/index.ts
Labels: size/M

#9095 chore: Bump swap sdk core for updated address types
  .changeset/late-years-rescue.md
Labels: size/XS

#9096 fix: update subgraph endpoint
  apps/web/src/views/V3Info/hooks/index.ts
Labels: size/M

#9101 chore: remove ts error
  apps/web/src/hooks/useApproveConfirmTransaction.tsx
  apps/web/src/pages/profile/[accountAddress].tsx
  apps/web/src/pages/remove/[tokenId].tsx
  apps/web/src/pages/stable/add/[[...currency]].tsx
  apps/web/src/pages/stable/remove/[[...currency]].tsx
  apps/web/src/pages/teams/[id].tsx
  apps/web/src/pages/v2/add/[[...currency]].tsx
  apps/web/src/pages/v2/remove/[[...currency]].tsx
  apps/web/src/pages/voting/proposal/[id].tsx
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/shared/ManageNFTsCard.tsx
  apps/web/src/views/Nft/market/hooks/useNftsForAddress.tsx
  apps/web/src/views/Profile/components/EditProfileModal/ChangeProfilePicView.tsx
  apps/web/src/views/Profile/components/ProfileHeader.tsx
  apps/web/src/views/Profile/index.tsx
  apps/web/src/views/ProfileCreation/ProfilePicture.tsx
  apps/web/src/views/Voting/Proposal/Vote.tsx
  apps/web/src/views/Voting/Proposal/Votes.tsx
  apps/web/src/views/Voting/components/CastVoteModal/DetailsView.tsx
  apps/web/src/views/Voting/components/CastVoteModal/index.tsx
Labels: size/L

#9102 feat: add base gauges
  packages/gauges/src/constants/config/prod.ts
Labels: size/L

#9103 feat: add pixel farm
  packages/farms/constants/eth.ts
  packages/tokens/src/constants/eth.ts
Labels: size/S

#9098 chore: Update ND descriptions based on feedback
  packages/games/src/constants/games/nemesisDownfall.ts
Labels: size/XS

#8560 feat(Game): Support multiple games layout
  apps/games/components/Game/Community/Banner/index.tsx
  apps/games/components/Game/Home/Game.tsx
  apps/games/components/Game/Home/Games.tsx
  apps/games/components/Game/Home/OtherGames.tsx
  apps/games/components/Game/Home/TrendingTags.tsx
  apps/games/components/Game/index.tsx
  apps/games/components/Game/project.tsx
  apps/games/hooks/useGameLink.ts
  apps/games/utils/getGameLink.ts
  packages/games/src/constants/games/binaryX.ts
  packages/games/src/constants/games/example.ts
  packages/games/src/constants/games/index.ts
  packages/games/src/constants/games/nemesisDownfall.ts
  packages/games/src/constants/games/pancakeProtectors.ts
  packages/games/src/types.ts
Labels: Delayed Release, size/L

#9111 ci: Update farm config branch
  .github/workflows/farmConfig.yml
Labels: size/XS

#9113 feat: add zkEVM lst farms
  packages/farms/constants/polygonZkEVM.ts
  packages/tokens/src/constants/polygonZkEVM.ts
Labels: size/M

#9112 feat(web): Expose farm config api
  apps/web/src/pages/api/configs/farms/[chain].ts
  apps/web/src/pages/api/configs/farms/index.ts
Labels: size/M

#9115 feat: xrgb farm & csix Syrup Pools
  packages/farms/constants/bsc.ts
  packages/pools/src/constants/pools/56.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/S

#9128 feat: list xrgb eth farm
  packages/farms/constants/eth.ts
  packages/tokens/src/constants/eth.ts
Labels: size/S

#9125 chore: Fix eslint warnings
  apps/web/src/components/Modal/USCitizenConfirmModal.tsx
  apps/web/src/views/V3Info/hooks/index.ts
Labels: size/XS

#9129 feat: token alias
  apps/web/src/state/info/constant.ts
  apps/web/src/utils/getSymbolAlias.ts
  apps/web/src/utils/getTokenAlias.ts
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/V3Info/components/Search/index.tsx
  apps/web/src/views/V3Info/components/TransactionsTable/index.tsx
  apps/web/src/views/V3Info/views/PoolPage.tsx
Labels: size/L

#9130 fix: remove duplicated linea farm config
  packages/farms/constants/linea.ts
  packages/farms/tests/v3.test.ts
Labels: size/M

#9131 feat: token alias
  apps/web/src/views/AddLiquidityV3/components/StablePairCard.tsx
  apps/web/src/views/Info/components/InfoSearch/index.tsx
  apps/web/src/views/Info/components/InfoTables/PoolsTable.tsx
  apps/web/src/views/Info/components/InfoTables/TransactionsTable.tsx
  apps/web/src/views/LiquidStaking/constants/56.ts
  apps/web/src/views/LiquidStaking/constants/types.ts
  apps/web/src/views/V3Info/components/PoolTable/index.tsx
  apps/web/src/views/V3Info/components/Search/index.tsx
  apps/web/src/views/V3Info/views/TokenPage.tsx
  packages/farms/constants/bsc.ts
  packages/gauges/src/constants/config/prod.ts
  packages/smart-router/evm/constants/stableSwap/bsc.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/L

#9133 feat: token alias patch
  apps/web/src/views/Info/Tokens/TokenPage.tsx
  apps/web/src/views/Info/components/InfoTables/TokensTable.tsx
  apps/web/src/views/Info/components/InfoTables/TransactionsTable.tsx
  apps/web/src/views/V3Info/components/TokenTable/index.tsx
  apps/web/src/views/V3Info/views/PoolPage.tsx
  packages/farms/constants/bsc.ts
  packages/gauges/src/constants/config/prod.ts
  packages/smart-router/evm/constants/stableSwap/bsc.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/M

#9134 feat: add 2 bnb v2 farm
  packages/farms/constants/bsc.ts
Labels: size/S

#9136 feat: Use llama api to get block timestamps
  apps/web/src/utils/getBlocksFromTimestamps.ts
Labels: size/M

#9132 feat: New Farms on Polygon zkEVM and zkSync
  packages/farms/constants/polygonZkEVM.ts
  packages/farms/constants/zkSync.ts
Labels: size/S

#9144 fix: typo
  apps/web/src/components/Menu/GlobalSettings/SettingsModal.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/Question.tsx
  apps/web/src/views/FixedStaking/components/WithdrawalMessage.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#9147 chore: Reduce sample rate
  apps/web/src/utils/datadog.ts
Labels: size/XS

#9123 fix: Use same currency display components when removing liquidity
  apps/web/src/views/RemoveLiquidity/RemoveLiquidityV3.tsx
Labels: size/S

#9141 chore: Ts error patch 4
  apps/web/src/pages/liquidity/index.tsx
  apps/web/src/state/info/types.ts
  apps/web/src/state/lists/hooks.ts
  apps/web/src/state/lottery/fetchUnclaimedUserRewards.ts
  apps/web/src/state/lottery/getLotteriesData.ts
  apps/web/src/state/lottery/getUserLotteryData.ts
  apps/web/src/state/lottery/getUserTicketsData.ts
  apps/web/src/state/lottery/helpers.ts
  apps/web/src/state/lottery/index.ts
  apps/web/src/state/mint/hooks.ts
  apps/web/src/state/multicall/retry.test.ts
  apps/web/src/state/pools/helpers.ts
  apps/web/src/state/pools/hooks.ts
  apps/web/src/state/pools/selectors.ts
  apps/web/src/state/pottery/index.ts
  apps/web/src/state/profile/helpers.ts
  apps/web/src/state/profile/hooks.ts
  apps/web/src/state/swap/hooks.test.ts
  apps/web/src/state/swap/useStableSwapPairs.ts
  apps/web/src/state/teams/helpers.ts
  apps/web/src/state/transactions/actions.ts
  apps/web/src/state/transactions/reducer.ts
  apps/web/src/state/types.ts
  apps/web/src/views/Swap/hooks/useStableConfig.ts
Labels: size/XL

#9124 fix: Cake circulating supply info
  apps/web/src/views/Home/components/CakeDataRow.tsx
Labels: size/S

#9120 feat: Remove autoplay
  apps/games/components/Game/Home/Games.tsx
Labels: size/XS

#9114 fix: Remove v3 liquidity info not shown when has 0 percent
  apps/web/src/hooks/v3/useDerivedV3BurnInfo.ts
Labels: size/XS

#9110 feat(gauges): Allow fetch on block number
  .changeset/large-bats-sleep.md
  apps/web/src/config/nodes.ts
  apps/web/src/pages/api/gauges/getAllGauges.ts
  apps/web/src/views/GaugesVoting/components/WeightsPieChart.tsx
  packages/gauges/src/fetchAllGauges.ts
  packages/gauges/src/fetchAllKilledGauges.ts
  packages/gauges/src/fetchGaugeVoting.ts
  packages/gauges/src/fetchGaugesCount.ts
  packages/gauges/src/getAllGauges.ts
  packages/gauges/src/types.ts
Labels: size/M

#9013 chore: add position manager startTime filter
  apps/web/src/views/PositionManagers/containers/PCSVaultCard.tsx
  apps/web/src/views/PositionManagers/containers/VaultCards.tsx
  apps/web/src/views/PositionManagers/hooks/usePositionManagerDetailsData.ts
Labels: size/S

#9151 fix: Address too long
  apps/web/src/views/TradingReward/components/Leaderboard/MobileResult.tsx
Labels: size/S, automerge

#9155 fix: Missing per symbol translation
  apps/web/src/components/RangePriceSection/index.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
  apps/web/src/views/LimitOrders/components/LimitOrderPrice.tsx
  apps/web/src/views/LimitOrders/components/LimitOrderTable/CompactRow.tsx
Labels: size/S

#9161 chore: list XRGB pools on BSC
  packages/pools/src/constants/pools/56.ts
Labels: size/XS

#9156 fix: Use lowercase instead of locale for address comparisons
  apps/web/src/config/__tests__/tokens.test.ts
  apps/web/src/hooks/usePoolAvgInfo.ts
  apps/web/src/state/transactions/actions.ts
  apps/web/src/state/transactions/hooks.tsx
  apps/web/src/views/PositionManagers/hooks/useViewMode.ts
  apps/web/src/views/Predictions/components/History/PnlTab/SummaryRow.tsx
  apps/web/src/views/Predictions/components/TradingView.tsx
  apps/web/src/views/Predictions/context/ConfigProvider.tsx
  apps/web/src/views/Swap/components/Chart/PriceChartContainer.tsx
  apps/web/src/views/V3Info/data/pool/topPools.ts
  apps/web/src/views/V3Info/data/search/index.ts
Labels: size/M

#9159 feat: Add NemesisDownfall Banner
  apps/web/src/views/Home/components/Banners/NemesisDownfallBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/games/src/constants/games/nemesisDownfall.ts
  packages/localization/src/config/translations.json
  packages/widgets-internal/components/Banner/BannerActionContainer.tsx
  packages/widgets-internal/components/Banner/BannerContainer.tsx
  packages/widgets-internal/components/Banner/BannerGraphics.tsx
  packages/widgets-internal/components/Banner/BannerTitle.tsx
  packages/widgets-internal/components/Banner/actions/ButtonLink.tsx
  packages/widgets-internal/components/Banner/actions/LinkExternal.tsx
  packages/widgets-internal/components/Banner/actions/index.ts
  packages/widgets-internal/components/Banner/badges/PancakeSwapBadge.tsx
  packages/widgets-internal/components/Banner/index.ts
Labels: size/L

#9165 fix: Game url
  apps/games/utils/getGameLink.ts
  apps/web/src/views/Home/components/Banners/NemesisDownfallBanner.tsx
Labels: size/XS

#9168 chore: Make token warning links external
  apps/web/src/views/Swap/components/SwapWarningModal/56/LUSDWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/56/METISWarning.tsx
Labels: size/S

#9051 feat: wormhole bridge widget FE integration
  apps/bridge/.env.example
  apps/bridge/Providers.tsx
  apps/bridge/components/DisclaimerModal/DisclaimerModal.tsx
  apps/bridge/components/GeneralDisclaimerModal/GeneralRiskAcceptModal.tsx
  apps/bridge/components/GeneralDisclaimerModal/config.ts
  apps/bridge/components/Menu.tsx
  apps/bridge/components/Page.tsx
  apps/bridge/components/WormHole/WormholeWidget.tsx
  apps/bridge/components/WormHole/chains.ts
  apps/bridge/components/WormHole/components/Page.tsx
  apps/bridge/components/WormHole/constants.ts
  apps/bridge/components/WormHole/theme.ts
  apps/bridge/components/WormHole/types.ts
  apps/bridge/components/layerZero/index.tsx
  apps/bridge/package.json
  apps/bridge/pages/_app.tsx
  apps/bridge/pages/wormhole-aptos.tsx
  apps/bridge/pages/wormhole.tsx
  apps/bridge/state/alexar/useAlexarDisclaimer.ts
  apps/bridge/state/stargate/useStargateDisclaimer.ts
  apps/bridge/state/useGetBridgeDisclaimerState.ts
  apps/bridge/state/wormhole/enableTestnet.ts
  apps/bridge/state/wormhole/useWormholeDisclaimer.ts
  apps/bridge/tsconfig.json
  apps/bridge/utils/atomWithStorageWithErrorCatch.ts
  apps/bridge/utils/nodes/nodereal.ts
  apps/bridge/utils/nodes/pokt.ts
  apps/web/src/__tests__/translations.test.ts
  packages/localization/src/config/translations.json
  pnpm-lock.yaml
Labels: size/XXL

#9160 chore: list PM vaults on Eth
  apps/web/src/views/PositionManagers/containers/VaultCards.tsx
  apps/web/src/views/PositionManagers/hooks/useApr.ts
  apps/web/src/views/PositionManagers/hooks/useFilters.ts
  packages/position-managers/src/constants/vaults/eth.ts
Labels: size/M

#9162 chore: list new farms and gauges
  packages/farms/constants/bsc.ts
  packages/farms/constants/linea.ts
  packages/farms/constants/polygonZkEVM.ts
  packages/farms/constants/zkSync.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/bsc.ts
  packages/tokens/src/constants/zkSync.ts
Labels: size/L

#9172 chore: update eth PM vault adapter address
  packages/position-managers/src/constants/vaults/eth.ts
Labels: size/XS

#9173 chore: update bridge guide docs link
  apps/bridge/components/DisclaimerModal/DisclaimerModal.tsx
Labels: size/XS

#9176 chore: update pnpm version to use latest
  package.json
Labels: size/XS

#9178 chore: list new gauges and farms
  packages/farms/constants/base.ts
  packages/farms/constants/linea.ts
  packages/farms/constants/polygonZkEVM.ts
  packages/farms/constants/zkSync.ts
  packages/gauges/src/constants/config/prod.ts
Labels: size/L
