Repository pancakeswap/pancake-frontend, pull requests merged in 2024-09, with the labels that each got.

#10593 chore: Add GA in position manager
  apps/web/src/utils/customGTMEventTracking.ts
  apps/web/src/views/PositionManagers/components/AddLiquidity.tsx
Labels: size/S

#10596 feat: dola farm
  packages/farms/src/farms/base.ts
  packages/tokens/src/constants/base.ts
Labels: size/S

#10233 chore: Remove farm community auction page
  apps/web/src/pages/farms/auction.tsx
  apps/web/src/state/farms/fetchFarmsWithAuctions.ts
  apps/web/src/views/FarmAuction/components/AuctionCakeBurn.tsx
  apps/web/src/views/FarmAuction/components/AuctionDetailsCard/AuctionFooter.tsx
  apps/web/src/views/FarmAuction/components/AuctionDetailsCard/AuctionSchedule.tsx
  apps/web/src/views/FarmAuction/components/AuctionDetailsCard/CannotBidMessage.tsx
  apps/web/src/views/FarmAuction/components/AuctionDetailsCard/index.tsx
  apps/web/src/views/FarmAuction/components/AuctionHistory.tsx
  apps/web/src/views/FarmAuction/components/AuctionLeaderboard/AuctionLeaderboardTable.tsx
  apps/web/src/views/FarmAuction/components/AuctionLeaderboard/AuctionProgress.tsx
  apps/web/src/views/FarmAuction/components/AuctionLeaderboard/AuctionRibbon.tsx
  apps/web/src/views/FarmAuction/components/AuctionLeaderboard/index.tsx
  apps/web/src/views/FarmAuction/components/AuctionTimer.tsx
  apps/web/src/views/FarmAuction/components/CongratulationsCard.tsx
  apps/web/src/views/FarmAuction/components/FAQs.tsx
  apps/web/src/views/FarmAuction/components/NotWhitelistedNotice.tsx
  apps/web/src/views/FarmAuction/components/PlaceBidModal.tsx
  apps/web/src/views/FarmAuction/components/ReclaimBidCard.tsx
  apps/web/src/views/FarmAuction/components/WhitelistedBiddersButton.tsx
  apps/web/src/views/FarmAuction/components/WhitelistedBiddersModal.tsx
  apps/web/src/views/FarmAuction/constants.ts
  apps/web/src/views/FarmAuction/helpers.tsx
  apps/web/src/views/FarmAuction/hooks/useCongratulateAuctionWinner.tsx
  apps/web/src/views/FarmAuction/hooks/useCurrentFarmAuction.ts
  apps/web/src/views/FarmAuction/hooks/useFarmAuction.ts
  apps/web/src/views/FarmAuction/hooks/useReclaimAuctionBid.ts
  apps/web/src/views/FarmAuction/hooks/useV3FarmAuctionConfig.ts
  apps/web/src/views/FarmAuction/hooks/useWhitelistedAddresses.ts
  apps/web/src/views/FarmAuction/index.tsx
  apps/web/src/views/Farms/Farms.tsx
  apps/web/src/views/Farms/FarmsV3.tsx
  packages/localization/src/config/translations.json
Labels: size/XXL

#10602 fix: ss lp fee tier
  apps/web/src/state/farmsV4/state/farmPools/fetcher.ts
Labels: size/S

#10600 chore: Bump up swiper
  apps/aptos/package.json
  apps/blog/package.json
  apps/games/package.json
  apps/gamification/package.json
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/L

#10605 fix: temporarily remove cmc arb list
  apps/web/src/config/constants/lists.ts
Labels: size/S

#10606 fix: fee base
  apps/web/src/state/farmsV4/state/farmPools/fetcher.ts
Labels: size/XS

#10607 chore: Update Event
  apps/web/src/utils/customGTMEventTracking.ts
  apps/web/src/views/CakeStaking/hooks/useContractWrite/useWriteWithApproveCallback.ts
Labels: size/S

#10608 feat: omit pid
  packages/farms/src/utils.ts
Labels: size/S

#10609 chore: Update expired popup list
  .github/actions/install-deps/action.yml
  apps/web/src/components/Modal/AffiliateExpiredModal.tsx
  apps/web/src/hooks/useAffiliateExpired.ts
  package.json
  packages/localization/src/config/translations.json
Labels: size/L

#10612 chore: add hackathon banner
  apps/web/src/views/Home/components/Banners/HackathonBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#10601 feat: remove old farm config
  apps/web/src/config/__tests__/farms.test.ts
  packages/farms/constants/arb.ts
  packages/farms/constants/base.ts
  packages/farms/constants/bsc.ts
  packages/farms/constants/bscTestnet.ts
  packages/farms/constants/eth.ts
  packages/farms/constants/linea.ts
  packages/farms/constants/opBNB.ts
  packages/farms/constants/opBnbTestnet.ts
  packages/farms/constants/polygonZkEVM.ts
  packages/farms/constants/polygonZkEVMTestnet.ts
  packages/farms/constants/v3/index.ts
  packages/farms/constants/zkSync.ts
  packages/farms/constants/zkSyncTestnet.ts
  packages/farms/scripts/build.ts
  packages/farms/src/getLegacyFarmConfig.test.ts
  packages/farms/tests/v3.test.ts
Labels: size/XXL

#10613 feat: new syrup pool
  packages/pools/src/constants/pools/56.ts
Labels: size/XS

#10614 revert: Update expired popup list (#10609)
  .github/actions/install-deps/action.yml
  apps/web/src/components/Modal/AffiliateExpiredModal.tsx
  apps/web/src/hooks/useAffiliateExpired.ts
  package.json
  packages/localization/src/config/translations.json
Labels: size/L

#10595 fix: Provider exist check when window null
  .changeset/old-cats-wink.md
  packages/wagmi/connectors/trustWallet/trustWallet.ts
Labels: size/S, Sentry

#10590 fix: Token address crash in fixed staking
  apps/web/src/views/FixedStaking/hooks/useStakedPools.ts
Labels: size/M, Sentry

#10577 chore: add topper campaign banner
  apps/web/src/views/Home/components/Banners/TopperCampaignBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#10619 chore: remove banners
  apps/web/src/components/PhishingWarningBanner/index.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/M

#10620 feat: PNP & mPENDLE token warning
  apps/web/src/config/constants/swapWarningTokens.ts
  apps/web/src/config/constants/warningTokens/arbitrumWarningTokens.ts
  apps/web/src/config/constants/warningTokens/bscWarningTokens.ts
  apps/web/src/views/Swap/components/SwapWarningModal/arbitrum/index.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/arbitrum/mPendleWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/PNPWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/index.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/index.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#10611 feat: reflect filter to URL query
  apps/web/src/views/universalFarms/PoolsPage.tsx
  apps/web/src/views/universalFarms/PositionPage.tsx
  apps/web/src/views/universalFarms/components/PoolsFilterPanel.tsx
  apps/web/src/views/universalFarms/hooks/useFilterToQueries.ts
Labels: size/L

#10599 fix: drop the session chainId
  apps/web/src/config/constants/index.ts
  apps/web/src/hooks/useActiveChainId.ts
  apps/web/src/hooks/useActiveWeb3React.ts
  apps/web/src/views/universalFarms/components/PositionItem/PositionItem.tsx
Labels: size/M

#10622 fix: missed v2/ss bCakeWrapperAddr
  apps/web/src/state/farmsV4/state/farmPools/fetcher.ts
Labels: size/XS

#10610 fix: Crash in position manager fetch apr
  apps/web/src/views/PositionManagers/hooks/useFetchApr.ts
Labels: size/XS, Sentry

#10624 fix: Error when drawing image on context
  apps/web/src/views/Home/hooks/useDrawSequence.ts
Labels: size/XS, Sentry

#10591 fix: Crash nft activity collection filter
  apps/gamification/views/Profile/hooks/useNftStorage.tsx
  apps/web/src/state/nftMarket/storage.ts
Labels: size/S, Sentry

#10623 fix: Crash cake staking input
  apps/web/src/views/CakeStaking/components/LockCakeForm.tsx
Labels: size/XS, Sentry

#10618 revert: Update expired popup list
  .github/actions/install-deps/action.yml
  apps/web/src/components/Modal/AffiliateExpiredModal.tsx
  apps/web/src/hooks/useAffiliateExpired.ts
  package.json
  packages/localization/src/config/translations.json
Labels: size/L

#10630 chore: add GA in prediction
  apps/web/src/utils/customGTMEventTracking.ts
  apps/web/src/views/Predictions/components/RoundCard/OpenRoundCard.tsx
Labels: size/M

#10633 chore: Increase traffic for price api
  apps/web/src/config/experimentalFeatures.ts
Labels: size/XS

#10587 chore: add user's nonce to paymaster txn
  apps/web/src/hooks/usePaymaster.ts
Labels: size/XS

#10628 fix: Network switch when no account connected and liquidity link with different chain in positions
  apps/web/src/components/NetworkModal/WrongNetworkModal.tsx
  apps/web/src/components/NetworkSwitcher.tsx
  apps/web/src/hooks/useActiveChainId.ts
  apps/web/src/hooks/useAuth.tsx
  apps/web/src/hooks/useSwitchNetwork.ts
  apps/web/src/utils/addQueryToPath.ts
  apps/web/src/views/PoolDetail/components/MyPositions.tsx
  apps/web/src/views/universalFarms/components/PoolListItemAction.tsx
  apps/web/src/views/universalFarms/components/PositionActions/V3UnstakeModalContent.tsx
  apps/web/src/views/universalFarms/components/PositionItem/PositionItem.tsx
  apps/web/src/views/universalFarms/utils/index.ts
Labels: size/L

#10636 refactor: rename mBTC
  packages/tokens/src/constants/eth.ts
Labels: size/XS

#10640 chore: update stake/unstake pool in Aptos
  apps/aptos/components/Pools/components/PoolCard/StakeModalContainer.tsx
  apps/aptos/components/Swap/SwapModalFooter.tsx
  apps/aptos/utils/customGTMEventTracking.ts
Labels: size/M

#10644 feat: list-new-farms-base-arb
  .changeset/kind-frogs-rescue.md
  packages/farms/src/farms/arb.ts
  packages/farms/src/farms/base.ts
  packages/farms/src/farms/index.test.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/arb.ts
  packages/tokens/src/constants/base.ts
Labels: size/XL

#10511 chore: Remove warnings
  apps/web/src/pages/liquidity/index.tsx
  apps/web/src/views/BuyCrypto/components/EnableNotificationTooltip/EnableNotificationsTooltip.tsx
  apps/web/src/views/BuyCrypto/components/OnRampCurrencySelect/index.tsx
  apps/web/src/views/Home/components/Banners/BrasilMeetupBanner.tsx
  apps/web/src/views/Home/components/Banners/WebNotificationBanner.tsx
  apps/web/src/views/Notifications/constants.ts
  packages/localization/src/config/translations.json
Labels: size/S

#10522 chore: Bump up tanstack/query to 5.52.1
  apps/aptos/package.json
  apps/blog/package.json
  apps/games/package.json
  apps/gamification/package.json
  apps/web/package.json
  apps/web/src/hooks/useGasSponsorshipBalance.ts
  packages/awgmi/package.json
  packages/awgmi/src/hooks/useAccountBalance.ts
  packages/awgmi/src/hooks/useAccountBalances.ts
  packages/awgmi/src/hooks/useAccountResources.ts
  packages/wagmi/package.json
  pnpm-lock.yaml
Labels: size/L

#10509 fix: Add modal title translation to vecake add modal
  apps/web/src/views/TradingReward/components/YourTradingReward/VeCake/VeCakeAddCakeOrWeeksModal.tsx
Labels: size/XS

#10258 chore: Remove unused components from voting
  apps/web/src/views/Voting/components/Proposals/index.tsx
  apps/web/src/views/Voting/config.ts
  apps/web/src/views/Voting/helpers.ts
  apps/web/src/views/Voting/strategies.ts
Labels: size/L

#10649 fix: Update integrity trading view chart
  apps/web/src/components/TradingView.tsx
Labels: size/XS

#10650 fix: Crash liquidity with wrong url
  apps/web/src/pages/increase/[[...currency]].tsx
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/pages/remove/[tokenId].tsx
  apps/web/src/pages/stable/add/[[...currency]].tsx
  apps/web/src/pages/v2/add/[[...currency]].tsx
Labels: size/S, Sentry

#10555 feat: Integrate zap widget
  apps/web/package.json
  apps/web/src/__tests__/translations.test.ts
  apps/web/src/components/ZapLiquidityWidget.tsx
  apps/web/src/config/constants/zapV3.ts
  apps/web/src/hooks/useTradeVerifiedByQuoter.ts
  apps/web/src/hooks/v3/types.ts
  apps/web/src/hooks/v3/useV3DerivedInfo.ts
  apps/web/src/pages/stable/add/[[...currency]].tsx
  apps/web/src/pages/v2/add/[[...currency]].tsx
  apps/web/src/state/mint/actions.ts
  apps/web/src/state/mint/hooks.ts
  apps/web/src/state/mint/reducer.test.ts
  apps/web/src/state/mint/reducer.ts
  apps/web/src/state/transactions/actions.ts
  apps/web/src/utils/types.ts
  apps/web/src/views/AddLiquidity/AddStableLiquidity/hooks/useStableLPDerivedMintInfo.tsx
  apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
  apps/web/src/views/AddLiquidity/PoolPriceBar.tsx
  apps/web/src/views/AddLiquidity/index.tsx
  apps/web/src/views/AddLiquidityV3/IncreaseLiquidityV3.tsx
  apps/web/src/views/AddLiquidityV3/Modal.tsx
  apps/web/src/views/AddLiquidityV3/components/ApproveLiquidityTokens.tsx
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
  apps/web/src/views/AddLiquidityV3/components/V3SubmitButton.tsx
  apps/web/src/views/AddLiquidityV3/formViews/StableFormView.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V2FormView.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/form/actions.ts
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/form/hooks/useV3MintActionHandlers.ts
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/form/reducer.ts
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
  apps/web/src/views/AddLiquidityV3/index.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3ApyButton.tsx
  apps/web/src/views/Home/components/Banners/BrasilMeetupBanner.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/PoolPositionAprButton.tsx
  apps/web/src/views/universalFarms/components/PositionItem/PriceRange.tsx
  packages/localization/src/config/translations.json
  pnpm-lock.yaml
Labels: Delayed Release, size/XL

#10656 chore: Update wording
  apps/web/src/components/ZapLiquidityWidget.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#10657 fix: Use sha-384 for integrity
  apps/web/src/components/TradingView.tsx
  apps/web/src/pages/_app.tsx
Labels: size/XS

#10658 chore: Add fee info report
  .github/actions/install-deps/action.yml
  apps/web/src/components/ZapLiquidityWidget.tsx
  package.json
Labels: size/S

#10663 chore: List syrup pool
  packages/pools/src/constants/pools/1101.ts
  packages/pools/src/constants/pools/56.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/M

#10653 feat: Add Tg prediction bot banner
  apps/web/src/views/Home/components/Banners/TgPredictionBotBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useIsRenderTgPredictionBotBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
Labels: size/L, automerge

#10660 chore: add new gauges
  packages/farms/src/farms/polygonZkEVM.ts
  packages/gauges/src/constants/config/prod.ts
Labels: size/M

#10668 chore: add uni btc farm
  packages/farms/src/farms/bsc.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/S

#10669 fix: poolsStatus out of bound
  apps/web/src/state/farmsV4/state/farmPools/hooks.ts
Labels: size/XS

#10670 fix: Farm exception
  packages/farms/src/farms/polygonZkEVM.ts
Labels: size/XS

#10671 feat: add pid test
  packages/farms/src/farms/index.test.ts
Labels: size/S

#10674 fix: Unable to verify quote in native token
  apps/web/src/hooks/useTradeVerifiedByQuoter.ts
Labels: size/XS

#10667 chore: Bump up wagmi 2.12.10
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: size/L

#10666 fix: Isuserrejected error when cause exists but undefined
  apps/web/sentry.client.config.js
  apps/web/src/utils/sentry.ts
Labels: size/XS, Sentry

#10665 chore: Remove warnings
  apps/aptos/components/CurrencyInputPanel/index.tsx
  apps/aptos/components/SearchModal/CurrencyList.tsx
  apps/gamification/views/Campaign/components/QuestList.tsx
  apps/gamification/views/Dashboard/components/DashboardLayout.tsx
  apps/gamification/views/DashboardCampaignEdit/components/ImageUpload.tsx
  apps/gamification/views/DashboardQuestEdit/components/SubmitAction/ActionModal.tsx
  apps/gamification/views/DashboardQuestEdit/components/Tasks/AddHoldToken.tsx
  apps/gamification/views/Profile/components/ProfileHeader.tsx
  apps/gamification/views/ProfileCreation/Nft/helpers.ts
  apps/web/src/hooks/useSwitchNetwork.ts
  apps/web/src/views/BuyCrypto/components/OnRampCurrencySelect/index.tsx
  apps/web/src/views/Farms/Farms.tsx
  apps/web/src/views/Farms/FarmsV3.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  apps/web/src/views/Info/Pools/PoolPage.tsx
Labels: size/L

#10673 feat: add new ALMs
  packages/position-managers/src/constants/vaults/bsc.ts
Labels: size/M

#10675 chore: list cbBTC on eth and base
  packages/tokens/src/constants/base.ts
  packages/tokens/src/constants/eth.ts
Labels: size/S

#10679 chore: Update wording for 451
  apps/web/src/pages/451.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#10682 fix: Crash in gauges voting
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/hooks/useGaugeRows.ts
Labels: size/XS, Sentry

#10685 chore: list new farms on eth and base
  packages/farms/src/farms/base.ts
  packages/farms/src/farms/eth.ts
Labels: size/M

#10686 chore: list new gauges
  packages/gauges/src/constants/config/prod.ts
Labels: size/M

#10690 chore: remove topper campaign and banner
  apps/web/src/views/BuyCrypto/components/ProviderCampaign/ProviderCampaign.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/XS

#10691 fix: No quote for exact output
  .changeset/slow-cougars-sparkle.md
  packages/routing-sdk/src/findBestTrade.ts
Labels: size/S

#10694 chore: Add security header
  apps/gamification/next.config.mjs
Labels: size/XS

#10684 fix: Filter out tokens in list that are not matching the criteria
  .changeset/funny-mirrors-rescue.md
  packages/token-lists/react/getTokenList.ts
Labels: size/S

#10695 chore: Upgrade nextjs
  apps/aptos/package.json
  apps/blog/package.json
  apps/bridge/package.json
  apps/games/package.json
  apps/gamification/package.json
  apps/web/package.json
  examples/playground/package.json
  packages/next-config/package.json
  packages/widgets-internal/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: size/L

#10698 chore: Bump wagmi and viem
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: size/L

#10700 chore: update ifo and its banner config
  apps/web/src/views/Home/components/Banners/hooks/useIsRenderIFOBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/ifos/src/constants/ifos/arb.ts
  packages/ifos/src/types.ts
Labels: size/M

#10689 fix: Number display
  apps/gamification/views/Dashboard/components/DashboardLayout.tsx
  apps/gamification/views/Quest/components/Reward/SuccessClaimedModal.tsx
  apps/gamification/views/Quest/index.tsx
Labels: size/S

#10701 feat: Add eth reactor and quoter
  .changeset/weak-years-nail.md
  packages/pcsx-sdk/src/constants.ts
Labels: size/S

#10704 chore: list new farm on bsc
  packages/farms/src/farms/bsc.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/S

#10703 feat: Make crosschain ifo info visible on other chains
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/components/Menu/hooks/useIfoStatus.ts
  apps/web/src/hooks/useIfoConfig.ts
  apps/web/src/views/Home/components/Banners/hooks/useIsRenderIFOBanner.tsx
  packages/ifos/src/constants/ifos/goerli.ts
Labels: size/M

#10676 fix: Apr in add liquidity
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountV3Position.ts
  apps/web/src/views/AddLiquidityV3/Modal.tsx
  apps/web/src/views/AddLiquidityV3/components/AprCalculatorV2.tsx
  apps/web/src/views/AddLiquidityV3/index.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/PoolPositionAprButton.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/V3PoolAprModal.tsx
Labels: size/L

#10710 chore: Use metamask sdk for wallet connect
  apps/web/next-env.d.ts
  apps/web/src/config/wallet.ts
  apps/web/src/utils/wagmi.ts
Labels: size/XS

#10711 chore: update arb ifo address
  packages/ifos/src/constants/ifos/arb.ts
Labels: size/XS

#10714 Revert "chore: Use metamask sdk for wallet connect"
  apps/web/next-env.d.ts
  apps/web/src/config/wallet.ts
  apps/web/src/utils/wagmi.ts
Labels: size/XS

#10715 fix: Chain param in query after switching network to bsc
  apps/web/src/components/NetworkModal/WrongNetworkModal.tsx
  apps/web/src/hooks/useSwitchNetwork.ts
Labels: size/XS

#10718 fix: Task completed
  apps/gamification/views/Quest/index.tsx
Labels: size/XS, automerge

#10712 chore: remove predictions in-page banner
  apps/web/src/views/Predictions/index.tsx
Labels: size/XS

#10721 chore: Update footer earn link
  packages/uikit/src/widgets/Menu/components/footerConfig.ts
Labels: size/XS

#10699 feat: Add make a bet
  apps/gamification/components/NetworkSelectorModal/index.tsx
  apps/gamification/config/supportedChain.tsx
  apps/gamification/hooks/useSiwe.ts
  apps/gamification/views/DashboardQuestEdit/components/Tasks/AddMakePrediction.tsx
  apps/gamification/views/DashboardQuestEdit/components/Tasks/index.tsx
  apps/gamification/views/DashboardQuestEdit/context/types.ts
  apps/gamification/views/DashboardQuestEdit/hooks/useTaskInfo.tsx
  apps/gamification/views/DashboardQuestEdit/type.ts
  apps/gamification/views/DashboardQuestEdit/utils/generateNewTask.ts
  apps/gamification/views/DashboardQuestEdit/utils/verifyTask.ts
  apps/gamification/views/Quest/components/Tasks/Task.tsx
  apps/gamification/views/Quest/components/Tasks/index.tsx
Labels: size/L

#10724 fix: update limit logic for ifo basic sale
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#10729 feat: Add ga in start quest
  apps/gamification/utils/customGTMEventTracking.ts
  apps/gamification/views/Quest/components/Tasks/index.tsx
Labels: size/M

#10732 chore: set ifo learn more link to forum post
  packages/ifos/src/constants/ifos/arb.ts
  packages/localization/src/config/translations.json
  packages/uikit/src/widgets/Ifo/IfoHasVestingNotice.tsx
Labels: size/XS

#10731 chore: list egp syrup pool on arb
  packages/pools/src/constants/pools/42161.ts
Labels: size/XS

#10736 chore: list 6 new gauges
  packages/gauges/src/constants/config/prod.ts
Labels: size/M

#10735 chore: list egp farm on arb
  packages/farms/src/farms/arb.ts
Labels: size/XS

#10737 chore: list new farms & gauges on base
  packages/farms/src/farms/base.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/base.ts
Labels: size/M

#10705 chore: list new PM on arb
  packages/position-managers/src/constants/vaults/arb.ts
Labels: Delayed Release, size/M

#10745 feat: Add Chef
  .github/CODEOWNERS
Labels: size/XS

#10739 fix: SSR issue
  apps/blog/components/Article/AllArticle/index.tsx
  apps/blog/next-env.d.ts
Labels: size/S

#10746 chore: list uniBTC as a warning token
  apps/web/src/config/constants/swapWarningTokens.ts
  apps/web/src/config/constants/warningTokens/bscWarningTokens.ts
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/UniBTCWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/index.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#10742 chore: list new ALM PM on bsc
  packages/position-managers/src/constants/vaults/bsc.ts
Labels: size/S

#10747 chore: list new farm on bsc
  packages/farms/src/farms/bsc.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/S

#10749 chore: Remove warnings
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/hooks/useSwitchNetwork.ts
  apps/web/src/views/Home/components/Banners/hooks/useIsRenderIFOBanner.tsx
Labels: size/XS

#10748 fix: V2 farms not shown in legacy farms page
  packages/farms/src/getLegacyFarmConfig.ts
Labels: size/S

#10750 chore: list pepe syrup pool on bsc
  packages/pools/src/constants/pools/56.ts
Labels: size/XS

#10751 fix: Log better quote type
  apps/web/src/views/Swap/V3Swap/hooks/useAllTypeBestTrade.ts
  apps/web/src/views/Swap/V3Swap/index.tsx
Labels: size/XS

#10741 fix: V3 Apr Modal Max and Token amounts
  apps/web/src/views/universalFarms/components/PoolAprButton/V3PoolAprModal.tsx
Labels: size/S

#10759 fix: Legacy farm page not showing stable pairs
  packages/farms/src/getLegacyFarmConfig.ts
Labels: size/S

#10753 fix: update the tokenList cache in universal pages
  apps/web/src/config/constants/exchange.ts
  apps/web/src/state/lists/updater.ts
Labels: size/XS

#10755 fix: Check worker event data has iterator
  apps/gamification/utils/worker.ts
  apps/web/src/utils/worker.ts
Labels: size/M, Sentry

#10726 fix: Crash bcake migration page with unsupported chain
  apps/web/src/views/Migration/components/bCake/PositionManagerTable.tsx
Labels: size/M, Sentry

#10719 perf: Don't fetch cake price when currency is not and not enabled
  apps/web/src/hooks/useStablecoinPrice.ts
  apps/web/src/views/AffiliatesProgram/components/Dashboard/CommissionInfo.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/Reward/LatestReward.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useLeaderboard.tsx
  apps/web/src/views/CakeStaking/components/CakeRewardsCard.tsx
  apps/web/src/views/CakeStaking/components/LockCakeForm.tsx
  apps/web/src/views/Home/components/Banners/LotteryBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useIsRenderUserBanner.ts
  apps/web/src/views/Home/components/CakeDataRow.tsx
  apps/web/src/views/Home/components/CommunitySection/LotteryCardContent.tsx
  apps/web/src/views/Home/components/UserBanner/HarvestCard.tsx
  apps/web/src/views/Home/hooks/useGetTopFarmsByApr.tsx
  apps/web/src/views/Ifos/hooks/v2/useGetPublicIfoData.ts
  apps/web/src/views/Ifos/hooks/v3/useGetPublicIfoData.ts
  apps/web/src/views/Ifos/hooks/v7/useGetPublicIfoData.ts
  apps/web/src/views/Ifos/hooks/v8/useGetPublicIfoData.ts
  apps/web/src/views/Lottery/components/BuyTicketsModal/BuyTicketsModal.tsx
  apps/web/src/views/Lottery/components/ClaimPrizesModal/ClaimPrizesInner.tsx
  apps/web/src/views/Lottery/components/Hero.tsx
  apps/web/src/views/Lottery/components/NextDrawCard.tsx
  apps/web/src/views/Lottery/components/PreviousRoundCard/FooterExpanded.tsx
  apps/web/src/views/Lottery/components/RewardBracketDetail.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/RecentCakeProfitRow.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/VaultCardActions/HasSharesActions.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
  apps/web/src/views/Pools/components/RevenueSharing/BenefitsModal/RevenueSharing.tsx
  apps/web/src/views/Pottery/components/Banner/index.tsx
  apps/web/src/views/Pottery/components/FinishedRounds/AllHistoryCard/PreviousRoundCardBody.tsx
  apps/web/src/views/Pottery/components/Pot/Claim/AvailableWithdraw.tsx
  apps/web/src/views/Pottery/components/Pot/Claim/PrizeToBeClaimed.tsx
  apps/web/src/views/Pottery/components/Pot/YourDeposit.tsx
  apps/web/src/views/Pottery/components/Pot/index.tsx
  apps/web/src/views/TradingCompetition/helpers.ts
  apps/web/src/views/TradingReward/components/CurrentRewardPool.tsx
  apps/web/src/views/TradingReward/components/Leaderboard/DesktopResult.tsx
  apps/web/src/views/TradingReward/components/Leaderboard/MobileResult.tsx
  apps/web/src/views/TradingReward/components/Leaderboard/RankingCard.tsx
  apps/web/src/views/TradingReward/components/TopTraders/YourTradingReward/CurrentPeriod.tsx
  apps/web/src/views/TradingReward/components/YourTradingReward/QualifiedPreview.tsx
  apps/web/src/views/TradingReward/components/YourTradingReward/VeCake/VeCakePreview.tsx
  apps/web/src/views/TradingReward/hooks/useRewardInCake.tsx
Labels: size/L

#10760 chore: Bump pnpm
  .github/actions/install-deps/action.yml
  package.json
Labels: size/XS

#10754 fix: Add undefined check for trade order
  apps/web/src/views/Swap/V3Swap/hooks/useAllTypeBestTrade.ts
  apps/web/src/views/Swap/V3Swap/index.tsx
Labels: size/S, Sentry
