Repository pancakeswap/pancake-frontend, pull requests merged in 2024-11, with the labels that each got.

#10890 feat: Connect position manager api
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/List.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/TableRow.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/TableRow.tsx
  apps/web/src/views/GaugesVoting/hooks/useGaugesFilter.ts
  apps/web/src/views/GaugesVoting/hooks/usePositionManagerName.ts
  apps/web/src/views/GaugesVoting/utils.ts
  apps/web/src/views/Migration/components/bCake/PositionManagerTable.tsx
  apps/web/src/views/PositionManagers/hooks/usePositionManager.ts
  apps/web/src/views/PositionManagers/hooks/useVaultConfigs.ts
  packages/gauges/src/tests/config.test.ts
  packages/position-managers/src/config.test.ts
  packages/position-managers/src/constants/endpoints.ts
  packages/position-managers/src/constants/vaults/arb.ts
  packages/position-managers/src/constants/vaults/base.ts
  packages/position-managers/src/constants/vaults/bsc.ts
  packages/position-managers/src/constants/vaults/eth.ts
  packages/position-managers/src/constants/vaults/index.ts
  packages/position-managers/src/constants/vaults/linea.ts
  packages/position-managers/src/constants/vaults/zkevm.ts
  packages/position-managers/src/constants/vaults/zksync.ts
  packages/position-managers/src/index.ts
  packages/position-managers/src/utils/fetchPositionManager.ts
  packages/position-managers/src/utils/index.ts
Labels: size/XXL

#10904 fix: Warning not seen trx deadline setting, set value only when losing focus
  apps/web/src/components/Menu/GlobalSettings/TransactionSettings.tsx
Labels: size/M

#10906 feat: Add debounce and abort signal to position manager, make calls per chain instead of per gauge
  apps/web/src/views/GaugesVoting/hooks/useGaugesFilter.ts
  apps/web/src/views/GaugesVoting/hooks/usePositionManagerName.ts
  apps/web/src/views/GaugesVoting/utils.ts
  apps/web/src/views/PositionManagers/hooks/usePositionManager.ts
  packages/position-managers/src/utils/fetchPositionManager.ts
Labels: size/L

#10909 fix: Gauges list position manager name not visible
  apps/web/src/views/GaugesVoting/hooks/usePositionManagerName.ts
Labels: size/S

#10907 chore: Remove prod trigger for routing cron
  apis/routing/wrangler.toml
Labels: size/XS

#10915 chore: Remove routing crons
  apis/routing/wrangler.toml
Labels: size/XS

#10917 chore: Use next link for internal
  apps/web/src/views/Home/components/Banners/NewIFOBanner.tsx
  apps/web/src/views/ProfileCreation/Header.tsx
Labels: size/S

#10923 chore: Revert back to use explorer api
  apps/web/next.config.mjs
  apps/web/src/state/farmsV4/state/farmPools/fetcher.ts
Labels: size/L

#10903 fix: Back button not working after url changed by swap or query added
  apps/aptos/components/SearchModal/ManageTokens.tsx
  apps/aptos/pages/swap.tsx
  apps/web/src/views/LimitOrders/index.tsx
  apps/web/src/views/Swap/Twap/Twap.tsx
  apps/web/src/views/Swap/V3Swap/containers/FlipButton.tsx
  apps/web/src/views/Swap/V3Swap/containers/FormMain.tsx
  apps/web/src/views/SwapSimplify/V4Swap/FlipButton.tsx
  apps/web/src/views/SwapSimplify/V4Swap/FormMainV4.tsx
  packages/utils/replaceBrowserHistory.ts
  packages/utils/replaceBrowserHistoryMultiple.ts
Labels: size/L

#10927 chore: Publish v4 sdk
  .changeset/happy-pianos-kneel.md
  packages/v4-sdk/package.json
Labels: size/XS

#10920 fix: Correct typos in translation keys across locales
  apps/web/src/views/Nft/market/components/MarketPageTitle.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#10929 fix: mismatch gauge in cms and sc side
  apps/web/src/__tests__/gagues/gauges.test.ts
  apps/web/vitest.config.ts
  apps/web/vitest.setup.js
  packages/gauges/src/fetchAllGauges.ts
  packages/gauges/src/getAllGauges.ts
  packages/gauges/src/types.ts
Labels: size/L

#10899 perf: Use query instead of queries to reduce rerenders initially
  apps/web/src/hooks/v3/usePools.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountStableLpDetails.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountV2LpDetails.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountV3Positions.ts
  apps/web/src/state/farmsV4/state/farmPools/hooks.ts
Labels: size/XL

#10924 chore: Missing titles in swap and info v3 and calculate basepath only no exact
  apps/web/src/config/constants/meta.ts
Labels: size/M

#10934 fix: Liquidity positions not updated after add or remove
  apps/web/src/pages/liquidity/pools.tsx
  apps/web/src/state/farmsV3/hooks.ts
  apps/web/src/state/farmsV4/state/accountPositions/atom.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/index.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountPositionDetailByPool.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountStableLpDetails.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountV2LpDetails.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountV3Positions.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useLatestTxReceipt.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useUpdateLatestTxReceipt.ts
  apps/web/src/state/transactions/hooks.tsx
  apps/web/src/views/universalFarms/components/PositionActions/V3PositionActions.tsx
  apps/web/src/views/universalFarms/components/PositionItem/PositionInfo.tsx
Labels: size/L

#10925 fix: Items unique key warning in dropdown menu to avoid rerenders
  packages/uikit/src/components/DropdownMenu/DropdownMenu.tsx
Labels: size/M

#10935 fix: Update keep previous data param in info query hooks
  apps/web/src/state/info/hooks.ts
  apps/web/src/views/V3Info/hooks/index.ts
Labels: size/S

#10937 feat: Added fee section to the confirmartion modal
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/L

#10938 fix: Currency error on limit when one currency undefined
  apps/web/src/state/swap/useSwapActionHandlers.ts
  apps/web/src/views/Swap/Twap/Twap.tsx
Labels: size/XS, Sentry

#10931 feat: amm trade add shadow request 1%
  apps/web/src/config/experimentalFeatures.ts
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSwapBestTrade.ts
Labels: size/L

#10941 fix: missed killed filter from cms
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/TableRow.tsx
  packages/gauges/src/getAllGauges.ts
Labels: size/XS

#10943 fix: 🐛 Fix infinit refresh bugs
  apps/web/src/views/GaugesVoting/hooks/useUserVoteGauges.ts
Labels: size/XS

#10932 fix: Increase decimals on vecake card
  apps/web/src/views/CakeStaking/components/CakeRewardsCard.tsx
  apps/web/src/views/CakeStaking/hooks/useRevenueSharingProxy.ts
  apps/web/src/views/Pools/components/RevenueSharing/BenefitsModal/RevenueSharing.tsx
  apps/web/src/views/Pools/hooks/useRevenueSharingPool.ts
Labels: size/M

#10936 chore: Return to positions page from v2,stable details and import pages
  apps/web/src/pages/stable/[address].tsx
  apps/web/src/pages/v2/pair/[[...currency]].tsx
  apps/web/src/views/PoolFinder/index.tsx
Labels: size/XS

#10948 fix: undefined gauge hash
  apps/web/src/views/GaugesVoting/hooks/useUserVoteGauges.ts
Labels: size/S

#10950 fix: filter gauges for all scope
  apps/web/src/views/GaugesVoting/hooks/useGauges.ts
  apps/web/src/views/GaugesVoting/hooks/useUserVoteGauges.ts
Labels: size/M

#10952 fix: wrong filter
  apps/web/src/views/GaugesVoting/hooks/useGauges.ts
Labels: size/XS

#10946 chore: Add connect wallet to positions page
  apps/web/src/views/universalFarms/PositionPage.tsx
Labels: size/XS

#10963 feat: Feat/ton expansioon contracts interface
  apps/ton/.eslintrc
  apps/ton/.gitignore
  apps/ton/next-env.d.ts
  apps/ton/next.config.mjs
  apps/ton/package.json
  apps/ton/public/ton-manifest.json
  apps/ton/src/app/favicon.ico
  apps/ton/src/app/fonts/GeistMonoVF.woff
  apps/ton/src/app/fonts/GeistVF.woff
  apps/ton/src/app/globals.css
  apps/ton/src/app/layout.tsx
  apps/ton/src/app/page.module.css
  apps/ton/src/app/page.tsx
  apps/ton/src/atoms/addressAtom.ts
  apps/ton/src/atoms/ton.types.ts
  apps/ton/src/components/Header.tsx
  apps/ton/src/components/connector/TonConnector.tsx
  apps/ton/src/pages/_app.tsx
  apps/ton/src/pages/index.tsx
  apps/ton/src/pages/test/index.tsx
  apps/ton/src/styles/globals.css
  apps/ton/tsconfig.json
  apps/web/package.json
  apps/web/src/components/AddressInputSelect/index.tsx
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: size/XL

#10911 feat: Connect SS API
  .changeset/metal-forks-draw.md
  apis/routing/package.json
  apps/web/src/pages/api/configs/farms/v2/[chain].ts
  apps/web/src/pages/api/configs/farms/v2/index.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/index.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountPositionDetailByPool.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountStableLpDetails.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useStableSwapPairsByChainId.ts
  apps/web/src/state/farmsV4/state/farmPools/fetcher.ts
  apps/web/src/state/farmsV4/state/farmPools/hooks.ts
  apps/web/src/state/farmsV4/state/utils.ts
  apps/web/src/state/swap/useStableSwapPairs.ts
  apps/web/src/views/PoolDetail/components/PoolStatus.tsx
  apps/web/src/views/universalFarms/PoolsPage.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/V2PoolAprModal.tsx
  apps/web/src/views/universalFarms/components/PoolListItemAction.tsx
  packages/aptos-swap-sdk/src/index.test.ts
  packages/farms/src/getLegacyFarmConfig.ts
  packages/farms/src/utils.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/getStableCandidatePools.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/onChainPoolProviders.ts
  packages/smart-router/evm/v4-router/queries/getV4BinPools.ts
  packages/smart-router/evm/v4-router/queries/getV4ClPools.ts
  packages/smart-router/legacy-router/getBestTrade.ts
  packages/smart-router/legacy-router/getBestTradeFromStablePools.ts
  packages/smart-router/legacy-router/getStableSwapPairs.ts
  packages/smart-router/legacy-router/legacyRouter.ts
  packages/stable-swap-sdk/package.json
  packages/stable-swap-sdk/src/config/endpoint.ts
  packages/stable-swap-sdk/src/constants/pools/arb.ts
  packages/stable-swap-sdk/src/constants/pools/bsc.ts
  packages/stable-swap-sdk/src/constants/pools/bscTestnet.ts
  packages/stable-swap-sdk/src/constants/pools/eth.ts
  packages/stable-swap-sdk/src/constants/pools/index.ts
  packages/stable-swap-sdk/src/constants/pools/pools.test.ts
  packages/stable-swap-sdk/src/constants/pools/pools.ts
  packages/stable-swap-sdk/src/index.test.ts
  packages/swap-sdk/src/index.test.ts
  pnpm-lock.yaml
Labels: size/XXL

#10971 chore: affiliate-sunset-modal
  apps/web/src/components/Modal/AffiliateSunsetModal.tsx
  apps/web/src/hooks/useAffiliateSunsetList.tsx
  apps/web/src/pages/_app.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#10955 feat: Bump up zap liquidity widget
  apps/web/package.json
  apps/web/src/components/ConnectWalletButton.tsx
  apps/web/src/components/WalletModalManager.tsx
  apps/web/src/components/ZapLiquidityWidget.tsx
  apps/web/src/views/AddLiquidityV3/IncreaseLiquidityV3.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
  apps/web/src/views/AddLiquidityV3/index.tsx
  packages/localization/src/config/translations.json
  pnpm-lock.yaml
Labels: size/XXL

#10974 chore: Disallow fake token
  apps/web/src/config/constants/tokenLists/pancake-unsupported.tokenlist.json
Labels: size/XS

#10951 fix: 🐛 Fix search text not emptied on close
  apps/web/src/views/GaugesVoting/components/Table/AddGauge/AddGaugeModal.tsx
Labels: size/S

#10959 fix: Partial key frame error on ad card
  apps/web/src/components/AdPanel/Card.tsx
Labels: size/M, Sentry

#10949 fix: Swap Infinite loading and error message not shown when user routing setting customized
  apps/web/src/components/AccessRisk/SwapRevampRiskDisplay.tsx
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/views/Swap/V3Swap/hooks/useAllTypeBestTrade.ts
  apps/web/src/views/SwapSimplify/V4Swap/SwapCommitButton.tsx
  apps/web/src/views/SwapSimplify/V4Swap/index.tsx
  packages/smart-router/evm/v3-router/providers/quoteProviders.ts
Labels: size/M

#10900 chore: Remove warnings
  apps/web/src/hooks/usePCSX.ts
  apps/web/src/hooks/useSwitchNetwork.ts
  apps/web/src/views/Home/components/Banners/PCSXBanner.tsx
  apps/web/src/views/Voting/Proposal/Vote.tsx
Labels: size/XS

#10958 fix: User rejected error not shown properly in wallets
  apps/gamification/utils/sentry.ts
  apps/web/sentry.client.config.js
  apps/web/src/utils/sentry.ts
Labels: size/M

#10916 chore: Use isAddressEqual for comparison
  apps/web/src/components/AccessRisk/index.tsx
  apps/web/src/components/Paymaster/GasTokenSelector.tsx
  apps/web/src/hooks/useMerkl.tsx
  apps/web/src/pages/add/[[...currency]].tsx
  apps/web/src/pages/stable/[address].tsx
  apps/web/src/state/swap/hooks.ts
  apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
  apps/web/src/views/FixedStaking/index.tsx
  apps/web/src/views/GaugesVoting/components/TripleLogo.tsx
  apps/web/src/views/Migration/components/v3/Step1.tsx
  apps/web/src/views/Swap/V3Swap/components/SwapModalFooter.tsx
  apps/web/src/views/Swap/V3Swap/components/SwapModalFooterV2.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useSwapInputError.ts
  apps/web/src/views/Swap/hooks/useEstimatedAmount.ts
Labels: size/M

#10975 feat: Stableswap add cache
  .changeset/famous-gifts-shop.md
  packages/stable-swap-sdk/src/constants/pools/index.ts
Labels: size/M

#10979 fix: Farm symbol
  packages/tokens/src/constants/base.ts
Labels: size/XS

#10982 chore: Remove turkey banner
  apps/web/src/components/AdPanel/Card.tsx
  apps/web/src/components/AdPanel/FAQ/config/buyCrypto.tsx
  apps/web/src/components/AdPanel/FAQ/config/prediction.ts
  apps/web/src/components/AdPanel/FAQ/config/swap.tsx
  apps/web/src/components/AdPanel/FAQ/types.ts
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/S

#10962 feat: mev landing
  apps/web/src/components/AdPanel/Ads/AdMevProtection.tsx
  apps/web/src/components/AdPanel/config.tsx
  apps/web/src/pages/mev/index.tsx
  apps/web/src/views/Mev/AddMevRpcButton.tsx
  apps/web/src/views/Mev/Hero.tsx
  apps/web/src/views/Mev/InfoSection.tsx
  apps/web/src/views/Mev/MevIntroSection.tsx
  apps/web/src/views/Mev/MevSwapDetail.tsx
  apps/web/src/views/Mev/MevToggle.tsx
  apps/web/src/views/Mev/hooks/index.ts
  apps/web/src/views/Mev/index.tsx
  apps/web/src/views/Mev/types.ts
  apps/web/src/views/Mev/utils.ts
  apps/web/src/views/SwapSimplify/V4Swap/ButtonAndDetailsPanel.tsx
  apps/web/src/views/SwapSimplify/V4Swap/TradeDetails.tsx
  apps/web/src/views/SwapSimplify/V4Swap/index.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/components/Svg/Icons/ShieldIcon.tsx
  packages/uikit/src/components/Svg/index.tsx
Labels: size/XXL

#10984 chore: update mev doc link
  apps/web/src/views/Mev/InfoSection.tsx
Labels: size/XS

#10986 chore: update mev trust wallet link
  apps/web/src/views/Mev/InfoSection.tsx
Labels: size/XS

#10985 chore: Bump up liquidity widget add masterchef address
  apps/web/package.json
  apps/web/src/components/ZapLiquidityWidget.tsx
  apps/web/src/hooks/v3/useV3Positions.ts
  apps/web/src/views/AddLiquidityV3/IncreaseLiquidityV3.tsx
  apps/web/src/views/AddLiquidityV3/index.tsx
  pnpm-lock.yaml
Labels: size/L

#10992 feat: Remove nav new tag
  apps/web/src/components/Menu/config/config.ts
Labels: size/XS
