Repository pancakeswap/pancake-frontend, pull requests merged in 2024-07, with the labels that each got.

#10113 feat: new default token logo
  .changeset/small-falcons-sell.md
  apps/aptos/components/Logo/CurrencyLogo.tsx
  apps/web/src/views/Info/components/CurrencyLogo/index.tsx
  packages/uikit/src/components/Svg/Icons/DefaultToken.tsx
  packages/uikit/src/components/Svg/index.tsx
  packages/uikit/src/components/TokenLogo/TokenLogo.tsx
Labels: size/M

#10118 feat: add ETHBrussels event in v4 news
  apps/web/src/views/LandingV4/components/NewsAndEvents/Featured.tsx
  apps/web/src/views/LandingV4/config/blog/staticThirdPartyNews.ts
  apps/web/src/views/LandingV4/hooks/useAllArticle.ts
Labels: size/M

#10119 feat: Update wording
  apps/web/src/views/TradingReward/components/TopTraders/CurrentRewardPool.tsx
  apps/web/src/views/TradingReward/components/TopTraders/YourTradingReward/CurrentPeriod.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#9909 fix: Old farms shown when staked only selected if balance staked directly
  apps/web/src/state/user/hooks/index.tsx
  apps/web/src/views/Farms/Farms.tsx
  apps/web/src/views/Farms/FarmsV3.tsx
  apps/web/src/views/Farms/utils/getStakedFarms.ts
  apps/web/src/views/Migration/bCake.tsx
  apps/web/src/views/Migration/components/bCake/MigrationFarmStep.tsx
  apps/web/src/views/Migration/components/bCake/Step1.tsx
  apps/web/src/views/Migration/components/v3/OldFarmRow.tsx
Labels: size/L

#10121 feat: Add ohlc data to candlestick chart
  packages/uikit/src/components/Chart/PairPriceChart.tsx
Labels: size/M

#10124 fix: Buy crypto shows old fee details while loading
  apps/web/src/views/BuyCrypto/components/TransactionFeeDetails/TransactionFeeDetails.tsx
  apps/web/src/views/BuyCrypto/containers/BuyCryptoForm.tsx
Labels: size/S

#10104 feat: new uikit of MultiSelect (#10103)
  .changeset/flat-seahorses-visit.md
  packages/uikit/package.json
  packages/uikit/src/__tests__/components/checkbox.test.tsx
  packages/uikit/src/components/Checkbox/Checkbox.tsx
  packages/uikit/src/components/Checkbox/types.ts
  packages/uikit/src/components/MultiSelect/MultiSelect.tsx
  packages/uikit/src/components/MultiSelect/SearchBox.tsx
  packages/uikit/src/components/MultiSelect/index.stories.tsx
  packages/uikit/src/components/MultiSelect/index.tsx
  packages/uikit/src/components/MultiSelect/types.tsx
  packages/uikit/src/components/Select/index.stories.tsx
  packages/uikit/src/components/index.ts
  packages/widgets-internal/farm/FarmWidget.tsx
  packages/widgets-internal/farm/components/NetworkFilter/NetworkFilter.tsx
  packages/widgets-internal/farm/components/NetworkFilter/index.tsx
  packages/widgets-internal/farm/components/TokenFilter/TokenFilter.tsx
  packages/widgets-internal/farm/components/TokenFilter/index.tsx
  pnpm-lock.yaml
Labels: size/XL

#10130 chore: list new solvbtc.ena/solvbtc farms & gauges
  packages/farms/constants/arb.ts
  packages/farms/constants/bsc.ts
  packages/farms/constants/common/index.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/M

#10131 chore: list zro gauges
  packages/gauges/src/constants/config/prod.ts
Labels: size/M

#10140 chore: Add iso to unsupported list
  apps/web/src/config/constants/tokenLists/pancake-unsupported.tokenlist.json
Labels: size/XS

#10129 fix: Unstake farms with vault
  apps/web/src/state/user/hooks/index.tsx
  apps/web/src/views/Farms/hooks/getNonBscVaultFee.ts
  apps/web/src/views/Farms/hooks/useStakeFarms.ts
  apps/web/src/views/Farms/hooks/useUnstakeFarms.ts
Labels: size/M

#10141 chore: Update pnpm action version
  .github/workflows/deploy-apis.yml
  .github/workflows/farmConfig.yml
  .github/workflows/format.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/testConfig.yml
  .github/workflows/unitTests.yml
  .github/workflows/updateCron.yml
  apps/web/src/config/constants/tokenLists/pancake-unsupported.tokenlist.json
Labels: size/S

#10142 fix: Toggle user farm staked
  apps/web/src/state/user/hooks/index.tsx
Labels: size/XS

#10143 fix: Toggle user farm
  apps/web/src/state/user/hooks/index.tsx
Labels: size/S

#10136 feat: treeSelect uikit and PoolsTypeFilter widget
  .changeset/tasty-meals-repair.md
  packages/uikit/src/components/MultiSelect/EmptyMessage.tsx
  packages/uikit/src/components/MultiSelect/MultiSelect.tsx
  packages/uikit/src/components/MultiSelect/SearchBox.tsx
  packages/uikit/src/components/MultiSelect/assets/empty-message.svg
  packages/uikit/src/components/MultiSelect/index.stories.tsx
  packages/uikit/src/components/TreeSelect/TreeSelect.tsx
  packages/uikit/src/components/TreeSelect/index.stories.tsx
  packages/uikit/src/components/TreeSelect/index.tsx
  packages/uikit/src/components/index.ts
  packages/widgets-internal/farm/FarmWidget.tsx
  packages/widgets-internal/farm/components/PoolsTypeFilter/PoolsTypeFilter.tsx
  packages/widgets-internal/farm/components/PoolsTypeFilter/index.tsx
  packages/widgets-internal/farm/components/TokenFilter/TokenFilter.tsx
Labels: size/XL

#10128 chore: zksync Airdrop banner and modal
  apps/web/src/components/ClaimZksyncAirdropModal/hooks.tsx
  apps/web/src/components/ClaimZksyncAirdropModal/index.tsx
  apps/web/src/config/abi/zksyncAirdrop.ts
  apps/web/src/config/constants/contracts.ts
  apps/web/src/config/paymaster.ts
  apps/web/src/hooks/useContract.ts
  apps/web/src/hooks/useGasSponsorshipBalance.ts
  apps/web/src/pages/api/paymaster/index.ts
  apps/web/src/utils/addressHelpers.ts
  apps/web/src/utils/contractHelpers.ts
  apps/web/src/utils/paymaster.ts
  apps/web/src/views/Home/components/Banners/ZksyncAirdrpoBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
  packages/widgets-internal/components/Banner/BannerGraphics.tsx
Labels: size/XL

#10144 chore: list sqd-eth farm arbitrum
  .changeset/lucky-peaches-sleep.md
  packages/farms/constants/arb.ts
  packages/tokens/src/constants/arb.ts
Labels: size/S

#10120 feat: Merkl apr integration
  apps/web/src/state/farms/types.ts
  apps/web/src/views/Farms/FarmsV3.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/CardActionsContainer.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmInfo.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3ApyButton.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3Card.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3CardList.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3StakeAndUnStake.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/SingleFarmV3Card.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/Farms/components/FarmTable/Row.tsx
  apps/web/src/views/Farms/components/getDisplayApr.ts
  packages/localization/src/config/translations.json
  packages/widgets-internal/farm/components/MerklNotice/index.tsx
  packages/widgets-internal/roi/RoiCalculator.tsx
Labels: size/L

#10150 fix: Token project links
  packages/tokens/src/constants/arb.ts
  packages/tokens/src/constants/bscTestnet.ts
  packages/tokens/src/constants/common.ts
  packages/tokens/src/constants/zkSync.ts
Labels: size/M

#10137 feat: add token's icon & empty message & placeholder
  .changeset/nasty-tomatoes-juggle.md
  packages/uikit/src/components/MultiSelect/MultiSelect.tsx
  packages/uikit/src/components/MultiSelect/index.stories.tsx
  packages/uikit/src/components/MultiSelect/types.tsx
  packages/uikit/src/components/Svg/Icons/Empty.tsx
  packages/uikit/src/components/Svg/index.tsx
Labels: size/L

#10153 perf: Dont fetch zksync airdrop everytime and fix multiaccount fetch
  apps/web/src/components/ClaimZksyncAirdropModal/hooks.tsx
  apps/web/src/components/ClaimZksyncAirdropModal/index.tsx
  apps/web/src/views/Home/components/Banners/MoonPayBanner.tsx
  apps/web/src/views/Home/components/Banners/ZksyncAirdropBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/L

#10155 chore: list new arb PM vault
  packages/position-managers/src/constants/vaults/arb.ts
  packages/tokens/src/constants/arb.ts
Labels: size/S

#10160 chore: Unify wagmi viem versions
  apis/farms/package.json
  apis/routing/package.json
  apps/bridge/package.json
  apps/gamification/package.json
  apps/web/package.json
  apps/web/sentry.client.config.js
  apps/web/src/components/ErrorBoundary/SentryErrorBoundary.tsx
  apps/web/src/utils/clearUserStates.ts
  package.json
  packages/chains/tsup.config.bundled_h7syd7szdge.mjs
  packages/farms/package.json
  packages/gauges/package.json
  packages/ifos/package.json
  packages/multicall/package.json
  packages/pcsx-sdk/package.json
  packages/permit2-sdk/package.json
  packages/pools/package.json
  packages/position-managers/package.json
  packages/prediction/package.json
  packages/smart-router/package.json
  packages/swap-sdk-evm/package.json
  packages/swap-sdk/package.json
  packages/uikit/package.json
  packages/universal-router-sdk/package.json
  packages/utils/package.json
  packages/v2-sdk/package.json
  packages/v3-sdk/package.json
  packages/v4-sdk/package.json
  packages/wagmi/package.json
  packages/widgets-internal/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  scripts/package.json
Labels: size/XXL

#10162 chore: Turbo v2
  package.json
  pnpm-lock.yaml
  turbo.json
Labels: size/L

#10163 chore: list new gauges
  packages/gauges/src/constants/config/prod.ts
Labels: size/S

#10171 feat: List missing pair
  apps/web/src/views/TradingReward/config/pairs/edgeCasesFarms/bscFarm.ts
  apps/web/src/views/TradingReward/config/pairs/edgeCasesFarms/lineaFarm.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/M

#10169 feat: intergrate token+network+farmType into PoolsFilterPanel
  apps/web/src/hooks/Tokens.ts
  apps/web/src/pages/farms/index.tsx
  apps/web/src/state/user/hooks/useUserAddedTokens.ts
  apps/web/src/views/Farms/FarmsV4.tsx
  apps/web/src/views/Farms/v4/components/Pools.tsx
  apps/web/src/views/Farms/v4/components/PoolsFilterPanel.tsx
  apps/web/src/views/Farms/v4/components/Table.tsx
  apps/web/src/views/Farms/v4/components/index.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/components/Checkbox/Checkbox.tsx
  packages/uikit/src/components/Checkbox/types.ts
  packages/uikit/src/components/MultiSelect/MultiSelect.tsx
  packages/uikit/src/components/MultiSelect/SearchBox.tsx
  packages/uikit/src/components/MultiSelect/index.stories.tsx
  packages/uikit/src/components/MultiSelect/types.tsx
  packages/uikit/src/components/TreeSelect/TreeSelect.tsx
  packages/widgets-internal/farm/components/NetworkFilter/NetworkFilter.tsx
  packages/widgets-internal/farm/components/PoolsTypeFilter/PoolsTypeFilter.tsx
  packages/widgets-internal/farm/components/TokenFilter/TokenFilter.tsx
Labels: size/XL

#10164 chore: list new pool on Arb
  packages/pools/src/constants/pools/42161.ts
Labels: size/XS

#10173 chore: list new gauges on Arb
  packages/gauges/src/constants/config/prod.ts
Labels: size/S

#10175 fix: Stable farm aprs not shown properly
  apps/web/src/state/farms/index.ts
  packages/farms/src/v2/fetchFarmsV2.ts
Labels: size/M

#10148 chore: Clean up components patch 1
  apps/web/src/components/CrossChainVeCakeModal/index.tsx
  apps/web/src/components/Merkl/MerklSection.tsx
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/state/info/constant.ts
  apps/web/src/views/Farms/components/FarmTable/Row.tsx
  apps/web/src/views/Home/components/FarmsPoolsRow/RowHeading.tsx
  apps/web/src/views/Home/components/FarmsPoolsRow/TopFarmPool.tsx
  apps/web/src/views/Home/components/FarmsPoolsRow/index.tsx
  apps/web/src/views/Home/hooks/useGetTopFarmsByApr.tsx
  apps/web/src/views/Ifos/components/Hero.tsx
  apps/web/src/views/PositionManagers/components/LiquidityManagement.tsx
  apps/web/src/views/PositionManagers/components/RewardAssets.tsx
  apps/web/src/views/PositionManagers/components/TableView/ActionPanel.tsx
  apps/web/src/views/PositionManagers/components/TableView/FarmCell.tsx
  apps/web/src/views/PositionManagers/components/TableView/LiquidityManagement.tsx
  apps/web/src/views/PositionManagers/components/TableView/index.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/Acknowledgement.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/index.tsx
  apps/web/src/views/Swap/index.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/components/Acknowledgement/index.tsx
Labels: size/L

#10181 feat: new universal farms config
  .vscode/settings.json
  packages/farms/src/config.test.ts
  packages/farms/src/config.ts
Labels: size/XXL

#10174 feat: add TableView uikit & UniversalFarms table list
  apps/web/src/pages/farms/index.tsx
  apps/web/src/views/Farms/UniversalFarms.tsx
  apps/web/src/views/Farms/v4/components/Pools.tsx
  apps/web/src/views/Farms/v4/components/PoolsBanner.tsx
  apps/web/src/views/Farms/v4/components/PoolsFilterPanel.tsx
  apps/web/src/views/Farms/v4/components/Table.tsx
  apps/web/src/views/Farms/v4/components/index.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/components/MultiSelect/MultiSelect.tsx
  packages/uikit/src/components/MultiSelect/SearchBox.tsx
  packages/uikit/src/components/TableView/Table.tsx
  packages/uikit/src/components/TableView/index.stories.tsx
  packages/uikit/src/components/TableView/index.tsx
  packages/uikit/src/components/TreeSelect/TreeSelect.tsx
  packages/uikit/src/components/index.ts
  packages/widgets-internal/farm/components/TokenFilter/TokenFilter.tsx
Labels: size/L

#10183 fix: optimize uikit of multiSelect
  packages/uikit/src/components/Checkbox/Checkbox.tsx
  packages/uikit/src/components/Checkbox/types.ts
  packages/uikit/src/components/MultiSelect/MultiSelect.tsx
  packages/uikit/src/components/MultiSelect/SearchBox.tsx
  packages/uikit/src/components/MultiSelect/index.stories.tsx
  packages/uikit/src/components/MultiSelect/types.tsx
  packages/uikit/src/components/TreeSelect/TreeSelect.tsx
  packages/widgets-internal/farm/components/NetworkFilter/NetworkFilter.tsx
  packages/widgets-internal/farm/components/PoolsTypeFilter/PoolsTypeFilter.tsx
  packages/widgets-internal/farm/components/TokenFilter/TokenFilter.tsx
Labels: size/XL

#10191 chore: Remove deprecated usetoken wagmi hook
  apps/web/src/hooks/Tokens.ts
Labels: size/M

#10185 feat: initial universal farm list
  apps/web/src/views/Farms/UniversalFarms.tsx
  apps/web/src/views/Farms/v4/components/PoolsFilterPanel.tsx
  apps/web/src/views/Farms/v4/components/PoolsPage.tsx
  apps/web/src/views/Farms/v4/components/index.tsx
  packages/uikit/src/components/MultiSelect/index.stories.tsx
  packages/uikit/src/components/TreeSelect/index.stories.tsx
  packages/widgets-internal/components/NetworkFilter/NetworkFilter.tsx
  packages/widgets-internal/components/NetworkFilter/index.tsx
  packages/widgets-internal/components/PoolTagFilter/PoolTagFilter.tsx
  packages/widgets-internal/components/PoolTagFilter/index.tsx
  packages/widgets-internal/components/PoolTypeMenu/PoolTypeMenu.tsx
  packages/widgets-internal/components/PoolTypeMenu/index.tsx
  packages/widgets-internal/components/TokenFilter/TokenFilter.tsx
  packages/widgets-internal/components/TokenFilter/index.tsx
  packages/widgets-internal/components/TokenOverview/TokenOverview.tsx
  packages/widgets-internal/components/TokenOverview/index.tsx
  packages/widgets-internal/farm/FarmWidget.tsx
  packages/widgets-internal/farm/components/PoolsTypeFilter/index.tsx
  packages/widgets-internal/index.ts
Labels: size/L

#10187 chore: Clean up patch 2
  apps/aptos/components/Liquidity/components/CurrencySelect.tsx
  apps/web/src/components/CurrencySelect/index.tsx
  apps/web/src/components/SearchModal/CurrencySearch.tsx
  apps/web/src/components/SearchModal/sorting.ts
  apps/web/src/hooks/useTokenComparator.ts
  packages/uikit/src/components/MultiSelector/MultiSelector.tsx
  packages/uikit/src/components/Select/Select.tsx
  packages/uikit/src/components/StyledComponents/index.tsx
  packages/uikit/src/components/index.ts
Labels: size/L

#10196 fix: Invalid variable assignment in maxLiquidityForAmounts
  .changeset/weak-flowers-decide.md
  packages/v3-sdk/src/utils/maxLiquidityForAmounts.ts
Labels: size/S

#10198 chore: Add four meme banner
  apps/web/src/views/Home/components/Banners/FourMemeBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
  packages/widgets-internal/components/Banner/BannerTitle.tsx
Labels: size/M

#10200 chore: Add aitech pool
  .changeset/light-waves-move.md
  packages/pools/src/constants/pools/56.ts
Labels: size/S

#10182 refactor: farms api
  apps/web/src/pages/api/configs/farms/[chain].ts
  apps/web/src/pages/api/configs/farms/index.ts
  packages/farms/index.test.ts
  packages/farms/src/config.test.ts
  packages/farms/src/config.ts
  packages/farms/src/index.ts
Labels: size/L

#10207 feat: fetch farming list data
  apps/web/src/views/Farms/v4/components/PoolsFilterPanel.tsx
  apps/web/src/views/Farms/v4/components/PoolsPage.tsx
  packages/farms/src/config.test.ts
  packages/farms/src/config.ts
  packages/farms/src/index.ts
  packages/uikit/src/components/MultiSelect/types.tsx
  packages/uikit/src/components/TableView/Table.tsx
  packages/widgets-internal/components/NetworkFilter/NetworkFilter.tsx
  packages/widgets-internal/components/PoolTypeMenu/PoolTypeMenu.tsx
Labels: size/L

#10209 fix: Farm auction page not working
  apps/web/src/utils/addressHelpers.ts
  apps/web/src/utils/contractHelpers.ts
  apps/web/src/views/FarmAuction/hooks/useCurrentFarmAuction.ts
  apps/web/src/views/FarmAuction/hooks/useFarmAuction.ts
Labels: size/M

#10208 chore: new ALM PM vault on zksync
  packages/position-managers/src/constants/vaults/zksync.ts
Labels: size/M

#10212 chore: add aptos banner
  apps/aptos/components/Banner/AptosYieldFarmingBanner.tsx
  apps/aptos/components/Farms/components/Farms.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#10213 chore: remove duplicated code patch 3
  apps/web/src/views/V3Info/data/token/poolsForToken.ts
  apps/web/src/views/V3Info/hooks/index.ts
  apps/web/src/views/V3Info/types.ts
  apps/web/src/views/V3Info/utils/index.ts
Labels: size/M

#10216 fix: Missing translations
  packages/localization/src/config/translations.json
Labels: size/XS

#10204 feat: list new gauges and farms for base and bsc
  packages/farms/constants/base.ts
  packages/farms/constants/bsc.ts
  packages/farms/constants/common/index.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/base.ts
  packages/tokens/src/constants/bsc.ts
  packages/tokens/src/constants/common.ts
Labels: size/L

#10217 feat: farms pools data
  apps/web/src/state/farmsV4/hooks.ts
  apps/web/src/state/farmsV4/state/extendPoolsAtom.ts
  apps/web/src/state/farmsV4/state/farmPoolsAtom.ts
  apps/web/src/state/farmsV4/state/poolAprAtom.ts
  apps/web/src/state/farmsV4/state/type.ts
  apps/web/src/state/farmsV4/state/userPositionsAtom.ts
  apps/web/src/state/farmsV4/state/utils.ts
  apps/web/src/state/info/api/schema.d.ts
  apps/web/src/views/Farms/UniversalFarms.tsx
  apps/web/src/views/Farms/v4/components/PoolsPage.tsx
  packages/farms/index.test.ts
  packages/farms/src/config.ts
  packages/farms/src/const.ts
  packages/farms/src/index.ts
Labels: size/XXL

#10219 fix: Merkl doc link
  apps/web/src/components/Merkl/MerklSection.tsx
Labels: size/S

#10218 chore: list-new-arbitrum-gauges
  packages/farms/constants/arb.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/arb.ts
Labels: size/L

#10220 fix: Merkl details link
  apps/web/src/components/Merkl/MerklSection.tsx
Labels: size/S

#10226 feat: Add v2/v3/ss apr calc, apr state, and extend pool query
  apps/web/src/config/index.ts
  apps/web/src/state/farmsV4/atom.ts
  apps/web/src/state/farmsV4/hooks.ts
  apps/web/src/state/farmsV4/state/extendPools/atom.ts
  apps/web/src/state/farmsV4/state/extendPools/fetcher.ts
  apps/web/src/state/farmsV4/state/extendPools/hooks.ts
  apps/web/src/state/farmsV4/state/extendPoolsAtom.ts
  apps/web/src/state/farmsV4/state/farmPools/atom.ts
  apps/web/src/state/farmsV4/state/farmPools/fetcher.ts
  apps/web/src/state/farmsV4/state/farmPools/hooks.ts
  apps/web/src/state/farmsV4/state/poolApr/atom.ts
  apps/web/src/state/farmsV4/state/poolApr/fetcher.ts
  apps/web/src/state/farmsV4/state/poolApr/hooks.ts
  apps/web/src/state/farmsV4/state/poolAprAtom.ts
  apps/web/src/state/farmsV4/state/type.ts
  apps/web/src/state/farmsV4/state/userPositionsAtom.ts
Labels: size/XL

#10223 chore(patch-4): consolidate transformPoolData
  apps/web/src/views/V3Info/data/protocol/transactions.ts
  apps/web/src/views/V3Info/data/token/transactions.ts
  apps/web/src/views/V3Info/types.ts
  apps/web/src/views/V3Info/utils/index.ts
Labels: size/L

#10024 feat: add topper and paymonade
  apps/web/src/state/buyCrypto/hooks.ts
  apps/web/src/views/BuyCrypto/components/ProviderCampaign/ProviderCampaign.tsx
  apps/web/src/views/BuyCrypto/components/ProviderSelector/ProviderSelector.tsx
  apps/web/src/views/BuyCrypto/components/TransactionFeeDetails/TransactionFeeDetails.tsx
  apps/web/src/views/BuyCrypto/constants.ts
  apps/web/src/views/BuyCrypto/containers/BuyCryptoForm.tsx
  apps/web/src/views/BuyCrypto/hooks/useOnRampLimits.ts
  apps/web/src/views/BuyCrypto/hooks/useOnRampQuotes.ts
  apps/web/src/views/BuyCrypto/hooks/useProviderAvailabilities.ts
  apps/web/src/views/BuyCrypto/index.tsx
  apps/web/src/views/BuyCrypto/styles.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#10229 feat: merkl apr
  apps/web/src/state/farmsV4/state/poolApr/atom.ts
  apps/web/src/state/farmsV4/state/poolApr/fetcher.ts
  apps/web/src/state/farmsV4/state/poolApr/hooks.ts
  packages/farms/src/const.ts
Labels: size/L

#10210 feat: integrate filter to farm list
  apps/web/src/components/TokenImage/index.tsx
  apps/web/src/state/farmsV4/state/extendPools/atom.ts
  apps/web/src/state/farmsV4/state/extendPools/hooks.ts
  apps/web/src/state/farmsV4/state/farmPools/fetcher.ts
  apps/web/src/state/farmsV4/state/farmPools/hooks.ts
  apps/web/src/state/farmsV4/state/type.ts
  apps/web/src/state/farmsV4/state/utils.ts
  apps/web/src/views/Farms/v4/components/PoolsFilterPanel.tsx
  apps/web/src/views/Farms/v4/components/PoolsPage.tsx
  packages/farms/index.test.ts
  packages/farms/src/config.ts
  packages/hooks/src/useIntersectionObserver.ts
  packages/uikit/src/components/MultiSelect/MultiSelect.tsx
  packages/uikit/src/components/MultiSelect/SearchBox.tsx
  packages/uikit/src/components/MultiSelect/types.tsx
  packages/uikit/src/components/Svg/Icons/SortArrow.tsx
  packages/uikit/src/components/Svg/index.tsx
  packages/uikit/src/components/TableView/SortArrowButton.tsx
  packages/uikit/src/components/TableView/Table.tsx
  packages/uikit/src/components/TableView/index.tsx
  packages/widgets-internal/components/NetworkFilter/NetworkFilter.tsx
  packages/widgets-internal/components/PoolTypeMenu/PoolTypeMenu.tsx
  packages/widgets-internal/components/TokenFilter/TokenFilter.tsx
  packages/widgets-internal/components/TokenOverview/TokenOverview.tsx
Labels: size/XXL

#10241 chore: Bump pnpm
  package.json
Labels: size/XS

#10239 chore: Bump up wallet connect ethereum provider
  packages/wagmi/package.json
  pnpm-lock.yaml
Labels: size/L

#10242 chore: Bump sdk core
  .changeset/beige-steaks-begin.md
Labels: size/XS

#10244 feat: make-zksync-airdrop-modal-globally
  apps/web/src/components/ClaimZksyncAirdropModal/index.tsx
  apps/web/src/hooks/useZksyncAirDropAutoPopup.ts
  apps/web/src/pages/_app.tsx
  apps/web/src/views/Home/components/Banners/ZksyncAirdropBanner.tsx
Labels: size/L

#10180 feat: support cross chain veCake on ZKsync
  apps/web/src/components/CrossChainVeCakeModal/ChainLogos.tsx
  apps/web/src/components/CrossChainVeCakeModal/constants.ts
  apps/web/src/components/CrossChainVeCakeModal/index.tsx
  apps/web/src/config/constants/contracts.ts
  packages/farms/constants/v3/index.ts
  packages/farms/src/const.ts
  packages/ifos/src/constants/lzChainMap.ts
Labels: size/S

#10249 fix: walletconnect issue for zksync paymaster
  apps/web/src/hooks/usePaymaster.ts
Labels: size/S

#10251 chore: Add okx wallet
  apps/web/src/config/wallet.ts
  apps/web/src/global.d.ts
Labels: size/M

#10255 chore: Add deep link to okx wallet
  apps/web/src/config/wallet.ts
Labels: size/XS

#10254 chore: raise layerZeroFeeBuffer
  apps/web/src/components/CrossChainVeCakeModal/constants.ts
  apps/web/src/components/CrossChainVeCakeModal/index.tsx
  apps/web/src/views/CakeStaking/index.tsx
Labels: size/S

#10250 feat: mobile UI adaptation & implement fiat number display
  apps/web/src/hooks/Tokens.ts
  apps/web/src/state/farmsV4/state/extendPools/hooks.ts
  apps/web/src/views/Farms/v4/components/PoolListItemAction.tsx
  apps/web/src/views/Farms/v4/components/PoolListView.tsx
  apps/web/src/views/Farms/v4/components/PoolsFilterPanel.tsx
  apps/web/src/views/Farms/v4/components/PoolsPage.tsx
  apps/web/src/views/Farms/v4/components/useColumnConfig.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/widgets/Modal/BottomDrawer/BottomDrawer.tsx
  packages/utils/formatFiatNumber.ts
  packages/utils/formatNumber.ts
  packages/widgets-internal/components/NetworkFilter/NetworkFilter.tsx
  packages/widgets-internal/components/NumberDisplay/FiatNumberDisplay.tsx
  packages/widgets-internal/components/NumberDisplay/TokenNumberDisplay.tsx
  packages/widgets-internal/components/NumberDisplay/index.tsx
  packages/widgets-internal/components/TokenFilter/TokenFilter.tsx
  packages/widgets-internal/components/TokenOverview/TokenOverview.tsx
Labels: size/XL

#10259 chore: list new gauges
  packages/farms/constants/base.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/base.ts
Labels: size/S

#10260 feat: apr component
  apps/web/src/state/farmsV4/state/poolApr/atom.ts
  apps/web/src/state/farmsV4/state/poolApr/fetcher.ts
  apps/web/src/state/farmsV4/state/poolApr/hooks.ts
  apps/web/src/state/farmsV4/state/type.ts
  apps/web/src/state/farmsV4/state/utils.ts
  apps/web/src/utils/batcher.ts
  apps/web/src/views/Farms/hooks/useLmPoolLiquidity.ts
  apps/web/src/views/Farms/hooks/useMasterChefV2Data.ts
  apps/web/src/views/Farms/hooks/useV2LpTokenTotalSupply.ts
  apps/web/src/views/Farms/v4/components/PoolApyButton.tsx
  packages/localization/src/config/translations.json
  packages/widgets-internal/farm/components/FarmApyButton/index.tsx
Labels: size/XL

#10262 perf: Make is smart contract hook immutable
  apps/web/src/hooks/useIsSmartContract.ts
Labels: size/XS

#10267 chore: Add menu ga click tracking
  apps/web/src/components/Menu/hooks/useMenuItems.ts
  apps/web/src/utils/customGTMEventTracking.ts
  packages/uikit/src/components/MenuItem/types.ts
  packages/uikit/src/components/MenuItems/MenuItems.tsx
  packages/uikit/src/components/MenuItems/types.ts
Labels: size/M

#10268 chore: add oort banner
  apps/web/src/views/Home/components/Banners/OortTradingBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#10273 chore: fix banner full screen text
  apps/web/src/views/Home/components/Banners/OortTradingBanner.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#10274 perf: reduce rerender of ItemAction
  apps/web/src/views/Farms/v4/components/PoolListItemAction.tsx
  apps/web/src/views/Farms/v4/components/useColumnConfig.tsx
Labels: size/XS

#10261 fix: Add workaround for zksync smart wallets when withdraw
  apps/web/src/views/Farms/hooks/v3/useFarmV3Actions.tsx
Labels: size/M

#10266 feat: v2/v3/stable positions
  apps/web/src/hooks/v3/usePools.ts
  apps/web/src/state/farmsV4/state/accountPositions/atom.ts
  apps/web/src/state/farmsV4/state/accountPositions/fetcher.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks.ts
  apps/web/src/state/farmsV4/state/accountPositions/type.ts
  packages/stable-swap-sdk/src/constants/pools/bsc.ts
Labels: size/XL

#10282 feat: display combined apr
  apps/web/src/state/farmsV4/state/poolApr/fetcher.ts
  apps/web/src/state/farmsV4/state/poolApr/hooks.ts
  apps/web/src/views/Farms/v4/components/PoolsPage.tsx
  apps/web/src/views/Farms/v4/components/useColumnConfig.tsx
Labels: size/M

#10287 feat: 2 new gauges
  .changeset/violet-guests-attend.md
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/M

#10221 feat: List new game karat galaxy
  packages/games/src/constants/games/index.ts
  packages/games/src/constants/games/karatGalaxy.ts
Labels: size/M

#10289 fix: Karat Galaxy eslint
  packages/games/src/constants/games/karatGalaxy.ts
Labels: size/M

#10293 chore: remove stale banners
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/XS

#10290 chore: add pepe syrup pool
  packages/pools/src/constants/pools/56.ts
Labels: size/XS

#10284 fix: Oort banner desc text not visible
  apps/web/src/views/Home/components/Banners/OortTradingBanner.tsx
Labels: size/S

#10275 feat: implement My Position page
  apps/web/src/components/RangeTag.tsx
  apps/web/src/hooks/v3/usePools.ts
  apps/web/src/hooks/v3/useV3Positions.ts
  apps/web/src/hooks/v3/utils/getPriceOrderingFromPositionForUI.ts
  apps/web/src/pages/farms/index.tsx
  apps/web/src/state/farmsV4/hooks.ts
  apps/web/src/state/farmsV4/state/accountPositions/atom.ts
  apps/web/src/state/farmsV4/state/accountPositions/fetcher.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks.ts
  apps/web/src/state/farmsV4/state/accountPositions/type.ts
  apps/web/src/state/farmsV4/state/extendPools/atom.ts
  apps/web/src/state/farmsV4/state/extendPools/hooks.ts
  apps/web/src/state/farmsV4/state/utils.ts
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/PoolListItem.tsx
  apps/web/src/views/Farms/v4/components/index.tsx
  apps/web/src/views/Swap/hooks/useStableConfig.ts
  apps/web/src/views/universalFarms/PoolsPage.tsx
  apps/web/src/views/universalFarms/PositionPage.tsx
  apps/web/src/views/universalFarms/UniversalFarms.tsx
  apps/web/src/views/universalFarms/components/PoolApyButton.tsx
  apps/web/src/views/universalFarms/components/PoolListItemAction.tsx
  apps/web/src/views/universalFarms/components/PoolListView.tsx
  apps/web/src/views/universalFarms/components/PoolsBanner.tsx
  apps/web/src/views/universalFarms/components/PoolsFilterPanel.tsx
  apps/web/src/views/universalFarms/components/PositionItem.tsx
  apps/web/src/views/universalFarms/components/StyledCard.tsx
  apps/web/src/views/universalFarms/components/index.tsx
  apps/web/src/views/universalFarms/components/useColumnConfig.tsx
  apps/web/src/views/universalFarms/index.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/__tests__/components/buttonmenu.test.tsx
  packages/uikit/src/components/ButtonMenu/ButtonMenu.tsx
  packages/uikit/src/components/ButtonMenu/types.ts
  packages/uikit/src/components/MultiSelect/MultiSelect.tsx
  packages/uikit/src/components/TableView/SortArrowButton.tsx
  packages/uikit/src/components/Tag/theme.ts
  packages/uikit/src/components/Tag/types.ts
  packages/uikit/src/tokens/colors.ts
  packages/widgets-internal/components/NetworkFilter/NetworkFilter.tsx
  packages/widgets-internal/components/TokenFilter/TokenFilter.tsx
Labels: size/XXL

#10283 feat: pool details page
  apps/web/src/pages/pools/[chainName]/[id].tsx
  apps/web/src/state/info/hooks.ts
  apps/web/src/state/info/types.ts
  apps/web/src/utils/chainNameConverter.ts
  apps/web/src/views/PoolDetail/PoolDetail.tsx
  apps/web/src/views/PoolDetail/components/BreadcrumbNav.tsx
  apps/web/src/views/PoolDetail/components/PoolInfo.tsx
  apps/web/src/views/PoolDetail/hooks/usePoolData.ts
  apps/web/src/views/PoolDetail/hooks/usePoolSymbol.ts
  apps/web/src/views/PoolDetail/hooks/useRouterQuery.ts
  apps/web/src/views/PoolDetail/hooks/useStablePoolFee.ts
  apps/web/src/views/PoolDetail/index.ts
  packages/localization/src/config/translations.json
  packages/uikit/src/components/FeeTier/FeeTier.tsx
  packages/widgets-internal/components/CurrencyLogo/DoubleCurrencyLogo.tsx
  packages/widgets-internal/components/FeeTierTooltip/index.tsx
Labels: size/L

#10277 fix: Chain name not visible on wrong network modal
  apps/web/src/components/NetworkModal/WrongNetworkModal.tsx
Labels: size/M

#10295 chore: add new arb and base gauges
  packages/farms/constants/arb.ts
  packages/farms/constants/base.ts
  packages/gauges/src/constants/config/prod.ts
Labels: size/M

#10280 fix: Liquid staking apr's and slisbnb withdraw link
  apps/web/src/views/LiquidStaking/constants/56.ts
  apps/web/src/views/LiquidStaking/constants/FAQs/BnbSnbnbFaq.tsx
  apps/web/src/views/LiquidStaking/hooks/useLiquidStakingApr.tsx
Labels: size/M

#10294 chore: add-allora-banner
  apps/web/src/components/PhishingWarningBanner/Allora.tsx
  apps/web/src/components/PhishingWarningBanner/index.tsx
  apps/web/src/views/Home/components/Banners/AlloraBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#10299 feat: Remove profile creation fee
  apps/web/src/views/ProfileCreation/UserName.tsx
Labels: size/M
