Repository pancakeswap/pancake-frontend, pull requests merged in 2024-08, with the labels that each got.

#10304 feat(NFT): Hide lowestPrice text when is zero
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/shared/ManageNFTsCard.tsx
  apps/web/src/views/Nft/market/components/BuySellModals/SellModal/EditStage.tsx
  apps/web/src/views/Nft/market/components/BuySellModals/SellModal/SellStage.tsx
  apps/web/src/views/Nft/market/components/BuySellModals/SellModal/TransferStage.tsx
Labels: size/XS

#10300 chore: add ethena usde farm and gauge on eth
  packages/farms/constants/eth.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/eth.ts
Labels: size/S

#10301 feat: add link for pool action
  apps/web/src/views/universalFarms/components/PoolListItemAction.tsx
  apps/web/src/views/universalFarms/components/PoolListView.tsx
  apps/web/src/views/universalFarms/components/useColumnConfig.tsx
Labels: size/L

#10270 chore: fix some comments
  packages/uikit/src/hooks/useTooltip/useTooltip.tsx
Labels: size/XS

#10245 fix: Swap refresh button not working when pair change
  apps/web/src/hooks/useThrottleFn.ts
Labels: size/XS

#10306 feat: pool detail position
  apps/web/src/state/farmsV4/state/accountPositions/fetcher.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks.ts
  apps/web/src/state/farmsV4/state/extendPools/fetcher.ts
  apps/web/src/state/farmsV4/state/extendPools/hooks.ts
  apps/web/src/state/farmsV4/state/poolApr/hooks.ts
  apps/web/src/state/farmsV4/state/utils.ts
  apps/web/src/state/info/hooks.ts
  apps/web/src/state/info/types.ts
  apps/web/src/views/PoolDetail/components/BreadcrumbNav.tsx
  apps/web/src/views/PoolDetail/components/MyPositions.tsx
  apps/web/src/views/PoolDetail/components/PoolInfo.tsx
  apps/web/src/views/PoolDetail/hooks/usePoolData.ts
  apps/web/src/views/PoolDetail/hooks/usePoolInfo.ts
  apps/web/src/views/PoolDetail/hooks/usePoolSymbol.ts
  apps/web/src/views/universalFarms/components/PositionItem.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/components/Card/theme.ts
  packages/uikit/src/components/Card/types.ts
  packages/uikit/src/tokens/colors.ts
Labels: size/XL

#10253 fix: Ipfs links in voting
  apps/web/src/state/types.ts
  apps/web/src/state/voting/helpers.ts
  apps/web/src/views/Voting/Proposal/Details.tsx
  apps/web/src/views/Voting/components/Proposal/VoteRow.tsx
  apps/web/src/views/Voting/components/Proposals/Proposals.tsx
  apps/web/src/views/Voting/config.ts
Labels: size/M

#10307 feat: pool-detail-pair-info
  apps/web/src/state/farmsV4/state/type.ts
  apps/web/src/state/farmsV4/state/utils.ts
  apps/web/src/views/PoolDetail/components/ChangePercent.tsx
  apps/web/src/views/PoolDetail/components/PoolCurrencies.tsx
  apps/web/src/views/PoolDetail/components/PoolInfo.tsx
  apps/web/src/views/PoolDetail/components/PoolStatus.tsx
  apps/web/src/views/PoolDetail/components/PoolTokens.tsx
  apps/web/src/views/V3Info/utils/numbers.ts
  packages/localization/src/config/translations.json
Labels: size/L

#10305 fix: correct usd price of position & refactor code by diff protocol
  apps/web/src/state/farmsV4/state/accountPositions/hooks.ts
  apps/web/src/views/universalFarms/PositionPage.tsx
  apps/web/src/views/universalFarms/components/PositionItem.tsx
  apps/web/src/views/universalFarms/components/StakeModal.tsx
  packages/localization/src/config/translations.json
Labels: size/XL

#10318 fix: Potential opener manipulation
  packages/next-config/withWebSecurityHeaders.ts
Labels: size/XS

#10313 feat: add/remove liquidity Action to Position item
  apps/web/src/state/farmsV4/state/accountPositions/fetcher.ts
  apps/web/src/state/farmsV4/state/accountPositions/type.ts
  apps/web/src/state/farmsV4/state/extendPools/hooks.ts
  apps/web/src/views/PoolDetail/components/MyPositions.tsx
  apps/web/src/views/PoolDetail/components/PoolInfo.tsx
  apps/web/src/views/PoolDetail/hooks/usePoolInfo.ts
  apps/web/src/views/PoolDetail/hooks/usePoolSymbol.ts
  apps/web/src/views/PoolDetail/hooks/useStablePoolFee.ts
  apps/web/src/views/universalFarms/PositionPage.tsx
  apps/web/src/views/universalFarms/components/PositionItem.tsx
Labels: size/XL

#10322 chore: add new farms and gauges
  packages/farms/constants/arb.ts
  packages/farms/constants/bsc.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/arb.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/M

#10330 chore: Remove comments
  apps/gamification/config/constants/dashboardAllowList.ts
Labels: size/S

#10332 fix: TG connect
  apps/gamification/next.config.mjs
  apps/gamification/views/Profile/hooks/settingsModal/useConnectTelegram.tsx
  packages/next-config/withWebSecurityHeaders.ts
Labels: size/M

#10324 fix: Remove pools from page network support modal description
  apps/web/src/components/NetworkModal/PageNetworkSupportModal.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#10325 feat: Update gamification UI
  apps/gamification/config/constants/contracts.ts
  apps/gamification/config/constants/endpoints.ts
  apps/gamification/views/Profile/hooks/settingsModal/useConnectTelegram.tsx
  apps/gamification/views/Quest/components/Reward/Questers.tsx
  apps/gamification/views/Quest/components/Share.tsx
  apps/gamification/views/Quest/index.tsx
  apps/gamification/views/Quests/index.tsx
Labels: size/M

#10323 chore: fix quests button menu allignment
  apps/gamification/views/Quests/components/Quests.tsx
  packages/uikit/src/__tests__/components/buttonmenu.test.tsx
  packages/uikit/src/components/ButtonMenu/ButtonMenu.tsx
Labels: size/XS

#10326 feat: position item mobile UI
  apps/web/src/state/farmsV4/state/extendPools/hooks.ts
  apps/web/src/state/farmsV4/state/poolApr/utils.ts
  apps/web/src/state/farmsV4/state/utils.ts
  apps/web/src/views/universalFarms/PoolsPage.tsx
  apps/web/src/views/universalFarms/PositionPage.tsx
  apps/web/src/views/universalFarms/components/PoolListItemAction.tsx
  apps/web/src/views/universalFarms/components/PositionItem.tsx
  apps/web/src/views/universalFarms/components/useColumnConfig.tsx
  apps/web/src/views/universalFarms/utils/index.ts
  packages/uikit/src/components/Svg/Icons/SwapHoriz.tsx
  packages/uikit/src/components/Svg/index.tsx
  packages/uikit/src/components/TableView/Table.tsx
  packages/widgets-internal/components/CurrencyLogo/DoubleCurrencyLogo.tsx
Labels: size/L

#10333 feat: Gamification update
  apps/gamification/views/DashboardQuestEdit/components/SubmitAction/index.tsx
  apps/gamification/views/DashboardQuestEdit/components/Tasks/AddHoldToken.tsx
  apps/gamification/views/DashboardQuestEdit/context/types.ts
  apps/gamification/views/DashboardQuestEdit/utils/generateNewTask.ts
  apps/gamification/views/DashboardQuestEdit/utils/verifyTask.ts
Labels: size/M, automerge

#10344 chore: Remove dashboard access
  apps/gamification/config/constants/dashboardAllowList.ts
Labels: size/XS

#10312 fix: Only show Pcs nfts when changing profile pic and add pancake collectibles link
  apps/web/src/pages/profile/pancake-collectibles.tsx
  apps/web/src/views/Nft/market/hooks/useNftsForAddress.tsx
  apps/web/src/views/Nft/market/hooks/useUserProfileCreationNfts.tsx
  apps/web/src/views/Profile/components/EditProfileModal/ChangeProfilePicView.tsx
  apps/web/src/views/Profile/components/EditProfileModal/StartView.tsx
  apps/web/src/views/Profile/components/EditProfileModal/index.tsx
  apps/web/src/views/Profile/components/PancakeCollectibles.tsx
  apps/web/src/views/Profile/components/ProfileHeader.tsx
  apps/web/src/views/ProfileCreation/ProfilePicture.tsx
Labels: size/L

#10337 feat: Update gamification UI
  apps/gamification/views/Quest/components/Reward/Questers.tsx
  apps/gamification/views/Quest/index.tsx
Labels: size/S, automerge

#10331 feat: add page loading for pool detail page
  apps/web/src/views/PoolDetail/components/BreadcrumbNav.tsx
  apps/web/src/views/PoolDetail/components/PoolInfo.tsx
Labels: size/S

#10320 feat: unified v2/ss/v3 transaction table
  apps/web/src/views/PoolDetail/components/PoolInfo.tsx
  apps/web/src/views/PoolDetail/components/Transactions/Transactions.tsx
  apps/web/src/views/PoolDetail/components/Transactions/TransactionsTable.tsx
  apps/web/src/views/PoolDetail/components/Transactions/index.ts
  apps/web/src/views/PoolDetail/components/Transactions/styled.ts
  apps/web/src/views/PoolDetail/components/Transactions/type.ts
  apps/web/src/views/PoolDetail/hooks/usePoolTransactions.ts
  apps/web/src/views/V3Info/hooks/index.ts
  packages/localization/src/config/translations.json
Labels: size/XL

#10341 feat: pool detail apr
  apps/web/src/pages/farms/index.tsx
  apps/web/src/state/farmsV4/state/extendPools/fetcher.ts
  apps/web/src/state/farmsV4/state/poolApr/fetcher.ts
  apps/web/src/state/farmsV4/state/poolApr/hooks.ts
  apps/web/src/views/PoolDetail/PoolDetail.tsx
  apps/web/src/views/PoolDetail/components/PoolInfo.tsx
  apps/web/src/views/universalFarms/PoolsPage.tsx
Labels: size/M

#10327 feat: unified pool charts
  apps/web/src/config/constants/index.ts
  apps/web/src/views/PoolDetail/components/ChartFee.tsx
  apps/web/src/views/PoolDetail/components/ChartLiquidity/ChartLiquidity.tsx
  apps/web/src/views/PoolDetail/components/ChartLiquidity/ChartToolTip.tsx
  apps/web/src/views/PoolDetail/components/ChartLiquidity/ChartV2Liquidity.tsx
  apps/web/src/views/PoolDetail/components/ChartLiquidity/ChartV3Liquidity.tsx
  apps/web/src/views/PoolDetail/components/ChartLiquidity/CurrentPriceLabel.tsx
  apps/web/src/views/PoolDetail/components/ChartLiquidity/index.ts
  apps/web/src/views/PoolDetail/components/ChartLiquidity/styled.ts
  apps/web/src/views/PoolDetail/components/ChartLiquidity/type.ts
  apps/web/src/views/PoolDetail/components/ChartTVL.tsx
  apps/web/src/views/PoolDetail/components/ChartVolume.tsx
  apps/web/src/views/PoolDetail/components/PoolCharts.tsx
  apps/web/src/views/PoolDetail/components/PoolInfo.tsx
  apps/web/src/views/PoolDetail/hooks/usePoolChartFeeData.ts
  apps/web/src/views/PoolDetail/hooks/usePoolChartTVLData.ts
  apps/web/src/views/PoolDetail/hooks/usePoolChartVolumeData.ts
  apps/web/src/views/V3Info/components/BarChart/alt.tsx
  apps/web/src/views/V3Info/hooks/index.ts
  packages/localization/src/config/translations.json
Labels: size/XL

#10339 feat: total positions value
  apps/web/src/state/farmsV4/state/accountPositions/fetcher.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks.ts
  apps/web/src/state/farmsV4/state/accountPositions/type.ts
  apps/web/src/views/PoolDetail/components/MyPositions.tsx
  apps/web/src/views/PoolDetail/hooks/useV3Positions.ts
  packages/localization/src/config/translations.json
Labels: size/L

#10340 fix: Network multi select not fully visible on mobile in gamification
  apps/gamification/components/NetworkMultiSelector.tsx
  apps/gamification/views/Quests/components/Quests.tsx
  apps/gamification/views/Quests/index.tsx
  packages/uikit/src/components/MultiSelect/MultiSelect.tsx
Labels: size/M

#10334 chore: add lorenzo btc farm
  packages/farms/constants/bsc.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/S

#10346 feat: add detailMode
  apps/web/src/views/PoolDetail/components/MyPositions.tsx
  apps/web/src/views/universalFarms/components/PositionItem.tsx
Labels: size/L

#10338 fix: fixed UIQA issues
  apps/web/src/components/TokenImage/index.tsx
  apps/web/src/state/farmsV4/state/extendPools/hooks.ts
  apps/web/src/state/farmsV4/state/utils.ts
  apps/web/src/views/universalFarms/PoolsPage.tsx
  apps/web/src/views/universalFarms/PositionPage.tsx
  apps/web/src/views/universalFarms/UniversalFarms.tsx
  apps/web/src/views/universalFarms/components/PoolApyButton.tsx
  apps/web/src/views/universalFarms/components/PoolListItemAction.tsx
  apps/web/src/views/universalFarms/components/PoolsFilterPanel.tsx
  apps/web/src/views/universalFarms/components/PositionItem.tsx
  apps/web/src/views/universalFarms/components/StyledCard.tsx
  apps/web/src/views/universalFarms/components/useColumnConfig.tsx
  apps/web/src/views/universalFarms/utils/index.ts
  packages/localization/src/config/translations.json
  packages/tokens/src/helpers/getTokensByChain.ts
  packages/uikit/src/components/Image/TokenPairImage.tsx
  packages/uikit/src/components/Image/styles.tsx
  packages/uikit/src/components/Image/types.ts
  packages/uikit/src/components/MultiSelect/MultiSelect.tsx
  packages/uikit/src/components/MultiSelect/SearchBox.tsx
  packages/uikit/src/components/TableView/Table.tsx
  packages/widgets-internal/components/TokenFilter/TokenFilter.tsx
  packages/widgets-internal/components/TokenOverview/TokenOverview.tsx
Labels: size/L

#10348 fix: resolved review issues
  apps/web/src/views/universalFarms/PoolsPage.tsx
  apps/web/src/views/universalFarms/components/PoolListView.tsx
  apps/web/src/views/universalFarms/components/PoolsFilterPanel.tsx
  apps/web/src/views/universalFarms/components/PositionItem.tsx
  apps/web/src/views/universalFarms/hooks/index.tsx
  packages/tokens/src/helpers/getTokensByChain.ts
  packages/uikit/src/components/MultiSelect/MultiSelect.tsx
  packages/uikit/src/components/MultiSelect/SearchBox.tsx
  packages/widgets-internal/components/NetworkFilter/NetworkFilter.tsx
Labels: size/L

#10350 chore: usdce-usdc farm on arbitrum
  packages/farms/constants/arb.ts
  packages/gauges/src/constants/config/prod.ts
Labels: size/S

#10345 chore: Reduce zksync layer zero buffer
  apps/web/src/components/CrossChainVeCakeModal/constants.ts
  apps/web/src/components/CrossChainVeCakeModal/hooks/useMultichainVeCakeWellSynced.ts
  apps/web/src/components/CrossChainVeCakeModal/index.tsx
  apps/web/src/views/CakeStaking/index.tsx
Labels: size/M

#10308 feat: Trigger block data after trx to reflect changes immediately without waiting interval
  apps/web/src/hooks/useCatchTxError.tsx
  apps/web/src/hooks/usePublicNodeWaitForTransaction.ts
  apps/web/src/state/block/hooks.ts
  apps/web/src/state/transactions/updater.tsx
  packages/wagmi/src/hooks/useBlock.ts
Labels: size/M

#10358 feat: Add quest in menu
  apps/web/src/components/Menu/config/config.ts
  packages/localization/src/config/translations.json
Labels: size/XS

#10359 fix: resolved stable pool loading
  apps/web/src/state/farmsV4/state/farmPools/fetcher.ts
Labels: size/XS

#10357 feat: optimize the url of universal farms
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/pages/farms-legacy/index.tsx
  apps/web/src/pages/farms/auction.tsx
  apps/web/src/pages/farms/history.tsx
  apps/web/src/pages/farms/index.tsx
  apps/web/src/pages/liquidity/pools.tsx
  apps/web/src/pages/liquidity/positions.tsx
  apps/web/src/views/universalFarms/PoolsPage.tsx
  apps/web/src/views/universalFarms/PositionPage.tsx
  apps/web/src/views/universalFarms/UniversalFarms.tsx
Labels: size/L

#10360 fix: Refetch block data immediate after trx receipt in updater
  apps/web/src/state/transactions/updater.tsx
Labels: size/XS

#10362 chore: List usdt bitu stable pool
  .changeset/angry-nails-perform.md
  packages/stable-swap-sdk/src/constants/pools/bsc.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/S

#10363 chore: add SEED farm on arbitrum
  packages/farms/constants/arb.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/arb.ts
Labels: size/S

#10361 chore: add quest banner
  apps/web/src/views/Home/components/Banners/QuestBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#10364 chore: make quest banner logo dark text
  apps/web/src/views/Home/components/Banners/QuestBanner.tsx
Labels: size/XS

#10365 chore: fix btc signature issue
  apps/web/src/views/BuyCrypto/containers/BuyCryptoForm.tsx
  apps/web/src/views/BuyCrypto/hooks/useOnRampSignature.ts
Labels: size/XS

#10369 fix: resolved position list data repeat
  apps/web/src/state/farmsV4/state/accountPositions/fetcher.ts
  apps/web/src/views/universalFarms/PoolsPage.tsx
  apps/web/src/views/universalFarms/components/PoolListItemAction.tsx
  apps/web/src/views/universalFarms/components/useColumnConfig.tsx
  packages/uikit/src/components/TableView/Table.tsx
Labels: size/L

#10370 fix: universal farm UI qa issues
  apps/web/src/views/universalFarms/PositionPage.tsx
  apps/web/src/views/universalFarms/UniversalFarms.tsx
  apps/web/src/views/universalFarms/components/PoolsBanner.tsx
  apps/web/src/views/universalFarms/components/PositionItem.tsx
  apps/web/src/views/universalFarms/components/StyledCard.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/components/MultiSelect/MultiSelect.tsx
  packages/uikit/src/components/MultiSelect/SearchBox.tsx
  packages/uikit/src/components/TableView/Table.tsx
  packages/uikit/src/components/Tag/theme.ts
  packages/uikit/src/tokens/colors.ts
Labels: size/L

#10373 fix: Connector chainid problem in gamification
  apps/gamification/views/Profile/components/ProfileHeader.tsx
  apps/gamification/views/Profile/hooks/settingsModal/useConnectDiscord.tsx
  apps/gamification/views/Profile/hooks/settingsModal/useConnectTelegram.tsx
  apps/gamification/views/Profile/hooks/settingsModal/useConnectTwitter.tsx
Labels: size/M

#10228 fix: Rabby wallet error
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/L

#10375 fix: reduce the pool list api fetch
  apps/web/src/pages/liquidity/pool/[chainName]/[id].tsx
  apps/web/src/state/farmsV4/state/farmPools/fetcher.ts
  apps/web/src/state/farmsV4/state/poolApr/hooks.ts
  apps/web/src/state/farmsV4/state/type.ts
  apps/web/src/state/farmsV4/state/utils.ts
  apps/web/src/views/universalFarms/PoolsPage.tsx
  apps/web/src/views/universalFarms/components/PoolApyButton.tsx
  apps/web/src/views/universalFarms/components/PoolListItemAction.tsx
  apps/web/src/views/universalFarms/components/PoolListView.tsx
  apps/web/src/views/universalFarms/components/PoolsBanner.tsx
  apps/web/src/views/universalFarms/components/useColumnConfig.tsx
  packages/localization/src/config/translations.json
  packages/widgets-internal/components/FeeTierTooltip/index.tsx
  packages/widgets-internal/components/NumberDisplay/FiatNumberDisplay.tsx
Labels: size/L

#10384 chore: Remove pancake mayor
  packages/games/src/constants/games/binaryX.ts
  packages/games/src/constants/games/index.ts
Labels: size/M

#10382 feat: position actions
  apps/web/src/state/farmsV4/hooks.ts
  apps/web/src/state/farmsV4/state/accountPositions/fetcher.ts
  apps/web/src/state/farmsV4/state/accountPositions/fetcher/v3/getAccountV3FarmingPendingCakeReward.ts
  apps/web/src/state/farmsV4/state/accountPositions/fetcher/v3/getAccountV3Positions.ts
  apps/web/src/state/farmsV4/state/accountPositions/fetcher/v3/getAccountV3TokenIds.ts
  apps/web/src/state/farmsV4/state/accountPositions/fetcher/v3/index.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/index.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountPositionDetailByPool.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountStableLpDetails.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountV2LpDetails.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountV2PendingCakeReward.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountV3Positions.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useExtraV3PositionInfo.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useTokenByChainId.ts
  apps/web/src/state/farmsV4/state/accountPositions/type.ts
  apps/web/src/state/farmsV4/state/poolApr/fetcher.ts
  apps/web/src/state/farmsV4/state/utils.ts
  apps/web/src/views/PoolDetail/components/MyPositions.tsx
  apps/web/src/views/PoolDetail/components/PoolEarnings.tsx
  apps/web/src/views/universalFarms/PositionPage.tsx
  apps/web/src/views/universalFarms/components/Modals/V3StakeModal.tsx
  apps/web/src/views/universalFarms/components/PositionActions/StakeActions.tsx
  apps/web/src/views/universalFarms/components/PositionActions/V2PositionActions.tsx
  apps/web/src/views/universalFarms/components/PositionActions/V3PositionActions.tsx
  apps/web/src/views/universalFarms/components/PositionActions/V3UnstakeModalContent.tsx
  apps/web/src/views/universalFarms/components/PositionActions/index.tsx
  apps/web/src/views/universalFarms/components/PositionItem.tsx
  apps/web/src/views/universalFarms/components/PositionItem/PositionInfo.tsx
  apps/web/src/views/universalFarms/components/PositionItem/PositionItem.tsx
  apps/web/src/views/universalFarms/components/PositionItem/PositionItemSkeleton.tsx
  apps/web/src/views/universalFarms/components/PositionItem/PriceRange.tsx
  apps/web/src/views/universalFarms/components/PositionItem/StablePositionItem.tsx
  apps/web/src/views/universalFarms/components/PositionItem/V2PositionItem.tsx
  apps/web/src/views/universalFarms/components/PositionItem/V3PositionItem.tsx
  apps/web/src/views/universalFarms/components/PositionItem/index.ts
  apps/web/src/views/universalFarms/components/PositionItem/styled.ts
  apps/web/src/views/universalFarms/components/index.tsx
  apps/web/src/views/universalFarms/hooks/index.ts
  apps/web/src/views/universalFarms/hooks/useCakeEarning.ts
  apps/web/src/views/universalFarms/hooks/useCheckShouldSwitchNetwork.ts
  apps/web/src/views/universalFarms/hooks/useTotalPriceUSD.ts
  apps/web/src/views/universalFarms/hooks/useV2FarmActions.ts
Labels: size/XXL

#10383 fix: add skeleton for Positions loading
  apps/web/src/views/universalFarms/PositionPage.tsx
  packages/utils/formatFiatNumber.ts
Labels: size/S

#10376 feat: Port trigger block data after trx to gamifications
  apps/gamification/hooks/usePublicNodeWaitForTransaction.ts
  apps/gamification/state/transactions/updater.tsx
  apps/gamification/views/DashboardQuestEdit/hooks/useQuestRewardApprovalStatus.ts
Labels: size/S

#10354 feat: Update trading reward contract
  apps/web/src/config/constants/contracts.ts
  apps/web/src/views/TradingReward/components/YourTradingReward/TotalPeriod.tsx
Labels: size/XS

#10379 feat: Reduce average block times of chains
  apps/gamification/hooks/usePublicNodeWaitForTransaction.ts
  apps/gamification/state/transactions/updater.tsx
  apps/web/src/components/SubgraphHealthIndicator/SubgraphHealthIndicator.tsx
  apps/web/src/config/constants/averageChainBlockTimes.ts
  apps/web/src/hooks/usePublicNodeWaitForTransaction.ts
  apps/web/src/hooks/useSafeTxHashTransformer.ts
  apps/web/src/state/transactions/updater.tsx
  apps/web/src/views/Swap/MMLinkPools/hooks/useSwapCallback.ts
  packages/chains/src/averageChainBlockTimes.ts
  packages/chains/src/index.test.ts
  packages/chains/src/index.ts
Labels: size/M

#10386 fix: Wrong subgraph health shown when active chain is different than page supports
  apps/web/src/hooks/useSubgraphHealth.ts
Labels: size/S

#10381 fix: MstEth price gauge
  apps/web/src/views/PositionManagers/components/TableView/index.tsx
  packages/position-managers/src/constants/vaults/arb.ts
Labels: size/XS

#10385 chore: list new farms and gauges
  packages/farms/constants/base.ts
  packages/farms/constants/eth.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/base.ts
  packages/tokens/src/constants/eth.ts
Labels: size/L

#10374 feat: Use pcs wagmi hooks for block sync
  apps/web/src/hooks/Tokens.ts
  apps/web/src/views/AddLiquidityV3/Migrate.tsx
  apps/web/src/views/CakeStaking/hooks/useAPR.ts
  apps/web/src/views/CakeStaking/hooks/useVeCakeTotalSupply.ts
  apps/web/src/views/Farms/components/YieldBooster/hooks/bCakeV3/useBCakeV3Info.ts
  apps/web/src/views/Farms/components/YieldBooster/hooks/useProxyCAKEBalance.ts
  apps/web/src/views/FixedStaking/hooks/useHandleWithdrawSubmission.tsx
  apps/web/src/views/Home/hooks/useCakeEmissionPerBlock.tsx
  apps/web/src/views/Predictions/components/ChainlinkChart.tsx
Labels: size/S

#10319 feat: Add default rpc gas price to settings and fix returning default gasprice when it is in wrong network
  apps/web/src/components/Menu/GlobalSettings/GasSettings.tsx
  apps/web/src/state/user/hooks/index.tsx
Labels: size/M

#10336 fix: Rewards earned shown for users not qualified in breakdown list and add previous period component
  apps/web/src/views/TradingReward/hooks/useAllTradingRewardPair.tsx
  apps/web/src/views/TradingReward/hooks/useRewardBreakdown.tsx
Labels: size/S

#10387 feat: Reduce buffer phase in arb ai predictions
  apps/web/src/views/Predictions/components/RoundCard/AIPredictions/AIOpenRoundCard.tsx
  apps/web/src/views/Predictions/components/RoundCard/OpenRoundCard.tsx
  packages/prediction/src/constants/config.ts
Labels: size/L

#10372 feat: add birthday banner
  apps/web/src/views/Home/components/Banners/BirthdayBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#10388 chore: fix popout on birthday banner
  apps/web/src/views/Home/components/Banners/BirthdayBanner.tsx
Labels: size/XS

#10368 feat: Brasil meetup banner
  apps/web/src/views/Home/components/Banners/BrasilMeetupBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/L

#10391 feat: Remove start trading button
  apps/web/src/views/Home/components/Banners/BrasilMeetupBanner.tsx
Labels: size/XS

#10392 fix: Add learn more link to mobile
  apps/web/src/views/Home/components/Banners/BrasilMeetupBanner.tsx
Labels: size/XS

#10394 chore: list new farms and gauges on base and arb
  packages/farms/constants/arb.ts
  packages/farms/constants/base.ts
  packages/gauges/src/constants/config/prod.ts
Labels: size/M

#10400 chore: update merkl config
  apps/web/src/config/constants/merklPools.json
Labels: size/M

#10390 fix: universal farm issues
  apps/web/src/hooks/Tokens.ts
  apps/web/src/pages/liquidity/pool/[chainName]/[id].tsx
  apps/web/src/state/farmsV4/state/accountPositions/fetcher.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/index.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountStableLpDetails.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountV2LpDetails.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountV3Positions.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useExtraV3PositionInfo.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useTokenByChainId.ts
  apps/web/src/views/PoolDetail/PoolDetail.tsx
  apps/web/src/views/PoolDetail/components/PoolStatus.tsx
  apps/web/src/views/PoolDetail/hooks/useV3Positions.ts
  apps/web/src/views/universalFarms/components/PoolListItemAction.tsx
  apps/web/src/views/universalFarms/components/useColumnConfig.tsx
  packages/localization/src/config/translations.json
  packages/widgets-internal/components/TokenFilter/TokenFilter.tsx
Labels: size/L

#10402 fix: resolve bsc detail page path
  apps/web/src/views/universalFarms/components/PoolListItemAction.tsx
Labels: size/XS

#10395 chore: log swap Tx sent event
  apps/web/src/utils/customGTMEventTracking.ts
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButton.tsx
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMConfirmModalState.ts
  apps/web/src/views/Swap/V3Swap/containers/SwapCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalState.ts
Labels: size/M

#10404 fix: resolve cannot stake v2/ss pool #PAN-3506
  apps/web/src/state/farmsV4/state/accountPositions/fetcher.ts
  apps/web/src/views/universalFarms/components/PositionActions/V2PositionActions.tsx
Labels: size/S

#10406 fix: resolve cannot stake v2/ss pool when cross chain
  apps/web/src/hooks/useTokenAllowance.ts
  apps/web/src/views/universalFarms/components/PositionActions/V2PositionActions.tsx
Labels: size/M

#10407 fix: resolve stable position count error
  apps/web/src/views/PoolDetail/components/MyPositions.tsx
Labels: size/XS

#10405 chore: GTM log more details for farm and addLiquidity
  apps/web/src/utils/customGTMEventTracking.ts
  apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
  apps/web/src/views/AddLiquidity/index.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
  apps/web/src/views/Farms/components/FarmCard/StakeAction.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
  apps/web/src/views/Farms/hooks/v3/useFarmV3Actions.tsx
Labels: size/L

#10408 chore: list new farm&gauges on eth
  packages/farms/constants/eth.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/eth.ts
Labels: size/S

#10403 feat: apr-position
  apps/web/src/state/farmsV4/state/accountPositions/fetcher.ts
  apps/web/src/state/farmsV4/state/accountPositions/fetcher/v3/getAccountV3Positions.ts
  apps/web/src/state/farmsV4/state/accountPositions/type.ts
  apps/web/src/state/farmsV4/state/poolApr/fetcher.ts
  apps/web/src/state/farmsV4/state/poolApr/hooks.ts
  apps/web/src/state/farmsV4/state/type.ts
  apps/web/src/state/farmsV4/state/utils.ts
  apps/web/src/views/PoolDetail/PoolDetail.tsx
  apps/web/src/views/PoolDetail/components/MyPositions.tsx
  apps/web/src/views/universalFarms/components/PoolApyButton.tsx
  apps/web/src/views/universalFarms/components/PositionItem/PositionInfo.tsx
  apps/web/src/views/universalFarms/components/PositionItem/PositionItem.tsx
  apps/web/src/views/universalFarms/components/PositionItem/StablePositionItem.tsx
  apps/web/src/views/universalFarms/components/PositionItem/V2PositionItem.tsx
  apps/web/src/views/universalFarms/components/PositionItem/V3PositionItem.tsx
  apps/web/src/views/universalFarms/hooks/useCakeEarning.ts
Labels: size/L

#10412 chore: remove OORT banner
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/XS

#10411 fix: resolved add liquidity link error when cross chains
  apps/web/src/views/PoolDetail/components/MyPositions.tsx
Labels: size/S

#10413 fix: resolved compiled code throw error when into arb detail page
  apps/web/src/views/universalFarms/hooks/useCakeEarning.ts
Labels: size/S

#10414 fix: resolved feetier amount
  apps/web/src/views/universalFarms/components/PositionActions/StakeActions.tsx
  apps/web/src/views/universalFarms/components/PositionActions/V2PositionActions.tsx
  apps/web/src/views/universalFarms/components/PositionActions/V3PositionActions.tsx
  apps/web/src/views/universalFarms/components/PositionItem/PositionInfo.tsx
  apps/web/src/views/universalFarms/components/PositionItem/PositionItem.tsx
  apps/web/src/views/universalFarms/components/PositionItem/V3PositionItem.tsx
  apps/web/src/views/universalFarms/hooks/useIsFarmLive.ts
Labels: size/M

#10415 feat: Move finished pools
  .changeset/lemon-cherries-thank.md
  packages/pools/src/constants/pools/324.ts
  packages/pools/src/constants/pools/42161.ts
  packages/pools/src/constants/pools/56.ts
Labels: size/M

#10356 feat: Gamification UI improvement
  apps/gamification/components/SpinnerWithLoadingText.tsx
  apps/gamification/next.config.mjs
  apps/gamification/package.json
  apps/gamification/views/DashboardQuestEdit/components/EditTemplate.tsx
  apps/gamification/views/DashboardQuestEdit/components/InputStyle.tsx
  apps/gamification/views/DashboardQuestEdit/components/Reward/AddRewardModal.tsx
  apps/gamification/views/DashboardQuestEdit/components/SubmitAction/LongPressDeleteModal.tsx
  apps/gamification/views/DashboardQuestEdit/components/Tasks/AddBlogPost.tsx
  apps/gamification/views/DashboardQuestEdit/components/Tasks/AddHoldToken.tsx
  apps/gamification/views/DashboardQuestEdit/components/Tasks/AddLottery.tsx
  apps/gamification/views/DashboardQuestEdit/components/Tasks/AddLpAddress.tsx
  apps/gamification/views/DashboardQuestEdit/components/Tasks/AddSwap.tsx
  apps/gamification/views/DashboardQuestEdit/components/Tasks/ExpandButton.tsx
  apps/gamification/views/DashboardQuestEdit/components/Tasks/SocialTask.tsx
  apps/gamification/views/DashboardQuestEdit/config/index.ts
  apps/gamification/views/DashboardQuestEdit/index.tsx
  apps/gamification/views/DashboardQuestEdit/utils/generateNewTask.ts
  apps/gamification/views/DashboardQuests/components/Records.tsx
  apps/gamification/views/Profile/components/JoinedQuests.tsx
  apps/gamification/views/Quest/components/Reward/Questers.tsx
  apps/gamification/views/Quest/components/Reward/index.tsx
  apps/gamification/views/Quest/components/Tasks/Task.tsx
  apps/gamification/views/Quest/components/Tasks/index.tsx
  apps/gamification/views/Quest/index.tsx
  apps/gamification/views/Quests/components/Quest.tsx
  apps/gamification/views/Quests/components/Quests.tsx
  pnpm-lock.yaml
Labels: size/XL

#10347 feat: Gamification add server type
  apps/gamification/pages/api/dashboard/quest-info.ts
  apps/gamification/pages/api/task/completeVisitingWebTask.ts
  apps/gamification/pages/api/twitterFollow.ts
  apps/gamification/pages/api/twitterLiked.ts
  apps/gamification/pages/api/twitterRetweet.ts
  apps/gamification/pages/api/userInfo/[userId]/quests/[questId]/start.ts
  apps/gamification/views/Quests/components/Quests.tsx
Labels: size/L, automerge

#10417 fix: wrong matched farm pool
  apps/web/src/state/farmsV4/state/farmPools/fetcher.ts
Labels: size/XS

#10418 chore: pin 4 farms to the top 4 on zksync
  packages/farms/constants/zkSync.ts
Labels: size/M

#10419 fix: resolved cross chain fetch position data failed
  apps/web/src/hooks/v3/usePools.ts
  apps/web/src/views/universalFarms/hooks/useTotalPriceUSD.ts
Labels: size/L

#10420 fix: resolved percent div 0 error
  apps/web/src/views/PoolDetail/components/PoolStatus.tsx
Labels: size/XS

#10424 fix: resolved pool detail page loading
  apps/web/src/views/universalFarms/components/PoolListItemAction.tsx
  apps/web/src/views/universalFarms/components/PositionItem/PositionItem.tsx
Labels: size/M

#10426 fix: resolved page redirect when click stake button
  apps/web/src/views/universalFarms/components/PositionActions/StakeActions.tsx
  apps/web/src/views/universalFarms/components/PositionActions/V3PositionActions.tsx
Labels: size/M

#10421 fix: apr
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountPositionDetailByPool.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useExtraV3PositionInfo.ts
  apps/web/src/state/farmsV4/state/farmPools/fetcher.ts
  apps/web/src/state/farmsV4/state/poolApr/atom.ts
  apps/web/src/state/farmsV4/state/poolApr/fetcher.ts
  apps/web/src/state/farmsV4/state/poolApr/hooks.ts
  apps/web/src/state/farmsV4/state/utils.ts
  apps/web/src/views/PoolDetail/components/MyPositions.tsx
  apps/web/src/views/PoolDetail/components/PoolInfo.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/AprButton.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/AprTooltipContent.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/PoolAprButton.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/PoolGlobalAprButton.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/PoolPositionAprButton.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/V2PoolAprModal.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/V3PoolAprModal.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/index.ts
  apps/web/src/views/universalFarms/components/PoolApyButton.tsx
  apps/web/src/views/universalFarms/components/PoolListItemAction.tsx
  apps/web/src/views/universalFarms/components/PoolListView.tsx
  apps/web/src/views/universalFarms/components/PositionActions/StakeActions.tsx
  apps/web/src/views/universalFarms/components/PositionActions/V2PositionActions.tsx
  apps/web/src/views/universalFarms/components/PositionActions/V3PositionActions.tsx
  apps/web/src/views/universalFarms/components/PositionItem/PositionInfo.tsx
  apps/web/src/views/universalFarms/components/PositionItem/PositionItem.tsx
  apps/web/src/views/universalFarms/components/PositionItem/StablePositionItem.tsx
  apps/web/src/views/universalFarms/components/PositionItem/V2PositionItem.tsx
  apps/web/src/views/universalFarms/components/PositionItem/V3PositionItem.tsx
  apps/web/src/views/universalFarms/components/StopPropagation.tsx
  apps/web/src/views/universalFarms/components/index.tsx
  apps/web/src/views/universalFarms/components/useColumnConfig.tsx
  apps/web/src/views/universalFarms/hooks/useBCakeWrapperInfo.ts
  apps/web/src/views/universalFarms/utils/displayApr.ts
  apps/web/src/views/universalFarms/utils/sumApr.ts
Labels: size/XXL

#10430 fix: resolved open position with cross chain
  apps/web/src/hooks/useActiveWeb3React.ts
  apps/web/src/views/universalFarms/components/PositionItem/PositionItem.tsx
Labels: size/M

#10428 feat: pass position to v3 unstake modal
  apps/web/src/views/universalFarms/components/PositionItem/V3PositionItem.tsx
Labels: size/XS

#10429 fix: pools redirect link
  apps/web/src/views/AddLiquidityV3/index.tsx
  apps/web/src/views/PoolDetail/components/BreadcrumbNav.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#10431 fix: harvest-button
  apps/web/src/views/PoolDetail/components/MyPositions.tsx
  apps/web/src/views/PoolDetail/components/PoolEarnings.tsx
  apps/web/src/views/PoolDetail/components/PoolStatus.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#10427 chore: add IDR fiat
  apps/web/public/images/currencies/aud.png
  apps/web/public/images/currencies/brl.png
  apps/web/public/images/currencies/cad.png
  apps/web/public/images/currencies/eur.png
  apps/web/public/images/currencies/gbp.png
  apps/web/public/images/currencies/hkd.png
  apps/web/public/images/currencies/jpy.png
  apps/web/public/images/currencies/krw.png
  apps/web/public/images/currencies/usd.png
  apps/web/public/images/currencies/vnd.png
  apps/web/src/components/Logo/CurrencyLogo.tsx
  apps/web/src/views/BuyCrypto/constants.ts
Labels: size/S

#10433 chore: add IDR fiat (#10427)
  apps/web/src/views/BuyCrypto/constants.ts
Labels: size/XS

#10432 chore: list new farms & gauges on bsc
  packages/farms/constants/bsc.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/M

#10435 fix: multiplier-by-chain
  apps/web/src/state/farmsV4/state/poolApr/fetcher.ts
Labels: size/M

#10443 fix: Network support modals width mobile
  apps/web/src/components/NetworkModal/PageNetworkSupportModal.tsx
  apps/web/src/components/NetworkModal/UnsupportedNetworkModal.tsx
  apps/web/src/components/NetworkModal/WrongNetworkModal.tsx
Labels: size/XS

#10409 fix: Buy crypto url query not applied to output currency
  apps/web/src/hooks/useCanBuyCrypto.ts
  apps/web/src/state/buyCrypto/hooks.ts
  apps/web/src/views/BuyCrypto/components/OnRampCurrencySelect/index.tsx
  apps/web/src/views/BuyCrypto/constants.ts
  apps/web/src/views/Swap/V3Swap/containers/BuyCryptoLink.tsx
Labels: size/M

#10437 feat: Implement partners docs tooltip component in buy crypto
  apps/web/src/views/BuyCrypto/components/FAQ.tsx
Labels: size/M

#10416 perf: Dont create portal when tooltip not visible
  packages/uikit/src/hooks/useTooltip/useTooltip.tsx
Labels: size/M

#10317 perf: Make v3 migration links internal to reduce calls
  apps/web/src/pages/liquidity/index.tsx
  apps/web/src/views/Farms/FarmsV3.tsx
  apps/web/src/views/Teams/index.tsx
Labels: size/M

#10446 chore: Add missing build filter
  package.json
Labels: size/XS

#10447 fix: resolved token name of farmlist
  .github/workflows/format.yml
  apps/web/src/state/farmsV4/state/utils.ts
Labels: size/S

#10448 feat: add Find other LP tokens and Migrate to V3 link
  .github/workflows/unitTests.yml
  apps/web/src/views/universalFarms/PositionPage.tsx
Labels: size/S

#10442 fix: Prediction landscape height and lottie ssr
  apps/web/src/components/PhishingWarningBanner/AIPredictionStripe.tsx
  apps/web/src/state/predictions/hooks.ts
  apps/web/src/state/predictions/selectors.ts
  apps/web/src/views/Predictions/Desktop.tsx
  apps/web/src/views/Predictions/Mobile.tsx
  apps/web/src/views/Predictions/components/Container.tsx
  apps/web/src/views/Predictions/components/InPageBanner.tsx
  apps/web/src/views/Predictions/components/Label.tsx
  apps/web/src/views/Predictions/components/RoundCard/AIPredictions/AIPredictionsLogo.tsx
  apps/web/src/views/Predictions/components/RoundCard/AIPredictions/PayoutMeter.tsx
  apps/web/src/views/Predictions/components/RoundCard/CardHeader.tsx
  apps/web/src/views/Predictions/index.tsx
Labels: size/L

#10449 fix: apply apr to liquidity detail
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/state/farmsV4/state/accountPositions/fetcher/v3/getAccountV3Positions.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountV3Position.ts
  apps/web/src/state/farmsV4/state/poolApr/hooks.ts
  apps/web/src/views/AddLiquidityV3/Modal.tsx
  apps/web/src/views/AddLiquidityV3/components/AprCalculatorV2.tsx
  apps/web/src/views/AddLiquidityV3/index.tsx
Labels: size/L

#10452 fix: merkl-apr
  apps/web/src/views/universalFarms/components/PoolAprButton/AprTooltipContent.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/PoolGlobalAprButton.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/PoolPositionAprButton.tsx
Labels: size/M

#10450 fix: info page link
  apps/web/src/views/universalFarms/components/PoolListItemAction.tsx
  apps/web/src/views/universalFarms/components/PositionActions/V2PositionActions.tsx
  apps/web/src/views/universalFarms/components/PositionItem/StablePositionItem.tsx
  apps/web/src/views/universalFarms/components/PositionItem/V2PositionItem.tsx
  packages/widgets-internal/farm/components/DepositModal/index.tsx
Labels: size/M

#10453 fix: expired farm
  apps/web/src/state/farmsV4/state/farmPools/fetcher.ts
  apps/web/src/state/farmsV4/state/poolApr/fetcher.ts
  apps/web/src/state/farmsV4/state/poolApr/hooks.ts
  apps/web/src/views/universalFarms/components/PoolAprButton/AprTooltipContent.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/PoolAprButton.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/PoolPositionAprButton.tsx
  packages/widgets-internal/components/TokenFilter/TokenFilter.tsx
Labels: size/M

#10454 fix: backTo link
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/config/constants/meta.ts
  apps/web/src/pages/stable/[address].tsx
  apps/web/src/pages/v2/pair/[[...currency]].tsx
  apps/web/src/views/AddLiquidity/ChoosePair.tsx
  apps/web/src/views/CakeStaking/components/BenefitCard.tsx
  apps/web/src/views/Home/components/EcoSystemSection/index.tsx
  apps/web/src/views/Home/components/SalesSection/data.ts
  apps/web/src/views/PoolDetail/components/Transactions/TransactionsTable.tsx
  apps/web/src/views/PoolFinder/index.tsx
  apps/web/src/views/universalFarms/UniversalFarms.tsx
Labels: size/M

#10393 feat: add exports for motion components
  packages/uikit/src/components/Box/Box.tsx
  packages/uikit/src/components/Box/Flex.tsx
  packages/uikit/src/components/Box/Grid.tsx
  packages/uikit/src/components/Box/index.tsx
  packages/uikit/src/components/Motion/AnimatePresence.tsx
  packages/uikit/src/components/Motion/index.stories.tsx
  packages/uikit/src/components/Motion/index.ts
  packages/uikit/src/components/index.ts
Labels: size/M

#10154 chore: faster prediction prices
  apps/web/src/components/PhishingWarningBanner/AIPredictionStripe.tsx
  apps/web/src/pages/api/prediction/price/index.ts
  apps/web/src/views/Predictions/components/RoundCard/AIPredictions/AILiveRoundCard.tsx
  apps/web/src/views/Predictions/context/PredictionConfigProviders.tsx
  apps/web/src/views/Predictions/hooks/usePredictionPrice.ts
  packages/prediction/src/type.ts
Labels: size/M

#10457 fix: add switch network before do tx action
  apps/web/src/views/PoolDetail/components/MyPositions.tsx
  apps/web/src/views/universalFarms/components/PositionActions/V2PositionActions.tsx
  apps/web/src/views/universalFarms/components/PositionActions/V3PositionActions.tsx
  apps/web/src/views/universalFarms/hooks/useCheckShouldSwitchNetwork.ts
  packages/localization/src/config/translations.json
Labels: size/M

#10458 fix: resolved v3 pool info action
  apps/web/src/views/universalFarms/components/PoolListItemAction.tsx
Labels: size/XS

#10461 fix: resolved token list missing
  apps/web/src/state/lists/hooks.ts
  apps/web/src/state/lists/updater.ts
  apps/web/src/views/universalFarms/components/PoolsFilterPanel.tsx
Labels: size/M

#10460 fix: earning chainId
  apps/web/src/hooks/useContract.ts
  apps/web/src/state/farmsV3/hooks.ts
  apps/web/src/views/PoolDetail/components/MyPositions.tsx
  apps/web/src/views/PoolDetail/components/PoolEarnings.tsx
  apps/web/src/views/universalFarms/components/PositionItem/PositionInfo.tsx
  apps/web/src/views/universalFarms/hooks/useCakeEarning.ts
Labels: size/M

#10462 fix: add merkl link
  apps/web/src/views/universalFarms/components/PoolAprButton/PoolAprButton.tsx
Labels: size/XS

#10463 chore: add btcb-kbtc farm
  packages/farms/constants/bsc.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/S

#10298 feat: add onramp notification onboarding / topper fix
  apps/web/src/components/NotificationOnBoardingButton.tsx
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/hooks/useInitNotificationsClient.ts
  apps/web/src/hooks/useInitializeNotifications.ts
  apps/web/src/pages/_app.tsx
  apps/web/src/views/BuyCrypto/components/EnableNotificationTooltip/EnableNotificationsTooltip.tsx
  apps/web/src/views/BuyCrypto/components/Tooltip/Tooltip.tsx
  apps/web/src/views/BuyCrypto/components/TransactionFeeDetails/TransactionFeeDetails.tsx
  apps/web/src/views/BuyCrypto/containers/BuyCryptoForm.tsx
  apps/web/src/views/BuyCrypto/hooks/useDefaultAmount.ts
  apps/web/src/views/BuyCrypto/hooks/useOnRampQuotes.ts
  apps/web/src/views/BuyCrypto/hooks/useOnRampSignature.ts
  apps/web/src/views/BuyCrypto/types.ts
  apps/web/src/views/Notifications/constants.ts
  apps/web/src/views/Notifications/containers/OnBoardingView.tsx
  apps/web/src/views/Notifications/hooks/sendPushNotification.ts
  apps/web/src/views/Notifications/index.tsx
  apps/web/src/views/Notifications/types.ts
  apps/web/src/views/Notifications/utils/textHelpers.ts
  packages/localization/src/config/translations.json
Labels: size/XL

#10465 fix: resolved min/max price
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useExtraV3PositionInfo.ts
  apps/web/src/views/universalFarms/components/PositionItem/PriceRange.tsx
  apps/web/src/views/universalFarms/components/PositionItem/V3PositionItem.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#10467 fix: stake-modal-apr
  apps/web/src/state/farmsV4/state/poolApr/hooks.ts
  apps/web/src/views/Farms/components/FarmCard/StakeAction.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/PoolPositionAprButton.tsx
  apps/web/src/views/universalFarms/components/PositionActions/V2PositionActions.tsx
  apps/web/src/views/universalFarms/components/PositionItem/StablePositionItem.tsx
  apps/web/src/views/universalFarms/components/PositionItem/V2PositionItem.tsx
  packages/widgets-internal/farm/components/DepositModal/index.tsx
Labels: size/M

#10468 fix: teahouse certain vault slippage issue
  apps/web/src/views/PositionManagers/components/RemoveLiquidity.tsx
  apps/web/src/views/PositionManagers/hooks/useOnStake.tsx
  apps/web/src/views/PositionManagers/hooks/usePMSlippage.ts
Labels: Delayed Release, size/M

#10471 chore: Increase api load to 20%
  apps/web/src/config/experimentalFeatures.ts
Labels: size/XS

#10473 chore: remove FeeRefund banner
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/XS

#10451 chore: Bump up nextjs to 14.2.5
  apps/aptos/package.json
  apps/blog/package.json
  apps/bridge/package.json
  apps/games/package.json
  apps/gamification/package.json
  apps/web/package.json
  examples/playground/package.json
  packages/next-config/package.json
  packages/widgets-internal/package.json
  pnpm-lock.yaml
Labels: size/L

#10466 chore: fix decimal input for indonesian rupee
  apps/web/src/views/BuyCrypto/components/OnRampCurrencySelect/index.tsx
  apps/web/src/views/BuyCrypto/constants.ts
  apps/web/src/views/BuyCrypto/containers/BuyCryptoForm.tsx
  apps/web/src/views/BuyCrypto/hooks/useDefaultAmount.ts
Labels: size/M

#10478 fix: v3-roi
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useExtraV3PositionInfo.ts
  apps/web/src/views/universalFarms/components/PoolAprButton/PoolAprButton.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/PoolPositionAprButton.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/V3PoolAprModal.tsx
  packages/widgets-internal/roi/RoiCalculator.tsx
  packages/widgets-internal/roi/hooks/usePriceRange.ts
Labels: size/M

#10483 fix: resolved UI cannot refresh after stake/unstake/harvest a position
  apps/web/src/state/farmsV4/state/accountPositions/atom.ts
  apps/web/src/state/farmsV4/state/accountPositions/fetcher/v3/getAccountV3Positions.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountStableLpDetails.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountV2LpDetails.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountV3Positions.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useLatestTxReceipt.ts
  apps/web/src/views/Farms/hooks/v3/useFarmV3Actions.tsx
  apps/web/src/views/universalFarms/components/PositionActions/V2PositionActions.tsx
  apps/web/src/views/universalFarms/components/PositionActions/V3PositionActions.tsx
Labels: size/M

#10477 chore: add-tooltip-to-usd0-usdt-swell-farm
  apps/web/src/components/SwellTooltip/SwellTooltip.tsx
  apps/web/src/views/Farms/components/CustomTooltips/SwellFarmTooltip.tsx
  apps/web/src/views/Farms/hooks/useHasCustomFarmLpTooltips.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#10485 fix: add poolInfo farming key as ref
  apps/web/src/views/universalFarms/components/PoolAprButton/V3PoolAprModal.tsx
Labels: size/XS

#10491 chore: remove phising fee refund banner
  apps/web/src/components/PhishingWarningBanner/index.tsx
Labels: size/XS

#10492 fix: add v2/ss fee24h
  apps/web/src/state/farmsV4/state/type.ts
  apps/web/src/state/farmsV4/state/utils.ts
  apps/web/src/views/PoolDetail/components/PoolStatus.tsx
Labels: size/M

#10493 feat: add txs filter
  apps/web/src/views/PoolDetail/components/Transactions/TransactionsTable.tsx
  apps/web/src/views/PoolDetail/components/Transactions/styled.ts
  apps/web/src/views/PoolDetail/hooks/usePoolTransactions.ts
Labels: size/S

#10494 fix: v3 total farms
  apps/web/src/views/PoolDetail/components/PoolEarnings.tsx
  apps/web/src/views/universalFarms/hooks/useCakeEarning.ts
Labels: size/M

#10495 fix: add V2 and SS positions in active filter
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountPositionDetailByPool.ts
  apps/web/src/views/Farms/hooks/v3/useFarmV3Actions.tsx
  apps/web/src/views/universalFarms/PositionPage.tsx
  apps/web/src/views/universalFarms/components/Modals/V3StakeModal.tsx
  apps/web/src/views/universalFarms/components/PositionActions/V2PositionActions.tsx
  apps/web/src/views/universalFarms/components/PositionActions/V3PositionActions.tsx
Labels: size/M

#10499 fix: resolved farming fetching data index error
  apps/web/src/state/farmsV4/state/accountPositions/fetcher.ts
Labels: size/M

#10500 fix: Total cost display
  apps/web/src/views/Lottery/components/BuyTicketsModal/BuyTicketsModal.tsx
Labels: size/XS, automerge

#10501 feat: add unstaked farm apr
  apps/web/src/views/universalFarms/components/PoolAprButton/PoolPositionAprButton.tsx
  apps/web/src/views/universalFarms/hooks/useMasterChefV3FarmBoosterAddress.ts
  apps/web/src/views/universalFarms/hooks/useUserMultiplier.ts
Labels: size/M

#10502 feat: V3PoolDerivedAprButton
  apps/web/src/views/AddLiquidityV3/components/AprCalculatorV2.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/PoolPositionAprButton.tsx
Labels: size/L

#10503 fix: lp fee in modal
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useExtraV3PositionInfo.ts
Labels: size/S

#10496 chore: Bump wagmi viem
  .github/workflows/testConfig.yml
  .github/workflows/unitTests.yml
  apps/gamification/config/nodes.ts
  apps/gamification/hooks/useAccountEventListener.ts
  apps/web/src/components/Paymaster/GasTokenSelector.tsx
  apps/web/src/config/nodes.ts
  apps/web/src/hooks/useAccountEventListener.ts
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/hooks/useGaugeRows.ts
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/hooks/useUrlQueryGauge.ts
  package.json
  packages/universal-router-sdk/test/fixtures/constants/chains.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: size/XL

#10506 chore: Bump package manager
  package.json
Labels: size/XS

#10508 fix: resolved ROI checkbox & link
  apps/web/src/views/universalFarms/PositionPage.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/V2PoolAprModal.tsx
  apps/web/src/views/universalFarms/components/PositionItem/PositionInfo.tsx
  apps/web/src/views/universalFarms/components/PositionItem/PositionItem.tsx
  apps/web/src/views/universalFarms/components/StopPropagation.tsx
Labels: size/M

#10464 chore: re-use web notification banner
  apps/web/src/views/Home/components/Banners/WebNotificationBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#10507 chore: add new farms
  packages/farms/constants/base.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/arb.ts
  packages/tokens/src/constants/base.ts
  packages/tokens/src/constants/bsc.ts
  packages/tokens/src/constants/eth.ts
Labels: size/M

#10513 feat: total apr
  apps/web/src/state/farmsV4/state/poolApr/atom.ts
  apps/web/src/state/farmsV4/state/poolApr/fetcher.ts
  apps/web/src/views/PoolDetail/components/MyPositions.tsx
  apps/web/src/views/PoolDetail/components/MyPositionsContext.tsx
  apps/web/src/views/PoolDetail/components/Transactions/TransactionsTable.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/PoolGlobalAprButton.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/PoolPositionAprButton.tsx
  apps/web/src/views/universalFarms/components/PositionItem/PositionInfo.tsx
Labels: size/L
