Repository pancakeswap/pancake-frontend, pull requests merged in 2024-05, with the labels that each got.

#9722 feat: Add tooltip to pm with swell reward
  apps/web/src/config/swell.ts
  apps/web/src/views/PositionManagers/components/CardTitle.tsx
  apps/web/src/views/PositionManagers/components/DuoTokenVaultCard.tsx
  apps/web/src/views/PositionManagers/components/SwellTooltip.tsx
  apps/web/src/views/PositionManagers/components/TableView/index.tsx
  apps/web/src/views/PositionManagers/hooks/useHasSwellReward.ts
  packages/localization/src/config/translations.json
Labels: size/M

#9732 feat: list new arb gauges
  packages/farms/constants/zkSync.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/zkSync.ts
Labels: size/M

#9730 fix: Network switcher not working when wallet is in unsupported chain
  apps/web/src/components/NetworkModal/NetworkModal.tsx
  apps/web/src/components/NetworkSwitcher.tsx
Labels: size/S

#9740 fix: missing publish
  .changeset/rotten-dolls-call.md
Labels: size/XS

#9738 fix: on-ramp provider iframe content
  apps/web/src/components/FiatOnRampModal/ProviderIframe.tsx
Labels: size/XS

#9739 fix: Citizen confirm modal opens empty page for ifo when accepted
  apps/web/src/components/Modal/USCitizenConfirmModal.tsx
Labels: size/XS

#9701 fix: when limit price is zero
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/M

#9729 perf: Use next link to not refresh/load whole site
  apps/aptos/components/Menu/Menu.tsx
  apps/web/src/components/PhishingWarningBanner/Step3.tsx
  apps/web/src/components/TransactionDetailModal/FarmTransactionModal/FarmInfo.tsx
  apps/web/src/views/CakeStaking/components/SyrupPool/LearnMoreLink.tsx
  apps/web/src/views/FarmAuction/index.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3StakeAndUnStake.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/index.tsx
  apps/web/src/views/GaugesVoting/index.tsx
  apps/web/src/views/Home/components/CakeSection/index.tsx
  apps/web/src/views/Home/components/V4CakeIcon.tsx
  apps/web/src/views/Ifos/components/IfoVesting/NotTokens.tsx
  apps/web/src/views/LiquidStaking/constants/FAQs/EthWbethFaq.tsx
  apps/web/src/views/Predictions/Leaderboard/components/Crumbs.tsx
Labels: size/L

#9744 chore: Bump nodejs
  package.json
Labels: size/XS

#9745 chore: Bump usdv widget
  apps/web/package.json
  apps/web/src/global.d.ts
  apps/web/src/pages/usdv.tsx
  pnpm-lock.yaml
Labels: size/L

#9279 chore: support teahouse vault for PM
  apps/web/src/views/PositionManagers/components/CardTitle.tsx
  apps/web/src/views/PositionManagers/components/LiquidityManagement.tsx
  apps/web/src/views/PositionManagers/components/RemoveLiquidity.tsx
  apps/web/src/views/PositionManagers/components/TableView/FarmCell.tsx
  apps/web/src/views/PositionManagers/components/TableView/LiquidityManagement.tsx
  apps/web/src/views/PositionManagers/hooks/useOnStake.tsx
  apps/web/src/views/PositionManagers/utils/strategy.ts
  packages/localization/src/config/translations.json
  packages/position-managers/src/constants/managers.ts
  packages/position-managers/src/constants/supportedChains.ts
  packages/position-managers/src/constants/vaults/bsc.ts
  packages/position-managers/src/constants/vaults/index.ts
  packages/position-managers/src/constants/vaults/linea.ts
  packages/position-managers/src/types.ts
Labels: size/L

#9747 chore: remove unnecessary submenu for Buy
  apps/web/src/components/Menu/config/config.ts
Labels: size/XS

#9754 fix: Unexpected error on liquid staking page
  apps/web/src/views/LiquidStaking/hooks/useExchangeRate.tsx
  apps/web/src/views/LiquidStaking/hooks/useLiquidStakingApr.tsx
Labels: size/XS

#9755 fix: change-ranking-on-buy-crypto-provider-dropdown
  apps/web/src/views/BuyCrypto/components/ProviderSelector/ProviderGroupItem.tsx
  apps/web/src/views/BuyCrypto/components/ProviderSelector/ProviderSelector.tsx
  apps/web/src/views/BuyCrypto/constants.ts
  packages/localization/src/config/translations.json
Labels: size/S

#9756 feat: Update price api sdk for x types
  .changeset/curvy-shoes-train.md
  packages/price-api-sdk/src/orderPriceApiParsers.ts
  packages/price-api-sdk/src/types/api.ts
  packages/price-api-sdk/src/types/index.ts
  packages/price-api-sdk/src/types/order.ts
  packages/price-api-sdk/tsup.config.ts
Labels: size/L

#9757 fix: Duplicate token address
  packages/pools/src/constants/pools/56.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/S

#9762 chore: Update engine requirement
  package.json
Labels: size/XS

#9752 fix: Farm BCakeBoosterCard buttons not clickable on mobile
  apps/web/src/views/Farms/components/YieldBooster/components/bCakeV3/BCakeBoosterCard.tsx
Labels: size/XS

#9741 perf: Memoize bcakev3 info
  apps/web/src/views/Farms/components/YieldBooster/hooks/bCakeV3/useBCakeV3Info.ts
Labels: size/S

#9737 chore: remove repetitive word
  apps/web/src/state/info/queries/tokens/priceData.ts
Labels: size/XS

#9764 fix: empty type
  apps/web/src/utils/getMerklLink.tsx
Labels: size/S

#9678 feat: vecake-status
  apps/web/src/views/CakeStaking/components/CakePoolLockStatus.tsx
  apps/web/src/views/CakeStaking/components/LockedVeCakeStatus.tsx
  apps/web/src/views/CakeStaking/hooks/useVeCakeUserInfo.ts
  packages/localization/src/config/translations.json
Labels: size/L

#9766 chore: bump @binance/w3w-wagmi-connector-v2 version
  apps/gamification/package.json
  apps/web/package.json
  package.json
  pnpm-lock.yaml
Labels: size/XL

#9723 fix: Address count info
  apps/web/src/utils/getTotalTVL.ts
Labels: size/S

#9772 feat: Update participateLink
  apps/web/src/views/Home/components/Banners/MultichainBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/XS

#9776 feat: List solvBtcb-btcb farm
  packages/farms/constants/bsc.ts
Labels: size/XS

#9778 feat: Update Aptos concurrency
  package.json
Labels: size/XS

#9768 perf: remove tooltipVisible state in gauge chart
  apps/web/src/views/GaugesVoting/components/ChartTooltip.tsx
  apps/web/src/views/GaugesVoting/components/WeightsPieChart.tsx
Labels: size/S

#9624 feat: Support harvest card for other chains
  apps/web/src/hooks/useVaultApy.ts
  apps/web/src/pages/v2/pair/[[...currency]].tsx
  apps/web/src/state/farms/fetchFarmUser.ts
  apps/web/src/state/farms/fetchMasterChefData.ts
  apps/web/src/state/farms/hooks.ts
  apps/web/src/utils/addressHelpers.ts
  apps/web/src/utils/calls/farms.ts
  apps/web/src/utils/contractHelpers.ts
  apps/web/src/views/CakeStaking/hooks/useAPR.ts
  apps/web/src/views/Farms/components/YieldBooster/hooks/useBoostMultiplier.ts
  apps/web/src/views/Farms/hooks/useApproveFarm.ts
  apps/web/src/views/Home/components/Banners/hooks/useIsRenderUserBanner.ts
  apps/web/src/views/Home/components/UserBanner/HarvestCard.tsx
  apps/web/src/views/Home/hooks/useCakeEmissionPerBlock.tsx
  apps/web/src/views/Home/hooks/useFarmsWithBalance.tsx
Labels: size/L

#9792 chore: Fast routing default on
  apps/web/src/config/experimentalFeatures.ts
Labels: size/XS

#9660 chore: Bump nextjs 14
  apps/aptos/components/Farms/components/FarmTable/FarmTable.tsx
  apps/aptos/next.config.mjs
  apps/aptos/package.json
  apps/blog/next.config.mjs
  apps/blog/package.json
  apps/bridge/components/layerZero/index.tsx
  apps/bridge/next.config.mjs
  apps/bridge/package.json
  apps/bridge/pages/_app.tsx
  apps/bridge/utils/whenDefinedPolyfill.ts
  apps/games/next.config.mjs
  apps/games/package.json
  apps/gamification/next.config.mjs
  apps/gamification/package.json
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/src/pages/_app.tsx
  apps/web/src/views/CakeStaking/components/BenefitCard.tsx
  examples/playground/package.json
  packages/next-config/package.json
  packages/widgets-internal/package.json
  pnpm-lock.yaml
Labels: size/L

#9793 perf: Countdown dynamic style
  apps/web/src/components/PhishingWarningBanner/Countdown.tsx
Labels: size/S

#9794 feat: List farm
  packages/farms/constants/bsc.ts
Labels: size/S

#9799 chore: Universal router roll out
  apps/web/src/config/experimentalFeatures.ts
Labels: size/XS

#9771 feat: sync onramp api and add inverted quotes on FE
  apps/web/src/components/FiatOnRampModal/FiatOnRampModal.tsx
  apps/web/src/components/SearchModal/OnRampCurrencyModal.tsx
  apps/web/src/state/buyCrypto/actions.ts
  apps/web/src/state/buyCrypto/hooks.ts
  apps/web/src/state/buyCrypto/reducer.ts
  apps/web/src/views/BuyCrypto/components/OnRampCurrencySelect/index.tsx
  apps/web/src/views/BuyCrypto/constants.ts
  apps/web/src/views/BuyCrypto/containers/BuyCryptoForm.tsx
  apps/web/src/views/BuyCrypto/hooks/useBitcoinAddressValidator.ts
  apps/web/src/views/BuyCrypto/hooks/useDefaultAmount.ts
  apps/web/src/views/BuyCrypto/hooks/useIsBtc.ts
  apps/web/src/views/BuyCrypto/hooks/useOnRampCurrencyOrder.ts
  apps/web/src/views/BuyCrypto/hooks/useOnRampInputError.ts
  apps/web/src/views/BuyCrypto/hooks/useOnRampQuotes.ts
  apps/web/src/views/BuyCrypto/hooks/useOnRampSignature.ts
  apps/web/src/views/BuyCrypto/types.ts
Labels: Delayed Release, size/XL

#9800 feat: fee saved display
  apps/web/src/views/Swap/components/AdvancedSwapDetails.tsx
  apps/web/src/views/Swap/hooks/useFeeSaved.ts
  packages/localization/src/config/translations.json
  packages/tokens/src/constants/common.ts
Labels: size/L

#9805 fix: remove undefined key of stablecoin
  apps/web/src/views/Swap/hooks/useFeeSaved.ts
Labels: size/S

#9807 feat: update ifo docs link
  apps/web/src/views/Ifos/components/IfoContainer.tsx
Labels: size/XS

#9809 fix: move preflight check before first step
  apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalStateV2.ts
Labels: size/M

#9801 fix: Farms inactive lists are wrong
  apps/web/src/views/Farms/FarmsV3.tsx
Labels: size/XS

#9810 chore: Disable swc minify
  apps/web/next.config.mjs
Labels: size/XS

#9811 fix: V2 inactive farms
  apps/web/src/views/Farms/FarmsV3.tsx
Labels: size/XS

#9812 feat: new-gauges
  packages/farms/constants/bsc.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/M

#9813 chore: Remove masa banner
  apps/web/src/components/PhishingWarningBanner/Step3.tsx
  apps/web/src/components/PhishingWarningBanner/index.tsx
  apps/web/src/views/Home/components/Banners/MasaTCBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#9816 chore: fix some typos in comments
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/StepCounter.tsx
  packages/hooks/src/useIntersectionObserver.ts
  packages/widgets-internal/roi/StepCounter.tsx
Labels: size/XS

#9822 feat: add native unlock
  apps/web/src/views/CakeStaking/components/LockedVeCakeStatus.tsx
Labels: size/M

#9821 feat: add usd price fallback
  apps/web/src/views/Swap/hooks/useFeeSaved.ts
Labels: size/S

#9824 feat: add FeeRefund Banner
  apps/web/src/views/Home/components/Banners/FeeRefundBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#9825 fix: bg link
  apps/web/src/views/Home/components/Banners/FeeRefundBanner.tsx
Labels: size/XS

#9833 feat: list solvbtc syrup
  apps/web/src/config/__tests__/pools.test.ts
  packages/pools/src/constants/pools/56.ts
Labels: size/S

#9826 fix: opaque background on mercuryo logo
  apps/web/src/views/BuyCrypto/components/OnRampProviderLogo/OnRampProviderLogo.tsx
  apps/web/src/views/BuyCrypto/constants.ts
  apps/web/src/views/BuyCrypto/styles.tsx
Labels: size/M

#9830 fix: undefined default state rest bug on buy crypto iframe dismiss
  apps/web/src/views/BuyCrypto/containers/BuyCryptoForm.tsx
Labels: size/S

#9835 fix: Remove replace from links
  apps/web/src/components/TransactionDetailModal/FarmTransactionModal/FarmInfo.tsx
  apps/web/src/views/CakeStaking/components/SyrupPool/LearnMoreLink.tsx
  apps/web/src/views/FarmAuction/index.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3StakeAndUnStake.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/index.tsx
  apps/web/src/views/GaugesVoting/index.tsx
  apps/web/src/views/Home/components/CakeSection/index.tsx
  apps/web/src/views/Home/components/V4CakeIcon.tsx
  apps/web/src/views/Ifos/components/IfoCardStyles.tsx
  apps/web/src/views/Ifos/components/IfoVesting/NotTokens.tsx
  apps/web/src/views/LiquidStaking/constants/FAQs/EthWbethFaq.tsx
  apps/web/src/views/Predictions/Leaderboard/components/Crumbs.tsx
Labels: size/L

#9838 chore: Polygon zkevm subgraph migration
  .changeset/forty-oranges-tap.md
  packages/chains/src/subgraphs.ts
Labels: size/XS

#9831 fix: remove cdn script for mercuryo for url
  apps/web/src/components/FiatOnRampModal/FiatOnRampModal.tsx
  apps/web/src/components/FiatOnRampModal/ProviderIframe.tsx
Labels: size/L

#9844 chore: Replace with studio endpoints
  .changeset/good-days-sip.md
  apps/web/src/config/constants/endpoints.ts
  packages/chains/src/subgraphs.ts
Labels: size/S

#9852 fix: magic token name
  .changeset/heavy-bulldogs-teach.md
  packages/tokens/src/constants/arb.ts
Labels: size/XS

#9840 feat: universal router swap code cleanup
  apps/web/src/config/experimentalFeatures.ts
  apps/web/src/pages/api/vercel/flags.ts
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButton.tsx
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButtonV2.tsx
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMConfirmModalState.ts
  apps/web/src/views/Swap/V3Swap/containers/ApproveStepFlow.tsx
  apps/web/src/views/Swap/V3Swap/containers/ApproveStepFlowV2.tsx
  apps/web/src/views/Swap/V3Swap/containers/CommitButton.tsx
  apps/web/src/views/Swap/V3Swap/containers/ConfirmSwapModal.tsx
  apps/web/src/views/Swap/V3Swap/containers/ConfirmSwapModalV2.tsx
  apps/web/src/views/Swap/V3Swap/containers/MMCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/containers/MMCommitButtonV2.tsx
  apps/web/src/views/Swap/V3Swap/containers/SwapCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/containers/SwapCommitButtonV2.tsx
  apps/web/src/views/Swap/V3Swap/containers/index.ts
  apps/web/src/views/Swap/V3Swap/hooks/index.ts
  apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalState.ts
  apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalStateV2.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSwapCallArguments.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSwapCallArgumentsV2.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSwapCallback.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSwapCallbackV2.ts
  apps/web/src/views/Swap/V3Swap/hooks/useWallchain.ts
  apps/web/src/views/Swap/V3Swap/index.tsx
  packages/localization/src/config/translations.json
Labels: size/XXL

#9855 chore: add native usdc on zksync
  .changeset/neat-colts-remain.md
  apps/web/src/config/constants/tokenLists/pancake-default.tokenlist.json
  packages/tokens/src/constants/common.ts
  packages/tokens/src/constants/zkSync.ts
Labels: size/M

#9859 fix: Nft subgraph indicator shows Down initially
  apps/web/src/components/SubgraphHealthIndicator/FixedSubgraphHealthIndicator.tsx
  apps/web/src/components/SubgraphHealthIndicator/FloatingSubgraphHealthIndicators.tsx
  apps/web/src/components/SubgraphHealthIndicator/SubgraphHealthIndicator.tsx
  apps/web/src/hooks/useSubgraphHealth.ts
  apps/web/src/utils/viem.ts
  apps/web/src/views/AffiliatesProgram/hooks/useShowWarningMessage.tsx
  apps/web/src/views/LimitOrders/components/LimitOrderTable/TableNavigation.tsx
  apps/web/src/views/Pottery/components/Pot/Claim/index.tsx
  apps/web/src/views/Pottery/index.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TopTradersCard/index.tsx
  apps/web/src/views/TradingCompetition/components/YourScore/ScoreCard.tsx
Labels: size/M

#9857 chore: add zkSync native usdc to common tokens list
  apps/web/src/config/constants/exchange.ts
Labels: size/XS

#9858 feat: swell tooltip for farms and update for position managers
  apps/web/src/components/SwellTooltip/SwellTooltip.tsx
  apps/web/src/config/swell.ts
  apps/web/src/hooks/useHasSwellReward.ts
  apps/web/src/views/Farms/components/FarmCard/CardHeading.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3Card.tsx
  apps/web/src/views/Farms/components/FarmTable/Farm.tsx
  apps/web/src/views/PositionManagers/components/DuoTokenVaultCard.tsx
  apps/web/src/views/PositionManagers/components/TableView/index.tsx
  apps/web/src/views/PositionManagers/hooks/useHasSwellReward.ts
Labels: size/M

#9863 feat: add lint for page router
  apps/aptos/.eslintrc
  apps/blog/.eslintrc
  apps/bridge/.eslintrc
  apps/web/.eslintrc
  packages/eslint-config/lib/next-page-router.js
Labels: size/S

#9753 feat: gauges url query
  apps/web/package.json
  apps/web/src/views/CakeStaking/hooks/useProxyVeCakeBalance.ts
  apps/web/src/views/CakeStaking/hooks/useProxyVeCakeBalanceOfAtTime.ts
  apps/web/src/views/GaugesVoting/components/GaugesFilter/FilterFieldInput.tsx
  apps/web/src/views/GaugesVoting/components/MyVeCakeBalance.tsx
  apps/web/src/views/GaugesVoting/components/RemainingVotePower.tsx
  apps/web/src/views/GaugesVoting/components/Table/AddGauge/AddGaugeModal.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/List.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/TableRow.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/hooks/useGaugeRows.ts
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/hooks/useRowVoteState.ts
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/hooks/useUrlQueryGauge.ts
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/index.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/types.ts
  apps/web/src/views/GaugesVoting/components/WeightsPieChart.tsx
  apps/web/src/views/GaugesVoting/hooks/useEpochVotePower.ts
  apps/web/src/views/GaugesVoting/hooks/useGaugesFilter.ts
  apps/web/src/views/GaugesVoting/hooks/useUserVote.ts
  apps/web/src/views/GaugesVoting/hooks/useUserVoteGauges.ts
  apps/web/src/views/GaugesVoting/index.tsx
  packages/localization/src/config/translations.json
  pnpm-lock.yaml
Labels: size/XL

#9864 feat: add FURY on bsc, five farms and gauges
  .changeset/ninety-weeks-smell.md
  packages/farms/constants/bsc.ts
  packages/farms/constants/zkSync.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/L

#9869 feat: add MNT & mETH tokens, farms and gauges
  .changeset/tasty-cycles-behave.md
  packages/farms/constants/eth.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/eth.ts
Labels: size/M

#9870 feat: add ONEPUNCH token on Linea
  .changeset/eight-birds-heal.md
  packages/tokens/src/constants/linea.ts
Labels: size/S

#9871 chore: update bribe tooltip, remove aptos reward farm
  apps/aptos/config/constants/aptRewardFarm/1.ts
  apps/web/src/views/CakeStaking/components/DataSet/TotalApy.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#9874 fix: Eslint warnings
  apps/web/src/components/Modal/USCitizenConfirmModal.tsx
  apps/web/src/pages/usdv.tsx
  apps/web/src/state/limitOrders/hooks.ts
  apps/web/src/views/AffiliatesProgram/hooks/useShowWarningMessage.tsx
  apps/web/src/views/BuyCrypto/hooks/useOnRampSignature.ts
  apps/web/src/views/CakeStaking/components/DataSet/TotalApy.tsx
  apps/web/src/views/Farms/components/FarmCard/StakeAction.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/hooks/useRowVoteState.ts
  apps/web/src/views/Home/components/Banners/hooks/useIsRenderUserBanner.ts
  apps/web/src/views/Ifos/CurrentIfo.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoVestingCard/TotalAvailableClaim.tsx
  apps/web/src/views/Migration/components/bCake/PMRow.tsx
  apps/web/src/views/Migration/components/bCake/UnstakeButton.tsx
  apps/web/src/views/PositionManagers/hooks/useOnStake.tsx
  packages/eslint-config/lib/next-page-router.js
  packages/universal-router-sdk/test/trade.test.ts
Labels: size/M

#9865 perf: Reduce graphql requests in farms page
  apps/web/src/__tests__/views/info/utils/infoData.test.ts
  apps/web/src/hooks/useBCakeProxyContractAddress.ts
  apps/web/src/hooks/usePoolAvgInfo.ts
  apps/web/src/hooks/v3/useAllV3TicksQuery.ts
  apps/web/src/hooks/v3/usePoolTickData.ts
  apps/web/src/state/farms/hooks.ts
  apps/web/src/state/farms/types.ts
  apps/web/src/state/info/queries/pools/poolData.ts
  apps/web/src/state/info/queries/protocol/overview.ts
  apps/web/src/state/info/queries/tokens/priceData.ts
  apps/web/src/state/info/queries/tokens/tokenData.ts
  apps/web/src/state/swap/fetch/fetchDerivedPriceData.ts
  apps/web/src/utils/getBlocksFromTimestamps.ts
  apps/web/src/utils/getChangeForPeriod.ts
  apps/web/src/utils/infoDataHelpers.ts
  apps/web/src/utils/infoQueryHelpers.ts
  apps/web/src/views/Farms/FarmsV3.tsx
  apps/web/src/views/Farms/components/BCakeMigrateModal.tsx
  apps/web/src/views/Farms/components/FarmCard/ApyButton.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3ApyButton.tsx
  apps/web/src/views/Farms/components/YieldBooster/hooks/useProxyCAKEBalance.ts
  apps/web/src/views/Farms/components/YieldBooster/hooks/useProxyStakedActions.ts
  apps/web/src/views/Farms/components/YieldBooster/hooks/useYieldBoosterState.ts
  apps/web/src/views/Farms/context.ts
  apps/web/src/views/Farms/hooks/useBCakeProxyBalance.ts
  apps/web/src/views/Farms/utils/getStakedFarms.ts
  apps/web/src/views/Home/hooks/useFarmsWithBalance.tsx
  apps/web/src/views/Migration/components/v3/Step5.tsx
  apps/web/src/views/V3Info/data/token/tokenData.ts
  doc/Info.md
Labels: size/L

#9880 chore: Remove unused imports
  apps/web/src/hooks/useContract.ts
  apps/web/src/views/Farms/components/FarmCard/StakeAction.tsx
  apps/web/src/views/Migration/components/bCake/UnstakeButton.tsx
  apps/web/src/views/PositionManagers/components/TableView/index.tsx
  apps/web/src/views/PositionManagers/containers/PCSVaultCard.tsx
Labels: size/S

#9879 chore: list new farms and gauges
  packages/farms/constants/eth.ts
  packages/gauges/src/constants/config/prod.ts
Labels: size/S

#9890 chore: list syrup pool on BSC
  packages/pools/src/constants/pools/56.ts
Labels: size/XS

#9898 fix: ignore expired proxy vote
  apps/web/src/views/GaugesVoting/hooks/useUserVote.ts
Labels: size/XS

#9889 chore: fix some comments
  packages/smart-router/evm/v3-router/gasModel.ts
  packages/smart-router/evm/v3-router/utils/pool.ts
Labels: size/XS

#9886 fix: Use sg indicator the places where it is used
  apps/web/src/pages/liquidity/index.tsx
  apps/web/src/views/Pools/index.tsx
  apps/web/src/views/PositionManagers/index.tsx
  apps/web/src/views/Predictions/Leaderboard/index.tsx
  apps/web/src/views/Predictions/index.tsx
Labels: size/XS

#9885 fix: Staked tooltip updated text add missing plugin extends
  apps/web/src/views/CakeStaking/components/CakePoolLockStatus.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/List.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/TableRow.tsx
  apps/web/src/views/V3Info/components/BarChart/alt.tsx
  apps/web/src/views/V3Info/components/BarChart/index.tsx
  apps/web/src/views/V3Info/components/LineChart/alt.tsx
  apps/web/src/views/V3Info/components/LineChart/index.tsx
  apps/web/src/views/V3Info/data/pool/chartData.ts
  apps/web/src/views/V3Info/data/protocol/chart.ts
  apps/web/src/views/V3Info/data/token/chartData.ts
  apps/web/src/views/V3Info/data/token/priceData.ts
  apps/web/src/views/V3Info/hooks/chart.ts
  packages/localization/src/config/translations.json
  packages/utils/formatTimestamp.ts
  packages/widgets-internal/farm/components/FarmTable/Liquidity.tsx
Labels: size/M

#9902 chore: The graph migration for api endpoints
  apis/farms/src/bindings.d.ts
  apis/farms/src/lpApr.ts
  apis/farms/src/provider.ts
  apis/farms/src/v3.ts
  apis/farms/wrangler.toml
  apis/routing/src/bindings.d.ts
  apis/routing/src/provider.ts
  apis/routing/wrangler.toml
Labels: size/S

#9900 feat: Add Achievements packages
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/src/config/__tests__/campaigns.test.ts
  apps/web/src/config/__tests__/ifo.test.ts
  apps/web/src/config/constants/types.ts
  apps/web/src/state/achievements/helpers.ts
  apps/web/src/utils/achievements.ts
  packages/achievements/index.tsx
  packages/achievements/package.json
  packages/achievements/src/campaigns.ts
  packages/achievements/src/index.tsx
  packages/achievements/src/types.ts
  packages/achievements/tsconfig.json
  packages/achievements/vitest.config.ts
  pnpm-lock.yaml
Labels: size/L

#9904 chore: list new farms and gauges on ARB
  packages/farms/constants/arb.ts
  packages/gauges/src/constants/config/prod.ts
Labels: size/M
