Repository pancakeswap/pancake-frontend, pull requests merged in 2024-12, with the labels that each got.

#10991 chore: update ads asset url
  apps/web/src/components/AdPanel/Ads/AdCakeStaking.tsx
  apps/web/src/components/AdPanel/Ads/AdMevProtection.tsx
  apps/web/src/components/AdPanel/Ads/AdOptionsTrading.tsx
  apps/web/src/components/AdPanel/Ads/AdPCSX.tsx
  apps/web/src/components/AdPanel/Ads/AdQuests.tsx
  apps/web/src/components/AdPanel/Ads/AdRocker.tsx
  apps/web/src/components/AdPanel/Ads/AdTelegramBot.tsx
  apps/web/src/components/AdPanel/Ads/AdV4.tsx
  apps/web/src/components/AdPanel/Card.tsx
  apps/web/src/components/AdPanel/FAQ/config/buyCrypto.tsx
  apps/web/src/components/AdPanel/FAQ/config/prediction.ts
  apps/web/src/components/AdPanel/FAQ/config/swap.tsx
  apps/web/src/components/AdPanel/utils.ts
Labels: size/M

#10977 fix: Legacy Farm Page Staked Liquidity
  apps/web/next.config.mjs
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/state/farmsV3/hooks.ts
Labels: size/M

#10969 fix: Vecake rewards claim
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/config/abi/revenueSharingPoolGateway.ts
  apps/web/src/config/constants/contracts.ts
  apps/web/src/state/block/hooks.ts
  apps/web/src/views/CakeStaking/components/CakeRewardsCard.tsx
  apps/web/src/views/CakeStaking/config.ts
  apps/web/src/views/CakeStaking/hooks/useCurrentBlockTimestamp.ts
  apps/web/src/views/CakeStaking/hooks/useRevenueSharingProxy.ts
  packages/wagmi/src/hooks/useBlock.ts
Labels: size/L

#10998 fix: Network switch in swap
  apps/web/src/components/NetworkModal/WrongNetworkModal.tsx
  apps/web/src/components/NetworkSwitcher.tsx
  apps/web/src/hooks/useActiveChainId.ts
  apps/web/src/hooks/useSwitchNetwork.ts
Labels: size/M

#11002 fix: Warnings and dependency of select hook of overridden initial timestamp
  apps/web/src/state/block/hooks.ts
  apps/web/src/views/CakeStaking/components/CakeRewardsCard.tsx
  apps/web/src/views/CakeStaking/hooks/useCurrentBlockTimestamp.ts
  apps/web/src/views/Home/components/Banners/NewIFOBanner.tsx
  apps/web/src/views/ProfileCreation/Header.tsx
  apps/web/src/views/SwapSimplify/V4Swap/FlipButton.tsx
Labels: size/S

#11000 feat: Update gauges contract address
  .changeset/four-dryers-fry.md
  packages/gauges/src/constants/address.ts
Labels: size/XS

#10996 fix: Coinbase wallet popup
  apps/web/next.config.mjs
  apps/web/src/views/universalFarms/components/PositionActions/StakeActions.tsx
  packages/ui-wallets/src/WalletModal.tsx
  packages/widgets-internal/components/ExternalCurrencyLink/index.tsx
Labels: size/S

#11001 feat: Update changeset
  .changeset/famous-gifts-shop.md
  .changeset/gentle-paws-fry.md
  .changeset/metal-forks-draw.md
Labels: size/S

#11004 chore: add new springboard submenu
  apps/web/src/components/Menu/config/config.ts
  package.json
  packages/localization/src/config/translations.json
Labels: size/S

#11006 chore: update pnpm version for git action
  .github/actions/install-deps/action.yml
Labels: size/XS

#11008 chore: add springboard ad
  apps/web/src/components/AdPanel/Ads/AdSpringboard.tsx
  apps/web/src/components/AdPanel/config.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#11005 chore: add flip currency arrow animation
  apps/web/public/images/swap/Arrow_Lottie.json
  apps/web/public/images/swap/arrow_dark.json
  apps/web/public/images/swap/arrow_light.json
  apps/web/src/views/SwapSimplify/V4Swap/FlipButton.tsx
Labels: size/XXL

#10989 chore: mev-rpc-related-improvements
  apps/web/src/views/Mev/AddMevRpcButton.tsx
  apps/web/src/views/Mev/MevSwapDetail.tsx
  apps/web/src/views/Mev/hooks/index.ts
Labels: size/L

#11013 fix: Smart router unable to get quote for wrapped native
  .changeset/unlucky-dots-behave.md
  packages/smart-router/evm/v3-router/gasModel.ts
Labels: size/S

#11011 fix: Throw error to retry query
  packages/awgmi/core/src/view/fetchAptosView.ts
Labels: size/XS

#11015 feat: Update token name
  packages/tokens/src/constants/base.ts
Labels: size/XS

#11016 fix: Wallet switch chain issue
  apps/gamification/state/multicall/fetchChunk.ts
  apps/web/src/hooks/useAccountEventListener.ts
  apps/web/src/hooks/useAccountLocalEventListener.ts
  apps/web/src/state/multicall/fetchChunk.ts
  apps/web/src/utils/mevGuardChains.ts
  apps/web/src/views/Mev/hooks/index.ts
Labels: size/L

#11027 feat: add-new-calc-sc
  .changeset/dry-goats-shop.md
  packages/gauges/src/constants/address.ts
Labels: size/XS

#11022 feat: simple staking sunset modal
  apps/web/src/components/CustomTrans/index.ts
  apps/web/src/components/Modal/AffiliateExpiredModal.tsx
  apps/web/src/components/Modal/AffiliateSunsetModal.tsx
  apps/web/src/components/Modal/SimpleStakingSunsetModal.tsx
  apps/web/src/pages/_app.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#11032 fix: 🐛 Change blog link
  apps/web/src/components/Modal/SimpleStakingSunsetModal.tsx
Labels: size/XS

#11025 fix: Account position details not shown if chain doesn't have stable pairs
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountPositionDetailByPool.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useStableSwapPairsByChainId.ts
  apps/web/src/views/PoolDetail/components/PoolStatus.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/V2PoolAprModal.tsx
Labels: size/L

#11030 fix: update calc gauges address
  packages/gauges/src/constants/address.ts
Labels: size/XS

#11020 fix: 🐛 fix build errors cause by conflict pkg ver
  apps/aptos/package.json
  apps/blog/package.json
  apps/bridge/package.json
  apps/games/package.json
  apps/gamification/package.json
  apps/ton/package.json
  apps/web/package.json
  examples/playground/package.json
  packages/awgmi/package.json
  packages/localization/package.json
  packages/token-lists/package.json
  packages/ui-wallets/package.json
  packages/uikit/package.json
  packages/wagmi/package.json
  packages/widgets-internal/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: size/XXL

#11038 fix: video loaded issue on home page
  apps/web/src/views/Home/components/Hero.tsx
  apps/web/src/views/Home/hooks/useDrawCanvas.ts
Labels: size/M

#11039 chore: add empty app folder
  apps/ton/README.md
Labels: size/XS

#11040 chore: Update tradingview integrity hash
  apps/web/src/components/TradingView.tsx
Labels: size/XS

#11037 perf: Memoize mev rpc callbacks
  apps/web/src/views/Mev/AddMevRpcButton.tsx
Labels: size/S

#11044 chore: update ad panel image path
  apps/web/src/components/AdPanel/FAQ/config/prediction.ts
Labels: size/XS

#11024 feat: Remove USDV
  .changeset/soft-starfishes-own.md
  apps/web/package.json
  apps/web/src/components/SearchModal/CurrencySearch.tsx
  apps/web/src/hooks/useUsdvMintAvailable.ts
  apps/web/src/pages/usdv.tsx
  apps/web/src/views/LiquidStaking/components/StakeInfo/index.tsx
  packages/localization/src/config/translations.json
  packages/widgets-internal/index.ts
  pnpm-lock.yaml
Labels: size/XL

#11045 fix: storybook icon issue
  packages/uikit/src/components/Svg/Icons/RiskAlert.tsx
  packages/uikit/src/components/Svg/Icons/ShieldIcon.tsx
  packages/uikit/src/components/Svg/Icons/WalletFilledV2.tsx
  packages/uikit/src/components/Svg/index.tsx
Labels: size/S

#10908 chore: reset sponsored txns on ZKSync
  apps/web/src/components/Paymaster/GasTokenSelector.tsx
  apps/web/src/config/paymaster.ts
  apps/web/src/pages/api/paymaster/index.ts
  apps/web/src/views/Swap/V3Swap/components/SwapModalFooterV2.tsx
  apps/web/src/views/Swap/V3Swap/containers/TradeDetails.tsx
  apps/web/src/views/SwapSimplify/V4Swap/AdvancedSwapDetails.tsx
  apps/web/src/views/SwapSimplify/V4Swap/ButtonAndDetailsPanel.tsx
  apps/web/src/views/SwapSimplify/V4Swap/TradeDetails.tsx
  apps/web/src/views/SwapSimplify/V4Swap/index.tsx
Labels: size/L

#11048 feat: Read contract value in ton
  apps/ton/.eslintrc
  apps/ton/package.json
  apps/ton/src/atoms/ton.types.ts
  apps/ton/src/components/Providers.tsx
  apps/ton/src/components/connector/TonConnector.tsx
  apps/ton/src/pages/_app.tsx
  apps/ton/src/pages/test/index.tsx
  apps/ton/src/ton/atom/addressAtom.ts
  apps/ton/src/ton/atom/contractAtom.ts
  apps/ton/src/ton/atom/contractOfTypeAtom.ts
  apps/ton/src/ton/atom/isConnectedAtom.ts
  apps/ton/src/ton/atom/tonStateAtom.ts
  apps/ton/src/ton/context/ContractProxy.ts
  apps/ton/src/ton/context/TonContext.ts
  apps/ton/src/ton/context/endpoints.ts
  apps/ton/src/ton/def/contractClass.def.ts
  apps/ton/src/ton/def/contracts.def.ts
  apps/ton/src/ton/def/function.def.ts
  apps/ton/src/ton/generateQueryId.ts
  apps/ton/src/ton/logic/balanceOfAtom.ts
  apps/ton/src/ton/logic/balanceOfJettonAtom.ts
  apps/ton/src/ton/logic/balanceOfNativeAtom.ts
  apps/ton/src/ton/logic/jettonWalletOfAtom.ts
  apps/ton/src/ton/opcodes.ts
  apps/ton/src/ton/react/TonContextProvider.tsx
  apps/ton/src/ton/ton.enums.ts
  apps/ton/src/ton/ton.types.ts
  apps/ton/src/ton/utils/Emiter.ts
  apps/ton/src/ton/utils/Logger.ts
  pnpm-lock.yaml
Labels: size/XXL

#11049 chore: empty nextjs project
  apps/ton/.gitignore
  apps/ton/README.md
  apps/ton/next.config.mjs
  apps/ton/package.json
  apps/ton/public/favicon.ico
  apps/ton/src/pages/_app.tsx
  apps/ton/src/pages/_document.tsx
  apps/ton/src/pages/api/hello.ts
  apps/ton/src/pages/fonts/GeistMonoVF.woff
  apps/ton/src/pages/fonts/GeistVF.woff
  apps/ton/src/pages/index.tsx
  apps/ton/src/styles/Home.module.css
  apps/ton/src/styles/globals.css
  apps/ton/tsconfig.json
  pnpm-lock.yaml
Labels: size/XXL

#11047 chore: Use general download links for wallets to cover all browsers
  apps/web/src/config/wallet.ts
Labels: size/XS

#11055 fix: Liquidity chart not visible on some pools
  apps/web/src/hooks/useV3Pools.ts
  apps/web/src/hooks/v3/useAllV3TicksQuery.ts
  apps/web/src/hooks/v3/usePoolTickData.ts
  apps/web/src/utils/getActiveTick.ts
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3ApyButton.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/V3PoolAprModal.tsx
Labels: size/L

#11060 chore: Increase max chunk retries to 5
  apps/aptos/next.config.mjs
  apps/blog/next.config.mjs
  apps/bridge/next.config.mjs
  apps/games/next.config.mjs
  apps/gamification/next.config.mjs
  apps/web/next.config.mjs
Labels: size/S

#11063 fix: Theme switch issue
  apps/ton/package.json
  pnpm-lock.yaml
Labels: size/L

#11052 chore: Change pagination bullet color in adpanel to make it visible
  apps/web/src/components/AdPanel/CardLayouts.tsx
  apps/web/src/components/AdPanel/CarrouselWithSlider.tsx
  apps/web/src/components/AdPanel/config.tsx
Labels: size/L

#11010 feat: 🎸 Try to optimize the build speed
  apps/web/next.config.mjs
Labels: size/XS

#11067 fix: 🐛 Fix Arguments passing order of usePoolTickData
  apps/web/src/hooks/v3/usePoolTickData.ts
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3ApyButton.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/V3PoolAprModal.tsx
Labels: size/M

#11034 feat: Add PCS bridge
  apps/bridge/components/Menu.tsx
  apps/web/package.json
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/pages/bridge/index.tsx
  packages/canonical-bridge/package.json
  packages/canonical-bridge/src/components/RefreshingIcon.tsx
  packages/canonical-bridge/src/components/V1BridgeLink.tsx
  packages/canonical-bridge/src/components/icons/ExternalLinkIcon.tsx
  packages/canonical-bridge/src/configs/chains.ts
  packages/canonical-bridge/src/configs/env.ts
  packages/canonical-bridge/src/configs/index.ts
  packages/canonical-bridge/src/hooks/useTransferConfig.ts
  packages/canonical-bridge/src/index.ts
  packages/canonical-bridge/src/modules/i18n/locales/en.ts
  packages/canonical-bridge/src/modules/i18n/locales/index.ts
  packages/canonical-bridge/src/modules/wallet/BridgeWalletProvider.tsx
  packages/canonical-bridge/src/theme/breakpoints.ts
  packages/canonical-bridge/src/theme/dark.ts
  packages/canonical-bridge/src/theme/light.ts
  packages/canonical-bridge/src/token-config/mainnet/cBridge/config.json
  packages/canonical-bridge/src/token-config/mainnet/chains.ts
  packages/canonical-bridge/src/token-config/mainnet/layerZero/config.json
  packages/canonical-bridge/src/token-config/mainnet/meson/config.json
  packages/canonical-bridge/src/token-config/mainnet/stargate/config.json
  packages/canonical-bridge/src/views/GlobalStyle/index.ts
  packages/canonical-bridge/src/views/index.tsx
  packages/canonical-bridge/tsconfig.json
  packages/canonical-bridge/vite.config.ts
  packages/canonical-bridge/vitest.config.ts
  packages/hooks/package.json
  packages/uikit/package.json
  pnpm-lock.yaml
Labels: size/XXL

#11059 feat: 🎸 Add currency type
  packages/routing-sdk/addons/ton/package.json
  packages/routing-sdk/addons/ton/src/Jetton.ts
  packages/routing-sdk/addons/ton/src/currency.ts
  packages/routing-sdk/addons/ton/src/index.test.ts
  packages/routing-sdk/addons/ton/src/index.ts
  packages/routing-sdk/addons/ton/tsconfig.json
  packages/routing-sdk/addons/ton/tsup.config.ts
  packages/routing-sdk/addons/ton/vitest.config.ts
  packages/utils/package.json
  pnpm-lock.yaml
Labels: size/XL

#11069 fix: Switch theme issue deps
  packages/hooks/package.json
  packages/uikit/package.json
  pnpm-lock.yaml
Labels: size/XXL

#11070 fix: bridge menu on mobile
  apps/web/src/components/Menu/config/config.ts
  packages/localization/src/config/translations.json
Labels: size/M

#11072 chore: update evm url on bridge
  apps/bridge/components/Menu.tsx
Labels: size/XS

#11073 chore: inject rpc for bridge package
  apps/web/src/pages/bridge/index.tsx
  packages/canonical-bridge/src/views/index.tsx
Labels: size/S

#11061 fix: mev toggle display logic
  apps/web/src/views/Mev/hooks/index.ts
Labels: size/S

#11076 fix: Fix pcs bridge layerzero decimal issue
  packages/canonical-bridge/package.json
  pnpm-lock.yaml
Labels: size/L

#11077 chore: update meta title and og image for bridge
  apps/web/src/config/constants/meta.ts
Labels: size/XS

#11079 fix(canonical-bridge): Remove stargate
  packages/canonical-bridge/src/hooks/useTransferConfig.ts
Labels: size/S

#11085 revert: fix(canonical-bridge): Remove stargate
  packages/canonical-bridge/src/hooks/useTransferConfig.ts
Labels: size/S

#11084 fix: Farm symbol
  .changeset/five-onions-beam.md
  packages/tokens/src/constants/arb.ts
  packages/tokens/src/constants/base.ts
Labels: size/S

#10291 feat: Add cancel order component to deprecated limit orders
  apps/web/src/config/abi/gelatoLimit.ts
  apps/web/src/pages/api/query/transaction/index.ts
  apps/web/src/views/LimitOrders/components/LimitOrderTable/ExistingLimitOrderTable.tsx
  apps/web/src/views/LimitOrders/components/LimitOrderTable/NoOrdersMessage.tsx
  apps/web/src/views/LimitOrders/components/LimitOrderTable/index.tsx
  apps/web/src/views/LimitOrders/hooks/useGelatoLimitOrdersHistory.ts
  apps/web/src/views/LimitOrders/types.ts
  packages/localization/src/config/translations.json
Labels: size/XL

#11023 feat: support veCake & bCake feature on base
  apps/web/src/components/CrossChainVeCakeModal/constants.ts
  apps/web/src/components/CrossChainVeCakeModal/index.tsx
  apps/web/src/config/constants/contracts.ts
  packages/farms/constants/v3/index.ts
  packages/farms/src/const.ts
  packages/ifos/src/constants/lzChainMap.ts
Labels: size/S

#11088 fix: add universal farm constants for bCake on base
  apps/web/src/state/farmsV4/state/poolApr/fetcher.ts
Labels: size/XS

#11090 chore: xmas effect 2024
  apps/web/src/views/SwapSimplify/V4Swap/XmasEffect.tsx
  apps/web/src/views/SwapSimplify/index.tsx
Labels: size/L

#11093 fix: Merkl link for pools with reward on different chain
  apps/web/src/config/constants/merklPools.json
  scripts/updateMerkl/index.ts
Labels: size/S

#11092 fix: Add token to wallet in mobile and avoid extension conflicts
  apps/web/src/components/AddToWallet/AddToWalletButton.tsx
  apps/web/src/utils/wallet.ts
Labels: size/L

#11089 chore: align merkl data source
  apps/web/src/state/farmsV4/state/poolApr/fetcher.ts
Labels: size/XS

#11094 chore: list new TC
  apps/web/src/components/AdPanel/Ads/AdTradingCompetition.tsx
  apps/web/src/components/AdPanel/config.tsx
  apps/web/src/components/PhishingWarningBanner/TradingCompetition.tsx
  apps/web/src/components/PhishingWarningBanner/index.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#11098 fix: Fix/ads banner competition
  apps/web/src/components/AdPanel/Ads/AdTradingCompetition.tsx
  apps/web/src/components/PhishingWarningBanner/TradingCompetition.tsx
Labels: size/S

#11096 chore: rename binance wallet
  apps/gamification/config/wallet.ts
  apps/web/src/config/wallet.ts
  apps/web/src/hooks/useDataDogRUM.ts
Labels: size/XS

#11100 chore: update TC AITech unit
  apps/web/src/components/PhishingWarningBanner/TradingCompetition.tsx
Labels: size/XS

#11091 chore: update xmas effect details
  apps/web/src/views/SwapSimplify/V4Swap/XmasEffect.tsx
Labels: size/S

#11102 chore: update TC banner details
  apps/web/src/components/AdPanel/Ads/AdTradingCompetition.tsx
  apps/web/src/components/PhishingWarningBanner/TradingCompetition.tsx
Labels: size/XS
