Repository pancakeswap/pancake-frontend, pull requests merged in 2024-06, with the labels that each got.

#9908 chore: list new farms and gauges on ARB part2
  packages/farms/constants/arb.ts
  packages/tokens/src/constants/arb.ts
Labels: size/L

#9912 chore: Mark turbo dev as parallel
  package.json
Labels: size/S

#9899 feat: Chart data testing
  apps/web/package.json
  apps/web/src/state/info/api/client.ts
  apps/web/src/state/info/api/schema.d.ts
  apps/web/src/state/swap/hooks.ts
  apps/web/src/views/Swap/components/Chart/BasicChart.tsx
  pnpm-lock.yaml
Labels: size/XXL

#9903 feat: Order closed liquidity positions by desc
  apps/web/src/hooks/usePairs.ts
  apps/web/src/hooks/useV2Pairs.ts
  apps/web/src/pages/liquidity/index.tsx
  apps/web/src/views/Migration/components/v3/Step2.tsx
Labels: size/M

#9911 chore: list new gauges on ARB
  packages/gauges/src/constants/config/prod.ts
Labels: size/L

#9913 chore: Migrate base subgraphs
  .changeset/flat-foxes-change.md
  apps/web/src/config/constants/endpoints.ts
  packages/chains/src/subgraphs.ts
Labels: size/S

#9915 chore: Bump wagmi and viem
  .changeset/bright-fishes-hang.md
  apis/farms/package.json
  apis/routing/package.json
  apps/bridge/package.json
  apps/gamification/package.json
  apps/web/package.json
  packages/farms/package.json
  packages/gauges/package.json
  packages/ifos/package.json
  packages/multicall/package.json
  packages/pcsx-sdk/package.json
  packages/permit2-sdk/package.json
  packages/pools/package.json
  packages/position-managers/package.json
  packages/prediction/package.json
  packages/smart-router/package.json
  packages/swap-sdk-evm/package.json
  packages/swap-sdk/package.json
  packages/universal-router-sdk/package.json
  packages/utils/package.json
  packages/v2-sdk/package.json
  packages/v3-sdk/package.json
  packages/wagmi/package.json
  packages/widgets-internal/package.json
  pnpm-lock.yaml
  scripts/package.json
Labels: size/XL

#9917 feat: Fee tier to explorer api
  apps/web/src/hooks/v3/useFeeTierDistribution.ts
  apps/web/src/hooks/v3/useFeeTierDistributionQuery.ts
  apps/web/src/state/info/api/client.ts
  apps/web/src/state/info/api/schema.d.ts
  apps/web/src/views/Swap/components/Chart/BasicChart.tsx
  apps/web/src/views/Swap/components/HotTokenList/useList.tsx
Labels: size/L

#9920 feat: usd+warn
  apps/web/src/components/USDPlusWarningTooltip/index.tsx
  apps/web/src/config/constants/swapWarningTokens.ts
  apps/web/src/views/Farms/components/FarmTable/Farm.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/ABNBWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/BTTWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/BondlyWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/CcarWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/FREEWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/GalaWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/ItamWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/LUSDWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/METISWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/NFPWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/NMTWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/RugPullWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/SafemoonWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/XCADWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/index.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/index.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/mainnet/ALETHWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/mainnet/index.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/zksync/USDPlusWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/zksync/index.tsx
  apps/web/src/views/Swap/hooks/useWarningImport.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#9919 chore: Remove token price subgraph
  apps/web/src/views/PositionManagers/components/TableView/index.tsx
  apps/web/src/views/PositionManagers/hooks/index.ts
  apps/web/src/views/PositionManagers/hooks/useTokenPriceFromSubgraph.ts
Labels: size/M

#9918 perf: Reduce voting status graphql requests in homepage
  apps/web/src/components/Menu/hooks/useVotingStatus.ts
Labels: size/M

#9923 chore: Bump pnpm
  package.json
  pnpm-lock.yaml
Labels: size/XXL

#9895 refactor: Use previous data when farms avg info query changes
  apps/web/src/state/farms/hooks.ts
Labels: size/S

#9893 refactor: remove window.prompt/confirm
  .changeset/late-planes-taste.md
  apps/aptos/components/Providers.tsx
  apps/aptos/components/SearchModal/ManageLists.tsx
  apps/aptos/pages/swap.tsx
  apps/web/next.config.mjs
  apps/web/src/Providers.tsx
  apps/web/src/components/SearchModal/ManageLists.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalState.ts
  packages/localization/src/config/translations.json
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/hooks/index.ts
  packages/uikit/src/hooks/useDialog/Dialog.tsx
  packages/uikit/src/hooks/useDialog/DialogContext.tsx
  packages/uikit/src/hooks/useDialog/index.ts
  packages/uikit/src/hooks/useDialog/useConfirm.ts
  packages/uikit/src/hooks/useDialog/useConfirmV2.tsx
  packages/uikit/src/hooks/useDialog/usePrompt.ts
  packages/uikit/src/hooks/useDialog/usePromptV2.tsx
  packages/uikit/src/index.ts
  packages/uikit/src/widgets/Modal/Modal.tsx
  packages/uikit/src/widgets/Modal/ModalContext.tsx
  packages/uikit/src/widgets/Modal/styles.tsx
  packages/widgets-internal/swap/ExpertModal.tsx
  packages/widgets-internal/swap/confirmPriceImpactWithoutFee.ts
  packages/widgets-internal/swap/index.ts
  packages/widgets-internal/swap/useAsyncConfirmPriceImpactWithoutFee.ts
Labels: size/XL

#9925 feat: Add more explorer fetch info v2
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/state/info/api/hooks.ts
  apps/web/src/state/info/api/schema.d.ts
  apps/web/src/state/info/constant.ts
  apps/web/src/state/info/hooks.ts
  apps/web/src/state/info/queries/tokens/topTokens.ts
  apps/web/src/views/Info/Tokens/TokenPage.tsx
  apps/web/src/views/Info/components/InfoCharts/CandleChart/index.tsx
  apps/web/src/views/Info/components/InfoCharts/ChartCard/index.tsx
Labels: size/XL

#9929 fix: PM usd pricing
  apps/web/src/views/PositionManagers/components/TableView/index.tsx
Labels: size/XS

#9934 fix: Ifo page error
  packages/utils/formatTimestamp.ts
Labels: size/XS

#9927 feat: v2 tvl chart explorer
  apps/web/src/state/info/api/hooks.ts
  apps/web/src/state/info/hooks.ts
  apps/web/src/state/info/types.ts
  apps/web/src/views/Info/Overview/index.tsx
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/Info/Tokens/TokenPage.tsx
  apps/web/src/views/Info/components/InfoCharts/ChartCard/index.tsx
  apps/web/src/views/Info/components/InfoCharts/HoverableChart.tsx
Labels: size/L

#9930 feat: Use explorer in total tvl info
  apps/web/src/state/info/api/schema.d.ts
  apps/web/src/utils/getTotalTVL.ts
Labels: size/XXL

#9938 revert: "feat: v2 tvl chart explorer"
  apps/web/src/state/info/api/hooks.ts
  apps/web/src/state/info/hooks.ts
  apps/web/src/state/info/types.ts
  apps/web/src/views/Info/Overview/index.tsx
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/Info/Tokens/TokenPage.tsx
  apps/web/src/views/Info/components/InfoCharts/ChartCard/index.tsx
  apps/web/src/views/Info/components/InfoCharts/HoverableChart.tsx
Labels: size/L

#9944 feat: v2 tvl chart explorer
  apps/web/src/state/info/api/hooks.ts
  apps/web/src/state/info/hooks.ts
  apps/web/src/state/info/types.ts
  apps/web/src/views/Info/Overview/index.tsx
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/Info/Tokens/TokenPage.tsx
  apps/web/src/views/Info/components/InfoCharts/ChartCard/index.tsx
  apps/web/src/views/Info/components/InfoCharts/HoverableChart.tsx
Labels: size/L

#9896 feat: smart account use on-chain approve
  apps/web/package.json
  apps/web/src/hooks/useIsSmartContract.ts
  apps/web/src/hooks/usePermit2.ts
  apps/web/src/hooks/useSafeTxHashTransformer.ts
  apps/web/src/hooks/useWritePermit.ts
  apps/web/src/state/transactions/hooks.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalState.ts
  apps/web/src/views/Swap/hooks/useWarningImport.tsx
  packages/uikit/src/hooks/useDialog/DialogContext.tsx
  pnpm-lock.yaml
Labels: size/L

#9935 feat: Remove watchlist info v2
  apps/web/src/hooks/useInfoUserSavedTokensAndPoolsList.ts
  apps/web/src/state/user/actions.ts
  apps/web/src/state/user/hooks/index.tsx
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/Info/Pools/index.tsx
  apps/web/src/views/Info/Tokens/TokenPage.tsx
  apps/web/src/views/Info/Tokens/index.tsx
  apps/web/src/views/Info/components/InfoCharts/LineChart/index.tsx
  apps/web/src/views/Info/components/InfoSearch/index.tsx
Labels: size/L

#9954 feat: list-new-arb-gauges/farms
  packages/farms/constants/arb.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/arb.ts
  packages/tokens/src/constants/eth.ts
Labels: size/M

#9956 fix: Add toSorted polyfill to array
  apps/web/src/pages/_app.tsx
Labels: size/XS

#9957 chore: PM migration on ETH
  apps/web/src/pages/migration/bcake.tsx
  packages/position-managers/src/config.test.ts
  packages/position-managers/src/constants/vaults/eth.ts
  packages/position-managers/src/constants/vaults/index.ts
Labels: size/S

#9964 chore: Subgraph migration
  .changeset/cuddly-eggs-smell.md
  apps/web/src/config/constants/endpoints.ts
  packages/chains/package.json
  packages/chains/src/index.test.ts
  packages/chains/src/subgraphs.ts
Labels: size/M

#9967 feat: Change teams image url
  apps/web/public/images/teams/cakers-banner.png
  apps/web/public/images/teams/chaotic-cakers-alt.png
  apps/web/public/images/teams/chaotic-cakers-bg.svg
  apps/web/public/images/teams/chaotic-cakers-lg.png
  apps/web/public/images/teams/chaotic-cakers-md.png
  apps/web/public/images/teams/chaotic-cakers-sm.png
  apps/web/public/images/teams/fearsome-flippers-alt.png
  apps/web/public/images/teams/fearsome-flippers-bg.svg
  apps/web/public/images/teams/fearsome-flippers-lg.png
  apps/web/public/images/teams/fearsome-flippers-md.png
  apps/web/public/images/teams/fearsome-flippers-sm.png
  apps/web/public/images/teams/flippers-banner.png
  apps/web/public/images/teams/no-team-banner.png
  apps/web/public/images/teams/storm-banner.png
  apps/web/public/images/teams/syrup-storm-alt.png
  apps/web/public/images/teams/syrup-storm-bg.svg
  apps/web/public/images/teams/syrup-storm-lg.png
  apps/web/public/images/teams/syrup-storm-md.png
  apps/web/public/images/teams/syrup-storm-sm.png
  apps/web/src/components/ProfileAvatarWithTeam.tsx
  apps/web/src/views/Profile/components/ProfileHeader.tsx
  apps/web/src/views/ProfileCreation/TeamSelection.tsx
  apps/web/src/views/Teams/components/TeamCard.tsx
  apps/web/src/views/Teams/components/TeamListCard.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/Podium/TeamPodiumIcon.tsx
Labels: size/M

#9968 fix: useIsSmartContract
  apps/web/src/hooks/useIsSmartContract.ts
Labels: size/XS

#9969 fix: Revert invalid field names
  apis/farms/src/lpApr.ts
  apps/web/src/state/info/queries/pools/poolData.ts
  apps/web/src/state/info/queries/pools/topPools.ts
  apps/web/src/state/info/queries/tokens/poolsForToken.ts
  apps/web/src/state/info/queries/tokens/priceData.ts
  apps/web/src/state/info/queries/tokens/tokenData.ts
  apps/web/src/state/swap/useLPApr.ts
  apps/web/src/utils/getAprsForStableFarm.ts
  scripts/updateLPsAPR.ts
Labels: size/M

#9972 feat: List new position manager
  packages/farms/constants/eth.ts
  packages/position-managers/src/constants/vaults/eth.ts
Labels: size/M

#9971 fix: Switch back to use old v2 proxy
  apps/web/src/config/constants/endpoints.ts
Labels: size/XS

#9973 feat: add holdstation token
  .changeset/many-games-leave.md
  packages/tokens/src/constants/zkSync.ts
Labels: size/S

#9970 feat: v2 pool/token page explorer data
  apps/web/src/state/info/hooks.ts
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/Info/Tokens/TokenPage.tsx
Labels: size/L

#9939 feat: Use explorer api bnb prices hook
  apps/web/src/views/Info/hooks/useBnbPrices.ts
Labels: Delayed Release, size/M

#9963 feat: Use explorer api in v3 info
  apps/web/src/state/info/api/schema.d.ts
  apps/web/src/views/V3Info/data/pool/chartData.ts
  apps/web/src/views/V3Info/data/pool/poolData.ts
  apps/web/src/views/V3Info/data/pool/tickData.ts
  apps/web/src/views/V3Info/data/pool/transactions.ts
  apps/web/src/views/V3Info/data/protocol/chart.ts
  apps/web/src/views/V3Info/data/protocol/derived.ts
  apps/web/src/views/V3Info/data/protocol/overview.ts
  apps/web/src/views/V3Info/data/protocol/transactions.ts
  apps/web/src/views/V3Info/data/token/chartData.ts
  apps/web/src/views/V3Info/data/token/priceData.ts
  apps/web/src/views/V3Info/data/token/tokenData.ts
  apps/web/src/views/V3Info/data/token/transactions.ts
  apps/web/src/views/V3Info/hooks/index.ts
  apps/web/src/views/V3Info/index.tsx
  apps/web/src/views/V3Info/views/TokenPage.tsx
Labels: size/XXL

#9936 feat: v3 liquidity explorer
  apps/web/src/hooks/usePoolAvgInfo.ts
  apps/web/src/hooks/v3/useAllV3TicksQuery.ts
Labels: size/L

#9976 chore: Revert pnpm
  package.json
  pnpm-lock.yaml
Labels: size/XXL

#9845 feat: zyfi integration
  apps/web/src/components/Paymaster/GasTokenSelector.tsx
  apps/web/src/config/paymaster.ts
  apps/web/src/hooks/useApproveCallback.ts
  apps/web/src/hooks/useGasToken.ts
  apps/web/src/hooks/usePaymaster.ts
  apps/web/src/hooks/usePermit2.ts
  apps/web/src/pages/api/paymaster/index.ts
  apps/web/src/views/Home/components/Banners/PaymasterBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  apps/web/src/views/Swap/V3Swap/components/SwapModalFooter.tsx
  apps/web/src/views/Swap/V3Swap/containers/TradeDetails.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalState.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSendSwapTransaction.ts
  apps/web/src/views/Swap/components/AdvancedSwapDetails.tsx
  packages/localization/src/config/translations.json
Labels: Delayed Release, size/XXL

#9981 feat: List new farm
  apps/web/src/views/Farms/components/CustomTooltips/TaikoEthTooltips.tsx
  apps/web/src/views/Farms/components/FarmCard/CardHeading.tsx
  apps/web/src/views/Farms/components/FarmTable/Farm.tsx
  apps/web/src/views/Farms/hooks/useHasCustomFarmLpTooltips.tsx
  packages/farms/constants/eth.ts
  packages/localization/src/config/translations.json
Labels: size/M

#9977 feat: Remove old graphql query
  apps/web/src/hooks/v3/useAllV3TicksQuery.ts
  apps/web/src/hooks/v3/useFeeTierDistribution.ts
  apps/web/src/hooks/v3/useFeeTierDistributionQuery.ts
  apps/web/src/state/info/api/client.ts
  apps/web/src/state/swap/fetch/fetchDerivedPriceData.ts
  apps/web/src/state/swap/hooks.ts
  apps/web/src/state/swap/queries/getDerivedPrices.ts
  apps/web/src/views/Swap/components/Chart/BasicChart.tsx
  apps/web/src/views/V3Info/hooks/index.ts
Labels: size/XL

#9985 feat: merkl script
  scripts/updateMerkl/index.ts
Labels: size/XS

#9989 feat: use pool address
  scripts/updateMerkl/index.ts
Labels: size/XS

#9986 fix: v2 info graph init hover value
  apps/web/src/state/info/hooks.ts
Labels: size/S

#9978 feat: Explorer api in pair price chart
  apps/web/src/state/info/api/schema.d.ts
  apps/web/src/views/V3Info/data/token/priceData.ts
  apps/web/src/views/V3Info/hooks/index.ts
Labels: size/L

#9991 feat: List gauges and farm
  packages/farms/constants/bsc.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/M

#9992 chore: Add bsc v2 exchange proxy endpoint
  apps/web/src/config/constants/endpoints.ts
Labels: size/XS

#9993 chore: Take down top trader banner
  apps/web/src/views/Home/components/Banners/TopTraderBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#9996 chore: Switch to use subgraph proxies
  apis/farms/src/lpApr.ts
  apps/web/src/components/SubgraphHealthIndicator/FloatingSubgraphHealthIndicators.tsx
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/views/AffiliatesProgram/hooks/useShowWarningMessage.tsx
  packages/prediction/src/endpoints.ts
Labels: size/M

#9997 chore: Remove unused graph price hook
  apps/web/src/state/pools/fetchAceTokenPrice.ts
Labels: size/S

#9998 feat: Use explorer search
  apis/farms/src/handler.ts
  apis/farms/src/index.ts
  apis/farms/src/lpApr.ts
  apps/web/src/components/SubgraphHealthIndicator/FloatingSubgraphHealthIndicators.tsx
  apps/web/src/pages/add/[[...currency]].tsx
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/state/info/api/schema.d.ts
  apps/web/src/state/info/hooks.ts
  apps/web/src/state/info/queries/search/index.ts
  apps/web/src/state/info/queries/tokens/chartData.ts
  apps/web/src/utils/getBlocksFromTimestamps.ts
  apps/web/src/utils/graphql.ts
  apps/web/src/views/AffiliatesProgram/components/Overview/index.tsx
  apps/web/src/views/Farms/FarmsV3.tsx
  apps/web/src/views/Info/components/InfoSearch/index.tsx
  apps/web/src/views/Info/hooks/useBlocksFromTimestamps.ts
  apps/web/src/views/Pools/index.tsx
  apps/web/src/views/PositionManagers/index.tsx
  apps/web/src/views/Swap/SwapFeaturesContext.tsx
  apps/web/src/views/Swap/index.tsx
  apps/web/src/views/V3Info/components/Search/index.tsx
  apps/web/src/views/V3Info/data/search/index.ts
  apps/web/src/views/V3Info/data/token/poolsForToken.ts
  apps/web/src/views/V3Info/hooks/index.ts
  apps/web/src/views/V3Info/views/TokenPage.tsx
  packages/localization/src/config/translations.json
Labels: size/XXL

#10000 fix: block timestamp chainname
  apps/web/src/state/info/constant.ts
  apps/web/src/utils/getBlocksFromTimestamps.ts
Labels: size/S

#9999 feat: Add abort signal to explorer api calls
  apps/web/src/views/V3Info/data/pool/chartData.ts
  apps/web/src/views/V3Info/data/pool/tickData.ts
  apps/web/src/views/V3Info/data/pool/transactions.ts
  apps/web/src/views/V3Info/data/protocol/chart.ts
  apps/web/src/views/V3Info/data/protocol/overview.ts
  apps/web/src/views/V3Info/data/protocol/transactions.ts
  apps/web/src/views/V3Info/data/token/chartData.ts
  apps/web/src/views/V3Info/data/token/priceData.ts
  apps/web/src/views/V3Info/data/token/transactions.ts
  apps/web/src/views/V3Info/hooks/index.ts
Labels: size/L

#10001 chore: Support subgraph healtch check after upgrade
  apps/web/src/components/SubgraphHealthIndicator/FixedSubgraphHealthIndicator.tsx
  apps/web/src/components/SubgraphHealthIndicator/FloatingSubgraphHealthIndicators.tsx
  apps/web/src/components/SubgraphHealthIndicator/SubgraphHealthIndicator.tsx
  apps/web/src/hooks/useSubgraphHealth.ts
  apps/web/src/views/AffiliatesProgram/hooks/useShowWarningMessage.tsx
  apps/web/src/views/LimitOrders/components/LimitOrderTable/TableNavigation.tsx
  apps/web/src/views/Pottery/components/Pot/Claim/index.tsx
  apps/web/src/views/Pottery/index.tsx
  apps/web/src/views/TradingCompetition/MoDCompetition.tsx
  apps/web/src/views/TradingCompetition/MoboxCompetition.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TeamRanksWithParticipants.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TopTradersCard/index.tsx
  apps/web/src/views/TradingCompetition/components/YourScore/ScoreCard.tsx
  apps/web/src/views/TradingCompetition/mobox/components/YourScore/MoboxYourScore.tsx
  apps/web/src/views/TradingCompetition/mod/components/YourScore/ModYourScore.tsx
Labels: size/L

#9979 feat: Affiliate referral expiration popup
  apps/web/src/components/DisclaimerModal/index.tsx
  apps/web/src/components/Modal/AffiliateExpiredModal.tsx
  apps/web/src/hooks/useAffiliateExpired.ts
  apps/web/src/hooks/useInAccessList.ts
  apps/web/src/hooks/useUserAcknowledgement.ts
  apps/web/src/pages/_app.tsx
  apps/web/src/utils/accessList.ts
  packages/localization/src/config/translations.json
Labels: size/L

#10002 fix: Use explorer chain name hook
  apps/web/src/views/V3Info/hooks/index.ts
Labels: size/L

#10004 fix: gas token logo source, token decimals
  .changeset/slow-shrimps-admire.md
  apps/web/src/components/Paymaster/GasTokenSelector.tsx
  packages/tokens/src/constants/zkSync.ts
Labels: size/XS

#10003 chore: merkl tooltip wording
  apps/web/src/utils/getMerklLink.tsx
  apps/web/src/views/Farms/components/FarmCard/CardHeading.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3Card.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/Farms/components/FarmTable/Farm.tsx
  apps/web/src/views/Farms/components/FarmTable/Row.tsx
  packages/localization/src/config/translations.json
  packages/widgets-internal/farm/components/FarmTable/FarmTokenInfo.tsx
  packages/widgets-internal/farm/components/MerklNotice/index.tsx
  packages/widgets-internal/farm/types.ts
Labels: size/L

#9891 fix: show skeleton when new quote is fetching
  apps/web/src/views/BuyCrypto/components/OnRampCurrencySelect/index.tsx
  apps/web/src/views/BuyCrypto/containers/BuyCryptoForm.tsx
Labels: size/M

#10008 feat: Use explorer api for farms apr
  .github/workflows/updateCron.yml
  apps/web/src/queries/farms/index.ts
  apps/web/src/state/farms/hooks.ts
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3ApyButton.tsx
  apps/web/src/views/Farms/context.ts
  packages/chains/src/chainNames.ts
  packages/chains/src/index.test.ts
  packages/chains/src/utils.ts
  scripts/updateLPsAPR.ts
Labels: size/L

#10010 fix: unknown chain name when query fee
  apps/web/src/hooks/v3/useFeeTierDistributionQuery.ts
Labels: size/XS

#10011 feat: Update farm liquidity api
  .changeset/quick-turkeys-pay.md
  apis/farms/.dev.vars
  apis/farms/src/bindings.d.ts
  apis/farms/src/provider.ts
  apis/farms/src/v3.ts
  apis/farms/wrangler.toml
  packages/chains/src/chainNames.ts
  packages/chains/src/index.test.ts
  packages/chains/src/utils.ts
Labels: size/L

#10015 feat: List alp pool
  packages/pools/src/constants/boostedPools/arb.ts
  packages/pools/src/constants/pools/42161.ts
Labels: size/S

#10014 refactor: reuse price sdk on farms sdk
  packages/farms/constants/common/index.ts
  packages/farms/src/fetchFarmsV3.ts
Labels: size/M

#10017 feat: Use explorer api in lp apr
  apps/web/src/components/PositionCard/index.tsx
  apps/web/src/pages/stable/[address].tsx
  apps/web/src/pages/v2/pair/[[...currency]].tsx
  apps/web/src/state/farms/hooks.ts
  apps/web/src/state/farms/index.ts
  apps/web/src/state/info/api/schema.d.ts
  apps/web/src/state/swap/useLPApr.ts
  apps/web/src/utils/apr.ts
  apps/web/src/views/AddLiquidity/ChoosePair.tsx
  apps/web/src/views/AddLiquidity/index.tsx
  apps/web/src/views/Farms/Farms.tsx
  apps/web/src/views/Farms/FarmsV3.tsx
  apps/web/src/views/Home/hooks/useGetTopFarmsByApr.tsx
  apps/web/src/views/Migration/components/bCake/Step1.tsx
  apps/web/src/views/Migration/components/bCake/Step2.tsx
  apps/web/src/views/Migration/components/v3/Step1.tsx
  apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/index.tsx
  apps/web/src/views/V3Info/index.tsx
  packages/farms/src/types.ts
  packages/farms/src/v2/deserializeFarm.ts
Labels: size/L

#9982 chore: Disable deposit in Simple Staking
  apps/web/src/views/FixedStaking/components/ClaimModal.tsx
  apps/web/src/views/FixedStaking/components/FixedStakingCard.tsx
  apps/web/src/views/FixedStaking/components/FixedStakingModal.tsx
  apps/web/src/views/FixedStaking/components/FixedStakingRow.tsx
  apps/web/src/views/FixedStaking/components/HarvestModal.tsx
  apps/web/src/views/FixedStaking/components/RestakeFixedStakingModal.tsx
  apps/web/src/views/FixedStaking/index.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#10025 chore: Remove gql leftovers
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/state/info/api/schema.d.ts
  apps/web/src/state/info/constant.ts
  apps/web/src/state/info/hooks.ts
  apps/web/src/state/info/queries/pools/chartData.ts
  apps/web/src/state/info/queries/pools/poolData.ts
  apps/web/src/state/info/queries/pools/topPools.ts
  apps/web/src/state/info/queries/pools/transactions.ts
  apps/web/src/state/info/queries/protocol/chart.ts
  apps/web/src/state/info/queries/protocol/overview.ts
  apps/web/src/state/info/queries/protocol/transactions.ts
  apps/web/src/state/info/queries/tokens/poolsForToken.ts
  apps/web/src/state/info/queries/tokens/priceData.ts
  apps/web/src/state/info/queries/tokens/topTokens.ts
  apps/web/src/state/info/queries/tokens/transactions.ts
  apps/web/src/state/info/types.ts
  apps/web/src/utils/getAprsForStableFarm.ts
  apps/web/src/utils/graphql.ts
  apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
  apps/web/src/views/AddLiquidityV3/formViews/StableFormView.tsx
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/V3Info/data/search/index.ts
  apps/web/src/views/V3Info/data/token/poolsForToken.ts
  apps/web/src/views/V3Info/hooks/index.ts
Labels: size/XXL

#10012 feat: Enable all chains swap chart
  apps/web/src/views/Swap/SwapFeaturesContext.tsx
  apps/web/src/views/Swap/components/Chart/BasicChart.tsx
  apps/web/src/views/Swap/components/Chart/styles.tsx
  packages/uikit/src/__tests__/widgets/modal.test.tsx
  packages/uikit/src/components/BottomDrawer/BottomDrawer.tsx
  packages/uikit/src/components/Chart/PairPriceChart.tsx
  packages/uikit/src/components/index.ts
  packages/uikit/src/widgets/Menu/index.stories.tsx
  packages/uikit/src/widgets/Modal/BottomDrawer/BottomDrawer.tsx
  packages/uikit/src/widgets/Modal/BottomDrawer/index.stories.tsx
  packages/uikit/src/widgets/Modal/BottomDrawer/index.ts
  packages/uikit/src/widgets/Modal/BottomDrawer/styles.ts
  packages/uikit/src/widgets/Modal/ModalContext.tsx
  packages/uikit/src/widgets/Modal/NotEnoughTokensModal.tsx
  packages/uikit/src/widgets/Modal/index.tsx
Labels: size/L

#10027 docs: Update smart-router README.md
  packages/smart-router/README.md
Labels: size/XS

#10028 fix: Apr unit test
  apps/web/src/__tests__/utils/apr.test.ts
Labels: size/XS

#9878 feat: Cross chain vecake & Bcake
  apps/web/public/images/cake-staking/boost-bsc.png
  apps/web/public/images/cake-staking/cross-chain.png
  apps/web/src/components/CrossChainVeCakeModal/ChainLogos.tsx
  apps/web/src/components/CrossChainVeCakeModal/components/NetworkUpdateToDate.tsx
  apps/web/src/components/CrossChainVeCakeModal/components/NextButton.tsx
  apps/web/src/components/CrossChainVeCakeModal/components/SwitchToBnbCahinModal.tsx
  apps/web/src/components/CrossChainVeCakeModal/components/SyncButton.tsx
  apps/web/src/components/CrossChainVeCakeModal/constants.ts
  apps/web/src/components/CrossChainVeCakeModal/hooks/useCrossChainMessage.ts
  apps/web/src/components/CrossChainVeCakeModal/hooks/useMultichainVeCakeWellSynced.ts
  apps/web/src/components/CrossChainVeCakeModal/hooks/useProfileProxyWellSynced.ts
  apps/web/src/components/CrossChainVeCakeModal/index.tsx
  apps/web/src/config/abi/pancakeProfileProxy.ts
  apps/web/src/config/abi/pancakeVeSenderV2ABI.ts
  apps/web/src/config/constants/contracts.ts
  apps/web/src/hooks/useContract.ts
  apps/web/src/hooks/useTokenBalance.ts
  apps/web/src/state/farmsV3/hooks.ts
  apps/web/src/utils/addressHelpers.ts
  apps/web/src/utils/contractHelpers.ts
  apps/web/src/views/CakeStaking/components/BenefitCard.tsx
  apps/web/src/views/CakeStaking/hooks/useCakePoolLockInfo.ts
  apps/web/src/views/CakeStaking/hooks/useVeCakeUserInfo.ts
  apps/web/src/views/CakeStaking/index.tsx
  apps/web/src/views/Farms/FarmsV3.tsx
  apps/web/src/views/Farms/components/FarmCard/CardActionsContainer.tsx
  apps/web/src/views/Farms/components/FarmCard/CardHeading.tsx
  apps/web/src/views/Farms/components/FarmCard/FarmCard.tsx
  apps/web/src/views/Farms/components/FarmCard/StakeAction.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3Card.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/SingleFarmV3Card.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
  apps/web/src/views/Farms/components/FarmTable/Row.tsx
  apps/web/src/views/Farms/components/YieldBooster/components/bCakeV3/BCakeBoosterCard.tsx
  apps/web/src/views/Farms/components/YieldBooster/components/bCakeV3/CardView.tsx
  apps/web/src/views/Farms/components/YieldBooster/components/bCakeV3/StatusView.tsx
  apps/web/src/views/Farms/components/YieldBooster/components/bCakeV3/StatusViewButtons.tsx
  apps/web/src/views/Farms/components/YieldBooster/hooks/bCakeV3/useBCakeV3Info.ts
  apps/web/src/views/Home/components/Banners/VeCakeBanner.tsx
  apps/web/src/views/PositionManagers/components/Header.tsx
  apps/web/src/views/PositionManagers/components/LiquidityManagement.tsx
  apps/web/src/views/PositionManagers/components/TableView/FarmCell.tsx
  apps/web/src/views/PositionManagers/components/TableView/LiquidityManagement.tsx
  apps/web/src/views/PositionManagers/hooks/index.ts
  apps/web/src/views/PositionManagers/hooks/usePMV2SSMaxMultiplier.ts
  apps/web/src/views/PositionManagers/hooks/useWrapperBooster.ts
  packages/farms/constants/v3/index.ts
  packages/farms/src/const.ts
  packages/ifos/src/constants/lzChainMap.ts
  packages/localization/src/config/translations.json
  packages/uikit/src/components/Svg/Icons/LinkIcon.tsx
  packages/uikit/src/components/Svg/index.tsx
Labels: size/XXL

#10031 feat: remove Merkl popup
  apps/web/src/components/Merkl/MerklSection.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#10036 chore: Remove old info gateway
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/state/info/queries/tokens/topTokens.ts
Labels: size/S

#10038 feat: add zk&base farms/gauges
  packages/farms/constants/base.ts
  packages/farms/constants/zkSync.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/base.ts
  packages/tokens/src/constants/zkSync.ts
Labels: size/L

#10039 feat: pcsx decay
  .changeset/angry-cougars-begin.md
  packages/pcsx-sdk/src/orders/ExclusiveDutchOrder.test.ts
  packages/pcsx-sdk/src/orders/ExclusiveDutchOrder.ts
Labels: size/M

#10041 feat: add $ZK as gas token
  apps/web/src/components/Paymaster/GasTokenSelector.tsx
  apps/web/src/config/paymaster.ts
Labels: size/XS

#10042 feat: Add chef penguin
  .github/CODEOWNERS
Labels: size/XS

#10043 fix: Remove redundant 0s
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardTokens.tsx
  packages/ifos/src/constants/ifos/bsc.ts
Labels: size/L

#10047 feat: paymaster position, default gas token usdc
  apps/web/src/components/Paymaster/GasTokenSelector.tsx
  apps/web/src/config/paymaster.ts
  apps/web/src/views/Swap/V3Swap/components/SwapModalFooter.tsx
  apps/web/src/views/Swap/components/AdvancedSwapDetails.tsx
Labels: size/M

#10054 chore: Add timeout to stats requests
  apps/web/src/utils/getTotalTVL.ts
Labels: size/S

#10049 feat: Add 1H to basic swap chart
  apps/web/src/hooks/v3/usePairTokensPrice.ts
  apps/web/src/state/swap/actions.ts
  apps/web/src/state/swap/hooks.ts
  apps/web/src/state/swap/types.ts
  apps/web/src/views/Swap/components/Chart/BasicChart.tsx
  apps/web/src/views/V3Info/data/token/priceData.ts
  apps/web/src/views/V3Info/hooks/index.ts
  packages/localization/src/config/translations.json
  packages/uikit/src/components/Chart/PairPriceChart.tsx
  packages/uikit/src/components/Chart/index.stories.tsx
  packages/widgets-internal/roi/PriceChart.tsx
Labels: size/M

#9892 fix: add theme customization for widget url gen
  apps/web/src/views/BuyCrypto/constants.ts
  apps/web/src/views/BuyCrypto/hooks/useOnRampSignature.ts
Labels: size/S

#10058 feat: Old price display on chart when tap in mobile and use default timezone
  packages/uikit/src/components/Chart/PairPriceChart.tsx
Labels: size/M

#10052 chore: Remove skip count from block timestamps
  apps/web/src/utils/getBlocksFromTimestamps.ts
  apps/web/src/views/Info/hooks/useBlocksFromTimestamps.ts
Labels: size/XS

#10061 feat: list lista farm & gauge
  packages/farms/constants/bsc.ts
  packages/gauges/src/constants/config/prod.ts
Labels: size/S

#10062 feat: add zro farms
  packages/farms/constants/arb.ts
  packages/farms/constants/base.ts
  packages/farms/constants/bsc.ts
  packages/farms/constants/eth.ts
  packages/tokens/src/constants/base.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/M

#10066 fix: position manager UI details
  apps/web/src/views/PositionManagers/components/TableView/FarmCell.tsx
  apps/web/src/views/PositionManagers/components/TableView/LiquidityManagement.tsx
  apps/web/src/views/PositionManagers/components/TableView/index.tsx
Labels: size/S

#10067 feat: list zke & rf
  .changeset/short-cherries-melt.md
  packages/tokens/src/constants/zkSync.ts
Labels: size/S

#10071 feat: alm migrate
  packages/position-managers/src/constants/vaults/eth.ts
Labels: size/XS

#9827 fix: ui fixes for farm notification messages
  apps/web/src/views/Notifications/components/NotificationItem/NotificationItem.tsx
  apps/web/src/views/Notifications/components/NotificationItem/NotificationItemImage.tsx
  apps/web/src/views/Notifications/utils/textHelpers.ts
  packages/localization/src/config/translations.json
Labels: size/M

#10077 chore: Disable revalidation
  apps/web/src/pages/index.tsx
Labels: size/XS

#10081 chore: Remove info leftovers
  apps/web/src/state/info/api/client.ts
  apps/web/src/state/info/constant.ts
  apps/web/src/state/info/hooks.ts
  apps/web/src/state/info/queries/helpers.ts
  apps/web/src/state/info/queries/types.ts
  apps/web/src/state/info/types.ts
  apps/web/src/views/Info/hooks/useBlocksFromTimestamps.ts
  apps/web/src/views/V3Info/hooks/index.ts
Labels: size/L

#10075 fix: info logo issue
  apps/web/src/views/Info/components/CurrencyLogo/index.tsx
  packages/widgets-internal/components/CurrencyLogo/utils.ts
Labels: size/S

#10057 fix: recalculate the booster APR for PM v2 SS V3 bCake
  apps/web/src/state/farms/fetchFarmUser.ts
  apps/web/src/state/farms/index.ts
  apps/web/src/state/farmsV3/hooks.ts
  apps/web/src/views/Farms/FarmsV3.tsx
  apps/web/src/views/PositionManagers/components/AddLiquidity.tsx
  apps/web/src/views/PositionManagers/components/DuoTokenVaultCard.tsx
  apps/web/src/views/PositionManagers/components/LiquidityManagement.tsx
  apps/web/src/views/PositionManagers/components/TableView/ActionPanel.tsx
  apps/web/src/views/PositionManagers/components/TableView/LiquidityManagement.tsx
  apps/web/src/views/PositionManagers/components/TableView/index.tsx
  apps/web/src/views/PositionManagers/containers/PCSVaultCard.tsx
  apps/web/src/views/PositionManagers/hooks/useApr.ts
  apps/web/src/views/PositionManagers/hooks/useBoostedLiquidityX.tsx
  apps/web/src/views/PositionManagers/hooks/useTotalStakedInUsd.ts
  packages/farms/src/index.ts
  packages/farms/src/types.ts
  packages/farms/src/v2/deserializeFarmUserData.ts
Labels: size/L

#10063 feat: Add candlestick to swap chart
  apps/web/src/state/swap/hooks.ts
  apps/web/src/views/Swap/components/Chart/PriceChart.tsx
  apps/web/src/views/Swap/components/Chart/SwapChart.tsx
  apps/web/src/views/Swap/components/Chart/utils.ts
  packages/localization/src/config/translations.json
  packages/uikit/src/components/Chart/PairPriceChart.tsx
  packages/uikit/src/components/Chart/index.stories.tsx
  packages/uikit/src/components/Svg/Icons/CandleGraph.tsx
  packages/uikit/src/components/Svg/index.tsx
  packages/widgets-internal/roi/PriceChart.tsx
Labels: size/L

#10084 feat: uikit feature stack
  .changeset/late-shoes-clap.md
  .changeset/seven-guests-pull.md
  packages/uikit/src/components/Svg/Icons/LinkIcon.tsx
  packages/uikit/src/components/Svg/Icons/Miscellaneous.tsx
  packages/uikit/src/components/Svg/index.stories.tsx
  packages/uikit/src/components/Svg/index.tsx
  packages/widgets-internal/components/FeatureStack/FeatureStack.tsx
  packages/widgets-internal/components/FeatureStack/index.ts
  packages/widgets-internal/index.ts
Labels: size/L

#10088 fix: WETH-swETH ALM config
  packages/position-managers/src/constants/vaults/eth.ts
Labels: size/XS

#10083 feat: add perpetual banner
  apps/web/src/components/PhishingWarningBanner/PerpetualSeason.tsx
  apps/web/src/components/PhishingWarningBanner/index.tsx
  apps/web/src/views/Home/components/Banners/PerpetualSeasonalBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
  packages/widgets-internal/components/Banner/BannerTitle.tsx
Labels: size/L

#10087 feat: Move LISTA IFO to finished
  packages/ifos/src/constants/ifos/bsc.ts
Labels: size/XS, automerge

#10091 fix: fix utm_source & stripe logo of perpetual banner
  apps/web/src/components/PhishingWarningBanner/PerpetualSeason.tsx
  apps/web/src/views/Home/components/Banners/PerpetualSeasonalBanner.tsx
Labels: size/XS

#10092 fix: change url of perp to hardcode
  apps/web/src/components/PhishingWarningBanner/PerpetualSeason.tsx
  apps/web/src/views/Home/components/Banners/PerpetualSeasonalBanner.tsx
Labels: size/S

#10093 fix: v3 farm staked liquidity display issue
  apps/web/src/state/farmsV3/hooks.ts
Labels: size/XS

#10021 feat: AI Predictions on Arbitrum
  .changeset/serious-ladybugs-hope.md
  .changeset/sharp-beds-smell.md
  apps/web/package.json
  apps/web/public/images/predictions/meter.json
  apps/web/public/images/predictions/meter_dark.json
  apps/web/public/images/predictions/prediction.json
  apps/web/src/components/PhishingWarningBanner/AIPredictionStripe.tsx
  apps/web/src/components/PhishingWarningBanner/PerpetualSeason.tsx
  apps/web/src/components/PhishingWarningBanner/index.tsx
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/config/constants/prediction/price.ts
  apps/web/src/pages/api/prediction/price/index.ts
  apps/web/src/state/predictions/helpers.ts
  apps/web/src/state/predictions/index.ts
  apps/web/src/state/types.ts
  apps/web/src/utils/types.ts
  apps/web/src/views/Home/components/Banners/PaymasterBanner.tsx
  apps/web/src/views/Home/components/Banners/PredictionBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  apps/web/src/views/Predictions/Desktop.tsx
  apps/web/src/views/Predictions/MobileChart.tsx
  apps/web/src/views/Predictions/components/ChartDisclaimer.tsx
  apps/web/src/views/Predictions/components/CollectWinningsButton.tsx
  apps/web/src/views/Predictions/components/History/AIPredictions/AIBetDetails.tsx
  apps/web/src/views/Predictions/components/History/AIPredictions/AIBetResult.tsx
  apps/web/src/views/Predictions/components/History/AIPredictions/AIRoundResultHistory.tsx
  apps/web/src/views/Predictions/components/History/HistoricalBet.tsx
  apps/web/src/views/Predictions/components/RoundCard/AIPredictions/AICalculatingCard.tsx
  apps/web/src/views/Predictions/components/RoundCard/AIPredictions/AICardHeader.tsx
  apps/web/src/views/Predictions/components/RoundCard/AIPredictions/AIEnteredTag.tsx
  apps/web/src/views/Predictions/components/RoundCard/AIPredictions/AIExpiredRoundCard.tsx
  apps/web/src/views/Predictions/components/RoundCard/AIPredictions/AILiveRoundCard.tsx
  apps/web/src/views/Predictions/components/RoundCard/AIPredictions/AIMultiplierArrow.tsx
  apps/web/src/views/Predictions/components/RoundCard/AIPredictions/AIOpenRoundCard.tsx
  apps/web/src/views/Predictions/components/RoundCard/AIPredictions/AIPositionTag.tsx
  apps/web/src/views/Predictions/components/RoundCard/AIPredictions/AIPredictionsLogo.tsx
  apps/web/src/views/Predictions/components/RoundCard/AIPredictions/AISetPositionCard.tsx
  apps/web/src/views/Predictions/components/RoundCard/AIPredictions/BetBadgeStack.tsx
  apps/web/src/views/Predictions/components/RoundCard/AIPredictions/PayoutMeter.tsx
  apps/web/src/views/Predictions/components/RoundCard/LiveRoundPrice.tsx
  apps/web/src/views/Predictions/components/RoundCard/index.tsx
  apps/web/src/views/Predictions/components/RoundResult/RoundResult.tsx
  apps/web/src/views/Predictions/components/RoundResult/styles.tsx
  apps/web/src/views/Predictions/components/TokenSelector/Price.tsx
  apps/web/src/views/Predictions/helpers.ts
  apps/web/src/views/Predictions/hooks/usePollOraclePrice.ts
  apps/web/src/views/Predictions/hooks/usePredictionPrice.ts
  apps/web/src/views/Predictions/index.tsx
  packages/localization/src/config/translations.json
  packages/prediction/src/abis/aiPredictions.ts
  packages/prediction/src/chainlinkOracleContract.ts
  packages/prediction/src/constants/predictions/arb.ts
  packages/prediction/src/constants/supportedChains.ts
  packages/prediction/src/endpoints.ts
  packages/prediction/src/index.tsx
  packages/prediction/src/predictionContract.ts
  packages/prediction/src/type.ts
  packages/uikit/src/components/Svg/Icons/GlassGlobe.tsx
  packages/uikit/src/components/Svg/index.tsx
  pnpm-lock.yaml
Labels: size/XXL

#10094 feat: add new Farm & Gauges
  packages/farms/constants/bsc.ts
  packages/farms/constants/zkSync.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/arb.ts
Labels: size/M

#10095 feat: increase decimal precision in collect winnings modal
  apps/web/src/views/Predictions/components/CollectRoundWinningsModal.tsx
Labels: size/XS

#10101 feat: show usd value when opening bet
  apps/web/src/views/Predictions/components/RoundCard/AIPredictions/AIOpenRoundCard.tsx
  apps/web/src/views/Predictions/components/RoundCard/AIPredictions/AISetPositionCard.tsx
  apps/web/src/views/Predictions/components/RoundCard/SetPositionCard.tsx
Labels: size/M

#10105 fix: Perp seasonal banner height in mobile
  apps/web/src/views/Home/components/Banners/PerpetualSeasonalBanner.tsx
Labels: size/XS

#10096 chore: Update CODEOWNERS
  .github/CODEOWNERS
Labels: size/XS

#10106 fix: Ifo missing version 8 Ifo card
  apps/web/src/views/Ifos/PastIfo.tsx
  apps/web/src/views/Ifos/components/IfoCardV8Data.tsx
Labels: size/XS

#10082 feat(uikit): fee-tier
  .changeset/tasty-pots-walk.md
  packages/localization/src/config/translations.json
  packages/uikit/src/components/FeeTier/FeeTier.tsx
  packages/uikit/src/components/FeeTier/index.stories.tsx
  packages/uikit/src/components/FeeTier/index.ts
  packages/uikit/src/components/index.ts
  packages/widgets-internal/components/FeeTierTooltip/index.tsx
  packages/widgets-internal/index.ts
Labels: size/L

#10107 chore: remove multichain banner
  apps/web/src/views/Home/components/Banners/MultichainBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#10073 chore: Make roi calculator chart default to day
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3ApyButton.tsx
Labels: size/S

#10072 fix: Keep previous data on chainlink chart to not show loading on each fetch
  apps/web/src/views/Predictions/components/ChainlinkChart.tsx
Labels: size/XS

#10089 chore: Remove v3 info leftovers
  apps/web/src/views/V3Info/data/pool/poolData.ts
  apps/web/src/views/V3Info/data/pool/topPools.ts
  apps/web/src/views/V3Info/data/protocol/derived.ts
  apps/web/src/views/V3Info/data/token/topTokens.ts
Labels: size/L

#10110 feat: add in-page banner in prediction page
  apps/web/src/components/PhishingWarningBanner/AIPredictionStripe.tsx
  apps/web/src/views/Predictions/components/InPageBanner.tsx
  apps/web/src/views/Predictions/index.tsx
Labels: size/L

#10111 chore: remove traverse banner
  apps/web/src/views/Home/components/Banners/GalxeTraverseBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#10112 chore: remove infostripe condition for inpage banner
  apps/web/src/views/Predictions/components/InPageBanner.tsx
Labels: size/XS

#10117 chore: list new pepe syrup pool
  apps/web/src/views/Predictions/index.tsx
  packages/pools/src/constants/pools/56.ts
Labels: size/S
