Repository pancakeswap/pancake-frontend, pull requests merged in 2024-10, with the labels that each got.

#10762 feat: Hide optional icon
  apps/gamification/next-env.d.ts
  apps/gamification/views/Quest/components/Tasks/Task.tsx
  apps/gamification/views/Quest/components/Tasks/index.tsx
Labels: size/S

#10765 chore: list new farm on eth
  packages/farms/src/farms/eth.ts
  packages/tokens/src/constants/eth.ts
Labels: size/S

#10401 feat: Navbar revamp
  apps/aptos/components/Menu/footerConfig.ts
  apps/web/src/__tests__/utils/utils.test.ts
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/components/Menu/hooks/useMenuItems.ts
  apps/web/src/components/Menu/index.tsx
  apps/web/src/components/Menu/utils.ts
  apps/web/src/views/CakeStaking/index.tsx
  apps/web/src/views/Farms/index.tsx
  apps/web/src/views/Lottery/components/SubMenu/index.tsx
  apps/web/src/views/Lottery/index.tsx
  apps/web/src/views/Pools/index.tsx
  apps/web/src/views/PositionManagers/components/SubMenu/index.tsx
  apps/web/src/views/PositionManagers/index.tsx
  apps/web/src/views/Predictions/components/InPageBanner.tsx
  apps/web/src/views/Predictions/index.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/components/DropdownMenu/DropdownMenu.tsx
  packages/uikit/src/components/DropdownMenu/types.ts
  packages/uikit/src/components/Footer/Footer.tsx
  packages/uikit/src/components/MenuItems/MenuItems.tsx
  packages/uikit/src/components/MenuItems/types.ts
  packages/uikit/src/components/Svg/Icons/Game.tsx
  packages/uikit/src/components/Svg/index.tsx
  packages/uikit/src/widgets/Menu/Menu.tsx
  packages/uikit/src/widgets/Menu/components/footerConfig.ts
  packages/uikit/src/widgets/Menu/types.ts
Labels: size/XXL

#10768 chore: list new pool on bsc
  packages/pools/src/constants/pools/56.ts
Labels: size/XS

#10770 feat: Update Nav
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/views/PositionManagers/components/SubMenu/index.tsx
  apps/web/src/views/universalFarms/components/PoolsBanner.tsx
Labels: size/M

#10771 feat: Bump bridge widget version
  apps/bridge/components/layerZero/config.ts
Labels: size/XS

#10767 feat: Nigeria meetup banner
  apps/web/src/views/Home/components/Banners/NigeriaMeetupBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
  packages/widgets-internal/components/Banner/BannerTitle.tsx
Labels: size/L

#10779 feat: Remove expired homepage info strip banners
  apps/web/src/components/PhishingWarningBanner/PerpetualSeason.tsx
  apps/web/src/components/PhishingWarningBanner/index.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#10781 chore: list new gauges on arb&bsc
  packages/gauges/src/constants/config/prod.ts
Labels: size/M

#10780 feat: Enable zap for all bsc pools and add arb and eth whitelist
  apps/web/src/components/ZapLiquidityWidget.tsx
  apps/web/src/config/constants/zapV3.ts
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
Labels: size/M

#10784 chore: defiedge warning on position manager
  apps/web/src/views/PositionManagers/components/Header.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#10785 fix: Dynamic status indicator not working on menu
  apps/gamification/components/Menu/index.tsx
  apps/web/src/components/Menu/hooks/useMenuItems.ts
  apps/web/src/components/Menu/index.tsx
  packages/uikit/src/components/BottomNav/BottomNav.tsx
  packages/uikit/src/components/MenuItems/MenuItems.tsx
  packages/uikit/src/util/findMenuItemsStatusColor.ts
Labels: size/L

#10788 fix: Web3 inbox account error
  apps/web/src/hooks/useInitializeNotifications.ts
Labels: size/XS

#10789 feat: Disabled stake button when pool finished
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
Labels: size/XS

#10792 chore: list new gauges and farm
  packages/farms/src/farms/eth.ts
  packages/gauges/src/constants/config/prod.ts
Labels: size/M

#10791 chore: remove uniBTC warning
  apps/web/src/config/constants/swapWarningTokens.ts
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/index.tsx
Labels: size/S

#10790 fix: Swap warning error when currency undefined
  apps/web/src/utils/shouldShowSwapWarning.ts
  apps/web/src/views/Swap/hooks/useWarningImport.tsx
Labels: size/S, Sentry

#10730 feat: Gauges with API
  .changeset/shy-shrimps-know.md
  apis/routing/src/index.ts
  apps/web/src/hooks/usePoolsOnChain.ts
  packages/gauges/src/constants/config/endpoint.ts
  packages/gauges/src/constants/config/getGauges.ts
  packages/gauges/src/constants/config/index.ts
  packages/gauges/src/constants/config/prod.ts
  packages/gauges/src/constants/index.ts
  packages/gauges/src/getAllGauges.ts
  packages/gauges/src/getGaugesByChain.ts
  packages/gauges/src/index.test.ts
  packages/gauges/src/index.ts
  packages/gauges/src/tests/config.test.ts
  packages/smart-router/evm/index.test.ts
  packages/smart-router/evm/v3-router/functions/getPairCombinations.ts
  packages/smart-router/evm/v3-router/index.ts
  packages/smart-router/evm/v3-router/providers/getCommonTokenPrices.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/getStableCandidatePools.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/getV2CandidatePools.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/getV3CandidatePools.ts
  packages/smart-router/evm/v4-router/queries/getV3Pools.ts
  pnpm-lock.yaml
Labels: size/XXL

#10796 chore: Enable experimental trading for 20% of existing traffic
  apps/web/src/config/experimentalFeatures.ts
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/views/Swap/V3Swap/hooks/useAllTypeBestTrade.ts
  apps/web/src/views/Swap/V3Swap/index.tsx
  packages/routing-sdk/addons/v3/src/constants/gasCost.ts
  packages/smart-router/evm/v3-router/types/trade.ts
Labels: size/M

#10797 chore(web): update kyberswap zap widgets
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/M

#10772 revert: Hide optional icon (#10762)
  apps/gamification/next-env.d.ts
  apps/gamification/views/Quest/components/Tasks/Task.tsx
  apps/gamification/views/Quest/components/Tasks/index.tsx
Labels: Delayed Release, size/S

#10801 fix: Missing gauge
  .changeset/strange-forks-love.md
  packages/gauges/src/getAllGauges.ts
Labels: size/XS

#10800 fix(zap): pump kyberswap zap widget version to fix source params
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/L

#10773 feat: Connect pool API
  apps/web/src/__tests__/state/pools/helpers.test.ts
  apps/web/src/config/__tests__/pools.test.ts
  apps/web/src/hooks/useContract.ts
  apps/web/src/state/pools/hooks.ts
  apps/web/src/state/pools/index.ts
  apps/web/src/utils/calls/pools.ts
  apps/web/src/views/Home/hooks/useGetTopPoolsByApr.tsx
  apps/web/src/views/Pools/hooks/useApprove.tsx
  packages/pools/src/constants/config/endpoint.ts
  packages/pools/src/constants/pools/1.ts
  packages/pools/src/constants/pools/1101.ts
  packages/pools/src/constants/pools/1442.ts
  packages/pools/src/constants/pools/204.ts
  packages/pools/src/constants/pools/280.ts
  packages/pools/src/constants/pools/324.ts
  packages/pools/src/constants/pools/42161.ts
  packages/pools/src/constants/pools/421613.ts
  packages/pools/src/constants/pools/56.ts
  packages/pools/src/constants/pools/59140.ts
  packages/pools/src/constants/pools/59144.ts
  packages/pools/src/constants/pools/8453.ts
  packages/pools/src/constants/pools/84531.ts
  packages/pools/src/constants/pools/97.ts
  packages/pools/src/constants/pools/index.ts
  packages/pools/src/index.test.ts
  packages/pools/src/queries/fetchPools.ts
  packages/pools/src/queries/fetchUserPoolsData.ts
  packages/pools/src/utils/getPoolContractBySousId.ts
Labels: size/XXL

#10803 fix: Menu active subitems and remove submenu from views
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/components/Menu/index.tsx
  apps/web/src/components/Menu/utils.ts
  apps/web/src/views/CakeStaking/index.tsx
  apps/web/src/views/Farms/index.tsx
  apps/web/src/views/Ifos/index.tsx
  apps/web/src/views/LandingV4/components/SubMenu/index.tsx
  apps/web/src/views/LandingV4/index.tsx
  apps/web/src/views/Lottery/components/SubMenu/index.tsx
  apps/web/src/views/Lottery/index.tsx
  apps/web/src/views/Pools/index.tsx
  apps/web/src/views/PositionManagers/components/SubMenu/index.tsx
  apps/web/src/views/PositionManagers/index.tsx
  apps/web/src/views/Predictions/index.tsx
  apps/web/src/views/universalFarms/components/PoolsBanner.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/widgets/Menu/Menu.tsx
Labels: size/L

#10806 chore: Add farms to menu match href list
  apps/web/src/components/Menu/config/config.ts
Labels: size/XS

#10809 fix: Failed to quote if failed to get gauge list
  .changeset/heavy-wolves-yawn.md
  packages/gauges/src/getGaugesByChain.ts
Labels: size/XS

#10808 fix: Inaccurate quote after on chain verification
  .changeset/red-mangos-try.md
  apps/web/src/hooks/useTradeVerifiedByQuoter.ts
  packages/routing-sdk/addons/quoter/src/fetchQuotes.ts
  packages/routing-sdk/addons/quoter/src/fetchV3Quote.ts
  packages/routing-sdk/addons/quoter/src/types.ts
Labels: size/M

#10787 chore: Bump up nextjs 14.2.14
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: size/L

#10810 chore: Bump wagmi viem and pnpm
  .github/actions/install-deps/action.yml
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: size/XL

#10815 fix: AbortController and AbortSignal.timeout Polyfill
  apps/web/package.json
  apps/web/src/pages/_app.tsx
  apps/web/src/utils/abortcontroller-polyfill.ts
  pnpm-lock.yaml
Labels: size/S

#10814 chore: Remove nigeria meetup banner, dont fetch farms length when no account and callback on select query
  apps/web/src/hooks/useBCakeProxyContractAddress.ts
  apps/web/src/hooks/useContract.ts
  apps/web/src/hooks/useMerkl.tsx
  apps/web/src/hooks/usePermit2Details.ts
  apps/web/src/state/block/hooks.ts
  apps/web/src/state/farms/hooks.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountV2PendingCakeReward.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountV3Position.ts
  apps/web/src/views/CakeStaking/hooks/useVeCakeUserInfo.ts
  apps/web/src/views/Farms/components/YieldBooster/hooks/useProxyCAKEBalance.ts
  apps/web/src/views/Farms/hooks/useBCakeProxyBalance.ts
  apps/web/src/views/Home/components/Banners/hooks/useIsRenderTgPredictionBotBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useIsRenderUserBanner.ts
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  apps/web/src/views/Home/hooks/useCakeEmissionPerBlock.tsx
  apps/web/src/views/Home/hooks/useFarmsWithBalance.tsx
  apps/web/src/views/PoolDetail/hooks/usePoolTransactions.ts
Labels: size/L

#10819 fix: dropdown menu button onclick missed
  .changeset/twenty-swans-prove.md
  packages/uikit/.storybook/main.js
  packages/uikit/.storybook/vite.config.ts
  packages/uikit/src/components/DropdownMenu/DropdownMenu.tsx
  packages/uikit/src/components/DropdownMenu/mock.tsx
Labels: size/S

#10821 chore: Use external link for docs
  apps/web/src/index.tsx
  apps/web/src/views/BuyCrypto/containers/BuyCryptoForm.tsx
  apps/web/src/views/CakeStaking/components/LockedVeCakeStatus.tsx
  apps/web/src/views/CakeStaking/components/SyrupPool/LearnMoreLink.tsx
  apps/web/src/views/Farms/components/FarmCard/CardHeading.tsx
  apps/web/src/views/Farms/components/FarmTable/Farm.tsx
  apps/web/src/views/Farms/components/YieldBooster/components/bCakeV3/BCakeBoosterCard.tsx
  apps/web/src/views/FixedStaking/components/DisclaimerCheckBox.tsx
  apps/web/src/views/FixedStaking/components/WithdrawalMessage.tsx
  apps/web/src/views/FixedStaking/hooks/useHandleWithdrawSubmission.tsx
  apps/web/src/views/Home/components/CakeSection/index.tsx
  apps/web/src/views/Lottery/components/HowToPlay.tsx
  apps/web/src/views/Pools/components/PoolsTable/PoolRow.tsx
  packages/uikit/src/components/Footer/Footer.tsx
  packages/widgets-internal/ifo/Tips.tsx
Labels: size/M

#10824 chore: Add arb mm token list
  apps/web/src/config/constants/lists.ts
Labels: size/XS

#10825 chore: Ramp up experimental trading
  apps/web/src/components/App/Transactions/XTransaction.tsx
  apps/web/src/components/Menu/GlobalSettings/SettingsModal.tsx
  apps/web/src/config/experimentalFeatures.ts
  apps/web/src/views/Swap/V3Swap/components/RoutesBreakdown.tsx
  packages/localization/src/config/translations.json
  packages/widgets-internal/swap/ApproveModalContent.tsx
  packages/widgets-internal/swap/ApproveModalContentV1.tsx
Labels: size/S

#10818 fix: Crash swap trade details
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/views/Swap/V3Swap/containers/TradeDetails.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useAllTypeBestTrade.ts
Labels: size/S, Sentry

#10827 feat: Sort banner
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Labels: size/XS

#10817 perf: Load polyfill only when timeout not available
  apps/web/src/utils/abortcontroller-polyfill.ts
Labels: size/S

#10823 fix: Add mBTC-BTCB on BSC and mBTC-WBTC on ARB
  packages/farms/src/farms/arb.ts
  packages/farms/src/farms/bsc.ts
Labels: size/S

#10826 feat: Add banner and infostripe for PCSX
  apps/web/src/components/PhishingWarningBanner/Step3.tsx
  apps/web/src/components/PhishingWarningBanner/index.tsx
  apps/web/src/views/Home/components/Banners/PCSXBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  apps/web/src/views/Home/components/UserBanner/index.tsx
  packages/localization/src/config/translations.json
  packages/utils/user/phishingBanner.ts
Labels: size/L

#10832 feat: Obording 3 new famrs
  packages/farms/src/farms/base.ts
Labels: size/S

#10833 feat: List position manager
  packages/position-managers/src/constants/vaults/bsc.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/M

#10836 feat: List ynbnb farm
  packages/farms/src/farms/bsc.ts
Labels: size/XS

#10837 fix: TVL and Volume issue on farm page
  apps/web/src/state/farmsV4/state/farmPools/fetcher.ts
Labels: size/L

#10774 perf: Remove isaddressequal usage and Call update cake apr once instead of per farm when initial load
  apps/web/src/hooks/usePermit2Requires.ts
  apps/web/src/state/farmsV4/state/accountPositions/fetcher.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountPositionDetailByPool.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountV2LpDetails.ts
  apps/web/src/state/farmsV4/state/extendPools/atom.ts
  apps/web/src/state/farmsV4/state/farmPools/fetcher.ts
  apps/web/src/state/farmsV4/state/farmPools/hooks.ts
  apps/web/src/state/farmsV4/state/poolApr/atom.ts
  apps/web/src/state/farmsV4/state/poolApr/fetcher.ts
  apps/web/src/state/farmsV4/state/poolApr/hooks.ts
  apps/web/src/state/farmsV4/state/utils.ts
  apps/web/src/utils/checksumAddress.ts
  apps/web/src/utils/index.ts
  apps/web/src/views/CakeStaking/hooks/useIsMigratedToVeCake.ts
  apps/web/src/views/CakeStaking/hooks/useProxyVeCakeBalance.ts
  apps/web/src/views/CakeStaking/hooks/useProxyVeCakeBalanceOfAtTime.ts
  apps/web/src/views/Farms/components/FarmCard/CardHeading.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3Card.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/Farms/components/FarmTable/Farm.tsx
  apps/web/src/views/Farms/hooks/useLmPoolLiquidity.ts
  apps/web/src/views/GaugesVoting/hooks/useEpochVotePower.ts
  apps/web/src/views/GaugesVoting/hooks/useUserVote.ts
  apps/web/src/views/GaugesVoting/hooks/useUserVoteGauges.ts
  apps/web/src/views/PoolDetail/components/BreadcrumbNav.tsx
  apps/web/src/views/PoolDetail/components/PoolStatus.tsx
  apps/web/src/views/Pools/components/PoolsTable/PoolRow.tsx
  apps/web/src/views/universalFarms/PositionPage.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/V2PoolAprModal.tsx
  apps/web/src/views/universalFarms/components/PoolListItemAction.tsx
  apps/web/src/views/universalFarms/hooks/useEstimateUserMultiplier.ts
  apps/web/src/views/universalFarms/hooks/useMasterChefV3FarmBoosterAddress.ts
  packages/farms/src/getLegacyFarmConfig.ts
  packages/farms/src/utils.ts
  packages/smart-router/evm/v3-router/getRoutesWithValidQuote.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/getCandidatePools.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/poolTvlSelectors.ts
  packages/smart-router/evm/v4-router/queries/getV3Pools.ts
Labels: size/L

#10839 fix: Invalid volume
  apps/web/src/state/farmsV4/state/farmPools/fetcher.ts
Labels: size/XS

#10843 chore: Rewrite info v3
  apps/web/next.config.mjs
Labels: size/M

#10845 chore: Fix info page domain blocking issue
  apps/web/next.config.mjs
Labels: size/S

#10635 feat: Add position details to stableswap/v2 pool detail page
  apps/web/src/components/PositionCard/index.tsx
  apps/web/src/hooks/useTotalPriceUSD.ts
  apps/web/src/pages/stable/[address].tsx
  apps/web/src/pages/v2/pair/[[...currency]].tsx
  apps/web/src/state/farmsV4/state/accountPositions/fetcher.ts
  apps/web/src/state/farmsV4/state/poolApr/hooks.ts
  apps/web/src/state/swap/useLPApr.ts
  apps/web/src/views/AddLiquidity/ChoosePair.tsx
  apps/web/src/views/AddLiquidity/index.tsx
  apps/web/src/views/PoolDetail/components/MyPositions.tsx
  apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/index.tsx
  apps/web/src/views/universalFarms/components/PositionItem/StablePositionItem.tsx
  apps/web/src/views/universalFarms/components/PositionItem/V2PositionItem.tsx
  apps/web/src/views/universalFarms/components/PositionItem/V3PositionItem.tsx
  apps/web/src/views/universalFarms/hooks/index.ts
  apps/web/src/views/universalFarms/utils/displayApr.ts
  packages/localization/src/config/translations.json
Labels: size/L

#10847 feat: Remove vote whitelist
  apps/web/src/views/Voting/config.ts
Labels: size/XS

#10835 feat: List arb farm
  packages/farms/src/farms/arb.ts
  packages/tokens/src/constants/arb.ts
Labels: size/S

#10848 feat: Token add missing project link
  packages/tokens/src/constants/base.ts
  packages/tokens/src/constants/common.ts
  packages/tokens/src/constants/zkSync.ts
Labels: size/S

#10856 chore: Update cors list for workers
  apis/farms/package.json
  apis/proxy-worker/package.json
  apis/routing/package.json
  apis/routing/wrangler.toml
  package.json
  packages/farms/package.json
  packages/gauges/src/tests/config.test.ts
  packages/worker-utils/index.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: size/XL

#10857 fix: Use offchain quote if failed to verify on chain
  apps/web/src/hooks/useTradeVerifiedByQuoter.ts
Labels: size/XS

#10855 feat: List new pm
  packages/position-managers/src/constants/vaults/bsc.ts
Labels: size/M

#10859 fix: Aptos safepal expiration transaction
  apps/aptos/client.ts
  apps/aptos/hooks/useLedgerTimestamp.ts
  apps/aptos/hooks/useSimulationAndSendTransaction.ts
Labels: size/M

#10862 fix: wrong api query implement
  apps/web/src/pages/api/configs/farms/v2/[chain].ts
  apps/web/src/pages/api/configs/farms/v2/index.ts
Labels: size/S

#10680 fix: Filter out whitelisted merkl awards
  apps/web/src/components/Merkl/MerklSection.tsx
  apps/web/src/components/Merkl/MerklTag.tsx
  apps/web/src/hooks/useMerkl.tsx
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/pages/liquidity/index.tsx
  apps/web/src/pages/stable/[address].tsx
  apps/web/src/pages/v2/pair/[[...currency]].tsx
  apps/web/src/state/farmsV4/state/extendPools/hooks.ts
  apps/web/src/state/farmsV4/state/poolApr/fetcher.ts
  apps/web/src/state/farmsV4/state/poolApr/hooks.ts
  apps/web/src/views/AddLiquidity/components/LiquidityCardRow/index.tsx
  apps/web/src/views/AddLiquidityV3/Modal.tsx
  apps/web/src/views/AddLiquidityV3/index.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3Card.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/Farms/components/FarmTable/Row.tsx
  apps/web/src/views/Migration/components/v3/Step4.tsx
  apps/web/src/views/PoolDetail/hooks/usePoolInfo.ts
  apps/web/src/views/universalFarms/components/PositionItem/PositionInfo.tsx
Labels: size/L

#10865 feat: Add error message to aptos trx expired
  apps/aptos/hooks/useSimulationAndSendTransaction.ts
  packages/awgmi/core/src/connectors/petra.ts
  packages/awgmi/src/hooks/useSendTransaction.ts
  packages/localization/src/config/translations.json
Labels: size/M

#10866 feat: Pool api missing cache
  packages/pools/src/constants/pools/index.ts
Labels: size/M

#10868 chore: fast routing by default
  apps/web/src/components/Menu/GlobalSettings/SettingsModalV2/CustomizeRoutingTab.tsx
Labels: size/XS

#10870 chore: enable submenu for trade
  apps/web/src/components/Menu/config/config.ts
Labels: size/XS

#10871 fix: buy crypto notification layer issue on mobile
  apps/web/src/views/BuyCrypto/styles.tsx
Labels: size/XS

#10854 chore: Add api key for aptos api access
  apps/aptos/client.ts
  apps/aptos/next-env.d.ts
  apps/aptos/package.json
  packages/aptos-swap-sdk/package.json
  packages/awgmi/package.json
  packages/awgmi/src/hooks/useAccountBalances.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: size/XL

#10829 feat: Connect farm api
  apps/web/src/hooks/useFarm.ts
  apps/web/src/hooks/useV3FarmAPI.ts
  apps/web/src/pages/api/configs/farms/v2/[chain].ts
  apps/web/src/pages/api/configs/farms/v2/index.ts
  apps/web/src/pages/api/v3/[chainId]/farms/index.ts
  apps/web/src/state/farmsV3/hooks.ts
  apps/web/src/state/farmsV4/state/accountPositions/fetcher.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountV2LpDetails.ts
  apps/web/src/state/farmsV4/state/extendPools/fetcher.ts
  apps/web/src/state/farmsV4/state/extendPools/hooks.ts
  apps/web/src/state/farmsV4/state/farmPools/fetcher.ts
  apps/web/src/state/farmsV4/state/farmPools/hooks.ts
  apps/web/src/state/farmsV4/state/utils.ts
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/FeeSelector.tsx
  apps/web/src/views/Home/components/Banners/hooks/useIsRenderUserBanner.ts
  apps/web/src/views/Migration/components/bCake/MigrationFarmStep.tsx
  apps/web/src/views/PoolDetail/components/PoolInfo.tsx
  apps/web/src/views/Swap/components/HotTokenList/SwapTokenTable.tsx
  apps/web/src/views/Swap/components/HotTokenList/TradingRewardIcon.tsx
  apps/web/src/views/Swap/components/HotTokenList/constants.ts
  apps/web/src/views/Swap/components/HotTokenList/index.tsx
  apps/web/src/views/Swap/components/HotTokenList/types.ts
  apps/web/src/views/Swap/components/HotTokenList/useList.tsx
  apps/web/src/views/Swap/components/HotTokenList/utils.ts
  apps/web/src/views/Swap/hooks/useTradingRewardTokenList.tsx
  apps/web/src/views/Swap/index.tsx
  apps/web/src/views/TradingReward/config/pairs/index.tsx
  apps/web/src/views/universalFarms/components/PositionActions/V2PositionActions.tsx
  packages/farms/config/endpoint.ts
  packages/farms/constants/v3/index.ts
  packages/farms/index.test.ts
  packages/farms/scripts/build.ts
  packages/farms/src/farms/arb.ts
  packages/farms/src/farms/base.ts
  packages/farms/src/farms/bsc.ts
  packages/farms/src/farms/eth.ts
  packages/farms/src/farms/index.test.ts
  packages/farms/src/farms/index.ts
  packages/farms/src/farms/linea.ts
  packages/farms/src/farms/opBNB.ts
  packages/farms/src/farms/opBnbTestnet.ts
  packages/farms/src/farms/polygonZkEVM.ts
  packages/farms/src/farms/zkSync.ts
  packages/farms/src/fetchUniversalFarms.ts
  packages/farms/src/getLegacyFarmConfig.ts
  packages/farms/src/index.ts
  packages/farms/tests/v3.test.ts
  packages/localization/src/config/translations.json
Labels: size/XXL

#10874 fix: Pcsx user settings not considered reset and not disabled on first click
  apps/web/src/hooks/usePCSX.ts
  apps/web/src/state/user/smartRouter.ts
Labels: size/S

#10805 fix: Chain and chainId discrepancy in url when changing networks
  apps/web/src/components/Menu/index.tsx
  apps/web/src/hooks/useSwitchNetwork.ts
  apps/web/src/utils/addQueryToPath.ts
  apps/web/src/views/Home/components/Banners/OortTradingBanner.tsx
  apps/web/src/views/PancakeSquad/components/EventStepsSection/config.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/BTTWarning.tsx
Labels: size/S

#10654 fix: Is trustwallet check in ethereum object providers crash
  .changeset/ten-dogs-leave.md
  packages/wagmi/connectors/trustWallet/trustWallet.ts
Labels: size/S, Sentry

#10880 perf: Memoized combined token maps
  apps/web/src/hooks/Tokens.ts
Labels: size/M

#10858 feat: Weighted voting UI
  apps/web/public/images/cake-staking/not-enough-veCAKE.png
  apps/web/src/state/types.ts
  apps/web/src/state/voting/helpers.ts
  apps/web/src/views/Voting/CreateProposal/index.tsx
  apps/web/src/views/Voting/Proposal/Details.tsx
  apps/web/src/views/Voting/Proposal/Overview.tsx
  apps/web/src/views/Voting/Proposal/ResultType/SingleVoteResults.tsx
  apps/web/src/views/Voting/Proposal/ResultType/WeightedVoteResults.tsx
  apps/web/src/views/Voting/Proposal/Results.tsx
  apps/web/src/views/Voting/Proposal/Vote.tsx
  apps/web/src/views/Voting/Proposal/VoteType/SingleVote.tsx
  apps/web/src/views/Voting/Proposal/VoteType/VoteStyle.tsx
  apps/web/src/views/Voting/Proposal/VoteType/WeightedVote.tsx
  apps/web/src/views/Voting/Proposal/VoteType/types.ts
  apps/web/src/views/Voting/Proposal/Votes.tsx
  apps/web/src/views/Voting/components/CastVoteModal/DetailsView.tsx
  apps/web/src/views/Voting/components/CastVoteModal/MainView.tsx
  apps/web/src/views/Voting/components/CastVoteModal/index.tsx
  apps/web/src/views/Voting/components/CastVoteModal/types.ts
  apps/web/src/views/Voting/components/Proposal/VoteRow.tsx
  apps/web/src/views/Voting/config.ts
  packages/localization/src/config/translations.json
Labels: size/XL

#10844 feat: V4 Quoter Integration
  .changeset/forty-beers-carry.md
  .changeset/seven-adults-switch.md
  .changeset/tame-elephants-lick.md
  .changeset/wicked-bobcats-play.md
  apps/web/src/hooks/useV4BinPools.ts
  apps/web/src/hooks/useV4ClPools.ts
  apps/web/src/utils/convertTrade.ts
  apps/web/src/views/Swap/V3Swap/components/RouteDisplayModal.tsx
  apps/web/src/views/Swap/V3Swap/utils/exchange.ts
  packages/price-api-sdk/src/types/amm.ts
  packages/smart-router/evm/abis/IBinQuoter.ts
  packages/smart-router/evm/abis/ICLQuoter.ts
  packages/smart-router/evm/abis/IV4MixedRouteQuoter.ts
  packages/smart-router/evm/constants/v4.ts
  packages/smart-router/evm/index.test.ts
  packages/smart-router/evm/v3-router/functions/getBestRouteCombinationByQuotes.ts
  packages/smart-router/evm/v3-router/gasModel.ts
  packages/smart-router/evm/v3-router/providers/onChainQuoteProvider.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/internalTypes.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/onChainPoolProviders.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/subgraphPoolProviders.ts
  packages/smart-router/evm/v3-router/providers/quoteProviders.ts
  packages/smart-router/evm/v3-router/schema.ts
  packages/smart-router/evm/v3-router/smartRouter.ts
  packages/smart-router/evm/v3-router/types/index.ts
  packages/smart-router/evm/v3-router/types/pool.ts
  packages/smart-router/evm/v3-router/types/route.ts
  packages/smart-router/evm/v3-router/types/v4MixedQuoter.ts
  packages/smart-router/evm/v3-router/utils/encodeV4MixedRouteActions.ts
  packages/smart-router/evm/v3-router/utils/encodeV4MixedRouteParams.ts
  packages/smart-router/evm/v3-router/utils/encodeV4RouteToPath.ts
  packages/smart-router/evm/v3-router/utils/getPriceImpact.ts
  packages/smart-router/evm/v3-router/utils/pool.ts
  packages/smart-router/evm/v3-router/utils/route.ts
  packages/smart-router/evm/v3-router/utils/transformer.ts
  packages/smart-router/evm/v4-router/constants/index.ts
  packages/smart-router/evm/v4-router/constants/v4Pools.ts
  packages/smart-router/evm/v4-router/queries/getV4BinPools.ts
  packages/smart-router/evm/v4-router/queries/getV4ClPools.ts
  packages/smart-router/evm/v4-router/queries/index.ts
  packages/smart-router/evm/v4-router/schema.ts
  packages/smart-router/evm/v4-router/types/index.ts
  packages/smart-router/evm/v4-router/types/pool.ts
  packages/smart-router/package.json
  packages/swap-sdk-core/src/constants.ts
  packages/swap-sdk-core/src/fractions/price.ts
  packages/swap-sdk-core/src/index.test.ts
  packages/swap-sdk-core/src/utils.ts
  packages/universal-router-sdk/src/entities/protocols/pancakeswap.ts
  packages/v4-sdk/src/index.ts
  pnpm-lock.yaml
Labels: size/XXL

#10882 feat: Routing sdk add support for native token pools
  .changeset/seven-fishes-relax.md
  packages/routing-sdk/src/findBestTrade.ts
  packages/routing-sdk/src/graph/edge.ts
  packages/routing-sdk/src/graph/graph.ts
  packages/routing-sdk/src/graph/index.ts
  packages/routing-sdk/src/graph/priceCalculator.ts
  packages/routing-sdk/src/graph/vertice.ts
  packages/routing-sdk/src/index.test.ts
  packages/routing-sdk/src/types/graph.ts
Labels: size/M

#10883 fix: Farm API
  apps/web/src/hooks/useV3FarmAPI.ts
  apps/web/src/state/farmsV4/state/accountPositions/fetcher.ts
Labels: size/S

#10886 fix: Gauges voting crash on voting power
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/index.tsx
Labels: size/XS, Sentry

#10884 feat: Update weighted vote suggestion
  apps/web/src/views/Voting/Proposal/ResultType/WeightedVoteResults.tsx
  apps/web/src/views/Voting/Proposal/Vote.tsx
Labels: size/S

#10891 fix: missing chain query
  apps/web/src/utils/addQueryToPath.ts
Labels: size/XS

#10896 fix: 🐛 Fix the pool tvl display when amount > 1B
  apps/web/src/views/PoolDetail/components/PoolInfo.tsx
  apps/web/src/views/PoolDetail/components/PoolTvlWarning.tsx
  packages/localization/src/config/translations.json
Labels: size/M
