Repository pancakeswap/pancake-frontend, pull requests merged in 2024-03, with the labels that each got.

#9153 feat: Add v3 health indicator to liquidity details page
  apps/web/src/hooks/useSubgraphHealth.ts
  apps/web/src/pages/liquidity/[tokenId].tsx
Labels: size/XS

#9181 feat(Trading Reward): Add Edge Case Farms
  apps/web/src/views/TradingReward/components/RewardsBreakdown/index.tsx
  apps/web/src/views/TradingReward/config/pairs/edgeCasesFarms/baseFarm.ts
  apps/web/src/views/TradingReward/config/pairs/edgeCasesFarms/bscFarm.ts
  apps/web/src/views/TradingReward/config/pairs/edgeCasesFarms/lineaFarm.ts
  apps/web/src/views/TradingReward/config/pairs/edgeCasesFarms/zkEVMFarm.ts
  apps/web/src/views/TradingReward/config/pairs/edgeCasesFarms/zkSyncFarm.ts
  apps/web/src/views/TradingReward/config/pairs/index.tsx
  packages/tokens/src/constants/bsc.ts
  packages/tokens/src/constants/zkSync.ts
Labels: size/L

#9182 chore: list new farms
  packages/farms/constants/base.ts
  packages/farms/constants/bsc.ts
  packages/farms/constants/linea.ts
  packages/farms/constants/polygonZkEVM.ts
  packages/farms/constants/zkSync.ts
Labels: size/M

#9186 chore: list merkl pool on zkevm
  apps/web/src/config/constants/merklPools.json
Labels: size/S

#9183 fix: token highlight table display
  apps/web/src/state/info/constant.ts
  apps/web/src/state/info/utils.ts
  apps/web/src/views/Swap/components/HotTokenList/SwapTokenTable.tsx
Labels: size/M

#9184 fix: Trading reward page not using clientside navigation when redirect and flashes
  apps/web/next.config.mjs
  apps/web/src/pages/trading-reward/index.tsx
Labels: size/S

#9191 fix: Fail to swap for the very first time
  apps/web/src/views/Swap/V3Swap/hooks/useSwapCallback.ts
Labels: size/M

#8999 feat: Screen wallet
  apps/web/src/components/NetworkModal/NetworkModal.tsx
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/config/constants/index.ts
  apps/web/src/index.tsx
  apps/web/src/pages/_app.tsx
  apps/web/src/pages/add/[[...currency]].tsx
  apps/web/src/pages/increase/[[...currency]].tsx
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/pages/remove/[tokenId].tsx
  apps/web/src/pages/swap.tsx
  apps/web/src/pages/v2/add/[[...currency]].tsx
  apps/web/src/pages/v2/migrate/[address].tsx
  apps/web/src/pages/v2/pair/[[...currency]].tsx
  apps/web/src/pages/v2/remove/[[...currency]].tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/widgets/Modal/Modal.tsx
Labels: size/L

#9192 chore: Update changeset
  .changeset/tall-doors-work.md
Labels: size/XS

#9202 docs: Add v4 router usage example
  .changeset/tiny-candles-cry.md
  packages/smart-router/README.md
Labels: size/M

#9204 perf: Dont fetch token prices when apr calculator not open
  apps/web/src/hooks/v3/usePairTokensPrice.ts
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3ApyButton.tsx
  apps/web/src/views/V3Info/hooks/index.ts
Labels: size/S

#9207 fix: Roi calculator range price discrepancy with add liquidity
  packages/widgets-internal/roi/RangeSelector.tsx
Labels: size/XS

#9211 docs: Correct the import path from smart router package
  .changeset/brave-buses-begin.md
  packages/smart-router/README.md
Labels: size/S

#9081 fix: Cake staking week placeholder
  apps/web/src/views/CakeStaking/components/LockWeeksForm.tsx
Labels: size/S

#9105 refactor: fixed some of uikit components which were not displayed correctly in storybook
  packages/uikit/src/components/Svg/Icons/AlpIcon.tsx
  packages/uikit/src/components/Svg/Icons/BarChart.tsx
  packages/uikit/src/components/Svg/Icons/Base.tsx
  packages/uikit/src/components/Svg/Icons/Bulb.tsx
  packages/uikit/src/components/Svg/Icons/FavoriteBorder.tsx
  packages/uikit/src/components/Svg/Icons/Governance.tsx
  packages/uikit/src/components/Svg/Icons/InsertChartOutlined.tsx
  packages/uikit/src/components/Svg/Icons/LightBulb.tsx
  packages/uikit/src/components/Svg/Icons/PauseCircle.tsx
  packages/uikit/src/components/Svg/Icons/PieChart.tsx
  packages/uikit/src/components/Svg/Icons/Store.tsx
  packages/uikit/src/components/Svg/index.stories.tsx
  packages/uikit/src/components/Svg/index.tsx
  packages/uikit/src/components/Toast/Toast.stories.tsx
Labels: size/M

#9214 fix: sentry bugs patch
  apps/web/src/views/CakeStaking/hooks/useVeCakeUserInfo.ts
  apps/web/src/views/Swap/V3Swap/hooks/useWallchain.ts
  packages/smart-router/evm/v3-router/functions/getPairCombinations.ts
Labels: size/XS

#9215 feat: update gauges
  packages/farms/constants/bsc.ts
  packages/farms/constants/eth.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/bsc.ts
  packages/tokens/src/constants/eth.ts
Labels: size/L

#9222 chore: Increase fast routing opt in to 10%
  apps/web/src/config/experimentalFeatures.ts
Labels: size/XS

#9223 feat: Add opBNB tag
  apps/web/src/state/user/reducer.ts
  apps/web/src/views/TradingReward/components/PairInfo.tsx
  packages/widgets-internal/farm/components/Tags/index.tsx
Labels: size/M

#9226 chore: bump version of '@pancakeswap/tokens' to patch level
  .changeset/thirty-geckos-heal.md
Labels: size/XS

#9232 fix: remove lottery cny banner
  apps/web/public/images/lottery/cny-banner-coin.png
  apps/web/public/images/lottery/cny-banner-fruit.png
  apps/web/public/images/lottery/cny-banner-left-beak.png
  apps/web/public/images/lottery/cny-banner.png
  apps/web/public/images/lottery/cny-bunny.png
  apps/web/public/images/lottery/cny-golden-hat.png
  apps/web/public/images/lottery/cny-mobile-banner.png
  apps/web/src/views/Lottery/components/CnyBanner/CnyBanner.tsx
  apps/web/src/views/Lottery/components/CnyBanner/bannerConfig.ts
  apps/web/src/views/Lottery/components/Hero.tsx
  apps/web/src/views/Lottery/index.tsx
  apps/web/src/views/Lottery/pageSectionStyles.tsx
Labels: size/L

#9231 chore: use wallet price api on PM
  apps/web/src/views/PositionManagers/containers/PCSVaultCard.tsx
Labels: size/S

#9233 fix: serve wev3 notis to all users
  apps/web/src/config/experimentalFeatures.ts
  apps/web/src/state/notifications/reducer.ts
Labels: size/XS

#9229 feat: add new farms
  packages/farms/constants/bsc.ts
  packages/farms/constants/zkSync.ts
  packages/gauges/src/constants/config/prod.ts
  packages/pools/src/constants/pools/56.ts
  packages/tokens/src/constants/bsc.ts
  packages/tokens/src/constants/zkSync.ts
Labels: size/L

#9234 fix: Profile pic change
  apps/web/src/views/Profile/components/EditProfileModal/ChangeProfilePicView.tsx
Labels: size/XS

#9243 fix: Vercel build error under node 18.19.x
  package.json
  packages/farms/package.json
  pnpm-lock.yaml
Labels: size/L

#9230 fix: Missing translations in merkl components
  apps/web/src/components/Merkl/MerklSection.tsx
  apps/web/src/components/Merkl/MerklTag.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#9244 fix: token link
  packages/tokens/src/constants/bsc.ts
Labels: size/XS

#9252 chore: Remove v3 sg indicator from swap
  apps/web/src/pages/swap.tsx
Labels: size/XS

#9258 fix: SG indicator on top of transaction modal in mobile
  apps/web/src/components/SubgraphHealthIndicator/FloatingSubgraphHealthIndicators.tsx
  packages/uikit/src/index.ts
Labels: size/S

#9256 fix: Sg indicator not working when initial access
  apps/web/src/hooks/useSubgraphHealth.ts
Labels: size/XS

#9242 chore: Extract stable swap from smart router
  .changeset/real-stingrays-visit.md
  apps/web/package.json
  apps/web/src/pages/liquidity/index.tsx
  apps/web/src/views/AddLiquidity/AddStableLiquidity/hooks/useDerivedLPInfo.ts
  package.json
  packages/smart-router/evm/index.test.ts
  packages/smart-router/evm/index.ts
  packages/smart-router/evm/v3-router/providers/offChainQuoteProvider.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/onChainPoolProviders.ts
  packages/smart-router/evm/v3-router/utils/pool.ts
  packages/smart-router/legacy-router/getStableSwapPairs.ts
  packages/smart-router/package.json
  packages/stable-swap-sdk/package.json
  packages/stable-swap-sdk/src/amm/amm.ts
  packages/stable-swap-sdk/src/amm/getLPOutput.ts
  packages/stable-swap-sdk/src/amm/getLPOutputWithoutFee.ts
  packages/stable-swap-sdk/src/amm/getSwapOutput.test.ts
  packages/stable-swap-sdk/src/amm/getSwapOutput.ts
  packages/stable-swap-sdk/src/amm/index.ts
  packages/stable-swap-sdk/src/amm/utils.ts
  packages/stable-swap-sdk/src/constants/index.ts
  packages/stable-swap-sdk/src/constants/pools/arb.ts
  packages/stable-swap-sdk/src/constants/pools/bsc.ts
  packages/stable-swap-sdk/src/constants/pools/bscTestnet.ts
  packages/stable-swap-sdk/src/constants/pools/index.ts
  packages/stable-swap-sdk/src/constants/pools/pools.ts
  packages/stable-swap-sdk/src/index.test.ts
  packages/stable-swap-sdk/src/index.ts
  packages/stable-swap-sdk/src/types.ts
  packages/stable-swap-sdk/tsconfig.json
  packages/stable-swap-sdk/tsup.config.ts
  packages/universal-router-sdk/package.json
  packages/universal-router-sdk/test/utils/buildTrade.ts
  pnpm-lock.yaml
Labels: size/L

#9255 fix(Blog): Fix filter align
  apps/blog/components/Article/AllArticle/index.tsx
  apps/blog/components/Article/CategoriesSelector.tsx
Labels: size/S

#9260 feat(permit2-sdk): Add missing hash function and tests
  .changeset/curly-dodos-add.md
  packages/permit2-sdk/package.json
  packages/permit2-sdk/src/allowanceTransfer.test.ts
  packages/permit2-sdk/src/allowanceTransfer.ts
  packages/permit2-sdk/src/signatureTransfer.test.ts
  packages/permit2-sdk/src/signatureTransfer.ts
Labels: size/L

#9262 fix: Remove unnecessary type from PermitBatchTransferFromData
  packages/permit2-sdk/src/signatureTransfer.ts
Labels: size/XS

#9266 chore: Add quick on chain quote as offchain quoting fallback
  apps/web/src/hooks/useBestAMMTrade.ts
Labels: size/M

#9263 feat: Add fee on transfer detector functions
  .changeset/nervous-avocados-hope.md
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/hooks/useTokenFee.ts
  packages/smart-router/evm/abis/FeeOnTransferDetector.ts
  packages/smart-router/evm/fot.ts
  packages/smart-router/evm/index.test.ts
  packages/smart-router/evm/index.ts
  packages/smart-router/evm/v4-router/trade.ts
Labels: size/L

#9268 fix(tscheck): src/views/AddLiquidityV3
  apps/web/src/views/AddLiquidityV3/formViews/StableFormView.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/FeeSelector.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/PoolListItem.tsx
  apps/web/src/views/AddLiquidityV3/hooks/useCurrencyParams.ts
Labels: size/M

#9271 feat: Add new feeOnTransferDetectorAddresses for various chains
  .changeset/strange-spiders-double.md
  packages/smart-router/evm/fot.ts
Labels: size/S

#9276 fix: Crash in swap when unspported chain in wallet with non native currency
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/hooks/useNativeCurrency.ts
Labels: size/S

#9269 fix(typecheck): src/views/AffiliatesProgram
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/PoolListItem.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/AffiliateModal/NonAffiliateModal.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/AffiliateModal/index.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/Reward/HistoricalReward.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/Reward/LatestReward.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/Reward/SingleHistoricalReward.tsx
  apps/web/src/views/AffiliatesProgram/components/Dashboard/Reward/index.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useDefaultLinkId.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useShowWarningMessage.tsx
  apps/web/src/views/AffiliatesProgram/hooks/useUserClaimList.tsx
Labels: size/L

#9284 chore: temp fix for moonpay inavlid signature
  apps/web/src/views/BuyCrypto/hooks/useIframeUrlFetcher.ts
Labels: size/XS

#9289 fix(typecheck): src/views/(Ifo|Info|LimitOrder|LiqudStaking)
  apps/web/src/components/TransactionConfirmationModal/index.tsx
  apps/web/src/views/Ifos/components/IfoPoolVaultCardMobile.tsx
  apps/web/src/views/Ifos/contexts/IfoContext.tsx
  apps/web/src/views/Info/components/CurrencyLogo/index.tsx
  apps/web/src/views/Info/components/InfoTables/TransactionsTable.tsx
  apps/web/src/views/Info/hooks/useBnbPrices.ts
  apps/web/src/views/LimitOrders/components/CurrencyInputHeader.tsx
  apps/web/src/views/LimitOrders/components/LimitOrderTable/CellFormat.tsx
  apps/web/src/views/LimitOrders/components/LimitOrderTable/CurrencyFormat.tsx
  apps/web/src/views/LimitOrders/components/LimitOrderTable/DetailLimitOrderModal.tsx
  apps/web/src/views/LimitOrders/hooks/useFormattedOrderData.ts
  apps/web/src/views/LimitOrders/hooks/useGelatoLimitOrdersHistory.ts
  apps/web/src/views/LimitOrders/utils/getRatePercentageDifference.test.ts
  apps/web/src/views/LimitOrders/utils/getRatePercentageMessage.test.ts
  apps/web/src/views/LiquidStaking/hooks/useLiquidStakingApr.tsx
  apps/web/src/views/LiquidStaking/hooks/useLiquidStakingList.tsx
Labels: size/L

#9282 fix(typecheck): src/views/Home/*
  apps/web/src/views/Home/components/ColoredWordHeading.tsx
  apps/web/src/views/Home/components/FarmsPoolsRow/index.tsx
  apps/web/src/views/Home/components/IconCard.tsx
  apps/web/src/views/Home/components/SalesSection/index.tsx
  apps/web/src/views/Home/hooks/useGetTopPoolsByApr.tsx
Labels: size/M

#9281 fix(typecheck): src/views/FixedStaking/*
  apps/web/src/views/FixedStaking/components/AprCell.tsx
  apps/web/src/views/FixedStaking/components/FixedStakingCalculator.tsx
  apps/web/src/views/FixedStaking/components/FixedStakingModal.tsx
  apps/web/src/views/FixedStaking/components/FixedStakingRow.tsx
  apps/web/src/views/FixedStaking/components/StakingModalTemplate.tsx
  apps/web/src/views/FixedStaking/hooks/useSelectedPeriod.tsx
  apps/web/src/views/FixedStaking/hooks/useStakedPools.ts
Labels: size/L

#9280 fix(typecheck): src/views/Farms*
  apps/web/src/components/Logo/ChainLogo.tsx
  apps/web/src/hooks/useContract.ts
  apps/web/src/utils/getLiquidityUrlPathParts.ts
  apps/web/src/views/BuyCrypto/index.tsx
  apps/web/src/views/FarmAuction/components/AuctionDetailsCard/index.tsx
  apps/web/src/views/FarmAuction/components/AuctionHistory.tsx
  apps/web/src/views/FarmAuction/components/AuctionLeaderboard/index.tsx
  apps/web/src/views/FarmAuction/components/AuctionTimer.tsx
  apps/web/src/views/FarmAuction/components/CongratulationsCard.tsx
  apps/web/src/views/FarmAuction/components/NotWhitelistedNotice.tsx
  apps/web/src/views/FarmAuction/components/PlaceBidModal.tsx
  apps/web/src/views/FarmAuction/components/ReclaimBidCard.tsx
  apps/web/src/views/FarmAuction/hooks/useCongratulateAuctionWinner.tsx
  apps/web/src/views/FarmAuction/hooks/useCurrentFarmAuction.ts
  apps/web/src/views/FarmAuction/hooks/useFarmAuction.ts
  apps/web/src/views/FarmAuction/hooks/useReclaimAuctionBid.ts
  apps/web/src/views/FarmAuction/hooks/useV3FarmAuctionConfig.ts
  apps/web/src/views/FarmAuction/hooks/useWhitelistedAddresses.ts
  apps/web/src/views/Farms/Farms.tsx
  apps/web/src/views/Farms/components/FarmCard/FarmCard.tsx
  apps/web/src/views/Farms/components/FarmCard/StakeAction.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/CardActionsContainer.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3CardList.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3StakeAndUnStake.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
  apps/web/src/views/Farms/components/FarmTypesFilter.tsx
  apps/web/src/views/Farms/components/MultiChainHarvestModal.tsx
  apps/web/src/views/Farms/components/YieldBooster/components/ActionButton.tsx
  apps/web/src/views/Farms/components/YieldBooster/components/BCakeCalculator.tsx
  apps/web/src/views/Farms/components/YieldBooster/components/BCakeLockedDuration.tsx
  apps/web/src/views/Farms/components/YieldBooster/components/CreateProxyButton.tsx
  apps/web/src/views/Farms/components/YieldBooster/components/MigrateActionButton.tsx
  apps/web/src/views/Farms/components/YieldBooster/components/ProxyFarmContainer.tsx
  apps/web/src/views/Farms/components/YieldBooster/hooks/useBoostMultiplier.ts
  apps/web/src/views/Farms/components/YieldBooster/hooks/useGetBoostedAPR.ts
  apps/web/src/views/Farms/components/YieldBooster/hooks/useYieldBoosterState.ts
  apps/web/src/views/Farms/hooks/getNonBscVaultFee.ts
  apps/web/src/views/Farms/hooks/useBCakeProxyBalance.ts
  apps/web/src/views/Farms/hooks/useBCakeProxyContractAddress.ts
  apps/web/src/views/Farms/hooks/useFarmCProxyAddress.ts
  apps/web/src/views/Farms/hooks/useFetchOraclePrice.ts
  apps/web/src/views/Farms/hooks/useFirstTimeCrossFarming.ts
  apps/web/src/views/Farms/hooks/useMultiChainHarvestModal.tsx
  apps/web/src/views/Farms/hooks/useNonBscHarvestFarm.ts
  apps/web/src/views/Farms/hooks/useUserBoosterStatus.ts
  apps/web/src/views/Farms/hooks/v3/useFarmV3Actions.tsx
Labels: size/XL

#9290 fix(typecheck): src/views/Lottery
  apps/web/src/state/lottery/hooks.ts
  apps/web/src/state/lottery/selectors.ts
  apps/web/src/utils/calls/estimateGas.ts
  apps/web/src/views/Lottery/components/AllHistoryCard/RoundSwitcher.tsx
  apps/web/src/views/Lottery/components/AllHistoryCard/index.tsx
  apps/web/src/views/Lottery/components/BuyTicketsModal/BuyTicketsModal.tsx
  apps/web/src/views/Lottery/components/BuyTicketsModal/generateTicketNumbers.tsx
  apps/web/src/views/Lottery/components/ClaimPrizesModal/ClaimPrizesInner.tsx
  apps/web/src/views/Lottery/components/ClaimPrizesModal/index.tsx
  apps/web/src/views/Lottery/components/Countdown/index.tsx
  apps/web/src/views/Lottery/components/NextDrawCard.tsx
  apps/web/src/views/Lottery/components/PreviousRoundCard/Body.tsx
  apps/web/src/views/Lottery/components/PreviousRoundCard/Footer.tsx
  apps/web/src/views/Lottery/components/PreviousRoundCard/FooterExpanded.tsx
  apps/web/src/views/Lottery/components/RewardBracketDetail.tsx
  apps/web/src/views/Lottery/components/RewardBrackets.tsx
  apps/web/src/views/Lottery/components/TicketNumber.tsx
  apps/web/src/views/Lottery/components/ViewTicketsModal/CurrentRoundTicketsInner.tsx
  apps/web/src/views/Lottery/components/ViewTicketsModal/PreviousRoundTicketsInner.tsx
  apps/web/src/views/Lottery/components/ViewTicketsModal/index.tsx
  apps/web/src/views/Lottery/components/WinningNumbers.tsx
  apps/web/src/views/Lottery/components/YourHistoryCard/index.tsx
  apps/web/src/views/Lottery/hooks/useGetUnclaimedRewards.ts
  apps/web/src/views/Lottery/hooks/useNextEventCountdown.ts
  apps/web/src/views/Lottery/hooks/useShowMoreUserRounds.ts
Labels: size/L

#9293 fix: TS errors under src/views/Voting
  apps/web/src/views/Voting/Proposal/Overview.tsx
  apps/web/src/views/Voting/components/Proposal/VoteRow.tsx
  apps/web/src/views/Voting/components/Proposals/Proposals.tsx
  apps/web/src/views/Voting/helpers.ts
Labels: size/S

#9294 fix: TS errors under src/views/V3Info
  apps/web/src/views/V3Info/components/BarChart/alt.tsx
  apps/web/src/views/V3Info/components/DensityChart/CurrentPriceLabel.tsx
  apps/web/src/views/V3Info/components/DensityChart/CustomToolTip.tsx
  apps/web/src/views/V3Info/components/DensityChart/index.tsx
  apps/web/src/views/V3Info/components/LineChart/alt.tsx
  apps/web/src/views/V3Info/components/TopTokenMovers/index.tsx
  apps/web/src/views/V3Info/data/protocol/derived.ts
  apps/web/src/views/V3Info/utils/numbers.ts
Labels: size/M

#9295 fix: TS errors under src/views/TradingReward
  apps/web/src/views/TradingReward/components/Leaderboard/MyRank.tsx
  apps/web/src/views/TradingReward/components/Leaderboard/index.tsx
  apps/web/src/views/TradingReward/config/pairs/edgeCasesFarms/baseFarm.ts
  apps/web/src/views/TradingReward/config/pairs/edgeCasesFarms/bscFarm.ts
  apps/web/src/views/TradingReward/config/pairs/edgeCasesFarms/lineaFarm.ts
  apps/web/src/views/TradingReward/config/pairs/edgeCasesFarms/zkEVMFarm.ts
  apps/web/src/views/TradingReward/config/pairs/edgeCasesFarms/zkSyncFarm.ts
  apps/web/src/views/TradingReward/hooks/useClaimAllReward.tsx
Labels: size/S

#9291 chore: Opt in 20% for fast routing
  apps/web/src/config/experimentalFeatures.ts
Labels: size/XS

#9292 fix(typecheck): src/views/Migration
  apps/web/src/hooks/useCatchTxError.tsx
  apps/web/src/state/farms/hooks.ts
  apps/web/src/state/farms/selectors.ts
  apps/web/src/state/transactions/hooks.tsx
  apps/web/src/views/Farms/hooks/useUnstakeFarms.ts
  apps/web/src/views/Migration/components/Farm/Cells/Unstake.tsx
  apps/web/src/views/Migration/components/MigrationFarmTable.tsx
  apps/web/src/views/Migration/components/ProgressSteps.tsx
  apps/web/src/views/Migration/components/v3/OldFarmRow.tsx
  apps/web/src/views/Migration/components/v3/Step1.tsx
  apps/web/src/views/Migration/components/v3/Step2.tsx
  apps/web/src/views/Migration/components/v3/Step4.tsx
  apps/web/src/views/Migration/components/v3/UnstakeButton.tsx
Labels: size/L

#9288 feat: List new farms and pools
  .changeset/nice-dolphins-marry.md
  packages/farms/constants/bsc.ts
  packages/gauges/src/constants/config/prod.ts
  packages/pools/src/constants/pools/56.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/L

#9299 fix(typecheck): src/views/Nft
  apps/web/src/state/nftMarket/helpers.ts
  apps/web/src/state/nftMarket/hooks.ts
  apps/web/src/state/nftMarket/types.ts
  apps/web/src/utils/index.ts
  apps/web/src/views/Nft/market/ActivityHistory/ActivityHistory.tsx
  apps/web/src/views/Nft/market/ActivityHistory/utils/fetchActivityNftMetadata.tsx
  apps/web/src/views/Nft/market/ActivityHistory/utils/sortActivity.tsx
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/ActivityCard.tsx
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/OwnerCard.tsx
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/index.tsx
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/ForSaleTableCard/index.tsx
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/MainPancakeBunnyCard.tsx
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/index.tsx
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/shared/DetailsCard.tsx
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/shared/MoreFromThisCollection.tsx
  apps/web/src/views/Nft/market/Collection/IndividualNFTPage/shared/PropertiesCard.tsx
  apps/web/src/views/Nft/market/Collection/Items/CollectionNfts.tsx
  apps/web/src/views/Nft/market/Collection/Items/CollectionWrapper.tsx
  apps/web/src/views/Nft/market/Collection/Items/Filters.tsx
  apps/web/src/views/Nft/market/Collection/Items/PancakeBunniesCollectionNfts.tsx
  apps/web/src/views/Nft/market/Home/Newest.tsx
  apps/web/src/views/Nft/market/components/Activity/ActivityRow.tsx
  apps/web/src/views/Nft/market/components/Activity/MobileModal.tsx
  apps/web/src/views/Nft/market/components/BannerHeader/index.tsx
  apps/web/src/views/Nft/market/components/BuySellModals/BuyModal/ReviewStage.tsx
  apps/web/src/views/Nft/market/components/BuySellModals/BuyModal/index.tsx
  apps/web/src/views/Nft/market/components/BuySellModals/SellModal/EditStage.tsx
  apps/web/src/views/Nft/market/components/BuySellModals/SellModal/SellStage.tsx
  apps/web/src/views/Nft/market/components/BuySellModals/SellModal/SetPriceStage.tsx
  apps/web/src/views/Nft/market/components/BuySellModals/SellModal/TransferStage.tsx
  apps/web/src/views/Nft/market/components/BuySellModals/SellModal/index.tsx
  apps/web/src/views/Nft/market/components/BuySellModals/shared/TransactionConfirmed.tsx
  apps/web/src/views/Nft/market/components/CollectibleCard/CardBody.tsx
  apps/web/src/views/Nft/market/components/CollectibleCard/CollectibleLinkCard.tsx
  apps/web/src/views/Nft/market/components/CollectibleCard/styles.tsx
  apps/web/src/views/Nft/market/components/Filters/ListCollectionFilter/index.tsx
  apps/web/src/views/Nft/market/components/Filters/ListTraitFilter/index.tsx
  apps/web/src/views/Nft/market/components/MarketPageTitle.tsx
  apps/web/src/views/Nft/market/components/NFTMedia.tsx
  apps/web/src/views/Nft/market/components/ProfileNftModal.tsx
  apps/web/src/views/Nft/market/hooks/useAllPancakeBunnyNfts.ts
  apps/web/src/views/Nft/market/hooks/useCollectionNfts.tsx
  apps/web/src/views/Nft/market/hooks/useGetLowestPrice.ts
  apps/web/src/views/Nft/market/hooks/usePancakeBunnyCheapestNfts.tsx
  apps/web/src/views/Nft/market/hooks/usePancakeBunnyOnSaleNfts.tsx
Labels: size/XL

#9298 fix: Total ifo sold info in cake-staking
  packages/ifos/src/utils/getIfoConfig.ts
Labels: size/XS

#9296 fix: TS errors under src/views/TradingCompetition
  apps/web/src/views/TradingCompetition/EasterCompetition.tsx
  apps/web/src/views/TradingCompetition/FanTokenCompetition.tsx
  apps/web/src/views/TradingCompetition/MoDCompetition.tsx
  apps/web/src/views/TradingCompetition/MoboxCompetition.tsx
  apps/web/src/views/TradingCompetition/components/BattleCta/index.tsx
  apps/web/src/views/TradingCompetition/components/ClaimModal/index.tsx
  apps/web/src/views/TradingCompetition/components/Countdown/Step.tsx
  apps/web/src/views/TradingCompetition/components/Countdown/Timer.tsx
  apps/web/src/views/TradingCompetition/components/Countdown/index.tsx
  apps/web/src/views/TradingCompetition/components/PrizesInfo/PrizesGrid/PrizesGrid.tsx
  apps/web/src/views/TradingCompetition/components/RegisterModal/MakeProfile.tsx
  apps/web/src/views/TradingCompetition/components/RegisterModal/RegisterWithProfile.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/Podium/PodiumWithParticipants.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/Podium/TeamPodiumIcon.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/Podium/index.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TeamRanks.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TopTradersCard/ExpandedGridItem.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TopTradersCard/GridItem.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TopTradersCard/TopTradersGrid.tsx
  apps/web/src/views/TradingCompetition/components/TeamRanks/TopTradersCard/index.tsx
Labels: size/L

#9300 fix: TS errors under src/views/Pools
  apps/web/src/hooks/useContract.ts
  apps/web/src/views/Pools/components/AutoEarningsBreakdown.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/FeeSummary.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/RecentCakeProfitRow.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/UnstakingFeeCountdownRow.tsx
  apps/web/src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
  apps/web/src/views/Pools/components/LockedPool/Buttons/AddCakeButton.tsx
  apps/web/src/views/Pools/components/LockedPool/Common/ConvertToLock.tsx
  apps/web/src/views/Pools/components/LockedPool/Common/Overview/BalanceRow.tsx
  apps/web/src/views/Pools/components/LockedPool/Common/Overview/DateRow.tsx
  apps/web/src/views/Pools/components/LockedPool/Common/Overview/index.tsx
  apps/web/src/views/Pools/components/LockedPool/Modals/AddAmountModal.tsx
  apps/web/src/views/Pools/components/LockedPool/Modals/ExtendDurationModal.tsx
  apps/web/src/views/Pools/components/LockedPool/Modals/RoiCalculatorModalProvider.tsx
  apps/web/src/views/Pools/components/LockedPool/hooks/useAvgLockDuration.tsx
  apps/web/src/views/Pools/components/Modals/CollectModal.tsx
  apps/web/src/views/Pools/components/PoolCard/CardActions/index.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/AutoHarvest.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/Harvest.tsx
  apps/web/src/views/Pools/components/PoolsTable/PoolRow.tsx
  apps/web/src/views/Pools/components/RevenueSharing/BenefitsModal/ClaimButton.tsx
  apps/web/src/views/Pools/components/RevenueSharing/BenefitsModal/LockedBenefits.tsx
  apps/web/src/views/Pools/helpers.tsx
  apps/web/src/views/Pools/hooks/useApprove.tsx
  apps/web/src/views/Pools/hooks/useWithdrawalFeeTimer.ts
Labels: size/L

#9303 fix: Snapshot cors error results undefined in benefit card
  apps/web/src/views/CakeStaking/components/BenefitCard.tsx
  apps/web/src/views/CakeStaking/hooks/useSnapshotProposalsCount.ts
Labels: size/S

#9302 fix: Dont remove dot from total ifo sold
  packages/ifos/src/utils/getIfoConfig.ts
Labels: size/XS

#9305 feat: Update config
  .changeset/bright-gorillas-admire.md
  packages/farms/constants/arb.ts
  packages/farms/constants/base.ts
  packages/farms/constants/bsc.ts
  packages/farms/constants/eth.ts
  packages/farms/constants/linea.ts
  packages/gauges/src/constants/config/prod.ts
  packages/pools/src/constants/pools/56.ts
  packages/tokens/src/constants/base.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/L, automerge

#9205 chore: Update ts error
  apps/web/src/config/constants/types.ts
  apps/web/src/hooks/Tokens.ts
  apps/web/src/hooks/useV3Pools.ts
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButton.tsx
  apps/web/src/views/Swap/MMLinkPools/hooks/useDerivedSwapInfoWithMM.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useGetRFQTrade.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useIsMMQuotingPair.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMOrderBookTrade.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMParam.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMQuoteCountDown.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMTradeInfo.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useSwapCallback.ts
  apps/web/src/views/Swap/MMLinkPools/types.ts
  apps/web/src/views/Swap/MMLinkPools/utils/exchange.ts
  apps/web/src/views/Swap/V3Swap/components/TransactionConfirmSwapContent.tsx
  apps/web/src/views/Swap/V3Swap/containers/ConfirmSwapModal.tsx
  apps/web/src/views/Swap/V3Swap/containers/FormMain.tsx
  apps/web/src/views/Swap/V3Swap/containers/RiskCheck.tsx
  apps/web/src/views/Swap/V3Swap/containers/TradeDetails.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useSlippageAdjustedAmounts.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSwapInputError.ts
  apps/web/src/views/Swap/V3Swap/utils/exchange.ts
  apps/web/src/views/Swap/components/AdvancedSwapDetails.tsx
  apps/web/src/views/Swap/components/SwapRoute.tsx
  apps/web/src/views/Teams/components/TeamCard.tsx
  apps/web/src/views/TradingCompetition/index.tsx
  apps/web/src/views/TradingReward/components/Leaderboard/MyRank.tsx
  apps/web/src/views/TradingReward/components/Leaderboard/index.tsx
  apps/web/src/views/V3Info/components/DensityChart/CurrentPriceLabel.tsx
  apps/web/src/views/V3Info/components/DensityChart/index.tsx
  apps/web/src/views/Voting/Proposal/Overview.tsx
  apps/web/src/views/Voting/components/Proposal/VoteRow.tsx
  apps/web/src/views/Voting/components/Proposals/Proposals.tsx
  packages/smart-router/evm/v3-router/utils/getExecutionPrice.ts
Labels: Delayed Release, size/L

#9228 fix: Use thegraph for bsc price info
  apps/web/src/views/V3Info/hooks/index.ts
Labels: size/XS

#9312 chore: Price api endpoint update
  .changeset/big-pandas-raise.md
  apps/web/src/config/constants/endpoints.ts
  packages/smart-router/evm/v3-router/providers/getCommonTokenPrices.ts
  packages/utils/getCurrencyPrice.ts
Labels: size/S

#9314 refactor: Update external link to Pancake Protectors game landing page and project logo URLs to new domain for consistency.
  apps/web/src/views/Home/components/Banners/PancakeProtectorBanner.tsx
  packages/games/src/constants/games/example.ts
  packages/games/src/constants/games/pancakeProtectors.ts
Labels: size/M

#9304 fix(typecheck): src/views/Swap
  apps/web/src/views/Swap/MMLinkPools/apis/index.ts
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButtonV2.tsx
  apps/web/src/views/Swap/MMLinkPools/hooks/useDerivedSwapInfoWithMM.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useGetRFQTrade.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useIsMMSupportChain.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMTradeInfo.ts
  apps/web/src/views/Swap/V3Swap/containers/FormMain.tsx
  apps/web/src/views/Swap/V3Swap/containers/TradeDetails.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useSwapInputError.ts
  apps/web/src/views/Swap/components/AdvancedSwapDetails.tsx
  apps/web/src/views/Swap/components/Chart/BasicChart.tsx
  apps/web/src/views/Swap/components/Chart/NoChartAvailable.tsx
  apps/web/src/views/Swap/components/Chart/TradingViewChart.tsx
  apps/web/src/views/Swap/components/ConfirmSwapModalContainer.tsx
  apps/web/src/views/Swap/components/HotTokenList/index.tsx
  apps/web/src/views/Swap/components/RouterViewer.tsx
  apps/web/src/views/Swap/components/SwapRoute.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/Acknowledgement.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/index.tsx
  apps/web/src/views/Swap/hooks/useTradingRewardTokenList.tsx
  packages/smart-router/evm/v3-router/types/trade.ts
  packages/smart-router/evm/v3-router/utils/transformer.ts
  packages/smart-router/evm/v4-router/transformer.ts
Labels: size/L

#9315 fix(typecheck): src/views/TradingCompetition
  apps/web/src/hooks/useUsernameWithVisibility.ts
  apps/web/src/views/TradingCompetition/components/RegisterModal/ReactivateProfile.tsx
  apps/web/src/views/TradingCompetition/components/YourScore/AchievementPoints.tsx
  apps/web/src/views/TradingCompetition/components/YourScore/CardUserInfo.tsx
  apps/web/src/views/TradingCompetition/components/YourScore/UserPrizeGridDollar.tsx
  apps/web/src/views/TradingCompetition/easter/components/PrizesInfo/PrizesGrid/EasterPrizesGrid.tsx
  apps/web/src/views/TradingCompetition/easter/components/YourScore/EasterUserPrizeGrid.tsx
  apps/web/src/views/TradingCompetition/helpers.ts
  apps/web/src/views/TradingCompetition/mobox/components/YourScore/MoboxUserPrizeGrid.tsx
  apps/web/src/views/TradingCompetition/mobox/components/YourScore/MoboxYourScore.tsx
  apps/web/src/views/TradingCompetition/mod/components/YourScore/ModUserPrizeGrid.tsx
  apps/web/src/views/TradingCompetition/mod/components/YourScore/ModYourScore.tsx
Labels: size/L

#9317 fix(typecheck): src/views/Profile
  apps/web/src/views/Nft/market/components/BuySellModals/SellModal/index.tsx
  apps/web/src/views/Nft/market/components/ProfileNftModal.tsx
  apps/web/src/views/Profile/components/Achievements/AchievementRow/index.tsx
  apps/web/src/views/Profile/components/Achievements/ClaimPointsCallout.tsx
  apps/web/src/views/Profile/components/Achievements/index.tsx
  apps/web/src/views/Profile/components/ActivityHistory/index.tsx
  apps/web/src/views/Profile/components/EditProfileModal/ApproveCakeView.tsx
  apps/web/src/views/Profile/components/EditProfileModal/StartView.tsx
  apps/web/src/views/Profile/components/EditProfileModal/index.tsx
  apps/web/src/views/Profile/components/EditProfileModal/reducer.ts
  apps/web/src/views/Profile/components/UnconnectedProfileNfts.tsx
  apps/web/src/views/Profile/components/UserNfts.tsx
  apps/web/src/views/ProfileCreation/ConfirmProfileCreationModal.tsx
  apps/web/src/views/ProfileCreation/Header.tsx
  apps/web/src/views/ProfileCreation/Mint.tsx
  apps/web/src/views/ProfileCreation/ProfilePicture.tsx
  apps/web/src/views/ProfileCreation/SelectionCard.tsx
  apps/web/src/views/ProfileCreation/Steps.tsx
  apps/web/src/views/ProfileCreation/UserName.tsx
  apps/web/src/views/ProfileCreation/contexts/ProfileCreationProvider.tsx
  apps/web/src/views/ProfileCreation/contexts/hook.ts
  apps/web/src/views/ProfileCreation/contexts/types.ts
Labels: size/L

#9324 fix: update ag eur token symbol and name
  packages/farms/constants/bsc.ts
  packages/farms/constants/eth.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/bsc.ts
  packages/tokens/src/constants/eth.ts
Labels: size/S

#9327 chore: Turn strict null check on
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/tsconfig.build.json
  apps/web/tsconfig.test.json
Labels: size/S

#9316 fix: SG Indicator initally shows delayed in chains other than bsc with wrong text and block
  apps/web/src/components/SubgraphHealthIndicator/FloatingSubgraphHealthIndicators.tsx
  apps/web/src/components/SubgraphHealthIndicator/SubgraphHealthIndicator.tsx
  apps/web/src/hooks/useSubgraphHealth.ts
  packages/localization/src/config/translations.json
Labels: size/M

#9328 feat: Support getting input by exact output
  .changeset/kind-glasses-mate.md
  packages/smart-router/evm/v3-router/providers/offChainQuoteProvider.ts
  packages/smart-router/evm/v4-router/graph/graph.ts
  packages/smart-router/evm/v4-router/trade.ts
  packages/smart-router/evm/v4-router/utils/getBetterTrade.ts
  packages/smart-router/evm/v4-router/utils/groupPoolsPyType.ts
  packages/smart-router/evm/v4-router/utils/index.ts
  packages/v3-sdk/src/entities/pool.ts
Labels: size/L

#9329 chore: Remove ts check workflow
  .github/workflows/tsCheck.yml
Labels: size/M

#9331 chore: Bump tokens pkg
  .changeset/fair-starfishes-live.md
Labels: size/XS

#9335 fix: v3 Roi calculator display
  packages/widgets-internal/roi/aprHelper.ts
  packages/widgets-internal/roi/hooks/useRate.ts
Labels: size/S

#9340 chore: update X post
  apps/web/src/views/Home/components/CommunitySection/TwitterCards.tsx
Labels: size/S

#9344 chore: add nfp and nmt warning config
  apps/web/src/config/constants/swapWarningTokens.ts
  apps/web/src/config/constants/warningTokens.ts
  apps/web/src/views/Swap/components/SwapWarningModal/56/NFPWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/56/NMTWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/56/index.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#9345 fix: use dev endpoint
  apps/web/src/config/constants/endpoints.ts
Labels: size/XS

#9338 feat: Remove unused icon
  apps/web/src/components/Menu/config/config.ts
Labels: size/XS, automerge

#9352 fix: Not getting the optimal output with exact out
  .changeset/metal-doors-promise.md
  packages/smart-router/evm/v4-router/graph/graph.ts
Labels: size/S

#9351 feat: Remove TWAMM
  apps/web/src/views/LandingV4/config/index.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#9353 feat: Sort V4 tag in front
  apps/blog/components/Article/CategoriesSelector.tsx
Labels: size/XS, automerge

#9356 feat: Update Blog
  apps/blog/hooks/useAllArticle.ts
  apps/web/src/views/LandingV4/components/NewsAndEvents/BlogCard.tsx
  apps/web/src/views/LandingV4/components/NewsAndEvents/Featured.tsx
Labels: size/M, automerge

#9347 chore: Change translation text in staking
  apps/web/src/views/FixedStaking/components/UnstakeBeforeEndedModal.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#9358 feat: Featured with ids
  apps/web/src/views/LandingV4/components/NewsAndEvents/Featured.tsx
  apps/web/src/views/LandingV4/hooks/useAllArticle.ts
Labels: size/M

#9361 fix(PositionMgr): Fix ALPACA StrategyInfo url
  packages/position-managers/src/constants/vaults/bsc.ts
Labels: size/XS

#9339 feat: Pause toast hidden timer when page is not focused
  packages/uikit/src/contexts/ToastsContext/Provider.tsx
Labels: size/L

#9360 fix: Lottery ticket match display
  apps/web/src/views/Lottery/components/TicketNumber.tsx
Labels: size/XS

#9359 fix: Revoke transaction text
  apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalStateV2.ts
  packages/localization/src/config/translations.json
Labels: size/XS

#9367 feat: Store historical v3 pools tvl data
  apis/routing/package.json
  apis/routing/src/pools.ts
  apis/routing/src/subgraphPoolBackup.ts
  pnpm-lock.yaml
Labels: size/M

#9368 feat: add extend lock log
  apps/web/src/views/CakeStaking/hooks/useContractWrite/useWriteIncreaseLockAmountCallback.tsx
  apps/web/src/views/CakeStaking/hooks/useContractWrite/useWriteIncreaseLockWeeksCallback.tsx
Labels: size/M

#9274 fix: mm trade steps & lock
  .vscode/settings.json
  apps/web/src/hooks/useApproveCallback.ts
  apps/web/src/hooks/usePermit2.ts
  apps/web/src/hooks/usePermit2Requires.ts
  apps/web/src/hooks/useThrottleFn.ts
  apps/web/src/utils/client.ts
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButtonV2.tsx
  apps/web/src/views/Swap/MMLinkPools/hooks/useApprove.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMConfirmModalState.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useSwapCallback.ts
  apps/web/src/views/Swap/V3Swap/containers/CommitButton.tsx
  apps/web/src/views/Swap/V3Swap/containers/ConfirmSwapModalV2.tsx
  apps/web/src/views/Swap/V3Swap/containers/MMCommitButtonV2.tsx
  apps/web/src/views/Swap/V3Swap/containers/SwapCommitButtonV2.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useAllTypeBestTrade.ts
  apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalStateV2.ts
  apps/web/src/views/Swap/V3Swap/index.tsx
  apps/web/src/views/Swap/V3Swap/types.ts
  apps/web/src/views/Swap/components/SwapTransactionErrorContent.tsx
  packages/localization/src/config/translations.json
Labels: size/XL

#9357 refactor: Update onramp endpoints, remove no used userip
  apps/web/src/components/FiatOnRampModal/FiatOnRampModal.tsx
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/pages/buy-crypto/index.tsx
  apps/web/src/state/buyCrypto/actions.ts
  apps/web/src/state/buyCrypto/hooks.ts
  apps/web/src/state/buyCrypto/reducer.ts
  apps/web/src/views/BuyCrypto/hooks/usePriceQuoter.ts
  apps/web/src/views/BuyCrypto/hooks/useProviderAvailability.ts
  apps/web/src/views/BuyCrypto/index.tsx
Labels: size/L

#9275 feat: open 5%
  apps/web/src/config/experimentalFeatures.ts
Labels: size/XS

#9369 chore: shows the staking token website
  apps/aptos/components/Pools/components/PoolCard/PoolStatsInfo.tsx
  apps/aptos/components/Pools/hooks/useAddressPriceMap.ts
  apps/aptos/config/constants/tokens/1.ts
  packages/localization/src/config/translations.json
Labels: size/M

#9362 chore: list new bCakeWrapper PM vault on arb
  apps/web/src/views/PositionManagers/components/AddLiquidity.tsx
  apps/web/src/views/PositionManagers/components/AprButton.tsx
  apps/web/src/views/PositionManagers/components/DuoTokenVaultCard.tsx
  apps/web/src/views/PositionManagers/components/YieldInfo.tsx
  apps/web/src/views/PositionManagers/hooks/useApr.ts
  packages/localization/src/config/translations.json
  packages/position-managers/src/constants/vaults/arb.ts
Labels: size/L

#9355 feat: New Phishing banner
  apps/web/src/components/PhishingWarningBanner/Countdown.tsx
  apps/web/src/components/PhishingWarningBanner/Step1.tsx
  apps/web/src/components/PhishingWarningBanner/Step2.tsx
  apps/web/src/components/PhishingWarningBanner/index.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#9377 style: Fix mobile horizontal scroll issue
  apps/web/src/style/Global.tsx
Labels: size/XS

#9375 feat: Move finished pools
  .changeset/little-spies-judge.md
  packages/pools/src/constants/pools/204.ts
  packages/pools/src/constants/pools/56.ts
Labels: size/M, automerge

#9337 fix: v3 Roi calculator display part2
  packages/widgets-internal/roi/Details.tsx
  packages/widgets-internal/roi/RoiCalculator.tsx
  packages/widgets-internal/roi/aprHelper.ts
  packages/widgets-internal/roi/constants.ts
  packages/widgets-internal/roi/hooks/useRate.ts
  packages/widgets-internal/roi/hooks/useRoi.ts
Labels: size/L

#9379 feat: Add data rotation to tvl cache by date
  apis/routing/src/subgraphPoolBackup.ts
Labels: size/L

#9380 chore: list new farm and gauges
  packages/farms/constants/polygonZkEVM.ts
  packages/gauges/src/constants/config/prod.ts
Labels: size/S

#9388 chore: list via pool
  packages/pools/src/constants/pools/56.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/S

#9387 feat: Nft Avatar add background color
  apps/web/src/views/Nft/market/components/BannerHeader/AvatarImage.tsx
  apps/web/src/views/Nft/market/components/CollectibleCard/CollectionCard.tsx
Labels: size/XS

#9389 feat: Phishing Banner add timer check
  packages/utils/user/phishingBanner.ts
Labels: size/XS

#9382 fix: remove redundant character
  apps/web/src/views/Info/components/InfoSearch/index.tsx
Labels: size/XS

#9390 chore: Fast routing opt in 30%
  apps/web/src/config/experimentalFeatures.ts
Labels: size/XS

#9386 feat: Aptos pool add tooltip
  apps/aptos/components/Farms/components/FarmCard/CardHeading.tsx
  apps/aptos/components/Farms/components/FarmCard/FarmCard.tsx
  apps/aptos/components/Farms/components/FarmTable/Farm.tsx
  apps/aptos/components/Farms/components/FarmTable/FarmTable.tsx
  apps/aptos/components/Farms/components/FarmTable/PoolEarnAptTooltips.tsx
  apps/aptos/components/Farms/hooks/useCheckIsUserIpPass.ts
  apps/aptos/components/Farms/hooks/useIsAptRewardFarm.ts
  apps/aptos/components/Pools/components/PoolTable/ActionPanel.tsx
  apps/aptos/components/Pools/components/PoolTable/AptRewardTooltip.tsx
  apps/aptos/components/Pools/components/PoolTable/PoolRow.tsx
  apps/aptos/components/Pools/components/PoolTable/UsUserAptRewardTooltips.tsx
  apps/aptos/components/Pools/hooks/useIsAptosRewardToken.ts
  apps/aptos/components/Pools/index.tsx
  apps/aptos/config/constants/aptRewardFarm/1.ts
  apps/aptos/config/constants/aptRewardFarm/2.ts
  apps/aptos/config/constants/aptRewardFarm/index.ts
  apps/aptos/config/constants/aptRewardFarm/type.ts
  apps/web/src/__tests__/translations.test.ts
  packages/localization/src/config/translations.json
  packages/widgets-internal/farm/types.ts
  packages/widgets-internal/pool/Cells/EarningCell.tsx
  packages/widgets-internal/pool/Cells/NameCell.tsx
  packages/widgets-internal/pool/PoolCard.tsx
  packages/widgets-internal/pool/PoolCardHeader.tsx
  packages/widgets-internal/pool/PoolsTable/HarvestAction.tsx
  packages/widgets-internal/pool/types.ts
  packages/widgets-internal/pool/withCardActions.tsx
  packages/widgets-internal/pool/withCollectModal.tsx
Labels: size/XL

#9392 chore: list new PM on ARB
  packages/position-managers/src/constants/vaults/arb.ts
Labels: size/M

#9391 chore: remove MEOW giftBox and link
  apps/web/src/components/CurrencyInputPanel/index.tsx
Labels: size/M

#9381 fix: max tick check on v3 sdk
  apps/web/src/hooks/v3/useV3DerivedInfo.ts
Labels: size/S

#9393 chore: check v3 max tick part2
  apps/web/src/hooks/v3/useV3DerivedInfo.ts
Labels: size/S

#9394 fix: liq range select by nearset tickSpacing
  apps/web/src/hooks/v3/useV3DerivedInfo.ts
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/RangeSelector.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/form/hooks/useRangeHopCallbacks.ts
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#9140 feat: web3inbox package update
  apps/web/package.json
  apps/web/src/components/Menu/GlobalSettings/WebNotiToggle.tsx
  apps/web/src/components/NotificationOnBoardingButton.tsx
  apps/web/src/hooks/useSubscribeToWebPush.ts
  apps/web/src/state/notifications/actions.ts
  apps/web/src/state/notifications/hooks.ts
  apps/web/src/state/notifications/reducer.ts
  apps/web/src/views/Notifications/components/NotificationDropdown/NotificationMenu.tsx
  apps/web/src/views/Notifications/components/NotificationHeader/NotificationHeader.tsx
  apps/web/src/views/Notifications/components/NotificationItem/NotificationItem.tsx
  apps/web/src/views/Notifications/components/NotificationItem/NotificationItemImage.tsx
  apps/web/src/views/Notifications/components/SettingsItem/SettingsItem.tsx
  apps/web/src/views/Notifications/constants.ts
  apps/web/src/views/Notifications/containers/NotificationSettings.tsx
  apps/web/src/views/Notifications/containers/NotificationView.tsx
  apps/web/src/views/Notifications/containers/OnBoardingView.tsx
  apps/web/src/views/Notifications/hooks/useNotificationHistory.ts
  apps/web/src/views/Notifications/index.tsx
  apps/web/src/views/Notifications/styles.tsx
  apps/web/src/views/Notifications/utils/textHelpers.ts
  packages/localization/src/config/translations.json
  pnpm-lock.yaml
Labels: size/XXL

#9401 chore(blog): Turn a bit more cache control cache
  apps/blog/pages/api/articles.tsx
Labels: size/XS

#9399 chore: add error name and mm log
  apps/web/src/views/Swap/MMLinkPools/hooks/useSwapCallback.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSendSwapTransaction.ts
Labels: size/S

#9400 feat: open 20%
  apps/web/src/config/experimentalFeatures.ts
Labels: size/XS

#9402 chore: list zksync pool
  packages/pools/src/constants/pools/324.ts
Labels: size/S

#9403 fix: Crash when swap accessed from unsupported chain
  apps/web/src/hooks/usePoolsOnChain.ts
  apps/web/src/hooks/useV2Pools.ts
  apps/web/src/hooks/useV3Pools.ts
  packages/smart-router/evm/v3-router/functions/getPairCombinations.ts
Labels: size/M

#9412 refactor: Introduce new trade format
  .changeset/wise-owls-notice.md
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButton.tsx
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButtonV2.tsx
  apps/web/src/views/Swap/MMLinkPools/hooks/useDerivedSwapInfoWithMM.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useGetRFQTrade.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useIsMMTradeBetter.tsx
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMConfirmModalState.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMOrderBookTrade.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useMMTradeInfo.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useSwapCallArguments.ts
  apps/web/src/views/Swap/MMLinkPools/hooks/useSwapCallback.ts
  apps/web/src/views/Swap/MMLinkPools/types.ts
  apps/web/src/views/Swap/MMLinkPools/utils/exchange.ts
  apps/web/src/views/Swap/V3Swap/components/RouteDisplayModal.tsx
  apps/web/src/views/Swap/V3Swap/components/RoutesBreakdown.tsx
  apps/web/src/views/Swap/V3Swap/components/SwapModalFooter.tsx
  apps/web/src/views/Swap/V3Swap/components/TransactionConfirmSwapContent.tsx
  apps/web/src/views/Swap/V3Swap/containers/CommitButton.tsx
  apps/web/src/views/Swap/V3Swap/containers/ConfirmSwapModal.tsx
  apps/web/src/views/Swap/V3Swap/containers/ConfirmSwapModalV2.tsx
  apps/web/src/views/Swap/V3Swap/containers/MMCommitButtonV2.tsx
  apps/web/src/views/Swap/V3Swap/containers/TradeDetails.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useAllTypeBestTrade.ts
  apps/web/src/views/Swap/V3Swap/hooks/useCheckSufficient.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSlippageAdjustedAmounts.ts
  apps/web/src/views/Swap/V3Swap/types.ts
  apps/web/src/views/Swap/V3Swap/utils/exchange.ts
  apps/web/src/views/Swap/components/SwapModalHeader.tsx
  packages/smart-router/evm/v3-router/utils/getExecutionPrice.ts
  packages/smart-router/evm/v3-router/utils/getPriceImpact.ts
  packages/smart-router/evm/v3-router/utils/maximumAmount.ts
  packages/smart-router/evm/v3-router/utils/route.ts
  packages/smart-router/evm/v4-router/graph/graph.ts
  packages/smart-router/evm/v4-router/graph/route.ts
  packages/smart-router/evm/v4-router/index.ts
  packages/smart-router/evm/v4-router/trade.ts
  packages/smart-router/evm/v4-router/transformer.test.ts
  packages/smart-router/evm/v4-router/transformer.ts
  packages/smart-router/evm/v4-router/types/trade.ts
Labels: size/XL

#9414 fix: Suppress error throw on exact output
  packages/smart-router/evm/v4-router/graph/graph.ts
Labels: size/XS

#9418 fix: Unfocused toast shown again if dismissed by user
  packages/uikit/src/contexts/ToastsContext/Provider.tsx
Labels: size/S

#9421 feat: list EGO-USDT farm and gauge
  packages/farms/constants/bsc.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/S

#9423 feat: staking banner
  apps/web/src/views/Home/components/Banners/WBNBFixedStakingBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
  packages/widgets-internal/components/Banner/BannerGraphics.tsx
  packages/widgets-internal/components/Banner/BannerMain.tsx
Labels: size/L

#9425 chore: add giftBox and link for INFP
  apps/web/src/components/CurrencyInputPanel/index.tsx
Labels: size/S

#9426 feat: add gift link
  apps/web/src/views/FixedStaking/components/AprCell.tsx
Labels: size/S

#9431 feat: open 50%
  apps/web/src/config/experimentalFeatures.ts
Labels: size/XS

#9433 fix(style): mobile actions area overleap swiper indicate
  packages/widgets-internal/components/Banner/BannerMain.tsx
Labels: size/XS

#9432 chore: Disable stable swap for exact output
  .changeset/cuddly-mails-speak.md
  packages/smart-router/evm/v4-router/graph/graph.ts
Labels: size/S

#9430 feat: reorder farm pools
  packages/farms/constants/arb.ts
  packages/farms/constants/bsc.ts
  packages/farms/constants/eth.ts
Labels: size/L

#9436 feat: list ezETH linea farm and gauge
  packages/farms/constants/linea.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/constants/linea.ts
Labels: size/S

#9437 fix: price updates scope image
  apps/web/src/views/Notifications/components/SettingsItem/SettingsItem.tsx
  apps/web/src/views/Notifications/containers/OnBoardingView.tsx
  apps/web/src/views/Notifications/types.ts
Labels: size/XS

#9441 fix: Footer config
  apps/aptos/components/Menu/Menu.tsx
  apps/aptos/components/Menu/footerConfig.ts
  packages/uikit/src/widgets/Menu/components/footerConfig.ts
Labels: size/L

#9435 feat: Introduce price api sdk
  .changeset/rare-beers-march.md
  apps/web/package.json
  apps/web/src/state/pools/index.ts
  apps/web/src/utils/batcher.ts
  package.json
  packages/farms/package.json
  packages/farms/src/v2/fetchFarmsV2.ts
  packages/price-api-sdk/package.json
  packages/price-api-sdk/src/getCurrencyPrice.test.ts
  packages/price-api-sdk/src/getCurrencyPrice.ts
  packages/price-api-sdk/src/getPoolType.ts
  packages/price-api-sdk/src/getTradeType.ts
  packages/price-api-sdk/src/index.ts
  packages/price-api-sdk/src/orderPriceApiParsers.ts
  packages/price-api-sdk/src/types/amm.ts
  packages/price-api-sdk/src/types/api.ts
  packages/price-api-sdk/src/types/common.ts
  packages/price-api-sdk/src/types/index.ts
  packages/price-api-sdk/src/types/order.ts
  packages/price-api-sdk/src/types/orderType.ts
  packages/price-api-sdk/src/types/pcsx.ts
  packages/price-api-sdk/tsconfig.json
  packages/price-api-sdk/tsup.config.ts
  pnpm-lock.yaml
Labels: size/L

#9444 chore: Fix typings not found issue with nodenext
  .changeset/hungry-points-learn.md
  packages/price-api-sdk/tsup.config.ts
Labels: size/S

#9443 chore: Reduce gas price default to 1 gwei
  apps/web/src/state/types.ts
Labels: size/XS

#9424 fix: Balance component shows token balance wrong
  packages/utils/formatFractions.ts
Labels: size/S

#9452 chore: Price api stress testing
  .changeset/flat-donuts-behave.md
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/config/experimentalFeatures.ts
  apps/web/src/hooks/useBestAMMTrade.ts
  packages/price-api-sdk/src/index.ts
  packages/price-api-sdk/src/orderPriceApiParsers.ts
  packages/price-api-sdk/src/types/api.ts
Labels: size/M

#9449 feat: multichain-banner
  .changeset/rare-donuts-pump.md
  .vscode/settings.json
  apps/web/src/views/Home/components/Banners/MultichainBanner.tsx
  apps/web/src/views/Home/components/Banners/WBNBFixedStakingBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
  packages/widgets-internal/components/Banner/BannerDesc.tsx
  packages/widgets-internal/components/Banner/index.ts
Labels: size/L
