Repository pancakeswap/pancake-frontend, pull requests merged in 2024-01, with the labels that each got.

#8719 fix(Aptos-Pools): Fix apr issue
  packages/widgets-internal/pool/Apr.tsx
Labels: size/XS

#8692 chore: landing page use assets from assets repo
  apps/web/src/views/Home/components/CommunitySection/ImagesOnBg.tsx
  apps/web/src/views/Home/components/Footer.tsx
  apps/web/src/views/Home/components/MetricsSection/index.tsx
  apps/web/src/views/Home/images/aptos-ball-rocket.png
  apps/web/src/views/Home/images/aptos-tag.png
  apps/web/src/views/Home/images/astronaut-bunny.png
  apps/web/src/views/Home/images/bnb-ball-rocket.png
  apps/web/src/views/Home/images/bnb-tag.png
  apps/web/src/views/Home/images/cake-section-main.png
  apps/web/src/views/Home/images/cake.png
  apps/web/src/views/Home/images/community-items/1.png
  apps/web/src/views/Home/images/community-items/2.png
  apps/web/src/views/Home/images/community-items/3.png
  apps/web/src/views/Home/images/community-items/4.png
  apps/web/src/views/Home/images/community-items/5.png
  apps/web/src/views/Home/images/cta-pancake-big.png
  apps/web/src/views/Home/images/cta-pancake.png
  apps/web/src/views/Home/images/cta-rock-2.png
  apps/web/src/views/Home/images/cta-rock.png
  apps/web/src/views/Home/images/eth-ball-rocket.png
  apps/web/src/views/Home/images/socials/1.png
  apps/web/src/views/Home/images/socials/2.png
  apps/web/src/views/Home/images/socials/3.png
  apps/web/src/views/Home/images/socials/4.png
Labels: size/M

#8713 fix(wallet): show binance w3w icon on mobile
  apps/web/src/config/wallet.ts
  apps/web/src/global.d.ts
Labels: size/S

#8689 feat(swap): Improve swap error message parsing and handle
  apps/web/src/hooks/Trades.ts
  apps/web/src/hooks/useApproveCallback.ts
  apps/web/src/hooks/useCatchTxError.tsx
  apps/web/src/utils/errors.ts
  apps/web/src/utils/exchange.ts
  apps/web/src/utils/sentry.ts
  apps/web/src/utils/transactionErrorToUserReadableMessage.ts
  apps/web/src/utils/wrappedCurrency.ts
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/containers/ConfirmSwapModal.tsx
  apps/web/src/views/Swap/V3Swap/containers/SwapCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalState.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useSendSwapTransaction.ts
  apps/web/src/views/Swap/V3Swap/hooks/useWallchain.ts
Labels: size/L

#8722 chore: Cakepie ifo
  apps/web/public/images/achievements/ifo-ckp.svg
  apps/web/public/images/ifos/arena-bg.png
  apps/web/public/images/ifos/belt-bg.png
  apps/web/public/images/ifos/berry-bg.png
  apps/web/public/images/ifos/blink-bg.png
  apps/web/public/images/ifos/co-bg.png
  apps/web/public/images/ifos/dar-bg.png
  apps/web/public/images/ifos/ditto-bg.png
  apps/web/public/images/ifos/dkt-bg.png
  apps/web/public/images/ifos/dpt-bg.png
  apps/web/public/images/ifos/duet-bg.png
  apps/web/public/images/ifos/era-bg.png
  apps/web/public/images/ifos/froyo-bg.png
  apps/web/public/images/ifos/helmet-bg.png
  apps/web/public/images/ifos/hoop-bg.png
  apps/web/public/images/ifos/horizon-bg.png
  apps/web/public/images/ifos/hotcross-bg.png
  apps/web/public/images/ifos/kalmar-bg.png
  apps/web/public/images/ifos/krs-bg.png
  apps/web/public/images/ifos/mgp-bg.png
  apps/web/public/images/ifos/peel-bg.png
  apps/web/public/images/ifos/porto-bg.png
  apps/web/public/images/ifos/sable-bg.png
  apps/web/public/images/ifos/santos-bg.png
  apps/web/public/images/ifos/soteria-bg.png
  apps/web/public/images/ifos/squad-bg.png
  apps/web/public/images/ifos/tenet-bg.png
  apps/web/public/images/ifos/trivia-bg.png
  apps/web/public/images/ifos/watch-bg.png
  apps/web/public/images/ifos/wmx-bg.png
  apps/web/public/images/ifos/wom-bg.png
  apps/web/src/config/constants/campaigns.ts
  apps/web/src/views/Ifos/components/Hero.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
  apps/web/src/views/Ifos/components/IfoSteps.tsx
  apps/web/src/views/Ifos/components/VeCakeCard.tsx
  apps/web/src/views/Ifos/helpers/getBannerUrl.ts
  apps/web/src/views/Ifos/hooks/v7/useGetWalletIfoData.ts
  packages/hooks/src/useImageColor.ts
  packages/ifos/src/constants/ifos/bsc.ts
  packages/localization/src/config/translations.json
  packages/tokens/src/56.ts
  packages/widgets-internal/ifo/VeCakeCard.tsx
Labels: size/L

#8725 chore: CKP IFO banner
  apps/web/src/views/Home/components/Banners/NewIFOBanner.tsx
  apps/web/src/views/Home/components/Banners/WebNotificationBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/hooks/src/useCountdown.ts
  packages/localization/src/config/translations.json
Labels: size/L

#8702 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XL

#8724 chore: Track perf on quote
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/utils/datadog.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSwapBestTrade.ts
Labels: size/S

#8732 feat: Remove new tag
  apps/web/src/components/Menu/config/config.ts
Labels: size/XS, automerge

#8731 feat: Separate gauges file
  packages/gauges/src/constants/config/index.ts
  packages/gauges/src/constants/config/prod.ts
  packages/gauges/src/constants/config/testnet.ts
  packages/gauges/src/getAllGauges.ts
  packages/gauges/src/index.test.ts
  packages/localization/src/config/translations.json
Labels: size/L, automerge

#8688 fix: Encoding issue regarding the swap protocol
  packages/smart-router/evm/index.test.ts
  packages/smart-router/evm/v3-router/smartRouter.ts
  packages/smart-router/evm/v3-router/utils/index.ts
  packages/universal-router-sdk/src/entities/protocols/pancakeswap.ts
  packages/universal-router-sdk/src/entities/types.ts
  packages/universal-router-sdk/src/index.ts
  packages/universal-router-sdk/src/swapRouter.ts
  packages/universal-router-sdk/test/trade.test.ts
  packages/universal-router-sdk/test/utils/buildTrade.ts
Labels: size/XL

#8733 chore: adjust ifo banner logic
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/hooks/src/useCountdown.ts
Labels: size/XS

#8726 chore: List cake mcake stable pool
  packages/smart-router/evm/constants/stableSwap/56.ts
Labels: size/S

#8735 chore: update MM signer wallet address
  apps/web/src/views/Swap/MMLinkPools/constants.ts
Labels: size/XS

#8736 feat: Update perp only eth support v1 link
  apps/web/src/utils/getPerpetualUrl.ts
Labels: size/XS

#8745 fix: Cannot connect to binance w3w in app
  apps/web/src/config/wallet.ts
Labels: size/XS

#8744 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#8734 feat: Alp pool move to finished
  .changeset/twenty-rings-explain.md
  apps/web/src/views/Pools/components/Apr.tsx
  apps/web/src/views/Pools/components/Modals/StakeModal.tsx
  apps/web/src/views/Pools/components/PoolCard/AprRow.tsx
  apps/web/src/views/Pools/components/PoolsTable/Cells/NameCell.tsx
  apps/web/src/views/Pools/hooks/useBoostedPoolApr.ts
  packages/pools/src/constants/pools/42161.ts
Labels: size/M, automerge

#8752 chore: fix userDelegated pool table view
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
Labels: size/XS

#8751 feat: Ifo description support url
  apps/web/src/views/Ifos/components/IfoFoldableCard/Achievement.tsx
  packages/ifos/src/constants/ifos/bsc.ts
Labels: size/M, automerge

#8754 chore: fix veCake migrated card display logic
  apps/web/src/views/CakeStaking/components/SyrupPool/VeCakeMigrateCard.tsx
  apps/web/src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
Labels: size/XS

#8755 fix: Ifo numbers
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
Labels: size/XS

#8760 chore: list mcake sdcake stable farm
  packages/farms/constants/bsc.ts
Labels: size/S

#8764 chore: List pnp-bnb farm
  packages/farms/constants/bsc.ts
Labels: size/XS

#8766 fix: Missing translations in titles
  apps/web/src/pages/v2/migrate/[address].tsx
  apps/web/src/views/AddLiquidityV3/IncreaseLiquidityV3.tsx
  apps/web/src/views/Farms/components/UpdatePositionsReminder.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#8759 chore: New Crowdin updates
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/M

#8768 chore: update landing community info
  apps/web/src/views/Home/components/CommunitySection/CommunitySummary.tsx
Labels: size/XS

#8767 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#8765 fix: Modal v1 overlay cant trigger custom on dismiss
  packages/uikit/src/widgets/Modal/ModalContext.tsx
Labels: size/XS

#8761 feat: Add error message to transaction confirmation and fix pending confirmation in remove liquidity
  apps/web/src/components/TransactionConfirmationModal/index.tsx
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/views/AddLiquidity/components/ConfirmAddLiquidityModal.tsx
  apps/web/src/views/AddLiquidityV3/IncreaseLiquidityV3.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
  apps/web/src/views/RemoveLiquidity/RemoveLiquidityV3.tsx
  apps/web/src/views/Swap/components/ConfirmRemoveLiquidityModal.tsx
Labels: size/L

#8707 chore: Block blacklist from query
  apps/aptos/components/SearchModal/ImportToken.tsx
  apps/web/src/components/ImportTokenWarningModal.tsx
  apps/web/src/components/SearchModal/ImportToken.tsx
  apps/web/src/components/UnsupportedModal.tsx
  apps/web/src/hooks/Tokens.ts
  packages/localization/src/config/translations.json
Labels: size/L

#8771 chore: Bump wrangler
  apis/farms/package.json
  apis/proxy-worker/package.json
  apis/routing/package.json
  package.json
  packages/farms/package.json
  pnpm-lock.yaml
Labels: size/M

#8677 test: add token-list check
  .changeset/tiny-badgers-jam.md
  packages/chains/src/chainId.ts
  packages/chains/src/index.test.ts
  packages/chains/src/utils.ts
  packages/chains/test/chain.test.ts
  packages/farms/tests/v3.test.ts
Labels: size/M

#8395 refactor: Use query in profile
  apps/web/src/pages/profile/pancake-collectibles.tsx
  apps/web/src/state/profile/hooks.ts
  apps/web/src/views/Profile/components/PancakeCollectibles.tsx
Labels: size/M

#7349 chore: Remove no used deps
  package.json
  pnpm-lock.yaml
Labels: size/L

#8774 feat: list new gauges and xai-weth farm
  packages/farms/constants/arb.ts
  packages/farms/src/types.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/42161.ts
  packages/tokens/src/56.ts
Labels: size/M

#8431 refactor: Use query in liquidity
  .changeset/polite-steaks-raise.md
  apps/web/src/hooks/useV3Pools.ts
  apps/web/src/pages/liquidity/[tokenId].tsx
  packages/smart-router/evm/v3-router/providers/multicallSwapProvider.ts
  packages/smart-router/evm/v3-router/types/providers.ts
Labels: size/M

#8779 fix: Workaround fix ssr issues in aptos
  apps/aptos/components/Menu/Menu.tsx
Labels: size/M

#8776 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/M

#8780 fix: Invalid farm apr
  apps/aptos/config/constants/lpAprs/1.json
  apps/web/src/config/constants/lpAprs/1.json
  apps/web/src/config/constants/lpAprs/56.json
  packages/farms/constants/bsc.ts
  scripts/updateAptosLpsAPR/farmsOneWeekAgo.json
  scripts/updateLPsAPR.ts
Labels: size/XL

#8786 feat: add cake-ckp syrup pool
  packages/pools/src/constants/pools/56.ts
Labels: size/S

#8793 fix: Missing price source for v2 farms
  apps/web/src/hooks/useCurrencyPrice.ts
  apps/web/src/utils/getCurrencyPrice.ts
  packages/farms/constants/bsc.ts
  packages/farms/src/v2/farmPrices.test.ts
  packages/farms/src/v2/farmPrices.ts
  packages/farms/src/v2/fetchFarmsV2.ts
  packages/smart-router/legacy-router/getStableSwapPairs.ts
  packages/utils/getCurrencyPrice.ts
  packages/utils/package.json
  pnpm-lock.yaml
Labels: size/L

#8797 fix: Missing pool apr
  apps/web/src/state/pools/index.ts
  packages/utils/getCurrencyPrice.ts
Labels: size/S

#8787 chore: New Crowdin updates
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/S

#8784 chore: update position manager lp fee API
  apps/web/src/views/PositionManagers/hooks/useFetchApr.ts
  packages/position-managers/src/constants/endpoints.ts
Labels: size/S

#8785 feat: add new gauges on arbitrum eth and bsc
  packages/farms/constants/arb.ts
  packages/farms/constants/bsc.ts
  packages/farms/constants/common/index.ts
  packages/farms/constants/eth.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/1.ts
  packages/tokens/src/42161.ts
  packages/tokens/src/56.ts
Labels: size/L

#8801 chore: New Crowdin updates
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/M

#8804 feat: new vault and syrup pool
  apps/web/src/views/PositionManagers/utils/strategy.ts
  packages/localization/src/config/translations.json
  packages/pools/src/constants/pools/56.ts
  packages/position-managers/src/constants/vaults/eth.ts
  packages/position-managers/src/types.ts
Labels: size/M

#8805 fix: gauge duplicated hash
  packages/gauges/src/getAllGauges.ts
Labels: size/S

#8806 chore: remove vault
  packages/position-managers/src/constants/vaults/eth.ts
Labels: size/S

#8821 chore: Update opbnb subgraph
  .changeset/orange-teachers-kiss.md
  apis/farms/src/bindings.d.ts
  apis/farms/src/provider.ts
  apis/farms/src/v3.ts
  apis/farms/wrangler.toml
  apis/routing/src/bindings.d.ts
  apis/routing/src/provider.ts
  apis/routing/wrangler.toml
  apps/web/src/config/constants/endpoints.ts
  packages/chains/src/index.test.ts
  packages/chains/src/subgraphs.ts
Labels: size/L

#8808 fix: Harvest card pending tx indicator not working
  apps/web/src/views/Home/components/UserBanner/HarvestCard.tsx
Labels: size/XS

#8807 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/L

#8813 fix: Fix token amount input width
  apps/web/src/components/Modal/ModalInput.tsx
  packages/uikit/src/widgets/Modal/ModalInput.tsx
Labels: size/S

#8783 feat: Early abort
  .changeset/modern-zoos-thank.md
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/quote-worker.ts
  apps/web/src/state/multicall/updater.tsx
  apps/web/src/utils/viem.ts
  apps/web/src/utils/worker.ts
  packages/multicall/src/multicall.ts
  packages/smart-router/evm/v3-router/getBestTrade.ts
  packages/smart-router/evm/v3-router/getRoutesWithValidQuote.ts
  packages/smart-router/evm/v3-router/providers/multicallSwapProvider.ts
  packages/smart-router/evm/v3-router/providers/onChainQuoteProvider.ts
  packages/smart-router/evm/v3-router/providers/quoteProviders.ts
  packages/smart-router/evm/v3-router/types/providers.ts
  packages/smart-router/evm/v3-router/types/trade.ts
  packages/utils/abortControl.ts
  packages/utils/package.json
  packages/utils/viem/isAbortError.ts
  pnpm-lock.yaml
Labels: size/XL

#8796 feat: Access Risk support ETH chain
  apps/web/src/components/AccessRisk/AccessRiskTooltips.tsx
  apps/web/src/components/AccessRisk/config/supportedChains.ts
  apps/web/src/components/AccessRisk/index.tsx
  apps/web/src/components/SearchModal/ImportToken.tsx
  apps/web/src/views/LimitOrders/index.tsx
  apps/web/src/views/Swap/SwapFeaturesContext.tsx
Labels: Delayed Release, size/M

#8811 fix(Farms): Fix add stableLP issue
  apps/web/src/views/AddLiquidityV3/index.tsx
Labels: size/XS

#8828 chore: Add new position manager vault
  packages/position-managers/src/constants/vaults/eth.ts
Labels: size/S

#8827 feat: new cgpt syrup pool
  packages/pools/src/constants/pools/56.ts
Labels: size/XS

#8835 chore: Update stableswap fee rate
  packages/smart-router/evm/constants/stableSwap/56.ts
Labels: size/XS

#8838 fix: stop menu collapse on onramp menu onclick
  apps/web/src/components/FiatOnRampModal/FiatOnRampModal.tsx
Labels: size/S

#8836 fix: Invalid negative tvl
  apps/web/src/views/V3Info/data/pool/poolData.ts
  apps/web/src/views/V3Info/views/PoolPage.tsx
Labels: size/S

#8839 chore: List arb stable pools
  .changeset/dull-monkeys-tap.md
  packages/smart-router/evm/constants/stableSwap/arb.ts
  packages/smart-router/evm/constants/stableSwap/bsc.ts
  packages/smart-router/evm/constants/stableSwap/bscTestnet.ts
  packages/smart-router/evm/constants/stableSwap/pools.ts
  packages/tokens/src/arb.ts
  packages/tokens/src/arbGoerli.ts
  packages/tokens/src/base.ts
  packages/tokens/src/baseTestnet.ts
  packages/tokens/src/bsc.ts
  packages/tokens/src/bscTestnet.ts
  packages/tokens/src/eth.ts
  packages/tokens/src/goerli.ts
  packages/tokens/src/index.ts
  packages/tokens/src/linea.ts
  packages/tokens/src/lineaTestnet.ts
  packages/tokens/src/opBNB.ts
  packages/tokens/src/opBnbTestnet.ts
  packages/tokens/src/polygonZkEVM.ts
  packages/tokens/src/polygonZkEVMTestnet.ts
  packages/tokens/src/scrollSepolia.ts
  packages/tokens/src/zkSync.ts
  packages/tokens/src/zkSyncTestnet.ts
Labels: size/M

#8841 feat: gauge config test
  packages/gauges/package.json
  packages/gauges/src/abis/gaugesVoting.ts
  packages/gauges/src/constants/config/prod.ts
  packages/gauges/src/fetchAllKilledGauges.ts
  packages/gauges/src/getAllGauges.ts
  packages/gauges/src/tests/config.test.ts
  pnpm-lock.yaml
Labels: size/L

#8847 refactor: usd price fetcher
  apps/web/package.json
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/hooks/useCurrencyUsdPrice.ts
  apps/web/src/state/pools/index.ts
  apps/web/src/utils/batcher.ts
  packages/farms/src/v2/fetchFarmsV2.ts
  packages/utils/getCurrencyPrice.test.ts
  packages/utils/getCurrencyPrice.ts
  packages/utils/package.json
  pnpm-lock.yaml
Labels: size/L

#8849 feat: replace stable price hook
  apps/web/src/hooks/useBUSDPrice.ts
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/hooks/useCurrencyUsdPrice.ts
  apps/web/src/utils/llamaPrice.ts
  apps/web/src/views/PositionManagers/hooks/useEarningTokenPriceInfo.ts
  apps/web/src/views/Predictions/Leaderboard/components/Results/styles.tsx
  apps/web/src/views/Predictions/components/CollectRoundWinningsModal.tsx
  apps/web/src/views/Predictions/components/History/BetResult.tsx
  apps/web/src/views/Predictions/components/History/PnlTab/PnlTab.tsx
  apps/web/src/views/Predictions/hooks/useTokenPrice.ts
Labels: size/L

#8851 fix(style): gauge/staking white-space & overlapping
  apps/web/src/views/CakeStaking/components/LockWeeksForm.tsx
  apps/web/src/views/GaugesVoting/components/Table/AddGauge/AddGaugeModal.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/TableHeader.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/TableRow.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/index.tsx
  packages/uikit/src/components/Table/Cell.tsx
Labels: size/M

#8850 chore: Whitelist mpendle pendle pair on router
  packages/smart-router/evm/constants/exchange.ts
  packages/smart-router/evm/constants/v3.ts
Labels: size/XS

#8854 fix: Migrate with 0.01 tier
  apps/web/src/views/AddLiquidityV3/Migrate.tsx
Labels: size/M

#8856 fix: Migrate manual approval address
  apps/web/src/views/AddLiquidityV3/Migrate.tsx
Labels: size/XS

#8855 fix: Price when removing stable pair
  apps/web/src/views/Swap/hooks/useEstimatedAmount.ts
Labels: size/XS

#8845 fix: Use traditional token approval for liquidity removal
  apps/web/src/views/AddLiquidityV3/Migrate.tsx
  apps/web/src/views/RemoveLiquidity/index.tsx
Labels: size/L

#8853 refactor: Use query in ifos
  apps/web/src/views/Ifos/components/IfoFoldableCard/index.tsx
  apps/web/src/views/Ifos/components/IfoVesting/VestingPeriod/Info.tsx
  apps/web/src/views/Ifos/hooks/vesting/useFetchVestingData.ts
Labels: size/M

#8842 refactor: Use query in access risk
  apps/web/src/components/AccessRisk/index.tsx
  apps/web/src/components/SearchModal/ImportToken.tsx
Labels: size/M

#8860 feat: list new gauges and farms
  packages/farms/constants/bsc.ts
  packages/farms/constants/linea.ts
  packages/farms/constants/zkSync.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/bsc.ts
  packages/tokens/src/zkSync.ts
Labels: size/L

#8861 fix: gauage gid correction
  packages/gauges/src/constants/config/prod.ts
Labels: size/S

#8866 feat: add killed param
  apps/web/src/pages/api/gauges/getAllGauges.ts
  packages/gauges/src/getAllGauges.ts
Labels: size/S

#8865 feat(Blog): Hide language
  apps/blog/hooks/useLanguage.ts
  package.json
Labels: size/S

#8862 fix: remove async
  packages/gauges/src/tests/config.test.ts
Labels: size/XS

#8867 feat: Hide Old Pool Performance Fee
  apps/web/src/views/Pools/components/PoolStatsInfo.tsx
  apps/web/src/views/Pools/components/Stat.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#8868 fix: position manager amountInUsd NaN display issue
  apps/web/src/views/PositionManagers/components/StakedAssets.tsx
Labels: size/S

#8870 feat: fix gauge order and list aptos farm
  apps/aptos/config/constants/farms/1.ts
  apps/aptos/config/constants/tokens/1.ts
  packages/gauges/src/constants/config/prod.ts
Labels: size/M

#8871 fix: stAPT Price
  apps/aptos/config/constants/priceHelperLps/farms/1.ts
Labels: size/XS, automerge

#8792 feat(Aptos): Farm support duo rewards
  apps/aptos/components/Farms/components/FarmCard/ApyButton.tsx
  apps/aptos/components/Farms/components/FarmCard/CardActionsContainer.tsx
  apps/aptos/components/Farms/components/FarmCard/CardHeading.tsx
  apps/aptos/components/Farms/components/FarmCard/EarnedTokenInfo.tsx
  apps/aptos/components/Farms/components/FarmCard/EarnedUsdPrice.tsx
  apps/aptos/components/Farms/components/FarmCard/FarmCard.tsx
  apps/aptos/components/Farms/components/FarmCard/HarvestAction.tsx
  apps/aptos/components/Farms/components/FarmCard/StakeAction.tsx
  apps/aptos/components/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/aptos/components/Farms/components/FarmTable/Actions/HarvestAction.tsx
  apps/aptos/components/Farms/components/FarmTable/Actions/StakedAction.tsx
  apps/aptos/components/Farms/components/FarmTable/Apr.tsx
  apps/aptos/components/Farms/components/FarmTable/FarmTable.tsx
  apps/aptos/components/Farms/components/FarmTable/Row.tsx
  apps/aptos/components/Farms/components/Farms.tsx
  apps/aptos/components/Farms/components/getDisplayApr.ts
  apps/aptos/components/Farms/hooks/useCheckIsUserIpPass.ts
  apps/aptos/config/constants/contracts/masterchef.ts
  apps/aptos/config/constants/farms/1.ts
  apps/aptos/config/constants/farms/2.ts
  apps/aptos/config/index.ts
  apps/aptos/pages/farms/history.tsx
  apps/aptos/pages/farms/index.tsx
  apps/aptos/state/farms/hook.ts
  apps/aptos/state/farms/utils/pendingApt.ts
  apps/aptos/state/farms/utils/pendingCake.ts
  apps/web/src/__tests__/translations.test.ts
  apps/web/src/views/Farms/components/FarmCard/ApyButton.tsx
  apps/web/src/views/Farms/components/FarmCard/FarmCard.tsx
  apps/web/src/views/Farms/components/FarmCard/StakeAction.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/HarvestAction.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
  packages/awgmi/core/src/index.test.ts
  packages/awgmi/core/src/index.ts
  packages/awgmi/core/src/view/fetchAptosView.ts
  packages/farms/src/types.ts
  packages/farms/src/v2/deserializeFarm.ts
  packages/localization/src/config/translations.json
  packages/uikit/src/components/RoiCalculatorModal/RoiCalculatorFooter.tsx
  packages/uikit/src/components/RoiCalculatorModal/RoiCalculatorModal.tsx
  packages/uikit/src/components/RoiCalculatorModal/RoiCard.tsx
  packages/widgets-internal/farm/components/DepositModal/index.tsx
  packages/widgets-internal/farm/components/FarmTable/Actions/HarvestAction.tsx
  packages/widgets-internal/farm/components/FarmTable/index.tsx
  packages/widgets-internal/farm/components/StakedLP/index.tsx
Labels: size/XXL

#8872 fix: Aptos ROI bug
  apps/aptos/components/Farms/components/Farms.tsx
  apps/aptos/state/farms/utils/pendingApt.ts
  packages/uikit/src/components/RoiCalculatorModal/RoiCalculatorFooter.tsx
Labels: size/S, automerge

#8878 fix(SubgraphHealth): Fix zIndex
  apps/web/src/components/SubgraphHealthIndicator/SubgraphHealthIndicator.tsx
Labels: size/XS

#8810 fix(Farms): V2 farms does not display booster information on mobile
  apps/web/src/views/Farms/components/FarmTable/Row.tsx
Labels: size/XS

#8830 fix(Farms): Fix last row radius
  apps/aptos/components/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/aptos/components/Farms/components/FarmTable/FarmTable.tsx
  apps/aptos/components/Farms/components/FarmTable/Row.tsx
  apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
  apps/web/src/views/Farms/components/FarmTable/FarmTable.tsx
  apps/web/src/views/Farms/components/FarmTable/Row.tsx
Labels: size/M

#8852 feat: stableSwap info page for multi-chain
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/state/info/constant.ts
  apps/web/src/state/info/queries/pools/poolData.ts
  apps/web/src/state/info/queries/pools/topPools.ts
  apps/web/src/state/info/queries/tokens/tokenData.ts
  apps/web/src/state/swap/fetch/fetchDerivedPriceData.ts
  apps/web/src/utils/graphql.ts
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/Info/index.tsx
  apps/web/src/views/V3Info/components/Layout/index.tsx
  packages/chains/package.json
  packages/chains/src/index.test.ts
  packages/chains/src/subgraphs.ts
Labels: size/L

#8883 fix: Frontend fix for mercuryo iframe bug
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/views/BuyCrypto/hooks/useIframeUrlFetcher.ts
Labels: size/XS

#8799 fix: Add missing translations
  apps/web/src/views/CakeStaking/components/BenefitCard.tsx
  apps/web/src/views/CakeStaking/components/SyrupPool/VeCakeButton.tsx
  apps/web/src/views/GaugesVoting/components/ChartLabel.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/index.tsx
  apps/web/src/views/Swap/MMLinkPools/components/MMCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/containers/SwapCommitButton.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#8892 chore(seo): Update metadata
  apps/aptos/next-seo.config.ts
  apps/blog/next-seo.config.ts
  apps/web/next-seo.config.ts
Labels: size/S

#8893 perf: bundle size 1
  apps/web/next.config.mjs
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/M

#8894 perf: Lazy load web3inbox
  apps/web/src/components/Menu/GlobalSettings/SettingsModal.tsx
  apps/web/src/components/Menu/GlobalSettings/WebNotiToggle.tsx
  apps/web/src/components/Menu/index.tsx
  apps/web/src/hooks/useWebNotifications.ts
Labels: size/L

#8891 feat(Position Managers): List AIOZ-WBNB
  apps/web/src/views/PositionManagers/components/YieldInfo.tsx
  packages/position-managers/src/constants/vaults/bsc.ts
Labels: size/S

#8896 feat: List new gauges
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/arb.ts
  packages/tokens/src/bsc.ts
  packages/tokens/src/eth.ts
  packages/tokens/src/polygonZkEVM.ts
Labels: size/L

#8890 fix: remove custom onboard noti to cloud
  apps/web/src/views/Notifications/constants.ts
  apps/web/src/views/Notifications/containers/OnBoardingView.tsx
  apps/web/src/views/Notifications/types.ts
Labels: size/S

#8900 feat: List new farms
  packages/farms/constants/arb.ts
  packages/farms/constants/bsc.ts
  packages/farms/constants/eth.ts
  packages/farms/constants/polygonZkEVM.ts
  packages/farms/constants/zkSync.ts
Labels: size/M

#8885 refactor: Use query in v2 pair
  apps/web/src/pages/v2/pair/[[...currency]].tsx
Labels: size/S

#8901 fix: Multiple worker script requests
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/quote-worker.ts
  apps/web/src/state/multicall/updater.tsx
  apps/web/src/utils/worker.ts
Labels: size/M

#8886 refactor: Use query in position manager
  apps/web/src/views/PositionManagers/hooks/useTokenPriceFromSubgraph.ts
Labels: size/S

#8884 refactor: Use query in list updater
  apps/web/src/state/lists/updater.ts
Labels: size/S

#8882 refactor: Use query in active ifo with blocks hook
  apps/web/src/hooks/useActiveIfoWithBlocks.ts
Labels: size/S

#8409 refactor: Use query in user
  apps/web/src/state/user/hooks/index.tsx
Labels: size/M

#8903 chore: Update default metadata desc
  apps/web/src/config/constants/meta.ts
Labels: size/XS

#8879 fix: Transaction updater gets stuck after receipt not found when retries
  apps/web/src/config/constants/index.ts
  apps/web/src/state/multicall/retry.ts
  apps/web/src/state/transactions/updater.tsx
Labels: size/S

#8908 perf: Only request for worker script once
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/hooks/useWorker.ts
  apps/web/src/quote-worker.ts
  apps/web/src/state/multicall/updater.tsx
  apps/web/src/utils/worker.ts
  apps/web/src/utils/workerScriptLoader.ts
  apps/web/src/utils/workerUrlExtractor.ts
Labels: Delayed Release, size/L

#8909 Revert "perf: Only request for worker script once"
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/hooks/useWorker.ts
  apps/web/src/quote-worker.ts
  apps/web/src/state/multicall/updater.tsx
  apps/web/src/utils/worker.ts
  apps/web/src/utils/workerScriptLoader.ts
  apps/web/src/utils/workerUrlExtractor.ts
Labels: size/L

#8910 perf: Only request for worker script once
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/hooks/useWorker.ts
  apps/web/src/quote-worker.ts
  apps/web/src/state/lists/updater.ts
  apps/web/src/state/multicall/updater.tsx
  apps/web/src/utils/worker.ts
  apps/web/src/utils/workerScriptLoader.ts
  apps/web/src/utils/workerUrlExtractor.ts
Labels: size/L

#8912 Revert "perf: Only request for worker script once"
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/hooks/useWorker.ts
  apps/web/src/quote-worker.ts
  apps/web/src/state/lists/updater.ts
  apps/web/src/state/multicall/updater.tsx
  apps/web/src/utils/worker.ts
  apps/web/src/utils/workerScriptLoader.ts
  apps/web/src/utils/workerUrlExtractor.ts
Labels: size/L

#8914 fix: remove deprecated cake warning
  apps/web/src/components/Menu/UserMenu/CakeBenefitsCard.tsx
  apps/web/src/components/Menu/UserMenu/WalletInfo.tsx
  apps/web/src/utils/index.ts
  packages/localization/src/config/translations.json
  packages/uikit/src/components/CopyButton/CopyAddress.tsx
Labels: size/L

#8917 perf: Remove pottery status fetch for menu
  apps/web/src/components/Menu/hooks/useMenuItemsStatus.ts
Labels: size/XS

#8916 fix: Locked end notification not refresh when account changes
  apps/web/src/hooks/useLockedEndNotification.tsx
Labels: size/XS

#8905 refactor: Use query in transaction updater
  apps/web/src/state/transactions/updater.tsx
Labels: size/S

#8902 feat: Update Trading Reward URL
  apps/web/next.config.mjs
  apps/web/src/pages/trading-reward/cake-stakers.tsx
  apps/web/src/views/TradingReward/components/SubMenu/index.tsx
  apps/web/src/views/TradingReward/components/TopTraders/CurrentRewardPool.tsx
  apps/web/src/views/TradingReward/components/TopTraders/YourTradingReward/CurrentPeriod.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#8920 feat: List Arb farm
  packages/farms/constants/arb.ts
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/arb.ts
Labels: size/M, automerge

#8913 perf: Support abort on worker function calls
  apps/web/src/hooks/useBestAMMTrade.ts
  apps/web/src/hooks/useWorker.ts
  apps/web/src/pages/_app.tsx
  apps/web/src/quote-worker.ts
  apps/web/src/state/lists/updater.ts
  apps/web/src/state/multicall/updater.tsx
  apps/web/src/utils/worker.ts
  apps/web/src/utils/workerScriptLoader.ts
  apps/web/src/utils/workerUrlExtractor.ts
Labels: size/L

#8921 feat: Update aptos wording
  apps/aptos/components/Farms/components/FarmCard/EarnedUsdPrice.tsx
  apps/aptos/components/Farms/components/FarmCard/StakeAction.tsx
  apps/aptos/components/Farms/components/FarmTable/Actions/StakedAction.tsx
  apps/aptos/components/Farms/hooks/useCheckIsUserIpPass.ts
  apps/web/src/__tests__/translations.test.ts
  packages/localization/src/config/translations.json
Labels: size/S, automerge

#8924 feat: List opBNB Farm
  packages/farms/constants/opBNB.ts
  packages/tokens/src/opBNB.ts
Labels: size/M

#8880 style: Liquid Staking margin
  apps/web/src/views/LiquidStaking/constants/FAQs/EthWbethFaq.tsx
Labels: size/XS, automerge

#8931 feat: list new gauges
  packages/gauges/src/constants/config/prod.ts
  packages/tokens/src/bsc.ts
Labels: size/M

#8935 fix: Aptos Harvest bug
  apps/aptos/components/Farms/hooks/useCheckIsUserIpPass.ts
Labels: size/XS, automerge

#8937 chore: fix zksync v2 info issue
  apps/web/src/state/info/queries/pools/poolData.ts
  apps/web/src/state/info/queries/tokens/tokenData.ts
Labels: size/L

#8941 fix(simple-staking): Display decimal balance
  apps/web/src/views/FixedStaking/components/AmountWithUSDSub.tsx
Labels: size/XS

#8947 chore: Remove no used v3 staker deps
  .changeset/yellow-bottles-brush.md
  packages/v3-sdk/package.json
  pnpm-lock.yaml
Labels: size/M

#8945 feat: add wbnb-rbnb v3 farm
  packages/farms/constants/bsc.ts
  packages/tokens/src/zkSync.ts
Labels: size/S

#8949 feat: add killed params to csv api
  apps/web/src/pages/api/gauges/getAllGauges.ts
  apps/web/src/pages/api/gauges/getAllGaugesCSV.ts
Labels: size/XS

#8953 chore: update web-noti feature flag to all users
  apps/web/src/config/experimentalFeatures.ts
Labels: size/XS

#8955 chore: adjust web3 noti feature flag to 50%
  apps/web/src/config/experimentalFeatures.ts
Labels: size/XS
