Repository pancakeswap/pancake-frontend, pull requests merged in 2025-02, with the labels that each got.

#11169 feat: ton v2 swap
  apps/ton/package.json
  apps/ton/src/atoms/currencyAtoms.ts
  apps/ton/src/atoms/lists/fetchListAtom.ts
  apps/ton/src/components/TonSwap/CurrencyInputPanelSimplify/index.tsx
  apps/ton/src/components/TonSwap/SearchModal/CommonBases.tsx
  apps/ton/src/components/TonSwap/SearchModal/CurrencyList.tsx
  apps/ton/src/components/TonSwap/SearchModal/CurrencySearch.tsx
  apps/ton/src/components/TonSwap/SearchModal/CurrencySearchModal.tsx
  apps/ton/src/config/constants/commonBases.ts
  apps/ton/src/hooks/swap/useSwapActionHandlers.ts
  apps/ton/src/hooks/swap/useTradeExactIn.ts
  apps/ton/src/hooks/swap/useTradeExactOut.ts
  apps/ton/src/hooks/tokens/useNativeCurrency.ts
  apps/ton/src/ton/logic/balanceAtom.ts
  apps/ton/src/ton/logic/balanceMultipleAtom.ts
  apps/ton/src/utils/tokens/currency.ts
  apps/ton/src/utils/tokens/filterTokens.ts
  apps/ton/src/utils/tokens/wrappedTokenInfo.ts
  apps/ton/src/utils/tryParseAmount.ts
  apps/ton/src/views/TONSwap/SwapForm.tsx
  packages/routing-sdk/addons/ton-v2/package.json
  packages/routing-sdk/addons/ton-v2/src/constants/gasCost.ts
  packages/routing-sdk/addons/ton-v2/src/constants/index.ts
  packages/routing-sdk/addons/ton-v2/src/constants/poolType.ts
  packages/routing-sdk/addons/ton-v2/src/createTonPool.ts
  packages/routing-sdk/addons/ton-v2/src/index.test.ts
  packages/routing-sdk/addons/ton-v2/src/index.ts
  packages/routing-sdk/addons/ton-v2/src/types.ts
  packages/routing-sdk/addons/ton-v2/tsconfig.json
  packages/routing-sdk/addons/ton-v2/tsup.config.ts
  packages/routing-sdk/addons/ton-v2/vitest.config.ts
  packages/routing-sdk/addons/ton/src/index.ts
  packages/ton-v2-sdk/CHANGELOG.md
  packages/ton-v2-sdk/package.json
  packages/ton-v2-sdk/src/abis/IPancakePair.ts
  packages/ton-v2-sdk/src/constants/AgnosticBaseCurrency.ts
  packages/ton-v2-sdk/src/constants/AgnosticNativeCurrency.ts
  packages/ton-v2-sdk/src/constants/AgnosticToken.ts
  packages/ton-v2-sdk/src/constants/CurrencyAmount.ts
  packages/ton-v2-sdk/src/constants/Jetton.ts
  packages/ton-v2-sdk/src/constants/Native.ts
  packages/ton-v2-sdk/src/constants/Token.ts
  packages/ton-v2-sdk/src/constants/chains.ts
  packages/ton-v2-sdk/src/constants/currency.ts
  packages/ton-v2-sdk/src/constants/index.ts
  packages/ton-v2-sdk/src/constants/nativeTokens.ts
  packages/ton-v2-sdk/src/index.test.ts
  packages/ton-v2-sdk/src/index.ts
  packages/ton-v2-sdk/src/types.ts
  packages/ton-v2-sdk/src/utils/amount.ts
  packages/ton-v2-sdk/src/utils/getAddress.ts
  packages/ton-v2-sdk/src/utils/index.ts
  packages/ton-v2-sdk/src/utils/price.ts
  packages/ton-v2-sdk/src/utils/swap.ts
  packages/ton-v2-sdk/src/utils/trade.ts
  packages/ton-v2-sdk/tsconfig.json
  packages/ton-v2-sdk/tsup.config.ts
  packages/ton-v2-sdk/vitest.config.ts
  pnpm-lock.yaml
Labels: size/XXL

#11168 fix: tokens icons fix, limit price message
  apps/web/package.json
  apps/web/src/views/Swap/Twap/Twap.tsx
  pnpm-lock.yaml
Labels: size/L

#11176 chore: rename PROS old token
  packages/tokens/src/constants/bsc.ts
Labels: size/XS

#11178 fix: add liquidity transaction succ
  apps/ton/src/pages/testMint/index.tsx
  apps/ton/src/ton/logic/liquidity/useAddLiquidity.ts
  apps/ton/src/ton/logic/swap/useSwap.ts
  apps/ton/src/ton/utils/address.ts
  apps/ton/src/ton/wrappers/tact_Router.ts
  apps/ton/src/views/TONAddLiquidity/AddLiquidityCard/CardContent.tsx
  apps/ton/src/views/TONSwap/SwapForm.tsx
Labels: size/L

#11179 fix: integrate addLiquidity and swap to sc
  apps/ton/src/pages/testMint/index.tsx
  apps/ton/src/ton/logic/liquidity/useAddLiquidity.ts
  apps/ton/src/ton/logic/swap/useSwap.ts
  apps/ton/src/ton/wrappers/tact_Router.ts
Labels: size/L

#11173 fix: User gauges takes too much time to load on slow networks and fix loading indicator
  apps/web/src/utils/viem.ts
  apps/web/src/views/CakeStaking/hooks/useVeCakeUserInfo.ts
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/hooks/useGaugeRows.ts
  apps/web/src/views/GaugesVoting/hooks/useUserVoteGauges.ts
Labels: size/S

#11174 fix: Update router query always when on wallet connect
  apps/web/src/hooks/useWalletConnectRouterSync.ts
  apps/web/src/pages/_app.tsx
  apps/web/src/views/SwapSimplify/V4Swap/SwapCommitButton.tsx
  packages/utils/replaceBrowserHistory.ts
  packages/utils/replaceBrowserHistoryMultiple.ts
Labels: size/M

#11186 fix: refactor swap
  apps/ton/src/ton/logic/liquidity/useAddLiquidity.ts
  apps/ton/src/ton/logic/swap/useSwap.ts
  apps/ton/src/ton/wrappers/tact_Router.ts
  apps/ton/src/views/TONSwap/SwapForm.tsx
  packages/ton-v2-sdk/src/abis/IPancakePair.ts
  packages/ton-v2-sdk/src/constants/CurrencyAmount.ts
  packages/ton-v2-sdk/src/constants/currency/AgnosticBaseCurrency.ts
  packages/ton-v2-sdk/src/constants/currency/AgnosticNativeCurrency.ts
  packages/ton-v2-sdk/src/constants/currency/AgnosticToken.ts
  packages/ton-v2-sdk/src/constants/currency/Jetton.ts
  packages/ton-v2-sdk/src/constants/currency/Native.ts
  packages/ton-v2-sdk/src/constants/currency/Token.ts
  packages/ton-v2-sdk/src/constants/currency/currency.ts
  packages/ton-v2-sdk/src/constants/currency/index.ts
  packages/ton-v2-sdk/src/constants/index.ts
  packages/ton-v2-sdk/src/constants/nativeTokens.ts
  packages/ton-v2-sdk/src/constants/opcodes.ts
  packages/ton-v2-sdk/src/index.test.ts
  packages/ton-v2-sdk/src/index.ts
  packages/ton-v2-sdk/src/utils/index.ts
  packages/ton-v2-sdk/src/utils/liquidity.ts
  packages/ton-v2-sdk/src/utils/swap.ts
Labels: size/L

#11191 feat: 🎸 Update cache config
  apps/web/src/pages/api/configs/farms/v2/index.ts
Labels: size/XS

#11193 fix: only display pcs space proposal
  apps/web/src/pages/voting/proposal/[id].tsx
  apps/web/src/state/types.ts
  apps/web/src/state/voting/helpers.ts
Labels: size/S

#11194 fix: resolved switch swap
  apps/ton/src/atoms/swap/swapStateAtom.ts
  apps/ton/src/components/TonSwap/CurrencyInputPanelSimplify/index.tsx
  apps/ton/src/config/constants/tokens.ts
  apps/ton/src/hooks/swap/useAllCommonPairs.ts
  apps/ton/src/hooks/swap/useTradeExactIn.ts
  apps/ton/src/hooks/swap/useTradeExactOut.ts
  apps/ton/src/ton/atom/liquidity/poolDataQueriesAtom.ts
  apps/ton/src/views/TONSwap/SwapForm.tsx
  packages/ton-v2-sdk/src/constants/currency/AgnosticToken.ts
  packages/ton-v2-sdk/src/constants/currency/Native.ts
Labels: size/L

#11197 fix: add liquidity support native TON
  apps/ton/public/lists/testnet.json
  apps/ton/src/hooks/swap/useAllCommonPairs.ts
  apps/ton/src/hooks/useUserAddress.ts
  apps/ton/src/ton/generateQueryId.ts
  apps/ton/src/ton/logic/liquidity/useAddLiquidity.ts
  apps/ton/src/ton/logic/swap/useSwap.ts
Labels: size/L

#11200 fix: add translation keys and ci for TON
  apps/ton/src/views/TONSwap/SwapForm.tsx
  apps/web/src/__tests__/translations.test.ts
  packages/localization/src/config/translations.json
Labels: size/M

#11202 feat: 🎸 Add andy competition
  apps/web/src/components/AdPanel/Ads/AdTradingCompetition.tsx
  apps/web/src/components/AdPanel/config.tsx
  apps/web/src/components/PhishingWarningBanner/TradingCompetition.tsx
  apps/web/src/components/PhishingWarningBanner/index.tsx
Labels: size/M

#11205 fix: v2 miss stake button
  apps/web/src/state/farmsV4/state/extendPools/fetcher.ts
  packages/farms/index.test.ts
  packages/farms/src/farms/index.ts
  packages/farms/src/utils.ts
Labels: size/S

#11206 fix: v2 stake fetch allowance fail
  apps/web/src/state/farmsV4/state/accountPositions/fetcher.ts
Labels: size/S

#11207 fix: onramp image
  apps/web/src/views/BuyCrypto/components/OnRampProviderLogo/OnRampProviderLogo.tsx
Labels: size/XS

#11201 perf: Memoize bridge props to avoid triggering effect logic on each render
  packages/canonical-bridge/src/modules/wallet/BridgeWalletProvider.tsx
  packages/canonical-bridge/src/views/index.tsx
Labels: size/S

#11208 fix: ton swap details deopdown UI
  apps/ton/src/views/TONSwap/AdvancedSwapDetailsDropdown.tsx
  apps/ton/src/views/TONSwap/SwapForm.tsx
Labels: size/S

#11188 fix: Crash when scaled number too big
  packages/utils/formatFractions.ts
Labels: size/XS, Sentry

#11195 fix: Crash when document body null
  packages/uikit/src/components/Overlay/Overlay.tsx
Labels: size/S, Sentry

#11211 fix: ton swap details fee
  apps/ton/src/atoms/swap/swapDetailPanelStateAtom.ts
  apps/ton/src/components/TonSwap/ButtonAndDetailsPanel.tsx
  apps/ton/src/components/TonSwap/PricingAndSlippage.tsx
  apps/ton/src/components/TonSwap/SwapCommitButton.tsx
  apps/ton/src/hooks/swap/useIsSwapDetailPanelOpen.ts
  apps/ton/src/views/TONSwap/AdvancedSwapDetails.tsx
  apps/ton/src/views/TONSwap/AdvancedSwapDetailsDropdown.tsx
  apps/ton/src/views/TONSwap/SwapForm.tsx
Labels: size/L

#11192 fix: Crash when output amount zero
  packages/smart-router/evm/v3-router/utils/getPriceImpact.ts
Labels: size/XS, Sentry

#11209 feat: 🎸 add common banner and infostripe config
  apps/web/src/components/AdPanel/Ads/AdCommon.tsx
  apps/web/src/components/AdPanel/Ads/AdTradingCompetition.tsx
  apps/web/src/components/AdPanel/Card.tsx
  apps/web/src/components/AdPanel/InfoStripes/AIPredictionStripe.tsx
  apps/web/src/components/AdPanel/InfoStripes/Allora.tsx
  apps/web/src/components/AdPanel/InfoStripes/Countdown.tsx
  apps/web/src/components/AdPanel/InfoStripes/FeeRefund.tsx
  apps/web/src/components/AdPanel/InfoStripes/ICampaignBanner.ts
  apps/web/src/components/AdPanel/InfoStripes/InfoStripeCommon.tsx
  apps/web/src/components/AdPanel/InfoStripes/SolvStrip.tsx
  apps/web/src/components/AdPanel/InfoStripes/Step1.tsx
  apps/web/src/components/AdPanel/InfoStripes/Step2.tsx
  apps/web/src/components/AdPanel/InfoStripes/Step3.tsx
  apps/web/src/components/AdPanel/InfoStripes/TextHighlight.tsx
  apps/web/src/components/AdPanel/InfoStripes/TradingCompetition.tsx
  apps/web/src/components/AdPanel/InfoStripes/index.tsx
  apps/web/src/components/AdPanel/config.tsx
  apps/web/src/components/AdPanel/hooks/useAdsConfig.ts
  apps/web/src/components/AdPanel/types.ts
  apps/web/src/components/Menu/index.tsx
  apps/web/src/views/Predictions/components/InPageBanner.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#11213 fix: 🐛 fix apr issues
  apps/web/src/views/universalFarms/utils/sumApr.ts
Labels: size/XS

#11196 fix: Killed gauges display problem ; reduce the ttl for cache by lru
  apps/web/src/pages/api/gauges/getAllGauges.ts
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/List.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/TableRow.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/hooks/useGaugeRows.ts
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/index.tsx
  apps/web/src/views/GaugesVoting/hooks/useGauges.ts
  apps/web/src/views/GaugesVoting/hooks/useUserVote.ts
  apps/web/src/views/GaugesVoting/hooks/useVotedPower.ts
  packages/gauges/package.json
  packages/gauges/src/constants/config/getGauges.ts
  packages/gauges/src/fetchAllGauges.ts
  packages/gauges/src/fetchGaugeVoting.ts
  packages/gauges/src/getAllGauges.ts
  packages/localization/src/config/translations.json
  packages/utils/cacheByLRU.ts
  packages/utils/package.json
  pnpm-lock.yaml
Labels: size/L

#11214 feat: ton swap confirm modal
  apps/ton/src/atoms/modals/confirmSwapModalAtom.tsx
  apps/ton/src/atoms/modals/transactionModalAtom.tsx
  apps/ton/src/components/Modals/ActionModal.tsx
  apps/ton/src/components/TonSwap/ConfirmSwapModal/index.tsx
  apps/ton/src/components/TonSwap/FormattedPriceImpact.tsx
  apps/ton/src/components/TonSwap/SwapDetails/AdvancedSwapDetails.tsx
  apps/ton/src/components/TonSwap/SwapDetails/AdvancedSwapDetailsDropdown.tsx
  apps/ton/src/components/TonSwap/SwapDetails/PricingAndSlippage.tsx
  apps/ton/src/components/TonSwap/SwapDetails/SwapRoute.tsx
  apps/ton/src/ton/logic/liquidity/useAddLiquidity.ts
  apps/ton/src/ton/logic/liquidity/useRemoveLiquidity.ts
  apps/ton/src/ton/logic/swap/useSwap.ts
  apps/ton/src/views/TONSwap/SwapForm.tsx
  apps/web/src/views/Swap/components/CurrencyInputHeader.tsx
  apps/web/src/views/SwapSimplify/V4Swap/index.tsx
  packages/localization/src/config/translations.json
  packages/widgets-internal/index.ts
  packages/widgets-internal/swap-v2/SwapWidgetV2.tsx
  packages/widgets-internal/swap-v2/TradePrice.tsx
  packages/widgets-internal/swap-v2/index.ts
  packages/widgets-internal/swap/ApproveModalContent.tsx
  packages/widgets-internal/swap/Logos.tsx
  packages/widgets-internal/swap/SwapPendingModalContent.tsx
  packages/widgets-internal/swap/SwapPendingModalContentV1.tsx
  packages/widgets-internal/swap/TokenTransferInfo.tsx
Labels: size/XL

#11217 fix: update mim out value
  apps/ton/src/components/Modals/ActionModal.tsx
  apps/ton/src/components/TonSwap/CurrencyInputPanelSimplify/index.tsx
  apps/ton/src/components/widgets/swap-v2/CurrencyInputPanelSimplify.tsx
  apps/ton/src/views/TONSwap/SwapForm.tsx
  apps/ton/tsconfig.json
  packages/localization/src/config/translations.json
Labels: size/L

#11218 fix: refetch quote
  apps/ton/src/hooks/swap/useAllCommonPairs.ts
  apps/ton/src/ton/atom/liquidity/poolDataQueriesAtom.ts
Labels: size/S

#11219 fix: ton floating bar icon
  apps/ton/src/components/FloatingNavigation.tsx
  apps/ton/src/ton/logic/liquidity/useAddLiquidity.ts
  apps/ton/src/ton/utils/generateQueryId.ts
Labels: size/XS

#11220 chore: remove xmax effect on swap page
  apps/web/src/views/Swap/Twap/TwapSwap.tsx
  apps/web/src/views/SwapSimplify/index.tsx
Labels: size/XS

#11224 feat: TON multiple hops
  apps/ton/public/lists/testnet.json
  apps/ton/src/components/TonSwap/SwapCommitButton.tsx
  apps/ton/src/config/constants/exchange.ts
  apps/ton/src/config/presetPools.ts
  apps/ton/src/ton/logic/swap/useSwap.ts
  apps/ton/src/utils/maxAmountSpend.ts
  apps/ton/src/views/TONSwap/SwapForm.tsx
  packages/ton-v2-sdk/src/utils/swap.ts
Labels: size/L

#11225 fix: NaN staking balance causes roi modal my balance not loaded correctly
  apps/web/src/state/pools/helpers.ts
Labels: size/XS

#11227 fix: TON whitelist token and pools
  apps/ton/public/lists/testnet.json
  apps/ton/src/config/constants/exchange.ts
  apps/ton/src/config/presetPools.ts
Labels: size/S

#11222 fix: Object not found crash on barchart tooltip
  apps/web/src/views/V3Info/components/DensityChart/CustomToolTip.tsx
  apps/web/src/views/V3Info/components/DensityChart/index.tsx
Labels: size/XS, Sentry

#11216 fix: Dynamic routes leak static routes
  apps/web/src/pages/liquidity/[tokenId].tsx
Labels: size/XS, Sentry

#11229 fix: TON swap error handle
  apps/ton/src/atoms/modals/errorMsgModalAtom.tsx
  apps/ton/src/atoms/modals/transactionModalAtom.tsx
  apps/ton/src/components/Modals/ActionModal.tsx
  apps/ton/src/ton/atom/liquidity/poolDataQueriesAtom.ts
  apps/ton/src/ton/logic/swap/useSwap.ts
  apps/ton/src/views/TONSwap/SwapForm.tsx
Labels: size/L

#11230 fix: TON swap retry
  apps/ton/src/ton/atom/liquidity/poolDataQueriesAtom.ts
Labels: size/S

#11233 fix: TON swap flip
  apps/ton/src/components/TonSwap/FlipButton.tsx
  apps/ton/src/hooks/swap/useSwapActionHandlers.ts
  apps/ton/src/views/TONSwap/SwapForm.tsx
Labels: size/S

#11231 fix: 🐛 stable swap network switch fix
  apps/web/src/hooks/useAccountEventListener.ts
Labels: size/XS

#11234 fix: 🐛 reduce farms' cache time to 20s
  apps/web/src/pages/api/configs/farms/v2/index.ts
Labels: size/S

#11237 chore: TON whitelist token
  apps/ton/public/lists/testnet.json
Labels: size/XS

#11238 chore: TON whitelist pool
  apps/ton/src/config/presetPools.ts
Labels: size/XS

#11228 chore: support monad testnet
  apis/routing/src/provider.ts
  apps/aptos/components/NetworkSwitcher.tsx
  apps/gamification/components/NetworkSwitcher.tsx
  apps/gamification/config/nodes.ts
  apps/web/src/components/NetworkSwitcher.tsx
  apps/web/src/config/chains.ts
  apps/web/src/config/constants/contracts.ts
  apps/web/src/config/constants/exchange.ts
  apps/web/src/config/constants/lists.ts
  apps/web/src/config/constants/supportChains.ts
  apps/web/src/config/nodes.ts
  apps/web/src/config/pools.ts
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
  apps/web/src/views/TradingReward/config/pairs/index.tsx
  packages/chains/src/averageChainBlockTimes.ts
  packages/chains/src/chainId.ts
  packages/chains/src/chainNames.ts
  packages/chains/src/subgraphs.ts
  packages/farms/constants/common/index.ts
  packages/farms/src/const.ts
  packages/farms/src/v2/fetchFarmsV2.ts
  packages/multicall/src/constants/blockConflictTolerance.ts
  packages/permit2-sdk/src/constants.ts
  packages/routing-sdk/addons/quoter/src/constants/mixedRouteQuoterV1.ts
  packages/routing-sdk/addons/quoter/src/constants/v3Quoter.ts
  packages/routing-sdk/addons/quoter/src/fetchMixedRouteQuote.ts
  packages/routing-sdk/addons/quoter/src/fetchV3Quote.ts
  packages/smart-router/evm/constants/exchange.ts
  packages/smart-router/evm/constants/gasModel/index.ts
  packages/smart-router/evm/constants/gasModel/v3.ts
  packages/smart-router/evm/constants/multicall.ts
  packages/smart-router/evm/constants/v3.ts
  packages/smart-router/evm/v3-router/providers/onChainQuoteProvider.ts
  packages/swap-sdk-evm/src/constants.ts
  packages/tokens/src/allTokens.ts
  packages/tokens/src/constants/common.ts
  packages/tokens/src/constants/monadTestnet.ts
  packages/tokens/src/index.ts
  packages/universal-router-sdk/src/constants.ts
  packages/v2-sdk/src/constants.ts
  packages/v3-sdk/src/constants.ts
Labels: size/L

#11245 chore: update Ton center API endpoint and token
  apps/ton/src/ton/context/TonContext.ts
Labels: size/XS

#11246 chore: Remove quests from menu and components
  apps/web/src/components/AdPanel/Ads/AdQuests.tsx
  apps/web/src/components/AdPanel/Variations/ContentTwoActions.tsx
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/views/Home/components/Banners/QuestBanner.tsx
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#11248 fix: user slippage
  apps/ton/src/atoms/settings/settingsAtom.ts
  apps/ton/src/components/Buttons/SlippageButton.tsx
  apps/ton/src/components/Modals/AddLiquidityModal.tsx
  apps/ton/src/components/Modals/RemoveLiquidityModal.tsx
  apps/ton/src/components/TonSwap/SwapDetails/AdvancedSwapDetails.tsx
  apps/ton/src/components/TonSwap/SwapDetails/PricingAndSlippage.tsx
  apps/ton/src/hooks/useUserSlippage.ts
  apps/ton/src/views/TONAddLiquidity/AddLiquidityCard/CardContent.tsx
  apps/ton/src/views/TONSwap/SwapForm.tsx
Labels: size/M

#11249 feat: supported proxy TON addLiquidity and swap
  apps/ton/src/config/presetPools.ts
  apps/ton/src/ton/logic/liquidity/useAddLiquidity.ts
  apps/ton/src/ton/logic/swap/useSwap.ts
  apps/ton/src/ton/utils/address.ts
  apps/ton/src/ton/wrappers/tact_JettonMasterUSDT.ts
  packages/ton-v2-sdk/src/constants/nativeTokens.ts
  packages/ton-v2-sdk/src/constants/opcodes.ts
  packages/ton-v2-sdk/src/utils/liquidity.ts
Labels: size/M

#11247 chore: disable mev protect for binance web3 wallet
  apps/web/src/views/Mev/hooks/index.ts
Labels: size/XS

#11250 chore: remove ton addons and refactor ton-v2 sdk
  apps/ton/package.json
  packages/routing-sdk/addons/ton-v2/package.json
  packages/routing-sdk/addons/ton-v2/src/constants/gasCost.ts
  packages/routing-sdk/addons/ton-v2/src/constants/index.ts
  packages/routing-sdk/addons/ton-v2/src/constants/poolType.ts
  packages/routing-sdk/addons/ton-v2/src/createTonPool.ts
  packages/routing-sdk/addons/ton-v2/src/index.test.ts
  packages/routing-sdk/addons/ton-v2/src/index.ts
  packages/routing-sdk/addons/ton-v2/src/types.ts
  packages/routing-sdk/addons/ton-v2/tsconfig.json
  packages/routing-sdk/addons/ton-v2/tsup.config.ts
  packages/routing-sdk/addons/ton-v2/vitest.config.ts
  packages/ton-v2-sdk/src/constants/index.ts
  packages/ton-v2-sdk/src/constants/nativeTokens.ts
  packages/ton-v2-sdk/src/currency/AgnosticBaseCurrency.ts
  packages/ton-v2-sdk/src/currency/AgnosticNativeCurrency.ts
  packages/ton-v2-sdk/src/currency/AgnosticToken.ts
  packages/ton-v2-sdk/src/currency/Jetton.ts
  packages/ton-v2-sdk/src/currency/Native.ts
  packages/ton-v2-sdk/src/currency/Token.ts
  packages/ton-v2-sdk/src/currency/currency.ts
  packages/ton-v2-sdk/src/currency/index.ts
  packages/ton-v2-sdk/src/fractions/CurrencyAmount.ts
  packages/ton-v2-sdk/src/fractions/Price.ts
  packages/ton-v2-sdk/src/index.ts
  packages/ton-v2-sdk/src/types.ts
  packages/ton-v2-sdk/src/utils/amount.ts
  packages/ton-v2-sdk/src/utils/getAddress.ts
  packages/ton-v2-sdk/src/utils/price.ts
  packages/ton-v2-sdk/src/utils/route.ts
  packages/ton-v2-sdk/src/utils/trade.ts
  pnpm-lock.yaml
Labels: size/L

#11251 chore: changeset for monad testnet
  .changeset/breezy-parrots-notice.md
Labels: size/S

#11252 fix: ton token sortsBefore logic
  apps/ton/public/lists/testnet.json
  packages/ton-v2-sdk/src/currency/AgnosticToken.ts
  packages/ton-v2-sdk/src/index.test.ts
  packages/ton-v2-sdk/src/index.ts
  packages/ton-v2-sdk/src/utils/address.ts
  packages/ton-v2-sdk/src/utils/getAddress.ts
  packages/ton-v2-sdk/src/utils/index.ts
Labels: size/S

#11263 chore: whitelist pTON-PAN
  apps/ton/src/config/presetPools.ts
  apps/ton/src/views/TONAddLiquidity/AddLiquidityCard/CardContent.tsx
  apps/ton/src/views/TONRemoveLiquidity/RemoveLiquidityCard/CardContent.tsx
Labels: size/S

#11265 fix: ton swap decimal and sort
  apps/ton/src/hooks/swap/useAllCommonPairs.ts
  apps/ton/src/ton/atom/jettonWalletAddressAtom.ts
  apps/ton/src/ton/atom/liquidity/poolDataQueryAtom.ts
  apps/ton/src/ton/context/TonContext.ts
  apps/ton/src/ton/logic/liquidity/useAddLiquidity.ts
  apps/ton/src/ton/logic/swap/useSwap.ts
  apps/ton/src/ton/utils/address.ts
  apps/ton/src/views/TONSwap/SwapForm.tsx
Labels: size/L

#11266 fix: ton swap native TON amount incorrect
  apps/ton/src/ton/logic/swap/useSwap.ts
Labels: size/XS

#11267 fix: ton swap amount incorrect
  apps/ton/src/ton/logic/swap/useSwap.ts
Labels: size/S

#11268 fix: update tTON to TON as bases tokens for swap
  apps/ton/src/config/constants/exchange.ts
Labels: size/S

#11269 feat: Add options sunset notification
  apps/web/src/config/constants/options-sunset-addresses.json
  apps/web/src/hooks/useOptionsSunsetNotification.tsx
  apps/web/src/pages/_app.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#11255 chore: fix monad position display issue
  apps/web/src/state/farmsV4/state/accountPositions/fetcher/v3/getAccountV3Positions.ts
  apps/web/src/state/farmsV4/state/accountPositions/fetcher/v3/getAccountV3TokenIds.ts
  apps/web/src/views/universalFarms/hooks/useMultiChains.ts
Labels: size/M

#11270 fix: add/remove liquidity events
  apps/ton/src/hooks/swap/useAllCommonPairs.ts
  apps/ton/src/pages/_app.tsx
  apps/ton/src/ton/logic/liquidity/useAddLiquidity.ts
  apps/ton/src/ton/logic/swap/useSwap.ts
  apps/ton/src/utils/customGTMEventTracking.ts
  apps/ton/src/views/TONAddLiquidity/AddLiquidityCard/CardContent.tsx
  apps/ton/src/views/TONRemoveLiquidity/RemoveLiquidityCard/CardContent.tsx
  apps/ton/src/views/TONSwap/SwapForm.tsx
Labels: size/L

#11271 fix: ton swap url reflect
  apps/ton/package.json
  apps/ton/src/atoms/swap/swapStateAtom.ts
  apps/ton/src/components/TonSwap/FlipButton.tsx
  apps/ton/src/components/TonSwap/SwapCommitButton.tsx
  apps/ton/src/hooks/swap/useSwapActionHandlers.ts
  apps/ton/src/hooks/tokens/useCurrency.ts
  apps/ton/src/views/TONAddLiquidity/AddLiquidityCard/CardContent.tsx
  apps/ton/src/views/TONSwap/SwapForm.tsx
  pnpm-lock.yaml
Labels: size/L

#11272 fix: ton swap url reflect
  apps/ton/src/atoms/swap/swapStateAtom.ts
Labels: size/S

#11273 fix: native TON trade compare
  apps/ton/src/config/constants/exchange.ts
  apps/ton/src/hooks/swap/useAllCommonPairs.ts
  packages/ton-v2-sdk/src/utils/trade.ts
Labels: size/S

#11276 fix: update pTON to TON
  apps/ton/src/components/TonSwap/SearchModal/CurrencyList.tsx
  apps/ton/src/components/TonSwap/SwapDetails/SwapRoute.tsx
  apps/ton/src/ton/logic/liquidity/useRemoveLiquidity.ts
  apps/ton/src/ton/utils/tokenOrder.ts
  apps/ton/src/utils/getLink.ts
  apps/ton/src/utils/tokens/currency.ts
  apps/ton/src/utils/tokens/unwrappedToken.ts
  apps/ton/src/views/TONLiquidity/LiquidityCard/LiquidityRow.tsx
  apps/ton/src/views/TONRemoveLiquidity/RemoveLiquidityCard/CardContent.tsx
Labels: size/M

#11277 fix: ton swap connect wallet button
  apps/ton/src/views/TONSwap/SwapForm.tsx
Labels: size/M

#11278 fix: add liquidity native TON order
  apps/ton/src/ton/logic/liquidity/useAddLiquidity.ts
  apps/ton/src/ton/utils/tokenOrder.ts
Labels: size/S
