Repository pancakeswap/pancake-frontend, pull requests merged in 2025-07, with the labels that each got.

#11879 fix: add prediction datadog
  apps/web/src/views/Predictions/components/RoundCard/OpenRoundCard.tsx
Labels: size/S

#11880 fix: update link for tips
  apps/solana/src/features/Create/ClmmPool/CreateClmmPool.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#11882 perf: position list
  apps/solana/src/features/Portfolio/components/SectionMyPositions/TabClmm.tsx
  apps/solana/src/features/Portfolio/components/SectionMyPositions/components/Clmm/ClmmPositionItemsCard.tsx
  apps/solana/src/features/Portfolio/index.tsx
Labels: size/M

#11864 feat: add solana liquidity ad
  apps/web/src/components/AdPanel/Ads/AdCommon.tsx
  apps/web/src/components/AdPanel/config.tsx
  apps/web/src/components/AdPanel/hooks/useAdsConfig.ts
  apps/web/src/components/AdPanel/types.ts
  packages/localization/src/config/translations.json
Labels: size/M

#11881 fix: update tooltip content
  apps/solana/src/features/Pools/components/PoolListItem.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#11883 refactor: remove unused NavMoreButtonMenuPanel and DisclaimerPage components
  apps/solana/src/components/AppLayout/components/DisclaimerModal.tsx
  apps/solana/src/components/AppLayout/components/NavMoreButtonMenuPanel.tsx
  apps/solana/src/pages/docs/disclaimer.tsx
Labels: size/L

#11884 chore: hide disclaimer
  apps/solana/src/components/AppLayout/components/DisclaimerModal.tsx
Labels: size/XS

#11885 fix: update swap token address
  apps/solana/next.config.mjs
  apps/solana/src/features/Pools/components/PoolTableColumns/ColumnsPoolActions.tsx
  apps/solana/src/pages/__swap_.tsx
  apps/solana/src/pages/jupiter-swap.tsx
  apps/solana/src/pages/swap.tsx
  apps/solana/src/utils/config/routers.ts
Labels: size/M

#11890 fix: update jup price api
  apps/solana/src/features/JupiterSwap/Swap.tsx
  packages/jupiter-terminal/overrides/src/contexts/USDValueProvider.tsx
Labels: size/L

#11891 fix: undefined token
  packages/jupiter-terminal/overrides/src/components/Form.tsx
Labels: size/XS

#11892 fix: update FormattedUltraQuoteResponse
  packages/jupiter-terminal/overrides/src/entity/FormattedUltraQuoteResponse.ts
Labels: size/M

#11895 chore: resolved type error
  apps/solana/src/features/Staking/components/StakingPoolItem.tsx
  apps/solana/src/features/Swap/components/SwapPanel.tsx
  apps/solana/src/hooks/toast/useTxStatus.tsx
Labels: size/XS

#11900 chore: update swap event
  apps/solana/src/utils/report/curstomGTMEventTracking.ts
Labels: size/XS

#11902 feat: integrate OKX and backpack wallets
  apps/solana/src/provider/WalletProvider.tsx
  apps/solana/src/provider/walletAdapter/BackpackWalletAdapter.ts
  apps/solana/src/provider/walletAdapter/Ledger/LedgerWalletAdapter.ts
  apps/solana/src/provider/walletAdapter/Ledger/polyfill.ts
  apps/solana/src/provider/walletAdapter/Ledger/util.ts
  apps/solana/src/provider/walletAdapter/OKXWalletAdapter.ts
Labels: size/XL

#11903 fix: token icon load failed all the time
  apps/solana/src/components/TokenAvatar.tsx
  apps/solana/src/features/Swap/components/SwapInfoBoard.tsx
  apps/solana/src/provider/WalletProvider.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#11889 fix: Unused translations
  apps/solana/src/features/Pools/components/PoolListItem.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#11906 fix: remove raydium monitor events
  apps/solana/src/api/axios.ts
  apps/solana/src/components/WalletRecentTransactionBoard.tsx
  apps/solana/src/features/Portfolio/index.tsx
  apps/solana/src/hooks/app/useInitConnection.ts
  apps/solana/src/provider/WalletProvider.tsx
  apps/solana/src/utils/report/curstomGTMEventTracking.ts
  apps/solana/src/utils/report/datadog.ts
Labels: size/M

#11905 chore: unify pool links
  apps/web/src/utils/getPoolLink.ts
  apps/web/src/views/AddLiquidityInfinity/components/PoolList.tsx
  apps/web/src/views/PoolDetail/components/MyPositions.tsx
  apps/web/src/views/universalFarms/PoolsPage.tsx
  apps/web/src/views/universalFarms/components/PoolListItemAction.tsx
  apps/web/src/views/universalFarms/components/PoolListView.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#11909 chore: remove turkish
  apps/gamification/config/wallet.ts
  apps/web/src/config/wallet.ts
  apps/web/src/utils/getPerpetualLanguageCode.ts
  packages/localization/src/config/languages.ts
  packages/ui-wallets/src/docLangCodeMapping.ts
Labels: size/XS

#11919 feat: add tvl chart for solana pool
  apps/solana/src/features/Pools/Pools.tsx
  apps/solana/src/features/Pools/components/PoolChart/Chart.tsx
  apps/solana/src/features/Pools/components/PoolChart/index.tsx
  apps/solana/src/features/Pools/components/PoolDetailMobileDrawer.tsx
  apps/solana/src/hooks/pool/useFetchPoolChartData.ts
  apps/solana/src/hooks/pool/useFetchPoolChartTvl.ts
  apps/solana/src/store/configs/urls.ts
  apps/solana/src/store/useAppStore.ts
Labels: size/L

#11927 fix: lbamm liquidity chart default zoom level
  apps/web/src/views/PoolDetail/components/ChartLiquidity/BasicChartLiquidity.tsx
  apps/web/src/views/PoolDetail/components/ChartLiquidity/ChartInfinityBinLiquidity.tsx
  apps/web/src/views/PoolDetail/components/ChartLiquidity/type.ts
Labels: size/S

#11904 feat: update next config
  apps/web/next.config.mjs
Labels: size/XS

#11928 feat(PAN-7078): add new hook
  packages/infinity-sdk/src/constants/hooksList/bsc.ts
Labels: size/S

#11931 fix: Perpetual disclaimer not shown on mobile
  apps/web/src/components/Menu/index.tsx
  packages/uikit/src/components/BottomNav/BottomNav.tsx
  packages/uikit/src/components/BottomNavItem/BottomNavItem.tsx
  packages/uikit/src/components/BottomNavItem/types.ts
  packages/uikit/src/components/DropdownMenu/DropdownMenu.tsx
  packages/uikit/src/widgets/Menu/Menu.tsx
  packages/uikit/src/widgets/Modal/useModal.ts
Labels: size/M

#11937 fix: add warning for pandiai
  apps/web/src/config/constants/swapWarningTokens.ts
  apps/web/src/config/constants/warningTokens/bscWarningTokens.ts
  apps/web/src/views/AddLiquidity/hooks/useWarningLiquidity.tsx
  apps/web/src/views/AddLiquidity/index.tsx
  apps/web/src/views/AddLiquidityV3/index.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/PUNDIAIWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/index.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#11936 fix: update tg links and blog lang
  apps/blog/hooks/useLanguage.ts
  packages/localization/src/config/languages.ts
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/components/Footer/config.tsx
Labels: size/M

#11926 chore(cross-chain): support zksync, linea
  apps/web/src/quoter/utils/crosschain-utils/config.ts
Labels: size/M

#11616 feat: chart integration
  apps/web/package.json
  apps/web/src/components/Chart/ChartWithPriceHeader.tsx
  apps/web/src/components/Chart/PriceHeader.tsx
  apps/web/src/components/Chart/TradingViewChart.tsx
  apps/web/src/components/Chart/atom/chartPriceDataAtom.ts
  apps/web/src/components/Chart/lib/.prettierignore
  apps/web/src/components/Chart/lib/pancakeswap-charting-library.d.ts
  apps/web/src/components/Chart/lib/pancakeswap-charting-library.es.js
  apps/web/src/pages/swap/twap.tsx
  apps/web/src/views/Swap/Twap/TwapSwap.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/SwapSelectionTab.tsx
  apps/web/src/views/SwapSimplify/index.tsx
  packages/uikit/src/widgets/Modal/BottomDrawer/BottomDrawer.tsx
  packages/widgets-internal/components/CurrencyLogo/CurrencyLogo.tsx
Labels: size/XL

#11943 chore: filter non-whitelisted hook
  apps/web/src/quoter/atom/bestSameChainAtom.ts
  apps/web/src/state/farmsV4/search/edgeFarmQueries.ts
  packages/smart-router/evm/infinity-router/queries/remotePoolTransform.ts
Labels: size/M

#11948 fix(gift): cannot download QR image when token logo URL images/tokens/:address
  apps/web/next.config.mjs
  apps/web/src/hooks/useElementToCanvas.ts
  apps/web/src/views/Gift/components/CurrencyAmountGiftDisplay.tsx
  packages/widgets-internal/components/CurrencyLogo/CurrencyLogo.tsx
Labels: size/S

#11949 chore: chart improvements
  apps/web/src/components/AdPanel/DesktopCard.tsx
  apps/web/src/components/Chart/AggregatePricingModal.tsx
  apps/web/src/components/Chart/TradingViewChart.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/ButtonAndDetailsPanel.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/SwapSelectionTab.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/atoms.ts
  apps/web/src/views/SwapSimplify/index.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#11951 fix: hooks list undefined in infinity router
  packages/smart-router/evm/infinity-router/queries/remotePoolTransform.ts
Labels: size/XS

#11941 chore: add trans component ( Fix translation breaks )
  apps/web/src/__tests__/translations.test.ts
  apps/web/src/components/AccessRisk/AccessRiskTooltips.tsx
  apps/web/src/components/AdPanel/FAQ/config/swap.tsx
  apps/web/src/components/Chart/ChartbyLabel.tsx
  apps/web/src/components/Merkl/MerklSection.tsx
  apps/web/src/components/PositionCard/index.tsx
  apps/web/src/index.tsx
  apps/web/src/views/Lottery/components/RewardBracketDetail.tsx
  apps/web/src/views/PositionManagers/components/SingleTokenWarning.tsx
  apps/web/src/views/PositionManagers/components/SunsetWarning.tsx
  apps/web/src/views/Pottery/index.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/BTTWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/CcarWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/ItamWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/LUSDWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/METISWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/SafemoonWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/UniBTCWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/XCADWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/mainnet/ALETHWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/zksync/USDPlusWarning.tsx
  packages/localization/package.json
  packages/localization/src/Provider.tsx
  packages/localization/src/Trans.tsx
  packages/localization/src/config/translations.json
  packages/localization/src/i18n.ts
  packages/localization/src/useTranslation.ts
  pnpm-lock.yaml
Labels: size/XL

#11954 chore: remove v2 in solana
  apps/solana/src/features/Create/components/CreatePoolEntryDialog.tsx
  apps/solana/src/features/Pools/Pools.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#11960 fix: wrap out using contract balance
  .changeset/serious-bats-scream.md
  packages/universal-router-sdk/src/entities/protocols/TradePlanner.ts
  packages/universal-router-sdk/test/__snapshots__/router.Infinity.clamm.test.ts.snap
  packages/universal-router-sdk/test/router.Infinity.clamm.test.ts
Labels: size/S

#11961 chore: New Crowdin updates
  locales/hi-IN.json
  locales/ko-KR.json
Labels: size/L

#11965 chore: update unwrap charges universal router
  .changeset/curvy-llamas-clap.md
  packages/universal-router-sdk/src/entities/protocols/TradePlanner.ts
  packages/universal-router-sdk/test/__snapshots__/router.Infinity.clamm.test.ts.snap
  packages/universal-router-sdk/test/__snapshots__/router.Infinity.mix.test.ts.snap
  packages/universal-router-sdk/test/__snapshots__/trade.test.ts.snap
  packages/universal-router-sdk/test/router.Infinity.clamm.test.ts
Labels: size/L

#11969 chore: New Crowdin updates
  locales/ar-SA.json
  locales/de-DE.json
  locales/el-GR.json
  locales/pl-PL.json
  locales/vi-VN.json
  locales/zh-TW.json
Labels: size/XXL

#11978 feat: add new ammconfig
  .github/workflows/unitTests.yml
  apps/solana/src/features/Clmm/components/LiquidityChartRangeInput/Chart.tsx
  packages/solana-clmm-sdk/src/clmm/ammConfigs.ts
Labels: size/M

#11981 chore: add components for header
  .changeset/happy-clouds-unite.md
  package.json
  packages/jupiter-terminal/package.json
  packages/jupiter-terminal/scripts/build.sh
  packages/uikit/src/components/BottomNav/index.tsx
  packages/uikit/src/components/MenuItem/styles.tsx
  packages/uikit/src/components/index.ts
  packages/uikit/src/index.ts
  packages/uikit/src/util/findMenuItemsStatusColor.ts
  packages/uikit/src/widgets/Menu/Menu.tsx
  packages/uikit/src/widgets/Menu/context.ts
  packages/uikit/src/widgets/Menu/styled.ts
  packages/uikit/src/widgets/SimpleMenu/SimpleMenu.tsx
  packages/uikit/src/widgets/SimpleMenu/components/AnnouncementBanner.tsx
  packages/uikit/src/widgets/SimpleMenu/components/CakePriceWidget.tsx
  packages/uikit/src/widgets/SimpleMenu/components/LocaleSelector.tsx
  packages/uikit/src/widgets/SimpleMenu/components/Navigation.tsx
  packages/uikit/src/widgets/SimpleMenu/components/SimpleConnectButton.tsx
  packages/uikit/src/widgets/SimpleMenu/components/index.ts
  packages/uikit/src/widgets/SimpleMenu/hooks/useIsomorphicLayoutEffect.ts
  packages/uikit/src/widgets/SimpleMenu/index.ts
  packages/uikit/vite.config.ts
  pnpm-lock.yaml
Labels: size/XL

#11984 fix: farm-networks-search
  apps/web/src/views/universalFarms/atom/farmsSearchAtom.ts
Labels: size/S

#11986 fix: solana toast i18n PAN-7243/
  apps/solana/src/store/configs/clmm.tsx
  apps/web/src/__tests__/translations.test.ts
  packages/localization/src/config/translations.json
Labels: size/L

#11980 feat: support SVM Quoter
  apps/web/src/components/CurrencyInputPanelSimplify/index.tsx
  apps/web/src/hooks/useAutoSlippage.tsx
  apps/web/src/hooks/useAutoSlippageWithFallback.tsx
  apps/web/src/hooks/useUnifiedCurrencyBalance.ts
  apps/web/src/quoter/atom/bestAMMTradeFromQuoterWorker2Atom.ts
  apps/web/src/quoter/atom/bestSVMOrderAtom.ts
  apps/web/src/quoter/atom/bestSameChainAtom.ts
  apps/web/src/quoter/hook/useQuoterSync.ts
  apps/web/src/quoter/quoter.types.ts
  apps/web/src/quoter/utils/__test__/parseSVMTradeIntoSVMOrder.test.ts
  apps/web/src/quoter/utils/svm-utils/parseSVMTradeIntoSVMOrder.ts
  apps/web/src/state/wallet/hooks.ts
  apps/web/src/views/Swap/V3Swap/components/TransactionConfirmSwapContentV2.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalState.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useParsedAmounts.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSwapCurrency.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSwapInputError.ts
  apps/web/src/views/Swap/V3Swap/utils/exchange.ts
  apps/web/src/views/Swap/components/SwapRoute.tsx
  apps/web/src/views/Swap/utils.ts
  apps/web/src/views/SwapSimplify/InfinitySwap/AdvancedSwapDetails.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/FormMainInfinity.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/SwapCommitButton.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/TradeDetails.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/TradingFee.tsx
  apps/web/src/views/SwapSimplify/hooks/useIsPriceImpactTooHigh.ts
  packages/price-api-sdk/src/types/order.ts
  packages/price-api-sdk/src/types/orderType.ts
  packages/smart-router/evm/v3-router/types/pool.ts
  packages/smart-router/evm/v3-router/types/route.ts
  packages/solana-router-sdk/src/FormattedUltraQuoteResponse.ts
  packages/solana-router-sdk/src/getBestTrade.ts
  packages/swap-sdk-core/src/splToken.ts
  packages/swap-sdk-core/test/token.test.ts
  packages/utils/__tests__/tryParseAmount.test.ts
  packages/utils/tryParseAmount.ts
Labels: size/XL

#11990 fix: Failed to prompt wallet connect modal
  packages/next-config/withWebSecurityHeaders.ts
Labels: size/XS

#11992 fix: wallet connect issue
  .gitignore
  apps/web/src/components/ConnectWalletButton.tsx
  apps/web/src/contexts/Privy/privy.tsx
Labels: size/S

#11994 chore: Block framing for embedded wallet
  apps/web/src/hooks/useSecurityBlocking.ts
  apps/web/src/pages/_app.tsx
Labels: size/S

#11993 fix: i18n template escape issue
  packages/localization/src/Provider.tsx
  packages/localization/src/useTranslation.ts
Labels: size/M

#11999 fix: i18n regexp
  apps/web/.env.development
  packages/localization/src/useTranslation.ts
Labels: size/S

#12001 feat: sol swap execute
  apps/web/src/quoter/atom/bestSVMOrderAtom.ts
  apps/web/src/quoter/hook/useQuoterSync.ts
  apps/web/src/quoter/utils/svm-utils/parseSVMTradeIntoSVMOrder.ts
  apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalState.tsx
  packages/price-api-sdk/src/types/order.ts
  packages/solana-router-sdk/src/UltraSwapError.ts
  packages/solana-router-sdk/src/UltraSwapService.ts
  packages/solana-router-sdk/src/getBestTrade.ts
  packages/solana-router-sdk/src/index.ts
  packages/solana-router-sdk/src/types.ts
Labels: size/L

#12002 chore: fix missing deps
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/XS

#11955 chore: Remove polygon zkevm eth from buy crypto
  apps/web/src/components/SearchModal/OnRampCurrencyModal.tsx
  apps/web/src/views/BuyCrypto/constants.ts
  apps/web/src/views/BuyCrypto/containers/BuyCryptoForm.tsx
  apps/web/src/views/BuyCrypto/containers/FormContainer.tsx
Labels: size/S

#12004 chore: fix type error
  apps/web/src/contexts/Privy/atom.ts
  apps/web/src/global.d.ts
  apps/web/src/quoter/atom/bestSVMOrderAtom.ts
  apps/web/src/quoter/atom/bestSameChainAtom.ts
  apps/web/src/quoter/hook/useQuoterSync.ts
  apps/web/src/quoter/hook/useSingleTokenSwapInfo.ts
  apps/web/src/quoter/quoter.types.ts
  apps/web/src/quoter/utils/__test__/parseSVMTradeIntoSVMOrder.test.ts
  apps/web/src/quoter/utils/createQuoteQuery.ts
  apps/web/src/quoter/utils/crosschain-utils/base/CrossChainQuoteStrategy.ts
  apps/web/src/quoter/utils/crosschain-utils/implementations/SwapToBridgeStrategy.ts
  apps/web/src/quoter/utils/crosschain-utils/implementations/SwapToBridgeToSwapStrategy.ts
  apps/web/src/quoter/utils/svm-utils/parseSVMTradeIntoSVMOrder.ts
  apps/web/src/utils/addressHelpers.ts
  apps/web/src/utils/currencyId.ts
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/ConfirmSwapModalV3.tsx
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/SwapModalFooterV3.tsx
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/TransactionConfirmSwapContentV3.tsx
  apps/web/src/views/Swap/Bridge/api.ts
  apps/web/src/views/Swap/Bridge/types/index.ts
  apps/web/src/views/Swap/Bridge/utils/index.ts
  apps/web/src/views/Swap/V3Swap/components/SwapModalFooterV2.tsx
  apps/web/src/views/Swap/V3Swap/components/TransactionConfirmSwapContentV2.tsx
  apps/web/src/views/Swap/V3Swap/containers/ConfirmSwapModalV2.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalState.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useSwapCurrency.ts
  apps/web/src/views/Swap/V3Swap/utils/exchange.ts
  apps/web/src/views/Swap/utils.ts
  apps/web/src/views/SwapSimplify/InfinitySwap/AdvancedSwapDetails.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/FormMainInfinity.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/FormMainV4ForHomePage.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/SwapCommitButton.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/index.tsx
  apps/web/src/views/SwapSimplify/hooks/useQuoteTrackingStateMachine.ts
Labels: size/L

#11959 feat: Implement disable add liquidity for specific chains
  apps/web/src/components/Liquidity/LiquiditySunsetWarning.tsx
  apps/web/src/components/NetworkSelector.tsx
  apps/web/src/config/constants/liquidity.ts
  apps/web/src/pages/stable/[address].tsx
  apps/web/src/pages/v2/pair/[[...currency]].tsx
  apps/web/src/views/AddLiquidity/ChoosePair.tsx
  apps/web/src/views/AddLiquidityV3/components/V3SubmitButton.tsx
  apps/web/src/views/CreateLiquidityPool/components/MessagePoolInitialized.tsx
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/Info/Tokens/TokenPage.tsx
  apps/web/src/views/Liquidity/LiquidityView.tsx
  apps/web/src/views/PoolDetail/components/PoolInfo.tsx
  apps/web/src/views/PoolDetail/components/PoolStatus.tsx
  apps/web/src/views/V3Info/views/PoolPage.tsx
  apps/web/src/views/V3Info/views/TokenPage.tsx
  apps/web/src/views/universalFarms/components/PoolsBanner.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#11939 fix: Pool density data not shown on some pools
  apps/web/src/hooks/useAllTicksQuery.ts
Labels: size/S

#12009 feat: support pcs token list search
  packages/jupiter-terminal/overrides/src/components/FormPairSelector.tsx
Labels: size/S

#12015 fix token missing
  apps/web/src/hooks/useSolanaTokenList.ts
  apps/web/src/views/SwapSimplify/index.tsx
Labels: size/S

#12011 chore: interate Solana Wallet api
  apps/web/src/hooks/useAddressBalance.ts
Labels: size/XS
