Repository pancakeswap/pancake-frontend, pull requests merged in 2025-06, with the labels that each got.

#11605 chore: Remove vecake from apr breakdown desc and sync aprs
  apps/web/src/views/universalFarms/components/PoolAprButton/AprBreakdownModal.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/AprButton.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/PoolGlobalAprButton.tsx
  apps/web/src/views/universalFarms/components/PoolsBanner.tsx
  apps/web/src/views/universalFarms/components/PositionItem/PositionDebugView.tsx
  apps/web/src/views/universalFarms/hooks/useAPRBreakdown.ts
  apps/web/src/views/universalFarms/hooks/usePositionAPR.ts
  packages/localization/src/config/translations.json
  packages/widgets-internal/liquidity/infinity/RewardCard.tsx
Labels: size/M

#11751 feat: add market price to slippage check and start price
  apps/web/src/hooks/infinity/usePoolCurrentPrice.ts
  apps/web/src/hooks/usePoolMarketPriceSlippage.ts
  apps/web/src/views/AddLiquidityInfinity/components/SubmitButton.tsx
  apps/web/src/views/AddLiquidityV3/components/V3SubmitButton.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
  apps/web/src/views/CreateLiquidityPool/components/FieldStartingPrice.tsx
  apps/web/src/views/CreateLiquidityPool/components/SubmitCreateButton.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/hooks/useDialog/Dialog.tsx
  packages/uikit/src/hooks/useDialog/DialogContext.tsx
Labels: size/L

#11752 chore: update cors for dev
  apps/web/src/pages/api/farm/list.ts
  apps/web/src/pages/api/pools/candidates.ts
  apps/web/src/pages/api/pools/tvlref.ts
  apps/web/src/quoter/utils/edgePoolQueryClient.ts
  apps/web/src/quoter/utils/poolQueries.ts
  apps/web/src/views/universalFarms/atom/farmsSearchAtom.ts
Labels: size/S

#11753 fix: using full route when high price impact
  apps/web/src/quoter/atom/bestQuoteAtom.ts
  apps/web/src/quoter/hook/useQuoterSync.ts
Labels: size/S

#11757 chore: Disable grove rpcs
  apps/web/src/config/nodes.ts
Labels: size/S

#11749 chore: Remove tp chain switch refresh
  apps/web/src/hooks/useSwitchNetwork.ts
Labels: size/S

#11762 feat: update add liquidity max decimals
  apps/web/src/components/Liquidity/StepCounterV2.tsx
  apps/web/src/hooks/infinity/useCLPriceRange.ts
  apps/web/src/utils/formatRangeSelectorPrice.ts
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/RangeSelector.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/StepCounter.tsx
  packages/widgets-internal/swap/NumericalInput.tsx
  packages/widgets-internal/utils/numbers.ts
Labels: size/M

#11760 feat: Add fee info for lbamm pools
  apps/web/src/views/PositionInfinity/InfinityBinPosition.tsx
  apps/web/src/views/RemoveLiquidityInfinity/components/RemoveBinPosition.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#11764 fix: nav home link
  apps/aptos/components/Menu/Menu.tsx
  apps/aptos/next-env.d.ts
  packages/uikit/src/widgets/Menu/Menu.tsx
  packages/uikit/src/widgets/Menu/types.ts
Labels: size/XS

#11750 feat: [PAN-6207] Send Flow
  apps/web/src/components/Menu/UserMenu/index.tsx
  apps/web/src/components/WalletModalV2/ActionButton.tsx
  apps/web/src/components/WalletModalV2/AssetsList.tsx
  apps/web/src/components/WalletModalV2/SendAssetForm.tsx
  apps/web/src/components/WalletModalV2/SendAssets.tsx
  apps/web/src/components/WalletModalV2/SendTransactionFlow.tsx
  apps/web/src/components/WalletModalV2/WalletModal.tsx
  apps/web/src/components/WalletModalV2/type.ts
  apps/web/src/views/SwapSimplify/hooks/useUserInsufficientBalance.ts
  packages/localization/src/config/translations.json
  packages/widgets-internal/components/NetworkFilter/NetworkFilter.tsx
Labels: size/XXL

#11767 fix: apply wallet asset percent issue
  apps/web/src/components/WalletModalV2/SendAssetForm.tsx
  apps/web/src/components/WalletModalV2/WalletModal.tsx
Labels: size/XS

#11766 fix: Merkl apr batch fetch
  apps/web/.env.development
  apps/web/src/state/farmsV4/search/batchFarmDataFiller.ts
  apps/web/src/state/farmsV4/state/farmPools/fetcher.ts
  apps/web/src/state/farmsV4/state/poolApr/hooks.ts
Labels: size/L

#11768 feat: optimize farm search behavior
  apps/aptos/state/lists/index.ts
  apps/web/src/hooks/useTokenListPrepared.ts
  apps/web/src/state/lists/lists.ts
  apps/web/src/views/universalFarms/PoolsPage.tsx
  apps/web/src/views/universalFarms/atom/farmsSearchAtom.ts
  apps/web/src/views/universalFarms/components/PoolsFilterPanel.tsx
  packages/token-lists/react/lists.ts
Labels: size/L

#11773 fix: minor text update
  apps/web/src/views/BurnDashboard/index.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#11777 fix: xchain refund condition add a partial success case
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/OrderStatus/OrderResultModalContent.tsx
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/components/Timeline/index.tsx
Labels: size/S

#11780 fix: xchain don't show desc amounts if failed state
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/OrderStatus/OrderResultModalContent.tsx
Labels: size/S

#11782 fix: fee tier number
  packages/uikit/src/components/FeeTier/FeeTier.tsx
Labels: size/XS

#11785 feat: add dev doc
  packages/localization/src/config/translations.json
  packages/uikit/src/widgets/Menu/components/footerConfig.ts
Labels: size/XS

#11790 chore: CAKE bridging disclaimer and disable during upgrade
  .changeset/slimy-bags-talk.md
  apps/bridge/components/layerZero/index.tsx
  packages/canonical-bridge/src/hooks/useTransferConfig.ts
  packages/canonical-bridge/src/views/index.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#11793 chore: reset CAKE bridge after maintenance
  .changeset/moody-dolphins-count.md
  apps/bridge/components/layerZero/index.tsx
  packages/canonical-bridge/src/hooks/useTransferConfig.ts
  packages/canonical-bridge/src/views/index.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#11794 fix: CurrencySearch Modal slow response due to getting all balances on-chain
  apps/web/src/components/SearchModal/CurrencySearch.tsx
  apps/web/src/hooks/useTokenComparator.ts
  apps/web/src/state/wallet/hooks.ts
Labels: size/M

#11795 chore: disable zksync CAKE bridging on Main and V1 widgets
  apps/bridge/components/layerZero/index.tsx
  packages/canonical-bridge/src/hooks/useTransferConfig.ts
  packages/canonical-bridge/src/views/index.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#11798 feat: remove infi cl full range limit
  apps/web/src/hooks/infinity/useCLPriceIsFullRange.ts
  apps/web/src/views/AddLiquidityInfinity/components/SubmitButton.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#11775 fix: Merkl api remove items and add protocolid
  apps/web/src/hooks/useMerkl.tsx
  apps/web/src/state/farmsV4/state/poolApr/fetcher.ts
  scripts/updateMerkl/index.ts
Labels: size/M

#11754 chore: seperate light full candidates pool
  apps/web/src/pages/api/pools/candidates.ts
  apps/web/src/quoter/atom/bestSameChainAtom.ts
  apps/web/src/quoter/utils/edgePoolQueries.ts
  apps/web/src/quoter/utils/edgePoolQueryClient.ts
  apps/web/src/quoter/utils/edgeQueries.util.ts
  apps/web/src/quoter/utils/poolQueries.ts
  packages/smart-router/evm/infinity-router/queries/index.ts
Labels: size/L

#11803 feat: config addresses update, order history fix, added order id to list order
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/XS

#11806 feat: upgrade canonical-bridge with analytics, referral code
  .changeset/serious-camels-tell.md
  packages/canonical-bridge/package.json
  packages/canonical-bridge/src/views/index.tsx
  pnpm-lock.yaml
Labels: size/S

#11805 chore: ranking rpcs by session
  apps/web/src/utils/fallbackWithRank.test.ts
  apps/web/src/utils/fallbackWithRank.ts
Labels: size/L

#11810 fix: PAN 6313
  apps/web/src/components/SearchModal/CurrencySearch.tsx
  apps/web/src/components/SearchModal/CurrencySearchModal.tsx
  apps/web/src/components/SearchModal/SwapNetworkSelection.tsx
Labels: size/M

#11808 fix: Docs link in bin liquidity
  apps/web/src/components/Liquidity/Form/FieldLiquidityShape.tsx
  apps/web/src/views/AddLiquidityInfinity/components/BinLiquidityShapeSelector.tsx
  apps/web/src/views/AddLiquidityInfinity/components/BinPriceRangePanel.tsx
  apps/web/src/views/AddLiquidityInfinity/components/SubmitButton.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#11812 feat: add position manager warning
  apps/web/src/views/PositionManagers/components/SunsetWarning.tsx
  apps/web/src/views/PositionManagers/index.tsx
  apps/web/src/views/universalFarms/components/PoolsBanner.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#11792 fix: Swap / Twap routing issues when having multiple chains / from other pages
  apps/web/src/__tests__/views/swap/form.test.tsx
  apps/web/src/hooks/useAccountEventListener.ts
  apps/web/src/hooks/useActiveWeb3React.ts
  apps/web/src/hooks/useAutoSlippageWithFallback.tsx
  apps/web/src/hooks/useSwitchNetwork.ts
  apps/web/src/state/swap/hooks.ts
  apps/web/src/views/Swap/Bridge/hooks/useBridgeAvailableRoutes.ts
  apps/web/src/views/Swap/SwapFeaturesContext.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/AdvancedSwapDetails.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/FlipButton.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/FormMainInfinity.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/FormMainV4ForHomePage.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/SwapCommitButton.tsx
  apps/web/src/views/SwapSimplify/hooks/useHasDynamicHook.ts
Labels: size/L

#11816 feat: add back retry
  apps/web/src/config/nodes.ts
  apps/web/src/utils/fallbackWithRank.ts
Labels: size/S

#11815 chore: re-enable CAKE bridging, remove maintenance banners
  apps/bridge/components/layerZero/index.tsx
  packages/canonical-bridge/src/hooks/useTransferConfig.ts
  packages/canonical-bridge/src/views/index.tsx
Labels: size/M

#11818 fix: revert bridge widget version
  .changeset/ten-socks-fail.md
  packages/canonical-bridge/package.json
  packages/canonical-bridge/src/views/index.tsx
  pnpm-lock.yaml
Labels: size/S

#11820 fix: Stable apr when accessing positions directly
  apps/web/src/state/farmsV4/state/accountPositions/fetcher.ts
  apps/web/src/views/universalFarms/components/PoolAprButton/PoolGlobalAprButton.tsx
  apps/web/src/views/universalFarms/components/PositionActions/V2PositionActions.tsx
Labels: size/S

#11821 chore: remove tvl ref edge calls
  apps/web/src/quoter/utils/edgePoolQueries.ts
Labels: size/M

#11802 chore: using edge for stableprice
  apps/web/src/edge/tokenPrice.ts
  apps/web/src/hooks/useStablecoinPrice.ts
  apps/web/src/pages/api/token/price.ts
  apps/web/src/quoter/hook/useMulticallGasLimit.ts
  apps/web/src/utils/compuateTradePriceBreakdown.ts
  apps/web/src/utils/exchange.ts
Labels: size/XL

#11823 fix: Stablecoin price in useStablecoin hook
  apps/web/src/hooks/useStablecoinPrice.ts
Labels: size/S

#11824 fix: update liquidity pages
  apps/web/src/pages/add/[[...currency]].tsx
  apps/web/src/pages/increase/[[...currency]].tsx
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/pages/remove/[tokenId].tsx
  apps/web/src/pages/v2/add/[[...currency]].tsx
  apps/web/src/pages/v2/remove/[[...currency]].tsx
Labels: size/L

#11819 fix: PAN 6504
  apps/web/src/quoter/utils/crosschain-utils/utils/ContextBuilder.ts
Labels: size/XS

#11817 fix: Sync swap url when fallback
  apps/web/src/state/swap/hooks.ts
  apps/web/src/views/SwapSimplify/InfinitySwap/FormMainInfinity.tsx
Labels: size/M

#11828 fix: PAN 6545
  apps/web/src/hooks/useStablecoinPrice.ts
Labels: size/XS

#11830 fix: swap ssr issue
  apps/web/src/pages/swap/index.tsx
  apps/web/src/pages/swap/limit.tsx
  apps/web/src/pages/swap/twap.tsx
Labels: size/M

#11825 fix: Stablecoin price same for the session
  apps/web/src/hooks/useStablecoinPrice.ts
Labels: size/M

#11747 chore: Remove unused home view
  apps/web/public/images/farmV3MigrationBunny.png
  apps/web/public/images/farmV3MigrationBunnyFull.png
  apps/web/public/images/web3-notification-bunny.png
  apps/web/public/images/web3-notification-check.png
  apps/web/src/components/ColoredWordHeading.tsx
  apps/web/src/components/GradientLogoSvg.tsx
  apps/web/src/components/SlideSvg.tsx
  apps/web/src/pages/api/home/queries/queryTokens.ts
  apps/web/src/pages/api/home/queryCakeRelated.ts
  apps/web/src/views/AffiliatesProgram/components/Overview/AffiliatesBanner.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/Benefits.tsx
  apps/web/src/views/AffiliatesProgram/components/Overview/HowItWork.tsx
  apps/web/src/views/BurnDashboard/components/general/SupplyDeflationCombinedGraph.tsx
  apps/web/src/views/BurnDashboard/components/general/SupplyPieChart.tsx
  apps/web/src/views/Home/components/Banners/images/index.ts
  apps/web/src/views/Home/components/Banners/images/web3-notification-bg-mobile.png
  apps/web/src/views/Home/components/Banners/images/web3-notification-bg.png
  apps/web/src/views/Home/components/Banners/images/web3-notification-bubble-mobile.png
  apps/web/src/views/Home/components/Banners/images/web3-notification-bubble.png
  apps/web/src/views/Home/components/CakeDataRow.tsx
  apps/web/src/views/Home/components/WedgeSvgs.tsx
  apps/web/src/views/Home/hooks/useCakeEmissionPerBlock.tsx
  apps/web/src/views/Migration/bCake.tsx
  apps/web/src/views/Migration/v3.tsx
  apps/web/src/views/Notifications/containers/OnBoardingView.tsx
  apps/web/src/views/PancakeSquad/components/BunniesSection/index.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#11833 fix: add feature flag
  apps/web/src/quoter/utils/crosschain-utils/utils/ContextBuilder.ts
Labels: size/XS

#11834 fix: stable coin price query's token mock
  apps/web/src/edge/tokenPrice.ts
Labels: size/S

#11835 fix: mobile stable swap farm apr display
  apps/web/src/views/universalFarms/components/PoolListView.tsx
Labels: size/XS

#11796 fix: Mev Toggle flash when switching network
  apps/web/src/views/Mev/hooks/index.ts
Labels: size/S

#11839 fix: enable crosschain ss
  apps/web/src/quoter/utils/crosschain-utils/utils/ContextBuilder.ts
Labels: size/XS

#11809 fix: PAN 6439
  apps/web/src/hooks/__tests__/useStateMachine.test.ts
  apps/web/src/hooks/useStateMachine.ts
  apps/web/src/quoter/atom/bestCrossChainAtom.ts
  apps/web/src/utils/customGTMEventTracking.ts
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/OrderStatus/OrderResultModalContent.tsx
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/hooks/useOrderStatusTrackingStateMachine.ts
  apps/web/src/views/SwapSimplify/InfinitySwap/SwapCommitButton.tsx
  apps/web/src/views/SwapSimplify/hooks/useQuoteTrackingStateMachine.ts
Labels: size/XXL

#11837 fix: Feat/smart account warning for predicion
  apps/web/src/pages/prediction/index.tsx
  apps/web/src/pages/prediction/leaderboard.tsx
  apps/web/src/views/Predictions/components/SmartWalletWarning.tsx
  apps/web/src/views/Predictions/context/PredictionConfigProviders.tsx
  apps/web/src/views/Predictions/index.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#11843 feat: add gift support for usdf
  apps/web/src/views/PoolDetail/components/MyPositions.tsx
  apps/web/src/views/universalFarms/components/FarmStatusDisplay/config.ts
  apps/web/src/views/universalFarms/components/FarmStatusDisplay/hooks.ts
  apps/web/src/views/universalFarms/components/FarmStatusDisplay/index.tsx
  apps/web/src/views/universalFarms/components/FarmStatusDisplay/types.ts
  apps/web/src/views/universalFarms/components/RewardInfoCard/index.tsx
  apps/web/src/views/universalFarms/components/useColumnConfig.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#11849 chore: add scope for farmsearch
  apps/web/src/state/farmsV4/search/edgeFarmQueries.ts
Labels: size/XS

#11850 fix: fee tier display issue of infinity
  apps/web/src/state/farmsV4/search/batchFarmDataFiller.ts
  apps/web/src/state/farmsV4/search/farm.util.ts
Labels: size/S

#11852 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XXL

#11851 perf: Enable stablecoin price fetch when amount greater than 0
  apps/web/src/hooks/infinity/useFeesEarned.tsx
  apps/web/src/hooks/useStablecoinPrice.ts
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/PositionPreview.tsx
  apps/web/src/views/Liquidity/LiquidityView.tsx
  apps/web/src/views/PositionInfinity/InfinityBinPosition.tsx
  apps/web/src/views/PositionInfinity/InfinityCLPosition.tsx
  apps/web/src/views/RemoveLiquidity/RemoveLiquidityV3.tsx
  apps/web/src/views/RemoveLiquidityInfinity/components/RemoveBinPosition.tsx
  apps/web/src/views/RemoveLiquidityInfinity/components/RemoveClPosition.tsx
Labels: size/M

#11853 chore: perf build speed
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/tsconfig.json
Labels: size/S

#11838 fix: perf token page speed
  apps/web/src/components/TextWithSkeleton.tsx
  apps/web/src/edge/tokenInfo.ts
  apps/web/src/edge/tokenInfoPageDataAtom.ts
  apps/web/src/edge/tokenPrice.ts
  apps/web/src/pages/api/token/[type]/[chain]/[token].ts
  apps/web/src/quoter/utils/edgePoolQueries.ts
  apps/web/src/quoter/utils/edgeQueries.util.ts
  apps/web/src/utils/mockCurrency.ts
  apps/web/src/views/Info/Tokens/TokenPage.tsx
  apps/web/src/views/V3Info/views/TokenPage.tsx
Labels: size/XXL

#11857 chore: update bet event
  apps/web/src/utils/customGTMEventTracking.ts
  apps/web/src/views/Predictions/components/RoundCard/OpenRoundCard.tsx
Labels: size/M

#11859 chore: enable deBridge referral code
  .changeset/good-dodos-jump.md
  packages/canonical-bridge/package.json
  packages/canonical-bridge/src/views/index.tsx
Labels: size/XS

#11847 chore(crosschain): support mainnet
  apps/web/src/components/SearchModal/SwapNetworkSelection.tsx
  apps/web/src/config/nodes.ts
  apps/web/src/quoter/utils/crosschain-utils/base/CrossChainQuoteStrategy.ts
  apps/web/src/quoter/utils/crosschain-utils/config.ts
  apps/web/src/quoter/utils/crosschain-utils/implementations/BridgeToSwapStrategy.ts
  apps/web/src/quoter/utils/crosschain-utils/types.ts
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/ConfirmSwapModalV3.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalState.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/SwapCommitButton.tsx
  apps/web/src/views/SwapSimplify/hooks/useQuoteTrackingStateMachine.ts
  packages/localization/src/config/translations.json
Labels: size/L

#11708 chore: Update bnbchain rpcs
  apis/farms/.dev.vars
  apis/routing/.dev.vars
  apps/bridge/components/WormHole/constants.ts
  apps/gamification/config/chains.ts
  apps/gamification/config/nodes.ts
  apps/web/src/config/chains.ts
  apps/web/src/config/nodes.ts
  packages/gauges/src/tests/config.test.ts
  packages/smart-router/README.md
  packages/universal-router-sdk/test/fixtures/clients.ts
Labels: size/M

#11846 fix: Stablecoin price flickers when refetch
  apps/web/src/hooks/useStablecoinPrice.ts
Labels: size/M

#11865 fix: Total Lp Amount not visible when lp is inactive
  apps/web/src/components/CurrencyInputPanel/CurrencyInputPanelV2.tsx
  apps/web/src/components/CurrencyInputPanel/index.tsx
  apps/web/src/components/PositionCard/index.tsx
  apps/web/src/views/CreateLiquidityPool/components/SubmitCreateButton.tsx
  apps/web/src/views/Liquidity/LiquidityView.tsx
  apps/web/src/views/PositionInfinity/InfinityBinPosition.tsx
  apps/web/src/views/PositionInfinity/InfinityCLPosition.tsx
Labels: size/M

#11875 fix: replace mint logoURI
  apps/solana/src/hooks/pool/formatter.ts
Labels: size/XS

#11877 feat: offcial token list as whitelist
  packages/solana-core-sdk/src/raydium/token/token.ts
Labels: size/XS
