Repository pancakeswap/pancake-frontend, pull requests merged in 2025-10, with the labels that each got.

#12412 fix: remove build warning
  .gitignore
  apps/web/src/views/BridgeView.tsx
  turbo.json
Labels: size/M

#12419 fix: rsc replace
  apps/web/next.config.mjs
  apps/web/src/utils/getPerpetualUrl.ts
Labels: size/S

#12416 fix: ToSpliced crashes in old browsers
  apps/web/src/pages/_app.tsx
Labels: size/XS, Sentry

#12425 fix: token-list-cn-pattern
  .changeset/stale-ducks-live.md
  packages/token-lists/schema/pancakeswap.json
Labels: size/S

#12240 feat: ifo dryrun 02
  apps/web/src/pages/ifo/deposit/[ifoId]/[poolIndex].tsx
  apps/web/src/pages/ifo/v2/index.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/Timer.tsx
  apps/web/src/views/IfosV2/components/Hero.tsx
  apps/web/src/views/IfosV2/components/IfoCards/ClaimDisplay.tsx
  apps/web/src/views/IfosV2/components/IfoCards/ClaimedCard.tsx
  apps/web/src/views/IfosV2/components/IfoCards/IfoCardFinished.tsx
  apps/web/src/views/IfosV2/components/IfoCards/IfoCardIdle.tsx
  apps/web/src/views/IfosV2/components/IfoCards/IfoCardLive.tsx
  apps/web/src/views/IfosV2/components/IfoCards/IfoCards.tsx
  apps/web/src/views/IfosV2/components/IfoCards/IfoDepositForm.tsx
  apps/web/src/views/IfosV2/components/IfoCards/IfoPoolFinished.tsx
  apps/web/src/views/IfosV2/components/IfoCards/IfoPoolInfoDisplay.tsx
  apps/web/src/views/IfosV2/components/IfoCards/IfoPoolLive.tsx
  apps/web/src/views/IfosV2/components/IfoCards/StakedDisplay.tsx
  apps/web/src/views/IfosV2/components/IfoCards/Timer.tsx
  apps/web/src/views/IfosV2/components/IfoDeposit.tsx
  apps/web/src/views/IfosV2/components/IfoHistoryCard.tsx
  apps/web/src/views/IfosV2/config/index.tsx
  apps/web/src/views/IfosV2/helpers/getAllocationCurrencyAmount.ts
  apps/web/src/views/IfosV2/helpers/getBannerUrl.ts
  apps/web/src/views/IfosV2/helpers/index.ts
  apps/web/src/views/IfosV2/index.tsx
Labels: size/L
