Repository pancakeswap/pancake-frontend, pull requests merged in 2025-04, with the labels that each got.

#11418 fix: update solana logo link to swap page
  apps/solana/components/Menu.tsx
Labels: size/S

#11419 feat: solana banner ad
  apps/web/src/components/AdPanel/Ads/AdSolana.tsx
  apps/web/src/components/AdPanel/config.tsx
Labels: size/M

#11421 fix: solana link update
  apps/solana/components/Menu.tsx
  apps/solana/config/adBanner/ads/AdPCSxSolana.tsx
Labels: size/XS

#11426 feat: ido
  apps/web/public/images/ido/stakestone.svg
  apps/web/src/views/Idos/config/index.tsx
  apps/web/src/views/Idos/hooks/ido/useIDODuration.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#11425 chore: Remove options link
  apps/web/src/__tests__/translations.test.ts
  apps/web/src/components/AdPanel/Ads/AdOptionsTrading.tsx
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/components/Menu/index.tsx
  apps/web/src/config/constants/options-sunset-addresses.json
  apps/web/src/hooks/useOptionsSunsetNotification.tsx
  apps/web/src/hooks/useUserIsUsCitizenAcknowledgement.ts
  apps/web/src/pages/_app.tsx
  apps/web/src/utils/getOptionsUrl.ts
  packages/localization/src/config/translations.json
Labels: size/L

#11427 chore: updated twap addresses
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/XS

#11432 chore: disable console.error NextJS popup on local env
  apps/web/src/utils/infoQueryHelpers.ts
Labels: size/XS

#11429 feat: Update graph health api and implement api check
  apps/web/src/components/SubgraphHealthIndicator/FixedSubgraphHealthIndicator.tsx
  apps/web/src/components/SubgraphHealthIndicator/FloatingSubgraphHealthIndicators.tsx
  apps/web/src/components/SubgraphHealthIndicator/SubgraphHealthIndicator.tsx
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/hooks/useSubgraphHealth.ts
Labels: size/M

#11431 fix: Dont show warning when slippage auto
  apps/web/src/views/Swap/V3Swap/components/SlippageButton.tsx
  apps/web/src/views/SwapSimplify/V4Swap/index.tsx
Labels: size/M

#11435 revert: "fix: Dont show warning when slippage auto"
  apps/web/src/views/Swap/V3Swap/components/SlippageButton.tsx
  apps/web/src/views/SwapSimplify/V4Swap/index.tsx
Labels: size/M

#11420 chore: Remove beta from prediction disclaimer
  apps/web/src/__tests__/translations.test.ts
  apps/web/src/components/DisclaimerModal/index.tsx
  apps/web/src/views/Predictions/components/RiskDisclaimer.tsx
Labels: size/M

#11433 perf: Cache slippage tolerance calculation per trade
  apps/web/src/hooks/useAutoSlippage.tsx
  apps/web/src/hooks/useStablecoinPrice.ts
Labels: size/L

#11358 fix: Crash info token pages
  apps/web/src/views/Info/Tokens/TokenPage.tsx
  apps/web/src/views/Info/components/InfoTables/PoolsTable.tsx
  apps/web/src/views/V3Info/views/TokenPage.tsx
Labels: size/M, Sentry

#11424 fix: Use w3w provider for waiting trx
  apps/web/src/Providers.tsx
  apps/web/src/config/nodes.ts
  apps/web/src/contexts/W3WConfigContext.tsx
  apps/web/src/hooks/usePublicNodeWaitForTransaction.ts
  apps/web/src/state/farms/fetchMasterChefData.ts
  apps/web/src/state/lists/hooks.ts
  apps/web/src/state/lottery/fetchUnclaimedUserRewards.ts
  apps/web/src/state/lottery/getUserLotteryData.ts
  apps/web/src/state/lottery/helpers.ts
  apps/web/src/utils/isNotUndefinedOrNull.ts
  apps/web/src/utils/notEmpty.ts
  apps/web/src/views/Idos/config/index.tsx
  apps/web/src/views/Swap/x/useWaitForXOrderReceipt.ts
  apps/web/src/views/TradingReward/components/Leaderboard/index.tsx
Labels: size/L

#11451 feat: Merge PAN-4928 into PAN-4933
  apps/web/src/state/swap/reducer.ts
  apps/web/src/views/Swap/V3Swap/hooks/useAllTypeBestTrade.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSwapBestTrade.ts
  packages/price-api-sdk/src/orderPriceApiParsers.ts
  packages/price-api-sdk/src/types/api.ts
  packages/price-api-sdk/src/types/order.ts
  packages/price-api-sdk/src/types/orderType.ts
Labels: size/M

#11453 fix: reward calc amount incorrect
  apps/web/src/hooks/infinity/useInfinityCakeAPR.ts
Labels: size/XS

#11442 chore: update max auto slippage to 5%
  apps/web/src/hooks/useAutoSlippage.tsx
Labels: size/S

#11455 fix: pool has no active campaign but showing cake apr
  apps/web/src/hooks/infinity/useInfinityCakeAPR.ts
  apps/web/src/hooks/infinity/useIsFarming.ts
Labels: size/M

#11456 fix: disabled harvest when there no unclaimed previous epoch reward
  apps/web/src/views/universalFarms/components/PositionActions/InfinityPositionActions.tsx
  apps/web/src/views/universalFarms/hooks/useFarmInfinityActions.tsx
Labels: size/XS

#11458 chore: remove debug info for QA
  apps/web/src/views/PositionInfinity/InfinityCLPosition.tsx
Labels: size/XS

#11464 feat(PAN-5198): add existing position for calc derived bin lp apr
  apps/web/src/views/universalFarms/hooks/usePositionAPR.ts
  apps/web/src/views/universalFarms/utils/getActiveLiquidityFromShape.ts
Labels: size/M

#11457 perf: auto slippage improvements
  apps/web/src/components/CurrencyInputPanelSimplify/index.tsx
  apps/web/src/hooks/useAutoSlippage.tsx
  apps/web/src/hooks/useAutoSlippageWithFallback.tsx
  apps/web/src/state/swap/hooks.ts
  apps/web/src/views/CakeStaking/components/LockCakeForm.tsx
  apps/web/src/views/Swap/V3Swap/components/SlippageButton.tsx
  apps/web/src/views/Swap/V3Swap/components/SwapModalFooterV2.tsx
  apps/web/src/views/Swap/V3Swap/containers/ConfirmSwapModal.tsx
  apps/web/src/views/Swap/V3Swap/containers/ConfirmSwapModalV2.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useSendSwapTransaction.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSlippageAdjustedAmounts.ts
  apps/web/src/views/Swap/V3Swap/hooks/useSwapCallback.ts
  apps/web/src/views/Swap/V3Swap/hooks/useWallchain.ts
  apps/web/src/views/SwapSimplify/V4Swap/AdvancedSwapDetails.tsx
  apps/web/src/views/SwapSimplify/V4Swap/FormMainV4.tsx
  apps/web/src/views/SwapSimplify/V4Swap/FormMainV4ForHomePage.tsx
  apps/web/src/views/SwapSimplify/V4Swap/PricingAndSlippage.tsx
  apps/web/src/views/SwapSimplify/V4Swap/TradeDetails.tsx
  apps/web/src/views/SwapSimplify/V4Swap/index.tsx
  apps/web/src/views/SwapSimplify/index.tsx
Labels: size/L

#11467 fix(PAN-5210): uniq farm pools
  apps/web/src/state/farmsV4/state/farmPools/fetcher.ts
Labels: size/S

#11468 fix: cake apr use estimate value when compaign start
  apps/web/src/hooks/infinity/useFarmReward.ts
Labels: size/XS

#11470 fix(PAN-5213): force chianId with pool
  apps/web/src/views/PoolDetail/components/MyPositions.tsx
Labels: size/XS

#11472 fix(PAN-5002): update the liquidity after tx
  apps/web/src/hooks/infinity/getPool.ts
  apps/web/src/hooks/infinity/usePool.ts
  packages/infinity-sdk/src/entities/pool.ts
Labels: size/S

#11475 fix(PAN-5002): derived bin pool liquidity & lp fee
  apps/web/src/hooks/infinity/useInfinityCakeAPR.ts
  apps/web/src/state/farmsV4/state/extendPools/hooks.ts
  apps/web/src/views/universalFarms/hooks/usePositionAPR.ts
Labels: size/M

#11476 fix: PAN-5217
  apps/web/src/views/universalFarms/hooks/useBinAmountsFromUsdValue.ts
  apps/web/src/views/universalFarms/hooks/usePositionAPR.ts
Labels: size/S

#11463 fix: previous twap contract orders display
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/XS

#11466 feat: feature/ido snapshot
  apps/web/public/images/ido/mindnetwork.svg
  apps/web/src/views/Idos/components/IdoCards/IdoStakeActionCard.tsx
  apps/web/src/views/Idos/components/IdoCards/PreSaleInfoCard.tsx
  apps/web/src/views/Idos/config/index.tsx
  apps/web/src/views/Idos/helpers/getSnapshotLink.ts
  apps/web/src/views/Idos/hooks/w3w/useW3WAccountVerify.ts
  packages/localization/src/config/translations.json
Labels: size/L

#11479 fix: line wrap
  apps/web/src/views/Idos/config/index.tsx
Labels: size/XS

#11480 chore: update text
  apps/web/src/views/Idos/components/IdoCards/IdoDepositButton.tsx
  apps/web/src/views/Idos/components/IdoCards/PreSaleInfoCard.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#11484 fix(PAN-5239): xs create lp ui
  apps/web/src/views/CreateLiquidityPool/components/FieldSelectCurrencies.tsx
  apps/web/src/views/HookSettings/HookSettings.tsx
Labels: size/XS

#11474 perf: Remove redundant swap components on homepage
  apps/web/src/views/HomeV2/FavoriteDEXBanner.tsx
  apps/web/src/views/HomeV2/cards/component/MultipleLogos.tsx
  apps/web/src/views/HomeV2/index.tsx
  apps/web/src/views/SwapSimplify/SimpleSwapForHomePage.tsx
  apps/web/src/views/SwapSimplify/V4Swap/FormMainV4ForHomePage.tsx
  apps/web/src/views/SwapSimplify/V4Swap/SwapCommitButtonForHomepage.tsx
  apps/web/src/views/SwapSimplify/V4Swap/V4SwapFormForHomepage.tsx
Labels: size/XL

#11443 chore: Remove eos ad and make tc components dynamic
  apps/web/src/components/AdPanel/AdSlidesRender.tsx
  apps/web/src/components/AdPanel/Ads/AdTradingCompetition.tsx
  apps/web/src/components/AdPanel/config.tsx
Labels: size/M

#11482 fix: pan-5237-prodbinance-web3-cannot-swap
  apps/web/src/Providers.tsx
  apps/web/src/pages/_app.tsx
  apps/web/src/pages/ido/[ido].tsx
  apps/web/src/pages/ido/index.tsx
  apps/web/src/utils/viem.ts
Labels: size/M

#11491 chore: [PAN-5078] ads module quick fix
  apps/web/src/components/AdPanel/DesktopCard.tsx
Labels: size/S

#11485 chore: Feat/pan 5042 patch 2
  apps/web/.env.development
  apps/web/src/config/constants/endpoints.ts
  apps/web/src/state/multicall/hooks.ts
  apps/web/src/state/swap/hooks.ts
  apps/web/src/state/wallet/hooks.ts
  apps/web/src/views/Swap/Bridge/api.ts
  apps/web/src/views/Swap/Bridge/hooks/index.ts
  apps/web/src/views/Swap/Bridge/hooks/useBridgeCheckApproval.ts
  apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalState.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useSwapCurrency.ts
  apps/web/src/views/SwapSimplify/V4Swap/ConfirmSwapModal/ConfirmSwapModalV3.tsx
  apps/web/src/views/SwapSimplify/V4Swap/ConfirmSwapModal/SwapModalFooterV3.tsx
  packages/widgets-internal/swap/ApproveModalContent.tsx
Labels: size/L

#11489 chore: Remove merl competition ad
  apps/web/src/components/AdPanel/Ads/AdTradingCompetition.tsx
Labels: size/M

#11488 feat: patch for cms-v4
  apps/web/src/state/farmsV4/state/extendPools/fetcher.ts
  apps/web/src/state/farmsV4/state/farmPools/hooks.ts
  apps/web/src/views/universalFarms/components/PositionItem/V3PositionItem.tsx
  packages/farms/src/utils.ts
Labels: size/S

#11496 feat(PAN-5299): add snapshot link to eligible card
  apps/web/src/views/Idos/components/IdoCards/IdoStakeActionCard.tsx
  apps/web/src/views/Idos/components/IdoCards/PreSaleInfoCard.tsx
Labels: size/S

#11495 feat: [PAN-5074] update network selector
  apps/web/src/components/NetworkSwitcher.tsx
  apps/web/src/components/NetworkSwitcherModal.tsx
  packages/uikit/src/widgets/Menu/components/UserMenu/index.tsx
Labels: size/L

#11490 fix: Currency input percentage button in swap
  apps/web/src/components/CurrencyInputPanelSimplify/index.tsx
Labels: size/S

#11499 fix: picks using config's link to support v2 pools
  apps/web/src/components/AdPanel/Ads/AdPicks.tsx
  apps/web/src/components/AdPanel/types.ts
Labels: size/S

#11497 feat: tracking solana volume
  apps/solana/package.json
  apps/solana/pages/swap/index.tsx
  apps/solana/utils/curstomGTMEventTracking.ts
  apps/solana/utils/datadog.ts
  pnpm-lock.yaml
Labels: size/L

#11501 feat(PAN-5304): add farm icon
  apps/web/src/views/universalFarms/components/PoolAprButton/AprButton.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/PoolAprButton.tsx
Labels: size/S

#11500 chore: [PAN4549] update the chain selection component UX
  packages/widgets-internal/components/NetworkFilter/NetworkFilter.tsx
Labels: size/M

#11487 fix: Logos width home
  apps/web/src/views/HomeV2/FavoriteDEXBanner.tsx
  apps/web/src/views/HomeV2/cards/component/MultipleLogos.tsx
Labels: size/XS

#11505 chore: Update check approval endpoint
  apps/web/.env.development
  apps/web/src/views/Swap/Bridge/api.ts
  apps/web/src/views/Swap/Bridge/hooks/useBridgeCheckApproval.ts
Labels: size/XS

#11506 chore(universal-router-sdk): PAN-5319 add payerIsUser option
  .changeset/shy-moons-pretend.md
  packages/universal-router-sdk/src/entities/Command.ts
  packages/universal-router-sdk/src/entities/protocols/pancakeswap.ts
Labels: size/S

#11509 chore: NetworkFilter improvements for mobile
  packages/localization/src/config/translations.json
  packages/widgets-internal/components/NetworkFilter/NetworkFilter.tsx
Labels: size/M

#11512 chore: Add userIsPayer option to swap calldata encoding
  .changeset/nice-students-promise.md
  packages/universal-router-sdk/src/entities/Command.ts
  packages/universal-router-sdk/src/entities/protocols/pancakeswap.ts
  packages/universal-router-sdk/src/entities/types.ts
  packages/universal-router-sdk/src/swapRouter.ts
Labels: size/M

#11515 feat: add Route Card
  apps/web/src/components/NetworkSwitcher.tsx
  apps/web/src/state/swap/actions.ts
  apps/web/src/state/swap/reducer.test.tsx
  apps/web/src/views/Swap/V3Swap/components/RouteDisplayModal.tsx
  apps/web/src/views/Swap/V3Swap/components/TransactionConfirmSwapContent.tsx
  apps/web/src/views/Swap/V3Swap/components/TransactionConfirmSwapContentV2.tsx
  apps/web/src/views/Swap/V3Swap/containers/SwapCommitButton.tsx
  apps/web/src/views/Swap/V3Swap/containers/TradeDetails.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useSwapBestTrade.ts
  apps/web/src/views/Swap/components/SwapRoute.tsx
  apps/web/src/views/Swap/utils.ts
  apps/web/src/views/SwapSimplify/V4Swap/CrossChainConfirmSwapModal/OrderStatus/OrderDetailsPanel.tsx
  apps/web/src/views/SwapSimplify/V4Swap/CrossChainConfirmSwapModal/TransactionConfirmSwapContentV3.tsx
  apps/web/src/views/SwapSimplify/V4Swap/RoutesBreakdown.tsx
  apps/web/src/views/SwapSimplify/V4Swap/SwapCommitButton.tsx
  apps/web/src/views/SwapSimplify/V4Swap/TradeDetails.tsx
  apps/web/src/views/SwapSimplify/V4Swap/TradingFee.tsx
  apps/web/src/views/SwapSimplify/hooks/useIsPriceImpactTooHigh.ts
  packages/price-api-sdk/src/orderPriceApiParsers.ts
  packages/price-api-sdk/src/types/order.ts
  packages/smart-router/evm/v3-router/types/route.ts
Labels: size/L

#11516 feat: whitelist a few tokens
  .changeset/healthy-penguins-teach.md
  packages/smart-router/evm/constants/exchange.ts
  packages/tokens/src/constants/bsc.ts
Labels: size/S

#11519 feat: lorenzoprotocol ido
  apps/web/public/images/ido/lorenzo-banner.svg
  apps/web/public/images/ido/lorenzo.svg
  apps/web/src/pages/api/w3w/sign.ts
  apps/web/src/pages/api/w3w/verify.ts
  apps/web/src/views/Idos/components/IdoCards/PreSaleInfoCard.tsx
  apps/web/src/views/Idos/config/index.tsx
  apps/web/src/views/Idos/hooks/w3w/useW3WAccountVerify.ts
  packages/localization/src/config/translations.json
Labels: size/L

#11521 chore: update uikit version
  .changeset/late-chefs-compare.md
Labels: size/XS

#11524 fix(farm): update RoiCalculator support multi chains
  apps/web/.env
  apps/web/.env.development
  apps/web/src/hooks/v3/useAllV3TicksQuery.ts
  apps/web/src/hooks/v3/usePoolTickData.ts
  apps/web/src/hooks/v3/usePools.ts
  apps/web/src/hooks/v3/useV3DerivedInfo.ts
  apps/web/src/state/multicall/hooks.ts
  apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
  apps/web/src/views/Farms/components/FarmCard/ApyButton.tsx
  apps/web/src/views/Farms/components/FarmCard/V3/FarmV3ApyButton.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/V3PoolAprModal.tsx
  packages/widgets-internal/roi/RoiCalculator.tsx
  packages/widgets-internal/roi/hooks/usePriceRange.ts
Labels: size/L

#11520 chore: [PAN-5179] Add 3rd party points/incentives display to Pools page
  apps/web/src/views/PoolDetail/components/MyPositions.tsx
  apps/web/src/views/PoolDetail/components/PoolInfo.tsx
  apps/web/src/views/universalFarms/components/FarmStatusDisplay/config.ts
  apps/web/src/views/universalFarms/components/FarmStatusDisplay/hooks.ts
  apps/web/src/views/universalFarms/components/FarmStatusDisplay/index.tsx
  apps/web/src/views/universalFarms/components/FarmStatusDisplay/types.ts
  apps/web/src/views/universalFarms/components/PoolListView.tsx
  apps/web/src/views/universalFarms/components/RewardInfoCard/index.tsx
  apps/web/src/views/universalFarms/components/useColumnConfig.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/components/Svg/Icons/Reward.tsx
  packages/uikit/src/components/Svg/index.tsx
Labels: size/L

#11527 fix: [PAN-5390] fe susde showing as staked
  packages/tokens/src/constants/bsc.ts
Labels: size/XS

#11529 feat(swap): preserve input currency and remove URL updates
  apps/web/src/state/swap/hooks.ts
  apps/web/src/views/SwapSimplify/V4Swap/FormMainV4.tsx
Labels: size/S

#11528 chore: add Unit Test for usePools
  apps/web/src/hooks/v3/__tests__/usePools.test.ts
  apps/web/src/hooks/v3/usePools.ts
  apps/web/src/state/multicall/hooks.ts
  packages/wagmi/src/hooks/useBlock.ts
Labels: size/L

#11492 chore: Update opbnb bsc testnet block times
  .changeset/flat-seals-sniff.md
  packages/chains/src/averageChainBlockTimes.ts
Labels: size/XS, Lorentz

#11531 feat: ido-hyper
  apps/web/package.json
  apps/web/public/images/ido/hyper.svg
  apps/web/src/views/Idos/components/IdoCards/IdoStakeActionCard.tsx
  apps/web/src/views/Idos/components/IdoCards/PreSaleInfoCard.tsx
  apps/web/src/views/Idos/config/index.tsx
  packages/localization/src/config/translations.json
  pnpm-lock.yaml
Labels: size/L

#11534 feat(PAN-5433): add primus hook
  packages/infinity-sdk/src/constants/hooksList/bsc.ts
Labels: size/S

#11493 chore: Update opbnb block time
  .changeset/selfish-rice-raise.md
  apps/web/src/hooks/usePublicNodeWaitForTransaction.ts
  packages/chains/src/averageChainBlockTimes.ts
Labels: size/S, Lorentz

#11523 feat: veCake redemption page
  .eslintrc
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/config/abi/cakePool.ts
  apps/web/src/hooks/createWriteContractCallback.tsx
  apps/web/src/hooks/usePublicNodeWaitForTransaction.ts
  apps/web/src/hooks/useTokenBalance.ts
  apps/web/src/pages/cake-staking/redeem.tsx
  apps/web/src/utils/addressHelpers.ts
  apps/web/src/utils/contractHelpers.ts
  apps/web/src/views/CakeStaking/VeCakeRedeem.tsx
  apps/web/src/views/CakeStaking/components/CakeRewardsCard.tsx
  apps/web/src/views/CakeStaking/components/LockedVeCakeStatus.tsx
  apps/web/src/views/CakeStaking/components/RedeemFaqs.tsx
  apps/web/src/views/CakeStaking/components/RedeemHeader.tsx
  apps/web/src/views/CakeStaking/components/VeCakeExitField.tsx
  apps/web/src/views/CakeStaking/hooks/useCakeExitInfo.ts
  apps/web/src/views/CakeStaking/hooks/useRevenueSharingProxy.ts
  apps/web/src/views/CakeStaking/utils/useDisplayValue.ts
  packages/localization/src/config/translations.json
Labels: size/XXL

#11538 chore: Temp remove debridge from aggregator
  packages/canonical-bridge/src/hooks/useTransferConfig.ts
Labels: size/M

#11540 feat: order networks by volume
  apps/web/src/components/NetworkSwitcherModal.tsx
Labels: size/L

#11459 feat: Add integrity api and update tradingview integrity hash
  apps/web/.env
  apps/web/src/components/TradingView.tsx
  apps/web/src/pages/api/integrity/index.ts
  apps/web/src/utils/atomWithAsyncRetry.ts
  apps/web/src/views/Predictions/components/TradingView.tsx
  apps/web/src/views/Swap/components/Chart/TradingViewChart.tsx
Labels: size/M

#11541 chore: disable lint in web:build
  apps/web/package.json
Labels: size/XS

#11545 chore: Use grove for zkevm
  apps/web/src/config/nodes.ts
Labels: size/XS

#11546 chore: Remove nodies on zkevm
  apps/web/src/config/nodes.ts
Labels: size/XS

#11551 feat: filter out non-whitelist hooks pools
  apps/web/src/views/AddLiquidityInfinity/components/PoolList.tsx
Labels: size/XS

#11550 fix: background loading when no user input && cache key fix
  apps/web/src/quoter/atom/bestQuoteAtom.ts
  apps/web/src/quoter/atom/poolsAtom.ts
  apps/web/src/quoter/hook/useQuoterSync.ts
  apps/web/src/quoter/utils/PoolHashHelper.ts
  apps/web/src/quoter/utils/poolQueries.ts
Labels: size/S

#11553 fix: pool diff
  apps/web/src/state/farmsV4/state/farmPools/fetcher.ts
  apps/web/src/state/farmsV4/state/farmPools/hooks.ts
Labels: size/S

#11556 fix: back to link
  apps/web/src/views/AddLiquidityV3/index.tsx
Labels: size/XS

#11486 feat: Burn Dashboard
  apps/web/package.json
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/components/Progress/ProgressBar.tsx
  apps/web/src/config/constants/meta.ts
  apps/web/src/pages/api/burn-statistics/index.ts
  apps/web/src/pages/api/burn-statistics/update.ts
  apps/web/src/pages/burn-dashboard/index.tsx
  apps/web/src/utils/stats/burnHistoryTable.ts
  apps/web/src/utils/stats/burnTimeSeries.ts
  apps/web/src/utils/stats/deflationTimeSeries.ts
  apps/web/src/utils/stats/endpoints.ts
  apps/web/src/utils/stats/mintTimeSeries.ts
  apps/web/src/utils/stats/request.ts
  apps/web/src/utils/stats/totalSupplyMintBurn.ts
  apps/web/src/utils/stats/totalSupplyTimeSeries.ts
  apps/web/src/utils/stats/types.ts
  apps/web/src/views/BurnDashboard/components/StatsCard.tsx
  apps/web/src/views/BurnDashboard/components/TabMenu.tsx
  apps/web/src/views/BurnDashboard/components/burns/BurnLastSevenDaysCard.tsx
  apps/web/src/views/BurnDashboard/components/burns/RealTimeBurnHistoryTable.tsx
  apps/web/src/views/BurnDashboard/components/burns/TotalDeflationCard.tsx
  apps/web/src/views/BurnDashboard/components/burns/WeeklyBurnStackedChart.tsx
  apps/web/src/views/BurnDashboard/components/burns/YTDBurnCard.tsx
  apps/web/src/views/BurnDashboard/components/burns/YTDDeflationCard.tsx
  apps/web/src/views/BurnDashboard/components/emissions/EmissionsLastSevenDaysCard.tsx
  apps/web/src/views/BurnDashboard/components/emissions/WeeklyEmissionsStackedBarChart.tsx
  apps/web/src/views/BurnDashboard/components/emissions/YTDEmissionsCard.tsx
  apps/web/src/views/BurnDashboard/components/general/SupplyDeflationCombinedGraph.tsx
  apps/web/src/views/BurnDashboard/components/general/SupplyPieChart.tsx
  apps/web/src/views/BurnDashboard/components/styles.tsx
  apps/web/src/views/BurnDashboard/constants.ts
  apps/web/src/views/BurnDashboard/hooks/useBurnStats.ts
  apps/web/src/views/BurnDashboard/index.tsx
  apps/web/src/views/BurnDashboard/types.ts
  apps/web/src/views/BurnDashboard/utils.ts
  apps/web/vercel.json
  packages/localization/src/config/translations.json
  pnpm-lock.yaml
Labels: size/XXL

#11494 chore: Update bnb block time
  .changeset/shiny-crabs-glow.md
  apis/farms/src/handler.ts
  apps/gamification/config/index.ts
  apps/web/src/__tests__/utils/apr.test.ts
  apps/web/src/config/index.ts
  apps/web/src/views/Idos/components/IdoCards/Timer.tsx
  packages/chains/src/averageChainBlockTimes.ts
  packages/pools/src/constants/index.ts
Labels: Delayed Release, size/M, Lorentz

#11555 feat(PAN-5271): toast
  apps/solana/.eslintrc
  apps/solana/.husky/pre-commit
  apps/solana/.vscode/settings.json
  apps/solana/package.json
  apps/solana/src/hooks/toast/useGlobalToast.tsx
  packages/uikit/src/components/Alert/Alert.tsx
  packages/uikit/src/components/Alert/types.ts
  pnpm-lock.yaml
Labels: size/M

#11561 chore: update burn dashboard api
  apps/web/_next-typesafe-url_.d.ts
  apps/web/src/pages/api/burn-statistics/index.ts
  apps/web/src/pages/api/burn-statistics/update.ts
  apps/web/src/views/BurnDashboard/hooks/useBurnStats.ts
Labels: size/M

#11566 feat: token-list
  apps/solana/package.json
  apps/solana/src/components/AddressChip.tsx
  apps/solana/src/components/TokenAvatar.tsx
  apps/solana/src/components/TokenSelectDialog/TokenSelectDialog.tsx
  apps/solana/src/components/TokenSelectDialog/components/PopularTokenCell.tsx
  apps/solana/src/components/TokenSelectDialog/components/TokenList.tsx
  apps/solana/src/components/TokenSelectDialog/components/TokenListSetting.tsx
  pnpm-lock.yaml
Labels: size/L

#11567 chore: update deps
  .changeset/large-phones-nail.md
  packages/infinity-sdk/package.json
  packages/infinity-sdk/tsup.config.ts
  pnpm-lock.yaml
Labels: size/S

#11568 fix: reward calc amount incorrect PAN-5468
  apps/web/src/hooks/infinity/useFarmReward.ts
  apps/web/src/state/farmsV4/api/schema.d.ts
Labels: size/S

#11560 feat: add tvl api for support infinity routing
  apps/web/src/pages/api/infinity/pools.ts
Labels: size/L

#11572 feat(PAN-5269): pair-chart
  apps/solana/src/components/AppLayout/AppNavLayout.tsx
  apps/solana/src/features/Swap/Swap.tsx
  apps/solana/src/features/Swap/components/CandleChart.tsx
  apps/solana/src/features/Swap/components/SwapKlinePanel.tsx
  apps/solana/src/hooks/pool/useFetchPoolKLine.ts
  apps/solana/src/pages/_app.tsx
  apps/solana/src/theme/cssVariables/colors.ts
Labels: size/L

#11554 chore: TVL filtering poc
  .changeset/tame-pugs-dress.md
  apps/web/src/quoter/atom/bestAMMTradeFromQuoterWorker2Atom.ts
  apps/web/src/quoter/atom/bestAMMTradeFromQuoterWorkerAtom.ts
  apps/web/src/quoter/atom/bestQuoteAtom.ts
  apps/web/src/quoter/atom/bestRoutingSDKTradeAtom.ts
  apps/web/src/quoter/atom/poolsAtom.ts
  apps/web/src/quoter/atom/routingStrategy.ts
  apps/web/src/quoter/hook/useQuoterSync.ts
  apps/web/src/quoter/quoter.types.ts
  apps/web/src/quoter/utils/PoolHashHelper.ts
  apps/web/src/quoter/utils/createQuoteQuery.ts
  apps/web/src/quoter/utils/getVerifiedTrade.ts
  apps/web/src/quoter/utils/poolQueries.ts
  apps/web/src/views/Mev/hooks/index.ts
  packages/routing-sdk/addons/quoter/src/fetchQuotes.ts
  packages/routing-sdk/addons/quoter/src/utils/isMixedRoute.ts
  packages/routing-sdk/src/findBestTrade.ts
  packages/smart-router/evm/index.test.ts
  packages/smart-router/evm/infinity-router/queries/getInfinityBinPools.ts
  packages/smart-router/evm/infinity-router/queries/getInfinityClPools.ts
  packages/smart-router/evm/infinity-router/queries/getInfinityPools.ts
  packages/smart-router/evm/infinity-router/queries/getPoolTvl.ts
  packages/smart-router/evm/infinity-router/queries/index.ts
  packages/smart-router/evm/v3-router/constants/poolSelector.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/poolTvlSelectors.ts
  packages/smart-router/evm/v3-router/types/pool.ts
  packages/smart-router/evm/v3-router/utils/getPoolSelectorConfig.ts
  packages/smart-router/package.json
  packages/utils/cacheByLRU.ts
  pnpm-lock.yaml
Labels: size/XXL

#11577 chore: remove zkSync quicknode
  apps/web/src/config/nodes.ts
Labels: size/XS
