Repository pancakeswap/pancake-frontend, pull requests merged in 2025-05, with the labels that each got.

#11575 chore: add payerIsUser options and related test
  .changeset/nice-timers-train.md
  packages/universal-router-sdk/src/PancakeSwapUniversalRouter.ts
  packages/universal-router-sdk/src/entities/protocols/TradePlanner.ts
  packages/universal-router-sdk/src/entities/protocols/parseSwapTradeContext.ts
  packages/universal-router-sdk/src/utils/getPoolKey.ts
  packages/universal-router-sdk/test/__snapshots__/router.Infinity.clamm.test.ts.snap
  packages/universal-router-sdk/test/__snapshots__/router.Infinity.mix.test.ts.snap
  packages/universal-router-sdk/test/__snapshots__/trade.test.ts.snap
  packages/universal-router-sdk/test/router.Infinity.bin.test.ts
  packages/universal-router-sdk/test/router.Infinity.clamm.test.ts
  packages/universal-router-sdk/test/router.Infinity.mix.test.ts
  packages/universal-router-sdk/test/trade.test.ts
Labels: size/XL

#11578 fix: missed cache key
  apps/web/src/pages/api/token/[type]/[chain]/[token].ts
Labels: size/XS

#11579 fix: add isValid check
  apps/web/src/pages/api/token/[type]/[chain]/[token].ts
Labels: size/S

#11580 fix: remove lru
  apps/web/src/pages/api/token/[type]/[chain]/[token].ts
Labels: size/XS

#11581 fix: routing problem with BTZ (PAN-5551)
  apps/web/src/quoter/atom/atomWithLoadable.ts
  apps/web/src/quoter/atom/bestQuoteAtom.ts
  apps/web/src/quoter/atom/routingStrategy.ts
  packages/routing-sdk/addons/v2/src/createV2Pool.ts
Labels: size/M

#11582 fix: stable swap option
  apps/web/src/quoter/atom/bestAMMTradeFromQuoterWorker2Atom.ts
  apps/web/src/quoter/atom/bestAMMTradeFromQuoterWorkerAtom.ts
  apps/web/src/quoter/atom/bestRoutingSDKTradeAtom.ts
  apps/web/src/quoter/hook/useQuoterSync.ts
  apps/web/src/quoter/quoter.types.ts
  apps/web/src/quoter/utils/poolQueries.ts
Labels: size/S

#11584 chore: allow 1 hop routing work as result
  apps/web/src/quoter/atom/routingStrategy.ts
Labels: size/XS

#11574 chore: Remove swell tooltips
  apps/web/src/components/SwellTooltip/SwellTooltip.tsx
  apps/web/src/config/swell.ts
  apps/web/src/hooks/useHasSwellReward.ts
  apps/web/src/hooks/useNativeWrap.ts
  apps/web/src/hooks/usePermit2Requires.ts
  apps/web/src/hooks/useStablecoinPrice.ts
  apps/web/src/views/CakeStaking/hooks/useRevenueSharingProxy.ts
  apps/web/src/views/CakeStaking/hooks/useVeCakeUserInfo.ts
  apps/web/src/views/Farms/components/FarmCard/CardHeading.tsx
  apps/web/src/views/Farms/components/FarmTable/Farm.tsx
  apps/web/src/views/FixedStaking/components/FixedStakingModal.tsx
  apps/web/src/views/FixedStaking/components/HarvestModal.tsx
  apps/web/src/views/FixedStaking/components/RestakeFixedStakingModal.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/hooks/useUrlQueryGauge.ts
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/index.tsx
  apps/web/src/views/GaugesVoting/hooks/useEpochVotePower.ts
  apps/web/src/views/GaugesVoting/hooks/useVotedPower.ts
  apps/web/src/views/GaugesVoting/hooks/useWriteGaugesVoteCallback.tsx
  apps/web/src/views/Idos/hooks/ido/useIDOClaimCallback.tsx
  apps/web/src/views/Idos/hooks/ido/useIDODepositCallback.tsx
  apps/web/src/views/Idos/hooks/ido/useIDOUserStatus.ts
  apps/web/src/views/LiquidStaking/components/RequestWithdrawButton.tsx
  apps/web/src/views/LiquidStaking/hooks/useRequestWithdraw.tsx
  apps/web/src/views/Mev/AddMevRpcButton.tsx
  apps/web/src/views/Mev/Hero.tsx
  apps/web/src/views/Mev/hooks/index.ts
  apps/web/src/views/PositionManagers/components/DuoTokenVaultCard.tsx
  apps/web/src/views/PositionManagers/components/TableView/index.tsx
  apps/web/src/views/PositionManagers/hooks/useWrapperBooster.ts
  apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalState.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useWallchain.ts
  apps/web/src/views/SwapSimplify/hooks/useHasDynamicHook.ts
  packages/localization/src/config/translations.json
Labels: size/L

#11588 fix: jupiter build fail
  packages/jupiter-terminal/scripts/build.sh
Labels: size/XS

#11587 fix: update cache validation logic
  packages/utils/__tests__/lru.test.ts
  packages/utils/cacheByLRU.ts
Labels: size/L

#11589 feat: settings modal
  apps/solana/src/components/AppLayout/AppNavLayout.tsx
  apps/solana/src/components/AppLayout/components/ColorThemeSettingField.tsx
  apps/solana/src/components/AppLayout/components/DefaultExplorerSettingField.tsx
  apps/solana/src/components/AppLayout/components/LanguageSettingField.tsx
  apps/solana/src/components/AppLayout/components/RPCConnectionSettingField.tsx
  apps/solana/src/components/AppLayout/components/SettingField.tsx
  apps/solana/src/components/AppLayout/components/SlippageToleranceSettingField.tsx
  apps/solana/src/components/AppLayout/components/VersionedTransactionSettingField.tsx
  apps/solana/src/components/SlippageAdjuster/SlippageSettingModal.tsx
  apps/solana/src/components/SlippageAdjuster/index.tsx
  apps/solana/src/features/Pools/components/PoolDetailMobileDrawer.tsx
  apps/solana/src/features/Swap/Swap.tsx
  apps/solana/src/theme/cssVariables/colors.ts
  apps/solana/src/utils/config/birdeyeAPI.ts
  apps/solana/src/utils/escapeRegExp.ts
Labels: size/XL

#11593 feat: network switcher
  apps/solana/src/components/AppLayout/AppNavLayout.tsx
  apps/solana/src/components/NetworkSwitcher.tsx
  apps/solana/src/utils/config/chains.ts
  apps/solana/src/utils/config/endpoint.ts
Labels: size/M

#11594 feat: connect-button
  apps/solana/src/components/SolWallet/SelectWalletModal.tsx
  apps/solana/src/components/SolWallet/index.tsx
Labels: size/L

#11595 feat: priority modal
  apps/solana/src/components/AppLayout/components/PriorityButton.tsx
  apps/solana/src/components/AppLayout/components/PriorityModalContent.tsx
Labels: size/L

#11542 chore: [PAN-5450] update bridge packages
  packages/canonical-bridge/package.json
  packages/canonical-bridge/src/configs/chains.ts
  packages/canonical-bridge/src/hooks/useTransferConfig.ts
  packages/canonical-bridge/src/token-config/mainnet/chains.ts
  packages/canonical-bridge/src/views/index.tsx
  pnpm-lock.yaml
Labels: size/XXL

#11597 feat: solana add pool mobile UI
  apps/solana/src/components/AppLayout/AppNavLayout.tsx
  apps/solana/src/components/AppLayout/components/SlippageToleranceSettingField.tsx
  apps/solana/src/components/DecimalInput.tsx
  apps/solana/src/components/Steps.tsx
  apps/solana/src/components/SubPageNote.tsx
  apps/solana/src/components/Tabs.tsx
  apps/solana/src/components/TokenAvatar.tsx
  apps/solana/src/components/TokenInput.tsx
  apps/solana/src/features/Clmm/components/PreviewDepositModal.tsx
  apps/solana/src/features/Clmm/components/TokenInputGroup.tsx
  apps/solana/src/features/Create/ClmmPool/CreateClmmPool.tsx
  apps/solana/src/features/Create/ClmmPool/components/SelectPoolTokenAndFee.tsx
  apps/solana/src/features/Create/ClmmPool/components/SetPriceAndRange.tsx
  apps/solana/src/features/Create/ClmmPool/components/TokenAmountInput.tsx
  apps/solana/src/features/Create/components/CreatePoolEntryDialog.tsx
  apps/solana/src/features/Pools/Pools.tsx
  apps/solana/src/features/Pools/components/PoolChart/Chart.tsx
  apps/solana/src/features/Pools/components/PoolChart/ChartTooltip.tsx
  apps/solana/src/features/Pools/components/PoolChart/index.tsx
  apps/solana/src/features/Pools/components/PoolDetailMobileDrawer.tsx
  apps/solana/src/provider/GlobalColorProvider.tsx
  apps/solana/src/theme/components/Badge.ts
  apps/solana/src/theme/components/Drawer.ts
  apps/solana/src/theme/cssBlocks.ts
  apps/solana/src/theme/detailConfig.ts
  apps/solana/src/utils/config/birdeyeAPI.ts
Labels: size/L

#11598 chore: remove quick-lru dep
  apps/web/src/quoter/atom/routingStrategy.ts
  packages/utils/SimpleCache.ts
  packages/utils/cacheByLRU.ts
  packages/utils/lru.ts
  packages/utils/package.json
  pnpm-lock.yaml
Labels: size/M

#11606 chore: update pkgs related to utils ( for a deps update)
  .changeset/wet-guests-tease.md
Labels: size/XS

#11599 fix: add harvest button to close position if it have reward
  apps/web/src/views/PoolDetail/components/MyPositions.tsx
  apps/web/src/views/universalFarms/components/PositionItem/PositionInfo.tsx
Labels: size/S

#11601 fix: use router push
  apps/web/src/views/universalFarms/components/AddLiquidityButton.tsx
Labels: size/XS

#11608 chore: chain query & page ux
  apps/web/src/components/SearchModal/CommonBases.tsx
  apps/web/src/components/SearchModal/SwapNetworkSelection copy.tsx
  apps/web/src/components/SearchModal/SwapNetworkSelection.tsx
  apps/web/src/hooks/useSwitchNetwork.ts
  apps/web/src/state/swap/hooks.ts
  apps/web/src/views/SwapSimplify/InfinitySwap/FlipButton.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/FormMainInfinity.tsx
Labels: size/L

#11603 fix: add error modal
  apps/web/src/hooks/infinity/useAddCLLiquidity.tsx
  apps/web/src/hooks/infinity/usePool.ts
  apps/web/src/views/AddLiquidityInfinity/components/ErrorModal.tsx
  apps/web/src/views/CreateLiquidityPool/hooks/useAddBinLiquidity.tsx
Labels: size/M

#11610 feat: wallet modal
  apps/solana/src/components/SolWallet/WalletInfo.tsx
  apps/solana/src/components/SolWallet/WalletModal.tsx
  apps/solana/src/components/SolWallet/index.tsx
  apps/solana/src/hooks/token/useSolBalance.ts
  apps/solana/src/i18n/en.json
Labels: size/L

#11612 feat: toast
  apps/solana/src/components/Toast/index.tsx
  apps/solana/src/hooks/toast/useGlobalToast.tsx
  packages/uikit/src/ResetCSS.tsx
Labels: size/L

#11615 chore: collapse component improvements
  packages/widgets-internal/swap-v2/Collapse.tsx
Labels: size/S

#11609 chore: perf track for quote
  apps/web/src/hooks/useAutoSlippage.tsx
  apps/web/src/hooks/useStablecoinPrice.ts
  apps/web/src/quoter/atom/bestAMMTradeFromQuoterWorker2Atom.ts
  apps/web/src/quoter/atom/bestAMMTradeFromQuoterWorkerAtom.ts
  apps/web/src/quoter/atom/bestQuoteAtom.ts
  apps/web/src/quoter/atom/bestRoutingSDKTradeAtom.ts
  apps/web/src/quoter/atom/poolsAtom.ts
  apps/web/src/quoter/atom/routingStrategy.ts
  apps/web/src/quoter/hook/useQuoterSync.ts
  apps/web/src/quoter/hook/useSingleTokenSwapInfo.ts
  apps/web/src/quoter/perf/quoteTracker.ts
  apps/web/src/quoter/quoter.types.ts
  apps/web/src/quoter/utils/FetchCandidatePoolsError.ts
  apps/web/src/quoter/utils/PoolHashHelper.ts
  apps/web/src/quoter/utils/createQuoteQuery.ts
  apps/web/src/views/Swap/Twap/Twap.tsx
Labels: size/L

#11611 chore: Reduce default gas price bnbchain
  apps/web/src/state/types.ts
Labels: size/XS

#11619 chore: minor clean up
  apps/web/src/quoter/atom/bestCrossChainAtom.ts
  apps/web/src/state/swap/hooks.ts
  apps/web/src/views/SwapSimplify/InfinitySwap/FlipButton.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/FormMainV4ForHomePage.tsx
  apps/web/src/views/SwapSimplify/V4Swap/CrossChainConfirmSwapModal/hooks/useRecentCrossChainOrders.ts
Labels: size/M

#11620 feat: hooks support
  .changeset/famous-owls-tease.md
  apps/web/package.json
  apps/web/src/components/Cb1/useCb1Membership.tsx
  apps/web/src/components/FeeTierBreakdown.tsx
  apps/web/src/components/PoolFeatures/PoolFeatures.tsx
  apps/web/src/hooks/infinity/useHooksList.ts
  apps/web/src/hooks/infinity/useInfinityPositions.ts
  apps/web/src/hooks/useAccountActiveChain.ts
  apps/web/src/hooks/useContract.ts
  apps/web/src/quote-worker.ts
  apps/web/src/quoter/atom/bestAMMTradeFromQuoterWorkerAtom.ts
  apps/web/src/state/farmsV4/state/extendPools/hooks.ts
  apps/web/src/views/AddLiquidityInfinity/components/InfoPanel.tsx
  apps/web/src/views/AddLiquidityInfinity/components/PoolList.tsx
  apps/web/src/views/PoolDetail/components/PoolInfo.tsx
  apps/web/src/views/PositionDetails/components/PositionTitle.tsx
  apps/web/src/views/PositionInfinity/InfinityCLPosition.tsx
  apps/web/src/views/Swap/V3Swap/components/RouteDisplayModal.tsx
  apps/web/src/views/SwapSimplify/hooks/useHookDiscount/index.ts
  apps/web/src/views/SwapSimplify/hooks/useHookDiscount/useBrevisHookDiscount.ts
  apps/web/src/views/SwapSimplify/hooks/useHookDiscount/usePrimusHookDiscount.ts
  apps/web/src/views/universalFarms/components/PositionItem/PositionInfo.tsx
  apps/web/src/views/universalFarms/components/useColumnConfig.tsx
  apps/web/src/views/universalFarms/hooks/useInfinityCollectFeeAction.ts
  packages/infinity-sdk/src/constants/hooksList/bsc.ts
  packages/infinity-sdk/src/types.ts
  packages/localization/src/config/translations.json
  packages/multicall/src/getGasLimit.ts
  packages/multicall/src/multicall.ts
  packages/smart-router/evm/constants/infinityPresets.ts
  packages/smart-router/evm/infinity-router/queries/getInfinityBinPools.ts
  packages/smart-router/evm/infinity-router/queries/getInfinityClPools.ts
  packages/smart-router/evm/v3-router/providers/multicallProvider.ts
  packages/smart-router/evm/v3-router/providers/multicallSwapProvider.ts
  packages/smart-router/evm/v3-router/providers/onChainQuoteProvider.ts
  packages/smart-router/evm/v3-router/providers/quoteProviders.ts
  packages/smart-router/evm/v3-router/schema.ts
  packages/smart-router/evm/v3-router/types/providers.ts
  packages/widgets-internal/liquidity/index.ts
  packages/widgets-internal/liquidity/infinity/HookModal.tsx
  packages/widgets-internal/liquidity/infinity/hookCategoryDesc.tsx
  pnpm-lock.yaml
Labels: size/XL

#11613 fix: swap history input output
  apps/web/src/views/Info/components/InfoTables/TransactionsTable.tsx
  apps/web/src/views/PoolDetail/components/Transactions/TransactionsTable.tsx
  apps/web/src/views/V3Info/components/TransactionsTable/index.tsx
Labels: size/XS

#11623 chore: remove whitelist
  packages/infinity-sdk/src/constants/hooksList/bsc.ts
Labels: size/M

#11454 feat: update tokenpocket detect
  apps/web/src/config/wallet.ts
  apps/web/src/global.d.ts
Labels: size/XS

#11614 fix: Redeem cake when vault is unlocked
  apps/web/src/views/CakeStaking/VeCakeRedeem.tsx
  apps/web/src/views/CakeStaking/hooks/useCakePoolLockInfo.ts
  apps/web/src/views/CakeStaking/hooks/useVeCakeUserInfo.ts
Labels: size/M

#11626 feat: Redeem v1 vault
  apps/web/src/config/constants/contracts.ts
  apps/web/src/hooks/useContract.ts
  apps/web/src/utils/addressHelpers.ts
  apps/web/src/utils/contractHelpers.ts
  apps/web/src/views/CakeStaking/VeCakeRedeem.tsx
  apps/web/src/views/CakeStaking/hooks/useCakeExitInfo.ts
  apps/web/src/views/CakeStaking/hooks/useCakePoolV1Info.ts
  apps/web/src/views/CakeStaking/hooks/useVeCakeUserInfo.ts
  packages/pools/src/abis/ICakeVaultV1.ts
  packages/pools/src/index.test.ts
  packages/pools/src/index.ts
Labels: size/L

#11629 chore: recent orders
  apps/web/src/components/App/Transactions/CrossChainTransaction.tsx
  apps/web/src/components/App/Transactions/TransactionsModal.tsx
  apps/web/src/components/App/Transactions/types.ts
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/ConfirmSwapModalV3.tsx
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/OrderStatus/OrderDetailsPanel.tsx
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/OrderStatus/OrderResultModalContent.tsx
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/api/index.ts
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/hooks/useRecentCrossChainOrders.ts
  apps/web/src/views/Swap/Bridge/api.ts
  apps/web/src/views/Swap/Bridge/hooks/useBridgeStatus.ts
  apps/web/src/views/Swap/Bridge/hooks/useRecentBridgeOrders.ts
  apps/web/src/views/Swap/Bridge/types/index.ts
  packages/localization/src/config/translations.json
  packages/widgets-internal/components/TransactionList/TransactionListItemV2.tsx
  packages/widgets-internal/components/TransactionList/index.ts
  packages/widgets-internal/swap/TransactionErrorContent.tsx
Labels: size/XL

#11625 fix: [PAN-4805] Onramp UI issue for EUR
  apps/web/src/views/BuyCrypto/hooks/useOnRampQuotes.ts
Labels: size/S

#11631 fix: increase infi cl pool form
  apps/web/src/views/IncreaseLiquidity/hooks/useIncreaseForm.ts
  apps/web/src/views/IncreaseLiquidity/index.tsx
Labels: size/M

#11600 fix: bin position status
  apps/web/src/state/farmsV4/state/accountPositions/fetcher/infinity/getAccountInfinityBinPositions.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountInfinityBinPositions.ts
  apps/web/src/views/PoolDetail/components/MyPositions.tsx
  apps/web/src/views/PositionInfinity/InfinityBinPosition.tsx
  apps/web/src/views/PositionInfinity/InfinityCLPosition.tsx
  apps/web/src/views/universalFarms/components/PositionItem/InfinityBinPositionItem.tsx
  apps/web/src/views/universalFarms/hooks/useInfinityPositions.tsx
Labels: size/M

#11634 fix: Decimal cake redeem
  apps/web/src/views/CakeStaking/hooks/useCakePoolV1Info.ts
  apps/web/src/views/CakeStaking/hooks/useVeCakeUserInfo.ts
Labels: size/XS

#11635 chore: add copy button
  apps/web/src/components/SearchModal/CurrencyList.tsx
  apps/web/src/quoter/atom/bestCrossChainAtom.ts
  apps/web/src/quoter/hook/useQuoterSync.ts
  apps/web/src/quoter/utils/createQuoteQuery.ts
Labels: size/L

#11636 chore: add quote cache for getting quote
  apps/web/src/quoter/atom/bestCrossChainAtom.ts
Labels: size/S

#11639 chore: status/recent-order modal improvements
  apps/web/src/components/App/Transactions/CrossChainTransaction.tsx
  apps/web/src/components/App/Transactions/TransactionsModal.tsx
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/OrderStatus/OrderDetailsPanel.tsx
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/OrderStatus/OrderResultModalContent.tsx
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/components/Timeline/index.tsx
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/hooks/useTimelineItems.ts
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/state/detailsPanel.ts
  packages/localization/src/config/translations.json
Labels: size/L

#11640 chore: add tracker for x order
  apps/web/.env
  apps/web/src/quoter/atom/bestXAPIAtom.ts
  apps/web/src/quoter/perf/quoteTracker.ts
Labels: size/M

#11592 fix: bump version
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/XS

#11641 chore: update bridge package
  packages/canonical-bridge/package.json
  pnpm-lock.yaml
Labels: size/XS

#11638 chore: [PAN-5381] Voting page updates
  apps/web/src/views/CakeStaking/components/MyVeCakeCard.tsx
  apps/web/src/views/Voting/CreateProposal/index.tsx
  apps/web/src/views/Voting/Proposal/Vote.tsx
  apps/web/src/views/Voting/components/CastVoteModal/MainView.tsx
  apps/web/src/views/Voting/components/CastVoteModal/index.tsx
  apps/web/src/views/Voting/components/VoteDetailsModal.tsx
  apps/web/src/views/Voting/config.ts
  apps/web/src/views/Voting/helpers.ts
  apps/web/src/views/Voting/hooks/useGetVotingPower.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#11632 chore: refactor loadable with monad design
  apps/web/src/hooks/useStablecoinPrice.ts
  apps/web/src/quoter/atom/atomWithLoadable.ts
  apps/web/src/quoter/atom/bestQuoteAtom.ts
  apps/web/src/quoter/atom/routingStrategy.ts
  apps/web/src/quoter/hook/useQuoterSync.ts
  apps/web/src/quoter/hook/useSingleTokenSwapInfo.ts
  apps/web/src/views/Swap/Twap/Twap.tsx
  packages/utils/Loadable.ts
Labels: size/L

#11643 chore: remove gauges on menu
  apps/web/src/components/Menu/config/config.ts
Labels: size/S

#11624 feat: cms-routing-list
  apps/web/.env.development
  apps/web/src/quoter/atom/bestQuoteAtom.ts
  apps/web/src/quoter/atom/routingStrategy.ts
  apps/web/src/quoter/hook/QuoteContext.tsx
Labels: size/L

#11647 chore: quote perf add channel / quote / error msg
  apps/web/src/quoter/atom/bestAMMTradeFromQuoterWorker2Atom.ts
  apps/web/src/quoter/atom/bestAMMTradeFromQuoterWorkerAtom.ts
  apps/web/src/quoter/atom/bestRoutingSDKTradeAtom.ts
  apps/web/src/quoter/atom/bestXAPIAtom.ts
  apps/web/src/quoter/perf/quoteTracker.ts
Labels: size/M

#11648 fix(liquidity): PAN-5829 only allow owner to increase liquidity
  apps/web/src/views/AddLiquidityV3/IncreaseLiquidityV3.tsx
Labels: size/S

#11630 feat: Filter out v3 positions not exist in token list
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountV3Positions.ts
Labels: size/M

#11651 chore(5042): update status, route & recent orders modals
  apps/web/src/components/App/Transactions/CrossChainTransaction.tsx
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/ConfirmSwapModalV3.tsx
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/OrderStatus/OrderDetailsPanel.tsx
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/OrderStatus/OrderResultModalContent.tsx
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/hooks/useTimelineItems.ts
  apps/web/src/views/Swap/Bridge/hooks/useBridgeStatus.ts
  apps/web/src/views/Swap/Bridge/types/index.ts
  apps/web/src/views/Swap/Bridge/utils/bridgeTitle.ts
  apps/web/src/views/Swap/V3Swap/components/RouteDisplay/BridgeRoutesDisplay.tsx
  apps/web/src/views/Swap/V3Swap/components/RouteDisplay/HookDiscountFeeDisplay.tsx
  apps/web/src/views/Swap/V3Swap/components/RouteDisplay/types.ts
  apps/web/src/views/Swap/V3Swap/components/RouteDisplayModal.tsx
  apps/web/src/views/Swap/V3Swap/components/RoutesBreakdown.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/AdvancedSwapDetails.tsx
  packages/localization/src/config/translations.json
  packages/widgets-internal/components/CurrencyLogo/DualCurrencyDisplay.tsx
Labels: size/XXL

#11652 fix: tickLimit invert
  apps/web/src/hooks/infinity/useIsTickAtLimit.ts
  apps/web/src/pages/liquidity/[tokenId].tsx
  apps/web/src/views/PositionInfinity/components/PositionPrice.tsx
Labels: size/M

#11654 fix: Cant increase liquidity when lp farming
  apps/web/src/views/AddLiquidityV3/IncreaseLiquidityV3.tsx
Labels: size/XS

#11653 feat: add low tvl pool warning
  apps/web/src/views/AddLiquidityInfinity/components/SubmitButton.tsx
  apps/web/src/views/CreateLiquidityPool/components/SubmitCreateButton.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#11656 fix: zksync multicall Storage invocations limit reached
  apps/web/src/state/farmsV4/state/accountPositions/fetcher/v3/getAccountV3Positions.ts
Labels: size/XS

#11658 feat: add default hook fee
  apps/web/src/views/IncreaseLiquidity/index.tsx
  apps/web/src/views/PositionDetails/components/PositionTitle.tsx
Labels: size/S

#11659 chore: set quote track timeout to 20s ( current revalidate time is 10s , actually for user is 10s)
  apps/web/src/quoter/atom/bestAMMTradeFromQuoterWorker2Atom.ts
  apps/web/src/quoter/atom/bestAMMTradeFromQuoterWorkerAtom.ts
  apps/web/src/quoter/atom/bestRoutingSDKTradeAtom.ts
  apps/web/src/quoter/atom/bestXAPIAtom.ts
  apps/web/src/quoter/consts.ts
  apps/web/src/quoter/hook/useQuoterSync.ts
  apps/web/src/utils/withTimeout.ts
Labels: size/M

#11657 feat: add zkj symbol alias
  apps/web/src/components/CurrencyInputPanelSimplify/index.tsx
  apps/web/src/components/SearchModal/CurrencyList.tsx
  apps/web/src/components/SearchModal/CurrencySearch.tsx
  apps/web/src/components/SearchModal/CurrencySearchModal.tsx
  apps/web/src/state/info/constant.ts
  apps/web/src/utils/getTokenAlias.ts
  apps/web/src/views/AddLiquidityInfinity/components/CLPriceRangePanel.tsx
  apps/web/src/views/AddLiquidityInfinity/components/InfoPanel.tsx
  apps/web/src/views/PoolDetail/components/PoolInfo.tsx
Labels: size/M

#11649 fix: Liquidity selector default tokens when chain change and native token select
  apps/web/src/hooks/dynamicRoute/useSelectIdRoute.ts
  apps/web/src/views/AddLiquiditySelector/index.tsx
Labels: size/M

#11644 fix: Remove pm liquidity when account connects
  apps/web/src/components/Menu/UserMenu/WalletInfo.tsx
  apps/web/src/components/NetworkModal/NetworkModal.tsx
  apps/web/src/components/ZapLiquidityWidget.tsx
  apps/web/src/hooks/useAccountLocalEventListener.ts
  apps/web/src/views/AddLiquidityInfinity/components/SubmitButton.tsx
  apps/web/src/views/AddLiquidityV3/IncreaseLiquidityV3.tsx
  apps/web/src/views/AddLiquidityV3/formViews/StableFormView.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V2FormView.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
  apps/web/src/views/Farms/components/MultiChainHarvestModal.tsx
  apps/web/src/views/FixedStaking/hooks/useStakedPools.ts
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ClaimButton.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/VestingClaimButton.tsx
  apps/web/src/views/Ifos/components/IfoVesting/VestingPeriod/Claim.tsx
  apps/web/src/views/IncreaseLiquidity/index.tsx
  apps/web/src/views/LiquidStaking/components/WithdrawRequest/index.tsx
  apps/web/src/views/LiquidStaking/hooks/useReadWithdrawRequestInfo.ts
  apps/web/src/views/Migration/components/bCake/PositionManagerTable.tsx
  apps/web/src/views/Migration/components/bCake/StakedButton.tsx
  apps/web/src/views/Migration/components/bCake/UnstakeButton.tsx
  apps/web/src/views/Migration/components/bCake/V2StakedButton.tsx
  apps/web/src/views/PositionManagers/components/Header.tsx
  apps/web/src/views/PositionManagers/components/RemoveLiquidity.tsx
  apps/web/src/views/PositionManagers/components/RewardAssets.tsx
  apps/web/src/views/PositionManagers/hooks/useOnStake.tsx
  apps/web/src/views/Pottery/hooks/useClaimPottery.tsx
  apps/web/src/views/Pottery/hooks/useDepositPottery.tsx
  apps/web/src/views/Pottery/hooks/useWithdrawPottery.tsx
  apps/web/src/views/Profile/components/EditProfileModal/ApproveCakeView.tsx
  apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/index.tsx
  apps/web/src/views/Swap/hooks/useWarningImport.tsx
Labels: size/L

#11662 fix: ui
  apps/solana/src/components/AppLayout/AppNavLayout.tsx
  apps/solana/src/components/SlippageAdjuster/SlippageSettingModal.tsx
  apps/solana/src/components/SlippageAdjuster/index.tsx
  apps/solana/src/components/TokenInput.tsx
  apps/solana/src/features/Swap/Swap.tsx
  apps/solana/src/features/Swap/components/FlipButton.tsx
  apps/solana/src/theme/cssBlocks.ts
  packages/uikit/src/widgets/Menu/components/UserMenu/MenuIcon.tsx
Labels: size/M

#11664 feat: Wallet category + MEV Icon
  apps/aptos/components/ConnectWalletButton.tsx
  apps/aptos/config/wallets.ts
  apps/gamification/components/ConnectWalletButton.tsx
  apps/gamification/config/wallet.ts
  apps/web/src/components/ConnectWalletButton.tsx
  apps/web/src/components/Menu/UserMenu/index.tsx
  apps/web/src/components/WalletModalManager.tsx
  apps/web/src/config/wallet.ts
  apps/web/src/hooks/useAuth.tsx
  apps/web/src/utils/customGTMEventTracking.ts
  packages/localization/src/config/translations.json
  packages/ui-wallets/package.json
  packages/ui-wallets/src/WalletModal.css.ts
  packages/ui-wallets/src/WalletModal.tsx
  packages/ui-wallets/src/atom.ts
  packages/ui-wallets/src/components/Intro.tsx
  packages/ui-wallets/src/index.ts
  packages/ui-wallets/src/types.ts
  packages/uikit/src/widgets/Modal/Modal.tsx
  packages/uikit/src/widgets/Modal/types.ts
  pnpm-lock.yaml
Labels: size/XXL

#11663 fix: Default stableswap liqudity selector
  apps/web/src/hooks/dynamicRoute/useSelectIdRoute.ts
  apps/web/src/hooks/useSwitchNetwork.ts
  apps/web/src/views/AddLiquiditySelector/index.tsx
Labels: size/M

#11665 fix: update overlay background
  packages/ui-wallets/src/WalletModal.tsx
  packages/uikit/src/components/Overlay/Overlay.tsx
  packages/uikit/src/tokens/colors.ts
Labels: size/XS

#11666 fix: monadTestnet wallet error
  apps/gamification/components/ConnectWalletButton.tsx
  apps/web/src/components/WalletModalManager.tsx
Labels: size/S

#11667 feat: add symbol alias in import tokens & info search
  apps/web/src/components/SearchModal/ImportTokenRow.tsx
  apps/web/src/views/InfinityInfo/components/Search/index.tsx
  apps/web/src/views/Info/components/InfoSearch/index.tsx
  apps/web/src/views/V3Info/components/Search/index.tsx
  packages/widgets-internal/swap/withCurrencyLogo.tsx
Labels: size/S

#11669 fix: remove no used chart
  apps/web/src/views/SwapSimplify/index.tsx
Labels: size/M

#11670 fix: add missing tickspacing
  packages/smart-router/evm/infinity-router/queries/getInfinityPools.ts
Labels: size/XS

#11668 chore: Disable increase liquidity pm
  apps/web/src/views/PositionManagers/components/LiquidityManagement.tsx
  apps/web/src/views/PositionManagers/components/TableView/LiquidityManagement.tsx
Labels: size/XS

#11673 fix: next version
  apps/solana/next-env.d.ts
  apps/solana/next.config.mjs
  apps/solana/package.json
  pnpm-lock.yaml
Labels: size/XS

#11672 fix: Missing pool from subgraph
  .github/workflows/deploy-apis.yml
  apis/routing/src/bindings.d.ts
  apis/routing/src/queries/pools.ts
  apis/routing/src/subgraphPoolBackup.ts
  apis/routing/wrangler.toml
Labels: size/M

#11674 fix: fix cache & leak to layer-2 issue
  apps/web/src/hooks/useStablecoinPrice.ts
  apps/web/src/quoter/atom/bestAMMTradeFromQuoterWorker2Atom.ts
  apps/web/src/quoter/atom/bestAMMTradeFromQuoterWorkerAtom.ts
  apps/web/src/quoter/atom/bestQuoteAtom.ts
  apps/web/src/quoter/atom/bestRoutingSDKTradeAtom.ts
  apps/web/src/quoter/atom/poolsAtom.ts
  apps/web/src/quoter/hook/useQuoterSync.ts
  apps/web/src/quoter/hook/useSingleTokenSwapInfo.ts
  apps/web/src/quoter/quoter.types.ts
  apps/web/src/quoter/utils/PoolHashHelper.ts
  apps/web/src/quoter/utils/createQuoteQuery.ts
  apps/web/src/quoter/utils/poolQueries.ts
  apps/web/src/views/Swap/Twap/Twap.tsx
  packages/smart-router/evm/infinity-router/queries/getInfinityPools.ts
  packages/smart-router/evm/infinity-router/queries/remotePool.type.ts
  packages/smart-router/evm/infinity-router/queries/remotePoolTransform.ts
  packages/utils/Loadable.ts
  packages/utils/__tests__/lru.test.ts
  packages/utils/cacheByLRU.ts
Labels: size/XXL

#11677 chore: add perf tracker
  apps/web/src/utils/PerfTracker.ts
Labels: size/M

#11678 fix: Failed to upload when partial filled
  apis/routing/src/subgraphPoolBackup.ts
Labels: size/M

#11676 fix: prevent layout shift when modal opens
  packages/uikit/src/components/Overlay/Overlay.tsx
Labels: size/S

#11681 fix(PAN-5761): position price display
  apps/web/src/pages/liquidity/[tokenId].tsx
Labels: size/S

#11682 fix: ui-2
  apps/solana/src/components/AppLayout/AppNavLayout.tsx
  apps/solana/src/components/TokenSelectDialog/TokenSelectDialog.tsx
  apps/solana/src/components/TokenSelectDialog/components/TokenList.tsx
  apps/solana/src/components/TokenSelectDialog/components/TokenListSetting.tsx
  apps/solana/src/theme/components/Modal.ts
Labels: size/S

#11683 fix: ui-lp
  apps/solana/src/components/AmountSlider.tsx
  apps/solana/src/components/AppLayout/components/ColorThemeSettingField.tsx
  apps/solana/src/components/TokenInput.tsx
  apps/solana/src/features/Create/components/CreatePoolEntryDialog.tsx
  apps/solana/src/theme/components/Modal.ts
  packages/uikit/src/components/Overlay/Overlay.tsx
Labels: size/M

#11684 fix: home page cache update
  apps/web/src/pages/api/home/index.ts
  apps/web/src/pages/api/home/queries/queryPools.ts
  apps/web/src/pages/api/home/queries/queryPrediction.ts
  apps/web/src/pages/api/home/queries/queryTokenList.ts
  apps/web/src/pages/api/home/queries/queryTokens.ts
  apps/web/src/pages/api/home/queries/settings.ts
  apps/web/src/pages/api/home/queryCakeRelated.ts
  apps/web/src/pages/api/home/querySiteStats.ts
  apps/web/src/quoter/atom/bestQuoteAtom.ts
  apps/web/src/views/SwapSimplify/SimpleSwapForHomePage.tsx
  packages/multicall/src/multicall.ts
  packages/utils/cacheByLRU.ts
  packages/utils/promise.ts
Labels: size/L

#11688 feat(PAN-5676): create pool low liquidity warning
  apps/web/src/views/CreateLiquidityPool/components/SubmitCreateButton.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#11686 chore: Add iswrongnetwork param to account active chain hook
  apps/web/src/hooks/infinity/useAddCLLiquidity.tsx
  apps/web/src/hooks/useAccountActiveChain.ts
  apps/web/src/views/AddLiquidityV3/IncreaseLiquidityV3.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V2FormView.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
  apps/web/src/views/Farms/components/MultiChainHarvestModal.tsx
  apps/web/src/views/IncreaseLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/index.tsx
Labels: size/M

#11694 chore: update merkl config
  apps/web/src/config/constants/merklPools.json
Labels: size/M

#11693 fix: Multicall gas limit crash
  apps/web/src/quoter/hook/useMulticallGasLimit.ts
  packages/multicall/src/getGasLimit.ts
Labels: size/M

#11697 chore: Add nodies back
  apps/web/src/config/nodes.ts
Labels: size/XS

#11700 fix: percent mobile position
  apps/solana/src/components/AmountSlider.tsx
Labels: size/M

#11702 fix: ui-create-lp
  apps/solana/src/components/TokenInput.tsx
  apps/solana/src/features/Clmm/LiquidityEditModal/AddLiquidityModal.tsx
  apps/solana/src/features/Clmm/LiquidityEditModal/validateSchema.ts
  apps/solana/src/features/Clmm/components/PreviewDepositModal.tsx
  apps/solana/src/features/Clmm/components/TokenInputGroup.tsx
  apps/solana/src/features/Create/ClmmPool/components/TokenAmountInput.tsx
  apps/solana/src/features/Create/StandardPool/hooks/useMarketSchema.ts
  apps/solana/src/features/Farm/Edit/schema/useAdjustRewardSchema.ts
  apps/solana/src/features/Liquidity/Increase/Add/index.tsx
  apps/solana/src/features/Pools/components/PoolListItem.tsx
  apps/solana/src/features/Portfolio/components/SectionMyPositions/components/Clmm/ClmmPositionAccountItemDetail/PoolInfoDrawerFace.tsx
  apps/solana/src/features/Portfolio/components/SectionMyPositions/components/Clmm/ClmmPositionAccountItemDetailMobileDrawer.tsx
Labels: size/L

#11690 perf: replace with useStablecoinPriceAmount
  apps/web/src/views/CreateLiquidityPool/components/SubmitCreateButton.tsx
Labels: size/M

#11703 fix: bg
  apps/solana/src/features/Portfolio/components/SectionMyPositions/components/Clmm/ClmmPositionAccountItemDetail.tsx
  apps/solana/src/features/Portfolio/components/SectionMyPositions/components/Clmm/ClmmPositionAccountItemDetailMobileDrawer.tsx
Labels: size/XS

#11689 feat(PAN-5928): add whitelist hooks default fee
  apps/web/src/views/Swap/V3Swap/utils/exchange.ts
Labels: size/S

#11709 chore(5042): UI updates 3
  apps/web/src/components/App/Transactions/TransactionsModal.tsx
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/ConfirmSwapModalV3.tsx
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/OrderStatus/OrderResultModalContent.tsx
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/SwapModalHeaderV3.tsx
  apps/web/src/views/Swap/Bridge/hooks/useBridgeStatus.ts
  apps/web/src/views/Swap/Bridge/hooks/useRecentBridgeOrders.ts
  apps/web/src/views/Swap/Bridge/types/index.ts
  apps/web/src/views/Swap/V3Swap/components/RouteDisplay/BridgeRoutesDisplay.tsx
  packages/widgets-internal/components/CurrencyLogo/DualCurrencyDisplay.tsx
  packages/widgets-internal/swap/ApproveModalContentV3.tsx
Labels: size/L

#11710 fix: cache time
  apps/web/src/pages/api/pools/candidates.ts
Labels: size/XS

#11712 fix: Merkl api opportunity id
  apps/web/src/config/constants/merklPools.json
  apps/web/src/hooks/useMerkl.tsx
  apps/web/src/state/farmsV4/state/poolApr/fetcher.ts
  scripts/updateMerkl/index.ts
Labels: size/M

#11715 chore: add alias for currency selector
  apps/web/src/views/universalFarms/components/PoolsFilterPanel.tsx
  packages/widgets-internal/components/TokenFilter/TokenFilter.tsx
Labels: size/XS

#11719 chore: routing base from cms
  packages/smart-router/evm/constants/exchange.ts
  packages/smart-router/evm/v3-router/functions/getAdditionalBase.ts
  packages/smart-router/evm/v3-router/functions/getPairCombinations.ts
Labels: size/M

#11727 fix: PAN-6032
  apps/solana/src/components/AddressChip.tsx
  apps/solana/src/components/AppLayout/AppNavLayout.tsx
  apps/solana/src/components/TokenInput.tsx
  apps/solana/src/features/Staking/components/StakingPoolItem.tsx
  apps/solana/src/features/Swap/components/SwapInfoBoard.tsx
  apps/solana/src/features/Swap/swapMeta.tsx
  apps/solana/src/features/Swap/useSwapStore.ts
  packages/localization/src/config/translations.json
  packages/uikit/src/components/LangSelector/LangSelector.tsx
Labels: size/L

#11728 fix(PAN-6076): swap page bg
  packages/uikit/src/css/swap.css.ts
Labels: size/XS

#11733 chore: add dollar sign for wallet asset list
  apps/web/src/components/WalletModalV2/WalletModal.tsx
Labels: size/XS
