Repository pancakeswap/pancake-frontend, pull requests merged in 2025-09, with the labels that each got.

#12176 chore: fixes and improvements for pool add, detail, info pages
  apps/web/src/components/Liquidity/StepCounter.tsx
  apps/web/src/components/PoolInfoHeader/index.tsx
  apps/web/src/config/constants/supportChains.ts
  apps/web/src/pages/liquidity/create/[...selectId].tsx
  apps/web/src/pages/v2/migrate/[address].tsx
  apps/web/src/views/AddLiquidity/AddStableLiquidity/components/FormattedSlippage.tsx
  apps/web/src/views/AddLiquidityInfinity/components/FieldAddDepositAmount.tsx
  apps/web/src/views/AddLiquidityV3/formViews/StableFormView.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V2FormView.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/PoolListItem.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
  apps/web/src/views/CreateLiquidityPool/index.tsx
  apps/web/src/views/Info/Tokens/TokenPage.tsx
  apps/web/src/views/PoolDetail/components/PoolInfo.tsx
  apps/web/src/views/PoolDetail/components/PoolStatus.tsx
  apps/web/src/views/PoolDetail/components/PoolTokens.tsx
  apps/web/src/views/PoolDetail/components/ProtocolPositionsTables/PriceRangeDisplay.tsx
  apps/web/src/views/PoolDetail/components/ProtocolPositionsTables/V2OrSSPositionsTable.tsx
  apps/web/src/views/V3Info/views/PoolPage.tsx
  apps/web/src/views/V3Info/views/TokenPage.tsx
  apps/web/src/views/universalFarms/UniversalFarms.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/tokens/colors.ts
Labels: size/L

#12206 fix: show BNB token in Gas Fee Claim Gift
  apps/web/src/views/Gift/components/CreateGiftView.tsx
  apps/web/src/views/Gift/hooks/useReadGasPayment.tsx
Labels: size/XS

#12183 chore: refactor position list & support search
  apps/web/src/state/farmsV4/state/accountPositions/fetcher.ts
  apps/web/src/state/farmsV4/state/accountPositions/hooks/useAccountV3Positions.ts
  apps/web/src/state/farmsV4/state/accountPositions/type.ts
  apps/web/src/views/PoolDetail/components/ProtocolPositionsTables/InfinityBinPositionsTable.tsx
  apps/web/src/views/PoolDetail/components/ProtocolPositionsTables/InfinityCLPositionsTable.tsx
  apps/web/src/views/universalFarms/PositionPage.tsx
  apps/web/src/views/universalFarms/atom/farmsSearchAtom.ts
  apps/web/src/views/universalFarms/atom/tokensMapAtom.ts
  apps/web/src/views/universalFarms/components/Modals/InfinityPoolAprModal.tsx
  apps/web/src/views/universalFarms/components/PositionItem/InfinityCLPositionItem.tsx
  apps/web/src/views/universalFarms/components/PositionItem/PositionCard.tsx
  apps/web/src/views/universalFarms/components/PositionItem/PositionInfo.tsx
  apps/web/src/views/universalFarms/components/PositionItem/index.ts
  apps/web/src/views/universalFarms/hooks/useInfinityPositions.tsx
  apps/web/src/views/universalFarms/hooks/useStablePositions.tsx
  apps/web/src/views/universalFarms/hooks/useV2Positions.tsx
  apps/web/src/views/universalFarms/hooks/useV3Positions.tsx
  apps/web/src/views/universalFarms/utils/matchPositionSearch.ts
Labels: size/XL

#12235 chore: Remove v2 subgraph proxy
  apis/proxy-worker/src/index.ts
Labels: size/XS

#12286 fix: Pools list scroll jumps only when one network selected
  apps/web/src/state/farmsV4/state/poolApr/fetcher.ts
  apps/web/src/views/universalFarms/components/PoolAprButton/PoolPositionAprButton.tsx
  apps/web/src/views/universalFarms/components/PoolAprButtonV3/PoolPositionAprButtonV3.tsx
  apps/web/src/views/universalFarms/hooks/useInfinityPositions.tsx
  apps/web/src/views/universalFarms/hooks/useMultiChainsTokens.tsx
  apps/web/src/views/universalFarms/hooks/useStablePositions.tsx
  apps/web/src/views/universalFarms/hooks/useV2Positions.tsx
  apps/web/src/views/universalFarms/hooks/useV3Positions.tsx
  apps/web/src/views/universalFarms/utils/queryParser.ts
Labels: size/M

#12288 chore: farms search optimize
  apps/web/src/pages/api/farm/list.ts
  apps/web/src/quoter/utils/edgePoolQueries.ts
  apps/web/src/state/farmsV4/search/edgeFarmQueries.ts
  apps/web/src/state/farmsV4/search/farm.util.ts
  apps/web/src/views/universalFarms/PoolsPage.tsx
  apps/web/src/views/universalFarms/atom/farmSearch.fetch.ts
  apps/web/src/views/universalFarms/atom/farmSearch.filter.ts
  apps/web/src/views/universalFarms/atom/farmSearch.parser.ts
  apps/web/src/views/universalFarms/atom/farmsSearchAtom.ts
  apps/web/src/views/universalFarms/components/useColumnConfig.tsx
Labels: size/XL

#12283 fix: Remove translation json, workflow and translation fixes
  .github/workflows/unitTests.yml
  apps/solana/src/hooks/toast/useTxStatus.tsx
  doc/i18n.md
  packages/localization/src/Provider.tsx
  packages/localization/src/config/translation.extend.json
  packages/localization/src/config/translations.json
  packages/localization/src/hooks/useLocaleBundle.ts
  packages/localization/src/lru.ts
Labels: size/XXL

#12282 feat: Add ga events to picks and pool add liquidity
  apps/web/src/components/AdPanel/Ads/AdPicks.tsx
  apps/web/src/utils/customGTMEventTracking.ts
  apps/web/src/views/Info/Pools/PoolPage.tsx
  apps/web/src/views/V3Info/views/PoolPage.tsx
Labels: size/M

#12293 fix: add network switch guard
  apps/web/src/wallet/atoms/switchChainRequestAtom.ts
  apps/web/src/wallet/hook/useSwitchNetworkV2.ts
Labels: size/M

#12294 fix: check privy ready state before async wallet state
  apps/web/src/wallet/hook/useSyncWagmiState.ts
Labels: size/S

#12287 fix: Wallet exist popup initially on trust wallet and add wallet not working
  apps/web/src/utils/wallet.ts
Labels: size/M

#12303 fix: uniq pools
  apps/web/src/views/universalFarms/atom/farmsSearchAtom.ts
Labels: size/XS

#12312 feat: add support for sol farm list
  apps/aptos/components/Menu/footerConfig.ts
  apps/web/src/components/MiniUniversalFarms/components/PoolsTable.tsx
  apps/web/src/components/MiniUniversalFarms/hooks/useMiniPoolsData.ts
  apps/web/src/components/MiniUniversalFarms/index.tsx
  apps/web/src/hooks/infinity/useCampaigns.ts
  apps/web/src/hooks/infinity/useFarmReward.ts
  apps/web/src/hooks/infinity/useInfinityCakeAPR.ts
  apps/web/src/hooks/infinity/useIsFarming.ts
  apps/web/src/hooks/useMerkl.tsx
  apps/web/src/pages/api/home/queries/queryPools.ts
  apps/web/src/pages/api/pools/tvlref.ts
  apps/web/src/quoter/utils/edgePoolQueries.ts
  apps/web/src/quoter/utils/edgeQueries.util.ts
  apps/web/src/state/farmsV4/search/batchFarmDataFiller.ts
  apps/web/src/state/farmsV4/search/edgeFarmQueries.ts
  apps/web/src/state/farmsV4/search/farm.util.ts
  apps/web/src/state/farmsV4/search/filters.ts
  apps/web/src/state/farmsV4/state/extendPools/atom.ts
  apps/web/src/state/farmsV4/state/extendPools/fetcher.ts
  apps/web/src/state/farmsV4/state/farmPools/hooks.ts
  apps/web/src/state/farmsV4/state/poolApr/fetcher.ts
  apps/web/src/state/farmsV4/state/type.ts
  apps/web/src/state/farmsV4/state/utils.ts
  apps/web/src/utils/getPoolLink.ts
  apps/web/src/views/PoolDetail/components/ProtocolPositionsTables/SolanaV3PositionsTable.tsx
  apps/web/src/views/PoolDetail/components/ProtocolPositionsTables/V2OrSSPositionsTable.tsx
  apps/web/src/views/universalFarms/PoolsPage.tsx
  apps/web/src/views/universalFarms/PositionPage.tsx
  apps/web/src/views/universalFarms/atom/farmSearch.enrichment.ts
  apps/web/src/views/universalFarms/atom/farmSearch.filter.ts
  apps/web/src/views/universalFarms/atom/farmSearch.parser.ts
  apps/web/src/views/universalFarms/atom/farmSearch.search.ts
  apps/web/src/views/universalFarms/atom/farmsSearchAtom.ts
  apps/web/src/views/universalFarms/atom/searchQueryAtom.ts
  apps/web/src/views/universalFarms/components/PoolListView.tsx
  apps/web/src/views/universalFarms/components/useColumnConfig.tsx
  apps/web/src/views/universalFarms/hooks/useMultiChains.ts
  apps/web/src/views/universalFarms/utils/queryParser.ts
  packages/chains/src/utils.ts
  packages/farms/src/const.ts
  packages/smart-router/evm/infinity-router/queries/remotePoolTransform.ts
  packages/solana-core-sdk/src/api/type.ts
  packages/uikit/src/widgets/Menu/components/footerConfig.ts
Labels: size/XL

#12314 fix(MEV): get correct provider from privy's connector
  apps/web/src/views/Mev/hooks/index.ts
Labels: size/XS

#12300 fix: Wallet sync switch
  apps/web/src/wallet/eip6963Connector.ts
Labels: size/M

#12324 fix: by openai
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/es-ES.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/M

#12338 fix: broken bug bounty link on home page
  packages/uikit/src/widgets/Menu/components/footerConfig.ts
Labels: size/XS

#12316 fix: upgrade feature flag
  apps/web/package.json
  apps/web/src/app/.well-known/vercel/flags/route.ts
  apps/web/src/components/VercelToolbar.tsx
  apps/web/src/feature-flags/cookies.ts
  apps/web/src/feature-flags/index.ts
  apps/web/src/feature-flags/libs/async-memoize-one.ts
  apps/web/src/feature-flags/libs/reflect.ts
  apps/web/src/feature-flags/libs/request-cookies.ts
  apps/web/src/flags.ts
  apps/web/src/hooks/useExperimentalFeatureEnabled.ts
  apps/web/src/hooks/useVercelToolbar.ts
  apps/web/src/middlewares/ab-test-middleware.ts
  apps/web/src/pages/_app.tsx
  apps/web/src/pages/api/vercel/flags.ts
  apps/web/src/views/Mev/hooks/index.ts
  pnpm-lock.yaml
Labels: size/L

#12350 fix: merkl opportunities api
  .changeset/light-toys-roll.md
  apps/web/src/hooks/useMerkl.tsx
  apps/web/src/state/farmsV4/state/poolApr/fetcher.ts
  packages/farms/index.test.ts
  packages/farms/src/const.ts
  packages/farms/src/index.ts
Labels: size/S

#12354 fix: remove useless emoji
  apps/web/src/views/universalFarms/components/PoolAprButton/PoolPositionAprButton.tsx
Labels: size/S

#12356 fix: merkl-chainId
  apps/web/src/hooks/useMerkl.tsx
Labels: size/XS

#12374 chore: Add perf. stats in mutlicall return
  .changeset/slow-penguins-help.md
  packages/multicall/src/multicall.ts
Labels: size/M

#12384 fix: fix flickering
  apps/web/src/views/PCSLimitOrders/state/form/inputAtoms.ts
Labels: size/XS

#12382 fix: create dyn-infi-pool
  apps/web/src/views/CreateLiquidityPool/Infinity/CreateLiquidityInfinityForm.tsx
Labels: size/XS

#12396 fix: sol fix farming api
  apps/web/src/state/farmsV4/search/edgeFarmQueries.ts
Labels: size/XS

#12389 chore: Add town token warning and fix warning not shown when accessing directly
  apps/web/src/config/constants/swapWarningTokens.ts
  apps/web/src/config/constants/warningTokens/bscWarningTokens.ts
  apps/web/src/views/Swap/Twap/Twap.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/GenericTokenWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/index.tsx
  apps/web/src/views/Swap/hooks/useWarningImport.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/FormMainInfinity.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/FormMainV4ForHomePage.tsx
  apps/web/src/views/SwapSimplify/hooks/useIsRecipientError.ts
  apps/web/src/views/SwapSimplify/index.tsx
Labels: size/L

#12399 fix: Town token decimal
  apps/web/src/config/constants/warningTokens/bscWarningTokens.ts
Labels: size/XS

#12409 fix: home page remove testnet farm call
  apps/web/src/state/farmsV4/state/farmPools/fetcher.ts
Labels: size/S
