Repository pancakeswap/pancake-frontend, pull requests merged in 2025-01, with the labels that each got.

#11105 chore: update banner ad
  apps/web/src/components/AdPanel/Ads/AdTradingCompetition.tsx
  apps/web/src/components/AdPanel/config.tsx
Labels: size/S

#11103 fix: Merkl tag on farms
  apps/web/src/components/Merkl/MerklSection.tsx
  apps/web/src/config/constants/merklPools.json
  apps/web/src/hooks/useMerkl.tsx
  apps/web/src/pages/v2/pair/[[...currency]].tsx
  apps/web/src/state/farmsV4/state/poolApr/fetcher.ts
  apps/web/src/views/Farms/hooks/useLmPoolLiquidity.ts
  scripts/updateMerkl/index.ts
Labels: size/L

#11083 fix: No active position shown when loading lp positions
  apps/web/src/views/universalFarms/PositionPage.tsx
Labels: size/S

#11117 chore: Remove unused info hooks
  apps/web/src/state/info/hooks.ts
  apps/web/src/state/info/utils.ts
  apps/web/src/views/Info/hooks/useBlocksFromTimestamps.ts
  apps/web/src/views/V3Info/constants.ts
  apps/web/src/views/V3Info/hooks/index.ts
Labels: size/L

#11118 chore: Add quicknode on zksync
  .github/actions/install-deps/action.yml
  apps/web/.gitignore
  apps/web/src/config/nodes.ts
  package.json
  pnpm-lock.yaml
Labels: size/S

#11119 chore: update the xmas asset to new year asset
  apps/web/src/views/SwapSimplify/V4Swap/XmasEffect.tsx
Labels: size/XS

#11115 fix: Merkl url for zksync
  apps/web/src/config/constants/merklPools.json
  apps/web/src/state/info/constant.ts
  scripts/updateMerkl/index.ts
Labels: size/S

#11120 chore: update TC ad and info stripe
  apps/web/src/components/AdPanel/Ads/AdTradingCompetition.tsx
  apps/web/src/components/AdPanel/config.tsx
  apps/web/src/components/PhishingWarningBanner/index.tsx
Labels: size/M

#11121 feat: contract hooks
  apps/web/src/config/abi/ido.ts
  apps/web/src/config/constants/contracts.ts
  apps/web/src/hooks/useContract.ts
  apps/web/src/utils/addressHelpers.ts
  apps/web/src/utils/contractHelpers.ts
  apps/web/src/views/Idos/hooks/ido/usdIDOStatus.ts
  apps/web/src/views/Idos/hooks/ido/useIDOClaimCallback.tsx
  apps/web/src/views/Idos/hooks/ido/useIDOConfig.ts
  apps/web/src/views/Idos/hooks/ido/useIDOCurrencies.ts
  apps/web/src/views/Idos/hooks/ido/useIDODepositCallback.tsx
  apps/web/src/views/Idos/hooks/ido/useIDOPoolInfo.ts
  apps/web/src/views/Idos/hooks/ido/useIDOUserInfo.ts
  apps/web/src/views/Idos/hooks/ido/useIDOUserStatus.ts
Labels: size/XL

#11122 feat: 🎸 list farms aptos
  apps/aptos/config/constants/farms/1.ts
  apps/aptos/config/constants/tokens/1.ts
Labels: size/M

#11133 feat: w3w api
  apps/web/src/pages/api/w3w/sign.ts
  apps/web/src/pages/api/w3w/verify.ts
  apps/web/src/pages/ido/w3w.tsx
  apps/web/src/views/Idos/hooks/w3w/useW3WAccountSign.ts
  apps/web/src/views/Idos/hooks/w3w/useW3WAccountVerify.ts
Labels: size/L

#11041 chore: Bump up liquidity widget 1.0.6
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/L

#11116 feat: add ifo for solv
  apps/web/package.json
  apps/web/src/components/AdPanel/Ads/AdSolv.tsx
  apps/web/src/components/AdPanel/config.tsx
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/components/PhishingWarningBanner/SolvStrip.tsx
  apps/web/src/components/PhishingWarningBanner/index.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardTokens.tsx
  apps/web/src/views/Ifos/components/IfoVesting/VestingPeriod/Claim.tsx
  apps/web/src/views/Ifos/components/IfoVesting/VestingPeriod/Info.tsx
  apps/web/src/views/Ifos/components/IfoVesting/index.tsx
  apps/web/src/views/Ifos/components/VeCakeCard.tsx
  apps/web/src/views/Ifos/hooks/getVestingInfo.ts
  apps/web/src/views/Ifos/hooks/useUserIfoInfo.ts
  apps/web/src/views/Ifos/hooks/v8/fetchIfoData.ts
  apps/web/src/views/Ifos/hooks/v8/useGetWalletIfoData.ts
  apps/web/src/views/Ifos/hooks/vesting/useFetchVestingData.ts
  packages/achievements/src/campaigns.ts
  packages/ifos/src/abis/ICake.ts
  packages/ifos/src/abis/IfoV8.ts
  packages/ifos/src/constants/contracts.ts
  packages/ifos/src/constants/ifos/bsc.ts
  packages/ifos/src/queries/fetchUserIfo.ts
  packages/localization/src/config/translations.json
  packages/tokens/src/constants/bsc.ts
  packages/uikit/src/widgets/Ifo/IfoGetTokenModal.tsx
  packages/widgets-internal/ifo/ICakeInfo.tsx
Labels: size/XXL

#11142 fix: 🎸 replace ifo/token address
  apps/web/src/__tests__/views/pancakeSquad/utils.test.ts
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/index.tsx
  apps/web/src/views/Ifos/components/IfoVesting/VestingPeriod/Info.tsx
  apps/web/src/views/PancakeSquad/utils.ts
  packages/ifos/src/constants/ifos/bsc.ts
  packages/localization/src/config/translations.json
  packages/tokens/src/constants/bsc.ts
Labels: size/M

#11143 chore: update live tag in menu
  apps/web/src/components/Menu/config/config.ts
  packages/localization/src/config/translations.json
Labels: size/XS

#11148 feat: ido-v2-sc
  apps/web/src/config/abi/ido.ts
  apps/web/src/config/constants/contracts.ts
  apps/web/src/views/Idos/CurrentIfo.tsx
  apps/web/src/views/Idos/components/IdoCards/IdoCards.tsx
  apps/web/src/views/Idos/hooks/ido/usdIDOStatus.ts
  apps/web/src/views/Idos/hooks/ido/useIDOClaimCallback.tsx
  apps/web/src/views/Idos/hooks/ido/useIDOConfig.ts
  apps/web/src/views/Idos/hooks/ido/useIDOCurrencies.ts
  apps/web/src/views/Idos/hooks/ido/useIDODepositCallback.tsx
  apps/web/src/views/Idos/hooks/ido/useIDOPoolInfo.ts
  apps/web/src/views/Idos/hooks/ido/useIDOUserInfo.ts
  apps/web/src/views/Idos/hooks/ido/useIDOUserStatus.ts
  apps/web/src/views/Idos/hooks/ido/useIdoPublicData.ts
Labels: size/XL

#11145 chore: Remove ifo status and solv banner
  apps/web/src/components/AdPanel/Ads/AdIfo.tsx
  apps/web/src/components/AdPanel/Ads/AdListapie.tsx
  apps/web/src/components/AdPanel/config.tsx
  apps/web/src/components/AdPanel/useShouldRenderAdIfo.ts
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/hooks/useIfoConfig.ts
  apps/web/src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#11150 fix: 🐛 change ifo article url
  apps/web/src/components/PhishingWarningBanner/ListapieStripe.tsx
  packages/ifos/src/constants/ifos/bsc.ts
Labels: size/XS

#11152 chore: Update code owners
  .github/CODEOWNERS
Labels: size/XS

#11151 fix: Response cached by remote with query string
  apps/web/src/views/GaugesVoting/hooks/useGauges.ts
Labels: size/XS

#11154 feat: add constants
  packages/routing-sdk/addons/ton/src/constants/AgnosticBaseCurrency.ts
  packages/routing-sdk/addons/ton/src/constants/AgnosticNativeCurrency.ts
  packages/routing-sdk/addons/ton/src/constants/AgnosticToken.ts
  packages/routing-sdk/addons/ton/src/constants/Jetton.ts
  packages/routing-sdk/addons/ton/src/constants/currency.ts
  packages/routing-sdk/addons/ton/src/constants/index.ts
  packages/routing-sdk/addons/ton/src/index.test.ts
  packages/routing-sdk/addons/ton/src/index.ts
Labels: size/XS

#11155 fix: 🐛 change text
  apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
  apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#11158 feat: routing addons - ton v2
  packages/routing-sdk/addons/ton/package.json
  packages/routing-sdk/addons/ton/src/constants/gasCost.ts
  packages/routing-sdk/addons/ton/src/constants/index.ts
  packages/routing-sdk/addons/ton/src/constants/poolType.ts
  packages/routing-sdk/addons/ton/src/createTonPool.ts
  packages/routing-sdk/addons/ton/src/index.test.ts
  packages/routing-sdk/addons/ton/src/index.ts
  packages/routing-sdk/addons/ton/src/types.ts
  pnpm-lock.yaml
Labels: size/XL

#11125 feat: new ux implementation + new chains support
  apps/web/package.json
  apps/web/src/pages/swap/limit.tsx
  apps/web/src/views/Swap/Twap/Twap.tsx
  apps/web/src/views/Swap/Twap/TwapSwap.tsx
  apps/web/src/views/Swap/index.tsx
  apps/web/src/views/Swap/utils.ts
  apps/web/src/views/SwapSimplify/V4Swap/SwapSelectionTab.tsx
  locales/en-US.json
  packages/localization/src/config/translations.json
  pnpm-lock.yaml
Labels: size/XXL

#11160 fix: limit swap width
  apps/web/src/views/Swap/Twap/TwapSwap.tsx
Labels: size/XS

#11162 fix: mobile input
  apps/web/package.json
  pnpm-lock.yaml
Labels: size/L

#11159 fix: Faq config hook crash
  apps/web/src/components/AdPanel/FAQ/useFaqConfig.ts
Labels: size/XS

#11164 fix: loading card ui
  apps/web/src/pages/liquidity/[tokenId].tsx
Labels: size/S

#11163 perf: Remove ended events from strip and use css animation
  apps/web/src/components/PhishingWarningBanner/Countdown.tsx
  apps/web/src/components/PhishingWarningBanner/ListapieStripe.tsx
  apps/web/src/components/PhishingWarningBanner/TradingCompetition.tsx
  apps/web/src/components/PhishingWarningBanner/index.tsx
Labels: size/L

#11167 fix: Failed to deposit in aptos new farms
  apps/aptos/config/constants/farms/1.ts
Labels: size/M
