Repository pancakeswap/pancake-frontend, pull requests merged in 2025-03, with the labels that each got.

#11280 chore: white list TON-JET
  apps/ton/src/config/presetPools.ts
Labels: size/XS

#11243 feat: coinbase cb1 campaign
  apps/web/src/components/Cb1/Cb1Membership.tsx
  apps/web/src/components/Cb1/useCb1Membership.tsx
  apps/web/src/config/constants/index.ts
  apps/web/src/pages/_app.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#11281 fix: TON UIQA issues
  apps/ton/src/components/Misc/GrabberBar.tsx
  apps/ton/src/components/Modals/AppModal.tsx
  apps/ton/src/components/Modals/RefundModal.tsx
  apps/ton/src/components/Modals/SettingsModal/index.tsx
  apps/ton/src/components/Modals/WalletModal.tsx
  apps/ton/src/components/TonSwap/SearchModal/CurrencySearch.tsx
  apps/ton/src/components/TonSwap/SearchModal/CurrencySearchModal.tsx
Labels: size/L

#11282 fix: TON UIQA issues for tx modal
  apps/ton/src/atoms/modals/appModalAtom.ts
  apps/ton/src/atoms/modals/confirmSwapModalAtom.tsx
  apps/ton/src/components/Modals/ActionModal.tsx
  apps/ton/src/components/Modals/AppModal.tsx
  apps/ton/src/components/TonSwap/ConfirmSwapModal/index.tsx
  apps/ton/src/components/TonSwap/CurrencyInputPanelSimplify/state.ts
  apps/ton/src/ton/logic/liquidity/useAddLiquidity.ts
  apps/ton/src/ton/logic/swap/useSwap.ts
Labels: size/L

#11284 feat: remove andy banner
  apps/web/src/components/AdPanel/InfoStripes/TradingCompetition.tsx
  apps/web/src/components/AdPanel/InfoStripes/index.tsx
  apps/web/src/components/AdPanel/config.tsx
Labels: size/S

#11285 fix: TON max amount to swap exclude gas
  apps/ton/src/atoms/modals/appModalAtom.ts
  apps/ton/src/atoms/modals/confirmSwapModalAtom.tsx
  apps/ton/src/components/Modals/AppModal.tsx
  apps/ton/src/components/TonSwap/ConfirmSwapModal/index.tsx
  apps/ton/src/components/TonSwap/CurrencyInputPanelSimplify/index.tsx
  apps/ton/src/components/TonSwap/SwapCommitButton.tsx
  apps/ton/src/ton/atom/contractOfTypeAtom.ts
  apps/ton/src/ton/atom/liquidity/poolDataQueryAtom.ts
  apps/ton/src/ton/logic/swap/useSwap.ts
  apps/ton/src/views/TONSwap/SwapForm.tsx
  packages/ton-v2-sdk/src/constants/gas.ts
  packages/ton-v2-sdk/src/constants/index.ts
  packages/ton-v2-sdk/src/index.test.ts
  packages/ton-v2-sdk/src/index.ts
Labels: size/L

#11287 fix: TON flip currency
  apps/ton/src/atoms/swap/swapStateAtom.ts
  apps/ton/src/components/TonSwap/CurrencyInputPanelSimplify/index.tsx
  apps/ton/src/views/TONSwap/SwapForm.tsx
Labels: size/L

#11289 fix: fix cb1 text
  apps/web/src/components/Cb1/Cb1Membership.tsx
  packages/localization/src/config/translations.json
Labels: size/XS

#11292 fix: remove wallet modal & fix add liq ton amount
  apps/ton/src/ton/logic/liquidity/useAddLiquidity.ts
Labels: size/S

#11293 fix: TON swap & add liq modal animation
  apps/ton/public/images/animations/Submit_Lottie.json
  apps/ton/src/components/Animations/TransactionAnimation.tsx
  apps/ton/src/components/Misc/AddCircleLoading.tsx
  apps/ton/src/components/Modals/ActionModal.tsx
  apps/ton/src/ton/logic/liquidity/useRemoveLiquidity.ts
  apps/ton/src/views/TONSwap/SwapForm.tsx
Labels: size/L

#11296 fix: TON setting theme
  apps/ton/package.json
  apps/ton/src/components/Animations/TransactionAnimation.tsx
  apps/ton/src/components/Header.tsx
  apps/ton/src/components/Modals/ActionModal.tsx
  apps/ton/src/components/Modals/RefundModal.tsx
  apps/ton/src/components/Modals/SettingsModal/index.tsx
  apps/ton/src/components/TonSwap/CurrencyInputPanelSimplify/index.tsx
  apps/ton/src/components/TonSwap/SearchModal/CurrencyList.tsx
  apps/ton/src/components/TonSwap/SearchModal/CurrencySearchModal.tsx
  apps/ton/src/config/constants/formatting.ts
  apps/ton/src/pages/_document.tsx
  apps/ton/src/views/TONLiquidity/LiquidityCard/LiquidityRow.tsx
  pnpm-lock.yaml
Labels: size/L

#11297 fix: TON number format
  apps/ton/src/components/Modals/RefundModal.tsx
  apps/ton/src/components/TonSwap/CurrencyInputPanelSimplify/index.tsx
  apps/ton/src/components/TonSwap/SearchModal/CurrencyList.tsx
  apps/ton/src/config/constants/formatting.ts
  apps/ton/src/hooks/useLatestTxReceipt.ts
  apps/ton/src/ton/logic/balanceAtom.ts
  apps/ton/src/ton/logic/swap/useSwap.ts
  apps/ton/src/views/TONLiquidity/LiquidityCard/LiquidityRow.tsx
Labels: size/L

#11302 fix: multihops receive middle token
  apps/ton/src/hooks/useBlockNumber.ts
  apps/ton/src/ton/context/endpoints.ts
  apps/ton/src/ton/logic/balanceAtom.ts
  apps/ton/src/ton/logic/swap/useSwap.ts
  apps/ton/src/ton/utils/transaction.ts
  apps/ton/src/views/TONSwap/SwapForm.tsx
  packages/ton-v2-sdk/src/constants/gas.ts
Labels: size/M

#11299 chore: update contract address for monad testnet
  apps/gamification/config/constants/contracts.ts
  packages/multicall/src/constants/contracts.ts
  packages/permit2-sdk/src/constants.ts
  packages/routing-sdk/addons/quoter/src/constants/mixedRouteQuoterV1.ts
  packages/routing-sdk/addons/quoter/src/constants/v3Quoter.ts
  packages/smart-router/evm/constants/exchange.ts
  packages/smart-router/evm/constants/v3.ts
  packages/swap-sdk-evm/src/constants.ts
  packages/universal-router-sdk/src/constants.ts
  packages/universal-router-sdk/test/fixtures/constants/chains.ts
  packages/v2-sdk/src/constants.ts
  packages/v3-sdk/src/constants.ts
Labels: size/M

#11304 chore: update GTM config
  apps/ton/src/pages/_document.tsx
Labels: size/XS

#11305 fix: update balance after tx applied
  apps/ton/src/hooks/useBlockNumber.ts
  apps/ton/src/ton/logic/balanceAtom.ts
Labels: size/M

#11298 feat: Make common ads generation by config and remove trade ads
  apps/web/src/components/AdPanel/InfoStripes/InfoStripeCommon.tsx
  apps/web/src/components/AdPanel/InfoStripes/index.tsx
  apps/web/src/components/AdPanel/config.tsx
  apps/web/src/components/AdPanel/hooks/useAdsConfig.ts
Labels: size/L

#11306 fix: remove button disabled when isSwaping
  apps/ton/src/views/TONSwap/SwapForm.tsx
Labels: size/S

#11307 fix: update TON swap error modal
  apps/ton/src/ton/logic/swap/useSwap.ts
Labels: size/S

#11232 feat: Add pancake picks
  apps/web/src/components/AdPanel/AdTag.tsx
  apps/web/src/components/AdPanel/Ads/AdCommon.tsx
  apps/web/src/components/AdPanel/Ads/AdPicks.tsx
  apps/web/src/components/AdPanel/CardLayouts.tsx
  apps/web/src/components/AdPanel/CarrouselWithSlider.tsx
  apps/web/src/components/AdPanel/PickBaseCoin.tsx
  apps/web/src/components/AdPanel/config.tsx
  apps/web/src/components/AdPanel/index.ts
  apps/web/src/components/AdPanel/types.ts
  apps/web/src/pages/api/token/[type]/[chain]/[token].ts
  apps/web/src/pages/info/[chainName]/tokens/[address].tsx
  apps/web/src/pages/info/tokens/[address].tsx
  apps/web/src/pages/info/v3/[chainName]/tokens/[address].tsx
  apps/web/src/state/farmsV4/state/poolApr/fetcher.ts
  apps/web/src/state/farmsV4/state/poolApr/hooks.ts
  apps/web/src/state/info/api/schema.d.ts
  apps/web/src/state/info/dataQuery.ts
  apps/web/src/state/info/hooks.ts
  apps/web/src/state/info/queries/tokens/fetchEthPrices.ts
  apps/web/src/state/info/queries/tokens/fetchPoolsForToken.ts
  apps/web/src/state/info/queries/tokens/fetchTokenChartData.ts
  apps/web/src/state/info/queries/tokens/fetchTokenData.ts
  apps/web/src/state/info/queries/tokens/fetchTokenDatas.ts
  apps/web/src/state/info/queries/tokens/fetchTokensBulk.ts
  apps/web/src/state/info/types.ts
  apps/web/src/state/info/utils.ts
  apps/web/src/state/token/utils.ts
  apps/web/src/utils/pageUtils.ts
  apps/web/src/views/Info/Tokens/TokenPage.tsx
  apps/web/src/views/PoolDetail/components/PoolCurrencies.tsx
  apps/web/src/views/PoolDetail/components/PoolInfo.tsx
  apps/web/src/views/V3Info/components/BarChart/alt.tsx
  apps/web/src/views/V3Info/components/DensityChart/CurrentPriceLabel.tsx
  apps/web/src/views/V3Info/components/DensityChart/CustomToolTip.tsx
  apps/web/src/views/V3Info/components/DensityChart/index.tsx
  apps/web/src/views/V3Info/components/PoolTable/index.tsx
  apps/web/src/views/V3Info/components/TokenTable/index.tsx
  apps/web/src/views/V3Info/components/TopTokenMovers/index.tsx
  apps/web/src/views/V3Info/components/TransactionsTable/index.tsx
  apps/web/src/views/V3Info/data/pool/chartData.ts
  apps/web/src/views/V3Info/data/pool/transactions.ts
  apps/web/src/views/V3Info/data/protocol/chart.ts
  apps/web/src/views/V3Info/data/protocol/overview.ts
  apps/web/src/views/V3Info/data/protocol/transactions.ts
  apps/web/src/views/V3Info/data/token/priceData.ts
  apps/web/src/views/V3Info/data/token/tokenData.ts
  apps/web/src/views/V3Info/data/token/transactions.ts
  apps/web/src/views/V3Info/hooks/chart.ts
  apps/web/src/views/V3Info/hooks/index.ts
  apps/web/src/views/V3Info/index.tsx
  apps/web/src/views/V3Info/types.ts
  apps/web/src/views/V3Info/utils/data.ts
  apps/web/src/views/V3Info/utils/index.ts
  apps/web/src/views/V3Info/views/TokenPage.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/PoolGlobalAprButton.tsx
  apps/web/src/views/universalFarms/components/PoolListItemAction.tsx
  apps/web/src/views/universalFarms/components/PoolsBanner.tsx
  packages/localization/src/config/translations.json
  packages/utils/cacheByLRU.ts
Labels: size/XXL

#11308 fix: disabled the output currency input
  apps/ton/src/views/TONSwap/SwapForm.tsx
Labels: size/XS

#11309 chore: add tTON as swap bases
  apps/ton/src/config/constants/exchange.ts
Labels: size/XS

#11310 feat: Feat/apr tooltip text update mar 10
  apps/web/src/components/AdPanel/AdTag.tsx
  apps/web/src/components/AdPanel/Ads/AdPicks.tsx
  apps/web/src/views/universalFarms/components/PoolAprButton/AprTooltipContent.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#11312 fix: android broken
  apps/ton/src/components/Header.tsx
Labels: size/XS

#11318 fix: Route is disappear if token name is too long
  apps/ton/src/components/TonSwap/SwapDetails/SwapRoute.tsx
Labels: size/XS

#11316 feat: ido-2
  apps/web/public/images/ido/ido-banner.png
  apps/web/src/components/ConnectW3WButton.tsx
  apps/web/src/components/vConsole/index.tsx
  apps/web/src/global.d.ts
  apps/web/src/hooks/usePublicNodeWaitForTransaction.ts
  apps/web/src/pages/ido/w3w.tsx
  apps/web/src/views/Idos/CurrentIfo.tsx
  apps/web/src/views/Idos/components/Footer.tsx
  apps/web/src/views/Idos/components/Hero.tsx
  apps/web/src/views/Idos/components/IdoCards/ClaimedCard.tsx
  apps/web/src/views/Idos/components/IdoCards/IdoCards.tsx
  apps/web/src/views/Idos/components/IdoCards/IdoDepositButton.tsx
  apps/web/src/views/Idos/components/IdoCards/IdoSaleInfoCard.tsx
  apps/web/src/views/Idos/components/IdoContainer.tsx
  apps/web/src/views/Idos/components/IdoQuestions/index.tsx
  apps/web/src/views/Idos/config/index.tsx
  apps/web/src/views/Idos/hooks/ido/useCurrentIDOConfig.ts
  apps/web/src/views/Idos/hooks/ido/useIDOClaimCallback.tsx
  apps/web/src/views/Idos/hooks/ido/useIDOConfig.ts
  apps/web/src/views/Idos/hooks/ido/useIDOContract.ts
  apps/web/src/views/Idos/hooks/ido/useIDODepositCallback.tsx
  apps/web/src/views/Idos/hooks/ido/useIDODuration.tsx
  apps/web/src/views/Idos/hooks/ido/useIDOUserStatus.ts
  apps/web/src/views/Idos/hooks/w3w/useW3WAccountSign.ts
  packages/localization/src/config/translations.json
Labels: size/XL

#11320 feat: getTimePeriods rounding
  apps/web/src/views/Idos/hooks/ido/useIDODuration.tsx
  packages/utils/getTimePeriods.ts
Labels: size/S

#11322 feat: implement stable price for TON
  apps/ton/src/components/TonSwap/CurrencyInputPanelSimplify/index.tsx
  apps/ton/src/components/TonSwap/SearchModal/CurrencySearch.tsx
  apps/ton/src/components/TonSwap/SwapCommitButton.tsx
  apps/ton/src/config/constants/tokens.ts
  apps/ton/src/hooks/swap/useAllCommonPairs.ts
  apps/ton/src/hooks/swap/useSwapActionHandlers.ts
  apps/ton/src/hooks/useCurrencyUsdPrice.ts
  apps/ton/src/hooks/useStablePrice.ts
  apps/ton/src/utils/getCurrencyPrice.ts
  apps/ton/src/utils/tokens/getReserveOfToken.ts
  apps/ton/src/utils/tokens/involvesToken.ts
  apps/ton/src/views/TONSwap/SwapForm.tsx
  packages/ton-v2-sdk/src/types.ts
Labels: size/L

#11290 chore: mev userflow improvement
  apps/web/src/views/Mev/AddMevRpcButton.tsx
  apps/web/src/views/Mev/Hero.tsx
  apps/web/src/views/Mev/InfoSection.tsx
  apps/web/src/views/Mev/ManualConfigModal.tsx
  apps/web/src/views/Mev/MevSwapDetail.tsx
  apps/web/src/views/Mev/MevToggle.tsx
  apps/web/src/views/Mev/constant.ts
  apps/web/src/views/Mev/hooks/index.ts
  apps/web/src/views/Mev/hooks/useWalletProviderInfo.ts
  apps/web/src/views/Mev/types.ts
  apps/web/src/views/SwapSimplify/V4Swap/ButtonAndDetailsPanel.tsx
  apps/web/src/views/SwapSimplify/V4Swap/TradeDetails.tsx
  apps/web/src/views/SwapSimplify/V4Swap/index.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/components/Svg/Icons/ShieldCheckIcon.tsx
  packages/uikit/src/components/Svg/index.tsx
Labels: size/XL

#11328 chore: remove coinbase wallet from mev whitelist
  apps/web/src/views/Mev/constant.ts
Labels: size/XS

#11332 fix: Crash info token page
  apps/web/src/pages/info/v3/tokens/[address].tsx
  apps/web/src/utils/pageUtils.ts
  apps/web/src/views/V3Info/views/TokenPage.tsx
Labels: size/S

#11331 chore: affiliates program sunset
  apps/web/next.config.mjs
  apps/web/src/pages/_app.tsx
  apps/web/src/pages/affiliates-program/agreement.tsx
  apps/web/src/pages/affiliates-program/dashboard.tsx
  apps/web/src/pages/affiliates-program/index.tsx
  apps/web/src/pages/affiliates-program/leaderboard.tsx
  apps/web/src/pages/affiliates-program/us-agreement.tsx
  apps/web/src/pages/api/affiliates-program/affiliate-claim-fee.ts
  apps/web/src/pages/api/affiliates-program/affiliate-claim-list.ts
  apps/web/src/pages/api/affiliates-program/affiliate-exist.ts
  apps/web/src/pages/api/affiliates-program/affiliate-fee-create.ts
  apps/web/src/pages/api/affiliates-program/affiliate-fee-exist.ts
  apps/web/src/pages/api/affiliates-program/affiliate-info.ts
  apps/web/src/pages/api/affiliates-program/affiliate-login.ts
  apps/web/src/pages/api/affiliates-program/affiliate-nonce.ts
  apps/web/src/pages/api/affiliates-program/affiliate-regenerate-signature.ts
  apps/web/src/pages/api/affiliates-program/leader-board.ts
  apps/web/src/pages/api/affiliates-program/user-claim-fee.ts
  apps/web/src/pages/api/affiliates-program/user-claim-list.ts
  apps/web/src/pages/api/affiliates-program/user-exist.ts
  apps/web/src/pages/api/affiliates-program/user-info.ts
  apps/web/src/pages/api/affiliates-program/user-regenerate-signature.ts
  apps/web/src/pages/api/affiliates-program/user-register-fee.ts
  apps/web/src/utils/clearUserStates.ts
  apps/web/src/views/AffiliatesProgram/hooks/useAuthAffiliate.tsx
Labels: size/XXL

#11337 feat: sunset aptos farming
  apps/aptos/components/Farms/components/Farms.tsx
  apps/aptos/components/Farms/components/WarningTips.tsx
  apps/aptos/components/Menu/hooks/useMenuItems.ts
  packages/localization/src/config/translations.json
Labels: size/M

#11344 chore: remove okx wallet from mev whitelist
  apps/web/src/views/Mev/constant.ts
Labels: size/XS

#11347 fix: fix quoter jump
  apps/web/src/views/SwapSimplify/V4Swap/SwapCommitButtonForHomepage.tsx
Labels: size/S

#11349 fix: homepage swap url
  apps/web/src/views/SwapSimplify/V4Swap/SwapCommitButtonForHomepage.tsx
Labels: size/XS

#11241 fix: Java object gone crash
  apps/gamification/config/wallet.ts
  apps/web/src/config/wallet.ts
  apps/web/src/hooks/useDataDogRUM.ts
  apps/web/src/hooks/useSwitchNetwork.ts
  apps/web/src/hooks/useWeb3WalletView.ts
  apps/web/src/views/Farms/index.tsx
  packages/uikit/src/widgets/Modal/Modal.tsx
  packages/utils/safeGetWindow.ts
Labels: size/L, Sentry

#11351 chore: add mev url param to test Okx wallet
  apps/web/src/views/Mev/hooks/index.ts
Labels: size/S

#11354 chore: add coinbase wallet to mev param
  apps/web/src/views/Mev/hooks/index.ts
Labels: size/XS

#11356 feat: Add eos banner
  apps/web/src/components/AdPanel/Ads/AdTradingCompetition.tsx
  apps/web/src/components/AdPanel/InfoStripes/TradingCompetition.tsx
  apps/web/src/components/AdPanel/config.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#11355 fix: Crash when homepage api calls fail handle
  apps/web/src/utils/atomWithAsyncRetry.ts
  apps/web/src/views/HomeV2/StatsSummary.tsx
  apps/web/src/views/HomeV2/atom/homePageDataAtom.ts
  apps/web/src/views/HomeV2/cards/PredictionCard.tsx
  apps/web/src/views/HomeV2/cards/VoteForEmissionCard.tsx
  apps/web/src/views/HomeV2/cards/component/CardRowSectionButton.tsx
  apps/web/src/views/HomeV2/cards/component/MultipleLogos.tsx
  packages/gauges/src/tests/config.test.ts
  packages/universal-router-sdk/test/fixtures/clients.ts
Labels: size/L, Sentry

#11343 chore: position mananger page improvement
  apps/web/src/views/PositionManagers/components/Header.tsx
Labels: size/M

#11335 chore: liquidity page improvement
  apps/web/src/state/user/hooks/useUserPancakePicks.tsx
  apps/web/src/views/AddLiquidityV3/hooks/useCurrencyParams.ts
  apps/web/src/views/PoolDetail/components/BreadcrumbNav.tsx
  apps/web/src/views/PoolDetail/components/MyPositions.tsx
  apps/web/src/views/PoolDetail/components/PoolInfo.tsx
  apps/web/src/views/universalFarms/PoolsPage.tsx
  apps/web/src/views/universalFarms/PositionPage.tsx
  apps/web/src/views/universalFarms/UniversalFarms.tsx
  apps/web/src/views/universalFarms/components/AddLiquidityButton.tsx
  apps/web/src/views/universalFarms/components/PoolListView.tsx
  apps/web/src/views/universalFarms/components/PoolsBanner.tsx
  apps/web/src/views/universalFarms/components/PoolsFilterPanel.tsx
  apps/web/src/views/universalFarms/components/index.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/components/ButtonMenu/types.ts
  packages/uikit/src/components/PageHeader/PageHeader.tsx
Labels: size/XL

#11360 chore: jupiter terminal app init env
  apps/solana/.gitignore
  apps/solana/README.md
  apps/solana/next.config.mjs
  apps/solana/package.json
  apps/solana/public/favicon.ico
  apps/solana/src/pages/_app.tsx
  apps/solana/src/pages/_document.tsx
  apps/solana/src/pages/index.tsx
  apps/solana/tsconfig.json
  pnpm-lock.yaml
Labels: size/L

#11363 feat: round-3
  apps/web/public/images/ido/bedrock.png
  apps/web/public/images/ido/bubblemaps.png
  apps/web/public/images/ido/myshell.png
  apps/web/src/views/Idos/components/Icons.tsx
  apps/web/src/views/Idos/components/IdoCards/ClaimDisplay.tsx
  apps/web/src/views/Idos/components/IdoCards/ClaimedCard.tsx
  apps/web/src/views/Idos/components/IdoCards/IdoSaleInfoCard.tsx
  apps/web/src/views/Idos/components/IdoCards/Timer.tsx
  apps/web/src/views/Idos/config/index.tsx
  apps/web/src/views/Idos/hooks/ido/useIDOContract.ts
  apps/web/src/views/Idos/hooks/ido/useIDODepositCallback.tsx
  apps/web/src/views/Idos/hooks/w3w/useW3WAccountSign.ts
  packages/localization/src/config/translations.json
Labels: size/L

#11361 fix: faq banner path
  apps/web/src/components/AdPanel/AdPlayer.tsx
  apps/web/src/components/AdPanel/FAQ/config/index.ts
  apps/web/src/components/AdPanel/config.tsx
  apps/web/src/components/AdPanel/constants.ts
  apps/web/src/views/Migration/bCake.tsx
Labels: size/S

#11364 chore: add Vote Now
  apps/web/src/views/GaugesVoting/components/GaguesVotingMobileView.tsx
Labels: size/S

#11346 chore: PAN-4809 optimize Gauges, Staking, Syrup on mobile
  apps/web/src/components/CurrencyInputPanelSimplify/index.tsx
  apps/web/src/components/FoldableSection/FoldableText.tsx
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/components/PinnedFAQButton/index.tsx
  apps/web/src/state/vecake/atoms.ts
  apps/web/src/views/CakeStaking/components/DataSet/DataBox.tsx
  apps/web/src/views/CakeStaking/components/DataSet/NewStakingDataSet.tsx
  apps/web/src/views/CakeStaking/components/DataSet/TotalApy.tsx
  apps/web/src/views/CakeStaking/components/LockCake/NotLocking.tsx
  apps/web/src/views/CakeStaking/components/LockCake/index.tsx
  apps/web/src/views/CakeStaking/components/LockCakeForm.tsx
  apps/web/src/views/CakeStaking/components/LockWeeksForm.tsx
  apps/web/src/views/CakeStaking/components/MyVeCakeCard.tsx
  apps/web/src/views/CakeStaking/components/PageHead.tsx
  apps/web/src/views/CakeStaking/faqConfig.tsx
  apps/web/src/views/CakeStaking/index.tsx
  apps/web/src/views/GaugesVoting/components/CurrentEpoch.tsx
  apps/web/src/views/GaugesVoting/components/GaguesVotingMobileView.tsx
  apps/web/src/views/GaugesVoting/components/GaugesFilter/FilterFieldByType.tsx
  apps/web/src/views/GaugesVoting/components/MyVeCakeBalance.tsx
  apps/web/src/views/GaugesVoting/components/RemainingVotePower.tsx
  apps/web/src/views/GaugesVoting/components/Table/GaugesTable/List.tsx
  apps/web/src/views/GaugesVoting/components/Table/VoteTable/index.tsx
  apps/web/src/views/GaugesVoting/faqConfig.tsx
  apps/web/src/views/GaugesVoting/index.tsx
  apps/web/src/views/Ifos/components/IfoQuestions/config.tsx
  apps/web/src/views/Ifos/components/IfoQuestions/index.tsx
  apps/web/src/views/Pools/faqConfig.tsx
  apps/web/src/views/Pools/index.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/components/Button/ExpandableButton.tsx
  packages/uikit/src/components/TabMenu/TabMenu.tsx
  packages/uikit/src/widgets/Modal/Modal.tsx
  packages/uikit/src/widgets/Modal/styles.tsx
  packages/uikit/src/widgets/Modal/types.ts
  packages/widgets-internal/pool/PoolControls.tsx
  packages/widgets-internal/pool/PoolTabButtons.tsx
  packages/widgets-internal/swap-v2/CurrencyInputPanelSimplify.tsx
Labels: size/XXL

#10851 chore: Bump up nextjs 15
  apps/aptos/middleware.ts
  apps/aptos/next.config.mjs
  apps/aptos/package.json
  apps/blog/next.config.mjs
  apps/bridge/next.config.mjs
  apps/games/next.config.mjs
  apps/gamification/next.config.mjs
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/src/components/CrossChainVeCakeModal/index.tsx
  apps/web/src/middlewares/geo-block-middleware.ts
  apps/web/src/middlewares/ip-address-middleware.ts
  apps/web/src/views/CakeStaking/components/BenefitCard.tsx
  packages/widgets-internal/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: size/M

#11140 fix: Crash when number of pools invalid
  apps/web/src/state/multicall/hooks.ts
  apps/web/src/views/FixedStaking/hooks/useStakedPools.ts
Labels: size/S

#11338 fix: Switch needs reload on some wallets
  apps/web/src/hooks/useSwitchNetwork.ts
Labels: size/M

#11375 fix: Options causing state infinite
  apps/web/src/state/multicall/hooks.ts
Labels: size/XS

#11373 chore: Bump pnpm
  .changeset/small-melons-shave.md
  .github/CODEOWNERS
  .github/actions/install-deps/action.yml
  package.json
  packages/gauges/package.json
  packages/gauges/tsup.config.ts
  pnpm-lock.yaml
Labels: size/S

#11371 fix: Fix 2 homepage UI/QA issues
  apps/web/src/views/BuyCrypto/constants.ts
  apps/web/src/views/HomeV2/FavoriteDEXBanner.tsx
  apps/web/src/views/HomeV2/component/ScrollableFullScreen.tsx
  apps/web/src/views/SwapSimplify/SimpleSwapForHomePage.tsx
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/widgets/Menu/Menu.tsx
Labels: size/S

#11357 feat: home page jump adjustment
  apps/web/next.config.mjs
  apps/web/src/config/constants/meta.ts
  apps/web/src/middleware.ts
  apps/web/src/middlewares/visitor-rule-middleware.ts
  apps/web/src/pages/home.tsx
  packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
  packages/uikit/src/widgets/Menu/Menu.tsx
Labels: size/M

#11353 fix: fix monad testnet bugs
  apps/web/src/config/constants/exchange.ts
  packages/multicall/src/constants/contracts.ts
  packages/tokens/src/constants/common.ts
  packages/tokens/src/constants/monadTestnet.ts
  packages/widgets-internal/components/CurrencyLogo/utils.ts
Labels: size/S

#11372 fix: tokenicons and cache latency
  apps/web/src/pages/api/home/index.ts
  apps/web/src/pages/api/home/queries/queryTokenList.ts
  apps/web/src/pages/api/home/queries/queryTokens.ts
  packages/token-lists/react/getTokenList.ts
  packages/token-lists/react/index.test.ts
  packages/token-lists/react/index.ts
  packages/token-lists/react/useFetchListCallback.ts
Labels: size/L

#11376 chore: move Defiedge to history page
  apps/web/src/views/PositionManagers/components/AddLiquidity.tsx
  apps/web/src/views/PositionManagers/components/LiquidityManagement.tsx
  apps/web/src/views/PositionManagers/components/StakedAssets.tsx
  apps/web/src/views/PositionManagers/components/TableView/LiquidityManagement.tsx
  apps/web/src/views/PositionManagers/containers/VaultContent.tsx
  apps/web/src/views/PositionManagers/hooks/useOnStake.tsx
Labels: size/M

#11377 chore(PAN-4598): remove pnp warning
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/PNPWarning.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/index.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#11379 fix: remove pnp as a warning token
  apps/web/src/config/constants/swapWarningTokens.ts
  apps/web/src/config/constants/warningTokens/bscWarningTokens.ts
  apps/web/src/views/Swap/components/SwapWarningModal/bsc/index.tsx
Labels: size/XS

#11386 chore: [PAN-4848] Remove BETA from Prediction
  apps/web/src/components/AdPanel/FAQ/config/prediction.ts
  apps/web/src/components/Menu/config/config.ts
  packages/localization/src/config/translations.json
  scripts/translationManager.ts
Labels: size/L

#11389 chore: wording adjustments
  apps/web/src/views/Swap/V3Swap/components/SwapModalFooter.tsx
  apps/web/src/views/Swap/V3Swap/components/SwapModalFooterV2.tsx
  apps/web/src/views/Swap/components/AdvancedSwapDetails.tsx
  apps/web/src/views/SwapSimplify/V4Swap/AdvancedSwapDetails.tsx
  packages/localization/src/config/translations.json
Labels: size/S

#11390 fix: add minOut for multihops
  apps/ton/src/ton/logic/swap/useSwap.ts
  packages/ton-v2-sdk/src/utils/trade.ts
Labels: size/M

#11392 fix: minOut for first step of swap
  apps/ton/src/ton/logic/swap/useSwap.ts
Labels: size/XS

#11385 chore: remove old gtag ID
  apps/web/.env.production
  apps/web/src/pages/_document.tsx
Labels: size/XS

#11397 feat(PAN-4988): remove mpendle warn
  apps/web/src/config/constants/swapWarningTokens.ts
  apps/web/src/config/constants/warningTokens/arbitrumWarningTokens.ts
  apps/web/src/views/Swap/components/SwapWarningModal/arbitrum/index.tsx
  apps/web/src/views/Swap/components/SwapWarningModal/arbitrum/mPendleWarning.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#11406 chore: add limit decimal in swap
  packages/widgets-internal/swap/NumericalInput.tsx
Labels: size/XS

#11407 chore: enforce limit decimals rule when clicking max
  packages/widgets-internal/swap/NumericalInput.tsx
Labels: size/XS

#11403 fix: homepage token border-radius and base chain load fail
  apps/web/src/pages/api/home/index.ts
  apps/web/src/pages/api/home/queries/queryPools.ts
  apps/web/src/pages/api/home/queries/queryTokenList.ts
  apps/web/src/pages/api/home/queries/queryTokens.ts
  apps/web/src/pages/api/home/tokens.ts
  apps/web/src/views/HomeV2/cards/PerpetualsCard.tsx
  packages/utils/cacheByLRU.ts
Labels: size/L

#11405 feat: add 5th ido
  apps/web/public/images/ido/kiloex.png
  apps/web/src/hooks/useLockedEndNotification.tsx
  apps/web/src/views/Idos/components/IdoCards/IdoDepositButton.tsx
  apps/web/src/views/Idos/config/index.tsx
  apps/web/src/views/Idos/hooks/ido/useIDODepositCallback.tsx
  apps/web/src/views/Idos/hooks/w3w/useW3WAccountSign.ts
  packages/localization/src/config/translations.json
Labels: size/L

#11400 chore: Limit 6 decimals in Swap Input
  apps/web/src/components/CurrencyInputPanelSimplify/index.tsx
  packages/widgets-internal/swap-v2/NumericalInput.tsx
  packages/widgets-internal/swap-v2/WalletAssetDisplay.tsx
  packages/widgets-internal/swap/NumericalInput.tsx
  packages/widgets-internal/utils/numbers.ts
Labels: size/M

#11398 chore: Update tradingview chart integrity hash
  apps/web/src/components/TradingView.tsx
Labels: size/XS

#11413 chore: Updated balance component
  apps/web/package.json
  apps/web/src/views/Swap/Twap/Twap.tsx
  pnpm-lock.yaml
Labels: size/M

#11414 chore: [PAN-4887] Add MERL trading competition banner ads
  apps/web/src/components/AdPanel/Ads/AdTradingCompetition.tsx
  apps/web/src/components/AdPanel/config.tsx
Labels: size/S

#11416 fix: Swap crash when currency decimals and balance is 0
  apps/web/src/components/CurrencyInputPanelSimplify/index.tsx
  packages/uikit/src/hooks/useTooltip/useTooltip.tsx
  packages/utils/formatFractions.ts
  packages/widgets-internal/swap-v2/WalletAssetDisplay.tsx
Labels: size/S

#11410 chore: [PAN-5050] IDO gas optimization contract integration
  apps/web/src/config/abi/ido.ts
  apps/web/src/views/Idos/hooks/ido/useIDOPoolInfo.ts
  apps/web/src/views/Idos/hooks/ido/useIDOUserStatus.ts
  apps/web/src/views/Idos/hooks/ido/useIdoPublicData.ts
  apps/web/src/views/Idos/types.ts
Labels: size/M

#11401 fix: Info table crash
  apps/web/src/views/Info/components/InfoTables/PoolsTable.tsx
Labels: size/S, Sentry
