Repository pancakeswap/pancake-frontend, pull requests merged in 2025-08, with the labels that each got.

#12020 fix: remove auto confirm PAN-7489
  apps/solana/src/components/SolWallet/SelectWalletModal.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#12021 Feat/solana swap merge
  apps/web/src/state/token/solanaTokenBalances.ts
  apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalState.tsx
Labels: size/M

#12023 fix: PAN 7396
  apps/web/src/components/Menu/UserMenu/WalletModal.tsx
  apps/web/src/components/WalletModalV2/WalletModal.tsx
Labels: size/S

#12017 chore: support manage token
  apps/web/src/components/SearchModal/CurrencySearchModal.tsx
  apps/web/src/components/SearchModal/CurrencySearchModalV2.tsx
  apps/web/src/components/SearchModal/ImportToken.tsx
  apps/web/src/components/SearchModal/Manage.tsx
  apps/web/src/components/SearchModal/ManageTokens.tsx
  apps/web/src/components/SearchModal/SolanaImportToken.tsx
  apps/web/src/components/SearchModal/SolanaManageList.tsx
  apps/web/src/components/SearchModal/SolanaManageTokens.tsx
  apps/web/src/config/solana-list.ts
  apps/web/src/hooks/useSolanaTokenList.ts
  packages/localization/src/config/translations.json
  packages/widgets-internal/swap/TokenRowButton.tsx
Labels: size/L

#12024 feat: add points card for pools
  apps/web/src/views/PoolDetail/components/PoolInfo.tsx
  apps/web/src/views/universalFarms/components/FarmStatusDisplay/config.ts
  apps/web/src/views/universalFarms/components/FarmStatusDisplay/hooks.ts
  apps/web/src/views/universalFarms/components/FarmStatusDisplay/index.tsx
  apps/web/src/views/universalFarms/components/FarmStatusDisplay/types.ts
  apps/web/src/views/universalFarms/components/RewardInfoCard/index.tsx
  apps/web/src/views/universalFarms/components/useColumnConfig.tsx
  packages/localization/src/config/translations.json
Labels: size/M

#11977 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XXL

#12027 chore: add logs for tx errors
  apps/web/src/hooks/usePublicNodeWaitForTransaction.ts
  apps/web/src/utils/transactionErrorToUserReadableMessage.ts
Labels: size/S

#12029 fix: Input parameters not being used
  .changeset/cuddly-trains-repeat.md
  packages/multicall/src/multicall.ts
Labels: size/XS

#12030 fix balance max spend amount
  apps/web/src/utils/maxAmountSpend.test.ts
  apps/web/src/views/Swap/Bridge/CrossChainConfirmSwapModal/TransactionConfirmSwapContentV3.tsx
  apps/web/src/views/Swap/V3Swap/components/TransactionConfirmSwapContentV2.tsx
Labels: size/M

#12033 fix: PAN 7444
  apps/web/src/quoter/atom/bestSVMOrderAtom.ts
  apps/web/src/quoter/hook/useQuoterSync.ts
  apps/web/src/quoter/utils/PoolHashHelper.ts
Labels: size/L

#12034 fix: PAN 7397
  apps/web/src/views/Swap/V3Swap/components/SwapModalFooterV2.tsx
Labels: size/XS

#12035 fix: PAN 7499
  apps/web/src/hooks/useAddressBalance.ts
Labels: size/XS

#12037 feat: remove Blocto and torus PAN-7404
  apps/aptos/client.ts
  apps/gamification/config/wallet.ts
  apps/solana/src/provider/WalletProvider.tsx
  apps/web/src/config/wallet.ts
Labels: size/M

#12040 chore: show global settings in slippage button, remove history tab
  apps/web/src/views/Swap/components/SlippageButton.tsx
  apps/web/src/views/universalFarms/UniversalFarms.tsx
Labels: size/M

#12042 fix: PAN 7383
  apps/web/src/hooks/useAccountActiveChain.ts
Labels: size/XS

#12044 chore: New Crowdin updates
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XS

#12045 feat: update dyn hook repo list
  packages/infinity-sdk/src/constants/hooksList/bsc.ts
Labels: size/XS

#12047 feat: add priority fee and unwrap notice
  apps/web/src/components/Settings/PriorityFeeSettingField.tsx
  apps/web/src/components/Settings/SettingsMenu.tsx
  apps/web/src/quoter/atom/bestSVMOrderAtom.ts
  apps/web/src/views/Swap/V3Swap/components/SwapModalFooterV2.tsx
  packages/solana-router-sdk/src/getBestTrade.ts
  packages/solana-router-sdk/src/types.ts
  packages/utils/user/index.ts
  packages/utils/user/solanaPriorityFee.ts
Labels: size/L

#12053 fix: PAN 7370
  apps/web/src/quoter/utils/__test__/parseSVMTradeIntoSVMOrder.test.ts
  apps/web/src/quoter/utils/svm-utils/parseSVMTradeIntoSVMOrder.ts
Labels: size/L

#12054 fix: PAN 7370
  apps/web/src/quoter/utils/svm-utils/parseSVMTradeIntoSVMOrder.ts
Labels: size/S

#12036 feat: Candlestick Price Charts for Add Liquidity
  apps/web/src/components/AdPanel/DesktopCard.tsx
  apps/web/src/components/Liquidity/Form/FieldLiquidityShape.tsx
  apps/web/src/components/PoolInfoHeader/index.tsx
  apps/web/src/hooks/v3/usePoolTickData.ts
  apps/web/src/views/AddLiquidityInfinity/components/CLPriceRangePanel.tsx
  apps/web/src/views/AddLiquidityInfinity/components/InfinityPoolInfoHeader.tsx
  apps/web/src/views/AddLiquidityInfinity/components/useTokenToTokenRateData.ts
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/V3RangeSelector.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
  apps/web/src/views/AddLiquidityV3/index.tsx
  apps/web/src/views/AddLiquidityV3/types.ts
  packages/localization/src/config/translations.json
  packages/widgets-internal/components/PriceRangeChartWithPeriodAndLiquidity/AxisBottom.tsx
  packages/widgets-internal/components/PriceRangeChartWithPeriodAndLiquidity/AxisRight.tsx
  packages/widgets-internal/components/PriceRangeChartWithPeriodAndLiquidity/Brush.tsx
  packages/widgets-internal/components/PriceRangeChartWithPeriodAndLiquidity/CandleChart.tsx
  packages/widgets-internal/components/PriceRangeChartWithPeriodAndLiquidity/Chart.tsx
  packages/widgets-internal/components/PriceRangeChartWithPeriodAndLiquidity/GridLines.tsx
  packages/widgets-internal/components/PriceRangeChartWithPeriodAndLiquidity/PricePeriodRangeChart.tsx
  packages/widgets-internal/components/PriceRangeChartWithPeriodAndLiquidity/ToolTip.tsx
  packages/widgets-internal/components/PriceRangeChartWithPeriodAndLiquidity/Zoom.tsx
  packages/widgets-internal/components/PriceRangeChartWithPeriodAndLiquidity/svg.tsx
  packages/widgets-internal/components/PriceRangeChartWithPeriodAndLiquidity/types.ts
  packages/widgets-internal/liquidity/infinity/PriceRangeDatePicker.tsx
  packages/widgets-internal/liquidity/infinity/constants.ts
Labels: size/XXL

#12026 chore: remove v2bsc/v3op subgraphs
  .changeset/remove-bsc-v2-subgraphs.md
  apps/web/src/quoter/utils/edgePoolQueries.ts
  apps/web/src/quoter/utils/poolQueries.ts
  packages/chains/src/subgraphs.ts
  packages/smart-router/README.md
  packages/smart-router/evm/v3-router/providers/poolProviders/getCandidatePools.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/getV2CandidatePools.ts
  packages/smart-router/evm/v3-router/providers/poolProviders/hybridPoolProvider.ts
Labels: size/M

#12059 chore: refactor solana token price
  apps/web/src/components/SearchModal/CurrencySearch.tsx
  apps/web/src/hooks/solana/useSolanaTokenPrice.ts
Labels: size/L

#12057 chore: Cleanup unused dependencies
  apps/aptos/package.json
  apps/blog/package.json
  apps/bridge/package.json
  apps/games/package.json
  apps/gamification/package.json
  apps/ton/package.json
  apps/web/package.json
  examples/playground/package.json
  packages/awgmi/package.json
  packages/canonical-bridge/package.json
  packages/hooks/package.json
  packages/ifos/package.json
  packages/jupiter-terminal/package.json
  packages/localization/package.json
  packages/token-lists/package.json
  packages/ui-wallets/package.json
  packages/uikit/package.json
  packages/wagmi/package.json
  packages/widgets-internal/package.json
  pnpm-lock.yaml
Labels: size/M

#12046 fix: fix for ls stored non-exists lang
  packages/localization/src/helpers.ts
Labels: size/XS

#12065 fix: replaced the slippage‑inflated r.maxOutput with the exact r.output
  apps/solana/src/features/Liquidity/Increase/Add/index.tsx
Labels: size/XS

#12064 fix: PAN 7368
  apps/web/src/quoter/atom/bestSameChainAtom.ts
  apps/web/src/views/Swap/V3Swap/components/SwapModalFooterV2.tsx
  apps/web/src/views/Swap/V3Swap/components/TransactionConfirmSwapContentV2.tsx
  apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalState.tsx
  apps/web/src/views/Swap/components/AdvancedSwapDetails.tsx
  apps/web/src/views/Swap/utils.ts
  apps/web/src/views/SwapSimplify/InfinitySwap/AdvancedSwapDetails.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/SwapCommitButton.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/TradeDetails.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/TradingFee.tsx
  apps/web/src/views/SwapSimplify/hooks/useIsPriceImpactTooHigh.ts
  apps/web/src/views/SwapSimplify/hooks/usePriceBreakdown.ts
Labels: size/XL

#12066 feat: Add layerzero cake token relate config
  apps/web/src/pages/bridge/index.tsx
  packages/canonical-bridge/package.json
  packages/canonical-bridge/src/configs/chains.ts
  packages/canonical-bridge/src/hooks/useTransferConfig.ts
  packages/canonical-bridge/src/token-config/mainnet/chains.ts
  packages/canonical-bridge/src/token-config/mainnet/layerZero/config.json
  packages/canonical-bridge/vite.config.ts
  pnpm-lock.yaml
Labels: size/M

#12069 fix: PAN 7342
  apps/web/src/components/SearchModal/SolanaManageList.tsx
  apps/web/src/config/solana-list.ts
Labels: size/XS

#12075 fix: PAN 7563
  apps/web/src/quoter/utils/svm-utils/parseSVMTradeIntoSVMOrder.ts
  apps/web/src/views/Swap/V3Swap/components/RouteDisplay/JupPairNodes.tsx
  apps/web/src/views/Swap/V3Swap/components/RouteDisplayModal.tsx
Labels: size/M

#12076 fix: PAN 7563
  apps/web/src/views/Swap/V3Swap/components/SwapModalFooterV2.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/AdvancedSwapDetails.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/TradingFee.tsx
Labels: size/L

#12077 fix: PAN 7517
  apps/web/src/components/AccessRisk/utils/fetchTokenRisk.ts
Labels: size/XS

#12080 chore: v3 add liq new tier improvements
  apps/web/src/views/AddLiquidityV3/components/HideShowSelectorSection.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
  packages/localization/src/config/translations.json
Labels: size/L

#12084 fix: PAN 7368
  apps/web/src/views/Swap/V3Swap/components/RouteDisplayModal.tsx
Labels: size/S

#12087 fix: PAN 7368
  apps/web/src/hooks/solana/useSolanaTokenPrice.ts
  apps/web/src/views/SwapSimplify/InfinitySwap/TradingFee.tsx
  apps/web/src/views/SwapSimplify/hooks/useDirectBestSolanaTrade.ts
Labels: size/L

#12092 fix: sync switcher state
  apps/web/src/wallet/atoms/switchChainRequestAtom.ts
  apps/web/src/wallet/hook/useSwitchNetworkV2.ts
  apps/web/src/wallet/hook/useSyncWagmiState.ts
Labels: size/M

#12095 chore: optimize quoter timeout for mobile
  apps/web/src/quoter/consts.ts
  apps/web/src/quoter/hook/useQuoterSync.ts
  apps/web/src/quoter/utils/poolQueries.ts
Labels: size/M

#12096 fix: Solana token balance
  apps/web/src/state/token/solanaTokenBalances.ts
Labels: size/XS

#12099 fix: resolve duplicated quoter calls
  apps/web/src/quoter/consts.ts
  apps/web/src/quoter/hook/useQuoterSync.ts
  apps/web/src/quoter/utils/PoolHashHelper.ts
  apps/web/src/wallet/atoms/accountStateAtoms.ts
Labels: size/M

#12100 fix: quote shadow result restore
  apps/web/src/quoter/atom/bestSameChainAtom.ts
Labels: size/XS

#12074 feat: translation support TWAP
  apps/web/package.json
  apps/web/src/__tests__/translations.test.ts
  apps/web/src/views/Swap/Twap/Twap.tsx
  packages/localization/src/config/translations.json
  pnpm-lock.yaml
Labels: size/L

#12103 fix: PAN-7538
  apps/web/src/components/Menu/UserMenu/index.tsx
  apps/web/src/components/SearchModal/CurrencyList.tsx
Labels: size/M

#12106 chore(PAN-7556): add fallback for v3 pools current price when no trades
  apps/web/src/components/PoolInfoHeader/index.tsx
  apps/web/src/views/AddLiquidityV3/index.tsx
Labels: size/M

#12117 chore: network selector
  apps/web/package.json
  apps/web/src/__tests__/translations.test.ts
  apps/web/src/components/SearchModal/SwapNetworkSelection.tsx
  apps/web/src/views/Swap/Twap/Twap.tsx
  pnpm-lock.yaml
Labels: size/L

#12055 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XXL

#12135 fix: translations fallback to english
  .changeset/sixty-geese-rhyme.md
  packages/localization/src/Provider.tsx
Labels: size/S

#12139 chore: add mev toggle in create pool pages
  apps/web/src/views/CreateLiquidityPool/Infinity/CreateLiquidityInfinityForm.tsx
  apps/web/src/views/CreateLiquidityPool/V2/CreateLiquidityV2Form.tsx
  apps/web/src/views/CreateLiquidityPool/V3/CreateLiquidityV3Form.tsx
Labels: size/XS

#12142 fix: PAN 7703
  apps/web/src/state/swap/hooks.test.ts
  apps/web/src/state/swap/hooks.ts
Labels: size/S

#12129 chore: New Crowdin updates
  locales/ar-SA.json
  locales/bn-BD.json
  locales/de-DE.json
  locales/el-GR.json
  locales/en-US.json
  locales/es-ES.json
  locales/fi-FI.json
  locales/fil-PH.json
  locales/fr-FR.json
  locales/hi-IN.json
  locales/hu-HU.json
  locales/id-ID.json
  locales/it-IT.json
  locales/ja-JP.json
  locales/ko-KR.json
  locales/nl-NL.json
  locales/pl-PL.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru-RU.json
  locales/sv-SE.json
  locales/ta-IN.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/vi-VN.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: size/XXL

#12148 fix: only eth cake proposal
  apps/web/src/state/voting/helpers.ts
Labels: size/XS

#12150 chore: Use bot to trigger release
  .github/workflows/release.yml
Labels: size/XS

#12151 chore: Use token to attribute author
  .github/workflows/release.yml
Labels: size/XS

#12091 feat: SendTransactionFlow support Solana
  apps/web/src/components/Menu/UserMenu/index.tsx
  apps/web/src/components/WalletModalV2/AssetsList.tsx
  apps/web/src/components/WalletModalV2/EmptyWalletActions.tsx
  apps/web/src/components/WalletModalV2/QRCodeCopyButton.tsx
  apps/web/src/components/WalletModalV2/ReceiveModal.tsx
  apps/web/src/components/WalletModalV2/ReceiveOptionsView.tsx
  apps/web/src/components/WalletModalV2/SendAssetForm.tsx
  apps/web/src/components/WalletModalV2/SendAssets.tsx
  apps/web/src/components/WalletModalV2/SendTransactionFlow.tsx
  apps/web/src/components/WalletModalV2/SolanaPriorityFeeModal.tsx
  apps/web/src/components/WalletModalV2/WalletModal.tsx
  apps/web/src/components/WalletModalV2/WalletModalV2ViewStateProvider.tsx
  apps/web/src/components/WalletModalV2/hooks/useEnhancedTokenLogo.ts
  apps/web/src/components/WalletModalV2/hooks/useSolanaPriorityFee.ts
  apps/web/src/components/WalletModalV2/hooks/useSolanaTxError.ts
  apps/web/src/components/WalletModalV2/type.ts
  apps/web/src/components/WalletModalV2/utils/solanaSafeTransaction.ts
  apps/web/src/components/WalletModalV2/utils/solanaSendTransaction.ts
  apps/web/src/components/WalletModalV2/utils/solanaTxFeeEstimation.ts
  packages/localization/src/config/translations.json
Labels: size/XXL

#12123 fix: PAN 7474
  .lintstagedrc
  apps/web/src/components/AccessRisk/SwapRevampRiskDisplay.tsx
  apps/web/src/components/App/AppHeader.tsx
  apps/web/src/components/Menu/GlobalSettings/EVMSettingsTab.tsx
  apps/web/src/components/Menu/GlobalSettings/GasSettings.tsx
  apps/web/src/components/Menu/GlobalSettings/GlobalSettings.tsx
  apps/web/src/components/Menu/GlobalSettings/GlobalSettingsTab.tsx
  apps/web/src/components/Menu/GlobalSettings/RecentTransactionsButton.tsx
  apps/web/src/components/Menu/GlobalSettings/SettingsModal.tsx
  apps/web/src/components/Menu/GlobalSettings/SettingsModalV2/CustomizeRoutingTab.tsx
  apps/web/src/components/Menu/GlobalSettings/SettingsModalV2/ExpertModeTab.tsx
  apps/web/src/components/Menu/GlobalSettings/SettingsModalV2/SettingsTab.tsx
  apps/web/src/components/Menu/GlobalSettings/SettingsModalV2/index.tsx
  apps/web/src/components/Menu/GlobalSettings/SolanaSettingsTab.tsx
  apps/web/src/components/Menu/GlobalSettings/TransactionSettings.tsx
  apps/web/src/components/Menu/GlobalSettings/index.tsx
  apps/web/src/components/Menu/GlobalSettings/types.ts
  apps/web/src/components/Menu/index.tsx
  apps/web/src/components/Settings/SettingsMenu.tsx
  apps/web/src/components/Settings/SlippageTabs.tsx
  apps/web/src/components/Settings/index.ts
  apps/web/src/quoter/atom/bestCrossChainAtom.ts
  apps/web/src/quoter/atom/bestSameChainAtom.ts
  apps/web/src/quoter/atom/placeholderAtom.ts
  apps/web/src/quoter/hook/useQuoterSync.ts
  apps/web/src/quoter/utils/placeholderHandler.ts
  apps/web/src/state/user/smartRouter.ts
  apps/web/src/views/AddLiquidity/index.tsx
  apps/web/src/views/AddLiquidityInfinity/components/FieldAddDepositAmount.tsx
  apps/web/src/views/AddLiquidityV3/IncreaseLiquidityV3.tsx
  apps/web/src/views/AddLiquidityV3/Modal.tsx
  apps/web/src/views/AddLiquidityV3/formViews/StableFormView.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V2FormView.tsx
  apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
  apps/web/src/views/IncreaseLiquidity/index.tsx
  apps/web/src/views/PositionDetails/components/PositionTitle.tsx
  apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidity/index.tsx
  apps/web/src/views/RemoveLiquidityInfinity/components/RemoveBinPosition.tsx
  apps/web/src/views/RemoveLiquidityInfinity/components/RemoveClPosition.tsx
  apps/web/src/views/Swap/V3Swap/components/RouteDisplay/BridgeRoutesDisplay.tsx
  apps/web/src/views/Swap/V3Swap/components/RouteDisplayModal.tsx
  apps/web/src/views/Swap/components/CurrencyInputHeader.tsx
  apps/web/src/views/Swap/components/SlippageButton.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/AdvancedSwapDetails.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/ButtonAndDetailsPanel.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/PricingAndSlippage.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/RoutesBreakdown.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/SlippageRow.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/SwapCommitButton.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/SwapSelectionTab.tsx
  apps/web/src/views/SwapSimplify/InfinitySwap/index.tsx
  apps/web/src/views/universalFarms/PositionPage.tsx
  packages/localization/src/config/translations.json
  packages/uikit/src/components/LangSelector/LangSelectorV2.tsx
  packages/uikit/src/components/LangSelector/index.tsx
  packages/uikit/src/components/Text/PreTitle.tsx
  packages/utils/user/slippage.ts
  packages/widgets-internal/swap/ExpertModal.tsx
Labels: size/XXL

#12137 chore: remove hook whitelist for smart router
  .changeset/seven-spiders-wonder.md
  apps/web/src/quoter/utils/edgePoolQueries.ts
  packages/infinity-sdk/src/utils/findHookByAddress.ts
  packages/infinity-sdk/src/utils/index.ts
  packages/smart-router/evm/infinity-router/queries/remotePoolTransform.ts
Labels: size/L

#12164 chore: Allow ci checks for i18n branch
  .github/workflows/format.yml
  .github/workflows/lint.yml
  .github/workflows/unitTests.yml
  crowdin.yml
Labels: size/XS

#12170 chore: Remove persistent credentials post run
  .github/workflows/release.yml
Labels: size/XS

#12172 chore: Add pass run for unit test
  .github/workflows/unitTestPass.yml
  .github/workflows/unitTests.yml
Labels: size/S

#12005 feat: new binance w3w extension
  apps/web/package.json
  apps/web/src/config/wallet.ts
  apps/web/src/global.d.ts
  apps/web/src/views/Idos/hooks/w3w/useW3WAccountSign.ts
  pnpm-lock.yaml
Labels: size/M

#11935 fix: mobile perp jump
  apps/web/src/components/Menu/config/config.ts
Labels: size/XS

#12180 fix: ToReversed crash on some mobile browsers
  apps/web/src/pages/_app.tsx
Labels: size/S, Sentry

#12089 feat: Trade social comp banner
  apps/web/src/components/AdPanel/Ads/AdCommon.tsx
  apps/web/src/components/AdPanel/hooks/useAdsConfig.ts
  apps/web/src/components/AdPanel/types.ts
  apps/web/src/components/Logo/CurrencyLogo.tsx
  apps/web/src/components/Logo/CurrencyLogoV2.tsx
  apps/web/src/components/Menu/config/config.ts
  apps/web/src/components/MiniUniversalFarms/hooks/useMiniPoolsData.ts
  apps/web/src/components/NetworkModal/PageNetworkSupportModal.tsx
  apps/web/src/components/NetworkSwitcher.tsx
  apps/web/src/components/NetworkSwitcherModal.tsx
  apps/web/src/components/WalletModalV2/SendAssetForm.tsx
  apps/web/src/utils/tokenImages.ts
  packages/localization/src/config/translations.json
Labels: size/L

#12187 fix: add debridge api token
  apps/web/src/views/BridgeView.tsx
  packages/canonical-bridge/src/views/index.tsx
Labels: size/XS

#12194 chore: update abitier hook
  packages/infinity-sdk/src/constants/hooksList/bsc.ts
Labels: size/XS
